<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/a_Many_To_Many_BDL_tmpf_and_vsby.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 15 — Many-to-many: two targets at once, then multi-step ahead
- Flavor A (this notebook): predict SEVERAL targets at once - both Y columns placed LAST because split_sequences chops from the right; Dense(2, linear) so one LSTM's weights are shaped by both targets ('borrow strength').
- Flavor B (notebook b_): MULTI-STEP - forecast the next 3 hours (3 outputs); quality degrades further out.
- One recurrent model doing a whole forecasting job - the most general setup in the module.
- Keep to 8 minutes: the 2022 video ran 8:05.
-->

# a_Many To Many (Numeric Sequences)
------------------------------------
**Dr. Dave Wanik - University of Connecticut**

[y is two different variables, at (one) the same timestep]

Let's read in the BDL data and see if we can *predict two quantities at once*! Dewpoint (dwpf) and Mean Sea-level Pressure (mslp).

In [1]:
# import modules
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
#from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
#from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.layers import Input
#from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [2]:
# # https://drive.google.com/file/d/1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS/view?usp=sharing
# !gdown 1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS
# # read the data
# df = pd.read_csv('../data/cleanBDL.csv')

In [3]:
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/cleanBDL.csv"

# retrieve the CSV data and build a dataframe
df = pd.read_csv(url)

df.shape

(46272, 10)

In [4]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 46272 entries, 0 to 46271
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valid   46272 non-null  str
 1   tmpf    46272 non-null  float64
 2   dwpf    46272 non-null  float64
 3   relh    46272 non-null  float64
 4   drct    46272 non-null  float64
 5   sknt    46272 non-null  float64
 6   p01i    46272 non-null  float64
 7   alti    46272 non-null  float64
 8   mslp    46272 non-null  float64
 9   vsby    46272 non-null  float64
dtypes: float64(9), str(1)
memory usage: 4.4 MB

,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby
0,2015-01-01 00:00:00,17.96,6.08,59.10,190.0,5.0,0.0,30.09,1019.0,10.0
1,2015-01-01 01:00:00,19.94,8.06,59.40,190.0,5.0,0.0,30.08,1018.7,10.0
2,2015-01-01 02:00:00,23.00,6.98,49.69,210.0,9.0,0.0,30.06,1018.1,10.0
3,2015-01-01 03:00:00,21.92,5.00,47.52,230.0,11.0,0.0,30.04,1017.4,10.0
4,2015-01-01 04:00:00,23.00,3.92,43.21,250.0,13.0,0.0,30.05,1017.7,10.0

# Define X and Y
If we are going to use our split sequences script from Brownlee, then we need to make sure our Y variables are on the end!

In [5]:
# let's drop the valid column
# Y will be dwpf and relh
# X will be everything else!

del df['valid']
df.head() # check your work

    tmpf  dwpf   relh   drct  sknt  p01i   alti    mslp  vsby
0  17.96  6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0
1  19.94  8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0
2  23.00  6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0
3  21.92  5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0
4  23.00  3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0

In [6]:
Y = df[['dwpf', 'mslp']]
X = df.drop(columns=['dwpf', 'mslp'])
print(df.shape, X.shape, Y.shape)

# looks good! Let's prepare samples for modeling

(46272, 9) (46272, 7) (46272, 2)

In [7]:
# put Y all the way on the left
df = pd.concat([X, Y], axis=1, sort=False)
df.head(n=11)

     tmpf   relh   drct  sknt  p01i   alti  vsby  dwpf    mslp
0   17.96  59.10  190.0   5.0   0.0  30.09  10.0  6.08  1019.0
1   19.94  59.40  190.0   5.0   0.0  30.08  10.0  8.06  1018.7
2   23.00  49.69  210.0   9.0   0.0  30.06  10.0  6.98  1018.1
3   21.92  47.52  230.0  11.0   0.0  30.04  10.0  5.00  1017.4
4   23.00  43.21  250.0  13.0   0.0  30.05  10.0  3.92  1017.7
5   23.00  43.21  250.0  11.0   0.0  30.06  10.0  3.92  1018.1
6   23.00  41.45  240.0  13.0   0.0  30.07  10.0  3.02  1018.4
7   24.08  41.30  240.0  11.0   0.0  30.08  10.0  3.92  1018.9
8   26.06  38.03  210.0   8.0   0.0  30.08  10.0  3.92  1018.9
9   28.04  35.05  220.0  14.0   0.0  30.08  10.0  3.92  1018.8
10  30.02  33.97  210.0  10.0   0.0  30.07  10.0  5.00  1018.4

In [8]:
# some eda
df.plot.scatter(x='tmpf', y='dwpf')
df.plot.scatter(x='alti', y='mslp')

In [9]:
# to get our other code to run, we will put Y
# on the end then re-run our code (needs updating from blog)

# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
    # X and Y have been UPDATED so the last two columns drop off
		# USERS NEED TO UPDATE THIS FOR THEIR OWN PROBLEMS!!!
		seq_x, seq_y = sequences[i:end_ix, :-2], sequences[end_ix-1, 7:]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# Prepare Samples for Modeling
Everything needs to be in 3D arrays.

In [10]:
# let's turn X into lookbacks of 10 with all of our samples
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [11]:
# check your work
print(df.shape, X.shape, y.shape)

(46272, 9) (46263, 10, 7) (46263, 2)

In [12]:
# here's the first X
X[0]

array([[ 17.96,  59.1 , 190.  ,   5.  ,   0.  ,  30.09,  10.  ],
       [ 19.94,  59.4 , 190.  ,   5.  ,   0.  ,  30.08,  10.  ],
       [ 23.  ,  49.69, 210.  ,   9.  ,   0.  ,  30.06,  10.  ],
       [ 21.92,  47.52, 230.  ,  11.  ,   0.  ,  30.04,  10.  ],
       [ 23.  ,  43.21, 250.  ,  13.  ,   0.  ,  30.05,  10.  ],
       [ 23.  ,  43.21, 250.  ,  11.  ,   0.  ,  30.06,  10.  ],
       [ 23.  ,  41.45, 240.  ,  13.  ,   0.  ,  30.07,  10.  ],
       [ 24.08,  41.3 , 240.  ,  11.  ,   0.  ,  30.08,  10.  ],
       [ 26.06,  38.03, 210.  ,   8.  ,   0.  ,  30.08,  10.  ],
       [ 28.04,  35.05, 220.  ,  14.  ,   0.  ,  30.08,  10.  ]])

In [13]:
# here's the first Y
y[0]

# go scroll up and make sure this matches!
# and it does!

# you will need to customize your split script when
# prepping your data... be careful! take control of your data!

array([   3.92, 1018.8 ])

In [14]:
df.head(n=15)

     tmpf   relh   drct  sknt  p01i   alti  vsby  dwpf    mslp
0   17.96  59.10  190.0   5.0   0.0  30.09  10.0  6.08  1019.0
1   19.94  59.40  190.0   5.0   0.0  30.08  10.0  8.06  1018.7
2   23.00  49.69  210.0   9.0   0.0  30.06  10.0  6.98  1018.1
3   21.92  47.52  230.0  11.0   0.0  30.04  10.0  5.00  1017.4
4   23.00  43.21  250.0  13.0   0.0  30.05  10.0  3.92  1017.7
5   23.00  43.21  250.0  11.0   0.0  30.06  10.0  3.92  1018.1
6   23.00  41.45  240.0  13.0   0.0  30.07  10.0  3.02  1018.4
7   24.08  41.30  240.0  11.0   0.0  30.08  10.0  3.92  1018.9
8   26.06  38.03  210.0   8.0   0.0  30.08  10.0  3.92  1018.9
9   28.04  35.05  220.0  14.0   0.0  30.08  10.0  3.92  1018.8
10  30.02  33.97  210.0  10.0   0.0  30.07  10.0  5.00  1018.4
11  32.00  32.93  240.0  13.0   0.0  30.03  10.0  6.08  1017.2
12  33.08  31.53  220.0  15.0   0.0  29.99  10.0  6.08  1015.7
13  33.98  31.69  220.0  15.0   0.0  29.94  10.0  6.98  1014.2
14  33.08  31.53  220.0  12.0   0.0  29.93  10.0  6.08  1013.7

# Fit a Model
This will be similar to the last example in 'Sequence Problems_Pt1.ipynb'

In [15]:
# note how there's a 2 at the end
# usually we did this for a multi-classification problem, but not today!
# by default, it's a 'linear' activiation function
# so this is 2 node output and we're doing regression.

n_steps = X.shape[1]
n_features = X.shape[2]

model = Sequential()
model.add(LSTM(50, activation='relu',
               recurrent_dropout = 0.1,
               input_shape=(n_steps, n_features)))
model.add(Dropout(0.2))
model.add(Dense(2)) # since Y has two values, we need to predict two values
model.compile(optimizer='adam', loss='mse')

import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in
# the validation loss for 10 consecutive epochs.
es = keras.callbacks.EarlyStopping(monitor='val_loss',
                                   mode='min',
                                   patience=10, # you can play with this!
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(X,
                    y,
                    callbacks=[es],
                    epochs=800, # you can set this to a big number!
                    batch_size=10,
                    validation_split=0.2,
                    verbose=1)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/800

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:06:27 2s/step - loss: 533772.8750

  15/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 508580.3750

  28/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 491285.5312

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 452916.2500

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 382057.0000

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 331218.1875

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 297693.0000

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 268369.3125

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 245146.4219

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 225718.0156

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 210178.7500

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 195820.7500

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 184496.4531

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 174779.5938

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 165712.3438

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 157871.9688

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 151696.6562

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 149897.4219

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 145042.5625

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 140200.0469

 231/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 135817.4219

 242/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 131164.2656

 253/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 127460.5000

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 123762.7656

 273/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 120354.0156

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 117462.3203

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 114738.9297

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 111740.2109

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 109598.9375

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 107306.0312

 337/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 105061.5000

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 102659.6016

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 100404.1641

 371/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 98622.9297

 382/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 96572.8594

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 94728.7031

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 92888.2891

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 91316.6406

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 89726.5547

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 88033.0859

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 86595.7656

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 85422.3594

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 84070.1406

 484/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 82926.1250

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 81842.6328

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 80743.6719

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 79609.2969

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 78411.6406

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 77354.5312

 549/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 76415.9297

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 75701.5703

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 74802.4766

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 73894.9609

 587/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 73124.7812

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 72275.7266

 609/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 71417.9844

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 70543.2344

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 69765.8203

 640/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 69066.3438

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 68242.4141

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 67603.6719

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 66826.6719

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 66065.3672

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 65483.0352

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 64696.7734

 715/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 64057.9375

 726/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 63336.9961

 737/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 62717.0547

 749/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 62015.5469

 760/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 61457.4844

 772/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 60746.4570

 783/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 60250.3047

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 59678.9414

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 59131.2031

 817/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 58580.7930

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 58074.0078

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 57553.6719

 852/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 56996.8828

 863/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 56491.9844

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 56050.6328

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 55571.5391

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 55264.5352

 902/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 54988.0273

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 54689.2031

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 54392.8867

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 54128.3945

 930/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 53805.9336

 937/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 53551.3555

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 53263.5859

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 52887.5156

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 52571.2773

 971/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 52267.6016

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 51929.7148

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 51635.1836

 997/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 51348.4531

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 51067.4883

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 50744.8164

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 50474.9219

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 50123.4531

1044/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 49839.4883

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 49567.1094

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 49263.0000

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 48944.5391

1082/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 48658.3398

1092/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 48389.5156

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 48120.7539

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 47823.3750

1122/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 47539.5039

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 47287.7109

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 47084.7031

1150/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 46840.4922

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 46548.6992

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 46284.8125

1180/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 46028.9414

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 45736.1445

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 45426.3516

1212/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 45163.0195

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 44881.7031

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 44589.8477

1243/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 44351.0312

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 44099.2344

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 43838.9336

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 43592.6758

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 43344.2969

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 43102.6875

1309/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42852.2422

1317/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42687.5078

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42549.1719

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42341.4727

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 42107.7148

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41885.5039

1364/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41693.8320

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41499.4336

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41282.1953

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 41059.7773

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40854.1602

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40617.0820

1427/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40479.0117

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40287.1016

1450/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 40054.1797

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39848.1836

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39628.8789

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39407.6406

1496/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39210.2109

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 39016.8164

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 38863.0391

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 38679.1211

1540/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 38471.8906

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 38297.9375

1561/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 38126.0859

1571/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37958.9023

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37838.9141

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37674.7539

1599/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37527.7773

1608/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37384.3633

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37226.4258

1625/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 37099.4336

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36955.9336

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36845.0195

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36722.5664

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36601.6094

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36441.6289

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36289.8125

1689/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36171.1289

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 36051.3867

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 35940.4961

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 35795.9961

1724/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 35678.0586

1734/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 35567.2148

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 35438.2773

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 35295.8398

1764/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 35167.7109

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 35054.8789

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34931.2422

1793/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34787.0352

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34676.6953

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34565.9297

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34439.3594

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34338.6211

1837/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34248.9453

1845/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34146.7695

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 34042.2617

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33925.9453

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33816.3789

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33721.8281

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33629.2344

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33514.3945

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33407.0078

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33304.5938

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33203.9531

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33125.1211

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 33031.4141

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 32923.6406

1960/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 32841.7305

1969/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32734.7480

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32629.5410

1988/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32529.5137

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32425.6250

2006/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32327.1875

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32220.0898

2026/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32111.1621

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 32004.4219

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31918.8633

2055/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31819.6484

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31712.7031

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31639.1211

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31558.3809

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31478.9531

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31393.8438

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31337.9277

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31252.2090

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31176.7324

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31096.5449

2136/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 31036.4277

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30959.0176

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30873.8340

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30781.1367

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30728.9219

2178/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30649.4824

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 30594.1035

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30556.5098

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30488.7578

2206/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30406.2383

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30341.2012

2220/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30288.3027

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30245.9082

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30180.4375

2241/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30116.8691

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30075.7402

2253/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 30004.6094

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29950.5918

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29906.1914

2273/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29839.5586

2280/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29773.8691

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29732.4199

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29663.5879

2301/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29614.1992

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29545.5898

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29488.7070

2323/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29435.5918

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29385.5098

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29320.2578

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29257.7305

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29199.2852

2361/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29139.9180

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29067.4199

2377/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 29003.0684

2384/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 28938.8867

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 28872.0098

2402/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 28802.8770

2410/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 28738.2832

2419/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 28666.3008

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 28613.0527

2434/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28563.3477

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28503.0449

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28435.4688

2460/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28371.8320

2468/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28307.5781

2476/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28244.3613

2485/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28182.8906

2493/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28120.3379

2500/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28068.0234

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 28022.0840

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27956.7910

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27911.9043

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27842.2637

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27801.8184

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27747.6211

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27688.1719

2564/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27625.7656

2572/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27573.1133

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27513.8633

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27459.4531

2597/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27405.1426

2603/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27363.8125

2612/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27303.1074

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 27245.1152

2629/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 27191.0371

2638/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 27128.7988

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 27078.6348

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 27033.6699

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26975.0840

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26917.2285

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26865.4023

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26819.2578

2695/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26770.6934

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26714.4746

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26670.4727

2718/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26620.8066

2726/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26580.5234

2735/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26520.2480

2744/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26460.9492

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26406.5703

2760/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26360.4258

2769/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26317.4492

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26267.6074

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26213.5898

2795/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26167.8672

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26129.6621

2810/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 26118.5703

2818/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 26091.6641

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 26053.7129

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 26036.3203

2843/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 26002.4922

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25967.6855

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25934.4746

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25900.3574

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25859.2402

2886/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25813.8242

2894/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25779.1836

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25729.7090

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25688.5410

2921/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25643.6230

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25593.9980

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25553.1895

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25507.4746

2958/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25463.3359

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25414.5078

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25377.5996

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25325.5938

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 25279.9199

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25232.3691

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25182.8945

3019/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25138.7637

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25094.7480

3037/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25051.8105

3046/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 25007.7969

3055/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24973.7148

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24943.6074

3070/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24906.8672

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24865.8672

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24822.9297

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24777.5586

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24737.9512

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24693.1230

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24652.6152

3130/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24619.1328

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24582.3496

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24542.9492

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24506.8203

3164/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24464.4102

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 24428.0410

3177/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24402.4297

3185/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24366.3555

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24325.0547

3199/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24298.6699

3205/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24270.7969

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24230.0898

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24195.9883

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24151.4902

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24118.0000

3246/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24080.6367

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24040.4629

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24006.1953

3270/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23976.4609

3278/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23942.5742

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23910.8457

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23887.7480

3300/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23849.9805

3307/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23821.6094

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23792.6172

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23768.5820

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23734.9141

3339/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23693.8867

3347/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23663.8496

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23634.8730

3361/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23601.5176

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23571.7012

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23533.5781

3385/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23499.0195

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23461.4824

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23421.4180

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23385.6660

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23351.7539

3429/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23312.6836

3437/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23277.1855

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23248.8262

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23217.4609

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23186.2891

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23147.6602

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23114.1719

3488/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23080.2402

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23050.5215

3504/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23014.3027

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 22995.2559

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 22962.9238

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 22932.7891

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22908.1289

3539/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22875.5469

3545/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22852.5645

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22818.3965

3561/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22793.3066

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22756.5254

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22723.3125

3585/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22695.8574

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22665.5371

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22631.7266

3608/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22598.4434

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22566.3105

3624/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22535.4863

3632/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22505.7832

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22483.2441

3646/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22462.1953

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22439.1211

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22407.5723

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22381.6230

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22358.4102

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22325.0527

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22296.3555

3699/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22268.7441

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 28s 7ms/step - loss: 22260.2617 - val_loss: 2561.7864

Epoch 2/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:31 57ms/step - loss: 6072.9590

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 12377.5391

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 11109.1240

  28/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 10287.3135

  36/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 10122.6816

  44/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 10292.4922

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 10505.3789

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 10996.7949

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 11238.4326

  78/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 11332.6885

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 11242.7461

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 11625.4639

 103/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 12361.9355

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 12477.9258

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 12748.1367

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12744.3232

 139/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12879.1035

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12656.5234

 156/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12527.9102

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12552.0342

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12388.0527

 183/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12237.3691

 192/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12086.0898

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 12043.5977

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11959.3770

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11920.4941

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11857.3379

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11804.4473

 243/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11744.0479

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11707.1143

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11649.9668

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11614.8613

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11606.3018

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11491.0049

 296/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 11471.9648

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11483.3857

 313/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11464.3711

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11420.7754

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11367.1748

 337/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11317.3066

 346/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11311.5332

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11295.7627

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11227.7314

 370/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11163.4561

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11108.1377

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11050.6650

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11045.3828

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 11011.0977

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10946.2793

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10888.9922

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10838.5488

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10814.6543

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10816.0332

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10792.6309

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10727.5293

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10667.5010

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10614.9346

 484/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10627.8867

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10629.4629

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10554.2676

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 10510.2930

 520/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10505.0947

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10493.1895

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10497.4404

 547/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10451.1895

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10638.0068

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10781.0508

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10825.0986

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10883.8857

 592/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10939.6787

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 10959.1660

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 11052.9023

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 11113.5498

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 11168.3184

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 11187.2500

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11200.3291

 654/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11235.2363

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11241.1299

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11230.9238

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11247.4346

 688/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11219.9922

 697/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11211.3662

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11219.5312

 715/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11206.6641

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11182.6387

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11180.0830

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11192.6250

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11208.1777

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11317.3154

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11458.9082

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 11540.3418

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11563.9268

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11578.5791

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11563.1016

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11554.9873

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11531.3447

 827/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11515.7549

 836/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11505.6006

 844/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11491.8691

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11477.8984

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11455.2988

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11485.8145

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11478.8867

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11485.6523

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11468.5596

 906/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11470.6865

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11449.9150

 924/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11457.0420

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11466.5801

 932/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11463.8057

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11456.8145

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11449.6885

 950/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11437.1221

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11438.9316

 961/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11426.2227

 970/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11411.2090

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11393.7979

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11394.9248

 991/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11366.3857

 997/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11353.8633

1005/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11332.3926

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11319.1924

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11295.9062

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11298.8574

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 11285.1230

1044/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11270.3457

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11247.5000

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11240.1504

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11222.2178

1076/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11194.9922

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11195.0908

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11177.9004

1099/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11164.8477

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11154.5029

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11139.1348

1122/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11133.1260

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11111.7754

1138/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11107.2285

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11097.4551

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11078.5645

1162/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11068.1572

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11042.7510

1178/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11026.2578

1186/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 11010.8301

1196/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 10986.0566

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 10970.6113

1213/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10969.8799

1221/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10964.4766

1229/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10925.2422

1237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10901.9619

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10886.3457

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10876.0830

1258/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10865.3662

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10853.7256

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10849.2109

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10833.2236

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10814.5996

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10806.1338

1306/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10789.9053

1315/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10770.3535

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10764.2324

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10755.8955

1340/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10739.4307

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10717.3447

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10716.3770

1366/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 10717.3350

1375/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10701.5010

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10690.5654

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10681.0068

1400/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10660.7588

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10674.1406

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10661.7617

1428/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10651.2568

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10644.2168

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10627.9775

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10615.3604

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10606.7441

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10611.2695

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10609.5439

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10602.8340

1497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10597.2148

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10577.3975

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10571.5977

1519/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 10575.5527

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10568.3115

1535/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10553.5693

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10542.9209

1552/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10521.3301

1561/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10509.9023

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10499.5088

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10482.9463

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10472.1064

1597/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10477.1494

1606/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10460.8271

1615/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10446.0693

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10434.9893

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10419.7959

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10394.5254

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10396.7793

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 10392.6807

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10383.6367

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10367.7666

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10358.3018

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10345.8779

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10331.8330

1718/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10329.7285

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10312.1680

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10290.2266

1747/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10283.9160

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10271.7324

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10252.9297

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10251.5479

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10237.2656

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10216.5225

1801/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 10206.8965

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10195.0625

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10188.5742

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10172.6191

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10152.1104

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10133.0254

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10124.2217

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10111.2295

1876/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10103.3008

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10091.6230

1894/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10084.8838

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10065.2803

1912/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10066.5752

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10065.3330

1930/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10061.6953

1939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10055.5557

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 10048.4033

1957/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 10024.3281

1966/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 10012.2959

1975/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 10002.5537

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9992.3066

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9982.2842

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9978.5967

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9966.6914

2022/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9947.6104

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9934.8213

2041/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9921.3594

2050/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9911.6943

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9897.2578

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9889.7861

2072/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9892.1631

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9878.6172

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9868.5322

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 9870.4727

2106/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9857.0850

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9842.2275

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9835.2832

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9827.8457

2140/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9819.8193

2149/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9807.9424

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9797.0859

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9786.5537

2175/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9774.4834

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9767.8955

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9748.5732

2204/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9751.6748

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9742.6338

2222/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9735.2959

2230/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9724.4932

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9718.4404

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9705.2393

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 9698.2646

2265/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9683.7021

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9677.1357

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9677.6094

2291/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9667.7354

2300/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9655.3486

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9643.6943

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9630.8525

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9621.8691

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9612.4619

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9595.1123

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9591.3857

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9589.5566

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9589.2861

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9582.2002

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9579.6797

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9570.4131

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 9567.7100

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9558.9492

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9543.4336

2434/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9533.3174

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9523.4629

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9516.4932

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9511.8994

2472/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9502.5488

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9508.6787

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9507.9297

2500/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9511.7627

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9502.3008

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9502.0879

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9499.9336

2536/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9491.0107

2545/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9487.1680

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9476.5664

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9472.8984

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 9472.6230

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9469.5273

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9465.0693

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9458.4199

2601/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9447.5801

2609/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9440.7891

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9430.8398

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9433.2656

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9432.1826

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9430.2002

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9422.8311

2660/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9416.3379

2668/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9408.9756

2677/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9401.4570

2686/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9391.2891

2694/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9390.0576

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9385.1816

2712/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9381.5137

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9378.1836

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 9372.8418

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9365.7275

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9358.5420

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9348.0703

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9337.0312

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9326.6592

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9320.3936

2793/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9312.5049

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9302.4346

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9294.8340

2819/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9287.6885

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9284.7871

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9282.6807

2842/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9274.9316

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9274.2031

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9271.3467

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9266.3232

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9265.0225

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9254.9268

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9246.5439

2896/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 9247.1982

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9239.4355

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9233.3262

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9231.1826

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9227.9707

2941/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9222.5361

2950/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9209.0957

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9199.7041

2968/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9193.6299

2977/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9185.8340

2986/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9177.1133

2995/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9169.2334

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9159.6758

3013/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9152.9863

3022/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9145.6572

3031/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9141.1006

3041/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9138.3457

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 9134.9268

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9131.4902

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9123.7197

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9119.2666

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9120.1104

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9114.8301

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9107.0322

3104/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9099.7627

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9093.8350

3118/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9085.6650

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9083.5820

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9078.1611

3143/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9071.7412

3150/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9063.3896

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9060.9404

3165/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9053.7539

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9053.2764

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9052.6084

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9044.8281

3199/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9042.4229

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9036.2881

3215/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9033.2383

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9025.8721

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9022.4473

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9016.0547

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9011.8594

3258/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9003.9004

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8997.4600

3275/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8989.1279

3284/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8987.9658

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8988.1484

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8982.3672

3309/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8979.5234

3318/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8974.1504

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8968.2725

3333/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8964.6768

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8960.9189

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8958.2471

3360/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8957.7021

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8952.1943

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8949.7920

3385/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8942.9238

3395/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8936.6816

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8935.6592

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8928.4941

3421/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8921.4424

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8917.3447

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8909.8594

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8909.2900

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8907.0186

3459/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8902.4141

3468/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8902.9619

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8897.6670

3485/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8892.6914

3494/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8892.5361

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8890.2490

3512/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8887.5908

3521/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8888.4346

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8881.6787

3539/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8874.0449

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8873.1562

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8866.9355

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8855.1348

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8850.6348

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8842.9062

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8838.4219

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8836.1270

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8835.8281

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8842.3027

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8838.6553

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8828.3242

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8824.0654

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8817.2842

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8811.3135

3672/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8801.9297

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8792.7920

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8786.0156

3699/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8783.4512

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 8781.2451 - val_loss: 5611.4014

Epoch 3/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:08 51ms/step - loss: 2451.0229

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7496.2251

  20/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7007.4194

  29/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7222.5820

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7122.3989

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7340.5044

  58/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7301.1553

  66/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7171.5449

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7036.2314

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7141.8540

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7218.8379

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7203.8291

 115/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7122.4995

 124/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7154.9814

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7168.3804

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7160.6250

 151/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7157.0244

 160/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7195.8223

 169/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7199.2700

 178/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 7229.5059

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7113.3359

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7128.4468

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7147.4668

 216/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7138.6924

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7196.5269

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7143.6636

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7139.1748

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7194.2935

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7191.3052

 273/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7151.8613

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7130.9702

 291/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7145.8452

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7112.5635

 311/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7088.4849

 320/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 7065.8574

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7090.5708

 339/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7094.1343

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7099.0713

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7100.0195

 367/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7091.8687

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7098.6133

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7113.1436

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7115.4429

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7096.7910

 412/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7094.3320

 421/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7130.4248

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7109.5400

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7086.5210

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7122.2500

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7112.2798

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7132.7612

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7125.9443

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7100.0532

 489/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7066.9849

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7092.5933

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7115.8994

 515/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7121.1660

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7121.2153

 532/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7107.2339

 542/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7066.4761

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7059.5483

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7070.1597

 570/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7044.5845

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7047.9253

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7052.5679

 594/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7031.6362

 603/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7008.7266

 612/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6998.9541

 621/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 6996.4800

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6987.0537

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 6981.7769

 644/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 6971.7168

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 6965.0337

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6960.8232

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6965.3745

 670/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6979.1831

 675/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6972.5933

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6962.0234

 690/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6980.2754

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6976.9639

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6984.7036

 710/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6970.3442

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6988.1240

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6985.2090

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7000.0771

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 6997.7300

 746/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7034.0640

 754/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7047.8345

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7045.7646

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7056.1504

 777/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7050.2744

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7044.1157

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7035.6284

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 7045.3047

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7064.7349

 817/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7063.6929

 823/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7068.5908

 831/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7085.7090

 839/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7106.5024

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7102.7095

 856/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7112.4824

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7135.2568

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7130.0205

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7122.4888

 890/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7127.0278

 899/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7151.5259

 908/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7156.5029

 917/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7174.8643

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7177.1094

 935/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7161.4648

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7157.9600

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7160.5508

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 7162.1299

 970/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7164.6367

 979/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7167.6240

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7151.8657

 997/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7148.4717

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7143.9155

1014/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7142.1348

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7132.5903

1032/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7116.5479

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7124.1968

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7134.0859

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7123.3740

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7119.8662

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7126.6265

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7126.3755

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7137.3008

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7117.6484

1111/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 7122.6533

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7114.6914

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7096.0474

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7087.1562

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7083.4600

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7089.2744

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7092.2021

1177/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7088.0864

1186/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7102.0068

1195/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7114.4590

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7115.0645

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7110.3198

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7100.2607

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7105.5439

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7098.4507

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 7108.5713

1260/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7097.7715

1270/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7082.0601

1279/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7082.8687

1289/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7084.2153

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7083.8081

1308/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7088.9585

1316/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7083.5933

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7077.4272

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7072.9536

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7068.1416

1352/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7060.6147

1362/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7064.6650

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7067.1948

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7073.0327

1391/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 7073.2656

1402/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7065.8716

1412/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7056.1602

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7054.4263

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7058.7832

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7060.1665

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7050.7495

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7049.5962

1473/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7047.7734

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7039.9238

1494/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7036.9521

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7036.9668

1511/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7029.4150

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7020.2500

1530/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 7016.3965

1540/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7030.1172

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7027.8994

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7025.9551

1570/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7033.1890

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7047.1279

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7058.0317

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7059.0010

1608/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7048.5054

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7040.2793

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7045.6270

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7045.3149

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7039.9609

1658/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7038.9282

1668/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7032.9922

1678/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 7022.8872

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7013.9849

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7012.5151

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7010.5547

1718/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7019.1855

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7021.2798

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7019.8945

1747/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7023.9692

1757/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7020.8862

1767/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7015.3462

1777/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7007.5229

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7011.0293

1796/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7011.6880

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7005.4341

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7002.7104

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 7000.7134

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6996.3267

1846/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6995.0630

1857/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6998.7666

1866/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7002.5430

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6998.8745

1887/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6994.3423

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6990.6792

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7002.5903

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7000.4414

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7001.3403

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7005.6675

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 7001.5688

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6988.1709

1970/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6981.9238

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 6981.7969

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6977.7095

2002/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6989.4399

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6986.8540

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6986.5669

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6982.7578

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6978.9878

2056/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6974.3188

2067/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6980.3525

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6980.1084

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6979.7251

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6975.6133

2109/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6988.0791

2120/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6989.9292

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 6984.1553

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6983.6030

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6983.5327

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6977.9053

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6975.8545

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6975.8838

2188/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6976.2437

2196/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6974.3765

2205/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6976.2632

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6967.1445

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6970.2549

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6968.5278

2245/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6966.5132

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6967.9873

2263/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6966.0649

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6962.8218

2282/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6965.8369

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6964.2529

2301/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 6965.4321

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6962.4424

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6960.5771

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6952.6655

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6955.5439

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6950.9731

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6949.3770

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6949.9614

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6946.7173

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6945.9688

2392/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6940.0156

2402/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6937.9858

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6932.9248

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6929.0142

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6921.8325

2440/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6911.1948

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6905.5210

2460/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6904.4048

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6904.9053

2478/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 6899.8594

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6904.9224

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6906.5098

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6910.5073

2519/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6906.6030

2529/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6902.8423

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6900.0015

2547/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6899.8804

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6900.2539

2565/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6901.0132

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6910.3911

2585/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6919.2075

2595/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6916.1909

2605/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6909.4941

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6907.4492

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6902.0522

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6901.4214

2644/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6897.4634

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6899.9790

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6902.4434

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6897.9712

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6897.9419

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6892.1230

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6895.7969

2709/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6896.1772

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6896.7891

2727/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6898.5859

2737/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6899.1450

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6902.4272

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6898.1157

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6900.5122

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6900.1436

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6903.7397

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6908.7944

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6911.1274

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6917.2720

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 6964.7124

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7002.5732

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7027.5366

2854/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7039.0547

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7053.6074

2876/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7058.7080

2886/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7066.0171

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7067.9727

2908/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7072.9658

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7080.5786

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7093.1792

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7101.9019

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7107.2739

2962/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7106.1636

2971/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7106.5645

2983/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7105.0361

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 7101.0479

3003/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7107.5884

3013/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7110.8896

3024/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7113.7251

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7113.1108

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7117.8486

3057/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7123.2305

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7123.5913

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7128.6885

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7132.4951

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7145.7007

3110/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7152.5137

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7162.1846

3131/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7170.6694

3142/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7168.6460

3152/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7172.0518

3162/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7177.7852

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7177.9224

3183/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7173.5825

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7171.8135

3204/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7172.8672

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7180.4409

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7181.5542

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7180.3521

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7178.5571

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7185.2695

3264/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7191.3062

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7189.4341

3284/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7189.6372

3295/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7186.1987

3306/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7192.8774

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7191.1704

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7189.6211

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7182.7275

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7180.1055

3360/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7183.0332

3371/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7188.7080

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7193.9712

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7200.5732

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7198.2212

3414/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7193.1484

3425/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7196.0093

3436/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7190.6060

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7189.5034

3456/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7190.4702

3465/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7195.3105

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7191.2856

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7187.0269

3494/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7187.2227

3504/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7187.0225

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7190.9263

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7190.4712

3536/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7190.8672

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7189.8003

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7186.6562

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7189.5879

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7186.0439

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7188.9224

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7187.6284

3609/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7182.5752

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7178.5093

3629/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7177.5698

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7175.9775

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7174.5952

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7172.3228

3670/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7172.2544

3680/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7168.8667

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7165.3364

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7164.3398

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 7164.3398 - val_loss: 1335.9032

Epoch 4/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:08 35ms/step - loss: 11037.2891

  12/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 8875.9180

  23/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7942.3706

  34/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7833.8286

  46/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7268.0752

  57/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7539.0278

  68/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7817.5361

  79/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7518.8179

  90/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7418.9399

 100/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7338.3564

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7128.6562

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7046.3843

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6970.7456

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6834.6724

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6785.9165

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6868.5864

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6913.3096

 184/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6937.6353

 192/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6956.4619

 202/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7031.3188

 212/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7053.8330

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 7126.2593

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7168.0518

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7126.8677

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7113.0879

 268/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7042.9268

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6975.4897

 288/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6945.9116

 299/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7023.9961

 310/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6994.4014

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6981.8379

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 7017.4219

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6982.4248

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6991.8467

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6976.9966

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6964.9546

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6965.8169

 396/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6961.5205

 407/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6973.2676

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6954.5269

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6974.2998

 436/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6948.5635

 446/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6946.9849

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6940.1055

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6893.9160

 475/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6884.2437

 484/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6856.3042

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6875.9116

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6878.0215

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6866.2241

 524/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6856.6812

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6850.3306

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6881.0244

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6878.1074

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6865.8403

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6845.1382

 588/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6846.0796

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6847.5518

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6832.9985

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6829.1807

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6831.5693

 641/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6839.7012

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6852.1064

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6841.9204

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6829.0410

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6804.6807

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 6811.6333

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6797.0957

 715/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6798.5288

 725/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6838.0459

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6824.8667

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6808.0449

 753/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6808.6357

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6811.8882

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6813.9336

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6814.0425

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6816.2959

 800/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6796.0234

 810/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6785.2915

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6775.5156

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6767.9155

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6773.0796

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6768.2876

 861/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6764.2124

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6766.7061

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6755.1343

 892/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6753.1523

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6760.1997

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6756.4224

 924/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6749.9448

 935/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 6755.6855

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6738.8813

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6744.4995

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6752.5742

 977/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6726.8467

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6725.4253

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6717.4575

1009/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6703.5181

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6695.0571

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6688.3013

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6689.7070

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6683.4043

1060/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6686.1104

1070/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6674.9038

1081/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6674.8101

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6677.6338

1101/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6674.1362

1111/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6658.9780

1122/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6648.2529

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 6648.3999

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6639.7422

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6640.1250

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6636.0322

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6628.5508

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6623.2036

1193/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6619.0088

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6614.6055

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6623.0278

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6615.3242

1235/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6613.8496

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6615.1138

1255/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6621.1636

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6620.5684

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6617.4170

1286/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6605.1494

1296/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6600.3979

1306/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6596.3154

1316/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6614.0630

1327/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6607.3584

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 6607.1211

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6597.7090

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6595.0107

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6601.6831

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6589.6406

1389/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6575.8848

1400/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6570.8916

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6572.4478

1420/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6577.2026

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6588.9473

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6590.5928

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6586.6885

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6593.3037

1474/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6584.7974

1485/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6572.9355

1496/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6567.7168

1505/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6576.7300

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6575.0767

1526/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 6560.9365

1537/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6558.8022

1548/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6542.2207

1558/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6539.5649

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6538.5049

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6539.4150

1588/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6531.7759

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6543.4624

1608/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6543.2827

1619/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6553.0317

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6546.5811

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6546.7173

1649/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6545.2261

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6537.8511

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6536.9658

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6535.0723

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6541.4575

1702/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6546.3887

1712/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6547.3794

1722/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 6543.8320

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6540.3081

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6530.4844

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6520.6792

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6520.8555

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6515.8843

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6509.3286

1793/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6504.1387

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6503.3486

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6512.0479

1825/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6504.8164

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6501.0044

1846/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6498.8066

1857/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6495.0728

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6485.0938

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6489.6035

1887/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6484.1416

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6486.2593

1905/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6484.7368

1914/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6478.6831

1924/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 6480.4746

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6482.0439

1945/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6484.6880

1956/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6477.0239

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6487.1187

1978/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6486.8071

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6489.9121

1999/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6481.5625

2010/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6488.8652

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6489.0845

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6489.4517

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6488.4829

2053/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6484.3398

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6482.5952

2074/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6471.5327

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6465.9961

2096/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6463.2368

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6465.4175

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6473.9858

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 6475.0435

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6468.5073

2143/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6467.4111

2154/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6470.2490

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6470.5459

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6474.4463

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6476.4844

2194/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6475.7949

2204/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6471.0425

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6461.4438

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6455.0850

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6449.9170

2245/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6459.4219

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6454.9922

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6450.4014

2277/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6445.2646

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6446.6084

2298/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6446.7446

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6446.9004

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 6444.3223

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6442.6401

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6446.0288

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6439.8042

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6436.7891

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6438.0840

2385/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6448.9756

2396/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6440.6689

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6438.6050

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6435.1816

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6432.9351

2436/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6432.8130

2447/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6432.1523

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6429.4658

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6424.4746

2480/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6423.0166

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6418.9126

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6427.8486

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 6424.9961

2519/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6434.2808

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6435.0044

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6438.4077

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6434.7700

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6431.4272

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6426.6650

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6432.0342

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6433.0620

2601/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6435.7310

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6430.2827

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6430.0405

2631/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6431.8901

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6428.2793

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6428.7651

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6426.2666

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6421.9121

2682/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6415.8252

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6413.6079

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6416.4819

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6413.4033

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6413.1323

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6409.3022

2741/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6412.6572

2751/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6413.4233

2762/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6414.0161

2772/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6418.1226

2781/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6418.7041

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6418.6392

2803/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6422.3218

2813/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6427.1460

2824/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6422.8271

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6420.0991

2846/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6420.8848

2858/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6418.2124

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6412.7280

2880/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6412.6245

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6409.9590

2902/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6407.9609

2911/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6405.1909

2921/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6403.4756

2932/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6400.0552

2943/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6404.2739

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6405.8682

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6404.1602

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6407.1113

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6410.1738

2994/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6405.5229

3005/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6401.6860

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6404.5229

3025/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6401.6333

3036/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6396.6748

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6405.1631

3058/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6402.5708

3069/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6399.1445

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6397.7388

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6395.8311

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6394.1924

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6397.0234

3119/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6395.2856

3130/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6394.8706

3141/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6395.2500

3152/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6394.0044

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6397.7817

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6395.3013

3185/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6393.9019

3195/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6392.1206

3205/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6388.0947

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6384.1807

3227/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6380.8423

3237/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6379.4312

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6375.2480

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6376.1895

3270/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6369.4741

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6364.5522

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6367.1841

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6367.6406

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6365.2119

3323/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6363.3345

3334/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6364.0698

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6362.8296

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6359.7563

3366/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6354.8848

3376/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6355.4424

3387/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6354.9600

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6354.3047

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6354.3823

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6357.7144

3431/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6357.6211

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6354.2778

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6349.4062

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6344.8901

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6352.8447

3485/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6358.5874

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6359.3955

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6364.8364

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6369.4663

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6372.0952

3536/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6367.2080

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6369.9126

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6372.0938

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6368.4004

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6366.1606

3589/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6362.8989

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6367.3916

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6370.4204

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6370.3267

3633/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6375.1025

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6375.8926

3655/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6375.7422

3665/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6374.4854

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6381.4116

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6380.1431

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6377.1699

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 6376.6128 - val_loss: 513.0943

Epoch 5/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:28 56ms/step - loss: 7939.4912

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6085.8848

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5984.8999

  28/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6799.7417

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 6628.6978

  47/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 6856.8384

  57/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 6450.7090

  67/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 6409.3569

  77/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 6331.4565

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 6339.4360

  99/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 6311.3262

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 6336.3149

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6401.9917

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6318.5957

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6224.9824

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6266.5811

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6239.0776

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6109.8213

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6075.5801

 196/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6109.3657

 207/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6125.8828

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6184.7563

 227/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6163.9526

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6106.5952

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6112.2451

 255/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6070.2817

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6172.3257

 275/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6209.2837

 286/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6213.9502

 298/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6184.9033

 309/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6146.3721

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6160.1353

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6169.7959

 343/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6195.1040

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6136.9229

 362/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6114.5933

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 6089.1768

 381/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6105.1831

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6091.3101

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6054.4189

 407/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6058.4243

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6047.9922

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6055.1890

 434/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6055.6733

 443/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6040.9492

 452/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6004.2217

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5998.3423

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 6002.5347

 478/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5988.0469

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5968.2129

 495/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5962.6885

 501/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5980.7998

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5979.5532

 517/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5971.5615

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5964.6362

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5946.9204

 540/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5918.2783

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5897.5542

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5887.0923

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5892.0469

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5887.6914

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5884.6802

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5872.8970

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5889.1665

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5904.6602

 609/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5893.5566

 618/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5887.0947

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5893.8706

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5888.6533

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5895.6685

 652/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5889.8516

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5905.5122

 669/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5922.1152

 678/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5926.6465

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5933.2681

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5934.6064

 702/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5916.3647

 710/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5899.6855

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5896.5146

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5882.0708

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5884.8999

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5888.2915

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5888.3862

 749/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5896.8486

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5891.3423

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5909.5796

 771/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5894.1055

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5914.1104

 786/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5918.1108

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5934.3516

 800/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5957.4360

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5961.7515

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5947.0020

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5951.5532

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5948.2974

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5962.0298

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5951.5879

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5939.7480

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5930.7373

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5917.7812

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5923.4341

 879/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5933.7124

 887/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5933.0322

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5928.4800

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5919.7852

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5912.6108

 914/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5918.1543

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5913.6724

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5904.5820

 934/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5903.2632

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5909.7788

 950/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5931.7217

 959/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5936.4707

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5939.8599

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5947.1924

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5943.7056

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5943.6587

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5937.8579

1003/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5933.2319

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5920.7622

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5907.6284

1028/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5899.3496

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5888.3237

1044/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5901.0928

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5891.5815

1062/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5885.3330

1070/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5881.5190

1078/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5880.6807

1087/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5876.4600

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5870.3970

1105/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5875.7852

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5871.5688

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5877.2349

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5873.1001

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5859.2451

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5855.0752

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5850.9468

1162/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5853.6240

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5856.3921

1178/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5857.9927

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5850.1406

1193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5853.5625

1201/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5862.1064

1208/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5876.3701

1217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5879.9531

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5885.0288

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5887.8379

1243/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5888.0815

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5882.6655

1260/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5879.7954

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5879.0479

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5875.6973

1286/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5863.5933

1293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5871.7183

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5865.6265

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5866.5562

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5861.6973

1327/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5852.2056

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5858.3882

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5847.9053

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5847.1655

1359/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5848.5923

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5849.6147

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5854.3408

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5862.2759

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5865.2666

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5872.7666

1411/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5873.3335

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5868.6758

1427/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5863.6050

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5859.7271

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5849.7007

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5852.8101

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5862.5474

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5856.7690

1480/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5848.9946

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5852.1572

1497/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5848.5151

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5850.3125

1515/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5852.9326

1524/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5856.4663

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5851.2588

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5855.9834

1552/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5861.2744

1561/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5857.8228

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5852.5342

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5853.2056

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5857.4160

1593/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5854.9629

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5854.5649

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5852.2642

1620/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5848.4077

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5844.7715

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5851.7222

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5857.4570

1653/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5861.4946

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5858.7427

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5851.3237

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5854.9092

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5846.8003

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5847.0322

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5843.3252

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5842.7256

1722/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5835.6289

1730/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5836.6069

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5838.2827

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5833.5464

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5827.4336

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5822.3286

1769/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5821.2202

1777/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5823.1929

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5825.0566

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5826.7876

1803/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5826.1289

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5823.0122

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5819.6680

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5826.4546

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5826.1528

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5820.2944

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5822.5303

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5823.3120

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5816.1724

1879/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5814.8535

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5807.7222

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5807.1162

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5804.5132

1914/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5797.6211

1923/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5794.2109

1932/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5793.0293

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5790.9741

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5784.2725

1957/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5786.9448

1966/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5780.8413

1975/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5777.3276

1983/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5775.7217

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5783.0483

2000/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5779.8447

2008/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5777.4878

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5780.5186

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5780.5493

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5783.9058

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5781.9731

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5785.9531

2056/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5780.4609

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5780.3398

2075/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5774.8413

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5773.6909

2096/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5773.5796

2106/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5773.5493

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5768.7295

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5776.7188

2135/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5779.3496

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5785.6846

2154/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5788.8403

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5790.0635

2171/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5790.8613

2180/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5786.1636

2188/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5781.6279

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5777.9966

2208/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5778.3525

2216/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5776.8877

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5779.5415

2232/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5777.6353

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5778.4434

2250/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5785.5063

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5782.0273

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5786.8584

2277/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5789.6211

2285/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5786.2725

2293/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5786.9316

2301/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5786.4268

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5782.4253

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5778.4268

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5774.0439

2336/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5776.3481

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5782.2979

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5789.0391

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5793.2183

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5801.2554

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5800.0093

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5799.3525

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5797.4663

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5796.5845

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5797.9536

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5792.9331

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5789.8066

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5791.9287

2452/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5787.8184

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5787.6504

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5792.4023

2476/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5799.4624

2485/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5798.8711

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5800.3760

2504/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5801.3105

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5804.9512

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5811.9380

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5812.9722

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5814.5103

2546/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5817.2373

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5825.0874

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5832.9663

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5839.4092

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5843.7275

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5843.9785

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5839.7705

2607/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5838.7739

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5834.7192

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5834.1782

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5832.1089

2643/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5829.3198

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5832.0376

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5831.5029

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5827.0552

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5823.2417

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5825.2964

2701/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5825.8784

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5830.2578

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5830.8018

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5827.8882

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5825.5391

2748/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5820.9980

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5818.9419

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5818.6904

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5815.6353

2783/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5816.6484

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5813.8501

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5811.5171

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5807.8091

2817/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5806.9790

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5805.2173

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5802.7095

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5801.7905

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5803.1914

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5794.8662

2870/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5794.5068

2879/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5792.9116

2888/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5789.3696

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5789.2612

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5787.6631

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5787.8936

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5787.3623

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5784.5840

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5785.1001

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5785.8203

2958/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5782.2021

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5787.6250

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5788.0308

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5788.0854

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5787.9648

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5795.4175

3010/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5796.3311

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5801.8594

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5801.9395

3034/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5797.3862

3042/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5795.8872

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5797.6382

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5801.4761

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5802.1631

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5802.4097

3084/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5800.9243

3093/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5806.8760

3102/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5807.8955

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5805.9507

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5802.3311

3129/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5801.2559

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5798.9370

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5800.9814

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5797.9214

3165/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5796.3784

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5804.1147

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5805.8413

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5807.0542

3200/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5810.3062

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5809.4189

3217/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.8027

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.0679

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5804.1724

3246/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.9146

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5809.0430

3265/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5807.3027

3275/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.5156

3283/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5805.2246

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5803.6338

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.3413

3313/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5809.3638

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5807.2397

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5806.0283

3339/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5804.8374

3347/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5801.3110

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5800.6875

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5796.3662

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5795.0317

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5793.5474

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5793.0161

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5792.5283

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5792.8154

3418/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5791.8828

3426/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5791.9658

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5789.9004

3443/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5790.1655

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5788.9634

3461/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5786.1582

3470/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5784.6455

3478/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5784.8994

3486/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5786.4312

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5786.6392

3504/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5786.0762

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5785.3081

3520/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5787.6245

3528/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5791.0742

3537/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5792.2334

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5790.5938

3555/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5787.8467

3564/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5786.5503

3573/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5786.1938

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5785.2979

3589/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5785.1523

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5784.8379

3607/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5782.7168

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5781.0522

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5780.9678

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5781.2993

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5779.5493

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5780.1445

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5776.4072

3670/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5777.1494

3679/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5776.7642

3688/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5776.2764

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5777.4326

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5777.3672 - val_loss: 150.6325

Epoch 6/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:38 59ms/step - loss: 6090.4990

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5345.0879

  20/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5888.0864

  29/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5809.7373

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5739.2041

  48/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5805.8647

  57/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5785.1812

  65/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5838.1992

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5622.4868

  83/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5601.8223

  89/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5535.0591

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5448.6753

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5385.4707

 115/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5433.9897

 124/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5396.3716

 133/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5365.8965

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5394.3784

 151/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5373.0757

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5318.4131

 168/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5319.3672

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5328.6948

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5303.6372

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5322.3081

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5305.0723

 216/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5320.4419

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5350.5303

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5408.3320

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5434.5352

 255/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5492.7822

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5426.2886

 274/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5458.5269

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5449.4893

 291/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5440.2788

 300/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5416.9648

 308/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5427.2139

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5462.8755

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5482.6216

 335/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5510.0439

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5518.5444

 351/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5512.8633

 360/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5502.9854

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5509.6865

 376/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5532.0151

 384/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5524.8115

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5505.8472

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5498.2837

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5517.0981

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5526.7051

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5553.8657

 432/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5533.0796

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5534.8994

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5531.1411

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5548.6665

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5549.8511

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5535.2437

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5529.5850

 495/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5556.2378

 503/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5573.1035

 512/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5546.3818

 520/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5533.0757

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5542.0820

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5530.8511

 544/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5528.1064

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5534.0410

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5518.3452

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5511.5342

 575/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5515.8857

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5540.3374

 592/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5538.3452

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5524.4419

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5508.9019

 615/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5507.4224

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5507.1831

 631/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5526.5273

 640/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5523.1138

 650/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5512.2842

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5520.9282

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5523.4268

 675/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5533.3120

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5530.9014

 692/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5517.8521

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5520.0679

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5506.8564

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5506.7881

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5512.5269

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5511.8184

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5505.6772

 749/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5505.5610

 759/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5525.0742

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5551.0366

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5551.3276

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5566.5820

 799/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5569.1714

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5583.9282

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5562.6582

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5556.5093

 836/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5560.6553

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5550.9507

 856/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5552.4531

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5546.6680

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5539.5732

 883/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5531.5767

 892/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5534.1577

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5534.9033

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5528.3555

 917/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5533.2393

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5536.7622

 935/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5535.7920

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5541.7144

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5538.6387

 961/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5540.6445

 970/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5554.8462

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5583.6777

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5594.5347

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5606.1865

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5599.8467

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5611.2725

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5610.1489

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5617.3960

1038/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5624.0059

1047/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5617.3633

1055/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5639.0225

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5638.6108

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5650.9844

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5652.9565

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5663.4604

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5667.6050

1105/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5684.2944

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5690.0010

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5707.4858

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5712.6157

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5711.9971

1145/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5719.3804

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5711.3091

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5706.6064

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5696.7026

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5695.3784

1188/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5684.0405

1197/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5673.5708

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5683.4819

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5691.1025

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5702.2451

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5698.6636

1242/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5697.0737

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5692.8677

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5698.7681

1269/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5690.4609

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5691.9937

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5681.7310

1294/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5677.5107

1303/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5675.0254

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5672.0610

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5672.3535

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5667.7104

1338/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5664.7661

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5668.2280

1358/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5678.7842

1368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5682.5762

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5688.2397

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5700.3408

1398/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5694.4717

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5682.1343

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5684.7959

1428/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5682.6792

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5678.8760

1449/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5672.2803

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5671.0571

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5673.3843

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5676.4624

1494/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5672.2563

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5671.6904

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5676.1436

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5672.2417

1532/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5665.3667

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5653.9375

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5647.5952

1558/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5653.1777

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5653.4922

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5651.2095

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5641.8188

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5640.0552

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5642.2114

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5637.5825

1619/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5630.6011

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5629.1006

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5628.4746

1646/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5627.9380

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5626.6167

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5627.0493

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5628.4536

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5624.1201

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5617.8608

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5627.9990

1706/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5627.4038

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5630.3447

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5635.2817

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5635.4463

1740/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5637.9106

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5640.6943

1759/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5647.3931

1765/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5645.5010

1774/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5644.5151

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5637.2642

1791/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5634.4478

1800/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5632.8584

1809/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5638.1260

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5640.4492

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5630.0342

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5627.2339

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5628.6641

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5624.8477

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5618.1411

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5611.5459

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5606.6348

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5603.4717

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5615.3774

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5622.8540

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5639.2725

1923/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5640.8550

1932/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5640.7075

1941/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5638.6475

1949/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5636.9258

1958/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5635.7007

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5629.4424

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5632.7744

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5630.5752

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5633.2065

2006/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5629.0864

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5624.2734

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5615.6602

2035/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5612.6001

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5606.3335

2051/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5604.9619

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5602.0591

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5594.5034

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5586.5010

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5588.8286

2099/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5583.8081

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5577.9604

2116/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5579.1079

2124/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5577.5498

2132/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5581.5913

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5585.1235

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5587.1338

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5585.6870

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5581.6079

2175/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5591.2300

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5589.3696

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5581.9375

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5575.7871

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5570.4961

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5570.4673

2228/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5573.7944

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5568.9795

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5571.5884

2252/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5577.1680

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5580.2197

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5580.8071

2276/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5584.1152

2285/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5582.6699

2293/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5578.0322

2302/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5579.7285

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5574.5610

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5569.9077

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5567.4980

2337/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5564.8228

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5565.9077

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5567.1543

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5562.1099

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5559.7959

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5561.1323

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5557.8638

2400/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5561.2676

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.4517

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5558.0361

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5560.4136

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5561.1084

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5556.5327

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.0918

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.8765

2471/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.5889

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5563.8018

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5563.0806

2497/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.6323

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5559.5591

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5559.3076

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5559.9941

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5562.6108

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5561.1953

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5564.3140

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5559.7021

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5555.5571

2576/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5555.9868

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5558.9575

2596/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5561.7090

2605/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5563.2603

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5564.0669

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5569.4443

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5568.8965

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5571.9229

2655/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5573.1289

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5572.5015

2674/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5572.8735

2682/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5571.1284

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5566.8901

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5566.5518

2708/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5565.4629

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5567.2998

2725/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5564.2227

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5564.6904

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5565.5513

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5564.1885

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5561.6187

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5558.7378

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5554.4033

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5554.1587

2796/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5554.5498

2805/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5550.1011

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5550.8623

2823/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5547.2803

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5552.5000

2840/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5555.4805

2849/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5554.7344

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5549.7397

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5550.4697

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5549.5674

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5548.9722

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5549.9502

2901/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5550.3833

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5547.8535

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5550.6211

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5552.7764

2935/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5551.5278

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5552.4067

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5549.6880

2961/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5549.7305

2970/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5548.4541

2980/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5548.0801

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5546.5908

2996/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5545.4717

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5543.3413

3012/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5545.3491

3020/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5548.8477

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5546.6855

3037/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5550.2637

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5551.0195

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5553.4956

3065/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5554.1255

3074/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5552.8833

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5556.1826

3092/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5555.6123

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5554.1196

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5554.1465

3116/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5549.9673

3125/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5549.1841

3134/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5549.7666

3143/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5551.8682

3153/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5550.3960

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5551.3242

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5554.8599

3183/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5556.4043

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5557.4443

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5559.3477

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5556.3296

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5554.6519

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5556.1309

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5555.4980

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5556.9600

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5562.1592

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5558.3301

3276/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5559.0176

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5556.1221

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5553.8477

3301/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5552.1694

3310/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5554.0493

3319/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5555.9580

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5558.2104

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5560.1030

3346/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5559.7944

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5559.0029

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5561.8403

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5567.1768

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5574.4580

3391/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5580.1738

3401/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5581.1143

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5581.9629

3419/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5585.9268

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5592.2378

3437/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5592.8442

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5591.9917

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5591.9819

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5588.3408

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5586.9409

3480/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5582.9707

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5583.3687

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5580.5684

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5580.5757

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5579.7378

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5574.9941

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5572.1719

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5573.5620

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5576.6274

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5575.3975

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5575.2090

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5571.3643

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5570.9194

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5567.5078

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5566.1367

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5566.0029

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5563.1460

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5563.5400

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5562.8813

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5559.0337

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5559.0200

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5559.7227

3671/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5561.1211

3680/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5559.8525

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5560.1416

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5559.6108

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 7ms/step - loss: 5560.6616 - val_loss: 925.1566

Epoch 7/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:03 33ms/step - loss: 3446.3796

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6429.4570

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5793.2881

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5781.9868

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5617.1006

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5749.8989

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5742.0630

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5640.7559

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5616.8745

 103/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5562.0811

 112/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5500.2393

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5469.6187

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5505.3926

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5516.9766

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5567.4189

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5503.5454

 167/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5491.1553

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5395.8013

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5356.8491

 195/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5316.1177

 202/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5352.0435

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5400.1113

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5471.6802

 227/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5475.6553

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5546.8823

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5528.7144

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5531.9712

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5523.3643

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5505.9707

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5522.8530

 288/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5525.1987

 297/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5494.7749

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5474.5371

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5445.0815

 323/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5430.4351

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5428.7134

 340/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5414.0137

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5433.5229

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5433.2119

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5420.2114

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5416.6274

 381/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5376.5708

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5353.6484

 399/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5356.7222

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5342.6602

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5319.1431

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5335.2124

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5343.2759

 444/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5340.1470

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5318.7236

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5307.7803

 470/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5297.5229

 479/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5292.3257

 488/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5304.1108

 496/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5298.4834

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5281.6982

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5286.9380

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5302.3970

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5327.8999

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5323.5591

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5334.7847

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5303.8198

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5310.6133

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5308.4580

 587/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5287.4932

 597/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5295.2993

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5286.6240

 617/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5297.7881

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5273.2681

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5268.2949

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5294.9604

 657/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5297.9600

 668/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5305.9004

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5315.6597

 690/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5337.9390

 701/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5359.7939

 713/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5353.8423

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5340.8604

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5358.2173

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5358.0879

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5352.1626

 759/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5373.0083

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5379.6611

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5392.2593

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5401.4614

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5400.2544

 803/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5387.8423

 812/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5395.3096

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5399.2222

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5414.9536

 837/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5413.8613

 846/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5403.2285

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5411.1011

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5411.2881

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5402.0625

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5390.6382

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5401.5601

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5409.9600

 905/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5422.1528

 914/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5416.8882

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5405.9609

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5402.3594

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5409.5459

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5401.1265

 957/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5400.8667

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5396.2236

 973/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5398.2539

 982/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5395.0015

 990/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5386.8062

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5380.5571

1007/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5387.9580

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5380.9717

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5380.6611

1033/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5387.0112

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5396.7612

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5401.8296

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5401.5796

1067/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5410.1162

1076/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5423.3257

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5421.8774

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5419.5796

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5413.9243

1111/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5416.2388

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5411.8335

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5414.2998

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5422.2783

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5436.1138

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5425.0654

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5433.5547

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5427.1577

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5427.6958

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5431.5220

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5427.3413

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5436.7993

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5437.9312

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5444.1382

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5448.7168

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5440.0981

1247/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5443.2949

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5445.8589

1267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5437.1699

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5443.4551

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5442.6538

1294/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5454.5298

1305/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5449.0181

1315/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5447.4458

1326/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5439.4683

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5444.8008

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5439.9355

1361/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5434.4424

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5436.2051

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5440.2983

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5439.8408

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5436.9780

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5428.2310

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5424.1055

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5414.4546

1454/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5409.6992

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5404.6875

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5402.5239

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5399.1982

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5400.9658

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5400.3179

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5401.3125

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5399.1162

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5401.9805

1556/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5391.8628

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5387.6719

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5390.5229

1592/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5389.7871

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5385.4634

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5383.5654

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5393.0728

1639/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5383.6382

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5379.3965

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5385.2544

1673/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5391.0654

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5408.0479

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5406.5547

1700/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5412.0098

1709/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5411.1426

1718/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5404.5479

1727/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5403.6318

1736/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5398.5005

1745/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5392.9644

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5388.2285

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5387.7871

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5395.5376

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5390.7993

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5391.9058

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5395.4956

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5395.8057

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5401.5610

1824/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5398.9087

1833/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5402.9390

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5401.3936

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5393.6470

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5392.9219

1869/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5390.0488

1878/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5394.7817

1887/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5389.8955

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5385.3662

1904/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5382.5098

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5384.8662

1922/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5389.7427

1930/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5383.5049

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5383.0508

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5382.7520

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5389.7212

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5391.4321

1971/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5393.2314

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5388.3638

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5393.5542

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5397.4819

2006/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5407.0938

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5414.0107

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5413.4805

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5410.2134

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5408.0347

2050/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5401.4219

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5401.4058

2066/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5400.3379

2074/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5396.7397

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5399.7651

2092/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5400.8389

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5403.0703

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5397.7690

2120/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5395.7236

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5390.9116

2136/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5389.7358

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5392.4175

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5391.5693

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5389.5518

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5386.9077

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5383.7622

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5384.3110

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5388.9287

2208/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5385.7832

2217/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5382.7622

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5378.9272

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5379.1533

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5379.3638

2252/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5377.2632

2261/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5386.4604

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5383.7144

2278/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5388.5083

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5384.5562

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5382.0229

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5381.0122

2314/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5384.5576

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5384.4150

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5388.6846

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5387.4502

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5386.4121

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5383.1978

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5385.1562

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5386.5415

2380/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5388.2168

2388/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5387.2144

2397/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5389.5576

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5387.5869

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5388.0981

2422/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5385.1270

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5386.1875

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5393.6714

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5401.1030

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5401.6343

2456/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5406.6318

2464/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5402.0791

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5399.5127

2480/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5407.8369

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5406.3247

2497/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5404.3950

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5408.6982

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5408.2842

2524/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5406.5737

2532/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5403.4302

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5405.6836

2547/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5402.3979

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5399.5205

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5395.0640

2569/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5395.3340

2577/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5396.7480

2585/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5398.3896

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5400.7104

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5402.0522

2607/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5402.0620

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5401.3535

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5398.6104

2629/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5396.0947

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5394.5635

2641/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5393.4702

2648/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5396.5454

2656/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5397.6270

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5397.0049

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5391.4531

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5389.1216

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5388.4707

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5383.2837

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5382.6338

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5379.1367

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5376.6514

2715/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5373.7480

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5369.4512

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5369.8408

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5371.0581

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5378.0576

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5378.4824

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5381.8755

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5379.1514

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5384.1816

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5383.4341

2790/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5385.8740

2798/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5385.3838

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5383.7402

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5378.9004

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5377.2168

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5375.9395

2843/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5375.5073

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5372.7949

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5372.3389

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.8672

2876/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.4497

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.7129

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.1265

2899/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5379.6582

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5383.2544

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5380.7930

2921/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5379.0088

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.3979

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5375.6855

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5378.2642

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5372.6396

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.0312

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5374.1455

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5372.7002

2983/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5371.6362

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5375.8267

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.4468

3007/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5376.7808

3016/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5378.2646

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5377.0103

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5376.3511

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5377.0132

3048/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5378.3213

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5377.2905

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5375.0781

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5372.9053

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5370.9546

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5367.1655

3098/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5363.9932

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5366.5752

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5365.7695

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5369.6841

3131/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5370.8906

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5369.8774

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5369.9912

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5374.2256

3164/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5375.3677

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5374.8228

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5372.3086

3189/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5369.8179

3198/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5372.2056

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5370.3574

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5371.6064

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5370.4658

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5367.5400

3239/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5366.4590

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5371.4570

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5371.1704

3265/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5371.6802

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5374.0405

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5373.0981

3288/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5374.6987

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5376.5205

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5373.2891

3313/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5367.8638

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5367.8179

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5369.6318

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5371.5229

3346/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5372.0444

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5373.7896

3364/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5374.0825

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5375.3643

3383/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5376.2896

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5377.1943

3401/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5378.7759

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5378.0073

3421/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5379.6538

3431/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5377.4985

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5379.3101

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5382.5713

3460/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5382.6753

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5390.5400

3478/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5389.5586

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5387.0654

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5384.8369

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5383.5122

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5383.6709

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5387.3887

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5385.8281

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5386.5508

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5384.0815

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5382.9351

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5379.8604

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5378.4380

3581/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5379.8975

3589/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5379.9126

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5380.9189

3607/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5378.7632

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5380.2021

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5381.5977

3632/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5384.7144

3641/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5384.2104

3650/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5382.3618

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5381.0088

3668/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5379.7832

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5377.3281

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5377.7861

3694/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5379.4961

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5381.3452 - val_loss: 149.4433

Epoch 8/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:55 64ms/step - loss: 3541.3101

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6272.5752

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5543.4199

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5585.3838

  35/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5329.7925

  43/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5509.1914

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5744.3491

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5736.8320

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5659.5630

  79/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5579.9619

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5485.4038

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5406.0898

 108/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5407.5879

 118/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5417.9282

 126/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5358.9570

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5322.1270

 144/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5368.6060

 150/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5459.1973

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5470.2637

 167/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5454.6006

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5453.2778

 184/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5531.1846

 191/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5512.3760

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5475.8965

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5499.4761

 215/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5528.2344

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5565.4619

 232/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5609.2422

 240/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5576.3989

 249/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5549.2427

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5537.6177

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5516.9639

 276/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5526.9961

 285/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5505.0977

 294/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5553.7646

 303/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5544.4722

 312/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5547.4941

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5543.7104

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5542.4946

 338/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5557.4883

 346/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5538.6753

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5551.3745

 363/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5546.2358

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5544.5054

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5554.1548

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5571.8306

 399/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5547.2080

 409/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5559.2603

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5543.8813

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5532.2319

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5500.7754

 449/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5519.1406

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5498.1147

 469/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5501.3169

 478/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5498.0762

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5465.6348

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5450.7026

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5434.7588

 510/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5426.6860

 519/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5436.6152

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5431.2314

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5423.2988

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5413.6494

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5415.8003

 558/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5425.2700

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5423.5273

 576/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5419.1665

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5403.7329

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5404.2012

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5401.4526

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5412.0122

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5405.1606

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5398.0288

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5402.1875

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5393.3394

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5395.7456

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5380.8882

 668/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5371.2729

 677/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5386.1367

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5379.5996

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5397.9683

 702/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5384.3662

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5381.1875

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5376.1768

 726/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5375.0601

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5364.5786

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5364.3608

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5369.9751

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5391.8716

 771/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5396.2910

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5392.8057

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5391.4678

 798/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5377.7720

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5375.3081

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5366.5156

 823/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5366.4561

 832/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5365.2598

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5378.7441

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5367.9346

 858/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5349.6382

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5358.9990

 875/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5347.9814

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5333.7729

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5331.9570

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5334.2578

 910/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5326.7544

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5322.6187

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5330.2715

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5323.7876

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5326.5962

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5322.1118

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5318.8887

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5323.7041

 983/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5337.7197

 993/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5330.5283

1003/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5315.1162

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5302.5288

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5306.4331

1031/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5310.3140

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5312.1685

1052/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5304.0151

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5320.1587

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5320.6191

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5309.4155

1097/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5315.9492

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5315.7217

1116/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5320.3052

1126/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5318.0488

1134/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5326.1440

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5321.7017

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5317.5801

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5311.0239

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5312.1123

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5316.8770

1189/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5315.0820

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5314.5649

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5316.3770

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5312.8223

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5319.3296

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5314.1543

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5315.4917

1248/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5322.7446

1255/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5323.6831

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5327.9976

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5328.7314

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5320.0200

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5312.4604

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5318.0010

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5318.7549

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5326.0156

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5319.1865

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5315.7256

1346/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5319.1729

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5317.3843

1365/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5317.1772

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5334.1685

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5346.0566

1390/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5353.9258

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5354.4102

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5356.1509

1416/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5354.6748

1425/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5365.4492

1434/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5367.3960

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5366.7358

1451/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5369.6982

1459/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5366.3867

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5358.7017

1475/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5352.6519

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5354.0923

1491/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5352.3833

1500/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5346.0151

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5341.5762

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5338.0952

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5330.8218

1536/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5335.6577

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5344.6694

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5343.3286

1561/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5343.9780

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5345.0264

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5349.3818

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5351.6758

1596/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5348.8706

1605/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5349.6265

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5346.7803

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5340.7124

1633/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5333.5581

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5336.5215

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5344.5513

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5339.0107

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5337.6094

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5335.9805

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5330.6440

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5329.7139

1711/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5325.4395

1720/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5326.0786

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5319.0693

1736/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5319.0923

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5318.7280

1752/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5323.4370

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5318.1650

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5313.2134

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5311.3984

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5316.9893

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5315.4473

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5314.3599

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5314.3677

1821/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5316.5249

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5319.4180

1839/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5313.4229

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5316.5020

1856/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5317.2041

1864/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5313.0796

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5312.0293

1881/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5308.7749

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5309.7754

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5314.0356

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5317.6226

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5314.6045

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5311.3413

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5314.4136

1942/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5310.0815

1951/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5309.4463

1960/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5311.5908

1969/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5317.8208

1978/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5320.3853

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5321.3521

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5321.9609

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5319.3857

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5320.9106

2022/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5321.1299

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5321.3135

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5319.3706

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5317.4438

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5320.6255

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5327.0376

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5325.5942

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5328.5737

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5329.0039

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5326.7642

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5329.9521

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5328.6396

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5322.2578

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5318.0703

2139/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5317.5352

2147/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5315.8926

2155/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5314.6807

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5310.7471

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5309.5571

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5310.1396

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5314.0444

2203/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5311.6240

2212/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5314.3013

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5312.0308

2230/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5309.2817

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5305.2222

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5307.7588

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5309.5386

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5314.2363

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5313.2134

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5316.3921

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5313.3716

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5319.3550

2313/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5319.7114

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5317.6377

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5317.1040

2337/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5315.0459

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5313.4839

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5311.0527

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5310.0903

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5311.0425

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5308.4019

2388/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.5732

2396/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.8423

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.8975

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.8384

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5304.9263

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5306.4570

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5308.0884

2447/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.4771

2455/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5303.2134

2464/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5304.4189

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5305.7002

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5307.0825

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5305.8906

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5305.8364

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5305.6201

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5304.5469

2524/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5305.9019

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5306.9873

2541/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5313.0723

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5313.8921

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5309.7710

2564/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5308.1616

2572/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5304.6216

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5308.3086

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5308.4126

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5306.7725

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5306.2739

2615/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5305.0063

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5300.2734

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5300.7642

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5303.1812

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5300.2290

2660/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5301.6055

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5296.2285

2678/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5299.7939

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5302.1665

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5299.6226

2705/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5297.9370

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5302.2388

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5301.1138

2729/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5303.1289

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5298.2754

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5301.3032

2756/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5301.9731

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5298.7324

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5295.9326

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5297.9097

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5299.9238

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5296.2090

2817/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5298.5200

2827/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5295.5586

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5296.1201

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5294.2275

2855/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5295.0366

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5293.7490

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5290.8813

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5291.3760

2892/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5290.6484

2901/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5291.8818

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5292.7739

2918/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5289.2305

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5286.6514

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5286.6875

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5289.6240

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5289.8823

2960/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5289.3730

2969/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5295.5933

2978/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5298.4019

2986/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5300.5923

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5297.8086

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5303.0044

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5300.3477

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5298.5332

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5296.1543

3033/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5296.1069

3042/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5296.5117

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5295.5117

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5295.6460

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5309.2007

3070/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5308.7632

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5309.6992

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5312.9800

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5317.2368

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5318.5859

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5321.7778

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5326.0425

3131/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5325.5391

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5325.4800

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5325.7056

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5326.2866

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5329.4639

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5334.0210

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5335.2559

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5338.9077

3198/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5340.7241

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5341.5376

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5346.3906

3225/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5346.4951

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5346.6509

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5345.0356

3253/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5347.5757

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5345.8906

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5349.2095

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5355.4502

3289/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5354.5742

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5358.6777

3306/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5360.1504

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5360.6440

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5360.1406

3331/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5358.5171

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5364.9067

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5364.5967

3359/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5365.2124

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5367.4585

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5370.1543

3389/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5367.7407

3399/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5365.7983

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5370.9307

3418/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5371.3276

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5370.2222

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5371.2769

3448/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5371.3345

3457/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5368.8691

3466/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5369.0728

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5369.4893

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5369.4297

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5370.4229

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5370.5039

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5365.9736

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5362.5601

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5358.9326

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5366.3994

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5364.7583

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5364.0166

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5366.4453

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5364.1050

3576/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5365.2490

3585/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5366.9883

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5364.3291

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5361.1323

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5360.8926

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5362.6348

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5361.4414

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5361.8779

3645/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5358.4863

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5360.5815

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5360.4146

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5359.0542

3678/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5360.8276

3687/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5359.6519

3696/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5359.6709

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5361.7026 - val_loss: 163.4189

Epoch 9/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:58 65ms/step - loss: 3162.8689

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4684.3667

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5425.6021

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5333.4341

  36/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5371.3076

  44/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5369.5005

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5375.2920

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5212.9966

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4993.3535

  80/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4915.3765

  89/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5023.0527

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4971.4268

 107/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4892.9409

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4892.2334

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4868.5146

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4900.3979

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4893.2070

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5050.8711

 155/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5015.5815

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4970.4126

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5026.5610

 182/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5098.2148

 191/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5071.0132

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5107.4873

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5105.4170

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5154.5117

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5189.5845

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5148.6729

 243/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5156.5747

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5129.5615

 260/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5148.5298

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5160.6353

 277/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5142.9038

 286/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5154.0044

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5120.4707

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5159.9194

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5133.5151

 323/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5149.8354

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5187.8257

 343/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5175.5708

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5182.4971

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5202.7705

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5182.4326

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5160.4863

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5146.4004

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5175.8320

 407/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5168.5293

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5184.1572

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5157.3750

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5146.7437

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5163.0684

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5180.9375

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5162.0513

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5170.1094

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5156.2061

 484/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5140.7974

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5135.3296

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5126.1504

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5128.7319

 517/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5123.5371

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5132.0596

 534/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5134.6753

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5147.5103

 551/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5148.8198

 558/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5143.3652

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5151.9795

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5158.1958

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5152.2563

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5169.5430

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5166.4487

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5138.7734

 616/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5122.6533

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5109.9546

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5108.2739

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5118.4238

 652/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5108.5649

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5117.0640

 670/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5111.9819

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5114.8071

 688/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5128.4634

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5124.6899

 707/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5124.2539

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5125.3833

 725/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5137.8740

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5139.5591

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5126.8203

 751/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5139.5791

 760/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5157.4712

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5149.0952

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5137.9595

 787/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5130.6309

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5127.6094

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5125.5083

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5124.3647

 821/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5133.0938

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5134.4399

 835/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5140.9722

 844/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5129.1348

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5127.2773

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5143.4961

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5155.0571

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5148.5332

 890/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5162.3887

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5145.6343

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5141.0332

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5150.2329

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5156.0649

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5165.3105

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5176.8013

 958/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5170.8721

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5183.6074

 977/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5174.0190

 986/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5165.1177

 995/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5175.5938

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5173.5332

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5175.9360

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5174.4438

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5166.9312

1039/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5169.7690

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5177.5713

1056/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5174.2524

1065/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5167.1440

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5167.9038

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5176.6191

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5162.6382

1099/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5161.0410

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5166.7295

1117/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5162.4805

1126/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5156.9683

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5155.5337

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5155.3643

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5156.3647

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5156.1792

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5158.1069

1178/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5156.7622

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5158.4497

1196/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5151.1772

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5138.3716

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.3086

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5137.8887

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5137.4478

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5136.0347

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.9019

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5146.7661

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.5127

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5134.3516

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5142.2812

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5145.8330

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5143.4502

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5142.2202

1318/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.5762

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5138.5659

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5133.3516

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5140.7183

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.9507

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.1206

1365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5143.4116

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.8589

1379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5137.1045

1387/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.8291

1395/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.8540

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5136.0225

1411/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5135.1050

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5132.0024

1426/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5131.6416

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5126.2119

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5130.9106

1448/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5144.9175

1456/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5140.0830

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5145.4756

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5153.9966

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5153.8125

1485/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5160.9751

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5163.2412

1501/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5170.8740

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5175.8848

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5170.3521

1525/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5167.5615

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5167.4214

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5164.1865

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5162.1372

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5165.6753

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5157.4990

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5154.4365

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5153.7837

1596/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5152.1147

1605/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5149.3555

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5147.9585

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5147.8101

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5139.7969

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5142.1426

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5145.7212

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5147.5728

1644/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5145.8091

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5140.6226

1657/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5147.6230

1664/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5146.9268

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5146.1309

1678/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5139.0933

1684/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5137.8589

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5138.1001

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5143.1968

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5149.0342

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5146.5791

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5157.5366

1720/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5153.4248

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5163.3672

1734/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5159.8442

1740/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5160.2241

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5157.9507

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5157.4736

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5153.7842

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5161.7451

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5159.7744

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5168.7417

1784/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5165.7061

1791/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5168.1846

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5167.1519

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5181.9385

1808/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5181.9995

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5178.5913

1821/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5185.8599

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5193.0562

1833/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5193.9922

1841/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5195.7910

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5197.1440

1855/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5196.6758

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5195.4478

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5191.1226

1872/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5198.9775

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5203.5454

1884/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5211.9927

1892/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5208.7070

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5208.1631

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5215.0942

1912/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5214.8350

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5224.9990

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5228.3228

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5233.4917

1942/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5230.8760

1949/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5230.6748

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5229.2632

1963/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5228.5186

1969/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5230.1733

1977/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5228.7261

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5229.9307

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5228.8198

1999/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5230.2114

2007/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5236.3174

2014/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5239.0547

2023/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5240.3359

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5236.9209

2039/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5234.9150

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5235.5010

2056/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5234.8071

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5238.8203

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5240.2241

2078/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5244.1050

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5242.1553

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5235.3125

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5231.3154

2112/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5237.4478

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5238.6777

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5239.1084

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5249.3203

2146/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5246.7891

2154/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5244.7319

2163/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5242.7168

2171/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5238.9683

2180/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5237.8838

2189/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5234.9385

2197/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5235.9951

2206/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5234.4214

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5232.2139

2222/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5232.6777

2230/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5231.9858

2238/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5229.1001

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5233.1206

2255/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5235.7217

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5234.2661

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5228.3516

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5224.6562

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5226.1655

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5226.1436

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5225.2349

2312/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5221.6763

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5229.3506

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5230.1567

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5227.2661

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5227.1191

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5226.9141

2360/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5232.3989

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5231.1826

2377/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5234.6011

2385/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5234.2964

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5232.7607

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5230.9727

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5234.5410

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5229.6611

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5226.5234

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5228.2905

2440/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5232.0034

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5232.3149

2456/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5239.7441

2464/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5244.0005

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5241.9272

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5235.6758

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5233.9971

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5228.9819

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5227.5435

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5228.0762

2519/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5231.9248

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5230.3989

2534/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5234.7114

2541/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5233.8135

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5235.1938

2558/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5233.2671

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5230.5518

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5233.1821

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5238.2705

2588/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5234.3970

2596/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5231.1636

2605/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5234.9556

2612/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5233.8613

2620/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5235.8203

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5236.7397

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5239.4043

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5241.8784

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5241.7334

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5243.3477

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5245.1602

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5250.4253

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5250.1084

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5249.3276

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5251.4580

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5255.1338

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5253.1636

2729/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5252.7896

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5252.8521

2748/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5253.0532

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5251.3481

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5252.6235

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5251.1479

2783/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5254.7441

2793/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5252.8179

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5250.3848

2810/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5253.8052

2819/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5253.5522

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5255.7241

2836/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5252.2139

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5252.2832

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5248.0454

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5245.9927

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5244.0825

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5249.9243

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5245.9521

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5245.6479

2901/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5247.1875

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5248.1582

2918/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5245.8896

2926/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5249.9355

2933/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 5254.1724

2941/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5253.8433

2950/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5252.4844

2958/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5251.4609

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5256.9824

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5260.0259

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5261.2739

2992/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5262.4058

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5264.9272

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5262.4697

3016/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5260.3779

3024/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5263.2642

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5262.0674

3040/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5260.6367

3049/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5258.9639

3058/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5258.6450

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5262.5493

3074/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5261.7349

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5262.1392

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 5261.8193

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5265.4497

3106/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5266.9023

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5265.8730

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5269.1602

3129/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5267.3857

3137/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5268.0698

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5269.4131

3152/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5270.8936

3160/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5272.9644

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5271.3179

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5273.7852

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5275.9404

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5273.8887

3200/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5275.0288

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5277.7515

3215/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5280.5688

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5282.5562

3229/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5281.8184

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5283.8350

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5283.8555

3253/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5284.3838

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5281.6382

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5277.2227

3277/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5275.8037

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5275.5845

3294/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5276.5723

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5274.1846

3311/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5274.2461

3319/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5276.5449

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5275.4839

3335/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5277.8501

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5277.5781

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5277.9204

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5277.6357

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5278.6440

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5280.0835

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5275.9907

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5278.6631

3407/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5281.3550

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5280.1855

3425/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5279.7769

3434/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5278.4014

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5276.7695

3449/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5278.4585

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5277.6880

3467/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5272.0210

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5268.0464

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5268.5044

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5266.3652

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5266.7861

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5266.0688

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5262.6494

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5260.3691

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5260.6270

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5261.8911

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5262.0044

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5262.4565

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5260.1538

3576/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5256.2827

3585/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5256.5806

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5255.6279

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5255.7822

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5253.8745

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5250.5059

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5251.3906

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5250.4634

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5249.0713

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5247.6025

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5248.7446

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5247.4170

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5244.2681

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5243.5020

3693/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5243.5991

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 27s 7ms/step - loss: 5244.4307 - val_loss: 1104.9514

Epoch 10/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 4:02 66ms/step - loss: 4833.7681

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6747.3691

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6105.6177

  28/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5762.5737

  36/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6253.8662

  44/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 6331.5239

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 6305.2158

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 6078.4048

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5939.4268

  78/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5852.3521

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5853.1665

  95/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5882.1431

 104/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5772.9927

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5721.3140

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5722.6704

 127/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5664.6401

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5690.8804

 144/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5591.9116

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5612.4351

 162/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5648.9692

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5635.1919

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5561.3022

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5526.4238

 195/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5532.7031

 203/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5533.7671

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5487.0176

 219/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5407.1953

 227/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5430.3530

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5435.5317

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5498.7500

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5513.4624

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5500.5986

 274/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5474.6274

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5430.7886

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5516.1787

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5540.6646

 310/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5532.0825

 320/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5579.4326

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5626.1421

 338/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5633.0186

 347/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5622.8120

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5607.2896

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5615.0552

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5611.9897

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5603.0928

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5597.6060

 397/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5585.7876

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5564.5708

 412/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5551.6084

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5543.8730

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5566.2358

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5561.4404

 444/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5566.6191

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5558.5815

 458/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5584.5220

 467/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5582.1797

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5564.7124

 480/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5572.9561

 489/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5561.9536

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5562.9517

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5578.7959

 512/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5555.7139

 520/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5551.5298

 528/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5565.9365

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5541.3838

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5550.6030

 551/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5555.0610

 559/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5539.1572

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5521.3975

 573/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5518.7739

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5538.6680

 589/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5527.3350

 597/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5531.3516

 604/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5532.1016

 612/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5518.3784

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5527.6558

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5505.4224

 633/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5510.8384

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5508.2114

 644/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5510.2383

 652/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5504.3467

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5500.5728

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5484.3550

 675/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5472.9990

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5465.8364

 691/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5463.0400

 699/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5458.2935

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5453.0669

 714/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5436.6738

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5450.6973

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5443.8887

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5450.9771

 745/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5444.2959

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5460.5068

 760/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5475.3755

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5480.3096

 775/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5474.9346

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5469.4453

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5472.5356

 797/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5479.7935

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5496.1714

 811/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5493.6821

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - loss: 5497.7861

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5493.4419

 837/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5494.4087

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5494.9321

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5490.5400

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5489.8091

 867/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5484.6177

 875/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5474.9751

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5464.4019

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5470.0386

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5482.7588

 912/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5491.1357

 920/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5486.6895

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5489.8105

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5498.8735

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5493.6074

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5504.2324

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 7ms/step - loss: 5508.5801

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5505.4102

 981/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5500.2808

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5506.8330

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5499.1313

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5494.6113

1014/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5492.4883

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5486.8506

1032/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5489.2695

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5476.5264

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5468.8164

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5480.2339

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5480.6733

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5470.0864

1081/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5475.9497

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 5471.5791

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5459.0894

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5456.1382

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5452.8369

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5450.0947

1133/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5451.1646

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5452.0088

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5448.4941

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5442.9341

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - loss: 5446.2783

1177/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5452.2075

1185/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5453.4482

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5457.7847

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5455.2021

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5447.9883

1220/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5453.3369

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5451.2280

1237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5441.7515

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5451.7480

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5458.3604

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5461.3979

1272/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5459.6367

1280/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5461.3608

1289/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5453.4751

1297/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5449.9922

1306/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5449.6509

1315/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5445.7212

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5445.0796

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5446.0562

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5446.7393

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5455.7983

1358/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5451.2163

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5448.2422

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5444.6196

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5439.2505

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5441.3306

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5441.9365

1412/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5440.5576

1420/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5444.5835

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5442.3027

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5440.1992

1447/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5434.8955

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5425.5889

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5426.4883

1473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5429.6294

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5429.5669

1490/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5437.1475

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5444.5469

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5445.1523

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5445.6353

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5439.0386

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5442.4077

1538/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5443.6992

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5444.7109

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5443.1870

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5447.6680

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5444.7422

1572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5442.2393

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5438.0854

1588/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5435.5737

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5443.8276

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5439.6724

1609/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5440.9609

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5456.3843

1625/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5451.5591

1633/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5449.5298

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5444.7993

1647/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5443.6982

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5437.0977

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5433.1421

1668/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5430.5396

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5435.9023

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5437.8906

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5431.4141

1699/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5428.9590

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 5424.5059

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5422.7617

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5427.9380

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5426.6860

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5422.8975

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5421.8330

1752/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5417.1641

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5417.5908

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5413.8755

1776/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5412.1465

1784/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5415.7227

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5418.8271

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5422.7520

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5421.1299

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5426.6494

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5421.5093

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5417.6450

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5413.4585

1845/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5412.0815

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5407.6450

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5410.1792

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - loss: 5404.3408

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5402.3652

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5399.4424

1893/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5394.9253

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5398.5698

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5399.9321

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5398.3047

1923/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5392.7715

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5394.6152

1939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5394.7700

1947/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5398.9507

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5394.8853

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5391.1406

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5388.8052

1975/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5387.8252

1983/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5384.8052

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5381.5947

2000/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5374.5034

2010/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5373.3091

2018/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5370.2617

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 5374.3789

2035/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5371.8696

2044/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5373.5210

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5375.9536

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5381.4556

2070/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5378.6934

2078/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5377.6973

2087/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5382.1616

2096/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5385.5674

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5381.7456

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5385.3457

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5381.6030

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5382.0186

2139/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5380.5386

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5378.9482

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5375.8975

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 5370.3452

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5369.3779

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5367.7319

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5367.4746

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5374.9326

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5370.5728

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5366.3096

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5366.6475

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5361.9546

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5363.5342

2248/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5360.3022

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5358.3154

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5357.7095

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5353.2109

2280/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5355.9409

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5358.6655

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5356.5728

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5351.6089

2314/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5349.0522

2321/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 5347.2974

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5349.3320

2336/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5342.7139

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5341.4004

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5342.2085

2360/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5341.0195

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5338.5156

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5334.7290

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5327.6758

2395/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5326.9487

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5329.2446

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5330.3271

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5326.3623

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5332.4883

2436/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5332.9458

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5327.6660

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5330.5649

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5327.8862

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5325.7559

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 5319.1284

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5317.6904

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5314.8804

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5310.0137

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5311.5127

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5314.6006

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5316.3770

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5313.5332

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5313.7925

2546/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5312.1646

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5314.1914

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5317.0771

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5317.1528

2578/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5319.6523

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5320.1489

2596/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5319.0654

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5315.7905

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5318.2417

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 5315.4829

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5313.6250

2644/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5313.7261

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5312.6812

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5312.6226

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5316.3511

2678/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5319.1401

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5318.7651

2693/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5314.4375

2701/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5318.0625

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5311.5337

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5306.6826

2728/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5303.7783

2736/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5302.6919

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5304.1523

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5303.1025

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5304.9248

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - loss: 5305.7437

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5302.1055

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5300.3052

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5301.7490

2823/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5300.7144

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5297.1553

2847/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5291.4873

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5293.5762

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5300.9839

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5300.2598

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5297.2236

2908/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5296.1245

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5295.6978

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5293.8135

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5293.7715

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5290.4248

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5291.9165

2973/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5288.9722

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5291.2515

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5292.0981

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5293.5293

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5290.3228

3019/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5287.8774

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5287.3882

3036/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5287.1279

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5284.9536

3055/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5284.7368

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5285.6216

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5284.7104

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5284.0264

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5283.5649

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5283.0078

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5282.6294

3116/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5284.3013

3125/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5282.3311

3134/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5278.4634

3142/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5275.6655

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5274.0693

3159/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5272.9180

3168/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5270.6772

3177/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5269.6240

3185/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5269.3096

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5269.7988

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5269.7651

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5267.4795

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5266.3481

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5268.6162

3239/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5268.0815

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5268.8154

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5266.6807

3265/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5266.7114

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5266.7915

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5267.5127

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5264.5352

3299/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5263.6777

3307/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5263.5283

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5265.1602

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5263.1421

3334/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5265.0972

3342/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5262.3198

3351/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5265.0186

3359/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5265.3442

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5267.5293

3376/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5266.4097

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5267.4600

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5267.7769

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5269.2573

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5270.8311

3418/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5270.7905

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5269.7739

3436/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5268.0000

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5267.0352

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5264.3994

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5265.4829

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5264.7515

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5265.9219

3494/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5262.3442

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5261.3013

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5257.0513

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5254.9614

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5256.3594

3544/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5254.9741

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5254.8423

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5254.7007

3571/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5254.5967

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5253.7744

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5251.8989

3595/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5250.2197

3603/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5252.3101

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5250.3867

3618/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5250.1016

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5252.2231

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5251.7129

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5251.0000

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5249.5020

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5246.9937

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5247.6387

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5244.2754

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5241.2197

3693/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5240.2866

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 29s 8ms/step - loss: 5242.8110 - val_loss: 2191.6746

Epoch 11/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:11 52ms/step - loss: 4643.6035

  11/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 6031.9736

  20/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5590.4150

  29/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5233.8335

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4883.0347

  46/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4843.0308

  54/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4954.7993

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5007.7598

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5001.4629

  80/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4898.0215

  90/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4796.2432

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4934.2051

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5045.1396

 114/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4992.8262

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5030.5581

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5031.3081

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4975.1729

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4892.1401

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4912.8950

 166/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4918.3911

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4960.6333

 184/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5022.6675

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5014.3530

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4978.8071

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4958.3232

 219/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4924.4268

 229/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4870.5259

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4857.2710

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4893.0054

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4917.0923

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4928.1260

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4915.8262

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4901.0293

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4943.7368

 297/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4935.9302

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4942.6743

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4940.4653

 323/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4917.0786

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4929.1528

 340/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4924.2002

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4917.0884

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4912.0454

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4946.8833

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4961.2183

 384/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4932.9404

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4935.6338

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4930.5312

 409/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4907.8726

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4928.4980

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4951.2905

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4960.2402

 443/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4959.2422

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4948.9214

 463/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4945.2417

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4938.5986

 483/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4951.5664

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4948.4790

 503/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4936.2188

 512/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4932.6426

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4955.3765

 532/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4960.0884

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4948.0874

 547/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4943.4741

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4930.6982

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4936.9556

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4933.2495

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4925.4180

 592/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4907.7832

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4906.6934

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4900.1104

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4903.1084

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4919.1079

 635/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4933.4990

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4948.6260

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4946.1445

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4967.4590

 669/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4971.3613

 677/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4982.9004

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4979.9663

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4961.8511

 701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4966.5591

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4976.0684

 718/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4983.3242

 726/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4984.0742

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4993.6846

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4985.6543

 754/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5004.3394

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4993.7080

 772/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4984.2300

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4992.5693

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4999.6851

 798/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4996.6714

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5000.2505

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5004.4404

 825/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5011.8574

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5006.0181

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4998.7095

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5001.8066

 858/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4992.6616

 867/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4989.5151

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4978.5947

 885/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4964.2524

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4961.1846

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4955.0234

 911/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4959.4971

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4952.9971

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4970.6670

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4967.5254

 947/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4960.7788

 955/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4969.3623

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4956.7388

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4961.1523

 983/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4952.3691

 991/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4958.2456

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4956.9619

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4964.7549

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4961.0923

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4957.6558

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4954.8057

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4945.9194

1055/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4946.5718

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4945.8691

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4951.0967

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4947.9189

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4950.8213

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4948.0557

1113/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4946.0967

1123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4943.1084

1131/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4941.9272

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4946.3872

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4943.0962

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4949.7695

1163/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4940.0396

1172/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4937.4355

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4940.5479

1190/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4936.0273

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4937.2222

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4931.7266

1216/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4940.5640

1225/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4941.1909

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4936.1055

1243/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4954.2607

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4946.9702

1261/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4941.2852

1267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4937.9932

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4937.5991

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4939.2969

1294/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4934.6543

1302/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4933.6460

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4931.3291

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4934.6006

1327/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4936.3472

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4941.7363

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4936.5649

1351/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4947.3726

1359/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4951.5181

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4949.7627

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4968.9380

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4970.8296

1392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4974.7261

1401/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4974.7100

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4971.1069

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4980.8364

1427/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4984.0205

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4984.8018

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4991.8735

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4996.8467

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4999.1475

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5001.2417

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5003.3008

1486/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5005.3003

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5004.9072

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5008.4995

1511/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5015.7383

1520/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5018.6885

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5022.9912

1536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5028.4473

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5028.6606

1554/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5029.9009

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5033.9561

1571/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5039.6992

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5041.9224

1588/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5044.4634

1596/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5046.1533

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5041.2656

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5039.0415

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5036.9028

1633/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5031.1934

1643/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5028.2104

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5026.4590

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5029.1377

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5030.8760

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5030.3286

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5031.0664

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5030.4951

1711/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5035.8423

1721/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5038.4795

1729/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5033.8223

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5038.3027

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5037.2861

1755/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5050.5210

1764/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5055.2412

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5059.7866

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5056.0220

1791/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5058.0269

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5062.6855

1808/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5067.2808

1817/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5066.4658

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5064.1489

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5062.2598

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5060.9141

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5066.9976

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5067.1387

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5063.4736

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5060.6147

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5064.9111

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5070.1680

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5067.1279

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5069.8823

1924/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5072.3223

1933/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.7549

1942/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5070.6836

1951/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.1484

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5067.5908

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5063.4360

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5062.7104

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5060.5645

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5058.2720

2002/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5060.9263

2011/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5064.5918

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5065.9390

2028/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5069.2456

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5073.7666

2044/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5075.6528

2053/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5073.7407

2062/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5077.1313

2070/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5076.4048

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5076.8662

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5084.9829

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5089.6841

2106/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5089.8003

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5087.9116

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5085.8911

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5086.1226

2140/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5082.1582

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5087.8130

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5084.4619

2168/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5082.4893

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5085.8560

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5089.8057

2192/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5087.3779

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5087.2852

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5089.8071

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5091.1211

2230/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5089.2710

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5091.9077

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5087.0347

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5090.5435

2267/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5093.3877

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5098.1274

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5100.7622

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5098.2637

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5096.5728

2302/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5096.9561

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5096.9805

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5095.5488

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5096.7378

2336/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5093.2715

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5087.9077

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5086.6470

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5084.4912

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5082.9551

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.5786

2386/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5083.8799

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5082.3159

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5086.7769

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5087.7617

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5086.5688

2424/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5086.5239

2432/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5082.4268

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5083.4805

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5082.9199

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.5991

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.7764

2463/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5077.8853

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5076.3037

2476/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5075.3145

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5073.9272

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5078.0137

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.5215

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5080.5190

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5082.2324

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.0728

2519/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.6538

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5078.8354

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5078.2046

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.1079

2546/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.1118

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.2227

2558/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.0444

2565/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.1865

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5083.2466

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5084.8350

2588/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5085.1030

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5085.9634

2602/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5086.0557

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5087.9468

2617/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5084.4106

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5084.8032

2631/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5087.4302

2639/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5085.7212

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5083.2397

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5088.8657

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5089.7603

2668/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5087.7671

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5088.5923

2683/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5085.8345

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5083.6377

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5080.6509

2708/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5075.2422

2716/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5070.4624

2724/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5072.2539

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.3481

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.2417

2748/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5069.6499

2756/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5074.2959

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5072.7837

2773/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.7036

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5074.6528

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5073.0713

2801/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5073.7192

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5077.1416

2822/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5079.6860

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5079.3926

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5079.4839

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5079.0420

2858/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5080.9170

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5080.3354

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5080.0952

2886/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5076.9219

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5074.6514

2904/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5074.9189

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5076.4653

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5078.3164

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5080.1470

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5079.4507

2948/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5081.0679

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5081.3721

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5077.7651

2973/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5075.2578

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5074.9556

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5076.3828

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5078.1846

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5077.6519

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5078.6055

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5078.3594

3036/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5080.6851

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5084.1318

3054/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5083.3511

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5083.7202

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5081.7603

3080/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5081.9062

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5078.2593

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5076.5000

3106/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5074.5405

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5078.4609

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.4995

3132/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.8467

3141/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.2251

3150/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.1821

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.8042

3162/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5085.3389

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5084.4351

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5083.5493

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5082.4951

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5081.1084

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5079.6865

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5077.6133

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5077.1133

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5077.3423

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5078.9521

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5078.2539

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5080.5327

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5081.0811

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5081.3237

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5079.3086

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5077.9917

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5078.0405

3272/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5076.7847

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5078.1816

3286/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5080.4170

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5079.4155

3299/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5079.3408

3306/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5083.1836

3312/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5082.3618

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5083.9321

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5086.5869

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5086.6167

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5088.2681

3343/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5086.4014

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5087.1982

3354/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5085.3994

3362/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5085.2969

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5088.2314

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5088.4790

3383/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5086.5693

3391/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5083.8794

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.5942

3406/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5086.6299

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5086.2930

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5088.7676

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5088.2290

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5087.8896

3444/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.9980

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.9150

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5088.7754

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5086.0483

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5084.7705

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5082.4761

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5081.9131

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5083.0762

3502/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.2798

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5084.4243

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.3076

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.9673

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5084.5557

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.6455

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5085.8730

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5087.5283

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5088.9102

3564/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5087.4961

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5086.3813

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5086.0005

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5086.3452

3591/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5090.4214

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5092.8242

3604/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5095.9888

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5097.3398

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5100.8311

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5099.6675

3630/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5103.5444

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5107.6899

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5109.9067

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5108.8037

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5107.9497

3665/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5106.1899

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5107.1372

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5105.3374

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5104.6206

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5102.6763

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5100.2031

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 27s 7ms/step - loss: 5101.0059 - val_loss: 213.8428

Epoch 12/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:48 62ms/step - loss: 6719.4688

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4318.1348

  18/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5029.2905

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4867.9639

  35/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5274.1045

  44/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5122.4272

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5085.5034

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5013.4785

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5018.9551

  78/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4977.6650

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5034.9912

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5051.9160

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5029.0059

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5037.0454

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4997.8120

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4936.0688

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5004.1401

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5019.1255

 157/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5068.7573

 166/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5087.5103

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5083.8501

 183/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5052.6650

 192/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4993.4844

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4993.0161

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5017.5669

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4997.8110

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5011.7817

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5032.3716

 244/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5015.5708

 252/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5040.7837

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5020.3315

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5031.5562

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5058.5693

 286/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5044.8589

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5052.2231

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5049.6270

 312/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5053.9268

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5025.4404

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5034.5366

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5031.0039

 350/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5000.0879

 359/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4989.5244

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4996.8706

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4988.4863

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4982.9531

 395/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4964.3501

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4964.9902

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4966.3359

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4962.0542

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4940.2056

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4945.6689

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4940.0127

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4931.3677

 469/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4914.9297

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4922.1953

 486/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4931.2974

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4938.2710

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4942.1963

 510/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4929.3335

 519/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4926.0605

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4960.4639

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4971.6123

 542/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4990.7671

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4993.7314

 559/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5009.2720

 568/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5004.8989

 576/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5013.7646

 584/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5007.2651

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5007.1592

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5006.4111

 606/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5011.2300

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5024.0288

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5019.4585

 629/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5043.3130

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5039.5562

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5051.8145

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5053.4131

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5049.6943

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5053.0269

 676/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5038.5142

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5041.3208

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5034.4395

 701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5024.0879

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5008.2700

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5005.1689

 725/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5003.1787

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5011.2993

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5009.5732

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5019.1514

 759/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5003.4048

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5011.1738

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4998.7510

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4986.9111

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4996.0591

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5003.1436

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5021.4180

 817/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5016.9556

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5004.8252

 834/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5012.1343

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5003.2651

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5001.3452

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4996.3560

 868/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5001.9170

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4994.4526

 885/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4998.6421

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4991.7534

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4986.1763

 910/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4979.7422

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4976.9854

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4975.9834

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4980.3579

 947/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4979.8657

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4975.5063

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4981.4878

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4984.1895

 983/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5004.8506

 993/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4996.9658

1003/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4993.6753

1012/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5000.4585

1020/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4989.6890

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4997.9023

1038/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5004.7852

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5000.4517

1054/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4997.6299

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4994.1353

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4996.2900

1077/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4989.4727

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4988.3579

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4989.0815

1101/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5001.6826

1110/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5002.0791

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5004.5498

1126/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5004.6523

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4995.0688

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4999.9019

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5008.2778

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5005.9878

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5005.9873

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5011.4087

1184/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5014.3262

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5022.8696

1200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5023.1143

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5027.8667

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5022.9927

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5013.3149

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5021.9414

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5026.0728

1249/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5034.4092

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5039.6494

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5037.0386

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5040.8369

1282/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5044.1992

1291/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5044.5381

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5048.6343

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5047.4561

1315/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5052.8291

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5049.3691

1331/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5058.8760

1339/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5056.2544

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5056.8794

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5051.7266

1366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5046.8096

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5052.0859

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5057.6094

1392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5052.5952

1401/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5052.2485

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5053.9854

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5054.4492

1428/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5060.0127

1437/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5064.5522

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5059.3765

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5057.9658

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5062.5059

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5071.5347

1480/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5077.0518

1489/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5082.7266

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5088.5435

1508/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5090.8975

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5082.8960

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5078.5669

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5083.8794

1536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5089.5981

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5090.2651

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5098.1206

1563/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5093.3218

1573/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5097.0830

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5089.5459

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5089.6865

1601/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5087.6260

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5088.3779

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5083.4683

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5090.4834

1646/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5090.9136

1657/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5086.4038

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5083.8530

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5084.9204

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5082.8975

1702/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5078.0532

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5070.2739

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5070.8125

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5072.9146

1748/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5073.7510

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5076.4341

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5078.8608

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5084.4102

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5081.0220

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5080.7593

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5077.9512

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5073.0845

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5067.4258

1850/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5076.3193

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5074.7842

1875/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5070.1758

1886/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5077.8823

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5077.7588

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5076.4580

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5078.6494

1928/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5073.4663

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.2114

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5073.1128

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.3071

1963/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.9727

1972/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5073.6968

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.3218

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5068.6421

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5072.3652

2007/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5072.9810

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.6846

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5071.5693

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5073.5625

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5070.7441

2051/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5071.0562

2060/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5071.4355

2068/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5068.2256

2076/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5069.6499

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5071.3237

2094/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5069.6274

2102/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5069.8008

2111/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5069.1587

2120/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5067.2427

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5070.9624

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5069.5562

2147/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5063.9932

2156/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5065.9268

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5066.6689

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5066.9106

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5067.6069

2192/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5067.6338

2200/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5065.1914

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5066.8091

2217/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5068.4058

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5064.8169

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5068.7891

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5070.3755

2252/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5066.8984

2261/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.7388

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5067.3926

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5067.7607

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5067.4795

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.9873

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5062.8442

2312/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5061.6182

2321/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.6323

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.6294

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.7729

2348/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5065.7456

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.0391

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5063.3145

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5064.9229

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5061.4648

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5060.0942

2400/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5062.4365

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5063.1216

2419/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5064.3867

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5064.8809

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5063.2051

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5062.1040

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5059.8569

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5057.3916

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5056.5703

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5054.0132

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5053.8301

2507/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5052.2944

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5049.2310

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5049.6094

2534/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5048.5190

2543/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5046.7803

2552/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5044.7544

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5040.1436

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5036.6616

2576/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5035.5415

2585/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.1367

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5038.3428

2602/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5037.6924

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5036.3848

2620/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5036.0869

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5037.3262

2637/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5038.6538

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.7534

2655/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5034.7803

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5037.0366

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.0049

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5041.1475

2689/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5045.9966

2698/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5044.2329

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5042.6880

2716/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5040.9302

2725/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5040.6069

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5042.7632

2742/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5039.0796

2751/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5038.0674

2760/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5037.8267

2769/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5040.1069

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5040.5068

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5037.9590

2795/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5041.0854

2803/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5040.2969

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5039.1450

2821/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5039.8960

2829/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5038.6279

2837/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5036.8740

2846/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5038.6025

2855/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5039.4521

2864/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5037.3608

2872/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.3794

2880/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.1060

2888/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.3818

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5038.1216

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5038.6206

2914/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5040.0879

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5039.6343

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.0791

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.2778

2948/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5039.7744

2957/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.9985

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5038.1104

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5036.2520

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5035.1221

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5038.6353

3003/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5041.0166

3013/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5042.8906

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5038.6533

3033/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5037.8545

3043/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5037.1284

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5038.7280

3062/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5036.0474

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5037.0957

3082/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5034.9575

3091/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5039.6123

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5039.9077

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5040.0625

3117/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5041.2490

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5040.7061

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5040.2295

3142/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5038.6543

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5038.4175

3159/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5036.2637

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5038.8467

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5044.6851

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5048.2578

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5050.4980

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5050.7466

3211/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5048.8755

3220/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5049.7588

3229/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5046.5244

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5044.4009

3246/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5042.4912

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5043.8691

3264/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5043.3579

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5045.1279

3282/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5045.6411

3291/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5046.2686

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5045.9844

3306/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5047.7178

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5048.6118

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5052.2783

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5052.2983

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5054.8560

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5054.0933

3358/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5057.0337

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5057.7158

3376/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5056.4043

3385/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5057.8525

3394/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5056.2349

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5058.5073

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5057.2397

3419/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5063.1724

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5063.3447

3436/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5063.6885

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5065.2739

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5069.6538

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5069.4556

3472/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5067.1348

3481/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5065.7173

3490/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5065.8564

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5067.5366

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5066.6826

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5064.1665

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5061.7954

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5059.3682

3539/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.4561

3548/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5057.1294

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5056.7837

3564/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.1318

3568/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.3193

3576/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5060.9736

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5060.1416

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.5361

3603/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5057.7744

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5057.0142

3621/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.8462

3631/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5056.3662

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5058.0986

3650/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5057.7686

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5060.7339

3671/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5060.0278

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5056.9653

3693/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5057.7935

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5057.9946 - val_loss: 236.5281

Epoch 13/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:25 56ms/step - loss: 2522.6731

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4677.3423

  20/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4477.8428

  30/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 4721.0811

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4744.3345

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4745.4790

  59/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4638.9150

  69/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4678.6133

  79/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4565.6851

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4516.7720

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4420.1157

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4452.0469

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4441.0952

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4545.0317

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4644.3125

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4649.3145

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4684.6577

 155/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4754.5117

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4804.8774

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4792.3042

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4806.8481

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4796.0894

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4776.6904

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4776.0288

 214/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4819.2432

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4815.4478

 232/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4788.8291

 241/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4778.2939

 250/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4804.4390

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4828.7769

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4848.2129

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4876.6675

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4887.5352

 296/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4881.8418

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4846.7500

 311/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4846.4370

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4821.4502

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4847.6201

 334/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4853.2007

 343/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4848.7759

 352/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4869.4697

 360/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4878.8315

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4893.0044

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4906.8516

 385/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4882.9873

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4887.2036

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4888.4966

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4884.0771

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4869.5029

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4866.3906

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4846.5732

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4820.6821

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4817.9458

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4812.8311

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4793.6519

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4788.6748

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4797.8770

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4787.9731

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4790.9189

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4801.2139

 518/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4797.4673

 526/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4840.1074

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4837.5542

 544/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4845.7427

 551/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4846.1523

 559/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4856.3735

 568/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4869.2163

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4845.1743

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4850.9497

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4842.5835

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4841.0908

 617/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4845.9849

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4865.9097

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4864.8477

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4850.9595

 654/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4849.7598

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4853.8467

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4854.4126

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4866.7212

 692/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4868.5664

 701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4861.0972

 710/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4847.2021

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4844.5454

 727/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4842.5679

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4831.0210

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4830.4009

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4816.9248

 759/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4823.5010

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4838.3208

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4854.5117

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4863.7617

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4862.0859

 799/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4854.2173

 808/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4850.6299

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4852.3281

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4853.2310

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4850.5586

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4846.7910

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4847.7568

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4840.6172

 868/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4838.5410

 877/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4847.1064

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4844.5493

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4873.0068

 905/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4874.2026

 914/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4865.5938

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4870.3901

 930/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4887.9775

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4885.6553

 947/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4889.8252

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4890.3237

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4884.5469

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4880.2354

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4882.3320

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4889.3701

 997/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4884.1323

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4890.1724

1015/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4892.2812

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4879.0103

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4888.5854

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4882.6699

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4894.4287

1054/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4898.5669

1062/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4907.8638

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4919.8154

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4915.2798

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4917.4946

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4914.1792

1099/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4917.2485

1106/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4912.4990

1114/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4908.2827

1123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4912.2734

1131/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4911.1230

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4909.7183

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4915.6738

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4912.4062

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4915.3696

1173/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4918.6123

1183/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4915.3521

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4915.2422

1201/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4921.5796

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4926.1035

1219/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4929.7422

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4939.4341

1236/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4942.5342

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4944.4946

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4943.3086

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4941.8721

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4938.5571

1271/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4939.7515

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4943.2197

1284/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4952.6909

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4955.5503

1296/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4954.6514

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4953.2368

1308/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4955.4854

1314/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4951.5483

1322/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4951.9932

1329/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4952.7021

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4958.4419

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4958.9111

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4958.6445

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4958.4692

1362/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4959.6934

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4960.0327

1377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4963.9238

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4964.8125

1390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4963.2041

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4968.8389

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4968.0195

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4972.1167

1415/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4972.9619

1423/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4982.0356

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4981.9277

1437/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4988.3110

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4984.4409

1451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4983.9395

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4984.6465

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4985.3623

1475/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4984.2642

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4977.9736

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4968.5308

1500/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4967.9082

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4969.8267

1515/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4972.4253

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 4976.9282

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - loss: 4970.6353

1537/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - loss: 4971.2822

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - loss: 4978.7168

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - loss: 4979.9253

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4973.6416

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4971.4448

1575/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4970.6870

1584/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4966.4282

1593/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4967.9707

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4972.4175

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4976.6572

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4977.8218

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4979.2026

1636/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4978.4746

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4979.5107

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4987.0088

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4981.3657

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4985.0322

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - loss: 4984.7783

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4984.8135

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 4990.7109

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4995.1675

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4999.0483

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4998.9292

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4997.8979

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5003.8882

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4998.3340

1759/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4998.2720

1769/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4997.1357

1779/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 4992.8716

1788/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5000.0010

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5001.3379

1808/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5000.0532

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5005.6816

1828/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5012.6689

1839/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5005.8687

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5004.2495

1858/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5003.4351

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5000.0054

1876/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5000.2153

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5011.8481

1893/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5011.1719

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5016.2969

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5025.9912

1918/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5026.9468

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5028.5649

1936/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5024.4922

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5022.1548

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5026.1899

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5028.0596

1970/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5023.5884

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5021.4170

1988/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5018.0645

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5019.9551

2006/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5018.2646

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5024.2808

2023/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5024.4507

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5031.4438

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5034.1558

2051/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5027.9854

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5031.7412

2067/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5034.1567

2076/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5038.6079

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5035.8037

2094/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5041.1157

2103/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5042.4331

2111/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5043.2070

2119/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5044.4043

2128/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5047.6895

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5041.9541

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5038.7617

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5036.6040

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5038.5654

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5038.2778

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5041.7920

2187/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5037.6191

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5033.7080

2204/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5031.7627

2212/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5034.0215

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5035.9517

2229/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5040.4331

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5043.3364

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5041.6055

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5053.7720

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5054.8354

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5051.9146

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5058.5898

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5061.3340

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5064.3989

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5072.4160

2312/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5072.7085

2321/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5074.5376

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5074.1689

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5075.6304

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5075.6377

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5076.2441

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5078.6548

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5075.9634

2380/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5080.2163

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5077.3447

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5076.8193

2408/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5079.4507

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.5010

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5083.6396

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5080.3359

2447/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5084.1675

2456/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5081.9780

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.0811

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5079.6260

2480/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5075.0449

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.0659

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5072.6768

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5076.7104

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.8984

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.3472

2528/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5078.0366

2536/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5077.2544

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.5942

2553/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5077.4907

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.8511

2569/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5073.6064

2577/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.3223

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5074.3701

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5069.8916

2600/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5067.5298

2608/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5063.8462

2613/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5061.5444

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5063.7749

2629/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5063.2412

2638/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5066.5405

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5067.0874

2655/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5068.9971

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.4092

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5070.0430

2679/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.6680

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5070.2451

2695/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5068.3462

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5070.5869

2712/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5066.7168

2720/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5068.4980

2728/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5068.4844

2736/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.9321

2744/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5072.4414

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5069.9561

2760/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5065.5469

2768/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5065.4819

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5064.1948

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5063.3306

2791/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5068.4980

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5064.2056

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5069.0986

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5070.4131

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5068.2500

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.2163

2840/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.0259

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.9438

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.2441

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5069.9492

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5069.1372

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5071.2778

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5069.7314

2898/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5068.1011

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5065.9692

2914/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5065.9355

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5065.5771

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5069.2734

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5068.7021

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5070.1016

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5068.3154

2968/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5069.0288

2977/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5072.3774

2986/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5069.9644

2995/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5068.7617

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5066.7905

3012/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5065.2568

3021/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5065.3770

3029/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5068.6343

3037/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5071.7383

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5072.8081

3053/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5074.6592

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5072.3848

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5073.4507

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5070.6255

3082/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5069.9595

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5072.4727

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5073.0142

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5078.5532

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5084.6587

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5089.0259

3129/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5089.1260

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5091.9224

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5094.9341

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5092.6777

3162/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5092.8438

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5096.0596

3178/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5093.9419

3187/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5094.0576

3196/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5092.9595

3204/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5093.4385

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5094.4517

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5098.2158

3228/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5099.3857

3237/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5100.3721

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.2788

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.8320

3263/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5110.1729

3272/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5109.8916

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.8193

3288/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.7090

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5104.4600

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.7070

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.1919

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5106.7935

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5105.2529

3339/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5103.3281

3347/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5101.9360

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5099.9160

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5100.2808

3370/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5096.0942

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5094.8379

3387/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5094.1567

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5095.5439

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5096.7007

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5094.3672

3414/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5097.7168

3423/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5097.8530

3431/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5096.7939

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5096.8145

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5097.6855

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5097.2720

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5097.7485

3470/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5098.1089

3478/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5100.4590

3486/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5101.9771

3494/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5105.0913

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5103.3564

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5102.2231

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5100.8730

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5101.5903

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5103.1294

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5104.0190

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.2300

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.5708

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5111.2559

3573/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5112.4888

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5109.7085

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.4268

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5110.5576

3608/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5111.0679

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5109.7222

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.8179

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.6167

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5110.6875

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5109.3735

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5109.9785

3666/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5113.8110

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5115.1831

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5116.2783

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5119.1235

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5119.3398

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 27s 7ms/step - loss: 5119.1885 - val_loss: 132.9267

Epoch 14/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:09 51ms/step - loss: 4532.4556

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5553.7993

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5703.2197

  29/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5482.2837

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5482.1660

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 5294.0952

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5244.1978

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5119.3628

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5071.3062

  95/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5082.8384

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5156.9790

 116/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5120.5869

 127/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5107.0342

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5010.2227

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5107.7129

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5123.7930

 170/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5104.7466

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5072.5508

 190/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5082.5518

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5087.7515

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5044.4653

 225/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5087.7544

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5103.8833

 249/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5062.9243

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4979.3530

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4989.1616

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4985.6152

 288/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4974.5244

 297/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4955.9189

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4966.1724

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4947.9170

 322/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4943.6606

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4973.2817

 340/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4968.2778

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4953.8555

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4961.3887

 367/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4946.1099

 376/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4954.6597

 385/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4957.5562

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4931.2271

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4947.7534

 412/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4936.4438

 421/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4944.9873

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4929.8340

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4941.5415

 446/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4942.6909

 455/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4920.1318

 464/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4939.5776

 472/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4925.4150

 481/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4957.5596

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4935.1758

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4943.0205

 508/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4935.7334

 517/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4938.0337

 526/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4989.6445

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5021.0728

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5021.9980

 551/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5025.3462

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5023.3916

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5012.6123

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4996.5767

 587/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4982.5303

 595/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4982.1826

 604/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4966.1162

 613/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4970.7637

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4980.1133

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4979.7222

 640/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 4970.4150

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4960.5996

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4974.3057

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4973.2144

 676/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4963.6763

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4965.9160

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4970.3135

 703/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4955.9077

 712/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4961.9453

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4975.2168

 727/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4986.1772

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4984.8735

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4983.5098

 753/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4978.5688

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4986.8306

 773/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4999.4111

 783/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4988.6309

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4984.6113

 803/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4979.2622

 811/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4971.1514

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4968.5103

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4961.9507

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4964.3081

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4970.5796

 857/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 4989.7217

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4993.2739

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4996.4111

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5001.0303

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4998.5083

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4983.7388

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4990.4595

 912/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4989.7437

 920/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4991.1035

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4983.1553

 934/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4980.2988

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4974.4873

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4965.6343

 959/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4959.5444

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4964.9214

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4958.6465

 985/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4974.8491

 994/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4981.6865

1003/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4985.6709

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4980.3467

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4967.9224

1028/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4971.3667

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4974.7632

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4972.3369

1055/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4979.8799

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4984.9268

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4979.0781

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4982.2583

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4984.4531

1097/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4989.2476

1105/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4985.4868

1114/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4990.9453

1121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4990.5352

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 4996.9570

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5003.7588

1145/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5001.3242

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5003.2466

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5003.0571

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5010.9380

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5016.6162

1183/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5021.6401

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5018.9248

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5026.7163

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5027.9751

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5032.6465

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5024.1885

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5018.0762

1242/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5008.1577

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5007.5664

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5005.3374

1267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5008.5073

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5018.9268

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5021.3184

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5023.3862

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5024.7456

1308/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5020.8408

1318/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5016.2476

1326/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5020.0532

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5032.1548

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5028.1211

1351/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5033.1431

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5029.1328

1368/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5028.9443

1377/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5021.5430

1386/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5022.9629

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5017.6631

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5024.8223

1416/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5025.9810

1426/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5026.2764

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5029.7031

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5035.5132

1457/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5038.6147

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5044.8130

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5042.9004

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5033.1157

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5030.9126

1515/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5027.5044

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5023.8965

1539/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5021.7378

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5018.4062

1563/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5018.8042

1576/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5013.2451

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5011.8994

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5007.7012

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5015.9033

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5022.1431

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5020.7041

1646/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5016.4805

1658/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5014.3398

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5013.2456

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5010.3232

1694/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5016.4355

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5020.2681

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5029.5537

1727/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5031.0303

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5032.1099

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5035.4805

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5037.3237

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5033.8047

1785/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5034.0815

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5032.8325

1803/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5033.0161

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5028.4067

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5032.5576

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5032.0122

1837/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5032.7437

1846/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5031.6909

1855/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5027.9648

1864/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5025.0684

1874/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5024.6860

1882/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5026.6094

1890/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5027.5845

1899/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5031.3711

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5029.6113

1917/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5035.5361

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5030.7271

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5029.0273

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5027.0137

1951/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5026.9707

1960/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5022.9595

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5022.1494

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5022.9868

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5030.2124

1994/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5026.9707

2003/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5029.7344

2011/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5027.9463

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5025.2451

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5027.0537

2035/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5028.5049

2043/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5027.5713

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5025.7261

2062/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5022.6792

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5023.8862

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5026.0947

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5026.6470

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5030.9980

2106/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5030.4302

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5030.1909

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5028.7593

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5027.3794

2140/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5029.0952

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5025.6733

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5027.5776

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5028.9146

2175/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5028.5122

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5025.0693

2192/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5024.2686

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5023.9683

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5023.6909

2218/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5024.6089

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5021.3301

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5021.8394

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5018.7549

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5018.7427

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5015.5088

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5014.8916

2277/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5020.7236

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5018.0708

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5010.4365

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5012.1802

2313/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5015.0840

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5014.3276

2332/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5017.5703

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5015.0024

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5012.1812

2360/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5014.2183

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5014.5903

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5016.5962

2386/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5018.3643

2394/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5025.6060

2402/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5028.8848

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5030.9844

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5032.8340

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5031.2866

2434/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5029.7349

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5029.0806

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5035.0034

2456/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5035.8760

2464/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5034.7803

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5032.4282

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5036.0693

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.7988

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5035.6782

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5033.9775

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5038.5596

2523/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5035.5483

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5035.0352

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5033.6191

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5036.2017

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.4614

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5042.3213

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5044.4736

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5042.6670

2590/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.1226

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5039.4668

2608/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5038.9287

2617/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5041.5278

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5042.4736

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5041.6387

2644/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5046.3618

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5048.6304

2660/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5048.8696

2668/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5049.3560

2677/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5050.8320

2686/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5053.2246

2694/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5048.9478

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5046.4229

2712/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5047.1987

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5044.5859

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5047.7783

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5045.8247

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5049.2476

2756/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5049.2280

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5046.7109

2772/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5046.3477

2780/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5045.1411

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5047.9829

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5045.7061

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5044.6611

2815/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5046.4854

2823/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5042.8916

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5042.2280

2841/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5039.1138

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5036.0010

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.9756

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5032.9990

2879/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5034.0713

2889/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5035.7368

2899/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5037.3804

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5036.5508

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5031.4771

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5030.3813

2937/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5031.7554

2947/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5033.8027

2955/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5033.3457

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5030.6738

2971/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5031.7739

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5031.1528

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5029.3555

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5030.2622

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5032.5503

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5034.2290

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5034.2686

3034/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5036.8813

3043/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5039.6392

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5041.1597

3061/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5041.7056

3069/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5041.7368

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5040.0791

3086/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5044.9692

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5044.1675

3104/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5048.2397

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5046.2227

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5047.8862

3129/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5049.2515

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5048.0972

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5051.6870

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5056.1826

3164/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5056.2915

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5057.1558

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5057.6973

3189/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5058.8809

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5057.1899

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5055.4131

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5054.1670

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5052.8096

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5054.9585

3240/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5060.3862

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5063.0352

3258/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5060.5962

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5060.6099

3275/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5057.8706

3283/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5055.9722

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5055.4224

3299/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5052.5679

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5051.3877

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5049.7305

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5051.0786

3334/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5050.9805

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5050.1675

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5049.7065

3358/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5048.5273

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5047.4473

3376/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5046.6465

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5046.2964

3395/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5043.6460

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5043.1973

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5041.7993

3421/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5041.4038

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5041.8335

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5039.9985

3449/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5041.4834

3459/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5038.8193

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5039.9399

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5039.5205

3488/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5037.9585

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5043.0483

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5045.9966

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5047.0903

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5048.8320

3536/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5046.6880

3545/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5046.1904

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5043.7808

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.9629

3572/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5041.0000

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5041.7490

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5042.4805

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.4648

3607/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.4307

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5038.7666

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5038.8091

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.7871

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5039.4575

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5037.9771

3658/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5034.9272

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5036.3501

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5036.8843

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.7178

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5040.0723

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5039.2710

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 27s 7ms/step - loss: 5040.0801 - val_loss: 176.0144

Epoch 15/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:12 52ms/step - loss: 2942.7905

  11/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4984.6919

  20/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5092.6802

  29/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4721.3691

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5022.8823

  46/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4986.2598

  55/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5044.7280

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5029.8115

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4944.3647

  83/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4848.5288

  92/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4839.5049

 102/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4806.8936

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4796.6055

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4865.1416

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4887.2939

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4892.7441

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5055.1494

 156/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5019.0454

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5040.5122

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5059.9688

 181/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5048.2759

 188/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5036.9526

 196/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5071.4209

 205/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5063.4961

 214/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5039.7197

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5062.1660

 231/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5041.6948

 239/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5012.3188

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5018.1636

 255/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5033.4858

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5027.6226

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5021.7339

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5050.7124

 289/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5042.1060

 298/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5038.6035

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5029.6685

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4999.0967

 324/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4976.5830

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5000.4258

 340/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5023.7676

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5018.8057

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5013.6128

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5006.6519

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4971.6226

 384/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4945.9355

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4974.6934

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4994.6431

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4975.4409

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4960.3516

 428/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4958.0308

 437/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4942.8184

 446/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4932.4697

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4930.9336

 466/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4917.6724

 475/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4919.7563

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4957.9561

 495/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4965.0278

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4989.4648

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5004.9238

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5007.1577

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5026.8613

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5018.4424

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5061.3389

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5094.4448

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5100.5903

 575/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5124.8647

 584/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5151.4624

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5140.1387

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5123.1064

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5116.2290

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5113.3271

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5107.6377

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5093.5391

 647/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5076.5698

 656/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5076.0864

 665/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5072.6831

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5063.5942

 682/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5080.3145

 691/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5085.6191

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5076.2212

 707/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5082.5205

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5072.5352

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5067.9321

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5069.0469

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.9834

 751/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5054.4043

 760/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5044.9473

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5042.3105

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5042.2275

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5048.4507

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5061.2544

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.0879

 811/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5047.9912

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5037.6064

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5042.8901

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5045.6611

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5047.8418

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5044.3267

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5033.5312

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5042.2637

 881/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5044.0000

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5040.5293

 898/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5035.2231

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5036.8828

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5047.8853

 923/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5051.6631

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5043.7622

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5037.2734

 948/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5035.9028

 957/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5038.3501

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5037.8745

 975/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5042.0615

 985/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5044.9399

 994/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5061.2070

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5055.4717

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5052.6294

1018/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5053.6519

1026/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5053.7231

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5054.2041

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5052.8384

1055/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5054.1924

1065/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5053.6167

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5049.3643

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5057.4712

1094/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5052.0298

1104/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5066.0020

1114/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5072.4272

1125/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5085.7749

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5085.1523

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5082.5283

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5084.6860

1172/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5073.6152

1183/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5076.6953

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5085.8052

1201/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5080.8623

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5077.6904

1219/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5074.4922

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5078.6904

1236/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5087.9224

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5088.8892

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5084.6987

1262/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5083.5122

1270/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5089.5073

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5085.1763

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5095.6362

1295/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5095.3638

1304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5095.9824

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5096.4312

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5098.9819

1329/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5107.3721

1338/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5108.6128

1347/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5110.9409

1355/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5116.7046

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5113.6133

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5109.9478

1379/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5118.4097

1387/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5122.1299

1395/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5120.5322

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5125.5493

1412/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5122.2539

1421/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5127.2749

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5125.4102

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5136.4624

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5129.0864

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5123.3560

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5128.6113

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5130.8813

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5126.7485

1490/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5118.2402

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5115.8330

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5122.8354

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5117.5630

1525/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5116.4331

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5113.3945

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5112.9873

1552/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5106.9785

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5105.2637

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5105.8828

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5110.8228

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5112.7866

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5112.0493

1603/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5108.9189

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5106.2173

1619/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5108.2280

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5106.0908

1636/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5107.4385

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5117.9546

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5115.3901

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5115.9380

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5117.7905

1683/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5120.9702

1694/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5119.8857

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5123.1479

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5120.6855

1724/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5117.0234

1733/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5113.5039

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5108.9375

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5101.7246

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5106.2280

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5100.1587

1784/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5098.9761

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5099.0449

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5102.4297

1817/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5111.0752

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5106.1191

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5105.5391

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5114.3091

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5111.4263

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5114.5571

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5116.5308

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5119.2373

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5123.5801

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5122.5581

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5123.3945

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5122.7261

1924/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5125.3872

1932/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5127.4150

1941/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5127.2832

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5128.9707

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5125.5957

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5133.7700

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5134.1899

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5135.7407

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5135.6504

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5134.5112

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5134.4541

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5136.4351

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5138.0361

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5143.7109

2041/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5141.3667

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5140.9067

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5147.8608

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5148.1733

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5151.7939

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5147.5620

2090/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5142.4062

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5142.6851

2106/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5143.7373

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5142.6616

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5144.8901

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5141.5078

2140/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5140.1196

2149/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5141.6792

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5139.4307

2167/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5134.7886

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5133.9448

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5135.5151

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5137.8877

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5137.4741

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5137.8013

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5136.6567

2216/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5135.6035

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5139.9707

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5140.0503

2241/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5135.7158

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5134.3115

2257/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5133.6406

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5136.7642

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5140.8945

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5146.4224

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5142.7812

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5142.5908

2303/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5142.5527

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5144.0972

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5141.3262

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5144.5825

2336/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5140.9033

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5139.0371

2348/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5140.2241

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5146.3359

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5147.8115

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5147.6528

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5145.3799

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5146.5557

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5147.5791

2398/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5146.6909

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5140.9365

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5149.1235

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5153.5962

2428/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5153.9692

2434/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5155.2349

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5158.9688

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.4141

2452/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5153.1655

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.5825

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5153.9619

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.1445

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5160.5986

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5159.7563

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5158.7139

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.6035

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5157.4668

2511/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5158.1997

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.6157

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.6855

2534/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5160.4927

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5160.3647

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5156.9238

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5157.2905

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5168.1636

2572/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5170.3950

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5168.2686

2588/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5165.8262

2597/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.5586

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.1592

2613/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5161.9204

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5159.7998

2631/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5162.5771

2638/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5158.3184

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5157.6138

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5153.4927

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5156.6655

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5157.4805

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5156.5420

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5156.1523

2697/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5160.2515

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5156.5659

2714/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5157.5874

2722/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5155.8589

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5153.8325

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5158.7700

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5158.8931

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5156.7944

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5156.1221

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5156.4346

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5155.2300

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5151.5781

2801/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5152.0439

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5150.6396

2817/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5154.8374

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5150.7383

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5148.7646

2842/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5148.3760

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5151.5918

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5149.0918

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5146.7798

2875/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5148.1309

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5145.2505

2892/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5147.3687

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5146.4175

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5143.7036

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5143.5708

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5145.2827

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5145.9600

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5147.9204

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5145.5498

2969/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5148.6475

2979/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5152.2432

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5155.5576

2998/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5159.8242

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5157.9038

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5153.2378

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5155.3545

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5157.3276

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5155.7539

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5159.3838

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5162.7881

3069/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5166.1064

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5164.8511

3086/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5166.8350

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5165.8940

3104/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5169.1240

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5168.6187

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5165.6753

3130/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5170.7661

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5172.1699

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5169.5825

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5170.4180

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5165.3081

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5163.4541

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5162.3247

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5166.2090

3201/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5169.8569

3210/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5167.5771

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5166.1694

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5166.1401

3235/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5167.1572

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5165.0156

3253/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5161.2476

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5166.2427

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5170.7856

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5171.1445

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5170.9673

3299/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5169.2568

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5167.9619

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5168.3813

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5170.4111

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5170.5708

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5173.6699

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5173.9829

3357/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5174.3794

3364/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5173.6333

3372/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5171.3853

3381/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5168.9062

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5168.0132

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5166.9971

3406/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5166.4883

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5166.7192

3424/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5166.0928

3433/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5163.7168

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5165.0327

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5162.8384

3459/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5162.1489

3467/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5161.5020

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5163.3633

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5160.1323

3493/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5162.7510

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5161.4961

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5160.9390

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5162.3999

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5164.2563

3541/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.1870

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5161.5059

3560/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5159.4604

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5155.9175

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5152.5063

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5152.5327

3596/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5148.6704

3604/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5148.2314

3612/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5147.7559

3621/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5146.3799

3630/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5147.2285

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5147.0293

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5144.8330

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5144.7979

3665/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5147.3560

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5149.3457

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5150.6987

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5151.4175

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5150.8257

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5150.8257 - val_loss: 1107.2476

Epoch 16/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:44 61ms/step - loss: 5827.5010

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4552.5386

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4373.5239

  28/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4647.8726

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4483.7080

  46/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4398.4458

  54/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4684.9702

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4918.1099

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5025.0879

  79/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5185.1201

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5236.0093

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5274.8413

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5296.2095

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5404.1016

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5388.8267

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5401.5200

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5364.1455

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5326.2798

 157/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5219.3853

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5230.6260

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5267.1875

 182/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5237.1113

 191/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5230.2446

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5211.0713

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5236.8359

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5225.0547

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5182.2119

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5224.6113

 243/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5282.1138

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5319.6011

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5321.4453

 268/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5332.5767

 276/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5302.6733

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5290.1797

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5273.1792

 300/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5256.9331

 308/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5260.4712

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5290.4932

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5266.4990

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5255.7227

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5255.0332

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5276.9170

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5257.8589

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5243.6064

 373/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5247.9575

 382/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5270.7441

 391/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5245.6465

 399/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5257.2305

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5280.4126

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5246.0518

 423/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5239.2017

 432/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5238.1777

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5231.3237

 447/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5232.6768

 457/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5228.1016

 467/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5216.7544

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5219.7847

 486/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5256.0562

 496/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5259.7051

 506/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5261.3472

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5254.3779

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5261.7358

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5288.9463

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5290.3110

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5266.8379

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5277.5815

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5266.6294

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5279.2197

 587/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5289.3110

 595/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5286.5034

 604/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5296.5200

 613/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5296.2573

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5299.5869

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5308.7539

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5305.6011

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5294.1431

 653/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5287.0518

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5290.5088

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5281.6807

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5276.6670

 688/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5273.7373

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5261.6201

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5252.7710

 714/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5246.0415

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5244.6362

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5247.2544

 740/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5241.2896

 749/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5238.1440

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5239.5054

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5242.2329

 775/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5235.3916

 783/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5232.5449

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5228.2725

 799/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5238.0811

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5234.9058

 817/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5215.2686

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5211.2427

 835/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5197.8550

 844/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5213.5112

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5219.1924

 861/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5205.8613

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5201.1289

 879/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5209.6372

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5195.4038

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5195.6060

 902/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5185.9165

 910/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5209.6367

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5206.3965

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5208.3052

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5197.1406

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5194.6899

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5187.6206

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5197.5747

 969/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5190.0537

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5198.9233

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5186.3755

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5175.8193

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5178.2720

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5159.0635

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5155.7573

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5158.5420

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5159.9487

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5159.4907

1060/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5149.8584

1070/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5139.1021

1079/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5143.8809

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5140.4268

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5146.9492

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5150.6284

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5148.4678

1127/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5144.6836

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5139.2622

1145/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5143.3091

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5142.7026

1162/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5151.3784

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5162.1636

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5168.8643

1189/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5169.1719

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5170.5264

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5174.4282

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5179.3276

1223/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5175.9062

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5182.2178

1237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5177.2979

1246/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5176.5498

1255/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5175.1816

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5167.7627

1273/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5166.1553

1282/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5163.7407

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5167.9263

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5161.0029

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5161.3379

1316/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5157.4492

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5163.0049

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5154.9370

1340/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5154.5962

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5159.7646

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5162.4761

1364/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5172.3423

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5172.5698

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5175.6460

1390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5175.2852

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5181.5688

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5176.6973

1416/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5177.8145

1425/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5167.7007

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5165.0747

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5159.1265

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5159.2129

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5161.7930

1469/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5156.0581

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5153.6138

1487/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5151.9565

1496/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5151.8301

1505/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5153.5840

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5159.4932

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5167.2354

1530/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5166.0205

1538/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5173.8535

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5174.2886

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5174.2358

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5177.4668

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5179.7319

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5181.5352

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5178.3179

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5174.3340

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5174.3647

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5171.9365

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5175.3325

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5172.7300

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5180.1465

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5177.8301

1661/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5189.2554

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5186.1519

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5189.4551

1690/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5195.5767

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5193.1021

1711/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5186.7808

1720/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5183.0449

1729/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5177.9683

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5181.2612

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5182.3784

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5189.8594

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5191.9551

1771/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5195.2915

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5192.0659

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5198.1724

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5195.8545

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5194.7017

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5191.4839

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5191.2778

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5188.1763

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5184.1558

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5183.7578

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5182.0337

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5187.1914

1870/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5184.3369

1879/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5180.1343

1887/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5183.0283

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5185.0786

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5184.4551

1912/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5182.1440

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5189.8330

1929/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5195.2666

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5191.1821

1945/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5194.8462

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5187.7739

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5191.6323

1972/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5191.4395

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5192.5127

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5194.0928

2000/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5194.8413

2010/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5188.9150

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5186.4497

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5188.4224

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5187.7510

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5188.8989

2053/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5195.1631

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5194.0840

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5194.7266

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5192.8740

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5191.8774

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5185.5337

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5183.0210

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5184.4443

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5184.0947

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5184.9141

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5182.8042

2146/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5182.5205

2155/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5177.6206

2163/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5180.8481

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5179.1133

2181/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5179.4341

2189/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5179.2002

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5178.9912

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5181.5952

2217/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5180.4517

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5181.1260

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5178.3223

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5174.8462

2255/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5176.9297

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5172.9531

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5169.5278

2284/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5171.7676

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5176.8838

2302/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5173.0068

2310/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5172.5845

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5172.4155

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5174.3940

2335/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5170.7212

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5171.5889

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5175.9355

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5174.3296

2371/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5176.2759

2380/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5171.8433

2388/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5175.5630

2397/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5176.9390

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5181.9956

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5184.1484

2422/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5189.1104

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5195.2651

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5197.4355

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5197.1489

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5196.8228

2466/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5193.1226

2474/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5192.0112

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5194.2598

2492/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5192.5933

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5194.2661

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5188.8154

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5189.0000

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5190.1797

2535/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5187.4482

2543/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5190.7871

2551/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5198.0586

2558/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5196.3999

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5198.3110

2576/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5195.7769

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5197.0015

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5196.0518

2601/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5194.6274

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5195.8545

2619/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5195.8115

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5197.0791

2636/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5201.2754

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5201.8003

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5199.7710

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5199.2563

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5198.7510

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5194.5850

2689/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5195.0708

2698/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5194.3950

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5192.6699

2715/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5189.1045

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5190.1763

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5189.3521

2741/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5190.4033

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5188.9746

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5192.2896

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5191.5063

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5194.2510

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5197.0742

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5202.1558

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5203.1680

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5205.5615

2821/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5203.9360

2831/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5203.5547

2840/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5207.1260

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5205.4419

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5205.2173

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5200.8311

2878/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5201.3052

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5203.3779

2896/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.8198

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5209.8530

2914/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5208.8789

2923/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5206.6724

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.5840

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.1963

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.1377

2957/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5208.1362

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.9150

2974/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5205.9204

2983/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5203.9492

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5201.7515

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5198.9595

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5199.6753

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5200.2539

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5197.5864

3034/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5198.0576

3042/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5194.7964

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5194.7026

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5192.5210

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5192.1685

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5192.8618

3086/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5192.2358

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5192.4756

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5191.5493

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5190.4824

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5186.2412

3128/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5186.0210

3137/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5183.7065

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5186.3765

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5188.0547

3162/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5189.1445

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5189.1616

3179/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5185.5146

3187/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5183.4873

3196/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5184.5303

3205/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5184.9375

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5184.5439

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5188.5396

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5188.4429

3239/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5185.3462

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5185.5957

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5183.6816

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5186.4453

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5182.8398

3277/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5182.6445

3283/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5182.2153

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5180.1777

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5177.0923

3307/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5173.8950

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5175.0259

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5174.1050

3333/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5172.8652

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5172.0264

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5172.6782

3359/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5172.3179

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5172.2578

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5170.4595

3388/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5169.5884

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5165.9917

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5165.9512

3414/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5164.1841

3424/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5163.7554

3434/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5167.4136

3444/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5172.3608

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5169.6406

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5169.0967

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5167.8145

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5166.5547

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5165.2354

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5161.9023

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5160.6782

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5158.2466

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5160.4614

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5162.0122

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.5254

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.8765

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5167.7817

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5170.2812

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5166.8809

3583/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5167.0400

3591/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5166.7183

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5165.0815

3609/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5165.6138

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.9932

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.1753

3633/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5167.0996

3642/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5164.9854

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5165.0010

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5163.6421

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5161.3281

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5159.1641

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5158.0312

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5158.2080

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5158.4570 - val_loss: 213.5945

Epoch 17/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:19 54ms/step - loss: 6336.7842

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4746.0215

  19/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5476.1909

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 6009.5625

  35/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5672.4829

  43/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5731.7803

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5888.9199

  60/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5661.6597

  68/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5495.9561

  77/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5516.8452

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5372.4189

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5385.0229

 102/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5363.9351

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5265.2651

 119/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5253.5737

 128/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5243.0527

 136/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5317.4580

 145/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5373.3301

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5348.0400

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5323.4155

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5304.4585

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5290.5811

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5278.1836

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5251.2451

 207/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5263.3809

 216/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5267.8887

 225/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5293.2202

 233/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5276.9468

 241/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5245.4248

 250/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5209.0190

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5240.4937

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5227.9253

 274/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5224.7520

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5199.7588

 291/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5175.4341

 300/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5164.4995

 309/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5171.7642

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5184.0835

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5160.5503

 338/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5145.6743

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5147.5283

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5128.5049

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5149.1426

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5127.1035

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5127.6602

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5117.3643

 407/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5149.0820

 415/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5158.1782

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5166.0210

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5166.2964

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5161.3774

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5134.1416

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5116.0986

 469/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5111.0195

 479/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5120.9531

 488/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5107.7217

 496/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5092.2617

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5105.7573

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5112.7954

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5119.2812

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5103.7446

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5103.9482

 547/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5098.3164

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5093.6475

 564/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5108.1201

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5106.7783

 581/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5124.6719

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5109.4893

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5119.2817

 608/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5107.9585

 617/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5109.2812

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5131.2607

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5124.3794

 642/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5127.4194

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5130.7544

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5106.7783

 668/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5123.8906

 677/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5117.9531

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5108.5952

 695/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5093.6035

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5091.7041

 713/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5092.1631

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5091.7876

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5091.3599

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5101.4844

 747/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5087.2500

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5070.0303

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5056.2080

 772/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.0078

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5072.0322

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5077.0073

 797/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5072.7793

 806/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5079.6016

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5086.2036

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5086.4297

 832/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5072.9912

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5059.1772

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5061.7964

 856/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5077.2671

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5065.0405

 873/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5074.0161

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.1694

 892/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5070.0474

 902/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5076.6592

 912/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5073.2197

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5060.8164

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5050.0396

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5049.8452

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5054.8027

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5054.8457

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5058.3442

 982/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5062.7959

 991/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5052.3901

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5070.4902

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5066.9717

1014/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5069.8198

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5068.2139

1031/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5076.2158

1039/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5081.7280

1047/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5084.3325

1056/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5080.2080

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5077.4253

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5083.8521

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5085.3672

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5075.2334

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5073.3677

1104/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5068.9072

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5078.7656

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5082.0459

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5086.9775

1138/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5082.7832

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5090.8208

1155/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5097.8662

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5105.4385

1173/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5102.4155

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5105.9048

1188/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5112.2207

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5115.1313

1200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5113.4609

1209/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5111.3062

1217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5114.8022

1225/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5121.4653

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5113.7124

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5110.3257

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5118.0176

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5121.1699

1267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5122.2739

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5128.3716

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.9736

1291/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5137.8760

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5133.7344

1304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5135.4297

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5137.0547

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5132.5303

1327/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5136.9663

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5141.9731

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5147.1045

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5145.2393

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5139.8340

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5135.4385

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5130.6289

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5133.6973

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5128.3848

1391/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5125.1782

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5123.8677

1404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5130.8184

1412/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5127.6890

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5123.9316

1423/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5125.2456

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5120.1597

1437/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5117.0815

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5116.8481

1449/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5115.2300

1457/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5125.7651

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5121.2622

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5119.5640

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5125.4121

1487/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5125.5522

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5120.5459

1502/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5118.3525

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5115.2705

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5113.6958

1526/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5111.0244

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5121.1426

1542/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5117.3472

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5113.4746

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5112.5420

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5109.3638

1576/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5108.8174

1585/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5116.8354

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5119.8022

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5121.2168

1615/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5118.0791

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5122.9775

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5118.5430

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5125.3320

1658/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5123.4399

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5121.3340

1681/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5118.6660

1693/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5119.0796

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5118.3438

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5114.6489

1726/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5114.4697

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5105.0493

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5105.3418

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5106.6025

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5106.5806

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5119.3120

1797/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5122.8154

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5125.2173

1817/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5121.1714

1825/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5117.4941

1834/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5126.6343

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5129.5898

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5130.8105

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5130.5991

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5132.0479

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5139.2183

1886/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5137.7100

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5143.9370

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5138.8813

1911/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5137.9741

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5139.9233

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5145.6411

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5153.0425

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5166.0015

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5166.9927

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5169.6709

1970/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5172.0386

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5172.8989

1987/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5180.3164

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5181.0464

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5179.4302

2012/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5176.6538

2020/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5176.9194

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5176.5542

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5176.0381

2046/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5172.9292

2056/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5171.0439

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5173.3091

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5170.6489

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5170.5234

2087/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5165.7173

2096/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5169.6250

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5170.4653

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5173.0596

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5180.0864

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5179.2490

2139/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5185.7856

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5186.4478

2156/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5186.0596

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5188.3247

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5186.9355

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5180.2129

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5173.5718

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5174.7676

2208/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5173.4238

2216/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5176.0396

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5177.4829

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5185.6567

2242/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5184.6670

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5185.6099

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5194.9224

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5197.5791

2278/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5196.9448

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5197.1382

2298/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5199.1494

2307/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5196.5464

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5193.6182

2326/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5189.7891

2335/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5186.8179

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5184.2500

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5185.8208

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5181.5283

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5179.0518

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5177.3516

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5175.0576

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5170.9126

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5167.4370

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5168.2788

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5168.3760

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5166.2202

2440/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5164.9819

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5164.2573

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5162.2529

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5164.0278

2474/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5163.6562

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5162.9780

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5161.5308

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5167.9165

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5166.0024

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5161.3550

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5159.5391

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5165.3159

2541/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5167.3364

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5163.1562

2558/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5166.8760

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5169.9209

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.5239

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5165.2222

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5168.1899

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5167.3228

2607/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5170.1484

2615/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5168.3193

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5168.2920

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5164.4204

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5162.9375

2648/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5163.1777

2657/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5161.3428

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5160.8032

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5160.3335

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5164.9556

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.6265

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.2305

2708/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5165.2803

2716/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5166.1636

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5170.9033

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5167.0347

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5168.2095

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5168.8892

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5171.7222

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5168.3501

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5169.8135

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5172.1450

2793/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5175.8438

2801/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5174.3994

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5176.4819

2818/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5174.6919

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5174.2510

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5177.4595

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5176.8491

2854/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5175.9458

2864/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5179.6357

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5173.7959

2882/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5174.0908

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5172.6699

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5171.3730

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5167.5513

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5166.6338

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5168.1450

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5166.3271

2947/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5167.8413

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5168.8330

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5167.9541

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5169.8408

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5169.2139

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5168.8555

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5171.7310

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5174.0654

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5173.7837

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5174.0723

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5170.4233

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5168.2158

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5166.9292

3061/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5167.3770

3070/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5168.1738

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5167.0083

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5168.2705

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5169.6050

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5169.2749

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5170.3887

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5170.1689

3130/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5168.5625

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5163.4238

3146/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5162.6069

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5161.4326

3164/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5158.1870

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5156.9062

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5159.8882

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5160.1025

3199/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5162.9092

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5161.1475

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5160.1353

3225/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5157.1338

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5159.2471

3241/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5158.6226

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5155.6191

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5157.1333

3268/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5160.3999

3276/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5156.8945

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5154.5249

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5151.1040

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5150.7344

3311/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5149.1792

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5148.2993

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5148.0010

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5149.2168

3346/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5152.7241

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5154.1187

3361/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5152.9365

3370/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5153.7109

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5152.9316

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5151.7686

3394/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5150.5254

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5151.6865

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5150.6338

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5149.7842

3432/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5151.4736

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5153.8716

3451/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5154.8774

3460/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5151.3052

3470/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5151.7690

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5149.7026

3488/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5147.8794

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5146.3794

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5147.1357

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5142.4614

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5141.6938

3541/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5142.0718

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5141.8384

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5141.2007

3576/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5139.2856

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5140.0547

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5140.7109

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5138.1270

3624/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5135.7979

3637/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5134.5669

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5132.7188

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5133.5283

3671/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5133.3940

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5132.0317

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5127.4473

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5131.2598 - val_loss: 205.9339

Epoch 18/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 3:25 56ms/step - loss: 8315.2793

  10/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4486.2969

  18/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4557.9629

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5055.4482

  35/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 4951.5693

  43/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5202.9614

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5221.5063

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5081.9922

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5082.3809

  79/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5154.1255

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5088.5405

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5104.4058

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5198.6577

 114/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5391.1875

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5393.0703

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5412.7539

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5337.0713

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5316.4287

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5341.5220

 167/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5307.1411

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5270.3877

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5230.2412

 194/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5259.8384

 204/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5215.7290

 214/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5179.9258

 224/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5204.9712

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5200.8745

 242/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5170.1055

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5157.2217

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5096.2666

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5111.2603

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 5154.0835

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5182.5762

 298/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5200.0142

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5201.8369

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5201.9238

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5189.6650

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5158.2632

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5137.6245

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5124.8545

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5114.5508

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5102.6484

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5092.2881

 383/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5087.0859

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5130.5454

 400/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5118.4292

 409/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5121.7305

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5140.0425

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5164.0635

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5189.5034

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5191.1167

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5184.5581

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5175.9434

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5174.7700

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5136.3823

 486/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5144.7979

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5149.3066

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5155.8232

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5153.3721

 518/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5147.6611

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5142.5732

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 5130.5078

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5133.8794

 554/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5121.4204

 563/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5115.0645

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5118.8994

 580/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5115.2261

 588/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5126.6562

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5147.7061

 604/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5142.5664

 613/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5136.4487

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5145.1211

 631/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5128.1055

 639/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5120.8950

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5126.3604

 656/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5131.6108

 665/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5123.2036

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5114.7173

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5109.3926

 691/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5101.4258

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5099.3315

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5105.1245

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5103.0649

 726/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 5096.2285

 734/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5091.8242

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5087.0669

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5085.5322

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5076.1753

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5067.3169

 777/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.6294

 787/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5072.0913

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5064.3359

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5066.5474

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5073.1675

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5060.9644

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5047.8081

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5043.8535

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5034.7271

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5057.3584

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 6ms/step - loss: 5058.8232

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5057.8130

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5056.4180

 898/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5059.8335

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5054.6196

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5052.8281

 924/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5044.9160

 933/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5046.7822

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5044.0229

 950/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5036.5122

 958/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5030.8442

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5036.6094

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5030.0527

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5037.8101

 992/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5035.7065

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5035.0298

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5037.7915

1015/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5039.2002

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5041.9072

1031/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5043.6909

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5055.3325

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5057.3325

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 6ms/step - loss: 5059.6821

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5062.6758

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5062.8843

1082/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5065.3110

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5069.2046

1101/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5075.0371

1110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5075.7266

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5074.7300

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5071.1821

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5077.7925

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5077.9170

1155/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5087.4604

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5087.5864

1172/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5099.7905

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5097.8530

1189/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5097.0791

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5104.7104

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5112.0234

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5109.3970

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 6ms/step - loss: 5102.8447

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5099.5669

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5093.5186

1249/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5081.3740

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5072.6899

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5072.1323

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5066.9370

1284/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5072.7290

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5073.4199

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5067.3003

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5064.6323

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5063.5386

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5067.5420

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5064.6924

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5067.0000

1354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5068.9937

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5067.6919

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5071.3096

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - loss: 5076.9404

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5071.9126

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5080.2300

1412/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5083.7656

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5084.5728

1432/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5085.9990

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5086.0518

1451/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5082.2041

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5083.0771

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5083.2153

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5086.0898

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5085.4619

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5088.1128

1500/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5090.0889

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5094.5161

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5103.7627

1524/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5110.3711

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5104.5391

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5101.5601

1549/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 5100.0728

1558/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5101.0264

1566/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5098.4961

1575/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5099.2012

1583/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5100.9409

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5099.4868

1601/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5094.9722

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5096.4766

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5095.0972

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5092.2959

1635/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5096.4521

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5099.8169

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5099.0195

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5095.3975

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5094.6514

1681/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5091.3296

1690/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5090.8281

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5089.5195

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5092.2769

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - loss: 5094.1802

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5090.1333

1733/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5081.5933

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5079.5928

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5080.4521

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5079.8711

1769/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5083.2856

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5085.2397

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5080.8794

1796/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5077.2676

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5084.8804

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5089.7539

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5091.4233

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5092.0352

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5093.1963

1850/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5083.2661

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5089.6738

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5089.0801

1875/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5084.3384

1884/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - loss: 5084.0933

1893/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5080.9287

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5077.0112

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5080.4839

1917/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5080.2412

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5080.0073

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5084.9131

1945/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5080.1206

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5079.5283

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5076.5713

1973/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5074.2021

1983/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5078.6743

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5076.2803

2003/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5078.3403

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5077.6880

2022/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5075.5781

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5076.5649

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - loss: 5073.7061

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5071.9072

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5074.6265

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5071.9204

2074/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5073.3062

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5079.0962

2092/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5089.8418

2100/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5088.3750

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5094.0415

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5101.6553

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5105.4131

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5100.7451

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5096.7935

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5095.8394

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5100.1079

2168/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5099.9595

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5098.6416

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5096.0210

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5096.1685

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5094.3838

2210/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - loss: 5091.2529

2218/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5088.5654

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5089.9546

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5088.4971

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5091.4453

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5091.0503

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5086.3198

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5083.1226

2278/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.0771

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.6030

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5086.0005

2303/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5083.3384

2312/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.7559

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5081.3184

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5084.3950

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5086.1025

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5090.0630

2356/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5093.5796

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5097.0571

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 5094.3916

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5092.1992

2392/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5098.6343

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5097.2085

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5098.6904

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5095.6294

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5097.9028

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5096.6606

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5093.9141

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5093.0088

2460/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5095.0820

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5102.8901

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5104.4819

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5100.4805

2496/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5100.1787

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5100.1987

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5100.7070

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5096.1021

2535/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 5100.1050

2545/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5102.6104

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5106.2383

2565/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5103.5728

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5104.6748

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5105.0640

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5110.8267

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5109.2056

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5110.1348

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5111.6436

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5111.2510

2643/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5110.6074

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5112.6870

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5110.0181

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5110.7529

2686/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5105.6611

2695/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 5102.6196

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5103.5483

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5102.8491

2728/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5101.3560

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5097.8799

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5100.7515

2760/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5100.5425

2771/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5109.1494

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5116.2598

2791/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5120.0771

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5121.1436

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5119.8550

2822/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5122.8027

2833/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5120.2520

2843/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5117.6279

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 5116.0610

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.6851

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.9067

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5113.6299

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5113.9004

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5111.9541

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5108.3799

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5115.5703

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.4868

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.0732

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.8643

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5113.3281

2968/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5114.7563

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5116.5493

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5122.3438

2992/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5121.9443

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5119.1655

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5117.2124

3019/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 5117.1616

3029/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5117.8862

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5114.1733

3049/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5110.2280

3058/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5113.9185

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5113.2822

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5116.7090

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5116.1860

3098/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5116.3906

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5113.8457

3116/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5111.0952

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5110.1172

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5111.1284

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5113.1646

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5109.3960

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5106.6279

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5107.3105

3183/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5106.8809

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5110.7993

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5114.5190

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5114.1670

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5112.9023

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5115.5229

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5116.7412

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5119.1401

3258/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5122.9170

3268/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5120.8901

3278/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5124.8560

3287/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5129.8652

3297/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5127.0527

3307/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5127.5947

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5124.2710

3326/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5120.8945

3335/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5120.3936

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5120.2969

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5118.9194

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.7227

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.5786

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.3540

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5119.1294

3401/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5119.2168

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.1743

3421/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5117.3208

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5117.7070

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5122.1436

3448/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5119.3667

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5117.2842

3467/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5116.2783

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.0161

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5114.9741

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5114.9502

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.2085

3515/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5115.8569

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5118.4907

3533/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5119.1157

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5120.5249

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5120.5693

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5119.4155

3572/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5116.6587

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5115.9502

3592/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5114.3882

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5113.3315

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5111.8286

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5110.5244

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.8838

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5109.8999

3654/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5108.0146

3665/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5104.8779

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5101.7798

3687/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5105.3843

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5106.2954

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 5107.1689 - val_loss: 273.5351

Epoch 19/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:26 40ms/step - loss: 2925.6638

  12/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5371.7158

  22/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4979.5806

  32/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5006.0283

  42/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4814.2749

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4773.4106

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4538.0659

  72/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4630.5518

  83/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4614.8242

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4521.9604

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4668.9873

 116/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4661.5430

 127/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4647.0049

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4720.5381

 145/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4749.8550

 156/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4780.4009

 168/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4864.3457

 179/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4897.2007

 190/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4897.0850

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4947.1455

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4963.8364

 224/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4927.6118

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4932.1201

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4936.0859

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4888.8687

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4903.6665

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4872.0254

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4887.5903

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4866.3101

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4890.6611

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4888.8950

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4900.2046

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4929.3491

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4897.2100

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4967.1787

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4950.0278

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4990.8735

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5001.5752

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5015.8374

 437/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5002.4341

 449/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5013.1289

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4993.8442

 474/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4993.3311

 486/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4984.9575

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4988.5825

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5006.2061

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5002.0791

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5006.5576

 544/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4995.7896

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4981.9775

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4991.7139

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5001.9497

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4991.6802

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4986.4614

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4980.1387

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4988.6592

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4991.1265

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4993.4678

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4999.4380

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5002.9683

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5001.4980

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5005.7661

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5011.8599

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5017.8193

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5026.5430

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5028.4780

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5034.7524

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5041.8677

 777/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5045.7651

 788/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5055.8174

 800/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5046.7793

 812/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5048.6841

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5046.8677

 836/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5054.8252

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5053.9600

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5046.2612

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5039.0542

 883/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5046.0000

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5044.1499

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5029.9082

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5027.8145

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5036.4111

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5026.2646

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5008.8696

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5016.5430

 975/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5014.1357

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5019.6343

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5018.9204

1009/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5020.8433

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5025.4536

1033/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5026.8838

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5022.6440

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5026.8013

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5033.5508

1081/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5025.9033

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5034.9565

1104/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5031.5566

1116/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5036.2983

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5040.2632

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5048.4707

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5045.3989

1163/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5047.3481

1175/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5055.5654

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5053.6489

1199/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5048.1953

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5050.0601

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5046.4473

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5046.8174

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5049.6030

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5065.2051

1269/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5074.3818

1281/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5071.2729

1293/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5077.4292

1305/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5074.7671

1317/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5076.5498

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5076.7163

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5068.4224

1352/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5064.1240

1365/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5057.1055

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5075.9683

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5079.6978

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5085.8955

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5084.9570

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5078.1660

1427/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5078.0781

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5075.7852

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5072.6763

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5078.5283

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5078.9663

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5074.3853

1482/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5075.5020

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5090.2100

1502/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5089.8574

1511/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5088.1494

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5088.2266

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5085.6011

1537/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5086.7866

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5090.6089

1555/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5082.8804

1564/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5076.7612

1573/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5081.4082

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5077.3945

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5075.1479

1599/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5081.9722

1609/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5078.8574

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5082.1362

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5088.0674

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5085.3682

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5083.1348

1659/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5079.1045

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5079.0254

1681/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5082.3042

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5089.3794

1703/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5097.6826

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5098.8677

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5098.5508

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5092.7998

1748/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5089.8760

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5087.0586

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5086.7632

1784/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5086.0874

1796/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5092.8540

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5089.9897

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5084.4150

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5077.4316

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5077.0708

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5079.2603

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5083.6226

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5076.2612

1884/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5079.9565

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5084.6631

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5091.9775

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.6958

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5094.8120

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.7866

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5095.2026

1965/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.6436

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5091.5742

1988/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5095.6440

2000/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.2603

2012/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5096.4023

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5098.9893

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5096.7568

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5103.7847

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5111.0933

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5110.8813

2084/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5107.3594

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5119.2495

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5120.2686

2119/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5120.2314

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5113.2041

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5121.0352

2152/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5124.9087

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5129.7554

2175/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5131.4014

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5127.2632

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5123.2183

2206/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5114.7036

2216/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5117.0527

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5116.8975

2238/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5124.6582

2250/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5121.5933

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5116.8228

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5120.4526

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5127.1211

2298/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5123.7969

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5124.1289

2323/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5128.3091

2334/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5126.5859

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5130.4248

2358/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5129.5718

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5129.2046

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5131.6206

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5133.3691

2404/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5135.3462

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5133.4116

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5133.5044

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5138.5859

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5140.5522

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5137.2817

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5134.8472

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5133.9199

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5133.7930

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5134.2710

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5129.7603

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5128.7256

2542/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5135.7251

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5129.7881

2565/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5134.8184

2577/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5134.0083

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5133.4468

2600/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5132.7632

2612/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5137.1548

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5140.2573

2636/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5138.7285

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5137.1284

2658/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5133.1558

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5134.2363

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5134.7861

2693/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5132.8760

2705/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5127.8770

2715/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5128.8179

2727/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5126.4556

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5126.4971

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5133.6187

2762/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5132.9131

2771/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5134.1841

2783/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5134.3447

2795/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5137.6460

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5137.3325

2817/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5137.4219

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5139.2026

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5141.2251

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5143.0796

2863/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5139.9824

2876/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5138.9219

2888/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5138.0591

2899/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5138.7271

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5140.0601

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5136.4111

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5134.5781

2943/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5134.7861

2955/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5133.4209

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5133.7471

2978/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5134.3340

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5134.1230

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5135.3574

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5139.3384

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5136.8330

3037/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5138.3125

3049/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5139.0781

3061/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5140.3955

3073/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5143.6108

3085/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5141.0234

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5140.6152

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5137.9102

3119/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5132.8423

3131/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5133.5996

3143/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5134.1006

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5133.0732

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5130.6890

3178/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5128.8774

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5129.3032

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5134.3770

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5131.1685

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5132.2290

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5132.8838

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5133.8032

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5129.5264

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5128.8105

3282/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5125.6455

3294/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5127.7095

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5124.4590

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5122.2437

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5118.3848

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5118.7144

3351/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5120.4126

3362/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5120.9766

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5117.8579

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5118.1748

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5118.2900

3408/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5122.2036

3418/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5123.8760

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5119.0493

3443/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5117.9180

3455/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5116.1362

3468/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5114.9209

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5114.9590

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5114.2964

3502/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5111.8311

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5109.1553

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5107.0591

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5105.3457

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5104.5801

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5104.9570

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5103.0713

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5103.2329

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5109.3643

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5109.1079

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5106.7847

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5107.4336

3646/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5111.1772

3658/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5107.5464

3670/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5112.1079

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5111.0898

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5113.0156

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5111.1421 - val_loss: 548.3773

Epoch 20/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:05 34ms/step - loss: 3039.2527

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4478.5801

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4582.2310

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4563.8745

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4634.7773

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4953.9111

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5126.3877

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5023.9741

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4948.9692

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4844.8174

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5011.4189

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5093.7935

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5174.8833

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5147.0571

 166/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5118.2812

 179/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5092.1074

 190/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5093.0840

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5076.7607

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5012.4502

 225/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4992.5752

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4968.6943

 249/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4971.2461

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5010.0884

 273/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5079.0977

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5062.9360

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5053.5029

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5079.1104

 318/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5093.5239

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5097.1479

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5099.5234

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5070.5713

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5016.7710

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5006.2710

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5020.9839

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4998.9570

 413/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4982.3848

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4999.7539

 436/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5001.5371

 448/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5024.0005

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5032.3945

 471/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4994.7065

 483/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5002.8076

 495/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4977.8506

 507/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4984.1265

 519/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4982.8149

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4968.4414

 542/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4981.5747

 554/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4978.6626

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4975.8120

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4964.3247

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4978.2153

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5005.8760

 612/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5020.6606

 624/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5034.2749

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5023.5669

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5009.1987

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5029.1250

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5052.5293

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5057.8076

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5061.0317

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5054.3213

 721/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5054.6235

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5054.5342

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5061.4688

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5053.9678

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5054.1987

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5049.2275

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5037.9492

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5029.2393

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5028.4360

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5025.3916

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5034.8916

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5050.4849

 863/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5047.5796

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5041.2417

 885/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5038.0664

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5034.0640

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5036.5498

 921/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5037.8159

 932/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5034.0742

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5021.0000

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5022.5068

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5022.6353

 977/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5025.9155

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5031.1807

1001/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5034.1294

1012/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5035.5205

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5042.5327

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5048.6133

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5043.8687

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5035.7793

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5032.1792

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5029.8516

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5021.4756

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5017.6899

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5030.8828

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5030.4307

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5040.4443

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5026.1509

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5012.8604

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5006.5786

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5014.5273

1199/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5023.7158

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5027.4722

1221/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5029.8999

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5028.2671

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5040.4014

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5028.7900

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5034.3423

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5033.7627

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5028.7119

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5032.0137

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5024.9346

1322/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5024.3208

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5031.6250

1346/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5039.5269

1358/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5032.6074

1370/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5035.0762

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5028.4521

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5035.1328

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5046.2251

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5043.8018

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5041.5601

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5039.5952

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5038.5078

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5038.9331

1475/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5044.8174

1486/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5048.4897

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5051.3350

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5051.0093

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5056.3735

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5053.6567

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5046.8477

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5052.5449

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5049.8560

1581/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5053.3687

1592/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5059.4370

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5059.9595

1612/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5059.1719

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5057.0215

1631/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5060.6807

1641/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5058.0732

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5059.7524

1661/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5060.9839

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5059.7969

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5065.3228

1690/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5061.3237

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5058.1113

1706/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5055.0293

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5055.2485

1722/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5052.6226

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5052.6284

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5047.5054

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5058.1880

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5056.3677

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5055.5796

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5058.3647

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5066.9492

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5080.4414

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5086.7563

1825/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5094.4443

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5093.9697

1846/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5094.5088

1857/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5090.4956

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5087.5034

1878/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.7783

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5094.8232

1899/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5093.8291

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5092.8574

1918/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5095.7124

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5098.1621

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5096.2725

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5097.0596

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5098.3110

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5098.4976

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5100.0508

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5097.9834

1994/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5103.9731

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5105.0972

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5102.1465

2026/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5107.4302

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5109.2856

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5111.7207

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5110.0591

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5112.4517

2078/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5112.3994

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5109.4175

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5107.7637

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5103.4351

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5106.7915

2126/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5104.4448

2136/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5100.1855

2146/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5102.7354

2155/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5103.6646

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5101.6411

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5103.9912

2186/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5112.5503

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5113.2275

2204/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5114.3516

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5113.0483

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5113.6719

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5107.5532

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5111.8315

2261/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5113.7178

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5123.9565

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5123.0957

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5125.1475

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5120.6460

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5126.4072

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5122.1782

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5124.0586

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5135.1577

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5129.8828

2377/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5138.1621

2388/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5139.3604

2400/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5140.6021

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5141.6934

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5138.3730

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5138.1396

2447/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5136.4141

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5146.3794

2471/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5147.5469

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5144.1650

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5139.8379

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5141.6001

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5142.9790

2528/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5141.0659

2541/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5142.0220

2552/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5144.4287

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5143.8618

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5144.2500

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5141.1484

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5138.1060

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5135.9922

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5136.2471

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5137.1577

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5135.7612

2656/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5136.2246

2667/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5134.9453

2679/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5133.6597

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5129.6665

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5129.1113

2714/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5126.5356

2725/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5126.9595

2737/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5125.9717

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5124.1904

2760/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5123.4082

2772/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5120.4570

2783/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5120.9727

2794/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5120.9946

2806/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5119.2969

2818/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5123.7842

2830/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5122.0054

2841/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5124.0127

2853/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5127.2676

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5124.3438

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5123.0181

2889/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5120.8301

2901/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5122.2773

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5122.9326

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5119.4106

2938/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5118.4165

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5117.5449

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5117.3071

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5116.8379

2987/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5116.2158

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5110.1152

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5107.9307

3022/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5107.4614

3034/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5106.1436

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5104.6948

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5108.3296

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5115.0815

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5114.1685

3094/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.3877

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5112.5801

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.0854

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5112.0742

3137/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.0190

3149/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5115.8921

3161/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5115.6299

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5115.7563

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5117.8672

3196/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5114.0215

3209/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.5972

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5114.9058

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.7495

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.3584

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5113.7095

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5110.4722

3277/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5111.9448

3288/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5111.2100

3300/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5110.3931

3312/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5111.9434

3323/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5109.6064

3335/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5110.0786

3347/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5108.5571

3358/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5108.4199

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5107.6777

3381/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5106.2939

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5106.8604

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5109.6079

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5108.7070

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5108.2495

3440/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5107.4663

3451/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5104.3906

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5100.6987

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5099.4277

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.9644

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.7188

3511/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5102.9272

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5099.4604

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5102.0718

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5101.4751

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5102.2686

3568/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5097.7085

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5097.9746

3592/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.3169

3604/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.2212

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5096.3042

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5093.8799

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5097.1304

3650/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5097.4277

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5097.8081

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5099.8198

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.9663

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5100.0000

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5101.7573 - val_loss: 88.4717

Epoch 21/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:08 35ms/step - loss: 2643.0259

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5334.7739

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5271.4688

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4907.1328

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5056.0166

  65/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5025.1221

  77/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5038.3687

  89/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4865.2822

 100/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4805.9365

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4685.4170

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4710.6001

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4738.1167

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4759.2222

 161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4730.8091

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4804.6406

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4893.2686

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.8828

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4919.2339

 221/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4902.7285

 233/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4875.5908

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4932.9897

 256/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4924.5894

 268/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4914.5342

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4916.6011

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4910.3950

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4936.7656

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4915.9941

 327/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4911.0298

 339/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.8350

 350/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4871.0327

 362/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4848.5098

 374/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4860.6743

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4855.0981

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.4287

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4930.7979

 422/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4913.9233

 434/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4946.4424

 445/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4945.6606

 457/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4928.4917

 469/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4931.9473

 481/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4961.9980

 492/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4963.0010

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4978.5513

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4958.9521

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4957.1758

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4966.6187

 551/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4956.4985

 564/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4948.7002

 575/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4953.9497

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4945.6289

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4914.6260

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4940.6436

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4929.2734

 632/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4930.5156

 641/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4937.1709

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4935.7554

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4930.8149

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4934.8643

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4946.9360

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4936.0356

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4940.6157

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4940.7017

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4944.8125

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4936.9209

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4934.4282

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4960.5449

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4956.3354

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4967.6953

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4983.0444

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4987.3262

 825/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4982.4722

 837/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4971.5801

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4974.5469

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4991.0024

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5005.9404

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5018.1587

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5015.0669

 908/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5012.2461

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5019.4053

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5004.8843

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5015.0010

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5009.0552

 961/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4997.4985

 971/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4985.5610

 981/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4979.6030

 990/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4990.3257

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4992.9038

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4991.9150

1020/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4991.0781

1031/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4971.3218

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4973.5605

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4969.2124

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4962.3145

1067/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4957.9023

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4955.7734

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4954.0874

1092/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4965.0347

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4974.1235

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4978.4048

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4973.3662

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4977.1108

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4980.2383

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4978.6699

1157/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4986.0908

1167/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4983.1431

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4975.5049

1186/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4974.6440

1196/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4974.1748

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4975.0874

1217/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4972.8262

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4973.6084

1236/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4975.1631

1246/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4975.6172

1256/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4972.4927

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4961.6611

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4961.0464

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4964.5825

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4965.9868

1308/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4969.6328

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4976.2046

1329/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4975.6743

1339/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4974.8916

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4983.1050

1362/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4979.8413

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4979.5322

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4980.5649

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4983.7085

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4977.3418

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4988.9409

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4980.1338

1442/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4987.8271

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4981.7051

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4976.6172

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4979.3931

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4972.4355

1501/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4969.8521

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4964.7822

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4963.6338

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4955.4917

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4954.1958

1556/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4946.0088

1566/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4940.3057

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4943.9521

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4941.6011

1597/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4935.5366

1607/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4933.6914

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4925.6953

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4927.5625

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.0337

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4929.2622

1658/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4938.3496

1668/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4936.4951

1678/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4931.9087

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.6479

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4935.5596

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4932.0005

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4935.6782

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4939.4985

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4944.9976

1755/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4946.4097

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4951.2607

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4948.5254

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4941.9854

1800/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4939.2905

1809/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4938.0576

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4931.6138

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4926.2622

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4929.3125

1856/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4928.1162

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4921.4434

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4920.9800

1886/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4925.3340

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4922.3618

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4923.2056

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4924.5811

1918/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4928.0894

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4925.7905

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4928.9395

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4932.5894

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4935.2061

1963/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4932.1909

1972/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4932.3604

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4934.9360

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4931.1045

2002/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4935.0562

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4937.5566

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4944.9849

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4948.5347

2047/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4954.0728

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4952.7212

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4948.4077

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4953.3750

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4954.6504

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4955.8638

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4952.5894

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4955.3335

2142/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4961.1523

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4961.6230

2165/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4962.0952

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4962.2808

2188/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4961.3711

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4961.7310

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4958.9624

2222/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4962.5767

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4965.4546

2245/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4966.0396

2257/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4966.6646

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4960.8755

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4964.7285

2291/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4963.1157

2303/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4958.0376

2315/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4957.4521

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4960.2871

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4960.3774

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4960.3579

2361/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4959.5015

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4956.8008

2385/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4953.5713

2397/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4954.9805

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4956.0635

2419/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4950.8252

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4949.5522

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4949.5742

2455/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4951.0161

2466/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4951.4531

2478/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4953.5068

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4964.2349

2502/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4959.4707

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.1367

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4960.7061

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.7563

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.1865

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4966.4624

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4962.6416

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4963.0864

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4968.6704

2609/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4972.8184

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4971.6431

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4969.1035

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4967.4121

2658/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4967.9238

2670/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4966.4434

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4967.3193

2692/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4974.1167

2704/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4977.1631

2716/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4977.0215

2728/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4974.6772

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4970.9697

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4970.0718

2762/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4969.4946

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4966.8594

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4969.6626

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4974.9497

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4976.1060

2823/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4977.5664

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4977.8506

2847/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4978.3550

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4975.3823

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4972.9556

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4967.4990

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4965.1689

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4965.3906

2918/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4963.6382

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4960.3540

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4957.4258

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4956.3076

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4956.0156

2978/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4958.2822

2989/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4961.3687

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4961.0371

3012/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4960.6802

3024/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4958.9668

3036/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4959.8906

3048/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4959.3027

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4958.8960

3069/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4956.7422

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4951.9004

3092/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4954.8745

3104/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4952.1221

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4952.9038

3127/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4951.0259

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4952.8564

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4952.5601

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4955.3047

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4953.6982

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4948.6616

3198/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4948.8623

3210/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4951.4482

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.7944

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4951.6143

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4947.6577

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.9199

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.9736

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4944.9834

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4946.2212

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4947.3643

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4946.4561

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4945.4473

3339/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4943.4653

3351/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4940.5244

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4938.6772

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4938.6895

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4939.9595

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4941.6641

3408/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4945.6582

3419/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4945.1587

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4943.7954

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4942.7749

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4943.9443

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4940.9092

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4938.6943

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4937.8037

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4939.7983

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4937.1592

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4940.2671

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4937.9531

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4938.3813

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4937.5415

3570/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4942.3579

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4937.4917

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4938.7417

3605/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4939.5625

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4939.4976

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4941.7603

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4944.4619

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4941.5410

3664/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4941.7739

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4944.0522

3687/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4945.8604

3699/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4947.2793

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4948.3921 - val_loss: 270.3177

Epoch 22/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:05 34ms/step - loss: 4053.7976

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5444.3184

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4822.4282

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4896.5811

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4561.7900

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4499.1196

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4605.2920

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4667.6040

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4669.4937

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4746.0493

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4664.5347

 133/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4752.5776

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4702.4902

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4705.7065

 170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4698.6274

 183/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4749.2861

 195/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4744.5732

 207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4775.5635

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4805.9434

 230/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4841.1304

 241/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4858.7090

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4864.7393

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4834.4136

 275/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4832.5215

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4835.6929

 299/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4847.1821

 311/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4839.3882

 322/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4806.5942

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4779.7363

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4796.9697

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4780.9365

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4803.5693

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4763.2773

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4778.2363

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4812.8481

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4802.9062

 428/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4820.5596

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4812.3081

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4820.5571

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4835.6714

 474/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4861.9678

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4849.3901

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4869.5474

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4859.6138

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.9839

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4851.5376

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4866.9902

 555/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4851.4590

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4838.7407

 573/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4848.6523

 584/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4842.0190

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4839.1445

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4872.6099

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4872.7124

 631/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4852.8975

 643/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4845.1450

 653/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4834.0835

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4830.4648

 670/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4826.4302

 680/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4827.9258

 690/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4833.0391

 699/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4829.3882

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4826.6738

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4823.7329

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4818.7188

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4823.3125

 748/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4831.8179

 757/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4842.3486

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4840.4009

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4831.7964

 788/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4849.1172

 798/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4847.3638

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4858.8730

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4868.2378

 831/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4872.9043

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4878.9727

 849/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4881.5103

 857/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4881.8467

 868/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4873.7910

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4866.2212

 887/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4866.5449

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4874.6943

 908/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4882.6187

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4876.5752

 930/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4875.8691

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4863.9888

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4863.1504

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4865.5557

 973/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4868.0327

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4866.8696

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4865.7178

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4865.0942

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4868.2168

1033/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4876.1143

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4886.9443

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4881.1494

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4885.0879

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4887.0225

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4888.3521

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4893.9878

1114/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4906.0854

1126/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4913.6685

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4912.8647

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4915.2393

1163/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4911.5996

1173/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4911.2617

1184/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4904.3994

1193/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4898.9092

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4892.2163

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4888.2520

1227/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4890.8994

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4888.0708

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4886.3071

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4888.6357

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4892.6250

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4887.5503

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4878.8071

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4876.2637

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4882.4980

1331/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4886.5366

1342/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4886.8999

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4885.4683

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4883.7969

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4880.9043

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4880.5020

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4884.5566

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4879.8301

1414/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4891.6445

1426/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4892.5923

1437/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4895.7959

1449/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4893.8213

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4890.4502

1473/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4898.4385

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4897.6382

1491/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4898.9463

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4903.2476

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4914.0420

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4912.2524

1532/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4914.9775

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4913.0903

1555/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4911.2046

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4922.0845

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4921.6392

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4925.6211

1600/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4923.3247

1612/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4928.7783

1621/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4931.2993

1631/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4935.6831

1641/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4937.1133

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4934.2212

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4937.3071

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4944.6411

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4937.8423

1689/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4943.6328

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4943.3667

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4944.0254

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4940.9512

1720/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4942.5737

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4942.0859

1736/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4940.0039

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4941.2690

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4944.7573

1756/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4948.6377

1764/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4953.4238

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4953.5361

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4954.1777

1789/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4947.8706

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4955.0024

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4964.5322

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4967.0757

1821/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4969.3672

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4970.8491

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.7939

1845/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4975.2993

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4974.1309

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4975.6211

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4979.4937

1876/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4984.0322

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.6211

1894/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.9204

1904/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.5640

1914/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4987.7246

1924/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4985.5103

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4983.6021

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4985.2788

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.4819

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4990.8931

1971/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4985.8511

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.1982

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.0415

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.4209

2012/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.9521

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4984.4888

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.4316

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4987.3320

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4988.6060

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4987.1055

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.0396

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4990.9722

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4999.3481

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4997.2642

2118/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4997.5537

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4996.3530

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5001.1260

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5006.2119

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5005.1328

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5008.1890

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5007.8374

2192/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5006.3301

2203/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5007.8760

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5002.9556

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5006.8667

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5006.6724

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5007.7856

2261/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5011.7422

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5013.0337

2284/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5006.9604

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5007.7373

2303/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5006.9688

2313/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5007.9331

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5005.6885

2331/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5006.1987

2342/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5004.1353

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5005.4521

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5004.8555

2375/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5002.0503

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5001.4038

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5002.5483

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5000.0879

2422/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5006.9160

2432/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5007.9185

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5005.0830

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5003.5752

2461/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5004.2280

2471/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5002.2642

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5010.2319

2493/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5006.1470

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5010.0249

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5010.0718

2528/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5008.0806

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5006.0874

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5005.9805

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5005.2998

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5005.0054

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5003.0938

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5002.8179

2600/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5002.5811

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5003.8760

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5005.1636

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5004.7129

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5005.7490

2655/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5001.9199

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5004.5791

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5006.9814

2684/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5010.5781

2693/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5007.9297

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5009.6709

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5012.6572

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5017.7075

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5022.9961

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5030.0161

2754/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5024.9141

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5025.7563

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5026.1245

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5025.2314

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5025.1538

2808/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5029.8931

2818/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5024.9619

2829/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5022.4507

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5017.5269

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5013.6553

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5012.1548

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5010.1646

2880/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5008.1128

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5009.6753

2899/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5008.2300

2907/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5007.6011

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5008.7603

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5009.1133

2924/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5010.0640

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5008.1333

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5008.8062

2945/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5010.0288

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5012.6763

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5012.3740

2973/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5016.6694

2983/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5014.1938

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5016.5005

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5019.0977

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5018.6904

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5022.6167

3037/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5020.9014

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5015.5454

3058/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5017.2026

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5019.8652

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5023.9697

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5025.6416

3098/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5026.5283

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5026.9224

3117/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5029.9497

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5032.4629

3136/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5031.8115

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5029.8066

3158/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5028.0273

3168/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5031.8257

3179/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5030.7095

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5031.9053

3201/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5033.2710

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5032.6982

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5032.4775

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5030.8970

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5033.3491

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5032.3848

3264/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5029.3164

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5030.4956

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5029.8745

3295/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5031.5020

3306/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5030.8896

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5028.1182

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5029.0425

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5029.8862

3348/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5028.3657

3359/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5027.0806

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5030.6006

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5028.1450

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5025.2554

3401/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5022.3027

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5022.5264

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5026.6953

3432/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5024.8604

3443/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5022.2139

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5023.9951

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5021.4512

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5024.6724

3486/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5024.5898

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5024.2275

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5021.9502

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5021.2114

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5021.3394

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5020.3125

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5020.2705

3561/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5020.2310

3571/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5022.0532

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5024.5381

3592/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5022.7490

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5024.8882

3612/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5024.3599

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5022.2139

3633/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5021.3013

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5019.6533

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5019.1094

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5019.9834

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5022.1885

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5021.8364

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5022.7217

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 5021.4917 - val_loss: 105.9135

Epoch 23/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:05 34ms/step - loss: 4876.7788

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5510.8052

  24/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5395.1865

  35/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5147.5435

  47/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5074.7627

  59/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5055.5459

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5028.6489

  82/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5078.6938

  93/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4973.1133

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4966.2583

 117/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4960.6172

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4954.0884

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4889.9756

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4919.8296

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4898.6118

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4842.1704

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4848.8896

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4923.9238

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4894.2915

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4928.2944

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4953.4585

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4981.2363

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4970.4580

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4959.9780

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4929.6938

 294/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4909.0610

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4897.8198

 318/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4948.9580

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4928.2705

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4910.2520

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4936.3130

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4931.3545

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4909.4492

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4883.6074

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4851.1167

 413/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4855.1768

 425/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4839.6440

 437/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4851.3501

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4870.5562

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4866.8975

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4853.0708

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4857.5010

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4878.6431

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4882.1108

 519/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.0967

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4861.3926

 542/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4872.0020

 554/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4870.4297

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4858.5825

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4857.3511

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4866.4375

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4864.5352

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4864.1797

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4862.6465

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4843.9004

 650/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4841.4365

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4832.9956

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4826.1636

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4828.5498

 699/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4816.2583

 711/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4806.6919

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4814.6250

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4806.6299

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4805.8984

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4806.5825

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4823.3569

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4838.0034

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4829.1807

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4841.8345

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4851.2427

 827/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4840.5405

 839/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4845.8765

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4838.8926

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4848.3398

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4845.5166

 883/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4839.8672

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4845.6982

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4870.4492

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4868.3315

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4862.1699

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4862.6509

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4864.0015

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4881.8325

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4883.4688

 990/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4885.5981

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4875.5039

1015/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4867.4209

1026/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4862.8228

1038/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4876.3008

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4893.4160

1062/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4891.3140

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4898.4102

1087/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4894.6978

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4887.4800

1110/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4888.6431

1122/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4894.4663

1134/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4891.4082

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4892.4341

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4892.4580

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4885.5708

1180/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4885.0562

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4878.2715

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4872.5806

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4884.4839

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4881.6133

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4881.5239

1249/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4881.6768

1261/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4890.6431

1273/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4902.4146

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4910.1953

1297/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4906.7656

1309/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4903.5249

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4911.8774

1329/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4909.2432

1340/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4909.1880

1352/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4914.8179

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4917.4443

1375/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4920.9175

1387/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4917.4062

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4917.7007

1411/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4915.6948

1424/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4922.5312

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.4395

1448/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4938.6719

1459/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4937.2275

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4933.3169

1482/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4932.5488

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4936.6167

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.7476

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4946.5698

1526/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.5938

1538/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4947.9497

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4947.9487

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4942.6772

1574/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.4277

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.8921

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4947.7578

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4950.7773

1621/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4953.7119

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4962.0005

1643/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4965.2427

1655/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.5610

1667/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4965.8555

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.1118

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4960.8662

1703/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.2202

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.0752

1727/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4953.8662

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.6670

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4958.1992

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.0518

1774/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.7339

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.4058

1797/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4970.9199

1808/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4971.2334

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4970.8032

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4967.4023

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4973.4775

1854/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4973.3389

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4972.1211

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4979.4233

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4982.6255

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4980.9370

1914/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4986.5195

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4984.6528

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4980.6763

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4976.6396

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4968.8589

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4968.7788

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.9448

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4971.4805

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4971.1646

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4973.6885

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4978.3262

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.1064

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.0801

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4983.7163

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4979.2886

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4980.8657

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4980.9307

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.6484

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4980.8975

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4984.4092

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4984.5698

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4988.4912

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4990.6357

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4987.6582

2197/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4984.0103

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4980.4922

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4975.0562

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4977.7720

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4975.7100

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4976.2891

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4981.3159

2277/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4981.2158

2289/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4989.6987

2300/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4991.5068

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4988.7837

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4992.6748

2334/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4991.1387

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4982.1714

2359/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4981.0015

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4978.7954

2384/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4977.2476

2395/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4984.8687

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4992.8682

2419/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4992.4258

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4986.1772

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4979.4775

2455/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4985.5591

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4985.2500

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4980.8247

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4983.2168

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4990.7031

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4992.1396

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4999.5581

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4999.1670

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4994.2310

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4999.8208

2572/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4999.6348

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5002.5171

2596/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5004.5420

2608/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5003.3589

2619/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5002.5249

2631/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5000.3228

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4996.3350

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4990.6641

2666/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4987.8516

2678/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4984.3794

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4983.3462

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4982.6938

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4991.7949

2725/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4990.1880

2737/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4992.0947

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4997.1348

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4996.9702

2773/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4997.8999

2785/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4997.6406

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4992.6079

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4991.8901

2820/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4990.5557

2830/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4987.4204

2842/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4989.5898

2855/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4991.7422

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4992.8628

2879/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4995.4946

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4997.0132

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4993.4648

2915/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4990.4917

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4990.6963

2938/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4989.2988

2950/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4990.5308

2962/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4990.4395

2974/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4992.4351

2985/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4998.5054

2997/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4995.6548

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4996.1333

3021/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4995.8032

3033/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4996.2397

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4993.1963

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.8779

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4988.7041

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4992.0703

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4991.9077

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4993.5825

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4991.7568

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4989.3159

3134/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4986.6128

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4986.4102

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4993.8662

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4994.0630

3177/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.5166

3189/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.5156

3201/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.7725

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.4277

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4990.2075

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4993.8218

3246/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4992.4565

3258/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4990.1406

3270/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.7075

3282/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4994.8218

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4994.2822

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4994.8262

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.6011

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4994.5068

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4996.0459

3352/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.4448

3364/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4994.3345

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.8584

3387/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.5947

3399/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4992.7461

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.0493

3423/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4989.1274

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4993.2842

3447/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4992.5010

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4992.2070

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4995.0537

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4995.9497

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4996.3936

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4996.7910

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4998.0742

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4998.3848

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4999.8193

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5003.1709

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5004.1294

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5005.9258

3585/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5009.2173

3597/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5007.1904

3609/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5005.5791

3621/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5005.3745

3633/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5001.7446

3645/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4999.8203

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4998.9048

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4997.7432

3679/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4998.7329

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4999.5000

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4999.1382 - val_loss: 263.0190

Epoch 24/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 1:59 32ms/step - loss: 4282.0366

   9/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 7ms/step - loss: 4231.0249

  21/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4305.2144

  33/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4534.0298

  45/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4778.3750

  58/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4947.2671

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4864.8462

  83/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5148.6802

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5063.2583

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4993.8730

 117/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5013.7583

 128/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4981.0098

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4947.1201

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5026.8965

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4949.3604

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4921.7061

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4839.7749

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4817.0962

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4758.1553

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4780.1035

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4832.7407

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4830.3354

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4816.1997

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4824.5479

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4829.7817

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4833.5957

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4857.6860

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4885.2100

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4887.0615

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4908.2153

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4896.0146

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4901.8784

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4877.9463

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4873.3745

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4843.5171

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4857.6606

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4854.6938

 438/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4859.9121

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4869.8931

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4873.5127

 474/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4867.6099

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4857.3560

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4873.6875

 510/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4886.6675

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4885.2446

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4917.6978

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4924.7549

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4909.7866

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4907.3853

 580/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4931.6406

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4922.9795

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4926.7949

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4950.2964

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4953.7852

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4952.7939

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4948.7515

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4962.8008

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4958.6499

 682/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4965.9180

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4986.9521

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4979.7651

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4956.9922

 727/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4956.6816

 739/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4952.8018

 751/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4952.3472

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4961.6528

 775/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4953.0835

 786/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4945.6655

 798/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4937.5581

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4925.5059

 821/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4931.1465

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4925.8188

 845/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4930.4497

 857/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4930.8760

 869/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4935.2285

 881/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4933.6304

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4933.9590

 905/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4914.9312

 917/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4918.5146

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4914.3428

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4913.1416

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4911.0732

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4918.7129

 979/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4923.4233

 991/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4922.1758

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4910.6250

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4911.8828

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4902.8599

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4900.0479

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4907.9102

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4918.6113

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4920.6182

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4922.2251

1097/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4944.0493

1109/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4952.3042

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4954.9980

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4950.3208

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4958.5566

1157/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4965.7891

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4962.1851

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4962.0015

1193/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4967.5225

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4965.7944

1216/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4966.8237

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4957.3696

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4961.5605

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4957.0244

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4953.8833

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4940.2856

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4941.7085

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4947.5737

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4948.5771

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4951.4917

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4950.7017

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4950.5752

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.3418

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4954.7705

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4958.9248

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4952.9380

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4953.4600

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4960.3042

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.6167

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4954.5312

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4954.8438

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4950.7036

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4954.0391

1486/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4957.7837

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4962.6475

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.8882

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4967.3696

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.8281

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4956.1963

1542/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.6665

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.2012

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4953.5083

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4955.6685

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4956.1289

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.1084

1596/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.9458

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4969.4888

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4970.6030

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.1074

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4974.0024

1641/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4973.2295

1650/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4968.2881

1659/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4978.1260

1670/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4980.9102

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4973.9370

1690/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4973.2373

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4974.8154

1712/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4977.5693

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.5020

1735/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4984.9702

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4988.6343

1758/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.7290

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4981.3267

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4986.3682

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4985.8828

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4988.6304

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4983.8740

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4983.5796

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4983.0913

1850/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4984.7134

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4994.0806

1872/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5001.6367

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5003.5723

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5000.0083

1905/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4993.2290

1917/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4996.2119

1929/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4989.8813

1941/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4993.0171

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4983.8101

1965/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4980.8955

1977/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4982.2271

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4982.3955

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.8130

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4974.1265

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4975.2158

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4969.2993

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4970.0669

2060/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.7871

2072/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4976.2466

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4975.4136

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4977.8735

2107/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4970.1484

2119/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.1519

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4970.9810

2142/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.3013

2154/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4968.0312

2167/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4969.7593

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4965.8115

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4967.0596

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.9453

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4961.7598

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4963.2397

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4960.7046

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4957.6914

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4955.3911

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4954.0835

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4955.5762

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4959.1816

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4957.0146

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.9082

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4958.5547

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4956.9673

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4954.3809

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4951.4263

2375/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4953.5459

2386/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4950.1973

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4948.6758

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4949.4390

2424/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4949.1621

2436/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4951.2563

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4952.4434

2460/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4949.8970

2472/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4949.7720

2484/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4950.2637

2496/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4951.3462

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.9834

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4959.7563

2532/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.9604

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.9087

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.1392

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.1172

2578/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4960.1689

2590/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4955.7437

2602/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4956.6787

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4953.3794

2626/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4952.0562

2638/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.1030

2650/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4956.5210

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.1816

2674/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4949.9932

2686/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4951.3213

2698/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4948.4595

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4946.5874

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4944.9224

2733/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4946.6919

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4949.0576

2756/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4943.2690

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4944.0410

2779/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4940.0015

2791/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4939.6719

2803/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4946.1479

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4947.9556

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4949.6118

2837/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4952.9507

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4949.5386

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4948.4941

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4946.9492

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4949.4365

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4951.0566

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4949.0024

2916/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4945.3628

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4943.7891

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4943.3311

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4942.5957

2960/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4940.1113

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4939.7197

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4941.1055

2996/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4941.2715

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4938.1187

3020/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4940.0078

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4943.6030

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4942.1279

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4941.3198

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4942.5913

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.1021

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4948.9292

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.8394

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.7227

3119/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4950.2222

3131/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.9985

3141/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.8335

3154/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.3608

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4947.0015

3177/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4945.4922

3188/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.1846

3200/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.0288

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.2095

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4943.3145

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4943.2700

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4943.0996

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.3569

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4944.4019

3282/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4942.8623

3294/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4938.9829

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4936.7192

3318/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4937.8296

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4936.9380

3342/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.1445

3354/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4933.7046

3366/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.3354

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4933.4609

3391/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4932.1460

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4928.9956

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4929.7871

3426/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4930.1899

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4931.6577

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4932.4351

3461/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4933.6812

3473/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4933.2397

3485/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4929.9941

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4930.8467

3509/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4930.7930

3521/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4930.2622

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4929.9868

3544/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4928.7358

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4929.5288

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4929.0767

3579/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4929.2788

3591/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4927.7246

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4926.1343

3614/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4922.1230

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4919.3652

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4917.4155

3650/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4916.7065

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4915.2480

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4914.6187

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4916.7544

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4918.4736

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4919.1265 - val_loss: 110.4615

Epoch 25/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:12 36ms/step - loss: 6443.9277

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4988.3242

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4682.2168

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4957.4092

  48/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4839.0249

  60/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4915.6025

  71/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5032.5776

  82/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5100.1440

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4946.8882

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4978.1279

 118/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4825.5405

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4821.8105

 142/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4754.4590

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4801.5698

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4759.3813

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4834.9751

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4839.6646

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4845.9478

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4883.6362

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4896.0005

 233/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4868.0254

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4833.8042

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4877.2031

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4884.5054

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4921.8682

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4922.7808

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4937.9824

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4913.5098

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4912.0327

 340/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4930.5293

 352/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4933.7163

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4977.3032

 376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4954.6777

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4938.0884

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4944.2368

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4942.1475

 422/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4924.6865

 434/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4940.5322

 445/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4918.3486

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4938.0308

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4930.6465

 480/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4916.4307

 492/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4889.5996

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4880.4502

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.4546

 528/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4901.8945

 540/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4913.2383

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4917.8687

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4925.2910

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4934.4854

 589/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4947.8887

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4957.1680

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4960.3730

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4970.8740

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4986.2915

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4990.1538

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4991.1812

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4990.2549

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4971.6602

 697/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4964.5005

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4969.0527

 721/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4966.9976

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4975.7803

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4971.0796

 754/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4964.0005

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4966.4780

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4973.4331

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4980.1494

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4980.9482

 814/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4979.4390

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4979.8560

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5003.6694

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5013.2681

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5007.5396

 873/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5020.7485

 885/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5014.2676

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5008.7686

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4993.0400

 921/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4990.4829

 932/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4995.5977

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4988.8403

 955/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4992.8467

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4991.9922

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4990.2769

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4983.3066

1001/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4975.3535

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4971.2207

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4972.0381

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4975.8857

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4970.0562

1060/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4972.9165

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4964.4956

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4956.0625

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4957.5981

1106/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4958.6240

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4954.7568

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4955.7129

1141/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4959.4009

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4963.3901

1165/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4961.7407

1177/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4952.9556

1188/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4952.8999

1200/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4946.1108

1212/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4949.1699

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4936.7437

1236/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4927.6743

1248/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4931.3130

1260/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4935.4111

1272/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4938.3877

1284/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4932.8921

1295/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4936.8110

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4933.8633

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4938.1309

1331/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4938.5552

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4936.4819

1355/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4932.3018

1366/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4929.9771

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4933.8589

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4928.3291

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4926.0410

1411/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4930.5161

1423/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4929.9819

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4923.6270

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4931.0591

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4931.3477

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4925.3359

1482/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4915.3472

1494/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4916.0840

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4911.2983

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4915.7998

1530/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4913.8330

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4920.4307

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4917.0015

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4912.1162

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4911.1411

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4910.0410

1600/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4922.4131

1612/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4926.8696

1625/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4934.6265

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4932.2998

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4934.5942

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.7031

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4947.6318

1684/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4955.5908

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.9380

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4958.3696

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4958.5610

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4956.5635

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4956.5776

1755/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.0303

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4951.2490

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.0156

1789/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4955.5859

1801/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4953.7021

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.5903

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4964.4731

1831/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4962.2393

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4956.6543

1854/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.7725

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4958.9810

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4950.2183

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4951.5874

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.1948

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4960.9727

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4967.3564

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4967.7456

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4967.2002

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4963.7500

1973/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4961.9580

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4960.1738

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4956.6050

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4950.4312

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4953.8086

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4946.4170

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4950.6812

2051/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4949.8774

2063/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4950.3599

2075/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4951.5518

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4958.8931

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4958.9175

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4957.3525

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4957.3413

2135/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4962.2769

2147/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4966.8872

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4972.2349

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4969.6543

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4970.1406

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4964.8594

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4963.9170

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4964.8125

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4961.5010

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4955.4048

2248/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.3081

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4960.0801

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4959.8906

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4958.4805

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4958.7778

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4962.6870

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4967.6011

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4966.9336

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4966.8027

2351/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4965.2959

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4962.7056

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.9995

2384/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4956.3579

2396/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.1323

2408/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4960.0029

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.3286

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.8643

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4964.2007

2454/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4964.0459

2466/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.3384

2478/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4958.5679

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4957.4507

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4956.3486

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4955.7915

2524/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4956.0356

2535/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4958.5405

2547/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4957.6948

2559/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.5571

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4958.8213

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4956.6802

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.9927

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4954.0889

2618/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4957.6631

2630/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4955.2178

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4956.8779

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4955.0029

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4957.0649

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4953.8706

2689/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4953.5757

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4953.5938

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4953.8994

2722/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4954.5781

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4953.3735

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.4644

2756/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4947.8735

2768/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.0210

2780/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4946.1963

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.9976

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.2231

2815/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4951.1235

2827/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.7720

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4952.3716

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4952.6113

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4949.6265

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4951.4570

2885/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4953.3208

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4958.0278

2908/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4953.9473

2921/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4950.3076

2933/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4949.7651

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4952.9707

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4952.7090

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4948.9888

2978/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4945.5405

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4945.2900

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.4873

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4946.6909

3024/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4946.6118

3036/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4945.7935

3048/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4942.4468

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4941.1187

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4937.3857

3084/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4936.4038

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4938.9971

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4936.7188

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4941.2686

3132/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4939.6685

3144/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4935.7632

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4937.2192

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4940.0684

3179/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4941.0166

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4942.9766

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4942.1260

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4944.2402

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4943.4756

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4940.7583

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4940.2310

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.7456

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4938.3623

3286/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.6162

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.8286

3310/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.3931

3322/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4935.2368

3334/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4936.9126

3345/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.7812

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4941.7290

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4940.6992

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4944.9077

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4944.1792

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4941.4155

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4940.4766

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4943.7261

3436/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4943.7070

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4943.0005

3456/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4942.6650

3468/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4941.7490

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4939.7949

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4938.1855

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4937.7676

3515/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4936.6895

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4937.6396

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4939.5049

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4938.8311

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4938.3433

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4935.5464

3586/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4934.5278

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4935.5688

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4933.7900

3622/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.9199

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.8916

3646/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4924.9229

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4922.9165

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4922.3311

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4923.7417

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4921.1191

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4921.8145

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4921.8145 - val_loss: 67.5102

Epoch 26/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:03 33ms/step - loss: 4548.0737

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5272.2534

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5309.7310

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5254.8208

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5061.3745

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5063.2314

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5134.8823

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4807.6528

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4825.1865

 107/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4842.1123

 119/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4770.6533

 131/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4761.9751

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4716.8042

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4671.5967

 166/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4657.5073

 178/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4675.7729

 190/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4705.2715

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4753.0435

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4755.9302

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4751.9355

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4776.6279

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4808.6914

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4830.3701

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4857.7690

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4840.6768

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4848.1997

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4870.6997

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4862.9111

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4891.0537

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4900.2534

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4878.1523

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4872.8159

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4863.2124

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4868.1294

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4840.0151

 413/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4850.5835

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4841.0986

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4816.4971

 447/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4840.5840

 459/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4845.1797

 470/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4860.9224

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4870.9067

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4866.1943

 506/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4890.3965

 518/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4878.7847

 528/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4882.4976

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4876.3501

 549/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4903.0703

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4942.4263

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4972.7480

 584/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4999.5142

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5020.2349

 608/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5008.0449

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5007.8955

 632/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4992.3379

 644/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4992.5952

 656/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4998.7427

 668/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5000.0400

 680/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4988.7295

 692/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4981.4570

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4996.6260

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4986.7085

 728/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4994.1787

 740/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4983.0249

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5000.5542

 764/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4995.6665

 775/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5004.9941

 786/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5005.5103

 797/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4998.3618

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4992.2798

 821/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4996.6616

 832/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4994.9180

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4989.4785

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5011.0205

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5029.9536

 877/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5032.7627

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5033.7441

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5038.7866

 912/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5031.6519

 923/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5038.2729

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5031.1011

 948/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5032.6025

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5028.8823

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5022.3208

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5014.4092

 995/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5019.8286

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5011.9458

1018/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5000.7441

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4997.2578

1042/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4996.0830

1054/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4992.9395

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5002.9126

1079/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5001.3154

1091/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4988.9946

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4977.7661

1113/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4977.4590

1125/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4982.2305

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4999.0220

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4999.3569

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4990.9976

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4985.7183

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4987.8921

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4974.8623

1204/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4974.5161

1216/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4965.8403

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4966.5425

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4964.7007

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.9727

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.1523

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4960.8618

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4959.7261

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4951.9858

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.2002

1322/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.3369

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4951.3008

1344/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4958.7715

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4959.1841

1368/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4958.6489

1380/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4955.4346

1392/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4948.5669

1404/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4948.7959

1416/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4948.0742

1428/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4950.1602

1440/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4957.2056

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4954.0186

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.5146

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.4751

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4940.7808

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4951.4883

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.3560

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.3984

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.2207

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4945.7974

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4940.4531

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.3354

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.3745

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4946.6885

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.4097

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.1152

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4947.5425

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4952.2524

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.6865

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.4019

1674/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4954.6494

1685/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4952.4438

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.7603

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.1294

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4951.5557

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4953.6250

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.4556

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4965.1802

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4962.2124

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4966.7666

1789/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4968.1504

1801/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4960.9272

1813/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4962.7222

1825/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.9355

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4964.1147

1847/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4957.0562

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4949.3701

1870/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4944.4292

1882/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4950.6343

1892/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.7764

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.1318

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4957.9868

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.1108

1939/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4971.6919

1951/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4968.3145

1963/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.8389

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4961.5698

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4963.3711

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4963.5522

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4962.1636

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4961.3271

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4961.5137

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.5547

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4963.9834

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4958.4028

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4955.6519

2094/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4952.9453

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4951.9185

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4956.0786

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4955.3584

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4952.4771

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.1484

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4958.8574

2175/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4955.8062

2187/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4955.3706

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.1333

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4964.2788

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4970.7197

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4970.7046

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4968.7144

2258/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4971.4492

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4967.9209

2282/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4968.1025

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4967.4590

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4970.7935

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4974.4805

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4970.6997

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4971.9102

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4978.6226

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4977.0400

2375/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4975.6177

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4973.8242

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4968.0142

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4964.6016

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4971.1543

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4970.4443

2447/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4966.8516

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4968.8140

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4965.5752

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4965.1846

2493/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4965.7715

2503/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4965.2202

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4964.1328

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4962.3521

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4958.4326

2551/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4956.8818

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4961.8652

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4963.8188

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4964.0273

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4966.5923

2609/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4968.0571

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4970.3584

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4964.4692

2644/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4963.3623

2656/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4963.9111

2668/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4966.8979

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4964.6099

2692/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4970.9722

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4972.3140

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4976.1284

2722/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4979.6372

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4976.0205

2741/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4974.9170

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4974.3799

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4972.1899

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4967.7163

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4971.5479

2798/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4968.6831

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4973.8228

2820/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4979.3105

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4979.8589

2843/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4974.3818

2855/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4969.6191

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.0254

2879/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4969.7285

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.7183

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.9580

2914/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.9873

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4975.5596

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4975.3071

2947/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4973.0312

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4970.7876

2971/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.1411

2983/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4966.0630

2995/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4961.6631

3007/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4963.9971

3019/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4964.9648

3031/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4963.6465

3041/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4963.2354

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4962.8066

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4959.4492

3076/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4956.7021

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.0664

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.0605

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4953.8081

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.7480

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4955.1025

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.7451

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4950.8228

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4952.2744

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.4927

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4956.6777

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4957.0117

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4955.9297

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4957.9692

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4959.7212

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4963.0723

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4961.4512

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4966.2920

3278/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4964.2612

3291/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4966.6445

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4963.3901

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4965.8838

3326/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4968.6631

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4967.5264

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4967.3438

3362/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4967.0020

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4969.4033

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4967.2407

3397/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4966.8174

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4968.2261

3421/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4969.6509

3433/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4968.9058

3444/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4969.0039

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4966.9331

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4968.1704

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4968.5518

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4968.0830

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4968.8462

3511/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4969.8047

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4967.8013

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4971.6348

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4972.6929

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4971.4341

3570/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4973.8472

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4971.5562

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4970.1426

3607/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4969.1782

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4964.6279

3631/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4963.6387

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4961.8506

3655/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4962.6802

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4964.8257

3679/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4966.1763

3690/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4963.8379

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4961.3765 - val_loss: 145.0936

Epoch 27/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:07 35ms/step - loss: 5420.3691

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5039.0508

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5099.5024

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4932.0161

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4941.7871

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4790.3081

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4818.3735

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5041.1851

  99/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5022.3633

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4944.3359

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4930.8296

 133/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4880.6333

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4808.2842

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4758.8853

 170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4720.7568

 182/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4726.3301

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4736.1929

 205/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4727.7500

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4700.2031

 229/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4764.0234

 241/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4755.8301

 253/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4732.5684

 265/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4750.6411

 277/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4727.5327

 289/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4720.2036

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4732.7095

 310/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4745.2749

 322/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4741.5918

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4768.8711

 344/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4782.4482

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4751.4731

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4731.7168

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4730.4595

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4741.4634

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4751.5547

 415/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4760.5854

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4769.6035

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4779.9033

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4820.9419

 463/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4840.0244

 474/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4806.9092

 486/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4835.3262

 498/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4830.7188

 510/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4851.4414

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4860.3872

 534/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4869.3076

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4850.6636

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4848.8916

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4832.5825

 579/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4825.3687

 592/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4816.1528

 603/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4814.3472

 615/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4824.3462

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4817.0522

 636/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4827.5303

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4831.5220

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4817.9937

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4824.5356

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4858.5898

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4881.6196

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4883.4771

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4885.5938

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4888.3174

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4881.0532

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4883.6963

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4866.6548

 773/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4868.0332

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4855.9043

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4857.1338

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4862.4443

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4847.9058

 831/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4867.3306

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4872.6016

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4865.8677

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4874.0039

 877/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4884.9624

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4878.3887

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4881.8086

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4882.3560

 923/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4895.5195

 935/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4915.3760

 947/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4931.2798

 958/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4920.5376

 970/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4930.8389

 983/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4929.4375

 995/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4938.0674

1007/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4941.2998

1018/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4942.7612

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4928.0317

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4923.3218

1051/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4916.1953

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4916.5107

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4910.3159

1087/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4903.1133

1099/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4905.3916

1111/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4906.1626

1123/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4899.7217

1134/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4891.3638

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4904.0537

1157/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4903.2266

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4904.9224

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4902.6548

1193/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4908.8931

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4908.4956

1217/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4905.9546

1229/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4903.7930

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4908.8579

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4909.5776

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4912.7432

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4915.4341

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4919.4902

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4935.4141

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.8579

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4941.8755

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4943.9639

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4947.0581

1355/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.4688

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.2432

1379/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4948.1172

1391/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.0781

1403/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4950.5562

1415/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.4365

1426/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4957.6157

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4958.2607

1450/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4956.5674

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4950.5137

1474/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4945.7607

1485/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.0576

1497/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4946.5874

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4951.4336

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.7773

1533/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.7690

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4934.2676

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4926.8110

1570/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4922.0195

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4921.4038

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4923.2500

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4923.5693

1615/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4922.7925

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4921.9204

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4921.7812

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4924.8906

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4918.4668

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4917.4497

1687/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4919.9517

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4925.6401

1709/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4929.0483

1720/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4920.6055

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4927.2349

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4922.9536

1756/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4916.4043

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4912.5293

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4912.3916

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4917.8662

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4913.1533

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4912.4292

1828/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4910.5518

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4915.0103

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4908.9541

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4912.1416

1874/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4914.4263

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4909.9463

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4906.3350

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4902.5342

1919/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4897.8384

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4904.0615

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4901.6987

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4906.9717

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4906.3789

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4901.1016

1987/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4903.6294

1999/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4908.0610

2011/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4906.6162

2023/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4907.1938

2035/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4905.2822

2047/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4904.2959

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4902.1938

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4895.9253

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4891.2812

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4891.5933

2107/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4895.8770

2118/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4894.4761

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4897.4854

2142/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4893.0024

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4887.3652

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4886.7803

2176/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4883.1533

2187/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4885.4487

2199/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4889.1411

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4886.3481

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4885.8491

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4885.8140

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4887.9883

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4892.3608

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4897.2959

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4897.6377

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4900.8560

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4901.8916

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4912.3477

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4918.6748

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4918.4546

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4915.8442

2361/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4911.7388

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4916.9526

2384/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4918.8076

2396/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4910.7617

2408/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4917.4951

2419/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4923.1899

2431/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.7427

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4922.2827

2455/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4917.6577

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4919.4307

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4919.8389

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4916.8711

2503/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4917.3633

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4918.4526

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.5161

2539/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4922.7808

2551/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4925.4971

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4925.3291

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4929.8125

2585/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4933.6689

2597/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4933.8481

2607/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4929.3013

2617/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4931.7720

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4931.7310

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4930.1953

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4927.5439

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4928.2949

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4926.4248

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4926.6948

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4928.6089

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4927.5742

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4927.8018

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4931.5845

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4926.8901

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4925.0264

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4926.7383

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4923.4321

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4926.7041

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4925.7456

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4928.5820

2822/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4928.1313

2833/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4932.6909

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4934.2959

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4935.4297

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4936.5342

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4938.0254

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4934.0293

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4936.0391

2915/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4935.6489

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4936.6030

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4940.4546

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4943.7739

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4942.5225

2974/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4939.4019

2986/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4939.1406

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4941.1631

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4943.3740

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.7422

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4945.9126

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4946.6270

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4949.6587

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.7964

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.6558

3091/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4956.1855

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4956.2373

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.1484

3127/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4952.2290

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4949.9087

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4948.4141

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4945.0269

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4944.6157

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4942.2974

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4944.4058

3209/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4946.9937

3218/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4943.7231

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4941.7793

3241/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4941.6675

3251/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4938.4731

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.8765

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.2324

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4933.2378

3297/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4930.8643

3309/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4931.5244

3321/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4930.4404

3333/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4928.5869

3345/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4928.1196

3357/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4927.0259

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4923.8145

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4922.5879

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4922.1572

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4921.7896

3414/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.7808

3426/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4925.9849

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4925.0029

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4924.5210

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4922.3242

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4919.7314

3485/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4919.4087

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4918.7188

3509/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4921.4946

3521/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4925.9785

3533/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4925.3306

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.8623

3555/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4924.9097

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4924.9370

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.2510

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.2881

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.1714

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.7642

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.9849

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.8872

3645/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.0918

3657/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.3423

3669/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4926.7441

3681/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4925.4521

3693/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4926.5791

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4927.4697 - val_loss: 102.0959

Epoch 28/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 4:00 65ms/step - loss: 6238.6372

   6/3701 ━━━━━━━━━━━━━━━━━━━━ 37s 10ms/step - loss: 5692.2095

  15/3701 ━━━━━━━━━━━━━━━━━━━━ 28s 8ms/step - loss: 5908.1416

  23/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5558.4673

  31/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5453.7095

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5254.7690

  46/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5138.1440

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5234.1528

  60/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5045.9951

  68/3701 ━━━━━━━━━━━━━━━━━━━━ 26s 7ms/step - loss: 5100.0322

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5075.6626

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5208.5337

  92/3701 ━━━━━━━━━━━━━━━━━━━━ 25s 7ms/step - loss: 5225.6230

 101/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 7ms/step - loss: 5388.6235

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 7ms/step - loss: 5377.8374

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 24s 7ms/step - loss: 5366.1064

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 7ms/step - loss: 5289.5425

 139/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 7ms/step - loss: 5209.1919

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 23s 6ms/step - loss: 5144.5581

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5097.4414

 169/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5075.5933

 179/3701 ━━━━━━━━━━━━━━━━━━━━ 22s 6ms/step - loss: 5042.4995

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4982.9658

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4905.6973

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4904.5010

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - loss: 4910.2090

 230/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4891.5039

 240/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4820.2417

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4844.2192

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4847.8550

 268/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4865.5728

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4902.5669

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 4881.6782

 300/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4844.9653

 311/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4852.7632

 322/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4834.8018

 334/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4834.3086

 346/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 4822.9141

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4805.5830

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4820.7109

 381/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4794.4004

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 4812.3013

 406/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4823.1738

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4814.9600

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4828.0996

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4833.6333

 454/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4857.3462

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4854.6118

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4878.4238

 489/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 4872.1025

 501/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4875.7441

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4879.9814

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4857.1548

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4844.8311

 549/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4847.9937

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4869.5449

 571/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4865.2983

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4847.4487

 594/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4860.7944

 606/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4860.9556

 618/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4848.3535

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4843.7773

 641/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4827.8369

 653/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4816.8267

 664/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4808.4585

 675/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4828.6875

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4831.8477

 697/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4836.1855

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4846.3042

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4849.2896

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4853.1714

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4859.2441

 754/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4871.1030

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4883.4106

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4893.6143

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4917.8262

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4928.2173

 811/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4925.3403

 822/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4930.1831

 834/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4931.7798

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4929.1284

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4932.9492

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4944.9233

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4950.3354

 892/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4949.1475

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4943.8237

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4958.9360

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4955.8115

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4948.7539

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4946.6045

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4956.4595

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4949.1558

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4943.2646

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4926.4990

1007/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4926.6470

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4915.7109

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4919.0610

1042/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4935.6992

1054/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4941.1895

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4940.7397

1077/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4943.5659

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4937.0122

1100/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4930.6558

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4938.4214

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4945.7954

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4942.3657

1147/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4942.8008

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4939.8330

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4946.7139

1183/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4946.4976

1195/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4942.8350

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4943.5703

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4946.3833

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4950.1113

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4948.6152

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4945.7065

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4947.5371

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4949.5557

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4947.6030

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4942.3179

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4942.5962

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4938.6782

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4931.7466

1347/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4935.0947

1359/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4934.8267

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4936.8994

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4949.1055

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4945.8721

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4950.4658

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4955.9888

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4956.2480

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4955.8125

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4965.7524

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4971.8237

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4977.7227

1486/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4976.6196

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4974.3569

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4973.9302

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4972.7402

1532/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4972.2920

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4978.2578

1555/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4968.3286

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4971.6865

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4980.8188

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4976.8735

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4973.7241

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4975.7261

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4974.6382

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.4937

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4971.3613

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4971.1812

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.3018

1683/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4971.7402

1695/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4971.5645

1706/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4972.2583

1717/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4967.0171

1729/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4962.8110

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4956.6289

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4950.2603

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4952.8999

1777/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4958.2275

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4953.8936

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4955.8457

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4958.4473

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4958.8311

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4965.3872

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4971.2881

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4968.2925

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4962.6421

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4960.8901

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4960.6274

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4959.5186

1919/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4962.4253

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4966.9175

1941/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4966.6240

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4964.9873

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4965.8096

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4969.1978

1987/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4970.7441

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4978.3896

2008/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4974.6743

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4974.1699

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.3472

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4974.8911

2054/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4971.6562

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.7485

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4970.6167

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4970.7632

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4972.1587

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4975.2476

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4968.6372

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4967.3496

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4973.0352

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4976.4907

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4979.9644

2180/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4982.2163

2192/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4978.4146

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4980.9219

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4982.8662

2225/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4979.0713

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4980.7544

2250/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4986.2754

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4984.1162

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4983.9561

2285/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4982.7407

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4983.5322

2307/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4983.6045

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4980.0454

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4978.7402

2342/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4979.0967

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4973.1284

2366/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4966.7275

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4968.4956

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4967.9751

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4964.7383

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.2598

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.0259

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.8306

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.0146

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.0698

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4952.5752

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4953.7139

2497/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.0376

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4952.8662

2520/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4953.1035

2532/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4950.4849

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.5093

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.5830

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.4541

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.6748

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4960.3589

2605/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4961.0195

2617/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.6772

2629/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4955.8438

2641/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4950.5049

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4950.4883

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4952.5840

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4953.9194

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.0122

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4949.6187

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4949.4360

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.9585

2735/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.7334

2746/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4952.6440

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4957.1279

2769/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4961.6616

2781/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4964.0698

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4965.7168

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4967.2324

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4966.4067

2827/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4960.6504

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4960.0308

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4955.0869

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4955.0454

2872/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4953.8389

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4950.6758

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4952.9727

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4959.7949

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4963.5474

2934/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4963.4722

2945/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4964.0234

2957/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4963.9004

2968/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4967.2471

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4971.2783

2992/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4968.8750

3003/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4966.5415

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4968.4399

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4967.6201

3038/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4964.2930

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4964.5605

3061/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4965.6924

3073/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4966.8975

3085/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4968.5439

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4971.4937

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4969.9150

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4970.4868

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4974.2383

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4971.5454

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4969.9736

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4972.8198

3180/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4974.6289

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4975.6367

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4976.7534

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4976.9204

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4975.4858

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4976.8877

3251/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4973.8540

3263/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4977.9312

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.9980

3284/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4979.7192

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4981.2700

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.0479

3319/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4977.5493

3331/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4978.0176

3343/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4975.7607

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4979.6260

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.2852

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.3286

3391/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.4746

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.6455

3414/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4980.7354

3425/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4982.0103

3437/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4985.3931

3448/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4984.1523

3460/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4984.5210

3472/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4982.6855

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4983.1196

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4982.3262

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4981.2300

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4985.0469

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4983.1084

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4984.6519

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4981.0186

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4977.8296

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4977.8740

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4979.0352

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4977.8350

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4977.4849

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4976.8833

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4973.8872

3646/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4973.2383

3658/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4972.7603

3670/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4972.7773

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4972.7886

3694/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4974.5581

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4973.6743 - val_loss: 136.0623

Epoch 29/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:09 35ms/step - loss: 2499.7827

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5143.3062

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5176.2236

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5287.2788

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5245.4185

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5408.5669

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5488.3149

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5394.1187

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5308.6763

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5382.7710

 120/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5416.9355

 133/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5287.2183

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5329.9199

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5414.1689

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5387.5205

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5452.0820

 188/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5366.2847

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5352.2378

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5375.7168

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5346.4697

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5351.8257

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5322.6387

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5354.9429

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5327.4824

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5394.5176

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5413.1460

 303/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5365.0093

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5364.0781

 327/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5381.0225

 339/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5358.4170

 351/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5316.0195

 363/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5264.7686

 373/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5234.4136

 385/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5225.2046

 397/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5211.7202

 407/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5188.6899

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5205.3062

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5183.4883

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5184.8374

 454/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5169.9570

 466/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5144.8188

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5137.5898

 489/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5116.2598

 501/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5095.0601

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5115.6362

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5109.6392

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5106.4829

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5091.7783

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5091.7920

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5116.6816

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5100.7969

 595/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5094.0210

 606/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5095.8711

 618/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5078.3315

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5068.3760

 642/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5047.9531

 654/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5028.8394

 666/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5023.4590

 677/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5039.9351

 689/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5028.7422

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5039.7812

 711/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5041.2310

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5042.2241

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5038.9492

 745/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5047.5513

 757/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5049.4194

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5039.1260

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5056.7764

 793/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5053.0615

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5069.2798

 817/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5045.3013

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5031.6528

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5024.8931

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5019.7749

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5014.7378

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5009.2705

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5031.2925

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5025.9751

 910/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5030.7168

 921/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5029.1040

 933/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5033.8247

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5021.4224

 957/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5014.8154

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5020.4614

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5027.4556

 992/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5043.4448

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5043.3203

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5026.4258

1026/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5021.3706

1038/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5028.0498

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5032.6597

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5027.6353

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5029.6401

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5021.5576

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5020.7651

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5016.0923

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5017.9326

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5010.3560

1141/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5011.5605

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5014.1240

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5017.5581

1175/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5010.4648

1186/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5010.9888

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5017.4810

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5010.7588

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5012.2476

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5016.1924

1246/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5003.2183

1258/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4991.4795

1270/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4982.8677

1282/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4986.3677

1294/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4978.8188

1306/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4982.6543

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4983.0825

1330/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4983.6216

1342/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4980.3818

1354/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4974.2051

1366/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4983.7388

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4983.3691

1389/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4982.6099

1401/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4976.6675

1413/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4976.8530

1425/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4979.7012

1437/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4976.4170

1449/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4973.4194

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4976.4521

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4977.9487

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4971.8296

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4967.4219

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.4526

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4955.0049

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4958.3237

1540/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.1772

1552/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4956.6211

1564/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.6855

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4957.5581

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4952.0830

1601/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4953.3320

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4959.1270

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4956.6255

1635/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4955.0908

1647/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4956.8916

1659/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.3599

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4965.3594

1684/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4964.0889

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.5474

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.1450

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.8848

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4956.5371

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4953.7358

1755/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.8320

1767/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.0259

1779/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4964.2183

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4963.9551

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4963.0439

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4967.0562

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4969.2812

1839/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4973.9902

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4969.9346

1863/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4969.0703

1875/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4968.2803

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4967.5776

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4968.8628

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4969.9053

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4969.3965

1933/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4968.0889

1945/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4976.0894

1956/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.6797

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4984.4614

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4986.7349

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4984.8677

2003/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4987.0322

2014/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.1699

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4985.2817

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4983.0225

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4981.1553

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4987.3804

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4981.8428

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4987.5010

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4983.1367

2109/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4980.3604

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4973.4473

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4973.9883

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4973.0840

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4967.2280

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4968.4331

2181/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4971.6313

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4967.7178

2205/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4965.6455

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4962.2515

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4961.3535

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.3726

2250/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4959.0962

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.6562

2273/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4953.2979

2285/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4954.7188

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4957.0156

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4956.0923

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4955.9790

2332/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4953.1030

2343/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4956.2476

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4959.3003

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4961.5464

2377/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4964.2290

2389/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4961.7788

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4966.1143

2414/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4963.1064

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4966.1909

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4970.2622

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4971.4604

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.0010

2474/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.1553

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4975.3623

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4976.0967

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4977.5820

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4975.3613

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4975.7725

2542/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4979.1055

2553/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.3076

2565/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4970.9741

2576/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4970.5571

2588/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4967.5376

2600/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4971.0220

2612/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4969.7007

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4969.5903

2637/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4969.5933

2649/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4971.4595

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4973.3057

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4966.8774

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4968.9136

2697/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4970.0142

2709/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4966.7339

2720/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4974.3071

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4974.6880

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4976.0132

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4977.4111

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4973.3530

2779/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4969.2158

2790/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4968.4971

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4966.4688

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4964.0371

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4963.2896

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4959.0146

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4956.2285

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4955.0366

2872/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4956.8311

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4957.6396

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4956.0581

2908/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4955.3223

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4956.7729

2932/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4953.5352

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4955.8252

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4957.2051

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4960.3364

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4964.1426

2987/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4967.3755

2999/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4970.2817

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4970.0381

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4971.1118

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4969.0474

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4968.8569

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4967.2490

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4966.6631

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4967.9858

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4975.4521

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4973.8027

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4975.0371

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4974.6992

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4977.9448

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4978.0112

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4971.4326

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4968.9995

3192/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4967.6450

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4964.5273

3214/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4961.2476

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4967.0132

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4972.8271

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4974.9092

3260/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4975.2539

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4974.7319

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4973.2969

3297/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4969.7305

3307/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4967.0576

3319/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4965.1270

3331/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4966.9009

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4963.8613

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4960.5010

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4961.1240

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4959.2480

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4955.8945

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4954.1992

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4953.4004

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4951.4180

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4951.7573

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4953.4160

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4949.8604

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4949.5820

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4944.3140

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4938.0601

3511/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4940.3506

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4938.1826

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4936.7285

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4934.7515

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.1494

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.8677

3581/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.8335

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.9858

3605/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.3755

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.5229

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.5693

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.7969

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.0830

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.1411

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.1875

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.4082

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.0679

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4932.5713 - val_loss: 73.1275

Epoch 30/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:04 34ms/step - loss: 8891.7402

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 6120.1177

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5373.2729

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5389.5049

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5197.4380

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5371.7803

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5243.9565

  82/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5194.7554

  94/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5230.3018

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5140.4658

 118/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5121.2842

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5108.5117

 142/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5061.4580

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5059.2515

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5019.1460

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5106.8984

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5063.8560

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4989.2402

 212/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4964.6226

 224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5048.4717

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5051.5557

 249/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5089.7979

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5086.4224

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5083.9912

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5089.1138

 294/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5082.0557

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5113.2148

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5111.7319

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5091.7676

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5076.8525

 346/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5068.4956

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5034.5859

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5038.6514

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5057.3838

 391/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5069.6426

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5035.0703

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5030.5713

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5030.8335

 438/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5027.0698

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5018.5889

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5050.5659

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5064.0576

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5073.4839

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5065.3765

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5045.7344

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5035.8257

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5045.8379

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5049.8750

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5023.2100

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5018.1733

 581/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5022.3740

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5016.8301

 605/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5003.3804

 616/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4991.0508

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4986.3999

 640/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4982.3970

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4980.1523

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4979.8525

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4967.2915

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4964.2998

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4932.4565

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4921.0063

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4920.2676

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4913.9409

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4911.5127

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4908.7285

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4903.8398

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4905.1904

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4908.1777

 803/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4900.7891

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4898.0156

 827/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4896.8521

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4900.6440

 849/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4916.4487

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4918.6108

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4913.1636

 881/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4915.0962

 893/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4914.5542

 905/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4913.1377

 917/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4910.0054

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4900.4536

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4888.2930

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4893.8838

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4894.4102

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4903.2427

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4893.7559

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4894.5142

1012/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4896.8545

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4906.8721

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4906.3057

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4902.0049

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4906.8442

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4914.6440

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4912.4546

1092/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4915.5420

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4918.8267

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4918.0293

1127/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4915.6953

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4914.9561

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4924.4482

1163/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4916.9673

1175/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4916.3052

1187/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4910.0781

1199/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4901.0337

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4890.2896

1223/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4895.0996

1235/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4894.3564

1247/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4893.6499

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4897.8335

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4898.0273

1279/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4898.4136

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4904.9043

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4901.3130

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4907.4341

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4914.3682

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4914.7500

1342/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4917.0571

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4914.1538

1363/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4909.7480

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4911.7983

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4906.5488

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4908.8926

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4911.4893

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4906.3740

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4909.9893

1442/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4920.3618

1454/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4928.2075

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4929.1719

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4920.7695

1489/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 4922.3062

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.1182

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4925.6807

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4918.5269

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4916.6924

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4919.6396

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4914.1802

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4926.1592

1573/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.5669

1585/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.9370

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4928.0547

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4930.4121

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4931.4268

1633/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4927.4956

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4925.3784

1657/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4916.9165

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4915.4053

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4918.9062

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4918.5122

1702/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4921.0439

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 4923.8896

1724/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4924.7183

1736/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4920.9766

1748/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4922.2920

1759/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4924.7163

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4917.0210

1781/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4920.8066

1793/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4922.9185

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4917.9312

1817/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4923.3906

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4918.6758

1841/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4922.6592

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4931.0703

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4936.9072

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4934.8926

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4933.9551

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4931.6367

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4930.6641

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4925.8159

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4928.1362

1949/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4928.1689

1961/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4937.5967

1973/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4932.6470

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4940.8149

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4941.3984

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4943.0977

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4938.9668

2028/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4942.2852

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4942.0747

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4939.1577

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4946.1221

2076/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4947.9116

2087/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4949.2822

2099/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4948.8091

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4953.6406

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4956.4634

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4962.0566

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4963.2163

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4961.7754

2168/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.3936

2180/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.0078

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4969.2842

2203/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4968.5981

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4965.8794

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4963.4292

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4965.6245

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4963.0254

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4963.7329

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4969.6094

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4966.2822

2299/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4966.3359

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4968.6577

2323/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4967.9956

2333/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4967.4951

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4962.6602

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4958.3765

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 4955.1611

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.5107

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.9058

2404/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.4370

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.6919

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.1167

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.6172

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4955.6323

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.9170

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.2822

2484/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.7275

2496/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.4048

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4960.4868

2520/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4956.7197

2532/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4955.4268

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4957.3447

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4953.9307

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4954.1724

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.8882

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 4958.3940

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4957.2979

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4956.8384

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4960.8628

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.3896

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4951.1162

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4951.7612

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4956.4209

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4959.4819

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4958.5054

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4961.9971

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4959.5615

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4958.7588

2741/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4959.5679

2753/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.7041

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4956.8574

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.7222

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4954.6558

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4951.3384

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4949.0977

2822/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4945.1885

2834/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4949.0464

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4946.3037

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4942.3027

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4944.9365

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4942.7856

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4938.9419

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4937.8887

2917/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4935.6567

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4936.9746

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4936.8130

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4936.5625

2961/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4938.1323

2973/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4941.5146

2985/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4942.5693

2997/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4942.6445

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4950.0776

3021/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4950.4663

3033/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4953.3950

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4950.4941

3055/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4949.7485

3066/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.3047

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.9365

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4945.6235

3101/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.8994

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4944.8330

3124/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4946.0522

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4941.0859

3146/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4941.6880

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4941.8105

3166/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4942.9863

3178/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4940.7593

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4938.5166

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4938.2192

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4936.7324

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4937.4141

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4943.3779

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4939.2915

3260/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4940.0879

3272/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4936.1782

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4936.5918

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.3369

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.0332

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.8750

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4935.4209

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4937.8569

3352/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4938.6562

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4946.8242

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4951.9116

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4948.1724

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4949.3584

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4949.5918

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4947.2734

3433/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4950.3911

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4949.4009

3457/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4954.3701

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4955.7354

3480/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4955.6147

3492/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4958.2085

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4957.8550

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4957.0566

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4956.5234

3536/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4952.7139

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4950.1992

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4952.0938

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4952.6807

3581/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4953.4731

3593/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4955.3218

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4956.1021

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4954.1133

3624/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4951.9663

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4950.8184

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4950.3052

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4948.9727

3670/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4944.4214

3682/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4946.1504

3693/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4946.3643

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4949.8950 - val_loss: 229.5632

Epoch 31/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:09 35ms/step - loss: 6092.7217

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4513.4580

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4934.6997

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5124.4614

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5089.0278

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5020.6396

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4880.8657

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4952.0679

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4861.4277

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4742.1514

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4677.3774

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4650.4316

 142/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4606.9263

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4598.0723

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4685.0713

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4659.1245

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4647.4688

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4627.1978

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4586.5879

 225/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4586.1387

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4694.3062

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4718.3008

 260/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4726.7266

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4764.3623

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4755.5176

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4729.2280

 303/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4703.0620

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4694.9868

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4709.3325

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4741.4766

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4787.7485

 360/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4816.0483

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 4846.5303

 384/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4874.9663

 396/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4872.9907

 406/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4910.8706

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4925.3804

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4946.7544

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4966.3281

 452/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4981.7290

 464/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4973.0806

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4983.6992

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4989.4536

 498/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4978.1123

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4984.4014

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4995.7944

 534/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4980.6221

 546/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4964.1709

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4964.8716

 568/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4956.6572

 580/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4966.6719

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 4953.2603

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4960.3965

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4969.0171

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4982.7036

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4981.5581

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4978.5879

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5014.0649

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5016.0547

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5002.0034

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4998.8174

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5011.3726

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5002.5273

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5004.6738

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4995.3188

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4995.5938

 764/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4995.7012

 774/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5002.9155

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4994.2612

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4997.6855

 808/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5010.3569

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5007.2485

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4995.9092

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4988.9126

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4977.7495

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4987.3198

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4982.9800

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4985.0210

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4987.3560

 908/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4982.2061

 920/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4980.7437

 932/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4971.6479

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4953.4756

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4948.4194

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4944.1440

 979/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4937.6357

 991/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4930.1577

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4935.6089

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4942.2344

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4941.1982

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4944.0488

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4933.2720

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4935.4922

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4929.0586

1085/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4930.9180

1097/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4942.3042

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4941.7612

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4940.8848

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4941.7119

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4938.8545

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4955.0503

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4948.5981

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4948.9180

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4951.6509

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4938.6694

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4937.5425

1227/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4934.6387

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4927.4727

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4932.1978

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4947.5835

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4941.7783

1286/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4949.2979

1298/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4945.9727

1310/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4949.1128

1322/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4967.2959

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4967.8911

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4971.3789

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4967.9043

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4965.8530

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4970.3711

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4980.2451

1404/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4985.7944

1415/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4985.6089

1427/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4984.4551

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4989.4629

1448/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4994.3579

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4984.6284

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4981.6006

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4979.6255

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4971.0190

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.8984

1519/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4966.0430

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4967.7397

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.6372

1555/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4949.6631

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4945.3667

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.8394

1590/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.2324

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4930.1602

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4936.6758

1625/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4939.4902

1637/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4939.6235

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.4292

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.5190

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.2520

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4942.6572

1693/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4951.1919

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4953.0337

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4952.2729

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4957.2593

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4955.1147

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4952.0205

1758/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4944.0991

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4948.0869

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4951.7490

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4952.5728

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4951.7231

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4954.0513

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4953.9531

1841/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4953.1851

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4963.1514

1866/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4964.2109

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4972.1948

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4976.0811

1900/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4971.8555

1912/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 4963.6567

1924/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4960.1836

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 4959.0864

1947/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4958.7920

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.1655

1971/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4964.0928

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4962.7495

1996/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4971.4272

2008/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4974.6367

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4973.1885

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4969.7861

2043/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4968.7725

2055/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4964.3794

2066/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4967.9961

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.8618

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4969.0371

2100/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4974.4756

2111/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4972.2227

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4975.2485

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4965.2915

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4973.3945

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4983.2847

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4985.6528

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4987.1416

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4992.4736

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4987.7476

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4984.7363

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4985.3813

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4984.5127

2255/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4980.5742

2267/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4979.6934

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4979.0249

2291/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4980.0586

2303/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4975.4746

2315/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4978.4751

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4979.5952

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4977.3032

2351/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4972.2842

2363/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4972.5767

2375/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4976.1406

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4980.5098

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4980.6465

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4981.5586

2421/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4980.4634

2433/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4986.1401

2445/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4985.4580

2456/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4979.8472

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4976.4937

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4976.8604

2492/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.4268

2504/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.2002

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4970.4160

2528/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4973.0244

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4974.1929

2552/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4969.0854

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4963.4648

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4963.1323

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4959.1226

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4960.3159

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4955.8408

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4954.3330

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4952.1821

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4951.4634

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4947.1548

2670/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4951.0562

2682/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4949.1519

2694/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4943.1768

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4940.3315

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4939.3037

2729/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4942.4951

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4947.3867

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4947.1929

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4950.1230

2773/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4952.9648

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4949.0410

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4947.9517

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4950.1484

2821/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.5044

2833/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4951.8848

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4950.2393

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4950.1660

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4946.7148

2880/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4949.2344

2892/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.4590

2904/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.9702

2916/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.2900

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4947.5928

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4948.9478

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4945.6587

2962/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4943.2529

2974/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4941.9614

2985/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4942.1123

2997/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4941.5869

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4942.1787

3020/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4941.2690

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4952.4507

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4952.4512

3057/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4955.8350

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.4976

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4954.7500

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.0713

3102/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.8354

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4951.3447

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4950.0171

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4948.6577

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4948.4492

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4945.8145

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4947.9771

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4946.0835

3198/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4940.8159

3210/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4939.8481

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4937.4507

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4937.0337

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4933.9785

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4934.5894

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4939.0405

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.7632

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4936.9395

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4938.2905

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4938.3330

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4934.4912

3342/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4933.3101

3354/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4934.8560

3366/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4932.7202

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4937.0820

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4935.3740

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4933.8999

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4934.5107

3424/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4930.7524

3436/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4929.5503

3448/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4932.2817

3460/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4929.6035

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4930.4380

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.9272

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.3823

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.3511

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.0718

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4924.0117

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4923.0293

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4918.9727

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4918.8511

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4915.4810

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4915.7202

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4924.4849

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4928.4810

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.9106

3637/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4935.2817

3649/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4934.9199

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.5225

3672/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.0308

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.5728

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4922.9224

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4921.1299 - val_loss: 2109.9087

Epoch 32/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:00 33ms/step - loss: 3931.3684

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5384.0850

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5286.1738

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5126.6167

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5136.7979

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5065.4443

  72/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4925.1646

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5080.3428

  95/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5009.0415

 106/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4979.2979

 117/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4899.4048

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4764.3452

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4843.0444

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4838.2471

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4944.7881

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4885.2661

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4900.1860

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4910.4092

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4906.4629

 225/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4932.1064

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4936.2812

 249/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4891.5430

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4888.2705

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4842.5864

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4835.2114

 294/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4824.5532

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4810.6064

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4778.8394

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4807.7407

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4794.4946

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4808.5010

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4848.6772

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4877.1133

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4872.5757

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4890.3486

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4877.5596

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4888.0479

 438/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4857.7100

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.1743

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4899.6968

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4906.9365

 484/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4884.3848

 496/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4887.8306

 508/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4888.3799

 520/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4878.0645

 532/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4873.5439

 544/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4893.0239

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4919.4517

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4930.1172

 579/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4919.4321

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4915.2676

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4916.8125

 613/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4930.7129

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4948.4141

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4939.0225

 650/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4929.8506

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4936.1689

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4940.1768

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4933.3467

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4916.9277

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4918.3433

 721/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4921.6318

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4919.5918

 745/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4927.2510

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4913.5415

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4918.9336

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4917.5908

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4899.4307

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4895.4390

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4886.4014

 825/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4895.3042

 837/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4904.8486

 849/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4886.8672

 861/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4882.6807

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4884.6797

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4881.0894

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4878.5591

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4870.2231

 918/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4870.1074

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4869.4639

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4868.0762

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4863.2183

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4865.0161

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4859.7129

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4863.7461

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4854.5015

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4847.5054

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4843.7935

1034/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4853.8232

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4868.8911

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4852.9829

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4854.8125

1081/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4856.9941

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4864.7266

1105/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4879.9321

1117/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4889.2930

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4888.0859

1141/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4877.3892

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4886.5420

1162/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4891.5840

1174/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4905.2666

1184/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4902.1733

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4903.6914

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4903.9893

1216/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4900.1958

1227/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4904.6245

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4901.3804

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4900.2310

1262/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4903.4707

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4909.4639

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4909.3452

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4903.6982

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4903.5723

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4914.9810

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4917.5317

1347/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4910.7280

1358/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4911.9775

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4921.6060

1380/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4928.5459

1392/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.8042

1404/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.7124

1416/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4926.4204

1428/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4921.9976

1439/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4913.8872

1450/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4912.3179

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4911.4121

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4911.9702

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4911.2520

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4906.4546

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4901.5122

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4897.2148

1530/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4897.2280

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4902.0093

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4901.7759

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4892.2202

1576/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4883.7339

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4884.5757

1599/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4882.4634

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4892.2866

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4902.2427

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4907.1162

1645/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4900.2134

1656/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4894.2212

1667/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4903.4429

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4901.9097

1693/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4905.4692

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4905.4678

1717/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4903.6011

1729/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4899.7554

1740/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4905.3667

1752/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4902.8813

1764/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4897.2241

1776/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4895.2969

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4895.0542

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4891.4526

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4898.3286

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4897.0049

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4901.2676

1846/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4893.9370

1858/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4888.9409

1870/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4895.8008

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4892.0142

1894/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4899.9937

1905/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4895.4639

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4894.9004

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4903.2290

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4895.3804

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4898.4790

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4903.7808

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4902.7568

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4906.2183

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4910.2988

2008/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4905.3911

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4909.2642

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4905.0244

2043/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4907.4990

2055/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4904.8994

2067/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4904.2832

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4915.5586

2090/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4915.0933

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4919.4707

2112/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4917.2544

2124/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4913.0391

2136/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4918.8604

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4919.2622

2160/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4914.0454

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4913.4131

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4910.8237

2196/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4914.3418

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4910.1367

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4917.6514

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4917.0430

2241/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4915.7920

2253/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4918.8628

2265/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4916.4019

2277/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4917.3154

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4921.1597

2299/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4930.3848

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4926.6777

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4925.0913

2334/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4921.3662

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4918.3076

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4919.7739

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.2441

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4917.5806

2394/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4915.0488

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4913.0205

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4910.6528

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4909.3013

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4904.5889

2454/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4904.5801

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4903.3032

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4909.8740

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4913.7583

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4911.6152

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4908.1338

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4906.6875

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4904.6772

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4909.8398

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4906.2798

2569/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4903.0986

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4904.9722

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4908.2705

2605/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4912.3330

2617/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4909.8140

2629/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4905.4365

2641/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4904.4551

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4907.7319

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4904.7007

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4901.8169

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4902.5947

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4898.5298

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4898.3638

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4901.0405

2735/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4901.6313

2746/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4897.6484

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4898.9116

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4898.1279

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4894.4116

2794/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4894.7344

2806/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4893.7412

2818/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4895.5825

2830/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4890.2583

2842/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4893.1543

2854/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4893.6509

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4898.2290

2879/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4893.6133

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4896.2388

2902/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4902.1289

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4900.4600

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4906.5366

2937/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4909.3848

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4911.3008

2961/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4911.1890

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4912.4287

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4915.9038

2996/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4913.6284

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4916.1060

3020/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4914.1436

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4912.2095

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4911.9868

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4911.9951

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4911.9863

3080/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4911.4307

3091/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4915.1450

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4919.6084

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4920.9604

3128/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4920.2222

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4925.1309

3150/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4928.2881

3161/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4927.1694

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4926.1499

3185/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4928.3433

3196/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4928.3042

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4926.3140

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4926.7783

3229/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4925.1646

3241/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4924.7124

3253/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4922.3315

3265/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4920.9854

3277/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4921.1929

3289/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4923.7720

3301/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4925.0532

3313/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4925.1592

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4923.1421

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4924.1509

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4924.0659

3361/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4923.1328

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.8369

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.3384

3395/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.5225

3407/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4927.8477

3419/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.1606

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.0889

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4926.4507

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4924.0981

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4924.5977

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4927.4180

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.9722

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.0913

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.5107

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.2959

3535/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4925.7271

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4927.1816

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4926.2676

3570/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.3657

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.7749

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4933.9258

3606/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4933.8706

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4934.3325

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.6445

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.9932

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.0771

3664/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4931.6816

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4932.1562

3688/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4930.6440

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4929.6616

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4929.5986 - val_loss: 1056.8975

Epoch 33/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:14 36ms/step - loss: 3865.8960

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 6125.8086

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5889.8677

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6045.7153

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5810.7788

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5551.8877

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5406.6689

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5386.7358

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5394.1138

 107/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5296.7607

 118/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5335.5688

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5420.5386

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5425.5933

 153/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5376.5054

 165/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5383.6040

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5335.8345

 188/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5356.5000

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5283.0581

 212/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5208.6953

 224/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5222.4868

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5197.0708

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5267.9648

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5216.3081

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5210.2974

 281/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5184.0317

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5153.9746

 306/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5130.8579

 318/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5111.3008

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5103.6582

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5150.9038

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5140.6772

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5117.3950

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5097.3335

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5077.3633

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5062.5679

 412/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5070.9771

 422/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5055.5601

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5113.4570

 445/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5133.4673

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5159.8931

 467/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5172.6489

 479/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5183.7451

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5201.6221

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5183.5913

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5166.1729

 526/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5163.7905

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5148.5630

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5147.2300

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5130.4604

 573/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5113.3228

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5103.5742

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5083.9971

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5114.3096

 624/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5111.8867

 635/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5095.4390

 647/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5099.6328

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5090.5083

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5077.5625

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5096.2358

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5078.6016

 703/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5079.2485

 713/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5075.0811

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5081.0098

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5080.6040

 747/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5081.6562

 757/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5075.4644

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5066.3994

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5052.2466

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5036.6562

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5032.9556

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5043.2871

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5034.5029

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5031.3501

 852/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5035.1343

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5033.8745

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5020.8110

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5019.7241

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5035.3208

 911/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5053.8481

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5056.9683

 934/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5053.7754

 947/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5060.2168

 959/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5057.2563

 971/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5053.8667

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5048.2056

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5032.2578

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5029.0205

1020/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5034.3428

1032/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5039.2456

1044/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5034.8701

1056/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5039.9502

1068/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5032.7275

1078/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5032.6465

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5030.3965

1100/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5017.4873

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5015.0459

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5016.2397

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5006.4429

1147/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5005.9419

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5002.8306

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4996.4395

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5004.8530

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5005.0903

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5006.4697

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5007.3730

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5008.8003

1242/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5012.0269

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4999.3193

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4992.8164

1278/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4989.6318

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4990.7422

1302/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4997.4951

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5004.2671

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5004.5547

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5007.5024

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5007.6094

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5009.0947

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5005.9282

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4999.4937

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4997.3691

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4999.1577

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5009.7788

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5013.1353

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5011.5493

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5016.6924

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5027.1323

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5023.1519

1491/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5020.7959

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5027.4971

1515/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5023.2617

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5014.2544

1539/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5012.3433

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5006.7500

1563/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5010.9824

1575/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5006.2930

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5008.1948

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5004.3823

1609/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4997.6245

1621/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4994.1924

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4996.8604

1644/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4990.7021

1656/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4983.1172

1668/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4981.9639

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4982.0513

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4985.2446

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4984.4375

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4985.4482

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4987.8550

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4986.6982

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4987.7314

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4990.8413

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4985.6411

1781/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4986.1650

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4988.4448

1803/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4984.4106

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4990.4287

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4992.5601

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4993.1948

1850/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4997.7529

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4997.7329

1872/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4998.9272

1884/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4989.4751

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4984.4565

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4986.8447

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4988.8892

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4986.0454

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4984.9238

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4984.0796

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4987.8105

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4987.8716

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4983.6235

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4980.8184

2010/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4979.3735

2022/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4973.4839

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4971.4937

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4979.5112

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4977.9023

2067/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4970.7109

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4972.8223

2091/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4970.1802

2103/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4966.3066

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4972.9883

2127/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4965.4521

2139/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4958.3159

2151/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4954.8975

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4951.0850

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4940.2383

2186/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4937.3682

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4938.0552

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4937.5947

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4938.3379

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4937.9004

2245/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4941.1787

2257/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4945.8672

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4945.7080

2281/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4947.8340

2293/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4945.8408

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4941.3906

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4935.9165

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4937.6777

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4933.2183

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4929.1582

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4925.7876

2376/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4927.4717

2388/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4928.1831

2398/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4925.9712

2410/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4922.9023

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4921.5996

2434/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4919.8232

2443/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4923.8530

2452/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4921.4375

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.1030

2472/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4922.4536

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4922.3086

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4921.2539

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.9023

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4921.6538

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4921.7964

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4919.5420

2547/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4920.0874

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4917.4248

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4913.4023

2578/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4913.1909

2589/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4916.2739

2600/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4918.4341

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4914.4673

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4917.6797

2632/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4915.1133

2641/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4911.0884

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4914.0205

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4913.1143

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4914.8472

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4913.5566

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4915.5859

2698/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4917.1187

2709/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4916.5737

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4915.1353

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4920.1885

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4920.4116

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4921.7881

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4922.5283

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4920.1807

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4919.0566

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4919.1333

2810/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4923.1475

2819/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 4921.7114

2830/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4920.3838

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4920.6367

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4923.3325

2858/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4924.1489

2867/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4918.7007

2875/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4917.7915

2882/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4920.0908

2889/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4915.5005

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4915.6055

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4912.6172

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4910.6963

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4909.7505

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4907.8975

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4908.5508

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4909.1201

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4909.7139

2957/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4909.6904

2965/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4909.6050

2973/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4906.9297

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4905.6958

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4905.6567

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4904.4780

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4901.7192

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4898.7954

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4898.5073

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4899.5835

3044/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4898.3613

3053/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 4896.8384

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4896.4614

3073/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4895.9766

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4892.8521

3093/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4890.3945

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4886.9038

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4890.5312

3124/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4891.4058

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4889.5879

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4888.3564

3158/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4886.8560

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4881.4033

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4886.1265

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4884.0957

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4885.4648

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4885.7759

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4885.0342

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4883.2314

3250/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4883.5835

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4881.5215

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4879.3672

3286/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4879.4346

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4882.2222

3309/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4883.1279

3321/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4886.8545

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4889.8945

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4893.9014

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4897.0908

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4899.6968

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4905.4780

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4906.1665

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4906.8662

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4906.9663

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4902.9932

3440/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4902.2397

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4901.6841

3463/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4901.1514

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4904.6367

3485/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4903.6396

3497/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4906.0630

3509/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4909.9365

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4907.5410

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4906.3218

3541/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4908.2407

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4911.4448

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4911.5679

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4911.4844

3589/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4915.1270

3601/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4920.7920

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4919.6685

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4919.9180

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4918.2363

3649/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4919.1611

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4918.3584

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4917.9331

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4920.8081

3696/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4917.7065

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 4918.0190 - val_loss: 128.9516

Epoch 34/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:18 37ms/step - loss: 5483.3804

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4278.8477

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4681.0635

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4433.4956

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4288.9204

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4362.7715

  72/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4369.4531

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4407.1372

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 4469.8770

 108/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4394.4937

 119/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4386.5396

 130/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4481.3413

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4419.0200

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4470.4927

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4495.9956

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4546.5625

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4592.4282

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4627.4424

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4599.4668

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4573.4697

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4502.6221

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4471.6318

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4502.3901

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4517.4683

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4483.2939

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4483.9722

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4481.9756

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4474.2842

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4502.5068

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4549.1460

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4562.9536

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4561.7866

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4568.2710

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4576.1162

 400/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4574.0864

 411/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4580.6714

 422/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4598.8818

 434/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4628.5269

 446/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4604.0356

 458/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4617.0054

 470/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4617.5957

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4610.2310

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4598.3354

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4597.3906

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4581.7842

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4590.1973

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4610.9751

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4634.9868

 562/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4639.3105

 573/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4643.9282

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4654.1309

 597/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4664.3765

 609/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4666.3218

 621/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4667.8364

 633/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4661.9297

 644/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4660.5962

 656/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4648.7236

 668/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4653.5762

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4644.3789

 691/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4637.5620

 701/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4637.1953

 712/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4635.6880

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4641.1924

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4647.7495

 747/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4648.1533

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4645.6958

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4637.6069

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4642.4141

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4645.3418

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4642.2041

 814/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 4654.2207

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4669.9253

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4683.0713

 849/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4683.5054

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4685.4839

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4698.3594

 883/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4688.7417

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4687.1475

 905/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4688.5566

 917/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4678.6650

 929/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4675.2046

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4684.6069

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4684.0107

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4691.1040

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4698.5161

 986/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4692.3232

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4689.4580

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4693.1860

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4697.5688

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 4699.8765

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4698.3745

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4699.6792

1065/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4705.1108

1077/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4707.7012

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4703.7275

1100/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4708.3804

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4705.8193

1123/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4714.9419

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4711.5161

1147/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4713.1577

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4726.6885

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4725.2974

1183/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4742.1147

1195/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 4738.3291

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4740.6118

1219/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4742.0889

1231/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4743.3691

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4744.3994

1255/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4751.0591

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4748.0649

1278/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4747.3789

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4750.3188

1302/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4749.6924

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4751.7290

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4751.3325

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4736.1631

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4738.8833

1359/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4739.7412

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4734.7280

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4731.4805

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4734.7603

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4726.8047

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4727.3140

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4728.6084

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4739.4180

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4741.3896

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4745.4600

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4747.2905

1490/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4753.7725

1502/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4754.7432

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4749.5298

1526/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4743.1060

1538/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4741.5195

1549/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4743.6357

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4741.7163

1571/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4748.9414

1583/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4750.2461

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4745.7363

1605/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4749.7920

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4750.6797

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4755.6870

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4755.0107

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4757.1504

1664/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4752.7344

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4757.2207

1685/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4761.2153

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4763.6938

1710/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4765.2300

1721/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4766.4658

1733/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4760.8975

1745/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4757.4883

1757/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4753.8765

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4756.2021

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4769.0688

1791/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4776.4419

1803/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4777.2656

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4773.8096

1826/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4778.6953

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4775.0405

1850/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4781.4121

1862/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4782.6460

1874/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4780.9683

1886/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4780.1426

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4780.4521

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4779.8623

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4772.4023

1933/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4774.9341

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4773.7109

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4780.9028

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4781.3428

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4778.4980

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4778.2520

2003/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4781.3569

2012/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4785.2715

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4782.6978

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4783.9868

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4780.2148

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4776.7129

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4777.9868

2084/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4779.0674

2096/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4776.6455

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4779.5684

2120/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4775.4990

2132/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4777.6860

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4773.6836

2156/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4773.7300

2167/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4778.9502

2178/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4780.2739

2189/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4785.1147

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4787.5073

2212/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4786.1582

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4791.1626

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4790.5078

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4788.2578

2258/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4784.3154

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4789.3262

2281/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4793.3228

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4798.0581

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4802.7964

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4800.2334

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4802.7495

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4800.2803

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4802.3062

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4800.7529

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4798.9873

2386/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4793.7988

2398/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4797.8101

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4799.3760

2421/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4795.9893

2433/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4792.8447

2444/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4793.5820

2455/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4791.7783

2467/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4788.3691

2479/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4789.2969

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4788.9048

2502/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4789.5776

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4789.9097

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4792.6030

2536/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4792.1929

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4792.1987

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4792.2227

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4791.4097

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4791.9819

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4790.1748

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4787.0625

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4789.9087

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4785.7998

2639/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4783.0620

2650/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4781.2202

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4781.3228

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4782.5068

2684/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4779.1377

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4779.1006

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4780.1411

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4782.5288

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4780.7979

2742/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4778.7734

2753/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4778.2261

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4777.6133

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4778.4062

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4776.0635

2801/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4776.9185

2813/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4773.6714

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4776.3306

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4774.6650

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4774.6489

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4776.7729

2870/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4776.5010

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4774.5122

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4771.9775

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4768.1372

2916/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4769.5029

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4764.3735

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4762.4053

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4758.2939

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4759.7573

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4759.3149

2987/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4761.0327

2996/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4760.8828

3008/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4759.4663

3020/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4759.7153

3032/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4761.6948

3043/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4761.0527

3055/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4761.0024

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4760.4629

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4758.0688

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4757.6934

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4756.1177

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4756.1421

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4754.1318

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4753.2290

3146/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4755.6182

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4756.1025

3168/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4759.6255

3180/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4759.8076

3192/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4762.3579

3204/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4760.5791

3216/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4759.3784

3227/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4759.7734

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4760.6875

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4763.2886

3262/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4766.6211

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4766.3101

3286/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4765.1289

3297/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4768.4819

3309/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4768.1699

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4770.7568

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4769.0942

3343/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4768.6050

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4773.4438

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4773.0854

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4774.0552

3389/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4777.7930

3399/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4778.3315

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4778.7861

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4784.1353

3434/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4784.9194

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4784.1143

3457/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4784.2734

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4784.1372

3481/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4784.3345

3493/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4786.3872

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4787.6196

3517/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4784.2832

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.6328

3541/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.4521

3552/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4783.4800

3564/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.6172

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4781.7773

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.0737

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4783.0371

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4784.5566

3622/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4783.3472

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4780.5449

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4781.5010

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4779.1499

3668/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4778.8955

3680/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.7202

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4782.8320

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4780.5854 - val_loss: 313.3871

Epoch 35/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:07 34ms/step - loss: 5631.4990

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 3914.8884

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4380.5845

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4203.0488

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4799.5591

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5223.4570

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5257.4780

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5196.4600

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5194.9346

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5233.3755

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5217.7461

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5125.9761

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5060.3369

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5001.0439

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4940.3550

 181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4883.7622

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4906.6802

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4922.4409

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4949.1538

 228/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4940.4106

 240/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4969.7930

 252/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4911.1899

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4926.9741

 275/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4876.8745

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4856.9678

 299/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4896.1118

 311/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4889.8066

 324/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4885.3672

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4874.2300

 347/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4879.9321

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4849.5869

 370/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4845.1978

 382/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4838.5669

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4865.2656

 406/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4867.0938

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4852.1514

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4858.1377

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4865.5527

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4860.2021

 463/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4851.5654

 475/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4848.1152

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4846.8730

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4852.6821

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4851.1880

 520/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4854.6528

 531/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4849.1919

 544/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4850.0811

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4869.6060

 567/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4880.8599

 579/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4871.6167

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4890.7119

 603/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4890.5679

 615/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4889.0186

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4880.4917

 639/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4880.0166

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4859.9600

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4853.1797

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4849.8218

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4835.8408

 697/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4842.4253

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4839.4922

 721/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4829.3408

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4838.4399

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4837.4131

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4812.9238

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4815.2358

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4826.2690

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4830.0850

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4833.1235

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4833.3418

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4834.2744

 834/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4822.5635

 846/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4822.8062

 858/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4819.8022

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4832.9814

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4825.4893

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4815.5396

 906/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4808.8735

 918/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4816.9321

 930/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4819.9927

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4810.0112

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4798.2104

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4803.2163

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4794.6860

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4794.0952

1001/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4799.0835

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4802.0908

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4800.5869

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4794.6157

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4810.0415

1060/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4806.5337

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4811.4937

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4804.9580

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4802.4868

1109/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4800.3125

1121/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4792.9272

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4787.8525

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4793.1558

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4787.5112

1166/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4786.6177

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4785.3613

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4777.2778

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4781.0654

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4784.6519

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4795.2861

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4801.2573

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4800.1357

1261/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4805.9580

1273/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4803.8848

1286/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4810.7749

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4812.6138

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4818.7529

1322/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4818.4551

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4814.6553

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4812.1680

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4806.6763

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4813.2373

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4815.1104

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4809.6011

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4810.3135

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4818.3608

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4818.6001

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4832.3550

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4838.3228

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4838.5098

1477/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4836.8608

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4834.3120

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4832.5430

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4828.3530

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4828.8403

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4827.2368

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4827.0776

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4830.4868

1570/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4834.1289

1581/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4835.3628

1593/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4844.1553

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4850.9448

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4848.9087

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4849.4395

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4855.2700

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4860.6777

1664/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4863.4194

1676/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4859.8135

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4863.5317

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4863.9131

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4870.4634

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4875.9370

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4882.7568

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4883.6279

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4884.7480

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4893.5469

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4898.7617

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4897.6152

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4902.6323

1822/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4902.1592

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4899.0259

1843/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4900.4639

1856/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4894.6899

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4897.2422

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4906.1372

1892/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4908.4395

1904/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4909.5112

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4911.5078

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4916.0835

1939/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4923.9111

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4925.1362

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4926.5605

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4925.2861

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4926.4771

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4934.3315

2010/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4932.0854

2022/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4927.1626

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4927.9180

2046/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4930.7695

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4923.9761

2070/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4919.4570

2082/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4933.5825

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4931.1533

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4925.1514

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4922.2969

2126/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4915.4463

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4918.2280

2149/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4910.9512

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4907.2617

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4902.8887

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4898.5098

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4892.9175

2205/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4891.2749

2217/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4891.2393

2229/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4890.3994

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4886.3364

2252/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4887.4023

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4888.0068

2276/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4883.0435

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4880.2583

2299/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4877.8374

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4874.6543

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4874.7207

2335/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4873.2549

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4872.9595

2359/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4875.6494

2371/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4878.6440

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4879.1543

2394/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4876.5996

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4873.9062

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4871.6562

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4874.1206

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4872.4004

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4869.0674

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4873.9775

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4873.9648

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4881.3423

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4883.7334

2509/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4890.6597

2520/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4888.9531

2532/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4890.7578

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4894.1772

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4895.0840

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 4892.9380

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4892.1221

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4893.4883

2603/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4894.2495

2615/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4895.7310

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4892.6602

2639/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4889.2148

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4886.3394

2662/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4885.4253

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4885.3979

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4885.7383

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4884.7637

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4884.3599

2722/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4882.8975

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4881.9429

2746/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4883.4170

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4885.9028

2769/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4893.0498

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4890.8462

2794/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 4889.3457

2806/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4888.3979

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4884.6860

2827/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4886.5029

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4884.5645

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4883.9946

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4882.4922

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4880.3413

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4880.9062

2899/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4878.1201

2911/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4877.1299

2923/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4874.1240

2934/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4874.9165

2947/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4874.6533

2960/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4875.5396

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4876.0410

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4873.2500

2995/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4869.0015

3006/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4866.1348

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 4867.6133

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4868.6519

3040/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4866.8066

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4865.2017

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4864.5352

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4864.8071

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4866.8501

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4867.7603

3110/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4875.2100

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4877.6602

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4876.9980

3143/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4875.9595

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4876.3071

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4874.4224

3179/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4871.2725

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4867.9995

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4866.2319

3215/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4863.2124

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4860.6450

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4860.8750

3251/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4856.8281

3263/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.4546

3275/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.5596

3287/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4858.3735

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4857.3633

3310/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4856.3237

3321/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.4526

3333/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4858.0869

3345/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.4272

3357/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4854.9434

3369/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4853.7251

3381/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.7617

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4854.2871

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4855.3149

3417/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4854.2554

3430/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4854.3530

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4853.0835

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4850.3140

3466/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 4850.6729

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4851.8691

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4849.1572

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4850.7378

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4852.7007

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4849.1743

3537/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4847.7681

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4845.3384

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4849.5161

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4851.2285

3585/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4851.4277

3597/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4851.2607

3609/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4855.1079

3621/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4857.5200

3632/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4854.4888

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4855.7026

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4856.0801

3668/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4855.1934

3680/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4857.7686

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4857.7256

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 4859.4956 - val_loss: 119.7516

In [16]:
# and you can show how your model did

# since it's a single sample, we need to reshape
data = X[0]
data = data.reshape(1,10,7)
print(data)
print(model.predict(data))

# did we get close?
print(y[0])
# of course you can show scatterplots and everything else

[[[ 17.96  59.1  190.     5.     0.    30.09  10.  ]
  [ 19.94  59.4  190.     5.     0.    30.08  10.  ]
  [ 23.    49.69 210.     9.     0.    30.06  10.  ]
  [ 21.92  47.52 230.    11.     0.    30.04  10.  ]
  [ 23.    43.21 250.    13.     0.    30.05  10.  ]
  [ 23.    43.21 250.    11.     0.    30.06  10.  ]
  [ 23.    41.45 240.    13.     0.    30.07  10.  ]
  [ 24.08  41.3  240.    11.     0.    30.08  10.  ]
  [ 26.06  38.03 210.     8.     0.    30.08  10.  ]
  [ 28.04  35.05 220.    14.     0.    30.08  10.  ]]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step

[[  21.629856 1021.6726  ]]
[   3.92 1018.8 ]

In [17]:
# well done! You can also make scatterplots of actual vs. predicted
pred = model.predict(X)
pred

   1/1446 ━━━━━━━━━━━━━━━━━━━━ 6:40 277ms/step

  30/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  61/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  92/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 122/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 152/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 182/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 211/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 239/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 268/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 297/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 324/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 352/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 379/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 406/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 434/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 461/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 482/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 510/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 537/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 564/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 591/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 619/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 647/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 675/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 702/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 730/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 758/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 785/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 813/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 841/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 868/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 894/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 921/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 949/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 977/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1004/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1031/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1059/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1087/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1114/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1140/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1167/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1194/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1222/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1248/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1271/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1299/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1327/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1355/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1382/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1410/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1438/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1446/1446 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

array([[  21.629856, 1021.6726  ],
       [  21.618145, 1022.8693  ],
       [  21.108383, 1025.4362  ],
       ...,
       [  29.005615, 1021.16064 ],
       [  29.12322 , 1020.1032  ],
       [  29.562777, 1020.2228  ]], shape=(46263, 2), dtype=float32)

In [18]:
# pred1
plt.scatter(y[:,0], pred[:,0])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_44120\3040812647.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [19]:
# pred2
plt.scatter(y[:,1], pred[:,1])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_44120\898290747.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# it worked! predict two outputs at once -
# may have taken longer to fit,
# but it worked great!

# you may also try other architectures
# and advanced methods (Conv1D and MaxPooling1D etc)