<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/a_Many_To_Many_BDL_tmpf_and_vsby.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 15 — Many-to-many: two targets at once, then multi-step ahead
- Flavor A (this notebook): predict SEVERAL targets at once - both Y columns placed LAST because split_sequences chops from the right; Dense(2, linear) so one LSTM's weights are shaped by both targets ('borrow strength').
- Flavor B (notebook b_): MULTI-STEP - forecast the next 3 hours (3 outputs); quality degrades further out.
- One recurrent model doing a whole forecasting job - the most general setup in the module.
- Keep to 8 minutes: the 2022 video ran 8:05.
-->

# a_Many To Many (Numeric Sequences)
------------------------------------
**Dr. Dave Wanik - University of Connecticut**

[y is two different variables, at (one) the same timestep]

Let's read in the BDL data and see if we can *predict two quantities at once*! Dewpoint (dwpf) and Mean Sea-level Pressure (mslp).

In [1]:
# import modules
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
#from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
#from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.layers import Input
#from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

In [2]:
# # https://drive.google.com/file/d/1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS/view?usp=sharing
# !gdown 1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS
# # read the data
# df = pd.read_csv('../data/cleanBDL.csv')

In [3]:
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/cleanBDL.csv"

# retrieve the CSV data and build a dataframe
df = pd.read_csv(url)

df.shape

(46272, 10)

In [4]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 46272 entries, 0 to 46271
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valid   46272 non-null  str
 1   tmpf    46272 non-null  float64
 2   dwpf    46272 non-null  float64
 3   relh    46272 non-null  float64
 4   drct    46272 non-null  float64
 5   sknt    46272 non-null  float64
 6   p01i    46272 non-null  float64
 7   alti    46272 non-null  float64
 8   mslp    46272 non-null  float64
 9   vsby    46272 non-null  float64
dtypes: float64(9), str(1)
memory usage: 4.4 MB

,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby
0,2015-01-01 00:00:00,17.96,6.08,59.10,190.0,5.0,0.0,30.09,1019.0,10.0
1,2015-01-01 01:00:00,19.94,8.06,59.40,190.0,5.0,0.0,30.08,1018.7,10.0
2,2015-01-01 02:00:00,23.00,6.98,49.69,210.0,9.0,0.0,30.06,1018.1,10.0
3,2015-01-01 03:00:00,21.92,5.00,47.52,230.0,11.0,0.0,30.04,1017.4,10.0
4,2015-01-01 04:00:00,23.00,3.92,43.21,250.0,13.0,0.0,30.05,1017.7,10.0

# Define X and Y
If we are going to use our split sequences script from Brownlee, then we need to make sure our Y variables are on the end!

In [5]:
# let's drop the valid column
# Y will be dwpf and relh
# X will be everything else!

del df['valid']
df.head() # check your work

    tmpf  dwpf   relh   drct  sknt  p01i   alti    mslp  vsby
0  17.96  6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0
1  19.94  8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0
2  23.00  6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0
3  21.92  5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0
4  23.00  3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0

In [6]:
Y = df[['dwpf', 'mslp']]
X = df.drop(columns=['dwpf', 'mslp'])
print(df.shape, X.shape, Y.shape)

# looks good! Let's prepare samples for modeling

(46272, 9) (46272, 7) (46272, 2)

In [7]:
# put Y all the way on the left
df = pd.concat([X, Y], axis=1, sort=False)
df.head(n=11)

     tmpf   relh   drct  sknt  p01i   alti  vsby  dwpf    mslp
0   17.96  59.10  190.0   5.0   0.0  30.09  10.0  6.08  1019.0
1   19.94  59.40  190.0   5.0   0.0  30.08  10.0  8.06  1018.7
2   23.00  49.69  210.0   9.0   0.0  30.06  10.0  6.98  1018.1
3   21.92  47.52  230.0  11.0   0.0  30.04  10.0  5.00  1017.4
4   23.00  43.21  250.0  13.0   0.0  30.05  10.0  3.92  1017.7
5   23.00  43.21  250.0  11.0   0.0  30.06  10.0  3.92  1018.1
6   23.00  41.45  240.0  13.0   0.0  30.07  10.0  3.02  1018.4
7   24.08  41.30  240.0  11.0   0.0  30.08  10.0  3.92  1018.9
8   26.06  38.03  210.0   8.0   0.0  30.08  10.0  3.92  1018.9
9   28.04  35.05  220.0  14.0   0.0  30.08  10.0  3.92  1018.8
10  30.02  33.97  210.0  10.0   0.0  30.07  10.0  5.00  1018.4

In [8]:
# some eda
df.plot.scatter(x='tmpf', y='dwpf')
df.plot.scatter(x='alti', y='mslp')

In [9]:
# to get our other code to run, we will put Y
# on the end then re-run our code (needs updating from blog)

# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
    # X and Y have been UPDATED so the last two columns drop off
		# USERS NEED TO UPDATE THIS FOR THEIR OWN PROBLEMS!!!
		seq_x, seq_y = sequences[i:end_ix, :-2], sequences[end_ix-1, 7:]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# Prepare Samples for Modeling
Everything needs to be in 3D arrays.

In [10]:
# let's turn X into lookbacks of 10 with all of our samples
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [11]:
# check your work
print(df.shape, X.shape, y.shape)

(46272, 9) (46263, 10, 7) (46263, 2)

In [12]:
# here's the first X
X[0]

array([[ 17.96,  59.1 , 190.  ,   5.  ,   0.  ,  30.09,  10.  ],
       [ 19.94,  59.4 , 190.  ,   5.  ,   0.  ,  30.08,  10.  ],
       [ 23.  ,  49.69, 210.  ,   9.  ,   0.  ,  30.06,  10.  ],
       [ 21.92,  47.52, 230.  ,  11.  ,   0.  ,  30.04,  10.  ],
       [ 23.  ,  43.21, 250.  ,  13.  ,   0.  ,  30.05,  10.  ],
       [ 23.  ,  43.21, 250.  ,  11.  ,   0.  ,  30.06,  10.  ],
       [ 23.  ,  41.45, 240.  ,  13.  ,   0.  ,  30.07,  10.  ],
       [ 24.08,  41.3 , 240.  ,  11.  ,   0.  ,  30.08,  10.  ],
       [ 26.06,  38.03, 210.  ,   8.  ,   0.  ,  30.08,  10.  ],
       [ 28.04,  35.05, 220.  ,  14.  ,   0.  ,  30.08,  10.  ]])

In [13]:
# here's the first Y
y[0]

# go scroll up and make sure this matches!
# and it does!

# you will need to customize your split script when
# prepping your data... be careful! take control of your data!

array([   3.92, 1018.8 ])

In [14]:
df.head(n=15)

     tmpf   relh   drct  sknt  p01i   alti  vsby  dwpf    mslp
0   17.96  59.10  190.0   5.0   0.0  30.09  10.0  6.08  1019.0
1   19.94  59.40  190.0   5.0   0.0  30.08  10.0  8.06  1018.7
2   23.00  49.69  210.0   9.0   0.0  30.06  10.0  6.98  1018.1
3   21.92  47.52  230.0  11.0   0.0  30.04  10.0  5.00  1017.4
4   23.00  43.21  250.0  13.0   0.0  30.05  10.0  3.92  1017.7
5   23.00  43.21  250.0  11.0   0.0  30.06  10.0  3.92  1018.1
6   23.00  41.45  240.0  13.0   0.0  30.07  10.0  3.02  1018.4
7   24.08  41.30  240.0  11.0   0.0  30.08  10.0  3.92  1018.9
8   26.06  38.03  210.0   8.0   0.0  30.08  10.0  3.92  1018.9
9   28.04  35.05  220.0  14.0   0.0  30.08  10.0  3.92  1018.8
10  30.02  33.97  210.0  10.0   0.0  30.07  10.0  5.00  1018.4
11  32.00  32.93  240.0  13.0   0.0  30.03  10.0  6.08  1017.2
12  33.08  31.53  220.0  15.0   0.0  29.99  10.0  6.08  1015.7
13  33.98  31.69  220.0  15.0   0.0  29.94  10.0  6.98  1014.2
14  33.08  31.53  220.0  12.0   0.0  29.93  10.0  6.08  1013.7

# Fit a Model
This will be similar to the last example in 'Sequence Problems_Pt1.ipynb'

In [15]:
# note how there's a 2 at the end
# usually we did this for a multi-classification problem, but not today!
# by default, it's a 'linear' activiation function
# so this is 2 node output and we're doing regression.

n_steps = X.shape[1]
n_features = X.shape[2]

model = Sequential()
model.add(LSTM(50, activation='relu',
               recurrent_dropout = 0.1,
               input_shape=(n_steps, n_features)))
model.add(Dropout(0.2))
model.add(Dense(2)) # since Y has two values, we need to predict two values
model.compile(optimizer='adam', loss='mse')

import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in
# the validation loss for 10 consecutive epochs.
es = keras.callbacks.EarlyStopping(monitor='val_loss',
                                   mode='min',
                                   patience=10, # you can play with this!
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(X,
                    y,
                    callbacks=[es],
                    epochs=800, # you can set this to a big number!
                    batch_size=10,
                    validation_split=0.2,
                    verbose=1)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/800

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:01:51 2s/step - loss: 502519.1875

  16/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - loss: 468901.4062

  30/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 420863.5312

  43/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 343662.3125

  55/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 296525.0312

  66/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 268403.1250

  77/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 245134.9688

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 225498.8438

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 213813.2812

 108/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 202329.6094

 119/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 190867.2344

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 182654.9062

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 175954.2656

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 171459.6719

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 166596.3750

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 161739.0312

 172/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 157313.9844

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 153025.8594

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 150391.5938

 188/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 149436.1562

 191/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 148159.9844

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 145194.4688

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 141917.3438

 214/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 139076.8281

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 136135.8281

 230/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 133444.5156

 239/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 130710.1484

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 128050.2188

 256/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 125747.6406

 265/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 123397.8438

 274/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 121251.9141

 284/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 119203.8516

 294/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - loss: 117198.4531

 305/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 114954.1797

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 113054.5625

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 111408.7578

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 109287.4297

 347/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 107416.7500

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - loss: 106621.3438

 370/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 105591.2812

 382/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 104095.6250

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 102763.8203

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 101426.4844

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 6ms/step - loss: 99861.6328

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 98683.8828

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 97455.2656

 454/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 96308.5938

 466/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 95132.6641

 478/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 93667.4688

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 92587.6875

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 91281.9062

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 90093.4688

 526/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 89125.1641

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 87976.2109

 549/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 87033.2656

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 86001.1172

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 85015.1562

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 83962.6250

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 83337.8828

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 82493.8125

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 81765.2656

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 80900.6094

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 80133.6172

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 79437.8281

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 78867.4922

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 78620.0312

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 78177.8281

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 77530.4922

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 76931.4375

 733/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 76313.6875

 745/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 75800.9219

 757/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 75157.6719

 770/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 74621.0469

 783/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 74093.2344

 795/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 73474.9766

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 72959.4453

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 72377.6094

 831/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 71863.0312

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 71333.8516

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 71180.1094

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 71036.0781

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 70611.6094

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 70090.2969

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 69638.5469

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 69137.6484

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 68705.6406

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 68369.8125

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 67975.0703

 961/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 67595.7031

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 67249.6094

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 66813.3906

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 66372.8672

1009/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 65871.0391

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 65453.3125

1034/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 65083.0234

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 64752.7031

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 64356.4570

1070/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 63970.2188

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 63578.7695

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 63197.9375

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 62906.4023

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 62556.9922

1131/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 62157.6484

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 61799.3242

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 61504.1484

1167/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 61171.7266

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60784.4531

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60477.1562

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 60111.0352

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 59818.1133

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 59493.0352

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 59188.5156

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58837.8867

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58624.2617

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58357.1055

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 58076.2539

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57828.0312

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57520.6523

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57241.5039

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 57005.1992

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 56767.8359

1362/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 56576.0547

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 56312.4062

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 56027.3828

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 55780.1250

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 55472.5898

1423/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 55157.2773

1434/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 54949.0625

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 54689.8945

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 54402.9453

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 54150.0938

1482/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 53876.2539

1494/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 53639.7031

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 53377.6992

1519/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 53104.4453

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 52892.2969

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 52641.5820

1556/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 52396.0312

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 52150.6172

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 51985.2344

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 51743.1992

1603/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 51519.7148

1615/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 51296.1250

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 51070.2578

1639/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 50867.1953

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 50666.2031

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 50435.6055

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 50235.6562

1687/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 50010.8633

1700/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 49788.0117

1712/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 49590.8359

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 49381.3203

1735/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 49192.0547

1747/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 49003.3477

1760/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 48785.0352

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 48575.3516

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 48344.2891

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 48164.6602

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47986.3828

1822/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47801.3281

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47596.3164

1847/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47419.9141

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47234.0703

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 47053.6602

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 46875.4297

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 46682.0430

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 46526.6172

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 46339.8047

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 46116.1523

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45966.5742

1958/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45808.3555

1969/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45638.2969

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45507.7656

1994/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45363.1602

2006/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45214.7227

2018/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 45067.6211

2030/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44902.3438

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44774.7500

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44635.2578

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44473.1836

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44323.7773

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44156.7070

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 44002.4297

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 43866.3047

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 43726.7461

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 43573.3828

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 43466.4766

2160/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 43334.5273

2171/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 43199.2500

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 43068.7695

2196/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42917.0977

2208/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42772.7930

2220/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42627.5039

2232/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42493.1484

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42338.5977

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42219.2266

2267/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 42110.7773

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41970.4688

2291/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41823.7383

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41665.0156

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41515.5938

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41377.1406

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41264.6094

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41142.7539

2366/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 41005.5156

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40888.3398

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40773.0820

2402/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40639.7695

2415/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40490.5391

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40371.0117

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40241.5000

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40125.8359

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 40005.9180

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39877.0977

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39753.8320

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39630.9922

2510/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39530.8398

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39415.6250

2534/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39285.6406

2547/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39171.9609

2559/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 39055.4805

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 38955.7812

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 38866.5234

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38763.7266

2602/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38662.5391

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38557.9453

2626/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38440.3320

2638/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38330.0781

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38208.8828

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38107.9180

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 38012.8242

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37917.5508

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37817.8438

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37704.8945

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37615.7930

2735/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37518.8516

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37422.3398

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37326.8359

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37223.7930

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37126.8164

2795/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 37019.4727

2808/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 36907.7500

2821/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36801.7305

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36719.2578

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36623.9922

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36517.3711

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36430.5625

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36333.8711

2894/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36238.9414

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36149.9570

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 36054.1641

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35959.4648

2943/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35871.0625

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35784.7305

2965/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35700.5859

2977/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35614.3750

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35530.7383

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35443.0938

3012/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35356.2227

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 35279.9453

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 35191.7852

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 35124.3086

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 35049.7383

3070/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34973.8789

3082/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34899.4883

3094/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34813.2500

3107/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34717.6680

3119/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34633.3594

3132/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34563.0898

3144/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34471.9805

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34398.3555

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34326.3984

3178/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34248.1992

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34162.7930

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34083.3086

3215/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 34001.3945

3228/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 33913.9844

3241/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 33843.7852

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33749.3672

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33663.9102

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33587.1406

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33508.7188

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33439.1719

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33372.9375

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33305.7266

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33223.7969

3352/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33142.2500

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33055.6133

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32987.4961

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32915.5703

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32832.0430

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32749.4180

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32679.1504

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32609.5605

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32537.2520

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32478.3652

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32413.8184

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32342.6270

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32270.3320

3512/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32202.1875

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32136.7715

3536/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32067.7285

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32018.5117

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31967.1621

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31916.3223

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31864.3770

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31805.4180

3601/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31743.6367

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31677.3184

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31613.8711

3637/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31557.4863

3649/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31493.9277

3661/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31428.2559

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31370.7051

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31290.4395

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31225.2949

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 21s 5ms/step - loss: 31205.3652 - val_loss: 11950.8232

Epoch 2/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:00 33ms/step - loss: 7417.0869

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 13266.9766

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 12166.1836

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11295.0791

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11304.8857

  66/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11275.1523

  78/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11699.9316

  91/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11620.8389

 103/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11727.2500

 115/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11465.1406

 128/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11421.2002

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11363.4189

 151/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11433.9443

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11503.4961

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11388.1787

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11372.4512

 201/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11547.5244

 214/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11526.0820

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11547.4004

 239/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11486.8779

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11415.9131

 264/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11366.5059

 276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11355.4932

 289/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11353.7041

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11264.4492

 313/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11152.1709

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11146.5010

 337/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11156.0264

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11284.5557

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 11248.3926

 373/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11225.2764

 385/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11222.0439

 397/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11216.7480

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11219.4150

 420/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11177.7168

 433/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11121.0000

 446/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11172.4961

 458/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11079.8027

 470/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11048.8906

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11020.6777

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11034.2100

 506/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11033.3721

 518/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 11014.9014

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10994.1270

 542/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10987.9551

 553/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10996.6123

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10981.3701

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10953.0352

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10927.9824

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10920.5312

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10903.0205

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 10882.1982

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10885.3945

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10874.0342

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10924.5449

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10953.4121

 685/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10881.1025

 697/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10863.5859

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10881.7734

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10876.7480

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10877.2119

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10900.3867

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10885.6670

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10861.5518

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10874.8076

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10848.5127

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10827.8047

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10819.1885

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10795.5791

 836/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10795.7383

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10758.2080

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10763.8486

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10745.6416

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10709.4141

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 10693.5420

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10671.8682

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10668.1875

 934/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10638.6338

 946/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10622.8320

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10626.8652

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10612.1133

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10599.3193

 986/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10604.3652

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10594.3516

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10578.3506

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10545.0312

1033/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10544.0469

1043/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10540.9883

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10557.2158

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10543.7773

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10528.1865

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10535.7383

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10527.7080

1106/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10497.3184

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10489.5225

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10479.1904

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10505.1377

1150/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10504.5771

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10507.5361

1171/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10505.1885

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10489.5977

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10488.3584

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10475.5889

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10478.9902

1220/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 10488.0762

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10479.5664

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10469.4404

1248/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10459.4248

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10442.0957

1267/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10421.8574

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 10416.0361

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10416.9072

1294/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10435.8779

1304/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10404.7334

1314/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10397.2461

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10381.4316

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10372.0039

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10352.0312

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10345.9795

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10341.4150

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10330.8887

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10327.1455

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10318.0039

1398/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10305.9561

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10292.6611

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10288.3447

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10287.1494

1440/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10282.6230

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10253.5488

1463/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10238.3906

1474/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10223.2021

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10219.1182

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10203.9062

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10188.7090

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10172.1689

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10159.9561

1539/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10150.7627

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10126.8252

1561/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10114.7900

1572/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10117.8545

1583/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10106.3877

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10094.8564

1605/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10084.9473

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10088.8701

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10080.8750

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10069.5166

1649/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10060.3008

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10039.6094

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10024.6836

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10014.0107

1693/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 10009.9209

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 9994.9268

1715/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 9978.9082

1727/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 9969.4229

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 9968.3184

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 9963.8213

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9946.1162

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9943.6309

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9940.4375

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9938.6348

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9922.8086

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9923.9668

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9919.9697

1838/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9912.2627

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9910.5488

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9908.7266

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9904.0293

1882/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9897.4697

1892/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9891.0811

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9877.2168

1914/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9888.5771

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9892.5098

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9883.6797

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9878.5742

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9877.8477

1970/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 9873.0547

1981/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9863.3828

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9856.3281

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9858.9883

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9844.7998

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9846.1523

2038/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9850.2930

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9843.3789

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9843.1113

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9840.0762

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9824.4434

2091/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9821.0000

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9819.6904

2112/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9817.2871

2124/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9796.6953

2136/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9793.3438

2147/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9779.2549

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9772.1436

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9758.9512

2180/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9754.5693

2191/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 9746.4316

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9745.5918

2212/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9743.6494

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9736.7471

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9730.4902

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9715.6426

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9709.7373

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9705.9473

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9695.7842

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9680.5898

2308/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9669.3047

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9661.2080

2331/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9652.8320

2343/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9645.8711

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9647.2471

2366/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9647.4062

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9643.3545

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9637.5850

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9627.4424

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9618.0215

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 9616.3467

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9610.3867

2427/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9611.8535

2436/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9608.4609

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9601.6592

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9596.9590

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9585.5518

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9573.5684

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9569.7529

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9556.1719

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9546.7090

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9539.5039

2542/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9532.3770

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9521.0371

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9515.2998

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9510.1025

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9508.9238

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9506.5791

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 9498.1064

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9488.1895

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9476.1045

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9476.5752

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9464.9170

2675/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9458.3145

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9447.5801

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9444.4385

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9443.7021

2726/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9441.7627

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9444.0391

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9462.4668

2762/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9479.0381

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9481.8350

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9473.7959

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9473.4346

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9475.0586

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 9480.9639

2837/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9479.5684

2849/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9483.2217

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9490.6074

2875/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9484.8242

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9485.7783

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9480.8057

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9477.8271

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9472.2744

2932/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9468.0029

2945/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9465.2490

2957/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9456.9443

2969/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9449.6455

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9445.8975

2992/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9436.6162

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9439.2305

3016/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9437.6650

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9442.0352

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 9443.3672

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9439.6729

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9431.2422

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9428.0781

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9417.6660

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9414.3467

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9410.7197

3124/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9403.3760

3136/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9397.9717

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9392.4912

3159/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9389.4492

3171/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9382.6729

3183/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9374.9434

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9370.8564

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9368.8877

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9370.4180

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9365.3682

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9362.3584

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9355.8076

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9352.5107

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9348.5107

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9345.9092

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9340.4775

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9335.2734

3330/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9323.2129

3343/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9314.6172

3355/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9311.8154

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9304.4219

3379/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9296.3086

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9294.4375

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9287.4912

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9289.4961

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9286.6865

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9284.7900

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9284.7246

3451/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9284.2764

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9281.6328

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9273.3281

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9261.1807

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9253.1738

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9245.8799

3525/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9236.8174

3537/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9234.9902

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9225.3350

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9223.5732

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9218.8379

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9209.9102

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9201.9170

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9196.6055

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9187.5771

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9180.1025

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9181.8574

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9173.9307

3672/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9170.3994

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9163.3477

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9159.1748

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 9158.9004 - val_loss: 2900.8816

Epoch 3/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:01 33ms/step - loss: 7485.2485

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7268.6226

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7687.3267

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7759.1831

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7626.4258

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7669.1953

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7678.6821

  89/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7528.9668

 102/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7789.1670

 115/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7707.6724

 127/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7732.4644

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7726.1113

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7767.4604

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7736.8096

 177/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7872.4897

 190/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7910.0664

 202/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7907.5933

 215/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 8011.6577

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 8040.2549

 238/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7978.2998

 250/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7946.6152

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7880.3042

 276/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7852.0610

 288/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7855.1479

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7773.1328

 313/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7688.6250

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7686.1211

 337/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7632.0776

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7624.3442

 362/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7580.3687

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7558.0474

 387/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7544.3643

 399/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7528.4644

 411/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7571.3750

 423/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7542.8774

 435/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7531.1304

 448/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7491.7144

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7474.0918

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7455.3496

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7434.1304

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7421.1187

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7450.1030

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7482.1670

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7508.3970

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7500.9497

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7536.2588

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7503.8555

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7528.8579

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7543.7764

 609/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 7519.3726

 621/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7503.4858

 633/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7507.2266

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7513.9233

 657/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7527.6357

 669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7510.6582

 681/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7503.6699

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7480.7520

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7500.2100

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7487.6558

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7516.8647

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7524.6494

 753/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7538.5171

 765/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7553.8794

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7537.7227

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7529.5815

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7518.5347

 813/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7498.8247

 825/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7516.4722

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7527.0308

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7530.5864

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 7514.1792

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7519.6479

 887/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7523.8452

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7525.2700

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7530.8120

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7541.3530

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7574.5093

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7584.3042

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7596.6157

 973/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7600.6338

 985/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7597.9971

 997/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7593.6230

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7583.0400

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7573.2109

1034/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7563.7207

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7560.3696

1058/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7561.4360

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7550.4106

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7522.0366

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7519.0332

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 7529.7720

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7517.7109

1133/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7508.6904

1145/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7490.3994

1157/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7474.6611

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7472.2065

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7462.5029

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7463.0889

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7453.6392

1219/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7475.5322

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7561.3423

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7613.5898

1258/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7659.9287

1270/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7670.6577

1282/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7674.2759

1295/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7684.8438

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7683.8340

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7685.5176

1331/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 7685.4443

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7667.8477

1355/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7669.8281

1368/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7673.0229

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7685.6689

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7701.9277

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7706.5742

1418/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7728.0806

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7717.4370

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7725.3320

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7737.3506

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7742.4355

1477/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7735.2358

1489/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7737.2710

1502/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7743.6426

1514/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7741.8867

1526/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7742.0771

1538/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7742.9238

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7730.7607

1564/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7735.9307

1576/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7731.5791

1588/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7732.1582

1600/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7735.3804

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7728.8115

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7722.2637

1639/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7710.2153

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7693.8179

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7691.2671

1674/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7689.0518

1686/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7698.2720

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7700.4189

1710/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7709.4971

1723/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7704.6187

1735/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7706.7842

1747/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7717.4253

1759/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7718.8804

1771/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7722.9902

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7727.4546

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7720.3906

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7720.9854

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7722.3872

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7715.4282

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7726.8770

1854/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7736.2539

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7733.7075

1879/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7727.6592

1891/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7727.9053

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7728.6484

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7731.5234

1928/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7735.6807

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7749.2246

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7747.6377

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7759.9399

1977/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7759.1372

1990/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7753.8574

2002/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7747.0840

2014/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7757.4697

2026/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7747.0020

2038/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7741.0786

2050/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7738.6445

2062/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7734.6484

2074/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7734.8091

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7732.8428

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7725.7817

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7733.3286

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7726.1162

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7722.7812

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7711.0059

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7701.7886

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7695.4385

2181/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7692.4956

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7686.8838

2205/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7686.7417

2218/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7696.1147

2229/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7686.9663

2241/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7681.0107

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7680.4321

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7676.3345

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7672.4141

2290/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 7664.8364

2302/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7668.5122

2314/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7662.7056

2326/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7654.8535

2338/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7655.8276

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7645.2100

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7648.8989

2373/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7648.5508

2384/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7648.8169

2397/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7648.3179

2409/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7642.7842

2421/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7633.8794

2433/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7624.6802

2445/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7623.7715

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7626.7485

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7624.7959

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7618.4663

2493/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7620.4360

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7621.4976

2517/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 7628.2993

2529/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7626.7988

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7628.0889

2551/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7634.3647

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7630.6431

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7627.8076

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7621.9404

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7621.3232

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7610.7388

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7602.2715

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7595.5054

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7586.6953

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7583.3687

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7578.6973

2683/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7574.2065

2695/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7575.8433

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7570.8247

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7569.1924

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7564.4102

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7559.4214

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 7558.7363

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7549.3130

2780/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7547.7783

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7548.6133

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7551.3159

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7552.6938

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7547.3975

2840/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7538.8926

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7541.3384

2864/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7543.6519

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7535.5791

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7535.5249

2902/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7535.4790

2914/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7530.5713

2926/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7529.8945

2938/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7525.2437

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7518.0229

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7514.0088

2977/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7510.1636

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7511.6323

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7509.5845

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7508.8276

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7505.9951

3041/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7497.1289

3053/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7490.8784

3065/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7488.8984

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7482.9360

3089/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7480.4399

3102/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7473.0093

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7469.1587

3127/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7463.9404

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7462.0645

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7457.9951

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7453.2222

3175/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7450.8882

3187/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7445.6313

3199/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7447.6758

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7443.6709

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7432.0591

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7425.8130

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7414.4858

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7412.3462

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7405.3740

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7400.2783

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7391.1919

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7392.9888

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7393.0488

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7390.3643

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7385.5039

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7382.1553

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7380.6377

3381/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7378.8433

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7374.7402

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7371.0947

3417/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7367.0938

3429/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7364.8667

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7361.5591

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7364.2803

3465/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7364.1421

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7366.6636

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7364.3608

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7363.2847

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7358.3940

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7354.6016

3537/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7356.8057

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7354.3447

3560/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7349.2949

3572/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7347.8604

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7347.5977

3596/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7349.6035

3607/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7345.0293

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7341.2988

3631/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7341.8511

3643/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7341.7534

3655/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7339.3525

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7337.4619

3680/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7332.3418

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7325.7983

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 7317.2456 - val_loss: 1096.6273

Epoch 4/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:32 41ms/step - loss: 3044.7417

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 6629.0234

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6987.8970

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7109.8159

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7151.7046

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7097.8467

  75/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7162.4067

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7174.2266

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7086.3457

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7233.6499

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7067.5142

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7042.6172

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6923.4766

 161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6852.4131

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6865.5850

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6827.8394

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6738.3169

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6673.6812

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6624.2065

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6600.5591

 246/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6503.9507

 258/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6464.2959

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6447.2847

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6437.3105

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6397.0767

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6319.6357

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6305.9917

 330/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6302.9976

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6271.7573

 355/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6283.1084

 367/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6266.7144

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6268.1851

 391/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6308.9688

 403/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6283.2700

 415/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6285.2778

 426/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6268.3286

 438/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6255.3550

 450/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6247.3506

 463/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6269.8809

 475/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6274.2173

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6261.8511

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6266.5244

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6260.5205

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6251.2090

 535/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6265.5498

 546/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6258.7163

 558/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6267.1797

 570/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6277.8906

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6287.7163

 595/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6282.5000

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6236.7646

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6246.9062

 633/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6245.0283

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6225.7881

 657/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 6216.3828

 669/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6228.1987

 681/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6250.7725

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6246.2603

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6251.6533

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6244.9834

 731/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6252.5518

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6286.1738

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6302.4722

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6308.9951

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6330.5630

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6339.6035

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6332.3066

 814/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6337.8501

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6341.8101

 839/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6345.0166

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6370.1382

 863/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6379.0371

 875/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6402.6621

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 6405.6416

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6398.0776

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6396.7881

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6411.1411

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6419.0146

 950/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6406.7490

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6409.0522

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6391.1343

 986/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6418.5815

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6423.9990

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6436.0498

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6438.3013

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6457.5713

1047/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6465.3477

1059/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6450.5850

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6448.9336

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6451.2334

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6437.1016

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6439.0166

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 6457.3311

1131/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6465.2378

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6469.6260

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6448.8022

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6448.5645

1180/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6452.7119

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6464.9102

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6466.8262

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6472.9482

1229/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6472.9961

1241/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6470.6064

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6487.1821

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6501.1714

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6490.2651

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6491.3906

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6490.4399

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6483.2139

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6481.7061

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6482.8535

1349/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6478.1069

1361/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 6498.2861

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6488.7056

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6477.6753

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6473.6670

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6461.7549

1420/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6472.8184

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6478.0601

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6466.3408

1457/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6462.9380

1469/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6451.9468

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6450.5620

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6438.1226

1505/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6431.1748

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6434.5576

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6424.9458

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6425.2456

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6447.7256

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6451.0527

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6459.9170

1590/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6470.1348

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6462.5454

1614/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6453.8599

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6460.0112

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6461.4048

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6453.9976

1664/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6452.8281

1676/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6454.9683

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6453.7065

1700/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6467.2144

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6471.0645

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6467.4146

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6459.2822

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6459.2944

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6461.7065

1772/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6464.1699

1783/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6454.2856

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6446.4561

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6449.3218

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6436.0273

1831/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 6434.7354

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6431.0713

1854/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6437.7505

1866/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6446.2480

1878/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6454.4375

1890/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6459.9922

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6472.7891

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6469.4937

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6468.9873

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6480.6724

1953/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6475.7661

1965/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6478.5010

1977/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6482.6865

1990/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6470.0464

2002/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6466.8330

2015/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6474.0962

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6473.4805

2039/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6476.8467

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6475.1826

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6472.2466

2076/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6465.3018

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6471.1738

2100/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6465.1758

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6470.9854

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6475.7715

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6486.1387

2149/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6484.5806

2161/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6502.2720

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6503.1509

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6498.6978

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6492.7671

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6493.3804

2220/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6492.6919

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6497.8774

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6507.1108

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6506.5562

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6503.2969

2280/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6499.3809

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 6494.8511

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6498.6089

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6498.5039

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6508.2251

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6500.2607

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6489.3716

2366/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6492.2700

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6500.2739

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6498.9087

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6493.8086

2414/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6488.2207

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6488.0620

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6484.8428

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6482.1318

2461/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6477.3955

2473/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6469.8643

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6469.0098

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6467.0708

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6464.1011

2524/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 6460.5190

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6461.0176

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6459.4497

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6462.5806

2572/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6461.0117

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6456.8311

2597/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6459.5117

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6455.5034

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6460.3057

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6455.3311

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6450.7734

2660/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6453.8413

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6454.6753

2683/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6450.1748

2695/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6448.3301

2707/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6445.0254

2720/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6442.2554

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6439.0806

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6431.9561

2758/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 6426.8672

2771/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6425.7739

2783/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6423.2764

2795/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6428.9360

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6430.7188

2819/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6433.4204

2831/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6434.9146

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6434.2100

2856/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6432.3696

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6428.7744

2882/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6426.7192

2894/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6422.0967

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6422.2583

2918/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6415.4702

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6413.7656

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6405.6309

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6408.8784

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6404.6274

2979/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6402.3555

2992/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 6397.8613

3005/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6397.7905

3017/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6394.7637

3029/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6385.8154

3041/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6391.2476

3054/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6391.4346

3067/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6387.5571

3079/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6390.1240

3091/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6389.3101

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6386.7451

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6384.1089

3127/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6376.8330

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6376.0664

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6369.5127

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6367.0000

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6364.9785

3188/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6365.6494

3200/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6364.6387

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6361.6211

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6360.2588

3236/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6359.5806

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6357.4492

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6352.8530

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6354.6313

3283/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6349.3477

3295/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6346.4458

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6345.0757

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6345.7944

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6346.7681

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6345.8179

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6339.5337

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6339.0718

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6339.4697

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6335.1982

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6328.0679

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6327.5942

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6323.5229

3441/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6317.4990

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6319.3213

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6316.7139

3476/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6314.1899

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6310.1270

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6310.9321

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6307.5356

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6302.7642

3539/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6299.0225

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6297.3823

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6295.5054

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6288.6772

3587/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6289.0239

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6287.9800

3612/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6289.9624

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6289.8306

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6285.5229

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6282.3477

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6280.1685

3671/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6278.5562

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6278.5244

3696/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6273.7705

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 6271.0571 - val_loss: 284.8764

Epoch 5/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:08 35ms/step - loss: 8919.7773

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6844.6123

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7356.5840

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 7238.1533

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7936.2417

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7417.4873

  75/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7101.1372

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7055.6958

  99/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6826.4048

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6841.8926

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6903.5244

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6871.1274

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6807.4502

 160/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6761.7114

 172/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6716.7314

 184/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6737.7422

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6717.7305

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6737.3081

 221/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6640.2305

 233/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6535.9365

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6488.8062

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6404.4727

 269/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6418.5850

 282/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6369.2222

 293/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6336.2173

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6306.0078

 313/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6306.6587

 322/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6270.9614

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6256.9253

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6216.1919

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6160.1865

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6107.2915

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6070.8535

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6078.1104

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6056.7271

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6055.8687

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6037.5190

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6010.3418

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6006.1470

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5985.9717

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5969.1211

 483/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5961.9556

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5936.4604

 503/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5954.2026

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5939.0952

 522/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5952.3472

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5959.4824

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5963.3511

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5962.0630

 553/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5977.8320

 562/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5972.6567

 570/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5943.2104

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5937.3389

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5941.2695

 594/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5957.6353

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5917.9736

 609/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5917.6650

 616/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5917.6890

 624/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5908.2793

 632/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5895.6597

 642/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5887.1392

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5908.1982

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5903.8086

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5913.7915

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5914.3936

 678/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5910.6211

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5894.8052

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5890.8613

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5878.8403

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5870.0474

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5867.5562

 740/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5842.4312

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5841.7153

 761/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5838.0684

 771/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5846.9429

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5855.6509

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5861.5981

 801/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5868.2100

 811/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5878.7090

 823/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5886.1929

 835/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5889.8188

 847/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5888.5454

 859/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5878.4150

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5878.9438

 883/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5883.1260

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5883.6050

 906/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5882.3716

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5882.9199

 932/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5863.2090

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5849.4697

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5847.2881

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5851.8965

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5836.0879

 992/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5831.1748

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5810.7520

1015/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5807.0459

1027/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5796.0747

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5811.0444

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5815.5181

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5812.5952

1078/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5819.5977

1090/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5822.1973

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5824.4316

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5821.7505

1127/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5815.5312

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5809.1665

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5804.8442

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5801.6240

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5818.5225

1189/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5807.4707

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5794.0352

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5789.5151

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5783.7607

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5771.8486

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5768.3330

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5768.2476

1276/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5776.7178

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5772.7539

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5770.3032

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5773.7222

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5776.1802

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5761.5547

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5763.0215

1361/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5752.2759

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5752.9976

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5746.1245

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5741.0479

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5742.6602

1421/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5734.7930

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5728.9385

1445/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5728.8276

1456/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5723.7637

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5723.1895

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5719.9805

1491/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5717.9507

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5726.7998

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5724.8105

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5728.1494

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5738.2007

1554/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5735.3901

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5729.7471

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5733.6055

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5727.0874

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5732.4692

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5736.3960

1628/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5741.6895

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5743.1372

1653/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5741.1602

1665/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5743.9302

1678/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5749.7905

1689/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5749.1938

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5747.1128

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5748.5952

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5745.1162

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5742.9248

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5745.7427

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5744.9922

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5745.7505

1785/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5748.8599

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5750.9761

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5748.4507

1822/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5747.5229

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5747.6040

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5740.3936

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5738.9946

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5741.7236

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5739.8823

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5739.1069

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5745.1694

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5742.9575

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5741.9585

1942/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5744.0488

1954/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5742.4878

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5744.4663

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5739.2983

1991/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5750.8960

2003/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5752.0654

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5752.5469

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5750.4463

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5751.8149

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5749.7671

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5749.4771

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5743.0146

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5748.8838

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5746.0933

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5741.0664

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5743.8281

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5736.8813

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5740.8418

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5748.9800

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5757.2266

2186/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5761.2393

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5755.4097

2211/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5755.8516

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5761.7456

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5757.6660

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5753.5728

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5756.3535

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5760.4326

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5757.7280

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5768.7207

2307/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5771.2656

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5766.6265

2331/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5770.7197

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5772.1870

2356/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5774.8447

2368/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5778.2002

2380/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5783.4536

2392/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5787.4194

2404/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5787.3091

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5786.8452

2428/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5783.0742

2440/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5784.8301

2452/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5781.0967

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5780.5625

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5778.0020

2488/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5777.1909

2500/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5775.6084

2510/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5770.8315

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5771.8081

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5775.6875

2546/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5776.5034

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5775.0229

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5773.9517

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5773.5898

2583/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5768.4565

2595/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5766.1323

2607/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5763.2017

2619/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5761.0586

2631/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5760.5234

2643/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5760.9233

2655/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5763.3667

2667/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5772.1792

2679/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5775.2710

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5775.7812

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5778.4263

2714/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5784.3628

2727/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5784.0029

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5782.8477

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5782.6348

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5781.5347

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5778.0283

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5777.6235

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5771.9990

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5772.5439

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5773.6777

2836/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5768.7046

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5769.9863

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5773.1431

2872/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5771.9424

2883/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5768.8442

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5764.8418

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5760.9785

2917/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5759.0122

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5758.0044

2941/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5755.6221

2953/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5755.8535

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5751.6553

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5755.3159

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5749.4556

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5744.0015

3013/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5741.5547

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5743.7622

3038/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5747.0850

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5745.6934

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5744.4497

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5744.3838

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5743.9263

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5745.8999

3111/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5740.2471

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5740.8608

3134/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5743.0054

3146/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5740.2217

3158/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5739.1294

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5734.1553

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5731.9048

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5730.8286

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5729.4561

3218/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5733.6738

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5739.2534

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5736.7886

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5738.4326

3268/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5736.8301

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5735.3872

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5738.1304

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5742.9727

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5750.1221

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5758.4585

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5762.1230

3352/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5758.7402

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5760.1509

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5762.2520

3385/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5764.0415

3397/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5764.1250

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5766.8809

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5771.4956

3431/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5772.8564

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5776.8584

3454/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5781.3003

3466/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5781.3906

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5783.6064

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5783.2993

3504/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5786.4731

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5786.3999

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5791.5703

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5791.7329

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5789.2827

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5787.3550

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5790.3467

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5789.3501

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5784.6885

3614/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5785.1704

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5786.4316

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5784.1855

3648/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5784.7954

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5784.4204

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5790.1992

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5792.6953

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5793.0601

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5793.5264 - val_loss: 1085.4624

Epoch 6/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 1:58 32ms/step - loss: 4786.8447

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5895.0830

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5922.0933

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5954.9072

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5887.6548

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5938.0415

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5898.5215

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5806.3408

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5733.5483

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5771.0908

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5878.8110

 133/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5879.5073

 145/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5946.4766

 157/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6012.3872

 169/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5979.7827

 181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5942.1987

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5966.5576

 206/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5927.4414

 218/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5968.4531

 230/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5921.9556

 242/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5944.8379

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5964.6880

 266/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5937.4224

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5900.9414

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5876.1519

 302/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5839.9771

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5857.2588

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5866.1270

 337/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5829.7207

 349/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5844.7529

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5848.8306

 373/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5831.3169

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5818.5420

 398/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5818.9561

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5805.3794

 422/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5764.1826

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5775.5835

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5800.2773

 449/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5784.3882

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5747.0532

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5746.8804

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5742.8013

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5734.4873

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5738.1895

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5707.0249

 534/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5706.6509

 547/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5698.4878

 559/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5719.7314

 571/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5723.4653

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5726.1841

 595/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5724.2695

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5711.5142

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5721.2153

 632/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5706.0293

 645/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5712.2227

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5691.1543

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5672.1802

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5660.5044

 695/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5664.4487

 707/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5641.3960

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5639.6885

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5629.7222

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5642.1538

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5647.0630

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5691.6255

 782/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5695.2222

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5663.9614

 806/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5665.8555

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5656.9438

 829/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5659.5747

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5668.9795

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5669.7759

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5682.6401

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5670.6357

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5662.1318

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5664.6543

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5676.2476

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5663.7031

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5666.7168

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5666.8804

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5650.8594

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5654.3076

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5654.0244

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5645.9233

1012/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5642.1509

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5640.1440

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5628.4526

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5616.0259

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5624.6187

1073/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5635.9141

1086/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5626.6304

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5618.7583

1109/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5628.6543

1121/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5629.0713

1134/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5630.2905

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5618.7339

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5606.2837

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5603.6997

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5597.5981

1195/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5616.2422

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5618.8032

1220/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5618.4917

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5617.3916

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5617.5430

1256/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5610.3262

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5602.6064

1280/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5609.0713

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5600.7002

1305/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5602.1304

1317/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5606.2949

1329/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5601.2490

1341/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5598.6221

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5595.0073

1365/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5590.9819

1376/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5585.6401

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5579.0532

1401/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5588.1606

1413/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5592.5435

1425/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5600.2144

1436/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5591.2690

1448/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5585.6216

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5586.4546

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5583.8252

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5581.9531

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5587.7671

1508/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5592.6270

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5586.4512

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5595.0649

1542/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5597.5137

1554/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5607.6216

1567/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5606.1479

1579/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5605.9761

1592/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5601.5059

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5592.2803

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5586.5498

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5585.4595

1639/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5592.9233

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5603.6348

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5610.2061

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5613.1963

1687/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5614.1685

1699/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5613.4526

1711/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5614.3633

1722/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5609.4912

1734/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5607.9414

1746/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5617.4922

1757/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5625.4688

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5631.2837

1781/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5656.2915

1793/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5660.5151

1806/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5659.2788

1818/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5657.9951

1831/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5648.6841

1843/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5651.0645

1855/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5644.9429

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5644.4668

1879/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5641.7148

1891/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5637.8657

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5642.6294

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5634.1455

1928/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5633.8564

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5633.8442

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5632.1802

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5640.6968

1977/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5638.7231

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5632.4419

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5636.2417

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5638.7964

2025/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5633.7964

2038/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5636.0952

2050/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5639.0322

2062/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5634.2144

2075/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5629.9888

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5627.8184

2099/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5631.7148

2111/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5630.9731

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5633.5229

2135/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5629.9678

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5626.2852

2161/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5624.3643

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5626.8550

2186/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5625.9902

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5629.0059

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5627.9561

2220/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5626.4062

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5627.6470

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5618.6538

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5619.5063

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5618.9756

2280/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5620.2007

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5618.5791

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5614.7900

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5611.6050

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5609.1753

2342/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5602.8188

2354/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5605.0181

2367/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5605.8804

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5606.7031

2392/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5610.5562

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5602.8188

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5597.0723

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5595.5361

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5593.6025

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5594.1670

2463/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5598.8926

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5600.5347

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5598.9390

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5594.6704

2510/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5595.4351

2522/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5592.7764

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5592.3848

2545/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5587.3110

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5585.0400

2569/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5578.5742

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5581.4663

2593/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5579.0918

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5571.4038

2618/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5575.7637

2630/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5570.2139

2642/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5566.6738

2654/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5566.4375

2666/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5565.4985

2678/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5560.1143

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5563.5903

2701/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5561.8228

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5562.1738

2726/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5562.1001

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5560.5654

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5558.6001

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5552.2871

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5551.2681

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5548.0557

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5547.1709

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5547.1313

2824/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5544.8545

2837/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5543.6860

2849/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5550.2749

2861/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5547.1631

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5547.1904

2886/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5545.7241

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5545.8271

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5544.0605

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5546.1152

2935/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5547.2212

2947/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5543.5352

2959/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5545.3081

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5539.7026

2985/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5537.4326

2998/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5534.1182

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5536.3599

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5533.2085

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5533.2690

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5537.9556

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5542.3101

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5540.8184

3084/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5540.1445

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5544.3877

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5545.8101

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5544.2363

3132/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5545.0654

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5544.1836

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5545.7554

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5549.3721

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5546.8618

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5549.9106

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5549.9141

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5552.9209

3232/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5559.5962

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5557.8887

3256/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5557.2329

3268/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5553.3320

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5552.1875

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5555.3071

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5553.3320

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5551.6128

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5555.7490

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5552.1831

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5553.5361

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5556.7402

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5553.5737

3389/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5550.6899

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5548.7769

3413/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5546.5078

3425/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5546.5088

3437/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5541.9492

3449/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5542.7705

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5542.4971

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5544.8633

3486/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5550.4160

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5548.2290

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5548.0444

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5546.0522

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5545.4639

3546/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5543.8516

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5545.1509

3570/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5542.2842

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5542.5195

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5544.5776

3605/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5541.9648

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5543.7905

3629/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5546.7134

3641/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5549.3218

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5548.1641

3664/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5547.7383

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5544.6426

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5544.4243

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5544.2837 - val_loss: 783.5225

Epoch 7/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:00 33ms/step - loss: 5904.0098

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5643.9468

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5288.4209

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5229.3823

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5244.1025

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5205.3286

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5040.7617

  84/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5128.4644

  96/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5191.4351

 108/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5145.9590

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5249.8550

 134/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5289.7778

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5344.3086

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5277.7505

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5280.3530

 184/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5335.2749

 196/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5401.2393

 208/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5482.4585

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5470.5845

 233/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5534.0278

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5533.7324

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5553.2471

 268/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5481.6787

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5441.9902

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5449.0957

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5423.2559

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5419.6240

 328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5412.9878

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5371.3267

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5429.4985

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5424.8115

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5434.2988

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5451.0010

 401/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5480.2896

 414/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5478.5435

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5494.2212

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5481.0391

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5474.9473

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5456.4731

 474/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5476.1846

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5471.8325

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5488.5815

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5526.0044

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5545.5210

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5538.0269

 549/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5545.8765

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5545.7148

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5541.3257

 587/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5550.2617

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5572.5791

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5591.6465

 623/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5585.2456

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5592.9995

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5586.1909

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5592.0996

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5589.1167

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5579.1636

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5595.4575

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5591.1328

 718/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5579.8389

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5576.9370

 742/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5573.8325

 754/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5575.3433

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5582.7754

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5588.0327

 791/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5605.9795

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5613.8994

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5607.7319

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5596.2021

 841/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5573.9521

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5557.0088

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5562.5737

 877/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5554.6021

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5569.0327

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5566.0884

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5569.1260

 925/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5560.7559

 937/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5564.1104

 949/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5560.1904

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5552.9648

 975/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5551.4458

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5543.2139

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5546.8335

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5546.4326

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5557.3950

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5553.6953

1047/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5547.0337

1059/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5542.0938

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5554.7173

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5551.0493

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5563.5396

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5576.9897

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5594.9175

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5583.6567

1143/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5600.3228

1155/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5593.8418

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5588.1475

1180/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5599.8794

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5618.7310

1205/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5627.6030

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5620.7856

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5617.1445

1242/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5612.0645

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5617.9263

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5619.2974

1278/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5630.6851

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5639.2002

1302/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5632.8101

1315/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5635.3545

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5631.8960

1340/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5634.7168

1352/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5633.2266

1364/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5633.6753

1375/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5631.1387

1387/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5635.4609

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5638.9937

1411/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5639.0938

1424/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5636.6152

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5625.9258

1447/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5619.3955

1460/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5614.5571

1472/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5610.8633

1485/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5614.7954

1497/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5602.0010

1508/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5592.5044

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5595.8677

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5597.1104

1547/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5602.6465

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5606.0278

1573/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5609.4062

1585/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5619.2998

1597/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5619.7886

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5616.6733

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5613.0137

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5616.1685

1647/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5621.7285

1659/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5619.3867

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5621.8574

1683/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5611.9585

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5610.8882

1709/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5613.9414

1722/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5608.2344

1734/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5610.6221

1745/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5611.0991

1757/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5617.5225

1769/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5621.4053

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5631.6353

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5628.7690

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5623.5098

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5617.7876

1831/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5622.0220

1843/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5622.3140

1855/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5621.4570

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5620.4067

1878/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5614.4404

1890/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5608.0493

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5599.5508

1915/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5605.7822

1927/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5600.7461

1939/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5600.4512

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5593.4082

1965/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5596.8477

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5600.1099

1988/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5604.8296

2000/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5605.0151

2012/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5616.7720

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5615.7124

2037/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5617.2334

2049/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5607.4922

2061/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5606.1846

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5610.0552

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5617.8369

2099/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5619.1719

2111/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5617.4062

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5616.1084

2135/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5621.1479

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5624.5254

2161/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5624.4780

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5622.9321

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5618.6118

2197/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5617.1655

2210/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5622.2598

2222/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5620.6382

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5625.2700

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5626.1509

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5627.4722

2272/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5625.6904

2284/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5617.5767

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5608.9438

2308/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5606.2051

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5606.8320

2330/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5604.3374

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5600.9067

2351/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5595.6411

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5592.4287

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5596.7163

2385/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5594.5576

2397/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5591.7109

2410/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5593.3311

2422/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5589.6064

2435/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5584.9707

2448/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5586.3608

2459/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5588.0635

2471/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5589.6587

2484/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5592.1069

2497/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5594.1865

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5593.6230

2520/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5601.8110

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5600.1948

2544/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5605.8164

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5601.6826

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5598.6641

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5598.1997

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5593.9033

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5592.9033

2618/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5592.5034

2630/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5584.2402

2643/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5584.3374

2656/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5583.8633

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5582.1606

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5591.6729

2692/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5595.7466

2705/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5602.6519

2718/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5607.1519

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5604.9521

2742/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5608.4438

2754/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5615.8848

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5615.1323

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5616.7568

2790/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5610.9995

2803/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5604.8516

2815/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5603.7637

2827/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5604.5464

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5605.6602

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5604.3340

2863/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5601.4346

2876/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5601.4966

2888/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5605.5254

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5609.5356

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5608.4111

2924/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5606.6133

2936/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5607.1611

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5605.5933

2962/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5602.0415

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5606.5645

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5607.8022

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5609.5083

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5609.1602

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5612.3633

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5612.3394

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5608.5684

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5606.0273

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5604.9053

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5600.6377

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5598.4590

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5601.0796

3125/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5599.7275

3137/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5596.9243

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5595.3643

3160/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5590.7729

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5590.2188

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5593.4058

3195/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5593.5283

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5595.0454

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5590.3076

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5587.8364

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5585.1157

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5585.2080

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5584.8848

3279/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5585.3750

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5587.2437

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5583.9014

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5582.4619

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5583.5020

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5582.1685

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5577.6616

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5582.2310

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5583.4858

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5584.2324

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5582.4834

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5583.8154

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5586.3271

3440/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5588.3091

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5588.0396

3465/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5590.7231

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5590.9570

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5590.8130

3502/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5593.4966

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5592.4292

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5592.9961

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5591.2031

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5590.4561

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5588.2354

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5592.9580

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5592.2466

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5589.5371

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5588.8105

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5588.6284

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5590.7153

3650/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5593.2158

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5593.4277

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5593.0352

3688/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5595.6963

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5593.3931

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5593.3931 - val_loss: 1369.1675

Epoch 8/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 1:58 32ms/step - loss: 2933.4468

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6875.7900

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5998.0654

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6523.1909

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5862.0781

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5882.4658

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5882.7485

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5704.7295

 100/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5642.3403

 112/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5830.9961

 125/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5637.4004

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5586.2144

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5628.6548

 161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5622.0093

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5667.5430

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5709.1558

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5680.7334

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5598.5571

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5604.5278

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5509.4282

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5488.5532

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5490.3003

 273/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5556.8452

 285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5540.4082

 297/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5513.7007

 309/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5504.0723

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5511.6455

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5529.9941

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5534.6899

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5514.3379

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5538.4985

 381/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5549.4663

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5542.7202

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5553.2471

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5548.6406

 428/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5525.1841

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5511.0938

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5464.6226

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5449.8638

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5449.8179

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5476.6133

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5462.2456

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5484.4053

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5513.0020

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5490.1924

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5507.8057

 563/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5535.1660

 575/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5527.1489

 588/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5522.9907

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5527.5015

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5546.9033

 623/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5569.0728

 635/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5557.1748

 648/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5559.5288

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5545.0186

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5559.2422

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5557.9116

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5579.6235

 709/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5584.4907

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5577.5894

 734/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5568.2012

 746/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5572.0361

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5553.7827

 770/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5549.2188

 782/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5558.5156

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5588.0859

 806/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5590.6963

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5588.6406

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5592.1689

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5596.6997

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5594.4033

 867/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5594.6973

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5596.3960

 892/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5581.5796

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5590.2314

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5597.5103

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5601.8086

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5604.3174

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5611.8193

 963/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5613.6919

 975/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5618.5347

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5633.3359

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5633.6064

1012/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5648.0737

1024/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5646.2759

1036/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5637.6128

1047/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5650.1152

1059/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5637.7798

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5632.1011

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5637.5776

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5646.0078

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5647.1133

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5669.8633

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5673.6807

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5678.7827

1155/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5695.9907

1166/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5700.9058

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5721.1401

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5720.6030

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5719.7222

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5724.3887

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5723.8481

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5725.8491

1253/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5742.4697

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5732.1904

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5735.8364

1288/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5744.4341

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5746.6128

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5744.5439

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5743.3374

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5735.0981

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5734.0439

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5750.8110

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5755.1675

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5748.9922

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5750.8262

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5752.9497

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5748.5664

1434/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5755.6904

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5756.4590

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5766.8101

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5765.9399

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5776.7520

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5771.0776

1507/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5761.9604

1519/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5757.6118

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5784.3467

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5787.5522

1556/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5792.6104

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5790.9180

1581/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5796.5059

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5801.9585

1606/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5811.7422

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5811.8423

1631/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5815.7207

1643/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5806.8574

1656/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5801.2397

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5803.0020

1681/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5802.0991

1694/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5807.4429

1706/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5805.8354

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5814.5728

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5814.1255

1745/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5813.0928

1758/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5815.6909

1769/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5807.9878

1781/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5801.4277

1794/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5806.5986

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5807.0249

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5804.5542

1820/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5803.3320

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5800.3057

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5797.4136

1855/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5795.0029

1867/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5804.5469

1879/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5809.8584

1891/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5807.7446

1903/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5812.9009

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5815.0376

1928/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5816.4478

1940/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5813.6123

1952/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5816.2412

1964/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5818.1294

1976/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5818.9980

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5819.0996

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5826.3076

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5828.0283

2026/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5832.0415

2038/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5836.5156

2050/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5831.8711

2062/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5830.1196

2074/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5825.7764

2086/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5826.4678

2098/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5821.2671

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5816.3384

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5818.2690

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5817.3447

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5816.0781

2158/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5822.1157

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5816.2192

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5820.9419

2193/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5820.2588

2205/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5819.8257

2216/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5821.4980

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5824.7773

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5835.7139

2248/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5831.9819

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5829.7236

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5825.9937

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5828.8076

2295/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5831.9141

2307/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5827.9282

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5833.0776

2332/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5832.6387

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5839.2803

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5835.9351

2368/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5836.8130

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5839.8931

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5836.6030

2404/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5841.9839

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5843.7832

2428/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5849.6865

2440/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5849.9268

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5848.6997

2464/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5848.8911

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5849.9409

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5852.8857

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5854.2344

2512/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5852.9053

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5856.4424

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5856.4468

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5854.9751

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5849.8887

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5849.6968

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5850.5981

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5851.9341

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5856.8047

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5857.6494

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5863.8291

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5866.4355

2658/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5863.5923

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5858.0239

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5855.9409

2692/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5849.9937

2705/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5849.9980

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5848.5752

2729/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5844.0200

2741/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5845.1226

2753/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5841.1235

2765/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5838.9258

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5836.3481

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5832.3013

2801/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5833.9873

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5833.7930

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5838.8687

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5835.5903

2849/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5831.5078

2861/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5832.1533

2873/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5836.6768

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5841.2007

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5836.2949

2907/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5841.3115

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5846.0195

2931/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5846.4082

2943/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5844.6465

2955/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5846.1938

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5841.9355

2979/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5841.3267

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5839.9810

3003/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5836.7676

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5842.0840

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5842.3691

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5846.6948

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5842.4995

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5843.1904

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5843.3594

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5842.5205

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5840.0825

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5842.9116

3125/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5843.1938

3137/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5844.1665

3149/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5845.9888

3162/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5847.4961

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5850.2002

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5849.2793

3198/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5849.3701

3210/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5853.0972

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5854.3574

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5855.8267

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5859.6011

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5864.4795

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5864.3408

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5866.7744

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5862.8164

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5861.7378

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5861.8896

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5867.4731

3340/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5869.7627

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5872.8989

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5877.0903

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5879.7969

3388/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5882.1895

3400/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5883.6650

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5885.4438

3423/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5884.1211

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5886.5913

3447/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5887.7490

3459/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5882.1050

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5881.5361

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5879.3711

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5876.5254

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5876.2593

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5876.2573

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5875.3711

3544/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5877.7056

3557/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5879.8364

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5878.8027

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5880.7026

3591/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5882.1138

3603/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5881.4639

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5878.4673

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5876.0830

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5875.0103

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5875.0503

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5877.3809

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5880.6411

3688/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5877.5835

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5875.6865

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5875.5347 - val_loss: 262.7528

Epoch 9/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:06 34ms/step - loss: 3619.6069

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4812.0493

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4932.4497

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5051.4678

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5370.3467

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5555.4736

  77/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5778.0215

  90/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6016.6240

 103/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6072.7383

 116/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 6033.1079

 128/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5931.9463

 140/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5825.9854

 152/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5771.6206

 164/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5737.6890

 176/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5685.3110

 188/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5712.3701

 200/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5773.0635

 212/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5773.6597

 224/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5743.6499

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5725.9707

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5728.3228

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5725.2104

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5737.0303

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5741.1309

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5748.5195

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5731.7412

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5747.0825

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5727.1523

 343/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5727.6011

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5722.0762

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5732.7095

 381/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5804.0972

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5833.1240

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5815.7485

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5812.2227

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5780.7812

 443/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5776.4526

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5776.9810

 469/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5763.8872

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5777.9839

 495/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5781.0454

 507/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5800.0845

 519/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5782.1270

 531/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5792.1743

 543/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5789.3960

 556/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5807.3008

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5808.8145

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5774.6968

 594/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5778.3535

 606/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5742.4478

 618/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5741.1030

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5766.2529

 642/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5771.3472

 654/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5762.3384

 666/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5763.6797

 679/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5761.7886

 692/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5749.6938

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5761.7183

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5749.7866

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5747.6294

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5748.0049

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5756.3291

 764/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5753.7886

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5758.1240

 788/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5742.5669

 800/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5735.7100

 812/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5725.3911

 825/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5731.7939

 837/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5721.9458

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5711.8262

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5701.2339

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5699.7827

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5691.7129

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5717.3994

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5720.5161

 922/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5721.7061

 935/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5713.8730

 948/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5708.5049

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5731.4277

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5725.2358

 983/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5731.1255

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5732.3779

1009/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5732.3799

1020/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5735.3716

1032/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5734.6611

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5733.3774

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5745.1450

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5746.0903

1082/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5741.9937

1094/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5747.6313

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5771.4336

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5763.8530

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5755.2012

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5755.0693

1151/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5750.8428

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5741.8408

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5744.5122

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5736.5806

1195/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5737.1040

1207/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5731.6260

1219/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5724.7900

1232/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5732.1733

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5724.7153

1256/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5722.8516

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5731.1411

1280/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5740.7188

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5736.3208

1304/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5749.7720

1316/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5750.4658

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5753.1152

1339/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5760.3740

1350/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5761.5200

1362/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5769.0122

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5770.9893

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5778.8540

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5768.1323

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5765.3242

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5772.8169

1432/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5772.0078

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5775.8589

1456/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5773.3560

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5771.6050

1480/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5791.2681

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5778.9160

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5781.8237

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5786.3271

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5789.0586

1540/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5785.6929

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5775.9971

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5774.3140

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5773.5371

1590/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5777.6851

1603/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5773.7896

1614/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5778.0420

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5777.8657

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5780.0903

1651/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5771.9233

1664/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5772.7754

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5771.9526

1687/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5771.9844

1699/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5775.2764

1711/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5774.9365

1724/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5769.3198

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5770.2646

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5771.7490

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5767.3701

1774/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5765.8911

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5761.0967

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5769.2886

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5774.3662

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5769.5991

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5773.9805

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5771.1123

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5771.0117

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5775.5474

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5782.2500

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5783.7568

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5778.1938

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5773.9575

1933/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5774.6353

1945/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5771.7607

1957/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5769.7695

1970/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5763.0532

1983/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5761.1440

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5757.7148

2007/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5754.9102

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5754.2485

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5752.9194

2045/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5747.0874

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5752.5625

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5743.8003

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5746.7266

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5743.5049

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5740.6401

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5734.8350

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5733.3647

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5725.7817

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5724.0024

2165/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5718.8696

2178/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5712.9912

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5714.9341

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5714.1958

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5710.5269

2227/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5698.0967

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5695.7178

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5699.5596

2263/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5699.9854

2276/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5698.1978

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5698.6260

2299/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5694.7676

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5691.4170

2324/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5696.4380

2337/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5695.3599

2349/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5692.9048

2361/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5692.3892

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5688.3350

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5688.0132

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5688.0581

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5689.7129

2424/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5687.4336

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5688.0234

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5686.7500

2463/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5680.7554

2476/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5681.3750

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5683.8242

2500/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5685.4287

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5684.9897

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5690.2622

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5693.2773

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5691.6450

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5689.7720

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5685.3384

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5685.3599

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5679.0034

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5677.5439

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5676.9780

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5676.8848

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5681.6924

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5680.7119

2671/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5682.4546

2684/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5681.8467

2697/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5675.3560

2709/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5678.3916

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5674.7974

2732/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5676.2144

2744/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5671.0679

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5674.2183

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5675.8550

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5673.4985

2794/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5672.9995

2807/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5668.5391

2820/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5667.7695

2833/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5665.2510

2846/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5659.9326

2858/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5659.0532

2870/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5661.2007

2882/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5660.0259

2895/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5667.4771

2907/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5665.6045

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5668.1113

2932/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5672.7451

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5675.9600

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5677.7656

2968/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5674.0879

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5674.6016

2994/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5673.3887

3006/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5674.1797

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5673.7285

3030/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5671.6187

3043/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5666.9331

3056/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5666.8525

3068/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5662.7666

3081/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5663.2407

3093/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5658.6743

3105/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5656.6318

3117/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5662.1768

3130/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5664.7021

3142/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5663.4536

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5661.3159

3168/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5661.5869

3180/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5661.6821

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5660.4971

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5664.2651

3218/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5668.6948

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5670.9307

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5669.1943

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5667.4087

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5668.9780

3279/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5667.3638

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5664.0176

3304/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5664.3330

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5666.8467

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5664.6626

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5670.0654

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5668.5820

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5669.6768

3378/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5665.5557

3390/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5668.2378

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5667.2881

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5668.3008

3427/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5669.5850

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5670.6914

3451/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5669.2710

3464/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5672.6743

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5672.0518

3489/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5673.5371

3501/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5678.0161

3513/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5674.7969

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5669.2534

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5668.5093

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5666.8345

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5669.3809

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5668.1621

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5665.2568

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5665.0474

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5665.4092

3626/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5664.6445

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5662.8525

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5668.9932

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5674.7026

3675/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5671.2832

3687/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5672.5044

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5671.2891

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5670.7866 - val_loss: 218.7195

Epoch 10/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:08 35ms/step - loss: 8058.6562

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 7157.8481

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6619.2266

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6294.0532

  49/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6190.1733

  61/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6091.8433

  73/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6010.3403

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5875.1348

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5836.8247

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5855.3394

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5778.3535

 134/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5827.5483

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5772.1304

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5722.8301

 172/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5839.4248

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5842.2104

 196/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5796.9858

 208/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5795.4888

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5738.8232

 232/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5741.3218

 244/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5762.8003

 257/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5710.6924

 270/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5688.5562

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5658.9668

 291/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5614.5205

 302/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5600.2529

 312/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5629.7666

 323/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5567.3438

 334/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5575.9399

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5588.2559

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5589.4536

 367/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5598.1616

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5554.9028

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5572.6558

 400/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5586.6084

 410/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5614.0474

 420/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5614.1577

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5582.0327

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5599.6743

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5617.4067

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5595.4546

 471/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5580.1621

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5565.6895

 494/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5595.5840

 506/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5584.8369

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5574.6899

 526/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5574.9751

 538/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5554.0625

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5529.3091

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5529.8208

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5520.3281

 583/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5520.9780

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5537.7290

 603/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5514.7358

 611/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5530.6724

 619/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5520.1704

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5521.7700

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5511.2715

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5520.8271

 656/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5509.9707

 666/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5526.1870

 676/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5537.4980

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5557.3232

 695/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5552.7227

 704/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5541.1421

 711/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5550.1724

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5538.0640

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5522.9146

 740/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5516.9790

 751/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5537.4229

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5524.6572

 774/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5524.3364

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5526.2744

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5533.1001

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5525.3799

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5506.9360

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5500.3066

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5505.0479

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5526.4863

 862/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5534.5527

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5532.9160

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5542.1851

 898/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5541.5137

 910/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5557.1699

 923/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5567.5620

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5559.0308

 948/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5548.4258

 960/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5533.7222

 972/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5546.0708

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5544.3047

 995/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5531.3765

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5535.7188

1018/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5540.8477

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5549.8394

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5566.1504

1052/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5560.5176

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5572.2773

1075/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5565.9492

1087/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5574.3584

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5571.9751

1109/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5581.5244

1121/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5574.3213

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5570.8535

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5567.0483

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5571.8511

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5562.4077

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5549.6953

1190/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5539.6963

1201/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5546.9824

1213/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5546.7441

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5541.0034

1235/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5556.1719

1246/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5551.8735

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5547.5063

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5542.3643

1279/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5537.4692

1290/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5530.7100

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5530.8945

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5528.7988

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5548.2212

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5540.9443

1346/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5538.9995

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5532.7251

1367/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5539.1050

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5546.0493

1388/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5538.5884

1399/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5536.2363

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5530.5244

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5523.9902

1434/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5521.0762

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5521.9810

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5522.7017

1469/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5515.4053

1480/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5518.7075

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5511.2007

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5501.7598

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5505.8433

1527/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5507.9233

1539/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5504.4409

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5503.6592

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5501.8672

1572/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5498.4863

1583/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5497.3042

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5499.2344

1607/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5497.3237

1618/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5491.1592

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5490.2974

1641/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5486.0347

1652/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5481.8843

1663/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5481.3804

1674/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5482.5669

1685/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5478.5142

1697/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5470.0942

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5467.3882

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5472.4092

1730/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5482.8296

1741/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5480.5498

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5475.1035

1764/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5477.4951

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5477.4673

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5473.8301

1797/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5469.8452

1808/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5465.2085

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5466.8623

1830/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5462.0439

1842/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5467.0332

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5471.8213

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5468.4946

1876/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5471.9082

1887/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5469.5259

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5467.1382

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5462.1069

1917/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5463.4673

1926/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5459.2891

1936/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5468.0791

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5468.9814

1957/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5470.4707

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5473.0474

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5463.1328

1989/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5464.2383

1999/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5464.7749

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5461.1982

2020/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5469.8521

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5467.5625

2043/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5470.2710

2054/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5469.8105

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5466.9258

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5455.2676

2088/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5452.7305

2099/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5450.5542

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5444.8110

2122/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5446.6860

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5444.9419

2144/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5441.9575

2156/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5437.1123

2167/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5435.7622

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5429.7056

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5432.1694

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5430.3843

2213/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5436.1992

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5442.7388

2235/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5437.1821

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5432.8882

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5429.7549

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5424.2500

2282/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5422.6221

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5421.4224

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5423.1426

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5420.1836

2327/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5418.1436

2339/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5423.9263

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5431.3550

2361/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5439.8540

2372/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5439.1689

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5436.1221

2395/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5431.3228

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5432.1196

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5436.2422

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5433.8193

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5430.2231

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5432.1514

2461/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5423.1387

2472/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5425.7837

2483/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.8115

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.4072

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.8613

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.0088

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.5483

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5422.8286

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5418.8496

2559/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5418.7900

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5411.7759

2581/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5409.8989

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5407.9580

2603/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5407.0249

2614/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5406.7402

2625/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5400.6064

2636/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5410.0757

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5405.9800

2658/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5407.9131

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5407.4204

2680/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5414.1860

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5417.8545

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5420.2358

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5422.3833

2724/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5424.4419

2733/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5424.0806

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5425.9121

2753/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5426.3823

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5425.6641

2775/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5427.8164

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5425.5942

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5424.1079

2808/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5427.9146

2819/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5425.1851

2830/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5429.2456

2841/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5430.0718

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5431.1250

2863/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5431.9233

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5432.9619

2885/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5432.2354

2896/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5431.2998

2908/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5431.3809

2919/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5428.0571

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5424.1338

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5422.0884

2953/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5419.3799

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5415.5845

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5412.0991

2987/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5411.8623

2998/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5413.8975

3005/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5410.0293

3011/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5412.9688

3019/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5407.2988

3030/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5409.2339

3041/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5411.7612

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5411.4795

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5410.5776

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5408.6167

3086/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5415.1221

3098/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5415.2246

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5412.0811

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5417.2837

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5413.7446

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5415.2871

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5416.6899

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5417.2676

3180/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5412.3672

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5410.3311

3202/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5412.4736

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5414.0361

3224/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5412.3047

3235/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5411.2661

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5409.4487

3258/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5412.7241

3270/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5421.5786

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5428.1348

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5430.6948

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5433.4707

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5436.8403

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5436.5195

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5435.5210

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5433.7070

3360/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5430.6299

3371/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5433.3296

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5429.7925

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5427.6421

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5426.1382

3416/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5426.8662

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5423.1104

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5423.8828

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5422.5034

3461/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5422.0161

3473/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5421.8247

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5417.9224

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.4023

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5419.7944

3517/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.7227

3528/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5418.4639

3539/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.5991

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5419.5117

3561/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5418.5176

3573/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5418.3550

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5418.6509

3595/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5417.1738

3606/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5422.1406

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5417.3569

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5417.4922

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5419.5557

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.1016

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.2983

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.7715

3686/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5420.5356

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5419.0317

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 20s 5ms/step - loss: 5418.1548 - val_loss: 124.1996

Epoch 11/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:15 37ms/step - loss: 4785.2524

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5186.9902

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5299.8169

  36/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5243.7866

  47/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5248.6191

  58/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5190.7295

  69/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5105.6270

  80/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5001.1162

  91/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 4908.8394

 102/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5014.0757

 114/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5027.1099

 126/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5119.8301

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5094.2812

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5110.4141

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5136.5962

 168/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5201.4399

 178/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5223.9575

 189/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5194.6606

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5184.3164

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5167.9595

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5238.2837

 234/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5229.0942

 245/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5230.9541

 256/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5254.8984

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5262.3511

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5190.9097

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5177.0146

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5221.9551

 312/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5215.5835

 324/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5204.8950

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5218.9395

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5184.5156

 360/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5228.6099

 371/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5210.2622

 383/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5207.1006

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5204.3770

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5217.9678

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5223.8506

 428/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5230.3540

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5210.1069

 451/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5232.9927

 460/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5250.5552

 470/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5254.2329

 481/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5284.9399

 492/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5302.3301

 503/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5285.4321

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5273.0674

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5291.2290

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5313.5234

 547/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5303.3501

 558/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5293.3833

 570/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5292.9604

 582/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5294.7300

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5301.5420

 599/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5296.0215

 607/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5301.9844

 616/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5299.4478

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5312.2900

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5311.6245

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5284.8867

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5289.6875

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5272.4336

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5290.2866

 694/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5290.3452

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5276.8125

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5261.3374

 727/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5261.4629

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5257.0024

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5257.3545

 751/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5250.0410

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5241.7266

 773/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5244.2251

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5237.2549

 796/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5223.8779

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5236.6772

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5229.0942

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5222.9463

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5232.6284

 852/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5226.2480

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5247.6304

 875/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5239.3828

 886/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5236.5269

 897/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5242.4292

 908/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5268.3818

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5262.2778

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5269.7207

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5267.2026

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5266.8745

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5264.3438

 973/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5259.6104

 984/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5263.5767

 995/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5264.9609

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5262.6133

1018/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5255.6753

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5251.9854

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5240.6826

1051/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5238.8066

1063/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5229.7075

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5239.5557

1086/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5232.5166

1098/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5237.7812

1110/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5227.4062

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5238.5327

1131/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5231.5034

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5231.4531

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5233.1294

1165/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5228.2051

1177/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5231.5288

1188/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5228.6680

1199/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5220.6704

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5217.9209

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5219.3350

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5208.3701

1246/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5202.9165

1258/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5198.8066

1269/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5212.1484

1280/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5209.3687

1291/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5219.2969

1302/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5218.7856

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5213.4092

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5208.0127

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5203.5171

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5202.0264

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5193.3008

1364/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5199.1221

1375/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5189.8804

1387/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5193.0361

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5195.7651

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5197.6055

1421/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5200.1021

1432/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5205.6914

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5216.5239

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5217.2881

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5225.4932

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5224.6938

1489/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5233.6890

1500/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5232.7056

1512/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5235.9307

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5231.7832

1535/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5240.8267

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5236.2422

1558/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5230.0884

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5226.3477

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5230.6440

1591/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5232.3994

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5237.8198

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5242.6577

1624/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5237.3770

1635/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5238.0381

1647/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5240.6157

1659/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5234.8081

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5234.3765

1684/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5236.4868

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5233.0576

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5241.6821

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5249.2583

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5241.0757

1743/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5241.4741

1755/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5234.5801

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5231.1646

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5227.4736

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5224.1240

1803/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5225.4219

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5219.4390

1828/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5215.1392

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5209.5693

1852/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5213.9336

1864/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5212.0776

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5215.8076

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5220.1455

1900/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5226.1084

1912/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5218.0864

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5218.8877

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5227.3545

1949/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5226.6323

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5219.1958

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5221.7578

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5222.2075

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5230.5688

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5225.6626

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5233.6646

2033/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5241.2427

2046/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5245.5557

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5253.5093

2069/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5253.0522

2081/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5258.7134

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5268.6787

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5271.1860

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5269.1382

2129/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5261.1943

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5264.7910

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5267.2061

2165/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5263.6650

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5264.0068

2189/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5261.6196

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5257.7925

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5263.1455

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5260.5264

2237/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5265.4639

2249/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5260.1655

2261/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5259.5068

2273/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5258.5205

2284/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5258.7017

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5255.4072

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5248.7842

2321/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5250.2051

2333/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5249.7358

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5250.0962

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5245.7632

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5242.3096

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5237.5405

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5235.4800

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5231.2324

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5224.7031

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5227.6216

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5228.7329

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5229.6050

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5231.6597

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5234.1963

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5237.3164

2503/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5241.5742

2516/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5241.5430

2529/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5235.6147

2541/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5236.1396

2554/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5235.1890

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5239.4033

2578/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5234.9717

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5235.5483

2603/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5242.0889

2615/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5244.2021

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5243.8188

2639/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5242.9419

2651/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5247.4702

2663/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5241.0381

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5246.2500

2688/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5247.5923

2700/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5244.3184

2712/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5241.2954

2725/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5246.1875

2737/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5248.7827

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5250.6948

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5252.5386

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5248.2383

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5248.5439

2799/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5249.0684

2811/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5249.6646

2823/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5247.4277

2835/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5241.7622

2847/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5242.2563

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5239.0698

2870/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5237.5347

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5237.3643

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5242.0356

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5253.5767

2917/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5251.5029

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5250.7402

2941/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5249.2290

2953/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5247.5103

2965/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5255.0059

2977/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5259.9736

2989/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5259.4067

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5254.6943

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5253.4985

3026/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5256.1265

3038/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5252.9268

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5251.3018

3062/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5251.2061

3074/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5247.1792

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5246.6284

3098/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5249.3608

3110/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5244.4146

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5243.2104

3135/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5241.9668

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5239.4263

3161/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5241.7637

3173/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5244.5752

3185/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5246.4888

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5245.7896

3209/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5245.0166

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5243.3789

3232/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5237.6187

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5238.9238

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5239.6714

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5238.9233

3279/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5237.6689

3291/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5237.2329

3303/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5236.8145

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5235.4346

3326/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5237.9775

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5238.8945

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5237.9790

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5241.6279

3376/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5244.3301

3388/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5243.9775

3400/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5246.1914

3413/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5245.1235

3426/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5244.7949

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5240.3525

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5238.0264

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5240.5884

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5239.5586

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5240.5552

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5242.8599

3510/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5242.7227

3522/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5243.1016

3534/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5241.7129

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5241.9771

3558/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5241.7241

3570/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5242.2588

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5242.9580

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5245.9634

3606/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5248.6069

3619/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5249.0713

3631/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5252.2236

3644/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5257.5630

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5260.7871

3668/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5264.1582

3679/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5263.6440

3692/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5261.6396

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5260.2114 - val_loss: 877.2030

Epoch 12/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:02 33ms/step - loss: 787.5690

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4481.5713

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4549.5894

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4421.6011

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4696.2256

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4769.3975

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4756.9160

  89/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4905.2788

 101/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5010.5659

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5085.5352

 125/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5117.8662

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5129.4204

 150/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5155.5127

 162/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5151.4922

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5195.4849

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5211.4771

 197/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5231.4263

 209/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5212.6655

 221/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5319.7563

 231/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5332.8184

 243/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5299.7266

 255/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5318.5088

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5290.3979

 280/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5269.6655

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5257.9897

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5230.1802

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5237.8823

 328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5206.1567

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5219.6963

 353/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5242.6855

 365/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5208.6333

 376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5207.7358

 389/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5218.6519

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5229.0454

 415/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5211.6499

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5217.4536

 440/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5210.7129

 452/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5216.5845

 464/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5197.4653

 476/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5209.7930

 488/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5221.8052

 500/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5224.3818

 513/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5235.1558

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5250.4526

 537/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5255.2593

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5230.3506

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5213.1997

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5217.7305

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5225.3062

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5212.3022

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5220.4556

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5231.2568

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5241.7373

 647/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5261.2148

 660/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5257.2539

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5269.5249

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5254.2739

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5252.2563

 710/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5245.0698

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5254.9185

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5251.7168

 747/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5236.6260

 759/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5240.1372

 771/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5244.8550

 783/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5242.9463

 795/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5247.9556

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5259.3491

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5272.6567

 832/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5265.3672

 844/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5257.9077

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5264.2456

 867/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5257.2744

 879/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5253.3882

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5252.0640

 904/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5248.0825

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5252.3574

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5244.3193

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5238.6543

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5245.0869

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5242.6382

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5238.0688

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5232.3276

 999/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5245.0132

1011/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5249.4106

1023/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5250.5010

1034/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5245.9434

1045/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5239.3169

1057/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5237.2217

1069/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5242.3403

1081/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5247.6064

1093/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5264.7183

1106/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5266.0586

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5259.3931

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5261.9561

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5278.3804

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5283.1084

1166/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5284.0625

1179/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5293.1890

1191/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5287.1255

1203/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5285.2617

1215/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5296.5854

1228/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5300.1953

1240/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5309.1440

1252/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5319.5063

1264/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5329.1973

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5339.4912

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5327.1694

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5333.8247

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5333.7104

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5330.9097

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5343.8301

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5349.3193

1361/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5341.8418

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5343.3770

1386/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5341.1802

1398/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5335.3569

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5321.0986

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5330.3740

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5325.4829

1447/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5321.4766

1459/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5310.2134

1471/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5311.4141

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5308.9297

1496/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5319.3018

1509/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5322.4248

1521/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5319.0942

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5313.4165

1547/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5307.1899

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5306.5088

1571/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5318.0010

1584/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5326.4170

1597/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5317.4829

1609/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5316.1494

1620/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5319.0039

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5317.6621

1644/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5315.1675

1656/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5319.7046

1667/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5322.6074

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5314.7778

1693/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5306.7847

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5308.0269

1717/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5316.4517

1729/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5320.1738

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5319.2969

1754/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5316.2383

1766/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5308.9414

1778/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5311.7466

1790/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5310.7544

1802/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5311.7866

1814/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5311.7471

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5309.0781

1840/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5321.4624

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5325.9399

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5323.7759

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5318.1577

1890/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5312.4844

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5317.2573

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5322.4897

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5329.5283

1938/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5328.9097

1951/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5330.2275

1963/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5329.4819

1975/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5331.1338

1988/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5331.9097

2001/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5324.0122

2013/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5327.4097

2024/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5326.1152

2036/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5331.5952

2048/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5337.2881

2060/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5346.5083

2072/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5355.1680

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5350.8901

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5347.1108

2109/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5346.5581

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5348.9902

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5347.4731

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5339.9121

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5343.4785

2170/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5341.4585

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5345.8369

2196/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5347.9507

2208/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5356.8032

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5359.6445

2229/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5362.8003

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5359.0601

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5361.8403

2263/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5356.9175

2275/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5357.8159

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5352.2046

2298/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5356.6465

2310/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5364.4707

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5365.3101

2334/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5361.9272

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5361.6567

2359/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5364.0742

2371/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5367.6665

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5371.0420

2395/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5366.5103

2408/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5367.0503

2421/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5369.9634

2433/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5373.4380

2446/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5374.1206

2458/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5377.4624

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5379.7075

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5376.2744

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5377.2739

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5381.3291

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5378.1069

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5376.2939

2543/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5373.9238

2556/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5372.6089

2568/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5365.4561

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5362.9351

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5360.6118

2601/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5363.6279

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5362.9575

2618/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5361.6250

2626/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5363.4292

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5359.2515

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5352.8818

2657/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5352.6245

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5356.9932

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5353.9258

2693/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5352.8872

2705/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5350.8496

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5354.4102

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5350.0244

2742/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5345.7534

2754/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5342.2246

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5342.2310

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5335.7373

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5336.0366

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5335.2285

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5332.8164

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5334.4595

2838/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5335.5923

2850/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5332.4917

2862/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5331.6450

2874/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5329.6401

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5327.6577

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5326.8843

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5328.5059

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5325.0952

2937/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5325.4668

2948/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5322.9307

2960/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5321.0654

2972/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5321.8374

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5319.7988

2997/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5317.8496

3009/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5316.9004

3022/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5315.0581

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5311.1865

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5310.8984

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5309.3784

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5308.2354

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5310.7754

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5313.6743

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5317.0405

3120/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5313.6343

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5313.9102

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5314.5459

3157/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5314.0391

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5312.8970

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5312.9326

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5314.6797

3205/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5314.4536

3217/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5310.3623

3229/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5306.6226

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5304.8892

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5303.4512

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5305.1372

3278/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5305.5938

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5306.3213

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5314.7729

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5317.7134

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5322.5908

3339/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5321.4927

3351/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5319.3560

3363/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5321.3306

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5318.3604

3387/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5318.4175

3399/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5316.2886

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5317.5591

3425/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5317.1865

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5318.6118

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5323.0547

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5318.6016

3473/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5321.3945

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5324.6362

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5323.7305

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5322.7441

3520/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5321.9048

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5325.6284

3544/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5322.4321

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5322.6260

3569/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5324.6235

3582/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5324.9990

3594/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5322.2646

3606/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5322.4849

3618/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5321.6274

3630/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5318.0762

3642/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5318.6274

3654/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5319.4316

3666/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5317.3086

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5315.5264

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5313.4287

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5312.8647 - val_loss: 81.8533

Epoch 13/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:05 34ms/step - loss: 4538.8291

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5355.8618

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5142.4346

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5300.7817

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5478.3120

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5212.7969

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5102.8276

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5029.1123

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4954.7432

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4897.6367

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4887.0254

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4839.9194

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4901.6934

 160/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4842.6079

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4893.0649

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4898.7778

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4960.4326

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4943.0649

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4903.2134

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4954.9443

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4949.3413

 260/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4952.0200

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4961.6421

 284/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4990.5645

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4998.0435

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4977.8960

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4973.6914

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4977.3101

 344/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4990.8252

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5020.3125

 369/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5047.2871

 378/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5017.4302

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5032.9199

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5068.5713

 406/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5097.8916

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5088.0957

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5093.0151

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5070.1118

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5099.2832

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5131.5640

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5132.0903

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5143.9961

 503/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5120.4658

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5109.6753

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5110.9634

 540/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5113.5347

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5114.3403

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5114.8081

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5101.8101

 589/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5088.9883

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5100.5845

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5097.5405

 627/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5092.1943

 639/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5093.4414

 650/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5082.0923

 662/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5086.6802

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5090.3506

 686/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5084.6909

 699/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5085.9175

 711/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5075.1582

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5106.7856

 735/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5121.7104

 747/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5127.3501

 760/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5111.4775

 772/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5106.3467

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5110.2715

 795/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5100.8481

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5077.2314

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5072.9175

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5077.0967

 845/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5066.1274

 857/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5060.3521

 869/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5058.6948

 880/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5060.5776

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5051.8682

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5055.6294

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5061.3901

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5065.1172

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5062.7363

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5054.7417

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5073.7461

 977/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5067.9482

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5070.3696

1001/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5071.4233

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5085.2729

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5091.6099

1038/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5097.4033

1050/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5100.7749

1062/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5106.5752

1074/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5107.3823

1086/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5106.7007

1099/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5118.3711

1111/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5118.3848

1123/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5123.5366

1135/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5129.4248

1146/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5129.5835

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5122.3853

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5116.3535

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5128.1382

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5129.6460

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5120.3535

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5144.2114

1231/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5150.3135

1242/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5152.0239

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5142.1206

1266/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5146.6265

1279/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5146.9790

1292/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5142.3276

1304/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5143.9775

1316/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5145.2490

1328/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5150.7148

1340/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5152.2168

1353/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5159.8994

1365/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5157.2085

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5148.9072

1389/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5144.3433

1401/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5136.6782

1413/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5130.2847

1425/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5129.0669

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5129.5884

1450/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5136.6309

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5125.8145

1474/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5131.6206

1486/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5124.3975

1498/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5124.7871

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5120.4458

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5122.4897

1535/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5120.4019

1547/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5125.7129

1559/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5131.5171

1572/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5120.0815

1583/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5122.9497

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5122.1089

1607/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5117.5400

1619/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5104.3564

1630/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.0786

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.1548

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5114.0605

1667/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.9434

1679/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.5781

1691/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.3472

1703/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5107.5327

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5108.2534

1726/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5115.4292

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5117.3667

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5120.4971

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5122.5625

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5123.8730

1788/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5131.9360

1800/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5132.5894

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5130.5503

1824/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5128.6250

1837/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5126.8589

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5129.5034

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.0444

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.9219

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.4097

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5122.5571

1909/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5129.3350

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.7812

1932/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5123.5381

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5122.6992

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.8667

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5129.3516

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.7412

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5120.9707

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5119.8828

2018/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5115.2046

2030/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5121.6577

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5117.0693

2054/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5110.1738

2067/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5110.7759

2079/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.0122

2090/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5107.6675

2102/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.2842

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5102.2056

2126/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5099.7793

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5100.0288

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5107.8843

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5111.5308

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5111.6890

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5113.4292

2197/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5112.4126

2210/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.8569

2222/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.6455

2234/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5104.5068

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5109.2749

2258/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.7305

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5111.3857

2282/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.3613

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.1821

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5101.2148

2319/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5104.3301

2331/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5103.5308

2343/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5109.5352

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5106.5830

2367/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5107.8975

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5109.6836

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5111.1245

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5113.7656

2414/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5117.4795

2424/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5111.7671

2432/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5111.8765

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.4009

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.7598

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5119.3438

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5115.8506

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5116.4639

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5113.2490

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5108.0645

2525/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5108.5200

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5108.9966

2548/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5113.6455

2560/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5107.8296

2571/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5108.6704

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5110.0903

2596/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5105.4268

2608/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5102.8691

2621/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5101.8682

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5099.7500

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5097.4858

2657/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5098.5825

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5102.8276

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5109.1362

2694/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5109.9741

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5111.0303

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5118.3086

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.0591

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5123.6709

2755/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5118.5493

2768/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5120.6895

2781/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5120.6392

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5122.9976

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.7866

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5123.3081

2829/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.6641

2842/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5126.2778

2853/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5125.4771

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5123.1016

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5118.9712

2888/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.5581

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.0249

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.1626

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5134.1274

2938/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5138.6924

2950/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5139.7031

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5142.7295

2975/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5141.8735

2987/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5141.3975

2998/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5140.9487

3010/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.0977

3021/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5146.5215

3033/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5145.9771

3045/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.4297

3058/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.9927

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.7954

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.2153

3095/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5148.3628

3106/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.1289

3118/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5149.3081

3129/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5150.5601

3142/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.8677

3155/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5155.9819

3167/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5152.2720

3179/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.4102

3191/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5152.4707

3203/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5157.6440

3215/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5161.3760

3227/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5161.3848

3240/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5159.7104

3252/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.4780

3263/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5161.1055

3275/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5160.0752

3287/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5162.1533

3300/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5162.6138

3312/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5161.7300

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5162.6035

3336/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5159.8677

3347/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5155.6982

3358/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.5381

3371/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.2241

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.0503

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.8242

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.4624

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5155.7729

3432/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5156.7598

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.7925

3452/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5155.6523

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.3018

3473/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5153.1611

3484/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5153.4463

3496/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5153.7500

3508/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.1875

3520/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.8188

3532/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5160.0186

3544/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.0166

3556/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5166.7534

3568/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5169.1758

3580/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5172.5654

3592/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5172.9468

3604/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5173.5820

3617/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5172.7432

3630/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5172.7148

3641/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5170.9009

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5172.1538

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5168.6440

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5165.6382

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5165.6934

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5162.1118

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5160.9463 - val_loss: 907.7439

Epoch 14/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:05 34ms/step - loss: 2986.4780

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5546.6543

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5350.7852

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5369.7798

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5444.8315

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5519.6396

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5356.4453

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5299.5737

 100/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5166.1597

 112/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5104.7202

 124/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5049.0366

 136/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5094.4360

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5075.0063

 160/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5105.6353

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5134.8657

 186/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5103.8032

 198/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5066.2241

 210/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5087.0586

 222/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5114.9829

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5136.7964

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5089.9263

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5088.0420

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5059.6523

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5053.1592

 295/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5053.8374

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5046.2314

 319/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5043.1099

 331/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5068.5601

 342/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5076.6230

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5086.0537

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5059.7495

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5052.3643

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5050.0259

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5017.9146

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5027.5225

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5086.3257

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5060.3716

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5053.0483

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5065.2744

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5063.2817

 489/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5048.0430

 500/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5072.2100

 512/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5093.3076

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5093.0957

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5133.4224

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5128.1211

 561/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5142.0786

 574/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5124.3804

 586/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5133.9917

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5136.6255

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5131.0913

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5124.2593

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5131.6016

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5126.5332

 658/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5121.0913

 670/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5119.0933

 681/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5140.4780

 693/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5164.9849

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5159.9727

 716/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5177.4536

 728/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5155.5601

 740/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.6206

 752/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5159.9907

 765/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5182.6206

 777/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5172.0791

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5167.0518

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5152.1348

 815/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.2642

 827/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5167.9312

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5163.8848

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5163.7090

 863/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5160.0713

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5167.2500

 889/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5181.2441

 901/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5182.0439

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5177.1401

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5175.3101

 938/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5182.0869

 950/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5188.1519

 962/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5179.6270

 974/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5186.6465

 986/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5191.2515

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5194.6211

1010/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5198.2661

1022/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5215.3218

1035/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5205.8530

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5209.5923

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5224.0576

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5222.9292

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5215.9434

1096/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5218.1479

1108/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5226.7886

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5224.8936

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5221.6392

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5218.7910

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5226.1431

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5219.0605

1182/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5211.2402

1194/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5205.3384

1206/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5196.2788

1218/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5204.7866

1230/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5210.3330

1243/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5206.9463

1256/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5217.7241

1268/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5220.0654

1280/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5227.6865

1293/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5221.8296

1306/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5222.7637

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5221.4722

1331/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5217.6846

1344/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5210.7490

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5210.6221

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5209.9683

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5219.4385

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5214.3511

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5206.0591

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5208.3550

1429/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5211.4678

1441/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5222.6465

1452/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5221.6670

1464/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5229.5566

1477/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5231.5356

1490/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5228.6382

1502/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5233.7783

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5234.7065

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5233.1650

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5230.1455

1545/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5229.1772

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5221.9375

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5215.9570

1581/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5219.2798

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5219.9668

1606/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5213.7563

1617/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5207.6660

1630/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5206.0107

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5203.5986

1654/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5200.6963

1666/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5203.4639

1678/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5199.4009

1690/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5192.9170

1702/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5195.6860

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.1333

1726/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.1631

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5174.4648

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5173.7002

1762/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5178.7588

1774/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.2983

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.2827

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5178.1294

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.9546

1824/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5185.6162

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5184.6201

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5191.7656

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5195.4438

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5193.2051

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5192.2915

1897/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5194.9873

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5189.1143

1923/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5187.7090

1935/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5191.0728

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5188.1538

1961/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5190.5537

1974/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5188.2007

1986/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5203.0269

1998/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5205.3271

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5207.7012

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5204.7148

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5205.9204

2047/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5208.1743

2060/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5208.4580

2073/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5202.7554

2085/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5199.3306

2097/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5196.4805

2110/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5198.2729

2123/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5202.6890

2134/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5203.1211

2146/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5203.2456

2159/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5210.8730

2171/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5208.9863

2183/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5206.7764

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5208.2710

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5209.6128

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5207.8286

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5201.3682

2243/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5203.3281

2255/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5212.3418

2266/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5206.0767

2278/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5207.2642

2291/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5208.3105

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5211.0693

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5212.3198

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5213.8911

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5212.3755

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5216.3354

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5215.3984

2377/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5214.6650

2389/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5211.9917

2401/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5204.2720

2413/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5211.5771

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5206.9512

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5201.9858

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5201.5112

2461/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5200.7622

2472/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5199.3779

2484/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5202.5024

2496/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5204.8608

2508/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5205.6904

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5203.3042

2534/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5206.3979

2546/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5200.8203

2558/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5202.6431

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5205.0107

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5201.5728

2595/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5199.9805

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5201.3184

2618/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5202.4697

2630/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5200.6538

2641/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5198.8022

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5195.6699

2666/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5193.5947

2678/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5190.8564

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5194.0596

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5192.4297

2714/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5190.7324

2726/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5186.7236

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5186.7314

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5187.2173

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5191.2886

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5185.5693

2787/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5181.8765

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5182.1211

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5178.6978

2824/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5179.4639

2836/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5180.8828

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5181.6851

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5178.8096

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5178.4595

2882/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5179.0020

2894/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5177.2803

2906/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5174.9990

2918/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5173.4956

2930/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5172.0688

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5166.4668

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5166.8975

2967/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5163.2886

2979/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5162.1792

2991/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5160.2759

3003/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5160.7930

3016/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5158.2139

3028/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.8853

3040/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5150.4980

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5146.9551

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5145.8408

3076/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.5034

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.5811

3101/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.0898

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.2520

3123/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.7310

3136/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.0229

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5140.5737

3160/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5138.2915

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.5938

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.4761

3195/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.7515

3207/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.1602

3220/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.0176

3232/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.6519

3244/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.2793

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.8926

3269/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.0493

3281/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.6768

3293/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.8394

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.6592

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.9746

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.5332

3342/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.1104

3353/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.6577

3365/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.5474

3377/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5147.1538

3389/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.9531

3402/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.0293

3415/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.7100

3426/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.4551

3438/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.8750

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.2378

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.8691

3474/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5155.1108

3486/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5153.5674

3498/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5159.5322

3511/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.8560

3524/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.5122

3537/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5156.9761

3549/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.1104

3561/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5160.7700

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5160.5000

3586/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5164.0811

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5163.6758

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5163.3306

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5163.9668

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5164.7466

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5163.1616

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5159.1587

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.2026

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5154.9937

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5151.0371

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5151.4966 - val_loss: 67.2055

Epoch 15/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:12 36ms/step - loss: 5310.2085

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5257.7231

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5227.2598

  36/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5099.0957

  47/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5208.6196

  59/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5374.6997

  70/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5312.1538

  82/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5338.7271

  93/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5265.5093

 105/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5324.3608

 116/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5262.7759

 124/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5325.2002

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5305.6294

 141/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5300.2085

 151/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5206.1323

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5154.2363

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5197.6719

 185/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5235.0464

 196/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5189.0801

 208/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5166.7388

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5184.0757

 232/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5217.2563

 244/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5202.5894

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5186.8345

 265/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5164.1299

 276/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5156.6704

 287/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5155.8130

 298/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5151.4502

 307/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5142.7266

 316/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5122.3506

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5107.6108

 334/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5099.8760

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5116.9697

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5111.7173

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5113.0723

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5129.7969

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5163.7778

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5190.7534

 386/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5188.5112

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5196.9946

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5195.6060

 411/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5184.3379

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5182.1826

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5181.8843

 436/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5168.7075

 445/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5192.0068

 454/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5181.9136

 464/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5147.7974

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5150.7383

 482/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5137.3853

 492/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5161.6997

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5149.6069

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5150.1157

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5151.9302

 530/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5133.2964

 540/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5139.5220

 550/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5134.8564

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5123.0957

 570/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5137.4971

 580/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5147.2666

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5147.5254

 600/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5174.3188

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5165.3369

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5163.8794

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5151.4644

 641/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5154.1167

 652/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5156.6978

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5143.3179

 673/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5136.7554

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5151.7900

 695/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5157.9092

 706/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5170.9219

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5172.1138

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5171.1094

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5167.8604

 753/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5159.3784

 765/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5136.6738

 777/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5129.9414

 789/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5120.4121

 799/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5126.2153

 809/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 5105.6206

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5102.0952

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5108.0166

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5098.3110

 850/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5089.6406

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5078.5098

 871/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5081.0166

 881/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5076.5405

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5076.7236

 902/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5062.7725

 913/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5073.5513

 924/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5074.7998

 934/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5076.3838

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5071.7837

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5075.0752

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5073.1392

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5062.4092

 987/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 5ms/step - loss: 5078.3730

 998/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5075.3101

1008/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5072.9399

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5067.3320

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5063.3350

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5068.1714

1051/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5068.5864

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5082.5767

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5076.0317

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5080.4072

1094/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5092.6743

1104/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5087.1421

1115/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5090.8203

1126/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5084.2441

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5088.9551

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5084.0845

1159/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - loss: 5077.8228

1170/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5075.9609

1181/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5073.2485

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5071.2905

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5064.9565

1212/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5066.1499

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5059.4082

1233/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5064.7949

1244/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5063.8853

1254/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5064.2290

1265/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5063.4834

1277/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5070.6406

1289/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5075.3833

1301/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5077.2266

1313/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5070.7275

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 5087.7246

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5091.7729

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5090.5264

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5087.0879

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5095.0840

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5101.5703

1395/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5096.0581

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5084.5186

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5100.3970

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5094.7681

1442/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5093.8335

1453/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5093.6919

1465/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5099.6851

1476/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5097.4985

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5099.6157

1496/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5090.9258

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 5092.2163

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5094.0557

1524/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5094.9800

1536/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5089.5308

1548/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5092.2881

1560/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5099.7598

1572/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5098.7427

1584/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5095.7344

1597/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5094.2778

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5093.2871

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5096.8735

1635/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5098.5244

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5096.1685

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5097.4819

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 5100.6069

1684/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5095.9819

1696/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5103.0859

1708/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5102.1714

1721/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5107.1094

1733/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5105.7803

1745/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5107.1724

1756/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5108.6885

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5112.8467

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5123.2832

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5126.5205

1805/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5126.6562

1817/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5122.8247

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5128.5874

1841/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5124.0166

1853/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - loss: 5124.9629

1865/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5121.5933

1877/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5113.2036

1889/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5109.6216

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5111.8354

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5114.7534

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5118.0454

1937/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5117.9668

1950/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5121.6074

1962/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5122.9312

1975/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5118.9556

1987/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5123.7930

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5126.1948

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5126.3311

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5124.9028

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 5126.3726

2047/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5128.9849

2059/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5137.4805

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5133.4468

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5138.1953

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5140.5415

2107/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5151.2119

2119/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5157.2661

2131/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5168.2637

2143/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5176.1709

2155/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5176.8711

2167/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5175.0317

2179/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5171.9438

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5171.3613

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5170.0044

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5169.4370

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5160.7305

2238/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - loss: 5158.0181

2250/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5155.0903

2262/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5151.3525

2274/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5155.4150

2286/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5163.2930

2298/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5159.8315

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5161.8433

2323/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5164.8149

2335/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5165.7349

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5166.2090

2359/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5164.8687

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5165.8242

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5163.2988

2395/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5169.1157

2407/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5168.7842

2420/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5170.1201

2432/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - loss: 5168.8682

2445/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5163.1138

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5167.8628

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5177.2402

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5175.6421

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5178.1406

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5174.6460

2519/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5178.0635

2531/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5179.8208

2543/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5181.1997

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5181.3428

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5181.7593

2580/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5183.2969

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5183.2212

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5183.2896

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5181.4399

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 5175.6875

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5175.2939

2653/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5179.8877

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5181.7134

2677/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5180.1045

2689/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5177.8047

2701/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5177.9590

2713/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5173.4194

2726/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5169.4199

2738/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5173.1138

2750/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5169.2671

2763/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5174.2959

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5172.0425

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5168.8257

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5165.5747

2813/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5168.9580

2825/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5164.9316

2837/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 5165.3384

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5168.5459

2859/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5173.6914

2871/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5179.5181

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5178.5864

2897/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5177.2734

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5177.8794

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5180.4009

2933/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5181.9609

2945/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5181.8271

2958/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5179.7520

2971/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5180.6147

2984/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5185.0967

2997/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5184.4229

3010/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5182.5117

3022/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5183.1064

3034/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5183.4321

3046/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 5183.0181

3059/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5183.0752

3071/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5183.4497

3083/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5188.6729

3094/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5193.6987

3106/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5197.3516

3119/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5197.7549

3132/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5198.0000

3144/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5195.8950

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5195.7476

3169/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5194.3501

3180/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5196.1885

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5193.3389

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5191.8486

3218/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5194.2285

3229/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5194.6245

3241/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5191.9854

3253/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5193.1426

3266/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5196.3481

3278/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5197.3506

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5195.7539

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5193.5449

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5194.7607

3325/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5194.0977

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5191.4653

3349/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5187.9678

3361/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5192.4927

3373/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5195.5742

3385/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5198.2075

3396/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5196.8145

3403/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5195.8330

3411/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5193.1738

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5192.0942

3434/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5189.4829

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5190.0713

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5192.3472

3470/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5193.7026

3482/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5190.4678

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5187.1895

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5184.4883

3520/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5183.3438

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5181.4072

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5181.4058

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5179.1958

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5179.2324

3579/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5178.9839

3591/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5174.9604

3604/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5177.0044

3616/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5177.6396

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5176.9409

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5178.2939

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5178.6255

3666/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5181.6040

3678/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5179.1470

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5183.5171

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 5182.2212 - val_loss: 728.6365

Epoch 16/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:02 33ms/step - loss: 5028.4600

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5834.2012

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5408.4761

  39/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5403.1489

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5273.1704

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5462.1338

  75/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5456.0825

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5334.2026

  99/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5417.3989

 111/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5441.1050

 123/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5432.9453

 136/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5401.4976

 148/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5409.1411

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5354.5957

 170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5319.1631

 181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5332.6104

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5309.1416

 205/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5290.1929

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5247.9810

 229/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5253.1543

 242/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5256.0239

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5256.7104

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5221.4453

 279/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5214.8540

 292/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5219.6665

 304/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5249.0190

 317/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5227.0879

 329/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5245.6060

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5257.2002

 352/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5253.6431

 364/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5267.3994

 376/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5246.1592

 388/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5267.4658

 400/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5282.6440

 412/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5270.6606

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5285.1284

 436/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5268.0269

 448/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5227.8774

 461/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5217.4077

 473/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5194.0000

 485/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5184.2358

 497/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5192.3423

 509/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5192.4229

 521/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5186.1265

 533/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5181.0444

 545/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5180.1768

 557/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5186.9814

 569/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5191.1689

 581/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5195.5918

 593/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5202.6548

 605/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5215.8027

 618/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5206.7710

 630/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5197.2974

 642/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5195.3037

 655/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5188.5845

 667/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5190.6265

 680/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5185.5391

 692/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5180.5229

 705/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5194.4209

 717/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5199.4429

 729/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5195.9946

 741/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5213.7969

 753/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5216.9463

 766/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5232.8896

 778/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5223.9692

 790/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5209.4736

 802/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5215.5723

 814/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5227.6792

 826/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5225.0635

 838/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5226.2178

 851/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5227.6899

 863/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5221.7876

 874/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5218.0439

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5216.6943

 895/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5220.7808

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5217.0225

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5210.3252

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5197.9448

 943/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5212.0952

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5215.8657

 968/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5220.2593

 980/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5202.6470

 992/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5191.3271

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5183.6748

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5173.7695

1029/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5174.9722

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5177.0859

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5178.8862

1066/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5181.9326

1079/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5184.5132

1092/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5184.7295

1103/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5179.5425

1116/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5175.9375

1128/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5174.3618

1140/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5176.7622

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5184.6084

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5177.5786

1177/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5178.8706

1190/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5172.1128

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5182.1948

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5172.8335

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5163.9404

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5172.9116

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5178.0073

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5184.0137

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5184.7949

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5172.0913

1297/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5165.3125

1305/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5165.4692

1314/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5164.4590

1325/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5174.8428

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5175.5537

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5173.7739

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5180.2998

1372/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5181.2021

1384/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5181.1313

1395/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5171.2480

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5172.7788

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5177.6890

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5180.8174

1444/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5178.2710

1456/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5173.2061

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5170.8330

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5163.3667

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5157.1157

1505/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5155.6235

1517/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5154.2285

1529/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5168.2202

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5164.5718

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5174.1802

1565/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5171.4302

1577/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5170.3223

1588/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5170.6343

1600/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5167.3804

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5183.7671

1625/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5192.9277

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5192.4116

1650/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5192.4873

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5188.3521

1674/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5186.4785

1686/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5189.8970

1698/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5193.6304

1710/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5192.3896

1721/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5190.9727

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5187.6855

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5184.4478

1756/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5187.1528

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5182.3945

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.6870

1792/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5191.5933

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5186.6440

1815/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5182.8750

1827/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.7720

1839/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5177.8804

1851/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5178.7788

1864/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5177.0161

1876/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5174.1973

1888/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5175.3032

1901/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5172.4595

1913/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5180.8364

1925/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5183.6479

1936/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5184.8120

1948/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5183.0454

1960/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5184.1978

1972/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5187.3276

1984/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5200.7285

1996/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5206.4912

2008/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5208.6074

2020/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5203.5098

2032/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5202.1655

2044/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5216.6592

2056/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5218.0977

2068/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5215.9248

2080/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5219.1660

2092/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5221.8979

2104/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5219.7549

2116/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5216.5435

2128/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5215.5181

2141/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5212.6250

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5211.0073

2164/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5208.1333

2177/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5207.9600

2189/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5213.3433

2201/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5219.1860

2214/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5225.4648

2226/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5216.8633

2239/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5220.3862

2251/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5220.6743

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5223.2642

2276/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5219.0771

2288/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5217.1436

2300/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5217.4448

2312/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5217.7710

2324/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5214.7246

2337/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5211.9980

2350/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5212.5708

2362/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5221.9473

2375/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5220.9536

2387/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5221.3506

2399/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5219.2739

2412/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5221.3398

2425/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5225.5894

2437/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5228.9341

2450/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5232.2007

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5232.3286

2474/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5234.8496

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5236.1826

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5236.8818

2510/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5231.4360

2521/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5233.5171

2533/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5236.4819

2545/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.4741

2557/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5240.6528

2570/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5240.9277

2582/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.8540

2594/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5236.0889

2606/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5231.0430

2619/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5224.5464

2632/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5223.7915

2645/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5224.6831

2657/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5222.1875

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5214.7778

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5212.8013

2693/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5210.4395

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5212.0049

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5210.6245

2731/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5210.0591

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5207.5215

2754/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5207.1733

2766/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5207.9111

2778/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5207.6528

2790/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5204.4170

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5205.8999

2814/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5209.1040

2826/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5211.4961

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5211.2847

2851/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5215.2358

2864/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5218.6191

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5219.3325

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5219.7358

2902/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5226.9243

2913/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.6758

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5229.9175

2938/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5226.4253

2950/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5227.2749

2962/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5226.9985

2974/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5229.0942

2986/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5231.2446

2998/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.3540

3010/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5227.1987

3023/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5229.1606

3035/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5227.6099

3047/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5223.8843

3060/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5222.1401

3072/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5224.6733

3084/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5228.6953

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5231.4424

3108/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5235.9907

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5231.0244

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5229.6274

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5226.4604

3156/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5225.8037

3168/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5223.4331

3181/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5225.3257

3193/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5226.7417

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5224.7964

3219/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5225.8799

3230/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5224.9033

3242/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5222.3960

3254/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5220.4023

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5223.1587

3279/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5225.0703

3291/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5225.9805

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5222.9653

3314/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5220.3315

3326/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5222.6987

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5222.7197

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5224.1631

3362/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5220.9712

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5219.1113

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5218.8706

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5217.1909

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5219.1226

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5216.9243

3433/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5218.6597

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5216.9570

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5216.3750

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5218.4116

3481/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.4878

3493/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.7422

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5225.7568

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5224.2656

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.1626

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5226.4282

3554/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5226.7764

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5229.3203

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5229.1426

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5225.6616

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5226.7734

3613/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5233.2017

3624/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5229.4624

3636/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5231.6191

3648/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5230.9746

3660/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5232.0181

3672/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5232.4697

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5231.0859

3696/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5228.8379

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5229.0742 - val_loss: 1556.1888

Epoch 17/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:08 35ms/step - loss: 7322.1704

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5717.4653

  25/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5659.5371

  37/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 6003.2183

  48/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - loss: 5862.5684

  60/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5718.5435

  72/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5476.9126

  85/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5345.0425

  97/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5447.8110

 109/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5389.8418

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5409.2080

 134/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5362.9702

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5416.1733

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5388.3013

 169/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5356.2485

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5373.0200

 192/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5301.3232

 204/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5318.5864

 216/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5300.4404

 227/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5275.3979

 237/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5291.2988

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5290.0151

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5215.1929

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5258.9780

 284/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5232.3760

 296/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5188.5571

 309/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5191.5005

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5208.0884

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5201.2236

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5161.3931

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5194.5239

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5183.8696

 380/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5186.6274

 393/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5183.0913

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5199.4766

 417/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5209.2192

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5170.6895

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5167.4019

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5181.0332

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5205.4492

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5191.0464

 488/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5159.3032

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5141.8301

 511/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5151.3989

 524/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5169.0107

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5164.4565

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5187.8965

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5178.5586

 572/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5160.2964

 584/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5179.1382

 596/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5203.2393

 608/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5198.2080

 620/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5223.3760

 632/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5227.3594

 644/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5221.9937

 657/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5228.1528

 670/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5207.4834

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5206.8799

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5221.5815

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5231.0156

 719/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5215.0415

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5211.3174

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5213.3018

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5208.2417

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5193.6484

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5182.8613

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5190.2344

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5174.3062

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5167.9858

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.8242

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.2583

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5181.7017

 866/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5177.9775

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5166.8042

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5163.0503

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.5625

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5159.0811

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5150.1929

 941/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5158.2783

 953/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5152.2451

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5151.2842

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5152.4917

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5161.0942

1000/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5188.6636

1013/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5183.2603

1025/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5210.4897

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5203.7603

1049/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5191.0073

1061/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5188.2275

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5175.7363

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5174.1743

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5171.5923

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5169.2793

1119/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5167.9575

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5168.9531

1145/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5172.8062

1158/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5174.1938

1169/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5172.4658

1175/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5173.2998

1184/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5175.1948

1189/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5172.6079

1197/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5167.1514

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5174.0396

1222/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5160.8921

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5148.5103

1247/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5154.9253

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5166.8628

1271/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5169.8833

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5166.7236

1296/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5164.7637

1308/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5167.8447

1320/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5181.0957

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5177.0449

1344/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5191.1567

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5191.3496

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5189.0088

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5180.7671

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5187.9209

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5193.5522

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5181.3369

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5175.9263

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5166.9932

1456/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5167.2378

1468/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5171.6724

1480/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5167.5688

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5166.1709

1506/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5172.8970

1518/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5189.7388

1531/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5186.5688

1543/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5183.8379

1556/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5177.1006

1568/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5177.5933

1580/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5175.2065

1592/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5174.2305

1604/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5170.7739

1616/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5170.7100

1629/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5185.9463

1641/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5180.1240

1653/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5182.0923

1665/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.6787

1677/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.9790

1689/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.8018

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5182.5776

1714/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5182.2080

1726/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.7681

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5181.9736

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5175.4722

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5168.5234

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5164.2637

1785/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5162.9985

1798/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5157.5366

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5155.3452

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5152.6816

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5148.3193

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5141.2568

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5140.8335

1872/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5145.3140

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5142.6348

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5134.4521

1907/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5136.5913

1919/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5135.0728

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5132.2666

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.7969

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.8662

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5128.6104

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5124.4185

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5121.7778

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5116.2568

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5113.8232

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5114.0005

2041/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5111.8511

2053/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5116.3379

2066/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5119.0728

2078/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5115.4053

2091/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5123.1006

2103/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5118.2690

2115/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5113.3413

2128/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5115.4038

2140/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5111.5322

2153/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5112.7070

2166/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5121.9038

2178/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5115.8828

2190/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.7061

2202/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5109.1050

2215/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.3931

2228/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5111.3047

2240/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5110.0132

2252/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5113.1299

2264/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.7524

2276/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.8560

2287/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5112.1104

2299/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5116.2456

2311/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5117.8135

2323/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.9009

2335/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5129.0093

2347/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5128.0610

2359/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5124.9507

2371/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.5703

2383/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.0913

2396/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.9585

2408/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5126.5659

2421/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.6157

2433/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5123.8843

2445/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5127.1870

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5126.8862

2470/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5130.6372

2482/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5129.2788

2494/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.2607

2506/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5131.8281

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5128.8105

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5132.0664

2543/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5128.6157

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5123.7383

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5125.0420

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5125.7432

2592/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.0483

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5122.3306

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5116.4321

2628/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5112.4917

2640/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5115.4312

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5114.9546

2664/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5115.3101

2676/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5117.7173

2687/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.3237

2699/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5124.6357

2711/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5129.9673

2723/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5127.6641

2736/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5125.3145

2749/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5127.8735

2761/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5124.3311

2774/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5122.7280

2786/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5120.0825

2798/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5119.3052

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5122.1953

2820/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5123.5903

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5122.1489

2845/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5127.8999

2857/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5131.6587

2869/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5132.3286

2881/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5130.9194

2893/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5128.3496

2905/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5124.4902

2917/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5125.4360

2929/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5124.2729

2942/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5129.6060

2954/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5134.0063

2966/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5132.5181

2978/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5134.0659

2990/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5133.3018

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5137.5801

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5138.8359

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.0093

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5137.5791

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.7910

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.5537

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.7275

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.1533

3099/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.2866

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5145.6289

3124/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.4380

3136/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.0562

3149/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5146.3335

3161/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.7607

3174/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5140.4580

3186/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.4917

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.9556

3209/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.1353

3222/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.4282

3235/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.5488

3247/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5149.3037

3259/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.1641

3271/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5147.6763

3282/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.9595

3295/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5149.8965

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.2222

3316/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.0513

3328/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5146.7275

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.9976

3354/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.7793

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.1348

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.3940

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.4697

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5149.6367

3417/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.4111

3429/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.7417

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5147.7334

3455/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5148.6719

3468/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.2607

3481/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5149.3438

3493/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5149.2964

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5147.9951

3517/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5147.3521

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5146.3008

3541/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5148.7002

3553/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5147.9937

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5148.3066

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5144.4443

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5140.7305

3603/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5140.9189

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5144.1909

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5143.2368

3640/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5144.4087

3652/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5140.4961

3664/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5139.3892

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5136.4131

3687/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5132.4707

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5129.7856

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5129.1226 - val_loss: 679.9539

Epoch 18/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:24 39ms/step - loss: 2506.8101

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 3785.6812

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4557.7441

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4412.7998

  53/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4414.5420

  66/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4716.1069

  78/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4686.3740

  90/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4941.7974

 102/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5047.2422

 114/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5097.4463

 126/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5134.5010

 138/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5039.8042

 151/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4976.5952

 163/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5028.9854

 175/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5076.2690

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5123.8267

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5097.9907

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5068.7822

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5076.0190

 235/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5099.0713

 247/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5138.2441

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5202.3032

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5150.2778

 285/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5123.9263

 297/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5093.8823

 309/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5117.8721

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5130.5986

 334/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5149.8809

 346/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5143.1846

 358/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5155.8447

 370/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5150.1362

 382/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5162.3066

 394/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5138.2832

 406/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5123.7886

 419/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5130.0981

 431/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5134.5386

 444/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5143.9458

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5138.5249

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5113.0762

 480/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5107.5039

 492/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5112.6768

 504/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5117.6157

 516/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5100.6978

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5100.3037

 541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5120.7163

 554/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5107.0220

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5121.1514

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5120.6572

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5136.8408

 603/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5122.9844

 615/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5130.4688

 626/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5117.3970

 638/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5101.4067

 651/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5119.0898

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5127.7910

 676/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5135.9048

 688/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5121.0688

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5133.5864

 712/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5125.2217

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5122.8711

 730/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5133.9863

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5132.4995

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5141.7090

 762/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5132.7554

 774/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5141.4878

 784/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5133.9102

 795/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5143.8325

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5160.9380

 819/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5158.4307

 831/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5163.4121

 843/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5147.3862

 854/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5141.6602

 865/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5164.5996

 878/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5166.5405

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5185.4268

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5177.3101

 915/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5159.7725

 927/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5169.6782

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5177.8833

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5192.6040

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5204.6318

 977/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5212.4536

 989/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5207.0088

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5221.4849

1015/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5228.0068

1027/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5227.7817

1039/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5235.9639

1051/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5238.1157

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5224.4614

1076/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5230.5439

1089/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5238.6992

1100/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5229.3853

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5220.8730

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5221.7554

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5209.4639

1149/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5205.8091

1162/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5191.1440

1173/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5184.8306

1185/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5180.4204

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5177.3901

1211/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5164.1392

1224/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5156.3638

1236/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5157.7402

1249/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5167.5298

1261/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5174.7744

1273/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5169.9668

1285/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5161.5889

1297/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5157.5474

1309/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5153.8843

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5153.7168

1334/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5156.5747

1346/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5157.9517

1358/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5163.1978

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5168.3262

1383/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5166.2642

1396/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5162.4263

1408/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5163.1670

1420/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5159.6401

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5161.4189

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5163.5371

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5160.5537

1469/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5155.8354

1481/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5154.8047

1493/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5156.6855

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5151.8101

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5149.9097

1525/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5140.8179

1537/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5137.8296

1550/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5125.7656

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5113.0493

1574/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5112.5581

1586/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5098.2222

1598/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5094.3257

1610/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5102.7676

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5100.6538

1634/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5101.6582

1646/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5106.3203

1658/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5102.0605

1671/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5103.6045

1683/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5106.4668

1694/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5098.0806

1705/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5095.4746

1717/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5100.7666

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5098.8418

1740/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5102.3770

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5100.6904

1765/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5105.6123

1776/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5106.7471

1788/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5117.0010

1801/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5113.7778

1813/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5112.6553

1825/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5112.8501

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5110.3989

1847/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5109.8672

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5108.5508

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5111.3252

1883/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5113.3066

1895/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5102.6206

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5103.0630

1921/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5103.9946

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5101.7729

1947/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5100.3823

1958/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5100.6025

1969/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5095.2046

1982/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5093.3501

1993/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5098.0508

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5101.8857

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5106.3599

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5098.4287

2042/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5097.7871

2054/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5099.9829

2066/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5108.2817

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.9683

2090/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.7261

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.3530

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5112.2212

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.7046

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.8135

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5097.6880

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5101.3838

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5097.3062

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.0771

2195/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.8760

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.8101

2218/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5106.4810

2231/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5104.9468

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5107.6572

2257/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5102.6973

2269/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5101.5166

2281/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5097.7910

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5094.3027

2306/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5093.9170

2318/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5101.2563

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5102.0601

2342/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5097.8184

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5098.3628

2367/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5093.6553

2380/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5093.1094

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5092.8267

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5090.1035

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5085.6875

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5085.5874

2438/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5084.9390

2446/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5087.9521

2457/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5090.6001

2469/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5089.8311

2481/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5093.0811

2493/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5090.0923

2505/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5084.5010

2518/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5088.2954

2530/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5085.3247

2542/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5085.3428

2555/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5088.8560

2567/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5088.9810

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5084.8213

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5084.2515

2604/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5089.5122

2616/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5086.3623

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5083.3633

2633/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5081.4946

2644/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5080.5254

2656/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5078.1860

2668/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5085.5698

2679/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5085.7627

2691/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5082.4180

2703/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5081.2969

2715/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5077.7939

2727/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5077.9087

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5079.6904

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5077.4971

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5078.5205

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5082.9062

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5082.5771

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5079.7861

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5076.9683

2824/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5077.1318

2836/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5080.6362

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5083.5635

2860/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5082.1904

2872/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5088.9175

2884/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5092.8896

2896/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5091.8823

2909/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5088.2222

2920/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5088.3613

2932/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5087.8696

2944/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5098.1040

2956/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5107.0435

2969/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5105.5342

2981/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5105.2178

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5113.0991

3005/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5113.4272

3016/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5113.0327

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5114.5742

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5114.6582

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5116.8159

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5113.4497

3077/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5109.5103

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5109.6157

3102/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5108.4150

3114/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5107.8555

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5104.0859

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5104.3184

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5109.4780

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5112.0107

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5108.9209

3188/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5108.3784

3201/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5107.0005

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5102.2456

3225/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5102.8848

3237/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5102.0591

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5103.0898

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5100.7217

3273/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5102.1499

3285/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5102.4937

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5108.7505

3311/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5107.0991

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5105.6118

3337/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5102.9297

3348/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5104.6597

3359/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5101.7729

3371/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5100.2788

3383/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5101.5796

3395/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5099.5786

3407/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5096.5688

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5094.8696

3433/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5096.7886

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5098.9150

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5096.1250

3470/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5100.4019

3482/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5097.1602

3494/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5099.6108

3506/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5099.6934

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5098.0811

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5096.8247

3542/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5096.1724

3555/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5092.6313

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5093.6880

3579/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5096.0854

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5093.6431

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5094.3149

3614/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5094.3325

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5093.7910

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5094.0967

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5092.2456

3663/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5094.6099

3676/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5094.7681

3688/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5098.7788

3700/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5100.3496

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5101.3193 - val_loss: 377.9666

Epoch 19/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:07 35ms/step - loss: 2831.3931

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4168.9971

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4565.6582

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4879.1899

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4861.6924

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4847.7026

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4935.2539

  86/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5022.3564

  98/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4991.9937

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4939.5674

 122/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4861.0630

 134/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4866.5806

 146/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4910.5776

 158/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4904.0586

 170/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4875.8481

 183/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4872.0669

 195/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4847.6245

 207/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4874.6055

 220/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4847.4834

 232/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4825.4565

 243/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4790.8164

 255/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4764.2227

 267/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4737.0186

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4742.4282

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4732.0430

 302/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4818.1860

 315/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4839.5972

 328/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4852.8340

 341/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4899.7417

 354/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4852.4741

 366/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4870.1323

 377/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4879.3071

 390/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4912.7310

 402/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4903.3257

 415/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4907.6445

 427/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 4903.2114

 439/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4936.9287

 452/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4955.1680

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4961.0762

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4959.5420

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4990.5757

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5013.2202

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4984.5366

 523/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4977.3623

 531/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4971.7803

 541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4973.5317

 553/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4982.0957

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4979.7881

 577/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4951.4819

 589/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4951.0342

 600/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4936.8896

 612/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4926.5630

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4925.8579

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4902.4688

 650/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4918.6313

 663/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4933.1182

 675/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4962.4502

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4968.1274

 699/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 4972.3887

 711/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4959.6353

 723/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4972.8848

 734/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4967.1504

 746/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4959.5415

 758/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4957.1455

 769/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4948.7422

 782/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4943.4800

 795/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4968.1494

 807/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4969.7119

 820/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4985.1313

 832/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4989.2842

 844/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4989.8315

 856/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4980.7104

 869/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4976.9678

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4981.5811

 894/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4991.6890

 906/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4975.9414

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 4970.3179

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4964.1143

 944/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4964.3589

 956/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4970.2705

 967/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4969.9204

 979/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4966.2993

 992/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4956.2451

1004/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4954.4790

1017/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4949.1821

1030/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4938.3467

1041/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4931.9351

1053/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4935.4756

1065/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4933.1719

1078/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4929.5718

1090/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4929.7554

1102/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4922.6616

1114/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4934.6616

1127/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4931.6133

1139/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 4923.7202

1152/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4922.6943

1164/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4921.2622

1176/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4932.9268

1188/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.7837

1201/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4933.0093

1213/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4949.7354

1225/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4943.1646

1237/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4939.7173

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4937.2373

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4949.3857

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4940.0244

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4942.6240

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4940.4341

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4947.7627

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4946.2598

1335/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4942.2007

1347/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4934.5332

1359/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4931.1660

1371/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 4933.8970

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.7031

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.1953

1407/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4938.7368

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4933.3906

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4931.1353

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4939.1201

1454/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.2373

1467/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4941.6543

1479/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4942.5474

1492/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4944.6699

1504/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4947.0933

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4943.6299

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4943.6836

1541/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4948.2964

1553/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4953.5142

1566/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4961.1709

1578/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4960.1797

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4958.9248

1602/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 4954.9399

1615/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4957.2769

1627/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4957.4482

1640/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.6597

1653/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.6445

1665/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.5908

1677/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4954.6050

1689/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.2822

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4963.2021

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4965.8296

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4967.0923

1738/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4965.7100

1751/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.5220

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.1216

1774/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4955.9736

1786/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4961.3252

1799/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4960.3062

1811/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4959.3042

1823/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4962.5249

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 4970.8027

1847/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4973.8472

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4981.2705

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4982.4932

1886/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4989.6978

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4997.2373

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4998.8750

1922/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4997.5654

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4991.0527

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4997.6958

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5000.4980

1972/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4997.3179

1985/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4999.3066

1997/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4999.7471

2009/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4997.0649

2021/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4998.5908

2034/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4998.8647

2046/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5001.8184

2058/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 4999.4424

2071/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4999.2881

2083/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5002.1924

2095/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5003.8179

2108/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5003.5615

2121/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 4999.6934

2133/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5009.1621

2145/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5003.7554

2157/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5005.9727

2169/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5004.9961

2182/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5000.3550

2194/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5000.1895

2206/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5013.4849

2218/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5008.5889

2230/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5006.2983

2242/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5012.8076

2254/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5010.6895

2267/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5012.1494

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5012.6504

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5010.0391

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5010.3457

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5016.5903

2328/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5013.6221

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5020.1626

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5027.3242

2364/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5023.2319

2374/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5030.4146

2386/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5034.8472

2398/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5032.1826

2411/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5037.4224

2423/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5035.5288

2436/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5040.9062

2449/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5043.4033

2462/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5038.8442

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5040.7769

2486/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5040.2832

2498/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5036.2891

2511/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5036.3037

2524/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5040.3330

2537/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.5542

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.8110

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5042.0205

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5043.1787

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.4082

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5044.2598

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.5273

2624/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5039.9512

2636/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5042.8247

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5042.5522

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5045.4170

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5049.3569

2684/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5049.2217

2696/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5046.1621

2708/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.6841

2719/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5038.4546

2730/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5041.0156

2743/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5039.5605

2754/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5038.9780

2767/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5034.3809

2779/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5032.9028

2792/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5028.9727

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5037.2954

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5031.3223

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5031.6543

2839/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5031.1826

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5038.1255

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5042.2417

2878/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5042.4121

2890/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5045.9346

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5045.0479

2916/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5045.3154

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5044.6060

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5045.2900

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5052.5063

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5051.1055

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5052.3291

2989/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5057.5781

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5061.5386

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5061.4751

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5062.3130

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5063.7988

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5066.7451

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5066.2300

3076/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5064.5474

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5061.7065

3101/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5061.9985

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5058.4712

3125/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5059.6387

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5059.8232

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5062.9902

3164/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5061.7676

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5062.9927

3188/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5060.9043

3200/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5060.1372

3212/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5059.9453

3225/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5059.7876

3237/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5058.9507

3249/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5059.0825

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5060.4468

3272/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5058.0898

3284/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5060.7173

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5061.3750

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5062.8223

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5060.5356

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5061.9209

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5063.9814

3356/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5060.6470

3368/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5062.2822

3381/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5058.1304

3393/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5059.8096

3405/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5059.7705

3417/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5059.9995

3428/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5059.3989

3439/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5060.2754

3450/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5057.9077

3462/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5061.7056

3475/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.9888

3487/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5066.9243

3499/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.0469

3511/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.5532

3523/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.9048

3535/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.0225

3547/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5066.8955

3560/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5070.5986

3572/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5071.7827

3584/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5073.3848

3597/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5072.8076

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5072.4302

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5069.7373

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5070.5654

3648/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5066.0645

3659/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5066.1997

3671/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5065.1816

3683/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5064.0713

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5065.5278

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5064.2017 - val_loss: 89.4884

Epoch 20/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:01 33ms/step - loss: 6126.5371

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4667.1812

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4876.9077

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4674.7671

  50/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4771.0962

  62/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5040.6665

  74/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4991.6167

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5019.2163

  99/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4973.5586

 110/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5086.2529

 121/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5182.0757

 132/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5171.4551

 143/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5153.9429

 155/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5237.0747

 167/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5264.7056

 180/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5283.0854

 193/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5297.2222

 205/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5366.4844

 217/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5320.0000

 229/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5314.5640

 241/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5325.4048

 253/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5267.9370

 265/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5263.8149

 277/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5242.9717

 289/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5219.1538

 301/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5239.2222

 313/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5230.6758

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5190.5986

 336/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5176.0469

 348/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5168.5122

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5166.0488

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5147.4409

 384/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5151.3198

 396/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5138.2036

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5144.7114

 420/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5177.7266

 432/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5172.3613

 444/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5161.1216

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5123.2178

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5135.0723

 481/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5139.8408

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5125.8481

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5120.6260

 517/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5110.9585

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5117.8447

 541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5126.7139

 554/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5117.9263

 566/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5091.5298

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5086.7285

 591/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5079.0503

 604/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5063.4707

 616/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5070.2310

 628/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5076.4722

 640/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5065.4614

 652/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5069.2812

 664/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5086.4194

 676/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5094.5107

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5106.9888

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5110.7012

 712/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5105.7065

 724/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5105.6802

 736/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5106.3516

 748/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5103.6323

 761/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5098.3242

 773/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5105.7905

 785/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5091.2891

 798/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5075.8418

 810/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5068.5708

 821/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5079.3413

 833/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5070.1558

 845/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5065.1143

 858/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5063.5596

 870/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5060.2241

 882/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5051.9033

 895/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5064.6060

 907/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5070.6362

 919/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5069.8027

 931/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5068.9932

 942/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5070.5757

 954/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5058.9023

 966/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5070.2021

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5069.5513

 990/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5072.9004

1003/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5082.4146

1016/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5083.6636

1028/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5104.6533

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5106.3496

1052/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5110.9277

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5120.1582

1076/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5118.3896

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5125.3125

1101/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5145.7056

1113/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5141.9854

1125/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5137.2603

1137/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5138.9272

1149/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5137.1553

1161/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5155.7495

1173/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5153.4614

1186/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5152.4028

1198/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5137.2798

1210/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5134.9575

1223/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5131.8340

1235/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5137.3027

1247/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5140.3062

1259/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5141.3984

1271/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5133.0586

1283/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5128.2368

1295/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5129.0659

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5126.1465

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5133.9346

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5138.2583

1344/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5143.0034

1356/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5150.3423

1368/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5147.4438

1381/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5153.6230

1393/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5151.8501

1405/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5163.1318

1417/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5164.7622

1430/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5166.6841

1442/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5161.2334

1454/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5164.5122

1466/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5158.5342

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5151.4546

1491/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5146.5942

1503/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5151.9136

1516/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5152.3257

1528/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5146.3022

1540/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5144.8135

1551/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5147.9688

1564/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5138.7900

1576/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5134.8818

1589/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5131.6660

1601/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5126.1475

1613/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5124.4102

1626/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5120.1831

1638/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5118.7915

1650/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5122.1763

1662/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5117.4858

1675/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5118.3896

1688/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5120.6724

1701/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5127.1016

1713/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5127.5967

1725/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5119.8750

1737/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5116.7139

1749/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5111.0776

1761/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5113.0933

1773/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5114.6597

1785/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5116.8271

1797/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5117.4507

1810/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5123.2285

1822/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5127.2964

1835/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5128.3306

1847/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5132.5464

1859/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5125.2754

1871/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5123.0059

1882/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5127.5254

1894/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5128.2583

1906/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5130.2427

1919/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5133.7065

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5131.4839

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5133.0757

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5130.8896

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5131.2861

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5129.2539

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.5278

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.7319

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5122.7275

2028/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5125.5879

2040/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5126.0386

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5118.8618

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5119.8164

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5121.5479

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5121.5034

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5125.1807

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5120.8354

2125/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5126.3579

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5126.4556

2148/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5134.5708

2160/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5128.1758

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5127.7578

2184/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5128.8643

2197/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5127.2202

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5128.7915

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5124.1475

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5116.6445

2246/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.7300

2258/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.0840

2270/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.4531

2282/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5114.0747

2294/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5115.3169

2307/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5110.5527

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5119.1870

2332/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5117.1841

2344/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5117.5654

2355/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5116.9351

2368/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5124.5269

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.8247

2394/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5118.6982

2406/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5115.0083

2418/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5113.2666

2430/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5117.7231

2442/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5121.3125

2454/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.7686

2466/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5124.0645

2478/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5123.7427

2490/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.7793

2502/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5124.1885

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5118.4097

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.4097

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5117.8271

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5113.4956

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5117.2427

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5114.4512

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5112.7222

2598/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5114.3066

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5112.0991

2622/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5111.1753

2634/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5111.9380

2646/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5112.6753

2657/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5112.9312

2669/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.1982

2681/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5115.9932

2694/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5118.3701

2706/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5119.7261

2717/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5119.6479

2728/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5120.1323

2740/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5118.8008

2752/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5118.2520

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5117.9165

2776/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5118.9531

2788/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5122.1611

2800/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5120.9751

2812/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5120.7773

2824/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5121.7866

2836/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5124.2031

2848/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5126.1431

2861/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5127.4961

2873/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5132.0171

2885/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5129.8252

2898/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5128.3911

2910/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5134.6689

2922/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5137.2271

2934/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5137.8359

2946/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5138.2881

2958/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5138.9409

2970/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5136.7183

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5136.6426

2994/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5138.3428

3007/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5136.6294

3018/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5137.0591

3030/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5138.7754

3042/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.1665

3054/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.0981

3066/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.6729

3078/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.8335

3090/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5143.6328

3103/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.9624

3115/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5136.8115

3127/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.2373

3139/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.6987

3152/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5140.5352

3165/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.2368

3177/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5141.3081

3190/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.2188

3201/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.2437

3213/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.4702

3226/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5139.0903

3238/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5136.5845

3251/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5135.1279

3264/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5136.4146

3276/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5133.5381

3288/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5139.2944

3301/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5138.3740

3313/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5140.1538

3324/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5139.9546

3336/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5139.9053

3348/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5139.0693

3361/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5139.2236

3374/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5141.7705

3386/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5147.2559

3398/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5147.4180

3410/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.4561

3423/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5144.9243

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5145.6313

3446/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5144.1567

3458/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5142.3979

3471/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5141.9287

3483/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5139.5269

3495/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5140.0894

3507/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5145.0093

3519/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5145.9238

3531/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5145.6392

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5147.9014

3555/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5144.3945

3566/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5142.4268

3577/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5139.3696

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5141.1978

3599/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5142.3438

3611/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5143.5264

3623/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5142.1138

3634/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5141.9683

3645/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5142.7856

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5143.5845

3667/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5146.4883

3678/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5144.3813

3691/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5147.2295

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5146.6011 - val_loss: 956.5284

Epoch 21/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:21 38ms/step - loss: 3194.8352

  12/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5089.2471

  23/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5281.0396

  34/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5206.5605

  45/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5353.6235

  57/3701 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 5440.5737

  68/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5564.0864

  80/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5374.2368

  92/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5289.7314

 104/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5303.4341

 116/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5238.4263

 129/3701 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 5298.6143

 142/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5205.7783

 154/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5316.6807

 166/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5386.5610

 178/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5354.5522

 191/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5339.1714

 202/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5330.1074

 213/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5314.7368

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5279.2808

 239/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5254.5122

 251/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5247.7876

 263/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5282.9131

 275/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5291.5552

 288/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5309.7915

 300/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5335.0049

 312/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5304.0732

 325/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5285.7949

 338/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5296.6118

 351/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5282.6748

 363/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5271.6133

 375/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5256.0771

 387/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5250.0005

 399/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5273.6294

 411/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5271.5298

 424/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5255.4556

 436/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5286.3555

 449/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5305.4932

 462/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5290.0010

 475/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5295.6382

 487/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5286.8994

 499/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5282.2876

 512/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5229.1167

 525/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5223.7603

 536/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5206.5845

 548/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5200.1323

 560/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5201.0488

 573/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5205.6079

 585/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5186.6914

 598/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5188.6177

 610/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5171.6226

 622/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5162.0728

 634/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5156.6226

 646/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5182.1299

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5193.3691

 672/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5184.7510

 684/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5168.4282

 696/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5173.4019

 708/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5174.2876

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5199.1494

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5201.9927

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5193.3306

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5190.5801

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5164.9370

 780/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5159.2217

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5167.8574

 805/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5176.4619

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5170.7925

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5176.0366

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5178.7417

 855/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5176.9292

 867/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5175.9438

 879/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5182.0483

 891/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5161.8970

 903/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5174.3608

 916/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5195.2485

 928/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5202.7925

 940/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5205.0264

 952/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5197.5679

 965/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5208.1084

 978/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5201.4004

 990/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5203.1328

1002/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5201.0742

1014/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5186.3120

1027/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5183.7339

1040/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5190.1592

1052/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5178.4365

1064/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5176.5254

1076/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5188.2031

1088/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5201.2627

1100/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5189.4863

1112/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5203.6396

1124/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5201.8359

1136/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5192.0649

1148/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5192.4644

1160/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5189.1792

1172/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5187.8882

1184/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5181.2168

1196/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5173.6885

1208/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5175.0605

1221/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5173.1475

1234/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5168.9082

1245/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5167.9346

1257/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5163.5820

1269/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5173.9189

1282/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5165.9985

1295/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5171.9702

1307/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5167.5205

1319/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5166.5981

1332/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5176.4546

1343/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5167.3652

1354/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5169.9531

1366/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5166.4336

1378/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5171.4009

1390/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5169.6162

1402/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5172.3257

1414/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5176.0864

1426/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5177.5557

1438/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5185.1104

1450/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5182.1001

1462/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5179.0474

1473/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5171.0615

1484/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5173.5293

1497/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5173.3740

1510/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5183.6948

1522/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5183.6177

1534/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5188.1182

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5186.9082

1558/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5180.5195

1570/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5177.0464

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5176.2808

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5175.0107

1607/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5172.4282

1620/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.6797

1632/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.6216

1644/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5177.5986

1656/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5170.7476

1669/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5172.7979

1682/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5176.9287

1694/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5174.8989

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5178.7285

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.2983

1731/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5180.6865

1742/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.6650

1750/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5186.7461

1759/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5190.4917

1770/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5190.9287

1782/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5187.4883

1795/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5183.0928

1807/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5172.4150

1819/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5175.7061

1832/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5170.3779

1844/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5165.8750

1856/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5172.9595

1868/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5172.8828

1880/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5172.5957

1892/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5170.7866

1902/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5170.0293

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5168.5610

1919/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5169.5293

1931/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5168.5601

1943/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5169.8896

1956/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5169.0859

1967/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5169.3457

1979/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5173.6758

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5179.2036

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5179.8481

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5176.4199

2028/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5174.9707

2039/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5173.0674

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5165.8149

2064/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5164.8369

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5159.7134

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5153.1123

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5149.1826

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5147.6577

2127/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5144.7012

2139/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5146.1533

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5145.0571

2161/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5144.7271

2173/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5150.1719

2186/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5154.4590

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5155.8940

2209/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5161.1055

2221/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5160.2622

2233/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5161.7168

2245/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5159.8896

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5164.0044

2267/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5163.4375

2279/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5162.6045

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5154.1050

2305/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5151.4209

2317/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5151.0127

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5146.8652

2341/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5144.6191

2353/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5148.1445

2366/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5153.0444

2379/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5152.4443

2391/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5157.0156

2402/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5152.6450

2414/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5157.4097

2426/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5152.8311

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5151.3081

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5154.6626

2463/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5152.9673

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5155.3867

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5155.5356

2500/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5157.0972

2513/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5154.0576

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5152.3799

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5150.9907

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5151.7559

2563/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5154.7129

2574/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5154.7725

2586/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5152.6133

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5154.7827

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5155.4604

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5152.2480

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5151.5088

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5149.0532

2659/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5146.4688

2672/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5146.3799

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5149.7100

2697/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5146.5269

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5146.2729

2722/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5152.7861

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5152.8545

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5155.6631

2759/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5152.1162

2772/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5151.3662

2784/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5152.2588

2797/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5151.2397

2809/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5151.6436

2821/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5151.7837

2832/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5152.9175

2844/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5149.8442

2856/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5148.7676

2868/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5146.8569

2880/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5140.0337

2892/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5139.1812

2904/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5139.0757

2916/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5142.1587

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5143.8984

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5141.0254

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5144.8091

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5148.3521

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5146.3013

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5143.7759

3001/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5150.2515

3013/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5149.9785

3025/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5150.6226

3038/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5156.0562

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5154.2271

3062/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.1367

3073/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5156.1377

3084/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5160.0640

3096/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5161.8472

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5158.6851

3122/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5161.7661

3134/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5162.3828

3147/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5160.2109

3159/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5155.3955

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.6890

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.7852

3197/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.6729

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5150.0996

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.7622

3234/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5157.6011

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5154.6460

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.4272

3268/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5155.8843

3279/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.0312

3290/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5160.0430

3302/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5160.2407

3315/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5160.8657

3327/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.5371

3338/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.5986

3350/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.4092

3362/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5157.5068

3375/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5156.1943

3387/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5154.0361

3400/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.7324

3412/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5150.1860

3424/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5153.3906

3435/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5151.1519

3447/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.6650

3459/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.5952

3469/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5152.7114

3479/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5155.8589

3491/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.0469

3503/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5156.7568

3516/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.3418

3528/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5159.5435

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.3374

3551/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.5332

3563/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5155.3350

3575/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.0264

3588/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5154.9312

3600/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.4243

3612/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5154.7183

3625/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5152.7256

3638/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5155.2759

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5158.0610

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5157.6724

3673/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5162.1558

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5163.2705

3697/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5162.8276

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5162.9062 - val_loss: 875.6523

Epoch 22/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:15 37ms/step - loss: 9049.2314

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5948.4619

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5908.6812

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5860.5752

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5739.6494

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5670.9927

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5532.4375

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5502.9258

 101/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5585.4233

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5554.4404

 125/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5501.1914

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5490.8149

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5462.6216

 161/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5450.8408

 173/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5535.7388

 181/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5560.1553

 192/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5598.1885

 203/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5666.6655

 215/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5572.0884

 226/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5552.8340

 238/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5553.8447

 250/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5533.7212

 261/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5508.9009

 272/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5535.4897

 284/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5508.3608

 296/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5469.0464

 308/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5420.5493

 321/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5434.4727

 333/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5422.1455

 345/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5386.6909

 357/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5448.7764

 368/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5447.9951

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5430.5723

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5431.3687

 404/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5487.3281

 416/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5469.2583

 429/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5474.5669

 441/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5473.5752

 453/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5449.6416

 465/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5425.8203

 477/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5425.7910

 490/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5417.4878

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5387.5278

 515/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5386.2305

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5380.0757

 539/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5378.0435

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5343.2993

 564/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5343.1743

 576/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5348.3291

 589/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5374.0034

 601/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5400.6025

 613/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5410.6865

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5393.7964

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5406.1670

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5416.9375

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5408.9414

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5401.5059

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5409.7900

 698/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5409.0464

 710/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5411.5708

 722/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5404.3330

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5406.2993

 744/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5401.2817

 756/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5397.7759

 768/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5383.9663

 781/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5387.0796

 794/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5392.0723

 806/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5403.3896

 818/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5398.3076

 830/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5409.4595

 842/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5403.5747

 853/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5395.9883

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5398.8232

 877/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5410.0063

 890/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5421.1426

 902/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5433.2168

 914/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5432.2163

 926/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5431.4360

 939/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5423.2329

 951/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5423.3091

 964/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5410.1934

 976/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5400.3877

 988/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5393.1665

1001/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5383.9722

1014/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5408.1968

1026/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5403.3369

1037/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5401.7441

1048/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5396.4810

1060/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5381.2744

1072/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5391.1201

1084/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5394.1621

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5396.8892

1106/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5394.6875

1118/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5390.6709

1130/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5390.5967

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5379.4741

1153/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5374.9678

1165/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5381.7173

1178/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5377.1587

1190/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5375.7417

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5373.8921

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5366.9585

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5370.2412

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5364.6577

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5358.6074

1262/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5357.0503

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5343.2734

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5344.3901

1299/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5339.3242

1311/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5339.1572

1323/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5333.6621

1336/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5324.3550

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5319.8174

1361/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5312.5630

1374/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5310.0303

1386/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5308.3784

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5303.8057

1410/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5313.8765

1422/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5318.1870

1435/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5315.5029

1448/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5312.6772

1461/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5307.9639

1474/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5308.4043

1487/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5300.2910

1499/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5313.7236

1511/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5315.3550

1523/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5315.3740

1535/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5317.8179

1546/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5314.2568

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5308.2070

1569/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5313.4341

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5314.0464

1595/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5308.9468

1607/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5308.4766

1619/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5311.1284

1631/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5306.5181

1643/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5306.3213

1655/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5312.1929

1668/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5306.5649

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5307.6963

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5307.0483

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5299.0801

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5297.7266

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5291.9160

1739/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5284.5923

1752/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5280.2231

1763/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5280.0239

1775/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5277.2036

1787/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5289.2510

1800/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5293.7168

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5295.7402

1824/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5294.4634

1837/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5290.2139

1849/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5296.1885

1861/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5298.7305

1873/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5295.3584

1885/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5296.1299

1898/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5300.1655

1910/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5297.4023

1922/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5295.0444

1934/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5291.5493

1946/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5290.9351

1959/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5290.7227

1971/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5282.1299

1983/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5285.9019

1995/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5280.6904

2007/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5283.0815

2019/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5279.1792

2031/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5283.5171

2044/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5281.0601

2057/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5283.7856

2070/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5278.9888

2082/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5274.2354

2093/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5275.6089

2105/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5274.0225

2117/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5269.3862

2130/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5266.5674

2143/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5264.5532

2155/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5267.6641

2168/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5261.4443

2181/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5261.0371

2194/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5260.5122

2207/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5261.8643

2219/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5262.6118

2232/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5260.3657

2244/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5260.9346

2256/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5260.9463

2268/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5259.4619

2280/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5263.4609

2292/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5262.7534

2304/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5263.1309

2316/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5268.3115

2329/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5267.4517

2340/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5261.0767

2352/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5256.5757

2365/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5254.3047

2378/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5250.6963

2390/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5249.0874

2403/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5248.2100

2416/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5248.9512

2428/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5253.2642

2439/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5250.8301

2451/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5252.7271

2463/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5253.1953

2475/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5258.1753

2487/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5259.6934

2499/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5256.9712

2511/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5254.4834

2523/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5253.3203

2536/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5251.2080

2549/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5252.1587

2561/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5248.9170

2573/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5247.3960

2584/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5244.2334

2597/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5243.8149

2610/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5249.0361

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5248.9932

2636/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5248.7773

2648/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5245.4370

2661/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5245.7769

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5256.5859

2686/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5254.5332

2698/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5254.7646

2710/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5254.0464

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5249.8950

2733/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5252.7852

2745/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5248.0967

2757/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5248.2173

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5241.2441

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5238.2437

2793/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5237.1216

2804/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5237.5229

2816/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5234.5903

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5230.0249

2840/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.4678

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5230.6748

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5231.3062

2878/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5231.1758

2891/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5234.6572

2903/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5233.9810

2915/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.8062

2927/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.4888

2939/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5228.1299

2951/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5231.7305

2963/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5231.8081

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5230.2539

2989/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5224.6460

3002/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5220.0771

3014/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5220.9717

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5222.5933

3040/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5227.0391

3052/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5231.6147

3064/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5237.3096

3076/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5235.0083

3088/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5234.4033

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5236.0981

3113/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5235.4858

3126/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5233.1689

3138/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5234.5586

3151/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5236.8271

3163/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5239.0576

3176/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5243.0059

3188/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5241.1479

3199/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5241.4038

3211/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5239.0127

3223/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5234.3096

3235/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5239.8296

3248/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5242.8101

3261/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5243.5332

3274/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5247.0420

3286/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5244.8628

3298/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5244.8911

3310/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5245.7363

3323/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5242.2529

3335/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5241.8926

3348/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5238.6855

3360/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5238.0762

3372/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5236.4116

3384/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5234.4033

3397/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5230.4165

3409/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5231.4946

3422/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5233.1348

3434/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5236.6968

3445/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5232.6558

3456/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5234.5742

3468/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5232.6992

3480/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5234.8350

3492/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5237.5283

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5237.4976

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5238.0405

3529/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5235.1079

3540/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5234.9727

3552/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5232.0415

3565/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5235.3828

3578/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5240.4829

3590/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5240.5161

3602/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5240.8926

3615/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5242.3608

3628/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5241.0845

3641/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5245.3174

3653/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5241.2495

3665/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5244.1543

3677/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5241.7251

3689/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5242.4888

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5240.2388

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5240.2388 - val_loss: 101.5920

Epoch 23/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:07 34ms/step - loss: 7138.5767

  13/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4696.8247

  26/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4469.0244

  38/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 4878.5454

  51/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5023.0430

  63/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5084.3296

  75/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5201.6382

  87/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5345.8408

 100/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5242.9097

 112/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5283.5474

 124/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5295.8945

 135/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5227.5098

 147/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5278.4365

 159/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5269.0542

 171/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5250.1870

 183/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5185.4419

 195/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5219.5850

 207/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5177.9429

 219/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5204.6099

 231/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5256.1328

 242/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5240.8965

 254/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5212.6475

 266/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5154.7720

 278/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5136.5688

 290/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5148.9004

 302/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5137.5059

 314/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5126.8037

 326/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5131.4102

 338/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5118.7402

 350/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5094.4634

 361/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5090.6406

 372/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5088.4829

 383/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5084.8887

 395/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5079.2930

 408/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5073.9902

 420/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5116.9766

 432/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5107.2002

 444/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5123.0942

 456/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5142.0908

 468/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5175.8340

 480/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5175.4805

 493/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5155.5142

 505/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5157.9590

 517/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5146.6440

 529/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5149.9907

 541/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5148.0352

 552/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5153.4365

 564/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5146.9268

 576/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5126.8838

 588/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5129.8940

 600/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5141.9048

 612/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5141.0508

 623/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5143.3555

 635/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5139.3760

 647/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5132.6797

 659/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5133.1445

 671/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5130.1704

 683/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5147.9092

 695/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5150.9438

 707/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5177.1162

 720/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5192.6138

 732/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5197.7656

 743/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5198.7422

 755/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5205.5625

 767/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5188.1445

 779/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5192.8354

 792/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5206.8984

 804/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5190.7959

 816/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5182.8169

 828/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5184.0869

 840/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5187.6021

 852/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5202.0820

 864/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5212.9385

 876/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5207.1450

 888/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5212.5474

 900/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5206.3730

 912/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5213.3267

 924/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5208.0449

 936/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5212.0737

 948/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5192.1323

 961/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5202.9849

 973/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5198.9116

 985/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5209.8491

 996/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5228.8423

1009/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5224.3076

1021/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5218.8057

1033/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5224.9199

1046/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5233.9712

1059/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5247.6338

1071/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5256.7114

1083/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5259.0605

1095/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5265.0986

1107/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5260.0981

1120/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5246.6880

1132/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5252.6675

1144/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5248.4238

1156/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5246.9619

1168/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5240.2676

1180/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5229.1587

1192/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5230.1562

1204/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5225.7529

1216/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5222.2637

1227/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5219.1274

1239/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5218.6953

1251/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5210.4976

1263/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5216.1865

1275/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5212.7954

1287/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5213.5664

1300/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5223.1606

1312/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5228.9150

1324/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5232.6548

1337/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5236.4097

1348/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5241.6475

1360/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5236.1699

1373/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5233.1841

1385/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5239.4106

1397/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5232.4761

1409/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5236.5449

1421/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5242.6538

1433/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5258.4678

1446/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5258.2969

1458/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5263.6841

1470/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5252.0317

1483/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5258.0083

1495/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5266.8179

1508/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5275.8940

1520/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5277.1152

1532/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5286.0991

1544/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5273.9736

1557/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5268.2788

1570/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5261.4893

1582/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5259.8154

1594/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5260.7734

1606/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5266.0078

1614/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5266.7002

1622/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5266.2568

1631/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5267.6191

1642/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5277.0566

1655/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5273.2646

1667/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5283.1514

1680/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5280.3013

1692/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5276.6030

1704/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5269.7236

1716/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5262.4985

1728/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5258.9067

1741/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5253.3784

1753/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5245.0957

1765/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5234.7080

1777/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5233.1411

1789/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5241.0293

1801/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5243.8032

1812/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5240.9331

1824/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5240.0400

1836/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5240.9463

1848/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5245.9888

1860/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5244.6968

1872/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5238.4785

1884/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5238.4321

1896/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5234.3047

1908/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5233.7295

1920/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5224.8525

1932/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5232.4863

1944/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5231.5195

1956/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5235.1729

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5231.2446

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5232.8164

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5235.7314

2005/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5228.1289

2017/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5222.9102

2029/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5225.0112

2041/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5217.2109

2052/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5222.1855

2065/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5228.7490

2077/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5239.5151

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5242.2451

2101/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5239.9248

2114/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5241.6660

2126/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5237.1426

2137/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5236.7017

2149/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5234.1450

2160/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5237.4175

2172/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5240.1328

2185/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5250.3818

2198/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5250.1294

2210/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5250.6382

2223/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5241.8848

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5247.1689

2248/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5242.5806

2260/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5247.8911

2273/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5241.7974

2285/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5243.2676

2297/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5251.2695

2309/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5252.3979

2322/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5255.3989

2334/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5253.2036

2346/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5251.5571

2358/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5255.3228

2370/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5255.5010

2382/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5253.0356

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5248.6104

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5246.3496

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5246.7612

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5249.6133

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5247.2925

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5238.2954

2466/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5237.7856

2478/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5240.3770

2491/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5244.0269

2503/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5243.8315

2515/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5244.5649

2526/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5244.6685

2538/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5243.0645

2550/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.3765

2562/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5235.2354

2575/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5234.7290

2587/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5234.7979

2599/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5236.0054

2611/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5238.2129

2623/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.4736

2635/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5235.3398

2647/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5231.7393

2660/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5235.5469

2673/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5238.7617

2685/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.5020

2697/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5236.1475

2709/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5234.6909

2721/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5235.3960

2734/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5237.9492

2747/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5235.9800

2759/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5233.8599

2770/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5232.0498

2782/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5238.0952

2794/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5238.1338

2806/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5237.8657

2817/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5240.2632

2829/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5240.8721

2841/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5238.5723

2853/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5244.2573

2865/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5245.5635

2877/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5242.0239

2889/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5237.6992

2902/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5240.8115

2915/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5245.2925

2928/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5243.0093

2940/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5242.1553

2952/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5245.8467

2964/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5251.3525

2976/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5251.3135

2988/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5250.2690

3000/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5251.0474

3012/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5250.7920

3025/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5247.7070

3038/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5245.5020

3050/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5247.3252

3062/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5242.9268

3073/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5244.5771

3085/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5242.9893

3097/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5242.7422

3109/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5240.5737

3121/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5239.3398

3133/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5243.8179

3145/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5242.8574

3158/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5237.6733

3170/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5238.6650

3182/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5238.0103

3194/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5232.9849

3206/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5229.8613

3218/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5228.3428

3231/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5233.9155

3243/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5235.9976

3255/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5237.1494

3267/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5234.9009

3280/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5234.5352

3292/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5232.9141

3305/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5229.1079

3317/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5227.6748

3329/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5228.5029

3341/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5226.0811

3354/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5224.3975

3367/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5221.6050

3380/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5221.2822

3392/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5221.0586

3404/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5222.7485

3417/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5223.0308

3429/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5224.6240

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5226.0894

3453/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5226.3076

3465/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5225.1973

3477/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5222.6074

3490/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5220.9585

3502/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5222.5547

3514/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5220.5854

3526/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5222.9922

3538/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.6396

3550/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.4263

3562/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5219.1919

3574/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5220.8672

3586/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.7485

3598/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5223.5942

3610/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5220.0684

3622/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5219.0591

3635/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5221.7642

3647/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5219.2485

3656/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5220.7319

3664/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5225.3667

3672/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5225.7539

3684/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5226.5093

3695/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5224.7134

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5226.0234 - val_loss: 247.8773

Epoch 24/800

   1/3701 ━━━━━━━━━━━━━━━━━━━━ 2:06 34ms/step - loss: 2928.6997

  14/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5611.7134

  27/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5871.8867

  40/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5683.2705

  52/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5539.0879

  64/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5445.6636

  76/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5513.6587

  88/3701 ━━━━━━━━━━━━━━━━━━━━ 15s 4ms/step - loss: 5374.5859

 101/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5403.9629

 113/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5327.3936

 125/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5185.7085

 137/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5175.7144

 149/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5180.3940

 161/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5109.8179

 174/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5139.7437

 187/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5151.8496

 199/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5178.6211

 211/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5151.0879

 223/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5150.1958

 236/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5136.9087

 248/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5153.0259

 259/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5213.1353

 271/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5205.8672

 283/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5185.7642

 296/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5160.5820

 308/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5161.2134

 320/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5160.9814

 332/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5150.2686

 344/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5131.5527

 356/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5108.7065

 367/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5134.4829

 379/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5128.0146

 392/3701 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 5133.2847

 405/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5114.9590

 418/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5110.3457

 430/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5101.3755

 442/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5107.5522

 455/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5074.0156

 467/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5056.4526

 479/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5065.5449

 491/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5040.2324

 502/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5027.5078

 514/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5025.6406

 527/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5056.4663

 540/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5033.9917

 553/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5035.0146

 565/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5045.5952

 578/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5025.8311

 590/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5024.0371

 602/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5025.6753

 614/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5030.1650

 625/3701 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 5048.7241

 637/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5049.0049

 649/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5055.1406

 661/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5050.5566

 674/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5080.6357

 687/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5092.7300

 700/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5097.7642

 713/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5071.5337

 725/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5065.6860

 738/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5070.1177

 750/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5076.2944

 763/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5058.1572

 776/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5077.7954

 788/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5072.3672

 800/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5059.9224

 812/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5055.6997

 824/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5054.6191

 836/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5061.1865

 848/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5063.2524

 860/3701 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 5053.7915

 872/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5059.9590

 884/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5053.6997

 896/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5048.4248

 909/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5054.8335

 921/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5054.3013

 933/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5050.1968

 945/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5045.4585

 957/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5034.0239

 970/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5020.8940

 982/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5030.6768

 994/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5027.5288

1006/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5041.1812

1019/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5044.1704

1032/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5052.5864

1044/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5061.5547

1056/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5057.6953

1068/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5068.8892

1080/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5081.5303

1092/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5085.2749

1105/3701 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 5068.0093

1117/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5078.2207

1129/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5087.9878

1142/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5075.2197

1154/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5086.9307

1166/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5093.4609

1178/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5091.0825

1190/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5086.0654

1202/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5089.7373

1214/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5084.8936

1226/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5082.2900

1238/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5082.2974

1250/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5077.5039

1262/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5080.6602

1274/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5076.1299

1286/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5077.2769

1297/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5075.9565

1309/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5075.6348

1321/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5072.7988

1333/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5065.5518

1345/3701 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 5071.8232

1357/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5066.7798

1369/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5066.7256

1382/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5065.5371

1394/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5075.0176

1406/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5080.6836

1419/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5077.0312

1431/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5082.0757

1443/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5074.4541

1455/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5083.1650

1466/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5079.6333

1478/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5075.7998

1488/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5084.4351

1500/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5086.1084

1513/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5087.9390

1525/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5089.4341

1537/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5095.3579

1549/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5096.6519

1562/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5090.7280

1574/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5093.1636

1587/3701 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 5097.3193

1599/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5098.4985

1611/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5096.5459

1623/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5095.4775

1636/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5098.9321

1648/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5100.8364

1660/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5094.4604

1672/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5087.5957

1683/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5087.6499

1695/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5088.4561

1707/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5095.4893

1719/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5085.3101

1732/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5079.8271

1744/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5087.2744

1756/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5081.5273

1768/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5084.7974

1780/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5073.8989

1791/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5070.8149

1804/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5069.7988

1816/3701 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5068.9541

1829/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5065.3208

1841/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5062.9736

1854/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5056.4644

1866/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5056.3638

1878/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5064.1807

1891/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5054.3848

1904/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5059.3569

1916/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5063.4424

1929/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5064.6108

1942/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5065.6802

1955/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5065.8984

1968/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5071.1641

1980/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5070.6099

1992/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5073.0903

2004/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5072.4062

2016/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5076.9639

2027/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5085.4287

2039/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5095.6396

2051/3701 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 5091.6582

2063/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5091.5146

2076/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5095.2295

2089/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5097.9307

2102/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5100.6357

2113/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5101.5215

2126/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5103.2607

2138/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5099.3267

2150/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5097.7715

2162/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5099.2861

2174/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5099.5649

2187/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5101.2827

2200/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5105.8311

2212/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5113.0054

2224/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5108.5278

2236/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5115.1572

2247/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5119.6074

2259/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5116.7285

2271/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5118.7598

2283/3701 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 5124.2090

2296/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5127.9053

2308/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.6865

2320/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5129.8296

2332/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5129.8999

2345/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.9121

2357/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5122.3252

2369/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5121.2461

2381/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5119.0049

2393/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5123.6396

2405/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5118.7129

2417/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.1343

2429/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.2490

2441/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.1543

2453/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.6812

2465/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5120.7485

2477/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5125.2456

2489/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5126.0840

2501/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5126.3154

2514/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5127.1387

2527/3701 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 5124.4805

2540/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.2563

2553/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5119.7188

2566/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5119.1270

2579/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5121.0854

2591/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5124.3857

2603/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5127.0229

2615/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5125.3125

2627/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5126.1460

2639/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5130.1294

2652/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5129.0088

2665/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5136.6143

2677/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5138.3979

2690/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5140.7773

2702/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5139.1577

2715/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5143.7827

2727/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5143.2163

2739/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5150.6992

2751/3701 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - loss: 5145.2891

2764/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5147.4639

2777/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5142.0156

2789/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5140.0181

2802/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5149.4492

2815/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5146.4253

2828/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5148.5303

2841/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5154.1104

2852/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5149.4072

2864/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5147.6206

2875/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5149.9038

2887/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5146.8804

2900/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5146.1958

2912/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5143.6543

2925/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5142.5820

2937/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5140.7153

2949/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5138.3091

2960/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5137.0767

2971/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5142.2578

2982/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5141.2812

2993/3701 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 5140.9902

3004/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5149.8774

3015/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5145.6641

3027/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.2964

3039/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.7163

3051/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5138.2437

3063/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5142.3008

3075/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5140.2681

3087/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5144.4497

3100/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5147.9995

3112/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5148.9722

3124/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5149.0762

3136/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5152.2197

3148/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5155.2041

3160/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.1348

3172/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5153.1851

3184/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.7461

3196/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5149.8892

3208/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5148.5103

3221/3701 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5151.3057

3233/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5154.4438

3245/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5156.8652

3257/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5157.9771

3270/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5158.7158

3283/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5159.3252

3296/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5159.2725

3308/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5159.9717

3320/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5161.8042

3332/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5167.4136

3344/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5164.8408

3357/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5165.2480

3370/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5168.6772

3382/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5174.2876

3395/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5174.1484

3408/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5175.1729

3420/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5179.8804

3431/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5182.8545

3442/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5180.6426

3455/3701 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5181.8735

3467/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5185.0088

3480/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5184.6606

3492/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5185.1519

3505/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5185.6978

3518/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5183.8535

3530/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5180.4111

3543/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5182.9033

3555/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5185.2866

3567/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5184.9517

3579/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5185.3149

3589/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5188.4165

3601/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5187.6104

3614/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5187.8447

3627/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5189.0977

3639/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5190.4561

3651/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5187.1221

3662/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5188.4673

3674/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5189.7852

3685/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5192.1504

3698/3701 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5192.7495

3701/3701 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 5192.2017 - val_loss: 117.1135

In [16]:
# and you can show how your model did

# since it's a single sample, we need to reshape
data = X[0]
data = data.reshape(1,10,7)
print(data)
print(model.predict(data))

# did we get close?
print(y[0])
# of course you can show scatterplots and everything else

[[[ 17.96  59.1  190.     5.     0.    30.09  10.  ]
  [ 19.94  59.4  190.     5.     0.    30.08  10.  ]
  [ 23.    49.69 210.     9.     0.    30.06  10.  ]
  [ 21.92  47.52 230.    11.     0.    30.04  10.  ]
  [ 23.    43.21 250.    13.     0.    30.05  10.  ]
  [ 23.    43.21 250.    11.     0.    30.06  10.  ]
  [ 23.    41.45 240.    13.     0.    30.07  10.  ]
  [ 24.08  41.3  240.    11.     0.    30.08  10.  ]
  [ 26.06  38.03 210.     8.     0.    30.08  10.  ]
  [ 28.04  35.05 220.    14.     0.    30.08  10.  ]]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step

[[  21.786896 1023.7622  ]]
[   3.92 1018.8 ]

In [17]:
# well done! You can also make scatterplots of actual vs. predicted
pred = model.predict(X)
pred

   1/1446 ━━━━━━━━━━━━━━━━━━━━ 6:44 280ms/step

  30/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  59/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  88/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 117/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 146/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 176/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 203/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 232/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 261/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 287/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 315/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 343/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 371/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 399/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 426/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 452/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 479/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 506/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 534/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 561/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 587/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 614/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 642/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 669/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 695/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 722/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 749/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 775/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 802/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 830/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 856/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 883/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 911/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 940/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 967/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 992/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1020/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1045/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1073/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1101/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1127/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1154/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1182/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1208/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1233/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1258/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1286/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1310/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1334/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1361/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1387/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1413/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1439/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1446/1446 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

array([[  21.786896, 1023.7622  ],
       [  21.588722, 1023.1619  ],
       [  20.920126, 1025.1404  ],
       ...,
       [  29.11525 , 1015.2639  ],
       [  29.361076, 1014.15216 ],
       [  29.577003, 1012.98425 ]], shape=(46263, 2), dtype=float32)

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [18]:
from keras.models import load_model

model.save('a_Many_To_Many_BDL_tmpf_and_vsby.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('a_Many_To_Many_BDL_tmpf_and_vsby.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X[:5], verbose=0), reloaded.predict(X[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 50)             │        11,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │           102 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,108 (137.14 KB)

 Trainable params: 11,702 (45.71 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 23,406 (91.43 KB)

In [19]:
# pred1
plt.scatter(y[:,0], pred[:,0])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_12264\3040812647.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# pred2
plt.scatter(y[:,1], pred[:,1])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_12264\898290747.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [21]:
# it worked! predict two outputs at once -
# may have taken longer to fit,
# but it worked great!

# you may also try other architectures
# and advanced methods (Conv1D and MaxPooling1D etc)