<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/b_Many_To_Many_BDL_tmpf_and_tmpfPlus1.ipynb)

# b_Many To Many (Numeric Sequences)
---------------------------------
**Dr. Dave Wanik - University of Connecticut**

[y is one variable, but predicting two timesteps into the future - NOT AUTOREGRESSIVE]

Let's read in the BDL data and see if we can predict two or three time steps into the future. We call this n_outputs or time steps into the future.

This script works by using the same LSTM cell, connecting to a dense layer, but the dense layer has hidden_units = n_outputs.

In [1]:
# import modules
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
#from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
#from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.layers import Input
#from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

In [2]:
# # https://drive.google.com/file/d/1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS/view?usp=sharing
# !gdown 1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS
# # read the data
# df = pd.read_csv('../data/cleanBDL.csv')

In [3]:
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/cleanBDL.csv"

# retrieve the CSV data and build a dataframe
df = pd.read_csv(url)

df.shape

(46272, 10)

In [4]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 46272 entries, 0 to 46271
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valid   46272 non-null  str
 1   tmpf    46272 non-null  float64
 2   dwpf    46272 non-null  float64
 3   relh    46272 non-null  float64
 4   drct    46272 non-null  float64
 5   sknt    46272 non-null  float64
 6   p01i    46272 non-null  float64
 7   alti    46272 non-null  float64
 8   mslp    46272 non-null  float64
 9   vsby    46272 non-null  float64
dtypes: float64(9), str(1)
memory usage: 4.4 MB

,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby
0,2015-01-01 00:00:00,17.96,6.08,59.10,190.0,5.0,0.0,30.09,1019.0,10.0
1,2015-01-01 01:00:00,19.94,8.06,59.40,190.0,5.0,0.0,30.08,1018.7,10.0
2,2015-01-01 02:00:00,23.00,6.98,49.69,210.0,9.0,0.0,30.06,1018.1,10.0
3,2015-01-01 03:00:00,21.92,5.00,47.52,230.0,11.0,0.0,30.04,1017.4,10.0
4,2015-01-01 04:00:00,23.00,3.92,43.21,250.0,13.0,0.0,30.05,1017.7,10.0

# Define X and Y
If we are going to use our split sequences script from Brownlee, then we need to make sure our Y variables are on the end!

In [5]:
# let's drop the valid column
# Y will be dwpf and relh
# X will be everything else!

del df['valid']
df.head() # check your work

    tmpf  dwpf   relh   drct  sknt  p01i   alti    mslp  vsby
0  17.96  6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0
1  19.94  8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0
2  23.00  6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0
3  21.92  5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0
4  23.00  3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0

In [6]:
Y = df[['tmpf']]
X = df.drop(columns=['tmpf'])
print(df.shape, X.shape, Y.shape)

# looks good! Let's prepare samples for modeling

(46272, 9) (46272, 8) (46272, 1)

In [7]:
# put Y all the way on the left
df = pd.concat([X, Y], axis=1, sort=False)
df.head(n=11)

    dwpf   relh   drct  sknt  p01i   alti    mslp  vsby   tmpf
0   6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0  17.96
1   8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0  19.94
2   6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0  23.00
3   5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0  21.92
4   3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0  23.00
5   3.92  43.21  250.0  11.0   0.0  30.06  1018.1  10.0  23.00
6   3.02  41.45  240.0  13.0   0.0  30.07  1018.4  10.0  23.00
7   3.92  41.30  240.0  11.0   0.0  30.08  1018.9  10.0  24.08
8   3.92  38.03  210.0   8.0   0.0  30.08  1018.9  10.0  26.06
9   3.92  35.05  220.0  14.0   0.0  30.08  1018.8  10.0  28.04
10  5.00  33.97  210.0  10.0   0.0  30.07  1018.4  10.0  30.02

In [8]:
# some eda - we should be able to predict temperature!
df.plot.scatter(x='tmpf', y='dwpf')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21380\2614875674.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [9]:
# to get our other code to run, we will put Y
# on the end then re-run our code (needs updating from blog)

# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
    # X and Y have been UPDATED so the last two columns drop off
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1:]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# Prepare Samples for Modeling
Everything needs to be in 3D arrays.

In [10]:
# let's turn X into lookbacks of 10 with all of our samples
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [11]:
# check your work
print(df.shape, X.shape, y.shape)

(46272, 9) (46263, 10, 8) (46263, 1)

In [12]:
# here's the first X
X[0]

array([[   6.08,   59.1 ,  190.  ,    5.  ,    0.  ,   30.09, 1019.  ,
          10.  ],
       [   8.06,   59.4 ,  190.  ,    5.  ,    0.  ,   30.08, 1018.7 ,
          10.  ],
       [   6.98,   49.69,  210.  ,    9.  ,    0.  ,   30.06, 1018.1 ,
          10.  ],
       [   5.  ,   47.52,  230.  ,   11.  ,    0.  ,   30.04, 1017.4 ,
          10.  ],
       [   3.92,   43.21,  250.  ,   13.  ,    0.  ,   30.05, 1017.7 ,
          10.  ],
       [   3.92,   43.21,  250.  ,   11.  ,    0.  ,   30.06, 1018.1 ,
          10.  ],
       [   3.02,   41.45,  240.  ,   13.  ,    0.  ,   30.07, 1018.4 ,
          10.  ],
       [   3.92,   41.3 ,  240.  ,   11.  ,    0.  ,   30.08, 1018.9 ,
          10.  ],
       [   3.92,   38.03,  210.  ,    8.  ,    0.  ,   30.08, 1018.9 ,
          10.  ],
       [   3.92,   35.05,  220.  ,   14.  ,    0.  ,   30.08, 1018.8 ,
          10.  ]])

In [13]:
# here's the first Y
y[0]

# go scroll up and make sure this matches!
# and it does!

# you will need to customize your split script when
# prepping your data... be careful! take control of your data!

array([28.04])

## Y, Y+1 and Y+2
Let's make sure that our Y vector has multiple time steps, just like we did in the previous script.

In [14]:
# convert to a dataframe
tmp = pd.DataFrame(y)
# rename the column
tmp.rename(columns={0:'y'}, inplace=True)
# create some shifts
tmp['yPlus1'] = tmp['y'].shift(-1)
tmp['yPlus2'] = tmp['y'].shift(-2)
# check your work
print(tmp.head())
print(tmp.tail()) # we will have to deal with those NaN's

# either ffill them or delete them later.

       y  yPlus1  yPlus2
0  28.04   30.02   32.00
1  30.02   32.00   33.08
2  32.00   33.08   33.98
3  33.08   33.98   33.08
4  33.98   33.08   33.08
          y  yPlus1  yPlus2
46258  44.1    42.1    39.0
46259  42.1    39.0    39.9
46260  39.0    39.9    37.0
46261  39.9    37.0     NaN
46262  37.0     NaN     NaN

In [15]:
# I will opt to forward fill them
# and just except the dirt in my data
tmp = tmp.ffill()   # pandas 3 removed fillna(method=)
tmp.tail() # all better!

# of course, you could have dropped the last N arrays
# from both X and y (making sure the shape matches up)

          y  yPlus1  yPlus2
46258  44.1    42.1    39.0
46259  42.1    39.0    39.9
46260  39.0    39.9    37.0
46261  39.9    37.0    37.0
46262  37.0    37.0    37.0

In [16]:
# convert back to numpy array
y = tmp

In [17]:
y.shape

(46263, 3)

# Fit a Model
This will be similar to the last example in 'Sequence Problems_Pt1.ipynb'

In [18]:
# note how there's a 2 at the end
# usually we did this for a multi-classification problem, but not today!
# by default, it's a 'linear' activiation function
# so this is 2 node output and we're doing regression.

n_steps = X.shape[1]
n_features = X.shape[2]
n_outputs = y.shape[1]

print(n_steps, n_features, n_outputs)

10 8 3

In [19]:
model = Sequential()
model.add(LSTM(50, activation='relu',
               recurrent_dropout=0.1,
               input_shape=(n_steps, n_features)))
model.add(Dropout(0.2))
model.add(Dense(n_outputs)) # since Y has three values, we need to predict three values
model.compile(optimizer='adam', loss='mse')

import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in
# the validation loss for 10 consecutive epochs.
es = keras.callbacks.EarlyStopping(monitor='val_loss',
                                   mode='min',
                                   patience=10, # you can play with this!
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(X,
                    y,
                    callbacks=[es],
                    epochs=800, # you can set this to a big number!
                    batch_size=100,
                    validation_split=0.2,
                    verbose=1,
                    shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/800

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14:45 2s/step - loss: 58513.6367

 11/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 55275.3945

 21/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49882.3086

 30/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 45541.2578

 39/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 42127.1523

 48/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 39300.3945

 57/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 37193.8281

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 35222.4648

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 33446.5156

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 32140.7578

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 30978.2891

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 29632.6562

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 28319.9219

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 27092.9199

128/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 26009.9609

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 24936.6367

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 24070.0371

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 23185.4707

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 22337.5273

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 21647.5312

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 21019.0176

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 20426.7559

197/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 19889.1973

206/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19455.6094

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19038.4531

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18624.3281

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18233.9414

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17787.4102

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17418.1387

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17020.6777

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16632.8516

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16259.7949

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15890.6094

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15605.4248

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15344.9756

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15031.3779

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14727.9912

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14437.4229

336/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14149.6338

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13898.4424

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13651.2910

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13413.2334

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13173.8174

371/371 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 13112.2275 - val_loss: 995.1353

Epoch 2/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 1929.4257

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 2306.8279

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 2275.3081

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 2182.5789

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 2144.5730

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2111.2180

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2058.5554

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 2021.4545

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1997.5322

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1965.8870

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1943.1967

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1916.2255

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1893.6400

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1866.2749

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1843.1099

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1820.0327

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1804.2195

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1780.0902

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1755.5425

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1729.2300

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1706.8440

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1688.1317

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1662.3407

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1644.4991

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1630.7368

213/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1611.6002

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1590.6533

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1568.8379

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1552.2360

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1538.0605

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1520.0776

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1502.2380

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1484.1184

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1468.9535

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1455.6626

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1439.1926

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1423.2810

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1407.6151

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1393.0500

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1379.5745

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1368.0491

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1359.2365

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1349.5292

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1338.1204

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 1331.0934 - val_loss: 397.3501

Epoch 3/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 674.8811

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 824.2510

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 843.5190

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 857.7845

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 878.9934

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 862.5359

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 857.8528

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 850.0826

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 848.1766

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 846.3568

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 834.0432

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 837.4979

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 830.1387

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 829.2581

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 827.9764

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 825.2869

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 824.2032

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 822.4878

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 820.3211

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 816.8548

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 817.6188

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 816.7386

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 816.0958

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 818.6959

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 818.0471

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 818.9241

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 818.7724

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 818.1028

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 816.3593

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 817.6512

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 817.4995

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 815.7111

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 813.8739

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 811.0577

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 807.5303

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 806.0269

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 802.9207

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 799.2635

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 796.7350

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 793.8387

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 789.3308

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 784.6838

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 779.8126

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 775.7293 - val_loss: 301.6852

Epoch 4/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 540.4866

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 553.3457

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 565.0540

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 575.5923

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 583.1768

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 591.2930

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 581.9363

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 579.8870

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 576.3682

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 571.4644

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 567.8032

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 563.2778

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 559.1429

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 551.2177

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 548.1201

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 546.8323

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 542.7563

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 539.3162

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 537.2432

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 535.7278

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 537.2599

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 532.4626

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 530.8918

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 527.8971

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 523.4696

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 520.3876

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 516.3712

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 513.6755

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 509.1505

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 506.6110

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 502.4872

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 498.6862

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 494.9649

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 491.2980

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 487.4423

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 484.0134

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 480.9911

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 477.3008

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 474.4552

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 471.7880

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 468.3268

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 465.5991

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 462.4138

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 460.1606 - val_loss: 113.1302

Epoch 5/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 341.5619

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 298.6773

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 325.9714

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 318.4268

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 315.5653

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 314.0919

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 305.0858

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 309.9451

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 307.3659

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 305.5532

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 306.5062

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 303.5740

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 300.4170

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 299.8076

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 297.8400

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 295.8758

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 294.8450

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 293.4357

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 291.9969

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 290.3605

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 289.3529

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 289.2305

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 289.5215

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 290.7321

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 290.5694

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 289.4664

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 287.8992

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 286.6242

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 285.3025

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 285.0302

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 284.0400

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 283.6544

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 284.1184

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 283.3930

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 282.4892

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 281.2684

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 280.6318

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 280.1714

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 280.5309

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 279.7556

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 278.7541

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 279.0407

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 277.8022

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 277.1503

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 277.1925 - val_loss: 88.2627

Epoch 6/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 244.6599

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 214.7233

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 237.1422

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 246.0957

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 245.0347

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 247.6404

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 248.8071

 59/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 246.8986

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 246.6467

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 248.6257

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 247.2974

 94/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 248.7801

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 250.3048

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 250.8908

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 250.5824

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 252.2831

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 251.6079

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 251.5709

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 251.5029

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 253.0212

172/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 253.1106

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 254.5762

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 256.9971

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 257.0850

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 257.5768

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 256.4802

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 256.0877

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 256.2418

242/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 255.7343

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 255.9563

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 256.6413

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 257.5943

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 258.3824

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 259.9123

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 259.7710

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 261.3074

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 264.3295

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 267.6393

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 270.6116

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 274.0155

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 277.5883

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 280.5977

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 283.2302

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 284.9540

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 285.2056 - val_loss: 74.7879

Epoch 7/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 339.5864

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 328.0841

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 330.0198

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 326.0559

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 321.4805

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 319.0065

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 318.8515

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 319.3924

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 312.0523

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 306.3563

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 302.5483

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 298.5777

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 295.8741

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 293.7928

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 291.1470

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 289.1002

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 286.5526

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 285.9793

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 285.6802

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 282.9708

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 281.6069

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 285.6177

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 293.0287

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 299.0694

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 302.5217

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 303.7711

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 306.0634

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 308.9977

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 311.7145

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 313.7122

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 317.9452

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.0418

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.6521

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 321.3058

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 321.3003

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.7265

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.8146

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 320.1102

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 318.5670

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 316.8643

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 315.5080

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 313.2086

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 311.3605

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 311.0989 - val_loss: 64.0433

Epoch 8/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 208.5991

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 256.2144

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 256.6728

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 252.7210

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 253.8187

 46/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 256.1070

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 251.5187

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 246.2718

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 241.5540

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 237.9546

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 232.7630

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 230.0365

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 230.1621

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 227.6333

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 225.6012

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 224.9607

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 224.2363

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 223.3914

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 223.3599

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 222.3646

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 221.8215

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 220.7795

181/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 220.2549

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 219.5582

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 219.2276

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 218.7551

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 218.0987

216/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 217.2918

223/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 216.5672

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 215.9132

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 215.5190

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 214.9095

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 214.8141

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 214.2825

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 213.7444

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 213.3778

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 212.7186

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 213.0652

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 212.6182

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.9635

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.8495

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.4331

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.5915

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.6725

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.0712

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 210.5374

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 210.4155

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 210.2755

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 209.5654

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 209.3986

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 209.3994 - val_loss: 53.8288

Epoch 9/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - loss: 172.2900

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 195.8604

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 186.1809

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 193.2650

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 198.3344

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 194.9939

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 194.4622

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.1766

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 198.1759

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 198.3250

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 198.1803

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 197.6403

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.6579

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 197.4806

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.9944

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.4294

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 195.1641

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 194.4138

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.2763

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 195.7182

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 195.4692

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 195.3087

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 194.5431

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 194.9990

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 195.2145

217/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 195.5448

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.5370

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.6649

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.1473

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.7787

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.1789

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.3100

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.4655

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.8129

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.5879

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.7682

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.0663

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.3592

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.7130

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.3440

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.1006

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 187.4372

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.6488

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 189.6600 - val_loss: 94.8074

Epoch 10/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 43ms/step - loss: 266.1514

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 234.6336

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 235.2475

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 231.2529

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 230.5808

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 227.9573

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 224.8597

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 222.9515

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 222.1115

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 221.2538

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 217.1777

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 216.8835

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 214.9925

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 211.9341

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 210.4548

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 209.7730

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 209.5470

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 208.1315

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 207.3191

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 206.8833

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.2117

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.9662

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 204.9579

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 204.2521

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 203.2841

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 202.1112

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 200.5866

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 199.0780

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 198.9233

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 198.2585

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 196.7292

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 196.2617

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.8987

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.5281

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.5738

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.6885

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.7253

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.2546

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.8270

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.0101

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.2235

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.5697

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.2269

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 187.7447

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 187.8025 - val_loss: 72.9535

Epoch 11/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 149.9601

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 171.0625

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 179.4734

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 174.3006

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 176.9993

 43/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 181.5717

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 177.9883

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 178.3666

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 178.4928

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 176.4277

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 175.2209

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 174.3207

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 173.0273

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 172.0229

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 170.5603

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 170.9658

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 169.7181

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 170.1612

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 170.4345

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 169.8862

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 169.0474

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.9181

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 169.6197

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.9688

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.9755

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 168.4563

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 168.4974

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.6540

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.5777

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.2760

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.9806

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.2975

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.1279

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.8658

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.7618

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.5969

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.1337

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.7288

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.4116

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.8750

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.9153

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.4921

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.0851

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 162.7181 - val_loss: 56.6179

Epoch 12/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 169.6810

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 156.9806

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 163.9800

 28/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 164.1017

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 163.8867

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 160.7961

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 159.1612

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 160.7366

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 160.7545

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 159.0064

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.8196

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.7324

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 158.7904

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 158.5075

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.9570

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.6124

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 156.3787

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.2418

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.1763

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 157.0391

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 156.2930

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 156.4134

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 155.4959

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 155.2603

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 154.5905

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 154.8600

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.9889

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.9662

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.4555

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.3916

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.6390

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.6582

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.2364

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.2712

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.2244

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.0818

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 152.0908

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 151.5699

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 151.0851

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.8491

349/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.9183

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.8792

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.8756

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 150.8418 - val_loss: 42.7307

Epoch 13/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 137.5429

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 153.6911

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 143.9757

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 144.6472

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 142.8201

 45/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 138.6710

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.0417

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.6653

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.1347

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.1067

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.8328

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.8897

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.9881

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.5616

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.8245

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.9231

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.0654

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.9122

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.2691

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.7567

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.2566

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.1529

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.9309

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.3466

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.7125

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.5205

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.1410

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.2596

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.6339

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.4111

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.3338

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.1567

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.2521

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.2463

295/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.9625

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.9194

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.7716

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.9068

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.7857

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.8507

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.6327

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.6799

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.4592

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 137.4559 - val_loss: 22.5426

Epoch 14/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 110.8134

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 137.8253

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 144.8590

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 143.8161

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 143.5002

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 143.4003

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 141.1826

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 141.6106

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.8243

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.8691

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.2340

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.8322

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.8451

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 139.2683

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.4126

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.4771

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.7153

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.3062

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.4477

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.3575

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.1503

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.4670

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.7611

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 138.4041

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 137.5535

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.3628

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.1873

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 136.4730

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 136.1059

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 135.3989

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 135.0921

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.8102

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.3567

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.5108

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.4304

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.2267

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 134.0881

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 133.9715

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 133.5489

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 133.1224

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 132.8861

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 132.4906

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 132.3586

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 132.6437

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 132.8196 - val_loss: 21.4057

Epoch 15/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 158.0559

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 130.5668

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 130.2411

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 132.4769

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 128.8199

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 127.9751

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 128.0039

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 127.2301

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 128.7736

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 129.0058

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 128.4083

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 128.1064

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 127.7640

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 127.2065

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 127.0486

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 126.0039

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 126.4836

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.9195

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.6489

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.1243

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.6606

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.6238

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.1303

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.5222

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.1785

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.2705

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.9208

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.5402

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.3727

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.8513

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.7509

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.6634

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.6135

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.8432

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.7136

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.6492

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.5081

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.5396

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.6858

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.4072

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.1934

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.3765

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124.2802

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 124.1350 - val_loss: 27.5707

Epoch 16/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 132.7093

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 115.8919

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 123.1360

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 124.4582

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 126.6513

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 125.7867

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 122.3598

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.8492

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.9182

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.3612

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.8591

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.4038

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 117.6845

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.5057

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.5098

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.5300

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.2831

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.0837

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.7554

164/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.4046

173/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.6882

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 120.1898

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.7833

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.5897

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.1456

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 119.1571

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.8431

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.5857

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.5481

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.2305

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.3283

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.2879

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.1200

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.8739

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118.0777

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.7354

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.5491

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.9017

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.5209

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.4436

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.5534

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.5510

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.3986

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117.3983

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 117.5362 - val_loss: 17.1361

Epoch 17/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 120.5206

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 127.7175

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 125.4031

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 123.2076

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 122.5365

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 123.9942

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 122.0687

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 121.9308

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 119.9516

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 118.3176

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 116.7211

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 116.1538

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 115.5408

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 115.6882

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 115.5058

128/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 116.2586

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 116.6324

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.2992

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.3326

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 117.2561

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 117.2488

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.1673

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.8232

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.4011

197/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.7965

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.4470

214/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.2339

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 115.9600

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.6584

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.4805

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.2316

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.0191

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.1044

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.7218

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.4545

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.2759

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.0354

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.8884

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.6925

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.5065

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.7697

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.6401

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.8559

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.7486

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.5253

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.2787

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 113.0823

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 112.9850

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 112.8663

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 112.8375

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 112.7549

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 112.6983 - val_loss: 45.4491

Epoch 18/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - loss: 186.2957

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 111.6402

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 112.9618

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 112.4819

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 111.4194

 40/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 112.1827

 48/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 113.2632

 56/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 114.4776

 64/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 113.7684

 71/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 113.8072

 77/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 114.8403

 85/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 114.1235

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 113.7396

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 112.5526

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 112.0167

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 111.8289

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 111.3158

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.9800

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.1054

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 109.7988

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.4303

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.3759

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.4572

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.9504

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.5714

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.2780

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.2936

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.2317

212/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.2081

219/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 110.2034

223/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 109.9539

229/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 110.2495

233/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 110.2565

236/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 110.3207

242/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 110.0256

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.7906

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4402

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4144

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4523

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.5433

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.2801

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.1518

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4908

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.5843

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.6616

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4137

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.4403

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.5830

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109.3561

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 109.2084

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.9679

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.9148

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.9791

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 109.0581

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 109.1008

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 109.0206

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.7528

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.7316

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 108.6605

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 108.6605 - val_loss: 33.2179

Epoch 19/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 8:14 1s/step - loss: 107.4723

 11/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 101.6887

 21/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 102.6707

 31/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 103.4579

 40/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 103.1924

 49/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.4603

 58/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.1836

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.3146

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.9048

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.9945

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.3896

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.3015

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.0042

119/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.0395

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.6581

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.3098

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.0796

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.5518

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.8132

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.4049

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.1749

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.6745

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.4064

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.9395

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.7066

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.7831

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.1224

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.4399

249/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.9883

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.0929

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.9954

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.5781

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.6295

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.1368

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.9641

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.2945

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.0622

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.1508

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.3074

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.2888

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.3244

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.4167

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.5629

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 108.5510 - val_loss: 14.8043

Epoch 20/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 36ms/step - loss: 96.3239

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 110.3799

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 107.3621

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 104.5767

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 103.6150

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 102.5572

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 101.9548

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.4522

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.3948

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.9567

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.2219

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.1856

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.8876

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.5999

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.1828

128/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.3348

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.2857

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.5507

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.7819

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.8261

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.0169

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.1848

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.5350

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.9912

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.0873

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.9526

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.8828

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.8046

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.4774

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.2904

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.9298

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.2842

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.3583

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.2946

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.1967

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.0086

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.8947

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.9348

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.9074

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.6765

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.5049

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.3857

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.2144

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.3671

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.5464

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 103.2682

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 103.2347 - val_loss: 15.7824

Epoch 21/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - loss: 100.2268

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 102.2264

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 105.9430

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.8674

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 103.4878

 40/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 103.9401

 48/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 103.5429

 55/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 103.1320

 63/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 102.6582

 71/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 101.2120

 78/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 100.7841

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.1713

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.5060

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.2137

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.0615

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.3363

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.9554

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.7463

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.9227

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.2137

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 96.9877

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.0077

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.0851

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.3303

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.1901

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.4635

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.7288

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 97.2856

215/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 96.6657

223/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 96.3032

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97.5199

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99.4551

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 101.5535

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 102.7876

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 104.3348

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 104.7571

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 105.2369

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 105.6614

295/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 105.7463

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 105.9017

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.3106

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.4196

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.5475

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.4354

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.1605

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.3114

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.2934

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106.2469

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 106.1415 - val_loss: 22.1593

Epoch 22/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - loss: 108.6490

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 111.4412

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.8692

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.5245

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.7775

 40/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.5209

 48/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.1301

 57/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.5832

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 106.3584

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.1535

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.2098

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.6500

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.6500

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.5285

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.5730

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.7255

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.8161

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.1553

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.8710

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.5867

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.7981

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.1173

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.3251

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.8615

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.5920

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.5786

217/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.0234

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.9304

234/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.7502

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.0129

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.4990

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.5816

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105.8311

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.0599

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.2303

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.2378

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.5008

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.4477

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.6062

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.3727

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.5086

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.7910

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.9830

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.9772

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 107.0507 - val_loss: 20.6891

Epoch 23/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 92.8251

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.1075

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 111.4714

 23/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 109.0282

 30/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 109.6590

 38/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.8087

 46/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.8387

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.0003

 59/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.1777

 66/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.4291

 73/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 107.2299

 80/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.3997

 87/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 106.4660

 94/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 105.2283

100/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 104.1875

107/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 103.6429

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 102.9937

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 102.1885

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 101.9301

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 101.7709

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 100.8995

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 100.5753

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 100.6000

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 100.8349

164/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 100.0861

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.4174

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.2100

181/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.1224

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.1132

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.0440

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.0915

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.1326

214/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 99.0356

220/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 98.8082

226/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 98.2518

233/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 98.5171

240/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 98.4871

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.2708

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97.7980

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97.4822

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97.1808

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.9231

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.4499

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.4107

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.3488

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.3050

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.1735

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.2779

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.1869

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.1137

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96.0476

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.8387

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.7322

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.6560

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.5087

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.6759

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 95.6676

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 95.6651

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 95.7208 - val_loss: 15.0229

Epoch 24/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 101.0647

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84.2708

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 88.0689

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.9017

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.2898

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.8570

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.7817

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.5024

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.7495

 76/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.9614

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.0257

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.2765

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.1529

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.1207

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.1617

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.7754

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.6987

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 89.5439

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 89.5602

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.0028

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.1905

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.2598

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.0060

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.0860

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.4860

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 90.7297

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 91.0085

217/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 91.4621

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91.0641

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91.2789

242/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91.3455

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91.0477

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 90.9876

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 90.6983

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 90.5584

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4791

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5871

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6805

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6843

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.8333

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6334

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5855

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.8090

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6536

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5061

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 90.4125 - val_loss: 14.3687

Epoch 25/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 104.4762

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 88.0144

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.4567

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.7849

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.4803

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.0807

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 90.5259

 59/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.5274

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.7669

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.8503

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.6179

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4298

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.8835

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.4832

119/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.9653

128/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.3024

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.4510

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.4229

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.7033

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.2062

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.7354

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.6745

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.5759

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.3299

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.0866

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.7249

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.7585

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.0084

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.1313

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.2137

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.8663

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.6692

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 88.7359

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.0732

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.2606

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.2275

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.3140

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.4734

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.3107

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.4557

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.4454

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.6461

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.4756

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.2455

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.5494

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.5799

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 89.5799 - val_loss: 13.5869

Epoch 26/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 18s 51ms/step - loss: 100.5444

  8/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 77.7672

 15/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.1012

 22/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 85.0226

 29/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 86.2809

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 86.5802

 45/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 86.2038

 54/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.3364

 63/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.8281

 72/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.9236

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 84.5547

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 84.7947

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 84.5125

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 85.7792

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 85.4463

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.1531

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.6761

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.3053

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.7079

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.8123

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5212

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.8158

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.8247

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.7143

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.6953

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5831

217/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6430

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.5412

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.5830

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.3200

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.4556

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2796

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.3959

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2083

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.1166

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0079

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0182

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9082

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9895

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.1503

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2904

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.1552

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0741

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0149

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 85.9487 - val_loss: 19.9081

Epoch 27/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 85.2784

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 90.7934

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85.6041

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85.9657

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85.3031

 40/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.4948

 48/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.5057

 55/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.8139

 62/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.0180

 70/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.2233

 77/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.7097

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.2711

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.7382

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.9433

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.4449

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.2700

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.9216

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.7495

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.7221

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.4848

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.8151

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.7552

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.5468

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.3525

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.2002

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.4728

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.2383

213/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.4404

221/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 80.4599

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5159

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5317

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.4268

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.3072

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.1196

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.1911

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.3721

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5886

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5303

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.7068

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.8372

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.7709

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.8476

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.7769

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.7097

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.5324

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.3978

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.2423

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 80.2551

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 80.3737 - val_loss: 12.8046

Epoch 28/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 80.4748

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 72.3344

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.3228

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.6554

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.4807

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.6731

 50/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 76.6610

 58/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.4172

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3009

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.7598

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.5444

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.4099

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.1729

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.0245

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 75.8106

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 75.7663

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.0470

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 75.6226

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 75.7028

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.1744

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.1055

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.3722

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.5997

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.7417

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.8861

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 76.6027

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 76.8876

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 76.9610

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.3331

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 76.9954

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.0089

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.2062

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.1137

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.3710

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.4733

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.2924

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.6644

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.7044

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.8947

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.8997

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.8900

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1356

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1895

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1390

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 78.0943 - val_loss: 12.6469

Epoch 29/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 45ms/step - loss: 82.2982

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 80.1069

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 80.5121

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.1133

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.5736

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.3342

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.2737

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.4946

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.6759

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.7904

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8245

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.6789

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.4614

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.1642

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.6351

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.5790

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 79.6654

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 79.4134

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 79.3804

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 79.1866

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.9103

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.4529

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.3794

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.6762

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.4442

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.3604

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.4586

213/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.8703

220/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 78.8086

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.7689

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.4885

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.1187

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.0091

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.0162

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.2514

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.0165

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.1096

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.1028

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.0936

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.9258

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.7497

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.7146

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.9856

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 77.9559

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.2240

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.3763

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.4305

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.3336

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 78.4116

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 78.2344 - val_loss: 28.2904

Epoch 30/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 73.7381

  8/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 69.6759

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 71.4317

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 73.6583

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 72.5402

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 73.0490

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 74.2991

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74.2678

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.4887

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.9201

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.6288

 94/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.3808

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.7376

110/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74.0401

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.8115

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.9613

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74.5241

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74.3301

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 74.0809

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.7300

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.4193

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.4950

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.2237

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.0125

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 73.0360

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.9608

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.7171

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.6369

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3330

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3099

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3387

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.2626

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.1877

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3167

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.3545

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0361

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0336

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.9928

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.8086

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.8437

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.8806

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.9935

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0822

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0344

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0977

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 72.0582 - val_loss: 12.0279

Epoch 31/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 79.5257

  7/371 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 72.8573

 12/371 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 72.1821

 19/371 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 74.0793

 27/371 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 70.5405

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 71.5584

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 73.0115

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 73.5708

 60/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 73.8197

 68/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 75.2164

 76/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 74.6598

 84/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 75.0440

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 74.1796

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 73.0990

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.9795

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.7613

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.2228

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 71.9511

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.1412

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.3604

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.2270

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.3224

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.0754

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 71.9533

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 71.7666

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 71.8429

210/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.0150

218/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 72.1324

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8746

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.9821

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8999

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8879

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 72.0054

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8293

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.9045

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.8933

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.5397

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.3278

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 71.0663

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9779

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9721

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9737

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9217

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.9061

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.8389

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 70.7909

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 70.9517 - val_loss: 12.5118

Epoch 32/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 49.5117

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64.2137

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.1849

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.2008

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 68.6317

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.4031

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.5228

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.4051

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.0293

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.9712

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.4108

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.0876

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.7150

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.1764

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.2161

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.1961

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.9190

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.7246

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.8303

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.2766

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.0259

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 71.1862

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 71.2910

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 71.7113

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.7743

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.9721

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0326

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0413

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0103

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.0051

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 72.1559

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.8672

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.7377

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.6742

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.4325

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.4258

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.4607

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.4466

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.3618

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.2566

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 71.0467

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 70.9249

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 70.7795

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 70.7048 - val_loss: 24.0127

Epoch 33/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 85.7087

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 76.4108

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 72.9325

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 71.4320

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.0909

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.9627

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.4454

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.7649

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.4281

 82/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.8879

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.9290

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.5215

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.1603

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.4468

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.1990

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.2407

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.9950

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.8357

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.3837

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.1905

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.5507

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.5769

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.7405

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.4303

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.6412

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.6700

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.4740

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.3840

249/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.3050

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.3692

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.2188

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.0908

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 69.0269

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.9167

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.7721

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.7668

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.6049

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.5148

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.4988

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.3994

349/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.2721

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.1793

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 68.1947

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 68.2292 - val_loss: 13.8287

Epoch 34/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 71.4361

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 67.1951

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 69.5933

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 68.1067

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 69.5920

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.3428

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.0570

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.1845

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 70.3540

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.3412

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.0521

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.5530

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 69.0124

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.4204

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.9402

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.6850

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.2700

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.7211

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.4840

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.4739

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.3755

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.3072

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.6663

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.7060

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.7949

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7000

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7748

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.9078

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.6994

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7466

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.6087

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.8996

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.7148

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.6920

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.6325

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.4967

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.4536

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.3367

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.3137

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.3079

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.2952

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.2381

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.2388

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 66.1871

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 66.1610 - val_loss: 27.2459

Epoch 35/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - loss: 93.5526

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.4014

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 65.3406

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.2505

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 67.0674

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.5940

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 66.6772

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.7065

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.5074

 76/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.5472

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.4669

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.2042

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.3823

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.5328

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.3735

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.1526

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.6024

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.4212

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.3530

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.7542

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.4373

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.3441

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.4287

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.4817

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.6007

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.7999

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 64.7317

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.7685

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.5825

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.6206

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.4548

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.6452

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.7140

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.7499

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.5790

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.5967

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.5085

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.2144

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.0345

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.2156

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.1809

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.2195

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.0731

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 63.9705

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 64.0132

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 63.9734

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 63.9071 - val_loss: 14.5820

Epoch 36/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 71.1269

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.7933

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.2243

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.9060

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.1437

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.0993

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.3741

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4714

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9773

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8401

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.7417

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.2646

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.6664

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8121

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9790

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9113

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.0498

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.6588

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8164

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.7526

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8476

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.9161

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.9720

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3856

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3105

217/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5848

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5395

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5848

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.6025

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.4981

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.6409

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7799

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9564

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9946

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9394

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9665

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1582

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1876

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.0457

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9647

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9917

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1400

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.2113

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.3200

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 63.3200 - val_loss: 14.2962

Epoch 37/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 63.9078

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.9978

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.1331

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.4574

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.6972

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.0265

 50/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62.7166

 58/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.5122

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.8046

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9743

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9048

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1617

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9787

110/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.3898

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2132

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2441

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.5175

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2452

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1051

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9275

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.6704

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.8792

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9234

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1754

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2224

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.0567

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.7928

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.9151

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.8222

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.7755

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.6210

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.5212

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.3589

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.2917

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1469

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1429

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.3089

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.3026

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1529

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1319

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.0465

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1265

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1348

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1750

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 63.2007 - val_loss: 11.2706

Epoch 38/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 49.9800

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.8342

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.3378

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.7338

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.0831

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62.2811

 50/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64.2028

 59/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2174

 67/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.3867

 74/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.5467

 82/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.8580

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.1839

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.9373

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.7190

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.9363

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.4244

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3940

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.4532

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.9657

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.4672

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9540

173/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1256

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.0791

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9368

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.9496

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1753

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.6245

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.8548

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 65.3186

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 65.1263

249/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 65.1256

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.9993

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.9684

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.8008

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.8202

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.7217

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.7271

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.6086

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.5854

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.3620

336/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.3071

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.2972

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.1550

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.9917

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 63.9093 - val_loss: 11.5774

Epoch 39/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - loss: 62.6761

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.0589

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.6243

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.0825

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0655

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.5084

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3606

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.6661

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.4081

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.7768

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.7001

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.5275

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.2262

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.9724

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0037

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0701

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.4923

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.3894

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.4476

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.0438

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.0377

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.7221

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.9882

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3153

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5422

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7672

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.9314

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1460

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.8773

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.8769

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7386

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.6363

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7367

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5510

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.4301

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.4573

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.3262

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.2632

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.2213

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.1808

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.0661

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.1186

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.0422

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 61.9814 - val_loss: 10.5144

Epoch 40/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - loss: 69.4080

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.6908

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.6177

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.2196

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.5933

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.2425

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.3866

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.1131

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8642

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.1476

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8643

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8848

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9932

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.0959

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.2991

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.2442

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9755

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.7888

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.1470

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9650

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.7883

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9147

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8276

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.0349

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.2155

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.3419

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.3746

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.2001

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.3417

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.2487

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.1872

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.0936

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9753

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9676

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9860

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8614

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9071

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9389

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8995

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8548

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8482

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.7101

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.6464

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.5932

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4700

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 60.5117 - val_loss: 11.6716

Epoch 41/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - loss: 52.7570

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 53.8627

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 54.7039

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 56.4559

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 55.7735

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 57.1739

 49/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 57.3098

 58/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 56.7031

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1908

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.5086

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.0431

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4603

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.0059

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.9986

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7219

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7938

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.1532

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.0506

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.5097

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4941

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4349

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.6422

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.8852

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.8217

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.8856

210/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.0765

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.1160

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.9240

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.7935

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.8708

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.7664

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.4583

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.3302

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.1624

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.1626

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.0075

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.8683

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.8413

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9163

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.8025

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.6412

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.6705

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5404

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5305

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4688

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 58.4688 - val_loss: 14.3791

Epoch 42/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 59.2806

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.0060

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.4276

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.4307

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.7761

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.2541

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.6005

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.9017

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7604

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4480

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4567

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.9601

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.3843

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.9819

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.7807

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.9214

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.4938

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.2992

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.5319

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.4931

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.6713

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.2162

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4068

197/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4654

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.4309

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.3396

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2953

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2016

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.0565

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.1166

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.0296

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.0217

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.0764

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.1502

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.0942

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.9599

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.8488

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6768

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6631

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6874

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.8185

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.7332

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6364

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6545

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 57.6738 - val_loss: 10.9177

Epoch 43/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 62.7372

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.4524

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.2330

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.5290

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.9632

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.3863

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7474

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.2371

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4168

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.6352

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4896

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.1850

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.8209

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4706

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.6263

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4413

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.2529

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7715

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.9969

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.5211

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.3524

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7252

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7315

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.6904

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7456

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9672

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.1915

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.3142

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.1009

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.0008

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9624

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9660

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9311

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9045

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9322

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.8244

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7297

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7183

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5605

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5466

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7108

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.6004

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5417

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5420

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 58.5420 - val_loss: 12.0002

Epoch 44/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 63.6989

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.5180

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.0322

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 60.3276

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 59.0950

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 60.2141

 46/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.6311

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 58.6932

 59/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 58.2828

 67/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 58.4228

 75/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.2691

 83/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.3547

 92/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.1542

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.9511

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.0815

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.1061

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.8597

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.1287

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.9938

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.7411

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.7924

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.5038

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.7068

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.0953

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.0077

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.1043

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.2086

219/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 58.0143

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.8592

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.8356

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.7859

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.7119

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6546

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.7122

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.7317

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.9848

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.9320

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.9156

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.7767

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6387

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6771

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6497

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.4885

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.3523

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.2788

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 57.2254 - val_loss: 10.2792

Epoch 45/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 47.0817

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.3917

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.3575

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.9386

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.8867

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.7207

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.8982

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.8559

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.4316

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.0602

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.9331

 93/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.7662

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3303

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.4814

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.7849

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.6844

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.6916

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.8864

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.8796

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.0943

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1922

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.0491

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1507

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1519

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.9908

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1103

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.1785

212/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.2731

220/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.2980

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.4503

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.6901

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.5863

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.5055

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.5304

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.3235

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.2939

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.1974

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 57.0415

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.9876

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.9731

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.9097

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.6934

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.6300

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.7631

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.6877

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 56.7285

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 56.7102 - val_loss: 10.7043

Epoch 46/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 50.8477

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.0204

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.5453

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.5308

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55.8379

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.2153

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6877

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.9755

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.7066

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2108

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.7450

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.9565

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.8917

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.8106

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.5853

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.1869

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.5590

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.4583

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.5925

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.7260

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.9628

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.9330

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.1115

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.0829

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1013

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.9528

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1127

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.9453

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8831

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8572

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8859

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8558

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.3936

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7964

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1314

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.4195

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.7376

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2414

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4552

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5137

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.8250

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9666

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.0110

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 58.9980 - val_loss: 13.7228

Epoch 47/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 46.6501

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 60.1556

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.8603

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.8147

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62.4319

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 63.7230

 50/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 63.4747

 59/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 62.9137

 67/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 62.5157

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 62.5368

 83/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 61.9739

 91/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 61.3121

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9770

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.8846

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9951

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.6860

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.5217

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.2673

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.0209

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.5025

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.3541

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.2036

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4995

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4699

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4514

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.1835

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.1933

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.0797

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4723

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4913

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.6676

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.7321

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.7782

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.6483

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8611

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.7370

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.5468

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.5015

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4205

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.3038

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.2264

349/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.2575

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.1261

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.1840

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 60.0652 - val_loss: 20.0794

Epoch 48/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 57.0849

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62.0620

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 65.6891

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64.1352

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64.3130

 44/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.0352

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.6018

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.9846

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.0025

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0410

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.1853

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.6812

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.9872

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.4880

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.1799

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.0679

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.1768

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.0211

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.7749

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.6969

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.7189

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.9117

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.6900

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.5479

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.2508

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.9176

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.7192

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.6362

242/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4901

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5389

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.6666

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.5429

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.4834

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2986

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.2636

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.1986

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 58.1743

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.9831

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.7604

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.7138

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.5867

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6833

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.6200

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.5837

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 57.5837 - val_loss: 14.8397

Epoch 49/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 53.9398

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.3247

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 53.1699

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.0080

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 53.6769

 45/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.4020

 53/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55.3371

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.0692

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.3012

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.0639

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2249

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.1493

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.1471

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.7103

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.1800

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.0880

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6937

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6335

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.5911

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2877

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.5885

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4811

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3161

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3212

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3079

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1578

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1991

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2728

242/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.3314

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.4823

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6733

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6780

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.4198

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.3312

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2677

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0656

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1822

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1856

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2266

336/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0274

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.9507

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8939

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8589

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.6955

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 55.6842 - val_loss: 11.9414

Epoch 50/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - loss: 50.9556

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.3842

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 53.5425

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 53.3173

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.9854

 44/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.0803

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5632

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1546

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.6890

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.8580

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.6298

 94/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.8359

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4725

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.0523

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.2924

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.0753

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.7573

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.6840

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.6729

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5192

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.4548

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.2543

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.4150

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.3233

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5243

212/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5315

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3149

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3264

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.2292

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.1890

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.2703

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.2770

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3822

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.5183

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3932

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.2443

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0948

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 59.7627

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.4801

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.5438

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.1089

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.7740

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.0733

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 64.3520

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 64.4419 - val_loss: 13.6429

Epoch 51/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - loss: 79.5979

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 72.2045

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 71.3482

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 69.0913

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 68.4060

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 68.4721

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.9469

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.8298

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.5546

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.3032

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.9581

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 67.3187

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 66.3072

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.9749

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.4796

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.4063

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.9914

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.2866

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1675

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1579

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.7428

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.7617

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.5884

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.5464

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.6958

212/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.6997

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.6050

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.4251

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.4303

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.3007

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63.0748

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.8424

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.7533

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.4950

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.4636

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.2203

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.1427

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.8952

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.8270

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.6882

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.6258

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.4746

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.3469

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.2009

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.1322

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 61.1209 - val_loss: 26.7775

Epoch 52/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 67.3769

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.7294

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55.1868

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.5842

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.0370

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.1616

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.5334

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.0505

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.1489

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.0118

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.8145

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6272

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2520

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3327

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2119

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4994

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6154

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.5696

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6011

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.1058

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.1457

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.0322

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.1017

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.2398

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1030

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.9081

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7551

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7023

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7574

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6572

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.9518

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0619

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2661

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2375

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1242

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1885

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.9712

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.8818

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.6650

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.5303

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.5866

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.4764

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.4236

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 56.4724 - val_loss: 10.7126

Epoch 53/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 71.7492

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.6738

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 57.1991

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.7212

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1405

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.8663

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.5356

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.0394

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.3817

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.2015

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4669

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1374

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1723

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.3419

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.9618

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.0660

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1777

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.2552

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.6358

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.7229

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.3849

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4345

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4182

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4733

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.7104

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.6231

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.7708

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.6925

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.5308

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.4396

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.3343

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.2993

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.2132

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 54.1112

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.9893

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.8850

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.7318

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.5876

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.4730

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.4975

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.4391

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.4654

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.3157

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 53.3183 - val_loss: 9.2709

Epoch 54/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 42ms/step - loss: 49.0281

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.2141

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.2147

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.2900

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.7596

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.2170

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.2576

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.9816

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.1522

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.1953

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.0344

 94/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.7632

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3223

111/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3173

119/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 51.8714

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1362

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.2695

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1079

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1029

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.2151

172/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1435

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.2171

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1809

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.1576

206/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3665

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.1671

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.1998

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0174

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.8999

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.8100

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.7563

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.6769

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.6347

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.6356

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.4803

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5219

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5000

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.4478

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.3656

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.3842

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.2701

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.1721

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.2629

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.3664

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 51.3681 - val_loss: 13.1424

Epoch 55/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 57.7777

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.4812

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 52.5328

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 54.4106

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 55.0177

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.9448

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 56.6898

 59/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.8770

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.5544

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 55.1549

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.9026

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.4348

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.2361

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 54.1348

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5260

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.5264

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.1915

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 53.0064

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.6910

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.5639

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.4877

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3281

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3382

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3164

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52.3682

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.3554

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.3511

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.3646

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.2771

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.1829

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0054

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.1790

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0521

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.1174

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0661

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.9461

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0332

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0105

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0196

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.9244

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.6678

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5415

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5311

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.5894

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 51.5793 - val_loss: 10.8272

Epoch 56/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 55.0195

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.5637

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.9776

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.5651

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.0851

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.9107

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.9574

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.4976

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.1726

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.9339

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.2167

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.9299

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.7975

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.6928

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.3870

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.4636

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.9879

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.4093

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.4679

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.5356

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.7091

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.5223

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.8902

207/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.7905

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9644

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.8453

234/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.0148

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9890

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9728

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9593

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.0662

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.1489

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.1915

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.0072

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.0210

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9601

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9864

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9583

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.8901

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.7666

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.8901

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9067

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.8383

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 50.8124 - val_loss: 13.0547

Epoch 57/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 40.6791

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 47.9022

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.2981

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.2131

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.5989

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.0697

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.0620

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9615

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.5246

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.1066

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9040

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8783

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.4894

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.6779

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.6520

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8060

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8553

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8429

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0857

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3453

173/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2332

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0467

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0802

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9518

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9637

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8922

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9323

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1152

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0981

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2845

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3697

268/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2549

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1731

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2184

295/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2957

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1961

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1803

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0272

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8648

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8725

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0244

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0755

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1125

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49.1192 - val_loss: 14.1175

Epoch 58/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 44.0016

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 47.0519

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.9595

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.2500

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49.7299

 46/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.2870

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.4313

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.0274

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.1315

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.2867

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.3709

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.0529

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.8617

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.3210

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.1958

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.5187

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.0752

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.9878

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.8324

170/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.7682

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.6699

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.4605

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3144

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2621

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2409

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1145

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9573

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8045

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7820

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7933

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7818

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8650

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8849

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9801

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9591

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9423

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8784

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0018

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1143

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0342

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1096

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0974

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0447

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 49.0505 - val_loss: 10.2918

Epoch 59/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 53.4766

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.0516

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.4666

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.0570

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50.7618

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 51.3444

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.3902

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.3054

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.9177

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50.1991

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.7608

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.6198

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2213

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2152

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3914

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2435

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9911

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9407

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3481

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.5136

173/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3530

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0636

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9868

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0212

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0960

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2251

225/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3298

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3295

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2847

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3014

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3342

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.4670

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.4779

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.3639

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2454

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.1821

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.2406

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0780

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0669

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9458

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9197

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8897

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7469

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7970

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 48.8624 - val_loss: 14.6312

Epoch 60/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 47.9210

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 42.8905

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 46.4165

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 47.7498

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 48.7368

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.2059

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9546

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.3117

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.1879

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49.0305

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8584

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.4903

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.3490

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.2330

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.3052

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.4724

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.5717

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.7430

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9291

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.7372

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9329

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.7789

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.6994

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.9698

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 48.8614

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.9192

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8317

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8328

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7819

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7742

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.7722

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.8385

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.6684

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48.6147

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.0532

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 49.6911

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.6080

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50.9631

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.2781

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 51.7464

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.0438

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.6064

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.8901

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 53.2751

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 53.4356 - val_loss: 24.7169

Epoch 61/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - loss: 73.3778

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 58.1817

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 64.7782

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.3325

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.1938

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.9373

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.6041

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 65.0752

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 64.6024

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.7066

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.3444

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 63.1117

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.6696

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.3033

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8719

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.2714

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8225

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.7361

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0846

164/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 62.0098

172/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.7881

181/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8939

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.8132

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.3164

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.5155

216/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.2971

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.4641

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.4968

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.3207

249/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.2522

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.1464

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.1529

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9789

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 61.0071

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9541

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9926

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.9725

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8256

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.8477

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.6307

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4108

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.4193

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.3654

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60.3095

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 60.2884 - val_loss: 10.7924

Epoch 62/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 65.5796

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 63.8711

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.8920

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.5826

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 61.7847

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 62.1569

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 61.4478

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.7884

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 60.5276

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.9026

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4304

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.4204

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.1050

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.9219

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 59.0824

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.9582

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.7154

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 58.2032

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.8494

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.8577

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.6967

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.8056

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.6796

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.7033

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 57.3348

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.5413

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2295

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2625

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2576

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.3676

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.3412

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.2453

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0247

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1740

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.1294

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0286

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0115

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0782

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 57.0461

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.9723

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.9202

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7494

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7708

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.7738

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 56.7738 - val_loss: 20.7003

Epoch 63/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - loss: 41.3453

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 53.6646

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 56.5644

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 59.6000

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.8349

 39/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.0051

 47/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.3857

 55/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 57.9996

 63/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.2513

 72/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 58.0889

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.5867

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 57.3512

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.7409

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 56.5959

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4451

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.6422

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4669

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4411

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3481

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4772

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4238

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.3219

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.1944

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.1055

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.4137

212/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 56.2688

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2926

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0603

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.2263

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.1275

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0837

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 56.0791

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8845

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.7912

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.9092

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.8053

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.7065

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.7803

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.6531

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.6610

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.5385

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.4417

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55.4794

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55.2938

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55.2540

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 55.2203

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 55.2132 - val_loss: 9.8723

In [20]:
# and you can show how your model did

# since it's a single sample, we need to reshape
data = X[0]
data = data.reshape(1,n_steps,n_features)
print(data)
print(model.predict(data))

# did we get close?
print(y[0:1])

# of course you can show scatterplots and everything else
# for more examples

[[[   6.08   59.1   190.      5.      0.     30.09 1019.     10.  ]
  [   8.06   59.4   190.      5.      0.     30.08 1018.7    10.  ]
  [   6.98   49.69  210.      9.      0.     30.06 1018.1    10.  ]
  [   5.     47.52  230.     11.      0.     30.04 1017.4    10.  ]
  [   3.92   43.21  250.     13.      0.     30.05 1017.7    10.  ]
  [   3.92   43.21  250.     11.      0.     30.06 1018.1    10.  ]
  [   3.02   41.45  240.     13.      0.     30.07 1018.4    10.  ]
  [   3.92   41.3   240.     11.      0.     30.08 1018.9    10.  ]
  [   3.92   38.03  210.      8.      0.     30.08 1018.9    10.  ]
  [   3.92   35.05  220.     14.      0.     30.08 1018.8    10.  ]]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step

[[28.06298  28.023182 27.64164 ]]
       y  yPlus1  yPlus2
0  28.04   30.02    32.0

In [21]:
# select first column of y
y['y']

0        28.04
1        30.02
2        32.00
3        33.08
4        33.98
         ...
46258    44.10
46259    42.10
46260    39.00
46261    39.90
46262    37.00
Name: y, Length: 46263, dtype: float64

In [22]:
# well done! You can also make scatterplots of actual vs. predicted
pred = model.predict(X)
pred

   1/1446 ━━━━━━━━━━━━━━━━━━━━ 6:53 286ms/step

  30/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  59/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  89/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 120/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 150/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 177/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 195/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 211/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 231/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 259/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 286/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 313/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 340/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 367/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 395/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 422/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 449/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 476/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 503/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 531/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 557/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 583/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 610/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 637/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 664/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 691/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 718/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 745/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 770/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 798/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 826/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 853/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 880/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 905/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 932/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 959/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 986/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1013/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1040/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1068/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1096/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1123/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1150/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1177/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1204/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1230/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1256/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1283/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1311/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1337/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1364/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1391/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1418/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1446/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1446/1446 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

array([[28.062983, 28.023186, 27.64164 ],
       [29.567003, 29.505898, 29.099607],
       [30.90237 , 30.80346 , 30.36021 ],
       ...,
       [39.70868 , 39.352642, 38.79019 ],
       [40.164566, 39.904915, 39.41385 ],
       [38.266533, 37.979767, 37.51416 ]], shape=(46263, 3), dtype=float32)

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [23]:
from keras.models import load_model

model.save('b_Many_To_Many_BDL_tmpf_and_tmpfPlus1.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('b_Many_To_Many_BDL_tmpf_and_tmpfPlus1.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X[:5], verbose=0), reloaded.predict(X[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 50)             │        11,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │           153 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,861 (140.09 KB)

 Trainable params: 11,953 (46.69 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 23,908 (93.39 KB)

In [24]:
# select first column
pred[:,0:1]

array([[28.062983],
       [29.567003],
       [30.90237 ],
       ...,
       [39.70868 ],
       [40.164566],
       [38.266533]], shape=(46263, 1), dtype=float32)

In [25]:
# pred1
plt.scatter(y['y'], pred[:,0:1])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21380\1016567324.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# pred2
plt.scatter(y['yPlus1'], pred[:,1:2])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21380\3354951425.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
# and the third one
plt.scatter(y['yPlus2'], pred[:,1:2])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21380\2471302604.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [28]:
# it worked! of course the prediction into the
# future will be a little worst than the next time step

# and as you can see, prepping the data is important!