<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/b_Many_To_Many_BDL_tmpf_and_tmpfPlus1.ipynb)

# b_Many To Many (Numeric Sequences)
---------------------------------
**Dr. Dave Wanik - University of Connecticut**

[y is one variable, but predicting two timesteps into the future - NOT AUTOREGRESSIVE]

Let's read in the BDL data and see if we can predict two or three time steps into the future. We call this n_outputs or time steps into the future.

This script works by using the same LSTM cell, connecting to a dense layer, but the dense layer has hidden_units = n_outputs.

In [1]:
# import modules
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
#from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
#from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.layers import Input
#from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [2]:
# # https://drive.google.com/file/d/1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS/view?usp=sharing
# !gdown 1vhWT7__EDc-WQ7WGnK0RP2qq7-25LCWS
# # read the data
# df = pd.read_csv('../data/cleanBDL.csv')

In [3]:
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/cleanBDL.csv"

# retrieve the CSV data and build a dataframe
df = pd.read_csv(url)

df.shape

(46272, 10)

In [4]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 46272 entries, 0 to 46271
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   valid   46272 non-null  str
 1   tmpf    46272 non-null  float64
 2   dwpf    46272 non-null  float64
 3   relh    46272 non-null  float64
 4   drct    46272 non-null  float64
 5   sknt    46272 non-null  float64
 6   p01i    46272 non-null  float64
 7   alti    46272 non-null  float64
 8   mslp    46272 non-null  float64
 9   vsby    46272 non-null  float64
dtypes: float64(9), str(1)
memory usage: 4.4 MB

,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby
0,2015-01-01 00:00:00,17.96,6.08,59.10,190.0,5.0,0.0,30.09,1019.0,10.0
1,2015-01-01 01:00:00,19.94,8.06,59.40,190.0,5.0,0.0,30.08,1018.7,10.0
2,2015-01-01 02:00:00,23.00,6.98,49.69,210.0,9.0,0.0,30.06,1018.1,10.0
3,2015-01-01 03:00:00,21.92,5.00,47.52,230.0,11.0,0.0,30.04,1017.4,10.0
4,2015-01-01 04:00:00,23.00,3.92,43.21,250.0,13.0,0.0,30.05,1017.7,10.0

# Define X and Y
If we are going to use our split sequences script from Brownlee, then we need to make sure our Y variables are on the end!

In [5]:
# let's drop the valid column
# Y will be dwpf and relh
# X will be everything else!

del df['valid']
df.head() # check your work

    tmpf  dwpf   relh   drct  sknt  p01i   alti    mslp  vsby
0  17.96  6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0
1  19.94  8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0
2  23.00  6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0
3  21.92  5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0
4  23.00  3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0

In [6]:
Y = df[['tmpf']]
X = df.drop(columns=['tmpf'])
print(df.shape, X.shape, Y.shape)

# looks good! Let's prepare samples for modeling

(46272, 9) (46272, 8) (46272, 1)

In [7]:
# put Y all the way on the left
df = pd.concat([X, Y], axis=1, sort=False)
df.head(n=11)

    dwpf   relh   drct  sknt  p01i   alti    mslp  vsby   tmpf
0   6.08  59.10  190.0   5.0   0.0  30.09  1019.0  10.0  17.96
1   8.06  59.40  190.0   5.0   0.0  30.08  1018.7  10.0  19.94
2   6.98  49.69  210.0   9.0   0.0  30.06  1018.1  10.0  23.00
3   5.00  47.52  230.0  11.0   0.0  30.04  1017.4  10.0  21.92
4   3.92  43.21  250.0  13.0   0.0  30.05  1017.7  10.0  23.00
5   3.92  43.21  250.0  11.0   0.0  30.06  1018.1  10.0  23.00
6   3.02  41.45  240.0  13.0   0.0  30.07  1018.4  10.0  23.00
7   3.92  41.30  240.0  11.0   0.0  30.08  1018.9  10.0  24.08
8   3.92  38.03  210.0   8.0   0.0  30.08  1018.9  10.0  26.06
9   3.92  35.05  220.0  14.0   0.0  30.08  1018.8  10.0  28.04
10  5.00  33.97  210.0  10.0   0.0  30.07  1018.4  10.0  30.02

In [8]:
# some eda - we should be able to predict temperature!
df.plot.scatter(x='tmpf', y='dwpf')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_41684\2614875674.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [9]:
# to get our other code to run, we will put Y
# on the end then re-run our code (needs updating from blog)

# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
    # X and Y have been UPDATED so the last two columns drop off
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1:]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

# Prepare Samples for Modeling
Everything needs to be in 3D arrays.

In [10]:
# let's turn X into lookbacks of 10 with all of our samples
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [11]:
# check your work
print(df.shape, X.shape, y.shape)

(46272, 9) (46263, 10, 8) (46263, 1)

In [12]:
# here's the first X
X[0]

array([[   6.08,   59.1 ,  190.  ,    5.  ,    0.  ,   30.09, 1019.  ,
          10.  ],
       [   8.06,   59.4 ,  190.  ,    5.  ,    0.  ,   30.08, 1018.7 ,
          10.  ],
       [   6.98,   49.69,  210.  ,    9.  ,    0.  ,   30.06, 1018.1 ,
          10.  ],
       [   5.  ,   47.52,  230.  ,   11.  ,    0.  ,   30.04, 1017.4 ,
          10.  ],
       [   3.92,   43.21,  250.  ,   13.  ,    0.  ,   30.05, 1017.7 ,
          10.  ],
       [   3.92,   43.21,  250.  ,   11.  ,    0.  ,   30.06, 1018.1 ,
          10.  ],
       [   3.02,   41.45,  240.  ,   13.  ,    0.  ,   30.07, 1018.4 ,
          10.  ],
       [   3.92,   41.3 ,  240.  ,   11.  ,    0.  ,   30.08, 1018.9 ,
          10.  ],
       [   3.92,   38.03,  210.  ,    8.  ,    0.  ,   30.08, 1018.9 ,
          10.  ],
       [   3.92,   35.05,  220.  ,   14.  ,    0.  ,   30.08, 1018.8 ,
          10.  ]])

In [13]:
# here's the first Y
y[0]

# go scroll up and make sure this matches!
# and it does!

# you will need to customize your split script when
# prepping your data... be careful! take control of your data!

array([28.04])

## Y, Y+1 and Y+2
Let's make sure that our Y vector has multiple time steps, just like we did in the previous script.

In [14]:
# convert to a dataframe
tmp = pd.DataFrame(y)
# rename the column
tmp.rename(columns={0:'y'}, inplace=True)
# create some shifts
tmp['yPlus1'] = tmp['y'].shift(-1)
tmp['yPlus2'] = tmp['y'].shift(-2)
# check your work
print(tmp.head())
print(tmp.tail()) # we will have to deal with those NaN's

# either ffill them or delete them later.

       y  yPlus1  yPlus2
0  28.04   30.02   32.00
1  30.02   32.00   33.08
2  32.00   33.08   33.98
3  33.08   33.98   33.08
4  33.98   33.08   33.08
          y  yPlus1  yPlus2
46258  44.1    42.1    39.0
46259  42.1    39.0    39.9
46260  39.0    39.9    37.0
46261  39.9    37.0     NaN
46262  37.0     NaN     NaN

In [15]:
# I will opt to forward fill them
# and just except the dirt in my data
tmp = tmp.ffill()   # pandas 3 removed fillna(method=)
tmp.tail() # all better!

# of course, you could have dropped the last N arrays
# from both X and y (making sure the shape matches up)

          y  yPlus1  yPlus2
46258  44.1    42.1    39.0
46259  42.1    39.0    39.9
46260  39.0    39.9    37.0
46261  39.9    37.0    37.0
46262  37.0    37.0    37.0

In [16]:
# convert back to numpy array
y = tmp

In [17]:
y.shape

(46263, 3)

# Fit a Model
This will be similar to the last example in 'Sequence Problems_Pt1.ipynb'

In [18]:
# note how there's a 2 at the end
# usually we did this for a multi-classification problem, but not today!
# by default, it's a 'linear' activiation function
# so this is 2 node output and we're doing regression.

n_steps = X.shape[1]
n_features = X.shape[2]
n_outputs = y.shape[1]

print(n_steps, n_features, n_outputs)

10 8 3

In [19]:
model = Sequential()
model.add(LSTM(50, activation='relu',
               recurrent_dropout=0.1,
               input_shape=(n_steps, n_features)))
model.add(Dropout(0.2))
model.add(Dense(n_outputs)) # since Y has three values, we need to predict three values
model.compile(optimizer='adam', loss='mse')

import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in
# the validation loss for 10 consecutive epochs.
es = keras.callbacks.EarlyStopping(monitor='val_loss',
                                   mode='min',
                                   patience=10, # you can play with this!
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(X,
                    y,
                    callbacks=[es],
                    epochs=800, # you can set this to a big number!
                    batch_size=100,
                    validation_split=0.2,
                    verbose=1,
                    shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/800

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14:27 2s/step - loss: 23076.3496

 11/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 18480.3965

 21/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 14539.0801

 30/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 12523.4678

 39/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11092.9980

 48/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10055.6709

 57/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9186.3730

 66/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8559.8232

 74/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8056.7153

 83/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7592.2896

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7195.9414

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6888.9639

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6604.0161

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6318.8848

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6046.1167

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5796.6694

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5593.8340

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5413.2998

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5225.5254

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 5043.1357

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4876.0381

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4720.4746

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4588.6558

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 4462.3701

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4332.0400

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4207.5757

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4091.4104

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3977.9722

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3871.8643

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3784.7043

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3690.6243

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3600.9036

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3523.6575

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3442.3213

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3365.4771

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3291.1912

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3223.8616

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3165.6863

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3102.1243

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3042.2866

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2985.5503

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2936.0288

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2882.7932

371/371 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 2882.2571 - val_loss: 319.6956

Epoch 2/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 781.8250

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 714.0190

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 729.5833

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 723.9700

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 704.2319

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 714.3994

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 704.9343

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 699.5126

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 695.9034

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 688.2675

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 686.1063

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 680.9418

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 676.0663

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 670.5758

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 666.5175

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 659.5289

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 653.3776

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 650.3630

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 643.2968

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 638.1342

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 631.8455

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 625.7961

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 621.3513

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 617.0451

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 611.6513

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 605.8953

231/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 602.3341

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 598.3677

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 594.3527

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 590.3414

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 586.2543

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 581.4175

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 578.4031

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 575.4167

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 572.4191

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 569.4466

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 566.4320

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 563.1274

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 560.0123

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 557.4302

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 553.6368

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 551.7701

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 548.8005

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 548.3652 - val_loss: 189.1246

Epoch 3/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 413.0141

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 427.1860

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 407.1368

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 409.9273

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 411.2870

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 411.8902

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 411.8265

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 411.7029

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 409.8395

 82/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 411.2244

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 409.3343

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 408.0032

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 406.2292

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 406.0573

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 404.0413

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 401.9643

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 399.2785

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 398.4256

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 396.8873

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 395.5929

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 393.3036

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 391.5906

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 390.2769

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 387.9623

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 386.7418

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 385.5136

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 383.4660

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 382.5190

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 381.9678

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 380.4696

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 379.3712

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 378.8833

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 378.1700

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 377.1972

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 375.9883

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 375.2165

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 373.8541

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 372.0672

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 371.0097

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 369.2012

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 367.2070

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 366.2602

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 365.0917

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 364.2025 - val_loss: 116.8423

Epoch 4/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 303.0931

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 305.7132

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 296.2883

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 306.9671

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 303.5378

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 306.8035

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 301.7123

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 301.3660

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 300.8849

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 299.4837

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 298.2557

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 296.4133

100/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 293.0714

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 290.6865

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 288.8382

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 289.7078

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 287.7253

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 287.2224

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 285.9076

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 285.2574

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 284.6726

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 284.3947

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 281.8073

182/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 280.9217

190/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 279.5280

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 279.0675

205/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 277.9572

213/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 277.1813

221/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 276.2245

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 274.9449

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 273.8279

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 272.9697

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 271.8093

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 270.9240

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 269.9165

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 268.7712

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 268.2581

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 268.0420

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 267.1249

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 266.2460

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 265.8780

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 265.3599

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 264.7943

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 263.6208

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 263.0147

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 261.8639

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 260.9074

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 260.0925

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 258.8702

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 258.2226

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 257.9846 - val_loss: 51.6912

Epoch 5/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 204.8560

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 204.1572

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 203.2476

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 206.8212

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 201.8831

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 202.4886

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 202.5233

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 202.6379

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 204.6031

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.2915

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.1761

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.2208

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 205.0140

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 203.8840

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 203.0602

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 202.0275

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 200.5786

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 200.2321

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 200.5508

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 199.3573

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 198.7294

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 198.9221

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 197.3772

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 196.1737

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 196.0835

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 195.4802

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.9083

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.5864

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.3402

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.6809

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.4195

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.5770

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.2412

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.8911

295/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.6203

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.4039

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.7692

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.2149

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.3415

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.9596

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 190.1556

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.9073

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.5929

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.0628

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 189.0628 - val_loss: 33.8425

Epoch 6/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 131.4531

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 152.5362

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 160.6052

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 165.8473

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 165.2851

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 167.3768

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.0794

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.4931

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.3488

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.3747

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.7845

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 167.8779

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.0729

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.2330

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.7761

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.6090

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.3786

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.5042

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.6700

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.3823

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 167.8718

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 168.0114

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 167.0554

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 167.1890

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.4920

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.9436

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.7663

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.7529

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.1298

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 166.3071

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.9481

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.6890

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 165.4950

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.9295

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.5482

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.3144

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.1238

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.8489

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.5709

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 163.0155

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 162.4193

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 162.8605

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 162.4194

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 162.3931 - val_loss: 26.0021

Epoch 7/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 38ms/step - loss: 150.7173

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 141.5102

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 143.5900

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 146.7709

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 149.5111

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 148.3810

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 151.6819

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 152.4669

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 152.2472

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 153.5420

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 153.4965

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 152.9950

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 152.4427

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 151.5816

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 150.7085

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 151.2876

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 151.0289

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 149.8881

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 150.1426

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 149.1807

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 148.4950

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 148.8954

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 148.3735

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 149.6068

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 149.5496

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 149.2997

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.8964

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.5298

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.9704

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 149.1617

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.6649

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.0147

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.5793

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.2430

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.4566

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.2044

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.3922

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.3629

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.3502

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.4941

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.5113

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.6887

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.4256

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 147.2051 - val_loss: 30.6631

Epoch 8/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 157.4770

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 140.8444

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 138.0835

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 137.5031

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 138.7944

 45/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 142.2444

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 141.8893

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.1740

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.8968

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.7233

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.4201

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.1291

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.0168

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.1515

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.4826

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.4102

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.0578

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.4235

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 143.2901

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.4620

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 142.0028

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 141.6068

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 141.6891

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 140.6807

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 140.3022

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.8459

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.2433

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.2881

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.8586

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.5224

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.2672

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.0539

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.7736

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.8402

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.0685

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.8406

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.0993

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.0844

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.1565

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.9645

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.7857

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.4648

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.2027

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 137.3562 - val_loss: 21.4903

Epoch 9/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - loss: 101.4773

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 129.6114

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 131.8547

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 132.8831

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 130.3933

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 130.1337

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 130.4420

 57/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 130.5910

 64/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 129.9171

 72/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 129.5994

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 130.0778

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 131.7118

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 131.5846

102/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 132.1245

110/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 131.5181

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 131.2834

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 131.2362

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 130.4837

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 130.0246

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 129.5431

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 129.3316

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 129.1053

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 128.3902

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 127.8935

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 128.0336

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 127.9947

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 127.6359

214/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 127.5268

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.7755

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.6310

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.7264

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.8320

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.6953

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.5671

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.3705

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.2074

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.3485

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.2462

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.0470

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.1590

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.9224

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 127.1848

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.9196

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.7396

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.5278

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.3926

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.6034

338/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.7626

345/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 126.8248

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 127.1124

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 126.9916

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 126.8329

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 126.6587

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 126.5694

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 126.5694 - val_loss: 28.7209

Epoch 10/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 126.3522

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 122.7985

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 122.0296

 24/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 120.7898

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 121.9912

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 121.0399

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 121.5800

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 121.7457

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 121.1871

 76/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 122.7157

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 122.9993

 94/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.4404

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.7474

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.8692

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.5692

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.7573

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 125.2378

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.7672

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.5061

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.2992

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.2920

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 124.1816

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 124.1173

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 123.9421

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 123.8967

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 123.4919

215/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 122.9421

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 123.2015

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 123.0605

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.6002

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.2581

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.2853

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.4543

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.2228

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 122.0782

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.7929

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.7506

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.6846

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.7285

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.3987

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.4079

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.5402

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.4350

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.5236

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.3658

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.1770

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 121.1126

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 120.9479

370/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 120.8158

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 120.8057 - val_loss: 42.5867

Epoch 11/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 103.3104

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 126.6230

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 121.4984

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 118.0019

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 117.5482

 45/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 117.1553

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 115.7218

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 116.4497

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 117.5260

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 117.0163

 82/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 117.0707

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.7611

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.6790

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.2403

115/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.8801

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.8504

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.1558

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 115.3722

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 115.9775

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.0770

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.3791

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 115.7629

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.4116

181/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.6060

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.5350

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.2474

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.3162

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.3186

219/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 116.2137

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.2774

233/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.1536

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.2424

249/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.3012

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.4394

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.0448

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.1923

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.9267

286/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.9976

292/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.0811

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.0166

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 116.0405

311/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.7262

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.5084

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.4441

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.2815

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.2014

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.9218

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 114.9574

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.0010

361/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.2187

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115.2863

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 115.3558 - val_loss: 16.9068

Epoch 12/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 11:42 2s/step - loss: 140.5310

 12/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 117.0416

 21/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 112.5428

 30/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 110.7462

 40/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.9003

 50/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 110.0653

 59/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 110.7780

 68/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 110.0260

 77/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 109.4657

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 109.0805

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.9273

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.5782

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.7206

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.4984

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.2089

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.2527

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.1158

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.8282

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.4434

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 109.1969

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.9494

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 109.2156

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.9938

209/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7700

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.5916

226/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.8253

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.8713

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7802

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.8447

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.5459

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.3960

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.4816

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7082

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.2240

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.1510

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.4738

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7285

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7725

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.5382

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.7226

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.6460

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108.3339

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 108.2803 - val_loss: 15.5017

Epoch 13/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 110.5045

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 95.4157

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 100.7955

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 101.0527

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 103.8636

 43/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 104.5766

 52/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.6624

 61/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.2644

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.4483

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.7920

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.7465

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.4854

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.1316

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.0547

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.6368

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.2671

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.0795

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.2820

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.0915

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.9921

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.2834

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.2916

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.1104

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.8775

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.2781

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1683

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1092

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1725

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1768

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.4085

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.9824

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.0935

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.0864

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.0648

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.0101

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.2481

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.4066

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1374

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.9918

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107.1337

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.8348

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.8009

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106.5782

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 106.5407 - val_loss: 19.2034

Epoch 14/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 71.7720

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 103.0998

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 103.4674

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 105.5993

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 105.3811

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.5953

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.5965

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.2776

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.3994

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.0302

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.0382

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.8571

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.0848

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.2337

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.7790

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.0018

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.5186

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.6977

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.5356

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.6415

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 103.0213

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.4327

194/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.6977

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 102.6230

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.8117

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.6517

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9479

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.8685

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2888

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.5306

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2667

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.5646

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.5571

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.3207

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.4106

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.5165

319/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2902

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2045

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2894

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9098

355/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9490

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.0500

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.1713

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 103.1713 - val_loss: 13.9986

Epoch 15/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 104.7469

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 113.4051

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 111.8683

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 108.4341

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 107.5144

 44/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 108.0281

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.5285

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.3176

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 108.2000

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.0475

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 107.3081

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.6215

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.4051

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.1835

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.0790

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.0523

142/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.1859

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.5526

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 106.7975

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.7819

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.5859

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.9508

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 105.0694

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.7972

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 104.8565

215/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.1169

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.0013

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.9700

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.1182

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.1328

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.3145

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.1998

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 104.2716

275/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.8407

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.8130

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.5859

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.4369

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.2721

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.3210

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 103.1782

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9287

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9241

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.9599

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.7597

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 102.6363

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 102.6060 - val_loss: 12.8770

Epoch 16/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 82.6757

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 95.1300

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 96.0612

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 97.3468

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 100.7368

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 100.7937

 47/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 100.3586

 53/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 101.7255

 61/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 101.1863

 69/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 101.0424

 77/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 101.3333

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 101.7800

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 102.1115

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 102.1614

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 101.6792

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 101.1596

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.0105

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.8474

146/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.4334

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.2612

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.3201

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.1048

172/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.0371

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.8241

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 100.0573

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.3884

196/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.2794

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 99.1675

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.9685

215/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.9379

221/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.6815

227/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.5645

233/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 98.5032

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.5683

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.5900

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6354

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6579

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6845

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.8278

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.9301

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 99.1305

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 99.1682

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.9992

301/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.9970

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.9743

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.9327

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.7025

329/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.7457

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6756

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.7347

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6793

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.5886

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98.6152

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 98.6709 - val_loss: 17.5313

Epoch 17/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 12:25 2s/step - loss: 108.5622

 12/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 91.4262

 22/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 95.0008

 32/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97.5434

 42/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99.4619

 51/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97.7086

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97.2958

 67/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.5275

 76/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.8273

 85/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.0941

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.2796

104/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.0271

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.9839

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.3907

131/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.5108

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.6901

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98.6538

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98.2355

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.9757

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98.2610

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 98.9519

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 99.4313

201/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.4867

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.7334

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.9512

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.2225

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 101.0076

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.9333

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.7002

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.7889

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 100.3329

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.8155

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.7571

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.8205

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.4413

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.1680

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.1463

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.2362

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.2256

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.4989

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.5210

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 99.2694

371/371 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 99.2190 - val_loss: 17.3632

Epoch 18/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 39ms/step - loss: 87.4232

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 90.0137

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 95.9777

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 96.0294

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.9987

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.3791

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.5763

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.8077

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.0742

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.8477

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.0319

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.3562

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.3033

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.2482

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.0874

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.1692

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.6525

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.0577

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.4800

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.4037

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.2465

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.9547

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.1638

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.4194

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.6971

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.4505

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.3310

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.3398

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.0966

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.1797

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.2686

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.2357

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.5209

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.4476

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.4001

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 95.6677

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.1157

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.4082

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.6299

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.8460

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.9408

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.9725

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 96.9496

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 97.0798

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 97.1807 - val_loss: 20.3789

Epoch 19/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 152.0169

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 109.8980

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 102.9191

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 98.9653

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.7501

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.5247

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 97.8017

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.8865

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.7848

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.2024

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 96.4402

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.7840

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.4019

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.1167

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.0553

128/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.7855

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.8131

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.1759

151/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.9422

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.8935

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.6561

178/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.6622

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.2621

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.4212

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.8567

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.0333

222/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.7908

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.9088

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6439

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.7845

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.7834

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6778

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6581

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8431

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8139

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.0344

304/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.9402

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.9222

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8002

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6202

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.9795

349/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8953

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8981

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.9024

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 93.8175 - val_loss: 10.9011

Epoch 20/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 76.0630

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85.5923

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 88.0866

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.0537

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.6196

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.6888

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.6924

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.0831

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.2591

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.2593

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.0478

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.7883

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.5564

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.3368

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.1815

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.5689

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.1771

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.7126

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.6368

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.7621

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.3473

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.1010

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.4328

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.8950

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.4593

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.3508

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.2451

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8209

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 94.0200

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.8706

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6895

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.4077

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6537

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.6368

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.5464

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.4873

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.3270

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.3309

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.1525

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.8629

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.9941

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.3269

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 93.5182

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 93.4751 - val_loss: 16.5329

Epoch 21/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 98.2432

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84.7233

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 92.0334

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.6010

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.4490

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.7667

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.8285

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.5621

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.6379

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.1084

 86/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.4109

 95/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.5240

103/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.7046

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.8862

120/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.0990

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.1511

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4778

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.3880

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.0507

163/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4539

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4700

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.6967

189/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.7976

198/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.0396

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.8021

214/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.1947

223/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.3141

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.5211

241/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.5920

250/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.4166

258/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.5439

267/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.5695

276/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.0999

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.3573

294/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.0453

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.9920

312/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.0293

321/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.7000

330/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.8316

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.7528

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.9286

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.8609

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.8062

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 91.7164 - val_loss: 11.1766

Epoch 22/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 79.5247

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84.4564

 16/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 90.9371

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 91.0514

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 90.3976

 42/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.3422

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.7098

 60/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.2984

 69/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.0793

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.2273

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.7697

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.0592

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4672

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.5354

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4428

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.9516

140/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.4530

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.2999

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.2674

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.9388

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.6886

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 91.0696

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.9326

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 90.6608

209/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3537

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5413

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6852

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5496

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6254

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5381

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.5343

269/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3121

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4663

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4112

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6461

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.6864

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4693

322/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3597

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3550

339/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4662

347/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4478

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.2210

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 89.9373

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 89.9043 - val_loss: 25.4646

Epoch 23/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 103.9277

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 103.3737

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 99.4907

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 96.8087

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 95.2883

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.7515

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.2883

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.3732

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 95.4420

 79/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.3353

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.5468

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.8310

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 94.3108

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.6047

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.1752

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.8599

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 93.1110

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.7434

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.0589

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.3605

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.4893

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.4632

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.1897

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 92.1459

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 92.1055

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.8251

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.6223

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.4151

247/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.2707

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.3224

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.4106

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.1448

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 91.0365

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.9928

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.7456

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3873

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3931

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.2465

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.2460

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.3394

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4265

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4736

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 90.4449

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 90.4816 - val_loss: 31.7188

Epoch 24/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 107.9444

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 95.5864

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 91.6315

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 90.9413

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.1136

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.5867

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.6599

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.8601

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.9245

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.0089

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.6117

 97/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.6609

106/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.5403

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.3292

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.1900

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.9255

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5645

148/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5592

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.7041

166/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5427

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5154

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.4421

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.3876

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.2913

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.3905

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2430

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0254

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9933

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2733

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.1663

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.2648

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.1669

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7908

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7275

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7219

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7428

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.6501

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.6276

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7140

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.6936

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.8518

357/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0014

365/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0329

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 85.9851 - val_loss: 16.3662

Epoch 25/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 90.9484

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 87.3494

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 83.3232

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 86.7707

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.6868

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.0609

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5085

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.5795

 71/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.5283

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.1319

 89/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.7747

 98/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.2000

107/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.4576

116/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.7363

125/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.5617

134/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.5382

143/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.2385

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 85.1016

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.7226

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.9940

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.9582

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.5497

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.5938

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 84.3161

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.5083

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.6051

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.5090

236/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.7923

245/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 84.9349

254/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.1692

263/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.3105

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.2083

281/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.0298

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.3079

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.5470

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.6467

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.6668

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9022

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.0253

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.8900

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.9582

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7907

366/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 85.7799

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 85.7054 - val_loss: 9.7610

Epoch 26/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 13s 37ms/step - loss: 90.7054

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 89.0476

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 85.2062

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 88.6832

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 88.8708

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 89.0680

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 88.2351

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.2877

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.8731

 82/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.5323

 91/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.9037

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.4881

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.6939

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.2877

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.4743

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.8183

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.8971

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.6004

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.4235

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.6738

180/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 86.9158

188/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.0034

197/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.1104

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 87.1078

212/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.9663

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.8358

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.0656

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.2328

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.4233

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.4599

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.5613

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.5571

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 87.1217

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.8514

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.8379

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6830

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6398

327/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.5213

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.5027

344/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6016

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6763

362/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.6726

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86.4634

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 86.4634 - val_loss: 11.6674

Epoch 27/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 85.2481

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 86.9694

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.8993

 26/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82.8427

 35/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82.9983

 44/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.6249

 51/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 83.1632

 57/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.1293

 64/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.4146

 70/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84.3267

 72/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.1486

 78/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 83.9007

 85/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.1959

 92/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 83.4530

 98/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.7065

104/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 83.9823

110/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.1893

116/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.2868

120/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.5021

126/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.9690

132/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 84.8506

138/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 85.2192

143/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 85.3041

148/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 85.3098

154/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.2580

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.3751

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.3785

172/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.3445

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.1854

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.0781

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 84.9361

197/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.0552

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.2959

209/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.1453

215/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 84.9154

221/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 84.9990

228/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 84.9666

234/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.0946

241/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.1031

247/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.1541

254/371 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 85.2154

260/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.3822

266/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.1816

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.2856

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.2782

284/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.1789

290/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0694

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.1170

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.1694

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0555

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0812

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.1515

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0413

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9417

336/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 85.0415

341/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9398

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9938

353/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9732

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9412

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.9087

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.7822

371/371 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 84.7822 - val_loss: 11.2646

Epoch 28/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 88.7035

  8/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 91.5620

 15/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 90.3662

 22/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.5319

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 90.0055

 34/371 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 90.8708

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.9150

 48/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.3954

 55/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.6308

 61/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.9402

 69/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 89.3821

 77/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88.6268

 84/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88.2000

 91/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88.4281

 98/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 88.4151

105/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 87.8447

112/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.9978

119/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.8337

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.3519

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.4918

139/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.4001

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.4521

155/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.4230

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 86.9526

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 87.0162

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 86.8449

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 86.4403

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.7469

200/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.7426

208/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.6076

216/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.9217

224/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.8387

232/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 86.8449

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 87.1112

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.9930

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.7328

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.4564

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.5116

278/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.4931

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.3628

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 86.1586

302/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.8643

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.7429

318/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.9218

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.7234

335/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.6611

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.5118

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.4251

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.2068

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 85.0119

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 85.0753 - val_loss: 10.1873

Epoch 29/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 44ms/step - loss: 94.8490

  8/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.8307

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.3256

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.8327

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.8773

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.6655

 49/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81.0547

 56/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.1159

 64/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.1945

 72/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81.7208

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.7732

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.2243

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.4168

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.2187

113/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.0532

121/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.9804

129/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.5717

137/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 83.1186

145/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 83.1221

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.9666

160/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.8310

168/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.4835

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.3709

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.9482

191/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.8821

199/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.8262

207/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.8341

215/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.4914

224/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4621

232/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5613

240/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4159

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.8114

256/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.9743

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.8649

272/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7495

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5855

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7065

295/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.8163

303/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6909

310/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.8384

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.9040

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7073

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5767

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6474

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6056

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6812

364/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5568

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5833

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 81.5833 - val_loss: 16.3100

Epoch 30/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - loss: 80.4181

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81.6758

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.1148

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.6662

 32/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80.1130

 40/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79.7690

 46/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81.7935

 52/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 82.9779

 57/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 82.8814

 65/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 82.3220

 73/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 83.1147

 80/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 83.3412

 87/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 82.9732

 94/371 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 83.1204

102/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.1667

110/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.9027

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.9574

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.5960

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.4110

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.2890

149/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.3402

157/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.1044

164/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.8318

171/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.7378

179/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.4593

187/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.6603

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.5344

203/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.5372

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.5156

219/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.5964

227/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 81.6857

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.9577

243/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7024

251/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6738

259/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5011

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4182

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4897

277/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5897

285/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5602

293/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4151

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.2541

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.2889

316/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.2450

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.4098

332/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.3770

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.5237

348/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7389

356/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6773

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.6636

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81.7399

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 81.7399 - val_loss: 12.2072

Epoch 31/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 16s 45ms/step - loss: 74.3703

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 74.5210

 17/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 75.6444

 25/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79.7925

 33/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 82.2864

 41/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.0754

 49/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.1332

 57/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.2863

 66/371 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83.0043

 75/371 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 82.6109

 84/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.1353

 92/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.5190

101/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.7945

109/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.6502

118/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.1619

127/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.3247

136/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.3721

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.0238

152/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.1609

161/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 82.0598

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.5629

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.7276

185/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.7724

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.6749

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.1247

211/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.8740

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.2123

229/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0853

238/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8348

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0538

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0688

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7547

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.5914

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.6043

289/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7000

298/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8527

307/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8008

315/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8290

324/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7988

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8648

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7452

350/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7762

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8457

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.7702

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 80.9004 - val_loss: 10.5821

Epoch 32/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 15s 41ms/step - loss: 80.9936

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84.8397

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82.2370

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.0469

 37/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.5477

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.2883

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.4194

 64/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.1415

 73/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.4716

 80/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.5001

 88/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.0027

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.0024

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.6376

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.5050

123/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.3610

132/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.6869

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.5754

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.6678

159/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.5242

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.8152

175/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 81.0495

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.8033

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.9434

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.7466

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.8312

219/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0742

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.9938

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0858

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.3151

252/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.4474

261/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.3237

270/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1226

279/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0895

287/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0104

296/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0163

305/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.2311

313/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.2619

320/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1965

328/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1683

337/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.2249

346/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.0837

354/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1868

363/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1158

371/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81.1484

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 81.1484 - val_loss: 14.6570

Epoch 33/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 72.7300

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.8947

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.6878

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.7160

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.5802

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.6684

 54/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 80.3347

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.3346

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8243

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.6590

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.5478

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.8407

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.5598

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.9654

124/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.1623

133/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3126

141/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3116

150/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3763

158/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.2121

167/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.9461

176/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.3814

184/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.4203

193/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.5325

202/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.9000

211/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.9082

220/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.8650

228/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.9585

237/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.7588

246/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.6147

255/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.5120

264/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.4904

273/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3324

282/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.2963

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3594

300/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3336

309/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3422

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.2039

325/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1494

333/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1660

342/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1972

351/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3063

359/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.4562

368/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.5920

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 78.5726 - val_loss: 11.4419

Epoch 34/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 38ms/step - loss: 90.2236

 10/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 79.3344

 19/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 77.0953

 28/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 80.5427

 37/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.5280

 46/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.0937

 55/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.0938

 63/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.7730

 72/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.9893

 81/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.7382

 90/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8445

 99/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.6887

108/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.4860

117/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.8018

126/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.6017

135/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.0352

144/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.7952

153/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.1623

162/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.2857

169/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.5549

177/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.5369

186/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.5533

195/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.9561

204/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.9206

213/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80.0302

221/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4887

230/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.5928

239/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.6121

248/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4249

257/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4855

265/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.5867

274/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.5107

283/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.5824

291/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.6092

299/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.5221

308/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4212

317/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.3648

326/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.3993

334/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.4342

343/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.3455

352/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.1811

360/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.0850

369/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 79.1129

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 79.0756 - val_loss: 20.9029

Epoch 35/800

  1/371 ━━━━━━━━━━━━━━━━━━━━ 14s 40ms/step - loss: 67.6405

  9/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 78.8130

 18/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 78.6145

 27/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 78.5370

 36/371 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 78.2800

 45/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3494

 53/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.3932

 62/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.2436

 70/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 77.2686

 78/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.1423

 87/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.5851

 96/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.4094

105/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.6520

114/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.1511

122/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8316

130/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.2684

138/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.0589

147/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.9466

156/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 79.2360

165/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.9531

174/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8257

183/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.9967

192/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.8373

201/371 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 78.3166

210/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.7130

218/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.9199

227/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.8411

235/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.7411

244/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.5780

253/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.3334

262/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.1634

271/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.9180

280/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.7752

288/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.8969

297/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.8778

306/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.0075

314/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.2027

323/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.9208

331/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.9003

340/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.0889

349/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77.9376

358/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.0717

367/371 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 78.0863

371/371 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 78.0868 - val_loss: 11.9137

In [20]:
# and you can show how your model did

# since it's a single sample, we need to reshape
data = X[0]
data = data.reshape(1,n_steps,n_features)
print(data)
print(model.predict(data))

# did we get close?
print(y[0:1])

# of course you can show scatterplots and everything else
# for more examples

[[[   6.08   59.1   190.      5.      0.     30.09 1019.     10.  ]
  [   8.06   59.4   190.      5.      0.     30.08 1018.7    10.  ]
  [   6.98   49.69  210.      9.      0.     30.06 1018.1    10.  ]
  [   5.     47.52  230.     11.      0.     30.04 1017.4    10.  ]
  [   3.92   43.21  250.     13.      0.     30.05 1017.7    10.  ]
  [   3.92   43.21  250.     11.      0.     30.06 1018.1    10.  ]
  [   3.02   41.45  240.     13.      0.     30.07 1018.4    10.  ]
  [   3.92   41.3   240.     11.      0.     30.08 1018.9    10.  ]
  [   3.92   38.03  210.      8.      0.     30.08 1018.9    10.  ]
  [   3.92   35.05  220.     14.      0.     30.08 1018.8    10.  ]]]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step

[[27.32622  26.807281 26.402674]]
       y  yPlus1  yPlus2
0  28.04   30.02    32.0

In [21]:
# select first column of y
y['y']

0        28.04
1        30.02
2        32.00
3        33.08
4        33.98
         ...
46258    44.10
46259    42.10
46260    39.00
46261    39.90
46262    37.00
Name: y, Length: 46263, dtype: float64

In [22]:
# well done! You can also make scatterplots of actual vs. predicted
pred = model.predict(X)
pred

   1/1446 ━━━━━━━━━━━━━━━━━━━━ 6:54 287ms/step

  30/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  60/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

  88/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 118/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 148/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 178/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 207/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 232/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 260/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 287/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 312/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 338/1446 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step

 364/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 392/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 420/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 442/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 470/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 498/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 526/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 553/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 581/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 609/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 637/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 663/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 691/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 719/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 746/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 774/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 801/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 828/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 855/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 880/1446 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

 908/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 936/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 964/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 992/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1020/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1048/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1076/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1102/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1130/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1155/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1178/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1205/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1229/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1258/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1286/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1314/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1340/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1368/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1395/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1422/1446 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

1446/1446 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step

array([[27.32622 , 26.807281, 26.402674],
       [29.13072 , 28.60801 , 28.162449],
       [30.303923, 29.740906, 29.22007 ],
       ...,
       [37.59651 , 36.94209 , 36.358448],
       [40.236202, 39.61105 , 38.980526],
       [35.6823  , 35.06623 , 34.59759 ]], shape=(46263, 3), dtype=float32)

In [23]:
# select first column
pred[:,0:1]

array([[27.32622 ],
       [29.13072 ],
       [30.303923],
       ...,
       [37.59651 ],
       [40.236202],
       [35.6823  ]], shape=(46263, 1), dtype=float32)

In [24]:
# pred1
plt.scatter(y['y'], pred[:,0:1])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_41684\1016567324.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [25]:
# pred2
plt.scatter(y['yPlus1'], pred[:,1:2])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_41684\3354951425.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# and the third one
plt.scatter(y['yPlus2'], pred[:,1:2])
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_41684\2471302604.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
# it worked! of course the prediction into the
# future will be a little worst than the next time step

# and as you can see, prepping the data is important!