<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 9 — Multivariate RNN Pt 1: split_sequences, column order, the classification head
- Multivariate differs only in prep: all X on the left, TARGET AS THE LAST COLUMN (drop the date); look-back is the hyperparameter.
- split_sequences with look-back 10 -> 2,655 samples of 10 x features; the -1 predicts the NEXT step.
- SimpleRNN with a sigmoid head, n_steps / n_features inherited from the shape; if it learns in one epoch, add dropout.
- Show the time-series plot even for classification - it misses the quick in/out transitions.
-->

# Multivariate Occupancy Example (RNN)
----------------------------
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental sensor data (temperature, humidity, light, CO2).

Link: http://archive.ics.uci.edu/ml/datasets/Occupancy+Detection+

Same flow as before, just need to prep our data differently. For now, we ignore the time dimension but we could resample to a regular resolution.

Wow - also a nice example: https://machinelearningmastery.com/multivariate-time-series-forecasting-lstms-keras/

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from LuisM78’s GitHub repository:
# url = 'https://raw.githubusercontent.com/LuisM78/Occupancy-detection-data/master/datatest.txt'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/datatest.txt"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 2665 entries, 140 to 2804
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2665 non-null   str
 1   Temperature    2665 non-null   float64
 2   Humidity       2665 non-null   float64
 3   Light          2665 non-null   float64
 4   CO2            2665 non-null   float64
 5   HumidityRatio  2665 non-null   float64
 6   Occupancy      2665 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 195.3 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.7000,26.272,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.7180,26.290,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.7300,26.230,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.7225,26.125,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.7540,26.200,488.600000,779.000000,0.004767,1
145,2015-02-02 14:23:59,23.7600,26.260,568.666667,790.000000,0.004779,1
146,2015-02-02 14:25:00,23.7300,26.290,536.333333,798.000000,0.004776,1
147,2015-02-02 14:25:59,23.7540,26.290,509.000000,797.000000,0.004783,1
148,2015-02-02 14:26:59,23.7540,26.350,476.000000,803.200000,0.004794,1
149,2015-02-02 14:28:00,23.7360,26.390,510.000000,809.000000,0.004796,1
150,2015-02-02 14:29:00,23.7450,26.445,481.500000,815.250000,0.004809,1
151,2015-02-02 14:30:00,23.7000,26.560,481.800000,824.000000,0.004817,1
152,2015-02-02 14:31:00,23.7000,26.600,475.250000,832.000000,0.004824,1
153,2015-02-02 14:31:59,23.7000,26.700,469.000000,845.333333,0.004842,1
154,2015-02-02 14:32:59,23.7000,26.774,464.000000,852.400000,0.004856,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    1693
1     972
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(2665, 6)

     Temperature  Humidity       Light         CO2  HumidityRatio  Occupancy
140      23.7000    26.272  585.200000  749.200000       0.004764          1
141      23.7180    26.290  578.400000  760.400000       0.004773          1
142      23.7300    26.230  572.666667  769.666667       0.004765          1
143      23.7225    26.125  493.750000  774.750000       0.004744          1
144      23.7540    26.200  488.600000  779.000000       0.004767          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(2656, 10, 5)
(2656,)

In [11]:
# check the first few values
X[0]

array([[2.37000000e+01, 2.62720000e+01, 5.85200000e+02, 7.49200000e+02,
        4.76416302e-03],
       [2.37180000e+01, 2.62900000e+01, 5.78400000e+02, 7.60400000e+02,
        4.77266099e-03],
       [2.37300000e+01, 2.62300000e+01, 5.72666667e+02, 7.69666667e+02,
        4.76515255e-03],
       [2.37225000e+01, 2.61250000e+01, 4.93750000e+02, 7.74750000e+02,
        4.74377336e-03],
       [2.37540000e+01, 2.62000000e+01, 4.88600000e+02, 7.79000000e+02,
        4.76659400e-03],
       [2.37600000e+01, 2.62600000e+01, 5.68666667e+02, 7.90000000e+02,
        4.77933243e-03],
       [2.37300000e+01, 2.62900000e+01, 5.36333333e+02, 7.98000000e+02,
        4.77613633e-03],
       [2.37540000e+01, 2.62900000e+01, 5.09000000e+02, 7.97000000e+02,
        4.78309371e-03],
       [2.37540000e+01, 2.63500000e+01, 4.76000000e+02, 8.03200000e+02,
        4.79409400e-03],
       [2.37360000e+01, 2.63900000e+01, 5.10000000e+02, 8.09000000e+02,
        4.79618871e-03]])

In [12]:
# check Y
y[0]

np.float64(1.0)

In [13]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [14]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(2656, 10, 5) (1328, 10, 5) (1328, 10, 5)
(2656,) (1328,) (1328,)

# RNN one layer model

In [15]:
# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

print(n_steps, n_features)

10 5

In [16]:
# now let's build a model
# NEED TO UPDATE FOR CLASSIFICATION

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])


es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,111 (4.34 KB)

 Trainable params: 1,111 (4.34 KB)

 Non-trainable params: 0 (0.00 B)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 5:33 2s/step - acc: 0.2000 - loss: 102.2059

 25/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.6880 - loss: 26.3949

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.8286 - loss: 14.5140

 74/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.8757 - loss: 10.9579

 98/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.8918 - loss: 8.5738

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9107 - loss: 7.0603

143/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9119 - loss: 6.5301

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9229 - loss: 5.6886

189/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9206 - loss: 5.3799

212/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9274 - loss: 5.0054

213/213 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - acc: 0.9275 - loss: 4.9960 - val_acc: 0.9774 - val_loss: 2.9031

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 1.0000 - loss: 1.1688e-26

 24/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9417 - loss: 2.1011

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9574 - loss: 1.8470

 70/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9629 - loss: 1.5423

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9527 - loss: 1.6161

116/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9603 - loss: 1.4690

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9612 - loss: 1.6229

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9627 - loss: 1.4430

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9565 - loss: 1.4287

203/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9586 - loss: 1.3803

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9595 - loss: 1.3298 - val_acc: 0.9624 - val_loss: 0.3866

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8000 - loss: 1.6708

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9182 - loss: 1.3590

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9545 - loss: 0.9887

 66/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9515 - loss: 1.0110

 87/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9471 - loss: 1.1082

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9556 - loss: 0.9298

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9600 - loss: 1.0444

153/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9542 - loss: 1.1834

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9554 - loss: 1.4303

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9571 - loss: 1.3121

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9586 - loss: 1.2317 - val_acc: 0.9248 - val_loss: 0.1984

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8000 - loss: 0.5008

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9565 - loss: 0.2108

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9636 - loss: 0.3261

 66/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9606 - loss: 0.3439

 87/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9540 - loss: 0.4391

109/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9596 - loss: 0.4378

131/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9649 - loss: 0.3761

153/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9621 - loss: 0.3665

169/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9645 - loss: 0.3704

188/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9564 - loss: 0.5241

206/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9592 - loss: 0.5594

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9595 - loss: 0.5997 - val_acc: 0.9774 - val_loss: 1.5822

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 1.0000 - loss: 2.7273e-07

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9636 - loss: 0.7474

 43/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9674 - loss: 0.5896

 65/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9631 - loss: 0.5010

 86/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9535 - loss: 0.5301

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9611 - loss: 0.4606

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9646 - loss: 0.4303

150/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9627 - loss: 0.4099

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9628 - loss: 0.4319

193/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9585 - loss: 0.5264

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9605 - loss: 0.6127 - val_acc: 0.9774 - val_loss: 1.5561

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 1.0000 - loss: 2.1895e-07

 21/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9810 - loss: 0.7310

 37/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9622 - loss: 0.6900

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9630 - loss: 0.5923

 72/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9639 - loss: 0.5087

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9560 - loss: 0.5645

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9622 - loss: 0.4859

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9652 - loss: 0.4321

153/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9608 - loss: 0.4541

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9595 - loss: 0.6507

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9619 - loss: 0.5910

212/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9613 - loss: 0.5683

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9614 - loss: 0.5672 - val_acc: 0.9774 - val_loss: 0.4308

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 9.5984e-10

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9391 - loss: 0.6859

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9600 - loss: 0.6760

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9612 - loss: 0.5503

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9528 - loss: 0.5647

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9604 - loss: 0.4739

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9636 - loss: 0.4184

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9610 - loss: 0.4244

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9611 - loss: 0.6095

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9592 - loss: 0.5554

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9605 - loss: 0.5288 - val_acc: 0.9774 - val_loss: 0.1023

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 1.0000 - loss: 0.0013

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9652 - loss: 0.2417

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9617 - loss: 0.2070

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9623 - loss: 0.1833

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9516 - loss: 0.2644

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9586 - loss: 0.2547

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9631 - loss: 0.2255

150/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9613 - loss: 0.2152

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9616 - loss: 0.2084

192/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9573 - loss: 0.3501

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9595 - loss: 0.4338 - val_acc: 0.9774 - val_loss: 1.3577

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 1.0000 - loss: 1.1004e-06

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9739 - loss: 0.5933

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9644 - loss: 0.5662

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9642 - loss: 0.4566

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9573 - loss: 0.4908

112/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9643 - loss: 0.4130

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9672 - loss: 0.3589

155/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9665 - loss: 0.3216

177/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9582 - loss: 0.4037

199/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9618 - loss: 0.4145

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9623 - loss: 0.4997 - val_acc: 0.9774 - val_loss: 1.2944

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 1.0000 - loss: 9.7291e-07

 24/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9833 - loss: 0.5168

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9689 - loss: 0.5114

 60/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9667 - loss: 0.4302

 76/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9684 - loss: 0.3732

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9621 - loss: 0.4183

113/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9664 - loss: 0.3758

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9682 - loss: 0.3331

150/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9667 - loss: 0.3033

169/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9692 - loss: 0.2791

186/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9602 - loss: 0.4129

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9635 - loss: 0.4339

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9633 - loss: 0.4682 - val_acc: 0.9774 - val_loss: 1.2399

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 1.0000 - loss: 5.9790e-07

 24/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9833 - loss: 0.4636

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9733 - loss: 0.4156

 66/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9697 - loss: 0.3517

 88/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9636 - loss: 0.3399

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9676 - loss: 0.3442

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9701 - loss: 0.2919

157/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9694 - loss: 0.2630

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9609 - loss: 0.3640

201/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9642 - loss: 0.3695

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - acc: 0.9642 - loss: 0.4412 - val_acc: 0.9774 - val_loss: 1.0492

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [17]:
# make a prediction
pred = model.predict(X_train)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

 1/42 ━━━━━━━━━━━━━━━━━━━━ 6s 165ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(1328, 1), dtype=float32)

In [18]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_train, pred)) # looks pretty good!
print(classification_report(y_train, pred))

[[811  33]
 [  0 484]]
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98       844
         1.0       0.94      1.00      0.97       484

    accuracy                           0.98      1328
   macro avg       0.97      0.98      0.97      1328
weighted avg       0.98      0.98      0.98      1328

In [19]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_train.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_train.shape[0]), pred, color='red') # predicted data
plt.suptitle('Train Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\3033679372.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[825  24]
 [  0 479]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.99       849
         1.0       0.95      1.00      0.98       479

    accuracy                           0.98      1328
   macro avg       0.98      0.99      0.98      1328
weighted avg       0.98      0.98      0.98      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 10 — Multivariate RNN Pt 2: LSTM swap, stacking, persistence baseline
- One-word LSTM swap: (features + units) x units + bias, x4 = 4,320 params.
- It predicts the zeros a bit better; weighted F1 comparable.
- Stacked SimpleRNN with return_sequences=True keeps the 10 x 30 sequence into a second RNN - and does WORSE here: too complex for an easy problem.
- Persistence is brutal to beat - show value over the dummy every time.
-->

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(LSTM(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc',
                   mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         4,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,351 (17.00 KB)

 Trainable params: 4,351 (17.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6:30 2s/step - acc: 0.2000 - loss: 59.4140

 20/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.5600 - loss: 12.2095

 37/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7135 - loss: 8.2573

 55/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8000 - loss: 6.2102

 72/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8417 - loss: 5.0912

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8578 - loss: 4.3867

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8785 - loss: 3.9222

124/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8935 - loss: 3.4607

141/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8908 - loss: 3.6165

157/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8981 - loss: 3.2973

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9023 - loss: 3.3356

188/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9085 - loss: 3.0570

204/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9108 - loss: 2.9181

213/213 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - acc: 0.9134 - loss: 2.8610 - val_acc: 0.9774 - val_loss: 2.8066

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 1.0000 - loss: 1.6262e-08

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9529 - loss: 1.9061

 34/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9471 - loss: 1.1140

 51/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9569 - loss: 0.8395

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9582 - loss: 0.7340

 84/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9500 - loss: 0.7599

101/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9584 - loss: 0.6320

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9624 - loss: 0.5707

133/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9624 - loss: 0.5291

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9554 - loss: 0.5754

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9588 - loss: 0.6158

182/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9549 - loss: 1.6269

199/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9548 - loss: 1.6240

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9492 - loss: 1.7475 - val_acc: 0.9774 - val_loss: 0.7822

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 3.5817e-16

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8667 - loss: 2.2427

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9290 - loss: 1.3531

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9319 - loss: 1.2551

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9460 - loss: 1.0355

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9418 - loss: 1.0092

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9432 - loss: 0.9572

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9423 - loss: 0.9635

125/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9488 - loss: 0.8557

141/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9489 - loss: 1.0045

157/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9503 - loss: 0.9351

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9491 - loss: 1.0740

189/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9481 - loss: 1.0237

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9512 - loss: 0.9625

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9492 - loss: 0.9682 - val_acc: 0.5977 - val_loss: 9.4599

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8000 - loss: 72.0541

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8706 - loss: 24.9840

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8750 - loss: 21.7854

 48/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9125 - loss: 15.2247

 64/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9312 - loss: 12.0008

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9350 - loss: 10.4980

 96/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9417 - loss: 9.0603

112/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9429 - loss: 8.0144

128/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9469 - loss: 7.0593

144/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9472 - loss: 6.3996

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9475 - loss: 5.8160

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9440 - loss: 5.5008

191/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9476 - loss: 5.0524

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9507 - loss: 4.6732

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9492 - loss: 4.5669 - val_acc: 0.9248 - val_loss: 0.3133

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 1.0000 - loss: 2.4065e-16

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9067 - loss: 3.0463

 29/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9172 - loss: 3.3490

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9422 - loss: 2.6820

 60/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9467 - loss: 2.3805

 75/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9493 - loss: 2.2895

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9489 - loss: 2.1278

106/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9491 - loss: 1.9166

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9541 - loss: 1.7778

138/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9507 - loss: 2.4697

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9532 - loss: 2.4426

170/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9529 - loss: 2.3407

187/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9487 - loss: 2.3280

203/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9517 - loss: 2.1710

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9529 - loss: 2.0888 - val_acc: 0.9737 - val_loss: 0.2806

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 1.0000 - loss: 7.3849e-34

 18/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9444 - loss: 1.4435

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9438 - loss: 0.8917

 48/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9583 - loss: 0.6264

 62/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9613 - loss: 0.5464

 78/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9513 - loss: 0.5330

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9462 - loss: 0.5459

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9537 - loss: 0.4713

124/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9581 - loss: 0.4520

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9554 - loss: 0.4990

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9545 - loss: 0.4740

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9544 - loss: 0.5342

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9535 - loss: 0.5636

201/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9552 - loss: 0.5308

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9557 - loss: 0.5169 - val_acc: 0.8872 - val_loss: 0.3897

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 1.0000 - loss: 1.7302e-06

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9500 - loss: 0.5968

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9625 - loss: 0.3694

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9617 - loss: 0.3087

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9619 - loss: 0.5156

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9570 - loss: 0.6683

 94/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9553 - loss: 0.5798

110/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.5199

126/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9651 - loss: 0.4540

142/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9620 - loss: 0.4651

158/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9658 - loss: 0.4188

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.5104

191/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9581 - loss: 0.5494

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9604 - loss: 0.5252

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9605 - loss: 0.5210 - val_acc: 0.9774 - val_loss: 0.2582

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 1.0000 - loss: 5.0323e-08

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9375 - loss: 0.5174

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9613 - loss: 0.3412

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9617 - loss: 0.2760

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9619 - loss: 0.2598

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9570 - loss: 0.2559

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.2213

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9640 - loss: 0.2135

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9669 - loss: 0.1934

142/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9676 - loss: 0.2103

159/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9698 - loss: 0.1985

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9634 - loss: 0.2550

191/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9623 - loss: 0.3080

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9644 - loss: 0.3089

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9642 - loss: 0.3182 - val_acc: 0.9774 - val_loss: 0.5591

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 1.0000 - loss: 2.6004e-12

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9529 - loss: 0.3766

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9636 - loss: 0.2459

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9673 - loss: 0.2002

 65/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9662 - loss: 0.2134

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9634 - loss: 0.2108

 98/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9551 - loss: 0.2629

114/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9596 - loss: 0.2794

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9631 - loss: 0.2839

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9616 - loss: 0.3377

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9617 - loss: 0.3276

178/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9596 - loss: 0.4575

193/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9585 - loss: 0.4277

209/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9608 - loss: 0.4143

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9605 - loss: 0.4179 - val_acc: 0.9774 - val_loss: 0.4508

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 1.0000 - loss: 2.4748e-09

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9250 - loss: 0.3902

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9500 - loss: 0.3820

 48/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9625 - loss: 0.2608

 64/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9656 - loss: 0.2505

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9625 - loss: 0.2782

 96/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9646 - loss: 0.2506

112/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9679 - loss: 0.2457

128/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9703 - loss: 0.2277

144/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9681 - loss: 0.2517

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9712 - loss: 0.2273

177/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9638 - loss: 0.3145

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9649 - loss: 0.3272

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9667 - loss: 0.3146

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9661 - loss: 0.3129 - val_acc: 0.8120 - val_loss: 0.6202

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 1.0000 - loss: 4.4233e-08

 18/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9444 - loss: 0.3319

 34/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9588 - loss: 0.3005

 50/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.2488

 66/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9606 - loss: 0.2507

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9561 - loss: 0.2467

 99/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9495 - loss: 0.2930

114/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9544 - loss: 0.3090

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9585 - loss: 0.3047

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9548 - loss: 0.3322

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9593 - loss: 0.2996

178/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9506 - loss: 0.3872

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9536 - loss: 0.3865

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9558 - loss: 0.3920

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9557 - loss: 0.4056 - val_acc: 0.9774 - val_loss: 0.5821

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 7s 174ms/step

32/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[819  30]
 [  5 474]]
              precision    recall  f1-score   support

         0.0       0.99      0.96      0.98       849
         1.0       0.94      0.99      0.96       479

    accuracy                           0.97      1328
   macro avg       0.97      0.98      0.97      1328
weighted avg       0.97      0.97      0.97      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), return_sequences=True, activation='relu'))
                                    # note that the output when
                                    # return_sequences=True makes the output [n_steps, features]
                                    # where rows = n_steps (10!) and features = hidden size (30!)
model.add(SimpleRNN(30)) # output is a simple vector [1,30] that goes into a dense layer
                          # NO RETURN_SEQUENCES!!!
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 10, 30)         │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,941 (11.49 KB)

 Trainable params: 2,941 (11.49 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7:56 2s/step - acc: 0.8000 - loss: 0.6905

 18/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8111 - loss: 0.5415

 34/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8118 - loss: 0.5118

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7959 - loss: 0.5138

 64/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8062 - loss: 0.4745

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8025 - loss: 0.4523

 94/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8277 - loss: 0.4270

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8467 - loss: 0.4071

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8617 - loss: 0.3940

133/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8707 - loss: 0.3769

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8644 - loss: 0.3690

159/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8591 - loss: 0.3604

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8651 - loss: 0.3461

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8692 - loss: 0.3400

197/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8761 - loss: 0.3325

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8829 - loss: 0.3243

213/213 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - acc: 0.8832 - loss: 0.3243 - val_acc: 0.9774 - val_loss: 0.4794

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 1.0000 - loss: 0.1601

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9600 - loss: 0.1983

 29/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9586 - loss: 0.1829

 43/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9674 - loss: 0.1759

 57/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9684 - loss: 0.1769

 71/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9718 - loss: 0.1788

 84/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9667 - loss: 0.1838

 97/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9691 - loss: 0.1788

110/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9709 - loss: 0.1767

123/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9740 - loss: 0.1728

137/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9708 - loss: 0.1721

150/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9693 - loss: 0.1708

164/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9720 - loss: 0.1668

177/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9695 - loss: 0.1667

190/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9695 - loss: 0.1668

204/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9706 - loss: 0.1635

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9708 - loss: 0.1629 - val_acc: 0.9774 - val_loss: 0.2995

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 1.0000 - loss: 0.0859

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9467 - loss: 0.1470

 29/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9655 - loss: 0.1257

 42/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1182

 55/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9709 - loss: 0.1230

 68/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9735 - loss: 0.1222

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9728 - loss: 0.1245

 94/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9723 - loss: 0.1248

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9757 - loss: 0.1190

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9767 - loss: 0.1175

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.1176

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1223

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9737 - loss: 0.1194

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9708 - loss: 0.1225

183/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9716 - loss: 0.1216

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9724 - loss: 0.1209

209/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9732 - loss: 0.1193

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9727 - loss: 0.1206 - val_acc: 0.9774 - val_loss: 0.2328

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - acc: 1.0000 - loss: 0.0645

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9600 - loss: 0.1241

 28/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1077

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9756 - loss: 0.1018

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9741 - loss: 0.1060

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9761 - loss: 0.1040

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9728 - loss: 0.1087

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9726 - loss: 0.1091

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.1029

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9769 - loss: 0.1017

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.1043

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1097

159/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9736 - loss: 0.1069

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9708 - loss: 0.1105

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9719 - loss: 0.1093

198/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9727 - loss: 0.1081

211/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9735 - loss: 0.1072

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9727 - loss: 0.1088 - val_acc: 0.9774 - val_loss: 0.2122

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 1.0000 - loss: 0.0530

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1074

 27/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9704 - loss: 0.1042

 40/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.0956

 53/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9736 - loss: 0.0993

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9761 - loss: 0.0960

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9725 - loss: 0.1023

 94/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9723 - loss: 0.1023

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.0954

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9770 - loss: 0.0935

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.0971

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9712 - loss: 0.1041

159/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9610 - loss: 0.1332

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9591 - loss: 0.1566

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9587 - loss: 0.1690

197/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9604 - loss: 0.1742

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9590 - loss: 0.1801

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9576 - loss: 0.1829 - val_acc: 0.6617 - val_loss: 0.7567

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 1.0000 - loss: 0.2314

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9333 - loss: 0.2658

 28/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9429 - loss: 0.2429

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9463 - loss: 0.2382

 55/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9382 - loss: 0.2387

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9420 - loss: 0.2365

 83/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9349 - loss: 0.2394

 97/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9423 - loss: 0.2298

110/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9455 - loss: 0.2253

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9508 - loss: 0.2197

135/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9496 - loss: 0.2160

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9497 - loss: 0.2135

159/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9522 - loss: 0.2116

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9512 - loss: 0.2086

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9514 - loss: 0.2083

199/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9538 - loss: 0.2056

213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9548 - loss: 0.2056

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9548 - loss: 0.2056 - val_acc: 0.9774 - val_loss: 0.3664

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 1.0000 - loss: 0.1283

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1704

 27/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9704 - loss: 0.1603

 40/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.1529

 53/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9736 - loss: 0.1565

 65/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9754 - loss: 0.1531

 78/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9718 - loss: 0.1587

 92/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9717 - loss: 0.1571

105/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9752 - loss: 0.1523

118/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9763 - loss: 0.1500

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9773 - loss: 0.1456

145/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9738 - loss: 0.1483

158/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.1459

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.1463

186/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9731 - loss: 0.1478

200/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.1453

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9746 - loss: 0.1459 - val_acc: 0.9774 - val_loss: 0.2837

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 1.0000 - loss: 0.0890

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1364

 28/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1263

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9756 - loss: 0.1210

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9741 - loss: 0.1251

 68/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9765 - loss: 0.1231

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9732 - loss: 0.1264

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9726 - loss: 0.1271

109/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9743 - loss: 0.1235

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9770 - loss: 0.1193

135/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9748 - loss: 0.1207

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9743 - loss: 0.1211

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9764 - loss: 0.1187

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.1218

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9739 - loss: 0.1219

197/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.1210

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9752 - loss: 0.1202

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9746 - loss: 0.1216 - val_acc: 0.9774 - val_loss: 0.2434

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 1.0000 - loss: 0.0688

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1199

 28/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1097

 42/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9762 - loss: 0.1027

 55/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9745 - loss: 0.1075

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9768 - loss: 0.1057

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9725 - loss: 0.1124

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9720 - loss: 0.1134

106/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9755 - loss: 0.1074

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9765 - loss: 0.1059

133/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.1049

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9740 - loss: 0.1080

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9762 - loss: 0.1052

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9734 - loss: 0.1084

187/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.1099

200/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.1075

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9746 - loss: 0.1086 - val_acc: 0.9774 - val_loss: 0.2196

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - acc: 1.0000 - loss: 0.0566

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1106

 28/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1014

 42/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9762 - loss: 0.0940

 56/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.0975

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9768 - loss: 0.0967

 83/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9687 - loss: 0.1112

 96/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9729 - loss: 0.1033

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.0979

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9769 - loss: 0.0968

135/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9748 - loss: 0.0989

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9743 - loss: 0.1001

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9764 - loss: 0.0971

174/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9736 - loss: 0.1011

187/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.1029

200/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.1004

213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.1011

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9746 - loss: 0.1011 - val_acc: 0.9774 - val_loss: 0.1920

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 0.0492

 14/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.1056

 27/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9704 - loss: 0.1060

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9756 - loss: 0.0943

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9741 - loss: 0.0966

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9761 - loss: 0.0937

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9725 - loss: 0.1019

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9720 - loss: 0.1036

106/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9755 - loss: 0.0957

118/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9763 - loss: 0.0923

131/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9771 - loss: 0.0898

144/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9736 - loss: 0.0993

158/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9759 - loss: 0.0940

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9733 - loss: 0.0987

186/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9731 - loss: 0.0997

200/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9750 - loss: 0.0956

213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9746 - loss: 0.0968

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9746 - loss: 0.0968 - val_acc: 0.9774 - val_loss: 0.1533

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 10s 250ms/step

28/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

[[0.628398  ]
 [0.628398  ]
 [0.628398  ]
 ...
 [0.58088505]
 [0.58088505]
 [0.58088505]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[827  22]
 [ 32 447]]
              precision    recall  f1-score   support

         0.0       0.96      0.97      0.97       849
         1.0       0.95      0.93      0.94       479

    accuracy                           0.96      1328
   macro avg       0.96      0.95      0.96      1328
weighted avg       0.96      0.96      0.96      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [25]:
from keras.models import load_model

model.save('Multivariate_Occupancy_RNN.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Multivariate_Occupancy_RNN.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 10, 30)         │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,825 (34.48 KB)

 Trainable params: 2,941 (11.49 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,884 (22.99 KB)

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [26]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Occupancy'].shift(1)
df.head()

,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy,Baseline
140,23.7000,26.272,585.200000,749.200000,0.004764,1,NaN
141,23.7180,26.290,578.400000,760.400000,0.004773,1,1.0
142,23.7300,26.230,572.666667,769.666667,0.004765,1,1.0
143,23.7225,26.125,493.750000,774.750000,0.004744,1,1.0
144,23.7540,26.200,488.600000,779.000000,0.004767,1,1.0

In [27]:
y_test_baseline = df['Baseline']
# just extract rows corresponding to y_test
y_test_baseline = y_test_baseline.tail(y_test.shape[0])
# verify shape
print(y_test.shape)
print(y_test_baseline.shape) # good!

(1328,)
(1328,)

In [28]:
# see how it does!
pred = y_test_baseline # the pred

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

[[842   7]
 [  7 472]]
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       849
         1.0       0.99      0.99      0.99       479

    accuracy                           0.99      1328
   macro avg       0.99      0.99      0.99      1328
weighted avg       0.99      0.99      0.99      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\3878943032.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [29]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_39096\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
# be careful of the baseline model
# and make sure you choose an appropriate measure
# for the problem you are trying to solve...