<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN_AdvancedTopics.ipynb)

# Multivariate Example (Advanced Topics)
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental data - let's see if Conv1D and MaxPooling1D can make an even better prediction (ConvLSTM).

**Common errors:** forgetting an activation function, not specifying the input shape (or mixing up the order!), not returning sequences when two layers (or accidentally return_sequences=True when only one layer!)

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from LuisM78’s GitHub repository:
# url = 'https://raw.githubusercontent.com/LuisM78/Occupancy-detection-data/master/datatest.txt'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/datatest.txt"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 2665 entries, 140 to 2804
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2665 non-null   str
 1   Temperature    2665 non-null   float64
 2   Humidity       2665 non-null   float64
 3   Light          2665 non-null   float64
 4   CO2            2665 non-null   float64
 5   HumidityRatio  2665 non-null   float64
 6   Occupancy      2665 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 195.3 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.7000,26.272,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.7180,26.290,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.7300,26.230,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.7225,26.125,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.7540,26.200,488.600000,779.000000,0.004767,1
145,2015-02-02 14:23:59,23.7600,26.260,568.666667,790.000000,0.004779,1
146,2015-02-02 14:25:00,23.7300,26.290,536.333333,798.000000,0.004776,1
147,2015-02-02 14:25:59,23.7540,26.290,509.000000,797.000000,0.004783,1
148,2015-02-02 14:26:59,23.7540,26.350,476.000000,803.200000,0.004794,1
149,2015-02-02 14:28:00,23.7360,26.390,510.000000,809.000000,0.004796,1
150,2015-02-02 14:29:00,23.7450,26.445,481.500000,815.250000,0.004809,1
151,2015-02-02 14:30:00,23.7000,26.560,481.800000,824.000000,0.004817,1
152,2015-02-02 14:31:00,23.7000,26.600,475.250000,832.000000,0.004824,1
153,2015-02-02 14:31:59,23.7000,26.700,469.000000,845.333333,0.004842,1
154,2015-02-02 14:32:59,23.7000,26.774,464.000000,852.400000,0.004856,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    1693
1     972
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(2665, 6)

     Temperature  Humidity       Light         CO2  HumidityRatio  Occupancy
140      23.7000    26.272  585.200000  749.200000       0.004764          1
141      23.7180    26.290  578.400000  760.400000       0.004773          1
142      23.7300    26.230  572.666667  769.666667       0.004765          1
143      23.7225    26.125  493.750000  774.750000       0.004744          1
144      23.7540    26.200  488.600000  779.000000       0.004767          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 50
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=50)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(2616, 50, 5)
(2616,)

In [11]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [12]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(2616, 50, 5) (1308, 50, 5) (1308, 50, 5)
(2616,) (1308,) (1308,)

# RNN one layer model (with Conv1D and pooling!)
With Conv1D and MaxPooling1D... don't forget that input shape needs to go in the first layer!

In [13]:
n_steps = X_train.shape[1] # lookback
n_features = X_train.shape[2] # columns

print(n_steps, n_features)

50 5

In [14]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(SimpleRNN(30, activation='relu', recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,890 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 6:59 2s/step - acc: 0.4000 - loss: 15.7661

 13/210 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.6000 - loss: 27.7861

 25/210 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.7120 - loss: 19.2174

 36/210 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.7667 - loss: 14.2077

 47/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7915 - loss: 12.1776

 58/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8172 - loss: 10.4992

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8400 - loss: 8.8249

 82/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8585 - loss: 8.0256

 93/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8667 - loss: 7.5700

104/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8750 - loss: 7.0319

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8852 - loss: 6.4372

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8921 - loss: 5.9114

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9000 - loss: 5.4767

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9000 - loss: 5.5093

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9045 - loss: 5.2680

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9036 - loss: 5.2282

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9040 - loss: 5.0631

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9096 - loss: 4.7669

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9126 - loss: 4.5092

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9148 - loss: 4.4828

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - acc: 0.9149 - loss: 4.4785 - val_acc: 0.9771 - val_loss: 2.0658

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 1.0000 - loss: 5.0065e-25

 12/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 3.2812

 23/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9391 - loss: 2.4111

 34/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9471 - loss: 2.2752

 44/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9500 - loss: 1.8209

 53/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9434 - loss: 2.0988

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9531 - loss: 1.7407

 75/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9573 - loss: 1.6373

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9576 - loss: 1.5320

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9542 - loss: 1.4599

106/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9528 - loss: 1.4374

117/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9538 - loss: 1.3697

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9556 - loss: 1.2927

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9588 - loss: 1.1976

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9592 - loss: 1.2443

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9582 - loss: 1.2713

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9548 - loss: 1.2816

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9506 - loss: 1.2957

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9534 - loss: 1.2203

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9558 - loss: 1.1590

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9560 - loss: 1.2123

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9560 - loss: 1.2112 - val_acc: 0.9771 - val_loss: 0.6176

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.8000 - loss: 0.3988

 11/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.8727 - loss: 2.0783

 22/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9273 - loss: 1.0818

 32/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9375 - loss: 1.4000

 43/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9442 - loss: 1.0641

 53/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9434 - loss: 1.3699

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9375 - loss: 1.2981

 75/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9440 - loss: 1.3306

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9435 - loss: 1.4153

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9453 - loss: 1.4179

104/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9462 - loss: 1.5347

114/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9491 - loss: 1.4580

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9536 - loss: 1.3297

128/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9547 - loss: 1.2985

139/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9583 - loss: 1.1958

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9587 - loss: 1.2100

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9550 - loss: 1.2474

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9497 - loss: 1.2681

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9484 - loss: 1.2124

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9513 - loss: 1.1433

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9520 - loss: 1.1680

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9532 - loss: 1.1390 - val_acc: 0.9771 - val_loss: 0.3982

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 1.0000 - loss: 9.6679e-13

 11/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.8364 - loss: 1.8175

 22/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9091 - loss: 0.9824

 33/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9212 - loss: 1.1947

 44/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9409 - loss: 0.8960

 55/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9382 - loss: 1.1014

 66/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9394 - loss: 1.0005

 76/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9447 - loss: 1.0225

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9471 - loss: 1.0365

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9429 - loss: 1.0316

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9463 - loss: 0.9412

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9479 - loss: 0.9041

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9523 - loss: 0.8277

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9560 - loss: 0.7631

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9526 - loss: 0.8619

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9485 - loss: 0.8674

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9404 - loss: 0.9145

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9425 - loss: 0.8744

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9455 - loss: 0.8286

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9483 - loss: 0.7874

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9484 - loss: 0.8043 - val_acc: 0.9771 - val_loss: 0.3384

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 3.2861e-08

 12/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8833 - loss: 1.0533

 23/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9304 - loss: 0.5605

 34/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9412 - loss: 0.5200

 45/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9422 - loss: 0.4256

 56/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9393 - loss: 0.5286

 66/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9455 - loss: 0.4606

 77/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9506 - loss: 0.4163

 88/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9523 - loss: 0.4232

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9469 - loss: 0.4642

109/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9505 - loss: 0.4196

120/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9533 - loss: 0.4156

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9569 - loss: 0.3837

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9600 - loss: 0.3563

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9589 - loss: 0.3988

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9580 - loss: 0.3824

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9523 - loss: 0.4011

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9519 - loss: 0.3819

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9546 - loss: 0.3602

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9549 - loss: 0.3814

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9560 - loss: 0.3719 - val_acc: 0.9771 - val_loss: 0.2537

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 1.0000 - loss: 1.1833e-07

 12/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8833 - loss: 0.6918

 22/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9273 - loss: 0.4296

 33/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9394 - loss: 0.4777

 43/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9488 - loss: 0.3828

 54/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9444 - loss: 0.4084

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9438 - loss: 0.3750

 74/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9514 - loss: 0.3244

 84/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9524 - loss: 0.3750

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9495 - loss: 0.3936

106/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9509 - loss: 0.3755

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9534 - loss: 0.3615

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9556 - loss: 0.3340

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9574 - loss: 0.3109

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9578 - loss: 0.3317

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9580 - loss: 0.3271

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9560 - loss: 0.3362

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9531 - loss: 0.3449

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9545 - loss: 0.3315

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9556 - loss: 0.3177

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9558 - loss: 0.3612

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9560 - loss: 0.3591 - val_acc: 0.9771 - val_loss: 0.2363

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 1.0000 - loss: 1.0617e-07

 11/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9273 - loss: 0.5702

 22/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9545 - loss: 0.2999

 33/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9576 - loss: 0.3180

 44/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9545 - loss: 0.2756

 54/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9519 - loss: 0.3275

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9531 - loss: 0.2979

 74/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9568 - loss: 0.2609

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9576 - loss: 0.2886

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9579 - loss: 0.2962

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9524 - loss: 0.2827

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9534 - loss: 0.2752

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9571 - loss: 0.2534

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9606 - loss: 0.2331

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9608 - loss: 0.2484

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9560 - loss: 0.2567

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9527 - loss: 0.2605

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9508 - loss: 0.2700

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9492 - loss: 0.2667

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9520 - loss: 0.2522

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9522 - loss: 0.2629 - val_acc: 0.9771 - val_loss: 0.2362

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 0.0056

 12/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9167 - loss: 0.5346

 23/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9304 - loss: 0.3490

 33/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.3629

 43/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9395 - loss: 0.2981

 54/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9370 - loss: 0.3627

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9469 - loss: 0.3068

 75/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9493 - loss: 0.2707

 86/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9558 - loss: 0.2386

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9521 - loss: 0.2342

106/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9509 - loss: 0.2220

117/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9538 - loss: 0.2171

128/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9578 - loss: 0.1985

139/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9612 - loss: 0.1828

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9611 - loss: 0.1880

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9575 - loss: 0.1975

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9518 - loss: 0.2131

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9514 - loss: 0.2055

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9539 - loss: 0.1950

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9564 - loss: 0.1845

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9551 - loss: 0.1991 - val_acc: 0.9771 - val_loss: 0.1345

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 1.0000 - loss: 0.0013

 11/210 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9273 - loss: 0.2052

 22/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1163

 33/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1395

 43/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9721 - loss: 0.1174

 53/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9660 - loss: 0.1440

 62/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.1310

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9694 - loss: 0.1183

 82/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.1213

 93/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9699 - loss: 0.1369

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.1323

113/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9681 - loss: 0.1290

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.1185

134/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9731 - loss: 0.1091

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.1017

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9716 - loss: 0.1165

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - loss: 0.1206

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9623 - loss: 0.1341

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9645 - loss: 0.1270

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9655 - loss: 0.1224

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9654 - loss: 0.1344

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9656 - loss: 0.1337 - val_acc: 0.9771 - val_loss: 0.1932

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 1.0000 - loss: 3.7989e-05

 12/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.2514

 23/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9565 - loss: 0.1491

 34/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9588 - loss: 0.1245

 44/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9682 - loss: 0.1000

 55/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1286

 65/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9662 - loss: 0.1133

 76/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9684 - loss: 0.1096

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.1008

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.1041

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0996

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9722 - loss: 0.0966

124/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9742 - loss: 0.0907

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.0847

143/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9776 - loss: 0.0794

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9763 - loss: 0.0836

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9739 - loss: 0.0929

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9684 - loss: 0.1015

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9691 - loss: 0.0999

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.0951

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9721 - loss: 0.0907

210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9713 - loss: 0.1032 - val_acc: 0.9771 - val_loss: 0.1132

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 1.0000 - loss: 0.0054

 11/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9455 - loss: 0.1618

 21/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9619 - loss: 0.1031

 31/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9613 - loss: 0.1057

 41/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.0831

 51/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9686 - loss: 0.0998

 62/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.0990

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9694 - loss: 0.0902

 81/210 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9704 - loss: 0.0876

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9694 - loss: 0.0932

 89/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9685 - loss: 0.0923

 92/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9674 - loss: 0.0940

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.0951

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9689 - loss: 0.0917

109/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9670 - loss: 0.0943

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9658 - loss: 0.0978

114/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9667 - loss: 0.0959

118/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9678 - loss: 0.0927

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9691 - loss: 0.0897

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9705 - loss: 0.0856

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9719 - loss: 0.0820

142/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9732 - loss: 0.0781

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9732 - loss: 0.0811

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9709 - loss: 0.0905

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9687 - loss: 0.0936

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9632 - loss: 0.1014

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9648 - loss: 0.0976

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9661 - loss: 0.0949

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9675 - loss: 0.0919

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9667 - loss: 0.0973

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - acc: 0.9675 - loss: 0.0951 - val_acc: 0.9771 - val_loss: 0.1118

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [15]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

 1/41 ━━━━━━━━━━━━━━━━━━━━ 11s 297ms/step

23/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(1308, 1), dtype=float32)

In [16]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

[[824  25]
 [  2 457]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98       849
         1.0       0.95      1.00      0.97       459

    accuracy                           0.98      1308
   macro avg       0.97      0.98      0.98      1308
weighted avg       0.98      0.98      0.98      1308

In [17]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\774347038.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [18]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step

28/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[824  25]
 [  2 457]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98       849
         1.0       0.95      1.00      0.97       459

    accuracy                           0.98      1308
   macro avg       0.97      0.98      0.98      1308
weighted avg       0.98      0.98      0.98      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [19]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(SimpleRNN(30, return_sequences=True, recurrent_dropout=0.2))) # don't forget to return_sequences!
model.add(Bidirectional(SimpleRNN(30, recurrent_dropout=0.2)))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 60)         │         3,780 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 60)             │         5,460 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            61 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,813 (38.33 KB)

 Trainable params: 9,813 (38.33 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 17:12 5s/step - acc: 0.6000 - loss: 0.5290

  6/210 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - acc: 0.6333 - loss: 0.5210

 10/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.7200 - loss: 0.4609

 14/210 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - acc: 0.7429 - loss: 0.4399

 18/210 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - acc: 0.7222 - loss: 0.4822

 22/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.7636 - loss: 0.4393

 26/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.7846 - loss: 0.4150

 30/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8000 - loss: 0.3977

 33/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8182 - loss: 0.3708

 37/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8324 - loss: 0.3490

 41/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8439 - loss: 0.3284

 45/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8578 - loss: 0.3073

 49/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8653 - loss: 0.2950

 53/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.8642 - loss: 0.2987

 57/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.8737 - loss: 0.2849

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.8820 - loss: 0.2705

 65/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.8892 - loss: 0.2578

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.8957 - loss: 0.2457

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9014 - loss: 0.2354

 77/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9039 - loss: 0.2331

 81/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9037 - loss: 0.2270

 85/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9059 - loss: 0.2218

 89/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9101 - loss: 0.2144

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9097 - loss: 0.2141

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9113 - loss: 0.2097

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9140 - loss: 0.2036

103/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9146 - loss: 0.2012

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9151 - loss: 0.1987

110/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9164 - loss: 0.1985

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9168 - loss: 0.1964

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9197 - loss: 0.1907

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9223 - loss: 0.1860

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9248 - loss: 0.1819

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9271 - loss: 0.1777

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9293 - loss: 0.1733

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9314 - loss: 0.1694

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9333 - loss: 0.1655

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9338 - loss: 0.1648

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9324 - loss: 0.1686

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9329 - loss: 0.1683

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9333 - loss: 0.1686

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9333 - loss: 0.1702

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9337 - loss: 0.1719

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9341 - loss: 0.1739

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9318 - loss: 0.1788

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9322 - loss: 0.1782

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9337 - loss: 0.1744

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9352 - loss: 0.1715

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9362 - loss: 0.1692

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9365 - loss: 0.1675

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9378 - loss: 0.1664

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9388 - loss: 0.1652

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9400 - loss: 0.1630

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9392 - loss: 0.1659

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9404 - loss: 0.1633

210/210 ━━━━━━━━━━━━━━━━━━━━ 9s 21ms/step - acc: 0.9407 - loss: 0.1626 - val_acc: 0.9771 - val_loss: 0.1133

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - acc: 1.0000 - loss: 0.0167

  5/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9600 - loss: 0.0625

  9/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9333 - loss: 0.2234

 13/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9538 - loss: 0.1641

 17/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9529 - loss: 0.1831

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9619 - loss: 0.1562

 25/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9520 - loss: 0.1912

 29/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9517 - loss: 0.1769

 33/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9576 - loss: 0.1587

 37/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9622 - loss: 0.1471

 41/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9659 - loss: 0.1349

 45/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9689 - loss: 0.1257

 49/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9673 - loss: 0.1252

 53/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9623 - loss: 0.1393

 57/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9649 - loss: 0.1312

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9672 - loss: 0.1243

 65/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9692 - loss: 0.1182

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9710 - loss: 0.1122

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9726 - loss: 0.1083

 77/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9714 - loss: 0.1093

 81/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9704 - loss: 0.1092

 85/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9694 - loss: 0.1131

 89/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9708 - loss: 0.1104

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9699 - loss: 0.1143

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9691 - loss: 0.1165

101/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9703 - loss: 0.1132

105/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9695 - loss: 0.1130

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9706 - loss: 0.1110

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9699 - loss: 0.1126

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9709 - loss: 0.1093

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9719 - loss: 0.1070

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9728 - loss: 0.1046

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9736 - loss: 0.1020

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9744 - loss: 0.0997

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9752 - loss: 0.0977

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9759 - loss: 0.0955

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9752 - loss: 0.0974

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9745 - loss: 0.1000

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9725 - loss: 0.1016

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9720 - loss: 0.1035

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9702 - loss: 0.1084

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9697 - loss: 0.1093

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9680 - loss: 0.1119

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9653 - loss: 0.1166

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9661 - loss: 0.1154

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9669 - loss: 0.1132

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9676 - loss: 0.1117

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9683 - loss: 0.1110

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9668 - loss: 0.1124

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9665 - loss: 0.1125

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9672 - loss: 0.1110

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9659 - loss: 0.1140

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9665 - loss: 0.1124

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9665 - loss: 0.1123 - val_acc: 0.9771 - val_loss: 0.1262

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 45ms/step - acc: 1.0000 - loss: 0.0150

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9600 - loss: 0.1176

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9333 - loss: 0.2124

 13/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9538 - loss: 0.1637

 17/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9529 - loss: 0.1818

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9619 - loss: 0.1550

 25/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9520 - loss: 0.1789

 29/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9517 - loss: 0.1779

 32/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9563 - loss: 0.1635

 35/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9600 - loss: 0.1546

 39/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9641 - loss: 0.1419

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9674 - loss: 0.1329

 47/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9660 - loss: 0.1312

 51/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9647 - loss: 0.1343

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9636 - loss: 0.1361

 59/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9661 - loss: 0.1279

 63/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9683 - loss: 0.1212

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9701 - loss: 0.1158

 71/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9718 - loss: 0.1107

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9707 - loss: 0.1146

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9718 - loss: 0.1113

 82/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9707 - loss: 0.1098

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9698 - loss: 0.1123

 90/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9667 - loss: 0.1195

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9681 - loss: 0.1155

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9673 - loss: 0.1140

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9686 - loss: 0.1101

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9698 - loss: 0.1104

110/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9691 - loss: 0.1127

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9702 - loss: 0.1105

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9712 - loss: 0.1075

122/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9721 - loss: 0.1050

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9730 - loss: 0.1023

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9738 - loss: 0.1001

134/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9746 - loss: 0.0981

138/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9754 - loss: 0.0960

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9761 - loss: 0.0939

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9752 - loss: 0.0988

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9745 - loss: 0.1001

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9725 - loss: 0.1030

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9720 - loss: 0.1039

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9700 - loss: 0.1074

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9695 - loss: 0.1059

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9677 - loss: 0.1093

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9649 - loss: 0.1148

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9644 - loss: 0.1168

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9652 - loss: 0.1144

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9657 - loss: 0.1127

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9665 - loss: 0.1118

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9672 - loss: 0.1105

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9679 - loss: 0.1108

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9685 - loss: 0.1098

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9692 - loss: 0.1081

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9668 - loss: 0.1122

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9673 - loss: 0.1115

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9675 - loss: 0.1110 - val_acc: 0.9771 - val_loss: 0.1465

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - acc: 1.0000 - loss: 0.0119

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9600 - loss: 0.0832

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9333 - loss: 0.1730

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9538 - loss: 0.1262

 17/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9529 - loss: 0.1630

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9619 - loss: 0.1397

 25/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9520 - loss: 0.1514

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9500 - loss: 0.1607

 31/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9548 - loss: 0.1479

 34/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9588 - loss: 0.1359

 37/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9622 - loss: 0.1280

 41/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9659 - loss: 0.1187

 45/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9689 - loss: 0.1113

 49/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9673 - loss: 0.1175

 53/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9623 - loss: 0.1336

 56/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9643 - loss: 0.1283

 59/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9661 - loss: 0.1227

 62/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9677 - loss: 0.1175

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9697 - loss: 0.1121

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9714 - loss: 0.1070

 74/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9730 - loss: 0.1021

 77/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9714 - loss: 0.1035

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9728 - loss: 0.1008

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9718 - loss: 0.1019

 88/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9727 - loss: 0.0992

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.1011

 95/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9726 - loss: 0.0982

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9714 - loss: 0.1005

101/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9723 - loss: 0.0987

105/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9733 - loss: 0.0982

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9743 - loss: 0.0965

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9735 - loss: 0.0972

116/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9741 - loss: 0.0948

120/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9750 - loss: 0.0932

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9758 - loss: 0.0912

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9766 - loss: 0.0891

131/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9771 - loss: 0.0878

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9778 - loss: 0.0867

138/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9783 - loss: 0.0854

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9789 - loss: 0.0836

146/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9767 - loss: 0.0899

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9760 - loss: 0.0913

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9753 - loss: 0.0907

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9734 - loss: 0.0970

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9727 - loss: 0.0984

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9721 - loss: 0.0982

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9716 - loss: 0.0996

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9676 - loss: 0.1058

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9672 - loss: 0.1056

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9678 - loss: 0.1043

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9674 - loss: 0.1036

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9679 - loss: 0.1020

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9686 - loss: 0.1024

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9692 - loss: 0.1015

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9698 - loss: 0.0998

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9704 - loss: 0.0982

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9691 - loss: 0.1030

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9694 - loss: 0.1024

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - acc: 0.9694 - loss: 0.1024 - val_acc: 0.9771 - val_loss: 0.1242

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - acc: 1.0000 - loss: 0.0086

  5/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9600 - loss: 0.1154

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9333 - loss: 0.1824

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9538 - loss: 0.1399

 17/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9529 - loss: 0.1632

 20/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9600 - loss: 0.1456

 24/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9583 - loss: 0.1377

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9500 - loss: 0.1665

 32/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9563 - loss: 0.1505

 36/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9611 - loss: 0.1370

 40/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9650 - loss: 0.1259

 44/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9682 - loss: 0.1180

 47/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9660 - loss: 0.1231

 50/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9640 - loss: 0.1282

 53/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9623 - loss: 0.1310

 57/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9649 - loss: 0.1235

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9672 - loss: 0.1170

 65/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9692 - loss: 0.1111

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9710 - loss: 0.1054

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9726 - loss: 0.1015

 77/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9714 - loss: 0.1043

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9728 - loss: 0.1010

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9738 - loss: 0.0978

 87/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9724 - loss: 0.1025

 90/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9689 - loss: 0.1087

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9702 - loss: 0.1053

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9694 - loss: 0.1059

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9706 - loss: 0.1026

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.1003

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9725 - loss: 0.0982

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.1012

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9726 - loss: 0.0982

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9736 - loss: 0.0961

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9742 - loss: 0.0942

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9750 - loss: 0.0918

131/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9756 - loss: 0.0901

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9763 - loss: 0.0886

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9770 - loss: 0.0867

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9776 - loss: 0.0848

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9755 - loss: 0.0881

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9735 - loss: 0.0918

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9742 - loss: 0.0899

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9722 - loss: 0.0948

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.0969

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9720 - loss: 0.0954

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.0974

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9674 - loss: 0.1050

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9682 - loss: 0.1039

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9689 - loss: 0.1021

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9696 - loss: 0.1007

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9702 - loss: 0.0993

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9708 - loss: 0.0992

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.0986

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9719 - loss: 0.0976

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9723 - loss: 0.0968

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9707 - loss: 0.0995

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9713 - loss: 0.0983

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - acc: 0.9713 - loss: 0.0982 - val_acc: 0.9771 - val_loss: 0.1372

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - acc: 1.0000 - loss: 0.0345

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9600 - loss: 0.0883

  8/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.9500 - loss: 0.1276

 11/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9455 - loss: 0.1723

 14/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9571 - loss: 0.1363

 17/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9529 - loss: 0.1836

 20/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9600 - loss: 0.1630

 23/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9565 - loss: 0.1592

 26/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9538 - loss: 0.1674

 29/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9517 - loss: 0.1735

 32/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9563 - loss: 0.1595

 35/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9600 - loss: 0.1481

 38/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9632 - loss: 0.1396

 42/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9667 - loss: 0.1298

 46/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9652 - loss: 0.1331

 50/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9640 - loss: 0.1359

 54/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9630 - loss: 0.1335

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9655 - loss: 0.1253

 62/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9677 - loss: 0.1187

 65/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9692 - loss: 0.1146

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9710 - loss: 0.1087

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9726 - loss: 0.1055

 77/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9714 - loss: 0.1058

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9728 - loss: 0.1016

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9738 - loss: 0.0983

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - acc: 0.9727 - loss: 0.1014

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9696 - loss: 0.1073

 96/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9688 - loss: 0.1051

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9700 - loss: 0.1014

104/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9712 - loss: 0.0989

108/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9722 - loss: 0.0967

111/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9712 - loss: 0.0985

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9719 - loss: 0.0969

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9729 - loss: 0.0938

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9736 - loss: 0.0921

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9744 - loss: 0.0905

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9752 - loss: 0.0884

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9759 - loss: 0.0869

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9766 - loss: 0.0852

140/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9771 - loss: 0.0837

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9778 - loss: 0.0820

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9755 - loss: 0.0885

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9735 - loss: 0.0920

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9742 - loss: 0.0901

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9723 - loss: 0.0961

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9718 - loss: 0.0983

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9701 - loss: 0.1014

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9673 - loss: 0.1066

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9667 - loss: 0.1084

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9672 - loss: 0.1068

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9678 - loss: 0.1054

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9683 - loss: 0.1039

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9690 - loss: 0.1021

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9675 - loss: 0.1030

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9680 - loss: 0.1025

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9687 - loss: 0.1014

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9693 - loss: 0.1001

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9680 - loss: 0.1026

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9684 - loss: 0.1021

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - acc: 0.9685 - loss: 0.1020 - val_acc: 0.9771 - val_loss: 0.1593

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - acc: 1.0000 - loss: 0.0396

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9600 - loss: 0.0951

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9333 - loss: 0.1890

 12/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9500 - loss: 0.1543

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9500 - loss: 0.1705

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9579 - loss: 0.1514

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9545 - loss: 0.1540

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.9520 - loss: 0.1544

 29/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9517 - loss: 0.1553

 33/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9576 - loss: 0.1404

 37/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9622 - loss: 0.1296

 41/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9659 - loss: 0.1195

 44/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9682 - loss: 0.1152

 48/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9667 - loss: 0.1197

 52/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9654 - loss: 0.1245

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9636 - loss: 0.1255

 59/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9661 - loss: 0.1176

 63/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9683 - loss: 0.1109

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9701 - loss: 0.1060

 71/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9718 - loss: 0.1019

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9707 - loss: 0.1047

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9722 - loss: 0.0999

 83/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9735 - loss: 0.0956

 87/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9724 - loss: 0.0972

 91/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9692 - loss: 0.1036

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9702 - loss: 0.1006

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9694 - loss: 0.1003

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9706 - loss: 0.0972

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.0947

110/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9709 - loss: 0.0968

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.0952

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9726 - loss: 0.0923

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9736 - loss: 0.0901

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9744 - loss: 0.0879

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9752 - loss: 0.0859

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9759 - loss: 0.0839

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9765 - loss: 0.0833

140/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9771 - loss: 0.0812

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9778 - loss: 0.0800

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9757 - loss: 0.0841

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9737 - loss: 0.0887

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9731 - loss: 0.0905

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9712 - loss: 0.0965

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9720 - loss: 0.0947

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9701 - loss: 0.0966

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9671 - loss: 0.1015

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9667 - loss: 0.1016

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9674 - loss: 0.0995

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9670 - loss: 0.0987

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9677 - loss: 0.0970

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9672 - loss: 0.0970

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9679 - loss: 0.0964

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9685 - loss: 0.0956

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9692 - loss: 0.0944

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9676 - loss: 0.0989

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9683 - loss: 0.0977

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9685 - loss: 0.0971 - val_acc: 0.9771 - val_loss: 0.1492

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 0.0150

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9600 - loss: 0.0778

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9333 - loss: 0.1326

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9538 - loss: 0.0985

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9500 - loss: 0.1517

 20/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9600 - loss: 0.1339

 24/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9583 - loss: 0.1383

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9500 - loss: 0.1510

 32/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9563 - loss: 0.1369

 35/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9600 - loss: 0.1306

 39/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9641 - loss: 0.1188

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9674 - loss: 0.1103

 47/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9660 - loss: 0.1094

 51/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9647 - loss: 0.1123

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9636 - loss: 0.1164

 59/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9661 - loss: 0.1092

 63/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9683 - loss: 0.1037

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9701 - loss: 0.0987

 71/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9718 - loss: 0.0947

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9707 - loss: 0.0989

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9722 - loss: 0.0944

 83/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9735 - loss: 0.0904

 87/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9724 - loss: 0.0960

 91/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9692 - loss: 0.0996

 95/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9705 - loss: 0.0958

 99/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9697 - loss: 0.0999

103/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9709 - loss: 0.0974

107/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9720 - loss: 0.0964

111/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9712 - loss: 0.0979

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9722 - loss: 0.0952

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9731 - loss: 0.0929

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9740 - loss: 0.0913

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9746 - loss: 0.0897

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9754 - loss: 0.0878

134/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9761 - loss: 0.0866

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9766 - loss: 0.0855

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9773 - loss: 0.0836

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9766 - loss: 0.0854

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9758 - loss: 0.0885

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9739 - loss: 0.0909

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9731 - loss: 0.0914

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9723 - loss: 0.0923

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9718 - loss: 0.0931

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9711 - loss: 0.0972

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9682 - loss: 0.1022

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9667 - loss: 0.1059

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9674 - loss: 0.1037

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9670 - loss: 0.1027

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9677 - loss: 0.1008

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9684 - loss: 0.1009

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9691 - loss: 0.1001

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9697 - loss: 0.0990

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9703 - loss: 0.0976

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9689 - loss: 0.1005

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9694 - loss: 0.0997

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9694 - loss: 0.0997 - val_acc: 0.9771 - val_loss: 0.1291

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 1.0000 - loss: 0.0251

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9600 - loss: 0.1064

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9333 - loss: 0.1819

 13/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9538 - loss: 0.1356

 17/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9529 - loss: 0.1355

 20/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9600 - loss: 0.1192

 23/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9565 - loss: 0.1132

 27/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9481 - loss: 0.1325

 31/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9548 - loss: 0.1186

 35/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9600 - loss: 0.1084

 39/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9641 - loss: 0.0994

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9674 - loss: 0.0929

 47/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9660 - loss: 0.1009

 51/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9647 - loss: 0.1028

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9636 - loss: 0.1068

 59/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9661 - loss: 0.1001

 62/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9677 - loss: 0.0959

 65/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9692 - loss: 0.0928

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9710 - loss: 0.0882

 72/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9722 - loss: 0.0862

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9711 - loss: 0.0883

 80/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9725 - loss: 0.0855

 84/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9738 - loss: 0.0819

 88/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9705 - loss: 0.0864

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9674 - loss: 0.0916

 96/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9667 - loss: 0.0931

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9680 - loss: 0.0902

104/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9692 - loss: 0.0885

108/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9704 - loss: 0.0870

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9696 - loss: 0.0886

116/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9707 - loss: 0.0864

120/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.0851

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9726 - loss: 0.0833

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9734 - loss: 0.0812

132/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9742 - loss: 0.0795

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9748 - loss: 0.0783

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9755 - loss: 0.0767

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9762 - loss: 0.0756

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9741 - loss: 0.0808

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9735 - loss: 0.0833

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9740 - loss: 0.0819

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9732 - loss: 0.0848

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.0892

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9709 - loss: 0.0893

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9702 - loss: 0.0892

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9663 - loss: 0.0958

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9670 - loss: 0.0947

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9678 - loss: 0.0928

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9683 - loss: 0.0919

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9690 - loss: 0.0903

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9696 - loss: 0.0902

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9703 - loss: 0.0896

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9709 - loss: 0.0882

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.0872

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9700 - loss: 0.0902

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9704 - loss: 0.0896 - val_acc: 0.9771 - val_loss: 0.1416

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 45ms/step - acc: 1.0000 - loss: 0.0200

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9600 - loss: 0.1078

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9333 - loss: 0.1636

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9538 - loss: 0.1288

 17/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.9529 - loss: 0.1730

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9619 - loss: 0.1450

 25/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9520 - loss: 0.1651

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9500 - loss: 0.1682

 32/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9563 - loss: 0.1497

 36/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9611 - loss: 0.1383

 40/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9650 - loss: 0.1277

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9674 - loss: 0.1234

 46/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9652 - loss: 0.1311

 50/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9640 - loss: 0.1324

 54/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9630 - loss: 0.1369

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9655 - loss: 0.1279

 62/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9677 - loss: 0.1208

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9697 - loss: 0.1145

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9714 - loss: 0.1089

 74/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9730 - loss: 0.1039

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9718 - loss: 0.1068

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9732 - loss: 0.1030

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9721 - loss: 0.1035

 89/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9708 - loss: 0.1040

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9699 - loss: 0.1055

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9691 - loss: 0.1056

101/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9703 - loss: 0.1018

105/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9714 - loss: 0.0998

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9725 - loss: 0.0973

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9717 - loss: 0.0984

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9726 - loss: 0.0954

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9736 - loss: 0.0935

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9744 - loss: 0.0909

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9752 - loss: 0.0894

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9759 - loss: 0.0876

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9766 - loss: 0.0859

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9773 - loss: 0.0840

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9766 - loss: 0.0842

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9758 - loss: 0.0867

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9752 - loss: 0.0898

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9745 - loss: 0.0935

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9727 - loss: 0.0983

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9721 - loss: 0.0999

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9716 - loss: 0.1024

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9688 - loss: 0.1100

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9695 - loss: 0.1088

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9702 - loss: 0.1067

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9708 - loss: 0.1052

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9714 - loss: 0.1039

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9720 - loss: 0.1041

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9726 - loss: 0.1026

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9731 - loss: 0.1010

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9717 - loss: 0.1032

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9722 - loss: 0.1019

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9723 - loss: 0.1018 - val_acc: 0.9771 - val_loss: 0.1518

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - acc: 1.0000 - loss: 0.0286

  5/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 1.0000 - loss: 0.0260

  9/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9556 - loss: 0.1471

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - acc: 0.9692 - loss: 0.1143

 17/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9647 - loss: 0.1502

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9714 - loss: 0.1260

 25/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9600 - loss: 0.1338

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9571 - loss: 0.1361

 32/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9625 - loss: 0.1223

 36/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9667 - loss: 0.1127

 40/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9700 - loss: 0.1051

 44/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9727 - loss: 0.0985

 48/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9708 - loss: 0.1032

 52/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9692 - loss: 0.1087

 56/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9679 - loss: 0.1137

 60/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9700 - loss: 0.1081

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9719 - loss: 0.1032

 68/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9735 - loss: 0.0987

 72/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9750 - loss: 0.0940

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9737 - loss: 0.0967

 80/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9750 - loss: 0.0935

 84/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9762 - loss: 0.0895

 88/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9750 - loss: 0.0933

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9739 - loss: 0.0962

 96/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9729 - loss: 0.0961

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9740 - loss: 0.0929

104/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9750 - loss: 0.0911

108/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9759 - loss: 0.0889

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9750 - loss: 0.0914

116/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9759 - loss: 0.0886

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9765 - loss: 0.0865

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9772 - loss: 0.0843

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9778 - loss: 0.0827

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9783 - loss: 0.0814

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9789 - loss: 0.0799

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9796 - loss: 0.0783

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9801 - loss: 0.0767

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9793 - loss: 0.0783

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9785 - loss: 0.0789

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9778 - loss: 0.0790

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9771 - loss: 0.0817

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9752 - loss: 0.0850

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9745 - loss: 0.0852

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9740 - loss: 0.0873

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9711 - loss: 0.0936

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9718 - loss: 0.0922

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9724 - loss: 0.0903

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9730 - loss: 0.0887

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9735 - loss: 0.0877

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9741 - loss: 0.0881

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9745 - loss: 0.0877

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9749 - loss: 0.0870

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9752 - loss: 0.0862

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9737 - loss: 0.0905

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9740 - loss: 0.0898

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - acc: 0.9742 - loss: 0.0893 - val_acc: 0.9771 - val_loss: 0.1524

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 22s 565ms/step

13/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

25/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

37/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step

[[0.96030676]
 [0.9603065 ]
 [0.9603064 ]
 ...
 [0.9629391 ]
 [0.9629342 ]
 [0.962934  ]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[801  48]
 [  3 456]]
              precision    recall  f1-score   support

         0.0       1.00      0.94      0.97       849
         1.0       0.90      0.99      0.95       459

    accuracy                           0.96      1308
   macro avg       0.95      0.97      0.96      1308
weighted avg       0.96      0.96      0.96      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# define shape
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(LSTM(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 30)             │         7,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,103 (31.65 KB)

 Trainable params: 8,103 (31.65 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7:14 2s/step - acc: 0.0000e+00 - loss: 350.5895

 10/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.3200 - loss: 159.4083

 18/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.3556 - loss: 139.0573

 26/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.3538 - loss: 123.7186

 34/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.4471 - loss: 97.9783

 42/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.5286 - loss: 80.3037

 50/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.5720 - loss: 69.9074

 59/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6271 - loss: 59.4377

 67/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6597 - loss: 54.4293

 74/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.6838 - loss: 50.9023

 82/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7098 - loss: 47.2568

 90/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7267 - loss: 44.3498

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7449 - loss: 41.4724

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7543 - loss: 38.9149

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7607 - loss: 37.0709

120/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7683 - loss: 35.0952

128/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7797 - loss: 33.1821

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7853 - loss: 31.8945

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.7972 - loss: 30.1225

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8039 - loss: 29.0660

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8100 - loss: 27.9437

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8167 - loss: 26.8285

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8194 - loss: 26.1197

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8264 - loss: 25.1151

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8328 - loss: 24.1849

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8396 - loss: 23.2027

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8439 - loss: 22.4457

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - acc: 0.8470 - loss: 21.9950 - val_acc: 0.9771 - val_loss: 2.7365

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 1.0000 - loss: 1.7464e-23

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9333 - loss: 5.7358

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9529 - loss: 3.4510

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9520 - loss: 3.2003

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9576 - loss: 2.8332

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9659 - loss: 2.2804

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9673 - loss: 2.1865

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9643 - loss: 2.3808

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9688 - loss: 2.0832

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9722 - loss: 1.8518

 80/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9700 - loss: 2.0415

 88/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9705 - loss: 1.9946

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 2.2136

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9689 - loss: 2.0631

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9694 - loss: 2.0106

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9714 - loss: 1.8754

127/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9732 - loss: 1.7573

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9748 - loss: 1.6531

143/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9762 - loss: 1.5607

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9733 - loss: 1.8149

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9709 - loss: 1.8749

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9697 - loss: 1.9056

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9651 - loss: 2.1003

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9665 - loss: 2.0182

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9677 - loss: 1.9422

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9689 - loss: 1.8718

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9701 - loss: 1.7973

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9692 - loss: 1.7978

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9694 - loss: 1.7875 - val_acc: 0.9771 - val_loss: 1.6454

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 1.0000 - loss: 4.0413e-25

  8/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 2.8271

 16/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 2.3902

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 1.9466

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9563 - loss: 1.7933

 39/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9641 - loss: 1.4714

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9652 - loss: 1.3424

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9630 - loss: 1.2934

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9677 - loss: 1.1265

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9686 - loss: 1.0757

 77/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9688 - loss: 1.0156

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9671 - loss: 1.0164

 93/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9656 - loss: 1.0433

100/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9660 - loss: 0.9835

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9685 - loss: 0.9107

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9687 - loss: 0.8625

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9691 - loss: 0.8091

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9708 - loss: 0.7655

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9723 - loss: 0.7264

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9736 - loss: 0.6916

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9697 - loss: 0.8485

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9684 - loss: 0.8210

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9687 - loss: 0.8304

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.8049

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9680 - loss: 0.7738

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9691 - loss: 0.7451

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9704 - loss: 0.7148

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9704 - loss: 0.6927

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9685 - loss: 0.6792 - val_acc: 0.8702 - val_loss: 2.1213

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 1.0000 - loss: 3.2145e-10

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9333 - loss: 1.5757

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9412 - loss: 1.5405

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9440 - loss: 1.4873

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 1.1712

 39/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9590 - loss: 0.9611

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9565 - loss: 0.8593

 53/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9585 - loss: 0.7512

 60/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9633 - loss: 0.6642

 68/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9647 - loss: 0.6306

 76/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9684 - loss: 0.5649

 84/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9643 - loss: 0.5313

 92/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9630 - loss: 0.5689

100/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9660 - loss: 0.5236

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9648 - loss: 0.5299

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9672 - loss: 0.4933

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9593 - loss: 1.3437

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9554 - loss: 2.0457

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9464 - loss: 2.4812

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9434 - loss: 2.7825

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9425 - loss: 2.9151

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9413 - loss: 2.9602

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9413 - loss: 3.0136

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9391 - loss: 3.0855

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9418 - loss: 2.9499

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9442 - loss: 2.8257

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9465 - loss: 2.7115

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9466 - loss: 2.6639

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9474 - loss: 2.6231 - val_acc: 0.9466 - val_loss: 0.9861

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 1.0000 - loss: 7.8735e-27

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9333 - loss: 2.9641

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9529 - loss: 2.1635

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9520 - loss: 1.9369

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9576 - loss: 1.5924

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9632 - loss: 1.3829

 44/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9682 - loss: 1.1943

 51/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9647 - loss: 1.1576

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9655 - loss: 1.0705

 65/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9692 - loss: 0.9566

 70/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9714 - loss: 0.8882

 77/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9714 - loss: 0.8322

 84/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9714 - loss: 0.7672

 91/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9670 - loss: 0.8241

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9673 - loss: 0.7678

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9676 - loss: 0.7193

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9694 - loss: 0.6815

117/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9692 - loss: 0.6498

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9675 - loss: 0.6228

128/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9688 - loss: 0.5989

134/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9701 - loss: 0.5722

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9714 - loss: 0.5477

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9710 - loss: 0.5424

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9703 - loss: 0.5379

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9693 - loss: 0.5969

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9684 - loss: 0.7143

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9690 - loss: 0.7005

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9671 - loss: 0.6951

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9667 - loss: 0.6795

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9665 - loss: 0.7573

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9651 - loss: 0.7380

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9650 - loss: 0.7216

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9659 - loss: 0.7018

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9670 - loss: 0.6794

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9680 - loss: 0.6586

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9688 - loss: 0.6428

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9688 - loss: 0.6266

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9685 - loss: 0.6153

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.9685 - loss: 0.6153 - val_acc: 0.7214 - val_loss: 4.0640

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 42ms/step - acc: 1.0000 - loss: 4.4055e-13

  8/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 1.6660

 15/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9600 - loss: 0.9076

 22/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9455 - loss: 1.5684

 29/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9448 - loss: 1.2085

 36/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9556 - loss: 0.9739

 44/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9591 - loss: 0.8186

 51/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9569 - loss: 0.7168

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9552 - loss: 0.6383

 66/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9606 - loss: 0.5617

 74/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9622 - loss: 0.5031

 82/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9610 - loss: 0.4624

 90/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9533 - loss: 0.5150

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9571 - loss: 0.4736

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9581 - loss: 0.4454

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9607 - loss: 0.4188

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9613 - loss: 0.3960

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9619 - loss: 0.3765

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9639 - loss: 0.3570

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9657 - loss: 0.3392

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.3428

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9634 - loss: 0.5165

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9615 - loss: 0.4984

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9621 - loss: 0.5697

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9602 - loss: 0.5556

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9617 - loss: 0.5344

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9632 - loss: 0.5148

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.4944

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9639 - loss: 0.4806

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9637 - loss: 0.4720 - val_acc: 0.7214 - val_loss: 4.0142

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 1.0000 - loss: 7.3132e-13

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9333 - loss: 1.4613

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9412 - loss: 1.4751

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 1.4166

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 1.0793

 40/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9600 - loss: 0.8635

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 0.7452

 55/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9527 - loss: 0.6640

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9581 - loss: 0.5890

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9629 - loss: 0.5225

 78/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9615 - loss: 0.4732

 86/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9581 - loss: 0.4425

 93/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9570 - loss: 0.4920

100/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9600 - loss: 0.4582

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9611 - loss: 0.4281

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9635 - loss: 0.4029

122/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9623 - loss: 0.3839

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.3606

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9664 - loss: 0.3422

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9669 - loss: 0.3373

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9647 - loss: 0.5109

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9627 - loss: 0.4927

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9631 - loss: 0.5657

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9611 - loss: 0.5530

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9628 - loss: 0.5288

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9642 - loss: 0.5094

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9655 - loss: 0.4915

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9647 - loss: 0.4782

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9646 - loss: 0.4672 - val_acc: 0.7252 - val_loss: 3.9038

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 1.1190e-12

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9333 - loss: 1.4237

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9412 - loss: 1.4488

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9440 - loss: 1.3480

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 1.0636

 40/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9600 - loss: 0.8510

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 0.7349

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9536 - loss: 0.6434

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9594 - loss: 0.5639

 71/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9634 - loss: 0.5083

 79/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9620 - loss: 0.4612

 86/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9581 - loss: 0.4369

 93/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9570 - loss: 0.4856

100/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9600 - loss: 0.4522

107/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9607 - loss: 0.4268

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9635 - loss: 0.3979

122/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9623 - loss: 0.3791

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.3560

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9664 - loss: 0.3379

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9681 - loss: 0.3214

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9642 - loss: 0.5113

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9633 - loss: 0.4949

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9639 - loss: 0.5646

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9630 - loss: 0.5477

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9635 - loss: 0.5285

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9651 - loss: 0.5061

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9663 - loss: 0.4881

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9675 - loss: 0.4715

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9656 - loss: 0.4621

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9656 - loss: 0.4621 - val_acc: 0.7290 - val_loss: 3.7478

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 1.0000 - loss: 1.6865e-12

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9556 - loss: 1.3886

 16/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9625 - loss: 1.4873

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 1.3657

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9548 - loss: 1.0823

 39/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9641 - loss: 0.8604

 47/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9617 - loss: 0.7402

 55/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9564 - loss: 0.6465

 63/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9619 - loss: 0.5644

 71/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9662 - loss: 0.5017

 79/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.4553

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9632 - loss: 0.4265

 94/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9617 - loss: 0.4741

102/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9627 - loss: 0.4415

109/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9651 - loss: 0.4137

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9672 - loss: 0.3895

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9659 - loss: 0.3712

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9677 - loss: 0.3514

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9693 - loss: 0.3335

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9708 - loss: 0.3173

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9669 - loss: 0.5040

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9658 - loss: 0.4877

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9663 - loss: 0.5556

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9644 - loss: 0.5422

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9659 - loss: 0.5184

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9674 - loss: 0.4966

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9687 - loss: 0.4767

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9680 - loss: 0.4633

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - acc: 0.9685 - loss: 0.4562 - val_acc: 0.7519 - val_loss: 3.6238

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - acc: 1.0000 - loss: 2.5379e-12

  5/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9600 - loss: 2.3586

  9/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9556 - loss: 1.3545

 13/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9692 - loss: 0.9509

 18/210 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - acc: 0.9556 - loss: 1.3166

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9619 - loss: 1.1285

 24/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9583 - loss: 1.3412

 28/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9500 - loss: 1.1819

 31/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9548 - loss: 1.0677

 35/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9600 - loss: 0.9457

 39/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9641 - loss: 0.8487

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9628 - loss: 0.7910

 47/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9617 - loss: 0.7303

 51/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9608 - loss: 0.6787

 54/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9593 - loss: 0.6456

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9586 - loss: 0.6053

 62/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9613 - loss: 0.5662

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9636 - loss: 0.5330

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9657 - loss: 0.5026

 74/210 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - acc: 0.9649 - loss: 0.4779

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9632 - loss: 0.4675

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - acc: 0.9630 - loss: 0.4446

 85/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9624 - loss: 0.4313

 89/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9618 - loss: 0.4886

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9613 - loss: 0.4729

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9629 - loss: 0.4540

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9627 - loss: 0.4360

107/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9645 - loss: 0.4162

110/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9655 - loss: 0.4056

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9667 - loss: 0.3915

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9661 - loss: 0.3799

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9659 - loss: 0.3665

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9669 - loss: 0.3551

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9677 - loss: 0.3469

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9684 - loss: 0.3391

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9693 - loss: 0.3292

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9704 - loss: 0.3176

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - acc: 0.9687 - loss: 0.3291

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9673 - loss: 0.4870

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9660 - loss: 0.4744

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9663 - loss: 0.5437

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - acc: 0.9651 - loss: 0.5325

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9654 - loss: 0.5170

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9667 - loss: 0.4976

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9679 - loss: 0.4795

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9690 - loss: 0.4628

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.9681 - loss: 0.4527

210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - acc: 0.9685 - loss: 0.4480 - val_acc: 0.7634 - val_loss: 3.6565

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 8s 41ms/step - acc: 1.0000 - loss: 3.9160e-12

  8/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9500 - loss: 1.4776

 15/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9733 - loss: 0.8049

 22/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9545 - loss: 1.4399

 29/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9517 - loss: 1.1285

 36/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9611 - loss: 0.9092

 44/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9636 - loss: 0.7641

 51/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9608 - loss: 0.6715

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9586 - loss: 0.5990

 65/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9631 - loss: 0.5358

 72/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9667 - loss: 0.4837

 79/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9646 - loss: 0.4453

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9632 - loss: 0.4172

 94/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9617 - loss: 0.4624

101/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9624 - loss: 0.4354

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9648 - loss: 0.4078

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9670 - loss: 0.3838

122/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9656 - loss: 0.3654

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9674 - loss: 0.3457

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9691 - loss: 0.3279

143/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9706 - loss: 0.3119

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9680 - loss: 0.3595

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9669 - loss: 0.4553

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9671 - loss: 0.4377

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9649 - loss: 0.5125

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9652 - loss: 0.4979

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9665 - loss: 0.4791

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9677 - loss: 0.4616

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9688 - loss: 0.4455

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9680 - loss: 0.4363

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - acc: 0.9685 - loss: 0.4296 - val_acc: 0.7672 - val_loss: 3.5044

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 8s 221ms/step

20/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

39/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[819  30]
 [  2 457]]
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98       849
         1.0       0.94      1.00      0.97       459

    accuracy                           0.98      1308
   macro avg       0.97      0.98      0.97      1308
weighted avg       0.98      0.98      0.98      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM two layer model

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(Conv1D(filters=128, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(LSTM(30,
                            return_sequences=True, # remember, if stacking layers, you need to return sequences!
                            activation='relu',
                            recurrent_dropout=0.2)))
model.add(GRU(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 48, 128)        │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 24, 60)         │        38,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 20)             │         4,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 45,149 (176.36 KB)

 Trainable params: 45,149 (176.36 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 25:37 7s/step - acc: 0.6000 - loss: 9.9714

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8000 - loss: 18.5918

  7/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 0.7714 - loss: 35.5731

  9/210 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - acc: 0.7333 - loss: 30.6617

 12/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.7333 - loss: 30.0606

 14/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.7143 - loss: 28.5686

 16/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.7125 - loss: 30.0760

 18/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.6556 - loss: 34.0725

 20/210 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - acc: 0.6200 - loss: 32.5597

 22/210 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - acc: 0.6000 - loss: 30.3140

 24/210 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - acc: 0.5750 - loss: 29.9010

 26/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5385 - loss: 28.9724

 28/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5214 - loss: 28.0056

 30/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5067 - loss: 28.4735

 32/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5125 - loss: 26.9236

 34/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5176 - loss: 25.4053

 36/210 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - acc: 0.5111 - loss: 24.3517

 38/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5211 - loss: 23.3727

 40/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5350 - loss: 22.2630

 42/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5476 - loss: 21.2532

 44/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5545 - loss: 20.4225

 46/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5652 - loss: 19.5935

 48/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5667 - loss: 18.9347

 50/210 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - acc: 0.5760 - loss: 18.2010

 52/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.5808 - loss: 17.5492

 54/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.5926 - loss: 16.9113

 56/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.6036 - loss: 16.3686

 58/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.6172 - loss: 15.8077

 60/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.6267 - loss: 15.3215

 62/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.6355 - loss: 14.8341

 64/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.6438 - loss: 14.4161

 66/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6515 - loss: 13.9878

 68/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6588 - loss: 13.5910

 70/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6686 - loss: 13.2029

 72/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6750 - loss: 12.9574

 74/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6811 - loss: 12.6217

 76/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6868 - loss: 12.3206

 78/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.6949 - loss: 12.0052

 80/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7000 - loss: 11.7264

 82/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7073 - loss: 11.4406

 84/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7143 - loss: 11.1682

 86/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7140 - loss: 11.0997

 88/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7159 - loss: 10.9651

 90/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7178 - loss: 10.7688

 92/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7239 - loss: 10.5348

 94/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7277 - loss: 10.3224

 96/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7312 - loss: 10.1199

 98/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7306 - loss: 9.9431

100/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7360 - loss: 9.7448

102/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7373 - loss: 9.5812

104/210 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - acc: 0.7365 - loss: 9.4285

106/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7358 - loss: 9.2816

108/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7370 - loss: 9.1218

110/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7400 - loss: 8.9666

112/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7429 - loss: 8.8134

114/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7474 - loss: 8.6593

116/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7517 - loss: 8.5104

118/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7525 - loss: 8.3814

120/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7567 - loss: 8.2429

122/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7607 - loss: 8.1085

124/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7629 - loss: 7.9804

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7669 - loss: 7.8064

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7705 - loss: 7.6855

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7740 - loss: 7.5683

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7759 - loss: 7.4568

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7793 - loss: 7.3464

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7810 - loss: 7.2415

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - acc: 0.7842 - loss: 7.1376

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7872 - loss: 7.0363

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7902 - loss: 6.9384

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7917 - loss: 6.8448

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7946 - loss: 6.7523

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7946 - loss: 6.6689

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7947 - loss: 6.5855

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7974 - loss: 6.4996

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.7987 - loss: 6.4176

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - acc: 0.8000 - loss: 6.3488

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8013 - loss: 6.2819

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8025 - loss: 6.2156

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8049 - loss: 6.1396

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8061 - loss: 6.0754

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8084 - loss: 6.0036

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8083 - loss: 5.9429

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8082 - loss: 5.8883

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.8092 - loss: 5.8261

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8103 - loss: 5.7628

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8124 - loss: 5.6983

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8145 - loss: 5.6347

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8166 - loss: 5.5729

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8186 - loss: 5.5120

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8205 - loss: 5.4525

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8225 - loss: 5.3942

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8233 - loss: 5.3390

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8230 - loss: 5.2902

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8238 - loss: 5.2371

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8236 - loss: 5.1861

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8254 - loss: 5.1334

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8271 - loss: 5.0819

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8289 - loss: 5.0315

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - acc: 0.8305 - loss: 4.9820

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8302 - loss: 4.9512

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8319 - loss: 4.9034

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.8335 - loss: 4.8568

210/210 ━━━━━━━━━━━━━━━━━━━━ 15s 35ms/step - acc: 0.8337 - loss: 4.8521 - val_acc: 0.9771 - val_loss: 0.1243

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - acc: 1.0000 - loss: 0.0034

  3/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 1.0000 - loss: 0.0364

  5/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 1.0000 - loss: 0.0260

  7/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9714 - loss: 0.1149

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - acc: 0.9111 - loss: 0.9917

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9273 - loss: 0.8186

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - acc: 0.9385 - loss: 0.6952

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - acc: 0.9467 - loss: 0.6095

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 27ms/step - acc: 0.9412 - loss: 0.5819

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9263 - loss: 26.8658

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9333 - loss: 24.3084

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9217 - loss: 22.2183

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9200 - loss: 20.4627

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9185 - loss: 18.9799

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9103 - loss: 18.5782

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9097 - loss: 18.4331

 33/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9091 - loss: 17.5788

 35/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9086 - loss: 16.5855

 37/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9135 - loss: 15.6891

 39/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9179 - loss: 14.8898

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9171 - loss: 14.1726

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9209 - loss: 13.5168

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - acc: 0.9111 - loss: 12.9823

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9106 - loss: 12.4530

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9102 - loss: 11.9476

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9059 - loss: 11.4997

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9057 - loss: 11.0717

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9055 - loss: 10.6738

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9088 - loss: 10.2993

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9119 - loss: 9.9503

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9148 - loss: 9.6257

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9175 - loss: 9.3201

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9169 - loss: 9.0357

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9194 - loss: 8.7660

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9188 - loss: 8.5173

 71/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9211 - loss: 8.2774

 73/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9205 - loss: 8.0527

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9200 - loss: 7.8537

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9221 - loss: 7.6498

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9241 - loss: 7.4562

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9259 - loss: 7.2735

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9277 - loss: 7.0987

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9271 - loss: 6.9353

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9264 - loss: 6.7798

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9258 - loss: 6.6294

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9231 - loss: 6.5032

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9247 - loss: 6.3634

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9263 - loss: 6.2295

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9216 - loss: 6.1154

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9232 - loss: 5.9918

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9248 - loss: 5.8737

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9262 - loss: 5.7607

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9276 - loss: 5.6527

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9290 - loss: 5.5474

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9303 - loss: 5.4456

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9297 - loss: 5.3510

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9310 - loss: 5.2564

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9322 - loss: 5.1650

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9316 - loss: 5.0792

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9311 - loss: 4.9963

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9322 - loss: 4.9147

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9333 - loss: 4.8353

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9344 - loss: 4.7579

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9339 - loss: 4.6847

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9349 - loss: 4.6120

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9359 - loss: 4.5416

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9368 - loss: 4.4734

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9378 - loss: 4.4074

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9358 - loss: 4.3469

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9353 - loss: 4.2854

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9362 - loss: 4.2252

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9371 - loss: 4.1661

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9366 - loss: 4.1158

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9361 - loss: 4.0679

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9369 - loss: 4.0133

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9351 - loss: 3.9628

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9359 - loss: 3.9110

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9355 - loss: 3.8622

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9350 - loss: 3.8176

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9358 - loss: 3.7705

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9354 - loss: 3.7279

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9362 - loss: 3.6825

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9358 - loss: 3.6396

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9353 - loss: 3.5980

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9314 - loss: 3.5616

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9310 - loss: 3.5230

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9295 - loss: 3.4851

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9303 - loss: 3.4459

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9299 - loss: 3.4082

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9307 - loss: 3.3702

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9304 - loss: 3.3341

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9311 - loss: 3.2978

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9319 - loss: 3.2625

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9326 - loss: 3.2276

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9333 - loss: 3.1949

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9319 - loss: 3.1642

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9326 - loss: 3.1320

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9313 - loss: 3.1019

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9320 - loss: 3.0707

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9327 - loss: 3.0401

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9333 - loss: 3.0100

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9340 - loss: 2.9811

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9337 - loss: 2.9549

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9343 - loss: 2.9269

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9349 - loss: 2.8994

210/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9350 - loss: 2.8966 - val_acc: 0.9771 - val_loss: 0.1833

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.0212

  3/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 1.0000 - loss: 0.0668

  5/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 1.0000 - loss: 0.0421

  7/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9714 - loss: 0.0920

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9778 - loss: 0.0841

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9818 - loss: 0.0803

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9846 - loss: 0.0702

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9867 - loss: 0.0611

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9765 - loss: 0.1721

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9684 - loss: 0.1687

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9714 - loss: 0.1526

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9652 - loss: 0.1816

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.1922

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9556 - loss: 0.1966

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9586 - loss: 0.1850

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9548 - loss: 0.1829

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9576 - loss: 0.1722

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9486 - loss: 0.1809

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9514 - loss: 0.1711

 39/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9487 - loss: 0.1712

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9463 - loss: 0.1684

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9442 - loss: 0.1653

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9422 - loss: 0.1749

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9404 - loss: 0.1795

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9429 - loss: 0.1726

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9412 - loss: 0.1774

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9396 - loss: 0.1814

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9382 - loss: 0.1792

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9404 - loss: 0.1729

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9424 - loss: 0.1672

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9443 - loss: 0.1623

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9460 - loss: 0.1571

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9446 - loss: 0.1551

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9463 - loss: 0.1506

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9478 - loss: 0.1465

 71/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9465 - loss: 0.1448

 73/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9479 - loss: 0.1414

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9493 - loss: 0.1401

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9506 - loss: 0.1365

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9519 - loss: 0.1336

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9506 - loss: 0.1362

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9518 - loss: 0.1330

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9506 - loss: 0.1376

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9517 - loss: 0.1349

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9506 - loss: 0.1336

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9473 - loss: 0.1396

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9484 - loss: 0.1371

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9495 - loss: 0.1345

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9485 - loss: 0.1383

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9495 - loss: 0.1355

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9505 - loss: 0.1331

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9515 - loss: 0.1313

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9524 - loss: 0.1301

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9533 - loss: 0.1283

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9541 - loss: 0.1262

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9532 - loss: 0.1288

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9540 - loss: 0.1270

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9548 - loss: 0.1248

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9556 - loss: 0.1228

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9563 - loss: 0.1209

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9570 - loss: 0.1194

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9577 - loss: 0.1178

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9584 - loss: 0.1170

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9591 - loss: 0.1154

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9597 - loss: 0.1147

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9603 - loss: 0.1130

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9609 - loss: 0.1117

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9615 - loss: 0.1102

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9620 - loss: 0.1088

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9626 - loss: 0.1072

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9631 - loss: 0.1068

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9636 - loss: 0.1054

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9614 - loss: 0.1093

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9605 - loss: 0.1127

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9611 - loss: 0.1113

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9616 - loss: 0.1117

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9621 - loss: 0.1103

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9626 - loss: 0.1091

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9618 - loss: 0.1114

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9610 - loss: 0.1138

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9602 - loss: 0.1160

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9607 - loss: 0.1148

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9600 - loss: 0.1163

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9593 - loss: 0.1163

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9586 - loss: 0.1194

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9567 - loss: 0.1246

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9561 - loss: 0.1266

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9566 - loss: 0.1254

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9571 - loss: 0.1243

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9575 - loss: 0.1230

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9580 - loss: 0.1217

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9585 - loss: 0.1204

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9589 - loss: 0.1192

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9594 - loss: 0.1179

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9587 - loss: 0.1179

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9592 - loss: 0.1172

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9596 - loss: 0.1164

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9600 - loss: 0.1155

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9604 - loss: 0.1146

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9608 - loss: 0.1136

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9602 - loss: 0.1133

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9606 - loss: 0.1134

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9590 - loss: 0.1169

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9594 - loss: 0.1161

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9598 - loss: 0.1152

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - acc: 0.9598 - loss: 0.1151 - val_acc: 0.9771 - val_loss: 0.1471

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 64ms/step - acc: 1.0000 - loss: 0.0131

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8667 - loss: 0.1405

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9200 - loss: 0.0867

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8857 - loss: 0.1491

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8889 - loss: 0.1707

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9091 - loss: 0.1511

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9231 - loss: 0.1298

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9333 - loss: 0.1135

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9294 - loss: 0.1845

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9368 - loss: 0.1744

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9429 - loss: 0.1579

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9217 - loss: 0.1744

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9200 - loss: 0.1795

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9259 - loss: 0.1734

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9310 - loss: 0.1635

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9355 - loss: 0.1553

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9394 - loss: 0.1474

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9429 - loss: 0.1448

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9459 - loss: 0.1375

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9436 - loss: 0.1350

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9463 - loss: 0.1324

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9488 - loss: 0.1277

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9511 - loss: 0.1256

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9489 - loss: 0.1295

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9510 - loss: 0.1248

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9490 - loss: 0.1302

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9472 - loss: 0.1345

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9491 - loss: 0.1319

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9509 - loss: 0.1273

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9525 - loss: 0.1232

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9541 - loss: 0.1199

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9556 - loss: 0.1162

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9569 - loss: 0.1154

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9582 - loss: 0.1120

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9594 - loss: 0.1108

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9606 - loss: 0.1082

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9616 - loss: 0.1060

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9600 - loss: 0.1124

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9610 - loss: 0.1097

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - acc: 0.9620 - loss: 0.1074

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 32ms/step - acc: 0.9630 - loss: 0.1050

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 32ms/step - acc: 0.9639 - loss: 0.1026

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9624 - loss: 0.1067

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9632 - loss: 0.1049

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9618 - loss: 0.1042

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9604 - loss: 0.1079

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9613 - loss: 0.1071

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9621 - loss: 0.1048

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9608 - loss: 0.1077

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9616 - loss: 0.1056

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9624 - loss: 0.1039

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9631 - loss: 0.1035

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9619 - loss: 0.1053

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9626 - loss: 0.1039

108/210 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.9630 - loss: 0.1029

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.9633 - loss: 0.1023

110/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9618 - loss: 0.1028

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9622 - loss: 0.1021

112/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9607 - loss: 0.1026

114/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9614 - loss: 0.1010

116/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9621 - loss: 0.0993

118/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.9627 - loss: 0.0979

120/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.9633 - loss: 0.0978

122/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.9639 - loss: 0.0965

124/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9645 - loss: 0.0956

126/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9651 - loss: 0.0942

128/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9656 - loss: 0.0933

130/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9662 - loss: 0.0919

132/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9667 - loss: 0.0910

134/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9672 - loss: 0.0898

136/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9676 - loss: 0.0887

138/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9681 - loss: 0.0874

140/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9686 - loss: 0.0863

142/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9690 - loss: 0.0855

144/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.9694 - loss: 0.0846

146/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.9671 - loss: 0.0923

148/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.9676 - loss: 0.0921

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.9667 - loss: 0.0951

152/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9658 - loss: 0.0956

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9662 - loss: 0.0945

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9654 - loss: 0.0967

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9646 - loss: 0.0984

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9638 - loss: 0.1009

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9642 - loss: 0.0997

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9646 - loss: 0.0987

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9627 - loss: 0.1011

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9631 - loss: 0.1002

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9600 - loss: 0.1079

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9593 - loss: 0.1091

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9598 - loss: 0.1090

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9602 - loss: 0.1079

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.9607 - loss: 0.1067

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - acc: 0.9611 - loss: 0.1058

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9615 - loss: 0.1048

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9620 - loss: 0.1038

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9624 - loss: 0.1027

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9628 - loss: 0.1023

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9632 - loss: 0.1031

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9635 - loss: 0.1025

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9639 - loss: 0.1020

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9643 - loss: 0.1012

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9646 - loss: 0.1006

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9650 - loss: 0.0999

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9653 - loss: 0.0997

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9637 - loss: 0.1026

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9641 - loss: 0.1035

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9644 - loss: 0.1034

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.9646 - loss: 0.1030

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.9646 - loss: 0.1030 - val_acc: 0.9771 - val_loss: 0.1890

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.0212

  3/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9333 - loss: 0.0807

  5/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.0517

  7/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9429 - loss: 0.1038

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9333 - loss: 0.1434

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9455 - loss: 0.1422

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9538 - loss: 0.1232

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9600 - loss: 0.1079

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9529 - loss: 0.1495

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9579 - loss: 0.1445

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9619 - loss: 0.1314

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9565 - loss: 0.1373

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9520 - loss: 0.1650

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9481 - loss: 0.1711

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9517 - loss: 0.1622

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9548 - loss: 0.1584

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9576 - loss: 0.1493

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.1457

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9622 - loss: 0.1378

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9641 - loss: 0.1357

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9659 - loss: 0.1302

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9674 - loss: 0.1263

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9689 - loss: 0.1245

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9660 - loss: 0.1283

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9673 - loss: 0.1263

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9647 - loss: 0.1299

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9623 - loss: 0.1332

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9636 - loss: 0.1332

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9649 - loss: 0.1285

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9661 - loss: 0.1246

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9672 - loss: 0.1229

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9683 - loss: 0.1192

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9692 - loss: 0.1189

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9701 - loss: 0.1153

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9710 - loss: 0.1125

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9718 - loss: 0.1103

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9726 - loss: 0.1132

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9707 - loss: 0.1147

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.1120

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9722 - loss: 0.1095

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9728 - loss: 0.1072

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9735 - loss: 0.1050

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9718 - loss: 0.1092

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9724 - loss: 0.1088

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9708 - loss: 0.1083

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9692 - loss: 0.1116

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9699 - loss: 0.1096

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9705 - loss: 0.1073

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9691 - loss: 0.1097

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9697 - loss: 0.1076

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9703 - loss: 0.1070

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9709 - loss: 0.1058

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.1066

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9720 - loss: 0.1064

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9725 - loss: 0.1052

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9712 - loss: 0.1073

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9717 - loss: 0.1071

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9722 - loss: 0.1052

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9726 - loss: 0.1037

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9731 - loss: 0.1023

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9736 - loss: 0.1023

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9740 - loss: 0.1021

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9744 - loss: 0.1006

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9748 - loss: 0.1003

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9752 - loss: 0.0991

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9756 - loss: 0.0978

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9759 - loss: 0.0981

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9763 - loss: 0.0978

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9766 - loss: 0.0978

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9770 - loss: 0.0966

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9773 - loss: 0.0966

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9776 - loss: 0.0955

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9766 - loss: 0.0979

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9755 - loss: 0.1003

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9758 - loss: 0.0994

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9748 - loss: 0.1000

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9752 - loss: 0.0988

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9755 - loss: 0.0988

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9745 - loss: 0.0984

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9736 - loss: 0.1008

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9727 - loss: 0.1007

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9730 - loss: 0.0998

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9721 - loss: 0.1019

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9713 - loss: 0.1016

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9704 - loss: 0.1035

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9684 - loss: 0.1059

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9676 - loss: 0.1078

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9680 - loss: 0.1068

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9684 - loss: 0.1057

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9687 - loss: 0.1046

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9691 - loss: 0.1035

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9694 - loss: 0.1025

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9697 - loss: 0.1015

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9701 - loss: 0.1004

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9704 - loss: 0.1001

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9707 - loss: 0.1008

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.1008

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.1014

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9716 - loss: 0.1005

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9719 - loss: 0.0998

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9721 - loss: 0.0990

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9724 - loss: 0.0986

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9707 - loss: 0.1005

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.1006

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.1002

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 31ms/step - acc: 0.9713 - loss: 0.1001 - val_acc: 0.9771 - val_loss: 0.1679

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 57ms/step - acc: 1.0000 - loss: 0.0115

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9333 - loss: 0.0662

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9600 - loss: 0.0424

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9429 - loss: 0.0577

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9333 - loss: 0.0713

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9455 - loss: 0.0740

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9538 - loss: 0.0641

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.0567

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9529 - loss: 0.1251

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9579 - loss: 0.1231

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9619 - loss: 0.1116

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9565 - loss: 0.1150

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9520 - loss: 0.1366

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9481 - loss: 0.1446

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9517 - loss: 0.1375

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9548 - loss: 0.1302

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9576 - loss: 0.1228

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.1246

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9622 - loss: 0.1186

 39/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9641 - loss: 0.1142

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9659 - loss: 0.1094

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9674 - loss: 0.1055

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9689 - loss: 0.1070

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9660 - loss: 0.1193

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9673 - loss: 0.1176

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9647 - loss: 0.1227

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9623 - loss: 0.1256

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9636 - loss: 0.1274

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9649 - loss: 0.1230

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9661 - loss: 0.1193

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9672 - loss: 0.1163

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9683 - loss: 0.1128

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9692 - loss: 0.1106

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9701 - loss: 0.1075

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9710 - loss: 0.1082

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9718 - loss: 0.1074

 73/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9726 - loss: 0.1057

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9707 - loss: 0.1093

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.1068

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9722 - loss: 0.1048

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9728 - loss: 0.1026

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9735 - loss: 0.1017

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9718 - loss: 0.1035

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9724 - loss: 0.1029

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9708 - loss: 0.1029

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9692 - loss: 0.1056

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9699 - loss: 0.1043

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9705 - loss: 0.1021

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9691 - loss: 0.1048

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9697 - loss: 0.1027

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9703 - loss: 0.1033

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9709 - loss: 0.1021

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.1020

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9720 - loss: 0.1006

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9725 - loss: 0.0992

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9712 - loss: 0.1017

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9717 - loss: 0.1015

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9722 - loss: 0.0997

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9726 - loss: 0.0992

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9731 - loss: 0.0976

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9736 - loss: 0.0967

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9740 - loss: 0.0955

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9744 - loss: 0.0941

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9748 - loss: 0.0929

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9752 - loss: 0.0917

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9756 - loss: 0.0904

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9759 - loss: 0.0895

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9763 - loss: 0.0884

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9766 - loss: 0.0875

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9770 - loss: 0.0863

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9773 - loss: 0.0854

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9776 - loss: 0.0843

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9766 - loss: 0.0885

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9755 - loss: 0.0923

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9758 - loss: 0.0913

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9748 - loss: 0.0931

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9752 - loss: 0.0919

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9755 - loss: 0.0910

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9745 - loss: 0.0929

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9736 - loss: 0.0936

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9727 - loss: 0.0956

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9730 - loss: 0.0947

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9721 - loss: 0.0963

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9713 - loss: 0.0965

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9704 - loss: 0.0987

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9684 - loss: 0.1027

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9676 - loss: 0.1043

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9680 - loss: 0.1034

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9684 - loss: 0.1024

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9687 - loss: 0.1012

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9691 - loss: 0.1003

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9694 - loss: 0.0993

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9697 - loss: 0.0984

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9701 - loss: 0.0973

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9704 - loss: 0.0973

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9707 - loss: 0.0969

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.0964

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.0964

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9716 - loss: 0.0956

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9719 - loss: 0.0954

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9721 - loss: 0.0946

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9724 - loss: 0.0944

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9707 - loss: 0.0974

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.0969

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.0968

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 31ms/step - acc: 0.9713 - loss: 0.0967 - val_acc: 0.9771 - val_loss: 0.1728

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 61ms/step - acc: 1.0000 - loss: 0.0190

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9333 - loss: 0.1100

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9600 - loss: 0.0687

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9429 - loss: 0.0769

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9333 - loss: 0.1175

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9455 - loss: 0.1072

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9538 - loss: 0.0929

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9600 - loss: 0.0893

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9529 - loss: 0.1582

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9579 - loss: 0.1509

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9619 - loss: 0.1372

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9565 - loss: 0.1561

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9520 - loss: 0.1665

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9481 - loss: 0.1719

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9517 - loss: 0.1625

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9548 - loss: 0.1546

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9576 - loss: 0.1457

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9600 - loss: 0.1471

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - acc: 0.9622 - loss: 0.1395

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9641 - loss: 0.1340

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9659 - loss: 0.1333

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9674 - loss: 0.1317

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9689 - loss: 0.1297

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9660 - loss: 0.1330

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9673 - loss: 0.1306

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9647 - loss: 0.1347

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9623 - loss: 0.1379

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9636 - loss: 0.1359

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9649 - loss: 0.1312

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9661 - loss: 0.1271

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9672 - loss: 0.1239

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9683 - loss: 0.1200

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9692 - loss: 0.1210

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9701 - loss: 0.1175

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9710 - loss: 0.1146

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9718 - loss: 0.1119

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9726 - loss: 0.1105

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9707 - loss: 0.1136

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9714 - loss: 0.1124

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9722 - loss: 0.1100

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9704 - loss: 0.1120

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9711 - loss: 0.1095

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9694 - loss: 0.1142

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9701 - loss: 0.1123

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9685 - loss: 0.1117

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9670 - loss: 0.1155

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9677 - loss: 0.1135

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9684 - loss: 0.1111

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9670 - loss: 0.1132

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9677 - loss: 0.1109

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9683 - loss: 0.1101

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9689 - loss: 0.1093

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9695 - loss: 0.1085

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9701 - loss: 0.1071

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9706 - loss: 0.1055

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9694 - loss: 0.1075

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9699 - loss: 0.1063

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9704 - loss: 0.1045

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9709 - loss: 0.1029

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9714 - loss: 0.1014

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9719 - loss: 0.1004

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9724 - loss: 0.0994

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9728 - loss: 0.0979

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9732 - loss: 0.0968

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9736 - loss: 0.0954

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9740 - loss: 0.0941

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9744 - loss: 0.0932

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9748 - loss: 0.0922

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9752 - loss: 0.0910

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9755 - loss: 0.0898

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9759 - loss: 0.0885

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9762 - loss: 0.0876

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9752 - loss: 0.0937

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9741 - loss: 0.0986

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9745 - loss: 0.0973

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9735 - loss: 0.1002

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9739 - loss: 0.0989

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9742 - loss: 0.0980

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9732 - loss: 0.0997

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9723 - loss: 0.1013

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9714 - loss: 0.1026

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9718 - loss: 0.1016

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9709 - loss: 0.1028

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9701 - loss: 0.1035

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9692 - loss: 0.1065

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9673 - loss: 0.1105

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9665 - loss: 0.1121

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9669 - loss: 0.1112

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9672 - loss: 0.1101

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9676 - loss: 0.1089

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9680 - loss: 0.1084

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9683 - loss: 0.1074

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9686 - loss: 0.1063

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9690 - loss: 0.1052

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9693 - loss: 0.1052

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9696 - loss: 0.1051

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9699 - loss: 0.1046

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9703 - loss: 0.1042

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9706 - loss: 0.1034

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9709 - loss: 0.1032

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9711 - loss: 0.1024

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9714 - loss: 0.1023

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9698 - loss: 0.1047

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9700 - loss: 0.1042

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9703 - loss: 0.1041

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - acc: 0.9704 - loss: 0.1040 - val_acc: 0.9771 - val_loss: 0.1941

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.0184

  3/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9333 - loss: 0.1095

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9600 - loss: 0.0704

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9429 - loss: 0.1086

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9333 - loss: 0.1398

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9455 - loss: 0.1465

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9538 - loss: 0.1272

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9600 - loss: 0.1114

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9529 - loss: 0.1488

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9579 - loss: 0.1488

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9619 - loss: 0.1347

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9565 - loss: 0.1503

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9520 - loss: 0.1556

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9481 - loss: 0.1581

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9517 - loss: 0.1495

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9548 - loss: 0.1435

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9576 - loss: 0.1354

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9600 - loss: 0.1395

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9622 - loss: 0.1325

 39/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9641 - loss: 0.1282

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9659 - loss: 0.1235

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9674 - loss: 0.1203

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9689 - loss: 0.1164

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9660 - loss: 0.1198

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9673 - loss: 0.1161

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9647 - loss: 0.1200

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9623 - loss: 0.1222

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9636 - loss: 0.1209

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9649 - loss: 0.1167

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9661 - loss: 0.1131

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9672 - loss: 0.1105

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9683 - loss: 0.1071

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9692 - loss: 0.1054

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9701 - loss: 0.1023

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9710 - loss: 0.0999

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9718 - loss: 0.0977

 73/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9726 - loss: 0.0962

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9707 - loss: 0.1001

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.0979

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9722 - loss: 0.0960

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9728 - loss: 0.0944

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9735 - loss: 0.0924

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9718 - loss: 0.0965

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9724 - loss: 0.0961

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9730 - loss: 0.0950

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.0986

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9720 - loss: 0.0969

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9726 - loss: 0.0948

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9711 - loss: 0.0975

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9717 - loss: 0.0955

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9723 - loss: 0.0943

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9728 - loss: 0.0935

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9733 - loss: 0.0944

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9738 - loss: 0.0934

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9743 - loss: 0.0920

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9730 - loss: 0.0951

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9735 - loss: 0.0942

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9739 - loss: 0.0925

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9744 - loss: 0.0912

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9748 - loss: 0.0899

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9752 - loss: 0.0895

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9756 - loss: 0.0887

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9760 - loss: 0.0874

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9764 - loss: 0.0864

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9767 - loss: 0.0854

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9771 - loss: 0.0842

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9774 - loss: 0.0837

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9778 - loss: 0.0836

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9781 - loss: 0.0828

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9784 - loss: 0.0817

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9787 - loss: 0.0811

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9790 - loss: 0.0801

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9779 - loss: 0.0828

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9769 - loss: 0.0859

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9772 - loss: 0.0866

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9762 - loss: 0.0884

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9765 - loss: 0.0873

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9768 - loss: 0.0865

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9758 - loss: 0.0884

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9748 - loss: 0.0884

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9739 - loss: 0.0908

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9742 - loss: 0.0899

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9733 - loss: 0.0914

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9725 - loss: 0.0914

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9716 - loss: 0.0948

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9696 - loss: 0.0993

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9688 - loss: 0.1005

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9691 - loss: 0.0997

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9695 - loss: 0.0987

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9698 - loss: 0.0976

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9702 - loss: 0.0967

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9705 - loss: 0.0958

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9708 - loss: 0.0949

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9711 - loss: 0.0939

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9714 - loss: 0.0940

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9717 - loss: 0.0949

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9720 - loss: 0.0945

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9723 - loss: 0.0940

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9726 - loss: 0.0933

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9729 - loss: 0.0927

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9731 - loss: 0.0920

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9734 - loss: 0.0918

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9717 - loss: 0.0933

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9720 - loss: 0.0928

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9722 - loss: 0.0922

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 31ms/step - acc: 0.9723 - loss: 0.0921 - val_acc: 0.9771 - val_loss: 0.1632

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - acc: 1.0000 - loss: 0.0197

  3/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9333 - loss: 0.1094

  5/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9600 - loss: 0.0676

  7/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9429 - loss: 0.1223

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9333 - loss: 0.1191

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9455 - loss: 0.1182

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9538 - loss: 0.1098

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9600 - loss: 0.1037

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9529 - loss: 0.1885

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9579 - loss: 0.1834

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9619 - loss: 0.1662

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9652 - loss: 0.1602

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9600 - loss: 0.1647

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9556 - loss: 0.1696

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9586 - loss: 0.1599

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9613 - loss: 0.1566

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - acc: 0.9636 - loss: 0.1477

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9657 - loss: 0.1454

 37/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9676 - loss: 0.1377

 39/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9692 - loss: 0.1324

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9707 - loss: 0.1270

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9721 - loss: 0.1228

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9733 - loss: 0.1183

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9702 - loss: 0.1222

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9714 - loss: 0.1181

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9686 - loss: 0.1268

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9660 - loss: 0.1321

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9673 - loss: 0.1297

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9684 - loss: 0.1256

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9695 - loss: 0.1215

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9705 - loss: 0.1203

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9714 - loss: 0.1166

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9723 - loss: 0.1142

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9731 - loss: 0.1109

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9739 - loss: 0.1081

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9746 - loss: 0.1057

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9753 - loss: 0.1052

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9733 - loss: 0.1096

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9740 - loss: 0.1070

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9747 - loss: 0.1049

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9753 - loss: 0.1026

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9759 - loss: 0.1003

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9741 - loss: 0.1042

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9747 - loss: 0.1025

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9753 - loss: 0.1005

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9736 - loss: 0.1035

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9742 - loss: 0.1018

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9747 - loss: 0.0997

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9732 - loss: 0.1020

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9737 - loss: 0.1000

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9743 - loss: 0.0996

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9748 - loss: 0.0988

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9752 - loss: 0.0994

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9757 - loss: 0.0983

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9761 - loss: 0.0968

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9748 - loss: 0.0989

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9752 - loss: 0.0978

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9757 - loss: 0.0962

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9761 - loss: 0.0948

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9765 - loss: 0.0933

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9769 - loss: 0.0942

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9772 - loss: 0.0940

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9776 - loss: 0.0926

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9780 - loss: 0.0924

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9783 - loss: 0.0920

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9786 - loss: 0.0907

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9789 - loss: 0.0901

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9793 - loss: 0.0892

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9796 - loss: 0.0883

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9799 - loss: 0.0871

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9801 - loss: 0.0864

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9804 - loss: 0.0854

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9793 - loss: 0.0879

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9782 - loss: 0.0901

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9785 - loss: 0.0892

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9762 - loss: 0.0946

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9765 - loss: 0.0934

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9768 - loss: 0.0932

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9758 - loss: 0.0949

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9748 - loss: 0.0975

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9739 - loss: 0.0991

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9742 - loss: 0.0981

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9733 - loss: 0.0994

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9725 - loss: 0.1003

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9716 - loss: 0.1022

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9696 - loss: 0.1069

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9688 - loss: 0.1083

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9691 - loss: 0.1080

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9695 - loss: 0.1070

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9698 - loss: 0.1058

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9702 - loss: 0.1049

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9705 - loss: 0.1040

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9708 - loss: 0.1030

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9711 - loss: 0.1019

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9714 - loss: 0.1028

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9717 - loss: 0.1032

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.1037

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.1042

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9716 - loss: 0.1034

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9719 - loss: 0.1032

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9721 - loss: 0.1024

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9724 - loss: 0.1022

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9707 - loss: 0.1047

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9710 - loss: 0.1042

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9713 - loss: 0.1035

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - acc: 0.9713 - loss: 0.1034 - val_acc: 0.9771 - val_loss: 0.1897

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 61ms/step - acc: 1.0000 - loss: 0.0234

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 1.0000 - loss: 0.0672

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 1.0000 - loss: 0.0449

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9714 - loss: 0.1091

  9/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9556 - loss: 0.1371

 11/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9636 - loss: 0.1261

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9692 - loss: 0.1095

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9733 - loss: 0.0959

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9647 - loss: 0.1332

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9684 - loss: 0.1298

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9714 - loss: 0.1175

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9652 - loss: 0.1219

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9600 - loss: 0.1341

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9556 - loss: 0.1405

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9586 - loss: 0.1329

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9613 - loss: 0.1277

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9636 - loss: 0.1213

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9657 - loss: 0.1199

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9676 - loss: 0.1136

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.9692 - loss: 0.1150

 41/210 ━━━━━━━━━━━━━━━━━━━━ 4s 29ms/step - acc: 0.9707 - loss: 0.1106

 43/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9721 - loss: 0.1073

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9733 - loss: 0.1037

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9702 - loss: 0.1086

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9714 - loss: 0.1049

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9686 - loss: 0.1120

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9660 - loss: 0.1159

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9673 - loss: 0.1142

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9684 - loss: 0.1107

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9695 - loss: 0.1072

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9705 - loss: 0.1064

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9714 - loss: 0.1030

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9723 - loss: 0.1012

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9731 - loss: 0.0982

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9739 - loss: 0.0958

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9746 - loss: 0.0936

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9753 - loss: 0.0921

 75/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9733 - loss: 0.0963

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9740 - loss: 0.0940

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9747 - loss: 0.0921

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9753 - loss: 0.0902

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9759 - loss: 0.0882

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9741 - loss: 0.0922

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9747 - loss: 0.0908

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9730 - loss: 0.0908

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9714 - loss: 0.0950

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9720 - loss: 0.0934

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9726 - loss: 0.0914

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9711 - loss: 0.0943

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9717 - loss: 0.0924

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9723 - loss: 0.0910

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9728 - loss: 0.0917

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.9733 - loss: 0.0914

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9738 - loss: 0.0904

109/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9743 - loss: 0.0890

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9730 - loss: 0.0915

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9735 - loss: 0.0905

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9739 - loss: 0.0889

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9744 - loss: 0.0876

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9748 - loss: 0.0872

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9752 - loss: 0.0866

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9756 - loss: 0.0858

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9760 - loss: 0.0845

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9764 - loss: 0.0835

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9767 - loss: 0.0826

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9771 - loss: 0.0814

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9774 - loss: 0.0809

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9778 - loss: 0.0809

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9781 - loss: 0.0802

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9784 - loss: 0.0791

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - acc: 0.9787 - loss: 0.0786

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9790 - loss: 0.0777

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9779 - loss: 0.0813

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9769 - loss: 0.0838

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9772 - loss: 0.0829

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9762 - loss: 0.0848

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9765 - loss: 0.0837

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9768 - loss: 0.0837

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9758 - loss: 0.0856

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9748 - loss: 0.0879

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9739 - loss: 0.0880

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9742 - loss: 0.0872

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9733 - loss: 0.0890

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9725 - loss: 0.0897

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9716 - loss: 0.0925

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9696 - loss: 0.0969

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9688 - loss: 0.0991

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - acc: 0.9691 - loss: 0.0982

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9695 - loss: 0.0972

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9698 - loss: 0.0962

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9702 - loss: 0.0953

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9705 - loss: 0.0943

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9708 - loss: 0.0934

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9711 - loss: 0.0924

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9714 - loss: 0.0932

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9717 - loss: 0.0934

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9720 - loss: 0.0931

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9723 - loss: 0.0926

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9726 - loss: 0.0923

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9729 - loss: 0.0916

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9731 - loss: 0.0908

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9734 - loss: 0.0906

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9717 - loss: 0.0933

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9720 - loss: 0.0929

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - acc: 0.9722 - loss: 0.0923

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - acc: 0.9723 - loss: 0.0922 - val_acc: 0.9771 - val_loss: 0.1742

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 66ms/step - acc: 1.0000 - loss: 0.0203

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9333 - loss: 0.1116

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.9600 - loss: 0.0712

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.9429 - loss: 0.1129

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9333 - loss: 0.1404

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.9455 - loss: 0.1279

 13/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9538 - loss: 0.1107

 15/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9600 - loss: 0.0970

 17/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9529 - loss: 0.2000

 19/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9579 - loss: 0.1969

 21/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9619 - loss: 0.1783

 23/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9565 - loss: 0.1747

 25/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9520 - loss: 0.1799

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9481 - loss: 0.1830

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9517 - loss: 0.1727

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9548 - loss: 0.1697

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9576 - loss: 0.1609

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9600 - loss: 0.1634

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9622 - loss: 0.1550

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9641 - loss: 0.1492

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9659 - loss: 0.1430

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - acc: 0.9674 - loss: 0.1409

 45/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9689 - loss: 0.1361

 47/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9660 - loss: 0.1396

 49/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9673 - loss: 0.1348

 51/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9647 - loss: 0.1392

 53/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9623 - loss: 0.1420

 55/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9636 - loss: 0.1414

 57/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9649 - loss: 0.1364

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9661 - loss: 0.1321

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9672 - loss: 0.1289

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9683 - loss: 0.1248

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9692 - loss: 0.1224

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9701 - loss: 0.1188

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9710 - loss: 0.1159

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9718 - loss: 0.1132

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9726 - loss: 0.1112

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 30ms/step - acc: 0.9707 - loss: 0.1146

 77/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9714 - loss: 0.1118

 79/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9722 - loss: 0.1096

 81/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9728 - loss: 0.1072

 83/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9735 - loss: 0.1048

 85/210 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9718 - loss: 0.1089

 87/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9724 - loss: 0.1071

 89/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9708 - loss: 0.1072

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9692 - loss: 0.1103

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9699 - loss: 0.1083

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9705 - loss: 0.1060

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9691 - loss: 0.1058

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9697 - loss: 0.1037

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9703 - loss: 0.1021

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9709 - loss: 0.1009

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9714 - loss: 0.1004

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9720 - loss: 0.0991

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9725 - loss: 0.0977

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.9712 - loss: 0.1000

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.9717 - loss: 0.0997

115/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9722 - loss: 0.0980

117/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9726 - loss: 0.0965

119/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9731 - loss: 0.0950

121/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9736 - loss: 0.0950

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9740 - loss: 0.0942

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9744 - loss: 0.0928

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9748 - loss: 0.0916

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9752 - loss: 0.0904

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9756 - loss: 0.0891

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9759 - loss: 0.0884

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9763 - loss: 0.0874

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9766 - loss: 0.0864

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9770 - loss: 0.0853

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9773 - loss: 0.0845

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.9776 - loss: 0.0835

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9766 - loss: 0.0869

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9755 - loss: 0.0895

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9758 - loss: 0.0885

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9748 - loss: 0.0904

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9752 - loss: 0.0892

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9755 - loss: 0.0884

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9745 - loss: 0.0905

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9736 - loss: 0.0925

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9727 - loss: 0.0945

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9730 - loss: 0.0935

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9721 - loss: 0.0951

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9725 - loss: 0.0946

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9716 - loss: 0.0966

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9696 - loss: 0.1012

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9688 - loss: 0.1032

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - acc: 0.9691 - loss: 0.1023

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9695 - loss: 0.1013

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9698 - loss: 0.1002

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9702 - loss: 0.0993

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9705 - loss: 0.0983

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9708 - loss: 0.0974

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9711 - loss: 0.0964

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9714 - loss: 0.0964

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9717 - loss: 0.0966

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9720 - loss: 0.0967

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9723 - loss: 0.0962

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9726 - loss: 0.0954

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9729 - loss: 0.0948

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9731 - loss: 0.0941

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9734 - loss: 0.0939

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9717 - loss: 0.0957

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9720 - loss: 0.0953

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - acc: 0.9722 - loss: 0.0952

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - acc: 0.9723 - loss: 0.0951 - val_acc: 0.9771 - val_loss: 0.1705

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 31s 796ms/step

 9/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

17/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

25/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

33/41 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step

[[0.9495113 ]
 [0.9561962 ]
 [0.95756423]
 ...
 [0.9570198 ]
 [0.9636141 ]
 [0.9692811 ]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[817  32]
 [ 22 437]]
              precision    recall  f1-score   support

         0.0       0.97      0.96      0.97       849
         1.0       0.93      0.95      0.94       459

    accuracy                           0.96      1308
   macro avg       0.95      0.96      0.95      1308
weighted avg       0.96      0.96      0.96      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_31060\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [25]:
from keras.models import load_model

model.save('Multivariate_Occupancy_RNN_AdvancedTopics.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Multivariate_Occupancy_RNN_AdvancedTopics.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 48, 128)        │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 24, 60)         │        38,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 20)             │         4,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 135,449 (529.10 KB)

 Trainable params: 45,149 (176.36 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 90,300 (352.74 KB)