<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN_AdvancedTopics.ipynb)

# Multivariate Example (Advanced Topics)
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental data - let's see if Conv1D and MaxPooling1D can make an even better prediction (ConvLSTM).

**Common errors:** forgetting an activation function, not specifying the input shape (or mixing up the order!), not returning sequences when two layers (or accidentally return_sequences=True when only one layer!)

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset: UCI room-occupancy detection (Candanedo & Feldheim, 2016), originally from LuisM78's GitHub.
# We use the two real files - 8,143 minutes of training data (Feb 4-10) followed by 9,752 of test (Feb 11-18) -
# stacked in date order into one two-week series. (The 2-day datatest.txt slice was too short to learn from.)
base = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/main/OPIM5509_Module4_Files/data/"
df = pd.concat([pd.read_csv(base + "datatraining.txt"), pd.read_csv(base + "datatest2.txt")], ignore_index=True)
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)   # chronological - never shuffle a time series
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 17895 entries, 0 to 17894
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           17895 non-null  datetime64[us]
 1   Temperature    17895 non-null  float64
 2   Humidity       17895 non-null  float64
 3   Light          17895 non-null  float64
 4   CO2            17895 non-null  float64
 5   HumidityRatio  17895 non-null  float64
 6   Occupancy      17895 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 978.8 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,2015-02-04 17:51:00,23.180,27.272000,426.0,721.250000,0.004793,1
1,2015-02-04 17:51:59,23.150,27.267500,429.5,714.000000,0.004783,1
2,2015-02-04 17:53:00,23.150,27.245000,426.0,713.500000,0.004779,1
3,2015-02-04 17:54:00,23.150,27.200000,426.0,708.250000,0.004772,1
4,2015-02-04 17:55:00,23.100,27.200000,426.0,704.500000,0.004757,1
5,2015-02-04 17:55:59,23.100,27.200000,419.0,701.000000,0.004757,1
6,2015-02-04 17:57:00,23.100,27.200000,419.0,701.666667,0.004757,1
7,2015-02-04 17:57:59,23.100,27.200000,419.0,699.000000,0.004757,1
8,2015-02-04 17:58:59,23.100,27.200000,419.0,689.333333,0.004757,1
9,2015-02-04 18:00:00,23.075,27.175000,419.0,688.000000,0.004745,1
10,2015-02-04 18:01:00,23.075,27.150000,419.0,690.250000,0.004741,1
11,2015-02-04 18:02:00,23.100,27.100000,419.0,691.000000,0.004739,1
12,2015-02-04 18:03:00,23.100,27.166667,419.0,683.500000,0.004751,1
13,2015-02-04 18:04:00,23.050,27.150000,419.0,687.500000,0.004734,1
14,2015-02-04 18:04:59,23.000,27.125000,419.0,686.000000,0.004715,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    14117
1     3778
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(17895, 6)

   Temperature  Humidity  Light     CO2  HumidityRatio  Occupancy
0        23.18   27.2720  426.0  721.25       0.004793          1
1        23.15   27.2675  429.5  714.00       0.004783          1
2        23.15   27.2450  426.0  713.50       0.004779          1
3        23.15   27.2000  426.0  708.25       0.004772          1
4        23.10   27.2000  426.0  704.50       0.004757          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 50
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=50)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(17846, 50, 5)
(17846,)

In [11]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [12]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(17846, 50, 5) (8923, 50, 5) (8923, 50, 5)
(17846,) (8923,) (8923,)

# RNN one layer model (with Conv1D and pooling!)
With Conv1D and MaxPooling1D... don't forget that input shape needs to go in the first layer!

In [13]:
n_steps = X_train.shape[1] # lookback
n_features = X_train.shape[2] # columns

print(n_steps, n_features)

50 5

In [14]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(SimpleRNN(30, activation='relu', recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,890 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6:10 3s/step - acc: 0.4531 - loss: 51.5475

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.5996 - loss: 25.0984

 15/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.6771 - loss: 19.1927

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.7223 - loss: 14.4937

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.7641 - loss: 11.7268

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.7829 - loss: 10.5202

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.7965 - loss: 9.5632

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8091 - loss: 8.5377

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8176 - loss: 7.7900

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8276 - loss: 7.1405

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8362 - loss: 6.5917

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8398 - loss: 6.1827

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8427 - loss: 5.8097

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8459 - loss: 5.4909

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8502 - loss: 5.2026

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.8541 - loss: 4.9351

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - acc: 0.8563 - loss: 4.7882 - val_acc: 0.9938 - val_loss: 0.1418

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.8906 - loss: 0.9659

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9375 - loss: 0.5374

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9211 - loss: 0.7223

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9235 - loss: 0.6970

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9215 - loss: 0.7301

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9233 - loss: 0.6914

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9277 - loss: 0.6484

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9311 - loss: 0.5865

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9338 - loss: 0.5739

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9343 - loss: 0.5576

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9370 - loss: 0.5407

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9377 - loss: 0.5203

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9389 - loss: 0.5149

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9382 - loss: 0.5113

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9392 - loss: 0.5013 - val_acc: 0.9782 - val_loss: 0.1788

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - acc: 0.9219 - loss: 0.5617

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9629 - loss: 0.3279

 15/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9594 - loss: 0.3261

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9638 - loss: 0.3012

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9594 - loss: 0.3204

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9548 - loss: 0.3951

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9552 - loss: 0.4312

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9571 - loss: 0.4207

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9574 - loss: 0.4035

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9595 - loss: 0.3717

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9600 - loss: 0.3592

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9604 - loss: 0.3479

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9604 - loss: 0.3344

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9608 - loss: 0.3293

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9612 - loss: 0.3269

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9609 - loss: 0.3223

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9608 - loss: 0.3140

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9608 - loss: 0.3140 - val_acc: 0.9557 - val_loss: 0.2104

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step - acc: 0.9531 - loss: 0.4281

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9740 - loss: 0.2050

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9669 - loss: 0.2197

 25/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9638 - loss: 0.2764

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9593 - loss: 0.3000

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9582 - loss: 0.3499

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9606 - loss: 0.3204

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9621 - loss: 0.3058

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9631 - loss: 0.2804

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9639 - loss: 0.2774

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9635 - loss: 0.2750

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9640 - loss: 0.2713

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9644 - loss: 0.2591

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9652 - loss: 0.2523

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9642 - loss: 0.2674

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9632 - loss: 0.2697 - val_acc: 0.9664 - val_loss: 0.1846

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 12s 113ms/step - acc: 0.9844 - loss: 0.1017

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9809 - loss: 0.1676

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9648 - loss: 0.1845

 24/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9694 - loss: 0.1682

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9678 - loss: 0.1718

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9648 - loss: 0.2072

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9629 - loss: 0.2277

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9645 - loss: 0.2206

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9657 - loss: 0.2095

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.2014

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9665 - loss: 0.2014

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9671 - loss: 0.1954

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9658 - loss: 0.1949

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9662 - loss: 0.1980

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9650 - loss: 0.2066

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9653 - loss: 0.2060

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9653 - loss: 0.2060 - val_acc: 0.9339 - val_loss: 0.2304

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 65ms/step - acc: 0.9375 - loss: 0.1237

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9805 - loss: 0.1427

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9754 - loss: 0.1566

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9732 - loss: 0.1373

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9727 - loss: 0.1656

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9696 - loss: 0.1939

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9676 - loss: 0.1973

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9681 - loss: 0.1837

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9699 - loss: 0.1714

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9715 - loss: 0.1584

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9725 - loss: 0.1571

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9701 - loss: 0.1669

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9693 - loss: 0.1636

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9679 - loss: 0.1727

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9671 - loss: 0.1793

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9661 - loss: 0.1799 - val_acc: 0.9899 - val_loss: 0.0839

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9844 - loss: 0.1687

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9809 - loss: 0.1505

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9724 - loss: 0.1681

 24/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9733 - loss: 0.1644

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9736 - loss: 0.1419

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9744 - loss: 0.1667

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9731 - loss: 0.1559

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.1510

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9764 - loss: 0.1372

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9756 - loss: 0.1442

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9744 - loss: 0.1481

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9730 - loss: 0.1534

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9730 - loss: 0.1524

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9725 - loss: 0.1554

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9714 - loss: 0.1597

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9717 - loss: 0.1594 - val_acc: 0.9798 - val_loss: 0.1020

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 35s 323ms/step - acc: 0.9688 - loss: 0.1452

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9707 - loss: 0.1188

 15/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9719 - loss: 0.1602

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9688 - loss: 0.1564

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9661 - loss: 0.1685

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9657 - loss: 0.1797

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9665 - loss: 0.1789

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9691 - loss: 0.1624

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9718 - loss: 0.1574

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9727 - loss: 0.1499

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9734 - loss: 0.1523

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9726 - loss: 0.1510

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9733 - loss: 0.1485

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9742 - loss: 0.1435

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9742 - loss: 0.1420

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9737 - loss: 0.1439

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9742 - loss: 0.1412 - val_acc: 0.9944 - val_loss: 0.0513

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - acc: 0.9844 - loss: 0.1298

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9766 - loss: 0.1307

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9746 - loss: 0.1604

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9708 - loss: 0.1693

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9651 - loss: 0.1935

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9649 - loss: 0.2011

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9638 - loss: 0.2081

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9675 - loss: 0.1886

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9693 - loss: 0.1758

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9702 - loss: 0.1641

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9685 - loss: 0.1691

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9691 - loss: 0.1712

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9684 - loss: 0.1668

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9678 - loss: 0.1681

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9674 - loss: 0.1683

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9668 - loss: 0.1712

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9669 - loss: 0.1719 - val_acc: 0.9966 - val_loss: 0.0456

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - acc: 0.9688 - loss: 0.2009

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9826 - loss: 0.1106

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9792 - loss: 0.1382

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9751 - loss: 0.1556

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9692 - loss: 0.1796

 43/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9662 - loss: 0.1825

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9675 - loss: 0.1686

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9696 - loss: 0.1583

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9715 - loss: 0.1460

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9728 - loss: 0.1410

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9728 - loss: 0.1432

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9732 - loss: 0.1437

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9735 - loss: 0.1377

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9728 - loss: 0.1398

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9711 - loss: 0.1495

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9711 - loss: 0.1491 - val_acc: 0.9944 - val_loss: 0.0968

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - acc: 0.9375 - loss: 0.3865

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9757 - loss: 0.1508

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9752 - loss: 0.1527

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9742 - loss: 0.1401

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9732 - loss: 0.1418

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9709 - loss: 0.1458

 52/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9718 - loss: 0.1358

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9731 - loss: 0.1281

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9750 - loss: 0.1206

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9742 - loss: 0.1230

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9734 - loss: 0.1189

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.1208

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9722 - loss: 0.1288

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9702 - loss: 0.1326

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9702 - loss: 0.1346 - val_acc: 0.9961 - val_loss: 0.0657

Epoch 12/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - acc: 0.9531 - loss: 0.2704

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9688 - loss: 0.1380

 15/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9688 - loss: 0.1578

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9723 - loss: 0.1387

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9720 - loss: 0.1329

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9714 - loss: 0.1510

 43/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9702 - loss: 0.1476

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9727 - loss: 0.1414

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9735 - loss: 0.1308

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9751 - loss: 0.1247

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9745 - loss: 0.1249

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9756 - loss: 0.1249

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9757 - loss: 0.1196

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9759 - loss: 0.1228

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1259

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9744 - loss: 0.1259 - val_acc: 0.9944 - val_loss: 0.0662

Epoch 13/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 32s 288ms/step - acc: 0.9688 - loss: 0.2239

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9861 - loss: 0.0974

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9814 - loss: 0.1032

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9796 - loss: 0.1072

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9743 - loss: 0.1107

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9741 - loss: 0.1312

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9725 - loss: 0.1290

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1194

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9758 - loss: 0.1161

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9767 - loss: 0.1139

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9762 - loss: 0.1161

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9761 - loss: 0.1176

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9758 - loss: 0.1145

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9753 - loss: 0.1163

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1220

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9744 - loss: 0.1222 - val_acc: 0.9944 - val_loss: 0.0598

Epoch 14/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - acc: 0.9531 - loss: 0.3257

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9722 - loss: 0.1337

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9736 - loss: 0.1469

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9728 - loss: 0.1400

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9698 - loss: 0.1451

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9720 - loss: 0.1523

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9726 - loss: 0.1417

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9752 - loss: 0.1303

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9764 - loss: 0.1181

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9770 - loss: 0.1127

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9765 - loss: 0.1117

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9770 - loss: 0.1133

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9776 - loss: 0.1085

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9773 - loss: 0.1123

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9770 - loss: 0.1120

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9756 - loss: 0.1153

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9760 - loss: 0.1151 - val_acc: 0.9938 - val_loss: 0.0594

Epoch 15/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - acc: 0.9688 - loss: 0.2331

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9809 - loss: 0.1134

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9792 - loss: 0.1112

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9820 - loss: 0.1034

 34/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9793 - loss: 0.1045

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9781 - loss: 0.1097

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9778 - loss: 0.1058

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9787 - loss: 0.0972

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9796 - loss: 0.0927

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9785 - loss: 0.0938

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9783 - loss: 0.0956

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9788 - loss: 0.0928

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9787 - loss: 0.0921

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9771 - loss: 0.0984

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9773 - loss: 0.0984 - val_acc: 0.9950 - val_loss: 0.0406

Epoch 16/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9844 - loss: 0.1828

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9809 - loss: 0.1096

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.1208

 25/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9719 - loss: 0.1468

 34/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9701 - loss: 0.1398

 43/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9680 - loss: 0.1423

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9713 - loss: 0.1307

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9730 - loss: 0.1230

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.1131

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1103

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9758 - loss: 0.1127

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9762 - loss: 0.1062

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9761 - loss: 0.1088

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9762 - loss: 0.1063

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1117

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9755 - loss: 0.1107 - val_acc: 0.9961 - val_loss: 0.0347

Epoch 17/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - acc: 0.9844 - loss: 0.1158

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9809 - loss: 0.0837

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9785 - loss: 0.0990

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9776 - loss: 0.0994

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9734 - loss: 0.1026

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9742 - loss: 0.1079

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9723 - loss: 0.1161

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9741 - loss: 0.1099

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9756 - loss: 0.1030

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9766 - loss: 0.0979

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9766 - loss: 0.0992

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9758 - loss: 0.1019

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9764 - loss: 0.1026

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9764 - loss: 0.1012

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9757 - loss: 0.1061

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9753 - loss: 0.1083

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9752 - loss: 0.1078 - val_acc: 0.9961 - val_loss: 0.0303

Epoch 18/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - acc: 0.9688 - loss: 0.1571

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9826 - loss: 0.0884

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9775 - loss: 0.1149

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9810 - loss: 0.1085

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9766 - loss: 0.1161

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9751 - loss: 0.1310

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9734 - loss: 0.1339

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9755 - loss: 0.1229

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9758 - loss: 0.1155

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9776 - loss: 0.1070

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9774 - loss: 0.1073

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9775 - loss: 0.1100

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9778 - loss: 0.1050

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9780 - loss: 0.1023

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9776 - loss: 0.1025

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9763 - loss: 0.1055

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9767 - loss: 0.1050 - val_acc: 0.9955 - val_loss: 0.0378

Epoch 19/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - acc: 0.9688 - loss: 0.1410

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9792 - loss: 0.0888

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9743 - loss: 0.1138

 25/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9719 - loss: 0.1262

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9740 - loss: 0.1119

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9726 - loss: 0.1239

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9745 - loss: 0.1140

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9762 - loss: 0.1111

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9769 - loss: 0.1025

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9761 - loss: 0.1051

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9768 - loss: 0.1055

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9767 - loss: 0.1036

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9766 - loss: 0.1046

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9760 - loss: 0.1080

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9752 - loss: 0.1081 - val_acc: 0.9938 - val_loss: 0.0480

Epoch 19: early stopping

Restoring model weights from the end of the best epoch: 9.

In [15]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

  1/279 ━━━━━━━━━━━━━━━━━━━━ 1:20 289ms/step

 21/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 46/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 72/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 99/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

125/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

152/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

179/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

205/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

227/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

247/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

270/279 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

[[1.9347812e-11]
 [2.1251240e-11]
 [3.5617377e-11]
 ...
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]]

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(8923, 1), dtype=float32)

In [16]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

[[6879  209]
 [  21 1814]]

              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98      7088
         1.0       0.90      0.99      0.94      1835

    accuracy                           0.97      8923
   macro avg       0.95      0.98      0.96      8923
weighted avg       0.98      0.97      0.97      8923

In [17]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\774347038.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [18]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/279 ━━━━━━━━━━━━━━━━━━━━ 11s 42ms/step

 19/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 38/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 57/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 76/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 95/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

109/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

126/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

143/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

161/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

180/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

199/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

218/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

237/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

258/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

[[1.9347812e-11]
 [2.1251240e-11]
 [3.5617377e-11]
 ...
 [1.0000000e+00]
 [1.0000000e+00]
 [1.0000000e+00]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]
[[6879  209]
 [  21 1814]]

              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98      7088
         1.0       0.90      0.99      0.94      1835

    accuracy                           0.97      8923
   macro avg       0.95      0.98      0.96      8923
weighted avg       0.98      0.97      0.97      8923

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [19]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(SimpleRNN(30, return_sequences=True, recurrent_dropout=0.2))) # don't forget to return_sequences!
model.add(Bidirectional(SimpleRNN(30, recurrent_dropout=0.2)))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 60)         │         3,780 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 60)             │         5,460 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            61 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,813 (38.33 KB)

 Trainable params: 9,813 (38.33 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 15:47 9s/step - acc: 0.5938 - loss: 0.6534

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.7773 - loss: 0.4876

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.8058 - loss: 0.4279

 10/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.8234 - loss: 0.3905

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8269 - loss: 0.3671

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8359 - loss: 0.3493

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8512 - loss: 0.3253

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8587 - loss: 0.3066

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8637 - loss: 0.3028

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8672 - loss: 0.2942

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8674 - loss: 0.2925

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8681 - loss: 0.2895

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8708 - loss: 0.2851

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8730 - loss: 0.2784

 44/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8729 - loss: 0.2783

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.8743 - loss: 0.2742

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.8778 - loss: 0.2676

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8806 - loss: 0.2636

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8807 - loss: 0.2626

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8829 - loss: 0.2590

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.8839 - loss: 0.2583

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.8851 - loss: 0.2556

 64/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.8865 - loss: 0.2522

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8873 - loss: 0.2501

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8888 - loss: 0.2471

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8904 - loss: 0.2441

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8915 - loss: 0.2421

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8922 - loss: 0.2404

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8928 - loss: 0.2389

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8936 - loss: 0.2375

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8952 - loss: 0.2348

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8962 - loss: 0.2330

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8973 - loss: 0.2308

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.8986 - loss: 0.2287

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9004 - loss: 0.2259

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9028 - loss: 0.2228

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9032 - loss: 0.2218

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9037 - loss: 0.2216

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9049 - loss: 0.2189

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9065 - loss: 0.2160

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9059 - loss: 0.2173

112/112 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - acc: 0.9059 - loss: 0.2173 - val_acc: 0.9608 - val_loss: 0.0665

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 51ms/step - acc: 0.8750 - loss: 0.2518

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9141 - loss: 0.1898

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9129 - loss: 0.2095

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9172 - loss: 0.1977

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9123 - loss: 0.2066

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9072 - loss: 0.2126

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9128 - loss: 0.2067

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9162 - loss: 0.1957

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9181 - loss: 0.1913

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9149 - loss: 0.1929

 30/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9177 - loss: 0.1878

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9185 - loss: 0.1890

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9196 - loss: 0.1904

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9193 - loss: 0.1888

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9180 - loss: 0.1883

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9201 - loss: 0.1845

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9226 - loss: 0.1813

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9238 - loss: 0.1795

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9258 - loss: 0.1755

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9276 - loss: 0.1723

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9297 - loss: 0.1678

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9302 - loss: 0.1675

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9309 - loss: 0.1651

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9325 - loss: 0.1614

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9331 - loss: 0.1599

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9342 - loss: 0.1575

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9354 - loss: 0.1559

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9365 - loss: 0.1538

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9377 - loss: 0.1518

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9386 - loss: 0.1498

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9392 - loss: 0.1484

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9407 - loss: 0.1456

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9410 - loss: 0.1456

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9424 - loss: 0.1433

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9430 - loss: 0.1427

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9440 - loss: 0.1410

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9441 - loss: 0.1417

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9445 - loss: 0.1410

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9447 - loss: 0.1414

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9457 - loss: 0.1392

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - acc: 0.9461 - loss: 0.1387 - val_acc: 0.9720 - val_loss: 0.0654

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step - acc: 0.9844 - loss: 0.0676

  4/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9883 - loss: 0.0534

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9866 - loss: 0.0674

 10/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9828 - loss: 0.0664

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9792 - loss: 0.0707

 15/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9521 - loss: 0.1449

 18/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9366 - loss: 0.1651

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9353 - loss: 0.1762

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9244 - loss: 0.2136

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9247 - loss: 0.2144

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9244 - loss: 0.2113

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9168 - loss: 0.2168

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9185 - loss: 0.2110

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9211 - loss: 0.2053

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9211 - loss: 0.2074

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9215 - loss: 0.2063

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9219 - loss: 0.2028

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9246 - loss: 0.1970

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9270 - loss: 0.1924

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9294 - loss: 0.1867

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9303 - loss: 0.1843

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9324 - loss: 0.1788

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9335 - loss: 0.1761

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9339 - loss: 0.1737

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9349 - loss: 0.1704

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9354 - loss: 0.1689

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9363 - loss: 0.1667

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9377 - loss: 0.1638

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9390 - loss: 0.1612

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9407 - loss: 0.1582

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9416 - loss: 0.1558

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9427 - loss: 0.1542

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9422 - loss: 0.1542

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9427 - loss: 0.1535

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9411 - loss: 0.1591

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9407 - loss: 0.1605

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9394 - loss: 0.1638

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9377 - loss: 0.1669

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - acc: 0.9377 - loss: 0.1669 - val_acc: 0.9877 - val_loss: 0.0866

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - acc: 0.7812 - loss: 0.3275

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.8867 - loss: 0.1985

  6/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.8958 - loss: 0.1978

  9/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9184 - loss: 0.1690

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9284 - loss: 0.1600

 15/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9333 - loss: 0.1548

 18/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9384 - loss: 0.1472

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9464 - loss: 0.1346

 24/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9460 - loss: 0.1342

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9462 - loss: 0.1304

 30/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9479 - loss: 0.1257

 33/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9470 - loss: 0.1319

 36/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9462 - loss: 0.1368

 39/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9451 - loss: 0.1408

 42/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9457 - loss: 0.1409

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9451 - loss: 0.1436

 48/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9453 - loss: 0.1430

 51/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9452 - loss: 0.1429

 54/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9459 - loss: 0.1423

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9468 - loss: 0.1402

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9482 - loss: 0.1380

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9499 - loss: 0.1341

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9510 - loss: 0.1316

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9518 - loss: 0.1293

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9520 - loss: 0.1287

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9529 - loss: 0.1266

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9539 - loss: 0.1249

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9543 - loss: 0.1248

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9546 - loss: 0.1242

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9549 - loss: 0.1234

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9558 - loss: 0.1221

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9558 - loss: 0.1216

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9554 - loss: 0.1228

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9558 - loss: 0.1221

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9558 - loss: 0.1232

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9558 - loss: 0.1235

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9555 - loss: 0.1242

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9560 - loss: 0.1234

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - acc: 0.9559 - loss: 0.1247 - val_acc: 0.9188 - val_loss: 0.2030

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - acc: 0.9531 - loss: 0.1269

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9805 - loss: 0.0700

  6/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9740 - loss: 0.0947

  9/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9757 - loss: 0.0861

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9727 - loss: 0.0911

 15/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9698 - loss: 0.1008

 18/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9740 - loss: 0.0931

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9769 - loss: 0.0847

 24/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9753 - loss: 0.0855

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9757 - loss: 0.0838

 30/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9766 - loss: 0.0805

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9766 - loss: 0.0818

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9756 - loss: 0.0851

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9747 - loss: 0.0859

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9746 - loss: 0.0858

 42/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9732 - loss: 0.0898

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9722 - loss: 0.0923

 48/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9714 - loss: 0.0942

 51/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9706 - loss: 0.0957

 54/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9714 - loss: 0.0946

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9723 - loss: 0.0927

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9724 - loss: 0.0927

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9727 - loss: 0.0915

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9735 - loss: 0.0896

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9733 - loss: 0.0898

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9735 - loss: 0.0896

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9737 - loss: 0.0893

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9740 - loss: 0.0880

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9740 - loss: 0.0879

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9742 - loss: 0.0874

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9744 - loss: 0.0871

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9751 - loss: 0.0857

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9753 - loss: 0.0850

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9752 - loss: 0.0852

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9751 - loss: 0.0856

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9753 - loss: 0.0848

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9752 - loss: 0.0847

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9749 - loss: 0.0846

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9746 - loss: 0.0858

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9744 - loss: 0.0860

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9745 - loss: 0.0857

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9746 - loss: 0.0860

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - acc: 0.9746 - loss: 0.0860 - val_acc: 0.9742 - val_loss: 0.1012

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 75ms/step - acc: 0.9688 - loss: 0.0962

  4/112 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - acc: 0.9766 - loss: 0.0754

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9665 - loss: 0.1184

 10/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9672 - loss: 0.1109

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9635 - loss: 0.1255

 15/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9615 - loss: 0.1288

 17/112 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - acc: 0.9596 - loss: 0.1296

 20/112 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - acc: 0.9602 - loss: 0.1297

 22/112 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - acc: 0.9616 - loss: 0.1251

 24/112 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - acc: 0.9596 - loss: 0.1282

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9601 - loss: 0.1260

 29/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9612 - loss: 0.1219

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9624 - loss: 0.1199

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9621 - loss: 0.1226

 38/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9613 - loss: 0.1224

 41/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9634 - loss: 0.1167

 44/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9638 - loss: 0.1162

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9631 - loss: 0.1185

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9641 - loss: 0.1148

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9658 - loss: 0.1111

 56/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9668 - loss: 0.1084

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9677 - loss: 0.1067

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9685 - loss: 0.1045

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9697 - loss: 0.1011

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9701 - loss: 0.0992

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9705 - loss: 0.0986

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9713 - loss: 0.0965

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9716 - loss: 0.0957

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9717 - loss: 0.0953

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9721 - loss: 0.0938

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9727 - loss: 0.0921

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9725 - loss: 0.0926

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9712 - loss: 0.0948

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9701 - loss: 0.0977

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9681 - loss: 0.1011

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9661 - loss: 0.1041

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9646 - loss: 0.1069

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9641 - loss: 0.1082

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9628 - loss: 0.1103

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9615 - loss: 0.1126

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - acc: 0.9609 - loss: 0.1139 - val_acc: 0.9944 - val_loss: 0.0669

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - acc: 0.9062 - loss: 0.2039

  4/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9492 - loss: 0.1431

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9464 - loss: 0.1480

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9547 - loss: 0.1291

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9531 - loss: 0.1326

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9531 - loss: 0.1373

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9572 - loss: 0.1296

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9588 - loss: 0.1246

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9575 - loss: 0.1271

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9581 - loss: 0.1246

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9572 - loss: 0.1232

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9568 - loss: 0.1259

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9578 - loss: 0.1244

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9559 - loss: 0.1293

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9539 - loss: 0.1356

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9501 - loss: 0.1474

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9497 - loss: 0.1478

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9484 - loss: 0.1500

 56/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9459 - loss: 0.1529

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9441 - loss: 0.1556

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9435 - loss: 0.1555

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9421 - loss: 0.1581

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9423 - loss: 0.1574

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9404 - loss: 0.1607

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9402 - loss: 0.1607

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9397 - loss: 0.1615

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9389 - loss: 0.1627

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9384 - loss: 0.1629

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9388 - loss: 0.1613

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9389 - loss: 0.1608

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9390 - loss: 0.1601

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9387 - loss: 0.1603

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9399 - loss: 0.1588

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9406 - loss: 0.1579

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9404 - loss: 0.1582

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9412 - loss: 0.1567

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9411 - loss: 0.1567

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9413 - loss: 0.1563

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9413 - loss: 0.1563 - val_acc: 0.9810 - val_loss: 0.1028

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 72ms/step - acc: 0.9375 - loss: 0.1797

  4/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9648 - loss: 0.1097

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9598 - loss: 0.1146

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9672 - loss: 0.1021

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9627 - loss: 0.1088

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9668 - loss: 0.1035

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9655 - loss: 0.1097

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9638 - loss: 0.1140

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9519 - loss: 0.1444

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9464 - loss: 0.1557

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9435 - loss: 0.1581

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9344 - loss: 0.1720

 38/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9256 - loss: 0.1825

 41/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9238 - loss: 0.1842

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9177 - loss: 0.1918

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9136 - loss: 0.1984

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9114 - loss: 0.2005

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9094 - loss: 0.2023

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9095 - loss: 0.2013

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9095 - loss: 0.2003

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9093 - loss: 0.2001

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9106 - loss: 0.1976

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9106 - loss: 0.1989

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9106 - loss: 0.2014

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9121 - loss: 0.1990

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9117 - loss: 0.2000

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9116 - loss: 0.2003

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9131 - loss: 0.1989

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9134 - loss: 0.1986

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9140 - loss: 0.1976

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9142 - loss: 0.1967

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9145 - loss: 0.1964

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9151 - loss: 0.1962

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9154 - loss: 0.1951

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9149 - loss: 0.1954

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9148 - loss: 0.1950

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9150 - loss: 0.1951 - val_acc: 0.9955 - val_loss: 0.0556

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - acc: 0.9375 - loss: 0.1653

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9609 - loss: 0.1215

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9509 - loss: 0.1436

  9/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9583 - loss: 0.1292

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9583 - loss: 0.1290

 14/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9587 - loss: 0.1300

 17/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9586 - loss: 0.1253

 20/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9625 - loss: 0.1199

 23/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9640 - loss: 0.1177

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9621 - loss: 0.1199

 29/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9612 - loss: 0.1208

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9595 - loss: 0.1257

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9576 - loss: 0.1303

 38/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9535 - loss: 0.1379

 41/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9550 - loss: 0.1339

 44/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9528 - loss: 0.1406

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9521 - loss: 0.1409

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9528 - loss: 0.1390

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9534 - loss: 0.1382

 56/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9540 - loss: 0.1367

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9547 - loss: 0.1358

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9559 - loss: 0.1321

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9577 - loss: 0.1278

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9584 - loss: 0.1254

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9586 - loss: 0.1233

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9589 - loss: 0.1232

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9599 - loss: 0.1212

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9595 - loss: 0.1220

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9597 - loss: 0.1219

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9594 - loss: 0.1222

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9599 - loss: 0.1212

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9595 - loss: 0.1227

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9595 - loss: 0.1229

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9591 - loss: 0.1233

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9593 - loss: 0.1231

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9590 - loss: 0.1237

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9591 - loss: 0.1231

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9587 - loss: 0.1231

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9594 - loss: 0.1214

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - acc: 0.9595 - loss: 0.1212 - val_acc: 0.9742 - val_loss: 0.1041

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - acc: 0.9844 - loss: 0.0984

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9922 - loss: 0.0593

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9821 - loss: 0.0856

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9844 - loss: 0.0788

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9772 - loss: 0.0857

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9785 - loss: 0.0813

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9819 - loss: 0.0741

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9815 - loss: 0.0760

 23/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9817 - loss: 0.0751

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9814 - loss: 0.0756

 29/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9811 - loss: 0.0731

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - acc: 0.9814 - loss: 0.0730

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9812 - loss: 0.0745

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9793 - loss: 0.0767

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9785 - loss: 0.0778

 42/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9788 - loss: 0.0777

 44/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9783 - loss: 0.0781

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9774 - loss: 0.0786

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9778 - loss: 0.0769

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9776 - loss: 0.0766

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9767 - loss: 0.0784

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9766 - loss: 0.0791

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9768 - loss: 0.0796

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9777 - loss: 0.0777

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9782 - loss: 0.0766

 68/112 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - acc: 0.9782 - loss: 0.0762

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9781 - loss: 0.0758

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9782 - loss: 0.0753

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9780 - loss: 0.0763

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9780 - loss: 0.0763

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9781 - loss: 0.0764

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9785 - loss: 0.0755

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9790 - loss: 0.0745

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9792 - loss: 0.0739

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9792 - loss: 0.0735

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9793 - loss: 0.0729

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9795 - loss: 0.0724

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9793 - loss: 0.0730

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9793 - loss: 0.0733

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9793 - loss: 0.0729

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - acc: 0.9797 - loss: 0.0719

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - acc: 0.9795 - loss: 0.0723 - val_acc: 0.9765 - val_loss: 0.0952

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - acc: 0.9844 - loss: 0.0621

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9922 - loss: 0.0430

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9888 - loss: 0.0547

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9891 - loss: 0.0526

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9868 - loss: 0.0557

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9854 - loss: 0.0584

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9877 - loss: 0.0521

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9865 - loss: 0.0558

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9850 - loss: 0.0571

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9860 - loss: 0.0532

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9859 - loss: 0.0534

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9853 - loss: 0.0564

 36/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9839 - loss: 0.0594

 38/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9827 - loss: 0.0618

 41/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9836 - loss: 0.0588

 44/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9840 - loss: 0.0591

 47/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9840 - loss: 0.0576

 50/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9844 - loss: 0.0563

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9832 - loss: 0.0579

 56/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9824 - loss: 0.0594

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9828 - loss: 0.0594

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9829 - loss: 0.0594

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9837 - loss: 0.0578

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9828 - loss: 0.0607

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9817 - loss: 0.0624

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9818 - loss: 0.0636

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9807 - loss: 0.0681

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9802 - loss: 0.0688

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9799 - loss: 0.0700

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9788 - loss: 0.0726

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9783 - loss: 0.0739

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9774 - loss: 0.0774

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9760 - loss: 0.0792

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9749 - loss: 0.0812

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9746 - loss: 0.0825

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9733 - loss: 0.0858

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9734 - loss: 0.0860

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9721 - loss: 0.0885

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9718 - loss: 0.0893

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9717 - loss: 0.0896 - val_acc: 0.9944 - val_loss: 0.0421

Epoch 12/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - acc: 0.9531 - loss: 0.1367

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9766 - loss: 0.0905

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9799 - loss: 0.0874

  9/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9826 - loss: 0.0782

 12/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9818 - loss: 0.0751

 15/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9802 - loss: 0.0785

 18/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9826 - loss: 0.0718

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9851 - loss: 0.0639

 24/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9831 - loss: 0.0709

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9832 - loss: 0.0681

 30/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9828 - loss: 0.0672

 33/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9801 - loss: 0.0714

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9790 - loss: 0.0740

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9785 - loss: 0.0742

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9777 - loss: 0.0751

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9778 - loss: 0.0762

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9776 - loss: 0.0763

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9770 - loss: 0.0770

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9763 - loss: 0.0797

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9756 - loss: 0.0809

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9755 - loss: 0.0812

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9746 - loss: 0.0839

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9749 - loss: 0.0834

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9748 - loss: 0.0838

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9752 - loss: 0.0833

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9758 - loss: 0.0829

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9762 - loss: 0.0827

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9763 - loss: 0.0826

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9760 - loss: 0.0831

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9762 - loss: 0.0825

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9765 - loss: 0.0817

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9768 - loss: 0.0807

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9766 - loss: 0.0808

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9767 - loss: 0.0804

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9769 - loss: 0.0795

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9771 - loss: 0.0786

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9770 - loss: 0.0788

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9769 - loss: 0.0790

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9767 - loss: 0.0788

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9772 - loss: 0.0773

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - acc: 0.9770 - loss: 0.0776 - val_acc: 0.9143 - val_loss: 0.2585

Epoch 13/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 51ms/step - acc: 0.9844 - loss: 0.0742

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9844 - loss: 0.0660

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9866 - loss: 0.0678

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9875 - loss: 0.0617

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9808 - loss: 0.0777

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9766 - loss: 0.0868

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9786 - loss: 0.0830

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9780 - loss: 0.0833

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9756 - loss: 0.0886

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9743 - loss: 0.0892

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9728 - loss: 0.0920

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9724 - loss: 0.0949

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9730 - loss: 0.0939

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9734 - loss: 0.0924

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9731 - loss: 0.0929

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9721 - loss: 0.0939

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9729 - loss: 0.0916

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9733 - loss: 0.0898

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9736 - loss: 0.0885

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9741 - loss: 0.0861

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9739 - loss: 0.0870

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9744 - loss: 0.0856

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9743 - loss: 0.0860

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9743 - loss: 0.0850

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9747 - loss: 0.0842

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9747 - loss: 0.0842

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9739 - loss: 0.0857

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9735 - loss: 0.0863

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9739 - loss: 0.0853

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9745 - loss: 0.0841

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9748 - loss: 0.0832

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9749 - loss: 0.0833

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9749 - loss: 0.0837

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9750 - loss: 0.0832

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9747 - loss: 0.0837

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9745 - loss: 0.0847

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9739 - loss: 0.0856

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9741 - loss: 0.0854

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9742 - loss: 0.0848

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9744 - loss: 0.0841

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9744 - loss: 0.0841 - val_acc: 0.8913 - val_loss: 0.2961

Epoch 14/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9844 - loss: 0.0756

  5/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9812 - loss: 0.0657

  9/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9861 - loss: 0.0625

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9772 - loss: 0.0826

 17/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9761 - loss: 0.0864

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9807 - loss: 0.0746

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9794 - loss: 0.0744

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9805 - loss: 0.0709

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9810 - loss: 0.0698

 36/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9800 - loss: 0.0721

 39/112 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - acc: 0.9800 - loss: 0.0713

 42/112 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9803 - loss: 0.0703

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9802 - loss: 0.0690

 48/112 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - acc: 0.9808 - loss: 0.0669

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9816 - loss: 0.0652

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9809 - loss: 0.0659

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9814 - loss: 0.0650

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - acc: 0.9818 - loss: 0.0649

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9814 - loss: 0.0670

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9818 - loss: 0.0657

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9812 - loss: 0.0663

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9809 - loss: 0.0666

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9810 - loss: 0.0665

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9814 - loss: 0.0655

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9815 - loss: 0.0655

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9814 - loss: 0.0655

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9817 - loss: 0.0643

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9819 - loss: 0.0638

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9822 - loss: 0.0629

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - acc: 0.9819 - loss: 0.0636

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9821 - loss: 0.0629

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9823 - loss: 0.0625

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9819 - loss: 0.0634

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9817 - loss: 0.0639

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9816 - loss: 0.0638

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9820 - loss: 0.0628

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9819 - loss: 0.0630 - val_acc: 0.9821 - val_loss: 0.0514

Epoch 15/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - acc: 0.9844 - loss: 0.0563

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9922 - loss: 0.0435

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9888 - loss: 0.0555

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9891 - loss: 0.0515

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9880 - loss: 0.0504

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9873 - loss: 0.0545

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9893 - loss: 0.0482

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9893 - loss: 0.0473

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9887 - loss: 0.0487

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9894 - loss: 0.0460

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9889 - loss: 0.0459

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9881 - loss: 0.0477

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9869 - loss: 0.0499

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9867 - loss: 0.0512

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9873 - loss: 0.0507

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9874 - loss: 0.0502

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9879 - loss: 0.0491

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9880 - loss: 0.0485

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9878 - loss: 0.0487

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9881 - loss: 0.0476

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9882 - loss: 0.0479

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9887 - loss: 0.0462

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9883 - loss: 0.0474

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9879 - loss: 0.0471

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9878 - loss: 0.0470

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9874 - loss: 0.0475

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9873 - loss: 0.0480

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9872 - loss: 0.0482

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9875 - loss: 0.0480

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9877 - loss: 0.0474

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9876 - loss: 0.0477

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9872 - loss: 0.0480

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9872 - loss: 0.0478

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9870 - loss: 0.0482

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9868 - loss: 0.0492

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9861 - loss: 0.0502

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - acc: 0.9861 - loss: 0.0500

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9860 - loss: 0.0506 - val_acc: 0.9401 - val_loss: 0.2287

Epoch 16/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - acc: 0.9688 - loss: 0.0852

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9766 - loss: 0.0663

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9799 - loss: 0.0657

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9828 - loss: 0.0597

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9772 - loss: 0.0798

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9746 - loss: 0.0920

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9770 - loss: 0.0871

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9759 - loss: 0.0891

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9731 - loss: 0.0931

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9749 - loss: 0.0879

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9743 - loss: 0.0881

 34/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9747 - loss: 0.0878

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9738 - loss: 0.0875

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9738 - loss: 0.0873

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9753 - loss: 0.0843

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9760 - loss: 0.0824

 48/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9766 - loss: 0.0803

 51/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9773 - loss: 0.0781

 54/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9774 - loss: 0.0763

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9784 - loss: 0.0736

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9787 - loss: 0.0733

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9797 - loss: 0.0707

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9802 - loss: 0.0699

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9797 - loss: 0.0696

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9803 - loss: 0.0680

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9805 - loss: 0.0680

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9804 - loss: 0.0679

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9804 - loss: 0.0679

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9805 - loss: 0.0675

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9806 - loss: 0.0675

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9810 - loss: 0.0669

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9811 - loss: 0.0666

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9809 - loss: 0.0667

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9812 - loss: 0.0658

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9814 - loss: 0.0653

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9814 - loss: 0.0656

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9814 - loss: 0.0662

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9809 - loss: 0.0666

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9811 - loss: 0.0656

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9811 - loss: 0.0655 - val_acc: 0.9737 - val_loss: 0.0903

Epoch 17/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - acc: 0.9844 - loss: 0.0849

  4/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9844 - loss: 0.0495

  7/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9866 - loss: 0.0589

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9875 - loss: 0.0554

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9868 - loss: 0.0559

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9863 - loss: 0.0589

 19/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9885 - loss: 0.0520

 22/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9886 - loss: 0.0501

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9881 - loss: 0.0497

 28/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9888 - loss: 0.0467

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9883 - loss: 0.0466

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9871 - loss: 0.0495

 37/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9865 - loss: 0.0502

 40/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9863 - loss: 0.0511

 43/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9869 - loss: 0.0502

 46/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9871 - loss: 0.0502

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9872 - loss: 0.0490

 52/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9865 - loss: 0.0510

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9861 - loss: 0.0511

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9860 - loss: 0.0510

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9859 - loss: 0.0522

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9866 - loss: 0.0503

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9867 - loss: 0.0507

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9864 - loss: 0.0503

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9861 - loss: 0.0501

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9860 - loss: 0.0510

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9854 - loss: 0.0533

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9838 - loss: 0.0581

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9823 - loss: 0.0614

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9815 - loss: 0.0636

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9793 - loss: 0.0674

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9782 - loss: 0.0693

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9769 - loss: 0.0732

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9763 - loss: 0.0747

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9752 - loss: 0.0780

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9749 - loss: 0.0786

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9737 - loss: 0.0808

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9727 - loss: 0.0828

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - acc: 0.9723 - loss: 0.0834 - val_acc: 0.9927 - val_loss: 0.0525

Epoch 18/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - acc: 0.9375 - loss: 0.2161

  4/112 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9688 - loss: 0.1136

  7/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9643 - loss: 0.1206

 10/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9703 - loss: 0.0997

 14/112 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - acc: 0.9632 - loss: 0.1144

 17/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9651 - loss: 0.1123

 20/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9633 - loss: 0.1183

 23/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9586 - loss: 0.1291

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - acc: 0.9495 - loss: 0.1525

 29/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9456 - loss: 0.1565

 32/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9380 - loss: 0.1633

 35/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9371 - loss: 0.1650

 38/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9330 - loss: 0.1709

 41/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9348 - loss: 0.1682

 45/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9337 - loss: 0.1723

 48/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9342 - loss: 0.1713

 51/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9338 - loss: 0.1700

 54/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9340 - loss: 0.1705

 56/112 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9350 - loss: 0.1689

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9367 - loss: 0.1664

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9375 - loss: 0.1647

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9387 - loss: 0.1624

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9396 - loss: 0.1601

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9404 - loss: 0.1579

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9405 - loss: 0.1568

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9423 - loss: 0.1532

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9441 - loss: 0.1501

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9456 - loss: 0.1469

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9470 - loss: 0.1437

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9483 - loss: 0.1405

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9495 - loss: 0.1379

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9508 - loss: 0.1351

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9515 - loss: 0.1335

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9525 - loss: 0.1309

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9531 - loss: 0.1301

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9539 - loss: 0.1284

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9541 - loss: 0.1282

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9553 - loss: 0.1252

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9557 - loss: 0.1243 - val_acc: 0.9832 - val_loss: 0.0389

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 8.

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/279 ━━━━━━━━━━━━━━━━━━━━ 4:21 940ms/step

 10/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 19/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 29/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 38/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 47/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 55/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 64/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 73/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 82/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 90/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

 99/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

107/279 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

115/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

123/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

131/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

139/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

148/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

157/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

167/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

177/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

187/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

197/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

207/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

218/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

229/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

239/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

250/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

260/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

269/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

277/279 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step

[[0.00091724]
 [0.00091724]
 [0.00091724]
 ...
 [0.22778545]
 [0.30025035]
 [0.3288676 ]]

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[6744  344]
 [  35 1800]]
              precision    recall  f1-score   support

         0.0       0.99      0.95      0.97      7088
         1.0       0.84      0.98      0.90      1835

    accuracy                           0.96      8923
   macro avg       0.92      0.97      0.94      8923
weighted avg       0.96      0.96      0.96      8923

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# define shape
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(LSTM(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 30)             │         7,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,103 (31.65 KB)

 Trainable params: 8,103 (31.65 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6:40 4s/step - acc: 0.1719 - loss: 230.9068

  5/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.1688 - loss: 121.1880

  9/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.4392 - loss: 88.2860

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.5373 - loss: 76.4578

 18/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.5998 - loss: 65.1826

 23/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.6379 - loss: 56.5669

 27/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.6615 - loss: 50.4766

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.6787 - loss: 44.3798

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7023 - loss: 39.4771

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7262 - loss: 35.3761

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7477 - loss: 32.0442

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7632 - loss: 29.7895

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7804 - loss: 27.3978

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.7948 - loss: 25.4004

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8078 - loss: 23.7662

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8173 - loss: 22.3781

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8235 - loss: 21.3995

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8303 - loss: 20.4882

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8362 - loss: 19.6537

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8421 - loss: 18.8932

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8458 - loss: 18.2014

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8497 - loss: 17.5055

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8521 - loss: 16.9242

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8559 - loss: 16.2542

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8587 - loss: 15.7219

112/112 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - acc: 0.8591 - loss: 15.4472 - val_acc: 0.9552 - val_loss: 1.8736

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - acc: 0.8906 - loss: 7.1529

  7/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9174 - loss: 4.1051

 13/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9279 - loss: 3.9194

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9334 - loss: 3.8246

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9333 - loss: 3.8742

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9307 - loss: 3.9765

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9272 - loss: 4.4472

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9240 - loss: 4.3048

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9234 - loss: 4.2425

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9241 - loss: 4.1794

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9271 - loss: 3.9369

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9286 - loss: 3.8957

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9283 - loss: 3.8334

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9273 - loss: 3.7207

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9258 - loss: 3.8707

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9261 - loss: 3.8406

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9271 - loss: 3.7862

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9276 - loss: 3.8870

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9290 - loss: 3.8118

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9292 - loss: 3.7738

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9285 - loss: 3.7507

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9266 - loss: 3.7307 - val_acc: 0.8672 - val_loss: 3.1595

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step - acc: 0.8438 - loss: 6.3700

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8333 - loss: 5.5359

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8438 - loss: 5.2243

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8633 - loss: 4.7162

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8869 - loss: 4.1243

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8948 - loss: 3.9562

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8967 - loss: 3.9577

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9010 - loss: 3.9687

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9059 - loss: 3.9532

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9062 - loss: 3.7937

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9081 - loss: 3.7374

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9082 - loss: 3.6559

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9115 - loss: 3.4829

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9143 - loss: 3.4038

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9167 - loss: 3.3080

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9177 - loss: 3.2280

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9175 - loss: 3.2347

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9185 - loss: 3.1604

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9199 - loss: 3.1413

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9219 - loss: 3.1258

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9233 - loss: 3.0655

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9247 - loss: 2.9805

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9235 - loss: 2.9584

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9235 - loss: 2.9584 - val_acc: 0.9541 - val_loss: 1.2474

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.8438 - loss: 4.1490

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9141 - loss: 1.7480

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9190 - loss: 1.8374

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9229 - loss: 1.9505

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9345 - loss: 1.8475

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9339 - loss: 1.8427

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9304 - loss: 1.9046

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9310 - loss: 1.8913

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9310 - loss: 1.9213

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9297 - loss: 1.8548

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9280 - loss: 1.9020

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9298 - loss: 1.8221

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9320 - loss: 1.8024

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9339 - loss: 1.7571

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9333 - loss: 1.7370

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9322 - loss: 1.7505

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9315 - loss: 1.7563

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9324 - loss: 1.7462

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9338 - loss: 1.7112

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9346 - loss: 1.6909

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9342 - loss: 1.6929

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9337 - loss: 1.6996 - val_acc: 0.9451 - val_loss: 1.3073

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step - acc: 0.9062 - loss: 2.0684

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9323 - loss: 0.9778

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9304 - loss: 1.1355

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9316 - loss: 1.2520

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9405 - loss: 1.2320

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9393 - loss: 1.2835

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9360 - loss: 1.3501

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9366 - loss: 1.3600

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9364 - loss: 1.4895

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9351 - loss: 1.4210

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9344 - loss: 1.4671

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9347 - loss: 1.4334

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9372 - loss: 1.3708

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9382 - loss: 1.3666

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9391 - loss: 1.3421

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9386 - loss: 1.3303

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9383 - loss: 1.3137

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9381 - loss: 1.3223

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9371 - loss: 1.3308

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9375 - loss: 1.3235

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9388 - loss: 1.2877

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9397 - loss: 1.2881

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9398 - loss: 1.2750

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9392 - loss: 1.2789

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9388 - loss: 1.2873 - val_acc: 0.9451 - val_loss: 1.1836

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - acc: 0.8438 - loss: 1.5669

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9193 - loss: 0.7687

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9361 - loss: 0.8151

 15/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9365 - loss: 0.9545

 20/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9438 - loss: 0.8199

 25/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9419 - loss: 0.9786

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9401 - loss: 0.9944

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9384 - loss: 1.0308

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9383 - loss: 1.0498

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9389 - loss: 1.0157

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9384 - loss: 1.0492

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9386 - loss: 1.0170

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9414 - loss: 0.9726

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9423 - loss: 0.9679

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9422 - loss: 0.9588

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9417 - loss: 0.9573

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9410 - loss: 0.9594

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9406 - loss: 0.9672

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9403 - loss: 0.9526

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9410 - loss: 0.9400

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9416 - loss: 0.9360

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9420 - loss: 0.9276

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9417 - loss: 0.9337

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9414 - loss: 0.9426 - val_acc: 0.9440 - val_loss: 1.1237

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step - acc: 0.8750 - loss: 1.0657

  5/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9344 - loss: 0.4911

  9/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9375 - loss: 0.6131

 13/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9435 - loss: 0.5989

 17/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9439 - loss: 0.6617

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9479 - loss: 0.6632

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9465 - loss: 0.7189

 31/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9420 - loss: 0.7498

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9411 - loss: 0.7803

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9395 - loss: 0.8000

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9410 - loss: 0.7720

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9409 - loss: 0.8136

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9412 - loss: 0.7918

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9432 - loss: 0.7610

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9440 - loss: 0.7573

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9445 - loss: 0.7392

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9443 - loss: 0.7292

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9449 - loss: 0.7306

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9439 - loss: 0.7493

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9446 - loss: 0.7525

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9461 - loss: 0.7264

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9471 - loss: 0.7279

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9463 - loss: 0.7272

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9459 - loss: 0.7284

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9456 - loss: 0.7356 - val_acc: 0.9417 - val_loss: 1.0348

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - acc: 0.8750 - loss: 0.7242

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9505 - loss: 0.3960

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9545 - loss: 0.4471

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9502 - loss: 0.5446

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9561 - loss: 0.5086

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9531 - loss: 0.5534

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9501 - loss: 0.5797

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9492 - loss: 0.5998

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9470 - loss: 0.6320

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9490 - loss: 0.5952

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9476 - loss: 0.6318

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9475 - loss: 0.6075

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9490 - loss: 0.5863

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9496 - loss: 0.5803

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9493 - loss: 0.5740

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9493 - loss: 0.5598

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9492 - loss: 0.5710

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9494 - loss: 0.5801

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9498 - loss: 0.5766

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9510 - loss: 0.5669

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9520 - loss: 0.5614

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9516 - loss: 0.5615

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9508 - loss: 0.5697

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9504 - loss: 0.5748 - val_acc: 0.9429 - val_loss: 0.8358

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step - acc: 0.8594 - loss: 0.6871

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9479 - loss: 0.3680

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9531 - loss: 0.3898

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9502 - loss: 0.4589

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9561 - loss: 0.4183

 26/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9537 - loss: 0.4384

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9506 - loss: 0.4644

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9505 - loss: 0.4779

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9498 - loss: 0.4924

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9499 - loss: 0.4892

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9491 - loss: 0.4936

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9503 - loss: 0.4740

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9512 - loss: 0.4580

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9510 - loss: 0.4459

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9509 - loss: 0.4491

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9509 - loss: 0.4537

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9521 - loss: 0.4475

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.4445

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9539 - loss: 0.4426

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9534 - loss: 0.4480

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9533 - loss: 0.4507

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.9533 - loss: 0.4507 - val_acc: 0.9423 - val_loss: 0.7710

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - acc: 0.9531 - loss: 0.3567

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9609 - loss: 0.2682

 12/112 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.9570 - loss: 0.2924

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9568 - loss: 0.3364

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.9588 - loss: 0.3342

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9560 - loss: 0.3400

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9541 - loss: 0.3563

 36/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9531 - loss: 0.3687

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9516 - loss: 0.3905

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9528 - loss: 0.3743

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9509 - loss: 0.3998

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9517 - loss: 0.3861

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9531 - loss: 0.3738

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9536 - loss: 0.3648

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9538 - loss: 0.3554

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9531 - loss: 0.3523

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9535 - loss: 0.3513

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9520 - loss: 0.3623

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9528 - loss: 0.3623

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9543 - loss: 0.3491

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9552 - loss: 0.3549

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9552 - loss: 0.3578

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9549 - loss: 0.3595

112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.9550 - loss: 0.3611 - val_acc: 0.9429 - val_loss: 0.7136

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step - acc: 0.9531 - loss: 0.3167

  6/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9635 - loss: 0.2422

 11/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9602 - loss: 0.2715

 16/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9570 - loss: 0.3142

 21/112 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.9621 - loss: 0.2748

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9615 - loss: 0.2807

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9572 - loss: 0.3125

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.9576 - loss: 0.3141

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9555 - loss: 0.3366

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9566 - loss: 0.3177

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9544 - loss: 0.3417

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9543 - loss: 0.3340

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9555 - loss: 0.3277

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9560 - loss: 0.3160

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9556 - loss: 0.3101

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9552 - loss: 0.3099

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9555 - loss: 0.3109

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9555 - loss: 0.3155

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9569 - loss: 0.3127

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9583 - loss: 0.3143

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9583 - loss: 0.3157

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.9576 - loss: 0.3245

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.9573 - loss: 0.3271 - val_acc: 0.9501 - val_loss: 0.5468

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/279 ━━━━━━━━━━━━━━━━━━━━ 59s 213ms/step

 16/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 32/279 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 45/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

 59/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

 73/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

 86/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

100/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

116/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

132/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

147/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

160/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

174/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

188/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

198/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

210/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

222/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

236/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

248/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

260/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

273/279 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step

[[1.0889709e-20]
 [1.1012359e-20]
 [1.3084985e-20]
 ...
 [0.0000000e+00]
 [0.0000000e+00]
 [0.0000000e+00]]

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[7019   69]
 [ 279 1556]]
              precision    recall  f1-score   support

         0.0       0.96      0.99      0.98      7088
         1.0       0.96      0.85      0.90      1835

    accuracy                           0.96      8923
   macro avg       0.96      0.92      0.94      8923
weighted avg       0.96      0.96      0.96      8923

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM two layer model

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(Conv1D(filters=128, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(LSTM(30,
                            return_sequences=True, # remember, if stacking layers, you need to return sequences!
                            activation='relu',
                            recurrent_dropout=0.2)))
model.add(GRU(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 48, 128)        │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 24, 60)         │        38,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 20)             │         4,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 45,149 (176.36 KB)

 Trainable params: 45,149 (176.36 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 21:04 11s/step - acc: 0.5469 - loss: 186.6793

  3/112 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - acc: 0.4792 - loss: 128.2205

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - acc: 0.4906 - loss: 102.9998

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.4888 - loss: 97.8645

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.4792 - loss: 96.8041

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.4673 - loss: 88.5287

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.4495 - loss: 80.1805

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.4198 - loss: 82.5387

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.4026 - loss: 78.2911

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.4013 - loss: 77.5471

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.3884 - loss: 73.4475

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.3852 - loss: 70.5549

 25/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.3825 - loss: 67.3253

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.3900 - loss: 63.5642

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.3831 - loss: 61.2421

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.3836 - loss: 58.3973

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.3793 - loss: 55.9985

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.3835 - loss: 53.4892

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.3872 - loss: 51.2402

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.3998 - loss: 49.1595

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.4093 - loss: 56.1866

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.4201 - loss: 54.4851

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.4274 - loss: 52.9767

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.4348 - loss: 51.7926

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.4385 - loss: 51.0737

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4420 - loss: 50.2375

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4450 - loss: 49.3508

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4473 - loss: 48.4678

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4422 - loss: 47.0550

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4403 - loss: 45.7041

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4342 - loss: 44.5913

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.4296 - loss: 43.5685

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4252 - loss: 42.5284

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4261 - loss: 41.3719

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4320 - loss: 40.8534

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4387 - loss: 39.8910

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4461 - loss: 39.0605

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4527 - loss: 38.3055

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.4585 - loss: 37.7212

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4618 - loss: 37.3188

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4692 - loss: 36.6071

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4772 - loss: 36.0462

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4818 - loss: 35.6196

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4846 - loss: 35.3460

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4869 - loss: 35.1047

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.4940 - loss: 34.4315

 85/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.5007 - loss: 34.2405

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5061 - loss: 33.5463

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5123 - loss: 33.1449

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5146 - loss: 32.8570

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5192 - loss: 32.3279

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5217 - loss: 32.0229

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5281 - loss: 31.4911

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5316 - loss: 30.9658

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5360 - loss: 30.3780

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5384 - loss: 29.8165

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.5429 - loss: 29.5002

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5467 - loss: 29.0337

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5508 - loss: 28.5591

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5550 - loss: 28.0549

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.5573 - loss: 27.5836

112/112 ━━━━━━━━━━━━━━━━━━━━ 18s 62ms/step - acc: 0.5577 - loss: 27.4811 - val_acc: 0.8050 - val_loss: 1.0508

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6:21 3s/step - acc: 0.6875 - loss: 6.1879

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7500 - loss: 2.7702

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7281 - loss: 2.5247

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.7433 - loss: 2.0287

  8/112 ━━━━━━━━━━━━━━━━━━━━ 4s 46ms/step - acc: 0.7422 - loss: 1.9565

 10/112 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - acc: 0.7359 - loss: 1.8390

 12/112 ━━━━━━━━━━━━━━━━━━━━ 4s 46ms/step - acc: 0.7305 - loss: 3.0749

 14/112 ━━━━━━━━━━━━━━━━━━━━ 4s 46ms/step - acc: 0.7377 - loss: 3.3144

 16/112 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - acc: 0.7441 - loss: 3.0855

 18/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.7352 - loss: 2.8923

 20/112 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - acc: 0.7344 - loss: 3.0280

 22/112 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - acc: 0.7408 - loss: 2.8295

 24/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7389 - loss: 2.8345

 26/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7440 - loss: 2.6793

 28/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7433 - loss: 3.0547

 30/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7448 - loss: 3.0528

 32/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7432 - loss: 3.0811

 34/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7459 - loss: 3.1436

 35/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7460 - loss: 3.0756

 37/112 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - acc: 0.7479 - loss: 2.9459

 39/112 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - acc: 0.7464 - loss: 2.8354

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7450 - loss: 2.7546

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7444 - loss: 2.7087

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7431 - loss: 2.6637

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7444 - loss: 2.5737

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7424 - loss: 2.6807

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7433 - loss: 2.6087

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7466 - loss: 2.5681

 52/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7431 - loss: 2.5840

 54/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7433 - loss: 2.5621

 56/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7444 - loss: 2.4939

 58/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7452 - loss: 2.4439

 60/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7443 - loss: 2.7694

 61/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7444 - loss: 2.7833

 63/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7438 - loss: 2.7297

 65/112 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - acc: 0.7452 - loss: 2.6650

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - acc: 0.7456 - loss: 2.6410

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - acc: 0.7477 - loss: 2.5830

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - acc: 0.7487 - loss: 2.5288

 72/112 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - acc: 0.7491 - loss: 2.5020

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - acc: 0.7487 - loss: 2.4688

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7484 - loss: 2.4774

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7494 - loss: 2.5855

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7500 - loss: 2.5559

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7496 - loss: 2.5428

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7513 - loss: 2.5003

 86/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7515 - loss: 2.4668

 88/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7525 - loss: 2.4698

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7523 - loss: 2.6579

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7517 - loss: 2.6754

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7532 - loss: 2.6583

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7534 - loss: 2.7186

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7529 - loss: 2.7481

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7517 - loss: 2.7156

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7520 - loss: 2.7461

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7520 - loss: 2.8353

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7525 - loss: 2.7952

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7536 - loss: 2.7660

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7540 - loss: 2.7464

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7536 - loss: 2.7975

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - acc: 0.7527 - loss: 2.7726

112/112 ━━━━━━━━━━━━━━━━━━━━ 8s 46ms/step - acc: 0.7527 - loss: 2.7726 - val_acc: 0.8106 - val_loss: 0.6890

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 9s 83ms/step - acc: 0.7188 - loss: 1.0860

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - acc: 0.7708 - loss: 0.7970

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7563 - loss: 1.2299

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7634 - loss: 1.0457

  9/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7604 - loss: 0.9458

 10/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.7578 - loss: 0.9214

 12/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.7539 - loss: 1.1696

 14/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.7612 - loss: 1.2062

 16/112 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - acc: 0.7676 - loss: 1.2902

 18/112 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - acc: 0.7552 - loss: 1.2531

 20/112 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - acc: 0.7523 - loss: 1.1814

 22/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7571 - loss: 1.1349

 24/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7572 - loss: 1.4145

 26/112 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - acc: 0.7614 - loss: 1.3561

 28/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7617 - loss: 1.4135

 30/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7641 - loss: 1.3967

 32/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7642 - loss: 1.6011

 34/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7661 - loss: 1.7223

 36/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7661 - loss: 1.7065

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7677 - loss: 1.8393

 40/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7664 - loss: 2.0819

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7638 - loss: 2.0275

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7627 - loss: 2.2669

 44/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7635 - loss: 2.2959

 46/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7612 - loss: 2.4212

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7601 - loss: 2.3504

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7599 - loss: 2.4013

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7613 - loss: 2.4706

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7583 - loss: 2.5354

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7585 - loss: 2.4632

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7590 - loss: 2.4700

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7595 - loss: 2.5831

 61/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7592 - loss: 2.6374

 62/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7591 - loss: 2.6072

 64/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7585 - loss: 2.5444

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7599 - loss: 2.5059

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7593 - loss: 2.4773

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7604 - loss: 2.4801

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7606 - loss: 2.4347

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7601 - loss: 2.3881

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7604 - loss: 2.4257

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7597 - loss: 2.5549

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7615 - loss: 2.5768

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7596 - loss: 2.5637

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7598 - loss: 2.6359

 85/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7608 - loss: 2.5985

 87/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7610 - loss: 2.5707

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7612 - loss: 2.5799

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7598 - loss: 2.6121

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7591 - loss: 2.5871

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7602 - loss: 2.5627

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7589 - loss: 2.5595

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7587 - loss: 2.5537

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7568 - loss: 2.5417

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7576 - loss: 2.5475

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7579 - loss: 2.5150

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7588 - loss: 2.5486

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7593 - loss: 2.5306

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7586 - loss: 2.4967

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - acc: 0.7583 - loss: 2.4882 - val_acc: 0.8011 - val_loss: 0.5921

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - acc: 0.6875 - loss: 1.3170

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7656 - loss: 0.7414

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7500 - loss: 0.7390

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7589 - loss: 0.6764

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7569 - loss: 0.6876

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7585 - loss: 0.6873

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7572 - loss: 0.8407

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7594 - loss: 0.7971

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7610 - loss: 0.7611

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7484 - loss: 0.7400

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7485 - loss: 0.7369

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7554 - loss: 0.7171

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7544 - loss: 0.8610

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7575 - loss: 0.8384

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7581 - loss: 0.8294

 31/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7621 - loss: 0.8116

 32/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7588 - loss: 0.8037

 34/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7615 - loss: 0.8448

 36/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7609 - loss: 0.8403

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7615 - loss: 0.8214

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7600 - loss: 0.8135

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7588 - loss: 0.8319

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7562 - loss: 0.8215

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7563 - loss: 0.8116

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7547 - loss: 0.8021

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7551 - loss: 0.8560

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7580 - loss: 0.8457

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7550 - loss: 0.8354

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7560 - loss: 0.8243

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7569 - loss: 0.8132

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7577 - loss: 0.8016

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7579 - loss: 0.7913

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7574 - loss: 0.7835

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7584 - loss: 0.7768

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7586 - loss: 0.7767

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7604 - loss: 0.7738

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7612 - loss: 0.7654

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7607 - loss: 0.7580

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7608 - loss: 0.7551

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7605 - loss: 0.7597

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7614 - loss: 0.7524

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7621 - loss: 0.7457

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7612 - loss: 0.7397

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7630 - loss: 0.7326

 86/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7629 - loss: 0.7272

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7637 - loss: 0.7218

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7640 - loss: 0.7194

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7637 - loss: 0.7144

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7633 - loss: 0.7100

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7648 - loss: 0.7049

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7637 - loss: 0.7010

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7639 - loss: 0.6962

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7624 - loss: 0.6931

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7633 - loss: 0.6892

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7638 - loss: 0.6857

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7647 - loss: 0.6819

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7653 - loss: 0.6778

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7645 - loss: 0.6770

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - acc: 0.7644 - loss: 0.6766 - val_acc: 0.8112 - val_loss: 0.5147

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - acc: 0.7031 - loss: 0.5369

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7604 - loss: 0.6074

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7563 - loss: 0.5685

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7634 - loss: 0.5424

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7622 - loss: 0.5247

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7656 - loss: 0.5129

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7644 - loss: 0.5082

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7667 - loss: 0.5059

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7684 - loss: 0.5031

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7541 - loss: 0.5147

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7545 - loss: 0.5116

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7609 - loss: 0.5081

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7625 - loss: 0.5127

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7645 - loss: 0.5096

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7645 - loss: 0.5181

 31/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7686 - loss: 0.5143

 33/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7661 - loss: 0.5331

 35/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7679 - loss: 0.5300

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7690 - loss: 0.5272

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7672 - loss: 0.5247

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7664 - loss: 0.5227

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7638 - loss: 0.5229

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7635 - loss: 0.5209

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7613 - loss: 0.5207

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7621 - loss: 0.5191

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7650 - loss: 0.5160

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7621 - loss: 0.5168

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7628 - loss: 0.5159

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7629 - loss: 0.5167

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7630 - loss: 0.5176

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7628 - loss: 0.5207

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7619 - loss: 0.5228

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7627 - loss: 0.5211

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7631 - loss: 0.5196

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7647 - loss: 0.5252

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7654 - loss: 0.5246

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7648 - loss: 0.5236

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7656 - loss: 0.5217

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7648 - loss: 0.5211

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7666 - loss: 0.5227

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7662 - loss: 0.5223

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7652 - loss: 0.5239

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7667 - loss: 0.5281

 86/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7667 - loss: 0.5265

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7672 - loss: 0.5269

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7674 - loss: 0.5258

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7672 - loss: 0.5256

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7665 - loss: 0.5256

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7666 - loss: 0.5248

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7681 - loss: 0.5240

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7671 - loss: 0.5236

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7675 - loss: 0.5230

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7664 - loss: 0.5227

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7658 - loss: 0.5225

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7669 - loss: 0.5220

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7668 - loss: 0.5229

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7674 - loss: 0.5216

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7681 - loss: 0.5214

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7683 - loss: 0.5200

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7679 - loss: 0.5196

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - acc: 0.7679 - loss: 0.5196 - val_acc: 0.8118 - val_loss: 0.4685

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - acc: 0.7188 - loss: 0.4892

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7760 - loss: 0.4548

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7625 - loss: 0.4686

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7679 - loss: 0.4688

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7639 - loss: 0.4678

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7670 - loss: 0.4706

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7656 - loss: 0.4744

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7677 - loss: 0.4721

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7693 - loss: 0.4696

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7558 - loss: 0.4779

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7560 - loss: 0.4767

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7622 - loss: 0.4723

 24/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7624 - loss: 0.4724

 26/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7668 - loss: 0.4686

 28/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7673 - loss: 0.4696

 30/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7693 - loss: 0.4666

 32/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7676 - loss: 0.4685

 34/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7711 - loss: 0.4652

 36/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7708 - loss: 0.4660

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7710 - loss: 0.4675

 40/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7699 - loss: 0.4680

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7675 - loss: 0.4888

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7656 - loss: 0.4904

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7653 - loss: 0.4900

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7633 - loss: 0.4914

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7640 - loss: 0.4897

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7669 - loss: 0.4962

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7642 - loss: 0.4972

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7651 - loss: 0.4950

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7656 - loss: 0.4936

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7659 - loss: 0.4918

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7659 - loss: 0.4909

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7651 - loss: 0.4902

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7659 - loss: 0.4935

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7661 - loss: 0.4922

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7677 - loss: 0.4910

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7680 - loss: 0.4908

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7673 - loss: 0.4906

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7677 - loss: 0.4962

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7668 - loss: 0.5083

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7688 - loss: 0.5056

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7672 - loss: 0.5058

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7677 - loss: 0.5064

 85/112 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7686 - loss: 0.5043

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7689 - loss: 0.5047

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7691 - loss: 0.5035

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7685 - loss: 0.5027

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7680 - loss: 0.5019

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7694 - loss: 0.5004

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7682 - loss: 0.5001

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7686 - loss: 0.4986

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7670 - loss: 0.4995

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7682 - loss: 0.5002

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7685 - loss: 0.5000

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7694 - loss: 0.4984

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7699 - loss: 0.4970

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7690 - loss: 0.4985

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - acc: 0.7690 - loss: 0.4984 - val_acc: 0.8213 - val_loss: 0.4297

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 77ms/step - acc: 0.7188 - loss: 0.5047

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7760 - loss: 0.4510

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7656 - loss: 0.4587

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7701 - loss: 0.4581

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7656 - loss: 0.5008

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7670 - loss: 0.4933

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7656 - loss: 0.4862

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7667 - loss: 0.4827

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7675 - loss: 0.4765

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7541 - loss: 0.4828

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7537 - loss: 0.4817

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7595 - loss: 0.4801

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7606 - loss: 0.4842

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7633 - loss: 0.4816

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7635 - loss: 0.5028

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7676 - loss: 0.5010

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7656 - loss: 0.4987

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7674 - loss: 0.4940

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7686 - loss: 0.4893

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7672 - loss: 0.4884

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7664 - loss: 0.4879

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7638 - loss: 0.4947

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7639 - loss: 0.4925

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7620 - loss: 0.4916

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7628 - loss: 0.4885

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7656 - loss: 0.4847

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7627 - loss: 0.4852

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7636 - loss: 0.4840

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7640 - loss: 0.4830

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7648 - loss: 0.4810

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7649 - loss: 0.4798

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7639 - loss: 0.4807

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7647 - loss: 0.4798

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7649 - loss: 0.4785

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7668 - loss: 0.4763

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7674 - loss: 0.4755

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7667 - loss: 0.4746

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7675 - loss: 0.4736

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7666 - loss: 0.4743

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7686 - loss: 0.4719

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7682 - loss: 0.4719

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7671 - loss: 0.4739

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7686 - loss: 0.4745

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7685 - loss: 0.4750

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7692 - loss: 0.4737

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7693 - loss: 0.4727

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7683 - loss: 0.4728

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7696 - loss: 0.4717

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7700 - loss: 0.4703

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7691 - loss: 0.4701

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7678 - loss: 0.4705

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7685 - loss: 0.4697

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7685 - loss: 0.4688

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7690 - loss: 0.4674

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7697 - loss: 0.4689

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7699 - loss: 0.4678

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7691 - loss: 0.4698

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 42ms/step - acc: 0.7691 - loss: 0.4698 - val_acc: 0.8230 - val_loss: 0.3879

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - acc: 0.7188 - loss: 0.4638

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7708 - loss: 0.4614

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7625 - loss: 0.4585

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7679 - loss: 0.4469

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7656 - loss: 0.4415

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7685 - loss: 0.4361

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7668 - loss: 0.4375

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7688 - loss: 0.4362

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7702 - loss: 0.4338

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7566 - loss: 0.4412

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7560 - loss: 0.4413

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7622 - loss: 0.4362

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7644 - loss: 0.4356

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7668 - loss: 0.4333

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7667 - loss: 0.4385

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7702 - loss: 0.4378

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7680 - loss: 0.4372

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7692 - loss: 0.4455

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7703 - loss: 0.4438

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7688 - loss: 0.4447

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7675 - loss: 0.4445

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7649 - loss: 0.4524

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7646 - loss: 0.4517

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7626 - loss: 0.4524

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7634 - loss: 0.4518

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7662 - loss: 0.4483

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7633 - loss: 0.4573

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7642 - loss: 0.4570

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7648 - loss: 0.4564

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7651 - loss: 0.4553

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7651 - loss: 0.4541

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7644 - loss: 0.4538

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7654 - loss: 0.4520

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7656 - loss: 0.4507

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7674 - loss: 0.4491

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7680 - loss: 0.4482

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7673 - loss: 0.4479

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7679 - loss: 0.4466

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7670 - loss: 0.4475

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7690 - loss: 0.4455

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7674 - loss: 0.4456

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7681 - loss: 0.4444

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7691 - loss: 0.4429

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7696 - loss: 0.4423

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7700 - loss: 0.4414

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7696 - loss: 0.4410

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7690 - loss: 0.4407

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7704 - loss: 0.4395

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7693 - loss: 0.4443

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7696 - loss: 0.4432

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7679 - loss: 0.4440

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7691 - loss: 0.4424

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7695 - loss: 0.4415

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7703 - loss: 0.4405

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7708 - loss: 0.4396

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7700 - loss: 0.4398

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7700 - loss: 0.4398 - val_acc: 0.8235 - val_loss: 0.3570

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 9s 83ms/step - acc: 0.7031 - loss: 0.5947

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7708 - loss: 0.4495

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7625 - loss: 0.4387

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7679 - loss: 0.4315

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7656 - loss: 0.4233

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7685 - loss: 0.4164

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7668 - loss: 0.4182

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7688 - loss: 0.4155

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7702 - loss: 0.4136

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7566 - loss: 0.4211

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7560 - loss: 0.4263

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7622 - loss: 0.4211

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7650 - loss: 0.4186

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7674 - loss: 0.4156

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7678 - loss: 0.4155

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7717 - loss: 0.4117

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7694 - loss: 0.4139

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7710 - loss: 0.4135

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7720 - loss: 0.4117

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7704 - loss: 0.4133

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7694 - loss: 0.4133

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7671 - loss: 0.4162

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7667 - loss: 0.4159

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7646 - loss: 0.4176

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7653 - loss: 0.4169

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7681 - loss: 0.4153

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7650 - loss: 0.4189

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7659 - loss: 0.4192

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7664 - loss: 0.4190

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7667 - loss: 0.4176

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7666 - loss: 0.4168

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7659 - loss: 0.4162

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7668 - loss: 0.4152

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7670 - loss: 0.4153

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7688 - loss: 0.4139

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7691 - loss: 0.4142

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7684 - loss: 0.4143

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7690 - loss: 0.4136

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7681 - loss: 0.4141

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7700 - loss: 0.4121

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7683 - loss: 0.4135

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7690 - loss: 0.4122

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7700 - loss: 0.4110

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7705 - loss: 0.4104

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7709 - loss: 0.4102

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7704 - loss: 0.4105

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7698 - loss: 0.4110

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7712 - loss: 0.4096

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7701 - loss: 0.4119

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7704 - loss: 0.4115

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7687 - loss: 0.4129

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7699 - loss: 0.4121

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7702 - loss: 0.4118

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7710 - loss: 0.4108

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7715 - loss: 0.4102

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7707 - loss: 0.4107

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7707 - loss: 0.4108 - val_acc: 0.8263 - val_loss: 0.3246

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 77ms/step - acc: 0.7188 - loss: 0.4495

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7760 - loss: 0.3894

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7656 - loss: 0.4006

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7701 - loss: 0.3970

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7674 - loss: 0.3974

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7699 - loss: 0.3948

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7680 - loss: 0.3997

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7698 - loss: 0.4007

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7711 - loss: 0.3985

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7574 - loss: 0.4078

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7574 - loss: 0.4064

 23/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7636 - loss: 0.4023

 25/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7663 - loss: 0.4010

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7685 - loss: 0.3986

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7689 - loss: 0.3984

 30/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7708 - loss: 0.3966

 32/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7690 - loss: 0.3996

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7704 - loss: 0.4123

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7719 - loss: 0.4101

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7728 - loss: 0.4090

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7712 - loss: 0.4100

 40/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7719 - loss: 0.4082

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7697 - loss: 0.4089

 44/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7685 - loss: 0.4097

 46/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7663 - loss: 0.4110

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7656 - loss: 0.4111

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7691 - loss: 0.4077

 52/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7662 - loss: 0.4096

 54/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7668 - loss: 0.4088

 56/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7670 - loss: 0.4106

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7683 - loss: 0.4088

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7674 - loss: 0.4094

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7674 - loss: 0.4084

 64/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7671 - loss: 0.4083

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7687 - loss: 0.4063

 68/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7686 - loss: 0.4058

 70/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7701 - loss: 0.4051

 72/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7704 - loss: 0.4042

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7694 - loss: 0.4043

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7693 - loss: 0.4039

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7700 - loss: 0.4024

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7705 - loss: 0.4014

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7694 - loss: 0.4018

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7710 - loss: 0.4000

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7709 - loss: 0.3993

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7715 - loss: 0.3987

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7715 - loss: 0.3981

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7706 - loss: 0.3989

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7718 - loss: 0.3980

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7723 - loss: 0.3971

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7714 - loss: 0.3976

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7710 - loss: 0.3977

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7693 - loss: 0.3987

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7705 - loss: 0.3975

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7704 - loss: 0.3972

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7709 - loss: 0.3962

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7717 - loss: 0.3956

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7717 - loss: 0.3953

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7712 - loss: 0.3956

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - acc: 0.7712 - loss: 0.3956 - val_acc: 0.8347 - val_loss: 0.2876

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - acc: 0.7188 - loss: 0.4548

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - acc: 0.7760 - loss: 0.3797

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7656 - loss: 0.3903

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7701 - loss: 0.3827

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7674 - loss: 0.3802

 11/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7699 - loss: 0.3720

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7680 - loss: 0.3763

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7698 - loss: 0.3768

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7711 - loss: 0.3755

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7574 - loss: 0.3853

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7574 - loss: 0.3858

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7636 - loss: 0.3811

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7663 - loss: 0.3799

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7685 - loss: 0.3790

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7689 - loss: 0.3777

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7727 - loss: 0.3749

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7704 - loss: 0.3764

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7719 - loss: 0.3763

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7724 - loss: 0.3779

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7708 - loss: 0.3781

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7698 - loss: 0.3778

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7674 - loss: 0.3808

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7670 - loss: 0.3814

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7650 - loss: 0.3830

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7656 - loss: 0.3817

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7687 - loss: 0.3791

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7659 - loss: 0.3807

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7668 - loss: 0.3799

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7673 - loss: 0.3793

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7675 - loss: 0.3788

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7674 - loss: 0.3788

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7666 - loss: 0.3788

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7675 - loss: 0.3776

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7677 - loss: 0.3776

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7695 - loss: 0.3765

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7700 - loss: 0.3761

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7693 - loss: 0.3767

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7698 - loss: 0.3768

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7689 - loss: 0.3773

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7708 - loss: 0.3757

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7691 - loss: 0.3769

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7698 - loss: 0.3763

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7708 - loss: 0.3750

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7712 - loss: 0.3745

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7716 - loss: 0.3743

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7711 - loss: 0.3747

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7705 - loss: 0.3751

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7716 - loss: 0.3747

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7721 - loss: 0.3743

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7712 - loss: 0.3748

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7700 - loss: 0.3754

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7705 - loss: 0.3752

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7704 - loss: 0.3744

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7709 - loss: 0.3735

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7717 - loss: 0.3729

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7721 - loss: 0.3724

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7713 - loss: 0.3733

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - acc: 0.7712 - loss: 0.3734 - val_acc: 0.8347 - val_loss: 0.2646

Epoch 12/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 81ms/step - acc: 0.7188 - loss: 0.4108

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7760 - loss: 0.3581

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.7656 - loss: 0.3752

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.7701 - loss: 0.3722

  9/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7674 - loss: 0.3727

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7699 - loss: 0.3659

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7680 - loss: 0.3712

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7698 - loss: 0.3711

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7711 - loss: 0.3667

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7574 - loss: 0.3760

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7574 - loss: 0.3770

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7636 - loss: 0.3710

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7663 - loss: 0.3695

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7685 - loss: 0.3668

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7689 - loss: 0.3658

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7727 - loss: 0.3634

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7704 - loss: 0.3862

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7719 - loss: 0.3837

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7728 - loss: 0.3807

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7712 - loss: 0.3809

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7702 - loss: 0.3792

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7678 - loss: 0.3811

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7674 - loss: 0.3816

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7653 - loss: 0.3832

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7659 - loss: 0.3831

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7690 - loss: 0.3795

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7662 - loss: 0.3804

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7670 - loss: 0.3795

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7675 - loss: 0.3776

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7677 - loss: 0.3774

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7677 - loss: 0.3771

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7669 - loss: 0.3767

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7678 - loss: 0.3750

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7687 - loss: 0.3739

 68/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7686 - loss: 0.3732

 70/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7701 - loss: 0.3719

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7702 - loss: 0.3714

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7695 - loss: 0.3712

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7700 - loss: 0.3704

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7691 - loss: 0.3705

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7710 - loss: 0.3686

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7693 - loss: 0.3696

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7700 - loss: 0.3689

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7710 - loss: 0.3670

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7714 - loss: 0.3663

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7718 - loss: 0.3658

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7713 - loss: 0.3658

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7707 - loss: 0.3659

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7720 - loss: 0.3649

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7709 - loss: 0.3651

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7711 - loss: 0.3645

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7695 - loss: 0.3656

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7706 - loss: 0.3648

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7710 - loss: 0.3643

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7718 - loss: 0.3639

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7722 - loss: 0.3635

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7714 - loss: 0.3639

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.7714 - loss: 0.3641 - val_acc: 0.8347 - val_loss: 0.2477

Epoch 13/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 77ms/step - acc: 0.7188 - loss: 0.3908

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - acc: 0.7760 - loss: 0.3224

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.7656 - loss: 0.3421

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7701 - loss: 0.3410

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7656 - loss: 0.3648

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7685 - loss: 0.3604

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7668 - loss: 0.3617

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7688 - loss: 0.3592

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7702 - loss: 0.3574

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7566 - loss: 0.3645

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7567 - loss: 0.3637

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7622 - loss: 0.3711

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7650 - loss: 0.3687

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7674 - loss: 0.3679

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7678 - loss: 0.3661

 31/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7717 - loss: 0.3640

 33/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7689 - loss: 0.3680

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7705 - loss: 0.3658

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7715 - loss: 0.3635

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7700 - loss: 0.3645

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7691 - loss: 0.3642

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7667 - loss: 0.3668

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7663 - loss: 0.3666

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7643 - loss: 0.3679

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7650 - loss: 0.3669

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7681 - loss: 0.3640

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7653 - loss: 0.3655

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7662 - loss: 0.3647

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7667 - loss: 0.3636

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7669 - loss: 0.3626

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7669 - loss: 0.3617

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7661 - loss: 0.3617

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7671 - loss: 0.3604

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7673 - loss: 0.3596

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7690 - loss: 0.3629

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7696 - loss: 0.3620

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7688 - loss: 0.3614

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7694 - loss: 0.3612

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7685 - loss: 0.3610

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7704 - loss: 0.3589

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7687 - loss: 0.3599

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7694 - loss: 0.3588

 85/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7704 - loss: 0.3570

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7708 - loss: 0.3558

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7712 - loss: 0.3553

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7708 - loss: 0.3555

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7702 - loss: 0.3556

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7715 - loss: 0.3549

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7705 - loss: 0.3550

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7707 - loss: 0.3538

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7690 - loss: 0.3551

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7702 - loss: 0.3541

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7705 - loss: 0.3528

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7713 - loss: 0.3521

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7718 - loss: 0.3514

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7708 - loss: 0.3525

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - acc: 0.7708 - loss: 0.3524 - val_acc: 0.8347 - val_loss: 0.2242

Epoch 14/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 76ms/step - acc: 0.7188 - loss: 0.3818

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7760 - loss: 0.3247

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7656 - loss: 0.3323

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7701 - loss: 0.3320

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7674 - loss: 0.3286

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7699 - loss: 0.3262

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7680 - loss: 0.3303

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7698 - loss: 0.3323

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7711 - loss: 0.3330

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7574 - loss: 0.3422

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7574 - loss: 0.3440

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7636 - loss: 0.3389

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7663 - loss: 0.3366

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7685 - loss: 0.3351

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7689 - loss: 0.3347

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7727 - loss: 0.3331

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7704 - loss: 0.3350

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7719 - loss: 0.3335

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7728 - loss: 0.3331

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7712 - loss: 0.3348

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7702 - loss: 0.3347

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7678 - loss: 0.3382

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7674 - loss: 0.3390

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7653 - loss: 0.3411

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7659 - loss: 0.3402

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7690 - loss: 0.3379

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7662 - loss: 0.3406

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7670 - loss: 0.3417

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7675 - loss: 0.3415

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7677 - loss: 0.3409

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7677 - loss: 0.3410

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7669 - loss: 0.3402

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7678 - loss: 0.3387

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7680 - loss: 0.3388

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7697 - loss: 0.3379

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7702 - loss: 0.3372

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7695 - loss: 0.3372

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7700 - loss: 0.3374

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7691 - loss: 0.3372

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7710 - loss: 0.3357

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7693 - loss: 0.3364

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7700 - loss: 0.3355

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7710 - loss: 0.3342

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7714 - loss: 0.3338

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7718 - loss: 0.3336

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7713 - loss: 0.3338

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7707 - loss: 0.3335

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7720 - loss: 0.3328

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7709 - loss: 0.3331

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7711 - loss: 0.3324

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7695 - loss: 0.3336

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7706 - loss: 0.3328

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7710 - loss: 0.3322

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7718 - loss: 0.3316

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7722 - loss: 0.3310

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7713 - loss: 0.3318

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7712 - loss: 0.3318 - val_acc: 0.8347 - val_loss: 0.2032

Epoch 15/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step - acc: 0.7188 - loss: 0.3691

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7760 - loss: 0.3094

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.7656 - loss: 0.3271

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7701 - loss: 0.3231

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7674 - loss: 0.3217

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7699 - loss: 0.3174

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7680 - loss: 0.3199

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7698 - loss: 0.3178

 17/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7711 - loss: 0.3160

 19/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7574 - loss: 0.3271

 21/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7574 - loss: 0.3291

 23/112 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - acc: 0.7636 - loss: 0.3230

 25/112 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - acc: 0.7663 - loss: 0.3217

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - acc: 0.7685 - loss: 0.3205

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - acc: 0.7689 - loss: 0.3195

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7727 - loss: 0.3178

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7704 - loss: 0.3213

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7719 - loss: 0.3214

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7728 - loss: 0.3211

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7730 - loss: 0.3215

 40/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7719 - loss: 0.3213

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7697 - loss: 0.3231

 44/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7685 - loss: 0.3246

 46/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7663 - loss: 0.3266

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7656 - loss: 0.3264

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7691 - loss: 0.3229

 52/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7662 - loss: 0.3255

 54/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7668 - loss: 0.3250

 56/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7670 - loss: 0.3249

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7683 - loss: 0.3237

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7674 - loss: 0.3244

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7674 - loss: 0.3234

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7669 - loss: 0.3232

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7678 - loss: 0.3219

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7680 - loss: 0.3213

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7697 - loss: 0.3208

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7702 - loss: 0.3205

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7695 - loss: 0.3215

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7700 - loss: 0.3211

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7691 - loss: 0.3211

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7710 - loss: 0.3340

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7693 - loss: 0.3355

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7700 - loss: 0.3344

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7710 - loss: 0.3327

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7714 - loss: 0.3316

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7718 - loss: 0.3312

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7713 - loss: 0.3310

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7707 - loss: 0.3319

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7720 - loss: 0.3312

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7709 - loss: 0.3312

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7711 - loss: 0.3304

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7692 - loss: 0.3396

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7703 - loss: 0.3386

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7707 - loss: 0.3377

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7715 - loss: 0.3368

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7719 - loss: 0.3371

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7711 - loss: 0.3375

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.7711 - loss: 0.3374 - val_acc: 0.8347 - val_loss: 0.1942

Epoch 16/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 8s 77ms/step - acc: 0.7188 - loss: 0.6224

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7760 - loss: 0.3805

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7656 - loss: 0.3983

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7701 - loss: 0.4093

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7674 - loss: 0.4047

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7699 - loss: 0.4072

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7680 - loss: 0.4141

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7698 - loss: 0.4146

 16/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7744 - loss: 0.4106

 18/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7630 - loss: 0.4188

 20/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7586 - loss: 0.4230

 22/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7635 - loss: 0.4174

 24/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7643 - loss: 0.4186

 26/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7686 - loss: 0.4159

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7685 - loss: 0.4151

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7689 - loss: 0.4133

 31/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7727 - loss: 0.4106

 33/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7704 - loss: 0.4134

 35/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7719 - loss: 0.4113

 36/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7721 - loss: 0.4107

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7730 - loss: 0.4097

 40/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7719 - loss: 0.4103

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7697 - loss: 0.4130

 44/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7685 - loss: 0.4136

 46/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7663 - loss: 0.4150

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7656 - loss: 0.4153

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7691 - loss: 0.4134

 52/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7662 - loss: 0.4150

 54/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7668 - loss: 0.4143

 56/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7670 - loss: 0.4145

 58/112 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.7683 - loss: 0.4131

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7674 - loss: 0.4130

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7674 - loss: 0.4125

 64/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7671 - loss: 0.4124

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7687 - loss: 0.4114

 68/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7686 - loss: 0.4115

 70/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7701 - loss: 0.4102

 72/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7704 - loss: 0.4104

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7694 - loss: 0.4116

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7693 - loss: 0.4119

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7700 - loss: 0.4103

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7705 - loss: 0.4091

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7694 - loss: 0.4097

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.7710 - loss: 0.4079

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7709 - loss: 0.4073

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7715 - loss: 0.4066

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7715 - loss: 0.4063

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7706 - loss: 0.4063

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7718 - loss: 0.4052

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7723 - loss: 0.4052

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7714 - loss: 0.4057

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7702 - loss: 0.4057

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7707 - loss: 0.4058

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7706 - loss: 0.4057

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7711 - loss: 0.4053

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7718 - loss: 0.4049

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7719 - loss: 0.4049

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.7714 - loss: 0.4058

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 41ms/step - acc: 0.7714 - loss: 0.4058 - val_acc: 0.8342 - val_loss: 0.3099

Epoch 17/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - acc: 0.7188 - loss: 0.4626

  3/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7760 - loss: 0.3830

  5/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7656 - loss: 0.3997

  7/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7701 - loss: 0.3899

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7674 - loss: 0.3884

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7699 - loss: 0.3824

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7680 - loss: 0.3870

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7698 - loss: 0.3879

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7711 - loss: 0.3895

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7574 - loss: 0.4005

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7574 - loss: 0.4025

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7636 - loss: 0.3971

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7663 - loss: 0.3960

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7685 - loss: 0.3958

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7689 - loss: 0.3949

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7727 - loss: 0.3952

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7704 - loss: 0.3976

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7719 - loss: 0.3961

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7728 - loss: 0.3959

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7712 - loss: 0.3964

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7698 - loss: 0.3980

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7674 - loss: 0.4002

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7670 - loss: 0.4006

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7650 - loss: 0.4025

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7656 - loss: 0.4022

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7687 - loss: 0.4002

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7659 - loss: 0.4021

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7668 - loss: 0.4025

 56/112 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - acc: 0.7667 - loss: 0.4024

 58/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7680 - loss: 0.3994

 60/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7672 - loss: 0.3999

 62/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7671 - loss: 0.3985

 64/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7668 - loss: 0.3980

 66/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7685 - loss: 0.3967

 68/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7684 - loss: 0.3953

 70/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7699 - loss: 0.3943

 72/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7702 - loss: 0.3937

 74/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7692 - loss: 0.3936

 76/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7691 - loss: 0.3934

 78/112 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7698 - loss: 0.3925

 80/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7703 - loss: 0.3921

 82/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7692 - loss: 0.3927

 84/112 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - acc: 0.7708 - loss: 0.3908

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7707 - loss: 0.3901

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7713 - loss: 0.3890

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7714 - loss: 0.3887

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7704 - loss: 0.3889

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7716 - loss: 0.3889

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7721 - loss: 0.3879

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7712 - loss: 0.3883

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7700 - loss: 0.3887

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7705 - loss: 0.3886

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7704 - loss: 0.3879

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7709 - loss: 0.3874

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7717 - loss: 0.3865

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7717 - loss: 0.3860

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7712 - loss: 0.3865

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.7712 - loss: 0.3865 - val_acc: 0.8342 - val_loss: 0.2638

Epoch 18/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - acc: 0.7188 - loss: 0.4065

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7760 - loss: 0.3398

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7656 - loss: 0.3666

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7701 - loss: 0.3572

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7674 - loss: 0.3548

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7699 - loss: 0.3535

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7680 - loss: 0.3613

 15/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7698 - loss: 0.3631

 17/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7711 - loss: 0.3640

 19/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7574 - loss: 0.3704

 21/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7567 - loss: 0.3742

 23/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7629 - loss: 0.3687

 25/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7656 - loss: 0.3659

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7679 - loss: 0.3640

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7683 - loss: 0.3639

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - acc: 0.7722 - loss: 0.3605

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7699 - loss: 0.3648

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7714 - loss: 0.3656

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7724 - loss: 0.3650

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7708 - loss: 0.3676

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7698 - loss: 0.3676

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7674 - loss: 0.3689

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7670 - loss: 0.3685

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - acc: 0.7650 - loss: 0.3699

 49/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7656 - loss: 0.3686

 51/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7687 - loss: 0.3663

 53/112 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - acc: 0.7659 - loss: 0.3675

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - acc: 0.7668 - loss: 0.3666

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - acc: 0.7673 - loss: 0.3659

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7675 - loss: 0.3648

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7674 - loss: 0.3643

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7666 - loss: 0.3642

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7675 - loss: 0.3647

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7677 - loss: 0.3641

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7695 - loss: 0.3621

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7700 - loss: 0.3616

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7693 - loss: 0.3616

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7698 - loss: 0.3623

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7689 - loss: 0.3625

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - acc: 0.7708 - loss: 0.3610

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7691 - loss: 0.3620

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7698 - loss: 0.3606

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7708 - loss: 0.3589

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7712 - loss: 0.3578

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7716 - loss: 0.3575

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7711 - loss: 0.3573

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - acc: 0.7705 - loss: 0.3577

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7719 - loss: 0.3566

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7721 - loss: 0.3559

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7712 - loss: 0.3562

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7700 - loss: 0.3566

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7705 - loss: 0.3566

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7704 - loss: 0.3560

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7709 - loss: 0.3549

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7717 - loss: 0.3545

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7717 - loss: 0.3539

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - acc: 0.7712 - loss: 0.3546

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7712 - loss: 0.3546 - val_acc: 0.8336 - val_loss: 0.2361

Epoch 19/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - acc: 0.7188 - loss: 0.3887

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7760 - loss: 0.3327

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7656 - loss: 0.3452

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7701 - loss: 0.3395

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7674 - loss: 0.3370

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7699 - loss: 0.3305

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7680 - loss: 0.3363

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7698 - loss: 0.3393

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7711 - loss: 0.3388

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7574 - loss: 0.3482

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7574 - loss: 0.3467

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7636 - loss: 0.3421

 25/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7663 - loss: 0.3401

 27/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7685 - loss: 0.3411

 29/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7689 - loss: 0.3420

 31/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7727 - loss: 0.3393

 33/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7704 - loss: 0.3436

 35/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7719 - loss: 0.3430

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7728 - loss: 0.3427

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7712 - loss: 0.3444

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7702 - loss: 0.3447

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7678 - loss: 0.3470

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7674 - loss: 0.3475

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7653 - loss: 0.3493

 49/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7659 - loss: 0.3490

 51/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7690 - loss: 0.3459

 53/112 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7662 - loss: 0.3478

 55/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7670 - loss: 0.3477

 57/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7675 - loss: 0.3472

 59/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7677 - loss: 0.3465

 61/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7677 - loss: 0.3457

 63/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7669 - loss: 0.3454

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7678 - loss: 0.3436

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7680 - loss: 0.3430

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7697 - loss: 0.3412

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7702 - loss: 0.3414

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7695 - loss: 0.3415

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7700 - loss: 0.3417

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7691 - loss: 0.3415

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7710 - loss: 0.3395

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7693 - loss: 0.3405

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7700 - loss: 0.3395

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7710 - loss: 0.3377

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7714 - loss: 0.3367

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7718 - loss: 0.3360

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7713 - loss: 0.3366

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7707 - loss: 0.3366

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7720 - loss: 0.3364

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7709 - loss: 0.3370

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7711 - loss: 0.3366

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7695 - loss: 0.3378

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7706 - loss: 0.3368

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7710 - loss: 0.3362

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7718 - loss: 0.3357

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7722 - loss: 0.3350

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7714 - loss: 0.3352

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7714 - loss: 0.3353 - val_acc: 0.8336 - val_loss: 0.2097

Epoch 20/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step - acc: 0.7188 - loss: 0.3933

  3/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7708 - loss: 0.3267

  5/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7625 - loss: 0.3303

  7/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7679 - loss: 0.3277

  9/112 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - acc: 0.7656 - loss: 0.3227

 11/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7685 - loss: 0.3177

 13/112 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - acc: 0.7668 - loss: 0.3249

 15/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7688 - loss: 0.3228

 17/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7702 - loss: 0.3226

 19/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7566 - loss: 0.3301

 21/112 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7567 - loss: 0.3319

 23/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7629 - loss: 0.3282

 25/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7656 - loss: 0.3266

 27/112 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - acc: 0.7679 - loss: 0.3266

 29/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7683 - loss: 0.3278

 31/112 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.7722 - loss: 0.3269

 33/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7699 - loss: 0.3292

 35/112 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7714 - loss: 0.3283

 37/112 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.7724 - loss: 0.3266

 38/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7726 - loss: 0.3271

 39/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7708 - loss: 0.3279

 41/112 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7698 - loss: 0.3284

 42/112 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - acc: 0.7693 - loss: 0.3289

 43/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7674 - loss: 0.3302

 45/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7670 - loss: 0.3295

 46/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7660 - loss: 0.3306

 47/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7650 - loss: 0.3309

 48/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7653 - loss: 0.3298

 50/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7688 - loss: 0.3274

 52/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7659 - loss: 0.3287

 54/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7665 - loss: 0.3289

 55/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7668 - loss: 0.3290

 57/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7673 - loss: 0.3284

 59/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7675 - loss: 0.3288

 61/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7674 - loss: 0.3285

 63/112 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - acc: 0.7666 - loss: 0.3287

 65/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7675 - loss: 0.3281

 67/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7677 - loss: 0.3277

 69/112 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - acc: 0.7695 - loss: 0.3259

 71/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7700 - loss: 0.3257

 73/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7693 - loss: 0.3251

 75/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7698 - loss: 0.3247

 77/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7689 - loss: 0.3248

 79/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7708 - loss: 0.3228

 81/112 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - acc: 0.7691 - loss: 0.3237

 83/112 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7698 - loss: 0.3227

 85/112 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7708 - loss: 0.3211

 87/112 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7712 - loss: 0.3201

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7716 - loss: 0.3202

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7711 - loss: 0.3204

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7705 - loss: 0.3207

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7719 - loss: 0.3196

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7708 - loss: 0.3199

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7710 - loss: 0.3196

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - acc: 0.7693 - loss: 0.3212

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7705 - loss: 0.3211

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7708 - loss: 0.3203

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7716 - loss: 0.3197

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7721 - loss: 0.3194

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7713 - loss: 0.3203

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - acc: 0.7712 - loss: 0.3202 - val_acc: 0.8207 - val_loss: 0.2179

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 10.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/279 ━━━━━━━━━━━━━━━━━━━━ 6:49 1s/step

  6/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 11/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 16/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 21/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 26/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 32/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 37/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 43/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 48/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 53/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 58/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 64/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 70/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 76/279 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step

 82/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

 86/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

 91/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

 96/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

102/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

107/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

113/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

119/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

124/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

130/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

136/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

142/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

148/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

153/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

159/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

165/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

170/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

175/279 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

180/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

185/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

190/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

195/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

200/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

206/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

211/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

216/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

220/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

225/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

230/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

236/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

241/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

247/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

253/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

258/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

264/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

269/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

275/279 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

279/279 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step

[[0.11493158]
 [0.11346414]
 [0.11674272]
 ...
 [0.33259243]
 [0.33798724]
 [0.21990974]]

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[7082    6]
 [1830    5]]
              precision    recall  f1-score   support

         0.0       0.79      1.00      0.89      7088
         1.0       0.45      0.00      0.01      1835

    accuracy                           0.79      8923
   macro avg       0.62      0.50      0.45      8923
weighted avg       0.72      0.79      0.70      8923

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26120\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [25]:
from keras.models import load_model

model.save('Multivariate_Occupancy_RNN_AdvancedTopics.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Multivariate_Occupancy_RNN_AdvancedTopics.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 48, 128)        │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 24, 60)         │        38,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 20)             │         4,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 135,449 (529.10 KB)

 Trainable params: 45,149 (176.36 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 90,300 (352.74 KB)