<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 9 — Multivariate RNN Pt 1: split_sequences, column order, the classification head
- Multivariate differs only in prep: all X on the left, TARGET AS THE LAST COLUMN (drop the date); look-back is the hyperparameter.
- split_sequences with look-back 10 -> 2,655 samples of 10 x features; the -1 predicts the NEXT step.
- SimpleRNN with a sigmoid head, n_steps / n_features inherited from the shape; if it learns in one epoch, add dropout.
- Show the time-series plot even for classification - it misses the quick in/out transitions.
-->

# Multivariate Occupancy Example (RNN)
----------------------------
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental sensor data (temperature, humidity, light, CO2).

Link: http://archive.ics.uci.edu/ml/datasets/Occupancy+Detection+

Same flow as before, just need to prep our data differently. For now, we ignore the time dimension but we could resample to a regular resolution.

Wow - also a nice example: https://machinelearningmastery.com/multivariate-time-series-forecasting-lstms-keras/

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from LuisM78’s GitHub repository:
# url = 'https://raw.githubusercontent.com/LuisM78/Occupancy-detection-data/master/datatest.txt'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/datatest.txt"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 2665 entries, 140 to 2804
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2665 non-null   str
 1   Temperature    2665 non-null   float64
 2   Humidity       2665 non-null   float64
 3   Light          2665 non-null   float64
 4   CO2            2665 non-null   float64
 5   HumidityRatio  2665 non-null   float64
 6   Occupancy      2665 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 195.3 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.7000,26.272,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.7180,26.290,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.7300,26.230,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.7225,26.125,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.7540,26.200,488.600000,779.000000,0.004767,1
145,2015-02-02 14:23:59,23.7600,26.260,568.666667,790.000000,0.004779,1
146,2015-02-02 14:25:00,23.7300,26.290,536.333333,798.000000,0.004776,1
147,2015-02-02 14:25:59,23.7540,26.290,509.000000,797.000000,0.004783,1
148,2015-02-02 14:26:59,23.7540,26.350,476.000000,803.200000,0.004794,1
149,2015-02-02 14:28:00,23.7360,26.390,510.000000,809.000000,0.004796,1
150,2015-02-02 14:29:00,23.7450,26.445,481.500000,815.250000,0.004809,1
151,2015-02-02 14:30:00,23.7000,26.560,481.800000,824.000000,0.004817,1
152,2015-02-02 14:31:00,23.7000,26.600,475.250000,832.000000,0.004824,1
153,2015-02-02 14:31:59,23.7000,26.700,469.000000,845.333333,0.004842,1
154,2015-02-02 14:32:59,23.7000,26.774,464.000000,852.400000,0.004856,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    1693
1     972
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(2665, 6)

     Temperature  Humidity       Light         CO2  HumidityRatio  Occupancy
140      23.7000    26.272  585.200000  749.200000       0.004764          1
141      23.7180    26.290  578.400000  760.400000       0.004773          1
142      23.7300    26.230  572.666667  769.666667       0.004765          1
143      23.7225    26.125  493.750000  774.750000       0.004744          1
144      23.7540    26.200  488.600000  779.000000       0.004767          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(2656, 10, 5)
(2656,)

In [11]:
# check the first few values
X[0]

array([[2.37000000e+01, 2.62720000e+01, 5.85200000e+02, 7.49200000e+02,
        4.76416302e-03],
       [2.37180000e+01, 2.62900000e+01, 5.78400000e+02, 7.60400000e+02,
        4.77266099e-03],
       [2.37300000e+01, 2.62300000e+01, 5.72666667e+02, 7.69666667e+02,
        4.76515255e-03],
       [2.37225000e+01, 2.61250000e+01, 4.93750000e+02, 7.74750000e+02,
        4.74377336e-03],
       [2.37540000e+01, 2.62000000e+01, 4.88600000e+02, 7.79000000e+02,
        4.76659400e-03],
       [2.37600000e+01, 2.62600000e+01, 5.68666667e+02, 7.90000000e+02,
        4.77933243e-03],
       [2.37300000e+01, 2.62900000e+01, 5.36333333e+02, 7.98000000e+02,
        4.77613633e-03],
       [2.37540000e+01, 2.62900000e+01, 5.09000000e+02, 7.97000000e+02,
        4.78309371e-03],
       [2.37540000e+01, 2.63500000e+01, 4.76000000e+02, 8.03200000e+02,
        4.79409400e-03],
       [2.37360000e+01, 2.63900000e+01, 5.10000000e+02, 8.09000000e+02,
        4.79618871e-03]])

In [12]:
# check Y
y[0]

np.float64(1.0)

In [13]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [14]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(2656, 10, 5) (1328, 10, 5) (1328, 10, 5)
(2656,) (1328,) (1328,)

# RNN one layer model

In [15]:
# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

print(n_steps, n_features)

10 5

In [16]:
# now let's build a model
# NEED TO UPDATE FOR CLASSIFICATION

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])


es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,111 (4.34 KB)

 Trainable params: 1,111 (4.34 KB)

 Non-trainable params: 0 (0.00 B)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11:25 3s/step - acc: 1.0000 - loss: 0.0000e+00

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8625 - loss: 43.1702

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7935 - loss: 48.4391

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7783 - loss: 33.8815

 62/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8032 - loss: 25.3735

 77/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8286 - loss: 20.5305

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8495 - loss: 17.0523

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8673 - loss: 14.8240

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8817 - loss: 13.2181

133/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8932 - loss: 11.9261

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8986 - loss: 10.7865

163/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9043 - loss: 9.8094

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9050 - loss: 8.9755

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9077 - loss: 8.2709

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9143 - loss: 7.6801

213/213 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - acc: 0.9153 - loss: 7.5933 - val_acc: 0.9774 - val_loss: 0.9352

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - acc: 1.0000 - loss: 6.5111e-06

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8875 - loss: 1.9173

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9226 - loss: 1.4752

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9304 - loss: 1.1581

 61/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9180 - loss: 1.0842

 75/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9173 - loss: 1.1773

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9289 - loss: 1.0109

104/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9346 - loss: 0.8827

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9429 - loss: 0.7715

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9463 - loss: 0.7413

149/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9436 - loss: 0.7452

163/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9485 - loss: 0.6812

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9508 - loss: 0.7024

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9536 - loss: 0.6574

209/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9550 - loss: 0.6200

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9557 - loss: 0.6101 - val_acc: 0.9774 - val_loss: 0.4329

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 4.0489e-06

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9647 - loss: 0.5767

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9500 - loss: 0.4067

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9565 - loss: 0.3872

 61/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9475 - loss: 0.3511

 76/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9526 - loss: 0.3823

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9484 - loss: 0.3952

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9519 - loss: 0.3863

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9492 - loss: 0.3819

136/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9529 - loss: 0.3556

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9536 - loss: 0.3603

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9566 - loss: 0.3365

181/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9591 - loss: 0.3244

197/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9594 - loss: 0.3164

212/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9585 - loss: 0.3088

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9586 - loss: 0.3083 - val_acc: 0.9624 - val_loss: 0.2096

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - acc: 1.0000 - loss: 3.9772e-09

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 1.0000 - loss: 0.0016

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 1.0000 - loss: 8.8381e-04

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9574 - loss: 0.3159

 62/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9645 - loss: 0.3082

 77/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9532 - loss: 0.4499

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9533 - loss: 0.4585

102/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9392 - loss: 0.5535

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9453 - loss: 0.5329

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9500 - loss: 0.5103

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9510 - loss: 0.4924

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9543 - loss: 0.4834

176/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9545 - loss: 0.4778

190/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9484 - loss: 0.5047

204/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9520 - loss: 0.4701

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9529 - loss: 0.4685 - val_acc: 0.9774 - val_loss: 0.3625

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 2.0093e-07

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9647 - loss: 0.2674

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9688 - loss: 0.1679

 48/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9750 - loss: 0.1963

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9619 - loss: 0.2352

 76/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9553 - loss: 0.2602

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9511 - loss: 0.2618

105/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9562 - loss: 0.2535

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9583 - loss: 0.2422

136/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9603 - loss: 0.2281

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9629 - loss: 0.2263

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9614 - loss: 0.2514

180/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9622 - loss: 0.2439

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9590 - loss: 0.2492

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.2943

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9595 - loss: 0.3140 - val_acc: 0.9774 - val_loss: 0.4862

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 1.0000 - loss: 3.9247e-05

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9600 - loss: 0.2322

 29/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9655 - loss: 0.1934

 43/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9442 - loss: 0.1990

 58/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9483 - loss: 0.2528

 73/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9479 - loss: 0.2581

 88/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9545 - loss: 0.2164

103/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9534 - loss: 0.2414

118/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9576 - loss: 0.2252

133/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9609 - loss: 0.2142

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9605 - loss: 0.2109

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9617 - loss: 0.2200

178/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9618 - loss: 0.2198

192/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9615 - loss: 0.2233

206/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9602 - loss: 0.2308

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9595 - loss: 0.2273 - val_acc: 0.9774 - val_loss: 0.2395

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - acc: 0.6000 - loss: 3.1350

 16/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9125 - loss: 0.5029

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9484 - loss: 0.3544

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9556 - loss: 0.3010

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9492 - loss: 0.3212

 73/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9589 - loss: 0.2597

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9618 - loss: 0.2411

104/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9500 - loss: 0.3040

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9546 - loss: 0.2685

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9567 - loss: 0.3150

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9527 - loss: 0.3072

163/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9534 - loss: 0.2880

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9542 - loss: 0.3280

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9546 - loss: 0.3240

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9558 - loss: 0.3218

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9557 - loss: 0.3307 - val_acc: 0.9774 - val_loss: 0.2489

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 1.8812e-05

 15/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9600 - loss: 0.1746

 29/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9655 - loss: 0.2182

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9773 - loss: 0.1459

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9525 - loss: 0.4273

 75/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9493 - loss: 0.6337

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9582 - loss: 0.5223

106/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9604 - loss: 0.4964

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9603 - loss: 0.4662

135/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.4449

150/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9627 - loss: 0.4032

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9651 - loss: 0.3779

181/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9635 - loss: 0.3572

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9653 - loss: 0.3317

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9638 - loss: 0.3401

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9642 - loss: 0.3365 - val_acc: 0.5526 - val_loss: 0.9918

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - acc: 1.0000 - loss: 0.0928

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9412 - loss: 0.3886

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9677 - loss: 0.2132

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9778 - loss: 0.1469

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9797 - loss: 0.1145

 74/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9730 - loss: 0.1539

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9708 - loss: 0.1945

105/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9695 - loss: 0.1992

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9717 - loss: 0.1951

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9687 - loss: 0.2012

149/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9678 - loss: 0.2226

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9612 - loss: 0.2682

180/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9611 - loss: 0.3208

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9577 - loss: 0.3278

209/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9569 - loss: 0.3514

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9567 - loss: 0.3553 - val_acc: 0.4962 - val_loss: 1.1821

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11s 52ms/step - acc: 1.0000 - loss: 0.1098

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9765 - loss: 0.1195

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9812 - loss: 0.1780

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9796 - loss: 0.1497

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9672 - loss: 0.1955

 84/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9667 - loss: 0.1795

101/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9663 - loss: 0.1621

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9692 - loss: 0.2104

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9606 - loss: 0.3675

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9568 - loss: 0.4096

164/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9549 - loss: 0.3985

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9575 - loss: 0.3854

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9538 - loss: 0.3920

211/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9555 - loss: 0.3861

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9557 - loss: 0.3836 - val_acc: 0.9774 - val_loss: 0.4429

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 0.8000 - loss: 3.2473

 17/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9765 - loss: 0.2183

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9455 - loss: 0.2947

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9551 - loss: 0.4245

 65/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9600 - loss: 0.3803

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9556 - loss: 0.3811

 97/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9629 - loss: 0.3189

113/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9628 - loss: 0.3123

129/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9643 - loss: 0.2777

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9644 - loss: 0.2936

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9630 - loss: 0.3024

178/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9629 - loss: 0.2826

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9629 - loss: 0.2767

210/213 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9610 - loss: 0.2689

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9605 - loss: 0.2679 - val_acc: 0.9474 - val_loss: 0.2427

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [17]:
# make a prediction
pred = model.predict(X_train)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

 1/42 ━━━━━━━━━━━━━━━━━━━━ 10s 267ms/step

31/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(1328, 1), dtype=float32)

In [18]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_train, pred)) # looks pretty good!
print(classification_report(y_train, pred))

[[811  33]
 [  0 484]]
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98       844
         1.0       0.94      1.00      0.97       484

    accuracy                           0.98      1328
   macro avg       0.97      0.98      0.97      1328
weighted avg       0.98      0.98      0.98      1328

In [19]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_train.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_train.shape[0]), pred, color='red') # predicted data
plt.suptitle('Train Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\3033679372.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step

29/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[809  40]
 [  2 477]]
              precision    recall  f1-score   support

         0.0       1.00      0.95      0.97       849
         1.0       0.92      1.00      0.96       479

    accuracy                           0.97      1328
   macro avg       0.96      0.97      0.97      1328
weighted avg       0.97      0.97      0.97      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 10 — Multivariate RNN Pt 2: LSTM swap, stacking, persistence baseline
- One-word LSTM swap: (features + units) x units + bias, x4 = 4,320 params.
- It predicts the zeros a bit better; weighted F1 comparable.
- Stacked SimpleRNN with return_sequences=True keeps the 10 x 30 sequence into a second RNN - and does WORSE here: too complex for an easy problem.
- Persistence is brutal to beat - show value over the dummy every time.
-->

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(LSTM(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc',
                   mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         4,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,351 (17.00 KB)

 Trainable params: 4,351 (17.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 12:23 4s/step - acc: 1.0000 - loss: 2.0368e-07

 12/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.8667 - loss: 2.9131

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8636 - loss: 2.4318

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8303 - loss: 1.8833

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8591 - loss: 2.0255

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8778 - loss: 1.7341

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8952 - loss: 1.4864

 72/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9083 - loss: 1.3007

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9160 - loss: 1.1799

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9231 - loss: 1.0687

101/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9287 - loss: 1.0664

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 1.9312

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9339 - loss: 2.9064

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 2.6946

143/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9329 - loss: 2.5002

155/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9303 - loss: 2.4239

167/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9341 - loss: 2.2581

179/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9385 - loss: 2.1075

190/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9411 - loss: 1.9930

201/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9423 - loss: 1.9092

212/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9434 - loss: 1.8197

213/213 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - acc: 0.9435 - loss: 1.8163 - val_acc: 0.9774 - val_loss: 0.1342

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - acc: 0.8000 - loss: 0.6627

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.1242

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9545 - loss: 0.1123

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9576 - loss: 0.1252

 45/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9689 - loss: 0.0983

 57/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.0778

 68/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9794 - loss: 0.0653

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.4107

 92/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9761 - loss: 0.3675

103/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.3441

114/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9737 - loss: 0.3213

126/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.3046

137/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9737 - loss: 0.2805

149/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9705 - loss: 0.2811

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.2735

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9699 - loss: 0.2548

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.2467

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.2436

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9692 - loss: 0.2475

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9699 - loss: 0.2439 - val_acc: 0.9774 - val_loss: 0.1559

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11s 53ms/step - acc: 1.0000 - loss: 6.6677e-05

 13/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9692 - loss: 0.1050

 24/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.0825

 35/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9829 - loss: 0.0620

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9826 - loss: 0.0625

 57/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9860 - loss: 0.0517

 68/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9824 - loss: 0.0682

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9823 - loss: 0.0674

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9846 - loss: 0.0599

102/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9824 - loss: 0.0696

112/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9839 - loss: 0.0650

123/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9837 - loss: 0.0642

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9851 - loss: 0.0598

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9822 - loss: 0.0675

158/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9823 - loss: 0.0678

170/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9729 - loss: 0.1443

181/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9735 - loss: 0.1393

192/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9740 - loss: 0.1349

203/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9724 - loss: 0.1634

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9689 - loss: 0.1624 - val_acc: 0.9774 - val_loss: 0.1225

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - acc: 1.0000 - loss: 4.5322e-04

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1881

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9739 - loss: 0.1346

 35/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9771 - loss: 0.1102

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9660 - loss: 0.1101

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9661 - loss: 0.2433

 71/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9690 - loss: 0.2280

 83/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9687 - loss: 0.2211

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9726 - loss: 0.1939

106/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9736 - loss: 0.1801

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.1687

128/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.1595

140/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9743 - loss: 0.1539

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.1483

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9728 - loss: 0.1489

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9711 - loss: 0.1472

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.1447

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9723 - loss: 0.1378

206/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9728 - loss: 0.1358

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9718 - loss: 0.1381 - val_acc: 0.9060 - val_loss: 0.2305

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - acc: 1.0000 - loss: 0.0042

 13/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9846 - loss: 0.0563

 25/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9760 - loss: 0.0729

 36/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9722 - loss: 0.0824

 47/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9787 - loss: 0.0651

 58/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9828 - loss: 0.0532

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9710 - loss: 0.0960

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9630 - loss: 0.0987

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9634 - loss: 0.1071

104/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - loss: 0.0959

115/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.1034

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.0946

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9669 - loss: 0.1082

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9656 - loss: 0.1180

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9679 - loss: 0.1107

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.1076

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9696 - loss: 0.1047

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9703 - loss: 0.1026

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9691 - loss: 0.1026

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9680 - loss: 0.1023 - val_acc: 0.9023 - val_loss: 0.3054

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - acc: 1.0000 - loss: 0.0054

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1005

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9739 - loss: 0.0845

 35/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0796

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9739 - loss: 0.0758

 58/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.0898

 70/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0755

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9780 - loss: 0.0841

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9763 - loss: 0.0863

105/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9752 - loss: 0.0869

116/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.0903

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.0865

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.0848

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9722 - loss: 0.0911

163/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9730 - loss: 0.0902

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.0854

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9761 - loss: 0.0804

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9755 - loss: 0.0869

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9720 - loss: 0.1051

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9708 - loss: 0.1065 - val_acc: 0.0564 - val_loss: 1.5080

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - acc: 1.0000 - loss: 0.0609

 13/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9385 - loss: 0.0975

 25/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9680 - loss: 0.0534

 37/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9730 - loss: 0.0598

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.0738

 60/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9700 - loss: 0.0796

 72/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9694 - loss: 0.0907

 84/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9714 - loss: 0.0870

 96/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9729 - loss: 0.0841

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9738 - loss: 0.0815

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9748 - loss: 0.0786

131/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9740 - loss: 0.0817

142/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9732 - loss: 0.0855

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9727 - loss: 0.0829

164/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9695 - loss: 0.0851

176/213 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9705 - loss: 0.0891

188/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9702 - loss: 0.0895

199/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.0919

209/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9665 - loss: 0.0920

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9661 - loss: 0.0914 - val_acc: 0.6579 - val_loss: 0.5638

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - acc: 0.8000 - loss: 0.1892

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0582

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9652 - loss: 0.0960

 34/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9765 - loss: 0.0652

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9783 - loss: 0.0683

 57/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.0927

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9710 - loss: 0.0954

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9700 - loss: 0.0954

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9663 - loss: 0.1027

 99/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.0985

110/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - loss: 0.0972

121/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9686 - loss: 0.0918

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.0997

142/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9676 - loss: 0.0982

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9669 - loss: 0.0989

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.0978

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9696 - loss: 0.0933

182/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0878

193/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9710 - loss: 0.0927

204/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.0882

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9736 - loss: 0.0849 - val_acc: 0.9398 - val_loss: 0.2080

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - acc: 0.8000 - loss: 0.4730

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1209

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1589

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1501

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9727 - loss: 0.1192

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.1075

 65/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9723 - loss: 0.1252

 76/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9711 - loss: 0.1189

 86/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9721 - loss: 0.1123

 97/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9711 - loss: 0.1103

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9722 - loss: 0.1048

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9697 - loss: 0.1060

131/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.1000

143/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9734 - loss: 0.0969

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9740 - loss: 0.0944

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9735 - loss: 0.0941

177/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9729 - loss: 0.0914

189/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.0873

201/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.0873

213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.0856

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9746 - loss: 0.0856 - val_acc: 0.8459 - val_loss: 0.3789

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 0.8000 - loss: 0.3695

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9500 - loss: 0.1165

 23/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9565 - loss: 0.1251

 34/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9588 - loss: 0.1305

 46/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9609 - loss: 0.1409

 58/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9655 - loss: 0.1231

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9681 - loss: 0.1120

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9704 - loss: 0.1037

 92/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9717 - loss: 0.0983

103/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.0984

115/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.1048

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9654 - loss: 0.1148

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9669 - loss: 0.1095

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9695 - loss: 0.1019

162/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9704 - loss: 0.0993

173/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9676 - loss: 0.1021

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9674 - loss: 0.1048

196/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9684 - loss: 0.1014

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9700 - loss: 0.0962

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9699 - loss: 0.0972 - val_acc: 0.9774 - val_loss: 0.0971

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 21s 101ms/step - acc: 1.0000 - loss: 0.0162

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9833 - loss: 0.0670

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.1371

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9500 - loss: 0.1287

 43/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9535 - loss: 0.1236

 55/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9491 - loss: 0.1606

 67/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9493 - loss: 0.1474

 78/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9564 - loss: 0.1296

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9622 - loss: 0.1126

102/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9627 - loss: 0.1206

114/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9649 - loss: 0.1155

126/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1129

137/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9679 - loss: 0.1091

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9676 - loss: 0.1088

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9675 - loss: 0.1064

172/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9674 - loss: 0.1039

184/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9696 - loss: 0.0990

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9711 - loss: 0.0942

206/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9699 - loss: 0.1029

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9708 - loss: 0.0998 - val_acc: 0.9737 - val_loss: 0.1821

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 11s 275ms/step

22/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step

[[0.99976265]
 [0.99977744]
 [0.999832  ]
 ...
 [1.        ]
 [1.        ]
 [1.        ]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[827  22]
 [  5 474]]
              precision    recall  f1-score   support

         0.0       0.99      0.97      0.98       849
         1.0       0.96      0.99      0.97       479

    accuracy                           0.98      1328
   macro avg       0.97      0.98      0.98      1328
weighted avg       0.98      0.98      0.98      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), return_sequences=True, activation='relu'))
                                    # note that the output when
                                    # return_sequences=True makes the output [n_steps, features]
                                    # where rows = n_steps (10!) and features = hidden size (30!)
model.add(SimpleRNN(30)) # output is a simple vector [1,30] that goes into a dense layer
                          # NO RETURN_SEQUENCES!!!
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 10, 30)         │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,941 (11.49 KB)

 Trainable params: 2,941 (11.49 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 14:27 4s/step - acc: 0.0000e+00 - loss: 0.8302

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.8727 - loss: 0.5055

 21/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.4391

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9484 - loss: 0.4032

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9561 - loss: 0.3719

 51/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9569 - loss: 0.3519

 62/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9516 - loss: 0.3384

 73/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9534 - loss: 0.3176

 83/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9566 - loss: 0.3057

 94/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9596 - loss: 0.2897

104/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9596 - loss: 0.2802

114/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9614 - loss: 0.2688

124/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9565 - loss: 0.2659

134/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9582 - loss: 0.2570

144/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9611 - loss: 0.2528

154/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9636 - loss: 0.2419

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9648 - loss: 0.2336

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9669 - loss: 0.2276

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9676 - loss: 0.2227

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9662 - loss: 0.2198

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9678 - loss: 0.2150

213/213 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - acc: 0.9680 - loss: 0.2121 - val_acc: 0.9774 - val_loss: 0.3059

Epoch 2/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - acc: 1.0000 - loss: 0.0403

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 1.0000 - loss: 0.0699

 21/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 1.0000 - loss: 0.0788

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9935 - loss: 0.0945

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9902 - loss: 0.0976

 51/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9882 - loss: 0.1011

 61/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9836 - loss: 0.1076

 70/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9857 - loss: 0.1025

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9825 - loss: 0.1068

 90/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9778 - loss: 0.1132

100/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9760 - loss: 0.1172

110/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9764 - loss: 0.1161

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9782 - loss: 0.1127

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9764 - loss: 0.1160

136/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.1174

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.1149

156/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.1156

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1172

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9737 - loss: 0.1158

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.1145

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.1136

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9737 - loss: 0.1148

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9736 - loss: 0.1145 - val_acc: 0.9774 - val_loss: 0.2083

Epoch 3/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 11s 53ms/step - acc: 1.0000 - loss: 0.0513

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 1.0000 - loss: 0.0747

 21/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9619 - loss: 0.1329

 30/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1156

 40/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.1015

 49/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9796 - loss: 0.0918

 56/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9786 - loss: 0.0922

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9810 - loss: 0.0867

 72/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9778 - loss: 0.0915

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9707 - loss: 0.1046

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9692 - loss: 0.1065

101/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9703 - loss: 0.1038

111/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9712 - loss: 0.1023

120/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9667 - loss: 0.1098

130/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9692 - loss: 0.1050

140/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9714 - loss: 0.1006

151/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9735 - loss: 0.0970

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.0988

170/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9741 - loss: 0.0953

180/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.0965

189/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.0981

198/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9737 - loss: 0.0957

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9740 - loss: 0.0947

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9736 - loss: 0.0954 - val_acc: 0.9774 - val_loss: 0.1807

Epoch 4/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - acc: 1.0000 - loss: 0.0371

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9636 - loss: 0.1295

 21/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9810 - loss: 0.0852

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9806 - loss: 0.0832

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9805 - loss: 0.0817

 50/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9760 - loss: 0.0916

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9729 - loss: 0.0973

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9739 - loss: 0.0943

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9747 - loss: 0.0927

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.0902

 99/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9758 - loss: 0.0888

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.0881

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9709 - loss: 0.0959

126/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9730 - loss: 0.0918

136/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.0867

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.0860

156/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9718 - loss: 0.0928

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9709 - loss: 0.0949

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0932

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9708 - loss: 0.0939

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9703 - loss: 0.0946

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9717 - loss: 0.0923

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9727 - loss: 0.0910 - val_acc: 0.9774 - val_loss: 0.1827

Epoch 5/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - acc: 1.0000 - loss: 0.0344

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9818 - loss: 0.0761

 21/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9714 - loss: 0.0954

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.1008

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.0957

 51/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.0910

 61/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9770 - loss: 0.0806

 71/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.0849

 82/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9756 - loss: 0.0833

 93/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9785 - loss: 0.0783

103/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9786 - loss: 0.0785

113/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9770 - loss: 0.0826

123/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9756 - loss: 0.0837

131/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9740 - loss: 0.0866

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9755 - loss: 0.0836

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9757 - loss: 0.0841

157/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9732 - loss: 0.0895

167/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.0994

177/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9706 - loss: 0.1012

187/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.1039

197/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9706 - loss: 0.1049

207/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9710 - loss: 0.1058

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9708 - loss: 0.1063 - val_acc: 0.9774 - val_loss: 0.3462

Epoch 6/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - acc: 0.8000 - loss: 0.2844

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9455 - loss: 0.1691

 21/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9619 - loss: 0.1441

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9484 - loss: 0.1577

 41/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9512 - loss: 0.1525

 51/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9569 - loss: 0.1457

 61/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9574 - loss: 0.1448

 71/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9606 - loss: 0.1379

 81/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9580 - loss: 0.1413

 91/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9626 - loss: 0.1354

102/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.1291

112/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9679 - loss: 0.1278

122/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9656 - loss: 0.1298

132/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9682 - loss: 0.1241

142/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9690 - loss: 0.1233

152/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9697 - loss: 0.1213

161/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9702 - loss: 0.1199

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9719 - loss: 0.1166

181/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9735 - loss: 0.1137

191/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9728 - loss: 0.1146

201/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9731 - loss: 0.1139

211/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.1114

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9736 - loss: 0.1125 - val_acc: 0.9774 - val_loss: 0.2067

Epoch 7/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - acc: 0.8000 - loss: 0.5498

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9636 - loss: 0.1196

 21/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9810 - loss: 0.1067

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9806 - loss: 0.1032

 40/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.1047

 50/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9720 - loss: 0.1158

 60/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1136

 70/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9743 - loss: 0.1106

 80/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.1139

 89/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9708 - loss: 0.1167

 99/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9717 - loss: 0.1132

109/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.1175

119/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.1127

128/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9734 - loss: 0.1073

138/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.1041

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9743 - loss: 0.1057

156/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.1044

165/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9745 - loss: 0.1035

175/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9726 - loss: 0.1064

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9741 - loss: 0.1033

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9723 - loss: 0.1068

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9737 - loss: 0.1041

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9736 - loss: 0.1038 - val_acc: 0.9774 - val_loss: 0.1910

Epoch 8/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 4:17 1s/step - acc: 1.0000 - loss: 0.0405

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9500 - loss: 0.1224

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9455 - loss: 0.1335

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9613 - loss: 0.1129

 39/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9590 - loss: 0.1209

 48/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9625 - loss: 0.1141

 58/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9655 - loss: 0.1076

 68/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9706 - loss: 0.0972

 78/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9692 - loss: 0.1024

 88/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9705 - loss: 0.0997

 98/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0981

108/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9704 - loss: 0.1007

118/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9695 - loss: 0.1017

128/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9703 - loss: 0.0998

138/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.0954

148/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9716 - loss: 0.0969

158/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9722 - loss: 0.0955

168/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9738 - loss: 0.0925

178/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9742 - loss: 0.0920

188/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9713 - loss: 0.0979

198/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9727 - loss: 0.0955

208/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9740 - loss: 0.0925

213/213 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - acc: 0.9736 - loss: 0.0930 - val_acc: 0.9774 - val_loss: 0.1685

Epoch 9/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 0.0110

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9833 - loss: 0.0832

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9818 - loss: 0.0860

 31/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9806 - loss: 0.0897

 40/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.0915

 50/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9760 - loss: 0.0993

 59/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9763 - loss: 0.0957

 69/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9768 - loss: 0.0928

 79/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9797 - loss: 0.0853

 88/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9773 - loss: 0.0918

 97/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.0965

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9776 - loss: 0.0897

117/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9761 - loss: 0.0927

127/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9764 - loss: 0.0929

136/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9765 - loss: 0.0925

146/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.0948

156/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.0971

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9747 - loss: 0.0959

176/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9750 - loss: 0.0946

186/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9731 - loss: 0.0989

195/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9744 - loss: 0.0954

205/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9727 - loss: 0.0990

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9736 - loss: 0.0962 - val_acc: 0.9774 - val_loss: 0.1626

Epoch 10/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 0.0059

 11/213 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 1.0000 - loss: 0.0390

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9909 - loss: 0.0563

 33/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9879 - loss: 0.0590

 44/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9818 - loss: 0.0705

 54/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9852 - loss: 0.0634

 64/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9844 - loss: 0.0653

 74/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9703 - loss: 0.0968

 85/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9647 - loss: 0.1080

 96/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.0994

107/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.0968

118/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9678 - loss: 0.1017

129/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9674 - loss: 0.1005

139/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9683 - loss: 0.1011

149/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9664 - loss: 0.1037

160/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9663 - loss: 0.1052

171/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - loss: 0.1029

182/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9692 - loss: 0.1007

193/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9699 - loss: 0.0992

203/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9714 - loss: 0.0960

212/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9726 - loss: 0.0931

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9727 - loss: 0.0930 - val_acc: 0.9774 - val_loss: 0.1786

Epoch 11/500

  1/213 ━━━━━━━━━━━━━━━━━━━━ 9s 44ms/step - acc: 1.0000 - loss: 0.0580

 12/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9833 - loss: 0.0607

 22/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9727 - loss: 0.0815

 32/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9625 - loss: 0.1060

 42/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9619 - loss: 0.1020

 53/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9434 - loss: 0.1240

 63/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9397 - loss: 0.1568

 74/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9351 - loss: 0.1844

 85/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9341 - loss: 0.1889

 95/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9389 - loss: 0.1839

105/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9429 - loss: 0.1769

115/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9478 - loss: 0.1721

126/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9508 - loss: 0.1723

137/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9518 - loss: 0.1693

147/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9537 - loss: 0.1648

157/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9541 - loss: 0.1626

166/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9554 - loss: 0.1612

176/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9580 - loss: 0.1575

185/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9589 - loss: 0.1559

194/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9608 - loss: 0.1519

204/213 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9627 - loss: 0.1470

213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9642 - loss: 0.1437 - val_acc: 0.9774 - val_loss: 0.2171

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/42 ━━━━━━━━━━━━━━━━━━━━ 19s 464ms/step

21/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

40/42 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step

[[0.7554284]
 [0.7554284]
 [0.7554284]
 ...
 [0.7554284]
 [0.7554284]
 [0.7554284]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[827  22]
 [  2 477]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.99       849
         1.0       0.96      1.00      0.98       479

    accuracy                           0.98      1328
   macro avg       0.98      0.98      0.98      1328
weighted avg       0.98      0.98      0.98      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [25]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Occupancy'].shift(1)
df.head()

,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy,Baseline
140,23.7000,26.272,585.200000,749.200000,0.004764,1,NaN
141,23.7180,26.290,578.400000,760.400000,0.004773,1,1.0
142,23.7300,26.230,572.666667,769.666667,0.004765,1,1.0
143,23.7225,26.125,493.750000,774.750000,0.004744,1,1.0
144,23.7540,26.200,488.600000,779.000000,0.004767,1,1.0

In [26]:
y_test_baseline = df['Baseline']
# just extract rows corresponding to y_test
y_test_baseline = y_test_baseline.tail(y_test.shape[0])
# verify shape
print(y_test.shape)
print(y_test_baseline.shape) # good!

(1328,)
(1328,)

In [27]:
# see how it does!
pred = y_test_baseline # the pred

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

[[842   7]
 [  7 472]]
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       849
         1.0       0.99      0.99      0.99       479

    accuracy                           0.99      1328
   macro avg       0.99      0.99      0.99      1328
weighted avg       0.99      0.99      0.99      1328

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\3878943032.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [28]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_13552\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [29]:
# be careful of the baseline model
# and make sure you choose an appropriate measure
# for the problem you are trying to solve...