<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 9 — Multivariate RNN Pt 1: split_sequences, column order, the classification head
- Multivariate differs only in prep: all X on the left, TARGET AS THE LAST COLUMN (drop the date); look-back is the hyperparameter.
- split_sequences with look-back 10 -> 2,655 samples of 10 x features; the -1 predicts the NEXT step.
- SimpleRNN with a sigmoid head, n_steps / n_features inherited from the shape; if it learns in one epoch, add dropout.
- Show the time-series plot even for classification - it misses the quick in/out transitions.
-->

# Multivariate Occupancy Example (RNN)
----------------------------
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental sensor data (temperature, humidity, light, CO2).

Link: http://archive.ics.uci.edu/ml/datasets/Occupancy+Detection+

Same flow as before, just need to prep our data differently. For now, we ignore the time dimension but we could resample to a regular resolution.

Wow - also a nice example: https://machinelearningmastery.com/multivariate-time-series-forecasting-lstms-keras/

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset: UCI room-occupancy detection (Candanedo & Feldheim, 2016), originally from LuisM78's GitHub.
# We use the two real files - 8,143 minutes of training data (Feb 4-10) followed by 9,752 of test (Feb 11-18) -
# stacked in date order into one two-week series. (The 2-day datatest.txt slice was too short to learn from.)
base = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/main/OPIM5509_Module4_Files/data/"
df = pd.concat([pd.read_csv(base + "datatraining.txt"), pd.read_csv(base + "datatest2.txt")], ignore_index=True)
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)   # chronological - never shuffle a time series
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 17895 entries, 0 to 17894
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           17895 non-null  datetime64[us]
 1   Temperature    17895 non-null  float64
 2   Humidity       17895 non-null  float64
 3   Light          17895 non-null  float64
 4   CO2            17895 non-null  float64
 5   HumidityRatio  17895 non-null  float64
 6   Occupancy      17895 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 978.8 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,2015-02-04 17:51:00,23.180,27.272000,426.0,721.250000,0.004793,1
1,2015-02-04 17:51:59,23.150,27.267500,429.5,714.000000,0.004783,1
2,2015-02-04 17:53:00,23.150,27.245000,426.0,713.500000,0.004779,1
3,2015-02-04 17:54:00,23.150,27.200000,426.0,708.250000,0.004772,1
4,2015-02-04 17:55:00,23.100,27.200000,426.0,704.500000,0.004757,1
5,2015-02-04 17:55:59,23.100,27.200000,419.0,701.000000,0.004757,1
6,2015-02-04 17:57:00,23.100,27.200000,419.0,701.666667,0.004757,1
7,2015-02-04 17:57:59,23.100,27.200000,419.0,699.000000,0.004757,1
8,2015-02-04 17:58:59,23.100,27.200000,419.0,689.333333,0.004757,1
9,2015-02-04 18:00:00,23.075,27.175000,419.0,688.000000,0.004745,1
10,2015-02-04 18:01:00,23.075,27.150000,419.0,690.250000,0.004741,1
11,2015-02-04 18:02:00,23.100,27.100000,419.0,691.000000,0.004739,1
12,2015-02-04 18:03:00,23.100,27.166667,419.0,683.500000,0.004751,1
13,2015-02-04 18:04:00,23.050,27.150000,419.0,687.500000,0.004734,1
14,2015-02-04 18:04:59,23.000,27.125000,419.0,686.000000,0.004715,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    14117
1     3778
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(17895, 6)

   Temperature  Humidity  Light     CO2  HumidityRatio  Occupancy
0        23.18   27.2720  426.0  721.25       0.004793          1
1        23.15   27.2675  429.5  714.00       0.004783          1
2        23.15   27.2450  426.0  713.50       0.004779          1
3        23.15   27.2000  426.0  708.25       0.004772          1
4        23.10   27.2000  426.0  704.50       0.004757          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=10)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(17886, 10, 5)
(17886,)

In [11]:
# check the first few values
X[0]

array([[2.31800000e+01, 2.72720000e+01, 4.26000000e+02, 7.21250000e+02,
        4.79298818e-03],
       [2.31500000e+01, 2.72675000e+01, 4.29500000e+02, 7.14000000e+02,
        4.78344095e-03],
       [2.31500000e+01, 2.72450000e+01, 4.26000000e+02, 7.13500000e+02,
        4.77946352e-03],
       [2.31500000e+01, 2.72000000e+01, 4.26000000e+02, 7.08250000e+02,
        4.77150883e-03],
       [2.31000000e+01, 2.72000000e+01, 4.26000000e+02, 7.04500000e+02,
        4.75699293e-03],
       [2.31000000e+01, 2.72000000e+01, 4.19000000e+02, 7.01000000e+02,
        4.75699293e-03],
       [2.31000000e+01, 2.72000000e+01, 4.19000000e+02, 7.01666667e+02,
        4.75699293e-03],
       [2.31000000e+01, 2.72000000e+01, 4.19000000e+02, 6.99000000e+02,
        4.75699293e-03],
       [2.31000000e+01, 2.72000000e+01, 4.19000000e+02, 6.89333333e+02,
        4.75699293e-03],
       [2.30750000e+01, 2.71750000e+01, 4.19000000e+02, 6.88000000e+02,
        4.74535072e-03]])

In [12]:
# check Y
y[0]

np.float64(1.0)

In [13]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [14]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(17886, 10, 5) (8943, 10, 5) (8943, 10, 5)
(17886,) (8943,) (8943,)

# RNN one layer model

In [15]:
# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

print(n_steps, n_features)

10 5

In [16]:
# now let's build a model
# NEED TO UPDATE FOR CLASSIFICATION

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])


es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,111 (4.34 KB)

 Trainable params: 1,111 (4.34 KB)

 Non-trainable params: 0 (0.00 B)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 3:16 2s/step - acc: 0.2031 - loss: 119.8557

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.5634 - loss: 37.4237

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7384 - loss: 21.7921

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.7937 - loss: 17.0252

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8196 - loss: 14.2867

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8381 - loss: 12.2541

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8521 - loss: 10.5444

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.8620 - loss: 9.2087

112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - acc: 0.8626 - loss: 9.1462 - val_acc: 0.9279 - val_loss: 1.0847

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.9531 - loss: 0.3340

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9430 - loss: 0.4828

 34/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9472 - loss: 0.4731

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9547 - loss: 0.3844

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9562 - loss: 0.3960

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9546 - loss: 0.3992

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9541 - loss: 0.4229

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9530 - loss: 0.4082 - val_acc: 0.8653 - val_loss: 1.3416

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.9531 - loss: 0.1350

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9601 - loss: 0.3248

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9586 - loss: 0.3222

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9636 - loss: 0.2554

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9623 - loss: 0.3048

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9590 - loss: 0.3374

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9568 - loss: 0.3333 - val_acc: 0.8681 - val_loss: 1.3583

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9531 - loss: 0.1243

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9614 - loss: 0.1764

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9627 - loss: 0.2609

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9656 - loss: 0.2401

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9672 - loss: 0.2610

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9669 - loss: 0.2594

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9647 - loss: 0.2861

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9632 - loss: 0.2886

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9623 - loss: 0.2838 - val_acc: 0.8642 - val_loss: 1.4117

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - acc: 0.9531 - loss: 0.1335

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9688 - loss: 0.2009

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9703 - loss: 0.2049

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9716 - loss: 0.2262

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9693 - loss: 0.2298

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9665 - loss: 0.2478

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9651 - loss: 0.2500 - val_acc: 0.8647 - val_loss: 1.4156

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.9531 - loss: 0.1347

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - acc: 0.9695 - loss: 0.1989

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9728 - loss: 0.1742

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9734 - loss: 0.1989

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9718 - loss: 0.1987

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9693 - loss: 0.2204

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9670 - loss: 0.2215

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9669 - loss: 0.2210 - val_acc: 0.8642 - val_loss: 1.4431

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.9375 - loss: 0.1409

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9756 - loss: 0.0924

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9741 - loss: 0.1592

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9773 - loss: 0.1384

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9755 - loss: 0.1769

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9725 - loss: 0.1914

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9703 - loss: 0.1935

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9698 - loss: 0.1965 - val_acc: 0.8636 - val_loss: 1.4405

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - acc: 0.9531 - loss: 0.1463

 13/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9772 - loss: 0.0855

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9772 - loss: 0.1525

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9780 - loss: 0.1327

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9775 - loss: 0.1240

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9771 - loss: 0.1531

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9755 - loss: 0.1611

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9730 - loss: 0.1723

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9713 - loss: 0.1748 - val_acc: 0.8658 - val_loss: 1.4036

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 11s 104ms/step - acc: 0.9688 - loss: 0.1353

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9852 - loss: 0.1084

 34/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9807 - loss: 0.1205

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9810 - loss: 0.1087

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9792 - loss: 0.1431

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9750 - loss: 0.1576

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9743 - loss: 0.1633

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9727 - loss: 0.1640 - val_acc: 0.8765 - val_loss: 1.1747

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - acc: 0.9688 - loss: 0.1133

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9811 - loss: 0.1368

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9780 - loss: 0.1400

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9778 - loss: 0.1268

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9766 - loss: 0.1512

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9752 - loss: 0.1589

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9741 - loss: 0.1577

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - acc: 0.9733 - loss: 0.1576 - val_acc: 0.8765 - val_loss: 1.1549

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - acc: 0.9688 - loss: 0.1082

 17/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9807 - loss: 0.1086

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9790 - loss: 0.1345

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9784 - loss: 0.1233

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9772 - loss: 0.1434

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9756 - loss: 0.1512

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9744 - loss: 0.1485 - val_acc: 0.8765 - val_loss: 1.1336

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [17]:
# make a prediction
pred = model.predict(X_train)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

  1/280 ━━━━━━━━━━━━━━━━━━━━ 45s 163ms/step

 35/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

 69/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

103/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

136/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

172/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

204/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

233/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

265/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

[[6.9888270e-01]
 [4.7488117e-01]
 [8.6087286e-01]
 ...
 [1.8671304e-12]
 [1.2250829e-12]
 [2.3660978e-12]]

array([[1.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]], shape=(8943, 1), dtype=float32)

In [18]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_train, pred)) # looks pretty good!
print(classification_report(y_train, pred))

[[6739  270]
 [ 345 1589]]

              precision    recall  f1-score   support

         0.0       0.95      0.96      0.96      7009
         1.0       0.85      0.82      0.84      1934

    accuracy                           0.93      8943
   macro avg       0.90      0.89      0.90      8943
weighted avg       0.93      0.93      0.93      8943

In [19]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_train.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_train.shape[0]), pred, color='red') # predicted data
plt.suptitle('Train Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\3033679372.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/280 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step

 28/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 58/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 87/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

116/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

146/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

173/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

202/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

229/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

256/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

[[7.1180696e-12]
 [3.2313830e-12]
 [5.8470854e-12]
 ...
 [3.3316988e-01]
 [1.3587382e-08]
 [5.3620995e-05]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
[[6957  151]
 [ 270 1565]]
              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97      7108
         1.0       0.91      0.85      0.88      1835

    accuracy                           0.95      8943
   macro avg       0.94      0.92      0.93      8943
weighted avg       0.95      0.95      0.95      8943

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 10 — Multivariate RNN Pt 2: LSTM swap, stacking, persistence baseline
- One-word LSTM swap: (features + units) x units + bias, x4 = 4,320 params.
- It predicts the zeros a bit better; weighted F1 comparable.
- Stacked SimpleRNN with return_sequences=True keeps the 10 x 30 sequence into a second RNN - and does WORSE here: too complex for an easy problem.
- Persistence is brutal to beat - show value over the dummy every time.
-->

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(LSTM(30, input_shape=(n_steps,n_features), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc',
                   mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         4,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,351 (17.00 KB)

 Trainable params: 4,351 (17.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4:18 2s/step - acc: 0.1875 - loss: 54.4597

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.7102 - loss: 9.6884

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8039 - loss: 7.4447

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8303 - loss: 5.9488

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8154 - loss: 5.3243

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8162 - loss: 4.9131

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8237 - loss: 4.6421

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8284 - loss: 4.3333

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8351 - loss: 4.0366

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8413 - loss: 3.6601

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8464 - loss: 3.4573

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8520 - loss: 3.2244

112/112 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - acc: 0.8566 - loss: 3.0484 - val_acc: 0.9665 - val_loss: 0.4896

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.9219 - loss: 0.5648

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9304 - loss: 0.7255

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9398 - loss: 0.5267

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9333 - loss: 0.5176

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9355 - loss: 0.5087

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9346 - loss: 0.5196

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9337 - loss: 0.6262

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9352 - loss: 0.5936

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9348 - loss: 0.6044

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9339 - loss: 0.5868

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9360 - loss: 0.5577

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9345 - loss: 0.5462

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9339 - loss: 0.5329 - val_acc: 0.9614 - val_loss: 0.3754

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.9531 - loss: 0.1691

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9420 - loss: 0.3629

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9485 - loss: 0.3284

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9487 - loss: 0.3424

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9485 - loss: 0.3485

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9474 - loss: 0.4302

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9483 - loss: 0.4039

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9478 - loss: 0.3943

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9468 - loss: 0.3984

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9477 - loss: 0.3866

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9479 - loss: 0.3879 - val_acc: 0.9346 - val_loss: 0.3922

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - acc: 0.9688 - loss: 0.0934

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9545 - loss: 0.2508

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9510 - loss: 0.2800

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9516 - loss: 0.2606

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9486 - loss: 0.3382

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9494 - loss: 0.3356

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9504 - loss: 0.4301

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9492 - loss: 0.4149

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9491 - loss: 0.3899

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9501 - loss: 0.3764

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9483 - loss: 0.3766

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9487 - loss: 0.3673

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9490 - loss: 0.3683 - val_acc: 0.9419 - val_loss: 0.3178

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9688 - loss: 0.0845

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9616 - loss: 0.1576

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9568 - loss: 0.1873

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9541 - loss: 0.1963

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9527 - loss: 0.2346

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9531 - loss: 0.2416

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9529 - loss: 0.3666

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9518 - loss: 0.3536

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9523 - loss: 0.3344

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9526 - loss: 0.3239

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9530 - loss: 0.3332

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9529 - loss: 0.3298

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9529 - loss: 0.3298 - val_acc: 0.9575 - val_loss: 0.2189

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.9688 - loss: 0.0782

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.1317

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9660 - loss: 0.1588

 34/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9665 - loss: 0.1686

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9671 - loss: 0.1649

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9623 - loss: 0.3026

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9611 - loss: 0.2991

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9605 - loss: 0.2784

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9607 - loss: 0.2743

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9602 - loss: 0.2725

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9593 - loss: 0.2710

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9592 - loss: 0.2697 - val_acc: 0.9670 - val_loss: 0.5027

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.9844 - loss: 0.0394

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9730 - loss: 0.0905

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9673 - loss: 0.1395

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9635 - loss: 0.5111

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9618 - loss: 0.6808

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9592 - loss: 0.7285

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9570 - loss: 0.6591

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9570 - loss: 0.6109

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9573 - loss: 0.5705

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9570 - loss: 0.5380

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9568 - loss: 0.5278 - val_acc: 0.9374 - val_loss: 0.2725

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - acc: 0.9688 - loss: 0.0770

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.1245

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9710 - loss: 0.1456

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9639 - loss: 0.3204

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9642 - loss: 0.2979

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9625 - loss: 0.2897

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9613 - loss: 0.4175

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9616 - loss: 0.4064

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9633 - loss: 0.3744

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9639 - loss: 0.3490

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9648 - loss: 0.3394

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9649 - loss: 0.3258

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9649 - loss: 0.3230 - val_acc: 0.8921 - val_loss: 0.3903

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step - acc: 0.9688 - loss: 0.0714

  9/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9688 - loss: 0.1305

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9740 - loss: 0.0948

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9724 - loss: 0.1391

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9728 - loss: 0.1485

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9729 - loss: 0.1482

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9727 - loss: 0.1559

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9714 - loss: 0.2619

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9707 - loss: 0.2503

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9701 - loss: 0.2416

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9696 - loss: 0.2389

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9691 - loss: 0.2409

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9671 - loss: 0.2429

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9667 - loss: 0.2470 - val_acc: 0.9698 - val_loss: 0.1470

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9844 - loss: 0.0626

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9656 - loss: 0.1165

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9688 - loss: 0.0951

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9676 - loss: 0.1486

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.1394

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9721 - loss: 0.1563

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9718 - loss: 0.2779

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9716 - loss: 0.2623

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9721 - loss: 0.2428

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9712 - loss: 0.2377

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9719 - loss: 0.2307

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9707 - loss: 0.2258

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9698 - loss: 0.2311 - val_acc: 0.9598 - val_loss: 0.1796

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 53s 480ms/step - acc: 0.9844 - loss: 0.0919

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9754 - loss: 0.1029

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9766 - loss: 0.1296

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9764 - loss: 0.1278

 53/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9732 - loss: 0.1557

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9707 - loss: 0.2679

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9707 - loss: 0.2439

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9701 - loss: 0.2364

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9698 - loss: 0.2339

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9685 - loss: 0.2343

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9685 - loss: 0.2343 - val_acc: 0.9575 - val_loss: 0.1639

Epoch 12/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7s 68ms/step - acc: 0.9844 - loss: 0.0449

  8/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9844 - loss: 0.0987

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9795 - loss: 0.0868

 25/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9787 - loss: 0.1197

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9759 - loss: 0.1252

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9760 - loss: 0.1208

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9748 - loss: 0.1337

 57/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9720 - loss: 0.2574

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9728 - loss: 0.2454

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9739 - loss: 0.2308

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9734 - loss: 0.2207

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9733 - loss: 0.2132

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9726 - loss: 0.2094

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9716 - loss: 0.2071

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.9709 - loss: 0.2189 - val_acc: 0.8821 - val_loss: 0.3736

Epoch 13/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9062 - loss: 0.1657

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9701 - loss: 0.1174

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.1157

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9745 - loss: 0.1145

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9764 - loss: 0.1123

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9751 - loss: 0.1306

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.2535

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9715 - loss: 0.2430

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9722 - loss: 0.2262

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9709 - loss: 0.2206

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9704 - loss: 0.2171

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9696 - loss: 0.2168

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9690 - loss: 0.2215 - val_acc: 0.9704 - val_loss: 0.1141

Epoch 14/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - acc: 0.9844 - loss: 0.0240

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9815 - loss: 0.0778

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9797 - loss: 0.0788

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9758 - loss: 0.1150

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9766 - loss: 0.1112

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9759 - loss: 0.1215

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9732 - loss: 0.2534

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9721 - loss: 0.2443

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9733 - loss: 0.2253

 85/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9717 - loss: 0.2179

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9714 - loss: 0.2121

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9705 - loss: 0.2149

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9698 - loss: 0.2193 - val_acc: 0.9676 - val_loss: 0.1209

Epoch 15/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.9844 - loss: 0.0245

 13/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9820 - loss: 0.0762

 25/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9781 - loss: 0.1144

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9776 - loss: 0.1130

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9767 - loss: 0.1239

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9749 - loss: 0.2388

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9749 - loss: 0.2224

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9729 - loss: 0.2114

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9725 - loss: 0.2081

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9711 - loss: 0.2106

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9711 - loss: 0.2106 - val_acc: 0.9693 - val_loss: 0.1086

Epoch 16/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9844 - loss: 0.0311

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9830 - loss: 0.0708

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9797 - loss: 0.0745

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9760 - loss: 0.1066

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9764 - loss: 0.1043

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9746 - loss: 0.1224

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9736 - loss: 0.2401

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9727 - loss: 0.2292

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9738 - loss: 0.2395

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9722 - loss: 0.2413

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9707 - loss: 0.2466

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9686 - loss: 0.2543

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9692 - loss: 0.2511 - val_acc: 0.9598 - val_loss: 0.2304

Epoch 17/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - acc: 0.9844 - loss: 0.0521

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9750 - loss: 0.2545

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9781 - loss: 0.2528

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9745 - loss: 0.2131

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9728 - loss: 0.2701

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9714 - loss: 0.2797

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9674 - loss: 0.2900

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9685 - loss: 0.2738

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9702 - loss: 0.2559

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9701 - loss: 0.2485

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9704 - loss: 0.2383

103/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9703 - loss: 0.2318

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9698 - loss: 0.2291

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9698 - loss: 0.2291 - val_acc: 0.9491 - val_loss: 0.1607

Epoch 18/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - acc: 0.9531 - loss: 0.0569

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9801 - loss: 0.0703

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9792 - loss: 0.1182

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9768 - loss: 0.1225

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9752 - loss: 0.1298

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9733 - loss: 0.1444

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9711 - loss: 0.1753

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9721 - loss: 0.1688

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9715 - loss: 0.1729

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9712 - loss: 0.1735

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.2103

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9672 - loss: 0.2151

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9670 - loss: 0.2187 - val_acc: 0.9721 - val_loss: 0.2810

Epoch 19/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.9844 - loss: 0.0742

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9648 - loss: 0.3030

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9674 - loss: 0.2553

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.2456

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9658 - loss: 0.2755

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9650 - loss: 0.2682

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9667 - loss: 0.2458

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9674 - loss: 0.2222

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9679 - loss: 0.2132

106/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9677 - loss: 0.2179

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9674 - loss: 0.2189 - val_acc: 0.9665 - val_loss: 0.1364

Epoch 20/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 42ms/step - acc: 0.9844 - loss: 0.0288

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9750 - loss: 0.0887

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.1226

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9725 - loss: 0.1274

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9719 - loss: 0.1322

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9693 - loss: 0.1423

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9688 - loss: 0.1709

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9713 - loss: 0.1609

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9706 - loss: 0.1603

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9708 - loss: 0.1614

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9706 - loss: 0.1552

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9704 - loss: 0.1540 - val_acc: 0.9452 - val_loss: 0.1526

Epoch 21/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - acc: 0.9844 - loss: 0.0564

  7/112 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9844 - loss: 0.0499

 15/112 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9833 - loss: 0.0449

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9837 - loss: 0.0712

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9800 - loss: 0.0855

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9798 - loss: 0.0897

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9784 - loss: 0.1057

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9773 - loss: 0.1339

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9772 - loss: 0.1282

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9764 - loss: 0.1341

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9764 - loss: 0.1318

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9755 - loss: 0.1364

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9740 - loss: 0.1375

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9739 - loss: 0.1409 - val_acc: 0.9044 - val_loss: 0.2925

Epoch 22/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9688 - loss: 0.0489

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9805 - loss: 0.0477

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9822 - loss: 0.0649

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9790 - loss: 0.0792

 43/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9775 - loss: 0.0900

 53/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.1079

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9740 - loss: 0.1373

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9752 - loss: 0.1326

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.1278

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9756 - loss: 0.1294

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9752 - loss: 0.1292

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9746 - loss: 0.1352 - val_acc: 0.9743 - val_loss: 0.1653

Epoch 23/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.9844 - loss: 0.0423

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9844 - loss: 0.0514

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9837 - loss: 0.0752

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9819 - loss: 0.0814

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9814 - loss: 0.0863

 52/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9781 - loss: 0.1022

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9757 - loss: 0.1318

 75/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9775 - loss: 0.1262

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9766 - loss: 0.1241

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9769 - loss: 0.1241

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9757 - loss: 0.1309

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9757 - loss: 0.1309 - val_acc: 0.9721 - val_loss: 0.1805

Epoch 24/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.9844 - loss: 0.0409

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9821 - loss: 0.0512

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9803 - loss: 0.0744

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9832 - loss: 0.0747

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9802 - loss: 0.0887

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9787 - loss: 0.1251

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9771 - loss: 0.1268

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9782 - loss: 0.1235

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9766 - loss: 0.1294

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9772 - loss: 0.1309

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9763 - loss: 0.1329

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.1331

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9751 - loss: 0.1373 - val_acc: 0.9564 - val_loss: 0.1163

Epoch 25/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.9844 - loss: 0.0452

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9779 - loss: 0.0962

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9801 - loss: 0.0806

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9768 - loss: 0.1033

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9769 - loss: 0.1217

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.1297

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9731 - loss: 0.1543

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9754 - loss: 0.1458

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9752 - loss: 0.1391

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9755 - loss: 0.1392

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9749 - loss: 0.1424

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.1449

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9739 - loss: 0.1464 - val_acc: 0.8770 - val_loss: 0.3379

Epoch 26/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 55s 504ms/step - acc: 0.9688 - loss: 0.0568

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9766 - loss: 0.2248

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9811 - loss: 0.1822

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9782 - loss: 0.1684

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9797 - loss: 0.1570

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9762 - loss: 0.1736

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9731 - loss: 0.1884

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9715 - loss: 0.1865

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9731 - loss: 0.1791

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9738 - loss: 0.1729

 90/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9740 - loss: 0.1665

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9731 - loss: 0.1669

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9715 - loss: 0.1688

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9718 - loss: 0.1700 - val_acc: 0.9648 - val_loss: 0.0956

Epoch 27/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - acc: 0.9844 - loss: 0.0328

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9875 - loss: 0.0508

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9893 - loss: 0.0421

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9838 - loss: 0.0701

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9848 - loss: 0.0749

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9830 - loss: 0.0929

 56/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9813 - loss: 0.1119

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9798 - loss: 0.1147

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9809 - loss: 0.1061

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9800 - loss: 0.1067

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9782 - loss: 0.1146

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9765 - loss: 0.1197 - val_acc: 0.9698 - val_loss: 0.0967

Epoch 28/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - acc: 0.9844 - loss: 0.0379

 16/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9873 - loss: 0.0447

 32/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9839 - loss: 0.0724

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9824 - loss: 0.0870

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9777 - loss: 0.1111

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9788 - loss: 0.1094

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9779 - loss: 0.1143

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9772 - loss: 0.1204

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9751 - loss: 0.1281

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9755 - loss: 0.1289 - val_acc: 0.9514 - val_loss: 0.1459

Epoch 29/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 45ms/step - acc: 0.9844 - loss: 0.0404

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9797 - loss: 0.0869

 18/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9835 - loss: 0.0878

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9794 - loss: 0.0943

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9793 - loss: 0.0967

 46/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9783 - loss: 0.1079

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9747 - loss: 0.1232

 64/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9724 - loss: 0.1319

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9730 - loss: 0.1381

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9728 - loss: 0.1359

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9730 - loss: 0.1344

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.1368

108/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9709 - loss: 0.1418

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9715 - loss: 0.1422 - val_acc: 0.9670 - val_loss: 0.0979

Epoch 30/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step - acc: 1.0000 - loss: 0.0190

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9891 - loss: 0.0493

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9901 - loss: 0.0397

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9855 - loss: 0.0733

 35/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9866 - loss: 0.0768

 44/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9851 - loss: 0.0863

 52/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9814 - loss: 0.0985

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9794 - loss: 0.1095

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9791 - loss: 0.1125

 76/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9799 - loss: 0.1118

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9790 - loss: 0.1116

 94/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9781 - loss: 0.1129

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9775 - loss: 0.1182

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9764 - loss: 0.1224 - val_acc: 0.9687 - val_loss: 0.0955

Epoch 31/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step - acc: 0.9844 - loss: 0.0470

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9844 - loss: 0.0942

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9877 - loss: 0.0659

 28/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9816 - loss: 0.0825

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9835 - loss: 0.0784

 45/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9826 - loss: 0.0885

 54/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9795 - loss: 0.0989

 63/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9772 - loss: 0.1072

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9779 - loss: 0.1080

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9782 - loss: 0.1067

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9775 - loss: 0.1096

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9769 - loss: 0.1152

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9757 - loss: 0.1158

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9757 - loss: 0.1185 - val_acc: 0.9508 - val_loss: 0.1117

Epoch 32/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - acc: 1.0000 - loss: 0.0268

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9929 - loss: 0.0437

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9930 - loss: 0.0342

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9859 - loss: 0.0579

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9855 - loss: 0.0618

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9831 - loss: 0.0775

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9801 - loss: 0.0968

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9784 - loss: 0.1011

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9789 - loss: 0.0983

 93/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9783 - loss: 0.1003

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.1108

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9762 - loss: 0.1119 - val_acc: 0.9743 - val_loss: 0.0768

Epoch 32: early stopping

Restoring model weights from the end of the best epoch: 22.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/280 ━━━━━━━━━━━━━━━━━━━━ 38s 136ms/step

 37/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

 76/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

105/280 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

130/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

153/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

178/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

203/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

226/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

244/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

266/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

[[3.4158917e-32]
 [2.8995378e-32]
 [3.3945365e-32]
 ...
 [1.0000000e+00]
 [9.9997771e-01]
 [9.9977356e-01]]

[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]
[[6881  227]
 [ 198 1637]]
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97      7108
         1.0       0.88      0.89      0.89      1835

    accuracy                           0.95      8943
   macro avg       0.93      0.93      0.93      8943
weighted avg       0.95      0.95      0.95      8943

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), return_sequences=True, activation='relu'))
                                    # note that the output when
                                    # return_sequences=True makes the output [n_steps, features]
                                    # where rows = n_steps (10!) and features = hidden size (30!)
model.add(SimpleRNN(30)) # output is a simple vector [1,30] that goes into a dense layer
                          # NO RETURN_SEQUENCES!!!
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=64,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 10, 30)         │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,941 (11.49 KB)

 Trainable params: 2,941 (11.49 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 7:12 4s/step - acc: 0.7969 - loss: 0.7181

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.7828 - loss: 0.5332

 19/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.8084 - loss: 0.4798

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8335 - loss: 0.4331

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8539 - loss: 0.3876

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8670 - loss: 0.3647

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8718 - loss: 0.3511

 67/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8783 - loss: 0.3348

 78/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8820 - loss: 0.3216

 87/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8858 - loss: 0.3130

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8883 - loss: 0.3060

105/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.8902 - loss: 0.3007

112/112 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - acc: 0.8919 - loss: 0.2962 - val_acc: 0.9491 - val_loss: 0.1641

Epoch 2/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - acc: 0.9062 - loss: 0.2214

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9109 - loss: 0.2301

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9102 - loss: 0.2326

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9130 - loss: 0.2300

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9131 - loss: 0.2287

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9139 - loss: 0.2251

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9124 - loss: 0.2264

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9126 - loss: 0.2245

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9111 - loss: 0.2239

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9095 - loss: 0.2221

100/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9100 - loss: 0.2221

110/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9118 - loss: 0.2202

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9118 - loss: 0.2204 - val_acc: 0.9961 - val_loss: 0.1358

Epoch 3/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9375 - loss: 0.2024

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9576 - loss: 0.1962

 27/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9531 - loss: 0.1884

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9500 - loss: 0.1858

 52/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9465 - loss: 0.1844

 66/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9479 - loss: 0.1828

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9512 - loss: 0.1783

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9516 - loss: 0.1757

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9522 - loss: 0.1747

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9516 - loss: 0.1743 - val_acc: 0.9972 - val_loss: 0.0933

Epoch 4/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.9531 - loss: 0.1471

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9505 - loss: 0.1683

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9495 - loss: 0.1630

 37/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9569 - loss: 0.1530

 47/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9584 - loss: 0.1509

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9569 - loss: 0.1535

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9574 - loss: 0.1508

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9565 - loss: 0.1508

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9561 - loss: 0.1505

 99/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9577 - loss: 0.1495

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9581 - loss: 0.1488

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 0.1483 - val_acc: 0.9681 - val_loss: 0.0941

Epoch 5/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - acc: 0.9844 - loss: 0.1185

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9797 - loss: 0.1302

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9789 - loss: 0.1238

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9729 - loss: 0.1265

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.1219

 49/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.1201

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.1203

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9761 - loss: 0.1174

 77/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9767 - loss: 0.1161

 86/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9766 - loss: 0.1163

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9763 - loss: 0.1155

104/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9760 - loss: 0.1163

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9748 - loss: 0.1171 - val_acc: 0.9693 - val_loss: 0.0975

Epoch 6/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 44ms/step - acc: 0.9844 - loss: 0.1030

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9616 - loss: 0.1324

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9635 - loss: 0.1309

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9646 - loss: 0.1269

 40/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9699 - loss: 0.1175

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9719 - loss: 0.1132

 60/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9724 - loss: 0.1131

 70/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9746 - loss: 0.1089

 79/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9751 - loss: 0.1068

 88/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9759 - loss: 0.1056

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9762 - loss: 0.1047

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9762 - loss: 0.1045

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9760 - loss: 0.1041 - val_acc: 0.9737 - val_loss: 0.0770

Epoch 7/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9844 - loss: 0.0781

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9858 - loss: 0.0806

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9914 - loss: 0.0732

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9885 - loss: 0.0790

 41/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9855 - loss: 0.0833

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9850 - loss: 0.0828

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9810 - loss: 0.0886

 71/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9820 - loss: 0.0864

 81/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9828 - loss: 0.0846

 91/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9827 - loss: 0.0838

101/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9819 - loss: 0.0841

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9806 - loss: 0.0850

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9806 - loss: 0.0850 - val_acc: 0.8865 - val_loss: 0.2274

Epoch 8/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step - acc: 0.9844 - loss: 0.0683

 10/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9891 - loss: 0.0667

 20/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9922 - loss: 0.0588

 29/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9898 - loss: 0.0652

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9900 - loss: 0.0636

 50/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9887 - loss: 0.0672

 61/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9851 - loss: 0.0738

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9803 - loss: 0.0823

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9782 - loss: 0.0874

 95/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9732 - loss: 0.0959

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9670 - loss: 0.1014

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9658 - loss: 0.1027 - val_acc: 0.9955 - val_loss: 0.0443

Epoch 9/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 41ms/step - acc: 0.9531 - loss: 0.1201

 13/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9748 - loss: 0.0990

 23/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9769 - loss: 0.0916

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9801 - loss: 0.0859

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9803 - loss: 0.0840

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9810 - loss: 0.0816

 59/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9804 - loss: 0.0831

 69/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9814 - loss: 0.0800

 80/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9824 - loss: 0.0782

 89/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9830 - loss: 0.0770

 98/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9829 - loss: 0.0765

109/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9815 - loss: 0.0781

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9808 - loss: 0.0786 - val_acc: 0.9961 - val_loss: 0.0743

Epoch 10/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step - acc: 0.9531 - loss: 0.1036

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9773 - loss: 0.0766

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9777 - loss: 0.0757

 30/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9760 - loss: 0.0759

 39/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9756 - loss: 0.0763

 48/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9642 - loss: 0.1021

 58/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9661 - loss: 0.1001

 65/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9671 - loss: 0.0978

 74/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9692 - loss: 0.0941

 83/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9697 - loss: 0.0935

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9694 - loss: 0.0936

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9709 - loss: 0.0913

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9716 - loss: 0.0898

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9718 - loss: 0.0895 - val_acc: 0.9659 - val_loss: 0.0822

Epoch 11/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - acc: 0.9844 - loss: 0.0608

 11/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9872 - loss: 0.0623

 21/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9874 - loss: 0.0610

 31/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9879 - loss: 0.0598

 42/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9866 - loss: 0.0613

 52/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9829 - loss: 0.0655

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9821 - loss: 0.0683

 73/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9831 - loss: 0.0661

 84/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9833 - loss: 0.0661

 96/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9824 - loss: 0.0679

107/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9809 - loss: 0.0711

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9804 - loss: 0.0717 - val_acc: 0.9922 - val_loss: 0.0395

Epoch 12/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - acc: 0.9531 - loss: 0.1058

 14/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9632 - loss: 0.0917

 26/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9603 - loss: 0.0984

 38/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9527 - loss: 0.1083

 51/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9510 - loss: 0.1131

 62/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9506 - loss: 0.1153

 72/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9512 - loss: 0.1137

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9508 - loss: 0.1140

 92/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9489 - loss: 0.1142

102/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9481 - loss: 0.1146

112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9501 - loss: 0.1136

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9501 - loss: 0.1136 - val_acc: 0.9542 - val_loss: 0.0925

Epoch 13/500

  1/112 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - acc: 1.0000 - loss: 0.0720

 12/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9818 - loss: 0.0933

 22/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9794 - loss: 0.0917

 33/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9777 - loss: 0.0880

 43/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9771 - loss: 0.0879

 55/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9753 - loss: 0.0884

 68/112 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9745 - loss: 0.0869

 82/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9722 - loss: 0.0879

 97/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9721 - loss: 0.0888

111/112 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9696 - loss: 0.0918

112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - acc: 0.9698 - loss: 0.0916 - val_acc: 0.9732 - val_loss: 0.0528

Epoch 13: early stopping

Restoring model weights from the end of the best epoch: 3.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

  1/280 ━━━━━━━━━━━━━━━━━━━━ 1:10 253ms/step

 22/280 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

 41/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 61/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

 82/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

101/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

120/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

140/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

161/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

178/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

197/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

217/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

239/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

262/280 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

280/280 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step

[[0.03601617]
 [0.03601617]
 [0.03601617]
 ...
 [0.76057756]
 [0.76057756]
 [0.76057756]]
[[0.]
 [0.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]
[[6846  262]
 [ 266 1569]]
              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96      7108
         1.0       0.86      0.86      0.86      1835

    accuracy                           0.94      8943
   macro avg       0.91      0.91      0.91      8943
weighted avg       0.94      0.94      0.94      8943

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [25]:
from keras.models import load_model

model.save('Multivariate_Occupancy_RNN.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Multivariate_Occupancy_RNN.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 10, 30)         │         1,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 30)             │         1,830 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,825 (34.48 KB)

 Trainable params: 2,941 (11.49 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,884 (22.99 KB)

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [26]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Occupancy'].shift(1)
df.head()

   Temperature  Humidity  Light     CO2  HumidityRatio  Occupancy  Baseline
0        23.18   27.2720  426.0  721.25       0.004793          1       NaN
1        23.15   27.2675  429.5  714.00       0.004783          1       1.0
2        23.15   27.2450  426.0  713.50       0.004779          1       1.0
3        23.15   27.2000  426.0  708.25       0.004772          1       1.0
4        23.10   27.2000  426.0  704.50       0.004757          1       1.0

In [27]:
y_test_baseline = df['Baseline']
# just extract rows corresponding to y_test
y_test_baseline = y_test_baseline.tail(y_test.shape[0])
# verify shape
print(y_test.shape)
print(y_test_baseline.shape) # good!

(8943,)
(8943,)

In [28]:
# see how it does!
pred = y_test_baseline # the pred

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

[[7086   22]
 [  23 1812]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      7108
         1.0       0.99      0.99      0.99      1835

    accuracy                           0.99      8943
   macro avg       0.99      0.99      0.99      8943
weighted avg       0.99      0.99      0.99      8943

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\3878943032.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [29]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_7736\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
# be careful of the baseline model
# and make sure you choose an appropriate measure
# for the problem you are trying to solve...