<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Multivariate_Occupancy_RNN_AdvancedTopics.ipynb)

# Multivariate Example (Advanced Topics)
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict whether a room is occupied as a function of its environmental data - let's see if Conv1D and MaxPooling1D can make an even better prediction (ConvLSTM).

**Common errors:** forgetting an activation function, not specifying the input shape (or mixing up the order!), not returning sequences when two layers (or accidentally return_sequences=True when only one layer!)

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from LuisM78’s GitHub repository:
# url = 'https://raw.githubusercontent.com/LuisM78/Occupancy-detection-data/master/datatest.txt'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/datatest.txt"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 2665 entries, 140 to 2804
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2665 non-null   str
 1   Temperature    2665 non-null   float64
 2   Humidity       2665 non-null   float64
 3   Light          2665 non-null   float64
 4   CO2            2665 non-null   float64
 5   HumidityRatio  2665 non-null   float64
 6   Occupancy      2665 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 195.3 KB
None

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
140,2015-02-02 14:19:00,23.7000,26.272,585.200000,749.200000,0.004764,1
141,2015-02-02 14:19:59,23.7180,26.290,578.400000,760.400000,0.004773,1
142,2015-02-02 14:21:00,23.7300,26.230,572.666667,769.666667,0.004765,1
143,2015-02-02 14:22:00,23.7225,26.125,493.750000,774.750000,0.004744,1
144,2015-02-02 14:23:00,23.7540,26.200,488.600000,779.000000,0.004767,1
145,2015-02-02 14:23:59,23.7600,26.260,568.666667,790.000000,0.004779,1
146,2015-02-02 14:25:00,23.7300,26.290,536.333333,798.000000,0.004776,1
147,2015-02-02 14:25:59,23.7540,26.290,509.000000,797.000000,0.004783,1
148,2015-02-02 14:26:59,23.7540,26.350,476.000000,803.200000,0.004794,1
149,2015-02-02 14:28:00,23.7360,26.390,510.000000,809.000000,0.004796,1
150,2015-02-02 14:29:00,23.7450,26.445,481.500000,815.250000,0.004809,1
151,2015-02-02 14:30:00,23.7000,26.560,481.800000,824.000000,0.004817,1
152,2015-02-02 14:31:00,23.7000,26.600,475.250000,832.000000,0.004824,1
153,2015-02-02 14:31:59,23.7000,26.700,469.000000,845.333333,0.004842,1
154,2015-02-02 14:32:59,23.7000,26.774,464.000000,852.400000,0.004856,1

In [3]:
# count of occupancy
df['Occupancy'].value_counts() # not perfectly balanced, but that's OK

Occupancy
0    1693
1     972
Name: count, dtype: int64

In [4]:
# visualize the data
df['Occupancy'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\633319714.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [5]:
# visualize the data
df['CO2'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\165701153.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [6]:
# drop the date column
df.drop(['date'], inplace=True, axis=1)
print(df.shape)
df.head()

(2665, 6)

     Temperature  Humidity       Light         CO2  HumidityRatio  Occupancy
140      23.7000    26.272  585.200000  749.200000       0.004764          1
141      23.7180    26.290  578.400000  760.400000       0.004773          1
142      23.7300    26.230  572.666667  769.666667       0.004765          1
143      23.7225    26.125  493.750000  774.750000       0.004744          1
144      23.7540    26.200  488.600000  779.000000       0.004767          1

In [7]:
# prep data for modeling (multivariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

from numpy import array

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in np.arange(len(sequences)): # be careful of this line!
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [8]:
# we could split our data first, normalize it, then create sequences

In [9]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 50
raw_seq = np.array(df) #make sure your data is stored as a numpy array!
# let's ignore the date column and just use the temperature data
X, y = split_sequences(raw_seq, n_steps=50)

In [10]:
# take a peak at what it did
print(X.shape)
print(y.shape)

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

(2616, 50, 5)
(2616,)

In [11]:
# split the data into train and test partitions
# we will use 50% of the data for train, and 50% for validation
train_pct_index = int(0.5 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [12]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

# verify that this all adds up!
# 2635 samples with 30 lookback and 6 columns

(2616, 50, 5) (1308, 50, 5) (1308, 50, 5)
(2616,) (1308,) (1308,)

# RNN one layer model (with Conv1D and pooling!)
With Conv1D and MaxPooling1D... don't forget that input shape needs to go in the first layer!

In [13]:
n_steps = X_train.shape[1] # lookback
n_features = X_train.shape[2] # columns

print(n_steps, n_features)

50 5

In [14]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(SimpleRNN(30, activation='relu', recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,890 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12:54 4s/step - acc: 0.0000e+00 - loss: 153.9056

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.4444 - loss: 57.3732

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.6353 - loss: 39.0384

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.7040 - loss: 29.7398

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.7455 - loss: 23.8997

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.7854 - loss: 20.3690

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.8000 - loss: 18.5474

 57/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.8175 - loss: 17.2920

 65/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8215 - loss: 16.8538

 73/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8301 - loss: 15.9004

 81/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8247 - loss: 16.1616

 89/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8337 - loss: 15.0368

 97/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8330 - loss: 14.0584

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8419 - loss: 13.0494

113/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8478 - loss: 12.3664

121/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8562 - loss: 11.5932

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8651 - loss: 10.8742

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8701 - loss: 10.4541

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8772 - loss: 9.8774

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8824 - loss: 9.5641

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8845 - loss: 9.4806

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8899 - loss: 9.0318

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8938 - loss: 8.6301

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8962 - loss: 8.3406

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8990 - loss: 8.1089

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.8980 - loss: 7.9604

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9010 - loss: 7.7135

210/210 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - acc: 0.9006 - loss: 7.8033 - val_acc: 0.9771 - val_loss: 2.1761

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 42s 204ms/step - acc: 0.6000 - loss: 37.0469

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9333 - loss: 4.6659

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9647 - loss: 2.4702

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9600 - loss: 2.6908

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9636 - loss: 2.1383

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9561 - loss: 3.2380

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9551 - loss: 3.0587

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9500 - loss: 3.0254

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9469 - loss: 2.9283

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9472 - loss: 2.8469

 79/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9494 - loss: 2.7939

 85/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9529 - loss: 2.5967

 92/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9543 - loss: 2.4188

 99/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9556 - loss: 2.4310

107/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9551 - loss: 2.4847

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9548 - loss: 2.5143

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9496 - loss: 2.5059

131/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9511 - loss: 2.6117

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9493 - loss: 2.6644

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9493 - loss: 2.5680

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9494 - loss: 2.6193

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9494 - loss: 2.7016

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9482 - loss: 2.7812

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9494 - loss: 2.6974

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9492 - loss: 2.6630

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9513 - loss: 2.5527

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9512 - loss: 2.5028

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9522 - loss: 2.5053

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9522 - loss: 2.5029 - val_acc: 0.9771 - val_loss: 1.0906

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 53ms/step - acc: 1.0000 - loss: 3.1274e-14

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9778 - loss: 0.1251

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9765 - loss: 0.8597

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9833 - loss: 0.6089

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9812 - loss: 0.5271

 40/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9700 - loss: 1.1256

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9708 - loss: 1.0811

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9679 - loss: 0.9779

 63/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9587 - loss: 1.2288

 71/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9577 - loss: 1.4764

 79/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9570 - loss: 1.5407

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9586 - loss: 1.6058

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9621 - loss: 1.4705

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9612 - loss: 1.4504

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9622 - loss: 1.3784

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9613 - loss: 1.4924

120/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.9617 - loss: 1.4800

128/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9625 - loss: 1.4255

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9606 - loss: 1.3719

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9586 - loss: 1.3606

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9569 - loss: 1.4716

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9578 - loss: 1.4993

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9562 - loss: 1.5200

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9559 - loss: 1.4978

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9543 - loss: 1.5164

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9537 - loss: 1.4939

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9533 - loss: 1.4651

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - acc: 0.9551 - loss: 1.4080

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - acc: 0.9551 - loss: 1.4396 - val_acc: 0.9771 - val_loss: 1.7825

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - acc: 1.0000 - loss: 1.2877e-05

  8/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9750 - loss: 0.1506

 16/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9625 - loss: 1.8276

 23/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9565 - loss: 2.5430

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9677 - loss: 1.8867

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9737 - loss: 1.5392

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9522 - loss: 1.5701

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9556 - loss: 1.3470

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9484 - loss: 1.4615

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9429 - loss: 1.5691

 78/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9487 - loss: 1.4082

 86/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9535 - loss: 1.2775

 94/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9489 - loss: 1.5611

102/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9510 - loss: 1.5087

110/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9491 - loss: 1.4635

118/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9475 - loss: 1.4652

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9488 - loss: 1.4411

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9504 - loss: 1.3645

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9504 - loss: 1.3628

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9530 - loss: 1.2896

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9503 - loss: 1.2635

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9503 - loss: 1.2462

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9497 - loss: 1.2254

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9497 - loss: 1.2132

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9508 - loss: 1.2198

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9528 - loss: 1.1700

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9547 - loss: 1.1238

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9551 - loss: 1.1302 - val_acc: 0.9771 - val_loss: 0.7877

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 1.0000 - loss: 1.0405e-10

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9778 - loss: 0.3364

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9647 - loss: 0.3837

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9520 - loss: 0.2990

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9515 - loss: 0.5620

 40/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9550 - loss: 0.4683

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9583 - loss: 0.4009

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9464 - loss: 0.5230

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9469 - loss: 0.4995

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9472 - loss: 0.5039

 80/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9500 - loss: 0.4962

 88/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9477 - loss: 0.5152

 96/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9375 - loss: 0.5673

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9359 - loss: 0.5584

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9369 - loss: 0.5585

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9361 - loss: 0.5670

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9360 - loss: 0.5848

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9383 - loss: 0.5523

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9404 - loss: 0.5401

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9432 - loss: 0.5146

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9449 - loss: 0.5264

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9476 - loss: 0.5007

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9450 - loss: 0.5632

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9453 - loss: 0.5611

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9476 - loss: 0.5371

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9497 - loss: 0.5154

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9498 - loss: 0.5769

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9503 - loss: 0.5742 - val_acc: 0.9771 - val_loss: 0.3000

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 50ms/step - acc: 1.0000 - loss: 1.3891e-10

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9429 - loss: 0.3689

 14/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9571 - loss: 0.2093

 22/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.9364 - loss: 0.8967

 30/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9467 - loss: 0.6685

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9368 - loss: 0.6327

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9174 - loss: 0.6409

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9259 - loss: 0.7317

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9258 - loss: 0.7809

 69/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9188 - loss: 0.8207

 77/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9247 - loss: 0.7640

 83/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9229 - loss: 0.8735

 91/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9253 - loss: 0.8268

 99/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9253 - loss: 0.8287

107/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9290 - loss: 0.8326

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9322 - loss: 0.8308

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9366 - loss: 0.7767

131/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9374 - loss: 0.7582

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9333 - loss: 0.7758

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9366 - loss: 0.7384

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9368 - loss: 0.8419

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9388 - loss: 0.8514

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9417 - loss: 0.8108

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9386 - loss: 0.8293

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9348 - loss: 0.8327

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9375 - loss: 0.7980

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9397 - loss: 0.7699

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9401 - loss: 0.8711

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9407 - loss: 0.8619 - val_acc: 0.9771 - val_loss: 2.0269

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 1.9598e-13

 10/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9800 - loss: 1.2913

 18/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9667 - loss: 1.8203

 26/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9692 - loss: 1.3175

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9613 - loss: 1.5084

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9684 - loss: 1.2305

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9522 - loss: 1.1246

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9519 - loss: 0.9982

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9548 - loss: 0.8941

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9543 - loss: 0.8018

 78/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9564 - loss: 0.7246

 86/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9581 - loss: 0.7093

 94/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9596 - loss: 0.7181

102/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9627 - loss: 0.6618

109/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9651 - loss: 0.6193

117/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9675 - loss: 0.5769

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9696 - loss: 0.5400

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9714 - loss: 0.5075

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9702 - loss: 0.5202

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9718 - loss: 0.4923

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9732 - loss: 0.4674

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9685 - loss: 0.4935

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9630 - loss: 0.4877

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9624 - loss: 0.4822

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9628 - loss: 0.4682

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9612 - loss: 0.4846

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9586 - loss: 0.4786

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9579 - loss: 0.4710

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9579 - loss: 0.4710 - val_acc: 0.9771 - val_loss: 0.1147

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - acc: 1.0000 - loss: 0.0045

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 1.0000 - loss: 0.0085

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9882 - loss: 0.2826

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9840 - loss: 0.2044

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9818 - loss: 0.2250

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9854 - loss: 0.1812

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9875 - loss: 0.1553

 55/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9855 - loss: 0.1615

 63/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9841 - loss: 0.1445

 70/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9829 - loss: 0.1611

 77/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9844 - loss: 0.1489

 84/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9810 - loss: 0.1492

 91/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9758 - loss: 0.1486

 98/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9755 - loss: 0.1469

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9733 - loss: 0.1410

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9750 - loss: 0.1325

120/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9750 - loss: 0.1266

127/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9764 - loss: 0.1202

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9748 - loss: 0.1463

142/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9746 - loss: 0.1431

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9705 - loss: 0.1572

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9692 - loss: 0.1565

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9646 - loss: 0.1607

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9649 - loss: 0.1573

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9652 - loss: 0.1550

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9652 - loss: 0.1539

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9665 - loss: 0.1491

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9667 - loss: 0.1474

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9641 - loss: 0.1644

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - acc: 0.9627 - loss: 0.1647 - val_acc: 0.9771 - val_loss: 0.1590

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.0165

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.8667 - loss: 0.3462

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9294 - loss: 0.1860

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9520 - loss: 0.1368

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9515 - loss: 0.1750

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9463 - loss: 0.2230

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9417 - loss: 0.2093

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9393 - loss: 0.1953

 64/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9438 - loss: 0.1794

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9500 - loss: 0.1613

 80/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9550 - loss: 0.1456

 87/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9563 - loss: 0.1441

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9579 - loss: 0.1406

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9612 - loss: 0.1306

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9604 - loss: 0.1339

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9597 - loss: 0.1353

126/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9619 - loss: 0.1294

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9609 - loss: 0.1311

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9603 - loss: 0.1357

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9584 - loss: 0.1329

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9605 - loss: 0.1285

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9624 - loss: 0.1225

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9621 - loss: 0.1246

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9637 - loss: 0.1194

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9632 - loss: 0.1211

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9626 - loss: 0.1256

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9631 - loss: 0.1267

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9637 - loss: 0.1253 - val_acc: 0.9771 - val_loss: 0.1431

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - acc: 1.0000 - loss: 0.1018

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9333 - loss: 0.2945

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9529 - loss: 0.1929

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9520 - loss: 0.1664

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9636 - loss: 0.1346

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9659 - loss: 0.1224

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - acc: 0.9592 - loss: 0.1284

 58/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9586 - loss: 0.1391

 67/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9582 - loss: 0.1402

 75/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9627 - loss: 0.1269

 83/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9639 - loss: 0.1228

 91/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9670 - loss: 0.1127

 99/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9677 - loss: 0.1109

105/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9676 - loss: 0.1106

114/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9649 - loss: 0.1152

122/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9656 - loss: 0.1108

131/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9679 - loss: 0.1065

139/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9698 - loss: 0.1019

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9714 - loss: 0.0971

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9690 - loss: 0.1070

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9693 - loss: 0.1039

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9708 - loss: 0.1003

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9709 - loss: 0.0998

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9722 - loss: 0.0960

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9724 - loss: 0.0952

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9725 - loss: 0.0943

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9723 - loss: 0.0949 - val_acc: 0.9771 - val_loss: 0.1130

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 1.0000 - loss: 0.0122

  9/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9778 - loss: 0.0746

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9647 - loss: 0.1405

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9600 - loss: 0.1349

 33/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9697 - loss: 0.1060

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9756 - loss: 0.0881

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9755 - loss: 0.0854

 57/210 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.9789 - loss: 0.0760

 65/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9785 - loss: 0.0820

 72/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9778 - loss: 0.0884

 80/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9800 - loss: 0.0810

 88/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9795 - loss: 0.0803

 95/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9789 - loss: 0.0803

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9806 - loss: 0.0754

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9802 - loss: 0.0750

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9798 - loss: 0.0792

127/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9795 - loss: 0.0839

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9807 - loss: 0.0801

143/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9790 - loss: 0.0829

151/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9775 - loss: 0.0857

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9774 - loss: 0.0866

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9784 - loss: 0.0848

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.0952

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.0965

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.0945

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9747 - loss: 0.0944

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - acc: 0.9756 - loss: 0.0921

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - acc: 0.9761 - loss: 0.0904 - val_acc: 0.9771 - val_loss: 0.1107

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [15]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
pred # run all if you get an error...

 1/41 ━━━━━━━━━━━━━━━━━━━━ 14s 368ms/step

19/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

38/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(1308, 1), dtype=float32)

In [16]:
# confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

[[824  25]
 [  1 458]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98       849
         1.0       0.95      1.00      0.97       459

    accuracy                           0.98      1308
   macro avg       0.97      0.98      0.98      1308
weighted avg       0.98      0.98      0.98      1308

In [17]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\774347038.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [18]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step

20/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

40/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[824  25]
 [  1 458]]
              precision    recall  f1-score   support

         0.0       1.00      0.97      0.98       849
         1.0       0.95      1.00      0.97       459

    accuracy                           0.98      1308
   macro avg       0.97      0.98      0.98      1308
weighted avg       0.98      0.98      0.98      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [19]:
# now let's build a model

# define
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(SimpleRNN(30, return_sequences=True, recurrent_dropout=0.2))) # don't forget to return_sequences!
model.add(Bidirectional(SimpleRNN(30, recurrent_dropout=0.2)))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 24, 60)         │         3,780 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 60)             │         5,460 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            61 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,813 (38.33 KB)

 Trainable params: 9,813 (38.33 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 31:58 9s/step - acc: 0.6000 - loss: 0.5785

  5/210 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - acc: 0.8000 - loss: 0.4913

  8/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.8500 - loss: 0.3898

 12/210 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - acc: 0.8333 - loss: 0.3798

 15/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.8400 - loss: 0.3565

 18/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.8667 - loss: 0.3092

 21/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.8762 - loss: 0.2903

 24/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8667 - loss: 0.2994

 27/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8741 - loss: 0.2868

 30/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8800 - loss: 0.2808

 33/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8909 - loss: 0.2670

 36/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9000 - loss: 0.2647

 39/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9077 - loss: 0.2501

 42/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.8952 - loss: 0.2663

 45/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.8978 - loss: 0.2573

 48/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9000 - loss: 0.2522

 51/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.8980 - loss: 0.2498

 54/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9000 - loss: 0.2455

 57/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9018 - loss: 0.2395

 60/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.8933 - loss: 0.2524

 63/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.8984 - loss: 0.2445

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9000 - loss: 0.2442

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9043 - loss: 0.2348

 72/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9028 - loss: 0.2386

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9040 - loss: 0.2329

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9051 - loss: 0.2312

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9062 - loss: 0.2270

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9048 - loss: 0.2233

 87/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9080 - loss: 0.2194

 90/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9111 - loss: 0.2149

 93/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9118 - loss: 0.2121

 96/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9125 - loss: 0.2109

 99/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9131 - loss: 0.2122

102/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9137 - loss: 0.2093

105/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9124 - loss: 0.2086

108/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9148 - loss: 0.2050

111/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9171 - loss: 0.2011

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9175 - loss: 0.2057

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9197 - loss: 0.2033

120/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9167 - loss: 0.2170

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9187 - loss: 0.2124

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9190 - loss: 0.2095

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9209 - loss: 0.2062

132/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9212 - loss: 0.2033

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9230 - loss: 0.2002

138/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9246 - loss: 0.1961

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9262 - loss: 0.1924

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9278 - loss: 0.1890

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9279 - loss: 0.1871

150/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9293 - loss: 0.1840

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9307 - loss: 0.1816

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9321 - loss: 0.1787

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9321 - loss: 0.1795

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9325 - loss: 0.1787

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9325 - loss: 0.1789

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9325 - loss: 0.1786

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9337 - loss: 0.1762

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9337 - loss: 0.1759

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9326 - loss: 0.1767

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9304 - loss: 0.1828

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9293 - loss: 0.1866

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9305 - loss: 0.1845

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9305 - loss: 0.1841

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9316 - loss: 0.1821

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9327 - loss: 0.1800

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9337 - loss: 0.1780

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9327 - loss: 0.1828

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9327 - loss: 0.1819

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9337 - loss: 0.1801

210/210 ━━━━━━━━━━━━━━━━━━━━ 15s 27ms/step - acc: 0.9331 - loss: 0.1805 - val_acc: 0.9771 - val_loss: 0.1604

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 1.0000 - loss: 0.0202

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 1.0000 - loss: 0.0459

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.9714 - loss: 0.1073

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9600 - loss: 0.1467

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9538 - loss: 0.1415

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9625 - loss: 0.1190

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9684 - loss: 0.1188

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9727 - loss: 0.1069

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9760 - loss: 0.0980

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9786 - loss: 0.0977

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9806 - loss: 0.0932

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9765 - loss: 0.1038

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9784 - loss: 0.0988

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9800 - loss: 0.0945

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9814 - loss: 0.0908

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9826 - loss: 0.0883

 49/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9837 - loss: 0.0858

 52/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9808 - loss: 0.0846

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9782 - loss: 0.0905

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9793 - loss: 0.0886

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - acc: 0.9770 - loss: 0.1036

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9750 - loss: 0.1058

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9761 - loss: 0.1023

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9771 - loss: 0.0984

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9726 - loss: 0.1044

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9737 - loss: 0.1015

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9722 - loss: 0.1055

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9732 - loss: 0.1047

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9741 - loss: 0.1038

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9750 - loss: 0.1016

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9736 - loss: 0.1027

 94/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9745 - loss: 0.1008

 97/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9753 - loss: 0.0985

100/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9760 - loss: 0.0962

103/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9767 - loss: 0.0940

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9755 - loss: 0.0975

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9743 - loss: 0.1007

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9750 - loss: 0.0984

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9757 - loss: 0.0979

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9763 - loss: 0.0963

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9769 - loss: 0.0958

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9774 - loss: 0.0950

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9780 - loss: 0.0934

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9785 - loss: 0.0915

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9774 - loss: 0.0935

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9750 - loss: 0.1001

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9741 - loss: 0.1005

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9746 - loss: 0.0997

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9738 - loss: 0.1023

148/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9743 - loss: 0.1011

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9748 - loss: 0.0994

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9753 - loss: 0.0982

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9745 - loss: 0.0997

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9750 - loss: 0.0981

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9755 - loss: 0.0969

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9759 - loss: 0.0956

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9751 - loss: 0.0967

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9756 - loss: 0.0955

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9760 - loss: 0.0947

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9753 - loss: 0.0962

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9746 - loss: 0.0959

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9739 - loss: 0.0986

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9722 - loss: 0.1033

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9726 - loss: 0.1025

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9731 - loss: 0.1013

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9724 - loss: 0.1031

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9709 - loss: 0.1058

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9713 - loss: 0.1045

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9707 - loss: 0.1076

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9702 - loss: 0.1075

210/210 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - acc: 0.9704 - loss: 0.1075 - val_acc: 0.9771 - val_loss: 0.2726

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 57ms/step - acc: 1.0000 - loss: 0.0033

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 1.0000 - loss: 0.1019

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0898

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0686

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0558

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 1.0000 - loss: 0.0483

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9579 - loss: 0.1750

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9455 - loss: 0.1780

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9520 - loss: 0.1578

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9571 - loss: 0.1433

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9613 - loss: 0.1333

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9647 - loss: 0.1236

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9676 - loss: 0.1171

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9600 - loss: 0.1451

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9628 - loss: 0.1367

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9609 - loss: 0.1408

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9633 - loss: 0.1343

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9615 - loss: 0.1345

 55/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9636 - loss: 0.1302

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9655 - loss: 0.1250

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9672 - loss: 0.1207

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9688 - loss: 0.1169

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9701 - loss: 0.1128

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9714 - loss: 0.1095

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9671 - loss: 0.1240

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9684 - loss: 0.1207

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9696 - loss: 0.1168

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9683 - loss: 0.1185

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9694 - loss: 0.1152

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9682 - loss: 0.1182

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9670 - loss: 0.1170

 94/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9681 - loss: 0.1137

 97/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9670 - loss: 0.1172

100/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9680 - loss: 0.1148

103/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9689 - loss: 0.1133

106/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9698 - loss: 0.1109

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9706 - loss: 0.1094

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9696 - loss: 0.1127

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9687 - loss: 0.1139

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9695 - loss: 0.1113

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9686 - loss: 0.1111

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9694 - loss: 0.1095

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9669 - loss: 0.1147

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9677 - loss: 0.1123

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9684 - loss: 0.1106

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9662 - loss: 0.1163

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9669 - loss: 0.1146

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9676 - loss: 0.1130

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9683 - loss: 0.1125

148/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9689 - loss: 0.1120

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9682 - loss: 0.1128

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9688 - loss: 0.1112

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9694 - loss: 0.1096

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9688 - loss: 0.1108

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9693 - loss: 0.1091

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9687 - loss: 0.1096

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9692 - loss: 0.1079

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9698 - loss: 0.1063

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9703 - loss: 0.1047

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9697 - loss: 0.1066

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9691 - loss: 0.1081

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9696 - loss: 0.1069

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.9690 - loss: 0.1064

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9684 - loss: 0.1071

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9679 - loss: 0.1088

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9684 - loss: 0.1075

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9688 - loss: 0.1066

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9693 - loss: 0.1053

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9698 - loss: 0.1038

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9702 - loss: 0.1029

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9704 - loss: 0.1026 - val_acc: 0.9771 - val_loss: 0.1556

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 61ms/step - acc: 0.8000 - loss: 0.5690

  4/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 0.9500 - loss: 0.1738

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9714 - loss: 0.1342

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9800 - loss: 0.1145

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9846 - loss: 0.0967

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9875 - loss: 0.0833

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9684 - loss: 0.1594

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9727 - loss: 0.1393

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9680 - loss: 0.1440

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9714 - loss: 0.1298

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9742 - loss: 0.1184

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9706 - loss: 0.1222

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9676 - loss: 0.1337

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9650 - loss: 0.1392

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9674 - loss: 0.1313

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9696 - loss: 0.1247

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9714 - loss: 0.1178

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9692 - loss: 0.1218

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9709 - loss: 0.1165

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9724 - loss: 0.1118

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9738 - loss: 0.1072

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9719 - loss: 0.1091

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9731 - loss: 0.1052

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9714 - loss: 0.1110

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9726 - loss: 0.1087

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9737 - loss: 0.1055

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9747 - loss: 0.1024

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9756 - loss: 0.0990

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9741 - loss: 0.1006

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9750 - loss: 0.0989

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9758 - loss: 0.0959

 94/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9766 - loss: 0.0932

 97/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9773 - loss: 0.0912

100/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9780 - loss: 0.0892

103/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9786 - loss: 0.0870

106/210 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - acc: 0.9792 - loss: 0.0849

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9798 - loss: 0.0839

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9804 - loss: 0.0818

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9809 - loss: 0.0798

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9814 - loss: 0.0784

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9818 - loss: 0.0772

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9806 - loss: 0.0807

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9780 - loss: 0.0936

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9769 - loss: 0.0973

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9774 - loss: 0.0955

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9779 - loss: 0.0938

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9770 - loss: 0.0994

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9761 - loss: 0.1021

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9764 - loss: 0.1011

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9755 - loss: 0.1044

150/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9747 - loss: 0.1051

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9752 - loss: 0.1038

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9744 - loss: 0.1063

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9736 - loss: 0.1092

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9741 - loss: 0.1086

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9733 - loss: 0.1093

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9738 - loss: 0.1082

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9719 - loss: 0.1114

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9713 - loss: 0.1125

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9718 - loss: 0.1107

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9700 - loss: 0.1117

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9705 - loss: 0.1104

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9688 - loss: 0.1161

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9693 - loss: 0.1145

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9698 - loss: 0.1129

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9703 - loss: 0.1112

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9707 - loss: 0.1101

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9711 - loss: 0.1102

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9716 - loss: 0.1087

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9710 - loss: 0.1090

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9713 - loss: 0.1079

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9713 - loss: 0.1079 - val_acc: 0.9771 - val_loss: 0.1369

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 60ms/step - acc: 1.0000 - loss: 0.0386

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 1.0000 - loss: 0.0260

  7/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 0.9714 - loss: 0.1001

 10/210 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - acc: 0.9600 - loss: 0.1249

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9692 - loss: 0.1028

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9750 - loss: 0.0921

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9789 - loss: 0.0833

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9818 - loss: 0.0735

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9840 - loss: 0.0679

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9857 - loss: 0.0628

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9871 - loss: 0.0589

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9765 - loss: 0.0882

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9784 - loss: 0.0848

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9750 - loss: 0.1015

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9767 - loss: 0.0952

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9783 - loss: 0.0896

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9796 - loss: 0.0852

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9769 - loss: 0.0922

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9782 - loss: 0.0880

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9759 - loss: 0.0911

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9770 - loss: 0.0874

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9781 - loss: 0.0855

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9761 - loss: 0.0910

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9771 - loss: 0.0874

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9699 - loss: 0.1096

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9711 - loss: 0.1071

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9722 - loss: 0.1061

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9707 - loss: 0.1067

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9718 - loss: 0.1053

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9727 - loss: 0.1018

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9714 - loss: 0.1035

 94/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9723 - loss: 0.1020

 97/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9711 - loss: 0.1050

100/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9720 - loss: 0.1029

103/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9728 - loss: 0.1008

106/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9736 - loss: 0.0991

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9743 - loss: 0.0965

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9732 - loss: 0.0981

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9722 - loss: 0.1009

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9712 - loss: 0.1035

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9702 - loss: 0.1042

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9710 - loss: 0.1019

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9717 - loss: 0.1005

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9723 - loss: 0.0986

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9714 - loss: 0.0989

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9721 - loss: 0.0973

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9712 - loss: 0.0987

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9718 - loss: 0.0973

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9710 - loss: 0.0980

148/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9716 - loss: 0.0971

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9722 - loss: 0.0962

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9714 - loss: 0.1034

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9720 - loss: 0.1019

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9725 - loss: 0.1001

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9718 - loss: 0.1016

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9711 - loss: 0.1035

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9704 - loss: 0.1039

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9709 - loss: 0.1029

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9703 - loss: 0.1052

178/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9708 - loss: 0.1039

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9713 - loss: 0.1028

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9685 - loss: 0.1073

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9690 - loss: 0.1064

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9695 - loss: 0.1049

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9679 - loss: 0.1068

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9684 - loss: 0.1059

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9688 - loss: 0.1048

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9693 - loss: 0.1039

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9696 - loss: 0.1033

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9700 - loss: 0.1022

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9704 - loss: 0.1013

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9704 - loss: 0.1013 - val_acc: 0.9771 - val_loss: 0.1111

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - acc: 1.0000 - loss: 0.0426

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9500 - loss: 0.2002

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9429 - loss: 0.2346

 10/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 0.9600 - loss: 0.1679

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9538 - loss: 0.1714

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9625 - loss: 0.1408

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9579 - loss: 0.1532

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9545 - loss: 0.1605

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9440 - loss: 0.1991

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9429 - loss: 0.1852

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9419 - loss: 0.1946

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9471 - loss: 0.1790

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9459 - loss: 0.1745

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9450 - loss: 0.1806

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9442 - loss: 0.1867

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9435 - loss: 0.1801

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9469 - loss: 0.1730

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9500 - loss: 0.1636

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9527 - loss: 0.1590

 58/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9483 - loss: 0.1702

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9508 - loss: 0.1627

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9531 - loss: 0.1576

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9552 - loss: 0.1538

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9571 - loss: 0.1484

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9589 - loss: 0.1455

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9605 - loss: 0.1415

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9620 - loss: 0.1387

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9610 - loss: 0.1385

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9624 - loss: 0.1346

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9614 - loss: 0.1373

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9604 - loss: 0.1408

 93/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9591 - loss: 0.1452

 96/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9604 - loss: 0.1421

 99/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9616 - loss: 0.1385

102/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9627 - loss: 0.1352

105/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9638 - loss: 0.1323

108/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9648 - loss: 0.1291

111/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9640 - loss: 0.1325

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9649 - loss: 0.1298

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9658 - loss: 0.1269

120/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9667 - loss: 0.1240

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9675 - loss: 0.1215

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9683 - loss: 0.1192

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9674 - loss: 0.1260

132/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9682 - loss: 0.1235

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9674 - loss: 0.1237

138/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9681 - loss: 0.1214

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9688 - loss: 0.1192

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9694 - loss: 0.1171

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9701 - loss: 0.1149

150/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9707 - loss: 0.1128

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9712 - loss: 0.1112

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9718 - loss: 0.1093

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9723 - loss: 0.1074

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.1056

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9732 - loss: 0.1044

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9735 - loss: 0.1037

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.1071

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9721 - loss: 0.1091

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9724 - loss: 0.1080

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9729 - loss: 0.1068

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9733 - loss: 0.1060

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9738 - loss: 0.1047

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9742 - loss: 0.1039

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9734 - loss: 0.1039

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9738 - loss: 0.1027

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9742 - loss: 0.1012

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9736 - loss: 0.1024

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9740 - loss: 0.1012

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9734 - loss: 0.1016

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9728 - loss: 0.1044

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9732 - loss: 0.1037

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - acc: 0.9732 - loss: 0.1036 - val_acc: 0.9771 - val_loss: 0.1681

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 14s 70ms/step - acc: 1.0000 - loss: 0.0019

  4/210 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - acc: 1.0000 - loss: 0.0397

  7/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 1.0000 - loss: 0.0388

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 1.0000 - loss: 0.0420

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0335

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 1.0000 - loss: 0.0311

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 1.0000 - loss: 0.0279

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9909 - loss: 0.0470

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9920 - loss: 0.0439

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9929 - loss: 0.0407

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9935 - loss: 0.0386

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9765 - loss: 0.0800

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9784 - loss: 0.0741

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9800 - loss: 0.0722

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9814 - loss: 0.0695

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9783 - loss: 0.0753

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9796 - loss: 0.0732

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9808 - loss: 0.0706

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9818 - loss: 0.0730

 58/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9793 - loss: 0.0799

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9803 - loss: 0.0767

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9781 - loss: 0.0837

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9791 - loss: 0.0815

 70/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9800 - loss: 0.0784

 73/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9808 - loss: 0.0767

 76/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9816 - loss: 0.0743

 79/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9823 - loss: 0.0721

 82/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9805 - loss: 0.0783

 85/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9812 - loss: 0.0766

 88/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9818 - loss: 0.0747

 91/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9824 - loss: 0.0724

 94/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9830 - loss: 0.0705

 97/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9814 - loss: 0.0725

100/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9820 - loss: 0.0706

103/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9825 - loss: 0.0689

106/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9811 - loss: 0.0749

109/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9817 - loss: 0.0733

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9821 - loss: 0.0719

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9809 - loss: 0.0768

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9814 - loss: 0.0752

121/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9802 - loss: 0.0789

124/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9790 - loss: 0.0800

127/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9780 - loss: 0.0805

130/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9785 - loss: 0.0793

133/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9774 - loss: 0.0803

136/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9779 - loss: 0.0791

139/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9784 - loss: 0.0782

142/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9775 - loss: 0.0846

145/210 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - acc: 0.9766 - loss: 0.0923

148/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9770 - loss: 0.0909

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9775 - loss: 0.0896

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9766 - loss: 0.0900

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9758 - loss: 0.0921

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9762 - loss: 0.0908

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9741 - loss: 0.0969

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9745 - loss: 0.0954

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9738 - loss: 0.0974

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9731 - loss: 0.0994

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9736 - loss: 0.0979

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9729 - loss: 0.0999

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9722 - loss: 0.1019

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9727 - loss: 0.1004

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9731 - loss: 0.1000

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9725 - loss: 0.1014

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.1006

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9711 - loss: 0.1019

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9716 - loss: 0.1011

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9720 - loss: 0.1005

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9724 - loss: 0.0999

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.0990

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9732 - loss: 0.0977

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9732 - loss: 0.0976 - val_acc: 0.9771 - val_loss: 0.1724

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 62ms/step - acc: 1.0000 - loss: 0.0287

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 1.0000 - loss: 0.0563

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 1.0000 - loss: 0.0431

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0441

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 1.0000 - loss: 0.0361

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9875 - loss: 0.0588

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9895 - loss: 0.0522

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9909 - loss: 0.0535

 24/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9917 - loss: 0.0502

 27/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9926 - loss: 0.0482

 30/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9867 - loss: 0.0675

 33/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9879 - loss: 0.0616

 36/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9833 - loss: 0.0623

 39/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9846 - loss: 0.0587

 42/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9857 - loss: 0.0548

 45/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9867 - loss: 0.0535

 48/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9875 - loss: 0.0506

 51/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9882 - loss: 0.0496

 54/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9852 - loss: 0.0692

 57/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9860 - loss: 0.0667

 60/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9867 - loss: 0.0643

 63/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9873 - loss: 0.0616

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9818 - loss: 0.0780

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9797 - loss: 0.0844

 72/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9806 - loss: 0.0812

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9813 - loss: 0.0782

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9795 - loss: 0.0843

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9802 - loss: 0.0815

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9810 - loss: 0.0804

 87/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9747 - loss: 0.0956

 90/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9756 - loss: 0.0929

 93/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9763 - loss: 0.0908

 96/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9771 - loss: 0.0883

 99/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9758 - loss: 0.0902

102/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9765 - loss: 0.0889

105/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9771 - loss: 0.0870

108/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9759 - loss: 0.0899

111/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9766 - loss: 0.0876

114/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9772 - loss: 0.0861

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9778 - loss: 0.0845

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9782 - loss: 0.0840

122/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9770 - loss: 0.0866

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9760 - loss: 0.0897

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9750 - loss: 0.0895

131/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9756 - loss: 0.0880

134/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9746 - loss: 0.0901

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9723 - loss: 0.0934

140/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9729 - loss: 0.0919

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9734 - loss: 0.0906

146/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9726 - loss: 0.0930

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9732 - loss: 0.0915

151/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9735 - loss: 0.0912

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9725 - loss: 0.0927

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9718 - loss: 0.0924

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9723 - loss: 0.0920

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9727 - loss: 0.0918

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9718 - loss: 0.0980

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9723 - loss: 0.0973

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9728 - loss: 0.0956

172/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9721 - loss: 0.0967

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9703 - loss: 0.1003

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9695 - loss: 0.1036

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9700 - loss: 0.1025

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9705 - loss: 0.1012

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9708 - loss: 0.1006

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9711 - loss: 0.0999

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9705 - loss: 0.1024

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9699 - loss: 0.1031

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9703 - loss: 0.1023

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9707 - loss: 0.1014

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9701 - loss: 0.1037

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9696 - loss: 0.1054

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9699 - loss: 0.1049

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9700 - loss: 0.1045

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - acc: 0.9703 - loss: 0.1037

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - acc: 0.9704 - loss: 0.1036 - val_acc: 0.9771 - val_loss: 0.1779

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - acc: 1.0000 - loss: 0.0563

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9500 - loss: 0.1448

  7/210 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - acc: 0.9714 - loss: 0.1068

  9/210 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - acc: 0.9778 - loss: 0.0837

 12/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9833 - loss: 0.0756

 14/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9857 - loss: 0.0666

 16/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.9875 - loss: 0.0677

 19/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9895 - loss: 0.0596

 22/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9818 - loss: 0.0896

 24/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.9750 - loss: 0.0933

 27/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9778 - loss: 0.0866

 29/210 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - acc: 0.9793 - loss: 0.0834

 32/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9812 - loss: 0.0790

 35/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9829 - loss: 0.0744

 38/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9842 - loss: 0.0694

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9850 - loss: 0.0670

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9860 - loss: 0.0644

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9870 - loss: 0.0610

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9878 - loss: 0.0584

 51/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9882 - loss: 0.0572

 54/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9889 - loss: 0.0567

 57/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9860 - loss: 0.0650

 60/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9867 - loss: 0.0622

 63/210 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - acc: 0.9810 - loss: 0.0853

 66/210 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - acc: 0.9788 - loss: 0.0927

 69/210 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - acc: 0.9739 - loss: 0.1036

 72/210 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - acc: 0.9750 - loss: 0.1011

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9760 - loss: 0.0979

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9744 - loss: 0.1015

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9728 - loss: 0.1073

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - acc: 0.9738 - loss: 0.1047

 87/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9724 - loss: 0.1059

 90/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9733 - loss: 0.1033

 93/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9742 - loss: 0.1007

 96/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9750 - loss: 0.0993

 99/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9758 - loss: 0.0974

101/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9762 - loss: 0.0962

104/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9750 - loss: 0.0990

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9757 - loss: 0.0971

110/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9764 - loss: 0.0951

113/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9770 - loss: 0.0927

116/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9776 - loss: 0.0906

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9765 - loss: 0.0950

122/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9770 - loss: 0.0928

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9776 - loss: 0.0908

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9750 - loss: 0.0949

131/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9740 - loss: 0.0967

134/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9746 - loss: 0.0948

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9723 - loss: 0.1036

140/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9714 - loss: 0.1049

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9720 - loss: 0.1037

146/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9712 - loss: 0.1053

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9718 - loss: 0.1047

152/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9724 - loss: 0.1040

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9729 - loss: 0.1029

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9734 - loss: 0.1014

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - acc: 0.9727 - loss: 0.1044

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9732 - loss: 0.1033

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9737 - loss: 0.1030

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9741 - loss: 0.1013

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9746 - loss: 0.0996

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9727 - loss: 0.1050

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9721 - loss: 0.1054

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9725 - loss: 0.1038

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9730 - loss: 0.1024

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9733 - loss: 0.1015

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9735 - loss: 0.1006

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9729 - loss: 0.1014

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9722 - loss: 0.1015

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9726 - loss: 0.1003

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9730 - loss: 0.0998

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9724 - loss: 0.1003

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9728 - loss: 0.0993

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9732 - loss: 0.0981

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 23ms/step - acc: 0.9732 - loss: 0.0981 - val_acc: 0.9771 - val_loss: 0.1487

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.0435

  4/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9500 - loss: 0.1368

  7/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9714 - loss: 0.1115

  9/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9778 - loss: 0.0958

 12/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9667 - loss: 0.1307

 15/210 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - acc: 0.9733 - loss: 0.1057

 18/210 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - acc: 0.9778 - loss: 0.0917

 21/210 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - acc: 0.9810 - loss: 0.0825

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9760 - loss: 0.0820

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9714 - loss: 0.0911

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9677 - loss: 0.1042

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9706 - loss: 0.0952

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9730 - loss: 0.0902

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9750 - loss: 0.0866

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9767 - loss: 0.0842

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9696 - loss: 0.0930

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9714 - loss: 0.0889

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9731 - loss: 0.0856

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9709 - loss: 0.0886

 57/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9719 - loss: 0.0866

 60/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9733 - loss: 0.0828

 63/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9746 - loss: 0.0812

 66/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9727 - loss: 0.0856

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9739 - loss: 0.0834

 72/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9750 - loss: 0.0804

 75/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9733 - loss: 0.0865

 78/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9744 - loss: 0.0840

 81/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9753 - loss: 0.0819

 84/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9762 - loss: 0.0802

 87/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9770 - loss: 0.0782

 90/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9778 - loss: 0.0764

 93/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9785 - loss: 0.0745

 96/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9792 - loss: 0.0730

 99/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9798 - loss: 0.0711

102/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9784 - loss: 0.0752

104/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9788 - loss: 0.0760

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9757 - loss: 0.0882

110/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9764 - loss: 0.0873

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9770 - loss: 0.0852

116/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9776 - loss: 0.0838

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9782 - loss: 0.0820

122/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9787 - loss: 0.0804

125/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9760 - loss: 0.0862

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9750 - loss: 0.0885

131/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9756 - loss: 0.0871

134/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9761 - loss: 0.0853

137/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9766 - loss: 0.0843

140/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9771 - loss: 0.0830

143/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9748 - loss: 0.0890

146/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9740 - loss: 0.0912

149/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9745 - loss: 0.0900

152/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9724 - loss: 0.0961

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9729 - loss: 0.0954

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9732 - loss: 0.0944

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9725 - loss: 0.0957

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.0955

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9732 - loss: 0.0950

167/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9725 - loss: 0.0974

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9729 - loss: 0.0961

173/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9734 - loss: 0.0951

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9716 - loss: 0.0990

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9721 - loss: 0.0975

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9725 - loss: 0.0965

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9730 - loss: 0.0954

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9734 - loss: 0.0941

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9728 - loss: 0.0962

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9722 - loss: 0.0984

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9726 - loss: 0.0970

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9730 - loss: 0.0956

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9723 - loss: 0.0963

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9727 - loss: 0.0950

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9729 - loss: 0.0947

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9732 - loss: 0.0939

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9732 - loss: 0.0939 - val_acc: 0.9771 - val_loss: 0.1286

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 60ms/step - acc: 0.8000 - loss: 0.7065

  4/210 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - acc: 0.9000 - loss: 0.2334

  7/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9429 - loss: 0.1431

 10/210 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - acc: 0.9600 - loss: 0.1061

 13/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9692 - loss: 0.0883

 16/210 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - acc: 0.9750 - loss: 0.0776

 19/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9789 - loss: 0.0690

 22/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9818 - loss: 0.0627

 25/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9840 - loss: 0.0575

 28/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9857 - loss: 0.0533

 31/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9806 - loss: 0.0644

 34/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9765 - loss: 0.0816

 37/210 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - acc: 0.9622 - loss: 0.1189

 40/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9650 - loss: 0.1117

 43/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9674 - loss: 0.1058

 46/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9696 - loss: 0.1010

 49/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9714 - loss: 0.0965

 52/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9731 - loss: 0.0942

 55/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9745 - loss: 0.0895

 58/210 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - acc: 0.9759 - loss: 0.0863

 61/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9770 - loss: 0.0824

 64/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9781 - loss: 0.0804

 67/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9791 - loss: 0.0771

 69/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9797 - loss: 0.0757

 71/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9775 - loss: 0.0780

 74/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9757 - loss: 0.0835

 77/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9740 - loss: 0.0893

 80/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9750 - loss: 0.0872

 83/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9735 - loss: 0.0912

 86/210 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - acc: 0.9721 - loss: 0.0936

 89/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9708 - loss: 0.0956

 92/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9717 - loss: 0.0934

 95/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9726 - loss: 0.0913

 98/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9714 - loss: 0.0955

101/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9703 - loss: 0.0987

104/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9712 - loss: 0.0976

107/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9720 - loss: 0.0968

110/210 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - acc: 0.9709 - loss: 0.1006

113/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9699 - loss: 0.1020

116/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9707 - loss: 0.1012

118/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9712 - loss: 0.0999

120/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9717 - loss: 0.0982

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9707 - loss: 0.1011

126/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9714 - loss: 0.0990

129/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9721 - loss: 0.0974

132/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9727 - loss: 0.0966

135/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9719 - loss: 0.1030

138/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9710 - loss: 0.1060

141/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9716 - loss: 0.1038

144/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9708 - loss: 0.1057

147/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9714 - loss: 0.1046

150/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9707 - loss: 0.1068

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9712 - loss: 0.1049

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9718 - loss: 0.1032

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - acc: 0.9723 - loss: 0.1016

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9727 - loss: 0.1006

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9720 - loss: 0.1032

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9723 - loss: 0.1024

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9726 - loss: 0.1016

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9731 - loss: 0.1000

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9736 - loss: 0.0989

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9739 - loss: 0.0978

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9743 - loss: 0.0974

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.9747 - loss: 0.0960

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9753 - loss: 0.0943

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9746 - loss: 0.0937

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9750 - loss: 0.0927

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9744 - loss: 0.0942

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9747 - loss: 0.0929

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9741 - loss: 0.0944

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9745 - loss: 0.0934

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9739 - loss: 0.0955

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.9742 - loss: 0.0945

210/210 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step - acc: 0.9742 - loss: 0.0945 - val_acc: 0.9771 - val_loss: 0.1344

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [20]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 38s 957ms/step

10/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

19/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

28/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

37/41 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step

[[0.89254713]
 [0.8925893 ]
 [0.89255244]
 ...
 [0.91341794]
 [0.9134065 ]
 [0.9134327 ]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
[[804  45]
 [  7 452]]
              precision    recall  f1-score   support

         0.0       0.99      0.95      0.97       849
         1.0       0.91      0.98      0.95       459

    accuracy                           0.96      1308
   macro avg       0.95      0.97      0.96      1308
weighted avg       0.96      0.96      0.96      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [21]:
# define shape
n_steps = X_train.shape[1]
n_features = X_train.shape[2]


# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(LSTM(30, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 48, 32)         │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 24, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 30)             │         7,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,103 (31.65 KB)

 Trainable params: 8,103 (31.65 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 15:02 4s/step - acc: 0.0000e+00 - loss: 85.5527

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.0857 - loss: 75.9975

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.3077 - loss: 58.4141

 19/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.4947 - loss: 42.5371

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.5917 - loss: 34.1582

 29/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.5655 - loss: 30.9691

 35/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.4743 - loss: 27.2012

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.4244 - loss: 26.4339

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.3957 - loss: 24.4172

 51/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.3686 - loss: 24.1833

 57/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.3404 - loss: 23.7337

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.3258 - loss: 22.2406

 68/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.3147 - loss: 21.6748

 74/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2946 - loss: 21.1174

 79/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2810 - loss: 20.3221

 85/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2635 - loss: 19.7591

 90/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2556 - loss: 19.0488

 96/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2646 - loss: 18.0278

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.2961 - loss: 17.1294

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.3185 - loss: 16.4965

113/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.3434 - loss: 15.8515

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.3630 - loss: 15.2334

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.3808 - loss: 14.6254

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4015 - loss: 14.1565

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4193 - loss: 13.6570

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4340 - loss: 13.1608

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4490 - loss: 12.6510

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4601 - loss: 12.1806

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4717 - loss: 11.7989

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4848 - loss: 11.4011

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.4929 - loss: 11.0855

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5006 - loss: 10.7879

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5122 - loss: 10.5078

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5215 - loss: 10.2318

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5267 - loss: 10.0716

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5316 - loss: 9.9146

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5396 - loss: 9.6763

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.5471 - loss: 9.4151

210/210 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - acc: 0.5497 - loss: 9.3647 - val_acc: 0.7824 - val_loss: 0.3936

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - acc: 0.8000 - loss: 8.0081

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8857 - loss: 1.6905

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8923 - loss: 1.4467

 19/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6421 - loss: 1.3476

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.5920 - loss: 1.1972

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6194 - loss: 1.1794

 37/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6649 - loss: 1.0901

 43/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6791 - loss: 1.0287

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6667 - loss: 0.9931

 53/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.6679 - loss: 0.9620

 59/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.6881 - loss: 0.9281

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7031 - loss: 0.9165

 70/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7143 - loss: 0.9133

 75/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7280 - loss: 0.9004

 80/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7375 - loss: 0.8828

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7465 - loss: 0.8705

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7522 - loss: 0.8644

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7588 - loss: 0.8544

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7667 - loss: 0.8437

108/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7741 - loss: 0.8306

114/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7719 - loss: 0.8208

119/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7731 - loss: 0.8127

125/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7744 - loss: 0.8043

131/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7756 - loss: 0.7958

137/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7766 - loss: 0.7887

142/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7789 - loss: 0.7829

148/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7797 - loss: 0.7764

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7831 - loss: 0.7697

160/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7837 - loss: 0.7641

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7867 - loss: 0.7582

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7836 - loss: 0.7552

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7818 - loss: 0.7520

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7824 - loss: 0.7469

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7798 - loss: 0.7437

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7794 - loss: 0.7400

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7779 - loss: 0.7373

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7784 - loss: 0.7343

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7772 - loss: 0.7318

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.7772 - loss: 0.7318 - val_acc: 0.0229 - val_loss: 0.8503

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 52ms/step - acc: 0.8000 - loss: 0.6135

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7714 - loss: 0.5904

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7385 - loss: 0.6220

 18/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7222 - loss: 0.6343

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7417 - loss: 0.6286

 30/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7667 - loss: 0.6209

 36/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7722 - loss: 0.6191

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7805 - loss: 0.6163

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7957 - loss: 0.6111

 51/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7961 - loss: 0.6107

 57/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7895 - loss: 0.6127

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7935 - loss: 0.6110

 68/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7853 - loss: 0.6141

 74/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7865 - loss: 0.6138

 80/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7850 - loss: 0.6141

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7884 - loss: 0.6125

 92/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7913 - loss: 0.6112

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7918 - loss: 0.6107

104/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7865 - loss: 0.6114

110/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7873 - loss: 0.6108

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7862 - loss: 0.6108

121/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7884 - loss: 0.6096

127/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7969 - loss: 0.6059

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7985 - loss: 0.6049

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8014 - loss: 0.6035

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8042 - loss: 0.6020

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8054 - loss: 0.6012

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8052 - loss: 0.6008

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8063 - loss: 0.6001

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8049 - loss: 0.6004

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8071 - loss: 0.5992

175/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8091 - loss: 0.5979

180/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8089 - loss: 0.5977

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8065 - loss: 0.5982

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8084 - loss: 0.5970

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8102 - loss: 0.5958

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8049 - loss: 0.5977

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8029 - loss: 0.5982

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8040 - loss: 0.5976 - val_acc: 0.0229 - val_loss: 0.9305

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - acc: 0.8000 - loss: 0.5842

  7/210 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - acc: 0.8000 - loss: 0.5839

 12/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.7833 - loss: 0.5931

 16/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.7750 - loss: 0.5962

 22/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.7636 - loss: 0.6012

 27/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7778 - loss: 0.5939

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7750 - loss: 0.5952

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7684 - loss: 0.5983

 43/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7721 - loss: 0.5962

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7796 - loss: 0.5926

 55/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7927 - loss: 0.5861

 61/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7902 - loss: 0.5872

 67/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7761 - loss: 0.5935

 73/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7781 - loss: 0.5921

 78/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7821 - loss: 0.5899

 83/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7855 - loss: 0.5878

 88/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7864 - loss: 0.5871

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7830 - loss: 0.5885

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7880 - loss: 0.5856

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7868 - loss: 0.5859

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7893 - loss: 0.5843

118/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7983 - loss: 0.5793

124/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5782

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8062 - loss: 0.5746

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8088 - loss: 0.5722

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8099 - loss: 0.5713

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8055 - loss: 0.5734

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8118 - loss: 0.5697

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8101 - loss: 0.5703

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8122 - loss: 0.5688

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8141 - loss: 0.5674

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8136 - loss: 0.5673

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8144 - loss: 0.5666

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8096 - loss: 0.5684

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8083 - loss: 0.5689

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8051 - loss: 0.5705

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8039 - loss: 0.5705

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8038 - loss: 0.5702

210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - acc: 0.8040 - loss: 0.5701 - val_acc: 0.0229 - val_loss: 1.0074

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 18s 87ms/step - acc: 0.8000 - loss: 0.5618

  6/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8000 - loss: 0.5615

 11/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.7818 - loss: 0.5724

 16/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8125 - loss: 0.5542

 21/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8000 - loss: 0.5573

 26/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8077 - loss: 0.5533

 29/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.8069 - loss: 0.5539

 33/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.8061 - loss: 0.5549

 38/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.7895 - loss: 0.5649

 43/210 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - acc: 0.7860 - loss: 0.5669

 48/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.7917 - loss: 0.5636

 53/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.7925 - loss: 0.5631

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.7897 - loss: 0.5649

 63/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8000 - loss: 0.5585

 69/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8029 - loss: 0.5565

 75/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8080 - loss: 0.5532

 81/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8099 - loss: 0.5497

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8116 - loss: 0.5486

 91/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8088 - loss: 0.5504

 96/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8062 - loss: 0.5518

101/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8099 - loss: 0.5494

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8094 - loss: 0.5497

112/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8054 - loss: 0.5521

117/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8034 - loss: 0.5532

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8065 - loss: 0.5510

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8062 - loss: 0.5510

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8074 - loss: 0.5500

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8057 - loss: 0.5509

145/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8069 - loss: 0.5500

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8080 - loss: 0.5492

155/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8090 - loss: 0.5483

161/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8099 - loss: 0.5475

166/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8060 - loss: 0.5500

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8070 - loss: 0.5491

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8057 - loss: 0.5499

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8066 - loss: 0.5490

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8097 - loss: 0.5468

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8083 - loss: 0.5475

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8071 - loss: 0.5482

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8079 - loss: 0.5474

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - acc: 0.8048 - loss: 0.5493

210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - acc: 0.8040 - loss: 0.5498 - val_acc: 0.0229 - val_loss: 1.0803

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 0.8000 - loss: 0.5447

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7714 - loss: 0.5649

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7231 - loss: 0.5983

 19/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7368 - loss: 0.5887

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7440 - loss: 0.5834

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7548 - loss: 0.5761

 37/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7622 - loss: 0.5708

 42/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7762 - loss: 0.5608

 47/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7915 - loss: 0.5498

 52/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7923 - loss: 0.5492

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7897 - loss: 0.5509

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7969 - loss: 0.5455

 69/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8058 - loss: 0.5389

 75/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8027 - loss: 0.5410

 81/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8049 - loss: 0.5392

 87/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8000 - loss: 0.5426

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7935 - loss: 0.5472

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7959 - loss: 0.5452

104/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7962 - loss: 0.5449

110/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7982 - loss: 0.5425

116/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5410

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8000 - loss: 0.5408

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8016 - loss: 0.5395

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8059 - loss: 0.5360

141/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8014 - loss: 0.5392

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8054 - loss: 0.5360

153/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8026 - loss: 0.5380

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8063 - loss: 0.5345

165/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8048 - loss: 0.5355

171/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8070 - loss: 0.5337

177/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8068 - loss: 0.5337

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8044 - loss: 0.5350

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8095 - loss: 0.5308

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8031 - loss: 0.5357

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8050 - loss: 0.5341

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8029 - loss: 0.5356

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8040 - loss: 0.5346 - val_acc: 0.0229 - val_loss: 1.1457

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - acc: 0.8000 - loss: 0.5324

  8/210 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - acc: 0.7000 - loss: 0.6112

 14/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7714 - loss: 0.5546

 20/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7600 - loss: 0.5636

 26/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7692 - loss: 0.5565

 32/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7563 - loss: 0.5646

 38/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7632 - loss: 0.5574

 44/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7773 - loss: 0.5465

 50/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7920 - loss: 0.5349

 56/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7964 - loss: 0.5315

 62/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7903 - loss: 0.5367

 68/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7853 - loss: 0.5409

 74/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7784 - loss: 0.5466

 80/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7750 - loss: 0.5494

 85/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7812 - loss: 0.5443

 91/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7780 - loss: 0.5470

 97/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7794 - loss: 0.5459

103/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7786 - loss: 0.5465

109/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7835 - loss: 0.5425

115/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7896 - loss: 0.5374

121/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7950 - loss: 0.5328

127/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7953 - loss: 0.5325

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7940 - loss: 0.5336

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7942 - loss: 0.5333

144/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7958 - loss: 0.5318

150/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.7973 - loss: 0.5305

156/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8013 - loss: 0.5270

162/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8025 - loss: 0.5259

168/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8048 - loss: 0.5234

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8023 - loss: 0.5255

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8011 - loss: 0.5264

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8000 - loss: 0.5273

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8021 - loss: 0.5254

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8010 - loss: 0.5262

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8020 - loss: 0.5253

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - acc: 0.8029 - loss: 0.5244

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8040 - loss: 0.5234 - val_acc: 0.0229 - val_loss: 1.2054

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 62ms/step - acc: 1.0000 - loss: 0.3477

  6/210 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - acc: 0.8000 - loss: 0.5236

 12/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8333 - loss: 0.4942

 18/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8111 - loss: 0.5135

 24/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8167 - loss: 0.5083

 30/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8067 - loss: 0.5169

 35/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8114 - loss: 0.5126

 40/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8050 - loss: 0.5182

 46/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7957 - loss: 0.5249

 52/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7962 - loss: 0.5245

 58/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7931 - loss: 0.5273

 64/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7781 - loss: 0.5408

 70/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7657 - loss: 0.5520

 76/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7684 - loss: 0.5496

 82/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7707 - loss: 0.5467

 87/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7632 - loss: 0.5535

 93/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7634 - loss: 0.5534

 99/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7697 - loss: 0.5478

105/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7714 - loss: 0.5463

111/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7784 - loss: 0.5394

117/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7829 - loss: 0.5353

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7886 - loss: 0.5301

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7953 - loss: 0.5239

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5196

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5196

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7973 - loss: 0.5221

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5195

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8013 - loss: 0.5183

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8037 - loss: 0.5160

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8059 - loss: 0.5139

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8057 - loss: 0.5140

181/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8066 - loss: 0.5130

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8075 - loss: 0.5122

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8062 - loss: 0.5133

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8061 - loss: 0.5134

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8050 - loss: 0.5144

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8038 - loss: 0.5154

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8040 - loss: 0.5152 - val_acc: 0.0229 - val_loss: 1.2613

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 62ms/step - acc: 0.8000 - loss: 0.5163

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8000 - loss: 0.5162

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8154 - loss: 0.5014

 19/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8316 - loss: 0.4858

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8240 - loss: 0.4930

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8387 - loss: 0.4786

 37/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8378 - loss: 0.4793

 43/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8372 - loss: 0.4798

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8286 - loss: 0.4881

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8185 - loss: 0.4979

 60/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8133 - loss: 0.5029

 66/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.8152 - loss: 0.5011

 72/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8139 - loss: 0.5013

 78/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8128 - loss: 0.5023

 84/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8095 - loss: 0.5055

 90/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8044 - loss: 0.5105

 95/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8021 - loss: 0.5127

101/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8040 - loss: 0.5109

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8057 - loss: 0.5091

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8036 - loss: 0.5111

118/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8068 - loss: 0.5079

124/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8081 - loss: 0.5066

130/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8077 - loss: 0.5069

136/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8044 - loss: 0.5101

142/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5145

147/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7973 - loss: 0.5172

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8000 - loss: 0.5140

157/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8051 - loss: 0.5088

163/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8049 - loss: 0.5090

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8036 - loss: 0.5103

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8057 - loss: 0.5077

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8056 - loss: 0.5078

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8076 - loss: 0.5057

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8063 - loss: 0.5070

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8061 - loss: 0.5071

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8069 - loss: 0.5062

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8048 - loss: 0.5084

210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - acc: 0.8040 - loss: 0.5092 - val_acc: 0.0229 - val_loss: 1.3092

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - acc: 1.0000 - loss: 0.3063

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7714 - loss: 0.5413

 12/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8500 - loss: 0.4604

 17/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8235 - loss: 0.4876

 22/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8182 - loss: 0.4930

 26/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8154 - loss: 0.4958

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.8258 - loss: 0.4850

 36/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7889 - loss: 0.5231

 41/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7854 - loss: 0.5267

 45/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7956 - loss: 0.5161

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7959 - loss: 0.5157

 53/210 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - acc: 0.7962 - loss: 0.5153

 57/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8000 - loss: 0.5114

 61/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.7934 - loss: 0.5182

 65/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8000 - loss: 0.5113

 68/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8059 - loss: 0.5052

 72/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8167 - loss: 0.4939

 76/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8237 - loss: 0.4865

 81/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8296 - loss: 0.4802

 86/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8233 - loss: 0.4868

 90/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8244 - loss: 0.4849

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8213 - loss: 0.4882

 98/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8224 - loss: 0.4869

102/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8196 - loss: 0.4899

106/210 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.8170 - loss: 0.4926

111/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8054 - loss: 0.5048

115/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8070 - loss: 0.5032

119/210 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.8034 - loss: 0.5069

123/210 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - acc: 0.8098 - loss: 0.5001

128/210 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - acc: 0.8062 - loss: 0.5038

133/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8090 - loss: 0.5008

138/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8087 - loss: 0.5012

142/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8070 - loss: 0.5029

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8068 - loss: 0.5031

149/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8081 - loss: 0.5018

154/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8078 - loss: 0.5020

159/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8101 - loss: 0.4995

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8085 - loss: 0.5011

169/210 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - acc: 0.8083 - loss: 0.5014

174/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8069 - loss: 0.5025

179/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8067 - loss: 0.5027

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8065 - loss: 0.5028

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8053 - loss: 0.5041

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8062 - loss: 0.5028

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8040 - loss: 0.5052

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - acc: 0.8039 - loss: 0.5052

210/210 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - acc: 0.8040 - loss: 0.5051 - val_acc: 0.0229 - val_loss: 1.3482

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - acc: 1.0000 - loss: 0.2922

  7/210 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - acc: 0.7429 - loss: 0.5701

 13/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.7846 - loss: 0.5249

 19/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8105 - loss: 0.4938

 25/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8000 - loss: 0.5060

 31/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8194 - loss: 0.4854

 37/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8378 - loss: 0.4654

 43/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8233 - loss: 0.4815

 49/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8122 - loss: 0.4937

 54/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8185 - loss: 0.4868

 60/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8233 - loss: 0.4816

 66/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8273 - loss: 0.4773

 72/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8306 - loss: 0.4736

 78/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8282 - loss: 0.4762

 83/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8265 - loss: 0.4781

 88/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8318 - loss: 0.4721

 94/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8340 - loss: 0.4696

100/210 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - acc: 0.8280 - loss: 0.4763

106/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8208 - loss: 0.4843

112/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8250 - loss: 0.4795

118/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8186 - loss: 0.4866

123/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8179 - loss: 0.4874

129/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8171 - loss: 0.4883

135/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8119 - loss: 0.4941

140/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8129 - loss: 0.4929

146/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8096 - loss: 0.4965

152/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8092 - loss: 0.4969

158/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8101 - loss: 0.4959

164/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8085 - loss: 0.4976

170/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8082 - loss: 0.4979

176/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8057 - loss: 0.5008

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8033 - loss: 0.5031

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8021 - loss: 0.5041

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.7990 - loss: 0.5077

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8010 - loss: 0.5054

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - acc: 0.8029 - loss: 0.5032

210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - acc: 0.8040 - loss: 0.5020 - val_acc: 0.0229 - val_loss: 1.3836

Epoch 11: early stopping

Restoring model weights from the end of the best epoch: 1.

In [22]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 13s 349ms/step

13/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

26/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

39/41 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step

[[0.5886785 ]
 [0.6291187 ]
 [0.6119151 ]
 ...
 [0.7392143 ]
 [0.49463767]
 [0.46719462]]
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [0.]
 [0.]]
[[799  50]
 [228 231]]
              precision    recall  f1-score   support

         0.0       0.78      0.94      0.85       849
         1.0       0.82      0.50      0.62       459

    accuracy                           0.79      1308
   macro avg       0.80      0.72      0.74      1308
weighted avg       0.79      0.79      0.77      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM two layer model

In [23]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)

# define model
model = Sequential()
model.add(Conv1D(filters=128, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Bidirectional(LSTM(30,
                            return_sequences=True, # remember, if stacking layers, you need to return sequences!
                            activation='relu',
                            recurrent_dropout=0.2)))
model.add(GRU(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
model.summary()

es = EarlyStopping(monitor='val_acc', mode='max',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 48, 128)        │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 24, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 24, 60)         │        38,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 20)             │         4,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 45,149 (176.36 KB)

 Trainable params: 45,149 (176.36 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 46:25 13s/step - acc: 0.2000 - loss: 49.6751

  4/210 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - acc: 0.1000 - loss: 92.6699

  6/210 ━━━━━━━━━━━━━━━━━━━━ 5s 29ms/step - acc: 0.1000 - loss: 71.0803

  8/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.1250 - loss: 62.3209

 10/210 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - acc: 0.1400 - loss: 67.8024

 12/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.1667 - loss: 62.2339

 14/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.2000 - loss: 60.3942

 16/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.2375 - loss: 56.3374

 18/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.2556 - loss: 51.5147

 20/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.2600 - loss: 48.9221

 22/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.2545 - loss: 47.8357

 24/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.2500 - loss: 48.0506

 26/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.2769 - loss: 45.1646

 28/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.3286 - loss: 41.9408

 30/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.3400 - loss: 39.9661

 32/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.3500 - loss: 41.0561

 34/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.3588 - loss: 40.4211

 36/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.3889 - loss: 38.6551

 38/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4053 - loss: 37.1078

 40/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4200 - loss: 35.9338

 42/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4286 - loss: 35.1884

 44/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4409 - loss: 33.9066

 46/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4478 - loss: 33.3490

 48/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4458 - loss: 36.2249

 50/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4520 - loss: 35.1837

 52/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4423 - loss: 42.1879

 54/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.4407 - loss: 41.6859

 56/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4429 - loss: 41.8433

 58/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4448 - loss: 43.4451

 60/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4600 - loss: 42.0810

 62/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4613 - loss: 44.0874

 64/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4656 - loss: 44.1984

 66/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.4667 - loss: 44.4751

 68/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.4735 - loss: 43.5558

 70/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.4771 - loss: 43.9115

 72/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.4861 - loss: 43.0309

 74/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.4865 - loss: 42.5336

 76/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.4947 - loss: 41.6932

 78/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5026 - loss: 40.7302

 80/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5050 - loss: 41.2094

 82/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5073 - loss: 40.8225

 84/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5095 - loss: 40.9301

 86/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5093 - loss: 41.4719

 88/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5091 - loss: 41.9242

 90/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5067 - loss: 42.3725

 92/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5087 - loss: 43.3365

 94/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5149 - loss: 42.9774

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.5158 - loss: 42.7974

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5175 - loss: 42.3783

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5091 - loss: 48.9887

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5129 - loss: 49.0760

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5126 - loss: 49.9136

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5162 - loss: 50.7030

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5159 - loss: 51.9243

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5229 - loss: 51.1059

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5243 - loss: 50.9026

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5310 - loss: 53.8989

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5287 - loss: 53.5414

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5316 - loss: 52.9069

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5328 - loss: 53.6465

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5355 - loss: 52.9849

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5350 - loss: 53.4192

125/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.5312 - loss: 55.2950

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5276 - loss: 55.0620

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5287 - loss: 54.9180

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5282 - loss: 56.0185

132/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5288 - loss: 55.8683

134/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5284 - loss: 56.5779

136/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5309 - loss: 56.0872

138/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5333 - loss: 55.4403

140/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5329 - loss: 61.7075

142/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5366 - loss: 61.1679

144/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5347 - loss: 60.7034

146/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5370 - loss: 60.6674

148/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5365 - loss: 61.1913

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5347 - loss: 60.8860

152/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5368 - loss: 60.5197

154/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.5403 - loss: 59.8095

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5423 - loss: 59.7769

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5430 - loss: 59.5475

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5437 - loss: 59.2538

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5469 - loss: 58.7562

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5512 - loss: 58.1211

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5506 - loss: 58.5113

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5500 - loss: 58.6073

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5506 - loss: 58.0053

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5523 - loss: 57.3615

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5517 - loss: 57.0591

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5500 - loss: 56.7223

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5483 - loss: 56.6355

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5478 - loss: 56.2773

182/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.5495 - loss: 56.0370

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5489 - loss: 55.9168

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5473 - loss: 56.4631

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5447 - loss: 57.1496

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5463 - loss: 57.2546

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5490 - loss: 56.8333

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5505 - loss: 57.8913

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5480 - loss: 58.6602

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.5485 - loss: 58.9522

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5490 - loss: 58.8149

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5515 - loss: 58.2947

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5520 - loss: 57.8870

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5495 - loss: 57.7343

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5490 - loss: 57.4355

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.5478 - loss: 57.6881

210/210 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - acc: 0.5478 - loss: 57.6881 - val_acc: 0.3740 - val_loss: 312.7802

Epoch 2/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 17s 85ms/step - acc: 0.6000 - loss: 135.5623

  3/210 ━━━━━━━━━━━━━━━━━━━━ 8s 43ms/step - acc: 0.6667 - loss: 55.7691

  5/210 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - acc: 0.6800 - loss: 107.7513

  7/210 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - acc: 0.6571 - loss: 95.4902

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5778 - loss: 82.5021

 11/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.5636 - loss: 87.5427

 13/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.5846 - loss: 81.0574

 15/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.5733 - loss: 84.2747

 16/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5750 - loss: 79.2076

 18/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5667 - loss: 75.6185

 19/210 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - acc: 0.5789 - loss: 75.7497

 21/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5619 - loss: 73.7685

 23/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5478 - loss: 92.2170

 25/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.5440 - loss: 87.5569

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5704 - loss: 81.1786

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5793 - loss: 80.5007

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5484 - loss: 82.6060

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5636 - loss: 77.6874

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5600 - loss: 75.7019

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5405 - loss: 79.0920

 39/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5282 - loss: 79.5494

 41/210 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - acc: 0.5220 - loss: 80.1545

 43/210 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - acc: 0.5070 - loss: 79.8382

 45/210 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - acc: 0.5067 - loss: 78.9011

 46/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5043 - loss: 79.3068

 48/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.4958 - loss: 77.9511

 50/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5000 - loss: 75.1893

 52/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5038 - loss: 74.3889

 54/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5111 - loss: 72.8733

 56/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5143 - loss: 72.9282

 58/210 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - acc: 0.5241 - loss: 70.5155

 60/210 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.5333 - loss: 68.6403

 62/210 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.5419 - loss: 66.8847

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.5460 - loss: 65.9293

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - acc: 0.5508 - loss: 64.2701

 67/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5552 - loss: 65.1201

 69/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5536 - loss: 64.3857

 71/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5549 - loss: 62.9279

 73/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5562 - loss: 61.5295

 75/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5600 - loss: 60.2167

 77/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5558 - loss: 60.2907

 79/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5519 - loss: 59.2225

 81/210 ━━━━━━━━━━━━━━━━━━━━ 5s 39ms/step - acc: 0.5556 - loss: 58.6926

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5590 - loss: 57.8728

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5624 - loss: 56.8590

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5609 - loss: 55.7063

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5618 - loss: 54.8948

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5560 - loss: 53.8205

 93/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5527 - loss: 53.3659

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5495 - loss: 52.5535

 96/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5458 - loss: 52.1480

 98/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5469 - loss: 51.1706

100/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5460 - loss: 50.9981

102/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5510 - loss: 50.5906

104/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5519 - loss: 50.0433

106/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.5547 - loss: 50.5405

108/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5537 - loss: 49.9995

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5523 - loss: 49.6615

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5604 - loss: 48.7667

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5611 - loss: 48.5525

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5670 - loss: 47.7298

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5675 - loss: 47.2756

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5697 - loss: 49.0384

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5686 - loss: 48.6252

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5675 - loss: 50.3164

125/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5680 - loss: 49.5937

127/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.5701 - loss: 48.8675

129/210 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.5690 - loss: 48.4006

131/210 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - acc: 0.5725 - loss: 47.8613

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - acc: 0.5714 - loss: 47.2544

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5733 - loss: 46.7564

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5737 - loss: 46.3006

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5755 - loss: 45.7280

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5773 - loss: 45.3150

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5804 - loss: 44.8052

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5834 - loss: 44.2087

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5850 - loss: 43.8699

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5839 - loss: 43.5535

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5868 - loss: 43.1276

153/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5882 - loss: 42.6492

155/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5923 - loss: 42.1142

157/210 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - acc: 0.5975 - loss: 41.5777

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6000 - loss: 41.1936

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6012 - loss: 40.7326

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6049 - loss: 40.3171

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6036 - loss: 40.2721

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6048 - loss: 39.9820

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6071 - loss: 39.5831

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6070 - loss: 39.1842

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6092 - loss: 38.8399

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6126 - loss: 38.4198

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6113 - loss: 38.2447

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6112 - loss: 37.8386

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6099 - loss: 37.6962

183/210 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - acc: 0.6077 - loss: 39.4065

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6097 - loss: 39.0009

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6107 - loss: 38.5992

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6074 - loss: 38.4658

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6073 - loss: 39.1867

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6062 - loss: 38.9701

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6082 - loss: 38.6851

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - acc: 0.6112 - loss: 38.2933

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6121 - loss: 47.3660

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6139 - loss: 48.0143

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6128 - loss: 50.0155

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6146 - loss: 49.5498

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6145 - loss: 49.6007

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.6163 - loss: 49.2728

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - acc: 0.6166 - loss: 49.2257 - val_acc: 0.4427 - val_loss: 8.4505

Epoch 3/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 64ms/step - acc: 0.6000 - loss: 4.6005

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.8000 - loss: 1.8510

  5/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.7600 - loss: 3.4908

  7/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.7143 - loss: 12.1696

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.6889 - loss: 14.2995

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7091 - loss: 15.3098

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7077 - loss: 14.7629

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7067 - loss: 14.8767

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7059 - loss: 13.7581

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6632 - loss: 20.2363

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6762 - loss: 19.2893

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6870 - loss: 17.9178

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6880 - loss: 16.6783

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6815 - loss: 16.7229

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.6621 - loss: 17.7572

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.6387 - loss: 17.6314

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.6182 - loss: 21.5837

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.6171 - loss: 21.3838

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5946 - loss: 26.7844

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5897 - loss: 25.8029

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5902 - loss: 27.2147

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5814 - loss: 27.5238

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5822 - loss: 26.4256

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5830 - loss: 25.5238

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5796 - loss: 24.8551

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5765 - loss: 24.1819

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5811 - loss: 23.7564

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5745 - loss: 25.2041

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5825 - loss: 24.4168

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.5797 - loss: 23.8849

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.5803 - loss: 23.4516

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.5810 - loss: 23.0602

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.5723 - loss: 24.0772

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.5731 - loss: 24.3012

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5739 - loss: 24.5733

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5690 - loss: 24.2578

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5726 - loss: 24.2567

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5787 - loss: 23.7282

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5844 - loss: 23.2507

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5873 - loss: 22.9931

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5926 - loss: 22.6244

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.5952 - loss: 22.1661

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.6000 - loss: 23.1219

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.6046 - loss: 22.7878

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.6022 - loss: 22.6038

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.6022 - loss: 22.3161

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6065 - loss: 21.9094

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6126 - loss: 21.4545

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6124 - loss: 21.1859

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6121 - loss: 22.6911

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6099 - loss: 22.4598

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6117 - loss: 24.1295

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6114 - loss: 23.7360

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6112 - loss: 23.5296

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6110 - loss: 23.2319

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6126 - loss: 22.8859

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6142 - loss: 22.6393

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6157 - loss: 22.3250

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6171 - loss: 22.2896

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6168 - loss: 22.0496

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.6182 - loss: 21.8448

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6195 - loss: 23.2909

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6176 - loss: 23.1734

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6157 - loss: 22.8771

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6202 - loss: 22.6967

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6214 - loss: 23.7535

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6226 - loss: 23.5280

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6207 - loss: 23.4581

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6219 - loss: 23.1617

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6201 - loss: 22.9786

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6199 - loss: 22.8161

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6182 - loss: 22.6996

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6234 - loss: 22.3894

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6245 - loss: 22.1637

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6255 - loss: 21.9846

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.6238 - loss: 21.7839

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.6248 - loss: 21.7407

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6271 - loss: 21.4912

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6293 - loss: 21.2360

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6277 - loss: 21.0609

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6273 - loss: 20.8438

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6282 - loss: 20.7226

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6242 - loss: 20.6083

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6251 - loss: 20.4459

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6284 - loss: 20.2234

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6304 - loss: 20.0151

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6324 - loss: 19.8129

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6331 - loss: 19.5975

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6339 - loss: 19.4539

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6346 - loss: 19.3975

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6365 - loss: 19.2313

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6372 - loss: 19.1078

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6400 - loss: 18.9204

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6406 - loss: 18.7341

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6381 - loss: 18.8301

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6387 - loss: 18.6782

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6404 - loss: 18.5674

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6369 - loss: 18.4199

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6355 - loss: 18.3632

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6332 - loss: 18.2204

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6318 - loss: 18.0593

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6315 - loss: 18.0498

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6302 - loss: 17.8932

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6309 - loss: 17.7307

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6325 - loss: 17.5661

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - acc: 0.6319 - loss: 17.5541 - val_acc: 0.0229 - val_loss: 8.9539

Epoch 4/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 14s 69ms/step - acc: 0.4000 - loss: 2.1757

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.5333 - loss: 9.0292

  5/210 ━━━━━━━━━━━━━━━━━━━━ 8s 39ms/step - acc: 0.4800 - loss: 10.6712

  7/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.4286 - loss: 8.0926

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.4444 - loss: 7.2711

 11/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.4727 - loss: 6.1633

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.4769 - loss: 5.5870

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.5200 - loss: 4.9251

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.5647 - loss: 4.3725

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.5895 - loss: 4.1074

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.5905 - loss: 4.7014

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.5826 - loss: 4.9994

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.6080 - loss: 4.6208

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.6222 - loss: 4.7399

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.6207 - loss: 7.0324

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.6323 - loss: 6.6027

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.6121 - loss: 6.4689

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.6057 - loss: 6.1623

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.6000 - loss: 5.9267

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5897 - loss: 5.9853

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5902 - loss: 5.7336

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5767 - loss: 5.5576

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5778 - loss: 5.3691

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5787 - loss: 5.3616

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5918 - loss: 5.1491

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5922 - loss: 4.9752

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5887 - loss: 4.8486

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5891 - loss: 4.7214

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5930 - loss: 4.6792

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5932 - loss: 4.5927

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5934 - loss: 4.4829

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.5968 - loss: 4.3829

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.6092 - loss: 4.2503

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6149 - loss: 4.1319

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6174 - loss: 5.5492

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6225 - loss: 5.4764

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6247 - loss: 5.4549

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6187 - loss: 5.4222

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6208 - loss: 5.2919

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6228 - loss: 5.1678

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6198 - loss: 5.2034

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6217 - loss: 5.1909

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6188 - loss: 6.9288

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6184 - loss: 6.8223

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6135 - loss: 6.7578

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6110 - loss: 6.8252

 93/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6129 - loss: 6.7568

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.6126 - loss: 6.6549

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6124 - loss: 6.5592

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6141 - loss: 6.4990

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6178 - loss: 6.3854

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6175 - loss: 6.4394

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6210 - loss: 6.5108

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6243 - loss: 6.4134

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6220 - loss: 6.3414

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6252 - loss: 6.2410

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6301 - loss: 6.2248

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6296 - loss: 6.7317

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6274 - loss: 6.8131

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6286 - loss: 6.7473

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6281 - loss: 6.6506

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.6260 - loss: 6.6871

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6224 - loss: 6.7374

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6220 - loss: 6.6543

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6248 - loss: 6.5580

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6275 - loss: 6.5186

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6301 - loss: 8.4070

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6326 - loss: 8.5757

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6365 - loss: 8.4534

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6374 - loss: 8.3507

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6411 - loss: 8.5904

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6462 - loss: 8.4720

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6455 - loss: 8.4273

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6463 - loss: 8.4089

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6470 - loss: 8.3175

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.6503 - loss: 8.2191

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6497 - loss: 8.3360

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6516 - loss: 8.2914

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6561 - loss: 8.1863

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6591 - loss: 8.6870

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6634 - loss: 8.5801

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6650 - loss: 8.4974

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6691 - loss: 8.3959

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6719 - loss: 8.2979

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6698 - loss: 8.2959

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6655 - loss: 8.2892

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6671 - loss: 8.2129

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6663 - loss: 8.2861

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6621 - loss: 8.4002

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6626 - loss: 8.3112

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.6608 - loss: 8.2345

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6568 - loss: 8.1864

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6541 - loss: 8.1389

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6524 - loss: 8.0916

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6497 - loss: 8.0247

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6450 - loss: 7.9620

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6415 - loss: 8.1677

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6421 - loss: 8.0890

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6426 - loss: 8.1014

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6432 - loss: 8.0359

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6418 - loss: 7.9927

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6424 - loss: 9.3973

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6449 - loss: 9.3557

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6415 - loss: 17.8005

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.6431 - loss: 17.6846

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.6434 - loss: 17.6677 - val_acc: 0.0420 - val_loss: 7.4248

Epoch 5/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 16s 78ms/step - acc: 0.8000 - loss: 1.7724

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 34ms/step - acc: 0.6667 - loss: 2.0651

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8000 - loss: 1.2965

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7714 - loss: 2.3605

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7556 - loss: 2.5076

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7455 - loss: 2.8812

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7538 - loss: 20.1353

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7733 - loss: 17.6098

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7647 - loss: 15.9235

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7789 - loss: 18.4290

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7619 - loss: 20.2098

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7739 - loss: 18.5643

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7680 - loss: 17.4989

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7481 - loss: 16.4331

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7448 - loss: 15.3987

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7548 - loss: 14.9737

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7576 - loss: 15.9980

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7600 - loss: 15.1930

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7514 - loss: 15.1529

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7538 - loss: 14.4339

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7610 - loss: 21.1773

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7674 - loss: 20.2040

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7733 - loss: 19.3179

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7660 - loss: 18.6528

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7714 - loss: 17.9080

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7804 - loss: 17.2186

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7849 - loss: 16.8627

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7782 - loss: 16.3490

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7825 - loss: 15.7902

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7797 - loss: 15.2950

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7836 - loss: 14.8489

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7841 - loss: 14.5895

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7785 - loss: 14.1785

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7791 - loss: 13.8266

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7826 - loss: 13.4555

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7831 - loss: 13.1604

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7808 - loss: 12.8493

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7707 - loss: 12.6206

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7714 - loss: 12.3066

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7722 - loss: 12.0621

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7728 - loss: 11.7807

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7711 - loss: 11.5171

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7718 - loss: 11.2562

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7655 - loss: 11.0356

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7663 - loss: 10.8004

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7692 - loss: 11.0211

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7699 - loss: 10.7936

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7600 - loss: 11.1371

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7588 - loss: 11.0548

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7596 - loss: 10.8572

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7545 - loss: 10.7770

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7456 - loss: 11.1001

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7352 - loss: 12.3141

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7327 - loss: 12.1289

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7321 - loss: 11.9439

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7315 - loss: 11.7689

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7292 - loss: 11.6502

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7252 - loss: 11.4666

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7231 - loss: 11.3269

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7210 - loss: 12.5958

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7174 - loss: 12.4245

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7171 - loss: 14.9718

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7168 - loss: 14.7414

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7213 - loss: 14.5127

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7194 - loss: 14.3071

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7176 - loss: 14.2614

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7173 - loss: 14.2980

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7170 - loss: 14.7157

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7168 - loss: 14.5256

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7180 - loss: 14.3311

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7191 - loss: 14.1358

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7189 - loss: 14.1736

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7200 - loss: 13.9914

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7224 - loss: 13.8114

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7235 - loss: 13.6311

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7245 - loss: 13.4648

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7255 - loss: 13.2980

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7265 - loss: 13.1325

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7287 - loss: 12.9700

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7270 - loss: 12.8316

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7292 - loss: 12.6742

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7325 - loss: 12.5211

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7333 - loss: 12.4037

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7341 - loss: 12.2607

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7349 - loss: 12.1213

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7345 - loss: 12.0013

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7376 - loss: 11.8640

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7349 - loss: 11.7808

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7345 - loss: 11.7366

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7363 - loss: 11.6152

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7344 - loss: 11.8758

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7352 - loss: 11.7481

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7348 - loss: 11.6367

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7323 - loss: 12.0540

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7316 - loss: 12.0024

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7333 - loss: 11.8785

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7337 - loss: 11.8176

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7344 - loss: 11.6973

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7351 - loss: 11.5857

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7367 - loss: 11.4699

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7354 - loss: 11.5129

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7360 - loss: 11.5409

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7376 - loss: 11.4306

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7373 - loss: 11.4251

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7379 - loss: 11.3215

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7385 - loss: 11.2164

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - acc: 0.7371 - loss: 12.4042

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - acc: 0.7371 - loss: 12.4042 - val_acc: 0.1183 - val_loss: 1.0010

Epoch 6/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 13s 64ms/step - acc: 0.8000 - loss: 0.5617

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.6667 - loss: 0.7091

  5/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.7200 - loss: 0.8549

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8000 - loss: 0.6702

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8222 - loss: 0.5869

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8182 - loss: 0.6593

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8154 - loss: 0.6476

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8000 - loss: 2.0048

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8118 - loss: 1.8072

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7895 - loss: 1.7401

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7619 - loss: 1.7933

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7565 - loss: 1.6753

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7520 - loss: 1.5855

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7481 - loss: 1.5340

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7586 - loss: 1.4666

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7419 - loss: 1.7737

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7333 - loss: 1.6942

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7429 - loss: 1.6213

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7243 - loss: 1.5882

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7179 - loss: 1.5515

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7122 - loss: 1.5208

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7070 - loss: 1.6065

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7111 - loss: 1.5545

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7064 - loss: 1.5125

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7061 - loss: 1.4939

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7137 - loss: 1.4491

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7208 - loss: 1.4071

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7200 - loss: 2.6341

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7123 - loss: 2.5753

 59/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7119 - loss: 2.5108

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7115 - loss: 2.4540

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7206 - loss: 2.3859

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7262 - loss: 2.3232

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7254 - loss: 2.2820

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7304 - loss: 2.2273

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7324 - loss: 2.1965

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7315 - loss: 2.1484

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7307 - loss: 2.5675

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7325 - loss: 2.5183

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7342 - loss: 2.4750

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7383 - loss: 2.4280

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7349 - loss: 2.4067

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7365 - loss: 2.3669

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7402 - loss: 2.3241

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7438 - loss: 2.2860

 91/210 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - acc: 0.7429 - loss: 4.0746

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7398 - loss: 4.5938

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7368 - loss: 5.3526

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7381 - loss: 5.2636

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7354 - loss: 5.1862

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7406 - loss: 5.0882

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7417 - loss: 5.0008

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7314 - loss: 4.9468

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7327 - loss: 4.8609

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7284 - loss: 5.5665

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7279 - loss: 5.4787

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7257 - loss: 5.4312

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7287 - loss: 5.3465

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7316 - loss: 5.2593

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7294 - loss: 5.1817

120/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7317 - loss: 5.1410

122/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7295 - loss: 5.2694

124/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7323 - loss: 5.1899

126/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7302 - loss: 5.1166

128/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7281 - loss: 5.0810

130/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7277 - loss: 5.0184

132/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7288 - loss: 4.9492

134/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7299 - loss: 5.2423

136/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7309 - loss: 5.2205

138/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7319 - loss: 5.1821

140/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7329 - loss: 5.1484

142/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7338 - loss: 5.0864

144/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7333 - loss: 5.0243

146/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7329 - loss: 5.3874

148/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7365 - loss: 5.3186

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7360 - loss: 5.2664

152/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7382 - loss: 5.2024

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7364 - loss: 6.3700

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7321 - loss: 6.3025

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7342 - loss: 6.2282

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7337 - loss: 6.1634

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7346 - loss: 6.0941

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7329 - loss: 6.0265

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7349 - loss: 5.9600

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7357 - loss: 5.9033

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7376 - loss: 5.8406

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7407 - loss: 5.7777

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7391 - loss: 5.7432

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7420 - loss: 5.6812

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7404 - loss: 6.0196

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7411 - loss: 5.9603

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7396 - loss: 5.9069

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7380 - loss: 6.0683

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7384 - loss: 6.0373

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7380 - loss: 6.1158

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7365 - loss: 6.2112

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7372 - loss: 6.1578

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7358 - loss: 6.2123

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7374 - loss: 6.2047

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7381 - loss: 6.2230

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7387 - loss: 6.1678

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7373 - loss: 7.1896

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7379 - loss: 8.7139

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7366 - loss: 8.6431

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7372 - loss: 8.8590

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7388 - loss: 8.7783

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.7380 - loss: 8.7712 - val_acc: 0.0229 - val_loss: 1.5603

Epoch 7/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - acc: 1.0000 - loss: 0.3240

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.6667 - loss: 2.1400

  5/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.7200 - loss: 1.5811

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7143 - loss: 1.3418

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7333 - loss: 1.2709

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.6909 - loss: 1.1852

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7077 - loss: 1.1016

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7467 - loss: 0.9878

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7294 - loss: 0.9634

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7474 - loss: 0.9317

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7619 - loss: 0.8855

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7652 - loss: 0.8808

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7680 - loss: 1.0216

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7704 - loss: 1.0068

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7655 - loss: 0.9800

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7742 - loss: 0.9583

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7758 - loss: 0.9349

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7771 - loss: 1.0047

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7676 - loss: 1.2125

 39/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7744 - loss: 1.1747

 41/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7756 - loss: 1.1461

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7721 - loss: 1.1962

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7778 - loss: 1.1949

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7830 - loss: 1.1624

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7837 - loss: 1.1342

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7804 - loss: 2.4422

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7660 - loss: 2.9464

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7745 - loss: 2.8514

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7754 - loss: 2.7685

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7729 - loss: 2.6961

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7803 - loss: 2.6204

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7778 - loss: 3.1148

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7785 - loss: 3.0386

 67/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7821 - loss: 2.9707

 69/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7884 - loss: 2.8962

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7915 - loss: 2.8259

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7890 - loss: 3.9801

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7893 - loss: 3.9587

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7870 - loss: 3.8709

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7924 - loss: 3.7785

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7926 - loss: 3.7334

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7880 - loss: 3.6592

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7835 - loss: 3.6071

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7816 - loss: 3.5756

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7775 - loss: 3.5172

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7736 - loss: 3.4514

 93/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7656 - loss: 3.5737

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7558 - loss: 3.5182

 97/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7485 - loss: 3.4743

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7394 - loss: 3.4741

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7307 - loss: 5.6354

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7262 - loss: 5.5469

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7162 - loss: 5.4730

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7140 - loss: 5.4088

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7046 - loss: 5.4983

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6955 - loss: 5.4333

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6973 - loss: 5.3453

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6991 - loss: 5.3159

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6974 - loss: 5.2393

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6924 - loss: 5.1630

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6909 - loss: 5.1200

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6894 - loss: 5.0555

125/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.6896 - loss: 4.9826

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6898 - loss: 4.9156

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6884 - loss: 4.8500

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6901 - loss: 4.8958

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6887 - loss: 4.8487

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6904 - loss: 4.7858

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6920 - loss: 4.7230

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6950 - loss: 5.6710

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.6993 - loss: 5.5923

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7021 - loss: 5.5191

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7034 - loss: 5.4493

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7075 - loss: 5.3768

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7074 - loss: 5.3157

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7073 - loss: 5.2526

153/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7072 - loss: 5.2315

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7097 - loss: 5.1680

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7108 - loss: 5.1116

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7145 - loss: 5.0492

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7155 - loss: 5.0101

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7166 - loss: 4.9527

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7152 - loss: 5.0868

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7174 - loss: 5.1001

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7172 - loss: 5.0467

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7181 - loss: 4.9974

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7179 - loss: 4.9449

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7177 - loss: 4.9042

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7186 - loss: 4.9449

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7173 - loss: 5.9183

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7182 - loss: 5.8646

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7191 - loss: 5.8060

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7200 - loss: 5.7479

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7198 - loss: 5.7826

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7196 - loss: 5.7276

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7183 - loss: 5.7430

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7161 - loss: 5.7048

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7159 - loss: 5.6527

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7147 - loss: 5.6025

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7146 - loss: 5.5593

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7164 - loss: 5.5077

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7172 - loss: 5.4772

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7161 - loss: 5.4360

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7169 - loss: 5.3898

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7177 - loss: 5.3419

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.7180 - loss: 5.3368 - val_acc: 0.0229 - val_loss: 1.0616

Epoch 8/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - acc: 0.8000 - loss: 0.4227

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.8000 - loss: 0.7375

  5/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.8000 - loss: 0.6217

  7/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.7429 - loss: 0.8011

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.7778 - loss: 0.7461

 11/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.7273 - loss: 0.7260

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7231 - loss: 0.7151

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7467 - loss: 0.6596

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7529 - loss: 0.6713

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7579 - loss: 0.6688

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7619 - loss: 0.6573

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7304 - loss: 1.0785

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7200 - loss: 1.2389

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7333 - loss: 1.1781

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7310 - loss: 1.1407

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7290 - loss: 1.1030

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7333 - loss: 1.0662

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7143 - loss: 1.0571

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7189 - loss: 1.0430

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7333 - loss: 1.0094

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7366 - loss: 0.9847

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7442 - loss: 0.9614

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7378 - loss: 0.9823

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7447 - loss: 0.9600

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7510 - loss: 0.9393

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7490 - loss: 0.9282

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7547 - loss: 0.9176

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7600 - loss: 0.9228

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7649 - loss: 0.9081

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7695 - loss: 0.8901

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7672 - loss: 1.4411

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7619 - loss: 1.4247

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7600 - loss: 2.0391

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7612 - loss: 2.2478

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7594 - loss: 2.2271

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7662 - loss: 2.1746

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7699 - loss: 2.1291

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7707 - loss: 4.0105

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7740 - loss: 3.9340

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7772 - loss: 3.8411

 80/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7800 - loss: 3.7941

 82/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7805 - loss: 3.7117

 84/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7810 - loss: 3.6523

 86/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7837 - loss: 3.5753

 88/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7864 - loss: 3.5254

 90/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7867 - loss: 3.4693

 92/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7913 - loss: 3.3988

 94/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7936 - loss: 3.3351

 96/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7958 - loss: 3.2872

 98/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7980 - loss: 3.2267

100/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7960 - loss: 3.1783

102/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7941 - loss: 3.1347

104/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7942 - loss: 3.0870

106/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7962 - loss: 3.0424

108/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7944 - loss: 2.9989

110/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7945 - loss: 2.9554

112/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7946 - loss: 2.9119

114/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7930 - loss: 2.8702

116/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7948 - loss: 2.8281

118/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7932 - loss: 2.8030

120/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7950 - loss: 2.7637

122/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7984 - loss: 2.7232

124/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8000 - loss: 2.7041

126/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8016 - loss: 2.6687

128/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8031 - loss: 2.6335

130/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8046 - loss: 2.5995

132/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8061 - loss: 2.5670

134/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8045 - loss: 2.5377

136/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8044 - loss: 2.5188

138/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8029 - loss: 2.5012

140/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.8000 - loss: 2.4929

142/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7986 - loss: 2.5718

144/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7972 - loss: 2.5448

146/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7959 - loss: 2.5374

148/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7959 - loss: 2.6199

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7947 - loss: 2.5979

152/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7947 - loss: 2.5800

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7935 - loss: 2.5534

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7936 - loss: 2.5265

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7924 - loss: 2.5030

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7925 - loss: 2.4773

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7951 - loss: 2.4500

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7951 - loss: 2.4326

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7964 - loss: 2.4083

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7952 - loss: 2.3881

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7929 - loss: 2.4289

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7919 - loss: 2.4081

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7920 - loss: 2.3862

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7920 - loss: 2.3645

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7899 - loss: 2.4525

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7867 - loss: 2.9092

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7857 - loss: 2.8833

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7848 - loss: 2.9889

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7839 - loss: 2.9630

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7830 - loss: 2.9547

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7821 - loss: 2.9541

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7812 - loss: 3.4327

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7814 - loss: 3.5006

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7816 - loss: 3.4748

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7788 - loss: 3.6983

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7750 - loss: 3.8288

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7733 - loss: 3.8218

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7745 - loss: 3.7885

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7748 - loss: 3.7589

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7721 - loss: 3.7417

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7706 - loss: 3.7590

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.7706 - loss: 3.7590 - val_acc: 0.0229 - val_loss: 0.9322

Epoch 9/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 59ms/step - acc: 0.8000 - loss: 0.6794

  3/210 ━━━━━━━━━━━━━━━━━━━━ 6s 31ms/step - acc: 0.8000 - loss: 11.6773

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8000 - loss: 7.2860

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7714 - loss: 6.3203

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.8222 - loss: 4.9765

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.8000 - loss: 10.1496

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7846 - loss: 8.6593

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7733 - loss: 7.5745

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7412 - loss: 7.7414

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7263 - loss: 8.7976

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7238 - loss: 8.1189

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.7130 - loss: 7.9672

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.7040 - loss: 7.3971

 27/210 ━━━━━━━━━━━━━━━━━━━━ 5s 32ms/step - acc: 0.7185 - loss: 6.8736

 29/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7172 - loss: 8.0056

 31/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7290 - loss: 7.5129

 33/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7273 - loss: 7.4178

 35/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7143 - loss: 7.9512

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7243 - loss: 7.7895

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7231 - loss: 9.4291

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7171 - loss: 9.1765

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7070 - loss: 8.8326

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7111 - loss: 8.6552

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7191 - loss: 8.3017

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7224 - loss: 8.0022

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - acc: 0.7137 - loss: 7.8357

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7170 - loss: 7.6887

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7164 - loss: 7.4418

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7158 - loss: 7.3388

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7119 - loss: 8.2484

 61/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7180 - loss: 8.0399

 63/210 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step - acc: 0.7238 - loss: 7.7989

 65/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7231 - loss: 7.6073

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7284 - loss: 7.3937

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7304 - loss: 7.1923

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7324 - loss: 7.4018

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7370 - loss: 7.2068

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7413 - loss: 7.0229

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7481 - loss: 6.8452

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7443 - loss: 6.7167

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7481 - loss: 6.5687

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7470 - loss: 6.4235

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7459 - loss: 6.3378

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7494 - loss: 6.2022

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7551 - loss: 6.0664

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 34ms/step - acc: 0.7582 - loss: 5.9704

 93/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7591 - loss: 8.8442

 95/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7600 - loss: 8.6765

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7608 - loss: 8.5071

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7616 - loss: 8.3431

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7584 - loss: 8.2068

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7534 - loss: 8.1581

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7467 - loss: 8.0295

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7495 - loss: 7.8873

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7486 - loss: 7.7551

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7477 - loss: 7.6491

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7434 - loss: 7.5469

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7426 - loss: 7.4360

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7436 - loss: 7.3179

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7429 - loss: 7.2393

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - acc: 0.7438 - loss: 7.1717

123/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7463 - loss: 7.1675

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7456 - loss: 7.0624

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7417 - loss: 7.0424

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7380 - loss: 6.9918

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7405 - loss: 6.9610

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7429 - loss: 6.8750

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7422 - loss: 11.4549

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7431 - loss: 11.3000

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7453 - loss: 11.1437

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7461 - loss: 11.0348

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7441 - loss: 10.8903

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7421 - loss: 10.7637

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7415 - loss: 10.6256

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7396 - loss: 10.4928

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - acc: 0.7400 - loss: 10.4257

152/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7408 - loss: 10.2969

154/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7403 - loss: 10.1755

156/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7372 - loss: 10.1401

158/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7405 - loss: 10.0151

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7412 - loss: 9.8962

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7407 - loss: 10.5768

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7439 - loss: 10.4506

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7422 - loss: 10.3321

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7405 - loss: 10.7565

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7412 - loss: 10.6891

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7430 - loss: 10.5857

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7448 - loss: 10.4822

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7443 - loss: 10.4078

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7438 - loss: 10.2973

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - acc: 0.7444 - loss: 10.1882

182/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7462 - loss: 10.0810

184/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7446 - loss: 10.0026

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7419 - loss: 10.7592

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7394 - loss: 10.6523

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7400 - loss: 10.5517

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7417 - loss: 10.4490

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7381 - loss: 10.3746

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7388 - loss: 10.2741

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7323 - loss: 10.3063

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7280 - loss: 11.0339

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7287 - loss: 10.9299

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7284 - loss: 10.8279

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7262 - loss: 12.3251

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7269 - loss: 12.2103

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - acc: 0.7266 - loss: 12.1432

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 37ms/step - acc: 0.7266 - loss: 12.1432 - val_acc: 0.0229 - val_loss: 1.0922

Epoch 10/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - acc: 0.8000 - loss: 0.5149

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.8000 - loss: 1.1281

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8400 - loss: 0.7962

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8286 - loss: 0.6967

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.8667 - loss: 0.5929

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.8909 - loss: 0.5295

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.8308 - loss: 0.6647

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8267 - loss: 6.1602

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.8353 - loss: 5.4798

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8105 - loss: 5.7561

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7810 - loss: 5.3508

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.8000 - loss: 4.9022

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7840 - loss: 4.5676

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7778 - loss: 4.3681

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7793 - loss: 4.3300

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7806 - loss: 4.0786

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7818 - loss: 3.8599

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7771 - loss: 3.6742

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7838 - loss: 3.5064

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7795 - loss: 3.3676

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7805 - loss: 3.4760

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7860 - loss: 3.3308

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7911 - loss: 3.2000

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7915 - loss: 3.0848

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7796 - loss: 2.9892

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7843 - loss: 2.8923

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7774 - loss: 2.8234

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7745 - loss: 2.7383

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7754 - loss: 2.6594

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7763 - loss: 3.2416

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7770 - loss: 3.2356

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7778 - loss: 3.4904

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7785 - loss: 3.3972

 67/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7821 - loss: 3.3071

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7884 - loss: 3.2200

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7887 - loss: 3.4923

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7918 - loss: 3.4090

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7893 - loss: 3.4005

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7870 - loss: 3.3373

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7873 - loss: 3.2800

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7827 - loss: 3.5541

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7855 - loss: 3.4782

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7835 - loss: 3.4354

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7816 - loss: 3.3695

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - acc: 0.7798 - loss: 3.4943

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7802 - loss: 3.4263

 93/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7785 - loss: 3.3634

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7789 - loss: 3.3005

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7794 - loss: 3.2427

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7798 - loss: 3.1893

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7762 - loss: 3.1413

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7748 - loss: 3.0913

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7695 - loss: 3.0761

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7682 - loss: 3.0620

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7670 - loss: 3.0221

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7676 - loss: 2.9762

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7646 - loss: 3.0112

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7617 - loss: 2.9737

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7624 - loss: 2.9320

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7613 - loss: 2.8926

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7636 - loss: 2.8511

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7626 - loss: 2.8152

125/210 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - acc: 0.7664 - loss: 2.7755

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7638 - loss: 2.8840

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7643 - loss: 2.8742

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7664 - loss: 2.8358

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7684 - loss: 2.8069

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7689 - loss: 2.7775

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7693 - loss: 2.7444

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7712 - loss: 2.7111

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7716 - loss: 2.6781

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7720 - loss: 2.6853

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7697 - loss: 2.6661

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7714 - loss: 2.7543

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7718 - loss: 2.7225

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7722 - loss: 2.6932

153/210 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - acc: 0.7725 - loss: 2.6680

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7703 - loss: 2.6613

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7720 - loss: 2.6328

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7698 - loss: 2.6468

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7702 - loss: 2.6234

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7669 - loss: 2.6076

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7661 - loss: 2.5836

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7653 - loss: 2.5605

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7657 - loss: 2.5362

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7661 - loss: 3.5887

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7688 - loss: 3.5515

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7680 - loss: 3.5199

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7706 - loss: 3.4839

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7698 - loss: 3.4818

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - acc: 0.7724 - loss: 3.4474

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7705 - loss: 3.4405

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7730 - loss: 3.4069

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7743 - loss: 3.3797

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7704 - loss: 3.3741

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7686 - loss: 3.3703

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7658 - loss: 3.3584

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7651 - loss: 3.3285

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7635 - loss: 3.3021

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7648 - loss: 3.2727

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7672 - loss: 3.2428

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7675 - loss: 3.2188

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7659 - loss: 3.2601

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7662 - loss: 3.2335

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7646 - loss: 3.2090

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.7648 - loss: 3.2063 - val_acc: 0.0229 - val_loss: 1.1232

Epoch 11/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - acc: 0.6000 - loss: 0.6870

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 39ms/step - acc: 0.7333 - loss: 0.5163

  5/210 ━━━━━━━━━━━━━━━━━━━━ 8s 40ms/step - acc: 0.7200 - loss: 0.5404

  7/210 ━━━━━━━━━━━━━━━━━━━━ 7s 38ms/step - acc: 0.7714 - loss: 0.5307

  9/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.7778 - loss: 0.5224

 11/210 ━━━━━━━━━━━━━━━━━━━━ 7s 36ms/step - acc: 0.7818 - loss: 0.5168

 13/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.8154 - loss: 0.4813

 15/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.7867 - loss: 0.5109

 17/210 ━━━━━━━━━━━━━━━━━━━━ 7s 37ms/step - acc: 0.7882 - loss: 0.5114

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8000 - loss: 0.4948

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8000 - loss: 0.5573

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8000 - loss: 0.5660

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.8080 - loss: 0.5540

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.8000 - loss: 0.9200

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7931 - loss: 0.8945

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7806 - loss: 0.8893

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7758 - loss: 0.8730

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7771 - loss: 0.8502

 37/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7838 - loss: 0.8253

 39/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7795 - loss: 1.1949

 41/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7854 - loss: 1.1548

 43/210 ━━━━━━━━━━━━━━━━━━━━ 6s 36ms/step - acc: 0.7814 - loss: 1.1862

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7822 - loss: 1.2498

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7830 - loss: 1.2165

 48/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7875 - loss: 1.1987

 50/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7880 - loss: 1.1686

 52/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7923 - loss: 1.1385

 54/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7926 - loss: 1.1119

 56/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7821 - loss: 1.0986

 58/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7862 - loss: 1.0702

 60/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7933 - loss: 1.0436

 62/210 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - acc: 0.7935 - loss: 1.2565

 64/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7906 - loss: 1.2766

 66/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7939 - loss: 1.2498

 67/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7881 - loss: 1.2607

 69/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7884 - loss: 1.2470

 70/210 ━━━━━━━━━━━━━━━━━━━━ 5s 37ms/step - acc: 0.7857 - loss: 1.2388

 71/210 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - acc: 0.7859 - loss: 1.2273

 73/210 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - acc: 0.7918 - loss: 1.2017

 75/210 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - acc: 0.7920 - loss: 1.1826

 77/210 ━━━━━━━━━━━━━━━━━━━━ 5s 38ms/step - acc: 0.7844 - loss: 1.2047

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7848 - loss: 1.1868

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7877 - loss: 1.1687

 82/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7878 - loss: 1.1748

 84/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7905 - loss: 1.8275

 86/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7860 - loss: 1.8175

 88/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7864 - loss: 1.7907

 90/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7889 - loss: 1.7601

 92/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7870 - loss: 1.7350

 94/210 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - acc: 0.7830 - loss: 1.7105

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7832 - loss: 1.7727

 97/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7773 - loss: 1.7558

 99/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7737 - loss: 1.7370

101/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7683 - loss: 1.7881

103/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7689 - loss: 1.7666

105/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7695 - loss: 1.7410

107/210 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - acc: 0.7645 - loss: 2.5776

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7670 - loss: 2.5390

110/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7673 - loss: 2.5230

112/210 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - acc: 0.7679 - loss: 2.5092

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7664 - loss: 2.5193

114/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7667 - loss: 2.5158

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7652 - loss: 2.5030

116/210 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - acc: 0.7621 - loss: 2.6779

118/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7627 - loss: 2.6431

120/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7650 - loss: 2.6170

122/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7639 - loss: 2.5913

124/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7661 - loss: 2.5641

126/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7603 - loss: 2.5820

128/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7594 - loss: 2.5550

130/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7615 - loss: 2.5212

132/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7621 - loss: 2.4915

134/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7642 - loss: 2.4593

135/210 ━━━━━━━━━━━━━━━━━━━━ 3s 40ms/step - acc: 0.7644 - loss: 2.4458

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7620 - loss: 2.4339

138/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7609 - loss: 2.4247

140/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7614 - loss: 2.3961

142/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7592 - loss: 2.4172

144/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7597 - loss: 2.3912

146/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7616 - loss: 2.3670

148/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7635 - loss: 2.3412

150/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7653 - loss: 2.3158

152/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7645 - loss: 2.2961

154/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7662 - loss: 2.2733

156/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7667 - loss: 2.2513

158/210 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - acc: 0.7671 - loss: 2.2479

160/210 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7663 - loss: 2.2966

162/210 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7679 - loss: 2.2733

164/210 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7671 - loss: 2.2660

166/210 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - acc: 0.7699 - loss: 2.2425

168/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7679 - loss: 2.2260

170/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7671 - loss: 2.2083

172/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7674 - loss: 2.1949

174/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7667 - loss: 2.1791

176/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7682 - loss: 2.1587

178/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7663 - loss: 2.1430

180/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7667 - loss: 2.1291

182/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7670 - loss: 2.1237

184/210 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - acc: 0.7663 - loss: 2.1071

186/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7645 - loss: 2.0909

188/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7660 - loss: 2.0730

190/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7632 - loss: 2.0595

192/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7635 - loss: 2.0435

194/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7619 - loss: 2.0321

196/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7612 - loss: 2.0168

198/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7626 - loss: 2.0012

200/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7640 - loss: 1.9847

202/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7663 - loss: 1.9677

204/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7657 - loss: 1.9741

206/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7680 - loss: 1.9567

208/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7673 - loss: 1.9482

210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7677 - loss: 1.9395

210/210 ━━━━━━━━━━━━━━━━━━━━ 9s 41ms/step - acc: 0.7677 - loss: 1.9395 - val_acc: 0.0229 - val_loss: 1.2103

Epoch 12/500

  1/210 ━━━━━━━━━━━━━━━━━━━━ 12s 61ms/step - acc: 1.0000 - loss: 0.2074

  3/210 ━━━━━━━━━━━━━━━━━━━━ 7s 35ms/step - acc: 0.8667 - loss: 0.4174

  5/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.8800 - loss: 0.3634

  7/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.9143 - loss: 0.3171

  9/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.8667 - loss: 1.0306

 11/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8909 - loss: 0.8996

 13/210 ━━━━━━━━━━━━━━━━━━━━ 6s 32ms/step - acc: 0.8769 - loss: 0.8952

 15/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8667 - loss: 0.8315

 17/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8588 - loss: 0.8291

 19/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8421 - loss: 0.8034

 21/210 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - acc: 0.8381 - loss: 0.7953

 23/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.8174 - loss: 0.8052

 25/210 ━━━━━━━━━━━━━━━━━━━━ 6s 34ms/step - acc: 0.7920 - loss: 0.8488

 27/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7852 - loss: 0.8492

 29/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7724 - loss: 3.1704

 31/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7742 - loss: 3.1720

 33/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7697 - loss: 3.0148

 35/210 ━━━━━━━━━━━━━━━━━━━━ 6s 35ms/step - acc: 0.7714 - loss: 2.8698

 37/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7676 - loss: 2.7635

 39/210 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - acc: 0.7795 - loss: 2.6376

 41/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7805 - loss: 2.5406

 43/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7767 - loss: 2.4649

 45/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7867 - loss: 2.3661

 47/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7830 - loss: 2.2889

 49/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7837 - loss: 2.2202

 51/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7765 - loss: 2.3723

 53/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7698 - loss: 2.3475

 55/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7709 - loss: 2.2789

 57/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7719 - loss: 2.2152

 59/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7695 - loss: 2.1602

 61/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7738 - loss: 2.1011

 63/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7746 - loss: 2.0501

 65/210 ━━━━━━━━━━━━━━━━━━━━ 5s 35ms/step - acc: 0.7692 - loss: 2.0288

 67/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7642 - loss: 1.9985

 69/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7594 - loss: 3.9579

 71/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7606 - loss: 3.9679

 73/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7562 - loss: 3.8786

 75/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7600 - loss: 3.7865

 77/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7636 - loss: 4.3257

 79/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7595 - loss: 4.2503

 81/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7630 - loss: 4.1542

 83/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7639 - loss: 4.0808

 85/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7647 - loss: 4.0092

 87/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7701 - loss: 3.9229

 89/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7708 - loss: 3.8463

 91/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7714 - loss: 3.7911

 93/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7720 - loss: 3.7178

 95/210 ━━━━━━━━━━━━━━━━━━━━ 4s 35ms/step - acc: 0.7726 - loss: 3.6482

 97/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7711 - loss: 3.5851

 99/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7697 - loss: 3.5341

101/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7723 - loss: 3.4735

103/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7650 - loss: 3.4219

105/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7619 - loss: 3.3732

107/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7626 - loss: 3.3205

109/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7615 - loss: 3.2714

111/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7640 - loss: 3.2206

113/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7646 - loss: 3.1721

115/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7652 - loss: 3.1707

117/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7675 - loss: 3.1237

119/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7647 - loss: 3.0888

121/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7653 - loss: 3.0457

123/210 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - acc: 0.7659 - loss: 3.0039

125/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7616 - loss: 2.9692

127/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7606 - loss: 3.5965

129/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7550 - loss: 3.7107

131/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7542 - loss: 3.6637

133/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7564 - loss: 3.6159

135/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7541 - loss: 3.5710

137/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7533 - loss: 3.5274

139/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7525 - loss: 3.4882

141/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7518 - loss: 3.4570

143/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7497 - loss: 3.4182

145/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7503 - loss: 3.4535

147/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7497 - loss: 3.4181

149/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7503 - loss: 3.6972

151/210 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - acc: 0.7483 - loss: 3.6590

153/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7477 - loss: 3.6214

155/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7510 - loss: 3.5783

157/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7516 - loss: 3.5426

159/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7509 - loss: 3.5061

161/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7503 - loss: 3.4698

163/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7521 - loss: 3.4328

165/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7515 - loss: 3.3979

167/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7485 - loss: 3.3998

169/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7503 - loss: 3.3716

171/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7474 - loss: 3.3812

173/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7491 - loss: 3.3455

175/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7486 - loss: 3.3433

177/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7503 - loss: 3.3101

179/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7497 - loss: 3.2817

181/210 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - acc: 0.7525 - loss: 3.2490

183/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7541 - loss: 3.2174

185/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7524 - loss: 3.2007

187/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7529 - loss: 3.1715

189/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7545 - loss: 3.1421

191/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7529 - loss: 3.1160

193/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7534 - loss: 3.0888

195/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7508 - loss: 3.1298

197/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7523 - loss: 3.1022

199/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7518 - loss: 3.0796

201/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7522 - loss: 3.0591

203/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7517 - loss: 3.0353

205/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7522 - loss: 3.0103

207/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7517 - loss: 2.9913

209/210 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - acc: 0.7531 - loss: 2.9658

210/210 ━━━━━━━━━━━━━━━━━━━━ 8s 38ms/step - acc: 0.7533 - loss: 2.9633 - val_acc: 0.0229 - val_loss: 1.2162

Epoch 12: early stopping

Restoring model weights from the end of the best epoch: 2.

In [24]:
# put it all together for other models

# make a prediction
pred = model.predict(X_test)# the pred
print(pred) # round them!

pred = np.round(pred,0)
print(pred) # run all if you get an error...

# confusion matrix - put this at the top!
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, pred)) # looks pretty good!
print(classification_report(y_test, pred))

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Occupied')
plt.show()

 1/41 ━━━━━━━━━━━━━━━━━━━━ 54s 1s/step

 7/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

13/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

20/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

26/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

32/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

38/41 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

41/41 ━━━━━━━━━━━━━━━━━━━━ 3s 44ms/step

[[9.9961185e-01]
 [9.9976557e-01]
 [9.7674388e-04]
 ...
 [9.9900854e-01]
 [9.9918532e-01]
 [9.9936867e-01]]
[[1.]
 [1.]
 [0.]
 ...
 [1.]
 [1.]
 [1.]]
[[822  27]
 [355 104]]
              precision    recall  f1-score   support

         0.0       0.70      0.97      0.81       849
         1.0       0.79      0.23      0.35       459

    accuracy                           0.71      1308
   macro avg       0.75      0.60      0.58      1308
weighted avg       0.73      0.71      0.65      1308

C:\Users\dww05002\AppData\Local\Temp\ipykernel_36200\1192869489.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()