<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_Lags.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 1 — Sequences are different + the window method (lags)
- Shuffle California Housing and nothing changes; shuffle a temperature series and you destroyed it - order carries information.
- The window method DELIBERATELY destroys the order: the past n_steps values become n_steps columns, so any model can fit it.
- Chronological 90/10 split, NO shuffle - shuffling leaks the future into training.
- Dense net with early stopping; note the MAE (~1.86 in 2022 - quote the number on screen).
- The trap: a 45-degree scatter PLUS a time-series plot, because a model can look great just by repeating yesterday.
-->

# Univariate Temperature Example (Lags/Window Method)
--------------------------------------------------
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the temperature as a function of N previous days.

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_37448\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# univariate lags ('series_to_supervised')
# link: https://machinelearningmastery.com/convert-time-series-supervised-learning-problem-python/

from pandas import concat

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
	"""
	Frame a time series as a supervised learning dataset.
	Arguments:
		data: Sequence of observations as a list or NumPy array.
		n_in: Number of lag observations as input (X).
		n_out: Number of observations as output (y).
		dropnan: Boolean whether or not to drop rows with NaN values.
	Returns:
		Pandas DataFrame of series framed for supervised learning.
	"""
	n_vars = 1 if type(data) is list else data.shape[1]
	df = pd.DataFrame(data)
	cols, names = list(), list()
	# input sequence (t-n, ... t-1)
	for i in range(n_in, 0, -1):
		cols.append(df.shift(i))
		names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
	# forecast sequence (t, t+1, ... t+n)
	for i in range(0, n_out):
		cols.append(df.shift(-i))
		if i == 0:
			names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
		else:
			names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
	# put it all together
	agg = concat(cols, axis=1)
	agg.columns = names
	# drop rows with NaN values
	if dropnan:
		agg.dropna(inplace=True)
	return agg

In [5]:
# here's what the code does for a lag of 1
values = [x for x in range(10)]
values

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
data = series_to_supervised(values, # the univariate dataset
                            n_in=1, # this means how many previous lags do you want
                            n_out=1) # this means how many steps ahead do you want to forecast (1 means current timestep)
print(data)

   var1(t-1)  var1(t)
1        0.0        1
2        1.0        2
3        2.0        3
4        3.0        4
5        4.0        5
6        5.0        6
7        6.0        7
8        7.0        8
9        8.0        9

In [7]:
# here's what the code does for a lag of 3
values = [x for x in range(10)]
data = series_to_supervised(values, # the univariate dataset
                            n_in=3, # this means how many previous lags do you want
                            n_out=1) # this means how many steps ahead do you want to forecast (1 means current timestep)
print(data)

   var1(t-3)  var1(t-2)  var1(t-1)  var1(t)
3        0.0        1.0        2.0        3
4        1.0        2.0        3.0        4
5        2.0        3.0        4.0        5
6        3.0        4.0        5.0        6
7        4.0        5.0        6.0        7
8        5.0        6.0        7.0        8
9        6.0        7.0        8.0        9

In [8]:
tmp = df['Temp']
tmp = pd.DataFrame(tmp)
tmp.head()

   Temp
0  20.7
1  17.9
2  18.8
3  14.6
4  15.8

In [9]:
# now let's use is on our datasaet
# let's use 10 lags (assume data is on a regular temporal scale)
# make sure the input is a pandas dataframe!
tmp = series_to_supervised(tmp, # the univariate dataset
                            n_in=10, # this means how many previous lags do you want
                            n_out=1)
tmp.head()

,var1(t-10),var1(t-9),var1(t-8),var1(t-7),var1(t-6),var1(t-5),var1(t-4),var1(t-3),var1(t-2),var1(t-1),var1(t)
10,20.7,17.9,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2
11,17.9,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3
12,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7
13,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7,21.5
14,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7,21.5,25.0

In [10]:
# split data into X and Y
y = tmp['var1(t)']
X = tmp.drop(['var1(t)'], axis=1)
print(X.shape, y.shape)

(3640, 10) (3640,)

In [11]:
# now split into train and test partition
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# Dense Neural Network

In [12]:
# now let's build a model

# define model
model = Sequential()
model.add(Dense(30, input_shape=(X.shape[1],), activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=5,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=10,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 30)             │           330 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 361 (1.41 KB)

 Trainable params: 361 (1.41 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8:34 2s/step - loss: 108.5948 - mae: 9.7193

 16/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 70.3075 - mae: 7.5295

 33/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 44.2747 - mae: 5.4992

 53/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.5991 - mae: 4.3939

 71/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1352 - mae: 3.9365

 90/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9334 - mae: 3.6646

110/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.8155 - mae: 3.4934

130/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.0503 - mae: 3.3265

152/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.4419 - mae: 3.1752

172/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.3961 - mae: 3.0689

190/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.7612 - mae: 3.0073

213/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.1474 - mae: 2.9455

235/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.4337 - mae: 2.8631

257/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.9239 - mae: 2.8151

262/262 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 13.8496 - mae: 2.8030 - val_loss: 6.9515 - val_mae: 2.0590

Epoch 2/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 13s 53ms/step - loss: 9.8864 - mae: 2.5931

 24/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6448 - mae: 2.3136

 49/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8263 - mae: 2.1786

 73/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6470 - mae: 2.1440

 99/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5179 - mae: 2.1401

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4093 - mae: 2.1290

154/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4785 - mae: 2.1367

182/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3177 - mae: 2.1181

216/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3174 - mae: 2.1258

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3897 - mae: 2.1394

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3098 - mae: 2.1256 - val_loss: 6.0205 - val_mae: 1.9265

Epoch 3/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 8.8083 - mae: 2.6106

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.2758 - mae: 2.0707

 76/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.3692 - mae: 2.1440

117/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1915 - mae: 2.1273

150/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0824 - mae: 2.1073

191/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0212 - mae: 2.0872

234/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8689 - mae: 2.0653

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7114 - mae: 2.0394 - val_loss: 5.6455 - val_mae: 1.8625

Epoch 4/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 4.9013 - mae: 1.8809

 39/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5867 - mae: 2.0697

 78/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5457 - mae: 2.0385

118/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7045 - mae: 2.0478

161/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6631 - mae: 2.0345

202/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5537 - mae: 2.0173

240/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5321 - mae: 2.0105

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.4675 - mae: 1.9996 - val_loss: 5.8652 - val_mae: 1.9231

Epoch 5/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 10.6666 - mae: 2.2246

 39/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.9063 - mae: 1.8373

 77/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1063 - mae: 1.8942

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5445 - mae: 1.9909

151/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3549 - mae: 1.9588

187/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2456 - mae: 1.9491

224/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2442 - mae: 1.9610

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3655 - mae: 1.9877

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.3655 - mae: 1.9877 - val_loss: 5.6445 - val_mae: 1.8842

Epoch 6/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 3.3250 - mae: 1.3379

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2262 - mae: 1.9876

 63/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8086 - mae: 1.9028

 89/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1450 - mae: 1.9590

117/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3152 - mae: 1.9818

141/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4310 - mae: 2.0117

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3957 - mae: 2.0027

190/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2832 - mae: 1.9831

213/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2255 - mae: 1.9736

236/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2262 - mae: 1.9716

260/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2443 - mae: 1.9727

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2476 - mae: 1.9726 - val_loss: 5.5020 - val_mae: 1.8567

Epoch 7/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 18s 70ms/step - loss: 5.3650 - mae: 1.9260

 24/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2246 - mae: 2.0077

 46/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9656 - mae: 1.9556

 69/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2718 - mae: 1.9941

 93/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6280 - mae: 2.0529

116/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6922 - mae: 2.0365

140/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6105 - mae: 2.0305

160/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5229 - mae: 2.0172

183/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4187 - mae: 2.0036

202/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3810 - mae: 1.9966

222/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3816 - mae: 1.9939

241/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3943 - mae: 1.9950

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3120 - mae: 1.9799

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3120 - mae: 1.9799 - val_loss: 5.5575 - val_mae: 1.8620

Epoch 8/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 6.0048 - mae: 1.9572

 23/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2241 - mae: 1.9971

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5492 - mae: 2.0434

 64/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1821 - mae: 1.9907

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0611 - mae: 1.9555

107/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0928 - mae: 1.9637

128/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1540 - mae: 1.9757

147/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2078 - mae: 1.9794

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1704 - mae: 1.9736

189/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3289 - mae: 1.9898

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2820 - mae: 1.9866

224/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2966 - mae: 1.9806

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2669 - mae: 1.9738

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2711 - mae: 1.9773 - val_loss: 5.5029 - val_mae: 1.8565

Epoch 9/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 11s 45ms/step - loss: 3.2600 - mae: 1.4837

 26/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7814 - mae: 1.8651

 47/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2883 - mae: 1.9346

 73/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9222 - mae: 1.8944

 99/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8033 - mae: 1.8723

128/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8794 - mae: 1.8879

152/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8772 - mae: 1.8845

175/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9291 - mae: 1.9056

198/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9018 - mae: 1.9046

219/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0255 - mae: 1.9235

243/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1237 - mae: 1.9425

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1812 - mae: 1.9529 - val_loss: 5.4686 - val_mae: 1.8565

Epoch 10/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - loss: 4.6705 - mae: 1.9438

 24/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0573 - mae: 1.9668

 46/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3501 - mae: 2.0001

 68/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3466 - mae: 1.9708

 90/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0788 - mae: 1.9321

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2369 - mae: 1.9698

137/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4425 - mae: 2.0059

158/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2047 - mae: 1.9689

181/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1292 - mae: 1.9500

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1450 - mae: 1.9447

228/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2822 - mae: 1.9668

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2180 - mae: 1.9613

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1824 - mae: 1.9577 - val_loss: 5.4643 - val_mae: 1.8558

Epoch 11/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 13s 50ms/step - loss: 6.4584 - mae: 2.0784

 24/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6277 - mae: 2.0312

 47/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4717 - mae: 1.9870

 69/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2415 - mae: 1.9637

 91/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2185 - mae: 1.9723

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2267 - mae: 1.9781

135/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2990 - mae: 1.9744

157/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2919 - mae: 1.9711

179/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2147 - mae: 1.9657

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2634 - mae: 1.9721

223/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2811 - mae: 1.9720

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2751 - mae: 1.9696

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2297 - mae: 1.9635 - val_loss: 5.4674 - val_mae: 1.8549

Epoch 12/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 1:51 427ms/step - loss: 7.3331 - mae: 2.0903

 29/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8502 - mae: 2.0724

 55/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2747 - mae: 1.9598

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2183 - mae: 1.9613

104/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2171 - mae: 1.9673

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2161 - mae: 1.9523

153/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1013 - mae: 1.9316

177/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2864 - mae: 1.9638

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2579 - mae: 1.9637

225/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2182 - mae: 1.9574

247/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2240 - mae: 1.9612

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2254 - mae: 1.9599 - val_loss: 5.6152 - val_mae: 1.8860

Epoch 13/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - loss: 4.7052 - mae: 2.0311

 24/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6496 - mae: 2.0459

 47/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4995 - mae: 1.9944

 70/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1704 - mae: 1.9365

 91/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0341 - mae: 1.9081

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0860 - mae: 1.9275

136/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2562 - mae: 1.9487

157/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3503 - mae: 1.9746

181/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3343 - mae: 1.9714

204/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3440 - mae: 1.9748

228/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3216 - mae: 1.9784

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3029 - mae: 1.9726

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2744 - mae: 1.9698 - val_loss: 5.4754 - val_mae: 1.8587

Epoch 14/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 1:51 427ms/step - loss: 4.0188 - mae: 1.6984

 23/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7889 - mae: 1.9160

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7776 - mae: 1.9283

 67/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1373 - mae: 1.9781

 91/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2547 - mae: 1.9948

115/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2490 - mae: 1.9830

138/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3126 - mae: 1.9853

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2578 - mae: 1.9790

191/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1444 - mae: 1.9530

218/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1426 - mae: 1.9533

242/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0827 - mae: 1.9436

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1456 - mae: 1.9518 - val_loss: 5.7133 - val_mae: 1.9062

Epoch 15/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 13s 53ms/step - loss: 6.8460 - mae: 2.4838

 26/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4608 - mae: 2.0579

 50/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3551 - mae: 2.0282

 73/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1489 - mae: 1.9791

 95/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2898 - mae: 2.0020

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2891 - mae: 1.9848

144/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2307 - mae: 1.9788

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2590 - mae: 1.9799

193/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1968 - mae: 1.9626

218/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2121 - mae: 1.9569

241/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2100 - mae: 1.9600

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1840 - mae: 1.9567

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1840 - mae: 1.9567 - val_loss: 5.4665 - val_mae: 1.8561

Epoch 15: early stopping

Restoring model weights from the end of the best epoch: 10.

In [13]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 1s 117ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

MAE:  1.7729757492358869

C:\Users\dww05002\AppData\Local\Temp\ipykernel_37448\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_37448\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Of course, you could play around with more lags and even try polynomial features or other scaling to get this to work. Heck, once your data is prepped, you can even try TPOT to see if you can get a better architecture then what you are evaluating.