<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_Lags.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 1 — Sequences are different + the window method (lags)
- Shuffle California Housing and nothing changes; shuffle a temperature series and you destroyed it - order carries information.
- The window method DELIBERATELY destroys the order: the past n_steps values become n_steps columns, so any model can fit it.
- Chronological 90/10 split, NO shuffle - shuffling leaks the future into training.
- Dense net with early stopping; note the MAE (~1.86 in 2022 - quote the number on screen).
- The trap: a 45-degree scatter PLUS a time-series plot, because a model can look great just by repeating yesterday.
-->

# Univariate Temperature Example (Lags/Window Method)
--------------------------------------------------
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the temperature as a function of N previous days.

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_33136\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# univariate lags ('series_to_supervised')
# link: https://machinelearningmastery.com/convert-time-series-supervised-learning-problem-python/

from pandas import concat

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
	"""
	Frame a time series as a supervised learning dataset.
	Arguments:
		data: Sequence of observations as a list or NumPy array.
		n_in: Number of lag observations as input (X).
		n_out: Number of observations as output (y).
		dropnan: Boolean whether or not to drop rows with NaN values.
	Returns:
		Pandas DataFrame of series framed for supervised learning.
	"""
	n_vars = 1 if type(data) is list else data.shape[1]
	df = pd.DataFrame(data)
	cols, names = list(), list()
	# input sequence (t-n, ... t-1)
	for i in range(n_in, 0, -1):
		cols.append(df.shift(i))
		names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
	# forecast sequence (t, t+1, ... t+n)
	for i in range(0, n_out):
		cols.append(df.shift(-i))
		if i == 0:
			names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
		else:
			names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
	# put it all together
	agg = concat(cols, axis=1)
	agg.columns = names
	# drop rows with NaN values
	if dropnan:
		agg.dropna(inplace=True)
	return agg

In [5]:
# here's what the code does for a lag of 1
values = [x for x in range(10)]
values

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
data = series_to_supervised(values, # the univariate dataset
                            n_in=1, # this means how many previous lags do you want
                            n_out=1) # this means how many steps ahead do you want to forecast (1 means current timestep)
print(data)

   var1(t-1)  var1(t)
1        0.0        1
2        1.0        2
3        2.0        3
4        3.0        4
5        4.0        5
6        5.0        6
7        6.0        7
8        7.0        8
9        8.0        9

In [7]:
# here's what the code does for a lag of 3
values = [x for x in range(10)]
data = series_to_supervised(values, # the univariate dataset
                            n_in=3, # this means how many previous lags do you want
                            n_out=1) # this means how many steps ahead do you want to forecast (1 means current timestep)
print(data)

   var1(t-3)  var1(t-2)  var1(t-1)  var1(t)
3        0.0        1.0        2.0        3
4        1.0        2.0        3.0        4
5        2.0        3.0        4.0        5
6        3.0        4.0        5.0        6
7        4.0        5.0        6.0        7
8        5.0        6.0        7.0        8
9        6.0        7.0        8.0        9

In [8]:
tmp = df['Temp']
tmp = pd.DataFrame(tmp)
tmp.head()

   Temp
0  20.7
1  17.9
2  18.8
3  14.6
4  15.8

In [9]:
# now let's use is on our datasaet
# let's use 10 lags (assume data is on a regular temporal scale)
# make sure the input is a pandas dataframe!
tmp = series_to_supervised(tmp, # the univariate dataset
                            n_in=10, # this means how many previous lags do you want
                            n_out=1)
tmp.head()

,var1(t-10),var1(t-9),var1(t-8),var1(t-7),var1(t-6),var1(t-5),var1(t-4),var1(t-3),var1(t-2),var1(t-1),var1(t)
10,20.7,17.9,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2
11,17.9,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3
12,18.8,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7
13,14.6,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7,21.5
14,15.8,15.8,15.8,17.4,21.8,20.0,16.2,13.3,16.7,21.5,25.0

In [10]:
# split data into X and Y
y = tmp['var1(t)']
X = tmp.drop(['var1(t)'], axis=1)
print(X.shape, y.shape)

(3640, 10) (3640,)

In [11]:
# now split into train and test partition
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# Dense Neural Network

In [12]:
# now let's build a model

# define model
model = Sequential()
model.add(Dense(30, input_shape=(X.shape[1],), activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=5,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=10,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 30)             │           330 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 361 (1.41 KB)

 Trainable params: 361 (1.41 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 3:12 736ms/step - loss: 92.3731 - mae: 8.1877

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 19.7124 - mae: 3.5778

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.5251 - mae: 3.1370

126/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.4875 - mae: 2.9025

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 12.2621 - mae: 2.7522

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.5540 - mae: 2.6620

251/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.9237 - mae: 2.5862

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.8077 - mae: 2.5747 - val_loss: 7.0360 - val_mae: 2.1090

Epoch 2/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 22.2994 - mae: 4.0904

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.4789 - mae: 2.3614

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.8730 - mae: 2.2505

118/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.5453 - mae: 2.1892

158/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.3910 - mae: 2.1619

200/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.2215 - mae: 2.1279

238/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1163 - mae: 2.1072

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0568 - mae: 2.1030 - val_loss: 6.1359 - val_mae: 1.9794

Epoch 3/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 19.7539 - mae: 3.9038

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.7313 - mae: 2.2514

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1977 - mae: 2.1427

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0356 - mae: 2.1031

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8235 - mae: 2.0665

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7135 - mae: 2.0474

254/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5914 - mae: 2.0278

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.6038 - mae: 2.0310 - val_loss: 5.8443 - val_mae: 1.9301

Epoch 4/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - loss: 18.1383 - mae: 3.7542

 34/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4325 - mae: 2.1842

 70/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1670 - mae: 2.1370

110/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9743 - mae: 2.0948

149/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6563 - mae: 2.0413

189/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6263 - mae: 2.0364

227/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5688 - mae: 2.0185

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.4451 - mae: 2.0030 - val_loss: 5.7393 - val_mae: 1.9119

Epoch 5/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 17.1715 - mae: 3.6631

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.3396 - mae: 2.1692

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9246 - mae: 2.1032

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8150 - mae: 2.0636

158/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6367 - mae: 2.0372

199/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5033 - mae: 2.0132

239/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4209 - mae: 1.9936

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.3707 - mae: 1.9891 - val_loss: 5.6811 - val_mae: 1.9009

Epoch 6/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 16.4596 - mae: 3.6027

 46/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1705 - mae: 2.1649

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8053 - mae: 2.0751

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7859 - mae: 2.0591

165/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5677 - mae: 2.0207

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4465 - mae: 2.0043

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3619 - mae: 1.9837

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3296 - mae: 1.9805 - val_loss: 5.6576 - val_mae: 1.8953

Epoch 7/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 15.9908 - mae: 3.5627

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1856 - mae: 2.1685

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8460 - mae: 2.0866

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6734 - mae: 2.0405

171/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5042 - mae: 2.0125

212/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4069 - mae: 1.9940

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2867 - mae: 1.9715

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3028 - mae: 1.9750 - val_loss: 5.6342 - val_mae: 1.8898

Epoch 8/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - loss: 15.6321 - mae: 3.5311

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0692 - mae: 2.1436

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7973 - mae: 2.0751

130/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6063 - mae: 2.0265

172/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4868 - mae: 2.0097

212/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3900 - mae: 1.9904

254/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2740 - mae: 1.9683

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2857 - mae: 1.9711 - val_loss: 5.6179 - val_mae: 1.8858

Epoch 9/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 15.4162 - mae: 3.5122

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1765 - mae: 2.1589

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7811 - mae: 2.0722

129/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5869 - mae: 2.0220

171/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4738 - mae: 2.0064

214/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3579 - mae: 1.9836

256/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2654 - mae: 1.9657

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2748 - mae: 1.9685 - val_loss: 5.6067 - val_mae: 1.8840

Epoch 10/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - loss: 15.2508 - mae: 3.4935

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0562 - mae: 2.1421

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7684 - mae: 2.0696

126/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6553 - mae: 2.0369

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4717 - mae: 2.0030

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3738 - mae: 1.9862

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2711 - mae: 1.9659

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2643 - mae: 1.9660 - val_loss: 5.6044 - val_mae: 1.8820

Epoch 11/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 15.1506 - mae: 3.4847

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1472 - mae: 2.1512

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8116 - mae: 2.0760

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6776 - mae: 2.0389

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4753 - mae: 2.0034

204/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3761 - mae: 1.9889

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3054 - mae: 1.9706

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2571 - mae: 1.9644 - val_loss: 5.6023 - val_mae: 1.8811

Epoch 12/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 14.9849 - mae: 3.4635

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0282 - mae: 2.1353

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6945 - mae: 2.0535

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5948 - mae: 2.0248

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4764 - mae: 2.0018

209/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3892 - mae: 1.9877

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2586 - mae: 1.9624

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2509 - mae: 1.9626 - val_loss: 5.5974 - val_mae: 1.8797

Epoch 13/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 14.8494 - mae: 3.4459

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0009 - mae: 2.1267

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7545 - mae: 2.0672

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6613 - mae: 2.0347

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4633 - mae: 2.0000

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3341 - mae: 1.9811

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2540 - mae: 1.9612

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2460 - mae: 1.9614 - val_loss: 5.5899 - val_mae: 1.8786

Epoch 14/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 14.7208 - mae: 3.4292

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1014 - mae: 2.1410

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7796 - mae: 2.0675

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6527 - mae: 2.0328

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4568 - mae: 1.9984

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3645 - mae: 1.9835

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2482 - mae: 1.9599

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2397 - mae: 1.9600 - val_loss: 5.5892 - val_mae: 1.8776

Epoch 15/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 14.6194 - mae: 3.4173

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9978 - mae: 2.1286

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7176 - mae: 2.0576

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5725 - mae: 2.0200

170/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4434 - mae: 1.9982

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3467 - mae: 1.9793

254/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2273 - mae: 1.9565

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2365 - mae: 1.9591 - val_loss: 5.5870 - val_mae: 1.8770

Epoch 16/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 14.5048 - mae: 3.3998

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0600 - mae: 2.1109

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7113 - mae: 2.0602

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5988 - mae: 2.0210

160/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5032 - mae: 2.0059

202/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3617 - mae: 1.9823

241/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2614 - mae: 1.9598

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.2294 - mae: 1.9575 - val_loss: 5.5831 - val_mae: 1.8764

Epoch 17/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 14.4265 - mae: 3.3850

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0540 - mae: 2.1367

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7262 - mae: 2.0603

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6329 - mae: 2.0286

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4293 - mae: 1.9926

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3593 - mae: 1.9812

251/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2251 - mae: 1.9550

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2262 - mae: 1.9567 - val_loss: 5.5783 - val_mae: 1.8758

Epoch 18/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 14.3663 - mae: 3.3729

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0719 - mae: 2.1341

 84/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6978 - mae: 2.0559

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5506 - mae: 2.0156

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4436 - mae: 1.9941

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3533 - mae: 1.9796

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2082 - mae: 1.9520

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2200 - mae: 1.9551 - val_loss: 5.5745 - val_mae: 1.8741

Epoch 19/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 14.3012 - mae: 3.3636

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0479 - mae: 2.1352

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7227 - mae: 2.0597

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6262 - mae: 2.0276

165/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4474 - mae: 1.9945

206/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3136 - mae: 1.9762

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2521 - mae: 1.9582

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.2195 - mae: 1.9553 - val_loss: 5.5761 - val_mae: 1.8744

Epoch 20/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - loss: 14.2892 - mae: 3.3595

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0598 - mae: 2.1310

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7180 - mae: 2.0570

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5977 - mae: 2.0227

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4157 - mae: 1.9890

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3358 - mae: 1.9762

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2222 - mae: 1.9531

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2122 - mae: 1.9533 - val_loss: 5.5618 - val_mae: 1.8715

Epoch 21/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 14.1535 - mae: 3.3329

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9394 - mae: 2.1125

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6363 - mae: 2.0400

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5909 - mae: 2.0216

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4082 - mae: 1.9875

212/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3084 - mae: 1.9713

251/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2057 - mae: 1.9505

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2054 - mae: 1.9521 - val_loss: 5.5581 - val_mae: 1.8706

Epoch 22/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 14.2326 - mae: 3.3467

 39/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0954 - mae: 2.1277

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6842 - mae: 2.0533

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5679 - mae: 2.0143

161/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4872 - mae: 1.9998

203/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3225 - mae: 1.9745

242/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2320 - mae: 1.9534

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.2056 - mae: 1.9517 - val_loss: 5.5543 - val_mae: 1.8702

Epoch 23/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 14.2112 - mae: 3.3367

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0606 - mae: 2.1288

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7396 - mae: 2.0577

122/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5423 - mae: 2.0122

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4399 - mae: 1.9915

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3116 - mae: 1.9749

248/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2274 - mae: 1.9534

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2006 - mae: 1.9517 - val_loss: 5.5491 - val_mae: 1.8686

Epoch 24/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 14.1147 - mae: 3.3188

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9404 - mae: 2.1155

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6721 - mae: 2.0457

130/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4746 - mae: 1.9991

172/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3892 - mae: 1.9870

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3032 - mae: 1.9690

251/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1950 - mae: 1.9482

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1945 - mae: 1.9499 - val_loss: 5.5485 - val_mae: 1.8682

Epoch 25/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 14.0954 - mae: 3.3110

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.0373 - mae: 2.1246

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6908 - mae: 2.0496

121/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5172 - mae: 2.0046

161/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4658 - mae: 1.9960

200/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3062 - mae: 1.9711

239/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2409 - mae: 1.9533

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1894 - mae: 1.9486 - val_loss: 5.5405 - val_mae: 1.8672

Epoch 26/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 14.0080 - mae: 3.2947

 45/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8733 - mae: 2.1062

 90/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5741 - mae: 2.0247

133/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4062 - mae: 1.9880

176/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3777 - mae: 1.9865

217/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2733 - mae: 1.9636

260/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1829 - mae: 1.9462

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1884 - mae: 1.9485 - val_loss: 5.5411 - val_mae: 1.8662

Epoch 27/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.9215 - mae: 3.2699

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9021 - mae: 2.1059

 84/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6504 - mae: 2.0447

123/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5245 - mae: 2.0088

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3910 - mae: 1.9835

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3130 - mae: 1.9710

253/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1866 - mae: 1.9458

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1838 - mae: 1.9478 - val_loss: 5.5422 - val_mae: 1.8666

Epoch 28/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 13.9682 - mae: 3.2859

 36/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9390 - mae: 2.0881

 77/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7444 - mae: 2.0622

117/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4541 - mae: 1.9976

156/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3815 - mae: 1.9840

198/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3194 - mae: 1.9733

232/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2720 - mae: 1.9567

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1794 - mae: 1.9467 - val_loss: 5.5376 - val_mae: 1.8676

Epoch 29/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.9361 - mae: 3.2755

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9793 - mae: 2.1227

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6660 - mae: 2.0465

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5684 - mae: 2.0158

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4042 - mae: 1.9841

204/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2812 - mae: 1.9676

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2074 - mae: 1.9480

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1744 - mae: 1.9455 - val_loss: 5.5306 - val_mae: 1.8646

Epoch 30/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 27ms/step - loss: 13.8663 - mae: 3.2611

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9740 - mae: 2.1211

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6601 - mae: 2.0447

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5446 - mae: 2.0122

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3622 - mae: 1.9778

206/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2551 - mae: 1.9639

247/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1878 - mae: 1.9449

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1705 - mae: 1.9448 - val_loss: 5.5318 - val_mae: 1.8663

Epoch 31/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.8574 - mae: 3.2539

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9905 - mae: 2.1208

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6993 - mae: 2.0487

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5190 - mae: 2.0055

158/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3897 - mae: 1.9858

193/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2824 - mae: 1.9669

231/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2525 - mae: 1.9525

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1693 - mae: 1.9444 - val_loss: 5.5323 - val_mae: 1.8665

Epoch 32/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 13.8919 - mae: 3.2504

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9928 - mae: 2.1190

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6602 - mae: 2.0440

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5343 - mae: 2.0109

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3516 - mae: 1.9764

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2818 - mae: 1.9655

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1753 - mae: 1.9433

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1647 - mae: 1.9437 - val_loss: 5.5258 - val_mae: 1.8640

Epoch 33/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.7196 - mae: 3.2065

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9716 - mae: 2.1167

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6303 - mae: 2.0439

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5086 - mae: 2.0034

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3851 - mae: 1.9802

206/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2423 - mae: 1.9613

248/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1878 - mae: 1.9441

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1609 - mae: 1.9426 - val_loss: 5.5209 - val_mae: 1.8627

Epoch 34/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.7470 - mae: 3.2101

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9470 - mae: 2.1167

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5759 - mae: 2.0257

128/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4476 - mae: 1.9927

162/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4267 - mae: 1.9891

203/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2600 - mae: 1.9624

243/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1900 - mae: 1.9439

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1573 - mae: 1.9414 - val_loss: 5.5173 - val_mae: 1.8627

Epoch 35/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 13.7684 - mae: 3.2193

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9589 - mae: 2.1142

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6359 - mae: 2.0404

122/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4752 - mae: 1.9993

162/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4204 - mae: 1.9879

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2658 - mae: 1.9625

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2015 - mae: 1.9460

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1558 - mae: 1.9412 - val_loss: 5.5232 - val_mae: 1.8631

Epoch 36/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.7311 - mae: 3.2173

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8518 - mae: 2.0971

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5699 - mae: 2.0244

129/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4210 - mae: 1.9874

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3517 - mae: 1.9767

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2550 - mae: 1.9582

251/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1547 - mae: 1.9387

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1532 - mae: 1.9404 - val_loss: 5.5212 - val_mae: 1.8631

Epoch 37/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 13.7308 - mae: 3.2174

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8429 - mae: 2.0955

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6142 - mae: 2.0398

121/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4602 - mae: 1.9944

163/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3861 - mae: 1.9799

206/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2289 - mae: 1.9582

248/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1771 - mae: 1.9411

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1504 - mae: 1.9398 - val_loss: 5.5197 - val_mae: 1.8627

Epoch 38/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.7236 - mae: 3.2181

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9319 - mae: 2.1147

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6369 - mae: 2.0389

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5271 - mae: 2.0085

167/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3289 - mae: 1.9719

206/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2242 - mae: 1.9581

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1770 - mae: 1.9414

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1463 - mae: 1.9393 - val_loss: 5.5151 - val_mae: 1.8614

Epoch 39/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 13.6871 - mae: 3.2147

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8313 - mae: 2.0930

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5536 - mae: 2.0205

128/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4267 - mae: 1.9885

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3390 - mae: 1.9740

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2691 - mae: 1.9609

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1543 - mae: 1.9377

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1437 - mae: 1.9384 - val_loss: 5.5107 - val_mae: 1.8601

Epoch 40/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 13.6211 - mae: 3.2091

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9216 - mae: 2.1122

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6613 - mae: 2.0401

121/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4448 - mae: 1.9921

161/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3965 - mae: 1.9831

202/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2506 - mae: 1.9591

242/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1604 - mae: 1.9381

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1398 - mae: 1.9379 - val_loss: 5.5103 - val_mae: 1.8607

Epoch 41/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 34ms/step - loss: 13.6640 - mae: 3.2221

 39/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9900 - mae: 2.1124

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5980 - mae: 2.0360

116/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3976 - mae: 1.9876

153/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2851 - mae: 1.9692

193/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2450 - mae: 1.9593

233/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2233 - mae: 1.9452

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1375 - mae: 1.9372 - val_loss: 5.5068 - val_mae: 1.8597

Epoch 42/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.6131 - mae: 3.2074

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9249 - mae: 2.1070

 84/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5818 - mae: 2.0292

126/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4743 - mae: 1.9990

170/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3223 - mae: 1.9722

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2033 - mae: 1.9528

249/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1576 - mae: 1.9368

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1330 - mae: 1.9361 - val_loss: 5.5058 - val_mae: 1.8588

Epoch 43/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.5975 - mae: 3.2084

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9001 - mae: 2.0852

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5879 - mae: 2.0344

119/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4604 - mae: 1.9971

159/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3666 - mae: 1.9796

203/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2251 - mae: 1.9560

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1710 - mae: 1.9402

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1255 - mae: 1.9355 - val_loss: 5.5005 - val_mae: 1.8587

Epoch 44/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - loss: 13.6557 - mae: 3.2103

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9323 - mae: 2.1063

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5859 - mae: 2.0337

119/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4572 - mae: 1.9964

159/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3651 - mae: 1.9794

200/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2284 - mae: 1.9565

239/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1724 - mae: 1.9389

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1244 - mae: 1.9353 - val_loss: 5.5003 - val_mae: 1.8575

Epoch 45/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 13.6472 - mae: 3.2154

 45/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7614 - mae: 2.0847

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5278 - mae: 2.0169

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4773 - mae: 2.0006

165/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3281 - mae: 1.9700

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1938 - mae: 1.9519

249/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1501 - mae: 1.9360

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1246 - mae: 1.9351 - val_loss: 5.5012 - val_mae: 1.8576

Epoch 46/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 13.6097 - mae: 3.2186

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8039 - mae: 2.0865

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5270 - mae: 2.0162

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4196 - mae: 1.9900

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3249 - mae: 1.9692

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2362 - mae: 1.9555

253/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1271 - mae: 1.9323

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1215 - mae: 1.9340 - val_loss: 5.4973 - val_mae: 1.8573

Epoch 47/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.5847 - mae: 3.2118

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8155 - mae: 2.0917

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5863 - mae: 2.0303

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4866 - mae: 2.0004

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3092 - mae: 1.9672

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2325 - mae: 1.9552

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1093 - mae: 1.9305

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1163 - mae: 1.9334 - val_loss: 5.4945 - val_mae: 1.8569

Epoch 48/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 13.6410 - mae: 3.2240

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8100 - mae: 2.0901

 87/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4985 - mae: 2.0118

129/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3657 - mae: 1.9762

172/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2942 - mae: 1.9670

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2169 - mae: 1.9500

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1073 - mae: 1.9291

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1144 - mae: 1.9321 - val_loss: 5.4963 - val_mae: 1.8567

Epoch 49/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 13.6009 - mae: 3.2299

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8798 - mae: 2.1022

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5770 - mae: 2.0279

122/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4116 - mae: 1.9865

162/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3707 - mae: 1.9775

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2045 - mae: 1.9525

246/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1437 - mae: 1.9337

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1117 - mae: 1.9319 - val_loss: 5.4889 - val_mae: 1.8558

Epoch 50/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 13.6196 - mae: 3.2333

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8879 - mae: 2.0981

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5541 - mae: 2.0209

129/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3558 - mae: 1.9746

171/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2834 - mae: 1.9643

215/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1713 - mae: 1.9420

260/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1058 - mae: 1.9290

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1074 - mae: 1.9308 - val_loss: 5.4902 - val_mae: 1.8560

Epoch 51/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 13.6088 - mae: 3.2304

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8866 - mae: 2.0978

 84/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5436 - mae: 2.0229

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3957 - mae: 1.9850

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3064 - mae: 1.9650

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2298 - mae: 1.9527

254/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1021 - mae: 1.9279

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1036 - mae: 1.9298 - val_loss: 5.4896 - val_mae: 1.8567

Epoch 52/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - loss: 13.6216 - mae: 3.2421

 37/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8604 - mae: 2.0760

 75/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6501 - mae: 2.0393

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4065 - mae: 1.9854

153/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2453 - mae: 1.9606

186/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2876 - mae: 1.9666

225/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2467 - mae: 1.9474

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.1018 - mae: 1.9295 - val_loss: 5.4899 - val_mae: 1.8561

Epoch 53/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 13.6384 - mae: 3.2469

 39/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.9351 - mae: 2.0999

 79/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5474 - mae: 2.0251

117/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3477 - mae: 1.9769

159/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3310 - mae: 1.9722

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2037 - mae: 1.9501

241/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1271 - mae: 1.9299

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0962 - mae: 1.9288 - val_loss: 5.4850 - val_mae: 1.8558

Epoch 54/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 13.6481 - mae: 3.2517

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8737 - mae: 2.0937

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5366 - mae: 2.0172

126/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4180 - mae: 1.9883

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2858 - mae: 1.9636

210/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2206 - mae: 1.9512

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1426 - mae: 1.9328

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0942 - mae: 1.9280 - val_loss: 5.4866 - val_mae: 1.8555

Epoch 55/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 13.6571 - mae: 3.2567

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7569 - mae: 2.0740

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5356 - mae: 2.0164

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4339 - mae: 1.9902

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3061 - mae: 1.9628

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1818 - mae: 1.9475

249/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1170 - mae: 1.9274

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0906 - mae: 1.9266 - val_loss: 5.4840 - val_mae: 1.8558

Epoch 56/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.6592 - mae: 3.2599

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8475 - mae: 2.0943

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5294 - mae: 2.0155

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3754 - mae: 1.9808

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2806 - mae: 1.9622

208/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2022 - mae: 1.9485

247/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1047 - mae: 1.9262

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0854 - mae: 1.9263 - val_loss: 5.4861 - val_mae: 1.8561

Epoch 57/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 13.6989 - mae: 3.2632

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7518 - mae: 2.0732

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4807 - mae: 2.0055

122/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3794 - mae: 1.9798

160/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3279 - mae: 1.9690

198/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2103 - mae: 1.9509

234/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1560 - mae: 1.9309

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0844 - mae: 1.9255 - val_loss: 5.4854 - val_mae: 1.8545

Epoch 58/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 13.6662 - mae: 3.2575

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8553 - mae: 2.0892

 83/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5373 - mae: 2.0184

124/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4403 - mae: 1.9895

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2965 - mae: 1.9608

205/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1719 - mae: 1.9457

245/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1308 - mae: 1.9295

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0814 - mae: 1.9245 - val_loss: 5.4868 - val_mae: 1.8549

Epoch 59/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 13.6643 - mae: 3.2639

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8522 - mae: 2.0884

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5267 - mae: 2.0206

108/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4509 - mae: 1.9927

138/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2866 - mae: 1.9635

177/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2296 - mae: 1.9563

215/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1424 - mae: 1.9353

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0725 - mae: 1.9206

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0782 - mae: 1.9235 - val_loss: 5.4877 - val_mae: 1.8558

Epoch 60/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 13.6976 - mae: 3.2624

 41/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8486 - mae: 2.0869

 81/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5805 - mae: 2.0204

118/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3316 - mae: 1.9728

159/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3096 - mae: 1.9666

200/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1730 - mae: 1.9437

241/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1094 - mae: 1.9247

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0769 - mae: 1.9233 - val_loss: 5.4819 - val_mae: 1.8558

Epoch 61/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.7238 - mae: 3.2790

 38/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8454 - mae: 2.0774

 77/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6055 - mae: 2.0329

113/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3693 - mae: 1.9770

154/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2312 - mae: 1.9559

197/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1932 - mae: 1.9485

238/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1251 - mae: 1.9270

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0725 - mae: 1.9230 - val_loss: 5.4871 - val_mae: 1.8570

Epoch 62/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 31ms/step - loss: 13.7459 - mae: 3.2703

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7302 - mae: 2.0670

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4604 - mae: 2.0002

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3525 - mae: 1.9752

168/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2722 - mae: 1.9577

209/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2007 - mae: 1.9466

250/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0807 - mae: 1.9217

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0686 - mae: 1.9225 - val_loss: 5.4854 - val_mae: 1.8564

Epoch 63/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.7654 - mae: 3.2737

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8582 - mae: 2.0884

 77/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5989 - mae: 2.0305

119/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3740 - mae: 1.9767

162/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3215 - mae: 1.9657

198/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1864 - mae: 1.9457

238/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1176 - mae: 1.9247

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0649 - mae: 1.9210 - val_loss: 5.4806 - val_mae: 1.8553

Epoch 64/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 30ms/step - loss: 13.7430 - mae: 3.2638

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7283 - mae: 2.0652

 84/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4919 - mae: 2.0092

123/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3559 - mae: 1.9731

165/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2643 - mae: 1.9541

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1639 - mae: 1.9410

226/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2034 - mae: 1.9389

260/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0612 - mae: 1.9186

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0615 - mae: 1.9202 - val_loss: 5.4794 - val_mae: 1.8556

Epoch 65/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - loss: 13.7561 - mae: 3.2750

 35/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8470 - mae: 2.0633

 75/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6003 - mae: 2.0264

115/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3163 - mae: 1.9676

155/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2252 - mae: 1.9517

195/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1811 - mae: 1.9447

226/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2006 - mae: 1.9383

258/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0375 - mae: 1.9142

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0584 - mae: 1.9195 - val_loss: 5.4767 - val_mae: 1.8558

Epoch 66/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 11s 45ms/step - loss: 13.7600 - mae: 3.2749

 25/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7508 - mae: 2.0374

 36/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7857 - mae: 2.0580

 49/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7479 - mae: 2.0802

 61/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7423 - mae: 2.0486

 75/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5947 - mae: 2.0259

 96/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4605 - mae: 1.9942

115/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3110 - mae: 1.9668

138/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2592 - mae: 1.9582

164/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2708 - mae: 1.9559

194/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1770 - mae: 1.9446

222/262 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2000 - mae: 1.9377

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0491 - mae: 1.9163

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0550 - mae: 1.9192 - val_loss: 5.4770 - val_mae: 1.8568

Epoch 67/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - loss: 13.7379 - mae: 3.2741

 32/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9349 - mae: 2.0775

 64/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6590 - mae: 2.0354

 95/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4723 - mae: 1.9948

129/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2865 - mae: 1.9593

160/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2945 - mae: 1.9623

193/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1507 - mae: 1.9392

225/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1970 - mae: 1.9358

258/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0318 - mae: 1.9128

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0524 - mae: 1.9181 - val_loss: 5.4764 - val_mae: 1.8568

Epoch 68/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 10s 41ms/step - loss: 13.7628 - mae: 3.2808

 35/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8354 - mae: 2.0629

 71/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.6401 - mae: 2.0315

109/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4120 - mae: 1.9863

146/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1865 - mae: 1.9454

186/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2292 - mae: 1.9536

226/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1921 - mae: 1.9365

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0500 - mae: 1.9177 - val_loss: 5.4758 - val_mae: 1.8563

Epoch 69/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 13.7551 - mae: 3.2819

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8073 - mae: 2.0856

 80/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4899 - mae: 2.0136

120/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3527 - mae: 1.9713

161/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2945 - mae: 1.9622

200/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1379 - mae: 1.9380

240/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0828 - mae: 1.9190

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0444 - mae: 1.9174 - val_loss: 5.4750 - val_mae: 1.8564

Epoch 70/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 13.7418 - mae: 3.2779

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8044 - mae: 2.0849

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5128 - mae: 2.0108

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3752 - mae: 1.9770

162/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3036 - mae: 1.9627

201/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1440 - mae: 1.9376

243/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0798 - mae: 1.9193

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0423 - mae: 1.9166 - val_loss: 5.4693 - val_mae: 1.8553

Epoch 71/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 27ms/step - loss: 13.7432 - mae: 3.2807

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7111 - mae: 2.0651

 85/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4793 - mae: 2.0050

127/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3220 - mae: 1.9692

170/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2247 - mae: 1.9520

212/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1394 - mae: 1.9356

253/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0477 - mae: 1.9152

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0400 - mae: 1.9166 - val_loss: 5.4782 - val_mae: 1.8575

Epoch 72/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 13.7143 - mae: 3.2668

 43/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7018 - mae: 2.0623

 86/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4257 - mae: 1.9922

128/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2961 - mae: 1.9614

171/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2182 - mae: 1.9504

211/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1472 - mae: 1.9358

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0379 - mae: 1.9137

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0421 - mae: 1.9163 - val_loss: 5.4760 - val_mae: 1.8572

Epoch 73/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - loss: 13.8510 - mae: 3.2952

 44/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.7219 - mae: 2.0718

 88/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3804 - mae: 1.9871

132/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2268 - mae: 1.9499

169/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2263 - mae: 1.9503

212/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1313 - mae: 1.9341

252/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0266 - mae: 1.9122

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0323 - mae: 1.9151 - val_loss: 5.4823 - val_mae: 1.8578

Epoch 74/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 32ms/step - loss: 13.7333 - mae: 3.2714

 42/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8025 - mae: 2.0848

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4976 - mae: 2.0075

123/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3175 - mae: 1.9655

166/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2189 - mae: 1.9461

207/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0973 - mae: 1.9313

249/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0562 - mae: 1.9147

262/262 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.0298 - mae: 1.9139 - val_loss: 5.4809 - val_mae: 1.8574

Epoch 75/500

  1/262 ━━━━━━━━━━━━━━━━━━━━ 8s 33ms/step - loss: 13.7922 - mae: 3.2757

 40/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8183 - mae: 2.0834

 82/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4896 - mae: 2.0069

125/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3545 - mae: 1.9740

165/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2338 - mae: 1.9495

209/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1634 - mae: 1.9400

249/262 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.0556 - mae: 1.9163

262/262 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0277 - mae: 1.9153 - val_loss: 5.4768 - val_mae: 1.8549

Epoch 75: early stopping

Restoring model weights from the end of the best epoch: 70.

In [13]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

MAE:  1.7997635246633177

C:\Users\dww05002\AppData\Local\Temp\ipykernel_33136\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_33136\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [14]:
from keras.models import load_model

model.save('Univariate_Temperature_Lags.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Univariate_Temperature_Lags.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 30)             │           330 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,085 (4.24 KB)

 Trainable params: 361 (1.41 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 724 (2.83 KB)

Of course, you could play around with more lags and even try polynomial features or other scaling to get this to work. Heck, once your data is prepped, you can even try TPOT to see if you can get a better architecture then what you are evaluating.