<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_RNN_Advanced.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 14 — ConvLSTM on the temperature and occupancy series
- Data prep is UNCHANGED - just add convolution + pooling in front of the recurrent layer (the 'ConvLSTM' of the 2010s).
- Univariate: look-back 30, kernel 3, 32 filters -> 30 x 1 becomes 28 x 32.
- Then hop to Multivariate_Occupancy_RNN_AdvancedTopics: look-back 50, 5 features -> 48 x 32, pooled to 24 x 32, into a SimpleRNN.
- The secret sauce is shapes: input_shape, return_sequences when stacking, and knowing every output shape and param count.
-->

# Univariate Temperature Example (Advanced)
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the temperature as a function of N previous days - building on our previous script, and adding some 1D convolutions, 1D maxpooling, and dropout. Just make sure your sequences are long enough to do meaningful convolutions!

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# prep data for modeling (univariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [5]:
# here's an example of how this script works
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90

In [6]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 30 # long enough to do convolutions!
raw_seq = df['Temp'] # the second column, where the data is. UPDATE THIS ON YOUR DATA!
# let's ignore the date column and just use the temperature data
X, y = split_sequence(raw_seq, n_steps)

In [7]:
# take a peak at what it did
print(X[0])
print(y[0])

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

[20.7 17.9 18.8 14.6 15.8 15.8 15.8 17.4 21.8 20.  16.2 13.3 16.7 21.5
 25.  20.7 20.6 24.8 17.7 15.5 18.2 12.1 14.4 16.  16.5 18.7 19.4 17.2
 15.5 15.1]
15.4

In [8]:
# now we reshape the data into a 3D array
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1 # this is 1 because it is univariate data
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [9]:
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [10]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)

# verify that this all adds up!
# samples, length, variables

(3620, 30, 1) (3258, 30, 1) (362, 30, 1)

In [11]:
# peak at it!
X_train[0]

array([[20.7],
       [17.9],
       [18.8],
       [14.6],
       [15.8],
       [15.8],
       [15.8],
       [17.4],
       [21.8],
       [20. ],
       [16.2],
       [13.3],
       [16.7],
       [21.5],
       [25. ],
       [20.7],
       [20.6],
       [24.8],
       [17.7],
       [15.5],
       [18.2],
       [12.1],
       [14.4],
       [16. ],
       [16.5],
       [18.7],
       [19.4],
       [17.2],
       [15.5],
       [15.1]])

In [12]:
# if we wanted to, we could do some scaling/normalization here, would not hurt!

# RNN one layer model (with Conv and Pooling)

In [13]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_steps = 30
n_features = 1

# for Conv1D, you can play with the filters and kernel size

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(SimpleRNN(30, activation='relu'))
model.add(Dropout(0.1)) # pick a number between 0.1 and 0.3
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,890 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,049 (8.00 KB)

 Trainable params: 2,049 (8.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 49:44 6s/step - loss: 235.1433 - mae: 14.7262

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 122.0132 - mae: 10.2785

 18/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 85.9864 - mae: 8.2156

 26/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 66.9167 - mae: 6.8582

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 57.8635 - mae: 6.1664

 39/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 52.2357 - mae: 5.7210

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 46.4531 - mae: 5.2858

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 41.3893 - mae: 4.9045

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 39.0058 - mae: 4.7045

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 36.1777 - mae: 4.5017

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 34.2710 - mae: 4.3570

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 32.0623 - mae: 4.1948

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 30.5921 - mae: 4.0546

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 29.1684 - mae: 3.9636

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 28.1253 - mae: 3.9019

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 27.3439 - mae: 3.8564

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 26.8139 - mae: 3.8167

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 25.7398 - mae: 3.7382

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 24.9640 - mae: 3.6789

139/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 24.3463 - mae: 3.6333

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 23.5432 - mae: 3.5645

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 22.9032 - mae: 3.5145

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 22.9511 - mae: 3.5325

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 22.4417 - mae: 3.4961

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 21.9129 - mae: 3.4536

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 21.7076 - mae: 3.4466

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 21.2934 - mae: 3.4204

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 20.8194 - mae: 3.3793

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 20.6147 - mae: 3.3691

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 20.2187 - mae: 3.3399

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 20.0233 - mae: 3.3264

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 19.7989 - mae: 3.3117

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 19.7531 - mae: 3.3074

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 19.4809 - mae: 3.2812

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 19.3011 - mae: 3.2686

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 18.9569 - mae: 3.2410

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 18.5930 - mae: 3.2051

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 18.3386 - mae: 3.1855

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 18.1766 - mae: 3.1695

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.8980 - mae: 3.1422

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.8123 - mae: 3.1317

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.6057 - mae: 3.1143

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.6721 - mae: 3.1134

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.4581 - mae: 3.0942

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.2752 - mae: 3.0812

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.1707 - mae: 3.0769

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 17.0200 - mae: 3.0673

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 16.9658 - mae: 3.0675

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 16.8711 - mae: 3.0605

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 16.7720 - mae: 3.0540

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 16.6542 - mae: 3.0444

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 16.5805 - mae: 3.0391

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.5307 - mae: 3.0415

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.3629 - mae: 3.0254

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.2540 - mae: 3.0182

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.1470 - mae: 3.0122

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.0299 - mae: 3.0025

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.9069 - mae: 2.9904

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.9099 - mae: 2.9945

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.7553 - mae: 2.9774

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.6225 - mae: 2.9666

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.4460 - mae: 2.9505

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.2848 - mae: 2.9333

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.1874 - mae: 2.9242

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.0746 - mae: 2.9128

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.0199 - mae: 2.9087

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.9443 - mae: 2.9050

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.8899 - mae: 2.9020

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.7625 - mae: 2.8905

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.6993 - mae: 2.8868

522/522 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - loss: 14.6327 - mae: 2.8815 - val_loss: 6.4329 - val_mae: 1.9831

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 39s 75ms/step - loss: 4.7402 - mae: 2.0526

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0786 - mae: 2.3639

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.2326 - mae: 2.5437

 23/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.8744 - mae: 2.5155

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.5288 - mae: 2.5024

 35/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0704 - mae: 2.4435

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1857 - mae: 2.4279

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8513 - mae: 2.4993

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9017 - mae: 2.5223

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8550 - mae: 2.4591

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3742 - mae: 2.5304

 75/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6255 - mae: 2.5672

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3955 - mae: 2.5338

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7306 - mae: 2.5710

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6692 - mae: 2.5668

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3299 - mae: 2.5149

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7661 - mae: 2.5402

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7555 - mae: 2.5455

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6474 - mae: 2.5326

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.5671 - mae: 2.5227

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.3530 - mae: 2.5000

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1618 - mae: 2.4748

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1455 - mae: 2.4625

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.2001 - mae: 2.4723

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.4996 - mae: 2.5055

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.2951 - mae: 2.4745

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1393 - mae: 2.4569

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0295 - mae: 2.4372

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0388 - mae: 2.4370

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0469 - mae: 2.4449

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1791 - mae: 2.4566

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1115 - mae: 2.4536

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1168 - mae: 2.4506

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1398 - mae: 2.4526

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 10.2027 - mae: 2.4604

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 10.1671 - mae: 2.4551

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 10.0720 - mae: 2.4439

273/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 10.0339 - mae: 2.4405

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.9852 - mae: 2.4297

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.9363 - mae: 2.4308

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8955 - mae: 2.4279

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8246 - mae: 2.4192

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8954 - mae: 2.4329

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8656 - mae: 2.4328

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8723 - mae: 2.4376

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8591 - mae: 2.4397

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8598 - mae: 2.4441

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8143 - mae: 2.4411

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.7905 - mae: 2.4379

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.9041 - mae: 2.4520

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8740 - mae: 2.4503

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.8135 - mae: 2.4417

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.7904 - mae: 2.4392

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.7698 - mae: 2.4356

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.7378 - mae: 2.4317

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.7316 - mae: 2.4320

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.6790 - mae: 2.4239

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.6377 - mae: 2.4186

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.6483 - mae: 2.4212

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.6456 - mae: 2.4219

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5958 - mae: 2.4173

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5146 - mae: 2.4064

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5332 - mae: 2.4067

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5150 - mae: 2.4073

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.4907 - mae: 2.4032

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.4841 - mae: 2.4021

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5518 - mae: 2.4119

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5309 - mae: 2.4071

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5362 - mae: 2.4096

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5229 - mae: 2.4049

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5038 - mae: 2.4006

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.4971 - mae: 2.4020

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 9.4971 - mae: 2.4020 - val_loss: 6.5311 - val_mae: 2.0065

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 40s 77ms/step - loss: 1.9182 - mae: 1.2708

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.0607 - mae: 2.2091

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.9911 - mae: 2.3562

 27/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3650 - mae: 2.3489

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3104 - mae: 2.3454

 45/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8250 - mae: 2.2885

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2442 - mae: 2.2166

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2201 - mae: 2.2341

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9196 - mae: 2.2993

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9035 - mae: 2.3004

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8339 - mae: 2.2953

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7949 - mae: 2.3026

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8420 - mae: 2.3168

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9628 - mae: 2.3278

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9243 - mae: 2.3321

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9767 - mae: 2.3373

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8937 - mae: 2.3287

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7490 - mae: 2.3122

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9892 - mae: 2.3331

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2084 - mae: 2.3642

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0832 - mae: 2.3512

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1585 - mae: 2.3592

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1032 - mae: 2.3500

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1468 - mae: 2.3611

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2404 - mae: 2.3716

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2319 - mae: 2.3780

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2890 - mae: 2.3818

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2926 - mae: 2.3858

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2457 - mae: 2.3792

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1880 - mae: 2.3710

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1591 - mae: 2.3661

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2264 - mae: 2.3735

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2870 - mae: 2.3806

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2146 - mae: 2.3744

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2173 - mae: 2.3775

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2304 - mae: 2.3779

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2210 - mae: 2.3814

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1550 - mae: 2.3782

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2055 - mae: 2.3805

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1780 - mae: 2.3743

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1599 - mae: 2.3681

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1520 - mae: 2.3638

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2182 - mae: 2.3743

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2316 - mae: 2.3787

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1841 - mae: 2.3752

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1644 - mae: 2.3747

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0523 - mae: 2.3587

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0439 - mae: 2.3599

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1449 - mae: 2.3713

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1342 - mae: 2.3697

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1566 - mae: 2.3704

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1746 - mae: 2.3727

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2055 - mae: 2.3814

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1854 - mae: 2.3768

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1674 - mae: 2.3755

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1084 - mae: 2.3662

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1556 - mae: 2.3749

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1582 - mae: 2.3753

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0989 - mae: 2.3663

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1514 - mae: 2.3719

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1262 - mae: 2.3714

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1337 - mae: 2.3719

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1131 - mae: 2.3712

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1108 - mae: 2.3707

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1905 - mae: 2.3780

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1375 - mae: 2.3732

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1566 - mae: 2.3778

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.1502 - mae: 2.3774 - val_loss: 6.0118 - val_mae: 1.9191

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 35s 69ms/step - loss: 6.1020 - mae: 2.2077

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.4714 - mae: 2.0996

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.9069 - mae: 2.2889

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.3307 - mae: 2.3751

 33/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.7774 - mae: 2.4606

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.1688 - mae: 2.4131

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5801 - mae: 2.4722

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2390 - mae: 2.4489

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.4161 - mae: 2.4588

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1052 - mae: 2.4300

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9384 - mae: 2.4121

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.4477 - mae: 2.4615

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.4642 - mae: 2.4732

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.6748 - mae: 2.4900

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.3435 - mae: 2.4423

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0507 - mae: 2.3953

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0524 - mae: 2.3993

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9108 - mae: 2.3822

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9873 - mae: 2.3850

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8042 - mae: 2.3506

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8070 - mae: 2.3391

165/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8682 - mae: 2.3483

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7824 - mae: 2.3341

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6684 - mae: 2.3185

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6752 - mae: 2.3145

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5885 - mae: 2.3024

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6955 - mae: 2.3142

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7087 - mae: 2.3158

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6983 - mae: 2.3125

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7221 - mae: 2.3204

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6060 - mae: 2.3038

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5387 - mae: 2.2916

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4791 - mae: 2.2857

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5369 - mae: 2.2933

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4659 - mae: 2.2835

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4909 - mae: 2.2885

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4501 - mae: 2.2852

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4527 - mae: 2.2824

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5193 - mae: 2.2885

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5321 - mae: 2.2937

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5310 - mae: 2.2897

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5511 - mae: 2.2973

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5105 - mae: 2.2930

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5032 - mae: 2.2870

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4792 - mae: 2.2833

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5070 - mae: 2.2873

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5827 - mae: 2.2927

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5302 - mae: 2.2865

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5544 - mae: 2.2895

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5408 - mae: 2.2860

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4847 - mae: 2.2766

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5491 - mae: 2.2865

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5855 - mae: 2.2969

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5698 - mae: 2.2944

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5677 - mae: 2.2926

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6285 - mae: 2.2982

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6224 - mae: 2.3010

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6820 - mae: 2.3067

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6921 - mae: 2.3079

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6445 - mae: 2.3007

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6537 - mae: 2.2981

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5723 - mae: 2.2851

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5427 - mae: 2.2818

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5537 - mae: 2.2842

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5825 - mae: 2.2877

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6206 - mae: 2.2926

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.6103 - mae: 2.2921 - val_loss: 5.8948 - val_mae: 1.8963

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - loss: 9.8982 - mae: 2.3880

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 11.6894 - mae: 2.7390

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.9511 - mae: 2.4898

 30/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.8053 - mae: 2.4801

 40/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8741 - mae: 2.3090

 50/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4939 - mae: 2.2838

 60/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0388 - mae: 2.2231

 70/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7772 - mae: 2.1976

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7455 - mae: 2.1865

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6603 - mae: 2.1705

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9010 - mae: 2.2128

110/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7447 - mae: 2.1831

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6938 - mae: 2.1770

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0844 - mae: 2.1997

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1379 - mae: 2.2136

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3587 - mae: 2.2480

160/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4022 - mae: 2.2501

171/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3286 - mae: 2.2481

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1809 - mae: 2.2339

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1484 - mae: 2.2301

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2731 - mae: 2.2466

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2494 - mae: 2.2449

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1662 - mae: 2.2374

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1142 - mae: 2.2268

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0939 - mae: 2.2242

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9953 - mae: 2.2128

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0315 - mae: 2.2154

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1166 - mae: 2.2267

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0449 - mae: 2.2196

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0732 - mae: 2.2187

273/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0948 - mae: 2.2262

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1189 - mae: 2.2302

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1723 - mae: 2.2363

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1777 - mae: 2.2304

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1572 - mae: 2.2272

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1652 - mae: 2.2279

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2082 - mae: 2.2292

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2259 - mae: 2.2322

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2787 - mae: 2.2388

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2633 - mae: 2.2395

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2904 - mae: 2.2396

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2994 - mae: 2.2430

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3516 - mae: 2.2419

375/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3121 - mae: 2.2407

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3025 - mae: 2.2426

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3064 - mae: 2.2440

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3097 - mae: 2.2489

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3535 - mae: 2.2524

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3847 - mae: 2.2589

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4158 - mae: 2.2646

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4092 - mae: 2.2633

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4143 - mae: 2.2647

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4562 - mae: 2.2720

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4824 - mae: 2.2748

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5038 - mae: 2.2760

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4937 - mae: 2.2748

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5442 - mae: 2.2805

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5711 - mae: 2.2864

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5767 - mae: 2.2875

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5511 - mae: 2.2842

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4991 - mae: 2.2776

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4557 - mae: 2.2711

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5227 - mae: 2.2791

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.4980 - mae: 2.2776 - val_loss: 6.3386 - val_mae: 1.9734

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 33s 65ms/step - loss: 5.1127 - mae: 1.9725

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.0893 - mae: 2.3242

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.6981 - mae: 2.4090

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0620 - mae: 2.3269

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.5912 - mae: 2.4376

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.5266 - mae: 2.4352

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4222 - mae: 2.4294

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.6053 - mae: 2.4454

 71/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4073 - mae: 2.4026

 79/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2413 - mae: 2.3741

 87/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8439 - mae: 2.3126

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5663 - mae: 2.2817

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6851 - mae: 2.3020

111/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5468 - mae: 2.2822

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4973 - mae: 2.2835

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5893 - mae: 2.2954

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5590 - mae: 2.2847

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7088 - mae: 2.2870

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5381 - mae: 2.2753

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4946 - mae: 2.2662

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4113 - mae: 2.2563

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4456 - mae: 2.2571

183/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4569 - mae: 2.2614

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4938 - mae: 2.2722

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4027 - mae: 2.2602

207/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3928 - mae: 2.2564

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4325 - mae: 2.2580

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4262 - mae: 2.2538

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3733 - mae: 2.2490

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4407 - mae: 2.2612

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4196 - mae: 2.2580

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4704 - mae: 2.2703

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5210 - mae: 2.2774

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5302 - mae: 2.2817

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4920 - mae: 2.2765

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5057 - mae: 2.2817

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5057 - mae: 2.2830

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4783 - mae: 2.2784

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5033 - mae: 2.2852

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4613 - mae: 2.2820

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3862 - mae: 2.2704

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4476 - mae: 2.2817

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4885 - mae: 2.2868

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5021 - mae: 2.2853

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4773 - mae: 2.2837

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4643 - mae: 2.2794

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5529 - mae: 2.2874

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6252 - mae: 2.2966

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6434 - mae: 2.2960

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6537 - mae: 2.2977

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6657 - mae: 2.3025

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6246 - mae: 2.2974

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6011 - mae: 2.2966

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5873 - mae: 2.2956

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6133 - mae: 2.2974

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5987 - mae: 2.2944

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5386 - mae: 2.2846

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5386 - mae: 2.2855

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5535 - mae: 2.2850

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6317 - mae: 2.2977

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6077 - mae: 2.2947

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5664 - mae: 2.2916

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5746 - mae: 2.2920

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6202 - mae: 2.3012

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6021 - mae: 2.2972

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.6163 - mae: 2.3001 - val_loss: 6.6910 - val_mae: 2.0345

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - loss: 8.0731 - mae: 2.3643

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.0717 - mae: 2.1902

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1188 - mae: 2.2583

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8061 - mae: 2.3571

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3261 - mae: 2.2917

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7759 - mae: 2.2102

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1487 - mae: 2.2398

 56/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0880 - mae: 2.2349

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.6997 - mae: 2.1788

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.6812 - mae: 2.1937

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8916 - mae: 2.2211

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6955 - mae: 2.2080

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5443 - mae: 2.1873

101/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5631 - mae: 2.1889

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.7533 - mae: 2.2075

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6799 - mae: 2.2030

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6672 - mae: 2.2020

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8156 - mae: 2.2277

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8564 - mae: 2.2450

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0538 - mae: 2.2736

157/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1588 - mae: 2.2870

165/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3922 - mae: 2.3176

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5146 - mae: 2.3260

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4122 - mae: 2.3132

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4840 - mae: 2.3106

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4927 - mae: 2.3103

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4364 - mae: 2.3077

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3891 - mae: 2.3017

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4522 - mae: 2.3148

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5470 - mae: 2.3259

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5051 - mae: 2.3210

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4312 - mae: 2.3104

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3577 - mae: 2.3012

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4138 - mae: 2.3085

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4578 - mae: 2.3165

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5020 - mae: 2.3192

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6261 - mae: 2.3284

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6148 - mae: 2.3259

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6042 - mae: 2.3259

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5943 - mae: 2.3231

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6942 - mae: 2.3346

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6352 - mae: 2.3223

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6328 - mae: 2.3250

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6530 - mae: 2.3292

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6880 - mae: 2.3353

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6457 - mae: 2.3332

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5823 - mae: 2.3245

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5603 - mae: 2.3172

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5691 - mae: 2.3181

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5560 - mae: 2.3121

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5228 - mae: 2.3083

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5632 - mae: 2.3055

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5632 - mae: 2.3053

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5642 - mae: 2.3046

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6193 - mae: 2.3139

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5412 - mae: 2.3032

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5794 - mae: 2.3081

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5264 - mae: 2.2987

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5048 - mae: 2.2953

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4914 - mae: 2.2940

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4241 - mae: 2.2824

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3954 - mae: 2.2773

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3749 - mae: 2.2756

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3737 - mae: 2.2746

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3393 - mae: 2.2705

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3508 - mae: 2.2716

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.3512 - mae: 2.2721 - val_loss: 5.7765 - val_mae: 1.8753

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 35s 69ms/step - loss: 7.3576 - mae: 2.4850

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2700 - mae: 2.2717

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5369 - mae: 2.4089

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7532 - mae: 2.2595

 33/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0110 - mae: 2.3061

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6738 - mae: 2.3868

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5035 - mae: 2.3265

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.4636 - mae: 2.3148

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7810 - mae: 2.3286

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7543 - mae: 2.3024

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6690 - mae: 2.3086

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3903 - mae: 2.2760

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2853 - mae: 2.2715

101/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1045 - mae: 2.2455

110/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0616 - mae: 2.2405

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9993 - mae: 2.2359

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0422 - mae: 2.2366

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9236 - mae: 2.2328

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0628 - mae: 2.2562

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0914 - mae: 2.2542

157/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0977 - mae: 2.2583

165/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1688 - mae: 2.2665

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2665 - mae: 2.2787

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3931 - mae: 2.2949

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2712 - mae: 2.2711

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3096 - mae: 2.2726

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2915 - mae: 2.2706

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1251 - mae: 2.2467

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1408 - mae: 2.2455

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9997 - mae: 2.2245

237/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0940 - mae: 2.2376

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0246 - mae: 2.2248

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0510 - mae: 2.2323

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0796 - mae: 2.2347

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0890 - mae: 2.2383

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0346 - mae: 2.2275

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0028 - mae: 2.2257

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9278 - mae: 2.2156

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9137 - mae: 2.2136

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8589 - mae: 2.2086

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8956 - mae: 2.2144

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9835 - mae: 2.2236

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9841 - mae: 2.2283

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0324 - mae: 2.2349

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9696 - mae: 2.2280

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9523 - mae: 2.2257

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0355 - mae: 2.2359

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0271 - mae: 2.2358

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0632 - mae: 2.2426

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0930 - mae: 2.2459

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1384 - mae: 2.2471

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1680 - mae: 2.2514

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1790 - mae: 2.2527

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1279 - mae: 2.2426

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1237 - mae: 2.2394

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0780 - mae: 2.2338

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0308 - mae: 2.2278

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9895 - mae: 2.2223

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9741 - mae: 2.2189

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9440 - mae: 2.2131

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8986 - mae: 2.2063

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9088 - mae: 2.2075

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8952 - mae: 2.2051

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8996 - mae: 2.2059

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9006 - mae: 2.2072

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.9006 - mae: 2.2072 - val_loss: 5.7910 - val_mae: 1.8778

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 9:33 1s/step - loss: 6.4584 - mae: 2.0753

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.1939 - mae: 2.3683

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8781 - mae: 2.4756

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.0301 - mae: 2.4113

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.8558 - mae: 2.4109

 45/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2936 - mae: 2.3439

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0567 - mae: 2.3078

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8465 - mae: 2.2942

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8432 - mae: 2.3060

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4360 - mae: 2.2438

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3819 - mae: 2.2439

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2125 - mae: 2.2138

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0876 - mae: 2.2036

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9404 - mae: 2.1836

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8956 - mae: 2.1701

131/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0777 - mae: 2.1895

140/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1467 - mae: 2.2074

148/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2158 - mae: 2.2231

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1003 - mae: 2.2108

162/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0423 - mae: 2.2103

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1341 - mae: 2.2293

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9736 - mae: 2.2047

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0554 - mae: 2.2104

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1556 - mae: 2.2167

201/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2632 - mae: 2.2379

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2000 - mae: 2.2324

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2867 - mae: 2.2435

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2610 - mae: 2.2423

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2891 - mae: 2.2461

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3260 - mae: 2.2465

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3053 - mae: 2.2440

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3448 - mae: 2.2494

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4865 - mae: 2.2679

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4523 - mae: 2.2679

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4656 - mae: 2.2700

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4796 - mae: 2.2753

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4997 - mae: 2.2762

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4801 - mae: 2.2715

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4527 - mae: 2.2712

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4223 - mae: 2.2668

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4082 - mae: 2.2655

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3926 - mae: 2.2617

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3649 - mae: 2.2585

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2969 - mae: 2.2484

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2933 - mae: 2.2454

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3011 - mae: 2.2461

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2533 - mae: 2.2396

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4443 - mae: 2.2501

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4102 - mae: 2.2468

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3862 - mae: 2.2437

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3676 - mae: 2.2425

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3430 - mae: 2.2414

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3068 - mae: 2.2348

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2959 - mae: 2.2323

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2374 - mae: 2.2240

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2085 - mae: 2.2176

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2831 - mae: 2.2280

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2777 - mae: 2.2265

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3418 - mae: 2.2376

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3860 - mae: 2.2435

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4264 - mae: 2.2485

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4484 - mae: 2.2546

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4538 - mae: 2.2550

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5199 - mae: 2.2639

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5079 - mae: 2.2640

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4935 - mae: 2.2648

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4882 - mae: 2.2645

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 8.4960 - mae: 2.2657 - val_loss: 6.4757 - val_mae: 2.0070

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 11.3875 - mae: 2.6607

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.2743 - mae: 2.5195

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2729 - mae: 2.3212

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1230 - mae: 2.2250

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2990 - mae: 2.2471

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1226 - mae: 2.2171

 56/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1251 - mae: 2.2413

 66/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1476 - mae: 2.2613

 76/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0701 - mae: 2.2617

 86/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0662 - mae: 2.2539

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9183 - mae: 2.2396

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9780 - mae: 2.2358

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8997 - mae: 2.2224

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9522 - mae: 2.2155

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9672 - mae: 2.2124

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0235 - mae: 2.2224

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9570 - mae: 2.2151

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0971 - mae: 2.2331

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0565 - mae: 2.2322

175/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0134 - mae: 2.2317

183/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9169 - mae: 2.2161

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0145 - mae: 2.2257

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1600 - mae: 2.2515

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1345 - mae: 2.2454

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1055 - mae: 2.2361

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0945 - mae: 2.2400

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2173 - mae: 2.2527

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1843 - mae: 2.2531

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1403 - mae: 2.2485

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1335 - mae: 2.2491

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1885 - mae: 2.2580

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1502 - mae: 2.2509

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2134 - mae: 2.2550

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2110 - mae: 2.2570

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1359 - mae: 2.2482

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1780 - mae: 2.2546

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2025 - mae: 2.2558

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1842 - mae: 2.2523

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2339 - mae: 2.2543

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1808 - mae: 2.2440

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1777 - mae: 2.2414

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1416 - mae: 2.2387

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2378 - mae: 2.2515

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3678 - mae: 2.2633

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3760 - mae: 2.2646

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3882 - mae: 2.2673

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3640 - mae: 2.2630

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3670 - mae: 2.2653

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3804 - mae: 2.2688

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3790 - mae: 2.2706

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3525 - mae: 2.2664

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3557 - mae: 2.2671

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3373 - mae: 2.2642

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2937 - mae: 2.2572

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2179 - mae: 2.2468

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2082 - mae: 2.2457

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2170 - mae: 2.2420

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1963 - mae: 2.2396

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1769 - mae: 2.2376

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1455 - mae: 2.2321

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1566 - mae: 2.2329

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1278 - mae: 2.2317

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1096 - mae: 2.2289

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1050 - mae: 2.2283

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0920 - mae: 2.2277

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.0952 - mae: 2.2276 - val_loss: 5.7552 - val_mae: 1.8703

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 50s 97ms/step - loss: 19.8089 - mae: 3.5796

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.6975 - mae: 2.0688

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4303 - mae: 2.1274

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2273 - mae: 2.2930

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.6718 - mae: 2.3423

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3155 - mae: 2.3202

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7847 - mae: 2.2584

 52/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2349 - mae: 2.3114

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8086 - mae: 2.2713

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7308 - mae: 2.3093

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8447 - mae: 2.3204

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8669 - mae: 2.3302

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8451 - mae: 2.3308

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9934 - mae: 2.3580

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9595 - mae: 2.3631

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7999 - mae: 2.3412

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4919 - mae: 2.2900

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3563 - mae: 2.2715

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1209 - mae: 2.2319

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0842 - mae: 2.2329

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1181 - mae: 2.2418

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1242 - mae: 2.2541

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0570 - mae: 2.2458

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1242 - mae: 2.2478

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0482 - mae: 2.2459

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0376 - mae: 2.2385

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1895 - mae: 2.2456

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1296 - mae: 2.2380

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1210 - mae: 2.2434

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2564 - mae: 2.2606

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1984 - mae: 2.2545

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1922 - mae: 2.2534

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2259 - mae: 2.2598

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2322 - mae: 2.2630

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1313 - mae: 2.2489

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2850 - mae: 2.2601

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3109 - mae: 2.2655

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2999 - mae: 2.2608

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3264 - mae: 2.2610

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2767 - mae: 2.2529

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3032 - mae: 2.2541

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2751 - mae: 2.2504

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2588 - mae: 2.2447

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2895 - mae: 2.2518

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2748 - mae: 2.2438

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2950 - mae: 2.2468

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3168 - mae: 2.2486

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3374 - mae: 2.2567

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3139 - mae: 2.2534

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2745 - mae: 2.2499

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2563 - mae: 2.2498

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1851 - mae: 2.2395

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2092 - mae: 2.2419

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2552 - mae: 2.2490

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2211 - mae: 2.2448

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2127 - mae: 2.2461

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1834 - mae: 2.2445

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1709 - mae: 2.2425

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1655 - mae: 2.2442

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1890 - mae: 2.2450

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.2082 - mae: 2.2487 - val_loss: 5.7183 - val_mae: 1.8646

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 63ms/step - loss: 4.3067 - mae: 1.7512

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1552 - mae: 2.1091

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0972 - mae: 2.2047

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3368 - mae: 2.2011

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7518 - mae: 2.1417

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8212 - mae: 2.2783

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5498 - mae: 2.2303

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3232 - mae: 2.1952

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9816 - mae: 2.1618

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8291 - mae: 2.1578

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0967 - mae: 2.1590

 97/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9468 - mae: 2.1419

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8977 - mae: 2.1472

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0302 - mae: 2.1782

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0107 - mae: 2.1748

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1137 - mae: 2.1943

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0564 - mae: 2.1806

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1721 - mae: 2.1988

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2409 - mae: 2.2216

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4065 - mae: 2.2482

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3864 - mae: 2.2479

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2069 - mae: 2.2218

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1733 - mae: 2.2171

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1098 - mae: 2.2076

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1021 - mae: 2.2129

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0543 - mae: 2.2117

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9904 - mae: 2.2051

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9293 - mae: 2.1964

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8964 - mae: 2.1896

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8525 - mae: 2.1859

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8981 - mae: 2.1944

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9269 - mae: 2.2039

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0131 - mae: 2.2185

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9049 - mae: 2.2033

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8040 - mae: 2.1867

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9377 - mae: 2.2038

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9878 - mae: 2.2055

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0643 - mae: 2.2166

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0585 - mae: 2.2155

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0432 - mae: 2.2179

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0908 - mae: 2.2148

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0469 - mae: 2.2095

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0014 - mae: 2.2044

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9791 - mae: 2.2011

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9524 - mae: 2.2019

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0141 - mae: 2.2119

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9515 - mae: 2.2026

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9381 - mae: 2.2031

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9693 - mae: 2.2115

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9587 - mae: 2.2127

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9952 - mae: 2.2171

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9576 - mae: 2.2154

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9531 - mae: 2.2152

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9733 - mae: 2.2184

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0658 - mae: 2.2307

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0621 - mae: 2.2304

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0529 - mae: 2.2316

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0125 - mae: 2.2247

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.0156 - mae: 2.2273 - val_loss: 6.0039 - val_mae: 1.9152

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 14.2065 - mae: 3.5381

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 15.4227 - mae: 2.9358

 20/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.7730 - mae: 2.3829

 30/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8769 - mae: 2.1714

 39/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9014 - mae: 2.2433

 49/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1458 - mae: 2.2932

 58/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.4692 - mae: 2.3537

 67/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4429 - mae: 2.3728

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3113 - mae: 2.3597

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9846 - mae: 2.3228

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9147 - mae: 2.3162

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7314 - mae: 2.2884

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4177 - mae: 2.2413

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2623 - mae: 2.2141

131/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2997 - mae: 2.2179

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2318 - mae: 2.2162

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2240 - mae: 2.2131

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0886 - mae: 2.1981

170/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9991 - mae: 2.1986

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0797 - mae: 2.2114

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9714 - mae: 2.1923

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9753 - mae: 2.2064

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9891 - mae: 2.2122

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0748 - mae: 2.2262

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0199 - mae: 2.2160

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9995 - mae: 2.2077

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1092 - mae: 2.2198

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2392 - mae: 2.2397

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2047 - mae: 2.2358

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1465 - mae: 2.2274

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2844 - mae: 2.2448

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2174 - mae: 2.2351

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2021 - mae: 2.2325

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1915 - mae: 2.2321

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1968 - mae: 2.2275

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3043 - mae: 2.2431

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2936 - mae: 2.2401

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2542 - mae: 2.2346

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1726 - mae: 2.2244

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1285 - mae: 2.2148

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0963 - mae: 2.2113

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1473 - mae: 2.2204

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1379 - mae: 2.2175

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1044 - mae: 2.2142

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0751 - mae: 2.2090

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0393 - mae: 2.2047

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0464 - mae: 2.2040

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0543 - mae: 2.2054

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0395 - mae: 2.1982

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0020 - mae: 2.1934

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0124 - mae: 2.1935

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1209 - mae: 2.2061

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1143 - mae: 2.2047

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1191 - mae: 2.2073

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0925 - mae: 2.2043

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1091 - mae: 2.2065

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.1088 - mae: 2.2067 - val_loss: 5.8337 - val_mae: 1.8834

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 6.2495 - mae: 2.1431

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.0422 - mae: 1.9828

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 5.9002 - mae: 1.9384

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.5142 - mae: 2.0125

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.4837 - mae: 1.9972

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.5508 - mae: 2.0101

 56/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2928 - mae: 2.0992

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1626 - mae: 2.0842

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4000 - mae: 2.1098

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1700 - mae: 2.0586

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.9755 - mae: 2.0321

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.8932 - mae: 2.0232

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.3271 - mae: 2.1017

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4034 - mae: 2.1140

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4519 - mae: 2.1162

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.3666 - mae: 2.1106

155/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2589 - mae: 2.0908

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.1880 - mae: 2.0862

177/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3353 - mae: 2.1016

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3414 - mae: 2.0975

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5065 - mae: 2.1233

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4862 - mae: 2.1166

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5140 - mae: 2.1250

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8011 - mae: 2.1517

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6806 - mae: 2.1378

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8757 - mae: 2.1641

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8723 - mae: 2.1673

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9153 - mae: 2.1797

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8481 - mae: 2.1722

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8342 - mae: 2.1695

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1144 - mae: 2.1938

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1304 - mae: 2.1978

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1167 - mae: 2.2017

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1431 - mae: 2.2070

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0878 - mae: 2.1992

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0774 - mae: 2.1991

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0823 - mae: 2.1980

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0808 - mae: 2.2004

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0205 - mae: 2.1920

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0003 - mae: 2.1896

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9927 - mae: 2.1933

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0342 - mae: 2.2025

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0197 - mae: 2.1974

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0245 - mae: 2.2013

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0902 - mae: 2.2124

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9553 - mae: 2.1911

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9275 - mae: 2.1847

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9491 - mae: 2.1863

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9556 - mae: 2.1856

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8779 - mae: 2.1752

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.8751 - mae: 2.1746 - val_loss: 6.8277 - val_mae: 2.0594

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 18.2760 - mae: 3.7350

 13/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.6016 - mae: 2.2607

 25/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.7611 - mae: 2.2233

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4777 - mae: 2.1666

 48/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.6990 - mae: 2.2195

 60/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.2421 - mae: 2.2770

 72/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3846 - mae: 2.2807

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3337 - mae: 2.2462

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1679 - mae: 2.2136

108/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1823 - mae: 2.2100

120/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0513 - mae: 2.1994

132/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8654 - mae: 2.1714

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7636 - mae: 2.1575

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6984 - mae: 2.1597

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9406 - mae: 2.1851

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9293 - mae: 2.1893

186/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9552 - mae: 2.2022

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9848 - mae: 2.2099

210/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0200 - mae: 2.2188

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1756 - mae: 2.2387

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3146 - mae: 2.2624

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3288 - mae: 2.2610

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2897 - mae: 2.2537

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2186 - mae: 2.2426

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2167 - mae: 2.2393

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1079 - mae: 2.2264

302/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1677 - mae: 2.2382

313/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2265 - mae: 2.2470

325/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2078 - mae: 2.2452

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0969 - mae: 2.2265

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0606 - mae: 2.2177

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0317 - mae: 2.2107

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9701 - mae: 2.1984

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9152 - mae: 2.1895

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9480 - mae: 2.1952

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9989 - mae: 2.2026

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9699 - mae: 2.2018

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9823 - mae: 2.2068

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9481 - mae: 2.2009

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9029 - mae: 2.1945

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8977 - mae: 2.1926

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8953 - mae: 2.1864

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9014 - mae: 2.1891

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8744 - mae: 2.1845

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8631 - mae: 2.1835

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8950 - mae: 2.1878

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9131 - mae: 2.1925

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9234 - mae: 2.1917

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9258 - mae: 2.1929

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.9170 - mae: 2.1907 - val_loss: 6.2087 - val_mae: 1.9466

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 10.6422 - mae: 2.9670

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.8679 - mae: 2.7039

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.7258 - mae: 2.5165

 35/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1468 - mae: 2.3724

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7484 - mae: 2.3089

 59/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.8444 - mae: 2.3066

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5508 - mae: 2.2809

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5270 - mae: 2.3022

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4773 - mae: 2.2952

107/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4134 - mae: 2.2892

119/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0701 - mae: 2.2265

131/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9496 - mae: 2.2176

140/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9310 - mae: 2.2070

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9785 - mae: 2.2158

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0194 - mae: 2.2182

173/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9424 - mae: 2.2117

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9746 - mae: 2.2135

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8162 - mae: 2.1952

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8167 - mae: 2.1854

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9405 - mae: 2.1969

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0276 - mae: 2.2091

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0005 - mae: 2.2077

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9770 - mae: 2.2007

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9821 - mae: 2.2029

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1919 - mae: 2.2215

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1661 - mae: 2.2244

300/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1227 - mae: 2.2216

311/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1161 - mae: 2.2248

324/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1929 - mae: 2.2343

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1363 - mae: 2.2315

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0706 - mae: 2.2164

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0358 - mae: 2.2131

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0149 - mae: 2.2130

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9700 - mae: 2.2051

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9616 - mae: 2.2059

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9517 - mae: 2.2062

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9828 - mae: 2.2128

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0532 - mae: 2.2234

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0334 - mae: 2.2215

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0973 - mae: 2.2318

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1058 - mae: 2.2326

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0667 - mae: 2.2227

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0913 - mae: 2.2208

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0654 - mae: 2.2183

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0363 - mae: 2.2151

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0410 - mae: 2.2178

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 8.0443 - mae: 2.2181 - val_loss: 5.7973 - val_mae: 1.8724

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 23s 45ms/step - loss: 11.2077 - mae: 2.5400

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0798 - mae: 2.3071

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3620 - mae: 2.3514

 35/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2326 - mae: 2.4525

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5471 - mae: 2.3543

 58/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8860 - mae: 2.4181

 70/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4156 - mae: 2.3472

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2550 - mae: 2.3213

 94/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0330 - mae: 2.2849

103/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1545 - mae: 2.3049

114/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9828 - mae: 2.2927

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8211 - mae: 2.2670

132/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8149 - mae: 2.2607

142/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8356 - mae: 2.2592

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0759 - mae: 2.2687

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1543 - mae: 2.2621

172/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1721 - mae: 2.2587

182/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0824 - mae: 2.2449

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0217 - mae: 2.2342

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9679 - mae: 2.2285

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2023 - mae: 2.2404

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0979 - mae: 2.2233

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1698 - mae: 2.2272

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2568 - mae: 2.2410

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2569 - mae: 2.2383

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1722 - mae: 2.2259

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1017 - mae: 2.2206

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1117 - mae: 2.2217

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0250 - mae: 2.2013

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0354 - mae: 2.2041

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9576 - mae: 2.1929

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9369 - mae: 2.1930

329/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0351 - mae: 2.2043

339/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0493 - mae: 2.2075

349/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0285 - mae: 2.2096

359/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9285 - mae: 2.1951

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8599 - mae: 2.1864

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8167 - mae: 2.1821

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7708 - mae: 2.1774

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7766 - mae: 2.1768

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7421 - mae: 2.1695

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7351 - mae: 2.1706

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6924 - mae: 2.1646

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6753 - mae: 2.1642

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6630 - mae: 2.1606

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6423 - mae: 2.1568

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6647 - mae: 2.1579

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6896 - mae: 2.1623

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7493 - mae: 2.1715

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7204 - mae: 2.1698

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7732 - mae: 2.1761

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7404 - mae: 2.1742

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.7059 - mae: 2.1682 - val_loss: 6.5182 - val_mae: 2.0125

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - loss: 3.8361 - mae: 1.6628

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.8741 - mae: 2.0341

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8514 - mae: 2.2336

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8121 - mae: 2.1918

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5965 - mae: 2.1762

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6801 - mae: 2.1789

 62/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4740 - mae: 2.1545

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3049 - mae: 2.1492

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5385 - mae: 2.1707

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4304 - mae: 2.1480

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8022 - mae: 2.1652

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7794 - mae: 2.1805

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6138 - mae: 2.1504

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5441 - mae: 2.1387

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3944 - mae: 2.1235

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4696 - mae: 2.1297

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4490 - mae: 2.1232

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6026 - mae: 2.1553

182/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6117 - mae: 2.1581

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5157 - mae: 2.1482

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5553 - mae: 2.1567

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5530 - mae: 2.1535

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6692 - mae: 2.1731

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7796 - mae: 2.1825

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7411 - mae: 2.1779

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7124 - mae: 2.1779

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7566 - mae: 2.1750

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8546 - mae: 2.1946

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8166 - mae: 2.1905

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7409 - mae: 2.1766

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7578 - mae: 2.1813

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7288 - mae: 2.1858

333/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7495 - mae: 2.1879

346/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8350 - mae: 2.1989

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8100 - mae: 2.1964

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7971 - mae: 2.1954

379/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8400 - mae: 2.2021

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7870 - mae: 2.1946

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7461 - mae: 2.1873

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7541 - mae: 2.1914

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6876 - mae: 2.1815

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7041 - mae: 2.1848

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7435 - mae: 2.1891

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7916 - mae: 2.1953

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7755 - mae: 2.1937

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7425 - mae: 2.1886

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7410 - mae: 2.1852

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7633 - mae: 2.1893

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7589 - mae: 2.1891

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7768 - mae: 2.1903

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.7768 - mae: 2.1903 - val_loss: 5.7242 - val_mae: 1.8656

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - loss: 5.7620 - mae: 1.6463

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8855 - mae: 2.2185

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.8761 - mae: 2.5430

 31/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.0050 - mae: 2.4915

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.6225 - mae: 2.4350

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5824 - mae: 2.4389

 66/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.7429 - mae: 2.4728

 76/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3442 - mae: 2.4167

 86/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2111 - mae: 2.3684

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0370 - mae: 2.3543

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6779 - mae: 2.3089

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4690 - mae: 2.2983

129/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3243 - mae: 2.2776

140/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1800 - mae: 2.2487

148/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2412 - mae: 2.2705

158/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1413 - mae: 2.2513

167/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4276 - mae: 2.2792

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4487 - mae: 2.2849

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5988 - mae: 2.3109

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4899 - mae: 2.2957

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5134 - mae: 2.2996

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5214 - mae: 2.3049

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4548 - mae: 2.2896

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2867 - mae: 2.2649

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1860 - mae: 2.2513

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1519 - mae: 2.2477

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0716 - mae: 2.2325

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1375 - mae: 2.2411

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0907 - mae: 2.2360

324/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0015 - mae: 2.2245

335/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9590 - mae: 2.2219

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8853 - mae: 2.2139

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8400 - mae: 2.2059

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8537 - mae: 2.2086

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9121 - mae: 2.2162

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9052 - mae: 2.2138

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8410 - mae: 2.2084

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8487 - mae: 2.2092

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8372 - mae: 2.2088

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8638 - mae: 2.2125

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9138 - mae: 2.2189

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9004 - mae: 2.2147

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8342 - mae: 2.2053

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8219 - mae: 2.2037

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8160 - mae: 2.1998

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7933 - mae: 2.1958

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7674 - mae: 2.1906

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7450 - mae: 2.1844

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7485 - mae: 2.1855

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.7386 - mae: 2.1850 - val_loss: 5.8504 - val_mae: 1.8940

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 23s 45ms/step - loss: 8.0559 - mae: 2.0898

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1629 - mae: 2.1425

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8894 - mae: 2.3072

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4540 - mae: 2.2560

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0264 - mae: 2.2481

 52/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6813 - mae: 2.2077

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3294 - mae: 2.1603

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2702 - mae: 2.1360

 87/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0238 - mae: 2.0974

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2095 - mae: 2.1278

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.1706 - mae: 2.1046

120/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3040 - mae: 2.1251

131/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.2740 - mae: 2.1041

140/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.1938 - mae: 2.0993

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5682 - mae: 2.1547

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5265 - mae: 2.1561

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4649 - mae: 2.1430

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4834 - mae: 2.1501

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6704 - mae: 2.1804

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7812 - mae: 2.1918

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7657 - mae: 2.1843

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7844 - mae: 2.1859

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7652 - mae: 2.1822

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8302 - mae: 2.1957

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7984 - mae: 2.1930

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8157 - mae: 2.1892

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8236 - mae: 2.1929

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7745 - mae: 2.1842

311/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7215 - mae: 2.1727

321/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6959 - mae: 2.1655

332/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6593 - mae: 2.1635

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6533 - mae: 2.1689

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6616 - mae: 2.1722

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7159 - mae: 2.1752

379/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7091 - mae: 2.1738

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6711 - mae: 2.1688

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6958 - mae: 2.1707

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7565 - mae: 2.1751

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7625 - mae: 2.1759

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6892 - mae: 2.1633

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6761 - mae: 2.1639

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6573 - mae: 2.1607

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6582 - mae: 2.1624

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6650 - mae: 2.1616

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6679 - mae: 2.1610

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6996 - mae: 2.1639

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6626 - mae: 2.1602

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6242 - mae: 2.1557

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 7.5993 - mae: 2.1526 - val_loss: 7.3391 - val_mae: 2.1404

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - loss: 14.0823 - mae: 3.1580

 13/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.7327 - mae: 2.3528

 24/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7986 - mae: 2.2392

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.6651 - mae: 2.1985

 50/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.1954 - mae: 2.2482

 64/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6658 - mae: 2.1829

 76/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6159 - mae: 2.1789

 88/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5931 - mae: 2.1883

101/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6798 - mae: 2.1869

115/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5778 - mae: 2.1775

129/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7744 - mae: 2.1884

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6269 - mae: 2.1720

156/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6572 - mae: 2.1730

167/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6973 - mae: 2.1797

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6600 - mae: 2.1789

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4882 - mae: 2.1498

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5008 - mae: 2.1484

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5546 - mae: 2.1589

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6166 - mae: 2.1550

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5621 - mae: 2.1478

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4494 - mae: 2.1327

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5208 - mae: 2.1466

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4348 - mae: 2.1352

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3517 - mae: 2.1230

293/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3855 - mae: 2.1258

304/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3656 - mae: 2.1212

315/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3427 - mae: 2.1185

326/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3285 - mae: 2.1152

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3063 - mae: 2.1098

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2904 - mae: 2.1101

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3422 - mae: 2.1162

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4166 - mae: 2.1298

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4740 - mae: 2.1364

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5339 - mae: 2.1395

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6363 - mae: 2.1515

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6343 - mae: 2.1506

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6206 - mae: 2.1487

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6705 - mae: 2.1570

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6901 - mae: 2.1546

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7420 - mae: 2.1633

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7794 - mae: 2.1657

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7717 - mae: 2.1670

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7061 - mae: 2.1568

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7412 - mae: 2.1593

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7686 - mae: 2.1660

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7838 - mae: 2.1664

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7266 - mae: 2.1556

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.7138 - mae: 2.1514 - val_loss: 5.7747 - val_mae: 1.8688

Epoch 21: early stopping

Restoring model weights from the end of the best epoch: 11.

In [14]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 3s 360ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step

MAE:  1.8101562310318922

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [15]:
# now let's build a model
from keras.layers import Bidirectional

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(Bidirectional(SimpleRNN(30, return_sequences=True, activation='relu')))
model.add(Bidirectional(SimpleRNN(30)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 14, 60)         │         3,780 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 60)             │         5,460 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            61 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,429 (36.83 KB)

 Trainable params: 9,429 (36.83 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 41:13 5s/step - loss: 85.6599 - mae: 9.1049

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 70.7346 - mae: 7.4888

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 60.1784 - mae: 6.6312

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 55.5993 - mae: 6.2390

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 48.6962 - mae: 5.7978

 29/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 44.0181 - mae: 5.4549

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 39.2819 - mae: 5.0318

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 37.6400 - mae: 4.9190

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 35.3461 - mae: 4.7439

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 32.8367 - mae: 4.5164

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 31.7346 - mae: 4.4218

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 30.3865 - mae: 4.3308

 68/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 29.4035 - mae: 4.2575

 74/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 28.3752 - mae: 4.1900

 80/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 27.3382 - mae: 4.1028

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 26.5045 - mae: 4.0117

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 25.8912 - mae: 3.9584

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 25.4964 - mae: 3.9154

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 25.1169 - mae: 3.8882

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 24.3982 - mae: 3.8216

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 24.2183 - mae: 3.8152

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 23.5323 - mae: 3.7620

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 22.6793 - mae: 3.6703

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 22.3230 - mae: 3.6306

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 21.9381 - mae: 3.5922

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 21.5443 - mae: 3.5666

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 21.1444 - mae: 3.5302

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 20.8404 - mae: 3.5024

159/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 20.5698 - mae: 3.4755

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 20.2836 - mae: 3.4584

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 20.1520 - mae: 3.4517

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 19.8822 - mae: 3.4347

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 19.5546 - mae: 3.4027

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 19.3013 - mae: 3.3852

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 19.2325 - mae: 3.3786

196/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 18.9110 - mae: 3.3467

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 18.4735 - mae: 3.2977

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 18.1913 - mae: 3.2649

213/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 17.9800 - mae: 3.2462

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.9692 - mae: 3.2487

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.7828 - mae: 3.2362

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.5035 - mae: 3.2059

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.3909 - mae: 3.1990

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.2416 - mae: 3.1883

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 17.0392 - mae: 3.1653

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.9506 - mae: 3.1541

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.8071 - mae: 3.1434

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.6501 - mae: 3.1223

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.4803 - mae: 3.1059

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.4322 - mae: 3.1023

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.2422 - mae: 3.0840

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 16.0858 - mae: 3.0686

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 15.9615 - mae: 3.0567

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 15.7943 - mae: 3.0427

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 15.7314 - mae: 3.0362

312/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 15.6783 - mae: 3.0364

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 15.5590 - mae: 3.0254

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 15.3917 - mae: 3.0071

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 15.2683 - mae: 2.9973

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 15.1157 - mae: 2.9812

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 15.0712 - mae: 2.9748

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.9803 - mae: 2.9626

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.8562 - mae: 2.9481

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.8153 - mae: 2.9397

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.7446 - mae: 2.9343

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.5844 - mae: 2.9161

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.4773 - mae: 2.9045

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.3571 - mae: 2.8901

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.2649 - mae: 2.8814

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.1551 - mae: 2.8694

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 14.0538 - mae: 2.8611

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 13.9440 - mae: 2.8486

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 13.8730 - mae: 2.8413

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.7737 - mae: 2.8304

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.6708 - mae: 2.8189

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.5595 - mae: 2.8029

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.4466 - mae: 2.7887

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.3490 - mae: 2.7775

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.2818 - mae: 2.7703

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.1893 - mae: 2.7599

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.1213 - mae: 2.7546

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.0616 - mae: 2.7466

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.0225 - mae: 2.7405

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.0116 - mae: 2.7419

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.9848 - mae: 2.7400

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 13.0130 - mae: 2.7438

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.9886 - mae: 2.7427

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.9221 - mae: 2.7344

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.8871 - mae: 2.7337

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.8928 - mae: 2.7379

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.8480 - mae: 2.7314

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.8146 - mae: 2.7286

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.7686 - mae: 2.7243

522/522 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - loss: 12.7648 - mae: 2.7239 - val_loss: 7.0439 - val_mae: 2.0759

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 10.9860 - mae: 2.9732

  7/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 11.8169 - mae: 2.6619

 12/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 10.0734 - mae: 2.5179

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.8736 - mae: 2.3107

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.6177 - mae: 2.2782

 26/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.7521 - mae: 2.3381

 31/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.4592 - mae: 2.4192

 35/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.4277 - mae: 2.4120

 40/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.2175 - mae: 2.3915

 44/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.0589 - mae: 2.3945

 48/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.9165 - mae: 2.3562

 53/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.6521 - mae: 2.3185

 58/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.4482 - mae: 2.2860

 63/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.5063 - mae: 2.3052

 68/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.2362 - mae: 2.2656

 73/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.0576 - mae: 2.2381

 78/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.4091 - mae: 2.2652

 83/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.4797 - mae: 2.2778

 87/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.4681 - mae: 2.2886

 91/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.3406 - mae: 2.2676

 96/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 8.5334 - mae: 2.2809

101/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.9173 - mae: 2.3277

106/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.9299 - mae: 2.3180

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.8665 - mae: 2.3061

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.7756 - mae: 2.2990

121/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.6534 - mae: 2.2859

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.5732 - mae: 2.2755

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.4884 - mae: 2.2609

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.4214 - mae: 2.2534

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.3754 - mae: 2.2469

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.3312 - mae: 2.2395

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.2973 - mae: 2.2368

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.3090 - mae: 2.2387

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.2031 - mae: 2.2221

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.2477 - mae: 2.2358

171/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.3029 - mae: 2.2461

176/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 8.1754 - mae: 2.2240

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 8.1016 - mae: 2.2132

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0036 - mae: 2.2029

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0032 - mae: 2.2078

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.9585 - mae: 2.2060

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.9506 - mae: 2.2032

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.8921 - mae: 2.1937

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.8782 - mae: 2.1931

221/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.8612 - mae: 2.1915

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7919 - mae: 2.1783

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7663 - mae: 2.1720

237/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7126 - mae: 2.1593

242/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7879 - mae: 2.1699

247/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7942 - mae: 2.1714

252/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.7918 - mae: 2.1702

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7463 - mae: 2.1630

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6788 - mae: 2.1525

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6835 - mae: 2.1533

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6316 - mae: 2.1489

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6568 - mae: 2.1496

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6425 - mae: 2.1494

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6064 - mae: 2.1428

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6155 - mae: 2.1462

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5863 - mae: 2.1422

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5751 - mae: 2.1411

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6044 - mae: 2.1414

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5526 - mae: 2.1344

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5534 - mae: 2.1329

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6009 - mae: 2.1426

329/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5943 - mae: 2.1404

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5821 - mae: 2.1386

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5969 - mae: 2.1426

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5441 - mae: 2.1359

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5129 - mae: 2.1329

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5200 - mae: 2.1355

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5150 - mae: 2.1380

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5046 - mae: 2.1365

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4914 - mae: 2.1357

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5274 - mae: 2.1425

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5527 - mae: 2.1453

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5724 - mae: 2.1499

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5177 - mae: 2.1399

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5464 - mae: 2.1429

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4933 - mae: 2.1334

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5109 - mae: 2.1348

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4899 - mae: 2.1327

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4578 - mae: 2.1289

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4223 - mae: 2.1240

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3858 - mae: 2.1186

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4097 - mae: 2.1234

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4007 - mae: 2.1233

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3552 - mae: 2.1162

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3118 - mae: 2.1057

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3179 - mae: 2.1062

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2926 - mae: 2.1010

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2929 - mae: 2.0976

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3136 - mae: 2.1018

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3102 - mae: 2.1025

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2817 - mae: 2.0997

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2554 - mae: 2.0961

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3260 - mae: 2.1028

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3237 - mae: 2.1041

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2969 - mae: 2.1005

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2786 - mae: 2.0969

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2393 - mae: 2.0906

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2447 - mae: 2.0919

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2560 - mae: 2.0942

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 7.2532 - mae: 2.0934 - val_loss: 6.2763 - val_mae: 1.9559

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 1.1192 - mae: 0.8415

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.2454 - mae: 1.6744

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6325 - mae: 1.9219

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0972 - mae: 1.8335

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3190 - mae: 1.8646

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4083 - mae: 1.8886

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.9717 - mae: 1.8039

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1732 - mae: 1.8192

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0882 - mae: 1.8072

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.9150 - mae: 1.7775

 59/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8008 - mae: 1.7504

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.6741 - mae: 1.7313

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.8994 - mae: 1.7705

 74/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.8827 - mae: 1.7703

 79/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.9440 - mae: 1.7817

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.9897 - mae: 1.7926

 89/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.9230 - mae: 1.7624

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2797 - mae: 1.8199

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4918 - mae: 1.8426

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4851 - mae: 1.8405

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9920 - mae: 1.9125

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1239 - mae: 1.9341

119/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0980 - mae: 1.9333

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1332 - mae: 1.9442

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0225 - mae: 1.9249

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0987 - mae: 1.9271

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0828 - mae: 1.9270

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0266 - mae: 1.9204

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0074 - mae: 1.9207

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0337 - mae: 1.9246

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0888 - mae: 1.9336

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1819 - mae: 1.9491

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.2578 - mae: 1.9576

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3004 - mae: 1.9674

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3845 - mae: 1.9821

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.6454 - mae: 2.0206

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8701 - mae: 2.0605

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9651 - mae: 2.0702

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9463 - mae: 2.0670

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9886 - mae: 2.0744

216/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8992 - mae: 2.0622

222/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.0371 - mae: 2.0859

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9611 - mae: 2.0730

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9874 - mae: 2.0809

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9871 - mae: 2.0840

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9163 - mae: 2.0713

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8537 - mae: 2.0608

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8598 - mae: 2.0626

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8537 - mae: 2.0620

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8083 - mae: 2.0545

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9699 - mae: 2.0724

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.0322 - mae: 2.0809

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9788 - mae: 2.0745

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.0195 - mae: 2.0818

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.0162 - mae: 2.0814

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9766 - mae: 2.0773

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9603 - mae: 2.0762

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9149 - mae: 2.0671

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9581 - mae: 2.0756

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9849 - mae: 2.0786

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0066 - mae: 2.0812

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9554 - mae: 2.0729

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9079 - mae: 2.0668

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8763 - mae: 2.0634

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8944 - mae: 2.0659

335/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8596 - mae: 2.0600

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8394 - mae: 2.0576

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7954 - mae: 2.0472

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7557 - mae: 2.0412

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7750 - mae: 2.0407

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7560 - mae: 2.0370

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7181 - mae: 2.0305

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7490 - mae: 2.0370

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7851 - mae: 2.0431

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7791 - mae: 2.0429

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7611 - mae: 2.0417

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.7705 - mae: 2.0431

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8039 - mae: 2.0481

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8334 - mae: 2.0520

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8007 - mae: 2.0488

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.8546 - mae: 2.0537

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9139 - mae: 2.0624

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9421 - mae: 2.0677

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9063 - mae: 2.0618

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9099 - mae: 2.0617

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9051 - mae: 2.0621

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9365 - mae: 2.0669

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9645 - mae: 2.0705

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9244 - mae: 2.0643

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9609 - mae: 2.0699

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0147 - mae: 2.0772

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9845 - mae: 2.0730

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0150 - mae: 2.0768

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9992 - mae: 2.0762

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0033 - mae: 2.0778

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0267 - mae: 2.0813

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0511 - mae: 2.0826

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0347 - mae: 2.0787

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0637 - mae: 2.0817

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0537 - mae: 2.0817

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0198 - mae: 2.0771

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0647 - mae: 2.0833

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 7.0622 - mae: 2.0828 - val_loss: 7.2385 - val_mae: 2.1199

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 2.0442 - mae: 0.9791

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.4245 - mae: 2.3967

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.5319 - mae: 2.3618

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5185 - mae: 2.2713

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.6950 - mae: 2.3140

 30/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.1501 - mae: 2.2613

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.5144 - mae: 2.1782

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.2341 - mae: 2.1476

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.6765 - mae: 2.1918

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7087 - mae: 2.2023

 59/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7426 - mae: 2.2163

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.9132 - mae: 2.2429

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.6059 - mae: 2.1920

 74/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.5070 - mae: 2.1804

 79/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3755 - mae: 2.1540

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4803 - mae: 2.1607

 89/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4811 - mae: 2.1551

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4724 - mae: 2.1517

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.6050 - mae: 2.1632

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.6930 - mae: 2.1823

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.7480 - mae: 2.1798

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.5590 - mae: 2.1477

119/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4805 - mae: 2.1392

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4179 - mae: 2.1303

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3448 - mae: 2.1155

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.3743 - mae: 2.1328

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.2757 - mae: 2.1223

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.1763 - mae: 2.1043

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.2826 - mae: 2.1153

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.2423 - mae: 2.1155

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.1853 - mae: 2.1078

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.0751 - mae: 2.0901

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.1107 - mae: 2.0935

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.0404 - mae: 2.0817

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9501 - mae: 2.0663

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9948 - mae: 2.0798

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8868 - mae: 2.0607

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8198 - mae: 2.0538

203/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7485 - mae: 2.0396

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7294 - mae: 2.0350

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7082 - mae: 2.0311

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.6320 - mae: 2.0168

226/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.6942 - mae: 2.0262

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6311 - mae: 2.0160

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5857 - mae: 2.0093

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6092 - mae: 2.0151

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5803 - mae: 2.0087

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5501 - mae: 2.0032

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5401 - mae: 1.9983

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5112 - mae: 1.9939

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5154 - mae: 1.9960

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4783 - mae: 1.9905

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4871 - mae: 1.9935

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5404 - mae: 2.0008

289/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6041 - mae: 2.0084

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5902 - mae: 2.0046

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5982 - mae: 2.0015

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5960 - mae: 2.0004

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6597 - mae: 2.0076

315/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6662 - mae: 2.0090

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6678 - mae: 2.0117

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6538 - mae: 2.0101

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.7002 - mae: 2.0181

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6628 - mae: 2.0134

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6981 - mae: 2.0186

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.7397 - mae: 2.0269

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6896 - mae: 2.0189

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6773 - mae: 2.0207

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6341 - mae: 2.0127

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5822 - mae: 2.0014

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6294 - mae: 2.0075

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6442 - mae: 2.0103

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6361 - mae: 2.0077

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6400 - mae: 2.0110

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5997 - mae: 2.0052

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6304 - mae: 2.0099

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6210 - mae: 2.0098

416/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6028 - mae: 2.0068

421/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.6131 - mae: 2.0069

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6061 - mae: 2.0092

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6335 - mae: 2.0143

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6208 - mae: 2.0135

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6076 - mae: 2.0131

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6234 - mae: 2.0164

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6194 - mae: 2.0159

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6077 - mae: 2.0135

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6968 - mae: 2.0217

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7177 - mae: 2.0233

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7095 - mae: 2.0233

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7307 - mae: 2.0251

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7754 - mae: 2.0321

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8167 - mae: 2.0359

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8900 - mae: 2.0455

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8898 - mae: 2.0449

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8958 - mae: 2.0483

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8725 - mae: 2.0439

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9118 - mae: 2.0500

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8843 - mae: 2.0445

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.8776 - mae: 2.0431 - val_loss: 6.2618 - val_mae: 1.9565

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 5.3451 - mae: 1.7159

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.0195 - mae: 1.8550

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4993 - mae: 2.0989

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2934 - mae: 2.0214

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1691 - mae: 1.9781

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5520 - mae: 1.8731

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1085 - mae: 1.9361

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4562 - mae: 1.9593

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2990 - mae: 1.9542

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2560 - mae: 1.9451

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3005 - mae: 1.9385

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1524 - mae: 1.9175

 68/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9082 - mae: 1.8705

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9523 - mae: 1.8866

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9189 - mae: 1.8849

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0175 - mae: 1.9070

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1736 - mae: 1.9161

 90/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2260 - mae: 1.9276

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.1357 - mae: 1.9039

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9846 - mae: 1.8832

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0312 - mae: 1.8891

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0854 - mae: 1.9038

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0160 - mae: 1.8937

119/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0669 - mae: 1.9036

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0337 - mae: 1.8975

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9981 - mae: 1.8903

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0348 - mae: 1.9002

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0257 - mae: 1.9071

139/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9938 - mae: 1.9034

144/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9400 - mae: 1.8973

149/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0643 - mae: 1.9086

154/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0473 - mae: 1.9103

159/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0939 - mae: 1.9208

164/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0340 - mae: 1.9115

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9857 - mae: 1.9020

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9454 - mae: 1.8995

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9344 - mae: 1.8966

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0800 - mae: 1.9176

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1030 - mae: 1.9232

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0625 - mae: 1.9186

200/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0167 - mae: 1.9116

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0108 - mae: 1.9067

211/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0768 - mae: 1.9191

216/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0030 - mae: 1.9067

222/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0067 - mae: 1.9071

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9978 - mae: 1.9070

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0530 - mae: 1.9198

237/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0517 - mae: 1.9228

242/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0912 - mae: 1.9297

247/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1029 - mae: 1.9278

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1764 - mae: 1.9410

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1199 - mae: 1.9330

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0887 - mae: 1.9250

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1128 - mae: 1.9277

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2009 - mae: 1.9441

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1825 - mae: 1.9383

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1618 - mae: 1.9366

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1490 - mae: 1.9331

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1204 - mae: 1.9296

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1199 - mae: 1.9296

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1171 - mae: 1.9296

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1779 - mae: 1.9392

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1942 - mae: 1.9418

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1478 - mae: 1.9341

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1483 - mae: 1.9353

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2566 - mae: 1.9490

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2576 - mae: 1.9490

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2667 - mae: 1.9513

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2876 - mae: 1.9520

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2732 - mae: 1.9512

336/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2680 - mae: 1.9499

341/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3271 - mae: 1.9583

346/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3198 - mae: 1.9572

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3001 - mae: 1.9528

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3404 - mae: 1.9609

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3263 - mae: 1.9584

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3284 - mae: 1.9604

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3489 - mae: 1.9619

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3492 - mae: 1.9611

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3678 - mae: 1.9638

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3519 - mae: 1.9630

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3307 - mae: 1.9600

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3226 - mae: 1.9583

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2909 - mae: 1.9532

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3649 - mae: 1.9604

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3817 - mae: 1.9635

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3615 - mae: 1.9592

419/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3702 - mae: 1.9613

425/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.4083 - mae: 1.9640

431/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4888 - mae: 1.9731

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4951 - mae: 1.9735

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4926 - mae: 1.9731

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5105 - mae: 1.9757

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5131 - mae: 1.9764

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5455 - mae: 1.9811

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5511 - mae: 1.9841

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5665 - mae: 1.9890

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5432 - mae: 1.9840

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5692 - mae: 1.9898

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5865 - mae: 1.9937

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5919 - mae: 1.9955

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5857 - mae: 1.9946

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5732 - mae: 1.9935

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6082 - mae: 1.9994

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5816 - mae: 1.9950

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5988 - mae: 1.9958

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6191 - mae: 2.0001

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6323 - mae: 2.0011

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6251 - mae: 2.0007

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6334 - mae: 2.0014

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 6.6423 - mae: 2.0037 - val_loss: 6.8131 - val_mae: 2.0635

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 46ms/step - loss: 2.8838 - mae: 1.5180

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.9581 - mae: 1.8212

 12/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.2248 - mae: 2.0044

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.6003 - mae: 2.0734

 23/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.1025 - mae: 2.0995

 29/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.1147 - mae: 2.1058

 34/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.2948 - mae: 2.1377

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.0178 - mae: 2.1146

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.7439 - mae: 2.0626

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.1630 - mae: 2.1053

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.0595 - mae: 2.0901

 57/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.2043 - mae: 2.1205

 61/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.0459 - mae: 2.1075

 66/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.8846 - mae: 2.0887

 71/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.8498 - mae: 2.0951

 76/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.6844 - mae: 2.0666

 81/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.5007 - mae: 2.0349

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5981 - mae: 2.0527

 90/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5415 - mae: 2.0421

 95/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5272 - mae: 2.0388

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4855 - mae: 2.0343

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4814 - mae: 2.0304

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3595 - mae: 2.0037

112/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5119 - mae: 2.0208

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4218 - mae: 2.0071

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5125 - mae: 2.0158

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5864 - mae: 2.0171

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5572 - mae: 2.0129

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5050 - mae: 2.0056

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5522 - mae: 2.0164

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5340 - mae: 2.0156

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.5097 - mae: 2.0158

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5992 - mae: 2.0267

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5108 - mae: 2.0142

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4939 - mae: 2.0068

171/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6772 - mae: 2.0230

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.6086 - mae: 2.0128

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5766 - mae: 2.0010

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5980 - mae: 2.0078

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5799 - mae: 2.0044

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5538 - mae: 2.0061

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.6158 - mae: 2.0158

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5445 - mae: 2.0063

216/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5371 - mae: 2.0073

222/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4907 - mae: 2.0011

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5210 - mae: 2.0076

234/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4668 - mae: 1.9990

240/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4825 - mae: 2.0057

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4476 - mae: 1.9985

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4261 - mae: 1.9931

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4119 - mae: 1.9916

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4212 - mae: 1.9948

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4064 - mae: 1.9959

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3662 - mae: 1.9885

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3408 - mae: 1.9872

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3160 - mae: 1.9817

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3617 - mae: 1.9882

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4057 - mae: 1.9869

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4057 - mae: 1.9871

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3829 - mae: 1.9843

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3610 - mae: 1.9795

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3498 - mae: 1.9751

319/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3605 - mae: 1.9761

324/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3724 - mae: 1.9751

329/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3602 - mae: 1.9692

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3529 - mae: 1.9700

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3171 - mae: 1.9622

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.2938 - mae: 1.9592

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.2983 - mae: 1.9612

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.2931 - mae: 1.9593

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3073 - mae: 1.9622

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3185 - mae: 1.9656

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.2967 - mae: 1.9607

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3589 - mae: 1.9700

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3668 - mae: 1.9708

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3584 - mae: 1.9697

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3702 - mae: 1.9708

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3591 - mae: 1.9692

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4264 - mae: 1.9778

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4093 - mae: 1.9753

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4340 - mae: 1.9767

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4603 - mae: 1.9785

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4480 - mae: 1.9765

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4201 - mae: 1.9716

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3991 - mae: 1.9670

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4250 - mae: 1.9680

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4301 - mae: 1.9703

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4342 - mae: 1.9720

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4244 - mae: 1.9717

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4163 - mae: 1.9719

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4421 - mae: 1.9754

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4672 - mae: 1.9773

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4855 - mae: 1.9808

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4750 - mae: 1.9800

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4799 - mae: 1.9828

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5211 - mae: 1.9878

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5445 - mae: 1.9928

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5325 - mae: 1.9916

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5317 - mae: 1.9919

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5152 - mae: 1.9903

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4981 - mae: 1.9880

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 6.4981 - mae: 1.9880 - val_loss: 6.6282 - val_mae: 2.0278

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 1.4856 - mae: 1.0395

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7267 - mae: 2.2140

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.6247 - mae: 2.2489

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.6822 - mae: 2.2181

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.9170 - mae: 2.3053

 30/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5833 - mae: 2.3710

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.4111 - mae: 2.3627

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.0626 - mae: 2.3039

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.9436 - mae: 2.2780

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.8218 - mae: 2.2538

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.4336 - mae: 2.1925

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.3763 - mae: 2.1448

 68/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.6239 - mae: 2.1564

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4418 - mae: 2.1207

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3838 - mae: 2.1077

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4352 - mae: 2.1170

 88/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4504 - mae: 2.1282

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3318 - mae: 2.1065

 97/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3140 - mae: 2.1091

102/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.1685 - mae: 2.0882

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.0606 - mae: 2.0685

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9883 - mae: 2.0624

118/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9796 - mae: 2.0618

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9391 - mae: 2.0630

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8603 - mae: 2.0499

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9014 - mae: 2.0638

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8736 - mae: 2.0597

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9106 - mae: 2.0633

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8442 - mae: 2.0486

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9602 - mae: 2.0642

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9249 - mae: 2.0540

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8280 - mae: 2.0390

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7815 - mae: 2.0383

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8175 - mae: 2.0369

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7607 - mae: 2.0303

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7429 - mae: 2.0249

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8800 - mae: 2.0414

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8252 - mae: 2.0321

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7341 - mae: 2.0180

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8500 - mae: 2.0368

212/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8025 - mae: 2.0320

217/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8805 - mae: 2.0383

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9037 - mae: 2.0420

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8816 - mae: 2.0407

233/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8629 - mae: 2.0366

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8942 - mae: 2.0414

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8665 - mae: 2.0398

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8789 - mae: 2.0402

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9004 - mae: 2.0370

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8288 - mae: 2.0234

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8483 - mae: 2.0279

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8953 - mae: 2.0354

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8485 - mae: 2.0251

277/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7999 - mae: 2.0185

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8051 - mae: 2.0202

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8194 - mae: 2.0237

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8019 - mae: 2.0222

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7453 - mae: 2.0136

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7419 - mae: 2.0129

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7092 - mae: 2.0096

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6785 - mae: 2.0038

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6586 - mae: 1.9996

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7244 - mae: 2.0092

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7282 - mae: 2.0131

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6778 - mae: 2.0045

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6778 - mae: 2.0038

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6844 - mae: 2.0061

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6531 - mae: 2.0027

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6096 - mae: 1.9962

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5914 - mae: 1.9946

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5807 - mae: 1.9932

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5562 - mae: 1.9889

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5556 - mae: 1.9884

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5511 - mae: 1.9822

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5423 - mae: 1.9815

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5330 - mae: 1.9802

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5046 - mae: 1.9779

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5176 - mae: 1.9795

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4754 - mae: 1.9712

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4652 - mae: 1.9712

420/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5562 - mae: 1.9854

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5727 - mae: 1.9872

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5855 - mae: 1.9912

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5915 - mae: 1.9927

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5887 - mae: 1.9936

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5672 - mae: 1.9911

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5533 - mae: 1.9885

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5909 - mae: 1.9937

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5959 - mae: 1.9956

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5960 - mae: 1.9978

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5956 - mae: 1.9989

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6120 - mae: 2.0031

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6300 - mae: 2.0041

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6050 - mae: 2.0010

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6104 - mae: 2.0022

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6533 - mae: 2.0093

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6333 - mae: 2.0062

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6492 - mae: 2.0101

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6403 - mae: 2.0072

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6285 - mae: 2.0059

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.6271 - mae: 2.0058 - val_loss: 5.7294 - val_mae: 1.8833

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - loss: 13.9059 - mae: 2.8636

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.7149 - mae: 2.0831

 12/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5793 - mae: 1.8482

 18/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2105 - mae: 1.7489

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3038 - mae: 1.7387

 30/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3586 - mae: 1.7445

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6649 - mae: 1.8223

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3828 - mae: 1.7806

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3613 - mae: 1.7880

 52/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2653 - mae: 1.7837

 57/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2299 - mae: 1.7763

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2075 - mae: 1.7809

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.1614 - mae: 1.7678

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3629 - mae: 1.8143

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.5940 - mae: 1.8496

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6042 - mae: 1.8458

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5755 - mae: 1.8449

 90/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5382 - mae: 1.8355

 95/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4722 - mae: 1.8268

100/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6018 - mae: 1.8553

105/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6572 - mae: 1.8669

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6197 - mae: 1.8667

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6964 - mae: 1.8817

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8267 - mae: 1.9108

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8530 - mae: 1.9139

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7834 - mae: 1.9025

137/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9541 - mae: 1.9224

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8920 - mae: 1.9068

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0050 - mae: 1.9212

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0203 - mae: 1.9271

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0220 - mae: 1.9290

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9805 - mae: 1.9222

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0113 - mae: 1.9271

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0498 - mae: 1.9337

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.9877 - mae: 1.9202

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0803 - mae: 1.9320

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1140 - mae: 1.9413

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1072 - mae: 1.9371

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0757 - mae: 1.9313

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1682 - mae: 1.9410

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1301 - mae: 1.9338

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1302 - mae: 1.9285

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1785 - mae: 1.9344

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1538 - mae: 1.9319

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1039 - mae: 1.9249

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1615 - mae: 1.9364

233/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2538 - mae: 1.9526

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2021 - mae: 1.9437

243/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1941 - mae: 1.9427

248/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2005 - mae: 1.9426

252/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1711 - mae: 1.9387

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2542 - mae: 1.9516

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2639 - mae: 1.9489

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3098 - mae: 1.9556

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2954 - mae: 1.9546

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2758 - mae: 1.9509

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3711 - mae: 1.9631

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4123 - mae: 1.9719

289/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3924 - mae: 1.9679

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3693 - mae: 1.9635

298/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3386 - mae: 1.9586

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3362 - mae: 1.9591

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3433 - mae: 1.9630

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.3946 - mae: 1.9678

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4361 - mae: 1.9732

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4211 - mae: 1.9700

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.5222 - mae: 1.9796

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.5408 - mae: 1.9840

338/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.5193 - mae: 1.9830

343/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.4938 - mae: 1.9808

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4615 - mae: 1.9784

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4717 - mae: 1.9795

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4261 - mae: 1.9712

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4569 - mae: 1.9766

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4345 - mae: 1.9743

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4439 - mae: 1.9783

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4555 - mae: 1.9775

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4181 - mae: 1.9726

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4310 - mae: 1.9760

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4320 - mae: 1.9759

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4072 - mae: 1.9728

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3943 - mae: 1.9712

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.4003 - mae: 1.9744

420/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3982 - mae: 1.9744

425/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3637 - mae: 1.9693

430/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.3774 - mae: 1.9708

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3599 - mae: 1.9688

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3366 - mae: 1.9663

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3638 - mae: 1.9697

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3497 - mae: 1.9687

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3415 - mae: 1.9666

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3354 - mae: 1.9668

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3480 - mae: 1.9643

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3340 - mae: 1.9624

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3613 - mae: 1.9664

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3382 - mae: 1.9640

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3080 - mae: 1.9602

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3048 - mae: 1.9604

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3388 - mae: 1.9646

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3700 - mae: 1.9673

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3854 - mae: 1.9697

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3563 - mae: 1.9662

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3871 - mae: 1.9704

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3877 - mae: 1.9717

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 6.3885 - mae: 1.9720 - val_loss: 5.8578 - val_mae: 1.8957

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 0.6035 - mae: 0.5765

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 4.9132 - mae: 1.7784

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 4.6659 - mae: 1.6811

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.2700 - mae: 1.6255

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0973 - mae: 1.7505

 29/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.1864 - mae: 1.7898

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3245 - mae: 1.8098

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4474 - mae: 1.8433

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2270 - mae: 1.7969

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.0994 - mae: 1.7523

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4005 - mae: 1.8106

 59/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7478 - mae: 1.8784

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7264 - mae: 1.8682

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7372 - mae: 1.8729

 74/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6429 - mae: 1.8617

 79/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4812 - mae: 1.8353

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4515 - mae: 1.8370

 90/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4627 - mae: 1.8358

 96/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4661 - mae: 1.8424

101/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6069 - mae: 1.8584

106/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5470 - mae: 1.8497

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5417 - mae: 1.8475

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8169 - mae: 1.8668

121/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8001 - mae: 1.8777

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0026 - mae: 1.9000

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9575 - mae: 1.8950

137/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0732 - mae: 1.9175

143/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1969 - mae: 1.9301

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3661 - mae: 1.9541

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3997 - mae: 1.9612

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3346 - mae: 1.9553

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4425 - mae: 1.9789

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4727 - mae: 1.9784

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4631 - mae: 1.9814

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3640 - mae: 1.9627

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4017 - mae: 1.9650

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.2942 - mae: 1.9445

203/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3044 - mae: 1.9482

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3487 - mae: 1.9517

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3331 - mae: 1.9522

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3609 - mae: 1.9597

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3503 - mae: 1.9568

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3537 - mae: 1.9618

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3616 - mae: 1.9636

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3669 - mae: 1.9630

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3485 - mae: 1.9598

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3945 - mae: 1.9658

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.3259 - mae: 1.9553

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4742 - mae: 1.9809

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4533 - mae: 1.9759

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4303 - mae: 1.9715

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4130 - mae: 1.9714

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4648 - mae: 1.9776

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4384 - mae: 1.9722

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4195 - mae: 1.9686

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4313 - mae: 1.9661

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4741 - mae: 1.9716

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4317 - mae: 1.9669

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4500 - mae: 1.9736

315/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4284 - mae: 1.9700

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4308 - mae: 1.9718

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4010 - mae: 1.9678

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3583 - mae: 1.9594

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3398 - mae: 1.9541

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3405 - mae: 1.9549

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3434 - mae: 1.9505

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3779 - mae: 1.9584

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4371 - mae: 1.9673

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4432 - mae: 1.9678

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3952 - mae: 1.9607

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4145 - mae: 1.9596

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4132 - mae: 1.9580

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3800 - mae: 1.9535

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4106 - mae: 1.9568

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3978 - mae: 1.9544

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4185 - mae: 1.9581

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4160 - mae: 1.9582

417/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4117 - mae: 1.9577

422/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.3896 - mae: 1.9561

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4238 - mae: 1.9589

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4353 - mae: 1.9607

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4292 - mae: 1.9617

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4131 - mae: 1.9611

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4233 - mae: 1.9641

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3981 - mae: 1.9599

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3882 - mae: 1.9587

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3672 - mae: 1.9572

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3481 - mae: 1.9537

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3504 - mae: 1.9568

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3351 - mae: 1.9546

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3102 - mae: 1.9519

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3196 - mae: 1.9547

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3258 - mae: 1.9560

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3035 - mae: 1.9537

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3113 - mae: 1.9567

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3088 - mae: 1.9570

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.2847 - mae: 1.9546

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.2934 - mae: 1.9563

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.3035 - mae: 1.9580 - val_loss: 5.8642 - val_mae: 1.8985

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 7.3561 - mae: 2.4172

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4802 - mae: 2.2119

 12/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.5045 - mae: 2.3117

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.8099 - mae: 2.1973

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.2629 - mae: 2.2132

 26/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.4513 - mae: 2.2377

 31/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.4538 - mae: 2.2237

 35/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.3423 - mae: 2.2025

 39/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.7085 - mae: 2.2452

 43/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.5310 - mae: 2.2278

 47/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.2871 - mae: 2.1835

 51/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.9901 - mae: 2.1269

 55/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.9924 - mae: 2.1196

 60/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.7740 - mae: 2.0734

 65/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.7467 - mae: 2.0574

 70/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5122 - mae: 2.0107

 75/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.3804 - mae: 1.9921

 79/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4316 - mae: 1.9885

 84/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2912 - mae: 1.9620

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2881 - mae: 1.9608

 94/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2466 - mae: 1.9514

 99/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.3402 - mae: 1.9659

104/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2462 - mae: 1.9475

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2667 - mae: 1.9571

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3902 - mae: 1.9607

118/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3625 - mae: 1.9577

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3465 - mae: 1.9619

128/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2962 - mae: 1.9615

133/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1997 - mae: 1.9418

137/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4945 - mae: 1.9719

142/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4663 - mae: 1.9605

147/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4551 - mae: 1.9559

152/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4045 - mae: 1.9523

157/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4930 - mae: 1.9654

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4506 - mae: 1.9576

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3752 - mae: 1.9451

170/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.3219 - mae: 1.9359

175/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2899 - mae: 1.9305

180/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1911 - mae: 1.9143

184/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2171 - mae: 1.9153

188/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1623 - mae: 1.9026

193/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0950 - mae: 1.8912

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1269 - mae: 1.8971

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1147 - mae: 1.8938

206/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1239 - mae: 1.8949

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0920 - mae: 1.8896

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0270 - mae: 1.8775

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0439 - mae: 1.8843

224/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1058 - mae: 1.8896

229/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1612 - mae: 1.9045

234/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1503 - mae: 1.9068

239/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1322 - mae: 1.9056

244/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1909 - mae: 1.9109

249/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2048 - mae: 1.9135

254/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2091 - mae: 1.9107

259/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2546 - mae: 1.9189

264/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.3028 - mae: 1.9289

269/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2489 - mae: 1.9191

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2065 - mae: 1.9123

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2045 - mae: 1.9128

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1839 - mae: 1.9117

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1873 - mae: 1.9126

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1672 - mae: 1.9104

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1912 - mae: 1.9104

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2055 - mae: 1.9121

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2953 - mae: 1.9280

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3428 - mae: 1.9350

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3382 - mae: 1.9344

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3926 - mae: 1.9437

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3681 - mae: 1.9396

332/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.4111 - mae: 1.9486

336/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3850 - mae: 1.9422

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3625 - mae: 1.9381

344/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3415 - mae: 1.9367

348/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3543 - mae: 1.9407

353/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3795 - mae: 1.9445

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3453 - mae: 1.9404

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3499 - mae: 1.9424

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3641 - mae: 1.9473

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3602 - mae: 1.9491

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3946 - mae: 1.9551

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3634 - mae: 1.9501

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3285 - mae: 1.9449

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3252 - mae: 1.9468

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3178 - mae: 1.9443

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3311 - mae: 1.9483

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3331 - mae: 1.9493

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2924 - mae: 1.9433

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3137 - mae: 1.9471

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3363 - mae: 1.9501

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3759 - mae: 1.9543

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3555 - mae: 1.9517

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3522 - mae: 1.9527

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3574 - mae: 1.9560

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3581 - mae: 1.9560

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3225 - mae: 1.9501

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3102 - mae: 1.9486

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3282 - mae: 1.9509

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3088 - mae: 1.9478

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3039 - mae: 1.9460

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3105 - mae: 1.9470

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2959 - mae: 1.9450

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2971 - mae: 1.9459

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2822 - mae: 1.9445

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2662 - mae: 1.9413

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2829 - mae: 1.9420

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2830 - mae: 1.9435

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2684 - mae: 1.9414

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2566 - mae: 1.9401

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2424 - mae: 1.9380

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 6.2418 - mae: 1.9381 - val_loss: 6.1013 - val_mae: 1.9541

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - loss: 3.8336 - mae: 1.6434

  5/522 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 5.6250 - mae: 1.8688

  9/522 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 5.4121 - mae: 1.8398

 14/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.4769 - mae: 1.7602

 18/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.2608 - mae: 1.7577

 23/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.5325 - mae: 1.8090

 27/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8225 - mae: 1.8090

 32/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.0396 - mae: 1.8697

 37/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.1821 - mae: 1.8883

 42/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0851 - mae: 1.8998

 47/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2015 - mae: 1.9251

 52/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2806 - mae: 1.9401

 57/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1528 - mae: 1.9241

 62/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0149 - mae: 1.9070

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0177 - mae: 1.9253

 72/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.9469 - mae: 1.9185

 78/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.9905 - mae: 1.9204

 83/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.8743 - mae: 1.9054

 88/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0343 - mae: 1.9240

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.9909 - mae: 1.9279

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.7649 - mae: 1.8812

102/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.7038 - mae: 1.8712

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.7146 - mae: 1.8801

112/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.7684 - mae: 1.8844

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.7299 - mae: 1.8797

120/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0922 - mae: 1.9213

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1023 - mae: 1.9298

128/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0918 - mae: 1.9277

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1445 - mae: 1.9352

137/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1809 - mae: 1.9448

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1983 - mae: 1.9545

145/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2363 - mae: 1.9591

150/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2410 - mae: 1.9606

155/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2549 - mae: 1.9588

160/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1788 - mae: 1.9433

164/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1515 - mae: 1.9397

169/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0840 - mae: 1.9308

174/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1345 - mae: 1.9365

179/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0876 - mae: 1.9221

184/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1833 - mae: 1.9365

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1259 - mae: 1.9290

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2194 - mae: 1.9333

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1411 - mae: 1.9194

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1165 - mae: 1.9153

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0772 - mae: 1.9098

213/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0899 - mae: 1.9098

218/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1855 - mae: 1.9272

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1959 - mae: 1.9282

229/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2078 - mae: 1.9277

235/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2169 - mae: 1.9333

240/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2439 - mae: 1.9385

245/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2131 - mae: 1.9337

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1502 - mae: 1.9198

255/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1734 - mae: 1.9242

261/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1479 - mae: 1.9201

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0643 - mae: 1.9048

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0714 - mae: 1.9080

277/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1089 - mae: 1.9123

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1329 - mae: 1.9139

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1582 - mae: 1.9149

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1829 - mae: 1.9178

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2370 - mae: 1.9256

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2206 - mae: 1.9268

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2193 - mae: 1.9270

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1804 - mae: 1.9206

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2438 - mae: 1.9265

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2695 - mae: 1.9324

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2648 - mae: 1.9316

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2671 - mae: 1.9324

335/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3135 - mae: 1.9392

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3394 - mae: 1.9465

344/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3415 - mae: 1.9487

349/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.3357 - mae: 1.9477

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3238 - mae: 1.9464

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3289 - mae: 1.9475

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3236 - mae: 1.9494

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3630 - mae: 1.9540

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3769 - mae: 1.9578

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3419 - mae: 1.9501

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.3193 - mae: 1.9466

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2755 - mae: 1.9395

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2548 - mae: 1.9365

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2515 - mae: 1.9376

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2563 - mae: 1.9362

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2611 - mae: 1.9369

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2263 - mae: 1.9300

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.2077 - mae: 1.9275

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1935 - mae: 1.9255

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1635 - mae: 1.9206

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1453 - mae: 1.9179

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1815 - mae: 1.9221

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1627 - mae: 1.9186

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1706 - mae: 1.9209

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1420 - mae: 1.9156

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1546 - mae: 1.9184

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1568 - mae: 1.9203

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1437 - mae: 1.9195

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1517 - mae: 1.9209

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1171 - mae: 1.9149

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1162 - mae: 1.9166

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1087 - mae: 1.9171

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0978 - mae: 1.9161

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0939 - mae: 1.9159

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0927 - mae: 1.9167

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0839 - mae: 1.9154

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1147 - mae: 1.9198

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1374 - mae: 1.9246

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1275 - mae: 1.9230

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 6.1275 - mae: 1.9230 - val_loss: 6.2301 - val_mae: 1.9557

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 11.5422 - mae: 2.1648

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 10.3614 - mae: 2.3831

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 11.9702 - mae: 2.5304

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.7916 - mae: 2.3323

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.1299 - mae: 2.2331

 26/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.0033 - mae: 2.2367

 32/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.1698 - mae: 2.1305

 37/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.5048 - mae: 2.0173

 43/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.4516 - mae: 2.0311

 48/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.5311 - mae: 2.0639

 53/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.1956 - mae: 2.0129

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.1832 - mae: 2.0297

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8340 - mae: 1.9686

 68/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.7789 - mae: 1.9721

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5404 - mae: 1.9379

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3885 - mae: 1.9094

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2549 - mae: 1.8969

 88/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2961 - mae: 1.9129

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3391 - mae: 1.9138

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2346 - mae: 1.8993

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2187 - mae: 1.8909

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4567 - mae: 1.9264

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6332 - mae: 1.9548

118/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6117 - mae: 1.9508

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6579 - mae: 1.9519

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6421 - mae: 1.9564

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5465 - mae: 1.9479

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5368 - mae: 1.9476

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4403 - mae: 1.9358

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4190 - mae: 1.9387

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4418 - mae: 1.9429

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3993 - mae: 1.9340

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3961 - mae: 1.9383

165/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3270 - mae: 1.9273

169/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3188 - mae: 1.9292

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3198 - mae: 1.9277

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3554 - mae: 1.9354

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4164 - mae: 1.9498

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4482 - mae: 1.9484

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4089 - mae: 1.9442

196/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4018 - mae: 1.9491

201/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3632 - mae: 1.9452

206/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3669 - mae: 1.9477

211/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3003 - mae: 1.9386

216/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2715 - mae: 1.9340

221/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2600 - mae: 1.9349

226/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2513 - mae: 1.9341

231/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2080 - mae: 1.9305

235/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1751 - mae: 1.9253

240/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1929 - mae: 1.9199

245/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1510 - mae: 1.9150

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1277 - mae: 1.9139

255/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1289 - mae: 1.9152

260/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1525 - mae: 1.9195

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1142 - mae: 1.9141

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1126 - mae: 1.9155

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1588 - mae: 1.9187

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1666 - mae: 1.9230

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1629 - mae: 1.9250

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1160 - mae: 1.9184

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1130 - mae: 1.9201

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0802 - mae: 1.9156

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1278 - mae: 1.9238

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1256 - mae: 1.9253

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1486 - mae: 1.9302

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1256 - mae: 1.9261

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1052 - mae: 1.9235

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0822 - mae: 1.9195

336/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0816 - mae: 1.9174

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0632 - mae: 1.9151

345/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0694 - mae: 1.9183

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.0251 - mae: 1.9112

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0247 - mae: 1.9132

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0410 - mae: 1.9152

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0226 - mae: 1.9153

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1051 - mae: 1.9228

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0937 - mae: 1.9196

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1184 - mae: 1.9265

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0940 - mae: 1.9210

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1335 - mae: 1.9254

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0969 - mae: 1.9186

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0957 - mae: 1.9174

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0878 - mae: 1.9168

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1134 - mae: 1.9209

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0958 - mae: 1.9194

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1316 - mae: 1.9236

420/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1218 - mae: 1.9221

425/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1069 - mae: 1.9200

430/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0858 - mae: 1.9170

435/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1411 - mae: 1.9248

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1468 - mae: 1.9264

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1325 - mae: 1.9251

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1146 - mae: 1.9224

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1062 - mae: 1.9205

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1091 - mae: 1.9219

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1140 - mae: 1.9226

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1169 - mae: 1.9241

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1389 - mae: 1.9294

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1187 - mae: 1.9258

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1649 - mae: 1.9321

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1589 - mae: 1.9310

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1549 - mae: 1.9314

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1411 - mae: 1.9291

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1348 - mae: 1.9290

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1315 - mae: 1.9268

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1231 - mae: 1.9255

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1288 - mae: 1.9252

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1158 - mae: 1.9216

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 6.1158 - mae: 1.9216 - val_loss: 5.7217 - val_mae: 1.8772

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 61ms/step - loss: 3.8625 - mae: 1.8306

  5/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.1735 - mae: 1.6214

 10/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 3.6931 - mae: 1.5144

 14/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.9498 - mae: 1.7537

 18/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.0420 - mae: 1.7696

 23/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.9877 - mae: 1.7635

 28/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 5.0899 - mae: 1.7970

 33/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 5.2101 - mae: 1.8330

 37/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.3911 - mae: 1.8443

 42/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.5340 - mae: 1.8811

 47/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.5223 - mae: 1.8688

 52/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1703 - mae: 1.9405

 57/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0424 - mae: 1.9195

 62/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.8288 - mae: 1.8942

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.7140 - mae: 1.8694

 72/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.6084 - mae: 1.8514

 77/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.6719 - mae: 1.8662

 82/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.6955 - mae: 1.8719

 87/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.9431 - mae: 1.9193

 92/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.8648 - mae: 1.9103

 96/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1271 - mae: 1.9422

100/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0983 - mae: 1.9457

105/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1544 - mae: 1.9554

109/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1421 - mae: 1.9423

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0762 - mae: 1.9281

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1805 - mae: 1.9430

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0333 - mae: 1.9155

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.9959 - mae: 1.9119

130/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0170 - mae: 1.9212

134/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0728 - mae: 1.9347

138/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0428 - mae: 1.9254

142/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0377 - mae: 1.9248

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.9607 - mae: 1.9126

150/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.9413 - mae: 1.9140

155/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.9323 - mae: 1.9136

159/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.8771 - mae: 1.9043

163/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.9839 - mae: 1.9127

167/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 6.0595 - mae: 1.9209

172/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1449 - mae: 1.9304

177/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0875 - mae: 1.9206

182/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0000 - mae: 1.9011

187/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0988 - mae: 1.9123

192/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1004 - mae: 1.9151

196/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0683 - mae: 1.9088

201/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0632 - mae: 1.9065

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0473 - mae: 1.9056

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0420 - mae: 1.9087

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0611 - mae: 1.9138

218/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0209 - mae: 1.9084

222/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0461 - mae: 1.9110

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1271 - mae: 1.9277

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1190 - mae: 1.9283

237/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1279 - mae: 1.9272

242/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1748 - mae: 1.9377

247/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2023 - mae: 1.9432

253/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2453 - mae: 1.9533

258/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.2057 - mae: 1.9486

263/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1993 - mae: 1.9444

268/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1854 - mae: 1.9443

273/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.1371 - mae: 1.9363

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1132 - mae: 1.9331

283/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1432 - mae: 1.9394

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1096 - mae: 1.9336

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0649 - mae: 1.9264

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0485 - mae: 1.9235

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0697 - mae: 1.9252

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1053 - mae: 1.9270

312/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1733 - mae: 1.9365

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2298 - mae: 1.9460

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2436 - mae: 1.9486

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2274 - mae: 1.9483

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1908 - mae: 1.9428

335/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2393 - mae: 1.9496

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.2144 - mae: 1.9462

345/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1931 - mae: 1.9419

349/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1754 - mae: 1.9389

353/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.1555 - mae: 1.9365

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1843 - mae: 1.9404

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1621 - mae: 1.9372

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1448 - mae: 1.9345

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1557 - mae: 1.9391

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1625 - mae: 1.9416

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1507 - mae: 1.9411

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1612 - mae: 1.9410

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1599 - mae: 1.9413

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1412 - mae: 1.9390

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1272 - mae: 1.9362

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1241 - mae: 1.9359

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.1101 - mae: 1.9334

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0907 - mae: 1.9316

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0631 - mae: 1.9286

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0707 - mae: 1.9300

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0502 - mae: 1.9267

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0556 - mae: 1.9265

438/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0758 - mae: 1.9286

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0656 - mae: 1.9285

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0617 - mae: 1.9280

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0418 - mae: 1.9253

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0337 - mae: 1.9261

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0468 - mae: 1.9284

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0784 - mae: 1.9319

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0878 - mae: 1.9321

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0675 - mae: 1.9275

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0658 - mae: 1.9297

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0329 - mae: 1.9230

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0111 - mae: 1.9205

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0011 - mae: 1.9200

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0209 - mae: 1.9208

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0019 - mae: 1.9182

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9928 - mae: 1.9169

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9823 - mae: 1.9160

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 5.9850 - mae: 1.9167 - val_loss: 5.7250 - val_mae: 1.8749

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 5.9987 - mae: 2.1916

  5/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.3515 - mae: 1.6877

 10/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 3.9912 - mae: 1.5924

 15/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.5429 - mae: 1.6878

 20/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.3881 - mae: 1.6203

 25/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.8732 - mae: 1.7150

 29/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.1099 - mae: 1.7444

 34/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4871 - mae: 1.7859

 39/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4036 - mae: 1.7759

 44/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4955 - mae: 1.7926

 50/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4282 - mae: 1.8144

 55/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4447 - mae: 1.8271

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5482 - mae: 1.8540

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5330 - mae: 1.8542

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4646 - mae: 1.8603

 79/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4962 - mae: 1.8528

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5797 - mae: 1.8527

 89/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4776 - mae: 1.8355

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7715 - mae: 1.8727

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8021 - mae: 1.8733

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8278 - mae: 1.8773

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7424 - mae: 1.8657

112/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9840 - mae: 1.8919

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9145 - mae: 1.8812

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9082 - mae: 1.8791

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9002 - mae: 1.8848

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8470 - mae: 1.8771

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.8554 - mae: 1.8795

140/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7839 - mae: 1.8695

144/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9065 - mae: 1.8856

148/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9224 - mae: 1.8879

153/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0211 - mae: 1.8954

158/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2107 - mae: 1.9091

162/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.1301 - mae: 1.8907

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0985 - mae: 1.8868

171/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0930 - mae: 1.8855

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0080 - mae: 1.8729

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0213 - mae: 1.8752

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9609 - mae: 1.8670

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9687 - mae: 1.8672

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9416 - mae: 1.8655

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9563 - mae: 1.8712

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9937 - mae: 1.8753

206/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9342 - mae: 1.8633

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9291 - mae: 1.8628

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9089 - mae: 1.8627

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9389 - mae: 1.8672

225/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0241 - mae: 1.8787

230/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9524 - mae: 1.8643

234/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0293 - mae: 1.8791

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0030 - mae: 1.8753

242/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0136 - mae: 1.8787

247/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9947 - mae: 1.8751

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9623 - mae: 1.8688

254/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9855 - mae: 1.8742

258/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9705 - mae: 1.8735

262/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0194 - mae: 1.8806

267/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.9898 - mae: 1.8763

271/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.0104 - mae: 1.8810

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9805 - mae: 1.8777

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9800 - mae: 1.8789

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9723 - mae: 1.8816

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9867 - mae: 1.8832

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0214 - mae: 1.8884

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0300 - mae: 1.8911

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9996 - mae: 1.8866

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9979 - mae: 1.8874

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9835 - mae: 1.8842

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9812 - mae: 1.8830

317/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9892 - mae: 1.8808

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9792 - mae: 1.8813

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9871 - mae: 1.8803

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9918 - mae: 1.8821

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 5.9836 - mae: 1.8809

338/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0381 - mae: 1.8880

343/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0506 - mae: 1.8943

346/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0749 - mae: 1.8985

350/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0722 - mae: 1.8992

354/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0416 - mae: 1.8946

358/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.0312 - mae: 1.8942

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0248 - mae: 1.8956

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0198 - mae: 1.8972

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0472 - mae: 1.9040

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0557 - mae: 1.9043

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0492 - mae: 1.9042

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0487 - mae: 1.9043

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0397 - mae: 1.9040

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0290 - mae: 1.9023

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0046 - mae: 1.8982

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0066 - mae: 1.8983

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9817 - mae: 1.8951

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 6.0015 - mae: 1.8975

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9745 - mae: 1.8938

422/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9631 - mae: 1.8904

426/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9597 - mae: 1.8912

431/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9896 - mae: 1.8972

436/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9754 - mae: 1.8959

441/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.9404 - mae: 1.8888

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9347 - mae: 1.8890

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9646 - mae: 1.8947

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9861 - mae: 1.8973

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9749 - mae: 1.8959

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9689 - mae: 1.8966

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9548 - mae: 1.8935

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9458 - mae: 1.8917

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9574 - mae: 1.8936

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9559 - mae: 1.8933

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9355 - mae: 1.8907

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9472 - mae: 1.8926

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9466 - mae: 1.8929

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9700 - mae: 1.8964

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9635 - mae: 1.8957

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9475 - mae: 1.8929

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9306 - mae: 1.8892

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9244 - mae: 1.8876

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9150 - mae: 1.8861

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 5.9189 - mae: 1.8866 - val_loss: 6.3073 - val_mae: 1.9761

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 7.3224 - mae: 2.6708

  6/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 5.5166 - mae: 1.8628

 10/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.8400 - mae: 1.7675

 14/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.1128 - mae: 1.8163

 19/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.9253 - mae: 1.7806

 23/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8868 - mae: 1.8970

 28/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.1585 - mae: 1.9537

 33/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.1372 - mae: 1.9379

 37/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.1500 - mae: 1.9220

 40/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8233 - mae: 1.8448

 44/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8661 - mae: 1.8356

 49/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.7776 - mae: 1.8307

 54/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8545 - mae: 1.8403

 58/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8909 - mae: 1.8319

 62/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.7484 - mae: 1.8158

 66/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6288 - mae: 1.7994

 71/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.6253 - mae: 1.8088

 75/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.6109 - mae: 1.8132

 80/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.5219 - mae: 1.7982

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.6041 - mae: 1.8214

 90/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.5447 - mae: 1.8108

 95/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.5000 - mae: 1.8066

100/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.4266 - mae: 1.7920

105/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.4467 - mae: 1.8075

109/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.4313 - mae: 1.8111

114/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.3539 - mae: 1.8027

119/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.3536 - mae: 1.8043

124/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.4293 - mae: 1.8224

128/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.3796 - mae: 1.8172

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.3421 - mae: 1.8090

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.3487 - mae: 1.8113

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.4324 - mae: 1.8254

145/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5582 - mae: 1.8462

149/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5489 - mae: 1.8436

153/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.6009 - mae: 1.8580

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5617 - mae: 1.8499

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5325 - mae: 1.8441

165/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5463 - mae: 1.8442

169/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5255 - mae: 1.8437

174/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5352 - mae: 1.8437

178/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5239 - mae: 1.8406

182/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.5282 - mae: 1.8439

187/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.6462 - mae: 1.8570

191/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.6760 - mae: 1.8576

195/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7528 - mae: 1.8709

198/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8205 - mae: 1.8815

202/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7595 - mae: 1.8712

206/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7354 - mae: 1.8669

210/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7540 - mae: 1.8745

214/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7557 - mae: 1.8771

218/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.7971 - mae: 1.8864

222/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9258 - mae: 1.9013

226/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9552 - mae: 1.9068

231/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9921 - mae: 1.9111

236/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1334 - mae: 1.9244

240/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1431 - mae: 1.9196

244/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1016 - mae: 1.9115

248/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1240 - mae: 1.9165

252/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1236 - mae: 1.9153

257/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1259 - mae: 1.9187

261/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1234 - mae: 1.9194

265/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0948 - mae: 1.9148

270/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.1125 - mae: 1.9176

275/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0884 - mae: 1.9140

280/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0433 - mae: 1.9065

284/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0656 - mae: 1.9094

288/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0576 - mae: 1.9100

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0159 - mae: 1.9024

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9874 - mae: 1.8976

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9966 - mae: 1.8997

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0014 - mae: 1.9004

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9680 - mae: 1.8936

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9762 - mae: 1.8954

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9721 - mae: 1.8950

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9825 - mae: 1.8973

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0119 - mae: 1.9021

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0568 - mae: 1.9093

336/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1037 - mae: 1.9156

341/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1333 - mae: 1.9182

346/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1177 - mae: 1.9182

351/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1392 - mae: 1.9188

355/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1231 - mae: 1.9167

360/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1219 - mae: 1.9178

365/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.1474 - mae: 1.9204

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1386 - mae: 1.9193

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1243 - mae: 1.9153

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1228 - mae: 1.9166

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1167 - mae: 1.9147

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1059 - mae: 1.9123

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0983 - mae: 1.9142

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.1023 - mae: 1.9159

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0781 - mae: 1.9117

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0666 - mae: 1.9119

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0414 - mae: 1.9069

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0225 - mae: 1.9049

416/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0437 - mae: 1.9050

420/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0254 - mae: 1.9021

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0017 - mae: 1.8987

427/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0095 - mae: 1.9013

432/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0160 - mae: 1.9018

436/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.9969 - mae: 1.8985

440/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0205 - mae: 1.9009

444/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 6.0068 - mae: 1.8995

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0015 - mae: 1.8990

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9992 - mae: 1.8987

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0373 - mae: 1.9049

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0488 - mae: 1.9072

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0386 - mae: 1.9061

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0397 - mae: 1.9078

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0676 - mae: 1.9129

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0951 - mae: 1.9173

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0994 - mae: 1.9181

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0896 - mae: 1.9173

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1450 - mae: 1.9224

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1299 - mae: 1.9204

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1369 - mae: 1.9233

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1177 - mae: 1.9212

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1119 - mae: 1.9189

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1042 - mae: 1.9182

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1222 - mae: 1.9215

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0934 - mae: 1.9164

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - loss: 6.0919 - mae: 1.9162 - val_loss: 5.9751 - val_mae: 1.9299

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 36s 70ms/step - loss: 8.5463 - mae: 2.5711

  5/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.6506 - mae: 1.8428

  9/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.7481 - mae: 1.8217

 14/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 5.5807 - mae: 1.9135

 18/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6222 - mae: 1.9053

 23/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6538 - mae: 1.9411

 28/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.5233 - mae: 1.9044

 33/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.4724 - mae: 1.8917

 37/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6135 - mae: 1.9154

 41/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.5692 - mae: 1.9116

 44/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.4557 - mae: 1.8903

 48/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.5648 - mae: 1.9317

 52/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.5682 - mae: 1.9187

 56/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.6745 - mae: 1.9255

 60/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.8202 - mae: 1.9430

 64/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.8636 - mae: 1.9541

 68/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.6628 - mae: 1.9185

 72/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.5731 - mae: 1.8948

 77/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.4073 - mae: 1.8673

 81/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.3269 - mae: 1.8522

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.4065 - mae: 1.8652

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.5615 - mae: 1.8775

 93/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.6045 - mae: 1.8739

 96/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.5938 - mae: 1.8746

100/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.7661 - mae: 1.8919

104/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.7040 - mae: 1.8843

108/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.8045 - mae: 1.8892

112/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9372 - mae: 1.9148

116/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.8516 - mae: 1.9003

118/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.8698 - mae: 1.9048

122/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.8912 - mae: 1.9072

126/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9750 - mae: 1.9199

130/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9129 - mae: 1.9073

134/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9869 - mae: 1.9259

137/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9986 - mae: 1.9281

141/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.0450 - mae: 1.9336

145/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.1691 - mae: 1.9503

148/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.1751 - mae: 1.9503

151/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.1869 - mae: 1.9476

154/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.3042 - mae: 1.9679

158/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.2601 - mae: 1.9601

162/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.2694 - mae: 1.9615

164/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.2186 - mae: 1.9511

168/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.2251 - mae: 1.9515

172/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.3078 - mae: 1.9584

174/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.3108 - mae: 1.9605

178/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.3261 - mae: 1.9645

182/522 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 6.2848 - mae: 1.9601

186/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.2386 - mae: 1.9560

190/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.2396 - mae: 1.9576

194/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.2048 - mae: 1.9527

197/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1617 - mae: 1.9456

201/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1033 - mae: 1.9348

205/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0552 - mae: 1.9256

208/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0879 - mae: 1.9324

211/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1496 - mae: 1.9407

214/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.2231 - mae: 1.9540

218/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1913 - mae: 1.9457

221/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1707 - mae: 1.9432

224/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1280 - mae: 1.9361

228/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0748 - mae: 1.9299

232/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1262 - mae: 1.9371

235/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1674 - mae: 1.9444

238/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.1152 - mae: 1.9354

242/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0635 - mae: 1.9268

245/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0399 - mae: 1.9238

248/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0439 - mae: 1.9249

252/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0131 - mae: 1.9192

256/522 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 6.0444 - mae: 1.9256

260/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 6.0056 - mae: 1.9203

264/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 6.0614 - mae: 1.9322

268/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 6.0334 - mae: 1.9269

272/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9913 - mae: 1.9185

276/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 6.0196 - mae: 1.9199

280/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9897 - mae: 1.9143

284/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9385 - mae: 1.9043

288/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9265 - mae: 1.9013

293/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9250 - mae: 1.9013

297/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9449 - mae: 1.9048

302/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9256 - mae: 1.9026

306/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9177 - mae: 1.9016

310/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.9075 - mae: 1.8985

314/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.8896 - mae: 1.8946

318/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 5.8969 - mae: 1.8982

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8782 - mae: 1.8941

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.9000 - mae: 1.8943

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8939 - mae: 1.8933

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8627 - mae: 1.8871

339/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8381 - mae: 1.8824

343/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8452 - mae: 1.8854

347/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8511 - mae: 1.8852

351/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8430 - mae: 1.8847

355/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8273 - mae: 1.8819

359/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8325 - mae: 1.8827

363/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8281 - mae: 1.8818

367/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8320 - mae: 1.8828

371/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8440 - mae: 1.8810

375/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8568 - mae: 1.8831

379/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8636 - mae: 1.8846

383/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 5.8635 - mae: 1.8864

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 5.8742 - mae: 1.8881

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8785 - mae: 1.8897

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 5.8838 - mae: 1.8926

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 5.8799 - mae: 1.8914

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8796 - mae: 1.8908

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8597 - mae: 1.8881

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8605 - mae: 1.8893

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8520 - mae: 1.8881

422/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8344 - mae: 1.8861

426/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8157 - mae: 1.8835

430/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.7976 - mae: 1.8815

434/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.8015 - mae: 1.8801

438/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.7905 - mae: 1.8785

443/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.7744 - mae: 1.8745

447/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.7982 - mae: 1.8800

451/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 5.7966 - mae: 1.8807

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8396 - mae: 1.8854

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8088 - mae: 1.8800

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8016 - mae: 1.8804

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.7892 - mae: 1.8796

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.7954 - mae: 1.8819

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8455 - mae: 1.8901

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9100 - mae: 1.8970

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8971 - mae: 1.8949

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9226 - mae: 1.8988

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9249 - mae: 1.8988

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9143 - mae: 1.8968

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9032 - mae: 1.8938

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9292 - mae: 1.8996

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9413 - mae: 1.9014

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9389 - mae: 1.9015

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 16ms/step - loss: 5.9273 - mae: 1.8993 - val_loss: 6.3929 - val_mae: 1.9765

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18:58 2s/step - loss: 1.9542 - mae: 1.1458

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.3289 - mae: 1.8045

 10/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.5812 - mae: 1.9957

 15/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.5908 - mae: 1.9367

 20/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.0628 - mae: 1.8144

 25/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.1302 - mae: 1.8217

 29/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.5410 - mae: 1.8692

 33/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.3843 - mae: 1.8524

 38/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2406 - mae: 1.8079

 43/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.4619 - mae: 1.8468

 48/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.4628 - mae: 1.8457

 53/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.3500 - mae: 1.8259

 58/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.3468 - mae: 1.8250

 62/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2809 - mae: 1.8103

 66/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.4143 - mae: 1.8182

 71/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.3148 - mae: 1.8020

 75/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2712 - mae: 1.7973

 80/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2936 - mae: 1.8122

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.1885 - mae: 1.7899

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.1103 - mae: 1.7672

 93/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.0507 - mae: 1.7588

 98/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 4.9288 - mae: 1.7356

103/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.0062 - mae: 1.7487

108/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.0927 - mae: 1.7643

113/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.1116 - mae: 1.7668

118/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.0945 - mae: 1.7636

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.0486 - mae: 1.7540

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1132 - mae: 1.7624

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1320 - mae: 1.7633

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.0726 - mae: 1.7561

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2142 - mae: 1.7811

146/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.0966 - mae: 1.7539

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.0959 - mae: 1.7568

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1291 - mae: 1.7651

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1104 - mae: 1.7627

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1783 - mae: 1.7743

171/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2399 - mae: 1.7862

176/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2616 - mae: 1.7941

180/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2727 - mae: 1.7953

185/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2214 - mae: 1.7848

189/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1885 - mae: 1.7823

193/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.1910 - mae: 1.7818

197/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.2293 - mae: 1.7929

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2967 - mae: 1.8032

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2878 - mae: 1.8026

211/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2788 - mae: 1.8022

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2597 - mae: 1.7992

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2381 - mae: 1.7972

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.2875 - mae: 1.8007

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.3661 - mae: 1.8144

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.3854 - mae: 1.8148

236/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.4608 - mae: 1.8294

240/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.4361 - mae: 1.8255

244/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.4371 - mae: 1.8263

248/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.4315 - mae: 1.8257

252/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.4055 - mae: 1.8226

256/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.4564 - mae: 1.8312

260/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.4751 - mae: 1.8357

265/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.5226 - mae: 1.8396

269/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.5828 - mae: 1.8494

273/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.6138 - mae: 1.8527

277/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.6112 - mae: 1.8512

281/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.6351 - mae: 1.8574

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.6691 - mae: 1.8604

289/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7414 - mae: 1.8747

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7183 - mae: 1.8708

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7635 - mae: 1.8767

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7478 - mae: 1.8738

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7376 - mae: 1.8717

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7443 - mae: 1.8741

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7401 - mae: 1.8745

319/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7351 - mae: 1.8753

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7949 - mae: 1.8832

327/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8168 - mae: 1.8869

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7997 - mae: 1.8830

335/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7968 - mae: 1.8823

339/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8086 - mae: 1.8847

344/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8036 - mae: 1.8833

349/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8981 - mae: 1.8952

353/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8681 - mae: 1.8894

357/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9355 - mae: 1.8951

361/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9106 - mae: 1.8924

365/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9250 - mae: 1.8945

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.9490 - mae: 1.8971

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8902 - mae: 1.8859

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8845 - mae: 1.8868

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8821 - mae: 1.8864

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8625 - mae: 1.8836

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8574 - mae: 1.8831

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8477 - mae: 1.8838

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8300 - mae: 1.8814

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8095 - mae: 1.8783

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8022 - mae: 1.8761

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8282 - mae: 1.8815

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8599 - mae: 1.8843

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8300 - mae: 1.8806

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8149 - mae: 1.8797

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.7961 - mae: 1.8767

437/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8159 - mae: 1.8796

441/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8071 - mae: 1.8794

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7922 - mae: 1.8768

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7780 - mae: 1.8746

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7737 - mae: 1.8744

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8107 - mae: 1.8778

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7942 - mae: 1.8759

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7929 - mae: 1.8750

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7907 - mae: 1.8753

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7750 - mae: 1.8722

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7643 - mae: 1.8703

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7527 - mae: 1.8693

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7306 - mae: 1.8657

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6993 - mae: 1.8595

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6744 - mae: 1.8559

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.6856 - mae: 1.8589

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7033 - mae: 1.8610

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7081 - mae: 1.8600

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7304 - mae: 1.8631

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7356 - mae: 1.8655

522/522 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 5.7356 - mae: 1.8661 - val_loss: 6.0960 - val_mae: 1.9642

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24:14 3s/step - loss: 9.8226 - mae: 2.4707

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.7487 - mae: 2.4514

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.3557 - mae: 2.2519

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.9338 - mae: 2.2132

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.4188 - mae: 2.2651

 25/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.3398 - mae: 2.2459

 30/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.2003 - mae: 2.2197

 35/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.3898 - mae: 2.2443

 40/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.1816 - mae: 2.1940

 44/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.8225 - mae: 2.1330

 49/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5676 - mae: 2.0792

 53/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4714 - mae: 2.0688

 58/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5600 - mae: 2.0865

 63/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.6609 - mae: 2.0874

 68/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5217 - mae: 2.0526

 72/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4739 - mae: 2.0380

 77/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4287 - mae: 2.0217

 81/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.3241 - mae: 1.9999

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2667 - mae: 1.9852

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2352 - mae: 1.9819

 93/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.3812 - mae: 1.9969

 98/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2552 - mae: 1.9659

102/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2432 - mae: 1.9583

106/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1520 - mae: 1.9407

110/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0310 - mae: 1.9207

114/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0032 - mae: 1.9154

118/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.9779 - mae: 1.9143

122/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.8965 - mae: 1.9001

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8690 - mae: 1.8955

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7835 - mae: 1.8795

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7080 - mae: 1.8673

139/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.6415 - mae: 1.8550

143/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7570 - mae: 1.8617

147/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8407 - mae: 1.8715

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8423 - mae: 1.8697

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8857 - mae: 1.8815

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.9513 - mae: 1.8920

165/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8581 - mae: 1.8747

170/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8926 - mae: 1.8849

175/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8326 - mae: 1.8721

179/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8201 - mae: 1.8732

183/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8280 - mae: 1.8755

188/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8226 - mae: 1.8696

192/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7754 - mae: 1.8571

197/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8777 - mae: 1.8732

202/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.9369 - mae: 1.8850

206/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9097 - mae: 1.8833

211/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8894 - mae: 1.8812

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8781 - mae: 1.8811

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8379 - mae: 1.8780

224/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8417 - mae: 1.8764

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9266 - mae: 1.8800

233/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8706 - mae: 1.8685

237/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9488 - mae: 1.8825

241/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9893 - mae: 1.8879

246/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9765 - mae: 1.8896

251/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9402 - mae: 1.8844

256/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9235 - mae: 1.8835

261/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9472 - mae: 1.8856

265/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0184 - mae: 1.8940

270/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0207 - mae: 1.8986

275/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0209 - mae: 1.8997

280/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 6.0522 - mae: 1.9049

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0277 - mae: 1.9028

289/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9842 - mae: 1.8942

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0194 - mae: 1.8947

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 6.0254 - mae: 1.8979

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9876 - mae: 1.8927

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9706 - mae: 1.8907

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9505 - mae: 1.8887

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9356 - mae: 1.8875

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9097 - mae: 1.8828

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9313 - mae: 1.8834

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9060 - mae: 1.8789

330/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9160 - mae: 1.8825

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9642 - mae: 1.8899

339/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9234 - mae: 1.8835

343/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9249 - mae: 1.8844

348/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9332 - mae: 1.8843

352/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9129 - mae: 1.8801

356/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8876 - mae: 1.8769

360/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8667 - mae: 1.8747

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8383 - mae: 1.8691

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8539 - mae: 1.8732

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8754 - mae: 1.8797

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8502 - mae: 1.8771

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8345 - mae: 1.8752

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8028 - mae: 1.8694

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8008 - mae: 1.8688

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.7810 - mae: 1.8659

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8149 - mae: 1.8669

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8239 - mae: 1.8685

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8617 - mae: 1.8748

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8814 - mae: 1.8782

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8736 - mae: 1.8788

419/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8643 - mae: 1.8778

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8857 - mae: 1.8803

427/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8701 - mae: 1.8775

431/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8624 - mae: 1.8755

435/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8490 - mae: 1.8745

439/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8570 - mae: 1.8769

443/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8393 - mae: 1.8754

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8293 - mae: 1.8753

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8095 - mae: 1.8705

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8065 - mae: 1.8706

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7954 - mae: 1.8675

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7894 - mae: 1.8661

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8314 - mae: 1.8722

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7997 - mae: 1.8669

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8138 - mae: 1.8710

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8359 - mae: 1.8743

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8355 - mae: 1.8754

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8258 - mae: 1.8734

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8104 - mae: 1.8704

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7959 - mae: 1.8669

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7787 - mae: 1.8648

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8311 - mae: 1.8727

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8476 - mae: 1.8765

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8758 - mae: 1.8800

522/522 ━━━━━━━━━━━━━━━━━━━━ 10s 14ms/step - loss: 5.8913 - mae: 1.8823 - val_loss: 7.3627 - val_mae: 2.1644

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 39s 75ms/step - loss: 2.5922 - mae: 1.4914

  5/522 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 4.4272 - mae: 1.5329

  9/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 4.1498 - mae: 1.5120

 14/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.2021 - mae: 1.7633

 18/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6520 - mae: 1.8869

 22/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.9444 - mae: 1.9444

 26/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.2539 - mae: 1.7911

 30/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.2313 - mae: 1.7986

 34/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.9626 - mae: 1.7524

 38/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.3301 - mae: 1.7942

 42/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.2997 - mae: 1.7948

 46/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.1876 - mae: 1.7861

 49/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.1872 - mae: 1.7797

 53/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.6155 - mae: 1.8474

 58/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 6.0704 - mae: 1.8893

 62/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 6.0198 - mae: 1.8938

 66/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.9469 - mae: 1.8831

 71/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.8696 - mae: 1.8708

 76/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.8204 - mae: 1.8782

 80/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 6.1285 - mae: 1.9018

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 5.9901 - mae: 1.8726

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.0637 - mae: 1.8918

 94/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0577 - mae: 1.8963

 98/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 6.0828 - mae: 1.9011

102/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0063 - mae: 1.8884

106/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0052 - mae: 1.8910

111/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0087 - mae: 1.8965

116/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0704 - mae: 1.9120

120/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0166 - mae: 1.9068

124/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0498 - mae: 1.9144

129/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 6.0179 - mae: 1.9100

133/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.9055 - mae: 1.8897

138/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.8401 - mae: 1.8817

142/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.8565 - mae: 1.8829

146/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.9490 - mae: 1.8987

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8562 - mae: 1.8847

155/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8886 - mae: 1.8911

159/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.9222 - mae: 1.8954

162/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.9355 - mae: 1.9000

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8441 - mae: 1.8813

171/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7684 - mae: 1.8701

176/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7813 - mae: 1.8735

181/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7653 - mae: 1.8726

186/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7006 - mae: 1.8610

191/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7150 - mae: 1.8653

196/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7349 - mae: 1.8656

200/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7115 - mae: 1.8632

204/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7263 - mae: 1.8643

209/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.7475 - mae: 1.8706

214/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 5.8133 - mae: 1.8772

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8106 - mae: 1.8750

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8009 - mae: 1.8766

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.7692 - mae: 1.8760

231/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.7070 - mae: 1.8642

236/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8752 - mae: 1.8855

241/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8563 - mae: 1.8809

245/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8785 - mae: 1.8841

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8727 - mae: 1.8843

254/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8824 - mae: 1.8882

258/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9031 - mae: 1.8923

262/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9143 - mae: 1.8955

266/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.8979 - mae: 1.8941

270/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9506 - mae: 1.9026

275/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9314 - mae: 1.9019

279/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9368 - mae: 1.9025

284/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9217 - mae: 1.9003

288/522 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9024 - mae: 1.8990

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8828 - mae: 1.8932

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8885 - mae: 1.8954

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8864 - mae: 1.8958

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8835 - mae: 1.8955

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8638 - mae: 1.8936

312/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8714 - mae: 1.8943

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.9008 - mae: 1.8945

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8807 - mae: 1.8909

325/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8637 - mae: 1.8889

329/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8392 - mae: 1.8844

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8330 - mae: 1.8815

338/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8835 - mae: 1.8890

343/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8421 - mae: 1.8814

347/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8232 - mae: 1.8792

351/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.7863 - mae: 1.8731

355/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8376 - mae: 1.8806

359/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8362 - mae: 1.8804

364/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8225 - mae: 1.8792

368/522 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 5.8188 - mae: 1.8799

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8115 - mae: 1.8782

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8021 - mae: 1.8770

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.7619 - mae: 1.8680

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8112 - mae: 1.8735

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.7980 - mae: 1.8704

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.7970 - mae: 1.8722

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8196 - mae: 1.8791

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8027 - mae: 1.8762

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8225 - mae: 1.8804

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8250 - mae: 1.8787

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8381 - mae: 1.8827

419/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8381 - mae: 1.8842

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8361 - mae: 1.8854

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8208 - mae: 1.8827

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8082 - mae: 1.8801

437/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8135 - mae: 1.8826

442/522 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 5.8109 - mae: 1.8831

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8141 - mae: 1.8847

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7989 - mae: 1.8807

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8242 - mae: 1.8844

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8054 - mae: 1.8806

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8252 - mae: 1.8809

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8067 - mae: 1.8778

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7984 - mae: 1.8776

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8361 - mae: 1.8834

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8567 - mae: 1.8877

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8726 - mae: 1.8900

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8622 - mae: 1.8882

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8426 - mae: 1.8845

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8381 - mae: 1.8827

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8463 - mae: 1.8831

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8391 - mae: 1.8802

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8337 - mae: 1.8812

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8122 - mae: 1.8765

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8380 - mae: 1.8797

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8246 - mae: 1.8773

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - loss: 5.8246 - mae: 1.8773 - val_loss: 5.8711 - val_mae: 1.9166

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 39s 75ms/step - loss: 7.4036 - mae: 2.4552

  5/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 4.6490 - mae: 1.8031

  9/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 5.0704 - mae: 1.8067

 13/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.2343 - mae: 1.8406

 17/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.7377 - mae: 1.9176

 22/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.4967 - mae: 1.9535

 26/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.3659 - mae: 1.9590

 31/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.9402 - mae: 1.9154

 35/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.8800 - mae: 1.9015

 40/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.6338 - mae: 1.8664

 44/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.4319 - mae: 1.8294

 49/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.6414 - mae: 1.8695

 54/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.6246 - mae: 1.8640

 58/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.5465 - mae: 1.8454

 63/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 5.3212 - mae: 1.8026

 68/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2737 - mae: 1.7972

 73/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.2737 - mae: 1.7839

 79/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.3267 - mae: 1.8014

 85/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.6013 - mae: 1.8255

 91/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.4818 - mae: 1.8047

 97/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4906 - mae: 1.8075

102/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5796 - mae: 1.8213

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5407 - mae: 1.8150

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6814 - mae: 1.8312

120/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7369 - mae: 1.8391

125/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7532 - mae: 1.8368

130/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6634 - mae: 1.8221

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6577 - mae: 1.8242

140/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6639 - mae: 1.8290

145/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6487 - mae: 1.8244

150/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5858 - mae: 1.8131

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5429 - mae: 1.8111

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.4792 - mae: 1.7983

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.4771 - mae: 1.8015

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.4469 - mae: 1.7997

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5755 - mae: 1.8250

183/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5293 - mae: 1.8195

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5532 - mae: 1.8259

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5300 - mae: 1.8256

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.6161 - mae: 1.8390

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5703 - mae: 1.8317

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5447 - mae: 1.8317

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5912 - mae: 1.8405

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5957 - mae: 1.8381

225/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5725 - mae: 1.8353

231/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5463 - mae: 1.8327

237/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.5327 - mae: 1.8329

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5611 - mae: 1.8419

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5194 - mae: 1.8350

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.4850 - mae: 1.8259

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.4767 - mae: 1.8274

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5446 - mae: 1.8342

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5450 - mae: 1.8358

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6466 - mae: 1.8553

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5951 - mae: 1.8433

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5718 - mae: 1.8387

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5766 - mae: 1.8397

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6038 - mae: 1.8434

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6292 - mae: 1.8489

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6124 - mae: 1.8470

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6205 - mae: 1.8465

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6405 - mae: 1.8494

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6332 - mae: 1.8497

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6120 - mae: 1.8465

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6222 - mae: 1.8508

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6411 - mae: 1.8561

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6444 - mae: 1.8544

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7359 - mae: 1.8673

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7562 - mae: 1.8676

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7880 - mae: 1.8728

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7585 - mae: 1.8696

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7470 - mae: 1.8677

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7721 - mae: 1.8738

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7527 - mae: 1.8707

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7493 - mae: 1.8715

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7364 - mae: 1.8711

417/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7657 - mae: 1.8760

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7471 - mae: 1.8710

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7393 - mae: 1.8669

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7465 - mae: 1.8669

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7436 - mae: 1.8661

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7271 - mae: 1.8645

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7110 - mae: 1.8629

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7087 - mae: 1.8632

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7020 - mae: 1.8632

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7016 - mae: 1.8619

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7094 - mae: 1.8585

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7144 - mae: 1.8612

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7087 - mae: 1.8596

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7136 - mae: 1.8606

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6879 - mae: 1.8561

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6798 - mae: 1.8549

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6718 - mae: 1.8534

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6501 - mae: 1.8496

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 5.6518 - mae: 1.8501 - val_loss: 6.3073 - val_mae: 1.9987

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 3.0454 - mae: 1.3713

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7525 - mae: 1.7894

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8017 - mae: 1.8325

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4524 - mae: 1.8059

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7722 - mae: 1.8427

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4216 - mae: 1.7995

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4390 - mae: 1.8116

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9368 - mae: 1.8822

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0502 - mae: 1.8916

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0872 - mae: 1.8550

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9357 - mae: 1.8349

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0092 - mae: 1.8529

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7241 - mae: 1.8096

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7833 - mae: 1.8407

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6468 - mae: 1.8186

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7185 - mae: 1.8041

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7530 - mae: 1.8206

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8345 - mae: 1.8361

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8362 - mae: 1.8417

113/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9635 - mae: 1.8526

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8673 - mae: 1.8386

125/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8893 - mae: 1.8519

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7905 - mae: 1.8372

137/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8679 - mae: 1.8434

143/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8632 - mae: 1.8492

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9233 - mae: 1.8617

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9327 - mae: 1.8663

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9066 - mae: 1.8619

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8956 - mae: 1.8564

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8617 - mae: 1.8507

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7974 - mae: 1.8468

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7647 - mae: 1.8493

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7849 - mae: 1.8534

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7854 - mae: 1.8558

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7786 - mae: 1.8565

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8172 - mae: 1.8688

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8130 - mae: 1.8709

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7780 - mae: 1.8649

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7658 - mae: 1.8624

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7910 - mae: 1.8690

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7769 - mae: 1.8654

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7339 - mae: 1.8619

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6802 - mae: 1.8520

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6794 - mae: 1.8567

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6694 - mae: 1.8555

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6605 - mae: 1.8544

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6387 - mae: 1.8482

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7606 - mae: 1.8686

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7371 - mae: 1.8653

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6908 - mae: 1.8570

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7184 - mae: 1.8624

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7753 - mae: 1.8710

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7372 - mae: 1.8624

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6916 - mae: 1.8544

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7090 - mae: 1.8556

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6728 - mae: 1.8486

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6833 - mae: 1.8538

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6914 - mae: 1.8549

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6608 - mae: 1.8465

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7137 - mae: 1.8533

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7189 - mae: 1.8568

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6883 - mae: 1.8527

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7098 - mae: 1.8546

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7251 - mae: 1.8574

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7474 - mae: 1.8621

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6982 - mae: 1.8530

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6769 - mae: 1.8524

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6552 - mae: 1.8497

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6286 - mae: 1.8454

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6078 - mae: 1.8407

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5912 - mae: 1.8392

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5922 - mae: 1.8416

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6054 - mae: 1.8405

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5906 - mae: 1.8372

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5726 - mae: 1.8352

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5608 - mae: 1.8338

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5782 - mae: 1.8375

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5568 - mae: 1.8328

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5448 - mae: 1.8306

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5526 - mae: 1.8312

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5759 - mae: 1.8329

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5642 - mae: 1.8307

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5693 - mae: 1.8320

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5404 - mae: 1.8276

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5376 - mae: 1.8280

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5406 - mae: 1.8284

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5459 - mae: 1.8306

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5459 - mae: 1.8306 - val_loss: 5.8559 - val_mae: 1.9205

Epoch 22/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 3.7551 - mae: 1.5595

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.4593 - mae: 1.9673

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.6178 - mae: 1.9187

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.3885 - mae: 1.8656

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0436 - mae: 1.8016

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.9363 - mae: 1.7964

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.5060 - mae: 1.7112

 45/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.5126 - mae: 1.7000

 51/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.4097 - mae: 1.6800

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.5966 - mae: 1.7211

 63/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.5578 - mae: 1.7096

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.8450 - mae: 1.7545

 75/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.8054 - mae: 1.7369

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.8064 - mae: 1.7382

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.0521 - mae: 1.7759

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 4.9708 - mae: 1.7549

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1522 - mae: 1.7879

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1396 - mae: 1.7768

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1123 - mae: 1.7721

118/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.0283 - mae: 1.7540

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.0330 - mae: 1.7450

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1192 - mae: 1.7681

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.0887 - mae: 1.7624

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.0886 - mae: 1.7628

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1475 - mae: 1.7720

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1835 - mae: 1.7799

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1938 - mae: 1.7814

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1540 - mae: 1.7722

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.1604 - mae: 1.7719

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.2958 - mae: 1.7965

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3181 - mae: 1.8020

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.2944 - mae: 1.7949

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3281 - mae: 1.7991

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3646 - mae: 1.8070

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3863 - mae: 1.8123

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3643 - mae: 1.8065

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3811 - mae: 1.8119

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3347 - mae: 1.8040

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3578 - mae: 1.8025

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3796 - mae: 1.8092

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3615 - mae: 1.8070

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3772 - mae: 1.8137

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4277 - mae: 1.8202

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.3859 - mae: 1.8151

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4071 - mae: 1.8213

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4428 - mae: 1.8274

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4475 - mae: 1.8269

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4121 - mae: 1.8198

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3973 - mae: 1.8176

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3855 - mae: 1.8141

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5223 - mae: 1.8252

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5044 - mae: 1.8213

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5275 - mae: 1.8278

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5932 - mae: 1.8332

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5690 - mae: 1.8301

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5642 - mae: 1.8296

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5461 - mae: 1.8278

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5773 - mae: 1.8337

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5374 - mae: 1.8269

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5130 - mae: 1.8236

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5086 - mae: 1.8219

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4733 - mae: 1.8143

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5341 - mae: 1.8201

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5096 - mae: 1.8147

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5036 - mae: 1.8142

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5019 - mae: 1.8128

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5049 - mae: 1.8135

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5524 - mae: 1.8229

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5727 - mae: 1.8268

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5364 - mae: 1.8215

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5140 - mae: 1.8197

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4879 - mae: 1.8152

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4523 - mae: 1.8093

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4479 - mae: 1.8099

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4410 - mae: 1.8068

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4573 - mae: 1.8102

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4536 - mae: 1.8094

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4670 - mae: 1.8146

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4936 - mae: 1.8201

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4922 - mae: 1.8209

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4936 - mae: 1.8211

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4706 - mae: 1.8179

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4684 - mae: 1.8182

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4616 - mae: 1.8175

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4548 - mae: 1.8184

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4599 - mae: 1.8187

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.4596 - mae: 1.8190 - val_loss: 6.2111 - val_mae: 1.9732

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 12.

In [16]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 5s 481ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step

MAE:  1.794491412626446

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [17]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=128, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Conv1D(filters=64, kernel_size=2))
model.add(MaxPooling1D(2))
model.add(Bidirectional(LSTM(32, activation='relu')))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 28, 128)        │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 14, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 13, 64)         │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 6, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,857 (163.50 KB)

 Trainable params: 41,857 (163.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 1:09:58 8s/step - loss: 12.8043 - mae: 3.1220

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 18.0367 - mae: 3.2660

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 13.2941 - mae: 2.8579

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 14.4182 - mae: 2.9581

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 13.8189 - mae: 2.9118

 36/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.6709 - mae: 2.8233

 43/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5658 - mae: 2.6741

 50/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5617 - mae: 2.6759

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.9685 - mae: 2.6131

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.1948 - mae: 2.6331

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.0228 - mae: 2.6240

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.9034 - mae: 2.5933

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.9320 - mae: 2.5903

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.8596 - mae: 2.5869

100/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.8112 - mae: 2.5863

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.8542 - mae: 2.5962

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.9767 - mae: 2.6005

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.0088 - mae: 2.6141

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7848 - mae: 2.5901

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.7462 - mae: 2.5913

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.8777 - mae: 2.6141

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.7687 - mae: 2.6066

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.6233 - mae: 2.5767

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.6742 - mae: 2.5825

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.4568 - mae: 2.5479

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.5919 - mae: 2.5620

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.5599 - mae: 2.5537

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.4873 - mae: 2.5459

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.3169 - mae: 2.5264

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.2886 - mae: 2.5243

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1607 - mae: 2.5041

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1907 - mae: 2.5092

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0739 - mae: 2.5003

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0057 - mae: 2.4938

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9555 - mae: 2.4901

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0283 - mae: 2.4988

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0334 - mae: 2.5014

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9450 - mae: 2.4888

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0725 - mae: 2.4960

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0839 - mae: 2.4981

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0485 - mae: 2.4990

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0025 - mae: 2.4909

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9083 - mae: 2.4817

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8822 - mae: 2.4776

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8208 - mae: 2.4682

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7444 - mae: 2.4541

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6746 - mae: 2.4411

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7153 - mae: 2.4458

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7427 - mae: 2.4422

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7656 - mae: 2.4457

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7673 - mae: 2.4502

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7670 - mae: 2.4477

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7562 - mae: 2.4493

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8430 - mae: 2.4575

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8776 - mae: 2.4643

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8319 - mae: 2.4593

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8927 - mae: 2.4678

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8581 - mae: 2.4608

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8280 - mae: 2.4583

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8602 - mae: 2.4603

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8204 - mae: 2.4562

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7581 - mae: 2.4494

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7332 - mae: 2.4469

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8238 - mae: 2.4586

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8059 - mae: 2.4575

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7917 - mae: 2.4549

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8272 - mae: 2.4614

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8210 - mae: 2.4593

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8205 - mae: 2.4583

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8094 - mae: 2.4568

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7956 - mae: 2.4552

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8501 - mae: 2.4622

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8473 - mae: 2.4610

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8165 - mae: 2.4558

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7615 - mae: 2.4478

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8001 - mae: 2.4536

522/522 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - loss: 9.8001 - mae: 2.4536 - val_loss: 8.2048 - val_mae: 2.2333

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 6.0341 - mae: 1.7666

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.8783 - mae: 2.4398

 16/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.9981 - mae: 2.3191

 23/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1865 - mae: 2.3230

 31/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.8032 - mae: 2.4171

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5047 - mae: 2.4102

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3224 - mae: 2.3415

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1226 - mae: 2.2969

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0518 - mae: 2.2701

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8472 - mae: 2.2573

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6725 - mae: 2.2506

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6672 - mae: 2.2632

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5168 - mae: 2.2284

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3499 - mae: 2.1995

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4871 - mae: 2.2243

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5922 - mae: 2.2478

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5782 - mae: 2.2447

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5523 - mae: 2.2546

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5142 - mae: 2.2510

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3987 - mae: 2.2456

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2751 - mae: 2.2336

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6922 - mae: 2.2732

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8968 - mae: 2.3032

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9090 - mae: 2.3033

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8043 - mae: 2.2890

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7885 - mae: 2.2908

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7318 - mae: 2.2858

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6790 - mae: 2.2817

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8167 - mae: 2.3009

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8819 - mae: 2.3093

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9413 - mae: 2.3191

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1144 - mae: 2.3404

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0970 - mae: 2.3333

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1256 - mae: 2.3321

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1522 - mae: 2.3404

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1191 - mae: 2.3375

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2416 - mae: 2.3537

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1568 - mae: 2.3438

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2172 - mae: 2.3507

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2579 - mae: 2.3594

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3401 - mae: 2.3690

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2728 - mae: 2.3547

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2705 - mae: 2.3561

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2049 - mae: 2.3511

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2424 - mae: 2.3530

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2741 - mae: 2.3594

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2889 - mae: 2.3612

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3588 - mae: 2.3738

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3277 - mae: 2.3702

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3005 - mae: 2.3684

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3141 - mae: 2.3699

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3679 - mae: 2.3801

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3777 - mae: 2.3845

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.4053 - mae: 2.3872

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3535 - mae: 2.3771

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2637 - mae: 2.3643

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2770 - mae: 2.3682

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2927 - mae: 2.3715

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2850 - mae: 2.3713

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3172 - mae: 2.3774

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2859 - mae: 2.3720

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3193 - mae: 2.3749

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3315 - mae: 2.3760

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3097 - mae: 2.3733

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2832 - mae: 2.3712

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2335 - mae: 2.3652

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2535 - mae: 2.3719

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2288 - mae: 2.3704

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2176 - mae: 2.3688

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2131 - mae: 2.3678

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2402 - mae: 2.3723

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.2486 - mae: 2.3737 - val_loss: 7.6520 - val_mae: 2.1599

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 62ms/step - loss: 5.4607 - mae: 1.7496

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3654 - mae: 2.1793

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1866 - mae: 1.9732

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4009 - mae: 2.0541

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9505 - mae: 2.1034

 39/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3651 - mae: 2.1193

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.4550 - mae: 2.2581

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5033 - mae: 2.3041

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5879 - mae: 2.3360

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.9231 - mae: 2.2361

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8774 - mae: 2.2381

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2785 - mae: 2.2792

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1367 - mae: 2.2895

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2502 - mae: 2.3007

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.3360 - mae: 2.3119

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1952 - mae: 2.3071

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2510 - mae: 2.3245

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0753 - mae: 2.3031

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1503 - mae: 2.3124

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0989 - mae: 2.3125

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0805 - mae: 2.3179

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0935 - mae: 2.3231

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9822 - mae: 2.3089

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0260 - mae: 2.3109

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1655 - mae: 2.3380

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1497 - mae: 2.3428

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0850 - mae: 2.3306

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1858 - mae: 2.3398

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1952 - mae: 2.3456

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2500 - mae: 2.3432

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2612 - mae: 2.3451

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.3675 - mae: 2.3590

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.3625 - mae: 2.3574

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3495 - mae: 2.3565

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3660 - mae: 2.3627

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3209 - mae: 2.3565

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3016 - mae: 2.3519

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2897 - mae: 2.3542

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3032 - mae: 2.3548

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2929 - mae: 2.3526

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2443 - mae: 2.3463

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3064 - mae: 2.3614

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2741 - mae: 2.3574

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3431 - mae: 2.3715

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3232 - mae: 2.3695

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3530 - mae: 2.3748

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3507 - mae: 2.3749

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3270 - mae: 2.3729

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.3243 - mae: 2.3751

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2850 - mae: 2.3723

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2857 - mae: 2.3766

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2007 - mae: 2.3647

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1838 - mae: 2.3628

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1370 - mae: 2.3556

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1273 - mae: 2.3561

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1222 - mae: 2.3551

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0756 - mae: 2.3481

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0939 - mae: 2.3535

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0599 - mae: 2.3500

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0174 - mae: 2.3436

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0273 - mae: 2.3469

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0143 - mae: 2.3443

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0546 - mae: 2.3518

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9940 - mae: 2.3421

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0401 - mae: 2.3478

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0320 - mae: 2.3479

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0259 - mae: 2.3480

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0094 - mae: 2.3483

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0009 - mae: 2.3460

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0317 - mae: 2.3508

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0297 - mae: 2.3517

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1012 - mae: 2.3603

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 9.0702 - mae: 2.3563 - val_loss: 8.2713 - val_mae: 2.2228

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 34s 66ms/step - loss: 6.8638 - mae: 2.3585

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7941 - mae: 2.2132

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3130 - mae: 2.3026

 21/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8996 - mae: 2.4184

 28/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7619 - mae: 2.6086

 35/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.5434 - mae: 2.5813

 42/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0425 - mae: 2.5063

 50/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.3086 - mae: 2.4897

 58/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5564 - mae: 2.4967

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.6507 - mae: 2.5008

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.1042 - mae: 2.5282

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.1083 - mae: 2.5491

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9371 - mae: 2.5257

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.0485 - mae: 2.5304

100/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.2336 - mae: 2.5490

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.4309 - mae: 2.5792

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.0506 - mae: 2.5133

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.0353 - mae: 2.5028

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8308 - mae: 2.4776

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5870 - mae: 2.4389

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.5463 - mae: 2.4356

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.6251 - mae: 2.4464

157/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.5960 - mae: 2.4358

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.4890 - mae: 2.4278

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2933 - mae: 2.4023

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2368 - mae: 2.3940

187/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.3081 - mae: 2.4088

194/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2548 - mae: 2.3992

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1507 - mae: 2.3837

207/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1381 - mae: 2.3875

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.2345 - mae: 2.3978

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1689 - mae: 2.3858

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1388 - mae: 2.3853

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1108 - mae: 2.3889

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0630 - mae: 2.3823

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0518 - mae: 2.3788

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0687 - mae: 2.3792

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1359 - mae: 2.3912

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1305 - mae: 2.3876

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1381 - mae: 2.3867

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0941 - mae: 2.3798

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.9937 - mae: 2.3644

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0173 - mae: 2.3676

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.9103 - mae: 2.3518

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.8645 - mae: 2.3459

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.8240 - mae: 2.3404

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.8186 - mae: 2.3418

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.8141 - mae: 2.3419

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7865 - mae: 2.3397

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7809 - mae: 2.3396

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7492 - mae: 2.3326

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7277 - mae: 2.3272

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6830 - mae: 2.3213

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6884 - mae: 2.3213

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7039 - mae: 2.3232

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7809 - mae: 2.3304

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7587 - mae: 2.3290

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7047 - mae: 2.3251

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6937 - mae: 2.3291

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7220 - mae: 2.3344

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7146 - mae: 2.3332

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7069 - mae: 2.3287

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7197 - mae: 2.3318

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6729 - mae: 2.3239

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6898 - mae: 2.3275

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6501 - mae: 2.3216

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6786 - mae: 2.3274

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7437 - mae: 2.3350

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7186 - mae: 2.3324

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7272 - mae: 2.3331

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7436 - mae: 2.3301

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7792 - mae: 2.3318

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.7558 - mae: 2.3259 - val_loss: 7.8205 - val_mae: 2.1828

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - loss: 6.6890 - mae: 2.1453

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.1752 - mae: 2.0068

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8953 - mae: 2.2282

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8317 - mae: 2.3222

 31/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2783 - mae: 2.2160

 39/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7650 - mae: 2.3006

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2673 - mae: 2.2404

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8131 - mae: 2.3020

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2530 - mae: 2.3200

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8790 - mae: 2.2781

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0807 - mae: 2.3078

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2076 - mae: 2.3309

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1771 - mae: 2.3442

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1896 - mae: 2.3538

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1249 - mae: 2.3532

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8779 - mae: 2.3116

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0507 - mae: 2.3407

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1524 - mae: 2.3558

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0977 - mae: 2.3489

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9403 - mae: 2.3309

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9607 - mae: 2.3363

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9754 - mae: 2.3333

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8617 - mae: 2.3199

174/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8783 - mae: 2.3206

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8471 - mae: 2.3241

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8666 - mae: 2.3285

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8341 - mae: 2.3244

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0068 - mae: 2.3356

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9647 - mae: 2.3324

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8524 - mae: 2.3192

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0008 - mae: 2.3296

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0464 - mae: 2.3341

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1961 - mae: 2.3529

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2722 - mae: 2.3656

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1519 - mae: 2.3512

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1035 - mae: 2.3491

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0834 - mae: 2.3471

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0184 - mae: 2.3395

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.9680 - mae: 2.3351

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.9834 - mae: 2.3353

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1087 - mae: 2.3488

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1513 - mae: 2.3529

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1806 - mae: 2.3597

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1472 - mae: 2.3561

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1188 - mae: 2.3489

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0873 - mae: 2.3484

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0898 - mae: 2.3490

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1189 - mae: 2.3550

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.0838 - mae: 2.3504

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1232 - mae: 2.3514

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1051 - mae: 2.3524

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1354 - mae: 2.3615

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1630 - mae: 2.3622

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1455 - mae: 2.3612

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1071 - mae: 2.3582

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1007 - mae: 2.3545

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1154 - mae: 2.3554

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0762 - mae: 2.3513

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0710 - mae: 2.3509

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0592 - mae: 2.3515

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0340 - mae: 2.3493

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0230 - mae: 2.3498

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0063 - mae: 2.3482

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0748 - mae: 2.3551

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0214 - mae: 2.3506

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0553 - mae: 2.3573

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0112 - mae: 2.3508

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9864 - mae: 2.3509

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0226 - mae: 2.3554

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9663 - mae: 2.3483

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.9625 - mae: 2.3484 - val_loss: 7.8063 - val_mae: 2.1605

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 7:45 893ms/step - loss: 11.7777 - mae: 3.0290

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5515 - mae: 2.0880

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.1444 - mae: 2.1392

 21/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.7251 - mae: 2.0851

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.5441 - mae: 2.0366

 37/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9790 - mae: 2.0793

 44/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2127 - mae: 2.1513

 52/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5083 - mae: 2.1766

 59/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4780 - mae: 2.1514

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0050 - mae: 2.0681

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9811 - mae: 2.0603

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9803 - mae: 2.0610

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3271 - mae: 2.1261

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4711 - mae: 2.1446

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3589 - mae: 2.1340

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5011 - mae: 2.1521

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5204 - mae: 2.1522

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4484 - mae: 2.1488

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4707 - mae: 2.1590

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5919 - mae: 2.1771

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6478 - mae: 2.1912

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.7428 - mae: 2.1984

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9237 - mae: 2.2229

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1477 - mae: 2.2520

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1306 - mae: 2.2558

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1448 - mae: 2.2623

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1422 - mae: 2.2559

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1087 - mae: 2.2497

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2668 - mae: 2.2631

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3129 - mae: 2.2639

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2380 - mae: 2.2497

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0980 - mae: 2.2283

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0129 - mae: 2.2194

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0343 - mae: 2.2217

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1384 - mae: 2.2315

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1185 - mae: 2.2252

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0018 - mae: 2.2077

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0334 - mae: 2.2128

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9930 - mae: 2.2088

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0335 - mae: 2.2147

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1258 - mae: 2.2255

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2056 - mae: 2.2357

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1330 - mae: 2.2220

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2729 - mae: 2.2453

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2497 - mae: 2.2411

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2285 - mae: 2.2374

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2228 - mae: 2.2370

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2162 - mae: 2.2383

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2251 - mae: 2.2377

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2776 - mae: 2.2433

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3208 - mae: 2.2490

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3754 - mae: 2.2539

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3966 - mae: 2.2568

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4068 - mae: 2.2580

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3554 - mae: 2.2515

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4136 - mae: 2.2599

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4669 - mae: 2.2685

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4748 - mae: 2.2695

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4685 - mae: 2.2724

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4351 - mae: 2.2710

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5255 - mae: 2.2804

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5406 - mae: 2.2811

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4963 - mae: 2.2761

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5255 - mae: 2.2802

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5018 - mae: 2.2792

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4750 - mae: 2.2745

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5613 - mae: 2.2838

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5998 - mae: 2.2888

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6481 - mae: 2.2968

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6501 - mae: 2.2977

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6779 - mae: 2.3022

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 8.6779 - mae: 2.3022 - val_loss: 7.8126 - val_mae: 2.1661

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 4.9797 - mae: 2.0090

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.7530 - mae: 2.6929

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.7536 - mae: 2.5615

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.9221 - mae: 2.5597

 31/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3303 - mae: 2.4522

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.4958 - mae: 2.4828

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7957 - mae: 2.3420

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.4681 - mae: 2.2917

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3492 - mae: 2.2834

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0122 - mae: 2.2228

 75/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9645 - mae: 2.2398

 82/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8421 - mae: 2.2273

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0041 - mae: 2.2425

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1765 - mae: 2.2663

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2768 - mae: 2.2732

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2660 - mae: 2.2768

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1591 - mae: 2.2617

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0084 - mae: 2.2334

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9255 - mae: 2.2247

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8132 - mae: 2.1972

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0903 - mae: 2.2284

157/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0580 - mae: 2.2211

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1694 - mae: 2.2295

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2724 - mae: 2.2476

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3200 - mae: 2.2514

187/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5336 - mae: 2.2812

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6686 - mae: 2.2955

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7162 - mae: 2.2971

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9749 - mae: 2.3263

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0758 - mae: 2.3470

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0629 - mae: 2.3438

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1181 - mae: 2.3423

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1503 - mae: 2.3532

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2554 - mae: 2.3731

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1615 - mae: 2.3585

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1337 - mae: 2.3519

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1731 - mae: 2.3603

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1438 - mae: 2.3575

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2715 - mae: 2.3695

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2830 - mae: 2.3731

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2041 - mae: 2.3584

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1181 - mae: 2.3486

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1217 - mae: 2.3476

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.2199 - mae: 2.3625

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1764 - mae: 2.3558

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1894 - mae: 2.3588

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1772 - mae: 2.3565

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1510 - mae: 2.3558

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1189 - mae: 2.3519

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1030 - mae: 2.3516

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1415 - mae: 2.3573

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 9.1158 - mae: 2.3547

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1015 - mae: 2.3485

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0483 - mae: 2.3438

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0980 - mae: 2.3525

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0813 - mae: 2.3505

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0295 - mae: 2.3434

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0272 - mae: 2.3442

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9966 - mae: 2.3387

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0167 - mae: 2.3433

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0376 - mae: 2.3432

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0340 - mae: 2.3446

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9794 - mae: 2.3357

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9809 - mae: 2.3362

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9820 - mae: 2.3404

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9707 - mae: 2.3393

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9420 - mae: 2.3351

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9211 - mae: 2.3337

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9370 - mae: 2.3367

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9467 - mae: 2.3383

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.9481 - mae: 2.3375 - val_loss: 8.7258 - val_mae: 2.3038

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 10.1152 - mae: 2.2586

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.8538 - mae: 2.7341

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6522 - mae: 2.3734

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1859 - mae: 2.3090

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1586 - mae: 2.3880

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7779 - mae: 2.3595

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0184 - mae: 2.3601

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8915 - mae: 2.3464

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8762 - mae: 2.3545

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8651 - mae: 2.3463

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1720 - mae: 2.3983

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2761 - mae: 2.3999

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0606 - mae: 2.3785

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.8636 - mae: 2.3623

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7536 - mae: 2.3405

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5862 - mae: 2.3211

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5055 - mae: 2.3077

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7246 - mae: 2.3326

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5659 - mae: 2.3077

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5979 - mae: 2.3155

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9393 - mae: 2.3485

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9104 - mae: 2.3317

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8092 - mae: 2.3256

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6203 - mae: 2.2945

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5814 - mae: 2.2922

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4609 - mae: 2.2745

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4209 - mae: 2.2731

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3954 - mae: 2.2641

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3449 - mae: 2.2616

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2901 - mae: 2.2575

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2737 - mae: 2.2555

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1847 - mae: 2.2476

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1822 - mae: 2.2458

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2000 - mae: 2.2514

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1616 - mae: 2.2487

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1051 - mae: 2.2414

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2133 - mae: 2.2488

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1662 - mae: 2.2449

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1553 - mae: 2.2442

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1838 - mae: 2.2415

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1901 - mae: 2.2447

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1730 - mae: 2.2443

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1661 - mae: 2.2435

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1837 - mae: 2.2506

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1377 - mae: 2.2455

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1896 - mae: 2.2523

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2477 - mae: 2.2589

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2218 - mae: 2.2598

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2764 - mae: 2.2638

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3408 - mae: 2.2726

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3939 - mae: 2.2802

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3742 - mae: 2.2765

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3126 - mae: 2.2676

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3607 - mae: 2.2768

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3293 - mae: 2.2711

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3274 - mae: 2.2701

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4328 - mae: 2.2770

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4318 - mae: 2.2781

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4186 - mae: 2.2763

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4595 - mae: 2.2821

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4565 - mae: 2.2825

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4167 - mae: 2.2783

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4179 - mae: 2.2781

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4355 - mae: 2.2815

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4333 - mae: 2.2843

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4246 - mae: 2.2841

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4248 - mae: 2.2835

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4254 - mae: 2.2834

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4585 - mae: 2.2895

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.4597 - mae: 2.2899 - val_loss: 7.6446 - val_mae: 2.1275

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 54ms/step - loss: 6.0083 - mae: 1.7562

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.4095 - mae: 2.3996

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.8225 - mae: 2.5400

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 10.8076 - mae: 2.6334

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.8656 - mae: 2.4737

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.9669 - mae: 2.3580

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7762 - mae: 2.3405

 56/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2647 - mae: 2.2737

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0951 - mae: 2.2563

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5546 - mae: 2.3006

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2886 - mae: 2.2496

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4242 - mae: 2.2747

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4595 - mae: 2.2759

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4079 - mae: 2.2626

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3790 - mae: 2.2569

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7547 - mae: 2.2862

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0753 - mae: 2.3224

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.9386 - mae: 2.3083

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8737 - mae: 2.3048

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7084 - mae: 2.2825

158/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6432 - mae: 2.2779

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6268 - mae: 2.2858

174/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5584 - mae: 2.2741

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5952 - mae: 2.2802

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5584 - mae: 2.2788

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7818 - mae: 2.3058

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8219 - mae: 2.3091

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7328 - mae: 2.2964

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6828 - mae: 2.2877

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7086 - mae: 2.3003

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7829 - mae: 2.3095

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6992 - mae: 2.2986

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6909 - mae: 2.3018

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6533 - mae: 2.3014

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5893 - mae: 2.2946

273/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5453 - mae: 2.2851

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6282 - mae: 2.2953

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6536 - mae: 2.3031

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6296 - mae: 2.3039

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6258 - mae: 2.2977

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6235 - mae: 2.2981

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7215 - mae: 2.3121

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.7307 - mae: 2.3135

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6830 - mae: 2.3074

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6352 - mae: 2.3015

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6567 - mae: 2.3042

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6026 - mae: 2.2946

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5799 - mae: 2.2919

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5020 - mae: 2.2796

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5176 - mae: 2.2818

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4968 - mae: 2.2809

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4865 - mae: 2.2799

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4803 - mae: 2.2795

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4791 - mae: 2.2814

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4389 - mae: 2.2782

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4029 - mae: 2.2748

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4077 - mae: 2.2713

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4260 - mae: 2.2703

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4622 - mae: 2.2749

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4183 - mae: 2.2700

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4359 - mae: 2.2700

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4526 - mae: 2.2725

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4691 - mae: 2.2762

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4807 - mae: 2.2791

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4664 - mae: 2.2776

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4546 - mae: 2.2765

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4896 - mae: 2.2807

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4819 - mae: 2.2819

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4835 - mae: 2.2835

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4836 - mae: 2.2839

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4478 - mae: 2.2782

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4410 - mae: 2.2789

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4741 - mae: 2.2843

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.4625 - mae: 2.2827 - val_loss: 7.5749 - val_mae: 2.1230

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 42:33 5s/step - loss: 2.4533 - mae: 1.3434

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4348 - mae: 2.1305

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3909 - mae: 2.1537

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9951 - mae: 2.2921

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5133 - mae: 2.2603

 36/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1222 - mae: 2.1850

 42/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9994 - mae: 2.1791

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.2404 - mae: 2.2159

 56/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.2772 - mae: 2.2063

 63/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1462 - mae: 2.2018

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7760 - mae: 2.2457

 75/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9160 - mae: 2.2763

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9570 - mae: 2.2740

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0636 - mae: 2.3001

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8996 - mae: 2.2882

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1427 - mae: 2.3016

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0932 - mae: 2.3014

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0829 - mae: 2.3069

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0181 - mae: 2.3096

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8037 - mae: 2.2830

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0219 - mae: 2.3223

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1312 - mae: 2.3360

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1211 - mae: 2.3294

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0660 - mae: 2.3318

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0718 - mae: 2.3398

174/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9515 - mae: 2.3289

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9330 - mae: 2.3277

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9220 - mae: 2.3276

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9635 - mae: 2.3351

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0790 - mae: 2.3598

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0112 - mae: 2.3480

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0310 - mae: 2.3441

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0600 - mae: 2.3470

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0574 - mae: 2.3483

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0039 - mae: 2.3410

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9153 - mae: 2.3298

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8128 - mae: 2.3151

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7602 - mae: 2.3101

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7263 - mae: 2.3059

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6166 - mae: 2.2892

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6399 - mae: 2.2951

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5716 - mae: 2.2872

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5288 - mae: 2.2807

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5608 - mae: 2.2862

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5711 - mae: 2.2880

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5610 - mae: 2.2854

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5073 - mae: 2.2815

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5924 - mae: 2.2930

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5843 - mae: 2.2902

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5662 - mae: 2.2871

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5511 - mae: 2.2878

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5710 - mae: 2.2920

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5143 - mae: 2.2801

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5782 - mae: 2.2893

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5766 - mae: 2.2907

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5830 - mae: 2.2907

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5637 - mae: 2.2899

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6218 - mae: 2.2930

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6204 - mae: 2.2952

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5566 - mae: 2.2869

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5513 - mae: 2.2870

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6198 - mae: 2.2958

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5839 - mae: 2.2899

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5607 - mae: 2.2867

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5462 - mae: 2.2852

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5744 - mae: 2.2909

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5663 - mae: 2.2883

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5574 - mae: 2.2853

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5328 - mae: 2.2817

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5615 - mae: 2.2865

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5567 - mae: 2.2845

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5797 - mae: 2.2879

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5513 - mae: 2.2839

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5417 - mae: 2.2825

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5601 - mae: 2.2847

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5603 - mae: 2.2856

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5182 - mae: 2.2804

522/522 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - loss: 8.4851 - mae: 2.2754 - val_loss: 9.3910 - val_mae: 2.3700

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 2:55 337ms/step - loss: 7.5791 - mae: 2.0466

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.3413 - mae: 2.0515

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.4745 - mae: 2.0872

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.4733 - mae: 2.1170

 28/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.3562 - mae: 2.1238

 35/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.0815 - mae: 2.0798

 42/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.5890 - mae: 2.1727

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.7951 - mae: 2.1548

 56/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.8924 - mae: 2.1756

 63/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.8072 - mae: 2.1658

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9238 - mae: 2.1503

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1612 - mae: 2.1719

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3072 - mae: 2.1961

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1250 - mae: 2.1902

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.0728 - mae: 2.1868

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9850 - mae: 2.1737

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3894 - mae: 2.2204

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8798 - mae: 2.2742

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6321 - mae: 2.2375

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8223 - mae: 2.2622

139/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7420 - mae: 2.2577

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6224 - mae: 2.2411

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5856 - mae: 2.2466

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7298 - mae: 2.2653

165/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7523 - mae: 2.2707

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8251 - mae: 2.2841

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8944 - mae: 2.3005

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8720 - mae: 2.3024

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9172 - mae: 2.3159

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8100 - mae: 2.3004

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8231 - mae: 2.3056

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8645 - mae: 2.3135

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0611 - mae: 2.3470

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0070 - mae: 2.3459

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0023 - mae: 2.3457

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0054 - mae: 2.3409

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9580 - mae: 2.3389

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9016 - mae: 2.3317

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9310 - mae: 2.3362

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9024 - mae: 2.3341

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8913 - mae: 2.3340

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8738 - mae: 2.3307

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8616 - mae: 2.3276

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8442 - mae: 2.3254

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8472 - mae: 2.3268

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7941 - mae: 2.3176

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7447 - mae: 2.3086

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.8265 - mae: 2.3135

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7820 - mae: 2.3076

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7503 - mae: 2.3055

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7880 - mae: 2.3059

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.7086 - mae: 2.2930

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6718 - mae: 2.2927

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6462 - mae: 2.2887

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6184 - mae: 2.2901

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6154 - mae: 2.2952

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5812 - mae: 2.2924

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5938 - mae: 2.2923

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6074 - mae: 2.2959

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6083 - mae: 2.2944

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5639 - mae: 2.2862

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5001 - mae: 2.2776

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5383 - mae: 2.2804

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5457 - mae: 2.2802

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5317 - mae: 2.2757

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5172 - mae: 2.2734

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5347 - mae: 2.2776

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5276 - mae: 2.2745

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5330 - mae: 2.2781

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4820 - mae: 2.2684

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4734 - mae: 2.2606

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4823 - mae: 2.2628

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4869 - mae: 2.2635

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4974 - mae: 2.2664

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5060 - mae: 2.2683

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5108 - mae: 2.2712

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5731 - mae: 2.2795

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5523 - mae: 2.2794

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5224 - mae: 2.2759

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.4952 - mae: 2.2716 - val_loss: 8.7501 - val_mae: 2.3302

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 18.5296 - mae: 3.3244

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 11.7415 - mae: 2.8088

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.8186 - mae: 2.5765

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 9.6027 - mae: 2.5915

 19/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 9.4667 - mae: 2.5547

 20/522 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 9.1824 - mae: 2.5162

 23/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.8729 - mae: 2.4579

 28/522 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 7.9844 - mae: 2.2786

 32/522 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 8.0125 - mae: 2.3039

 36/522 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 7.9348 - mae: 2.2872

 40/522 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - loss: 7.7365 - mae: 2.2739

 46/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 7.3434 - mae: 2.1996

 51/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 7.0314 - mae: 2.1509

 57/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 7.1950 - mae: 2.1562

 62/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 7.3961 - mae: 2.1757

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 7.2495 - mae: 2.1409

 73/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 7.7354 - mae: 2.1991

 78/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.7705 - mae: 2.2019

 83/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.6906 - mae: 2.1927

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.5944 - mae: 2.1845

 94/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.5702 - mae: 2.1831

100/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.8182 - mae: 2.2090

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 7.9308 - mae: 2.2260

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0737 - mae: 2.2455

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0077 - mae: 2.2431

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0288 - mae: 2.2522

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0229 - mae: 2.2549

142/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0416 - mae: 2.2611

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.1036 - mae: 2.2602

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.9648 - mae: 2.2394

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.8978 - mae: 2.2234

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.7899 - mae: 2.2045

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.7774 - mae: 2.2038

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.8170 - mae: 2.2025

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.9787 - mae: 2.2312

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.9840 - mae: 2.2323

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.9412 - mae: 2.2252

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.8595 - mae: 2.2182

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.0110 - mae: 2.2278

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.0311 - mae: 2.2316

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9535 - mae: 2.2211

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9945 - mae: 2.2257

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1458 - mae: 2.2537

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1459 - mae: 2.2510

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1288 - mae: 2.2528

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1689 - mae: 2.2560

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1894 - mae: 2.2568

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1403 - mae: 2.2500

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1643 - mae: 2.2542

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.1610 - mae: 2.2501

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2162 - mae: 2.2509

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.1947 - mae: 2.2462

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2419 - mae: 2.2500

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2653 - mae: 2.2551

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2492 - mae: 2.2531

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.3014 - mae: 2.2634

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2900 - mae: 2.2627

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2958 - mae: 2.2617

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2638 - mae: 2.2592

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2502 - mae: 2.2567

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2064 - mae: 2.2475

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.1921 - mae: 2.2454

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.2604 - mae: 2.2542

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3087 - mae: 2.2623

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2974 - mae: 2.2616

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2713 - mae: 2.2582

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2743 - mae: 2.2595

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2460 - mae: 2.2555

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2413 - mae: 2.2554

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2418 - mae: 2.2570

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3108 - mae: 2.2619

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2910 - mae: 2.2612

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2528 - mae: 2.2548

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2347 - mae: 2.2524

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2671 - mae: 2.2580

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2452 - mae: 2.2562

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2136 - mae: 2.2520

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2387 - mae: 2.2548

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2719 - mae: 2.2577

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 8.2693 - mae: 2.2573 - val_loss: 7.8690 - val_mae: 2.1845

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 14.5269 - mae: 3.5780

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 11.9899 - mae: 2.7353

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6206 - mae: 2.2820

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7343 - mae: 2.1445

 33/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3496 - mae: 2.2320

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6402 - mae: 2.2709

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7256 - mae: 2.2700

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.9189 - mae: 2.2933

 65/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.7745 - mae: 2.2786

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6291 - mae: 2.2545

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6377 - mae: 2.2627

 89/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1176 - mae: 2.3108

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.1203 - mae: 2.3196

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.0530 - mae: 2.3202

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.8554 - mae: 2.2821

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6554 - mae: 2.2618

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7189 - mae: 2.2694

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7595 - mae: 2.2803

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6353 - mae: 2.2634

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5393 - mae: 2.2556

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.7166 - mae: 2.2791

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6690 - mae: 2.2726

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.6421 - mae: 2.2765

183/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5757 - mae: 2.2777

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5261 - mae: 2.2719

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5331 - mae: 2.2698

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.5539 - mae: 2.2699

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4534 - mae: 2.2575

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3735 - mae: 2.2471

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3511 - mae: 2.2443

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4567 - mae: 2.2619

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5229 - mae: 2.2686

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5677 - mae: 2.2752

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5967 - mae: 2.2816

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.6042 - mae: 2.2868

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5798 - mae: 2.2871

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4958 - mae: 2.2751

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4232 - mae: 2.2644

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5544 - mae: 2.2754

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5833 - mae: 2.2824

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5261 - mae: 2.2725

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5241 - mae: 2.2711

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4554 - mae: 2.2622

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4745 - mae: 2.2698

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4781 - mae: 2.2714

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4316 - mae: 2.2632

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4881 - mae: 2.2722

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4753 - mae: 2.2710

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4712 - mae: 2.2718

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4751 - mae: 2.2726

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4903 - mae: 2.2744

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.4720 - mae: 2.2718

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.5118 - mae: 2.2774

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4968 - mae: 2.2753

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4506 - mae: 2.2689

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5493 - mae: 2.2806

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5506 - mae: 2.2820

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6128 - mae: 2.2877

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5603 - mae: 2.2791

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5122 - mae: 2.2727

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.5084 - mae: 2.2757

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4969 - mae: 2.2751

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4519 - mae: 2.2689

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4309 - mae: 2.2653

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4125 - mae: 2.2645

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4308 - mae: 2.2682

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4332 - mae: 2.2673

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4307 - mae: 2.2691

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4388 - mae: 2.2709

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4530 - mae: 2.2746

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4263 - mae: 2.2739

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4174 - mae: 2.2717

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4700 - mae: 2.2774

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 8.4699 - mae: 2.2776 - val_loss: 7.7278 - val_mae: 2.1577

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 2.8465 - mae: 1.5431

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.4103 - mae: 2.4053

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.1641 - mae: 2.5175

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.7612 - mae: 2.5852

 28/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9878 - mae: 2.4456

 35/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3853 - mae: 2.3599

 42/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1394 - mae: 2.3040

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.6853 - mae: 2.2450

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.2634 - mae: 2.3034

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6048 - mae: 2.3401

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.2533 - mae: 2.2843

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2788 - mae: 2.2782

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2341 - mae: 2.2811

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2722 - mae: 2.2918

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1193 - mae: 2.2820

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0460 - mae: 2.2728

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9958 - mae: 2.2680

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8827 - mae: 2.2442

131/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8958 - mae: 2.2358

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8378 - mae: 2.2268

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8509 - mae: 2.2317

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8248 - mae: 2.2265

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8040 - mae: 2.2182

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.7273 - mae: 2.2146

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8184 - mae: 2.2180

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8331 - mae: 2.2197

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8646 - mae: 2.2218

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9176 - mae: 2.2288

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9105 - mae: 2.2281

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9847 - mae: 2.2337

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0139 - mae: 2.2424

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9662 - mae: 2.2352

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1005 - mae: 2.2501

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0449 - mae: 2.2423

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0202 - mae: 2.2402

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9357 - mae: 2.2295

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9177 - mae: 2.2281

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8558 - mae: 2.2202

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9529 - mae: 2.2293

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0021 - mae: 2.2320

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0157 - mae: 2.2346

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9915 - mae: 2.2302

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9678 - mae: 2.2259

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0142 - mae: 2.2336

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0039 - mae: 2.2359

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9416 - mae: 2.2297

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8880 - mae: 2.2193

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9464 - mae: 2.2267

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8412 - mae: 2.2081

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8348 - mae: 2.2043

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8265 - mae: 2.2071

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9330 - mae: 2.2164

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0112 - mae: 2.2225

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0516 - mae: 2.2281

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1015 - mae: 2.2353

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1968 - mae: 2.2452

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1852 - mae: 2.2468

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2190 - mae: 2.2499

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2373 - mae: 2.2489

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2479 - mae: 2.2504

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2300 - mae: 2.2479

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2090 - mae: 2.2423

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1833 - mae: 2.2389

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3048 - mae: 2.2540

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2956 - mae: 2.2527

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2961 - mae: 2.2550

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2720 - mae: 2.2536

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2548 - mae: 2.2529

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3034 - mae: 2.2592

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2523 - mae: 2.2519

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2935 - mae: 2.2597

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.2571 - mae: 2.2561

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 8.2301 - mae: 2.2534 - val_loss: 7.5162 - val_mae: 2.1303

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - loss: 1.9062 - mae: 1.1553

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8835 - mae: 1.8741

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4979 - mae: 1.7392

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7475 - mae: 1.9071

 31/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0284 - mae: 1.9734

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2848 - mae: 2.0227

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0726 - mae: 2.0377

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2655 - mae: 2.0780

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4587 - mae: 2.1028

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7358 - mae: 2.1680

 76/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5003 - mae: 2.1534

 83/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3714 - mae: 2.1315

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4174 - mae: 2.1543

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4275 - mae: 2.1700

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.5016 - mae: 2.1860

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.5651 - mae: 2.1873

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.3359 - mae: 2.1439

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.3762 - mae: 2.1505

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.6081 - mae: 2.1838

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.6875 - mae: 2.1988

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6048 - mae: 2.1885

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.5902 - mae: 2.1926

155/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6086 - mae: 2.1984

162/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6526 - mae: 2.2028

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6776 - mae: 2.2054

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7415 - mae: 2.2148

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6625 - mae: 2.1986

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.5754 - mae: 2.1800

201/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7894 - mae: 2.1952

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8173 - mae: 2.2012

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8335 - mae: 2.2050

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7486 - mae: 2.1912

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7355 - mae: 2.1889

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7361 - mae: 2.1891

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6802 - mae: 2.1823

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6807 - mae: 2.1798

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8547 - mae: 2.2041

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.8307 - mae: 2.2024

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7847 - mae: 2.1948

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7022 - mae: 2.1820

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6926 - mae: 2.1810

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6641 - mae: 2.1724

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7009 - mae: 2.1793

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6864 - mae: 2.1764

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7190 - mae: 2.1833

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7011 - mae: 2.1806

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7482 - mae: 2.1864

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7220 - mae: 2.1822

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6758 - mae: 2.1748

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6820 - mae: 2.1698

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6510 - mae: 2.1686

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7301 - mae: 2.1791

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7915 - mae: 2.1865

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.8085 - mae: 2.1916

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.8287 - mae: 2.1978

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.8751 - mae: 2.2053

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8937 - mae: 2.2096

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8732 - mae: 2.2044

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8389 - mae: 2.2012

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7775 - mae: 2.1909

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7686 - mae: 2.1909

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8036 - mae: 2.1961

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7793 - mae: 2.1905

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7682 - mae: 2.1893

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7933 - mae: 2.1941

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7893 - mae: 2.1930

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8228 - mae: 2.1987

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8062 - mae: 2.1950

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8226 - mae: 2.1946

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9204 - mae: 2.2050

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9376 - mae: 2.2056

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8861 - mae: 2.1990

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9204 - mae: 2.2045

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9171 - mae: 2.2043

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9425 - mae: 2.2053

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9147 - mae: 2.2014

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 7.9147 - mae: 2.2014 - val_loss: 7.5893 - val_mae: 2.1611

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 6.2343 - mae: 1.8453

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1066 - mae: 2.4003

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5763 - mae: 2.4639

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.6040 - mae: 2.5335

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3820 - mae: 2.3037

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9137 - mae: 2.2336

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7159 - mae: 2.1983

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7306 - mae: 2.2045

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1950 - mae: 2.1279

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2475 - mae: 2.1256

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2399 - mae: 2.1222

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1373 - mae: 2.1015

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4636 - mae: 2.1493

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3635 - mae: 2.1466

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3621 - mae: 2.1418

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2674 - mae: 2.1377

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3465 - mae: 2.1465

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4362 - mae: 2.1654

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6456 - mae: 2.1925

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6511 - mae: 2.1996

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.7183 - mae: 2.2111

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5934 - mae: 2.1908

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5842 - mae: 2.1906

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.7218 - mae: 2.2131

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8784 - mae: 2.2286

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.8924 - mae: 2.2347

187/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.9283 - mae: 2.2314

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1025 - mae: 2.2487

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1103 - mae: 2.2561

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1701 - mae: 2.2579

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1204 - mae: 2.2590

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1187 - mae: 2.2541

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0720 - mae: 2.2519

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0218 - mae: 2.2462

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.0041 - mae: 2.2442

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8823 - mae: 2.2235

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8719 - mae: 2.2215

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8568 - mae: 2.2229

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9358 - mae: 2.2339

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9602 - mae: 2.2377

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9697 - mae: 2.2428

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9645 - mae: 2.2437

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9739 - mae: 2.2421

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9944 - mae: 2.2480

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9185 - mae: 2.2338

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9278 - mae: 2.2340

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9589 - mae: 2.2358

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0070 - mae: 2.2369

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9599 - mae: 2.2287

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9449 - mae: 2.2281

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9152 - mae: 2.2218

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9628 - mae: 2.2315

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8974 - mae: 2.2225

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8947 - mae: 2.2219

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9471 - mae: 2.2311

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0117 - mae: 2.2410

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0403 - mae: 2.2426

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0573 - mae: 2.2422

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0179 - mae: 2.2340

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0224 - mae: 2.2332

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0298 - mae: 2.2307

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0172 - mae: 2.2308

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0425 - mae: 2.2342

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1174 - mae: 2.2434

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0948 - mae: 2.2417

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0873 - mae: 2.2420

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0734 - mae: 2.2402

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1620 - mae: 2.2490

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1680 - mae: 2.2472

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1405 - mae: 2.2444

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1495 - mae: 2.2454

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1580 - mae: 2.2462

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1741 - mae: 2.2508

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 8.1862 - mae: 2.2525 - val_loss: 8.3080 - val_mae: 2.2939

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 57ms/step - loss: 5.5834 - mae: 2.1913

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2479 - mae: 2.1482

 16/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0783 - mae: 2.3025

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2924 - mae: 2.1966

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3338 - mae: 2.2133

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2728 - mae: 2.1706

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2168 - mae: 2.1592

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1657 - mae: 2.1577

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5617 - mae: 2.2139

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2290 - mae: 2.1500

 76/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2869 - mae: 2.1477

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4025 - mae: 2.1566

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3769 - mae: 2.1531

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4691 - mae: 2.1492

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6339 - mae: 2.1777

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4439 - mae: 2.1440

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3654 - mae: 2.1333

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3559 - mae: 2.1400

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4552 - mae: 2.1632

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4563 - mae: 2.1588

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4078 - mae: 2.1544

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4871 - mae: 2.1510

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4774 - mae: 2.1524

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4463 - mae: 2.1486

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3021 - mae: 2.1299

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2640 - mae: 2.1275

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3006 - mae: 2.1374

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2708 - mae: 2.1307

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3711 - mae: 2.1521

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3858 - mae: 2.1584

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3797 - mae: 2.1567

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3293 - mae: 2.1536

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3621 - mae: 2.1596

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3473 - mae: 2.1571

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5328 - mae: 2.1729

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5182 - mae: 2.1743

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5365 - mae: 2.1777

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6496 - mae: 2.1895

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7194 - mae: 2.1956

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7203 - mae: 2.1979

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7570 - mae: 2.1978

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7944 - mae: 2.2027

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8184 - mae: 2.2070

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9284 - mae: 2.2173

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9241 - mae: 2.2113

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9918 - mae: 2.2209

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.9494 - mae: 2.2177

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0042 - mae: 2.2274

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0254 - mae: 2.2309

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1188 - mae: 2.2430

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0636 - mae: 2.2349

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.0471 - mae: 2.2335

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0131 - mae: 2.2304

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0337 - mae: 2.2326

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0248 - mae: 2.2308

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0297 - mae: 2.2314

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0005 - mae: 2.2257

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9924 - mae: 2.2244

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9857 - mae: 2.2250

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9449 - mae: 2.2177

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9319 - mae: 2.2172

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8818 - mae: 2.2085

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8660 - mae: 2.2072

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8408 - mae: 2.2044

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8253 - mae: 2.2046

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8471 - mae: 2.2061

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8447 - mae: 2.2071

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8459 - mae: 2.2060

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8648 - mae: 2.2081

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8476 - mae: 2.2012

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8703 - mae: 2.2034

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.8549 - mae: 2.2012 - val_loss: 8.0396 - val_mae: 2.2027

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 23s 46ms/step - loss: 17.9702 - mae: 3.4817

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.4960 - mae: 2.3050

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.0227 - mae: 2.2255

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5653 - mae: 2.2645

 31/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.1894 - mae: 2.2389

 39/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2224 - mae: 2.2342

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0492 - mae: 2.2156

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9358 - mae: 2.2077

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8062 - mae: 2.1907

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3939 - mae: 2.1292

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4610 - mae: 2.1482

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3494 - mae: 2.1338

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2767 - mae: 2.1331

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2691 - mae: 2.1288

110/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5523 - mae: 2.1653

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3773 - mae: 2.1412

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2715 - mae: 2.1215

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2088 - mae: 2.1069

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1989 - mae: 2.1050

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1020 - mae: 2.0835

158/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0533 - mae: 2.0738

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3262 - mae: 2.1092

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3217 - mae: 2.1135

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2570 - mae: 2.1093

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3530 - mae: 2.1216

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3479 - mae: 2.1219

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4811 - mae: 2.1468

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5107 - mae: 2.1451

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5841 - mae: 2.1539

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5132 - mae: 2.1471

237/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4729 - mae: 2.1423

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4170 - mae: 2.1329

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3413 - mae: 2.1206

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3886 - mae: 2.1352

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3591 - mae: 2.1320

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3086 - mae: 2.1257

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4058 - mae: 2.1340

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4510 - mae: 2.1416

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4517 - mae: 2.1446

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5041 - mae: 2.1511

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5202 - mae: 2.1536

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5607 - mae: 2.1649

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6115 - mae: 2.1668

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7009 - mae: 2.1781

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7116 - mae: 2.1796

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7150 - mae: 2.1803

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7466 - mae: 2.1862

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7352 - mae: 2.1877

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6771 - mae: 2.1776

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6448 - mae: 2.1744

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6602 - mae: 2.1729

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6349 - mae: 2.1698

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6110 - mae: 2.1682

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6096 - mae: 2.1697

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6443 - mae: 2.1759

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7310 - mae: 2.1860

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7017 - mae: 2.1851

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6826 - mae: 2.1840

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7093 - mae: 2.1864

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6956 - mae: 2.1870

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7472 - mae: 2.1906

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7300 - mae: 2.1877

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7129 - mae: 2.1838

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6704 - mae: 2.1767

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6779 - mae: 2.1725

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7206 - mae: 2.1819

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7287 - mae: 2.1840

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6926 - mae: 2.1793

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6936 - mae: 2.1816

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6844 - mae: 2.1790

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.6895 - mae: 2.1781 - val_loss: 7.7369 - val_mae: 2.1770

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 1.8022 - mae: 0.8888

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.2007 - mae: 2.0219

 16/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.3101 - mae: 2.3540

 23/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8949 - mae: 2.1083

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.4038 - mae: 2.0280

 37/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.2712 - mae: 1.9872

 44/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.5033 - mae: 2.0425

 52/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1630 - mae: 2.1133

 58/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0203 - mae: 2.0905

 65/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2929 - mae: 2.1421

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3548 - mae: 2.1591

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5953 - mae: 2.1827

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8010 - mae: 2.2134

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.6392 - mae: 2.1991

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7454 - mae: 2.2191

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.6185 - mae: 2.1977

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3638 - mae: 2.1466

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3601 - mae: 2.1457

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4232 - mae: 2.1495

139/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4937 - mae: 2.1671

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.5686 - mae: 2.1655

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.6170 - mae: 2.1728

162/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4432 - mae: 2.1507

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4274 - mae: 2.1477

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3463 - mae: 2.1390

183/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2029 - mae: 2.1148

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3150 - mae: 2.1304

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3761 - mae: 2.1359

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3994 - mae: 2.1369

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3521 - mae: 2.1326

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3310 - mae: 2.1263

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4294 - mae: 2.1357

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4282 - mae: 2.1374

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3479 - mae: 2.1281

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5323 - mae: 2.1479

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5720 - mae: 2.1545

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5794 - mae: 2.1526

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.5571 - mae: 2.1502

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6313 - mae: 2.1607

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7372 - mae: 2.1764

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7752 - mae: 2.1842

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6956 - mae: 2.1737

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6266 - mae: 2.1629

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7108 - mae: 2.1727

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.6999 - mae: 2.1722

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7513 - mae: 2.1750

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7287 - mae: 2.1735

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7235 - mae: 2.1765

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7991 - mae: 2.1887

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.8320 - mae: 2.1939

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7574 - mae: 2.1818

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7777 - mae: 2.1853

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.7501 - mae: 2.1803

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6918 - mae: 2.1704

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6173 - mae: 2.1587

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5767 - mae: 2.1554

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5651 - mae: 2.1560

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5248 - mae: 2.1493

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4706 - mae: 2.1427

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4408 - mae: 2.1386

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4600 - mae: 2.1404

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4108 - mae: 2.1348

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4320 - mae: 2.1374

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4376 - mae: 2.1389

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4859 - mae: 2.1465

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4861 - mae: 2.1503

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4618 - mae: 2.1466

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4719 - mae: 2.1500

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4989 - mae: 2.1510

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5143 - mae: 2.1548

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5051 - mae: 2.1555

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5384 - mae: 2.1561

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.5500 - mae: 2.1572 - val_loss: 7.5467 - val_mae: 2.1501

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 6:37 763ms/step - loss: 2.2918 - mae: 1.4230

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0234 - mae: 2.0584

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3808 - mae: 2.1298

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0482 - mae: 2.1087

 32/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8064 - mae: 2.0982

 39/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2949 - mae: 2.0435

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9625 - mae: 2.0013

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2428 - mae: 2.0383

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1602 - mae: 2.0485

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7593 - mae: 1.9840

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7976 - mae: 1.9907

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.5817 - mae: 1.9674

 89/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7076 - mae: 1.9855

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9026 - mae: 2.0219

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9939 - mae: 2.0225

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1120 - mae: 2.0575

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0146 - mae: 2.0518

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9730 - mae: 2.0486

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9065 - mae: 2.0384

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8404 - mae: 2.0314

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7692 - mae: 2.0224

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7502 - mae: 2.0261

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7207 - mae: 2.0324

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.6558 - mae: 2.0230

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.6633 - mae: 2.0192

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7838 - mae: 2.0256

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8736 - mae: 2.0447

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8865 - mae: 2.0502

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9375 - mae: 2.0579

216/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9769 - mae: 2.0666

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9726 - mae: 2.0702

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0020 - mae: 2.0827

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0690 - mae: 2.0828

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1487 - mae: 2.0925

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1773 - mae: 2.0967

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1746 - mae: 2.0987

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1709 - mae: 2.0972

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1360 - mae: 2.0958

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2450 - mae: 2.1130

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2812 - mae: 2.1165

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2670 - mae: 2.1114

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2521 - mae: 2.1077

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2931 - mae: 2.1082

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2390 - mae: 2.1001

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2761 - mae: 2.1058

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3190 - mae: 2.1059

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2990 - mae: 2.1032

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3449 - mae: 2.1094

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3878 - mae: 2.1169

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3409 - mae: 2.1109

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3463 - mae: 2.1134

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4031 - mae: 2.1186

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4050 - mae: 2.1206

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4416 - mae: 2.1257

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4643 - mae: 2.1262

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5260 - mae: 2.1344

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5854 - mae: 2.1459

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5985 - mae: 2.1522

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5737 - mae: 2.1499

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5497 - mae: 2.1437

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5354 - mae: 2.1429

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5999 - mae: 2.1511

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6150 - mae: 2.1545

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6792 - mae: 2.1628

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6815 - mae: 2.1654

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6144 - mae: 2.1559

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6138 - mae: 2.1580

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6157 - mae: 2.1580

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6041 - mae: 2.1571

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6222 - mae: 2.1592

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6105 - mae: 2.1578

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - loss: 7.6076 - mae: 2.1568 - val_loss: 8.1465 - val_mae: 2.2189

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 58ms/step - loss: 8.0820 - mae: 2.2781

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3005 - mae: 2.0905

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9426 - mae: 2.2460

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.1460 - mae: 2.1456

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9521 - mae: 2.0706

 36/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0543 - mae: 2.1753

 44/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7873 - mae: 2.1543

 51/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5143 - mae: 2.1179

 59/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2254 - mae: 2.0835

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2067 - mae: 2.0717

 75/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0057 - mae: 2.0351

 83/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7795 - mae: 2.0091

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8911 - mae: 2.0270

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9562 - mae: 2.0472

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0919 - mae: 2.0679

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3352 - mae: 2.1024

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3820 - mae: 2.1207

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3963 - mae: 2.1311

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4466 - mae: 2.1294

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3689 - mae: 2.1244

148/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4972 - mae: 2.1432

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4117 - mae: 2.1353

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4451 - mae: 2.1446

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4725 - mae: 2.1511

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3758 - mae: 2.1382

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3328 - mae: 2.1348

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3188 - mae: 2.1333

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2266 - mae: 2.1180

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1429 - mae: 2.1044

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.1485 - mae: 2.1093

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.1234 - mae: 2.1088

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.0652 - mae: 2.1008

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.9803 - mae: 2.0869

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.0051 - mae: 2.0930

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.9652 - mae: 2.0853

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.9342 - mae: 2.0834

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.9908 - mae: 2.0881

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.9100 - mae: 2.0742

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8478 - mae: 2.0652

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8948 - mae: 2.0739

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8902 - mae: 2.0681

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8237 - mae: 2.0552

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8304 - mae: 2.0581

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.7966 - mae: 2.0558

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.8453 - mae: 2.0619

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.9617 - mae: 2.0763

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0374 - mae: 2.0860

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0033 - mae: 2.0807

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.9594 - mae: 2.0724

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0114 - mae: 2.0722

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0236 - mae: 2.0747

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0711 - mae: 2.0840

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.0827 - mae: 2.0869

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.1373 - mae: 2.0959

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.1336 - mae: 2.0980

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.2541 - mae: 2.1069

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.2306 - mae: 2.1025

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.1928 - mae: 2.0978

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.2119 - mae: 2.1038

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.1897 - mae: 2.0992

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.2363 - mae: 2.1068

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3005 - mae: 2.1126

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3870 - mae: 2.1263

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3762 - mae: 2.1251

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3490 - mae: 2.1217

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3289 - mae: 2.1203

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4365 - mae: 2.1355

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4788 - mae: 2.1393

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4832 - mae: 2.1402

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4930 - mae: 2.1404

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5032 - mae: 2.1415

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5379 - mae: 2.1473

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5546 - mae: 2.1515

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5464 - mae: 2.1494

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5504 - mae: 2.1489

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5486 - mae: 2.1477

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5287 - mae: 2.1459

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5188 - mae: 2.1438

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 7.5248 - mae: 2.1438 - val_loss: 7.7763 - val_mae: 2.1807

Epoch 22/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 7.0347 - mae: 2.0318

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5077 - mae: 2.4139

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8686 - mae: 2.0716

 23/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.6653 - mae: 2.0227

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0067 - mae: 2.1244

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7313 - mae: 2.1969

 46/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9965 - mae: 2.1988

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.2140 - mae: 2.2340

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.5800 - mae: 2.2442

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.0864 - mae: 2.1804

 76/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.9000 - mae: 2.1559

 82/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.8773 - mae: 2.1617

 89/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5617 - mae: 2.1154

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.4537 - mae: 2.1042

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.3847 - mae: 2.0990

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.2958 - mae: 2.0911

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2008 - mae: 2.0810

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1108 - mae: 2.0703

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1659 - mae: 2.0782

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1710 - mae: 2.0898

149/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2470 - mae: 2.1075

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1713 - mae: 2.0934

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3190 - mae: 2.0986

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2773 - mae: 2.0989

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1884 - mae: 2.0938

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0988 - mae: 2.0860

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0630 - mae: 2.0767

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1094 - mae: 2.0835

207/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0902 - mae: 2.0826

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0891 - mae: 2.0840

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0441 - mae: 2.0837

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9831 - mae: 2.0754

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0266 - mae: 2.0787

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0420 - mae: 2.0782

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9793 - mae: 2.0675

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9985 - mae: 2.0708

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0351 - mae: 2.0769

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0670 - mae: 2.0781

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0544 - mae: 2.0813

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0169 - mae: 2.0770

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9535 - mae: 2.0698

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9686 - mae: 2.0741

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9571 - mae: 2.0703

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9719 - mae: 2.0724

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9698 - mae: 2.0699

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9671 - mae: 2.0726

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0897 - mae: 2.0921

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1419 - mae: 2.1010

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1355 - mae: 2.1008

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0886 - mae: 2.0938

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1179 - mae: 2.0970

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1685 - mae: 2.1001

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1894 - mae: 2.1032

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1704 - mae: 2.0993

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1928 - mae: 2.1034

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1613 - mae: 2.0995

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1691 - mae: 2.1007

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1711 - mae: 2.1002

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1373 - mae: 2.0960

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1937 - mae: 2.1013

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2290 - mae: 2.1056

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1841 - mae: 2.0975

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2056 - mae: 2.1001

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2216 - mae: 2.1017

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3097 - mae: 2.1106

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3326 - mae: 2.1156

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2801 - mae: 2.1075

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2696 - mae: 2.1066

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3240 - mae: 2.1142

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3979 - mae: 2.1213

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4459 - mae: 2.1262

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.4492 - mae: 2.1265 - val_loss: 8.4660 - val_mae: 2.2537

Epoch 23/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - loss: 8.9121 - mae: 2.2599

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 8.6286 - mae: 2.2313

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.7412 - mae: 2.1380

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.5412 - mae: 2.1220

 33/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7584 - mae: 1.9851

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8165 - mae: 1.9945

 49/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7933 - mae: 1.9928

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7832 - mae: 2.0074

 65/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.6780 - mae: 1.9992

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.6937 - mae: 2.0123

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0864 - mae: 2.0729

 89/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9655 - mae: 2.0568

 97/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7943 - mae: 2.0391

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9651 - mae: 2.0523

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1202 - mae: 2.0855

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0709 - mae: 2.0890

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1037 - mae: 2.0915

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1290 - mae: 2.0941

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1742 - mae: 2.1085

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2220 - mae: 2.1089

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1650 - mae: 2.1093

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3589 - mae: 2.1385

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3175 - mae: 2.1283

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1573 - mae: 2.1050

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1571 - mae: 2.1115

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1318 - mae: 2.1074

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2016 - mae: 2.1257

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2308 - mae: 2.1326

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1975 - mae: 2.1291

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2957 - mae: 2.1334

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2402 - mae: 2.1299

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2101 - mae: 2.1226

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2272 - mae: 2.1219

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2343 - mae: 2.1207

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2646 - mae: 2.1290

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2691 - mae: 2.1273

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2557 - mae: 2.1284

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.2431 - mae: 2.1257

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1857 - mae: 2.1187

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.1314 - mae: 2.1115

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0991 - mae: 2.1079

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0846 - mae: 2.1056

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0162 - mae: 2.0959

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9808 - mae: 2.0925

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6.9740 - mae: 2.0905

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0183 - mae: 2.0959

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0107 - mae: 2.0922

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0393 - mae: 2.0979

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.0093 - mae: 2.0918

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0053 - mae: 2.0939

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.9974 - mae: 2.0912

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0126 - mae: 2.0940

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1390 - mae: 2.1089

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1313 - mae: 2.1067

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1636 - mae: 2.1112

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1822 - mae: 2.1156

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2170 - mae: 2.1158

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1727 - mae: 2.1093

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1681 - mae: 2.1110

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1963 - mae: 2.1143

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1772 - mae: 2.1118

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1673 - mae: 2.1093

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1375 - mae: 2.1011

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1553 - mae: 2.1037

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1380 - mae: 2.1004

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1435 - mae: 2.1016

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1159 - mae: 2.0969

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1239 - mae: 2.0979

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1666 - mae: 2.1042

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1415 - mae: 2.0989

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1105 - mae: 2.0942

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0765 - mae: 2.0890

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 7.0754 - mae: 2.0890 - val_loss: 7.8186 - val_mae: 2.1638

Epoch 24/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - loss: 5.0797 - mae: 1.8476

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7803 - mae: 1.9234

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7791 - mae: 2.2069

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9873 - mae: 2.1031

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.3664 - mae: 2.1437

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5948 - mae: 2.2834

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5264 - mae: 2.2641

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.1396 - mae: 2.2140

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.8806 - mae: 2.1946

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7793 - mae: 2.1995

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.5754 - mae: 2.1669

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.5167 - mae: 2.1455

 75/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.5379 - mae: 2.1512

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5843 - mae: 2.1653

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3941 - mae: 2.1280

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6455 - mae: 2.1457

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7413 - mae: 2.1583

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.9511 - mae: 2.1820

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7598 - mae: 2.1597

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6905 - mae: 2.1533

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7362 - mae: 2.1568

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6537 - mae: 2.1446

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.9636 - mae: 2.1875

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8160 - mae: 2.1663

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7365 - mae: 2.1642

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6408 - mae: 2.1470

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6419 - mae: 2.1508

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5823 - mae: 2.1425

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5005 - mae: 2.1275

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4926 - mae: 2.1266

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5205 - mae: 2.1193

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5029 - mae: 2.1198

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.5346 - mae: 2.1232

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.4484 - mae: 2.1083

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3386 - mae: 2.0939

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2946 - mae: 2.0913

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2479 - mae: 2.0828

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2754 - mae: 2.0861

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2472 - mae: 2.0875

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2141 - mae: 2.0864

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2164 - mae: 2.0811

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1102 - mae: 2.0647

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0831 - mae: 2.0609

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0210 - mae: 2.0544

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9743 - mae: 2.0509

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9504 - mae: 2.0494

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8671 - mae: 2.0357

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8835 - mae: 2.0388

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8667 - mae: 2.0362

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9297 - mae: 2.0496

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9684 - mae: 2.0554

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9357 - mae: 2.0499

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0482 - mae: 2.0592

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0408 - mae: 2.0630

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0409 - mae: 2.0599

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0164 - mae: 2.0565

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9644 - mae: 2.0480

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9402 - mae: 2.0445

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9045 - mae: 2.0397

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9281 - mae: 2.0454

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9850 - mae: 2.0504

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9523 - mae: 2.0478

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9313 - mae: 2.0471

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9573 - mae: 2.0507

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9317 - mae: 2.0496

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9047 - mae: 2.0490

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.8849 - mae: 2.0471

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9026 - mae: 2.0513

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9267 - mae: 2.0532

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.8996 - mae: 2.0493

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9176 - mae: 2.0513

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9404 - mae: 2.0538

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0476 - mae: 2.0670

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0321 - mae: 2.0655

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0342 - mae: 2.0675

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0192 - mae: 2.0661

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0064 - mae: 2.0635

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9843 - mae: 2.0592

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9976 - mae: 2.0609

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9700 - mae: 2.0575

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9684 - mae: 2.0594

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9588 - mae: 2.0591

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9507 - mae: 2.0571

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0710 - mae: 2.0724

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.0613 - mae: 2.0715 - val_loss: 8.2420 - val_mae: 2.2570

Epoch 24: early stopping

Restoring model weights from the end of the best epoch: 14.

In [18]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 11s 1s/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 99ms/step

MAE:  2.087284488309154

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM two layer model

In [19]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(Conv1D(filters=32, kernel_size=3)) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(LSTM(30,
               return_sequences=True, # remember, if stacking layers, you need to return sequences!
               input_shape=(n_steps,n_features),
               activation='relu'))
model.add(Dropout(0.1))
model.add(LSTM(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)
# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 1:23:47 10s/step - loss: 168.5463 - mae: 12.6301

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 128.9238 - mae: 10.5577

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 90.7943 - mae: 8.2672

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 67.8415 - mae: 6.6779

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 59.0770 - mae: 6.0964

 27/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 51.6040 - mae: 5.5711

 32/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 50.9211 - mae: 5.4985

 37/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 47.3491 - mae: 5.2355

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 44.3961 - mae: 5.0686

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 41.6095 - mae: 4.8963

 52/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 39.0782 - mae: 4.7229

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 37.7820 - mae: 4.6336

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 36.8777 - mae: 4.5690

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 35.6338 - mae: 4.4864

 74/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 34.4066 - mae: 4.3953

 80/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 33.0970 - mae: 4.3002

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 31.7430 - mae: 4.1878

 91/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 31.8670 - mae: 4.1977

 96/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 31.8390 - mae: 4.1976

101/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 31.6815 - mae: 4.2011

106/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 30.8896 - mae: 4.1481

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 30.2629 - mae: 4.1159

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 29.7760 - mae: 4.0943

121/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 29.2465 - mae: 4.0589

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 29.0888 - mae: 4.0452

131/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 29.0033 - mae: 4.0306

137/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 28.3856 - mae: 3.9863

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 27.7284 - mae: 3.9336

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 27.3828 - mae: 3.9137

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 27.0389 - mae: 3.8846

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 26.8593 - mae: 3.8851

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 26.4517 - mae: 3.8501

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 26.1419 - mae: 3.8263

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 25.7845 - mae: 3.7929

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 25.2807 - mae: 3.7494

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 25.0061 - mae: 3.7409

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 24.8747 - mae: 3.7402

196/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 24.5429 - mae: 3.7099

201/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 24.1938 - mae: 3.6813

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 23.9108 - mae: 3.6613

212/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 23.6070 - mae: 3.6344

218/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 23.2150 - mae: 3.5996

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 23.0648 - mae: 3.5887

229/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 22.9756 - mae: 3.5814

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.8144 - mae: 3.5800

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.4876 - mae: 3.5522

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.4990 - mae: 3.5438

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.4856 - mae: 3.5475

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.4304 - mae: 3.5453

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.2589 - mae: 3.5372

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 22.1278 - mae: 3.5243

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.8650 - mae: 3.5002

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.7090 - mae: 3.4877

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.5713 - mae: 3.4815

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.3863 - mae: 3.4701

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.1507 - mae: 3.4454

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 21.1006 - mae: 3.4425

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 20.9630 - mae: 3.4302

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 20.8151 - mae: 3.4213

322/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 20.7030 - mae: 3.4114

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 20.5843 - mae: 3.4051

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 20.3866 - mae: 3.3889

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 20.2567 - mae: 3.3782

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 20.1133 - mae: 3.3676

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 20.0274 - mae: 3.3622

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.9011 - mae: 3.3535

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.8042 - mae: 3.3455

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.8037 - mae: 3.3488

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.9453 - mae: 3.3603

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.8203 - mae: 3.3515

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.6041 - mae: 3.3312

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.4942 - mae: 3.3214

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.3556 - mae: 3.3132

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.2627 - mae: 3.3099

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.1475 - mae: 3.2994

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.0978 - mae: 3.2975

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.0018 - mae: 3.2910

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.9401 - mae: 3.2892

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.8673 - mae: 3.2819

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.7751 - mae: 3.2724

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.7169 - mae: 3.2666

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.6311 - mae: 3.2586

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.6112 - mae: 3.2598

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.4621 - mae: 3.2459

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.3503 - mae: 3.2389

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.2428 - mae: 3.2292

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.1630 - mae: 3.2219

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.1900 - mae: 3.2248

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.1328 - mae: 3.2232

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.0298 - mae: 3.2156

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.9929 - mae: 3.2124

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.9613 - mae: 3.2100

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.8362 - mae: 3.1981

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.7744 - mae: 3.1951

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.6519 - mae: 3.1825

522/522 ━━━━━━━━━━━━━━━━━━━━ 17s 14ms/step - loss: 17.6455 - mae: 3.1817 - val_loss: 7.3918 - val_mae: 2.1084

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 21.9855 - mae: 3.7443

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 13.4412 - mae: 2.9389

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.8352 - mae: 2.6689

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.8242 - mae: 2.6720

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.0104 - mae: 2.5478

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.0940 - mae: 2.6770

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.6859 - mae: 2.6342

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.1159 - mae: 2.6098

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.2865 - mae: 2.6297

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.3255 - mae: 2.6173

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.7047 - mae: 2.5336

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.8266 - mae: 2.5636

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.8028 - mae: 2.5742

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.7103 - mae: 2.5741

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.0554 - mae: 2.6251

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1797 - mae: 2.6655

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.3838 - mae: 2.6864

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.5226 - mae: 2.6878

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.3620 - mae: 2.6630

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.2530 - mae: 2.6558

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.3383 - mae: 2.6753

125/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1598 - mae: 2.6486

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1915 - mae: 2.6474

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1861 - mae: 2.6443

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.2791 - mae: 2.6534

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1797 - mae: 2.6301

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1171 - mae: 2.6266

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.0914 - mae: 2.6215

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.0702 - mae: 2.6180

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1757 - mae: 2.6297

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.3193 - mae: 2.6407

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1939 - mae: 2.6180

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 11.1149 - mae: 2.6086

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1608 - mae: 2.6104

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.3345 - mae: 2.6239

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.3787 - mae: 2.6314

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.3500 - mae: 2.6294

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2804 - mae: 2.6255

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1934 - mae: 2.6177

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2020 - mae: 2.6188

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2063 - mae: 2.6151

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1965 - mae: 2.6089

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1780 - mae: 2.6127

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1088 - mae: 2.6017

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0838 - mae: 2.5941

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1095 - mae: 2.5968

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0518 - mae: 2.5877

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 10.9851 - mae: 2.5755

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0160 - mae: 2.5831

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1201 - mae: 2.5978

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2467 - mae: 2.6065

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2774 - mae: 2.6102

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.2750 - mae: 2.6110

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.2645 - mae: 2.6172

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.3168 - mae: 2.6246

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.2274 - mae: 2.6159

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.1839 - mae: 2.6100

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.1778 - mae: 2.6120

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.1450 - mae: 2.6111

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0579 - mae: 2.6000

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0694 - mae: 2.6029

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0581 - mae: 2.6031

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0633 - mae: 2.6059

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0063 - mae: 2.6007

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0606 - mae: 2.6082

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0507 - mae: 2.6060

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0405 - mae: 2.6042

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0601 - mae: 2.6087

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 11.0718 - mae: 2.6098

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.0184 - mae: 2.6043

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1205 - mae: 2.6167

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1335 - mae: 2.6144

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1485 - mae: 2.6185

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1413 - mae: 2.6158

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1339 - mae: 2.6168

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1285 - mae: 2.6177

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.2054 - mae: 2.6253

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1800 - mae: 2.6214

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1891 - mae: 2.6214

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.2017 - mae: 2.6206

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1914 - mae: 2.6209

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1656 - mae: 2.6196

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1724 - mae: 2.6229

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1667 - mae: 2.6255

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1959 - mae: 2.6282

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.1744 - mae: 2.6252

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.2588 - mae: 2.6300

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 11.2258 - mae: 2.6248 - val_loss: 9.3515 - val_mae: 2.4272

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 6.8755 - mae: 1.9211

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.9506 - mae: 2.3600

 15/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 12.6810 - mae: 2.7641

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 11.1688 - mae: 2.6227

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.9309 - mae: 2.6074

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 11.2438 - mae: 2.6424

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 11.8748 - mae: 2.7528

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 11.7507 - mae: 2.7609

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5694 - mae: 2.7361

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.6215 - mae: 2.8341

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.4912 - mae: 2.8353

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.6665 - mae: 2.8128

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.5505 - mae: 2.8020

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 12.1389 - mae: 2.7420

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.7788 - mae: 2.7019

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.7012 - mae: 2.6835

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5916 - mae: 2.6670

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.7351 - mae: 2.6730

118/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.3768 - mae: 2.6320

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.4930 - mae: 2.6398

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5449 - mae: 2.6413

137/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.5196 - mae: 2.6341

144/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.2769 - mae: 2.6056

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.1494 - mae: 2.5874

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.3406 - mae: 2.5949

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.2314 - mae: 2.5809

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.2650 - mae: 2.5911

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.3318 - mae: 2.5907

183/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.2670 - mae: 2.5926

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.5001 - mae: 2.6068

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.5435 - mae: 2.6093

201/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11.6202 - mae: 2.6221

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.6172 - mae: 2.6195

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.6399 - mae: 2.6206

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.5666 - mae: 2.6138

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.5768 - mae: 2.6127

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.5506 - mae: 2.6132

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.5091 - mae: 2.6113

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.6195 - mae: 2.6289

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.5380 - mae: 2.6212

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.4551 - mae: 2.6104

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.4420 - mae: 2.6124

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.4047 - mae: 2.6086

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.3527 - mae: 2.5993

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.2526 - mae: 2.5871

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.1265 - mae: 2.5709

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0826 - mae: 2.5643

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0159 - mae: 2.5560

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 11.0115 - mae: 2.5567

298/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 10.9933 - mae: 2.5553

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.9583 - mae: 2.5563

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.9624 - mae: 2.5559

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.8476 - mae: 2.5416

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7700 - mae: 2.5339

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7495 - mae: 2.5328

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7158 - mae: 2.5329

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7331 - mae: 2.5362

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7339 - mae: 2.5411

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.6892 - mae: 2.5352

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.6371 - mae: 2.5314

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.6007 - mae: 2.5273

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.6411 - mae: 2.5342

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.5655 - mae: 2.5247

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.5804 - mae: 2.5289

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.5932 - mae: 2.5311

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.5541 - mae: 2.5268

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.5161 - mae: 2.5216

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.5335 - mae: 2.5272

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.5388 - mae: 2.5303

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.4868 - mae: 2.5245

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.4940 - mae: 2.5278

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.4531 - mae: 2.5203

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10.4617 - mae: 2.5196

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4824 - mae: 2.5226

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4717 - mae: 2.5228

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.6041 - mae: 2.5317

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5321 - mae: 2.5227

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5497 - mae: 2.5228

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5262 - mae: 2.5199

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5462 - mae: 2.5249

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5398 - mae: 2.5232

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5138 - mae: 2.5202

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4600 - mae: 2.5138

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4447 - mae: 2.5121

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4688 - mae: 2.5155

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4622 - mae: 2.5149

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4700 - mae: 2.5157

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4785 - mae: 2.5159

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4956 - mae: 2.5197

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4955 - mae: 2.5202

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5064 - mae: 2.5210

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.5051 - mae: 2.5225

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.4750 - mae: 2.5188

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 10.4477 - mae: 2.5162 - val_loss: 6.5044 - val_mae: 1.9702

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 20.6532 - mae: 3.7874

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.3777 - mae: 2.5039

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.7239 - mae: 2.6561

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 13.9741 - mae: 2.8635

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 12.9219 - mae: 2.7534

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.6267 - mae: 2.6247

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 11.0931 - mae: 2.5907

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.3712 - mae: 2.4841

 51/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.1377 - mae: 2.4784

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8763 - mae: 2.4534

 63/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.2135 - mae: 2.5065

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.2218 - mae: 2.4869

 76/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.6933 - mae: 2.5267

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.6446 - mae: 2.5213

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.5231 - mae: 2.5160

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.6716 - mae: 2.5461

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.6231 - mae: 2.5461

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.6269 - mae: 2.5412

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.4027 - mae: 2.5212

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.3283 - mae: 2.5023

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.1671 - mae: 2.4860

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10.0873 - mae: 2.4809

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.9005 - mae: 2.4596

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8656 - mae: 2.4395

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.8754 - mae: 2.4448

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.7523 - mae: 2.4247

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6328 - mae: 2.4110

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.6605 - mae: 2.4115

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7268 - mae: 2.4220

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7389 - mae: 2.4280

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7375 - mae: 2.4267

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8505 - mae: 2.4469

207/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.8348 - mae: 2.4474

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8749 - mae: 2.4523

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8641 - mae: 2.4493

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8446 - mae: 2.4505

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0638 - mae: 2.4796

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1775 - mae: 2.4934

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1542 - mae: 2.4947

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.2116 - mae: 2.5017

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1770 - mae: 2.4943

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1359 - mae: 2.4899

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1424 - mae: 2.4907

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1946 - mae: 2.4967

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0963 - mae: 2.4855

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0504 - mae: 2.4831

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9965 - mae: 2.4790

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0376 - mae: 2.4798

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0377 - mae: 2.4826

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.1600 - mae: 2.4979

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.1926 - mae: 2.5015

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.1453 - mae: 2.4969

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.1073 - mae: 2.4920

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0978 - mae: 2.4892

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0229 - mae: 2.4792

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9718 - mae: 2.4714

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9825 - mae: 2.4749

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9626 - mae: 2.4748

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9237 - mae: 2.4707

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0137 - mae: 2.4756

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1515 - mae: 2.4916

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1327 - mae: 2.4947

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1862 - mae: 2.5010

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1462 - mae: 2.4965

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1231 - mae: 2.4979

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1105 - mae: 2.4958

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.0606 - mae: 2.4903

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.0242 - mae: 2.4866

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.0100 - mae: 2.4828

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.0090 - mae: 2.4860

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1427 - mae: 2.5013

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1181 - mae: 2.4994

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1327 - mae: 2.5030

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1061 - mae: 2.5004

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1256 - mae: 2.5009

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1387 - mae: 2.5045

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.1279 - mae: 2.5036

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.2320 - mae: 2.5102

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 10.2348 - mae: 2.5115 - val_loss: 7.0632 - val_mae: 2.0655

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 7.1679 - mae: 2.2900

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 11.9156 - mae: 2.8991

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.5083 - mae: 2.5492

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 10.4004 - mae: 2.6949

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.2646 - mae: 2.6736

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.3559 - mae: 2.6705

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7966 - mae: 2.5678

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4085 - mae: 2.4842

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4712 - mae: 2.4890

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4032 - mae: 2.4780

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6538 - mae: 2.5062

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4047 - mae: 2.4775

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6698 - mae: 2.5013

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9932 - mae: 2.5231

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9737 - mae: 2.5191

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7169 - mae: 2.4828

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4948 - mae: 2.4444

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4111 - mae: 2.4331

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4855 - mae: 2.4418

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4772 - mae: 2.4449

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.3112 - mae: 2.4200

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.2741 - mae: 2.4196

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.3479 - mae: 2.4344

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.2565 - mae: 2.4198

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.2593 - mae: 2.4206

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.2744 - mae: 2.4206

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.5565 - mae: 2.4489

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.4862 - mae: 2.4373

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5176 - mae: 2.4466

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5847 - mae: 2.4581

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5733 - mae: 2.4586

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5049 - mae: 2.4512

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.4745 - mae: 2.4469

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.4296 - mae: 2.4463

216/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.4351 - mae: 2.4438

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5108 - mae: 2.4509

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.6282 - mae: 2.4590

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5821 - mae: 2.4551

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5819 - mae: 2.4573

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.6313 - mae: 2.4630

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.6277 - mae: 2.4612

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.5751 - mae: 2.4554

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.7693 - mae: 2.4708

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.8378 - mae: 2.4736

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 9.9693 - mae: 2.4835

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 10.0456 - mae: 2.4958

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.9588 - mae: 2.4847

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8646 - mae: 2.4750

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.9135 - mae: 2.4748

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8887 - mae: 2.4730

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8607 - mae: 2.4702

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8381 - mae: 2.4660

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8177 - mae: 2.4649

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7781 - mae: 2.4558

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7902 - mae: 2.4533

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7953 - mae: 2.4514

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8306 - mae: 2.4535

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.8479 - mae: 2.4586

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7958 - mae: 2.4525

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7727 - mae: 2.4530

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7207 - mae: 2.4469

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7545 - mae: 2.4515

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7372 - mae: 2.4460

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 9.7389 - mae: 2.4485

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7873 - mae: 2.4552

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8255 - mae: 2.4600

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8059 - mae: 2.4585

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7639 - mae: 2.4536

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8059 - mae: 2.4579

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.8166 - mae: 2.4624

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7986 - mae: 2.4623

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7698 - mae: 2.4567

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7937 - mae: 2.4596

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7415 - mae: 2.4516

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.7158 - mae: 2.4485

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.6742 - mae: 2.4423

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.6326 - mae: 2.4379

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.5846 - mae: 2.4310

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.6046 - mae: 2.4342

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.5743 - mae: 2.4330

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.5404 - mae: 2.4289

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.5241 - mae: 2.4290

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.5303 - mae: 2.4318

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 9.5303 - mae: 2.4318 - val_loss: 6.2168 - val_mae: 1.9410

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 56ms/step - loss: 8.3696 - mae: 2.1215

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.1399 - mae: 2.4297

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.0724 - mae: 2.1060

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.0884 - mae: 2.1252

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.0030 - mae: 2.0985

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.5509 - mae: 2.2143

 40/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3918 - mae: 2.2807

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4168 - mae: 2.3120

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7485 - mae: 2.3508

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0834 - mae: 2.3704

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.4364 - mae: 2.3913

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.3700 - mae: 2.3920

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.2376 - mae: 2.3760

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0798 - mae: 2.3608

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.2094 - mae: 2.3744

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1941 - mae: 2.3805

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1443 - mae: 2.3719

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0034 - mae: 2.3485

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9564 - mae: 2.3420

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8431 - mae: 2.3237

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7555 - mae: 2.3226

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6529 - mae: 2.3072

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6507 - mae: 2.3036

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6939 - mae: 2.3129

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8127 - mae: 2.3288

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6872 - mae: 2.3071

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6383 - mae: 2.2954

174/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9622 - mae: 2.3336

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.2330 - mae: 2.3486

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1492 - mae: 2.3441

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1207 - mae: 2.3435

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0695 - mae: 2.3446

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0008 - mae: 2.3380

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9629 - mae: 2.3313

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0291 - mae: 2.3376

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8806 - mae: 2.3092

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.9772 - mae: 2.3232

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8780 - mae: 2.3105

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0592 - mae: 2.3312

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0856 - mae: 2.3333

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1306 - mae: 2.3465

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1329 - mae: 2.3522

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1225 - mae: 2.3527

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0619 - mae: 2.3461

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.0402 - mae: 2.3476

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.9940 - mae: 2.3447

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.9672 - mae: 2.3438

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0168 - mae: 2.3490

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0902 - mae: 2.3614

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.1466 - mae: 2.3722

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.1934 - mae: 2.3752

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2287 - mae: 2.3825

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2587 - mae: 2.3877

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2199 - mae: 2.3831

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2090 - mae: 2.3803

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2518 - mae: 2.3839

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2719 - mae: 2.3865

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2872 - mae: 2.3891

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3271 - mae: 2.3987

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3170 - mae: 2.3991

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3004 - mae: 2.3957

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3041 - mae: 2.3963

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.4018 - mae: 2.4057

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4309 - mae: 2.4115

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4168 - mae: 2.4086

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3907 - mae: 2.4097

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4237 - mae: 2.4129

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4095 - mae: 2.4118

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3854 - mae: 2.4088

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3995 - mae: 2.4119

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4109 - mae: 2.4152

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3745 - mae: 2.4102

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3472 - mae: 2.4078

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3504 - mae: 2.4081

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4340 - mae: 2.4179

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4763 - mae: 2.4215

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4714 - mae: 2.4220

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4692 - mae: 2.4247

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4593 - mae: 2.4238

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4645 - mae: 2.4245

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5073 - mae: 2.4305

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4943 - mae: 2.4296

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 9.4912 - mae: 2.4292 - val_loss: 9.3613 - val_mae: 2.4440

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 30s 58ms/step - loss: 22.0321 - mae: 4.6117

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.8224 - mae: 2.4608

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.2780 - mae: 2.0399

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.9335 - mae: 2.1966

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.6984 - mae: 2.3420

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.1913 - mae: 2.2729

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.1500 - mae: 2.4396

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3573 - mae: 2.4860

 55/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3504 - mae: 2.5081

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 11.0018 - mae: 2.5974

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7973 - mae: 2.5776

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6519 - mae: 2.5649

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6623 - mae: 2.5476

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6181 - mae: 2.5364

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.4240 - mae: 2.5160

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.2355 - mae: 2.4980

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.6082 - mae: 2.5149

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.4481 - mae: 2.5037

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.4310 - mae: 2.5124

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.3167 - mae: 2.4897

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.2937 - mae: 2.4849

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.1019 - mae: 2.4595

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9015 - mae: 2.4280

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8037 - mae: 2.4257

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.5764 - mae: 2.3918

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5268 - mae: 2.3934

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5019 - mae: 2.3986

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.6283 - mae: 2.4090

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8894 - mae: 2.4376

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9327 - mae: 2.4463

194/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9073 - mae: 2.4436

201/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1059 - mae: 2.4688

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0433 - mae: 2.4667

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0509 - mae: 2.4629

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9751 - mae: 2.4582

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9074 - mae: 2.4519

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0568 - mae: 2.4701

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0556 - mae: 2.4744

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.0792 - mae: 2.4744

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1467 - mae: 2.4852

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.2728 - mae: 2.5016

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.3088 - mae: 2.5106

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.2334 - mae: 2.4986

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10.1490 - mae: 2.4887

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.1313 - mae: 2.4873

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 10.0605 - mae: 2.4773

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9708 - mae: 2.4656

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8908 - mae: 2.4564

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9358 - mae: 2.4613

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.9385 - mae: 2.4638

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.8668 - mae: 2.4548

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7980 - mae: 2.4462

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7567 - mae: 2.4418

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7314 - mae: 2.4404

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7251 - mae: 2.4383

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6964 - mae: 2.4375

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6714 - mae: 2.4336

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7007 - mae: 2.4378

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.7082 - mae: 2.4389

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6452 - mae: 2.4303

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6043 - mae: 2.4281

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6219 - mae: 2.4324

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.6403 - mae: 2.4361

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.6181 - mae: 2.4344

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5521 - mae: 2.4263

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5434 - mae: 2.4226

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5413 - mae: 2.4229

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5497 - mae: 2.4246

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5628 - mae: 2.4284

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5334 - mae: 2.4231

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4905 - mae: 2.4176

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5340 - mae: 2.4250

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5039 - mae: 2.4222

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4900 - mae: 2.4179

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4312 - mae: 2.4091

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4352 - mae: 2.4108

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4239 - mae: 2.4096

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4221 - mae: 2.4104

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4266 - mae: 2.4101

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4125 - mae: 2.4085

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.4460 - mae: 2.4148

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 9.4314 - mae: 2.4124 - val_loss: 6.1699 - val_mae: 1.9406

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 57ms/step - loss: 11.7177 - mae: 3.0508

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.0297 - mae: 2.4572

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.9372 - mae: 2.3991

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.5270 - mae: 2.4493

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.7144 - mae: 2.3378

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.6444 - mae: 2.3378

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7487 - mae: 2.3238

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5335 - mae: 2.3167

 55/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8441 - mae: 2.3672

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5956 - mae: 2.3364

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5150 - mae: 2.3275

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6640 - mae: 2.3404

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4456 - mae: 2.3067

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6149 - mae: 2.3314

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7651 - mae: 2.3235

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6420 - mae: 2.3120

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8060 - mae: 2.3448

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.7290 - mae: 2.3393

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6505 - mae: 2.3252

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6549 - mae: 2.3325

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8670 - mae: 2.3537

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8675 - mae: 2.3463

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8377 - mae: 2.3399

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8102 - mae: 2.3371

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8629 - mae: 2.3384

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.7504 - mae: 2.3227

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6397 - mae: 2.3144

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6048 - mae: 2.3114

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.5424 - mae: 2.3053

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5684 - mae: 2.3149

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6732 - mae: 2.3322

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7592 - mae: 2.3423

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7991 - mae: 2.3464

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7077 - mae: 2.3387

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7503 - mae: 2.3457

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6567 - mae: 2.3320

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5356 - mae: 2.3138

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.5335 - mae: 2.3140

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4057 - mae: 2.2942

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4600 - mae: 2.3029

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3915 - mae: 2.2912

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3746 - mae: 2.2924

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3332 - mae: 2.2844

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3285 - mae: 2.2860

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3116 - mae: 2.2876

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3091 - mae: 2.2859

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3207 - mae: 2.2858

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2617 - mae: 2.2805

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2615 - mae: 2.2809

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2409 - mae: 2.2760

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2570 - mae: 2.2840

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2467 - mae: 2.2821

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2832 - mae: 2.2902

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3422 - mae: 2.2948

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3564 - mae: 2.2975

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3755 - mae: 2.3005

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3377 - mae: 2.2946

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2988 - mae: 2.2889

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2816 - mae: 2.2873

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2505 - mae: 2.2841

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2674 - mae: 2.2844

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2676 - mae: 2.2832

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2500 - mae: 2.2834

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2580 - mae: 2.2843

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2597 - mae: 2.2861

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3626 - mae: 2.2992

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3498 - mae: 2.2954

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3462 - mae: 2.2943

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3757 - mae: 2.2985

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3984 - mae: 2.3017

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3811 - mae: 2.2983

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3959 - mae: 2.2990

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3894 - mae: 2.3007

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4336 - mae: 2.3063

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4487 - mae: 2.3088

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4010 - mae: 2.3014

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4087 - mae: 2.3037

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3756 - mae: 2.2971

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3989 - mae: 2.2969

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4114 - mae: 2.3002

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4157 - mae: 2.2977

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.4444 - mae: 2.3008 - val_loss: 5.7936 - val_mae: 1.8613

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 14.8049 - mae: 3.0799

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.4747 - mae: 2.5080

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.3146 - mae: 2.4510

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.4183 - mae: 2.5714

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.5502 - mae: 2.4587

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.2780 - mae: 2.5126

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.9453 - mae: 2.4900

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.7089 - mae: 2.4601

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.5976 - mae: 2.4441

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.6575 - mae: 2.4480

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.2563 - mae: 2.4037

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 9.1010 - mae: 2.3758

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.5906 - mae: 2.2810

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8461 - mae: 2.3128

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8899 - mae: 2.3203

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.7121 - mae: 2.2947

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6005 - mae: 2.2977

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6857 - mae: 2.3127

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6765 - mae: 2.3086

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6003 - mae: 2.2992

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.5183 - mae: 2.2908

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3973 - mae: 2.2729

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3450 - mae: 2.2679

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3040 - mae: 2.2696

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4125 - mae: 2.2809

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4426 - mae: 2.2898

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3189 - mae: 2.2667

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3077 - mae: 2.2682

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1788 - mae: 2.2502

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1932 - mae: 2.2516

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.2078 - mae: 2.2532

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1463 - mae: 2.2505

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0931 - mae: 2.2474

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0164 - mae: 2.2388

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0911 - mae: 2.2475

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0915 - mae: 2.2461

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.1011 - mae: 2.2520

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0391 - mae: 2.2457

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9692 - mae: 2.2353

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9349 - mae: 2.2283

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9804 - mae: 2.2352

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9960 - mae: 2.2394

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.0750 - mae: 2.2461

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.2400 - mae: 2.2663

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.2123 - mae: 2.2596

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.2887 - mae: 2.2664

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5720 - mae: 2.2967

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6021 - mae: 2.3003

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6835 - mae: 2.3116

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6681 - mae: 2.3112

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6541 - mae: 2.3117

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6378 - mae: 2.3073

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5951 - mae: 2.3009

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6289 - mae: 2.3035

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5806 - mae: 2.2967

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6672 - mae: 2.3048

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6160 - mae: 2.2987

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6263 - mae: 2.2990

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6216 - mae: 2.2989

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5634 - mae: 2.2901

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6555 - mae: 2.2999

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6659 - mae: 2.2951

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6919 - mae: 2.2955

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6578 - mae: 2.2879

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6611 - mae: 2.2890

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.6372 - mae: 2.2878

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6612 - mae: 2.2918

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6441 - mae: 2.2863

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6695 - mae: 2.2902

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6593 - mae: 2.2886

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6657 - mae: 2.2866

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7073 - mae: 2.2933

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6789 - mae: 2.2893

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7395 - mae: 2.2968

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7326 - mae: 2.2980

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7542 - mae: 2.3023

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7933 - mae: 2.3078

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7863 - mae: 2.3103

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7473 - mae: 2.3058

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7765 - mae: 2.3100

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7545 - mae: 2.3085

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7785 - mae: 2.3137

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8033 - mae: 2.3162

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.8065 - mae: 2.3169 - val_loss: 8.6946 - val_mae: 2.3493

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 63ms/step - loss: 6.3794 - mae: 2.1099

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.8638 - mae: 2.0572

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.5540 - mae: 2.0087

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.7839 - mae: 2.0910

 28/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9188 - mae: 2.1315

 35/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5870 - mae: 2.2639

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6481 - mae: 2.2566

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6550 - mae: 2.2419

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9484 - mae: 2.2791

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1838 - mae: 2.3473

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6129 - mae: 2.3945

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6117 - mae: 2.4054

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.6032 - mae: 2.4053

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.5476 - mae: 2.4844

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.2791 - mae: 2.4581

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.0260 - mae: 2.4284

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8151 - mae: 2.4077

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7718 - mae: 2.4100

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8664 - mae: 2.4275

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8055 - mae: 2.4199

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7646 - mae: 2.4198

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.7411 - mae: 2.4219

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9176 - mae: 2.4303

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9988 - mae: 2.4308

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.9285 - mae: 2.4275

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.8633 - mae: 2.4205

167/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8379 - mae: 2.4203

174/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.9903 - mae: 2.4436

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8712 - mae: 2.4311

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.8177 - mae: 2.4339

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7671 - mae: 2.4276

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7535 - mae: 2.4223

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.7836 - mae: 2.4323

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.6704 - mae: 2.4153

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5961 - mae: 2.4095

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5407 - mae: 2.4019

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.4586 - mae: 2.3910

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.4957 - mae: 2.4024

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.5229 - mae: 2.4067

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.4862 - mae: 2.3993

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.3833 - mae: 2.3869

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.3011 - mae: 2.3717

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.2556 - mae: 2.3685

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.1702 - mae: 2.3549

283/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9.3255 - mae: 2.3647

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3358 - mae: 2.3669

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3101 - mae: 2.3654

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.3120 - mae: 2.3635

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2593 - mae: 2.3584

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2621 - mae: 2.3545

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2127 - mae: 2.3512

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.2050 - mae: 2.3528

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.1395 - mae: 2.3443

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.1905 - mae: 2.3541

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.1721 - mae: 2.3534

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0880 - mae: 2.3452

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0334 - mae: 2.3387

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.9667 - mae: 2.3329

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0081 - mae: 2.3359

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0616 - mae: 2.3416

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0260 - mae: 2.3400

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9.0328 - mae: 2.3405

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.9745 - mae: 2.3334

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.0270 - mae: 2.3418

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.0199 - mae: 2.3423

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9680 - mae: 2.3313

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9373 - mae: 2.3282

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9367 - mae: 2.3278

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9331 - mae: 2.3287

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9077 - mae: 2.3285

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9602 - mae: 2.3374

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9209 - mae: 2.3316

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8966 - mae: 2.3279

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8848 - mae: 2.3259

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8821 - mae: 2.3251

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8316 - mae: 2.3172

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8176 - mae: 2.3160

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.8543 - mae: 2.3158

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9001 - mae: 2.3221

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9514 - mae: 2.3303

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.9032 - mae: 2.3245

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.8976 - mae: 2.3247 - val_loss: 6.6726 - val_mae: 2.0223

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 3.6373 - mae: 1.5357

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7470 - mae: 2.1795

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.7575 - mae: 2.0685

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.3130 - mae: 2.2156

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.0859 - mae: 2.3589

 33/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.8149 - mae: 2.4682

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.0795 - mae: 2.3541

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.5706 - mae: 2.4341

 51/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.2269 - mae: 2.3996

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8901 - mae: 2.3547

 63/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7870 - mae: 2.3397

 69/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9185 - mae: 2.3656

 76/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7069 - mae: 2.3460

 82/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6176 - mae: 2.3413

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6260 - mae: 2.3424

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5474 - mae: 2.3284

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.2283 - mae: 2.2774

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1306 - mae: 2.2587

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1945 - mae: 2.2639

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6138 - mae: 2.3046

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5560 - mae: 2.3073

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6662 - mae: 2.3206

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5509 - mae: 2.3054

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5430 - mae: 2.3067

153/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4538 - mae: 2.2951

159/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3800 - mae: 2.2872

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3605 - mae: 2.2911

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3279 - mae: 2.2894

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.2868 - mae: 2.2825

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3073 - mae: 2.2866

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4002 - mae: 2.2835

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4785 - mae: 2.2952

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4848 - mae: 2.3026

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5041 - mae: 2.3082

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5779 - mae: 2.3159

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6229 - mae: 2.3224

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6456 - mae: 2.3271

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6630 - mae: 2.3293

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5999 - mae: 2.3217

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7174 - mae: 2.3367

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8054 - mae: 2.3474

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.8091 - mae: 2.3476

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7906 - mae: 2.3472

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7016 - mae: 2.3346

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6531 - mae: 2.3300

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6959 - mae: 2.3387

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6822 - mae: 2.3366

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6556 - mae: 2.3340

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6792 - mae: 2.3389

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6924 - mae: 2.3361

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6567 - mae: 2.3331

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5999 - mae: 2.3254

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6362 - mae: 2.3322

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6151 - mae: 2.3310

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5746 - mae: 2.3239

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6379 - mae: 2.3313

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5820 - mae: 2.3264

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5468 - mae: 2.3196

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5639 - mae: 2.3236

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5708 - mae: 2.3243

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6088 - mae: 2.3343

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6477 - mae: 2.3347

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.6497 - mae: 2.3372

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6268 - mae: 2.3350

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6003 - mae: 2.3322

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5797 - mae: 2.3288

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6457 - mae: 2.3340

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6232 - mae: 2.3322

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6252 - mae: 2.3353

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6757 - mae: 2.3400

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6862 - mae: 2.3420

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7056 - mae: 2.3434

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7166 - mae: 2.3431

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6759 - mae: 2.3377

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6270 - mae: 2.3306

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6434 - mae: 2.3343

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7155 - mae: 2.3423

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6839 - mae: 2.3341

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6940 - mae: 2.3352

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6743 - mae: 2.3317

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6526 - mae: 2.3290

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6489 - mae: 2.3306

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.6525 - mae: 2.3314 - val_loss: 5.8531 - val_mae: 1.8895

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 3.4044 - mae: 1.2847

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.2223 - mae: 2.0932

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.6530 - mae: 1.9114

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.3290 - mae: 1.9918

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.4063 - mae: 2.0910

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.8922 - mae: 2.0774

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.1838 - mae: 2.1386

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3092 - mae: 2.1615

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5000 - mae: 2.1896

 59/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3134 - mae: 2.1814

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3835 - mae: 2.1827

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3207 - mae: 2.1883

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5516 - mae: 2.2413

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7233 - mae: 2.2453

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8106 - mae: 2.2493

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9317 - mae: 2.2736

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8807 - mae: 2.2783

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.9148 - mae: 2.2949

118/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8641 - mae: 2.2965

125/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8610 - mae: 2.2960

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6832 - mae: 2.2717

137/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7434 - mae: 2.2774

143/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.5438 - mae: 2.2485

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4289 - mae: 2.2327

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3062 - mae: 2.2164

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3431 - mae: 2.2160

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4439 - mae: 2.2155

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4660 - mae: 2.2226

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3821 - mae: 2.2111

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3199 - mae: 2.2077

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.2596 - mae: 2.2031

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.2444 - mae: 2.2027

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3720 - mae: 2.2268

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3758 - mae: 2.2327

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4180 - mae: 2.2397

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4779 - mae: 2.2468

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4365 - mae: 2.2399

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4613 - mae: 2.2443

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4321 - mae: 2.2442

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4658 - mae: 2.2496

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3869 - mae: 2.2372

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3309 - mae: 2.2331

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3130 - mae: 2.2338

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3172 - mae: 2.2281

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2945 - mae: 2.2234

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2409 - mae: 2.2175

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.1758 - mae: 2.2094

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2729 - mae: 2.2133

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3443 - mae: 2.2273

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3295 - mae: 2.2237

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3517 - mae: 2.2313

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4289 - mae: 2.2403

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4200 - mae: 2.2446

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4039 - mae: 2.2428

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3876 - mae: 2.2415

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4318 - mae: 2.2431

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3784 - mae: 2.2326

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4162 - mae: 2.2407

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4080 - mae: 2.2383

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4045 - mae: 2.2407

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3354 - mae: 2.2308

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3109 - mae: 2.2287

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3322 - mae: 2.2327

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3299 - mae: 2.2333

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3469 - mae: 2.2386

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4166 - mae: 2.2478

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4090 - mae: 2.2462

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4218 - mae: 2.2525

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4731 - mae: 2.2597

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5286 - mae: 2.2693

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5727 - mae: 2.2775

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5490 - mae: 2.2751

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5407 - mae: 2.2760

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5561 - mae: 2.2762

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5228 - mae: 2.2718

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5049 - mae: 2.2688

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4936 - mae: 2.2675

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5169 - mae: 2.2700

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5007 - mae: 2.2679

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4939 - mae: 2.2694

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4904 - mae: 2.2684

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.5157 - mae: 2.2728 - val_loss: 5.9306 - val_mae: 1.9112

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 62ms/step - loss: 4.0839 - mae: 1.8124

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.5864 - mae: 2.3390

 15/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.1468 - mae: 2.3419

 21/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.3821 - mae: 2.4299

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.7042 - mae: 2.5055

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.1310 - mae: 2.4308

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7654 - mae: 2.3677

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8404 - mae: 2.3786

 53/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0033 - mae: 2.3951

 59/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.1240 - mae: 2.3950

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8947 - mae: 2.3707

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0831 - mae: 2.3768

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8201 - mae: 2.3407

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7622 - mae: 2.3161

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7001 - mae: 2.3045

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8550 - mae: 2.3155

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7210 - mae: 2.3037

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7159 - mae: 2.3080

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7711 - mae: 2.3273

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.7458 - mae: 2.3145

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 9.0292 - mae: 2.3507

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8914 - mae: 2.3361

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8482 - mae: 2.3277

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.8001 - mae: 2.3207

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7072 - mae: 2.3080

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.7250 - mae: 2.3081

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.6419 - mae: 2.3033

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5985 - mae: 2.2936

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4004 - mae: 2.2575

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3031 - mae: 2.2426

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.1323 - mae: 2.2160

207/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.1665 - mae: 2.2287

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.1019 - mae: 2.2246

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.2146 - mae: 2.2389

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4182 - mae: 2.2613

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.5072 - mae: 2.2739

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.4487 - mae: 2.2654

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3952 - mae: 2.2551

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3461 - mae: 2.2485

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3548 - mae: 2.2520

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.3054 - mae: 2.2437

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.2758 - mae: 2.2423

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3540 - mae: 2.2511

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3381 - mae: 2.2517

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3485 - mae: 2.2546

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3128 - mae: 2.2507

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.2190 - mae: 2.2333

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.3019 - mae: 2.2391

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4571 - mae: 2.2599

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4450 - mae: 2.2621

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5274 - mae: 2.2686

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4962 - mae: 2.2646

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.4672 - mae: 2.2610

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5445 - mae: 2.2670

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5431 - mae: 2.2694

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5394 - mae: 2.2698

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5428 - mae: 2.2751

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5106 - mae: 2.2734

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5059 - mae: 2.2745

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8.5190 - mae: 2.2750

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5425 - mae: 2.2820

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5182 - mae: 2.2808

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5119 - mae: 2.2783

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5230 - mae: 2.2795

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4745 - mae: 2.2732

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4363 - mae: 2.2690

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4082 - mae: 2.2664

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3676 - mae: 2.2594

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3554 - mae: 2.2577

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3034 - mae: 2.2489

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3452 - mae: 2.2538

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3328 - mae: 2.2547

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.3176 - mae: 2.2527

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.2977 - mae: 2.2513

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4053 - mae: 2.2647

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4420 - mae: 2.2668

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4235 - mae: 2.2646

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4159 - mae: 2.2624

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.4667 - mae: 2.2647

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5006 - mae: 2.2665

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 8.5275 - mae: 2.2693 - val_loss: 6.0096 - val_mae: 1.8926

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 57ms/step - loss: 7.0681 - mae: 1.7565

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.8536 - mae: 1.8353

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7530 - mae: 2.0067

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8962 - mae: 2.0697

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.4956 - mae: 2.1091

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.2204 - mae: 2.1725

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.1848 - mae: 2.1946

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.6415 - mae: 2.2594

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.6084 - mae: 2.2639

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.6108 - mae: 2.2829

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.4294 - mae: 2.2555

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.4225 - mae: 2.2712

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5293 - mae: 2.2770

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.4265 - mae: 2.2700

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4658 - mae: 2.2716

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.2461 - mae: 2.2504

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.5130 - mae: 2.2778

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6641 - mae: 2.2820

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6952 - mae: 2.3061

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6254 - mae: 2.2989

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4972 - mae: 2.2879

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4844 - mae: 2.2841

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.4138 - mae: 2.2724

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3743 - mae: 2.2620

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.3742 - mae: 2.2624

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.2498 - mae: 2.2391

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.5603 - mae: 2.2722

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6124 - mae: 2.2845

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.5838 - mae: 2.2827

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.5160 - mae: 2.2803

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.4334 - mae: 2.2724

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.5175 - mae: 2.2745

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.6489 - mae: 2.2914

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.6929 - mae: 2.3014

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.6414 - mae: 2.2965

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7154 - mae: 2.3068

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.6935 - mae: 2.3057

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7480 - mae: 2.3074

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7827 - mae: 2.3170

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7949 - mae: 2.3200

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7493 - mae: 2.3080

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.8667 - mae: 2.3263

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.9258 - mae: 2.3353

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.8800 - mae: 2.3273

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.8143 - mae: 2.3206

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 8.7257 - mae: 2.3095

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.7755 - mae: 2.3202

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.7950 - mae: 2.3194

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.8251 - mae: 2.3236

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.8864 - mae: 2.3335

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.8589 - mae: 2.3262

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.8779 - mae: 2.3327

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.8458 - mae: 2.3308

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.7806 - mae: 2.3227

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.7316 - mae: 2.3152

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.7188 - mae: 2.3112

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6841 - mae: 2.3060

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6373 - mae: 2.2996

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6147 - mae: 2.2948

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.6100 - mae: 2.2912

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5508 - mae: 2.2825

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5268 - mae: 2.2794

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.4633 - mae: 2.2665

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.4535 - mae: 2.2655

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.5073 - mae: 2.2624

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.4751 - mae: 2.2588

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4471 - mae: 2.2583

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4716 - mae: 2.2607

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4656 - mae: 2.2569

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4491 - mae: 2.2553

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4171 - mae: 2.2506

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4052 - mae: 2.2516

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3866 - mae: 2.2500

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3655 - mae: 2.2488

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3455 - mae: 2.2475

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3593 - mae: 2.2487

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3966 - mae: 2.2513

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3939 - mae: 2.2519

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4125 - mae: 2.2545

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4535 - mae: 2.2606

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4424 - mae: 2.2597

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4261 - mae: 2.2557

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4374 - mae: 2.2584

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.4284 - mae: 2.2577

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3982 - mae: 2.2538

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3914 - mae: 2.2543

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3700 - mae: 2.2532

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.4141 - mae: 2.2582 - val_loss: 8.1602 - val_mae: 2.2897

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 30s 59ms/step - loss: 2.5155 - mae: 1.3860

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.7850 - mae: 2.5646

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.1034 - mae: 2.4765

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.2840 - mae: 2.5461

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 10.3410 - mae: 2.5690

 33/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.4283 - mae: 2.4302

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.3574 - mae: 2.4363

 45/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.0980 - mae: 2.4127

 51/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6269 - mae: 2.3379

 58/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4106 - mae: 2.3110

 65/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4573 - mae: 2.3192

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4978 - mae: 2.3138

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4476 - mae: 2.3234

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1617 - mae: 2.2902

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1039 - mae: 2.2884

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9234 - mae: 2.2648

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.8302 - mae: 2.2554

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7568 - mae: 2.2420

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7178 - mae: 2.2392

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6331 - mae: 2.2324

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8800 - mae: 2.2682

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7377 - mae: 2.2465

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6611 - mae: 2.2364

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8185 - mae: 2.2580

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8778 - mae: 2.2550

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.9413 - mae: 2.2637

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.9157 - mae: 2.2647

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8234 - mae: 2.2453

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7263 - mae: 2.2271

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7438 - mae: 2.2309

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6237 - mae: 2.2082

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5097 - mae: 2.1857

191/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5379 - mae: 2.1874

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.5692 - mae: 2.1887

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.5715 - mae: 2.1893

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6618 - mae: 2.2027

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6684 - mae: 2.2038

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7337 - mae: 2.2084

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7477 - mae: 2.2122

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7760 - mae: 2.2192

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7184 - mae: 2.2120

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6984 - mae: 2.2072

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7391 - mae: 2.2086

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7048 - mae: 2.2045

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7126 - mae: 2.2084

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7176 - mae: 2.2075

271/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7550 - mae: 2.2110

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7411 - mae: 2.2113

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6801 - mae: 2.2020

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6067 - mae: 2.1921

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6768 - mae: 2.2046

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6767 - mae: 2.2028

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6910 - mae: 2.2035

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7053 - mae: 2.2045

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.6893 - mae: 2.2039

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7216 - mae: 2.2055

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8125 - mae: 2.2156

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8239 - mae: 2.2152

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.9435 - mae: 2.2202

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.9388 - mae: 2.2235

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0024 - mae: 2.2295

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.9828 - mae: 2.2275

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0280 - mae: 2.2330

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0096 - mae: 2.2324

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0087 - mae: 2.2306

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0289 - mae: 2.2314

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0236 - mae: 2.2329

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0556 - mae: 2.2376

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8.0906 - mae: 2.2423

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.1261 - mae: 2.2437

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.2160 - mae: 2.2515

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.2054 - mae: 2.2506

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8.1819 - mae: 2.2467

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.2083 - mae: 2.2494

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.2170 - mae: 2.2518

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.2260 - mae: 2.2537

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2205 - mae: 2.2542

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2199 - mae: 2.2529

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2688 - mae: 2.2565

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2826 - mae: 2.2597

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2262 - mae: 2.2517

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2464 - mae: 2.2555

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2286 - mae: 2.2545

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2363 - mae: 2.2543

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2775 - mae: 2.2604

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2576 - mae: 2.2578

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2624 - mae: 2.2581

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2476 - mae: 2.2547

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2565 - mae: 2.2560

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2719 - mae: 2.2581

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2613 - mae: 2.2570

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 8.2528 - mae: 2.2555 - val_loss: 9.6654 - val_mae: 2.4950

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 43s 83ms/step - loss: 20.5326 - mae: 3.3538

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 11.5986 - mae: 2.6050

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 9.4971 - mae: 2.2685

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 9.9879 - mae: 2.3635

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 10.3957 - mae: 2.4703

 27/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 10.1042 - mae: 2.4267

 32/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 10.5089 - mae: 2.5110

 37/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 9.7969 - mae: 2.4081

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 9.7751 - mae: 2.4311

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 9.6145 - mae: 2.4156

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 9.2569 - mae: 2.3713

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 9.0686 - mae: 2.3574

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.9213 - mae: 2.3417

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.7288 - mae: 2.3209

 71/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.7214 - mae: 2.3280

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.8109 - mae: 2.3581

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.4488 - mae: 2.2997

 88/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.3914 - mae: 2.2818

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.3841 - mae: 2.2750

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.3044 - mae: 2.2664

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.5172 - mae: 2.2897

110/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.5000 - mae: 2.2918

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.5480 - mae: 2.2939

121/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.4603 - mae: 2.2785

127/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.3550 - mae: 2.2746

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.3327 - mae: 2.2700

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2162 - mae: 2.2619

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2150 - mae: 2.2652

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2742 - mae: 2.2798

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2968 - mae: 2.2819

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.3202 - mae: 2.2877

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.3259 - mae: 2.2854

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.3462 - mae: 2.2795

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2554 - mae: 2.2662

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2546 - mae: 2.2636

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2872 - mae: 2.2635

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.2291 - mae: 2.2566

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.1816 - mae: 2.2481

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.1541 - mae: 2.2480

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.3026 - mae: 2.2564

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2470 - mae: 2.2428

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.1938 - mae: 2.2367

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2197 - mae: 2.2458

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2554 - mae: 2.2568

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2055 - mae: 2.2485

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2069 - mae: 2.2488

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.2258 - mae: 2.2523

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.1684 - mae: 2.2451

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.1613 - mae: 2.2421

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.1504 - mae: 2.2394

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.2550 - mae: 2.2510

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.2361 - mae: 2.2479

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.2543 - mae: 2.2483

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.2512 - mae: 2.2453

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.2128 - mae: 2.2397

283/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.1754 - mae: 2.2325

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.1957 - mae: 2.2353

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.1179 - mae: 2.2250

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.0428 - mae: 2.2145

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9962 - mae: 2.2053

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9849 - mae: 2.2031

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9562 - mae: 2.2002

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9758 - mae: 2.2009

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9888 - mae: 2.2022

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 8.0432 - mae: 2.2064

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9987 - mae: 2.1997

338/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.9734 - mae: 2.1956

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9472 - mae: 2.1916

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9078 - mae: 2.1875

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9029 - mae: 2.1891

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9533 - mae: 2.1904

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9238 - mae: 2.1852

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9354 - mae: 2.1836

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9119 - mae: 2.1813

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9340 - mae: 2.1849

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9725 - mae: 2.1896

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9018 - mae: 2.1793

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9278 - mae: 2.1851

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9170 - mae: 2.1841

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9448 - mae: 2.1893

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.9409 - mae: 2.1902

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9313 - mae: 2.1898

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9133 - mae: 2.1875

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9305 - mae: 2.1901

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9059 - mae: 2.1876

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.8717 - mae: 2.1820

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9025 - mae: 2.1860

421/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.8798 - mae: 2.1823

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.8702 - mae: 2.1818

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.8913 - mae: 2.1819

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9833 - mae: 2.1894

437/522 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7.9449 - mae: 2.1838

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9488 - mae: 2.1865

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9608 - mae: 2.1895

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0093 - mae: 2.1949

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0012 - mae: 2.1934

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9817 - mae: 2.1896

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9602 - mae: 2.1874

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0017 - mae: 2.1947

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0009 - mae: 2.1964

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9790 - mae: 2.1935

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9751 - mae: 2.1941

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9604 - mae: 2.1911

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9905 - mae: 2.1935

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9856 - mae: 2.1935

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9561 - mae: 2.1889

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9713 - mae: 2.1921

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9581 - mae: 2.1909

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9850 - mae: 2.1928

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9742 - mae: 2.1905

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9878 - mae: 2.1927

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9941 - mae: 2.1946

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9958 - mae: 2.1966

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 7.9814 - mae: 2.1938 - val_loss: 9.9054 - val_mae: 2.5513

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 40s 78ms/step - loss: 6.0560 - mae: 2.2883

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.4040 - mae: 2.3362

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.3618 - mae: 2.2972

 15/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.9696 - mae: 2.2791

 19/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.6823 - mae: 2.2798

 23/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 7.9215 - mae: 2.3417

 27/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 8.7471 - mae: 2.4580

 31/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 9.3261 - mae: 2.5285

 34/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 8.9455 - mae: 2.4716

 37/522 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - loss: 8.8612 - mae: 2.4742

 40/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.7694 - mae: 2.4484

 43/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.9588 - mae: 2.4641

 47/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.8357 - mae: 2.4381

 50/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.8555 - mae: 2.4361

 53/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.8127 - mae: 2.4178

 58/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.7580 - mae: 2.4006

 62/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.6642 - mae: 2.3822

 65/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 9.0052 - mae: 2.4094

 69/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.8051 - mae: 2.3848

 73/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.4802 - mae: 2.3322

 77/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.4793 - mae: 2.3326

 80/522 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - loss: 8.6651 - mae: 2.3493

 84/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.4876 - mae: 2.3202

 88/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.3812 - mae: 2.3029

 92/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.4578 - mae: 2.3146

 96/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.5191 - mae: 2.3209

 99/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.4407 - mae: 2.3062

103/522 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - loss: 8.2739 - mae: 2.2805

107/522 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - loss: 8.1125 - mae: 2.2500

112/522 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - loss: 8.2006 - mae: 2.2500

117/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.1039 - mae: 2.2392

121/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.2828 - mae: 2.2599

125/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.2376 - mae: 2.2585

129/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.1546 - mae: 2.2409

133/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.0268 - mae: 2.2230

137/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.0204 - mae: 2.2217

140/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 8.0270 - mae: 2.2158

144/522 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - loss: 7.9631 - mae: 2.2137

148/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9179 - mae: 2.2070

152/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9723 - mae: 2.2137

156/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9048 - mae: 2.2033

160/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.8338 - mae: 2.1930

163/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9069 - mae: 2.2052

166/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9569 - mae: 2.2158

169/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9224 - mae: 2.2123

172/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9186 - mae: 2.2120

175/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.9146 - mae: 2.2108

178/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.8665 - mae: 2.2033

182/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.8676 - mae: 2.2049

186/522 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - loss: 7.8854 - mae: 2.2101

187/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8481 - mae: 2.2028

191/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.7890 - mae: 2.1967

194/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8179 - mae: 2.2031

197/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8322 - mae: 2.2068

201/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.7956 - mae: 2.2032

204/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8709 - mae: 2.2092

207/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8575 - mae: 2.2066

211/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8358 - mae: 2.2041

215/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8628 - mae: 2.2055

219/522 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 7.8620 - mae: 2.2087

224/522 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 7.8756 - mae: 2.2092

229/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 7.9115 - mae: 2.2103

234/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 8.0525 - mae: 2.2231

238/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 8.0709 - mae: 2.2254

243/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 8.0319 - mae: 2.2226

246/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 8.0437 - mae: 2.2284

250/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 8.0058 - mae: 2.2223

255/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 7.9514 - mae: 2.2150

260/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 7.8962 - mae: 2.2045

265/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 7.7996 - mae: 2.1874

270/522 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 7.7903 - mae: 2.1833

275/522 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 7.7618 - mae: 2.1812

280/522 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 7.7092 - mae: 2.1733

285/522 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 7.6742 - mae: 2.1714

290/522 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 7.6534 - mae: 2.1682

295/522 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 7.6262 - mae: 2.1630

300/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.6940 - mae: 2.1698

305/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.6309 - mae: 2.1584

310/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.5536 - mae: 2.1460

314/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.6124 - mae: 2.1499

319/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.6245 - mae: 2.1541

324/522 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 7.6345 - mae: 2.1545

329/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7122 - mae: 2.1664

334/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.6738 - mae: 2.1625

339/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.6303 - mae: 2.1562

344/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.6852 - mae: 2.1666

349/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7427 - mae: 2.1739

354/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7520 - mae: 2.1760

359/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7496 - mae: 2.1762

364/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7568 - mae: 2.1738

369/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7668 - mae: 2.1726

374/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7592 - mae: 2.1736

378/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7433 - mae: 2.1718

382/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.7505 - mae: 2.1723

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7482 - mae: 2.1731

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7403 - mae: 2.1749

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7273 - mae: 2.1739

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7226 - mae: 2.1763

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7955 - mae: 2.1827

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7902 - mae: 2.1802

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7434 - mae: 2.1722

416/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.7125 - mae: 2.1681

419/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.6907 - mae: 2.1656

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.6661 - mae: 2.1630

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.6910 - mae: 2.1655

433/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.6687 - mae: 2.1642

438/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 7.6799 - mae: 2.1616

443/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 7.6776 - mae: 2.1624

448/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 7.6932 - mae: 2.1647

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6920 - mae: 2.1667

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6373 - mae: 2.1587

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6201 - mae: 2.1570

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6349 - mae: 2.1603

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6387 - mae: 2.1602

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6308 - mae: 2.1593

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6396 - mae: 2.1604

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6663 - mae: 2.1669

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6482 - mae: 2.1655

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6828 - mae: 2.1714

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6885 - mae: 2.1721

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.7075 - mae: 2.1744

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.7485 - mae: 2.1802

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - loss: 7.7331 - mae: 2.1769 - val_loss: 5.5764 - val_mae: 1.8396

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 31s 61ms/step - loss: 3.3767 - mae: 1.5217

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.2170 - mae: 1.5994

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.0413 - mae: 1.7350

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.5068 - mae: 2.0258

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6880 - mae: 2.0365

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.3570 - mae: 2.0891

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8332 - mae: 2.0292

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9988 - mae: 2.0535

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8975 - mae: 2.0442

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9275 - mae: 2.0711

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9122 - mae: 2.0893

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.0821 - mae: 2.1068

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.2774 - mae: 2.1330

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.5094 - mae: 2.1641

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4610 - mae: 2.1693

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.6184 - mae: 2.1905

 91/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4855 - mae: 2.1780

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4233 - mae: 2.1694

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5082 - mae: 2.1705

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5190 - mae: 2.1685

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3750 - mae: 2.1491

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5594 - mae: 2.1631

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.6155 - mae: 2.1792

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5705 - mae: 2.1705

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.5604 - mae: 2.1661

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.7258 - mae: 2.1786

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8254 - mae: 2.1950

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.8605 - mae: 2.2015

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8029 - mae: 2.1826

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8733 - mae: 2.1884

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7769 - mae: 2.1723

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7656 - mae: 2.1743

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6880 - mae: 2.1640

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7498 - mae: 2.1767

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7537 - mae: 2.1803

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8081 - mae: 2.1896

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8082 - mae: 2.1934

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7046 - mae: 2.1768

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.6771 - mae: 2.1682

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6165 - mae: 2.1602

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7189 - mae: 2.1710

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7440 - mae: 2.1759

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.7066 - mae: 2.1736

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6521 - mae: 2.1631

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6079 - mae: 2.1595

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5919 - mae: 2.1596

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5462 - mae: 2.1526

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4792 - mae: 2.1435

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4976 - mae: 2.1479

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5016 - mae: 2.1488

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4650 - mae: 2.1450

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4642 - mae: 2.1489

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4576 - mae: 2.1449

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4178 - mae: 2.1401

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.3987 - mae: 2.1403

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4574 - mae: 2.1473

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4068 - mae: 2.1396

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4356 - mae: 2.1457

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4617 - mae: 2.1512

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4443 - mae: 2.1510

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4248 - mae: 2.1498

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4119 - mae: 2.1448

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4502 - mae: 2.1516

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4327 - mae: 2.1482

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4563 - mae: 2.1532

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5225 - mae: 2.1613

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5382 - mae: 2.1629

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5309 - mae: 2.1622

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5245 - mae: 2.1619

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5350 - mae: 2.1616

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5199 - mae: 2.1614

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5388 - mae: 2.1649

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5536 - mae: 2.1689

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5876 - mae: 2.1722

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5837 - mae: 2.1707

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.5974 - mae: 2.1732

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 7.6108 - mae: 2.1749 - val_loss: 8.8284 - val_mae: 2.3741

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 6.9763 - mae: 2.5663

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.4881 - mae: 2.3158

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.1073 - mae: 2.1078

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.4744 - mae: 2.1399

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.5931 - mae: 2.1379

 36/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9513 - mae: 2.2153

 44/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4997 - mae: 2.2625

 50/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.6644 - mae: 2.2950

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.0691 - mae: 2.2115

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9732 - mae: 2.2035

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9522 - mae: 2.1967

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.7745 - mae: 2.1815

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.5540 - mae: 2.1615

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.6623 - mae: 2.1732

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.7491 - mae: 2.1970

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.7112 - mae: 2.1947

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.7400 - mae: 2.1959

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.6722 - mae: 2.1878

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9774 - mae: 2.2267

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.0450 - mae: 2.2379

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.0252 - mae: 2.2332

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.0551 - mae: 2.2369

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9717 - mae: 2.2295

153/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.9536 - mae: 2.2311

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8591 - mae: 2.2190

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.8844 - mae: 2.2323

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7915 - mae: 2.2182

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 7.7140 - mae: 2.2088

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6447 - mae: 2.1994

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6552 - mae: 2.2032

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6260 - mae: 2.1996

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6253 - mae: 2.1997

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.5762 - mae: 2.1944

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6901 - mae: 2.2030

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6787 - mae: 2.1987

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6785 - mae: 2.2014

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.5807 - mae: 2.1827

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6582 - mae: 2.1953

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6972 - mae: 2.1996

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7117 - mae: 2.2004

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.6877 - mae: 2.1949

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7064 - mae: 2.1966

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.7374 - mae: 2.1988

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8610 - mae: 2.2089

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9197 - mae: 2.2143

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8776 - mae: 2.2087

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9237 - mae: 2.2098

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8586 - mae: 2.1997

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8653 - mae: 2.2017

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.8594 - mae: 2.2024

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.9101 - mae: 2.2031

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.9357 - mae: 2.2080

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8731 - mae: 2.1996

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8340 - mae: 2.1924

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8280 - mae: 2.1929

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7800 - mae: 2.1861

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7602 - mae: 2.1850

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7024 - mae: 2.1760

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.6959 - mae: 2.1761

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7408 - mae: 2.1879

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7234 - mae: 2.1848

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7045 - mae: 2.1853

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7631 - mae: 2.1966

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7502 - mae: 2.1938

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7471 - mae: 2.1966

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7726 - mae: 2.2035

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7874 - mae: 2.2058

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.8168 - mae: 2.2080

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7717 - mae: 2.2000

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.7475 - mae: 2.1972

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6961 - mae: 2.1881

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6741 - mae: 2.1858

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6509 - mae: 2.1842

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6048 - mae: 2.1773

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6055 - mae: 2.1771

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6092 - mae: 2.1773

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5773 - mae: 2.1722

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5853 - mae: 2.1740

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5638 - mae: 2.1715

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5881 - mae: 2.1747

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5950 - mae: 2.1751

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5817 - mae: 2.1724

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5714 - mae: 2.1693

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5379 - mae: 2.1635

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5454 - mae: 2.1642

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5267 - mae: 2.1612

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5531 - mae: 2.1670

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.5423 - mae: 2.1664

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 7.5367 - mae: 2.1671 - val_loss: 6.1097 - val_mae: 1.9270

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 23s 46ms/step - loss: 4.1307 - mae: 1.4995

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.2697 - mae: 2.3063

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.8724 - mae: 2.2731

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1574 - mae: 2.3400

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 7.4231 - mae: 2.2074

 38/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8658 - mae: 2.1318

 47/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.6594 - mae: 2.1022

 55/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.5890 - mae: 2.0774

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.7578 - mae: 2.0854

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.9540 - mae: 2.1114

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 7.0144 - mae: 2.1215

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 6.8357 - mae: 2.0970

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.7134 - mae: 2.0760

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8170 - mae: 2.0762

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8049 - mae: 2.0616

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8628 - mae: 2.0516

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.8299 - mae: 2.0523

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9954 - mae: 2.0734

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6.9796 - mae: 2.0628

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0575 - mae: 2.0748

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0709 - mae: 2.0752

158/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1129 - mae: 2.0834

165/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1053 - mae: 2.0868

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0651 - mae: 2.0799

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0263 - mae: 2.0721

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.0781 - mae: 2.0794

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1349 - mae: 2.0938

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2205 - mae: 2.1037

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2493 - mae: 2.1113

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3448 - mae: 2.1322

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.2951 - mae: 2.1235

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3153 - mae: 2.1308

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4620 - mae: 2.1477

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.4054 - mae: 2.1438

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.3458 - mae: 2.1369

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3836 - mae: 2.1465

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4060 - mae: 2.1504

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4447 - mae: 2.1601

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4693 - mae: 2.1656

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4586 - mae: 2.1638

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3742 - mae: 2.1484

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.4286 - mae: 2.1530

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7.3937 - mae: 2.1466

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.3491 - mae: 2.1390

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.3395 - mae: 2.1375

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5074 - mae: 2.1451

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5059 - mae: 2.1450

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.4662 - mae: 2.1348

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5430 - mae: 2.1486

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5489 - mae: 2.1513

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6402 - mae: 2.1575

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6637 - mae: 2.1587

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6083 - mae: 2.1490

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5967 - mae: 2.1471

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.5831 - mae: 2.1463

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6371 - mae: 2.1562

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7.6889 - mae: 2.1573

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.6852 - mae: 2.1572

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7078 - mae: 2.1590

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7226 - mae: 2.1634

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7922 - mae: 2.1707

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7979 - mae: 2.1746

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8004 - mae: 2.1750

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8135 - mae: 2.1765

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7903 - mae: 2.1754

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7649 - mae: 2.1712

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7499 - mae: 2.1695

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7803 - mae: 2.1737

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7961 - mae: 2.1753

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7843 - mae: 2.1759

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8018 - mae: 2.1794

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8030 - mae: 2.1799

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8167 - mae: 2.1819

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8406 - mae: 2.1861

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8262 - mae: 2.1857

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7748 - mae: 2.1779

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7925 - mae: 2.1818

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7833 - mae: 2.1829

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8354 - mae: 2.1895

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8259 - mae: 2.1889

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.8094 - mae: 2.1863

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.8125 - mae: 2.1864

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.8455 - mae: 2.1890

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.8504 - mae: 2.1892 - val_loss: 6.5681 - val_mae: 2.0180

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 34s 66ms/step - loss: 4.3420 - mae: 1.8604

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5292 - mae: 1.8722

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8123 - mae: 1.7533

 18/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2137 - mae: 1.8511

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.0198 - mae: 1.8161

 28/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5855 - mae: 1.9204

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0502 - mae: 1.9778

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8651 - mae: 1.9562

 46/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1691 - mae: 2.0071

 51/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3974 - mae: 2.0108

 57/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9166 - mae: 2.0804

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8906 - mae: 2.0966

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8454 - mae: 2.0830

 75/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8333 - mae: 2.0906

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9541 - mae: 2.1214

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8870 - mae: 2.1137

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8601 - mae: 2.1071

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.9537 - mae: 2.1167

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.0224 - mae: 2.1324

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3436 - mae: 2.1611

113/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4844 - mae: 2.1695

118/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.3355 - mae: 2.1397

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.2479 - mae: 2.1224

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.3312 - mae: 2.1236

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4285 - mae: 2.1386

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4934 - mae: 2.1555

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4439 - mae: 2.1515

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5744 - mae: 2.1567

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4616 - mae: 2.1348

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4807 - mae: 2.1447

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4609 - mae: 2.1484

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5070 - mae: 2.1574

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5897 - mae: 2.1674

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5223 - mae: 2.1548

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5861 - mae: 2.1636

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.4940 - mae: 2.1505

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4441 - mae: 2.1473

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5077 - mae: 2.1562

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.4799 - mae: 2.1504

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5509 - mae: 2.1577

211/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7.5826 - mae: 2.1546

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5852 - mae: 2.1555

217/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5525 - mae: 2.1504

221/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.4629 - mae: 2.1353

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.4285 - mae: 2.1309

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5097 - mae: 2.1428

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.5095 - mae: 2.1470

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5191 - mae: 2.1504

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5908 - mae: 2.1558

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5519 - mae: 2.1526

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5794 - mae: 2.1533

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5275 - mae: 2.1450

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5987 - mae: 2.1517

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.6098 - mae: 2.1499

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5917 - mae: 2.1461

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5877 - mae: 2.1494

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.6871 - mae: 2.1647

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.6324 - mae: 2.1576

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5848 - mae: 2.1518

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5360 - mae: 2.1432

312/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5450 - mae: 2.1439

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.5275 - mae: 2.1388

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.4816 - mae: 2.1330

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.4651 - mae: 2.1325

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4417 - mae: 2.1304

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4155 - mae: 2.1261

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4049 - mae: 2.1232

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4235 - mae: 2.1231

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4008 - mae: 2.1202

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4590 - mae: 2.1252

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4932 - mae: 2.1309

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4418 - mae: 2.1217

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4316 - mae: 2.1200

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4314 - mae: 2.1193

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.4122 - mae: 2.1181

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.3938 - mae: 2.1155

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.3769 - mae: 2.1137

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.3433 - mae: 2.1094

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.3280 - mae: 2.1069

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.3090 - mae: 2.1069

419/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.2691 - mae: 2.1019

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7.2614 - mae: 2.1011

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.2382 - mae: 2.0983

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.2575 - mae: 2.1010

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.2762 - mae: 2.1041

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.2551 - mae: 2.1008

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2779 - mae: 2.1059

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2974 - mae: 2.1085

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3381 - mae: 2.1124

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3137 - mae: 2.1095

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3139 - mae: 2.1089

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3324 - mae: 2.1118

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3019 - mae: 2.1056

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3042 - mae: 2.1053

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3154 - mae: 2.1079

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3140 - mae: 2.1069

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2900 - mae: 2.1029

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3065 - mae: 2.1089

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3202 - mae: 2.1121

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2860 - mae: 2.1067

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2826 - mae: 2.1079

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2837 - mae: 2.1090

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 7.2970 - mae: 2.1107 - val_loss: 6.8120 - val_mae: 2.0611

Epoch 22/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 3.0814 - mae: 1.5040

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8042 - mae: 1.9324

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.3368 - mae: 2.3190

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.5499 - mae: 2.2467

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.7316 - mae: 2.2659

 30/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.0775 - mae: 2.1620

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.3097 - mae: 2.1380

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.7735 - mae: 2.0581

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3793 - mae: 2.0144

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3145 - mae: 2.0125

 57/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.3158 - mae: 2.0251

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.4429 - mae: 2.0646

 65/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.2885 - mae: 2.0499

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.3501 - mae: 2.0697

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.2423 - mae: 2.0555

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.1770 - mae: 2.0449

 79/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.0862 - mae: 2.0324

 80/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.1952 - mae: 2.0468

 84/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.3563 - mae: 2.0789

 88/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.2592 - mae: 2.0636

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 7.2374 - mae: 2.0630

 92/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 7.1327 - mae: 2.0539

 97/522 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 7.1354 - mae: 2.0595

100/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.1114 - mae: 2.0612

104/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3588 - mae: 2.0919

106/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3634 - mae: 2.0963

110/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3457 - mae: 2.0963

114/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3301 - mae: 2.0949

118/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.2889 - mae: 2.0905

122/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.2842 - mae: 2.0853

127/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3525 - mae: 2.0945

131/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3413 - mae: 2.0933

135/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.3785 - mae: 2.0999

139/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.4444 - mae: 2.1097

143/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.4060 - mae: 2.1054

147/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.5677 - mae: 2.1144

151/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.5442 - mae: 2.1132

156/522 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 7.5497 - mae: 2.1192

161/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.5359 - mae: 2.1223

166/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.6232 - mae: 2.1324

170/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.5773 - mae: 2.1254

175/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.6233 - mae: 2.1415

179/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 7.5917 - mae: 2.1390

184/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 7.5316 - mae: 2.1356

188/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 7.5229 - mae: 2.1368

192/522 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - loss: 7.4336 - mae: 2.1232

196/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.4455 - mae: 2.1246

199/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.4189 - mae: 2.1230

203/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.3821 - mae: 2.1242

207/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.3518 - mae: 2.1219

211/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.3637 - mae: 2.1241

215/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.3551 - mae: 2.1190

219/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.2987 - mae: 2.1127

223/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.2222 - mae: 2.0998

225/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.2185 - mae: 2.0952

229/522 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 7.2668 - mae: 2.1051

234/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3754 - mae: 2.1136

239/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3541 - mae: 2.1117

243/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3125 - mae: 2.1056

248/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2741 - mae: 2.1019

253/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2469 - mae: 2.1005

258/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2633 - mae: 2.1005

263/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2757 - mae: 2.1029

266/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2836 - mae: 2.1011

270/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2819 - mae: 2.1000

274/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2859 - mae: 2.1033

278/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2703 - mae: 2.1006

282/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2989 - mae: 2.1019

287/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3187 - mae: 2.1036

289/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3167 - mae: 2.1028

293/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3021 - mae: 2.1009

297/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3320 - mae: 2.1032

299/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.3324 - mae: 2.1032

302/522 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 7.2999 - mae: 2.0994

306/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2675 - mae: 2.0966

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2565 - mae: 2.0942

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2931 - mae: 2.0953

317/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2905 - mae: 2.0955

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2669 - mae: 2.0924

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2547 - mae: 2.0906

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2583 - mae: 2.0932

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2732 - mae: 2.0973

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2613 - mae: 2.0968

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2792 - mae: 2.0994

336/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3228 - mae: 2.1044

340/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2998 - mae: 2.1021

344/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2917 - mae: 2.0981

348/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2899 - mae: 2.0978

352/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3350 - mae: 2.1039

356/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3388 - mae: 2.1071

360/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3382 - mae: 2.1062

364/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3241 - mae: 2.1041

368/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2837 - mae: 2.0969

371/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.3029 - mae: 2.0978

372/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2991 - mae: 2.0971

374/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.3204 - mae: 2.1023

379/522 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 7.3326 - mae: 2.1050

383/522 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 7.2952 - mae: 2.0996

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2951 - mae: 2.1001

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2826 - mae: 2.0994

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2820 - mae: 2.1003

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.3039 - mae: 2.1051

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2806 - mae: 2.1011

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2586 - mae: 2.0972

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2606 - mae: 2.0977

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2482 - mae: 2.0959

417/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2054 - mae: 2.0901

421/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.1948 - mae: 2.0895

426/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.1752 - mae: 2.0892

431/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2648 - mae: 2.1006

436/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 7.2871 - mae: 2.1023

440/522 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 7.2706 - mae: 2.0981

441/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2769 - mae: 2.1001

445/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.2686 - mae: 2.0992

448/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.3007 - mae: 2.1026

452/522 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 7.3117 - mae: 2.1052

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.2915 - mae: 2.1009

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.2999 - mae: 2.1033

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.2787 - mae: 2.1005

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2559 - mae: 2.0990

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2711 - mae: 2.1019

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2574 - mae: 2.1012

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2356 - mae: 2.0974

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2438 - mae: 2.0969

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2487 - mae: 2.1015

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2759 - mae: 2.1039

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2988 - mae: 2.1046

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2859 - mae: 2.1043

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 15ms/step - loss: 7.2697 - mae: 2.1018 - val_loss: 6.5262 - val_mae: 2.0137

Epoch 23/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 5.3123 - mae: 2.1915

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.9805 - mae: 2.3725

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.3881 - mae: 2.4117

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.7572 - mae: 2.2819

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.3057 - mae: 2.2927

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.6483 - mae: 2.2303

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.4964 - mae: 2.2113

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.2002 - mae: 2.1640

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.3924 - mae: 2.2103

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.2509 - mae: 2.1882

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.1195 - mae: 2.1668

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3997 - mae: 2.1707

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2765 - mae: 2.1711

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2877 - mae: 2.1582

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2270 - mae: 2.1431

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1396 - mae: 2.1337

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1943 - mae: 2.1477

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1599 - mae: 2.1399

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2202 - mae: 2.1449

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4326 - mae: 2.1681

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3016 - mae: 2.1429

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4139 - mae: 2.1566

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4373 - mae: 2.1591

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3488 - mae: 2.1488

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2661 - mae: 2.1365

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3969 - mae: 2.1517

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3316 - mae: 2.1433

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3920 - mae: 2.1486

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3362 - mae: 2.1451

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2246 - mae: 2.1245

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3177 - mae: 2.1366

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4561 - mae: 2.1549

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.4511 - mae: 2.1589

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3894 - mae: 2.1489

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2813 - mae: 2.1318

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2955 - mae: 2.1324

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2378 - mae: 2.1244

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1692 - mae: 2.1127

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2451 - mae: 2.1234

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2284 - mae: 2.1170

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2786 - mae: 2.1234

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2342 - mae: 2.1181

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2019 - mae: 2.1106

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2307 - mae: 2.1179

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2604 - mae: 2.1211

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2178 - mae: 2.1156

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2026 - mae: 2.1136

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1586 - mae: 2.1116

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1179 - mae: 2.1071

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1461 - mae: 2.1128

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1669 - mae: 2.1135

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1423 - mae: 2.1092

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2285 - mae: 2.1183

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2190 - mae: 2.1181

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2196 - mae: 2.1194

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2372 - mae: 2.1223

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1949 - mae: 2.1156

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2027 - mae: 2.1179

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1954 - mae: 2.1163

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1913 - mae: 2.1157

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1629 - mae: 2.1110

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1944 - mae: 2.1120

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2067 - mae: 2.1086

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2135 - mae: 2.1119

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2085 - mae: 2.1111

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1699 - mae: 2.1067

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1444 - mae: 2.1019

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1886 - mae: 2.1081

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2055 - mae: 2.1086

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2063 - mae: 2.1073

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.2192 - mae: 2.1096

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2254 - mae: 2.1101

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2135 - mae: 2.1091

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1833 - mae: 2.1052

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1524 - mae: 2.1013

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1455 - mae: 2.0990

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1112 - mae: 2.0946

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0766 - mae: 2.0887

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0808 - mae: 2.0906

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0877 - mae: 2.0936

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0930 - mae: 2.0933

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1305 - mae: 2.0991

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1409 - mae: 2.1033

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1527 - mae: 2.1053

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1132 - mae: 2.0988

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0987 - mae: 2.0928

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1010 - mae: 2.0922

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1279 - mae: 2.0914

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1096 - mae: 2.0855

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1095 - mae: 2.0866

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 7.1077 - mae: 2.0864 - val_loss: 6.3195 - val_mae: 1.9879

Epoch 24/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 55ms/step - loss: 5.0736 - mae: 1.9417

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2162 - mae: 1.8187

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5660 - mae: 1.9027

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5176 - mae: 1.8868

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7878 - mae: 1.9392

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6024 - mae: 1.9047

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5161 - mae: 1.8947

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4080 - mae: 1.8605

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3786 - mae: 1.8452

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3071 - mae: 1.8173

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8674 - mae: 1.9137

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7076 - mae: 1.8826

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9747 - mae: 1.9132

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4766 - mae: 1.9937

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4325 - mae: 1.9889

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4136 - mae: 1.9811

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6866 - mae: 2.0214

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.8150 - mae: 2.0453

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2168 - mae: 2.0888

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.0517 - mae: 2.0649

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.9979 - mae: 2.0614

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.0132 - mae: 2.0629

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.8853 - mae: 2.0433

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.0092 - mae: 2.0634

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.0518 - mae: 2.0792

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.9970 - mae: 2.0731

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.9153 - mae: 2.0617

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.8969 - mae: 2.0588

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.8072 - mae: 2.0404

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7421 - mae: 2.0372

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7943 - mae: 2.0432

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9050 - mae: 2.0583

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8955 - mae: 2.0600

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8345 - mae: 2.0536

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9220 - mae: 2.0681

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8647 - mae: 2.0618

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8316 - mae: 2.0574

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8715 - mae: 2.0605

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8345 - mae: 2.0567

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8057 - mae: 2.0532

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8888 - mae: 2.0671

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9156 - mae: 2.0724

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8738 - mae: 2.0684

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8649 - mae: 2.0661

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7837 - mae: 2.0535

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7377 - mae: 2.0484

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6760 - mae: 2.0374

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.7928 - mae: 2.0540

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.7703 - mae: 2.0512

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.7845 - mae: 2.0533

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8238 - mae: 2.0544

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.7382 - mae: 2.0385

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8228 - mae: 2.0515

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8886 - mae: 2.0576

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8731 - mae: 2.0537

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8793 - mae: 2.0557

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8793 - mae: 2.0562

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9623 - mae: 2.0675

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9735 - mae: 2.0697

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0506 - mae: 2.0828

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1193 - mae: 2.0943

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1405 - mae: 2.0958

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1617 - mae: 2.0998

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1124 - mae: 2.0886

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1184 - mae: 2.0898

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.1172 - mae: 2.0896

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1295 - mae: 2.0890

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1260 - mae: 2.0882

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1706 - mae: 2.0932

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1463 - mae: 2.0903

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1286 - mae: 2.0886

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1851 - mae: 2.0916

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2391 - mae: 2.0972

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2682 - mae: 2.1038

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2381 - mae: 2.1004

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2594 - mae: 2.1028

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2271 - mae: 2.0978

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2290 - mae: 2.0966

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1943 - mae: 2.0911

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1603 - mae: 2.0856

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1407 - mae: 2.0854

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1447 - mae: 2.0853

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1240 - mae: 2.0828

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.1144 - mae: 2.0816 - val_loss: 7.5301 - val_mae: 2.1869

Epoch 25/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 4.0357 - mae: 1.6768

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 4.9530 - mae: 1.6905

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.6874 - mae: 1.9675

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.0598 - mae: 2.0835

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7724 - mae: 2.0390

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7116 - mae: 1.9801

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8544 - mae: 2.0069

 41/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.7084 - mae: 1.9937

 46/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6253 - mae: 1.9774

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3365 - mae: 1.9458

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.2220 - mae: 1.9293

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.2238 - mae: 1.9383

 62/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.0572 - mae: 1.9048

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4532 - mae: 1.9656

 71/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.2448 - mae: 1.9289

 75/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5728 - mae: 1.9714

 79/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4844 - mae: 1.9588

 84/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.4346 - mae: 1.9573

 89/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.5768 - mae: 1.9772

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.4565 - mae: 1.9592

100/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.7006 - mae: 2.0018

105/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5394 - mae: 1.9698

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5542 - mae: 1.9821

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4549 - mae: 1.9665

121/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4247 - mae: 1.9615

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5573 - mae: 1.9704

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5221 - mae: 1.9696

138/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5072 - mae: 1.9724

143/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5053 - mae: 1.9769

148/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5932 - mae: 1.9912

152/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.5274 - mae: 1.9812

157/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4958 - mae: 1.9804

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.4393 - mae: 1.9711

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.3675 - mae: 1.9611

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5852 - mae: 1.9802

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5365 - mae: 1.9698

183/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.5596 - mae: 1.9699

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.6645 - mae: 1.9863

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.7142 - mae: 1.9947

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.7630 - mae: 2.0047

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8731 - mae: 2.0151

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9091 - mae: 2.0218

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9279 - mae: 2.0288

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8789 - mae: 2.0218

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8648 - mae: 2.0224

219/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8549 - mae: 2.0202

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8457 - mae: 2.0200

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8749 - mae: 2.0269

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8283 - mae: 2.0190

236/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8223 - mae: 2.0217

241/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8205 - mae: 2.0199

245/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8187 - mae: 2.0222

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.8774 - mae: 2.0313

255/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.9558 - mae: 2.0390

259/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 6.9881 - mae: 2.0468

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.9738 - mae: 2.0454

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 7.0033 - mae: 2.0455

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.9687 - mae: 2.0418

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 6.9564 - mae: 2.0415

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0642 - mae: 2.0561

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0799 - mae: 2.0571

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0639 - mae: 2.0583

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.1151 - mae: 2.0692

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.1307 - mae: 2.0696

315/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0600 - mae: 2.0600

320/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.0534 - mae: 2.0600

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9971 - mae: 2.0512

331/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9252 - mae: 2.0371

337/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9568 - mae: 2.0448

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9123 - mae: 2.0376

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9636 - mae: 2.0462

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9467 - mae: 2.0451

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9291 - mae: 2.0437

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9442 - mae: 2.0446

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9346 - mae: 2.0428

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9694 - mae: 2.0486

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9689 - mae: 2.0483

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9899 - mae: 2.0519

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0071 - mae: 2.0546

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0286 - mae: 2.0622

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0819 - mae: 2.0682

416/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0862 - mae: 2.0700

422/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0974 - mae: 2.0724

428/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.1312 - mae: 2.0772

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1119 - mae: 2.0743

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1213 - mae: 2.0755

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1359 - mae: 2.0764

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1045 - mae: 2.0732

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0749 - mae: 2.0679

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0523 - mae: 2.0667

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0160 - mae: 2.0616

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0168 - mae: 2.0633

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0076 - mae: 2.0627

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0118 - mae: 2.0642

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0273 - mae: 2.0656

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0525 - mae: 2.0695

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0314 - mae: 2.0664

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0176 - mae: 2.0624

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0328 - mae: 2.0635

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 7.0261 - mae: 2.0627 - val_loss: 5.5634 - val_mae: 1.8666

Epoch 26/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 62ms/step - loss: 5.2612 - mae: 1.9769

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.3582 - mae: 2.2589

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4283 - mae: 2.1472

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.1188 - mae: 2.2219

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.3328 - mae: 2.0721

 33/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.2109 - mae: 2.0352

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.9576 - mae: 1.9884

 45/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7085 - mae: 1.9297

 51/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4389 - mae: 1.8880

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7283 - mae: 1.9247

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7544 - mae: 1.9080

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8438 - mae: 1.9292

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7824 - mae: 1.9101

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9152 - mae: 1.9203

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9697 - mae: 1.9322

 88/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1788 - mae: 1.9578

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2977 - mae: 1.9816

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3147 - mae: 1.9909

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2079 - mae: 1.9691

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2406 - mae: 1.9830

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3442 - mae: 1.9957

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4713 - mae: 2.0116

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4177 - mae: 2.0065

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3760 - mae: 1.9986

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4014 - mae: 2.0050

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3712 - mae: 1.9985

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2856 - mae: 1.9786

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2678 - mae: 1.9771

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4786 - mae: 2.0012

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5671 - mae: 2.0239

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5966 - mae: 2.0148

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6014 - mae: 2.0214

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6140 - mae: 2.0224

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6524 - mae: 2.0340

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6022 - mae: 2.0265

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6285 - mae: 2.0333

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6834 - mae: 2.0439

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8258 - mae: 2.0589

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9365 - mae: 2.0755

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8780 - mae: 2.0685

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9194 - mae: 2.0775

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9541 - mae: 2.0847

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9372 - mae: 2.0839

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9053 - mae: 2.0804

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9399 - mae: 2.0817

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0111 - mae: 2.0797

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9996 - mae: 2.0778

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9798 - mae: 2.0757

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9191 - mae: 2.0650

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8642 - mae: 2.0574

298/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.8316 - mae: 2.0523

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8069 - mae: 2.0477

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8055 - mae: 2.0435

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.7979 - mae: 2.0450

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8247 - mae: 2.0479

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8175 - mae: 2.0465

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9237 - mae: 2.0576

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9269 - mae: 2.0600

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9078 - mae: 2.0590

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8795 - mae: 2.0561

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9565 - mae: 2.0632

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9646 - mae: 2.0605

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9483 - mae: 2.0593

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9585 - mae: 2.0588

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9792 - mae: 2.0626

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9810 - mae: 2.0640

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9876 - mae: 2.0618

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9918 - mae: 2.0633

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9900 - mae: 2.0637

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0029 - mae: 2.0673

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7.0093 - mae: 2.0703

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0110 - mae: 2.0722

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0201 - mae: 2.0745

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0132 - mae: 2.0747

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9777 - mae: 2.0681

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9775 - mae: 2.0702

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9944 - mae: 2.0740

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9970 - mae: 2.0743

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9961 - mae: 2.0734

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9994 - mae: 2.0745

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9917 - mae: 2.0701

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9504 - mae: 2.0613

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9724 - mae: 2.0677

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9569 - mae: 2.0673

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9361 - mae: 2.0647

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9928 - mae: 2.0694

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0048 - mae: 2.0726

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9893 - mae: 2.0711

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9898 - mae: 2.0708

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.9519 - mae: 2.0633 - val_loss: 5.6238 - val_mae: 1.8602

Epoch 27/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 33s 64ms/step - loss: 9.1524 - mae: 2.5055

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.6975 - mae: 2.1128

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8772 - mae: 1.9798

 18/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.2937 - mae: 2.0894

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8470 - mae: 1.9986

 28/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.0297 - mae: 2.0147

 32/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.9062 - mae: 2.0251

 38/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.7836 - mae: 2.0026

 44/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.6970 - mae: 1.9993

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6863 - mae: 2.0228

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3726 - mae: 1.9738

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1086 - mae: 1.9295

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0615 - mae: 1.9269

 75/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9907 - mae: 1.9247

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9220 - mae: 1.9108

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8464 - mae: 1.9002

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8066 - mae: 1.9000

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8366 - mae: 1.9097

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8169 - mae: 1.9046

105/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7870 - mae: 1.8965

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8025 - mae: 1.8964

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7404 - mae: 1.8816

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6081 - mae: 1.8555

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9298 - mae: 1.8846

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0149 - mae: 1.8980

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1549 - mae: 1.9164

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1781 - mae: 1.9195

153/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.2332 - mae: 1.9356

159/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.2163 - mae: 1.9328

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1660 - mae: 1.9210

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1676 - mae: 1.9270

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.2209 - mae: 1.9370

183/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4013 - mae: 1.9553

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3145 - mae: 1.9394

195/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.3345 - mae: 1.9433

201/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4114 - mae: 1.9495

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.4005 - mae: 1.9495

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5444 - mae: 1.9737

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5949 - mae: 1.9857

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5325 - mae: 1.9762

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4706 - mae: 1.9705

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.4863 - mae: 1.9691

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5203 - mae: 1.9779

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5078 - mae: 1.9781

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5153 - mae: 1.9822

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4446 - mae: 1.9686

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4360 - mae: 1.9657

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4964 - mae: 1.9761

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4403 - mae: 1.9663

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3848 - mae: 1.9575

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3709 - mae: 1.9554

298/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3318 - mae: 1.9499

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3285 - mae: 1.9502

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3900 - mae: 1.9586

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3608 - mae: 1.9526

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3328 - mae: 1.9502

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3593 - mae: 1.9548

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3104 - mae: 1.9489

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3396 - mae: 1.9531

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3519 - mae: 1.9570

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3768 - mae: 1.9583

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3766 - mae: 1.9605

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3871 - mae: 1.9627

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3571 - mae: 1.9589

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3393 - mae: 1.9562

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3538 - mae: 1.9609

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3773 - mae: 1.9648

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3900 - mae: 1.9691

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4525 - mae: 1.9807

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5040 - mae: 1.9874

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5036 - mae: 1.9881

412/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5045 - mae: 1.9878

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5092 - mae: 1.9909

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5072 - mae: 1.9912

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4856 - mae: 1.9874

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5220 - mae: 1.9898

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5301 - mae: 1.9898

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5324 - mae: 1.9908

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5339 - mae: 1.9929

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5079 - mae: 1.9893

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5240 - mae: 1.9926

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6259 - mae: 2.0064

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6229 - mae: 2.0065

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5990 - mae: 2.0033

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6601 - mae: 2.0117

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6572 - mae: 2.0114

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6531 - mae: 2.0119

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6464 - mae: 2.0117

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6198 - mae: 2.0085

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6347 - mae: 2.0098

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.6326 - mae: 2.0094 - val_loss: 5.5955 - val_mae: 1.8525

Epoch 28/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 54ms/step - loss: 9.4290 - mae: 2.3575

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.4745 - mae: 2.0891

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6206 - mae: 2.0215

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.0932 - mae: 2.0624

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9416 - mae: 2.0933

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8799 - mae: 2.1244

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.1586 - mae: 2.1966

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8420 - mae: 2.1358

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4964 - mae: 2.0634

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4681 - mae: 2.0609

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3790 - mae: 2.0412

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3568 - mae: 2.0245

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2395 - mae: 1.9867

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2422 - mae: 1.9897

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2933 - mae: 1.9985

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2138 - mae: 1.9829

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2575 - mae: 1.9870

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1492 - mae: 1.9726

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0840 - mae: 1.9643

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0298 - mae: 1.9530

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0957 - mae: 1.9687

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0788 - mae: 1.9671

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2357 - mae: 1.9938

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3470 - mae: 2.0062

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3609 - mae: 2.0174

153/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2577 - mae: 2.0064

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2966 - mae: 2.0133

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2851 - mae: 2.0131

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2165 - mae: 2.0022

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2018 - mae: 1.9983

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1688 - mae: 1.9971

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1302 - mae: 1.9868

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0764 - mae: 1.9777

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0865 - mae: 1.9771

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0540 - mae: 1.9663

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9984 - mae: 1.9536

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9678 - mae: 1.9529

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9532 - mae: 1.9489

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9408 - mae: 1.9463

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9930 - mae: 1.9573

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9656 - mae: 1.9515

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9751 - mae: 1.9466

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9080 - mae: 1.9359

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9053 - mae: 1.9365

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8617 - mae: 1.9295

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0094 - mae: 1.9457

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0306 - mae: 1.9538

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0593 - mae: 1.9553

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0790 - mae: 1.9592

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1082 - mae: 1.9611

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1002 - mae: 1.9602

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1041 - mae: 1.9615

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0946 - mae: 1.9593

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0986 - mae: 1.9601

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1230 - mae: 1.9643

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1515 - mae: 1.9704

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1467 - mae: 1.9680

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1782 - mae: 1.9749

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1519 - mae: 1.9724

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1252 - mae: 1.9688

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1974 - mae: 1.9750

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1648 - mae: 1.9697

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2283 - mae: 1.9786

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2525 - mae: 1.9816

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2579 - mae: 1.9847

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2675 - mae: 1.9876

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2877 - mae: 1.9908

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3284 - mae: 1.9969

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3352 - mae: 1.9980

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3118 - mae: 1.9953

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2991 - mae: 1.9927

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3183 - mae: 1.9980

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3261 - mae: 2.0013

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3421 - mae: 2.0033

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3854 - mae: 2.0112

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3697 - mae: 2.0075

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3646 - mae: 2.0074

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3703 - mae: 2.0096

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3809 - mae: 2.0114

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4092 - mae: 2.0105

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4224 - mae: 2.0113

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4075 - mae: 2.0087

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4255 - mae: 2.0099

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4292 - mae: 2.0109

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4318 - mae: 2.0115

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3992 - mae: 2.0059

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.3895 - mae: 2.0026 - val_loss: 6.1216 - val_mae: 1.9582

Epoch 29/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - loss: 9.5556 - mae: 2.7117

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9237 - mae: 2.0494

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3104 - mae: 1.7785

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1255 - mae: 1.9446

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.6785 - mae: 1.8573

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0672 - mae: 1.7377

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5110 - mae: 1.8393

 45/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7137 - mae: 1.8930

 51/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6305 - mae: 1.8915

 57/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0882 - mae: 1.9369

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3455 - mae: 1.9790

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.4696 - mae: 1.9877

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.6294 - mae: 2.0066

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.6664 - mae: 2.0064

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.7580 - mae: 2.0298

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.7726 - mae: 2.0421

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.6571 - mae: 2.0291

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.5536 - mae: 2.0155

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.4482 - mae: 2.0016

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4855 - mae: 2.0086

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3810 - mae: 1.9939

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3855 - mae: 1.9939

137/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3287 - mae: 1.9869

143/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2016 - mae: 1.9651

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2629 - mae: 1.9771

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2237 - mae: 1.9718

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2104 - mae: 1.9695

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2122 - mae: 1.9693

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1566 - mae: 1.9610

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2194 - mae: 1.9753

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2240 - mae: 1.9744

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2191 - mae: 1.9740

194/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2273 - mae: 1.9762

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2440 - mae: 1.9766

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3243 - mae: 1.9911

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4193 - mae: 2.0033

216/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4253 - mae: 2.0039

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5251 - mae: 2.0200

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5965 - mae: 2.0300

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5732 - mae: 2.0271

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5650 - mae: 2.0290

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5604 - mae: 2.0314

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5369 - mae: 2.0236

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5826 - mae: 2.0265

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5588 - mae: 2.0242

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5411 - mae: 2.0250

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5715 - mae: 2.0316

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5395 - mae: 2.0289

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5147 - mae: 2.0271

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4831 - mae: 2.0211

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5224 - mae: 2.0268

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5381 - mae: 2.0306

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5145 - mae: 2.0253

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4961 - mae: 2.0228

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4802 - mae: 2.0233

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4938 - mae: 2.0244

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4857 - mae: 2.0226

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4828 - mae: 2.0208

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5035 - mae: 2.0247

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5734 - mae: 2.0290

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5731 - mae: 2.0283

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5588 - mae: 2.0261

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5374 - mae: 2.0233

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5474 - mae: 2.0249

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5405 - mae: 2.0262

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5358 - mae: 2.0278

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5013 - mae: 2.0217

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4492 - mae: 2.0125

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4650 - mae: 2.0140

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4614 - mae: 2.0142

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4561 - mae: 2.0118

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4838 - mae: 2.0145

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5009 - mae: 2.0164

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5291 - mae: 2.0214

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5006 - mae: 2.0183

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5266 - mae: 2.0216

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5034 - mae: 2.0192

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5022 - mae: 2.0193

420/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4758 - mae: 2.0158

425/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4636 - mae: 2.0154

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.4938 - mae: 2.0213

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5388 - mae: 2.0264

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5241 - mae: 2.0244

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5087 - mae: 2.0229

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5411 - mae: 2.0274

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5618 - mae: 2.0328

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5295 - mae: 2.0267

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5474 - mae: 2.0286

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5183 - mae: 2.0238

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5649 - mae: 2.0314

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5820 - mae: 2.0341

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5627 - mae: 2.0304

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6217 - mae: 2.0357

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6285 - mae: 2.0363

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6060 - mae: 2.0336

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5844 - mae: 2.0295

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5832 - mae: 2.0293

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5475 - mae: 2.0232

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5315 - mae: 2.0202

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 6.5391 - mae: 2.0216 - val_loss: 7.4617 - val_mae: 2.1815

Epoch 30/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 30s 59ms/step - loss: 1.0058 - mae: 0.8733

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.5483 - mae: 2.1882

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.1127 - mae: 1.8713

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 6.4408 - mae: 1.9754

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.9873 - mae: 1.8951

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 5.8384 - mae: 1.8576

 41/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.7665 - mae: 1.8429

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.7961 - mae: 1.8346

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.9786 - mae: 1.8653

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.1618 - mae: 1.8866

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0181 - mae: 1.8747

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9361 - mae: 1.8674

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8586 - mae: 1.8556

 83/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9194 - mae: 1.8626

 89/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0139 - mae: 1.8791

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3028 - mae: 1.9075

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2249 - mae: 1.9065

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3937 - mae: 1.9136

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4145 - mae: 1.9214

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3785 - mae: 1.9210

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3778 - mae: 1.9221

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3164 - mae: 1.9174

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4578 - mae: 1.9398

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5465 - mae: 1.9500

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5157 - mae: 1.9475

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4007 - mae: 1.9272

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3354 - mae: 1.9235

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2864 - mae: 1.9184

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2197 - mae: 1.9031

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1967 - mae: 1.9004

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2098 - mae: 1.9072

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1675 - mae: 1.8994

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1258 - mae: 1.8921

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1540 - mae: 1.8987

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2722 - mae: 1.9153

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2783 - mae: 1.9200

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4376 - mae: 1.9396

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4597 - mae: 1.9494

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4304 - mae: 1.9467

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3766 - mae: 1.9386

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3611 - mae: 1.9374

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3696 - mae: 1.9413

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4050 - mae: 1.9493

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4264 - mae: 1.9520

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3787 - mae: 1.9420

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3725 - mae: 1.9427

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3372 - mae: 1.9398

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3313 - mae: 1.9401

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3224 - mae: 1.9364

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3625 - mae: 1.9438

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3739 - mae: 1.9494

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3508 - mae: 1.9482

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3911 - mae: 1.9527

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3777 - mae: 1.9502

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3905 - mae: 1.9565

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4040 - mae: 1.9570

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3942 - mae: 1.9571

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3929 - mae: 1.9574

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4028 - mae: 1.9584

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4180 - mae: 1.9599

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4549 - mae: 1.9643

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4782 - mae: 1.9694

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5116 - mae: 1.9757

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4933 - mae: 1.9760

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5013 - mae: 1.9752

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.5348 - mae: 1.9794

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5234 - mae: 1.9790

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5494 - mae: 1.9823

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5285 - mae: 1.9791

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5405 - mae: 1.9802

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5369 - mae: 1.9818

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5332 - mae: 1.9834

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5365 - mae: 1.9841

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5189 - mae: 1.9816

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5418 - mae: 1.9869

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5477 - mae: 1.9891

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5303 - mae: 1.9871

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5269 - mae: 1.9886

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4828 - mae: 1.9801

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4476 - mae: 1.9747

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4656 - mae: 1.9759

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5504 - mae: 1.9900

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5253 - mae: 1.9869

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5043 - mae: 1.9843

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.5089 - mae: 1.9842 - val_loss: 7.4536 - val_mae: 2.1825

Epoch 31/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 39s 76ms/step - loss: 10.0392 - mae: 2.8423

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.3676 - mae: 2.0440

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.5314 - mae: 2.2409

 17/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6210 - mae: 2.0641

 23/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.7664 - mae: 2.1058

 29/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8478 - mae: 2.1209

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1741 - mae: 1.9976

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6678 - mae: 2.0421

 46/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3131 - mae: 1.9845

 52/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1291 - mae: 1.9604

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1263 - mae: 1.9491

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1561 - mae: 1.9528

 70/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2131 - mae: 1.9559

 76/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1052 - mae: 1.9367

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9714 - mae: 1.9185

 88/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0507 - mae: 1.9325

 94/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1980 - mae: 1.9547

100/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2151 - mae: 1.9667

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2591 - mae: 1.9635

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3611 - mae: 1.9916

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3107 - mae: 1.9900

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2557 - mae: 1.9857

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2380 - mae: 1.9879

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2421 - mae: 1.9853

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1820 - mae: 1.9753

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2340 - mae: 1.9848

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2557 - mae: 1.9848

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3140 - mae: 1.9934

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3606 - mae: 1.9881

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3368 - mae: 1.9878

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2916 - mae: 1.9810

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4449 - mae: 2.0020

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4689 - mae: 2.0064

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4637 - mae: 2.0091

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4424 - mae: 2.0001

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4233 - mae: 1.9964

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3873 - mae: 1.9891

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3570 - mae: 1.9856

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4213 - mae: 1.9953

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3650 - mae: 1.9917

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2941 - mae: 1.9792

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3168 - mae: 1.9830

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3355 - mae: 1.9867

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3964 - mae: 1.9969

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4361 - mae: 2.0045

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4173 - mae: 1.9991

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4601 - mae: 2.0075

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4331 - mae: 2.0046

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4344 - mae: 2.0028

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4472 - mae: 2.0042

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4073 - mae: 1.9994

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3579 - mae: 1.9868

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2824 - mae: 1.9725

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2649 - mae: 1.9711

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2236 - mae: 1.9632

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2631 - mae: 1.9692

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2336 - mae: 1.9650

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2220 - mae: 1.9630

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2427 - mae: 1.9656

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2429 - mae: 1.9659

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2411 - mae: 1.9673

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2170 - mae: 1.9622

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2434 - mae: 1.9624

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2415 - mae: 1.9627

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2842 - mae: 1.9714

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2757 - mae: 1.9722

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3393 - mae: 1.9777

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4187 - mae: 1.9868

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4410 - mae: 1.9891

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4065 - mae: 1.9834

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4228 - mae: 1.9869

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4255 - mae: 1.9865

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4365 - mae: 1.9879

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4532 - mae: 1.9876

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5039 - mae: 1.9937

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4985 - mae: 1.9930

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5143 - mae: 1.9966

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4879 - mae: 1.9928

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5159 - mae: 1.9967

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5426 - mae: 1.9988

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5123 - mae: 1.9925

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5150 - mae: 1.9921

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5041 - mae: 1.9925

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4878 - mae: 1.9881

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5024 - mae: 1.9909

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5303 - mae: 1.9974

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5237 - mae: 1.9979

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.5228 - mae: 1.9979 - val_loss: 9.3028 - val_mae: 2.4719

Epoch 32/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 44:05 5s/step - loss: 1.2608 - mae: 0.8513

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0564 - mae: 2.0004

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2009 - mae: 1.7909

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5393 - mae: 1.7786

 27/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6750 - mae: 1.8410

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4666 - mae: 1.8373

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4732 - mae: 1.8428

 46/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4058 - mae: 1.8407

 52/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4353 - mae: 1.8514

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6243 - mae: 1.8857

 64/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5646 - mae: 1.8898

 70/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5531 - mae: 1.8896

 77/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4913 - mae: 1.8808

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5698 - mae: 1.9011

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6238 - mae: 1.9076

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7424 - mae: 1.9233

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.7557 - mae: 1.9158

111/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.6839 - mae: 1.9073

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7033 - mae: 1.9099

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7862 - mae: 1.9248

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8819 - mae: 1.9341

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8177 - mae: 1.9221

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8308 - mae: 1.9209

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8831 - mae: 1.9228

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.8139 - mae: 1.9090

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.9295 - mae: 1.9190

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.0288 - mae: 1.9349

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0331 - mae: 1.9338

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.2609 - mae: 1.9606

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.2484 - mae: 1.9618

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.2764 - mae: 1.9721

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1823 - mae: 1.9555

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.2211 - mae: 1.9614

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1754 - mae: 1.9596

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1425 - mae: 1.9540

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1519 - mae: 1.9510

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1463 - mae: 1.9474

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1057 - mae: 1.9417

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1760 - mae: 1.9482

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1046 - mae: 1.9385

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.0988 - mae: 1.9371

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.1118 - mae: 1.9391

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.0851 - mae: 1.9329

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6.0490 - mae: 1.9251

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0815 - mae: 1.9299

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0557 - mae: 1.9271

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0074 - mae: 1.9205

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9793 - mae: 1.9154

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9823 - mae: 1.9171

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0249 - mae: 1.9202

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0231 - mae: 1.9202

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9958 - mae: 1.9124

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0015 - mae: 1.9149

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0046 - mae: 1.9186

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0389 - mae: 1.9229

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0643 - mae: 1.9246

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0826 - mae: 1.9288

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0412 - mae: 1.9212

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0021 - mae: 1.9134

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.0002 - mae: 1.9165

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9681 - mae: 1.9118

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9990 - mae: 1.9150

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9794 - mae: 1.9132

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9774 - mae: 1.9134

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9699 - mae: 1.9119

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9515 - mae: 1.9088

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9205 - mae: 1.9046

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8949 - mae: 1.9018

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8845 - mae: 1.9008

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9188 - mae: 1.9053

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9119 - mae: 1.9048

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8978 - mae: 1.9011

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8942 - mae: 1.9008

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9060 - mae: 1.9015

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9244 - mae: 1.9057

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9471 - mae: 1.9089

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9428 - mae: 1.9100

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9951 - mae: 1.9175

522/522 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - loss: 5.9928 - mae: 1.9168 - val_loss: 6.5313 - val_mae: 2.0434

Epoch 33/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 10.1037 - mae: 2.4453

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.6647 - mae: 2.1019

 15/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 6.4957 - mae: 1.9943

 22/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.3440 - mae: 1.7976

 29/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.5236 - mae: 1.8735

 37/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.6068 - mae: 1.8560

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4635 - mae: 1.8323

 52/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.7367 - mae: 1.8604

 59/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4502 - mae: 1.8148

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4431 - mae: 1.8244

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4770 - mae: 1.8189

 81/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.3316 - mae: 1.7955

 89/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.4265 - mae: 1.8165

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.3830 - mae: 1.8047

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.7080 - mae: 1.8509

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 5.6587 - mae: 1.8358

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.6448 - mae: 1.8266

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 5.5454 - mae: 1.8167

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 5.5682 - mae: 1.8295

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 5.6613 - mae: 1.8491

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.6139 - mae: 1.8474

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.5935 - mae: 1.8426

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.6512 - mae: 1.8560

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.6817 - mae: 1.8572

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.7217 - mae: 1.8615

183/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.7166 - mae: 1.8558

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.7521 - mae: 1.8643

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.6926 - mae: 1.8563

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8545 - mae: 1.8820

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8712 - mae: 1.8876

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8950 - mae: 1.8871

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8343 - mae: 1.8751

237/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8236 - mae: 1.8746

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 5.8675 - mae: 1.8786

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8559 - mae: 1.8763

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8303 - mae: 1.8763

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8424 - mae: 1.8795

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8177 - mae: 1.8795

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8608 - mae: 1.8898

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8345 - mae: 1.8857

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8460 - mae: 1.8836

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8667 - mae: 1.8859

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8439 - mae: 1.8842

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8144 - mae: 1.8777

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8593 - mae: 1.8808

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8318 - mae: 1.8764

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8289 - mae: 1.8770

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8329 - mae: 1.8799

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5.8296 - mae: 1.8798

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.8281 - mae: 1.8819

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.8757 - mae: 1.8927

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9153 - mae: 1.9008

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9058 - mae: 1.9004

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.8998 - mae: 1.9026

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9532 - mae: 1.9130

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9067 - mae: 1.9046

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8573 - mae: 1.8954

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8445 - mae: 1.8940

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8376 - mae: 1.8961

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8185 - mae: 1.8926

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.7980 - mae: 1.8906

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8108 - mae: 1.8950

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8780 - mae: 1.8998

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8718 - mae: 1.8986

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8597 - mae: 1.8951

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8656 - mae: 1.8945

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8605 - mae: 1.8943

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8549 - mae: 1.8914

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8369 - mae: 1.8882

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8285 - mae: 1.8871

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8504 - mae: 1.8890

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8480 - mae: 1.8891

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8259 - mae: 1.8855

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8243 - mae: 1.8867

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8460 - mae: 1.8879

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8419 - mae: 1.8883

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8331 - mae: 1.8880

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8285 - mae: 1.8875

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.8265 - mae: 1.8871 - val_loss: 7.3097 - val_mae: 2.1604

Epoch 34/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 1:12 139ms/step - loss: 3.0424 - mae: 1.5373

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 2.4030 - mae: 1.3151

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.6645 - mae: 2.0029

 15/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.3760 - mae: 1.9997

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.2555 - mae: 1.9943

 26/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.9308 - mae: 1.9361

 31/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.5996 - mae: 1.9013

 35/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.6114 - mae: 1.8845

 41/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.2761 - mae: 1.8337

 46/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.2671 - mae: 1.8427

 52/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.2590 - mae: 1.8359

 57/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.5835 - mae: 1.8865

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.4056 - mae: 1.8580

 69/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.5063 - mae: 1.8736

 75/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8142 - mae: 1.9045

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8064 - mae: 1.9053

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9221 - mae: 1.9247

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9443 - mae: 1.9358

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8150 - mae: 1.9162

105/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7788 - mae: 1.9206

111/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9568 - mae: 1.9202

117/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9748 - mae: 1.9218

123/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8734 - mae: 1.9123

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7716 - mae: 1.8878

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7131 - mae: 1.8807

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8114 - mae: 1.8914

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7989 - mae: 1.8915

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8537 - mae: 1.9021

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8698 - mae: 1.9122

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7981 - mae: 1.9004

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7953 - mae: 1.9053

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7499 - mae: 1.8994

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7284 - mae: 1.8973

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8136 - mae: 1.9065

196/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8005 - mae: 1.9065

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7646 - mae: 1.9028

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6851 - mae: 1.8866

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6458 - mae: 1.8826

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5709 - mae: 1.8691

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5534 - mae: 1.8614

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5668 - mae: 1.8680

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5932 - mae: 1.8718

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6053 - mae: 1.8732

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5758 - mae: 1.8660

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5672 - mae: 1.8680

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5637 - mae: 1.8687

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5471 - mae: 1.8676

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5131 - mae: 1.8627

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4996 - mae: 1.8604

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4700 - mae: 1.8565

283/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4457 - mae: 1.8536

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4160 - mae: 1.8480

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4239 - mae: 1.8479

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4591 - mae: 1.8473

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4515 - mae: 1.8456

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4345 - mae: 1.8431

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4025 - mae: 1.8363

314/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.4922 - mae: 1.8421

319/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.5379 - mae: 1.8469

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6429 - mae: 1.8575

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7054 - mae: 1.8695

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7064 - mae: 1.8713

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6994 - mae: 1.8716

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7629 - mae: 1.8823

358/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7603 - mae: 1.8813

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7814 - mae: 1.8862

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7507 - mae: 1.8811

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7499 - mae: 1.8827

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7582 - mae: 1.8845

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7758 - mae: 1.8858

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.8222 - mae: 1.8913

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.8214 - mae: 1.8900

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.7989 - mae: 1.8865

417/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.8186 - mae: 1.8899

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.8204 - mae: 1.8885

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.8334 - mae: 1.8929

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8266 - mae: 1.8894

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8084 - mae: 1.8869

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7986 - mae: 1.8859

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8171 - mae: 1.8908

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8125 - mae: 1.8874

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8194 - mae: 1.8893

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8217 - mae: 1.8903

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8463 - mae: 1.8948

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8696 - mae: 1.9004

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8467 - mae: 1.8969

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8730 - mae: 1.9016

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8447 - mae: 1.8957

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8519 - mae: 1.8971

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8597 - mae: 1.8971

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8436 - mae: 1.8958

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 5.8427 - mae: 1.8951 - val_loss: 8.6549 - val_mae: 2.3807

Epoch 35/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32s 63ms/step - loss: 5.4793 - mae: 1.8698

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.0322 - mae: 1.8405

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.3941 - mae: 1.9593

 17/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 7.0333 - mae: 2.0843

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.9704 - mae: 2.0612

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6446 - mae: 2.0121

 33/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6597 - mae: 2.0197

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1270 - mae: 1.9117

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9905 - mae: 1.9051

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7346 - mae: 1.8688

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6654 - mae: 1.8633

 63/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8671 - mae: 1.8961

 70/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8244 - mae: 1.8807

 76/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9540 - mae: 1.9027

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7579 - mae: 1.8777

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7294 - mae: 1.8865

 90/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7805 - mae: 1.9008

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7049 - mae: 1.8836

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6213 - mae: 1.8704

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8638 - mae: 1.8933

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8316 - mae: 1.8850

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6918 - mae: 1.8603

118/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6514 - mae: 1.8551

122/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6179 - mae: 1.8535

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6115 - mae: 1.8603

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6464 - mae: 1.8616

134/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6265 - mae: 1.8624

139/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6175 - mae: 1.8675

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6385 - mae: 1.8725

145/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6676 - mae: 1.8707

151/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7749 - mae: 1.8782

157/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.9000 - mae: 1.8987

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.8387 - mae: 1.8877

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7699 - mae: 1.8764

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7573 - mae: 1.8769

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7755 - mae: 1.8783

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7891 - mae: 1.8847

200/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7948 - mae: 1.8844

207/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7904 - mae: 1.8869

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.6880 - mae: 1.8693

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7368 - mae: 1.8783

231/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7880 - mae: 1.8866

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7655 - mae: 1.8842

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.8253 - mae: 1.8859

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.8510 - mae: 1.8872

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8125 - mae: 1.8837

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8212 - mae: 1.8845

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8687 - mae: 1.8902

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9215 - mae: 1.8901

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9374 - mae: 1.8945

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9072 - mae: 1.8871

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9297 - mae: 1.8893

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8945 - mae: 1.8848

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8501 - mae: 1.8793

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8993 - mae: 1.8844

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9292 - mae: 1.8901

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9266 - mae: 1.8910

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9636 - mae: 1.8986

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9595 - mae: 1.8952

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9064 - mae: 1.8862

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.9372 - mae: 1.8906

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9119 - mae: 1.8892

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 5.9106 - mae: 1.8889

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9074 - mae: 1.8876

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8902 - mae: 1.8848

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8771 - mae: 1.8850

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8727 - mae: 1.8849

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8666 - mae: 1.8834

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8821 - mae: 1.8882

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.8956 - mae: 1.8937

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9110 - mae: 1.8957

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9035 - mae: 1.8947

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9281 - mae: 1.8974

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9477 - mae: 1.9018

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9171 - mae: 1.8992

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.9163 - mae: 1.8986

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 5.9169 - mae: 1.8994 - val_loss: 8.2145 - val_mae: 2.3216

Epoch 35: early stopping

Restoring model weights from the end of the best epoch: 25.

In [20]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 8s 789ms/step

10/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 84ms/step

MAE:  1.8217402136786867

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [21]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Temp'].shift(1)
df.head()

         Date  Temp  Baseline
0  1981-01-01  20.7       NaN
1  1981-01-02  17.9      20.7
2  1981-01-03  18.8      17.9
3  1981-01-04  14.6      18.8
4  1981-01-05  15.8      14.6

In [22]:
# if you wanted to see how this model does, use df['Baseline'] for the pred
# here's how I'd do it
y_test_baseline = df['Baseline'].tail(y_test.shape[0])
# check your work
y_test_baseline.shape

(362,)

In [23]:
# check shapes, looks good!
y_test.shape

(362,)

In [24]:
# now set this equal to pred and repeat code!

# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = y_test_baseline # the pred
actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\583441606.py:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [25]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_45052\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

2.025414364640884

In [27]:
# our RNN models beats the baseline model!
# don't be FOOLED by the line plot... or model is 20% better than a dumb model!

# On Your Own
* Update the script to make some interesting comparisons of models - which one would you recommend to your boss?
* Can you analyze the distribution of errors instead of just MAE?
* Try even more architectures - play with number of filters, kernel size, number of layers, and see if you can beat 1.8 MAE.
* See if scalaing can help.