<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_RNN.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 6 — Univariate RNN Pt 1: the 3-D tensor and split_sequence
- Drop the window feature engineering - hand the RNN the raw sequence as a 3-D tensor and let it learn the temporal features (like the ConvNet learned image features).
- 3,650 daily temperatures, look-back 10 -> 3,640 samples of 10 x 1. split_sequence: [1,2,3] -> 4, [2,3,4] -> 5, oldest to newest.
- The reshape to add the trailing 1 is where 90% of RNN errors live - do it slowly on camera.
- Chronological 90/10: 3,276 train / 364 test.
-->

# Univariate Temperature Example (RNN)
-------------------------

**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the next day's temperature as a function of N previous days.

Each of these is an example of a many-to-one classification (using a single feature with a lookback of N). This is the among the most tasks that need to be done with time series problems.

You could also try to implement a one-to-one by simply shifting the column by -1 then re-running (this is different than the baseline model we show at the end).

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# prep data for modeling (univariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [5]:
# here's an example of how this script works
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90

In [6]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = df['Temp'] # the second column, where the data is. UPDATE THIS ON YOUR DATA!
# let's ignore the date column and just use the temperature data
X, y = split_sequence(raw_seq, n_steps)

In [7]:
# check out X and y shape
print(df.shape)
print(X.shape)

(3650, 2)
(3640, 10)

In [8]:
# take a peak at what it did
print(X[0])
print(y[0])

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

[20.7 17.9 18.8 14.6 15.8 15.8 15.8 17.4 21.8 20. ]
16.2

In [9]:
# now we reshape the data into a 3D array
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1 # this is 1 because it is univariate data
X = X.reshape((X.shape[0], X.shape[1], n_features))
X.shape

(3640, 10, 1)

In [10]:
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [11]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)

# verify that this all adds up!

(3640, 10, 1) (3276, 10, 1) (364, 10, 1)

In [12]:
# peak at it!
X_train[0]

array([[20.7],
       [17.9],
       [18.8],
       [14.6],
       [15.8],
       [15.8],
       [15.8],
       [17.4],
       [21.8],
       [20. ]])

In [13]:
y[0]

np.float64(16.2)

In [14]:
# if we wanted to, we could do some scaling/normalization here, would not hurt!

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 7 — Univariate RNN Pt 2: fit SimpleRNN, then LSTM, then beat the baselines
- Confirm the tensor (3640, 10, 1); inherit n_steps and n_features FROM THE SHAPE; 30 red dots -> 31x30+30 params, spinning 10 times.
- Linear output, MSE loss, MAE tracked, early stopping on val_loss (20% of train as validation).
- SimpleRNN MAE ~1.77 vs the window method's ~1.76 - the same. One-word swap to LSTM -> ~1.74.
- The sermon: beat MEAN-ONLY and PERSISTENCE (shift-1, ~2.02) or you've learned nothing. A shifted copy looks great on a plot - always pair metric + scatter + time-series.
-->

# RNN one layer model

In [15]:
# samples, lookback, features
# samples = original rows in df - lookback period
# 3640 = 3650 - 10
X.shape

(3640, 10, 1)

In [16]:
# store these features for modeling
n_features = X.shape[2]
n_steps = X.shape[1]

print(n_steps, n_features)

10 1

In [17]:

# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before, but this is a better way)
n_features = X.shape[2] # 1 green dot
n_steps = X.shape[1] # 10 steps (not shown in the animation - this is how many times it loops)

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), activation='relu')) # 30 red dots
model.add(Dense(1, activation='linear'))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the train data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │           960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 991 (3.87 KB)

 Trainable params: 991 (3.87 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 32:37 4s/step - loss: 222.9408 - mae: 14.5514

 15/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 157.6572 - mae: 11.7742

 28/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 132.3150 - mae: 10.6723

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 106.0385 - mae: 9.2638

 51/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 84.4637 - mae: 7.8082

 63/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 70.0455 - mae: 6.7750

 75/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 59.9688 - mae: 6.0106

 88/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51.8864 - mae: 5.3820

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 46.4761 - mae: 4.9764

112/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 42.2499 - mae: 4.6631

124/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 39.0916 - mae: 4.4463

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 36.3547 - mae: 4.2500

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 34.1238 - mae: 4.0854

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 32.0273 - mae: 3.9313

172/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 30.0092 - mae: 3.7610

185/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 28.3301 - mae: 3.6418

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 26.9590 - mae: 3.5371

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 25.7674 - mae: 3.4404

221/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 24.8385 - mae: 3.3727

233/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 23.9206 - mae: 3.3087

245/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 23.0743 - mae: 3.2407

258/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 22.2490 - mae: 3.1828

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 21.5329 - mae: 3.1285

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 20.9771 - mae: 3.0899

292/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.5155 - mae: 3.0586

303/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.9635 - mae: 3.0178

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.4229 - mae: 2.9730

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.1287 - mae: 2.9554

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.6704 - mae: 2.9261

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.3354 - mae: 2.9019

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.0022 - mae: 2.8780

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.6455 - mae: 2.8525

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.3684 - mae: 2.8359

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.0941 - mae: 2.8210

399/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.7615 - mae: 2.7909

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.4578 - mae: 2.7677

422/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16.1691 - mae: 2.7454

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.9233 - mae: 2.7278

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.6804 - mae: 2.7096

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.4657 - mae: 2.6907

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.2417 - mae: 2.6707

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.0947 - mae: 2.6650

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.9373 - mae: 2.6553

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.7656 - mae: 2.6425

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.6233 - mae: 2.6323

517/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.4844 - mae: 2.6240

524/524 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 14.3702 - mae: 2.6154 - val_loss: 5.5198 - val_mae: 1.8645

Epoch 2/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14:25 2s/step - loss: 1.1127 - mae: 0.8299

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3474 - mae: 1.9322

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2278 - mae: 2.0396

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.7575 - mae: 1.9822

 48/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6877 - mae: 1.9714

 60/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.7099 - mae: 1.9981

 72/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3410 - mae: 1.9642

 84/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5246 - mae: 2.0012

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3105 - mae: 1.9728

108/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4292 - mae: 2.0010

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3939 - mae: 1.9914

133/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3592 - mae: 1.9780

146/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2288 - mae: 1.9553

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2900 - mae: 1.9655

171/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2450 - mae: 1.9634

185/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2768 - mae: 1.9690

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2174 - mae: 1.9601

213/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2160 - mae: 1.9631

228/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3069 - mae: 1.9677

242/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3538 - mae: 1.9730

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3276 - mae: 1.9698

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2773 - mae: 1.9638

279/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2795 - mae: 1.9673

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2901 - mae: 1.9696

303/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2583 - mae: 1.9641

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2283 - mae: 1.9640

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2137 - mae: 1.9558

342/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2406 - mae: 1.9587

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2591 - mae: 1.9607

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2510 - mae: 1.9616

380/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2406 - mae: 1.9615

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2677 - mae: 1.9603

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2398 - mae: 1.9546

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2667 - mae: 1.9590

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2851 - mae: 1.9646

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3476 - mae: 1.9746

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3699 - mae: 1.9797

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3812 - mae: 1.9802

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3840 - mae: 1.9838

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3730 - mae: 1.9833

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3918 - mae: 1.9892

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4025 - mae: 1.9896

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4063 - mae: 1.9919

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4185 - mae: 1.9952

524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - loss: 6.4117 - mae: 1.9941 - val_loss: 5.7075 - val_mae: 1.8759

Epoch 3/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 30s 58ms/step - loss: 0.9505 - mae: 0.8267

 14/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.1352 - mae: 1.7625

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.7109 - mae: 2.0337

 37/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.8025 - mae: 2.0583

 48/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9030 - mae: 2.0750

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6768 - mae: 2.0374

 71/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4052 - mae: 2.0035

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2179 - mae: 1.9781

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0480 - mae: 1.9438

107/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1253 - mae: 1.9609

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1200 - mae: 1.9648

130/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1355 - mae: 1.9690

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2453 - mae: 1.9844

153/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2202 - mae: 1.9818

165/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0965 - mae: 1.9622

177/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1014 - mae: 1.9580

190/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3181 - mae: 1.9845

203/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4234 - mae: 2.0006

217/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4731 - mae: 2.0123

230/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4709 - mae: 2.0121

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5518 - mae: 2.0275

255/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6008 - mae: 2.0388

268/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5315 - mae: 2.0277

282/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6367 - mae: 2.0427

296/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6588 - mae: 2.0463

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6011 - mae: 2.0344

323/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6028 - mae: 2.0338

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5871 - mae: 2.0312

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6002 - mae: 2.0339

363/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6097 - mae: 2.0316

376/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6048 - mae: 2.0325

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5625 - mae: 2.0233

403/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5297 - mae: 2.0192

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5138 - mae: 2.0191

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4998 - mae: 2.0136

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5054 - mae: 2.0124

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5134 - mae: 2.0146

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4875 - mae: 2.0129

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4793 - mae: 2.0115

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4800 - mae: 2.0121

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5011 - mae: 2.0152

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4965 - mae: 2.0172

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4504 - mae: 2.0067

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.4309 - mae: 2.0036 - val_loss: 5.4166 - val_mae: 1.8450

Epoch 4/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - loss: 2.8927 - mae: 1.3104

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4934 - mae: 1.8870

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3419 - mae: 1.9219

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9058 - mae: 2.0200

 47/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.7979 - mae: 2.0222

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.6130 - mae: 1.9925

 71/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.1971 - mae: 1.9367

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2336 - mae: 1.9438

 94/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2596 - mae: 1.9353

105/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3207 - mae: 1.9348

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3274 - mae: 1.9352

128/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1472 - mae: 1.9054

139/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1642 - mae: 1.9125

151/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1025 - mae: 1.9081

164/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1888 - mae: 1.9289

176/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1208 - mae: 1.9191

188/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3088 - mae: 1.9566

200/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3342 - mae: 1.9590

212/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3529 - mae: 1.9546

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4198 - mae: 1.9628

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3146 - mae: 1.9447

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2787 - mae: 1.9375

262/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3146 - mae: 1.9485

276/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2842 - mae: 1.9404

288/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3992 - mae: 1.9659

300/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3565 - mae: 1.9609

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3171 - mae: 1.9576

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4034 - mae: 1.9714

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3903 - mae: 1.9675

354/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3590 - mae: 1.9645

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3822 - mae: 1.9706

382/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3157 - mae: 1.9597

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2615 - mae: 1.9535

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2736 - mae: 1.9580

420/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3041 - mae: 1.9623

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2824 - mae: 1.9606

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2900 - mae: 1.9626

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2962 - mae: 1.9630

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3260 - mae: 1.9703

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3014 - mae: 1.9651

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2771 - mae: 1.9609

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2580 - mae: 1.9568

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3049 - mae: 1.9683

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2767 - mae: 1.9615 - val_loss: 5.6943 - val_mae: 1.8766

Epoch 5/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 39s 75ms/step - loss: 12.9450 - mae: 3.4184

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3695 - mae: 2.0031

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9494 - mae: 2.0688

 35/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4657 - mae: 2.0015

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0296 - mae: 2.0487

 56/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5396 - mae: 1.9734

 66/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5792 - mae: 1.9901

 75/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4124 - mae: 1.9736

 86/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3411 - mae: 1.9691

 98/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.7395 - mae: 2.0224

110/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4801 - mae: 1.9775

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2651 - mae: 1.9468

133/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2255 - mae: 1.9363

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4231 - mae: 1.9815

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4300 - mae: 1.9826

163/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4344 - mae: 1.9782

175/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2251 - mae: 1.9399

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2531 - mae: 1.9365

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1930 - mae: 1.9300

211/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3043 - mae: 1.9440

223/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4360 - mae: 1.9642

234/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4665 - mae: 1.9716

245/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3823 - mae: 1.9642

257/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3163 - mae: 1.9517

269/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2906 - mae: 1.9475

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3000 - mae: 1.9524

293/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3300 - mae: 1.9580

303/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3339 - mae: 1.9583

315/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3182 - mae: 1.9581

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2861 - mae: 1.9529

342/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3199 - mae: 1.9637

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4415 - mae: 1.9797

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4497 - mae: 1.9836

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4079 - mae: 1.9760

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4148 - mae: 1.9782

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3913 - mae: 1.9770

421/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3526 - mae: 1.9726

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4040 - mae: 1.9779

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3603 - mae: 1.9724

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3624 - mae: 1.9733

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3615 - mae: 1.9714

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3316 - mae: 1.9674

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3481 - mae: 1.9689

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3656 - mae: 1.9721

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3466 - mae: 1.9712

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.3448 - mae: 1.9712 - val_loss: 5.4570 - val_mae: 1.8464

Epoch 6/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - loss: 6.6649 - mae: 2.4943

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5674 - mae: 1.9361

 21/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8895 - mae: 1.8920

 32/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0661 - mae: 1.8683

 43/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0917 - mae: 1.9114

 54/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9238 - mae: 1.8947

 65/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.6344 - mae: 2.0173

 76/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2078 - mae: 1.9415

 87/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9826 - mae: 1.8963

 98/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8847 - mae: 1.8792

107/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0664 - mae: 1.9115

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2589 - mae: 1.9459

126/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2282 - mae: 1.9455

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2901 - mae: 1.9526

145/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2239 - mae: 1.9456

156/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3310 - mae: 1.9631

168/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3344 - mae: 1.9721

180/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2861 - mae: 1.9608

191/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3542 - mae: 1.9687

202/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3708 - mae: 1.9710

214/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4059 - mae: 1.9765

226/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5014 - mae: 1.9983

238/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4088 - mae: 1.9853

249/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2868 - mae: 1.9638

261/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2498 - mae: 1.9562

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2245 - mae: 1.9501

286/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1817 - mae: 1.9418

297/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1622 - mae: 1.9394

309/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1508 - mae: 1.9362

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2338 - mae: 1.9452

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2331 - mae: 1.9489

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2727 - mae: 1.9539

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2666 - mae: 1.9551

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3071 - mae: 1.9649

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3204 - mae: 1.9677

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2858 - mae: 1.9635

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3062 - mae: 1.9689

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3043 - mae: 1.9688

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2826 - mae: 1.9660

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3322 - mae: 1.9711

454/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3216 - mae: 1.9701

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3214 - mae: 1.9701

478/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2724 - mae: 1.9627

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3064 - mae: 1.9653

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2927 - mae: 1.9600

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3394 - mae: 1.9703

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.3218 - mae: 1.9687 - val_loss: 5.4344 - val_mae: 1.8476

Epoch 7/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 3.6565 - mae: 1.6510

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0544 - mae: 1.9406

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2404 - mae: 1.9527

 37/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2853 - mae: 1.9493

 49/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3904 - mae: 1.9903

 60/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3333 - mae: 2.0043

 70/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4139 - mae: 2.0195

 81/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4687 - mae: 2.0248

 92/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3815 - mae: 2.0212

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2309 - mae: 1.9962

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1786 - mae: 1.9746

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0972 - mae: 1.9515

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2638 - mae: 1.9726

146/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2261 - mae: 1.9665

158/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2925 - mae: 1.9696

168/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4946 - mae: 1.9976

179/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4107 - mae: 1.9833

188/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3338 - mae: 1.9670

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3720 - mae: 1.9727

211/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3450 - mae: 1.9692

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2438 - mae: 1.9528

234/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3635 - mae: 1.9710

245/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3311 - mae: 1.9685

256/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3518 - mae: 1.9713

267/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3424 - mae: 1.9707

279/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2574 - mae: 1.9575

290/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3515 - mae: 1.9704

302/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3418 - mae: 1.9685

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3627 - mae: 1.9707

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3564 - mae: 1.9711

337/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3732 - mae: 1.9755

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3223 - mae: 1.9684

360/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2597 - mae: 1.9606

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2674 - mae: 1.9598

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2365 - mae: 1.9575

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3348 - mae: 1.9687

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3296 - mae: 1.9676

419/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3237 - mae: 1.9661

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2993 - mae: 1.9614

443/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3262 - mae: 1.9672

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3039 - mae: 1.9617

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2547 - mae: 1.9519

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3089 - mae: 1.9602

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3277 - mae: 1.9601

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3078 - mae: 1.9612

517/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3100 - mae: 1.9657

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.3069 - mae: 1.9649 - val_loss: 5.4074 - val_mae: 1.8390

Epoch 8/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 37s 71ms/step - loss: 11.5335 - mae: 2.9663

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9511 - mae: 1.8691

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2376 - mae: 1.9495

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6352 - mae: 2.0302

 46/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5381 - mae: 2.0212

 57/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3244 - mae: 1.9811

 68/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4552 - mae: 1.9962

 78/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4870 - mae: 2.0069

 89/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4946 - mae: 2.0039

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6455 - mae: 2.0346

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7069 - mae: 2.0530

126/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6797 - mae: 2.0548

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6146 - mae: 2.0464

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5508 - mae: 2.0444

158/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6103 - mae: 2.0504

168/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4711 - mae: 2.0216

177/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3201 - mae: 1.9896

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2771 - mae: 1.9840

198/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2525 - mae: 1.9818

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2036 - mae: 1.9727

220/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3347 - mae: 1.9857

230/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4097 - mae: 1.9980

241/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3669 - mae: 1.9916

253/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3450 - mae: 1.9905

265/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3585 - mae: 1.9884

276/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3751 - mae: 1.9937

287/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4103 - mae: 2.0018

299/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4555 - mae: 2.0119

310/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4842 - mae: 2.0127

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4305 - mae: 2.0051

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4625 - mae: 2.0143

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4752 - mae: 2.0207

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4529 - mae: 2.0154

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4215 - mae: 2.0089

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4511 - mae: 2.0164

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5193 - mae: 2.0224

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4282 - mae: 2.0036

419/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4517 - mae: 2.0080

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4115 - mae: 2.0007

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3843 - mae: 1.9944

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3896 - mae: 1.9929

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3977 - mae: 1.9924

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3581 - mae: 1.9864

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3289 - mae: 1.9786

500/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2922 - mae: 1.9717

511/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3092 - mae: 1.9722

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2926 - mae: 1.9666

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2926 - mae: 1.9666 - val_loss: 5.5168 - val_mae: 1.8614

Epoch 9/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 23s 45ms/step - loss: 7.6794 - mae: 2.6049

 17/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0344 - mae: 2.1764

 31/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8002 - mae: 2.1440

 44/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7070 - mae: 2.1208

 56/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6989 - mae: 2.1211

 68/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6491 - mae: 2.1145

 80/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5858 - mae: 2.0688

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6266 - mae: 2.0859

105/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4998 - mae: 2.0548

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4019 - mae: 2.0322

126/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2424 - mae: 2.0041

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1550 - mae: 1.9846

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0663 - mae: 1.9638

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9853 - mae: 1.9491

170/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0038 - mae: 1.9366

182/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0907 - mae: 1.9585

194/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0426 - mae: 1.9511

204/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0498 - mae: 1.9506

213/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0325 - mae: 1.9523

225/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9979 - mae: 1.9464

235/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0984 - mae: 1.9586

245/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1491 - mae: 1.9708

256/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1967 - mae: 1.9790

268/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1795 - mae: 1.9757

280/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1559 - mae: 1.9726

291/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1136 - mae: 1.9608

302/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1893 - mae: 1.9758

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1710 - mae: 1.9755

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1598 - mae: 1.9661

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1110 - mae: 1.9588

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1362 - mae: 1.9617

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0941 - mae: 1.9532

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2011 - mae: 1.9665

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1783 - mae: 1.9637

398/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1707 - mae: 1.9623

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1842 - mae: 1.9658

422/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2476 - mae: 1.9698

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2580 - mae: 1.9703

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3656 - mae: 1.9837

459/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3789 - mae: 1.9849

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3446 - mae: 1.9765

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3062 - mae: 1.9691

495/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3103 - mae: 1.9693

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3222 - mae: 1.9726

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3274 - mae: 1.9718

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.3031 - mae: 1.9668 - val_loss: 5.4786 - val_mae: 1.8517

Epoch 10/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 23s 45ms/step - loss: 4.6790 - mae: 1.8003

 17/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.7356 - mae: 1.8577

 32/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2380 - mae: 1.9069

 46/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3599 - mae: 1.9093

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0938 - mae: 1.9052

 75/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0322 - mae: 1.9097

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3227 - mae: 1.9435

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3152 - mae: 1.9345

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3307 - mae: 1.9371

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4337 - mae: 1.9474

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4780 - mae: 1.9596

149/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6800 - mae: 1.9949

158/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7598 - mae: 2.0146

169/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8649 - mae: 2.0231

181/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8531 - mae: 2.0247

193/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7252 - mae: 2.0067

204/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6477 - mae: 1.9942

215/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5367 - mae: 1.9774

225/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5582 - mae: 1.9797

234/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4792 - mae: 1.9707

244/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4991 - mae: 1.9773

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4530 - mae: 1.9691

264/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4241 - mae: 1.9663

274/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4050 - mae: 1.9663

284/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3067 - mae: 1.9506

295/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2792 - mae: 1.9493

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2493 - mae: 1.9465

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2940 - mae: 1.9554

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2751 - mae: 1.9554

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2711 - mae: 1.9570

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2660 - mae: 1.9551

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2226 - mae: 1.9481

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2041 - mae: 1.9393

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2603 - mae: 1.9490

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2334 - mae: 1.9463

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2997 - mae: 1.9592

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3066 - mae: 1.9618

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3009 - mae: 1.9614

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3443 - mae: 1.9654

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3006 - mae: 1.9573

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2797 - mae: 1.9569

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2829 - mae: 1.9557

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3096 - mae: 1.9583

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2934 - mae: 1.9581

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2773 - mae: 1.9533

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2862 - mae: 1.9533 - val_loss: 5.5521 - val_mae: 1.8707

Epoch 11/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 38s 74ms/step - loss: 10.5071 - mae: 2.8429

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.0661 - mae: 2.1029

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6281 - mae: 2.0034

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1048 - mae: 1.9276

 52/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4341 - mae: 1.9675

 64/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5505 - mae: 1.9939

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3943 - mae: 1.9768

 91/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5254 - mae: 2.0207

105/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3484 - mae: 1.9945

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6178 - mae: 2.0223

130/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7118 - mae: 2.0326

142/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5595 - mae: 2.0098

154/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4880 - mae: 1.9932

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3938 - mae: 1.9820

178/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4768 - mae: 1.9969

191/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3916 - mae: 1.9906

203/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4024 - mae: 1.9933

214/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2806 - mae: 1.9731

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3420 - mae: 1.9837

233/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2912 - mae: 1.9717

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3484 - mae: 1.9791

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3553 - mae: 1.9776

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4073 - mae: 1.9909

277/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3526 - mae: 1.9834

287/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3386 - mae: 1.9797

298/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4277 - mae: 1.9896

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4159 - mae: 1.9844

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4963 - mae: 1.9941

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5218 - mae: 1.9955

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5172 - mae: 1.9918

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4741 - mae: 1.9890

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4860 - mae: 1.9949

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4563 - mae: 1.9923

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3826 - mae: 1.9807

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3916 - mae: 1.9792

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3249 - mae: 1.9664

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3156 - mae: 1.9671

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3048 - mae: 1.9660

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2970 - mae: 1.9639

459/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3762 - mae: 1.9763

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3049 - mae: 1.9635

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2975 - mae: 1.9643

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2740 - mae: 1.9618

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3117 - mae: 1.9643

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3092 - mae: 1.9635

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.3111 - mae: 1.9645 - val_loss: 5.5080 - val_mae: 1.8609

Epoch 12/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - loss: 2.5495 - mae: 1.3689

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3413 - mae: 2.1811

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1778 - mae: 2.1196

 33/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9787 - mae: 2.0857

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1603 - mae: 2.1194

 57/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0637 - mae: 2.1147

 69/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.8893 - mae: 2.0898

 80/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9490 - mae: 2.1027

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9288 - mae: 2.0994

104/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6728 - mae: 2.0514

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6049 - mae: 2.0385

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3247 - mae: 1.9858

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2616 - mae: 1.9729

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2699 - mae: 1.9662

161/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1853 - mae: 1.9564

174/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3317 - mae: 1.9655

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3409 - mae: 1.9617

201/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3044 - mae: 1.9561

214/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2819 - mae: 1.9533

226/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3540 - mae: 1.9609

239/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3709 - mae: 1.9688

251/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3386 - mae: 1.9652

262/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2744 - mae: 1.9538

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3068 - mae: 1.9542

285/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3085 - mae: 1.9561

297/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3913 - mae: 1.9714

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3630 - mae: 1.9653

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3851 - mae: 1.9733

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3807 - mae: 1.9728

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4108 - mae: 1.9787

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3841 - mae: 1.9732

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4046 - mae: 1.9793

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3913 - mae: 1.9772

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3939 - mae: 1.9774

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3812 - mae: 1.9750

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4105 - mae: 1.9803

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4102 - mae: 1.9823

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3448 - mae: 1.9732

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3665 - mae: 1.9793

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3264 - mae: 1.9739

478/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2603 - mae: 1.9622

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2656 - mae: 1.9618

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2819 - mae: 1.9671

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2658 - mae: 1.9618

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2459 - mae: 1.9581 - val_loss: 5.4629 - val_mae: 1.8446

Epoch 13/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 21:24 2s/step - loss: 11.5763 - mae: 3.3166

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9609 - mae: 2.1431

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3258 - mae: 2.2022

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2370 - mae: 1.9608

 46/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5753 - mae: 2.0354

 56/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2122 - mae: 1.9580

 66/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0946 - mae: 1.9288

 76/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0712 - mae: 1.9184

 87/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0923 - mae: 1.9297

 96/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3487 - mae: 1.9724

107/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3566 - mae: 1.9778

118/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2913 - mae: 1.9605

130/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2841 - mae: 1.9742

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0939 - mae: 1.9395

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0210 - mae: 1.9265

164/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9466 - mae: 1.9186

175/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0541 - mae: 1.9247

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0990 - mae: 1.9363

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0890 - mae: 1.9325

208/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0886 - mae: 1.9326

219/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0583 - mae: 1.9293

231/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0256 - mae: 1.9260

242/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1021 - mae: 1.9390

253/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0266 - mae: 1.9266

265/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0823 - mae: 1.9371

276/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0376 - mae: 1.9350

288/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0660 - mae: 1.9375

298/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0660 - mae: 1.9335

311/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0987 - mae: 1.9352

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1710 - mae: 1.9491

337/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1221 - mae: 1.9405

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1756 - mae: 1.9469

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2015 - mae: 1.9460

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2148 - mae: 1.9482

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2205 - mae: 1.9487

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2412 - mae: 1.9483

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2131 - mae: 1.9471

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2922 - mae: 1.9598

437/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2431 - mae: 1.9520

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2056 - mae: 1.9426

462/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1747 - mae: 1.9359

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1220 - mae: 1.9280

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1669 - mae: 1.9339

500/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1550 - mae: 1.9315

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1770 - mae: 1.9347

524/524 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - loss: 6.2159 - mae: 1.9374 - val_loss: 5.5952 - val_mae: 1.8758

Epoch 14/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 37s 72ms/step - loss: 8.0936 - mae: 2.3458

 11/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4728 - mae: 1.9025

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7437 - mae: 2.1499

 33/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0786 - mae: 2.0867

 43/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5568 - mae: 2.1530

 52/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7981 - mae: 2.2018

 63/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7003 - mae: 2.1876

 73/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9645 - mae: 2.2002

 83/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5394 - mae: 2.1427

 94/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3573 - mae: 2.1055

104/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2129 - mae: 2.0819

115/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0455 - mae: 2.0553

126/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9159 - mae: 2.0383

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8357 - mae: 2.0336

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8916 - mae: 2.0357

157/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.0690 - mae: 2.0579

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9515 - mae: 2.0451

176/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9872 - mae: 2.0534

184/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9230 - mae: 2.0435

194/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8315 - mae: 2.0317

205/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9199 - mae: 2.0437

214/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8622 - mae: 2.0376

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8149 - mae: 2.0291

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7634 - mae: 2.0233

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8385 - mae: 2.0354

259/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7619 - mae: 2.0258

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6875 - mae: 2.0180

282/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6996 - mae: 2.0211

293/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6197 - mae: 2.0049

304/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5651 - mae: 1.9960

315/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5339 - mae: 1.9948

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4903 - mae: 1.9883

337/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4298 - mae: 1.9807

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4786 - mae: 1.9885

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5168 - mae: 1.9940

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5156 - mae: 1.9903

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4768 - mae: 1.9854

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4752 - mae: 1.9864

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4469 - mae: 1.9826

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4348 - mae: 1.9824

414/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3712 - mae: 1.9728

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3788 - mae: 1.9735

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3747 - mae: 1.9712

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3938 - mae: 1.9742

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3865 - mae: 1.9728

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4099 - mae: 1.9729

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4260 - mae: 1.9762

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4016 - mae: 1.9734

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3922 - mae: 1.9722

493/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3569 - mae: 1.9653

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3130 - mae: 1.9601

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2914 - mae: 1.9556

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2741 - mae: 1.9541

524/524 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 6.2809 - mae: 1.9553 - val_loss: 5.5917 - val_mae: 1.8749

Epoch 15/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 35s 69ms/step - loss: 1.7230 - mae: 1.0676

 11/524 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.3679 - mae: 1.9924

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.2759 - mae: 1.8383

 32/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9112 - mae: 1.9413

 43/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4442 - mae: 1.8550

 53/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3194 - mae: 1.8170

 64/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4.9493 - mae: 1.7517

 75/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3194 - mae: 1.7925

 85/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3884 - mae: 1.8036

 95/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4790 - mae: 1.8246

103/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3576 - mae: 1.8070

112/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8136 - mae: 1.8715

123/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7954 - mae: 1.8612

134/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7470 - mae: 1.8639

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8357 - mae: 1.8817

154/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9076 - mae: 1.8920

165/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0879 - mae: 1.9277

176/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1832 - mae: 1.9341

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2236 - mae: 1.9439

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2342 - mae: 1.9493

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1811 - mae: 1.9383

221/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3411 - mae: 1.9522

232/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3633 - mae: 1.9592

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3670 - mae: 1.9642

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3781 - mae: 1.9619

264/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4018 - mae: 1.9732

275/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3087 - mae: 1.9561

286/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2895 - mae: 1.9551

296/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2629 - mae: 1.9511

307/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3245 - mae: 1.9640

318/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3084 - mae: 1.9640

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3960 - mae: 1.9738

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3946 - mae: 1.9722

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3550 - mae: 1.9657

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3219 - mae: 1.9623

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3137 - mae: 1.9571

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2311 - mae: 1.9446

403/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2816 - mae: 1.9523

414/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3157 - mae: 1.9591

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2904 - mae: 1.9566

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3255 - mae: 1.9605

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2939 - mae: 1.9587

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2971 - mae: 1.9592

482/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2635 - mae: 1.9552

495/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2439 - mae: 1.9522

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2236 - mae: 1.9494

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2197 - mae: 1.9506

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2085 - mae: 1.9504 - val_loss: 5.6068 - val_mae: 1.8687

Epoch 16/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 2.5240 - mae: 1.3824

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5699 - mae: 2.2307

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.1974 - mae: 1.9581

 34/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2205 - mae: 1.9315

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2080 - mae: 1.9424

 56/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9343 - mae: 1.8946

 67/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9034 - mae: 1.8722

 77/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8191 - mae: 1.8608

 87/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0249 - mae: 1.8945

 96/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0810 - mae: 1.9192

106/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9941 - mae: 1.9102

116/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2213 - mae: 1.9517

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1297 - mae: 1.9352

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0844 - mae: 1.9371

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1654 - mae: 1.9504

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9533 - mae: 1.9078

171/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9401 - mae: 1.9059

182/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0416 - mae: 1.9184

193/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9750 - mae: 1.9128

204/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0062 - mae: 1.9199

216/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9261 - mae: 1.9064

227/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9252 - mae: 1.9053

238/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9432 - mae: 1.9107

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8855 - mae: 1.8971

259/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8752 - mae: 1.8937

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8701 - mae: 1.8899

282/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8153 - mae: 1.8817

293/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8114 - mae: 1.8783

305/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8833 - mae: 1.8868

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9226 - mae: 1.8922

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9147 - mae: 1.8879

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9866 - mae: 1.9026

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0173 - mae: 1.9066

361/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9726 - mae: 1.8979

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0379 - mae: 1.9076

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0680 - mae: 1.9129

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1304 - mae: 1.9264

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1330 - mae: 1.9275

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1295 - mae: 1.9297

432/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1459 - mae: 1.9315

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2066 - mae: 1.9422

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2149 - mae: 1.9430

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2341 - mae: 1.9441

487/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1957 - mae: 1.9401

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2318 - mae: 1.9440

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2301 - mae: 1.9481

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2525 - mae: 1.9521 - val_loss: 5.7364 - val_mae: 1.8833

Epoch 17/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 7.1472 - mae: 2.0321

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4509 - mae: 1.7973

 23/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7090 - mae: 1.8653

 35/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9452 - mae: 1.9144

 46/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8485 - mae: 1.8636

 57/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9269 - mae: 1.8738

 67/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9072 - mae: 1.8898

 77/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9253 - mae: 1.8918

 85/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8925 - mae: 1.8870

 94/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9821 - mae: 1.9096

105/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8793 - mae: 1.8883

117/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0265 - mae: 1.9096

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0940 - mae: 1.9209

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0675 - mae: 1.9216

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1665 - mae: 1.9398

162/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3366 - mae: 1.9582

174/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3041 - mae: 1.9576

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2552 - mae: 1.9532

193/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3539 - mae: 1.9648

203/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3968 - mae: 1.9774

214/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3718 - mae: 1.9756

225/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4048 - mae: 1.9861

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3273 - mae: 1.9685

247/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2134 - mae: 1.9545

258/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2620 - mae: 1.9616

269/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2846 - mae: 1.9649

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3240 - mae: 1.9670

292/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3654 - mae: 1.9719

304/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3448 - mae: 1.9645

316/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2683 - mae: 1.9517

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2225 - mae: 1.9439

339/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2224 - mae: 1.9464

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1893 - mae: 1.9414

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1802 - mae: 1.9355

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2549 - mae: 1.9466

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2419 - mae: 1.9479

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2954 - mae: 1.9537

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3178 - mae: 1.9580

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2967 - mae: 1.9517

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3344 - mae: 1.9560

437/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3081 - mae: 1.9540

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2636 - mae: 1.9505

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2135 - mae: 1.9436

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2202 - mae: 1.9448

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2380 - mae: 1.9458

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2158 - mae: 1.9436

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2032 - mae: 1.9436

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2204 - mae: 1.9478 - val_loss: 5.4448 - val_mae: 1.8478

Epoch 17: early stopping

Restoring model weights from the end of the best epoch: 7.

In [18]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 6s 567ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step

MAE:  1.7645190508811028

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## On your own: add the learning curve and the train results!

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [19]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = X.shape[2] # 1 green dot = 1 feature
n_steps = X.shape[1] # these are time steps = there are 10!

# define model
model = Sequential()
model.add(LSTM(30, input_shape=(n_steps,n_features), activation='relu')) # 30 red dots = hidden size of 30
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         3,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,871 (15.12 KB)

 Trainable params: 3,871 (15.12 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 34:22 4s/step - loss: 204.2565 - mae: 13.5498

 11/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 175.4892 - mae: 12.6835

 21/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 156.9352 - mae: 11.8866

 33/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 139.5640 - mae: 11.0762

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 113.5162 - mae: 9.6601

 57/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 93.5841 - mae: 8.3279

 68/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 80.8714 - mae: 7.4868

 80/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 70.3133 - mae: 6.7653

 91/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 63.2007 - mae: 6.2354

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 57.5142 - mae: 5.8540

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 52.8256 - mae: 5.5095

124/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49.0776 - mae: 5.2416

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 45.2515 - mae: 4.9465

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 42.5063 - mae: 4.7455

160/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 39.7300 - mae: 4.5386

173/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 37.2838 - mae: 4.3509

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 35.1127 - mae: 4.1879

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 33.3044 - mae: 4.0603

211/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 31.8177 - mae: 3.9488

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 30.2770 - mae: 3.8258

238/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 28.8786 - mae: 3.7192

252/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 27.6914 - mae: 3.6312

265/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 26.7293 - mae: 3.5674

280/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 25.6113 - mae: 3.4757

295/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24.6517 - mae: 3.4009

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.9377 - mae: 3.3492

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.2560 - mae: 3.2991

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 22.4940 - mae: 3.2473

353/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.8441 - mae: 3.2004

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.2738 - mae: 3.1681

385/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.7509 - mae: 3.1290

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.2187 - mae: 3.0919

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.7188 - mae: 3.0522

432/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 19.2888 - mae: 3.0216

448/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.9014 - mae: 2.9907

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.4381 - mae: 2.9524

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.0190 - mae: 2.9159

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.5994 - mae: 2.8796

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.2710 - mae: 2.8557

524/524 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - loss: 17.1213 - mae: 2.8462 - val_loss: 5.4524 - val_mae: 1.8432

Epoch 2/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 34s 67ms/step - loss: 6.7859 - mae: 2.2464

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5793 - mae: 2.4479

 23/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5241 - mae: 2.1521

 34/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4026 - mae: 2.1140

 44/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9518 - mae: 2.0795

 55/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5889 - mae: 2.0132

 65/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9042 - mae: 2.0587

 75/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4892 - mae: 1.9767

 85/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4038 - mae: 1.9633

 96/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2720 - mae: 1.9463

106/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4750 - mae: 1.9715

116/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5369 - mae: 1.9802

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5343 - mae: 1.9758

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4448 - mae: 1.9649

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4333 - mae: 1.9681

158/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4549 - mae: 1.9700

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3890 - mae: 1.9540

175/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3786 - mae: 1.9535

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4002 - mae: 1.9566

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4505 - mae: 1.9637

208/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4379 - mae: 1.9666

218/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4820 - mae: 1.9730

230/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3775 - mae: 1.9575

241/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4193 - mae: 1.9674

252/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4029 - mae: 1.9675

262/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4569 - mae: 1.9816

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4549 - mae: 1.9817

284/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3928 - mae: 1.9699

295/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3852 - mae: 1.9745

305/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4264 - mae: 1.9842

315/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3425 - mae: 1.9696

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3628 - mae: 1.9738

337/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3804 - mae: 1.9756

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4188 - mae: 1.9833

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3930 - mae: 1.9784

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3849 - mae: 1.9801

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3597 - mae: 1.9730

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4067 - mae: 1.9868

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3899 - mae: 1.9835

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3991 - mae: 1.9864

422/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3669 - mae: 1.9821

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3867 - mae: 1.9810

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3342 - mae: 1.9724

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3332 - mae: 1.9711

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3537 - mae: 1.9741

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3108 - mae: 1.9681

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3447 - mae: 1.9686

493/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3562 - mae: 1.9721

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4193 - mae: 1.9776

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4444 - mae: 1.9843

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4108 - mae: 1.9813

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.4047 - mae: 1.9807 - val_loss: 5.9817 - val_mae: 1.9473

Epoch 3/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 35s 68ms/step - loss: 15.1411 - mae: 2.9930

 11/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5665 - mae: 1.8355

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.6616 - mae: 2.0332

 32/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5902 - mae: 2.1793

 43/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5071 - mae: 2.1921

 53/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9831 - mae: 2.0967

 63/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3066 - mae: 2.1383

 74/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5232 - mae: 2.1501

 85/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6117 - mae: 2.1621

 93/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4781 - mae: 2.1383

103/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3719 - mae: 2.1292

113/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0918 - mae: 2.0912

124/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0868 - mae: 2.0936

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.1357 - mae: 2.1007

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.0118 - mae: 2.0765

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.0356 - mae: 2.0808

171/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9204 - mae: 2.0586

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8509 - mae: 2.0491

195/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8819 - mae: 2.0538

207/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.9550 - mae: 2.0619

218/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8885 - mae: 2.0555

228/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7726 - mae: 2.0377

239/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7667 - mae: 2.0380

250/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.8386 - mae: 2.0557

260/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7324 - mae: 2.0410

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.7488 - mae: 2.0488

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6944 - mae: 2.0368

291/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6608 - mae: 2.0362

302/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6512 - mae: 2.0323

314/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.6389 - mae: 2.0315

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.6635 - mae: 2.0313

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.6377 - mae: 2.0248

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5848 - mae: 2.0171

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5545 - mae: 2.0143

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5100 - mae: 2.0095

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5149 - mae: 2.0095

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4576 - mae: 2.0028

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4793 - mae: 2.0056

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4383 - mae: 1.9986

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3747 - mae: 1.9864

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3898 - mae: 1.9890

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3947 - mae: 1.9917

456/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4046 - mae: 1.9950

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3934 - mae: 1.9936

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3699 - mae: 1.9893

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3498 - mae: 1.9839

495/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3776 - mae: 1.9859

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3732 - mae: 1.9855

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3955 - mae: 1.9896

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.3783 - mae: 1.9865 - val_loss: 5.6325 - val_mae: 1.8699

Epoch 4/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - loss: 3.9721 - mae: 1.6540

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.8048 - mae: 1.8189

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.4493 - mae: 1.8110

 38/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.5851 - mae: 2.0001

 50/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4872 - mae: 1.9700

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2035 - mae: 1.9178

 71/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2700 - mae: 1.9210

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3388 - mae: 1.9203

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5339 - mae: 1.9453

107/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4132 - mae: 1.9493

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5013 - mae: 1.9712

131/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4793 - mae: 1.9719

143/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6872 - mae: 2.0123

155/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6126 - mae: 1.9964

167/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5827 - mae: 1.9883

178/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5468 - mae: 1.9873

189/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3881 - mae: 1.9561

200/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4414 - mae: 1.9637

212/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5556 - mae: 1.9777

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5033 - mae: 1.9773

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5981 - mae: 1.9938

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6037 - mae: 1.9920

260/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5852 - mae: 1.9903

272/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5578 - mae: 1.9919

284/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5895 - mae: 2.0021

296/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6127 - mae: 2.0095

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6009 - mae: 2.0090

318/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5784 - mae: 2.0021

331/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5690 - mae: 2.0032

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6631 - mae: 2.0139

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6519 - mae: 2.0133

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6318 - mae: 2.0121

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6101 - mae: 2.0076

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6078 - mae: 2.0080

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6109 - mae: 2.0052

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5933 - mae: 2.0018

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5908 - mae: 2.0030

436/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.6096 - mae: 2.0087

448/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5414 - mae: 1.9973

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5190 - mae: 1.9945

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5301 - mae: 1.9999

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5271 - mae: 1.9994

495/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4870 - mae: 1.9926

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4317 - mae: 1.9817

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4192 - mae: 1.9778

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.4226 - mae: 1.9811 - val_loss: 5.4076 - val_mae: 1.8432

Epoch 5/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - loss: 1.8775 - mae: 1.2243

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4521 - mae: 1.9944

 23/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4992 - mae: 2.0028

 33/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3232 - mae: 1.9615

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.6420 - mae: 1.8707

 53/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9258 - mae: 1.9038

 66/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.1593 - mae: 1.9463

 79/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0540 - mae: 1.9318

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0585 - mae: 1.9286

106/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0850 - mae: 1.9237

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0581 - mae: 1.9182

128/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9681 - mae: 1.9007

139/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2447 - mae: 1.9434

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3383 - mae: 1.9608

162/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3350 - mae: 1.9585

174/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3431 - mae: 1.9590

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3102 - mae: 1.9551

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2958 - mae: 1.9606

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3095 - mae: 1.9639

220/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2992 - mae: 1.9585

232/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3214 - mae: 1.9650

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3512 - mae: 1.9733

255/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3155 - mae: 1.9625

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3192 - mae: 1.9647

277/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4242 - mae: 1.9813

288/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3767 - mae: 1.9729

300/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4119 - mae: 1.9778

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4617 - mae: 1.9820

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4269 - mae: 1.9784

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4614 - mae: 1.9843

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5317 - mae: 1.9978

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5301 - mae: 1.9979

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.5123 - mae: 1.9959

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4552 - mae: 1.9881

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.4059 - mae: 1.9783

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3916 - mae: 1.9755

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3745 - mae: 1.9704

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3497 - mae: 1.9646

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3112 - mae: 1.9628

454/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3121 - mae: 1.9629

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3292 - mae: 1.9676

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3270 - mae: 1.9704

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3666 - mae: 1.9754

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3426 - mae: 1.9685

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2893 - mae: 1.9584

517/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2967 - mae: 1.9609

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2662 - mae: 1.9557 - val_loss: 5.4479 - val_mae: 1.8503

Epoch 6/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 32s 62ms/step - loss: 2.1932 - mae: 1.3194

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4.6779 - mae: 1.6930

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.0828 - mae: 1.7388

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3266 - mae: 1.7841

 50/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9491 - mae: 1.9191

 63/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2335 - mae: 1.9841

 75/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1217 - mae: 1.9502

 87/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1531 - mae: 1.9483

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1022 - mae: 1.9516

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0666 - mae: 1.9403

126/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9512 - mae: 1.9249

140/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0903 - mae: 1.9466

155/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1026 - mae: 1.9468

170/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1121 - mae: 1.9462

184/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0406 - mae: 1.9256

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9579 - mae: 1.9083

218/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1103 - mae: 1.9382

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2687 - mae: 1.9633

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2587 - mae: 1.9702

273/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2278 - mae: 1.9607

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2393 - mae: 1.9613

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1816 - mae: 1.9532

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1420 - mae: 1.9460

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1725 - mae: 1.9458

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2973 - mae: 1.9610

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2347 - mae: 1.9506

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2175 - mae: 1.9480

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1942 - mae: 1.9450

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2247 - mae: 1.9545

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2814 - mae: 1.9652

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2761 - mae: 1.9612

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2771 - mae: 1.9606

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2476 - mae: 1.9547

515/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2609 - mae: 1.9581

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2832 - mae: 1.9629 - val_loss: 5.3490 - val_mae: 1.8325

Epoch 7/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - loss: 3.8986 - mae: 1.6625

 17/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.8728 - mae: 1.8931

 33/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.7800 - mae: 1.9045

 49/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4675 - mae: 2.0252

 65/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2882 - mae: 1.9741

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5569 - mae: 2.0432

 97/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8370 - mae: 2.0626

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7730 - mae: 2.0325

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6372 - mae: 2.0144

142/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7060 - mae: 2.0166

156/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8102 - mae: 2.0171

170/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6648 - mae: 1.9991

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6146 - mae: 1.9890

196/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5268 - mae: 1.9771

208/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5689 - mae: 1.9884

220/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5296 - mae: 1.9846

231/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6151 - mae: 1.9969

244/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5627 - mae: 1.9952

256/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4653 - mae: 1.9813

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3628 - mae: 1.9614

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3222 - mae: 1.9544

290/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3187 - mae: 1.9528

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3670 - mae: 1.9587

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4217 - mae: 1.9675

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3776 - mae: 1.9636

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3914 - mae: 1.9632

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3553 - mae: 1.9600

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4032 - mae: 1.9703

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4189 - mae: 1.9713

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3746 - mae: 1.9633

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3527 - mae: 1.9586

399/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3387 - mae: 1.9547

409/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3581 - mae: 1.9571

419/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3681 - mae: 1.9527

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3173 - mae: 1.9431

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2799 - mae: 1.9390

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2637 - mae: 1.9371

462/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3025 - mae: 1.9431

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3102 - mae: 1.9489

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2754 - mae: 1.9467

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2886 - mae: 1.9473

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2951 - mae: 1.9517

515/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2815 - mae: 1.9511

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2663 - mae: 1.9498 - val_loss: 5.4194 - val_mae: 1.8457

Epoch 8/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 31s 61ms/step - loss: 9.2248 - mae: 2.4164

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1863 - mae: 2.1479

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9492 - mae: 2.0636

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9580 - mae: 2.0943

 47/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5586 - mae: 2.0036

 58/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2920 - mae: 1.9709

 70/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3433 - mae: 1.9917

 85/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4746 - mae: 2.0066

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4068 - mae: 1.9885

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5015 - mae: 2.0023

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5278 - mae: 2.0094

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6447 - mae: 2.0330

156/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5692 - mae: 2.0177

170/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5203 - mae: 2.0173

184/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5904 - mae: 2.0263

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4131 - mae: 1.9917

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3175 - mae: 1.9768

221/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2966 - mae: 1.9691

231/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3909 - mae: 1.9786

242/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2871 - mae: 1.9626

254/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2337 - mae: 1.9543

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2929 - mae: 1.9546

278/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2661 - mae: 1.9525

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3162 - mae: 1.9600

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2254 - mae: 1.9420

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2104 - mae: 1.9395

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1179 - mae: 1.9216

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1246 - mae: 1.9243

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1708 - mae: 1.9351

360/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1866 - mae: 1.9440

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1668 - mae: 1.9445

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1640 - mae: 1.9462

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1718 - mae: 1.9500

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2173 - mae: 1.9536

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2211 - mae: 1.9554

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1904 - mae: 1.9527

439/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1679 - mae: 1.9475

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1503 - mae: 1.9466

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1809 - mae: 1.9499

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1684 - mae: 1.9495

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2051 - mae: 1.9541

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2086 - mae: 1.9536

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2335 - mae: 1.9586

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1975 - mae: 1.9530

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.2323 - mae: 1.9538 - val_loss: 5.5207 - val_mae: 1.8518

Epoch 9/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 40s 77ms/step - loss: 3.3361 - mae: 1.4316

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0045 - mae: 1.9420

 22/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8333 - mae: 1.8759

 33/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.3378 - mae: 1.9152

 45/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7656 - mae: 1.8470

 56/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4990 - mae: 1.8276

 67/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7321 - mae: 1.8731

 78/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5001 - mae: 1.8281

 90/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.6001 - mae: 1.8508

100/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7211 - mae: 1.8756

111/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8054 - mae: 1.8981

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8536 - mae: 1.9029

134/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.7157 - mae: 1.8806

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8393 - mae: 1.9030

160/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9213 - mae: 1.9111

173/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0340 - mae: 1.9278

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1623 - mae: 1.9431

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1420 - mae: 1.9428

210/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1443 - mae: 1.9442

223/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1321 - mae: 1.9409

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0810 - mae: 1.9288

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1183 - mae: 1.9337

259/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1369 - mae: 1.9350

271/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2726 - mae: 1.9496

283/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2357 - mae: 1.9471

295/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2081 - mae: 1.9411

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2542 - mae: 1.9442

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3188 - mae: 1.9569

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3353 - mae: 1.9633

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3531 - mae: 1.9630

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4146 - mae: 1.9744

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4233 - mae: 1.9763

382/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3674 - mae: 1.9712

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3235 - mae: 1.9666

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2831 - mae: 1.9618

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2850 - mae: 1.9632

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2595 - mae: 1.9613

438/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2483 - mae: 1.9625

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2794 - mae: 1.9643

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2608 - mae: 1.9600

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2979 - mae: 1.9644

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2825 - mae: 1.9619

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2566 - mae: 1.9562

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3217 - mae: 1.9670

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2975 - mae: 1.9629

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3089 - mae: 1.9631

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2791 - mae: 1.9577 - val_loss: 5.4108 - val_mae: 1.8376

Epoch 10/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 31s 60ms/step - loss: 16.6704 - mae: 3.6337

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 10.4831 - mae: 2.5591

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.2252 - mae: 2.2690

 35/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8251 - mae: 2.2094

 46/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2181 - mae: 2.1000

 58/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.6886 - mae: 2.0345

 69/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.6699 - mae: 2.0104

 80/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.7466 - mae: 2.0250

 91/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4306 - mae: 1.9624

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3868 - mae: 1.9499

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4615 - mae: 1.9660

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4361 - mae: 1.9683

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4274 - mae: 1.9665

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2815 - mae: 1.9446

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1538 - mae: 1.9206

180/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0926 - mae: 1.9174

194/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0248 - mae: 1.9149

208/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0354 - mae: 1.9098

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0868 - mae: 1.9260

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0267 - mae: 1.9183

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9645 - mae: 1.9084

261/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0203 - mae: 1.9176

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0447 - mae: 1.9221

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9856 - mae: 1.9152

298/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9466 - mae: 1.9052

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9419 - mae: 1.9071

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9476 - mae: 1.9050

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9564 - mae: 1.9061

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9962 - mae: 1.9124

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0622 - mae: 1.9225

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0196 - mae: 1.9164

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0352 - mae: 1.9188

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0298 - mae: 1.9177

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0491 - mae: 1.9237

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0749 - mae: 1.9299

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0889 - mae: 1.9342

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2611 - mae: 1.9570

443/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2710 - mae: 1.9575

454/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2085 - mae: 1.9477

462/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1913 - mae: 1.9443

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1571 - mae: 1.9421

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1671 - mae: 1.9422

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2208 - mae: 1.9502

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2004 - mae: 1.9461

515/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2091 - mae: 1.9481

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2096 - mae: 1.9472 - val_loss: 6.7854 - val_mae: 2.0850

Epoch 11/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 2.1397 - mae: 1.3189

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4.9415 - mae: 1.7390

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.5176 - mae: 1.8292

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.7645 - mae: 1.8486

 47/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.8319 - mae: 1.8856

 57/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9719 - mae: 1.9541

 68/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.0138 - mae: 1.9305

 79/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9759 - mae: 1.9294

 90/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9484 - mae: 1.9165

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8610 - mae: 1.8895

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.6866 - mae: 1.8522

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8853 - mae: 1.8842

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.6836 - mae: 1.8525

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.6763 - mae: 1.8522

158/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.7577 - mae: 1.8678

170/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.7522 - mae: 1.8630

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.7363 - mae: 1.8642

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9014 - mae: 1.8908

211/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9201 - mae: 1.8966

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7877 - mae: 1.8806

237/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9314 - mae: 1.8907

251/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8848 - mae: 1.8835

265/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8500 - mae: 1.8836

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7908 - mae: 1.8777

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9083 - mae: 1.8939

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0292 - mae: 1.9124

319/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9890 - mae: 1.9044

331/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0690 - mae: 1.9188

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0844 - mae: 1.9205

354/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1339 - mae: 1.9266

364/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1035 - mae: 1.9243

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1526 - mae: 1.9278

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1112 - mae: 1.9213

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1238 - mae: 1.9273

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1094 - mae: 1.9252

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0951 - mae: 1.9259

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1575 - mae: 1.9347

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1599 - mae: 1.9345

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1902 - mae: 1.9400

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2244 - mae: 1.9471

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2173 - mae: 1.9473

482/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2248 - mae: 1.9497

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2092 - mae: 1.9463

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2332 - mae: 1.9482

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2448 - mae: 1.9501

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2371 - mae: 1.9523

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2371 - mae: 1.9523 - val_loss: 5.6216 - val_mae: 1.8814

Epoch 12/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17:41 2s/step - loss: 7.7688 - mae: 2.2993

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3557 - mae: 2.1489

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7352 - mae: 2.2276

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1960 - mae: 2.1497

 48/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.8133 - mae: 2.1108

 60/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.8659 - mae: 2.1242

 72/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4759 - mae: 2.0525

 84/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0946 - mae: 1.9741

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2846 - mae: 1.9905

108/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3488 - mae: 2.0080

120/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1198 - mae: 1.9765

131/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1611 - mae: 1.9881

143/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0391 - mae: 1.9657

155/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1609 - mae: 1.9747

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2009 - mae: 1.9749

176/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1994 - mae: 1.9736

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1747 - mae: 1.9742

199/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1543 - mae: 1.9760

210/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0451 - mae: 1.9584

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0086 - mae: 1.9524

235/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0942 - mae: 1.9561

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1052 - mae: 1.9587

258/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2223 - mae: 1.9736

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1865 - mae: 1.9659

282/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1850 - mae: 1.9650

294/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1812 - mae: 1.9678

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1585 - mae: 1.9653

318/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1975 - mae: 1.9694

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1736 - mae: 1.9630

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1144 - mae: 1.9508

351/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0996 - mae: 1.9480

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1035 - mae: 1.9440

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1579 - mae: 1.9521

385/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1661 - mae: 1.9548

398/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1653 - mae: 1.9587

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1882 - mae: 1.9635

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1926 - mae: 1.9633

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1609 - mae: 1.9545

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1503 - mae: 1.9544

456/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1107 - mae: 1.9446

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0856 - mae: 1.9407

478/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0595 - mae: 1.9350

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1107 - mae: 1.9438

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1286 - mae: 1.9474

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2143 - mae: 1.9574

524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6.2302 - mae: 1.9578 - val_loss: 5.4008 - val_mae: 1.8434

Epoch 13/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 38s 73ms/step - loss: 13.1023 - mae: 3.0240

 12/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2386 - mae: 2.3084

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8061 - mae: 2.1757

 37/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.5636 - mae: 2.0306

 49/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9454 - mae: 1.9146

 61/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9338 - mae: 1.9137

 72/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1621 - mae: 1.9556

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8156 - mae: 1.8993

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7800 - mae: 1.8938

106/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.7938 - mae: 1.8974

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9737 - mae: 1.9183

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0684 - mae: 1.9344

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1769 - mae: 1.9579

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0837 - mae: 1.9482

160/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9500 - mae: 1.9238

172/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1079 - mae: 1.9324

184/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9978 - mae: 1.9138

196/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0084 - mae: 1.9128

208/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1724 - mae: 1.9346

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1287 - mae: 1.9268

231/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1617 - mae: 1.9301

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1969 - mae: 1.9399

256/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2616 - mae: 1.9538

268/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2536 - mae: 1.9595

279/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3000 - mae: 1.9669

289/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2936 - mae: 1.9682

301/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2501 - mae: 1.9622

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2399 - mae: 1.9612

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2373 - mae: 1.9603

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1754 - mae: 1.9508

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1954 - mae: 1.9497

357/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2687 - mae: 1.9635

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2629 - mae: 1.9619

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2104 - mae: 1.9498

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1833 - mae: 1.9438

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2297 - mae: 1.9510

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2474 - mae: 1.9525

422/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3130 - mae: 1.9610

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3117 - mae: 1.9609

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3439 - mae: 1.9647

457/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3301 - mae: 1.9637

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3566 - mae: 1.9695

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3251 - mae: 1.9636

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3267 - mae: 1.9591

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2959 - mae: 1.9524

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.3308 - mae: 1.9595

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.2586 - mae: 1.9451 - val_loss: 5.2763 - val_mae: 1.8188

Epoch 14/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 2.0145 - mae: 1.0806

 14/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3869 - mae: 1.9397

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6856 - mae: 2.0244

 38/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1028 - mae: 1.9240

 49/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.6771 - mae: 2.0003

 60/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.5153 - mae: 1.9852

 72/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3772 - mae: 1.9775

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0804 - mae: 1.9307

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9555 - mae: 1.9217

106/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6677 - mae: 1.8765

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7808 - mae: 1.8980

130/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8023 - mae: 1.8852

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9160 - mae: 1.9063

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9626 - mae: 1.9273

163/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1574 - mae: 1.9572

173/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2292 - mae: 1.9695

185/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1830 - mae: 1.9588

196/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0543 - mae: 1.9385

206/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1181 - mae: 1.9505

217/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1861 - mae: 1.9591

228/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2053 - mae: 1.9545

239/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1837 - mae: 1.9489

250/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1787 - mae: 1.9510

263/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1954 - mae: 1.9485

275/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2935 - mae: 1.9668

287/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2291 - mae: 1.9535

299/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1688 - mae: 1.9472

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2912 - mae: 1.9641

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2084 - mae: 1.9521

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1978 - mae: 1.9522

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1574 - mae: 1.9454

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1844 - mae: 1.9491

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1561 - mae: 1.9448

380/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1709 - mae: 1.9437

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0972 - mae: 1.9319

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0986 - mae: 1.9344

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1190 - mae: 1.9404

420/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1599 - mae: 1.9439

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1522 - mae: 1.9429

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1735 - mae: 1.9468

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1600 - mae: 1.9424

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1475 - mae: 1.9393

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1582 - mae: 1.9390

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1786 - mae: 1.9396

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1907 - mae: 1.9412

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1711 - mae: 1.9360

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1638 - mae: 1.9362

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1451 - mae: 1.9347

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.1454 - mae: 1.9348 - val_loss: 5.2986 - val_mae: 1.8239

Epoch 15/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 33s 64ms/step - loss: 6.0437 - mae: 1.7731

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.1673 - mae: 1.8534

 24/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 4.2624 - mae: 1.6696

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.3699 - mae: 1.8541

 49/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.7206 - mae: 1.8689

 61/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.6205 - mae: 1.8571

 72/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.7245 - mae: 1.8778

 82/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.9609 - mae: 1.8895

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1420 - mae: 1.9317

105/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1914 - mae: 1.9443

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0948 - mae: 1.9247

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9953 - mae: 1.9131

140/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0842 - mae: 1.9452

151/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1844 - mae: 1.9600

163/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2897 - mae: 1.9754

175/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2417 - mae: 1.9677

184/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1373 - mae: 1.9438

195/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2127 - mae: 1.9540

205/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1505 - mae: 1.9373

216/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1203 - mae: 1.9274

227/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0755 - mae: 1.9167

237/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9758 - mae: 1.8978

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9644 - mae: 1.8977

260/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9773 - mae: 1.8992

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9465 - mae: 1.8903

286/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9544 - mae: 1.8886

299/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.9738 - mae: 1.8968

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0009 - mae: 1.9033

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0606 - mae: 1.9121

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0575 - mae: 1.9127

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0212 - mae: 1.9053

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0611 - mae: 1.9117

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1133 - mae: 1.9195

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1873 - mae: 1.9300

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1268 - mae: 1.9219

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1490 - mae: 1.9260

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1478 - mae: 1.9245

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1244 - mae: 1.9190

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1045 - mae: 1.9167

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0688 - mae: 1.9130

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0667 - mae: 1.9146

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1414 - mae: 1.9260

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1434 - mae: 1.9258

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1381 - mae: 1.9265

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1212 - mae: 1.9211

517/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1797 - mae: 1.9303

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.1429 - mae: 1.9244 - val_loss: 5.2411 - val_mae: 1.8153

Epoch 16/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - loss: 1.5199 - mae: 1.0594

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.7067 - mae: 1.7477

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.1745 - mae: 1.8325

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.6047 - mae: 1.8675

 48/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.4712 - mae: 2.0334

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3563 - mae: 1.9991

 70/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2522 - mae: 1.9783

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2004 - mae: 1.9767

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2081 - mae: 1.9562

104/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1643 - mae: 1.9418

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.0604 - mae: 1.9186

128/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1473 - mae: 1.9207

139/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1730 - mae: 1.9216

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2575 - mae: 1.9307

164/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1970 - mae: 1.9364

175/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3509 - mae: 1.9493

185/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4266 - mae: 1.9605

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3911 - mae: 1.9557

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3791 - mae: 1.9530

220/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3315 - mae: 1.9446

231/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2791 - mae: 1.9371

243/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4419 - mae: 1.9556

255/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3615 - mae: 1.9494

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3156 - mae: 1.9426

277/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2488 - mae: 1.9359

288/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1403 - mae: 1.9225

300/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1082 - mae: 1.9189

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1276 - mae: 1.9242

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1659 - mae: 1.9341

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1079 - mae: 1.9234

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1069 - mae: 1.9288

357/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1834 - mae: 1.9390

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1990 - mae: 1.9424

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1901 - mae: 1.9420

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1830 - mae: 1.9412

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2420 - mae: 1.9513

414/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2331 - mae: 1.9501

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2689 - mae: 1.9557

438/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2494 - mae: 1.9541

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2038 - mae: 1.9456

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2126 - mae: 1.9483

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2149 - mae: 1.9497

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2044 - mae: 1.9504

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1987 - mae: 1.9506

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2040 - mae: 1.9509

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1870 - mae: 1.9473

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.1521 - mae: 1.9408 - val_loss: 5.3353 - val_mae: 1.8251

Epoch 17/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 29s 56ms/step - loss: 5.7252 - mae: 1.7997

 14/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0065 - mae: 1.9007

 27/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.6344 - mae: 1.9182

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8673 - mae: 1.9310

 54/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.3956 - mae: 1.8383

 69/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6359 - mae: 1.8593

 85/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6253 - mae: 1.8749

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.5787 - mae: 1.8731

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6454 - mae: 1.8985

133/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6280 - mae: 1.8811

149/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1713 - mae: 1.9435

165/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9461 - mae: 1.9060

180/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9056 - mae: 1.8892

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9781 - mae: 1.8963

215/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9493 - mae: 1.8839

229/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9757 - mae: 1.8879

244/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0234 - mae: 1.8917

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0500 - mae: 1.8985

277/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0638 - mae: 1.9012

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9857 - mae: 1.8895

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9576 - mae: 1.8869

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9942 - mae: 1.8976

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9738 - mae: 1.8934

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0074 - mae: 1.8961

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9989 - mae: 1.8972

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0691 - mae: 1.9141

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0868 - mae: 1.9154

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1701 - mae: 1.9269

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1724 - mae: 1.9293

457/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1565 - mae: 1.9287

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1444 - mae: 1.9284

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1630 - mae: 1.9301

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1263 - mae: 1.9254

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1262 - mae: 1.9243

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1262 - mae: 1.9243 - val_loss: 5.2870 - val_mae: 1.8217

Epoch 18/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 12.1248 - mae: 2.9882

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6367 - mae: 2.0480

 37/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.7641 - mae: 1.8646

 49/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0645 - mae: 1.9073

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2797 - mae: 1.9372

 74/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2382 - mae: 1.9488

 86/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1534 - mae: 1.9342

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1970 - mae: 1.9400

110/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1240 - mae: 1.9278

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3890 - mae: 1.9599

132/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3662 - mae: 1.9596

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4310 - mae: 1.9755

156/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3498 - mae: 1.9649

168/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3789 - mae: 1.9585

179/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4540 - mae: 1.9794

190/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3635 - mae: 1.9685

201/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3331 - mae: 1.9697

212/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4287 - mae: 1.9750

223/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4315 - mae: 1.9771

234/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3557 - mae: 1.9681

245/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3767 - mae: 1.9746

256/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3233 - mae: 1.9597

267/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3447 - mae: 1.9637

278/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3701 - mae: 1.9703

290/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3198 - mae: 1.9638

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2900 - mae: 1.9563

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2778 - mae: 1.9565

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3701 - mae: 1.9721

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2983 - mae: 1.9595

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2693 - mae: 1.9532

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2760 - mae: 1.9551

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2707 - mae: 1.9584

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2604 - mae: 1.9532

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2379 - mae: 1.9499

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2019 - mae: 1.9446

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1582 - mae: 1.9336

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1558 - mae: 1.9344

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1858 - mae: 1.9399

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1758 - mae: 1.9393

457/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1466 - mae: 1.9345

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1142 - mae: 1.9293

480/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1158 - mae: 1.9282

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1348 - mae: 1.9340

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1160 - mae: 1.9319

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0897 - mae: 1.9277

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.0868 - mae: 1.9269 - val_loss: 5.3172 - val_mae: 1.8312

Epoch 19/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 7.8568 - mae: 2.6163

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.2846 - mae: 1.5409

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1997 - mae: 1.9164

 38/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1512 - mae: 1.9587

 50/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5493 - mae: 2.0022

 63/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3854 - mae: 1.9724

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3471 - mae: 1.9819

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2627 - mae: 1.9621

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1053 - mae: 1.9250

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9852 - mae: 1.9081

124/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8339 - mae: 1.8822

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9590 - mae: 1.9117

146/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0543 - mae: 1.9172

157/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9579 - mae: 1.8994

169/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8521 - mae: 1.8824

180/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7455 - mae: 1.8594

191/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7106 - mae: 1.8584

203/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.6893 - mae: 1.8578

215/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7456 - mae: 1.8696

226/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7542 - mae: 1.8725

237/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8347 - mae: 1.8865

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9504 - mae: 1.9024

260/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9468 - mae: 1.9007

270/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8970 - mae: 1.8932

281/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9611 - mae: 1.9012

293/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9617 - mae: 1.9037

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9610 - mae: 1.9033

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9228 - mae: 1.8943

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9435 - mae: 1.8996

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0023 - mae: 1.9099

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0344 - mae: 1.9092

363/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0087 - mae: 1.9071

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0895 - mae: 1.9191

385/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0867 - mae: 1.9192

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1249 - mae: 1.9223

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0962 - mae: 1.9181

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0940 - mae: 1.9178

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1482 - mae: 1.9276

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1554 - mae: 1.9242

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1231 - mae: 1.9212

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1006 - mae: 1.9169

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1157 - mae: 1.9215

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1109 - mae: 1.9234

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0907 - mae: 1.9179

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0816 - mae: 1.9172

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1315 - mae: 1.9263

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.1192 - mae: 1.9256 - val_loss: 5.2530 - val_mae: 1.8171

Epoch 20/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 19:49 2s/step - loss: 2.9207 - mae: 1.3991

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6407 - mae: 2.0739

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1964 - mae: 1.9441

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1145 - mae: 1.9428

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9324 - mae: 1.9189

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3787 - mae: 1.9752

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3941 - mae: 1.9640

139/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2389 - mae: 1.9355

153/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2470 - mae: 1.9274

167/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1693 - mae: 1.9123

180/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1938 - mae: 1.9202

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2167 - mae: 1.9255

205/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1532 - mae: 1.9186

218/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1246 - mae: 1.9125

230/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1657 - mae: 1.9244

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2186 - mae: 1.9283

253/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1767 - mae: 1.9213

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2344 - mae: 1.9294

277/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2279 - mae: 1.9269

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2612 - mae: 1.9338

300/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2546 - mae: 1.9360

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3049 - mae: 1.9448

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3457 - mae: 1.9475

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3077 - mae: 1.9435

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2997 - mae: 1.9421

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3597 - mae: 1.9507

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3130 - mae: 1.9459

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3097 - mae: 1.9467

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3556 - mae: 1.9506

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3557 - mae: 1.9511

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2815 - mae: 1.9391

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3006 - mae: 1.9422

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2914 - mae: 1.9402

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1944 - mae: 1.9224

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1971 - mae: 1.9247

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1804 - mae: 1.9248

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1807 - mae: 1.9253

498/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1419 - mae: 1.9207

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1135 - mae: 1.9169

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1081 - mae: 1.9162

524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6.1216 - mae: 1.9188 - val_loss: 5.6635 - val_mae: 1.8927

Epoch 21/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 22:34 3s/step - loss: 6.3320 - mae: 1.8400

 15/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9745 - mae: 1.9459

 28/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2801 - mae: 1.9807

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3213 - mae: 1.9842

 52/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3482 - mae: 1.9882

 64/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2856 - mae: 1.9409

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2831 - mae: 1.9527

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1594 - mae: 1.9284

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1417 - mae: 1.9457

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1038 - mae: 1.9474

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9966 - mae: 1.9274

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0064 - mae: 1.9370

155/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9872 - mae: 1.9290

169/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9672 - mae: 1.9359

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8863 - mae: 1.9174

196/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9195 - mae: 1.9190

209/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9383 - mae: 1.9212

222/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9037 - mae: 1.9121

237/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8209 - mae: 1.8944

252/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8619 - mae: 1.8997

264/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9838 - mae: 1.9208

277/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9740 - mae: 1.9161

290/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9350 - mae: 1.9092

303/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8405 - mae: 1.8919

316/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8281 - mae: 1.8891

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8862 - mae: 1.8921

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.8926 - mae: 1.8964

353/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9282 - mae: 1.9034

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9375 - mae: 1.9033

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9468 - mae: 1.9065

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9261 - mae: 1.8984

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9077 - mae: 1.8982

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9688 - mae: 1.9112

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9872 - mae: 1.9144

437/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9961 - mae: 1.9122

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0628 - mae: 1.9205

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1189 - mae: 1.9293

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1406 - mae: 1.9321

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1460 - mae: 1.9341

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1714 - mae: 1.9354

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1604 - mae: 1.9336

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1346 - mae: 1.9309

524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6.1080 - mae: 1.9253 - val_loss: 5.2753 - val_mae: 1.8157

Epoch 22/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 32s 62ms/step - loss: 2.2122 - mae: 1.3455

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3662 - mae: 2.0105

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3755 - mae: 1.9965

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2021 - mae: 1.9552

 47/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.3907 - mae: 2.0040

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.2824 - mae: 1.9849

 71/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0214 - mae: 1.9563

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9783 - mae: 1.9479

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8352 - mae: 1.9190

107/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8696 - mae: 1.9266

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0157 - mae: 1.9389

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1649 - mae: 1.9632

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2826 - mae: 1.9838

154/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3317 - mae: 1.9828

169/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2186 - mae: 1.9594

183/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1858 - mae: 1.9518

197/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0621 - mae: 1.9262

210/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2364 - mae: 1.9582

224/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2497 - mae: 1.9640

238/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2766 - mae: 1.9648

252/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2255 - mae: 1.9587

266/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2626 - mae: 1.9651

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3335 - mae: 1.9728

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2597 - mae: 1.9582

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2936 - mae: 1.9646

316/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2428 - mae: 1.9589

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2120 - mae: 1.9482

339/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1980 - mae: 1.9462

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1704 - mae: 1.9397

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1890 - mae: 1.9410

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1864 - mae: 1.9383

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1411 - mae: 1.9341

403/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1837 - mae: 1.9424

415/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1010 - mae: 1.9277

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1202 - mae: 1.9318

439/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1141 - mae: 1.9294

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0914 - mae: 1.9221

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0751 - mae: 1.9215

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0820 - mae: 1.9195

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1017 - mae: 1.9220

500/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0786 - mae: 1.9188

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0797 - mae: 1.9179

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0661 - mae: 1.9170

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.0661 - mae: 1.9170 - val_loss: 5.3436 - val_mae: 1.8276

Epoch 23/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - loss: 7.3926 - mae: 2.0588

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.3854 - mae: 1.8825

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.8836 - mae: 1.8960

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.5920 - mae: 1.8483

 47/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5597 - mae: 1.8058

 58/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.1820 - mae: 1.7460

 69/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.4333 - mae: 1.7975

 80/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.7249 - mae: 1.8422

 91/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8072 - mae: 1.8687

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 5.8361 - mae: 1.8800

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1341 - mae: 1.9260

126/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1211 - mae: 1.9229

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3297 - mae: 1.9536

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1473 - mae: 1.9323

163/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1108 - mae: 1.9165

177/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1070 - mae: 1.9239

190/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0719 - mae: 1.9254

203/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1285 - mae: 1.9317

216/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0812 - mae: 1.9202

228/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1421 - mae: 1.9220

241/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2797 - mae: 1.9447

255/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1927 - mae: 1.9300

269/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1966 - mae: 1.9299

280/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1934 - mae: 1.9349

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1451 - mae: 1.9302

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1006 - mae: 1.9268

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0707 - mae: 1.9246

323/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9994 - mae: 1.9118

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0585 - mae: 1.9265

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1027 - mae: 1.9299

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1288 - mae: 1.9325

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1219 - mae: 1.9288

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0842 - mae: 1.9239

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1234 - mae: 1.9267

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1522 - mae: 1.9318

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1169 - mae: 1.9232

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1514 - mae: 1.9311

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0999 - mae: 1.9215

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0736 - mae: 1.9176

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0697 - mae: 1.9184

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0980 - mae: 1.9224

476/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0635 - mae: 1.9171

487/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0665 - mae: 1.9138

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0315 - mae: 1.9097

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0590 - mae: 1.9149

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0405 - mae: 1.9132

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 6.0369 - mae: 1.9128 - val_loss: 5.2873 - val_mae: 1.8259

Epoch 24/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 19:26 2s/step - loss: 2.0558 - mae: 1.1758

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5451 - mae: 1.8765

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.5405 - mae: 1.8376

 36/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.8412 - mae: 1.9018

 48/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.6575 - mae: 1.8738

 59/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2615 - mae: 1.9566

 71/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4773 - mae: 1.9878

 82/524 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.2086 - mae: 1.9562

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3055 - mae: 1.9699

103/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2715 - mae: 1.9647

112/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3446 - mae: 1.9773

124/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5588 - mae: 2.0070

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.4825 - mae: 1.9799

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.5733 - mae: 2.0028

160/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3687 - mae: 1.9690

171/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3555 - mae: 1.9718

182/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3754 - mae: 1.9756

193/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3788 - mae: 1.9791

204/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3205 - mae: 1.9745

215/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3572 - mae: 1.9866

225/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2771 - mae: 1.9818

236/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2675 - mae: 1.9886

247/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3368 - mae: 1.9973

258/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.3071 - mae: 1.9909

269/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.2254 - mae: 1.9736

280/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1565 - mae: 1.9576

290/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1259 - mae: 1.9474

301/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1312 - mae: 1.9489

312/524 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 6.1250 - mae: 1.9513

323/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1065 - mae: 1.9470

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1450 - mae: 1.9486

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.1491 - mae: 1.9498

354/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0809 - mae: 1.9377

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0824 - mae: 1.9361

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0345 - mae: 1.9232

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0542 - mae: 1.9243

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0085 - mae: 1.9161

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9808 - mae: 1.9095

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9679 - mae: 1.9052

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0214 - mae: 1.9087

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9639 - mae: 1.8977

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9812 - mae: 1.8985

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9821 - mae: 1.8975

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9606 - mae: 1.8959

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.9799 - mae: 1.8996

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0326 - mae: 1.9058

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0805 - mae: 1.9150

524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 6.0805 - mae: 1.9150 - val_loss: 5.3378 - val_mae: 1.8264

Epoch 25/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18:56 2s/step - loss: 8.8246 - mae: 2.4163

 14/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.8171 - mae: 1.8405

 26/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.4604 - mae: 1.7797

 38/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.9700 - mae: 1.6966

 50/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4.8450 - mae: 1.6800

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.1633 - mae: 1.7138

 74/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.4361 - mae: 1.7743

 85/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9447 - mae: 1.8397

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.7938 - mae: 1.8173

107/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9140 - mae: 1.8443

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0557 - mae: 1.8739

131/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1343 - mae: 1.8973

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1929 - mae: 1.9069

157/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3630 - mae: 1.9447

169/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1906 - mae: 1.9216

181/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1050 - mae: 1.9083

193/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1138 - mae: 1.9084

206/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1967 - mae: 1.9249

219/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1880 - mae: 1.9279

230/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1655 - mae: 1.9253

241/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1962 - mae: 1.9294

252/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1167 - mae: 1.9167

264/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.1416 - mae: 1.9224

273/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0371 - mae: 1.9027

286/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5.9598 - mae: 1.8916

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9715 - mae: 1.8890

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9825 - mae: 1.8921

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0065 - mae: 1.8974

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0279 - mae: 1.8992

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0396 - mae: 1.9028

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9997 - mae: 1.8987

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0284 - mae: 1.9085

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0924 - mae: 1.9172

397/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0346 - mae: 1.9118

409/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0941 - mae: 1.9175

422/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0979 - mae: 1.9181

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1323 - mae: 1.9239

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1121 - mae: 1.9217

459/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1342 - mae: 1.9235

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1404 - mae: 1.9264

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0823 - mae: 1.9146

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0959 - mae: 1.9186

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0428 - mae: 1.9099

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0452 - mae: 1.9109

524/524 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 6.0406 - mae: 1.9104 - val_loss: 5.3083 - val_mae: 1.8324

Epoch 25: early stopping

Restoring model weights from the end of the best epoch: 15.

In [20]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 3s 296ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step

MAE:  1.7349952689893955

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [21]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Temp'].shift(1)
df.head()

         Date  Temp  Baseline
0  1981-01-01  20.7       NaN
1  1981-01-02  17.9      20.7
2  1981-01-03  18.8      17.9
3  1981-01-04  14.6      18.8
4  1981-01-05  15.8      14.6

In [22]:
# if you wanted to see how this model does, use df['Baseline'] for the pred
# here's how I'd do it
y_test_baseline = df['Baseline'].tail(y_test.shape[0])
# check your work
y_test_baseline.shape

(364,)

In [23]:
# check shapes, looks good!
y_test.shape

(364,)

In [24]:
# now set this equal to pred and repeat code!



# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = y_test_baseline # the pred
actual = y_test # the actual

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))


plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

MAE:  2.0247252747252746

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\2020546298.py:21: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [25]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_26296\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

2.0247252747252746

In [27]:
# our RNN models beats the baseline model!
# don't be FOOLED by the line plot... or model is 20% better than a dumb model!