<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_RNN_Advanced.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 14 — ConvLSTM on the temperature and occupancy series
- Data prep is UNCHANGED - just add convolution + pooling in front of the recurrent layer (the 'ConvLSTM' of the 2010s).
- Univariate: look-back 30, kernel 3, 32 filters -> 30 x 1 becomes 28 x 32.
- Then hop to Multivariate_Occupancy_RNN_AdvancedTopics: look-back 50, 5 features -> 48 x 32, pooled to 24 x 32, into a SimpleRNN.
- The secret sauce is shapes: input_shape, return_sequences when stacking, and knowing every output shape and param count.
-->

# Univariate Temperature Example (Advanced)
**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the temperature as a function of N previous days - building on our previous script, and adding some 1D convolutions, 1D maxpooling, and dropout. Just make sure your sequences are long enough to do meaningful convolutions!

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# prep data for modeling (univariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [5]:
# here's an example of how this script works
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90

In [6]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 30 # long enough to do convolutions!
raw_seq = df['Temp'] # the second column, where the data is. UPDATE THIS ON YOUR DATA!
# let's ignore the date column and just use the temperature data
X, y = split_sequence(raw_seq, n_steps)

In [7]:
# take a peak at what it did
print(X[0])
print(y[0])

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

[20.7 17.9 18.8 14.6 15.8 15.8 15.8 17.4 21.8 20.  16.2 13.3 16.7 21.5
 25.  20.7 20.6 24.8 17.7 15.5 18.2 12.1 14.4 16.  16.5 18.7 19.4 17.2
 15.5 15.1]
15.4

In [8]:
# now we reshape the data into a 3D array
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1 # this is 1 because it is univariate data
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [9]:
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [10]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)

# verify that this all adds up!
# samples, length, variables

(3620, 30, 1) (3258, 30, 1) (362, 30, 1)

In [11]:
# peak at it!
X_train[0]

array([[20.7],
       [17.9],
       [18.8],
       [14.6],
       [15.8],
       [15.8],
       [15.8],
       [17.4],
       [21.8],
       [20. ],
       [16.2],
       [13.3],
       [16.7],
       [21.5],
       [25. ],
       [20.7],
       [20.6],
       [24.8],
       [17.7],
       [15.5],
       [18.2],
       [12.1],
       [14.4],
       [16. ],
       [16.5],
       [18.7],
       [19.4],
       [17.2],
       [15.5],
       [15.1]])

In [12]:
# if we wanted to, we could do some scaling/normalization here, would not hurt!

# RNN one layer model (with Conv and Pooling)

In [13]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_steps = 30
n_features = 1

# for Conv1D, you can play with the filters and kernel size

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(SimpleRNN(30, activation='relu'))
model.add(Dropout(0.1)) # pick a number between 0.1 and 0.3
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 30)             │         1,890 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 30)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,049 (8.00 KB)

 Trainable params: 2,049 (8.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16:55 2s/step - loss: 80.8332 - mae: 8.6186

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 31.0962 - mae: 4.5309

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 23.1035 - mae: 3.8369

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 19.2142 - mae: 3.4108

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 17.6110 - mae: 3.2632

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 16.7614 - mae: 3.1944

 85/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 16.5266 - mae: 3.1723

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 15.4704 - mae: 3.0641

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 14.7551 - mae: 2.9798

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 14.3279 - mae: 2.9329

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 14.0232 - mae: 2.9049

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13.5620 - mae: 2.8660

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13.5398 - mae: 2.8736

175/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13.3759 - mae: 2.8551

186/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13.3461 - mae: 2.8544

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 13.0390 - mae: 2.8179

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.8052 - mae: 2.7965

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.6548 - mae: 2.7858

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.6502 - mae: 2.7796

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.3553 - mae: 2.7440

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.1737 - mae: 2.7184

279/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 12.0613 - mae: 2.7071

292/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.9335 - mae: 2.6935

305/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.7154 - mae: 2.6703

318/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.5817 - mae: 2.6541

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.5174 - mae: 2.6422

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.4351 - mae: 2.6352

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.3316 - mae: 2.6184

370/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.2939 - mae: 2.6125

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.1353 - mae: 2.5905

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.0651 - mae: 2.5803

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.9587 - mae: 2.5678

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.9887 - mae: 2.5716

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.9563 - mae: 2.5701

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.9008 - mae: 2.5611

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.8394 - mae: 2.5558

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.8262 - mae: 2.5548

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.8241 - mae: 2.5563

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.8064 - mae: 2.5566

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.7489 - mae: 2.5521

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - loss: 10.7161 - mae: 2.5463 - val_loss: 6.1029 - val_mae: 1.9414

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16s 33ms/step - loss: 29.3321 - mae: 4.8557

 14/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 10.1520 - mae: 2.5496

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.0362 - mae: 2.3744

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6366 - mae: 2.3622

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6373 - mae: 2.3721

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7454 - mae: 2.3765

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.4781 - mae: 2.4762

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.3306 - mae: 2.4666

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.5032 - mae: 2.4869

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.5280 - mae: 2.4771

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.3262 - mae: 2.4469

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.2672 - mae: 2.4422

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.5419 - mae: 2.4759

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.4474 - mae: 2.4483

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.5210 - mae: 2.4606

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.4200 - mae: 2.4453

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.3975 - mae: 2.4435

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.4869 - mae: 2.4553

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.4539 - mae: 2.4546

262/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.2624 - mae: 2.4246

275/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.1979 - mae: 2.4104

289/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.0919 - mae: 2.3992

302/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.0272 - mae: 2.3881

316/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9345 - mae: 2.3722

330/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8545 - mae: 2.3582

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9288 - mae: 2.3660

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9138 - mae: 2.3624

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.9164 - mae: 2.3625

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7988 - mae: 2.3449

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8916 - mae: 2.3566

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8768 - mae: 2.3526

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8767 - mae: 2.3514

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8593 - mae: 2.3474

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7785 - mae: 2.3347

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7856 - mae: 2.3362

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7709 - mae: 2.3357

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8013 - mae: 2.3381

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7399 - mae: 2.3336

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7209 - mae: 2.3294

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.7225 - mae: 2.3299 - val_loss: 6.1435 - val_mae: 1.9390

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 10.1828 - mae: 2.9278

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 10.5447 - mae: 2.5786

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.8376 - mae: 2.4611

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7688 - mae: 2.3121

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9156 - mae: 2.3538

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.8197 - mae: 2.3461

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.3478 - mae: 2.4383

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.0100 - mae: 2.4000

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7402 - mae: 2.3568

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6478 - mae: 2.3263

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5268 - mae: 2.3065

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6528 - mae: 2.3352

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7881 - mae: 2.3632

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.8014 - mae: 2.3548

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7187 - mae: 2.3469

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9296 - mae: 2.3620

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9823 - mae: 2.3803

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9355 - mae: 2.3776

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.8832 - mae: 2.3712

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.8362 - mae: 2.3654

269/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.8538 - mae: 2.3658

283/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.7471 - mae: 2.3517

297/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6974 - mae: 2.3420

311/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6635 - mae: 2.3385

325/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5165 - mae: 2.3189

338/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5194 - mae: 2.3205

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5381 - mae: 2.3148

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5269 - mae: 2.3125

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5156 - mae: 2.3065

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5263 - mae: 2.3084

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.4934 - mae: 2.3004

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5162 - mae: 2.3038

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6636 - mae: 2.3192

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6970 - mae: 2.3211

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6665 - mae: 2.3207

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6353 - mae: 2.3145

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6553 - mae: 2.3183

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6326 - mae: 2.3131

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.5980 - mae: 2.3111

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5940 - mae: 2.3105 - val_loss: 6.0646 - val_mae: 1.9322

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 11.5651 - mae: 2.6103

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9.7870 - mae: 2.5245

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7275 - mae: 2.3717

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9300 - mae: 2.2317

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7708 - mae: 2.2328

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1074 - mae: 2.2552

 85/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.8023 - mae: 2.3517

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3293 - mae: 2.2727

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3886 - mae: 2.2808

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4786 - mae: 2.2882

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4006 - mae: 2.2828

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4578 - mae: 2.2967

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6257 - mae: 2.3157

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5722 - mae: 2.3025

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5002 - mae: 2.2935

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5156 - mae: 2.2909

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4530 - mae: 2.2914

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5596 - mae: 2.3057

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5389 - mae: 2.3114

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4893 - mae: 2.2962

271/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.3813 - mae: 2.2762

284/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2897 - mae: 2.2661

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1876 - mae: 2.2522

313/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1435 - mae: 2.2494

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0497 - mae: 2.2382

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0914 - mae: 2.2463

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0661 - mae: 2.2381

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0251 - mae: 2.2321

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0351 - mae: 2.2298

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0831 - mae: 2.2341

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0352 - mae: 2.2285

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0748 - mae: 2.2319

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1735 - mae: 2.2426

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1661 - mae: 2.2400

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1807 - mae: 2.2416

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1520 - mae: 2.2384

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1710 - mae: 2.2427

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1379 - mae: 2.2412

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0752 - mae: 2.2337

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.0901 - mae: 2.2355 - val_loss: 5.8715 - val_mae: 1.8921

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 6.4947 - mae: 2.1475

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1948 - mae: 2.2372

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0392 - mae: 2.2262

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5777 - mae: 2.1150

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6947 - mae: 2.1556

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4849 - mae: 2.1250

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9913 - mae: 2.2171

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7763 - mae: 2.1883

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8301 - mae: 2.2040

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1922 - mae: 2.2375

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0092 - mae: 2.2202

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0893 - mae: 2.2309

167/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1246 - mae: 2.2319

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1888 - mae: 2.2330

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5710 - mae: 2.2780

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5092 - mae: 2.2697

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4426 - mae: 2.2659

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.6500 - mae: 2.2824

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5612 - mae: 2.2740

263/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.4562 - mae: 2.2552

277/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.3767 - mae: 2.2462

291/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2931 - mae: 2.2284

305/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2121 - mae: 2.2219

320/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1161 - mae: 2.2095

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0725 - mae: 2.2060

347/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0765 - mae: 2.2015

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0295 - mae: 2.1925

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0612 - mae: 2.1966

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0695 - mae: 2.1989

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0623 - mae: 2.1960

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0490 - mae: 2.1974

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0726 - mae: 2.2011

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0931 - mae: 2.2036

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0478 - mae: 2.1988

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0950 - mae: 2.2048

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1098 - mae: 2.2071

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0885 - mae: 2.2036

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0947 - mae: 2.2037

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.0551 - mae: 2.1975 - val_loss: 5.8073 - val_mae: 1.8743

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 6.3081 - mae: 1.8427

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2448 - mae: 1.9550

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7355 - mae: 2.0111

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4831 - mae: 1.9755

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1768 - mae: 2.1057

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1912 - mae: 2.1121

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8006 - mae: 2.2106

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5999 - mae: 2.1698

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4805 - mae: 2.1493

122/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6476 - mae: 2.1617

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6468 - mae: 2.1616

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6716 - mae: 2.1721

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8781 - mae: 2.2110

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9176 - mae: 2.2116

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9538 - mae: 2.2206

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0220 - mae: 2.2218

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0189 - mae: 2.2275

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0264 - mae: 2.2365

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8811 - mae: 2.2150

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7858 - mae: 2.1994

271/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7324 - mae: 2.1804

284/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6989 - mae: 2.1781

297/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6458 - mae: 2.1658

310/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6205 - mae: 2.1658

325/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5181 - mae: 2.1555

338/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5522 - mae: 2.1599

352/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6831 - mae: 2.1692

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6928 - mae: 2.1677

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7176 - mae: 2.1747

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7558 - mae: 2.1787

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6905 - mae: 2.1677

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7197 - mae: 2.1767

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7538 - mae: 2.1831

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7812 - mae: 2.1888

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7930 - mae: 2.1914

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8002 - mae: 2.1922

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8282 - mae: 2.1955

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8327 - mae: 2.1979

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7679 - mae: 2.1879

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.7918 - mae: 2.1911 - val_loss: 5.8621 - val_mae: 1.8820

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 9.1622 - mae: 2.1266

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.9486 - mae: 2.3574

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1757 - mae: 2.1703

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4670 - mae: 2.1009

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1143 - mae: 2.1785

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8033 - mae: 2.1487

 81/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.7202 - mae: 2.2691

 94/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2935 - mae: 2.2045

107/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1354 - mae: 2.1918

120/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3354 - mae: 2.2099

133/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3332 - mae: 2.2146

146/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3415 - mae: 2.2289

159/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4846 - mae: 2.2565

172/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4227 - mae: 2.2526

186/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4754 - mae: 2.2636

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4632 - mae: 2.2567

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3287 - mae: 2.2424

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3451 - mae: 2.2497

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3674 - mae: 2.2560

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3492 - mae: 2.2523

268/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2462 - mae: 2.2345

281/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2876 - mae: 2.2483

294/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.2096 - mae: 2.2383

308/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1248 - mae: 2.2261

322/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0335 - mae: 2.2138

335/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0422 - mae: 2.2168

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1152 - mae: 2.2222

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0814 - mae: 2.2167

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0988 - mae: 2.2183

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1691 - mae: 2.2291

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1074 - mae: 2.2234

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0704 - mae: 2.2172

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0762 - mae: 2.2172

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0657 - mae: 2.2127

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0721 - mae: 2.2169

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0651 - mae: 2.2175

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1017 - mae: 2.2241

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1189 - mae: 2.2282

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0521 - mae: 2.2173

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 8.0347 - mae: 2.2146 - val_loss: 5.8090 - val_mae: 1.8731

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 10.2827 - mae: 2.3328

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2782 - mae: 2.2709

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4548 - mae: 2.2634

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7911 - mae: 2.1907

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8191 - mae: 2.2048

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9243 - mae: 2.1949

 85/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5212 - mae: 2.3197

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1235 - mae: 2.2520

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1332 - mae: 2.2567

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4685 - mae: 2.2878

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3006 - mae: 2.2692

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2871 - mae: 2.2740

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3680 - mae: 2.2987

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3818 - mae: 2.2992

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2985 - mae: 2.2906

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3083 - mae: 2.2864

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2565 - mae: 2.2831

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2951 - mae: 2.2857

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2428 - mae: 2.2867

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1871 - mae: 2.2731

268/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1057 - mae: 2.2587

281/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1689 - mae: 2.2637

294/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1778 - mae: 2.2600

308/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.1008 - mae: 2.2537

321/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9817 - mae: 2.2356

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9242 - mae: 2.2290

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9535 - mae: 2.2331

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9176 - mae: 2.2234

375/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9561 - mae: 2.2219

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0390 - mae: 2.2323

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0351 - mae: 2.2274

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0380 - mae: 2.2282

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0531 - mae: 2.2288

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0585 - mae: 2.2304

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0233 - mae: 2.2256

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0325 - mae: 2.2250

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0275 - mae: 2.2250

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0044 - mae: 2.2221

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9786 - mae: 2.2174

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9654 - mae: 2.2145

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9654 - mae: 2.2145 - val_loss: 5.8965 - val_mae: 1.8869

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 4.4219 - mae: 1.7461

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4500 - mae: 1.9932

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3030 - mae: 2.0736

 40/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7529 - mae: 1.9992

 53/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9052 - mae: 2.0301

 67/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8323 - mae: 2.0313

 81/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7745 - mae: 2.1732

 94/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5740 - mae: 2.1628

107/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6650 - mae: 2.1704

119/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6744 - mae: 2.1655

132/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6231 - mae: 2.1626

145/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6406 - mae: 2.1637

157/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6084 - mae: 2.1649

168/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8140 - mae: 2.1918

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7521 - mae: 2.1899

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9437 - mae: 2.2133

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0623 - mae: 2.2327

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9857 - mae: 2.2236

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0655 - mae: 2.2394

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0212 - mae: 2.2357

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9603 - mae: 2.2196

277/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9222 - mae: 2.2153

290/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8578 - mae: 2.2069

303/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8329 - mae: 2.2057

317/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7200 - mae: 2.1899

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7010 - mae: 2.1812

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7605 - mae: 2.1929

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8076 - mae: 2.1932

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8576 - mae: 2.2018

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8201 - mae: 2.1990

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8248 - mae: 2.1971

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8218 - mae: 2.1963

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9123 - mae: 2.2048

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9737 - mae: 2.2138

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9250 - mae: 2.2080

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9157 - mae: 2.2072

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9389 - mae: 2.2099

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9471 - mae: 2.2094

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9225 - mae: 2.2077

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8568 - mae: 2.1989

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8624 - mae: 2.1988 - val_loss: 5.7733 - val_mae: 1.8659

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 9.9203 - mae: 2.7833

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7094 - mae: 2.1868

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5347 - mae: 2.1260

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5129 - mae: 2.1472

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3263 - mae: 2.1174

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2782 - mae: 2.1013

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7148 - mae: 2.1786

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6131 - mae: 2.1454

112/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6505 - mae: 2.1596

126/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6852 - mae: 2.1498

140/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6384 - mae: 2.1454

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7278 - mae: 2.1733

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8978 - mae: 2.2073

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9424 - mae: 2.2173

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0314 - mae: 2.2223

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0162 - mae: 2.2177

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9998 - mae: 2.2234

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9819 - mae: 2.2297

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0246 - mae: 2.2360

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9595 - mae: 2.2281

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8800 - mae: 2.2146

278/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8752 - mae: 2.2128

291/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8059 - mae: 2.2040

303/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7381 - mae: 2.1939

315/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6822 - mae: 2.1821

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5804 - mae: 2.1667

339/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5821 - mae: 2.1679

352/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6896 - mae: 2.1783

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6509 - mae: 2.1754

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6883 - mae: 2.1787

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8097 - mae: 2.1935

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8029 - mae: 2.1929

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8073 - mae: 2.1954

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8392 - mae: 2.1965

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8750 - mae: 2.2023

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9033 - mae: 2.2055

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8911 - mae: 2.2047

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9040 - mae: 2.2079

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9256 - mae: 2.2118

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9218 - mae: 2.2131

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9054 - mae: 2.2097

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8772 - mae: 2.2054

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 7.8782 - mae: 2.2049 - val_loss: 5.9906 - val_mae: 1.9121

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 7.7111 - mae: 1.9949

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0461 - mae: 2.2825

 24/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0749 - mae: 2.2347

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2812 - mae: 2.1897

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2367 - mae: 2.1887

 58/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2374 - mae: 2.1717

 70/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1468 - mae: 2.1559

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7614 - mae: 2.2370

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6772 - mae: 2.2262

103/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4749 - mae: 2.1802

114/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3823 - mae: 2.1640

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5179 - mae: 2.1623

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3708 - mae: 2.1398

145/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4823 - mae: 2.1669

156/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3517 - mae: 2.1500

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7066 - mae: 2.1974

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7368 - mae: 2.2029

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8158 - mae: 2.2156

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8621 - mae: 2.2159

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8387 - mae: 2.2194

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8577 - mae: 2.2177

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8774 - mae: 2.2234

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8117 - mae: 2.2143

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7968 - mae: 2.2107

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7478 - mae: 2.1982

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7813 - mae: 2.2047

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6913 - mae: 2.1917

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6629 - mae: 2.1876

320/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6175 - mae: 2.1797

333/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5688 - mae: 2.1768

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5711 - mae: 2.1727

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6385 - mae: 2.1798

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6490 - mae: 2.1808

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5717 - mae: 2.1721

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6884 - mae: 2.1848

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6938 - mae: 2.1799

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7181 - mae: 2.1838

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7803 - mae: 2.1917

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7794 - mae: 2.1898

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7623 - mae: 2.1886

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7696 - mae: 2.1887

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7500 - mae: 2.1873

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7449 - mae: 2.1856

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6665 - mae: 2.1744

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 7.6771 - mae: 2.1760 - val_loss: 5.7356 - val_mae: 1.8619

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 7.3180 - mae: 2.0192

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8322 - mae: 2.2575

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9232 - mae: 2.2747

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9758 - mae: 2.0667

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0655 - mae: 2.0730

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0696 - mae: 2.0778

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7831 - mae: 2.1932

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4807 - mae: 2.1488

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3095 - mae: 2.1263

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5245 - mae: 2.1561

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4398 - mae: 2.1457

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4798 - mae: 2.1581

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6080 - mae: 2.1858

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6880 - mae: 2.2018

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7866 - mae: 2.2198

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8208 - mae: 2.2227

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8646 - mae: 2.2315

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9442 - mae: 2.2386

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9273 - mae: 2.2395

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8759 - mae: 2.2270

269/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8572 - mae: 2.2197

282/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7332 - mae: 2.2037

295/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6961 - mae: 2.1998

308/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6644 - mae: 2.2004

321/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6153 - mae: 2.1939

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5387 - mae: 2.1813

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5677 - mae: 2.1858

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5775 - mae: 2.1856

375/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6572 - mae: 2.1913

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6626 - mae: 2.1952

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7215 - mae: 2.2018

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7559 - mae: 2.2056

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8013 - mae: 2.2106

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7821 - mae: 2.2068

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8220 - mae: 2.2156

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8150 - mae: 2.2147

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8277 - mae: 2.2168

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8360 - mae: 2.2173

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8135 - mae: 2.2155

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7714 - mae: 2.2085

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7713 - mae: 2.2087 - val_loss: 5.7341 - val_mae: 1.8622

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 9.2098 - mae: 2.7356

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.3753 - mae: 2.1557

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1944 - mae: 2.1353

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4031 - mae: 2.0687

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3227 - mae: 2.0962

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3510 - mae: 2.0779

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0960 - mae: 2.2121

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7254 - mae: 2.1462

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6293 - mae: 2.1393

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7811 - mae: 2.1606

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6706 - mae: 2.1547

148/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6951 - mae: 2.1640

161/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8299 - mae: 2.1843

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7772 - mae: 2.1747

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8051 - mae: 2.1838

201/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8831 - mae: 2.1863

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8444 - mae: 2.1834

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9507 - mae: 2.2035

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9850 - mae: 2.2129

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8236 - mae: 2.1915

268/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7383 - mae: 2.1740

282/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7550 - mae: 2.1789

295/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6714 - mae: 2.1673

309/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6292 - mae: 2.1688

323/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5054 - mae: 2.1522

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4484 - mae: 2.1458

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4487 - mae: 2.1446

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4396 - mae: 2.1452

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4585 - mae: 2.1499

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5488 - mae: 2.1596

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5044 - mae: 2.1521

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4952 - mae: 2.1509

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5694 - mae: 2.1610

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5746 - mae: 2.1596

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5923 - mae: 2.1653

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5779 - mae: 2.1642

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6033 - mae: 2.1659

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5515 - mae: 2.1580

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4963 - mae: 2.1514

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.5057 - mae: 2.1504 - val_loss: 5.6986 - val_mae: 1.8562

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - loss: 9.9714 - mae: 2.3319

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2043 - mae: 2.1543

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2339 - mae: 2.1999

 40/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6435 - mae: 2.1707

 54/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5146 - mae: 2.1618

 68/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4173 - mae: 2.1306

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.5080 - mae: 2.2709

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1897 - mae: 2.2283

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0887 - mae: 2.2116

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0307 - mae: 2.1945

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9542 - mae: 2.1896

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1532 - mae: 2.2241

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2348 - mae: 2.2423

177/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2694 - mae: 2.2396

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2782 - mae: 2.2487

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4790 - mae: 2.2752

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4861 - mae: 2.2789

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4257 - mae: 2.2724

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2635 - mae: 2.2538

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1671 - mae: 2.2410

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.0935 - mae: 2.2280

286/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9798 - mae: 2.2114

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9025 - mae: 2.2036

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8681 - mae: 2.1985

326/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7745 - mae: 2.1841

339/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8662 - mae: 2.1894

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9378 - mae: 2.2011

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9191 - mae: 2.1963

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8974 - mae: 2.1923

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9534 - mae: 2.1928

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8922 - mae: 2.1853

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9373 - mae: 2.1906

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9911 - mae: 2.1966

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9759 - mae: 2.1955

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9431 - mae: 2.1918

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9542 - mae: 2.1959

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9355 - mae: 2.1921

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9540 - mae: 2.1869

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8862 - mae: 2.1748

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.8909 - mae: 2.1749 - val_loss: 5.7885 - val_mae: 1.8783

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 6.4656 - mae: 2.2262

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3882 - mae: 2.1496

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3185 - mae: 2.1287

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8885 - mae: 2.0631

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4540 - mae: 2.1571

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4652 - mae: 2.1450

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0336 - mae: 2.2401

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7220 - mae: 2.1893

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7638 - mae: 2.2064

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8907 - mae: 2.2009

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6720 - mae: 2.1679

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8702 - mae: 2.2014

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8839 - mae: 2.2016

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8729 - mae: 2.2025

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9313 - mae: 2.2103

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0579 - mae: 2.2268

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1007 - mae: 2.2357

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1208 - mae: 2.2426

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0618 - mae: 2.2408

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0320 - mae: 2.2292

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.9389 - mae: 2.2121

286/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8253 - mae: 2.1937

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7953 - mae: 2.1892

313/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7551 - mae: 2.1837

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6621 - mae: 2.1655

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6725 - mae: 2.1696

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6795 - mae: 2.1704

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6455 - mae: 2.1624

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6428 - mae: 2.1651

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6550 - mae: 2.1666

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6309 - mae: 2.1605

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6536 - mae: 2.1615

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6587 - mae: 2.1642

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6724 - mae: 2.1675

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6782 - mae: 2.1707

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6856 - mae: 2.1730

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6673 - mae: 2.1701

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6704 - mae: 2.1717

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6461 - mae: 2.1681

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6009 - mae: 2.1621

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6004 - mae: 2.1627 - val_loss: 5.7497 - val_mae: 1.8620

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 9.7124 - mae: 2.6792

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5265 - mae: 2.0970

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9353 - mae: 2.0669

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5318 - mae: 2.0059

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5258 - mae: 2.0203

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7832 - mae: 2.0546

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3679 - mae: 2.1450

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3399 - mae: 2.1453

108/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2087 - mae: 2.1174

121/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2395 - mae: 2.1154

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2405 - mae: 2.1175

147/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2523 - mae: 2.1178

160/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4303 - mae: 2.1484

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4788 - mae: 2.1524

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5300 - mae: 2.1667

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6248 - mae: 2.1778

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6305 - mae: 2.1838

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6302 - mae: 2.1878

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5838 - mae: 2.1878

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4719 - mae: 2.1624

271/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4489 - mae: 2.1563

284/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3953 - mae: 2.1484

298/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3007 - mae: 2.1333

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2549 - mae: 2.1333

325/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2036 - mae: 2.1171

339/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2300 - mae: 2.1195

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2598 - mae: 2.1176

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2403 - mae: 2.1154

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2011 - mae: 2.1114

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3022 - mae: 2.1245

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2349 - mae: 2.1092

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3346 - mae: 2.1215

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4082 - mae: 2.1287

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3833 - mae: 2.1252

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3584 - mae: 2.1230

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3755 - mae: 2.1289

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4252 - mae: 2.1350

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4418 - mae: 2.1372

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3993 - mae: 2.1306

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4012 - mae: 2.1331 - val_loss: 5.6708 - val_mae: 1.8562

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 5.5357 - mae: 1.9961

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0346 - mae: 2.2540

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2995 - mae: 2.1214

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6057 - mae: 2.0075

 54/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9324 - mae: 2.0814

 67/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9533 - mae: 2.0732

 81/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7869 - mae: 2.1948

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6221 - mae: 2.1847

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5757 - mae: 2.1806

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6784 - mae: 2.1809

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6978 - mae: 2.1814

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6868 - mae: 2.1913

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7737 - mae: 2.2103

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8625 - mae: 2.2133

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9132 - mae: 2.2222

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9159 - mae: 2.2190

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9621 - mae: 2.2334

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0540 - mae: 2.2466

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0096 - mae: 2.2505

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8687 - mae: 2.2217

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8325 - mae: 2.2125

285/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7795 - mae: 2.2009

298/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7416 - mae: 2.1916

311/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7062 - mae: 2.1900

324/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6762 - mae: 2.1859

338/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6836 - mae: 2.1875

352/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8105 - mae: 2.1970

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8470 - mae: 2.2022

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8098 - mae: 2.2005

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8918 - mae: 2.2114

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7815 - mae: 2.1932

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8134 - mae: 2.1974

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8627 - mae: 2.2016

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8665 - mae: 2.2046

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8714 - mae: 2.2068

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8374 - mae: 2.2032

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8489 - mae: 2.2048

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8096 - mae: 2.2005

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7584 - mae: 2.1918

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.7457 - mae: 2.1903 - val_loss: 5.8739 - val_mae: 1.8812

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 4.8098 - mae: 2.0513

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5526 - mae: 2.1681

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9499 - mae: 2.0567

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2579 - mae: 1.9236

 54/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7633 - mae: 2.0270

 68/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9642 - mae: 2.0489

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3864 - mae: 2.1189

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3327 - mae: 2.1063

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4709 - mae: 2.1274

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6068 - mae: 2.1392

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4345 - mae: 2.1130

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5034 - mae: 2.1359

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7301 - mae: 2.1752

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7274 - mae: 2.1668

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8495 - mae: 2.1913

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8383 - mae: 2.1912

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7921 - mae: 2.1894

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8028 - mae: 2.1939

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7844 - mae: 2.1960

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7270 - mae: 2.1820

271/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6923 - mae: 2.1767

285/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6108 - mae: 2.1655

298/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6247 - mae: 2.1681

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5739 - mae: 2.1663

326/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4873 - mae: 2.1500

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5271 - mae: 2.1571

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5527 - mae: 2.1591

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4975 - mae: 2.1505

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4968 - mae: 2.1564

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5454 - mae: 2.1624

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5131 - mae: 2.1591

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5377 - mae: 2.1618

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5333 - mae: 2.1595

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5138 - mae: 2.1563

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5432 - mae: 2.1633

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5570 - mae: 2.1643

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5911 - mae: 2.1707

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6046 - mae: 2.1695

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5131 - mae: 2.1551

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.5228 - mae: 2.1565 - val_loss: 5.7134 - val_mae: 1.8527

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 6.5774 - mae: 2.1856

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0991 - mae: 2.0866

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2398 - mae: 2.0643

 40/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1650 - mae: 2.0359

 54/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4634 - mae: 2.0878

 66/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4544 - mae: 2.0792

 78/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9352 - mae: 2.1653

 91/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.2101 - mae: 2.2179

104/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9434 - mae: 2.1842

117/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9635 - mae: 2.1855

131/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6883 - mae: 2.1504

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5668 - mae: 2.1309

158/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4852 - mae: 2.1258

172/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4627 - mae: 2.1175

185/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6473 - mae: 2.1468

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6735 - mae: 2.1528

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6430 - mae: 2.1487

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6764 - mae: 2.1573

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6409 - mae: 2.1549

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4926 - mae: 2.1312

267/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4187 - mae: 2.1145

280/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4345 - mae: 2.1143

294/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4609 - mae: 2.1224

308/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4032 - mae: 2.1172

321/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3452 - mae: 2.1101

335/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3265 - mae: 2.1062

349/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4203 - mae: 2.1209

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3621 - mae: 2.1127

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3720 - mae: 2.1151

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4365 - mae: 2.1227

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4415 - mae: 2.1218

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4661 - mae: 2.1263

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4960 - mae: 2.1299

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4944 - mae: 2.1291

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4966 - mae: 2.1309

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4982 - mae: 2.1317

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5337 - mae: 2.1376

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5032 - mae: 2.1333

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4779 - mae: 2.1291

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4552 - mae: 2.1257 - val_loss: 5.7084 - val_mae: 1.8619

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 3.5432 - mae: 1.5668

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7450 - mae: 2.0464

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6446 - mae: 2.0460

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2965 - mae: 1.9570

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4133 - mae: 1.9985

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6428 - mae: 2.0330

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5225 - mae: 2.1640

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2406 - mae: 2.1205

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1356 - mae: 2.1076

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3900 - mae: 2.1260

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4055 - mae: 2.1295

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4668 - mae: 2.1465

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5891 - mae: 2.1750

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6269 - mae: 2.1760

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8161 - mae: 2.1902

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8742 - mae: 2.1995

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8017 - mae: 2.1900

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8893 - mae: 2.1994

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8081 - mae: 2.1876

261/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6826 - mae: 2.1586

274/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6432 - mae: 2.1539

287/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6322 - mae: 2.1551

301/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5361 - mae: 2.1437

314/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4918 - mae: 2.1373

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3741 - mae: 2.1168

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3482 - mae: 2.1132

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3787 - mae: 2.1176

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3455 - mae: 2.1127

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3670 - mae: 2.1176

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3968 - mae: 2.1211

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3679 - mae: 2.1187

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4609 - mae: 2.1289

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5025 - mae: 2.1356

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4989 - mae: 2.1364

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5003 - mae: 2.1396

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5007 - mae: 2.1404

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5081 - mae: 2.1404

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4925 - mae: 2.1372

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4644 - mae: 2.1338

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4405 - mae: 2.1290 - val_loss: 5.7763 - val_mae: 1.8642

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 5.3065 - mae: 1.8918

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2295 - mae: 2.0026

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6260 - mae: 1.9915

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5071 - mae: 2.0169

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0347 - mae: 2.1106

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9071 - mae: 2.0598

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7858 - mae: 2.2003

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4892 - mae: 2.1529

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3967 - mae: 2.1321

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5906 - mae: 2.1519

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3810 - mae: 2.1274

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4379 - mae: 2.1443

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4910 - mae: 2.1516

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5202 - mae: 2.1506

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6437 - mae: 2.1761

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7991 - mae: 2.1916

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8052 - mae: 2.1960

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8788 - mae: 2.2076

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7882 - mae: 2.1982

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7238 - mae: 2.1853

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6551 - mae: 2.1730

285/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6045 - mae: 2.1715

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5763 - mae: 2.1691

313/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4519 - mae: 2.1529

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3313 - mae: 2.1352

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3398 - mae: 2.1403

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3939 - mae: 2.1428

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3891 - mae: 2.1434

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4064 - mae: 2.1451

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4607 - mae: 2.1454

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4135 - mae: 2.1381

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4413 - mae: 2.1386

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4838 - mae: 2.1438

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4490 - mae: 2.1383

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4401 - mae: 2.1394

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4458 - mae: 2.1396

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4679 - mae: 2.1413

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4575 - mae: 2.1377

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3996 - mae: 2.1303

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4029 - mae: 2.1312 - val_loss: 5.6382 - val_mae: 1.8424

Epoch 22/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 10.0831 - mae: 2.5762

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1473 - mae: 2.1207

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4061 - mae: 2.1556

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8701 - mae: 2.0258

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9743 - mae: 2.0541

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2838 - mae: 2.1145

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9492 - mae: 2.2329

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6986 - mae: 2.1745

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6516 - mae: 2.1650

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7104 - mae: 2.1649

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5383 - mae: 2.1435

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5653 - mae: 2.1564

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6203 - mae: 2.1613

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7120 - mae: 2.1773

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7624 - mae: 2.1940

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7295 - mae: 2.1836

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7406 - mae: 2.1933

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6948 - mae: 2.1797

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5554 - mae: 2.1647

261/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5169 - mae: 2.1522

275/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4750 - mae: 2.1462

288/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3901 - mae: 2.1336

302/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4771 - mae: 2.1461

315/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4038 - mae: 2.1353

329/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2812 - mae: 2.1168

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2582 - mae: 2.1111

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2416 - mae: 2.1048

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2227 - mae: 2.1035

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2202 - mae: 2.1050

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2676 - mae: 2.1036

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2557 - mae: 2.1004

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2612 - mae: 2.0978

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3220 - mae: 2.1070

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2888 - mae: 2.1036

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2597 - mae: 2.0992

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3124 - mae: 2.1066

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3034 - mae: 2.1037

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3091 - mae: 2.1054

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.2778 - mae: 2.1021 - val_loss: 5.7174 - val_mae: 1.8562

Epoch 23/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 4.5197 - mae: 1.7855

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5325 - mae: 2.1750

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4682 - mae: 2.0971

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0973 - mae: 2.0739

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0161 - mae: 2.0440

 68/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8729 - mae: 1.9853

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5918 - mae: 2.1038

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4877 - mae: 2.1071

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4757 - mae: 2.1077

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6711 - mae: 2.1363

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4159 - mae: 2.0994

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3823 - mae: 2.1090

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4769 - mae: 2.1313

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4832 - mae: 2.1294

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6040 - mae: 2.1575

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6436 - mae: 2.1634

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6841 - mae: 2.1712

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6850 - mae: 2.1743

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5973 - mae: 2.1641

260/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5631 - mae: 2.1506

274/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5289 - mae: 2.1449

287/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4554 - mae: 2.1340

300/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3633 - mae: 2.1182

314/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3105 - mae: 2.1138

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2343 - mae: 2.1008

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2719 - mae: 2.1057

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3158 - mae: 2.1115

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3615 - mae: 2.1188

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3378 - mae: 2.1153

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3900 - mae: 2.1182

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3673 - mae: 2.1156

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4069 - mae: 2.1207

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4603 - mae: 2.1312

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4344 - mae: 2.1288

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4325 - mae: 2.1306

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4108 - mae: 2.1265

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3903 - mae: 2.1247

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3898 - mae: 2.1207

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3072 - mae: 2.1080

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3092 - mae: 2.1089 - val_loss: 5.6655 - val_mae: 1.8491

Epoch 24/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 5.9380 - mae: 2.0006

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7007 - mae: 2.1354

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8884 - mae: 2.1697

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8703 - mae: 2.0218

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8314 - mae: 2.0292

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8891 - mae: 2.0312

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6952 - mae: 2.1620

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5066 - mae: 2.1389

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2810 - mae: 2.1001

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4460 - mae: 2.1097

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3174 - mae: 2.0848

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3930 - mae: 2.1081

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5137 - mae: 2.1308

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5714 - mae: 2.1337

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7374 - mae: 2.1557

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6304 - mae: 2.1414

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6236 - mae: 2.1449

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6564 - mae: 2.1537

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5771 - mae: 2.1491

262/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5206 - mae: 2.1347

276/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4489 - mae: 2.1222

290/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3830 - mae: 2.1145

303/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3501 - mae: 2.1086

317/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2761 - mae: 2.0972

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2042 - mae: 2.0848

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2756 - mae: 2.0912

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2747 - mae: 2.0884

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2599 - mae: 2.0837

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2563 - mae: 2.0844

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3408 - mae: 2.0950

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3471 - mae: 2.0938

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3628 - mae: 2.0937

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4034 - mae: 2.0965

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4060 - mae: 2.0969

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4194 - mae: 2.1023

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4431 - mae: 2.1063

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4569 - mae: 2.1096

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4505 - mae: 2.1085

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3930 - mae: 2.1008

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3969 - mae: 2.1017 - val_loss: 5.7494 - val_mae: 1.8707

Epoch 25/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 6.0342 - mae: 2.1216

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4225 - mae: 1.8920

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8710 - mae: 1.9772

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3497 - mae: 1.9043

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8094 - mae: 2.0200

 68/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0098 - mae: 2.0468

 81/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7686 - mae: 2.1699

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7267 - mae: 2.1692

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6028 - mae: 2.1535

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7208 - mae: 2.1542

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6398 - mae: 2.1438

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5833 - mae: 2.1513

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6822 - mae: 2.1692

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9035 - mae: 2.1982

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9640 - mae: 2.2085

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9448 - mae: 2.2064

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8928 - mae: 2.2014

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8245 - mae: 2.1922

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7191 - mae: 2.1856

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6251 - mae: 2.1682

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5709 - mae: 2.1567

284/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5486 - mae: 2.1527

297/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4717 - mae: 2.1447

310/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3960 - mae: 2.1359

323/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2870 - mae: 2.1206

336/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2834 - mae: 2.1199

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3333 - mae: 2.1245

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3248 - mae: 2.1253

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3611 - mae: 2.1300

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3707 - mae: 2.1320

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3420 - mae: 2.1265

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3793 - mae: 2.1283

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4092 - mae: 2.1312

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3835 - mae: 2.1258

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3577 - mae: 2.1248

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3789 - mae: 2.1324

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4003 - mae: 2.1347

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3961 - mae: 2.1343

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3728 - mae: 2.1305

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3478 - mae: 2.1277 - val_loss: 5.9626 - val_mae: 1.9145

Epoch 26/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - loss: 13.6422 - mae: 2.6367

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5308 - mae: 2.0994

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4821 - mae: 2.1429

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6444 - mae: 2.0071

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5933 - mae: 2.0138

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7086 - mae: 2.0236

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7301 - mae: 2.1797

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5555 - mae: 2.1559

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4746 - mae: 2.1425

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4919 - mae: 2.1398

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3455 - mae: 2.1157

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4875 - mae: 2.1479

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5646 - mae: 2.1659

177/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6013 - mae: 2.1658

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5336 - mae: 2.1611

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6643 - mae: 2.1773

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7450 - mae: 2.1928

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7811 - mae: 2.1992

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7292 - mae: 2.1973

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6647 - mae: 2.1816

271/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6783 - mae: 2.1819

284/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6084 - mae: 2.1735

298/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5690 - mae: 2.1673

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5368 - mae: 2.1649

326/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4201 - mae: 2.1441

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4283 - mae: 2.1472

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4303 - mae: 2.1459

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3842 - mae: 2.1382

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4061 - mae: 2.1419

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4253 - mae: 2.1435

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3996 - mae: 2.1394

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4271 - mae: 2.1379

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4659 - mae: 2.1455

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4290 - mae: 2.1397

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4177 - mae: 2.1388

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4048 - mae: 2.1366

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3963 - mae: 2.1359

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3699 - mae: 2.1315

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2979 - mae: 2.1198

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.3037 - mae: 2.1202 - val_loss: 5.8280 - val_mae: 1.8856

Epoch 27/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 3.8813 - mae: 1.5935

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2673 - mae: 2.1015

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8853 - mae: 2.0782

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9924 - mae: 2.0803

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2521 - mae: 2.1238

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4725 - mae: 2.1591

 85/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6550 - mae: 2.1974

 99/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4612 - mae: 2.1323

112/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4537 - mae: 2.1406

126/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5083 - mae: 2.1446

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3951 - mae: 2.1353

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4687 - mae: 2.1502

168/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7330 - mae: 2.1778

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8139 - mae: 2.1882

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7954 - mae: 2.1836

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7838 - mae: 2.1839

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7423 - mae: 2.1832

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7611 - mae: 2.1866

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7227 - mae: 2.1917

263/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7098 - mae: 2.1834

275/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6870 - mae: 2.1778

289/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5681 - mae: 2.1623

303/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5178 - mae: 2.1563

317/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4226 - mae: 2.1437

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3791 - mae: 2.1360

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3368 - mae: 2.1312

359/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2940 - mae: 2.1198

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3363 - mae: 2.1250

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2994 - mae: 2.1198

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3636 - mae: 2.1245

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3534 - mae: 2.1197

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3824 - mae: 2.1235

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3489 - mae: 2.1198

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3311 - mae: 2.1171

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3300 - mae: 2.1179

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3099 - mae: 2.1121

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2932 - mae: 2.1088

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2922 - mae: 2.1106

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2348 - mae: 2.1006

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.2348 - mae: 2.1006 - val_loss: 5.6208 - val_mae: 1.8443

Epoch 28/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 7.5277 - mae: 2.3230

 15/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9666 - mae: 2.1303

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9517 - mae: 2.0950

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7748 - mae: 2.0596

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7902 - mae: 2.1028

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7882 - mae: 2.0949

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5506 - mae: 2.2153

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3472 - mae: 2.1825

108/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0187 - mae: 2.1230

122/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1558 - mae: 2.1379

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0009 - mae: 2.1098

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0464 - mae: 2.1271

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1427 - mae: 2.1402

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2261 - mae: 2.1426

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3259 - mae: 2.1489

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3332 - mae: 2.1501

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2733 - mae: 2.1422

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2770 - mae: 2.1376

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2108 - mae: 2.1328

260/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2293 - mae: 2.1288

274/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1783 - mae: 2.1204

286/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1485 - mae: 2.1156

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1226 - mae: 2.1167

312/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0684 - mae: 2.1118

325/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9521 - mae: 2.0923

338/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9927 - mae: 2.0945

352/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0693 - mae: 2.1009

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0432 - mae: 2.0985

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1009 - mae: 2.1069

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1624 - mae: 2.1137

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1013 - mae: 2.1039

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0999 - mae: 2.1042

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1482 - mae: 2.1116

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2030 - mae: 2.1186

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2011 - mae: 2.1186

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2200 - mae: 2.1228

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2444 - mae: 2.1256

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2283 - mae: 2.1225

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1713 - mae: 2.1137

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1905 - mae: 2.1164 - val_loss: 5.6448 - val_mae: 1.8395

Epoch 29/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 8.1716 - mae: 1.7962

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0229 - mae: 2.2647

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3076 - mae: 2.0798

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5355 - mae: 1.9773

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7913 - mae: 2.0442

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7975 - mae: 2.0565

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6096 - mae: 2.1867

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2699 - mae: 2.1267

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2014 - mae: 2.1182

124/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2479 - mae: 2.1098

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3520 - mae: 2.1210

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2729 - mae: 2.1268

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2790 - mae: 2.1299

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4001 - mae: 2.1508

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5531 - mae: 2.1631

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5877 - mae: 2.1705

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5738 - mae: 2.1681

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5576 - mae: 2.1627

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4609 - mae: 2.1552

260/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4806 - mae: 2.1509

274/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3729 - mae: 2.1322

287/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2841 - mae: 2.1197

299/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2340 - mae: 2.1136

313/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1677 - mae: 2.1082

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1152 - mae: 2.1015

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1817 - mae: 2.1144

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2106 - mae: 2.1122

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1749 - mae: 2.1052

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1654 - mae: 2.1050

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2121 - mae: 2.1109

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1660 - mae: 2.1030

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1612 - mae: 2.1052

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2255 - mae: 2.1118

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2076 - mae: 2.1103

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2018 - mae: 2.1124

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2506 - mae: 2.1201

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2740 - mae: 2.1238

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2929 - mae: 2.1269

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2076 - mae: 2.1116

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.2224 - mae: 2.1135 - val_loss: 5.7125 - val_mae: 1.8593

Epoch 30/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 5.5832 - mae: 2.0266

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0133 - mae: 2.1849

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.4811 - mae: 2.2222

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5149 - mae: 2.1031

 57/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4748 - mae: 2.1225

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5606 - mae: 2.1386

 85/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8517 - mae: 2.2002

 99/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3271 - mae: 2.1063

113/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2588 - mae: 2.1109

126/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3459 - mae: 2.1037

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2587 - mae: 2.0947

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2561 - mae: 2.1114

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4076 - mae: 2.1415

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4602 - mae: 2.1493

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5860 - mae: 2.1664

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6266 - mae: 2.1696

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5923 - mae: 2.1687

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5959 - mae: 2.1710

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4808 - mae: 2.1600

262/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4494 - mae: 2.1543

276/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4272 - mae: 2.1482

289/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3763 - mae: 2.1357

303/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2938 - mae: 2.1265

316/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2623 - mae: 2.1228

326/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1823 - mae: 2.1082

336/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1559 - mae: 2.1060

347/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2810 - mae: 2.1179

359/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2215 - mae: 2.1063

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2744 - mae: 2.1135

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2533 - mae: 2.1124

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2864 - mae: 2.1149

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2770 - mae: 2.1147

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3133 - mae: 2.1206

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3961 - mae: 2.1323

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3883 - mae: 2.1302

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3981 - mae: 2.1332

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4082 - mae: 2.1345

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4065 - mae: 2.1340

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4050 - mae: 2.1342

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3927 - mae: 2.1347

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3704 - mae: 2.1314 - val_loss: 5.6628 - val_mae: 1.8531

Epoch 31/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 6.1589 - mae: 2.0665

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1708 - mae: 2.2266

 30/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1408 - mae: 2.1789

 45/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8865 - mae: 2.0978

 58/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7403 - mae: 2.1067

 71/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8003 - mae: 2.1075

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.1739 - mae: 2.1975

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8003 - mae: 2.1386

112/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7484 - mae: 2.1474

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8215 - mae: 2.1497

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7421 - mae: 2.1418

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7567 - mae: 2.1504

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8430 - mae: 2.1715

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8755 - mae: 2.1763

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0836 - mae: 2.1931

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0438 - mae: 2.2007

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0404 - mae: 2.2034

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8.0772 - mae: 2.2117

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.9392 - mae: 2.1951

261/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8676 - mae: 2.1830

275/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.7655 - mae: 2.1686

289/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6717 - mae: 2.1592

302/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6059 - mae: 2.1527

316/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5598 - mae: 2.1455

330/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4964 - mae: 2.1412

343/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5428 - mae: 2.1504

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5195 - mae: 2.1446

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5056 - mae: 2.1466

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4557 - mae: 2.1401

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5514 - mae: 2.1506

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5808 - mae: 2.1529

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5888 - mae: 2.1544

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.6078 - mae: 2.1564

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5867 - mae: 2.1543

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5691 - mae: 2.1571

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5500 - mae: 2.1545

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4812 - mae: 2.1430

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4683 - mae: 2.1414

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4114 - mae: 2.1302

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.4114 - mae: 2.1302 - val_loss: 5.6969 - val_mae: 1.8648

Epoch 32/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 3.5669 - mae: 1.4954

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8005 - mae: 2.0187

 28/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8231 - mae: 2.0565

 42/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3105 - mae: 1.9930

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6199 - mae: 2.0530

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5990 - mae: 2.0657

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1763 - mae: 2.1553

 97/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9415 - mae: 2.0965

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8011 - mae: 2.0720

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0547 - mae: 2.0944

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8618 - mae: 2.0697

151/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9868 - mae: 2.0991

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1066 - mae: 2.1183

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1411 - mae: 2.1108

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2019 - mae: 2.1205

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2435 - mae: 2.1224

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2387 - mae: 2.1243

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3554 - mae: 2.1425

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2587 - mae: 2.1299

259/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2495 - mae: 2.1272

273/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2292 - mae: 2.1197

286/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1167 - mae: 2.0994

300/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0564 - mae: 2.0931

314/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0290 - mae: 2.0939

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9243 - mae: 2.0758

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9244 - mae: 2.0762

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0187 - mae: 2.0860

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0627 - mae: 2.0931

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0547 - mae: 2.0939

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2073 - mae: 2.1144

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2089 - mae: 2.1131

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2284 - mae: 2.1153

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2499 - mae: 2.1183

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2482 - mae: 2.1202

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2387 - mae: 2.1206

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2380 - mae: 2.1210

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2589 - mae: 2.1239

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2338 - mae: 2.1177

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2005 - mae: 2.1104

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.2048 - mae: 2.1110 - val_loss: 5.6347 - val_mae: 1.8471

Epoch 33/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - loss: 6.7656 - mae: 1.8310

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2813 - mae: 1.9999

 30/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6041 - mae: 2.0538

 44/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3283 - mae: 1.9691

 58/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.2832 - mae: 1.9763

 72/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3338 - mae: 1.9739

 86/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0624 - mae: 2.1018

100/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9460 - mae: 2.0713

114/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7988 - mae: 2.0549

128/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8523 - mae: 2.0410

142/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9027 - mae: 2.0555

156/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7891 - mae: 2.0478

170/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9659 - mae: 2.0738

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0225 - mae: 2.0905

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2568 - mae: 2.1160

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2379 - mae: 2.1147

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2574 - mae: 2.1234

237/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3101 - mae: 2.1315

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2406 - mae: 2.1271

265/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2018 - mae: 2.1172

279/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1751 - mae: 2.1067

292/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1275 - mae: 2.0986

306/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0548 - mae: 2.0912

320/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0580 - mae: 2.0926

332/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9802 - mae: 2.0806

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0169 - mae: 2.0882

359/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0303 - mae: 2.0819

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0493 - mae: 2.0837

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0245 - mae: 2.0817

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1260 - mae: 2.0953

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0616 - mae: 2.0825

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1347 - mae: 2.0898

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1484 - mae: 2.0930

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1338 - mae: 2.0908

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1232 - mae: 2.0917

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1502 - mae: 2.0955

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1554 - mae: 2.0946

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1337 - mae: 2.0947

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0812 - mae: 2.0881

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.0812 - mae: 2.0881 - val_loss: 5.8507 - val_mae: 1.8936

Epoch 34/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 22s 44ms/step - loss: 6.1203 - mae: 2.1704

 14/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0023 - mae: 1.9746

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2751 - mae: 2.1001

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9051 - mae: 2.0447

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2244 - mae: 2.1340

 68/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2472 - mae: 2.1155

 82/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7348 - mae: 2.1926

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5123 - mae: 2.1507

109/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4625 - mae: 2.1278

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3747 - mae: 2.1144

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3210 - mae: 2.1044

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2864 - mae: 2.1130

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3941 - mae: 2.1368

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3508 - mae: 2.1302

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5333 - mae: 2.1605

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6650 - mae: 2.1778

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5722 - mae: 2.1677

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4805 - mae: 2.1593

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4556 - mae: 2.1563

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3574 - mae: 2.1383

267/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3809 - mae: 2.1338

280/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.4198 - mae: 2.1384

294/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3486 - mae: 2.1319

307/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3369 - mae: 2.1309

320/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2308 - mae: 2.1119

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1959 - mae: 2.1057

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2038 - mae: 2.1116

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1573 - mae: 2.1036

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1312 - mae: 2.0955

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1588 - mae: 2.1003

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1795 - mae: 2.1023

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1983 - mae: 2.1023

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2271 - mae: 2.1029

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2022 - mae: 2.1009

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1980 - mae: 2.1035

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2161 - mae: 2.1093

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2592 - mae: 2.1167

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2195 - mae: 2.1107

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1916 - mae: 2.1033

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1785 - mae: 2.1020 - val_loss: 5.7074 - val_mae: 1.8614

Epoch 35/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 7.0163 - mae: 2.3437

 14/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9741 - mae: 2.0481

 27/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8584 - mae: 2.0188

 40/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7775 - mae: 2.0301

 54/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8874 - mae: 2.0666

 67/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9896 - mae: 2.0654

 81/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4626 - mae: 2.1430

 95/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2998 - mae: 2.1143

108/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0782 - mae: 2.0792

122/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1163 - mae: 2.0841

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9667 - mae: 2.0640

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1351 - mae: 2.0966

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1615 - mae: 2.1140

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3327 - mae: 2.1246

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4851 - mae: 2.1494

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4641 - mae: 2.1495

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4301 - mae: 2.1441

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4395 - mae: 2.1515

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3314 - mae: 2.1397

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2298 - mae: 2.1137

273/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1657 - mae: 2.0975

287/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1326 - mae: 2.0964

302/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0747 - mae: 2.0923

315/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0019 - mae: 2.0835

329/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9252 - mae: 2.0685

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9330 - mae: 2.0707

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9181 - mae: 2.0668

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9413 - mae: 2.0715

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8966 - mae: 2.0657

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9546 - mae: 2.0692

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9525 - mae: 2.0669

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9960 - mae: 2.0722

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0806 - mae: 2.0829

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0531 - mae: 2.0794

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0724 - mae: 2.0825

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1245 - mae: 2.0913

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1534 - mae: 2.0919

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1288 - mae: 2.0872

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0756 - mae: 2.0780

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.0702 - mae: 2.0762 - val_loss: 5.6839 - val_mae: 1.8472

Epoch 36/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - loss: 14.1966 - mae: 2.6111

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1110 - mae: 2.0731

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0003 - mae: 2.0952

 41/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9790 - mae: 2.0579

 55/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9987 - mae: 2.0554

 69/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0578 - mae: 2.0628

 83/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.8288 - mae: 2.1703

 96/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4800 - mae: 2.1270

110/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3483 - mae: 2.1190

123/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.4607 - mae: 2.1284

136/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3912 - mae: 2.1224

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5135 - mae: 2.1521

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6218 - mae: 2.1803

177/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6686 - mae: 2.1831

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7292 - mae: 2.1957

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7761 - mae: 2.1987

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7296 - mae: 2.1969

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.7476 - mae: 2.1963

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.6351 - mae: 2.1859

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.5660 - mae: 2.1671

272/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5009 - mae: 2.1569

286/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3918 - mae: 2.1375

300/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3333 - mae: 2.1328

314/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2849 - mae: 2.1302

328/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1772 - mae: 2.1108

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1805 - mae: 2.1149

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2272 - mae: 2.1162

370/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2346 - mae: 2.1159

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2588 - mae: 2.1211

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2942 - mae: 2.1242

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2614 - mae: 2.1214

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3477 - mae: 2.1289

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3981 - mae: 2.1369

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3559 - mae: 2.1318

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3244 - mae: 2.1256

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3748 - mae: 2.1331

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3706 - mae: 2.1334

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3526 - mae: 2.1319

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2815 - mae: 2.1201

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.2821 - mae: 2.1199 - val_loss: 5.7067 - val_mae: 1.8638

Epoch 37/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 5.0547 - mae: 1.9774

 15/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.0997 - mae: 1.9132

 29/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5285 - mae: 1.9837

 43/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4636 - mae: 2.0086

 56/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5857 - mae: 2.0332

 70/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7921 - mae: 2.0478

 84/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.3500 - mae: 2.1438

 98/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0031 - mae: 2.0645

111/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7378 - mae: 2.0313

125/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9460 - mae: 2.0535

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7137 - mae: 2.0215

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6814 - mae: 2.0256

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8578 - mae: 2.0499

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9397 - mae: 2.0564

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9629 - mae: 2.0676

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0484 - mae: 2.0777

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9913 - mae: 2.0732

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0662 - mae: 2.0896

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0635 - mae: 2.0908

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0771 - mae: 2.0876

269/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0511 - mae: 2.0846

282/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9816 - mae: 2.0741

296/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9799 - mae: 2.0731

310/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9133 - mae: 2.0662

323/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8330 - mae: 2.0513

336/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7640 - mae: 2.0403

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8080 - mae: 2.0463

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7982 - mae: 2.0426

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8052 - mae: 2.0428

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8961 - mae: 2.0573

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8711 - mae: 2.0499

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9064 - mae: 2.0534

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9473 - mae: 2.0551

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9339 - mae: 2.0531

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9503 - mae: 2.0593

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9526 - mae: 2.0608

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9614 - mae: 2.0623

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9592 - mae: 2.0620

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9440 - mae: 2.0609

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9229 - mae: 2.0606

522/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9229 - mae: 2.0606 - val_loss: 5.7508 - val_mae: 1.8705

Epoch 37: early stopping

Restoring model weights from the end of the best epoch: 27.

In [14]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 2s 182ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

MAE:  1.8120725054767253

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# RNN two layer model
Don't forget to set return_sequences=True!

In [15]:
# now let's build a model
from keras.layers import Bidirectional

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(Bidirectional(SimpleRNN(30, return_sequences=True, activation='relu')))
model.add(Bidirectional(SimpleRNN(30)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 14, 60)         │         3,780 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 60)             │         5,460 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            61 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,429 (36.83 KB)

 Trainable params: 9,429 (36.83 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 37:16 4s/step - loss: 142.0427 - mae: 11.3905

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 121.5489 - mae: 10.3185

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 94.8380 - mae: 8.7671

 24/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 84.2092 - mae: 8.1065

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 74.5913 - mae: 7.5119

 36/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 68.5905 - mae: 7.2130

 42/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 63.4323 - mae: 6.8466

 48/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 59.0974 - mae: 6.4895

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 54.7718 - mae: 6.1844

 60/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 51.3538 - mae: 5.9472

 66/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 48.4960 - mae: 5.7001

 72/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 46.7093 - mae: 5.5667

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 44.8906 - mae: 5.4376

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 43.1388 - mae: 5.3200

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 41.3801 - mae: 5.1854

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 39.5193 - mae: 5.0301

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 38.2120 - mae: 4.9316

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 36.6867 - mae: 4.8091

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 35.5463 - mae: 4.7228

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 34.5965 - mae: 4.6447

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 33.7948 - mae: 4.5861

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 32.7924 - mae: 4.5056

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 31.8440 - mae: 4.4259

144/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 31.0715 - mae: 4.3660

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 30.5368 - mae: 4.3136

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 29.8338 - mae: 4.2564

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 29.3206 - mae: 4.2175

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 28.9607 - mae: 4.1958

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 28.4617 - mae: 4.1563

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 28.0988 - mae: 4.1168

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 27.5229 - mae: 4.0661

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 27.1090 - mae: 4.0343

196/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 26.7570 - mae: 3.9996

202/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 26.2882 - mae: 3.9603

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 25.9115 - mae: 3.9271

213/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 25.5570 - mae: 3.8979

219/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 25.1831 - mae: 3.8703

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 24.6952 - mae: 3.8244

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 24.5015 - mae: 3.7992

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 24.1373 - mae: 3.7611

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 23.7941 - mae: 3.7314

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 23.4855 - mae: 3.7080

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 23.1460 - mae: 3.6732

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 22.8610 - mae: 3.6471

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 22.5655 - mae: 3.6227

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 22.3405 - mae: 3.6038

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 22.1945 - mae: 3.5922

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 22.0406 - mae: 3.5824

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 21.8063 - mae: 3.5621

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 21.5323 - mae: 3.5333

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 21.3149 - mae: 3.5088

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 21.0806 - mae: 3.4871

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 20.8305 - mae: 3.4611

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 20.5586 - mae: 3.4345

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 20.2575 - mae: 3.4025

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 20.0921 - mae: 3.3879

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.8508 - mae: 3.3607

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.7576 - mae: 3.3548

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.6115 - mae: 3.3407

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.4628 - mae: 3.3276

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.3008 - mae: 3.3100

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 19.1160 - mae: 3.2917

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.9103 - mae: 3.2709

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.7777 - mae: 3.2558

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.6049 - mae: 3.2403

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.3939 - mae: 3.2178

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.2036 - mae: 3.1997

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.1383 - mae: 3.1950

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 18.0503 - mae: 3.1903

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 17.9326 - mae: 3.1786

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 17.8007 - mae: 3.1668

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 17.7257 - mae: 3.1609

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.6184 - mae: 3.1503

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.5269 - mae: 3.1431

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.4354 - mae: 3.1347

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.3486 - mae: 3.1292

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.2527 - mae: 3.1175

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.1529 - mae: 3.1088

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.0321 - mae: 3.0967

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.9193 - mae: 3.0865

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.8210 - mae: 3.0762

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.7087 - mae: 3.0641

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.6093 - mae: 3.0544

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.5105 - mae: 3.0425

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.4508 - mae: 3.0364

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.3912 - mae: 3.0322

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.2936 - mae: 3.0243

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.2259 - mae: 3.0172

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.1249 - mae: 3.0074

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.0497 - mae: 3.0017

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 15.9302 - mae: 2.9861

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 15.8608 - mae: 2.9803

522/522 ━━━━━━━━━━━━━━━━━━━━ 11s 12ms/step - loss: 15.8470 - mae: 2.9781 - val_loss: 7.6461 - val_mae: 2.1687

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 8.5564 - mae: 2.3668

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.2218 - mae: 2.2866

 12/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 8.6774 - mae: 2.3697

 18/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.0020 - mae: 2.2278

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.9140 - mae: 2.3070

 29/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.4980 - mae: 2.2442

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.7005 - mae: 2.1137

 39/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 7.9147 - mae: 2.1318

 43/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.4989 - mae: 2.0730

 46/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.5309 - mae: 2.0875

 50/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.9293 - mae: 2.1367

 55/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 7.8576 - mae: 2.1486

 61/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.9068 - mae: 2.1350

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.8467 - mae: 2.1309

 72/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.8108 - mae: 2.1244

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.1838 - mae: 2.1815

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.2928 - mae: 2.1983

 89/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.2572 - mae: 2.1993

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.1097 - mae: 2.1781

 99/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0233 - mae: 2.1596

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.9620 - mae: 2.1569

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.8464 - mae: 2.1440

114/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.8307 - mae: 2.1465

119/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.1060 - mae: 2.1608

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0161 - mae: 2.1532

130/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0891 - mae: 2.1743

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0526 - mae: 2.1743

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.9763 - mae: 2.1678

147/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.9655 - mae: 2.1719

152/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 8.0397 - mae: 2.1901

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.9528 - mae: 2.1827

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0709 - mae: 2.2066

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0350 - mae: 2.1980

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0578 - mae: 2.1966

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0339 - mae: 2.1919

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.0810 - mae: 2.2001

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.2282 - mae: 2.2153

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.1950 - mae: 2.2090

203/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 8.1589 - mae: 2.2067

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.1272 - mae: 2.2058

214/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.0706 - mae: 2.2004

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.0682 - mae: 2.2019

225/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.0120 - mae: 2.1955

231/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 8.0685 - mae: 2.2021

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.0604 - mae: 2.2031

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 8.0367 - mae: 2.2001

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.9849 - mae: 2.1963

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.9525 - mae: 2.1924

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.9174 - mae: 2.1856

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 7.8967 - mae: 2.1861

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.8740 - mae: 2.1823

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.8664 - mae: 2.1792

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.8375 - mae: 2.1749

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.8240 - mae: 2.1747

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.8580 - mae: 2.1831

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7901 - mae: 2.1715

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7655 - mae: 2.1686

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7538 - mae: 2.1676

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7561 - mae: 2.1665

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.7112 - mae: 2.1625

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6704 - mae: 2.1573

310/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6701 - mae: 2.1575

316/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.6078 - mae: 2.1512

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5989 - mae: 2.1485

326/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5313 - mae: 2.1379

332/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5588 - mae: 2.1426

337/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 7.5627 - mae: 2.1428

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5744 - mae: 2.1455

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5588 - mae: 2.1411

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5260 - mae: 2.1341

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5230 - mae: 2.1349

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5292 - mae: 2.1326

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5302 - mae: 2.1337

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4834 - mae: 2.1264

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4443 - mae: 2.1213

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5173 - mae: 2.1299

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5211 - mae: 2.1294

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5093 - mae: 2.1298

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.4848 - mae: 2.1265

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5089 - mae: 2.1294

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5411 - mae: 2.1340

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5320 - mae: 2.1340

421/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5411 - mae: 2.1329

426/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5749 - mae: 2.1370

430/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.5744 - mae: 2.1381

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5877 - mae: 2.1411

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5918 - mae: 2.1410

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6003 - mae: 2.1424

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6069 - mae: 2.1444

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5888 - mae: 2.1425

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5755 - mae: 2.1415

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5677 - mae: 2.1408

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5538 - mae: 2.1392

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5621 - mae: 2.1415

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5453 - mae: 2.1389

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5645 - mae: 2.1415

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5413 - mae: 2.1375

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5713 - mae: 2.1411

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5828 - mae: 2.1433

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5758 - mae: 2.1433

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5621 - mae: 2.1413

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5310 - mae: 2.1376

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5396 - mae: 2.1385

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5409 - mae: 2.1403

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5356 - mae: 2.1408

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5010 - mae: 2.1348

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4789 - mae: 2.1303

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4864 - mae: 2.1340

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - loss: 7.4980 - mae: 2.1346 - val_loss: 6.9314 - val_mae: 2.0801

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - loss: 7.8066 - mae: 2.1955

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1646 - mae: 1.9632

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6523 - mae: 2.0574

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3359 - mae: 1.9714

 24/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.2186 - mae: 2.0691

 30/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.9915 - mae: 2.0625

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4236 - mae: 1.9799

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4125 - mae: 1.9537

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7891 - mae: 2.0069

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.5779 - mae: 2.0029

 60/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.8343 - mae: 2.0161

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7268 - mae: 2.0035

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6682 - mae: 1.9893

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 7.0486 - mae: 2.0492

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1962 - mae: 2.0754

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2843 - mae: 2.0945

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1105 - mae: 2.0629

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1104 - mae: 2.0555

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.9858 - mae: 2.0391

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.9863 - mae: 2.0449

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1982 - mae: 2.0531

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1175 - mae: 2.0432

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2011 - mae: 2.0660

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1781 - mae: 2.0640

144/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1443 - mae: 2.0635

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1861 - mae: 2.0733

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1477 - mae: 2.0740

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2021 - mae: 2.0883

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1893 - mae: 2.0821

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2118 - mae: 2.0825

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.2025 - mae: 2.0788

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.1955 - mae: 2.0796

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 7.3921 - mae: 2.1020

198/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3812 - mae: 2.0986

204/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3505 - mae: 2.0984

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3333 - mae: 2.0964

216/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.3474 - mae: 2.1013

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2564 - mae: 2.0874

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2605 - mae: 2.0900

234/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2901 - mae: 2.0934

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2793 - mae: 2.0903

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.2233 - mae: 2.0863

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1966 - mae: 2.0841

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1759 - mae: 2.0786

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1619 - mae: 2.0793

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1500 - mae: 2.0752

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1013 - mae: 2.0699

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.1346 - mae: 2.0755

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0733 - mae: 2.0626

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0511 - mae: 2.0618

298/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 7.0204 - mae: 2.0592

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.9947 - mae: 2.0574

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9896 - mae: 2.0581

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9546 - mae: 2.0553

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9453 - mae: 2.0507

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8917 - mae: 2.0436

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8698 - mae: 2.0425

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.9138 - mae: 2.0471

340/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8918 - mae: 2.0447

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8808 - mae: 2.0436

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8886 - mae: 2.0420

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8782 - mae: 2.0381

362/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8607 - mae: 2.0363

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8913 - mae: 2.0389

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8755 - mae: 2.0371

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8445 - mae: 2.0323

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8213 - mae: 2.0283

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8889 - mae: 2.0398

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.8880 - mae: 2.0378

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.8802 - mae: 2.0379

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.8685 - mae: 2.0360

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.8728 - mae: 2.0353

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.9191 - mae: 2.0420

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.8887 - mae: 2.0373

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9143 - mae: 2.0403

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9467 - mae: 2.0434

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9500 - mae: 2.0453

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9584 - mae: 2.0466

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9807 - mae: 2.0503

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9733 - mae: 2.0489

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9833 - mae: 2.0494

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9894 - mae: 2.0516

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9710 - mae: 2.0492

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9647 - mae: 2.0485

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9613 - mae: 2.0488

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9449 - mae: 2.0466

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9462 - mae: 2.0484

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9618 - mae: 2.0509

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9624 - mae: 2.0504

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9461 - mae: 2.0472

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9810 - mae: 2.0517

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9961 - mae: 2.0547

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9846 - mae: 2.0540

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9605 - mae: 2.0508

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9667 - mae: 2.0520

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9682 - mae: 2.0541

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9486 - mae: 2.0520

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9307 - mae: 2.0492

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9140 - mae: 2.0478

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 6.9372 - mae: 2.0509 - val_loss: 6.3537 - val_mae: 1.9909

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 5.8472 - mae: 1.9660

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.3482 - mae: 1.8959

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.5272 - mae: 2.0764

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.0444 - mae: 1.9626

 22/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5313 - mae: 1.8867

 28/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.5049 - mae: 1.9900

 34/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0971 - mae: 1.9245

 40/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1353 - mae: 1.9140

 45/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0729 - mae: 1.9024

 48/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.3781 - mae: 1.9403

 52/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.1951 - mae: 1.9243

 57/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.1402 - mae: 1.9185

 62/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.3910 - mae: 1.9371

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.3350 - mae: 1.9469

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3006 - mae: 1.9318

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.6796 - mae: 1.9872

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8578 - mae: 2.0197

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.0534 - mae: 2.0575

 93/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.9247 - mae: 2.0389

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8464 - mae: 2.0163

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.7957 - mae: 2.0102

108/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.7214 - mae: 2.0001

113/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.7245 - mae: 2.0056

119/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.9184 - mae: 2.0146

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8208 - mae: 2.0048

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8330 - mae: 2.0111

134/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8429 - mae: 2.0191

140/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8202 - mae: 2.0159

145/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.8394 - mae: 2.0225

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8456 - mae: 2.0263

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8343 - mae: 2.0307

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8887 - mae: 2.0407

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8681 - mae: 2.0389

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.7974 - mae: 2.0246

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8667 - mae: 2.0318

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9032 - mae: 2.0374

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.8897 - mae: 2.0367

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0499 - mae: 2.0552

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0821 - mae: 2.0614

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0126 - mae: 2.0518

208/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0118 - mae: 2.0536

213/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9854 - mae: 2.0521

218/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0057 - mae: 2.0555

223/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9389 - mae: 2.0446

228/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9439 - mae: 2.0481

233/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.9856 - mae: 2.0539

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 7.0316 - mae: 2.0639

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9473 - mae: 2.0526

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.9439 - mae: 2.0534

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8871 - mae: 2.0457

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8913 - mae: 2.0425

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8570 - mae: 2.0397

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8524 - mae: 2.0354

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8098 - mae: 2.0294

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.8214 - mae: 2.0304

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7589 - mae: 2.0185

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7364 - mae: 2.0152

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7434 - mae: 2.0179

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.7109 - mae: 2.0162

304/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6954 - mae: 2.0154

308/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6977 - mae: 2.0165

313/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6758 - mae: 2.0156

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6220 - mae: 2.0076

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.6193 - mae: 2.0053

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.5738 - mae: 1.9990

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.5965 - mae: 2.0040

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5843 - mae: 2.0015

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5994 - mae: 2.0050

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5954 - mae: 2.0023

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5994 - mae: 2.0016

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5644 - mae: 1.9957

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5539 - mae: 1.9953

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5833 - mae: 1.9968

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5538 - mae: 1.9910

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5434 - mae: 1.9905

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5181 - mae: 1.9864

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5823 - mae: 1.9959

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5792 - mae: 1.9942

400/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5888 - mae: 1.9972

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5719 - mae: 1.9944

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.5715 - mae: 1.9937

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6170 - mae: 2.0001

421/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6248 - mae: 1.9995

427/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.6614 - mae: 2.0046

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6870 - mae: 2.0089

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.7060 - mae: 2.0120

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.7054 - mae: 2.0108

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6941 - mae: 2.0104

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6908 - mae: 2.0112

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6828 - mae: 2.0112

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6949 - mae: 2.0134

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.7028 - mae: 2.0155

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7058 - mae: 2.0145

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7292 - mae: 2.0188

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7308 - mae: 2.0199

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7149 - mae: 2.0176

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7070 - mae: 2.0176

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6753 - mae: 2.0137

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6434 - mae: 2.0092

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.6704 - mae: 2.0135 - val_loss: 6.3102 - val_mae: 1.9829

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 6.4801 - mae: 2.1864

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0658 - mae: 1.8575

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8873 - mae: 1.9658

 20/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4019 - mae: 1.8668

 26/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6094 - mae: 2.0151

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2776 - mae: 1.9574

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2859 - mae: 1.9460

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0552 - mae: 1.9154

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3668 - mae: 1.9578

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2060 - mae: 1.9427

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3624 - mae: 1.9466

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.2668 - mae: 1.9346

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3186 - mae: 1.9572

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.2855 - mae: 1.9458

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6954 - mae: 2.0058

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.9039 - mae: 2.0387

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 7.0671 - mae: 2.0765

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.9707 - mae: 2.0607

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8321 - mae: 2.0328

104/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.7606 - mae: 2.0260

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6976 - mae: 2.0154

115/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.6641 - mae: 2.0136

120/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8369 - mae: 2.0238

126/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.7576 - mae: 2.0150

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.8180 - mae: 2.0311

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7619 - mae: 2.0244

144/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7778 - mae: 2.0330

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7874 - mae: 2.0362

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.7334 - mae: 2.0331

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8211 - mae: 2.0516

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8071 - mae: 2.0469

174/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8092 - mae: 2.0456

180/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8076 - mae: 2.0427

186/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8046 - mae: 2.0447

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9443 - mae: 2.0624

198/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9327 - mae: 2.0606

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.9085 - mae: 2.0595

210/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.8915 - mae: 2.0577

216/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9093 - mae: 2.0613

222/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8375 - mae: 2.0491

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8451 - mae: 2.0534

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8809 - mae: 2.0592

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.9166 - mae: 2.0663

243/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8457 - mae: 2.0573

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8358 - mae: 2.0560

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8428 - mae: 2.0565

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.8151 - mae: 2.0511

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7840 - mae: 2.0422

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7763 - mae: 2.0413

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7520 - mae: 2.0383

271/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7515 - mae: 2.0357

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7208 - mae: 2.0319

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.7262 - mae: 2.0321

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6635 - mae: 2.0197

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6434 - mae: 2.0159

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6475 - mae: 2.0174

300/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.6069 - mae: 2.0134

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5778 - mae: 2.0116

311/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5816 - mae: 2.0132

317/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5359 - mae: 2.0067

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.5150 - mae: 2.0013

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4790 - mae: 1.9980

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4934 - mae: 1.9986

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4865 - mae: 1.9991

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4920 - mae: 1.9972

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4973 - mae: 1.9970

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4613 - mae: 1.9914

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4472 - mae: 1.9904

370/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4756 - mae: 1.9915

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4405 - mae: 1.9848

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4327 - mae: 1.9847

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4297 - mae: 1.9838

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4653 - mae: 1.9895

398/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4860 - mae: 1.9917

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4605 - mae: 1.9861

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.4644 - mae: 1.9871

416/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5038 - mae: 1.9933

422/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.5116 - mae: 1.9925

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5502 - mae: 1.9971

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5534 - mae: 1.9979

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5668 - mae: 1.9995

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5721 - mae: 1.9997

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5629 - mae: 1.9990

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5584 - mae: 2.0004

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5451 - mae: 1.9981

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5415 - mae: 1.9979

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5427 - mae: 1.9989

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5487 - mae: 2.0008

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5659 - mae: 2.0029

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5806 - mae: 2.0035

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6042 - mae: 2.0079

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5928 - mae: 2.0066

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5805 - mae: 2.0049

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5838 - mae: 2.0049

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5818 - mae: 2.0050

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5852 - mae: 2.0071

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5592 - mae: 2.0033

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5483 - mae: 2.0015

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5309 - mae: 1.9999

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5546 - mae: 2.0029

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 6.5546 - mae: 2.0029 - val_loss: 6.2893 - val_mae: 1.9718

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 5.6582 - mae: 2.0265

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 4.6706 - mae: 1.7918

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6941 - mae: 1.9286

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5219 - mae: 1.8730

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.6326 - mae: 1.9898

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2732 - mae: 1.9494

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8889 - mae: 1.8960

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0796 - mae: 1.9124

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4548 - mae: 1.9692

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.1903 - mae: 1.9399

 60/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4196 - mae: 1.9541

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3073 - mae: 1.9481

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2483 - mae: 1.9398

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.5964 - mae: 1.9936

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.7339 - mae: 2.0236

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.8360 - mae: 2.0438

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6731 - mae: 2.0081

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6315 - mae: 1.9945

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5266 - mae: 1.9768

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4667 - mae: 1.9695

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5892 - mae: 1.9781

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5358 - mae: 1.9710

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5601 - mae: 1.9789

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5269 - mae: 1.9804

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5483 - mae: 1.9887

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5355 - mae: 1.9925

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4848 - mae: 1.9891

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5895 - mae: 2.0079

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5543 - mae: 1.9986

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5529 - mae: 1.9970

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6113 - mae: 2.0038

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6043 - mae: 2.0045

194/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6983 - mae: 2.0157

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6814 - mae: 2.0137

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6485 - mae: 2.0075

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6491 - mae: 2.0106

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6897 - mae: 2.0175

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6358 - mae: 2.0088

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7072 - mae: 2.0178

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.7065 - mae: 2.0216

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6693 - mae: 2.0174

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6537 - mae: 2.0152

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5866 - mae: 2.0034

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.6232 - mae: 2.0080

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5877 - mae: 2.0014

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5825 - mae: 1.9986

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5668 - mae: 1.9960

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4979 - mae: 1.9831

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4811 - mae: 1.9803

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4716 - mae: 1.9815

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4559 - mae: 1.9817

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4355 - mae: 1.9787

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.4072 - mae: 1.9761

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3894 - mae: 1.9712

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3381 - mae: 1.9626

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3539 - mae: 1.9675

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3380 - mae: 1.9635

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3204 - mae: 1.9611

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3396 - mae: 1.9616

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3315 - mae: 1.9586

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3207 - mae: 1.9581

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3448 - mae: 1.9592

374/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3286 - mae: 1.9575

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3000 - mae: 1.9523

386/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2784 - mae: 1.9487

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3217 - mae: 1.9562

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3390 - mae: 1.9569

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3227 - mae: 1.9533

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.3101 - mae: 1.9515

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3628 - mae: 1.9591

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3369 - mae: 1.9543

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3463 - mae: 1.9544

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3922 - mae: 1.9616

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4138 - mae: 1.9636

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4099 - mae: 1.9630

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4143 - mae: 1.9642

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4194 - mae: 1.9665

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3973 - mae: 1.9643

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3970 - mae: 1.9650

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3966 - mae: 1.9655

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4097 - mae: 1.9679

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4253 - mae: 1.9687

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4557 - mae: 1.9739

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4358 - mae: 1.9714

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4207 - mae: 1.9691

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4229 - mae: 1.9710

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3807 - mae: 1.9641

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3690 - mae: 1.9643

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.3851 - mae: 1.9658 - val_loss: 6.1656 - val_mae: 1.9474

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 5.8198 - mae: 2.1360

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.5547 - mae: 1.8102

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6514 - mae: 1.9472

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2976 - mae: 1.8400

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.4379 - mae: 1.9681

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0277 - mae: 1.9140

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6428 - mae: 1.8614

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7694 - mae: 1.8677

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9267 - mae: 1.8985

 52/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0166 - mae: 1.9054

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9970 - mae: 1.9029

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0088 - mae: 1.8908

 70/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8943 - mae: 1.8825

 76/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.3495 - mae: 1.9488

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.5990 - mae: 1.9901

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.7621 - mae: 2.0299

 93/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.6240 - mae: 2.0034

 99/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4712 - mae: 1.9698

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4969 - mae: 1.9766

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3786 - mae: 1.9546

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3549 - mae: 1.9557

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4636 - mae: 1.9600

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4010 - mae: 1.9515

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4060 - mae: 1.9561

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3815 - mae: 1.9563

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4018 - mae: 1.9621

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3833 - mae: 1.9654

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3174 - mae: 1.9573

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4213 - mae: 1.9752

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3854 - mae: 1.9668

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3985 - mae: 1.9685

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4385 - mae: 1.9710

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4390 - mae: 1.9732

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5518 - mae: 1.9898

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5381 - mae: 1.9893

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4959 - mae: 1.9826

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4856 - mae: 1.9835

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5196 - mae: 1.9904

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4566 - mae: 1.9788

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4555 - mae: 1.9822

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5350 - mae: 1.9936

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.5125 - mae: 1.9906

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4545 - mae: 1.9833

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4533 - mae: 1.9824

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4297 - mae: 1.9746

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4350 - mae: 1.9763

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4372 - mae: 1.9718

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3950 - mae: 1.9668

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4053 - mae: 1.9694

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3415 - mae: 1.9555

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3290 - mae: 1.9551

299/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2979 - mae: 1.9520

305/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2887 - mae: 1.9535

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2866 - mae: 1.9531

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2572 - mae: 1.9492

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2394 - mae: 1.9448

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2075 - mae: 1.9420

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.2036 - mae: 1.9395

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1874 - mae: 1.9379

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1811 - mae: 1.9347

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1897 - mae: 1.9353

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1601 - mae: 1.9325

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1476 - mae: 1.9316

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1797 - mae: 1.9338

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1420 - mae: 1.9278

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1320 - mae: 1.9266

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1550 - mae: 1.9304

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1753 - mae: 1.9332

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1726 - mae: 1.9327

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1387 - mae: 1.9265

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1727 - mae: 1.9309

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.1811 - mae: 1.9323

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2138 - mae: 1.9354

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2499 - mae: 1.9406

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2661 - mae: 1.9427

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2686 - mae: 1.9419

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2785 - mae: 1.9460

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2533 - mae: 1.9434

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2515 - mae: 1.9436

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2445 - mae: 1.9431

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2550 - mae: 1.9453

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2573 - mae: 1.9447

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2845 - mae: 1.9474

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.3077 - mae: 1.9517

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2874 - mae: 1.9492

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2872 - mae: 1.9486

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2804 - mae: 1.9498

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2531 - mae: 1.9458

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2411 - mae: 1.9460

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 6.2541 - mae: 1.9469 - val_loss: 6.0359 - val_mae: 1.9299

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 5.2662 - mae: 2.0305

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.4459 - mae: 1.7760

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4354 - mae: 1.9105

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1451 - mae: 1.8196

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.2885 - mae: 1.9485

 32/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9010 - mae: 1.8959

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9304 - mae: 1.8872

 44/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8112 - mae: 1.8758

 50/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0671 - mae: 1.9099

 56/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8930 - mae: 1.8868

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9990 - mae: 1.8822

 68/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8885 - mae: 1.8804

 74/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1144 - mae: 1.9151

 80/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.4428 - mae: 1.9639

 86/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5382 - mae: 1.9949

 92/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.5118 - mae: 1.9841

 98/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3613 - mae: 1.9533

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3303 - mae: 1.9553

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2503 - mae: 1.9365

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1918 - mae: 1.9304

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.3078 - mae: 1.9386

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2729 - mae: 1.9351

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2227 - mae: 1.9316

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2117 - mae: 1.9312

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2077 - mae: 1.9327

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2128 - mae: 1.9362

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2072 - mae: 1.9370

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2365 - mae: 1.9448

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1911 - mae: 1.9344

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2439 - mae: 1.9379

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3031 - mae: 1.9481

189/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3065 - mae: 1.9516

195/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3543 - mae: 1.9566

201/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3712 - mae: 1.9596

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3652 - mae: 1.9598

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3149 - mae: 1.9528

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3382 - mae: 1.9545

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2931 - mae: 1.9491

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3640 - mae: 1.9595

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.4008 - mae: 1.9683

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3291 - mae: 1.9598

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.3197 - mae: 1.9584

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2884 - mae: 1.9500

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2897 - mae: 1.9499

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2985 - mae: 1.9477

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2554 - mae: 1.9427

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.2426 - mae: 1.9409

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1832 - mae: 1.9292

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1758 - mae: 1.9293

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1679 - mae: 1.9312

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1322 - mae: 1.9264

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1397 - mae: 1.9281

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1323 - mae: 1.9275

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.1126 - mae: 1.9229

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0741 - mae: 1.9161

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0896 - mae: 1.9205

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0579 - mae: 1.9144

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0495 - mae: 1.9144

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0305 - mae: 1.9123

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0571 - mae: 1.9141

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0511 - mae: 1.9125

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0442 - mae: 1.9132

364/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0289 - mae: 1.9108

368/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0597 - mae: 1.9125

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0504 - mae: 1.9120

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0261 - mae: 1.9083

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6.0258 - mae: 1.9091

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0064 - mae: 1.9054

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9989 - mae: 1.9047

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0358 - mae: 1.9111

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0455 - mae: 1.9133

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0549 - mae: 1.9131

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0627 - mae: 1.9143

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0379 - mae: 1.9091

406/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0242 - mae: 1.9068

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0371 - mae: 1.9085

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0791 - mae: 1.9162

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0728 - mae: 1.9156

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6.0809 - mae: 1.9141

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1078 - mae: 1.9174

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1214 - mae: 1.9197

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1415 - mae: 1.9217

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1338 - mae: 1.9209

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1418 - mae: 1.9215

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1346 - mae: 1.9216

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1332 - mae: 1.9226

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1347 - mae: 1.9240

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1299 - mae: 1.9238

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1230 - mae: 1.9220

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1314 - mae: 1.9234

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1523 - mae: 1.9285

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1319 - mae: 1.9234

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1621 - mae: 1.9279

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1865 - mae: 1.9323

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1885 - mae: 1.9323

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1833 - mae: 1.9319

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1835 - mae: 1.9324

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1766 - mae: 1.9310

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1766 - mae: 1.9326

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1548 - mae: 1.9292

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1327 - mae: 1.9255

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1307 - mae: 1.9278

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - loss: 6.1458 - mae: 1.9292 - val_loss: 5.9680 - val_mae: 1.9168

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 24s 47ms/step - loss: 5.3541 - mae: 2.0440

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.7751 - mae: 1.8652

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.9911 - mae: 2.0251

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4642 - mae: 1.8835

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.9363 - mae: 1.7993

 24/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 6.1281 - mae: 1.9389

 29/522 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - loss: 5.9972 - mae: 1.9322

 34/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 5.5510 - mae: 1.8443

 39/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.7129 - mae: 1.8620

 44/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.6754 - mae: 1.8587

 49/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 5.9750 - mae: 1.8960

 55/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.8638 - mae: 1.8893

 61/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.9203 - mae: 1.8779

 67/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.8315 - mae: 1.8791

 71/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.7637 - mae: 1.8644

 76/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 6.0852 - mae: 1.9134

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3320 - mae: 1.9537

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.3998 - mae: 1.9790

 91/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.4115 - mae: 1.9760

 94/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2858 - mae: 1.9547

 98/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2266 - mae: 1.9390

 99/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.1824 - mae: 1.9320

103/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2064 - mae: 1.9382

106/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.2182 - mae: 1.9350

111/522 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 6.0966 - mae: 1.9149

117/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.2468 - mae: 1.9268

123/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.1480 - mae: 1.9165

129/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0913 - mae: 1.9060

135/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0597 - mae: 1.9007

141/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0116 - mae: 1.8929

147/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0382 - mae: 1.9014

153/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 6.0640 - mae: 1.9105

158/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.0736 - mae: 1.9130

164/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 6.1053 - mae: 1.9203

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.0618 - mae: 1.9106

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1114 - mae: 1.9146

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1686 - mae: 1.9229

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1428 - mae: 1.9186

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2534 - mae: 1.9348

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2492 - mae: 1.9357

204/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2434 - mae: 1.9349

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2417 - mae: 1.9332

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2145 - mae: 1.9327

220/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2064 - mae: 1.9294

226/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.1638 - mae: 1.9248

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2290 - mae: 1.9342

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2777 - mae: 1.9453

243/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 6.2141 - mae: 1.9374

249/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.2024 - mae: 1.9354

255/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1417 - mae: 1.9265

261/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1863 - mae: 1.9306

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1441 - mae: 1.9226

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1539 - mae: 1.9232

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.1365 - mae: 1.9204

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0632 - mae: 1.9051

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0457 - mae: 1.9029

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0353 - mae: 1.9041

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0304 - mae: 1.9052

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0293 - mae: 1.9056

312/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 6.0104 - mae: 1.9044

318/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.9902 - mae: 1.9004

323/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.9810 - mae: 1.8992

328/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.9507 - mae: 1.8958

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9608 - mae: 1.8980

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9293 - mae: 1.8913

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9279 - mae: 1.8913

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9415 - mae: 1.8905

356/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9413 - mae: 1.8912

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9335 - mae: 1.8915

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9450 - mae: 1.8909

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9306 - mae: 1.8894

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.9053 - mae: 1.8848

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9105 - mae: 1.8859

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.8956 - mae: 1.8838

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9108 - mae: 1.8861

392/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9343 - mae: 1.8913

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9501 - mae: 1.8924

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9265 - mae: 1.8879

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9065 - mae: 1.8853

413/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9401 - mae: 1.8904

418/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9620 - mae: 1.8952

424/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.9608 - mae: 1.8925

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0008 - mae: 1.8986

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0233 - mae: 1.9000

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0275 - mae: 1.8996

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0366 - mae: 1.9035

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0182 - mae: 1.9015

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0149 - mae: 1.9015

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0118 - mae: 1.9020

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0153 - mae: 1.9025

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0329 - mae: 1.9057

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0422 - mae: 1.9053

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0700 - mae: 1.9103

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0679 - mae: 1.9103

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0543 - mae: 1.9089

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0582 - mae: 1.9085

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0530 - mae: 1.9096

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0208 - mae: 1.9044

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.0108 - mae: 1.9043

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 6.0303 - mae: 1.9073 - val_loss: 6.0051 - val_mae: 1.9293

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 5.2779 - mae: 2.0758

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.3962 - mae: 1.7761

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3942 - mae: 1.9112

 18/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.2669 - mae: 1.8496

 23/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0648 - mae: 1.9199

 28/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9253 - mae: 1.9034

 33/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6192 - mae: 1.8548

 38/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8031 - mae: 1.8736

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.5809 - mae: 1.8405

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0467 - mae: 1.9043

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7938 - mae: 1.8739

 58/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8060 - mae: 1.8785

 64/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8068 - mae: 1.8655

 70/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7055 - mae: 1.8567

 76/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1121 - mae: 1.9192

 81/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3158 - mae: 1.9535

 86/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3815 - mae: 1.9798

 91/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.3807 - mae: 1.9761

 97/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1732 - mae: 1.9404

103/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1835 - mae: 1.9426

109/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1239 - mae: 1.9286

115/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0430 - mae: 1.9157

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1401 - mae: 1.9225

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0587 - mae: 1.9089

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0338 - mae: 1.9074

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9691 - mae: 1.8957

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9522 - mae: 1.8916

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9350 - mae: 1.8929

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8650 - mae: 1.8845

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9769 - mae: 1.9016

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9538 - mae: 1.8940

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9782 - mae: 1.8962

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0176 - mae: 1.8987

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0173 - mae: 1.8990

193/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1213 - mae: 1.9149

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1267 - mae: 1.9171

205/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.1240 - mae: 1.9167

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.1065 - mae: 1.9142

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.1184 - mae: 1.9188

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.0675 - mae: 1.9078

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0790 - mae: 1.9140

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.1493 - mae: 1.9243

240/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.1388 - mae: 1.9214

246/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0886 - mae: 1.9172

252/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0668 - mae: 1.9137

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0666 - mae: 1.9103

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.0614 - mae: 1.9092

267/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.0333 - mae: 1.9041

273/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.0433 - mae: 1.9052

279/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 6.0190 - mae: 1.9017

285/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9473 - mae: 1.8865

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9312 - mae: 1.8844

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9155 - mae: 1.8849

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9128 - mae: 1.8869

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8983 - mae: 1.8855

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8944 - mae: 1.8859

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8812 - mae: 1.8831

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8395 - mae: 1.8775

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8442 - mae: 1.8802

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8175 - mae: 1.8746

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8034 - mae: 1.8731

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8193 - mae: 1.8721

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8175 - mae: 1.8731

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8127 - mae: 1.8734

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8336 - mae: 1.8754

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8031 - mae: 1.8698

380/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8041 - mae: 1.8699

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7835 - mae: 1.8669

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8323 - mae: 1.8760

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8259 - mae: 1.8744

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8101 - mae: 1.8705

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8003 - mae: 1.8692

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8460 - mae: 1.8774

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8234 - mae: 1.8737

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8657 - mae: 1.8770

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8716 - mae: 1.8788

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8987 - mae: 1.8816

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8997 - mae: 1.8809

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8873 - mae: 1.8803

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8775 - mae: 1.8799

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8831 - mae: 1.8825

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8672 - mae: 1.8794

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8774 - mae: 1.8822

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8854 - mae: 1.8819

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.9277 - mae: 1.8878

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.9352 - mae: 1.8891

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.9178 - mae: 1.8873

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.9205 - mae: 1.8876

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.9064 - mae: 1.8861

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8840 - mae: 1.8825

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8990 - mae: 1.8863

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.8990 - mae: 1.8863 - val_loss: 6.0180 - val_mae: 1.9343

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 4.8084 - mae: 1.9717

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 4.2118 - mae: 1.7624

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2311 - mae: 1.9001

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1078 - mae: 1.8404

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 6.0462 - mae: 1.9258

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7645 - mae: 1.8957

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3222 - mae: 1.8207

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5129 - mae: 1.8337

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9317 - mae: 1.8905

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7750 - mae: 1.8758

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8250 - mae: 1.8622

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7394 - mae: 1.8646

 73/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7570 - mae: 1.8608

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0904 - mae: 1.9151

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1875 - mae: 1.9429

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2642 - mae: 1.9562

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0684 - mae: 1.9238

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1217 - mae: 1.9328

105/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1067 - mae: 1.9265

110/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0101 - mae: 1.9109

116/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9393 - mae: 1.9006

122/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0517 - mae: 1.9091

128/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0041 - mae: 1.9021

134/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9343 - mae: 1.8938

140/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8640 - mae: 1.8814

146/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8586 - mae: 1.8788

152/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8584 - mae: 1.8801

158/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8665 - mae: 1.8801

164/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8751 - mae: 1.8820

170/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8462 - mae: 1.8763

176/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8902 - mae: 1.8800

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9559 - mae: 1.8885

188/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9663 - mae: 1.8910

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0277 - mae: 1.8999

200/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0178 - mae: 1.8987

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9976 - mae: 1.8934

212/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9899 - mae: 1.8943

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0136 - mae: 1.9000

224/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9728 - mae: 1.8920

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0520 - mae: 1.9035

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0586 - mae: 1.9075

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0235 - mae: 1.9014

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0208 - mae: 1.9037

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9695 - mae: 1.8954

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 6.0017 - mae: 1.8959

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9656 - mae: 1.8908

272/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9694 - mae: 1.8895

278/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9222 - mae: 1.8812

284/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8867 - mae: 1.8740

290/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8623 - mae: 1.8693

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8536 - mae: 1.8703

302/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8386 - mae: 1.8706

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8297 - mae: 1.8701

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.8288 - mae: 1.8714

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7834 - mae: 1.8623

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7765 - mae: 1.8620

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7812 - mae: 1.8652

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7481 - mae: 1.8600

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7530 - mae: 1.8622

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7558 - mae: 1.8600

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7505 - mae: 1.8593

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7543 - mae: 1.8621

367/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7583 - mae: 1.8599

373/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7529 - mae: 1.8601

379/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7400 - mae: 1.8589

385/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7218 - mae: 1.8556

391/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7692 - mae: 1.8645

397/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7629 - mae: 1.8619

403/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7511 - mae: 1.8594

409/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7374 - mae: 1.8583

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7735 - mae: 1.8640

421/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7911 - mae: 1.8659

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8084 - mae: 1.8665

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8308 - mae: 1.8698

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8382 - mae: 1.8695

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8347 - mae: 1.8682

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8195 - mae: 1.8679

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8195 - mae: 1.8695

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8157 - mae: 1.8701

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8313 - mae: 1.8712

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8530 - mae: 1.8757

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8473 - mae: 1.8734

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8781 - mae: 1.8778

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8899 - mae: 1.8805

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8755 - mae: 1.8782

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8604 - mae: 1.8761

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8413 - mae: 1.8735

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8184 - mae: 1.8701

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8296 - mae: 1.8728

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.8296 - mae: 1.8728 - val_loss: 6.0689 - val_mae: 1.9487

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - loss: 5.3125 - mae: 2.0306

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 3.9335 - mae: 1.6848

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2068 - mae: 1.8696

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0801 - mae: 1.8002

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.9681 - mae: 1.8785

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7122 - mae: 1.8610

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2877 - mae: 1.7960

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4707 - mae: 1.8051

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8934 - mae: 1.8719

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7805 - mae: 1.8661

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.7851 - mae: 1.8526

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7101 - mae: 1.8557

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7101 - mae: 1.8534

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0555 - mae: 1.9106

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.1542 - mae: 1.9393

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.2451 - mae: 1.9526

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0261 - mae: 1.9107

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0257 - mae: 1.9088

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9843 - mae: 1.9002

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9028 - mae: 1.8899

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 6.0122 - mae: 1.8980

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9331 - mae: 1.8852

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9053 - mae: 1.8823

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8221 - mae: 1.8680

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8071 - mae: 1.8645

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7870 - mae: 1.8666

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7101 - mae: 1.8569

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8089 - mae: 1.8746

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7851 - mae: 1.8694

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8143 - mae: 1.8721

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8627 - mae: 1.8761

187/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8687 - mae: 1.8774

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9751 - mae: 1.8938

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9643 - mae: 1.8923

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9558 - mae: 1.8915

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9410 - mae: 1.8867

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9592 - mae: 1.8910

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9100 - mae: 1.8813

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9243 - mae: 1.8862

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9998 - mae: 1.8963

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9796 - mae: 1.8932

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9291 - mae: 1.8879

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9229 - mae: 1.8867

259/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9079 - mae: 1.8792

265/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9219 - mae: 1.8824

271/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9139 - mae: 1.8782

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8815 - mae: 1.8735

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8438 - mae: 1.8670

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7930 - mae: 1.8569

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7913 - mae: 1.8584

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7562 - mae: 1.8544

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7462 - mae: 1.8551

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7465 - mae: 1.8566

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7282 - mae: 1.8520

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7060 - mae: 1.8486

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7030 - mae: 1.8502

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6741 - mae: 1.8448

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6847 - mae: 1.8473

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6656 - mae: 1.8422

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6663 - mae: 1.8419

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6708 - mae: 1.8435

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6812 - mae: 1.8431

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6640 - mae: 1.8416

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6479 - mae: 1.8401

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6283 - mae: 1.8369

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6666 - mae: 1.8444

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6552 - mae: 1.8404

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6450 - mae: 1.8387

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6390 - mae: 1.8384

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6894 - mae: 1.8470

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6669 - mae: 1.8427

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6980 - mae: 1.8455

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7286 - mae: 1.8493

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7501 - mae: 1.8505

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7424 - mae: 1.8495

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7475 - mae: 1.8501

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7404 - mae: 1.8505

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7366 - mae: 1.8511

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7203 - mae: 1.8484

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7340 - mae: 1.8529

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7274 - mae: 1.8507

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7418 - mae: 1.8532

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7364 - mae: 1.8529

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7600 - mae: 1.8562

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7587 - mae: 1.8549

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7808 - mae: 1.8578

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7954 - mae: 1.8606

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7782 - mae: 1.8591

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7818 - mae: 1.8596

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7817 - mae: 1.8608

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7532 - mae: 1.8565

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7344 - mae: 1.8533

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.7279 - mae: 1.8547

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 5.7410 - mae: 1.8561 - val_loss: 6.0363 - val_mae: 1.9465

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - loss: 5.3700 - mae: 2.0675

  6/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 3.9630 - mae: 1.6700

 11/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.4697 - mae: 1.9316

 16/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.9255 - mae: 1.7722

 21/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 4.5906 - mae: 1.7240

 26/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.8052 - mae: 1.8645

 32/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5310 - mae: 1.8362

 37/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.2266 - mae: 1.7968

 42/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.3655 - mae: 1.8011

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8803 - mae: 1.8756

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6359 - mae: 1.8552

 59/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6252 - mae: 1.8455

 65/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6284 - mae: 1.8416

 71/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.5721 - mae: 1.8382

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9214 - mae: 1.8963

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.1553 - mae: 1.9402

 89/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.2027 - mae: 1.9538

 95/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0757 - mae: 1.9244

101/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 6.0214 - mae: 1.9111

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9955 - mae: 1.9063

112/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9175 - mae: 1.8967

118/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 6.0686 - mae: 1.9108

124/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9446 - mae: 1.8912

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.9535 - mae: 1.8918

136/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.8515 - mae: 1.8720

142/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7794 - mae: 1.8583

148/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7811 - mae: 1.8623

154/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7358 - mae: 1.8583

160/522 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 5.7913 - mae: 1.8699

166/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7695 - mae: 1.8672

172/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6870 - mae: 1.8527

178/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8260 - mae: 1.8741

184/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8476 - mae: 1.8766

190/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8569 - mae: 1.8809

196/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9186 - mae: 1.8899

202/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.9156 - mae: 1.8891

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9468 - mae: 1.8919

214/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8931 - mae: 1.8843

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9154 - mae: 1.8877

226/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8716 - mae: 1.8825

232/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9245 - mae: 1.8882

238/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9718 - mae: 1.8984

244/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9167 - mae: 1.8938

250/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.9020 - mae: 1.8925

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8943 - mae: 1.8852

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8797 - mae: 1.8817

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8571 - mae: 1.8769

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8622 - mae: 1.8777

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8368 - mae: 1.8736

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7692 - mae: 1.8585

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7522 - mae: 1.8575

296/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7528 - mae: 1.8597

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7524 - mae: 1.8617

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7346 - mae: 1.8597

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7182 - mae: 1.8587

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6997 - mae: 1.8549

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.7060 - mae: 1.8564

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6630 - mae: 1.8491

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6738 - mae: 1.8512

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6391 - mae: 1.8449

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6487 - mae: 1.8471

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6493 - mae: 1.8446

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6415 - mae: 1.8434

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6483 - mae: 1.8457

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.6517 - mae: 1.8439

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6380 - mae: 1.8425

376/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6165 - mae: 1.8382

382/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5994 - mae: 1.8353

388/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6220 - mae: 1.8407

394/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6274 - mae: 1.8396

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6324 - mae: 1.8416

404/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6045 - mae: 1.8352

410/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6104 - mae: 1.8382

415/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.6298 - mae: 1.8415

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6146 - mae: 1.8392

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6639 - mae: 1.8430

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6742 - mae: 1.8448

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6844 - mae: 1.8447

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6870 - mae: 1.8437

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6829 - mae: 1.8452

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6643 - mae: 1.8432

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6650 - mae: 1.8441

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6706 - mae: 1.8455

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6772 - mae: 1.8481

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6835 - mae: 1.8472

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6927 - mae: 1.8489

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7272 - mae: 1.8546

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7052 - mae: 1.8521

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.7049 - mae: 1.8524

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6860 - mae: 1.8505

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6613 - mae: 1.8460

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.6666 - mae: 1.8480

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.6653 - mae: 1.8479 - val_loss: 6.0528 - val_mae: 1.9407

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 5.2790 - mae: 2.0197

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 3.4802 - mae: 1.5927

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.6041 - mae: 1.7602

 18/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 4.5678 - mae: 1.7028

 23/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 5.2630 - mae: 1.7717

 29/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.4646 - mae: 1.8308

 35/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 4.9989 - mae: 1.7447

 41/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.1938 - mae: 1.7620

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3885 - mae: 1.8060

 53/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4245 - mae: 1.8165

 59/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.4165 - mae: 1.8169

 65/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3809 - mae: 1.8042

 71/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.3520 - mae: 1.8049

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6609 - mae: 1.8552

 82/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8670 - mae: 1.8938

 87/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.9786 - mae: 1.9207

 92/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.8949 - mae: 1.9050

 97/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7246 - mae: 1.8702

102/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7423 - mae: 1.8716

107/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7427 - mae: 1.8720

112/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6849 - mae: 1.8648

116/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.6235 - mae: 1.8547

120/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 5.7922 - mae: 1.8718

124/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7165 - mae: 1.8599

128/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.7084 - mae: 1.8575

132/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6997 - mae: 1.8588

136/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.6300 - mae: 1.8444

140/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5758 - mae: 1.8358

144/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5531 - mae: 1.8307

148/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5714 - mae: 1.8342

152/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5546 - mae: 1.8313

156/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5070 - mae: 1.8257

160/522 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 5.5928 - mae: 1.8392

164/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.5803 - mae: 1.8405

168/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.5798 - mae: 1.8364

172/522 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 5.5095 - mae: 1.8253

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.6244 - mae: 1.8433

182/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.6874 - mae: 1.8520

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.6577 - mae: 1.8473

192/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.7725 - mae: 1.8636

197/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.7956 - mae: 1.8708

203/522 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 5.7585 - mae: 1.8623

209/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7622 - mae: 1.8586

215/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7455 - mae: 1.8584

221/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7315 - mae: 1.8543

227/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.6941 - mae: 1.8505

232/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7615 - mae: 1.8562

238/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.8227 - mae: 1.8689

244/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7675 - mae: 1.8636

250/522 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 5.7602 - mae: 1.8640

256/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.7479 - mae: 1.8565

262/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.7386 - mae: 1.8543

268/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.7110 - mae: 1.8485

274/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.7245 - mae: 1.8509

280/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.7011 - mae: 1.8473

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.6357 - mae: 1.8333

292/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.6129 - mae: 1.8312

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.6100 - mae: 1.8318

303/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.6093 - mae: 1.8348

309/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5932 - mae: 1.8337

315/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5838 - mae: 1.8335

321/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5727 - mae: 1.8306

327/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5296 - mae: 1.8238

333/522 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 5.5362 - mae: 1.8263

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5079 - mae: 1.8208

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5022 - mae: 1.8207

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5140 - mae: 1.8201

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 5.5089 - mae: 1.8186

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5008 - mae: 1.8173

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5121 - mae: 1.8195

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.4857 - mae: 1.8143

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.4911 - mae: 1.8156

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.4961 - mae: 1.8167

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5003 - mae: 1.8175

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5223 - mae: 1.8214

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.4999 - mae: 1.8171

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5190 - mae: 1.8204

417/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5240 - mae: 1.8212

423/522 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 5.5416 - mae: 1.8219

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5831 - mae: 1.8263

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5922 - mae: 1.8246

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5766 - mae: 1.8226

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5747 - mae: 1.8231

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5788 - mae: 1.8255

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5612 - mae: 1.8219

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5807 - mae: 1.8274

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5985 - mae: 1.8307

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6126 - mae: 1.8339

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5905 - mae: 1.8289

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6018 - mae: 1.8315

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6401 - mae: 1.8381

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6187 - mae: 1.8354

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6162 - mae: 1.8350

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6130 - mae: 1.8358

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5789 - mae: 1.8300

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5625 - mae: 1.8279

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.5786 - mae: 1.8312

522/522 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - loss: 5.5786 - mae: 1.8312 - val_loss: 6.1370 - val_mae: 1.9548

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 4.6214 - mae: 1.9106

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 3.9432 - mae: 1.6756

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8828 - mae: 1.8326

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8141 - mae: 1.7875

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5782 - mae: 1.8426

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3821 - mae: 1.8382

 36/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0954 - mae: 1.7863

 42/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1315 - mae: 1.7749

 48/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6677 - mae: 1.8540

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4196 - mae: 1.8269

 60/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5453 - mae: 1.8301

 66/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4127 - mae: 1.8161

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4002 - mae: 1.8092

 77/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6771 - mae: 1.8562

 83/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8710 - mae: 1.8973

 89/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8721 - mae: 1.9032

 95/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8063 - mae: 1.8855

101/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7715 - mae: 1.8754

107/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7617 - mae: 1.8754

113/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7091 - mae: 1.8659

119/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8464 - mae: 1.8759

125/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7356 - mae: 1.8549

131/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7529 - mae: 1.8604

137/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6570 - mae: 1.8449

143/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6245 - mae: 1.8385

149/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5862 - mae: 1.8329

155/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5765 - mae: 1.8363

161/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6122 - mae: 1.8437

167/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6164 - mae: 1.8452

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5899 - mae: 1.8407

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6919 - mae: 1.8556

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6645 - mae: 1.8495

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6978 - mae: 1.8590

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.8042 - mae: 1.8726

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7716 - mae: 1.8646

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7842 - mae: 1.8662

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7682 - mae: 1.8660

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7406 - mae: 1.8605

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6993 - mae: 1.8568

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7555 - mae: 1.8641

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7943 - mae: 1.8705

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7339 - mae: 1.8648

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7430 - mae: 1.8656

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7249 - mae: 1.8579

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7390 - mae: 1.8608

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7359 - mae: 1.8554

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6921 - mae: 1.8506

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6746 - mae: 1.8488

286/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6202 - mae: 1.8364

291/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6089 - mae: 1.8361

297/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5944 - mae: 1.8357

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5926 - mae: 1.8381

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5681 - mae: 1.8357

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5609 - mae: 1.8347

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5413 - mae: 1.8300

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4959 - mae: 1.8221

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5036 - mae: 1.8257

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4770 - mae: 1.8205

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4742 - mae: 1.8216

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4914 - mae: 1.8220

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4807 - mae: 1.8204

363/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4839 - mae: 1.8208

369/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4945 - mae: 1.8225

375/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4660 - mae: 1.8168

381/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4578 - mae: 1.8163

387/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4565 - mae: 1.8145

393/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4633 - mae: 1.8162

399/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4861 - mae: 1.8198

405/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4589 - mae: 1.8150

411/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4737 - mae: 1.8175

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4829 - mae: 1.8189

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4994 - mae: 1.8183

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5388 - mae: 1.8223

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5498 - mae: 1.8211

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5258 - mae: 1.8170

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5223 - mae: 1.8169

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5237 - mae: 1.8189

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5112 - mae: 1.8171

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5151 - mae: 1.8196

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5412 - mae: 1.8244

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5530 - mae: 1.8267

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5556 - mae: 1.8269

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5764 - mae: 1.8308

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5881 - mae: 1.8332

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5778 - mae: 1.8320

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5631 - mae: 1.8300

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5295 - mae: 1.8241

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5122 - mae: 1.8221

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5255 - mae: 1.8247

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.5255 - mae: 1.8247 - val_loss: 6.2588 - val_mae: 1.9737

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 4.6873 - mae: 1.9737

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 3.8132 - mae: 1.6914

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.7700 - mae: 1.8025

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8826 - mae: 1.7893

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5899 - mae: 1.8309

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3854 - mae: 1.8307

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0488 - mae: 1.7782

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1689 - mae: 1.7834

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6087 - mae: 1.8497

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4263 - mae: 1.8251

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4703 - mae: 1.8102

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4036 - mae: 1.8127

 72/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3900 - mae: 1.8068

 78/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.6731 - mae: 1.8574

 84/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.8015 - mae: 1.8859

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.8334 - mae: 1.8956

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7110 - mae: 1.8639

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7159 - mae: 1.8632

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6819 - mae: 1.8556

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6311 - mae: 1.8443

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7390 - mae: 1.8527

125/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6687 - mae: 1.8396

130/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6759 - mae: 1.8426

135/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6241 - mae: 1.8339

141/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5296 - mae: 1.8165

147/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5356 - mae: 1.8187

153/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5140 - mae: 1.8169

159/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5911 - mae: 1.8335

165/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5592 - mae: 1.8332

171/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5326 - mae: 1.8258

177/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6507 - mae: 1.8424

183/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6740 - mae: 1.8450

189/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7158 - mae: 1.8558

194/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7700 - mae: 1.8593

199/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7544 - mae: 1.8580

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7738 - mae: 1.8619

210/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7823 - mae: 1.8611

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7678 - mae: 1.8609

220/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.7531 - mae: 1.8589

225/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7161 - mae: 1.8550

230/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7817 - mae: 1.8610

236/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7910 - mae: 1.8640

242/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7623 - mae: 1.8583

248/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7818 - mae: 1.8643

254/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7136 - mae: 1.8533

260/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7505 - mae: 1.8546

266/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7195 - mae: 1.8506

271/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.7236 - mae: 1.8490

277/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6860 - mae: 1.8445

283/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6475 - mae: 1.8379

289/522 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5.6269 - mae: 1.8343

295/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6088 - mae: 1.8319

301/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6017 - mae: 1.8343

307/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5756 - mae: 1.8309

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5714 - mae: 1.8319

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5230 - mae: 1.8217

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4997 - mae: 1.8172

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.5038 - mae: 1.8211

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4727 - mae: 1.8166

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4805 - mae: 1.8196

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4829 - mae: 1.8179

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4670 - mae: 1.8151

361/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4833 - mae: 1.8188

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4741 - mae: 1.8154

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4672 - mae: 1.8141

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4560 - mae: 1.8135

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4227 - mae: 1.8077

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4643 - mae: 1.8149

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4500 - mae: 1.8113

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4403 - mae: 1.8090

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4291 - mae: 1.8081

414/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4641 - mae: 1.8142

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4370 - mae: 1.8095

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4941 - mae: 1.8129

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4922 - mae: 1.8135

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5106 - mae: 1.8140

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5012 - mae: 1.8119

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4897 - mae: 1.8116

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4732 - mae: 1.8104

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4847 - mae: 1.8144

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4814 - mae: 1.8140

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4878 - mae: 1.8157

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4978 - mae: 1.8169

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5336 - mae: 1.8232

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5363 - mae: 1.8233

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5237 - mae: 1.8219

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5168 - mae: 1.8210

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.5009 - mae: 1.8194

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4763 - mae: 1.8150

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4846 - mae: 1.8175

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.4846 - mae: 1.8175 - val_loss: 6.0168 - val_mae: 1.9305

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 3.0344 - mae: 1.5102

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 3.5452 - mae: 1.6381

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.4205 - mae: 1.7470

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.6063 - mae: 1.7464

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4026 - mae: 1.8171

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2792 - mae: 1.8260

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.9345 - mae: 1.7613

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0771 - mae: 1.7728

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.5691 - mae: 1.8513

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3736 - mae: 1.8194

 61/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4110 - mae: 1.8058

 67/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3156 - mae: 1.7975

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3020 - mae: 1.7924

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6093 - mae: 1.8441

 85/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7028 - mae: 1.8683

 91/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7978 - mae: 1.8846

 97/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5807 - mae: 1.8423

103/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6111 - mae: 1.8468

109/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5841 - mae: 1.8402

115/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4964 - mae: 1.8226

121/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6204 - mae: 1.8365

127/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5365 - mae: 1.8200

133/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5187 - mae: 1.8173

139/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4498 - mae: 1.8033

145/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4489 - mae: 1.8010

151/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3920 - mae: 1.7952

157/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3621 - mae: 1.7937

163/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4749 - mae: 1.8174

169/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4746 - mae: 1.8146

175/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4980 - mae: 1.8166

181/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5489 - mae: 1.8216

187/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5421 - mae: 1.8221

193/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6448 - mae: 1.8364

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6299 - mae: 1.8379

205/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6493 - mae: 1.8421

211/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6462 - mae: 1.8396

217/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6693 - mae: 1.8463

223/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6057 - mae: 1.8353

229/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5940 - mae: 1.8358

235/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6549 - mae: 1.8409

241/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6495 - mae: 1.8409

247/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6202 - mae: 1.8403

253/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6037 - mae: 1.8376

258/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5873 - mae: 1.8313

264/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5954 - mae: 1.8320

270/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.6052 - mae: 1.8294

276/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5712 - mae: 1.8265

282/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5338 - mae: 1.8195

288/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4931 - mae: 1.8123

294/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4796 - mae: 1.8108

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4458 - mae: 1.8065

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4362 - mae: 1.8077

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4325 - mae: 1.8080

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.4048 - mae: 1.8026

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3733 - mae: 1.7962

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3766 - mae: 1.8006

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3493 - mae: 1.7951

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3551 - mae: 1.7980

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3450 - mae: 1.7954

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3478 - mae: 1.7947

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3581 - mae: 1.7977

366/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3602 - mae: 1.7970

372/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3450 - mae: 1.7937

378/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3254 - mae: 1.7913

384/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2929 - mae: 1.7858

390/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3308 - mae: 1.7923

396/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3163 - mae: 1.7883

402/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3059 - mae: 1.7856

408/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2968 - mae: 1.7850

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3346 - mae: 1.7918

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3141 - mae: 1.7882

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3365 - mae: 1.7883

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3664 - mae: 1.7914

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3786 - mae: 1.7904

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3677 - mae: 1.7885

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3675 - mae: 1.7902

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3499 - mae: 1.7892

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3354 - mae: 1.7867

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3472 - mae: 1.7903

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3655 - mae: 1.7942

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3893 - mae: 1.7982

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3855 - mae: 1.7980

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4304 - mae: 1.8058

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4178 - mae: 1.8039

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4111 - mae: 1.8026

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4008 - mae: 1.8021

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3801 - mae: 1.7984

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3699 - mae: 1.7991

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.3768 - mae: 1.7997 - val_loss: 6.0667 - val_mae: 1.9444

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 2.3666 - mae: 1.2813

  7/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 3.5400 - mae: 1.6126

 13/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.3679 - mae: 1.7307

 19/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.6303 - mae: 1.7388

 25/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.2827 - mae: 1.7796

 31/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.1748 - mae: 1.7988

 37/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 4.8763 - mae: 1.7449

 43/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.0354 - mae: 1.7591

 49/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.4996 - mae: 1.8312

 55/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 5.3148 - mae: 1.8017

 61/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3460 - mae: 1.7885

 67/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.2465 - mae: 1.7792

 73/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.2396 - mae: 1.7755

 79/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5849 - mae: 1.8343

 84/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.6694 - mae: 1.8542

 90/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.7089 - mae: 1.8712

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5650 - mae: 1.8338

102/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5453 - mae: 1.8234

108/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5202 - mae: 1.8175

114/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4443 - mae: 1.8014

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.5421 - mae: 1.8089

126/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4516 - mae: 1.7939

132/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4401 - mae: 1.7927

138/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3537 - mae: 1.7749

144/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3331 - mae: 1.7711

150/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3112 - mae: 1.7685

156/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.2582 - mae: 1.7625

162/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3408 - mae: 1.7813

168/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3353 - mae: 1.7792

173/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.3363 - mae: 1.7806

179/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4295 - mae: 1.7943

185/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 5.4101 - mae: 1.7896

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4311 - mae: 1.7966

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5404 - mae: 1.8116

203/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5350 - mae: 1.8086

209/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5497 - mae: 1.8104

215/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5277 - mae: 1.8096

221/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5224 - mae: 1.8088

227/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4821 - mae: 1.8030

233/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5531 - mae: 1.8118

239/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5959 - mae: 1.8183

245/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5384 - mae: 1.8131

251/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5414 - mae: 1.8160

257/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5160 - mae: 1.8075

263/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5210 - mae: 1.8088

269/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.5274 - mae: 1.8047

275/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4968 - mae: 1.8026

281/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4869 - mae: 1.8024

287/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4375 - mae: 1.7920

293/522 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 5.4207 - mae: 1.7904

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3995 - mae: 1.7895

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3842 - mae: 1.7903

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3858 - mae: 1.7916

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3456 - mae: 1.7856

323/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3262 - mae: 1.7833

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2956 - mae: 1.7807

335/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2971 - mae: 1.7801

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2726 - mae: 1.7764

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2831 - mae: 1.7781

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2954 - mae: 1.7791

359/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2932 - mae: 1.7797

365/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2898 - mae: 1.7801

371/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2898 - mae: 1.7788

377/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2715 - mae: 1.7760

383/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2438 - mae: 1.7719

389/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2523 - mae: 1.7732

395/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2561 - mae: 1.7732

401/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2591 - mae: 1.7739

407/522 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.2332 - mae: 1.7701

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2584 - mae: 1.7753

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2616 - mae: 1.7768

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2946 - mae: 1.7779

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3163 - mae: 1.7799

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3222 - mae: 1.7785

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3172 - mae: 1.7774

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3036 - mae: 1.7760

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2921 - mae: 1.7764

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2879 - mae: 1.7753

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2957 - mae: 1.7781

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3005 - mae: 1.7794

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3206 - mae: 1.7826

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3324 - mae: 1.7859

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3611 - mae: 1.7913

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3433 - mae: 1.7888

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3423 - mae: 1.7893

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3217 - mae: 1.7869

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.2998 - mae: 1.7827

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.3027 - mae: 1.7844

522/522 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 5.3018 - mae: 1.7844 - val_loss: 6.0278 - val_mae: 1.9432

Epoch 18: early stopping

Restoring model weights from the end of the best epoch: 8.

In [16]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 5s 489ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step

MAE:  1.8372029487599326

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [17]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=128, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D(2))
model.add(Conv1D(filters=64, kernel_size=2))
model.add(MaxPooling1D(2))
model.add(Bidirectional(LSTM(32, activation='relu')))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)               │ (None, 28, 128)        │           512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 14, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_3 (Conv1D)               │ (None, 13, 64)         │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 6, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 64)             │        24,832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41,857 (163.50 KB)

 Trainable params: 41,857 (163.50 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 29:30 3s/step - loss: 125.1141 - mae: 10.7603

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 33.3873 - mae: 4.5164

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 22.5955 - mae: 3.6060

 34/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 17.5336 - mae: 3.1151

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 15.1803 - mae: 2.8752

 56/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 14.3577 - mae: 2.8328

 67/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13.6157 - mae: 2.7619

 78/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13.4959 - mae: 2.7579

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 13.1305 - mae: 2.7359

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 12.5580 - mae: 2.6778

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 11.9670 - mae: 2.6185

119/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.9912 - mae: 2.6160

129/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.7002 - mae: 2.5888

139/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.5891 - mae: 2.5909

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.3843 - mae: 2.5807

159/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.4279 - mae: 2.5923

170/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.2896 - mae: 2.5924

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.4083 - mae: 2.6042

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.3651 - mae: 2.5986

201/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.3195 - mae: 2.5913

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.2565 - mae: 2.5883

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.1268 - mae: 2.5767

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11.1114 - mae: 2.5679

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.9218 - mae: 2.5442

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.8108 - mae: 2.5400

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.7914 - mae: 2.5368

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.7114 - mae: 2.5250

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.7400 - mae: 2.5350

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.6082 - mae: 2.5188

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.5346 - mae: 2.5155

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.4719 - mae: 2.5078

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 10.3596 - mae: 2.4892

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3926 - mae: 2.4960

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3670 - mae: 2.4969

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3717 - mae: 2.4938

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3441 - mae: 2.4914

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3545 - mae: 2.4927

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.2702 - mae: 2.4835

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3048 - mae: 2.4879

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.2568 - mae: 2.4836

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1638 - mae: 2.4736

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1665 - mae: 2.4724

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1579 - mae: 2.4714

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1583 - mae: 2.4724

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1007 - mae: 2.4645

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.1118 - mae: 2.4658

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.0646 - mae: 2.4610

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.9971 - mae: 2.4505

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.0445 - mae: 2.4598

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.0137 - mae: 2.4562

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.9902 - mae: 2.4557

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.9849 - mae: 2.4563

522/522 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - loss: 9.9825 - mae: 2.4561 - val_loss: 10.0132 - val_mae: 2.4560

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 9.7285 - mae: 2.7286

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 12.0124 - mae: 2.7635

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.4046 - mae: 2.4243

 31/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0312 - mae: 2.3773

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4094 - mae: 2.2520

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8628 - mae: 2.3299

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9454 - mae: 2.3267

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9454 - mae: 2.3374

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5751 - mae: 2.4168

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3014 - mae: 2.3873

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0603 - mae: 2.3486

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0020 - mae: 2.3501

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1778 - mae: 2.3519

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1601 - mae: 2.3556

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1562 - mae: 2.3610

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2357 - mae: 2.3766

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3757 - mae: 2.4030

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.5274 - mae: 2.4191

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.5381 - mae: 2.4183

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.6325 - mae: 2.4259

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.5554 - mae: 2.4164

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.5196 - mae: 2.4180

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4590 - mae: 2.4103

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4923 - mae: 2.4051

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3840 - mae: 2.3944

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3911 - mae: 2.3989

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3420 - mae: 2.3892

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3324 - mae: 2.3892

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3638 - mae: 2.3926

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3685 - mae: 2.3964

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3181 - mae: 2.3902

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2479 - mae: 2.3822

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1833 - mae: 2.3720

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1205 - mae: 2.3598

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1465 - mae: 2.3669

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1814 - mae: 2.3739

352/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1636 - mae: 2.3649

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1223 - mae: 2.3584

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1586 - mae: 2.3624

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0740 - mae: 2.3501

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1378 - mae: 2.3585

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1100 - mae: 2.3571

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0544 - mae: 2.3512

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0641 - mae: 2.3519

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.1012 - mae: 2.3555

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0989 - mae: 2.3552

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0486 - mae: 2.3479

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0783 - mae: 2.3523

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0349 - mae: 2.3463

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9988 - mae: 2.3396

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0650 - mae: 2.3520

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0532 - mae: 2.3504

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0169 - mae: 2.3472

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.0384 - mae: 2.3505 - val_loss: 9.1969 - val_mae: 2.3447

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 9.1193 - mae: 2.6597

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 11.6962 - mae: 2.7439

 20/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2371 - mae: 2.3898

 30/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9037 - mae: 2.3486

 40/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4002 - mae: 2.2224

 49/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7757 - mae: 2.2901

 57/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5518 - mae: 2.2861

 68/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7695 - mae: 2.3155

 78/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3461 - mae: 2.3714

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3813 - mae: 2.3815

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1730 - mae: 2.3557

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8283 - mae: 2.3135

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1482 - mae: 2.3464

128/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9796 - mae: 2.3223

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0221 - mae: 2.3331

148/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9977 - mae: 2.3389

158/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1159 - mae: 2.3555

169/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2098 - mae: 2.3798

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4143 - mae: 2.4001

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4070 - mae: 2.3935

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4855 - mae: 2.4083

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3827 - mae: 2.3926

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3675 - mae: 2.3964

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2448 - mae: 2.3793

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3060 - mae: 2.3769

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2501 - mae: 2.3742

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2329 - mae: 2.3730

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1239 - mae: 2.3567

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2008 - mae: 2.3700

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1852 - mae: 2.3677

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1204 - mae: 2.3610

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0767 - mae: 2.3555

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9766 - mae: 2.3396

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9470 - mae: 2.3355

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0054 - mae: 2.3440

347/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0207 - mae: 2.3433

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0098 - mae: 2.3410

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0140 - mae: 2.3404

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9591 - mae: 2.3341

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0035 - mae: 2.3396

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9833 - mae: 2.3380

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9193 - mae: 2.3294

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9293 - mae: 2.3316

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9462 - mae: 2.3321

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9664 - mae: 2.3378

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9257 - mae: 2.3298

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9055 - mae: 2.3279

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9110 - mae: 2.3266

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8660 - mae: 2.3215

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8978 - mae: 2.3269

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8695 - mae: 2.3242

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9035 - mae: 2.3316

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9025 - mae: 2.3343

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.9020 - mae: 2.3353 - val_loss: 7.8022 - val_mae: 2.1565

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 7.8597 - mae: 2.5245

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.3593 - mae: 2.6798

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5404 - mae: 2.4580

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4135 - mae: 2.2896

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0099 - mae: 2.1957

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4505 - mae: 2.2751

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5449 - mae: 2.2740

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6362 - mae: 2.2972

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2233 - mae: 2.3706

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9916 - mae: 2.3429

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7744 - mae: 2.3085

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6878 - mae: 2.3069

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8552 - mae: 2.3056

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9318 - mae: 2.3214

145/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9018 - mae: 2.3252

155/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9475 - mae: 2.3368

166/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0900 - mae: 2.3638

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3307 - mae: 2.3892

186/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3095 - mae: 2.3830

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3202 - mae: 2.3865

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2543 - mae: 2.3765

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2473 - mae: 2.3799

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1537 - mae: 2.3688

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1952 - mae: 2.3638

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1438 - mae: 2.3618

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1159 - mae: 2.3586

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0298 - mae: 2.3463

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0889 - mae: 2.3560

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0696 - mae: 2.3534

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0017 - mae: 2.3463

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9473 - mae: 2.3398

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8473 - mae: 2.3237

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8148 - mae: 2.3191

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8806 - mae: 2.3284

347/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9120 - mae: 2.3305

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9016 - mae: 2.3282

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8824 - mae: 2.3237

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8564 - mae: 2.3213

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8337 - mae: 2.3196

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8915 - mae: 2.3258

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8143 - mae: 2.3157

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8427 - mae: 2.3188

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8501 - mae: 2.3176

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8562 - mae: 2.3200

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8159 - mae: 2.3139

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8367 - mae: 2.3152

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8535 - mae: 2.3165

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8161 - mae: 2.3132

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8327 - mae: 2.3154

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8207 - mae: 2.3141

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8762 - mae: 2.3252

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8277 - mae: 2.3170

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.8526 - mae: 2.3215 - val_loss: 9.6359 - val_mae: 2.4037

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - loss: 8.9848 - mae: 2.5984

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.9941 - mae: 2.7550

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3462 - mae: 2.4079

 31/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9782 - mae: 2.3641

 41/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3349 - mae: 2.2290

 51/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7575 - mae: 2.2932

 61/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8752 - mae: 2.3105

 71/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8296 - mae: 2.3147

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5079 - mae: 2.4052

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3086 - mae: 2.3873

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0033 - mae: 2.3391

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8472 - mae: 2.3287

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0127 - mae: 2.3349

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0512 - mae: 2.3406

142/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9923 - mae: 2.3393

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0370 - mae: 2.3524

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1218 - mae: 2.3668

172/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0532 - mae: 2.3590

182/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3402 - mae: 2.3929

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.4236 - mae: 2.3973

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3234 - mae: 2.3894

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.3062 - mae: 2.3879

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2638 - mae: 2.3842

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2665 - mae: 2.3761

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1583 - mae: 2.3627

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1239 - mae: 2.3622

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0693 - mae: 2.3518

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1208 - mae: 2.3586

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1179 - mae: 2.3614

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0589 - mae: 2.3533

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9882 - mae: 2.3447

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9110 - mae: 2.3315

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8563 - mae: 2.3224

333/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9041 - mae: 2.3308

343/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8885 - mae: 2.3295

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8852 - mae: 2.3237

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8496 - mae: 2.3199

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8887 - mae: 2.3240

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8043 - mae: 2.3122

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8580 - mae: 2.3187

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8299 - mae: 2.3157

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7918 - mae: 2.3147

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7833 - mae: 2.3137

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8251 - mae: 2.3183

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8220 - mae: 2.3172

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7792 - mae: 2.3117

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8001 - mae: 2.3138

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7746 - mae: 2.3104

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7486 - mae: 2.3059

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7924 - mae: 2.3143

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7798 - mae: 2.3126

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7480 - mae: 2.3104

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.7706 - mae: 2.3135 - val_loss: 8.2236 - val_mae: 2.2092

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 8.3935 - mae: 2.5372

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 11.4043 - mae: 2.7628

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7959 - mae: 2.3766

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8496 - mae: 2.3432

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1200 - mae: 2.2068

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5973 - mae: 2.2895

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6071 - mae: 2.2793

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7452 - mae: 2.3124

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.2939 - mae: 2.3792

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0639 - mae: 2.3514

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8235 - mae: 2.3132

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7483 - mae: 2.3128

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9244 - mae: 2.3199

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8580 - mae: 2.3144

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7990 - mae: 2.3138

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8843 - mae: 2.3297

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0235 - mae: 2.3560

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1394 - mae: 2.3648

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1686 - mae: 2.3676

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.2416 - mae: 2.3740

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1779 - mae: 2.3681

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1102 - mae: 2.3660

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0950 - mae: 2.3658

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1006 - mae: 2.3576

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0449 - mae: 2.3541

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9834 - mae: 2.3503

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9291 - mae: 2.3399

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9689 - mae: 2.3461

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9700 - mae: 2.3489

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9218 - mae: 2.3418

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8505 - mae: 2.3322

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7799 - mae: 2.3203

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7225 - mae: 2.3101

333/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7684 - mae: 2.3178

343/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7491 - mae: 2.3159

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7516 - mae: 2.3101

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7204 - mae: 2.3070

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7601 - mae: 2.3116

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6631 - mae: 2.2981

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7444 - mae: 2.3080

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6879 - mae: 2.3013

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6996 - mae: 2.3062

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6326 - mae: 2.2967

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6963 - mae: 2.3048

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6829 - mae: 2.3022

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6394 - mae: 2.2955

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6663 - mae: 2.2996

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6309 - mae: 2.2945

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6095 - mae: 2.2901

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6696 - mae: 2.3010

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6554 - mae: 2.2989

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6215 - mae: 2.2964

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.6439 - mae: 2.2998 - val_loss: 8.0449 - val_mae: 2.1830

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 8.3905 - mae: 2.5315

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 11.1457 - mae: 2.7358

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.5757 - mae: 2.4359

 34/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3073 - mae: 2.2505

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1334 - mae: 2.2047

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4261 - mae: 2.2648

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3833 - mae: 2.2361

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6463 - mae: 2.2908

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1669 - mae: 2.3526

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9396 - mae: 2.3237

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7032 - mae: 2.2868

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6791 - mae: 2.2941

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7901 - mae: 2.2940

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7076 - mae: 2.2896

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7054 - mae: 2.2946

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7755 - mae: 2.3058

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8998 - mae: 2.3305

173/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9790 - mae: 2.3352

183/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0869 - mae: 2.3496

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.1429 - mae: 2.3543

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0486 - mae: 2.3483

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0238 - mae: 2.3477

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9904 - mae: 2.3470

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0395 - mae: 2.3445

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9488 - mae: 2.3332

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8667 - mae: 2.3307

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8754 - mae: 2.3294

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8553 - mae: 2.3245

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9222 - mae: 2.3392

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8348 - mae: 2.3265

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8249 - mae: 2.3267

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8061 - mae: 2.3230

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6971 - mae: 2.3063

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6754 - mae: 2.3035

338/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6980 - mae: 2.3058

348/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7068 - mae: 2.3030

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7119 - mae: 2.3020

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7228 - mae: 2.3037

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6606 - mae: 2.2965

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6941 - mae: 2.3008

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6744 - mae: 2.3007

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6057 - mae: 2.2912

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6079 - mae: 2.2930

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6262 - mae: 2.2930

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6424 - mae: 2.2982

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6074 - mae: 2.2909

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5838 - mae: 2.2880

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5971 - mae: 2.2878

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5641 - mae: 2.2848

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6005 - mae: 2.2902

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5660 - mae: 2.2863

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6072 - mae: 2.2942

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5867 - mae: 2.2915

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.5920 - mae: 2.2928 - val_loss: 7.7957 - val_mae: 2.1561

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 7.7847 - mae: 2.4799

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.7891 - mae: 2.7108

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2189 - mae: 2.3294

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3578 - mae: 2.2675

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0387 - mae: 2.2005

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3705 - mae: 2.2519

 62/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4239 - mae: 2.2475

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4794 - mae: 2.2566

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.0858 - mae: 2.3382

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9765 - mae: 2.3290

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6697 - mae: 2.2810

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5643 - mae: 2.2782

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6128 - mae: 2.2672

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6252 - mae: 2.2777

145/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5899 - mae: 2.2802

155/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6599 - mae: 2.2967

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7724 - mae: 2.3206

176/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0231 - mae: 2.3463

186/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0211 - mae: 2.3444

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 9.0521 - mae: 2.3493

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9982 - mae: 2.3423

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9864 - mae: 2.3462

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8714 - mae: 2.3329

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9533 - mae: 2.3348

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8944 - mae: 2.3336

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8056 - mae: 2.3195

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7364 - mae: 2.3081

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8276 - mae: 2.3236

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7911 - mae: 2.3192

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7223 - mae: 2.3110

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7035 - mae: 2.3072

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5757 - mae: 2.2878

329/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5854 - mae: 2.2887

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6048 - mae: 2.2917

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6144 - mae: 2.2884

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5954 - mae: 2.2849

370/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6186 - mae: 2.2881

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5545 - mae: 2.2817

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.6066 - mae: 2.2865

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5732 - mae: 2.2860

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4998 - mae: 2.2768

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4820 - mae: 2.2759

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5307 - mae: 2.2822

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5165 - mae: 2.2814

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5034 - mae: 2.2784

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4822 - mae: 2.2760

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5129 - mae: 2.2786

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4604 - mae: 2.2717

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5157 - mae: 2.2791

500/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5057 - mae: 2.2785

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5014 - mae: 2.2813

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4921 - mae: 2.2801

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.4996 - mae: 2.2810 - val_loss: 7.7525 - val_mae: 2.1534

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 7.8622 - mae: 2.4998

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.7263 - mae: 2.7147

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3840 - mae: 2.4289

 34/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1833 - mae: 2.2438

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9597 - mae: 2.1927

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2784 - mae: 2.2391

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1897 - mae: 2.2099

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7350 - mae: 2.2747

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9432 - mae: 2.3193

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7355 - mae: 2.2933

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4568 - mae: 2.2495

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6019 - mae: 2.2606

128/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4245 - mae: 2.2391

138/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4640 - mae: 2.2546

148/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4859 - mae: 2.2662

158/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5734 - mae: 2.2806

168/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6682 - mae: 2.2993

178/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8501 - mae: 2.3182

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8518 - mae: 2.3174

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9697 - mae: 2.3359

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9031 - mae: 2.3280

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8569 - mae: 2.3282

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8235 - mae: 2.3200

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8210 - mae: 2.3117

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7558 - mae: 2.3095

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6701 - mae: 2.2996

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6784 - mae: 2.3006

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7202 - mae: 2.3100

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6547 - mae: 2.3010

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6355 - mae: 2.3005

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6253 - mae: 2.2965

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5026 - mae: 2.2773

329/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5055 - mae: 2.2759

340/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5321 - mae: 2.2791

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5416 - mae: 2.2763

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5230 - mae: 2.2721

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5600 - mae: 2.2774

379/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5006 - mae: 2.2710

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5131 - mae: 2.2712

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5014 - mae: 2.2735

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4381 - mae: 2.2653

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4231 - mae: 2.2647

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4719 - mae: 2.2707

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4647 - mae: 2.2719

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4366 - mae: 2.2664

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4170 - mae: 2.2645

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4477 - mae: 2.2679

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3944 - mae: 2.2613

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4500 - mae: 2.2687

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4381 - mae: 2.2683

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4466 - mae: 2.2727

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4346 - mae: 2.2709

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.4331 - mae: 2.2706 - val_loss: 7.9835 - val_mae: 2.1822

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 8.3394 - mae: 2.4966

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.7791 - mae: 2.6937

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3600 - mae: 2.3293

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4277 - mae: 2.2787

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7825 - mae: 2.1593

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1520 - mae: 2.2193

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1829 - mae: 2.2240

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3255 - mae: 2.2453

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.9897 - mae: 2.3288

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7882 - mae: 2.3040

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5399 - mae: 2.2646

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4873 - mae: 2.2711

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6064 - mae: 2.2696

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5419 - mae: 2.2691

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5382 - mae: 2.2705

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5480 - mae: 2.2770

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7016 - mae: 2.3006

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8337 - mae: 2.3173

185/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9047 - mae: 2.3263

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9304 - mae: 2.3299

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.9012 - mae: 2.3301

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8300 - mae: 2.3269

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7878 - mae: 2.3245

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.8368 - mae: 2.3231

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7346 - mae: 2.3143

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7040 - mae: 2.3131

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6627 - mae: 2.3057

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7118 - mae: 2.3116

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7089 - mae: 2.3138

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6539 - mae: 2.3071

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5937 - mae: 2.2978

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5332 - mae: 2.2875

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4797 - mae: 2.2761

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.5283 - mae: 2.2825

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4736 - mae: 2.2775

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4699 - mae: 2.2706

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4433 - mae: 2.2679

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4854 - mae: 2.2735

384/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3916 - mae: 2.2592

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4693 - mae: 2.2698

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4143 - mae: 2.2642

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4094 - mae: 2.2668

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3507 - mae: 2.2586

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4171 - mae: 2.2675

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4022 - mae: 2.2644

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3652 - mae: 2.2591

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3961 - mae: 2.2647

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3867 - mae: 2.2641

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3502 - mae: 2.2583

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3841 - mae: 2.2639

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3984 - mae: 2.2673

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3654 - mae: 2.2634

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.3850 - mae: 2.2674 - val_loss: 7.7411 - val_mae: 2.1536

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 8.2258 - mae: 2.5592

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.6963 - mae: 2.7120

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2900 - mae: 2.3415

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3920 - mae: 2.2893

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7798 - mae: 2.1869

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1336 - mae: 2.2452

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0745 - mae: 2.2177

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3500 - mae: 2.2683

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.8551 - mae: 2.3261

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6253 - mae: 2.2933

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3928 - mae: 2.2537

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3091 - mae: 2.2516

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3845 - mae: 2.2437

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3065 - mae: 2.2388

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2815 - mae: 2.2358

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3317 - mae: 2.2483

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4713 - mae: 2.2686

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6093 - mae: 2.2876

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7022 - mae: 2.3018

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7526 - mae: 2.3048

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7254 - mae: 2.3071

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6514 - mae: 2.3043

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6461 - mae: 2.3046

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6289 - mae: 2.2919

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5765 - mae: 2.2875

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5417 - mae: 2.2879

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5326 - mae: 2.2849

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5546 - mae: 2.2884

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5332 - mae: 2.2857

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4716 - mae: 2.2802

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4310 - mae: 2.2717

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3489 - mae: 2.2599

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3189 - mae: 2.2531

336/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3502 - mae: 2.2576

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3145 - mae: 2.2543

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3311 - mae: 2.2514

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3240 - mae: 2.2513

375/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3372 - mae: 2.2516

385/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2649 - mae: 2.2412

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3406 - mae: 2.2530

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2891 - mae: 2.2462

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2905 - mae: 2.2493

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2330 - mae: 2.2411

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3058 - mae: 2.2514

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2913 - mae: 2.2488

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2450 - mae: 2.2424

465/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2736 - mae: 2.2471

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2632 - mae: 2.2461

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2385 - mae: 2.2420

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2509 - mae: 2.2443

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2752 - mae: 2.2498

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2407 - mae: 2.2451

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.2641 - mae: 2.2495 - val_loss: 7.6438 - val_mae: 2.1450

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 7.9252 - mae: 2.5080

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.3933 - mae: 2.6737

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1576 - mae: 2.4048

 34/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9300 - mae: 2.2126

 45/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6555 - mae: 2.1708

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0785 - mae: 2.2360

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0275 - mae: 2.2063

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5339 - mae: 2.2647

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7206 - mae: 2.3039

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4875 - mae: 2.2687

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2073 - mae: 2.2264

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3892 - mae: 2.2409

127/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2230 - mae: 2.2179

137/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2239 - mae: 2.2238

147/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1452 - mae: 2.2149

157/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2413 - mae: 2.2385

167/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4385 - mae: 2.2677

177/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6534 - mae: 2.2962

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6339 - mae: 2.2921

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7166 - mae: 2.3070

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6464 - mae: 2.2998

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5794 - mae: 2.2948

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5360 - mae: 2.2877

237/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6346 - mae: 2.2893

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5661 - mae: 2.2892

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5703 - mae: 2.2927

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5287 - mae: 2.2850

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5832 - mae: 2.2973

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5778 - mae: 2.2960

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5163 - mae: 2.2887

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5027 - mae: 2.2854

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4335 - mae: 2.2752

326/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3695 - mae: 2.2643

336/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4298 - mae: 2.2729

346/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4576 - mae: 2.2748

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4293 - mae: 2.2693

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4363 - mae: 2.2699

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4028 - mae: 2.2658

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3421 - mae: 2.2576

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3875 - mae: 2.2648

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3357 - mae: 2.2576

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3300 - mae: 2.2596

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3297 - mae: 2.2580

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3368 - mae: 2.2620

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2914 - mae: 2.2539

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2890 - mae: 2.2540

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3136 - mae: 2.2577

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2875 - mae: 2.2549

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3487 - mae: 2.2629

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3038 - mae: 2.2577

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3589 - mae: 2.2672

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.3096 - mae: 2.2603

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.3295 - mae: 2.2643 - val_loss: 7.6138 - val_mae: 2.1393

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 8.5892 - mae: 2.6433

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.4173 - mae: 2.6845

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.1720 - mae: 2.4023

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1757 - mae: 2.2474

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7938 - mae: 2.1911

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0703 - mae: 2.2333

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9940 - mae: 2.2030

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4730 - mae: 2.2605

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6410 - mae: 2.2951

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4507 - mae: 2.2664

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2233 - mae: 2.2236

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0972 - mae: 2.2172

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2221 - mae: 2.2236

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3074 - mae: 2.2408

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2987 - mae: 2.2449

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3497 - mae: 2.2563

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4401 - mae: 2.2740

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5758 - mae: 2.2882

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6461 - mae: 2.2980

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7174 - mae: 2.3048

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6719 - mae: 2.3008

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5990 - mae: 2.2968

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5300 - mae: 2.2891

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5821 - mae: 2.2879

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5150 - mae: 2.2829

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4677 - mae: 2.2786

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4659 - mae: 2.2757

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4706 - mae: 2.2765

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4384 - mae: 2.2738

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3879 - mae: 2.2685

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3682 - mae: 2.2667

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2861 - mae: 2.2544

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2140 - mae: 2.2406

335/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2725 - mae: 2.2504

345/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2169 - mae: 2.2435

354/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2372 - mae: 2.2413

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2033 - mae: 2.2367

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2496 - mae: 2.2427

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1770 - mae: 2.2323

393/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2123 - mae: 2.2377

403/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1907 - mae: 2.2364

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1439 - mae: 2.2329

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1396 - mae: 2.2334

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1933 - mae: 2.2396

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1727 - mae: 2.2354

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1371 - mae: 2.2301

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1709 - mae: 2.2364

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1478 - mae: 2.2326

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1237 - mae: 2.2293

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1848 - mae: 2.2380

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1768 - mae: 2.2370

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1712 - mae: 2.2392

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.1767 - mae: 2.2409 - val_loss: 7.7240 - val_mae: 2.1595

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.7923 - mae: 2.3898

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 10.2630 - mae: 2.6291

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9031 - mae: 2.2936

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1958 - mae: 2.2467

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4402 - mae: 2.1226

 52/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8480 - mae: 2.1672

 62/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9313 - mae: 2.1843

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9840 - mae: 2.1884

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5689 - mae: 2.2685

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3595 - mae: 2.2441

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0165 - mae: 2.1849

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9809 - mae: 2.1941

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0438 - mae: 2.1893

133/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9498 - mae: 2.1733

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9461 - mae: 2.1716

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9769 - mae: 2.1847

164/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1187 - mae: 2.2176

174/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2659 - mae: 2.2368

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3904 - mae: 2.2527

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4893 - mae: 2.2637

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4877 - mae: 2.2684

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4252 - mae: 2.2637

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4012 - mae: 2.2619

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4341 - mae: 2.2591

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3678 - mae: 2.2513

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3234 - mae: 2.2490

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2847 - mae: 2.2420

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3049 - mae: 2.2453

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3516 - mae: 2.2573

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2496 - mae: 2.2425

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2007 - mae: 2.2355

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1911 - mae: 2.2330

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1359 - mae: 2.2212

332/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1479 - mae: 2.2254

342/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1547 - mae: 2.2276

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1379 - mae: 2.2184

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1391 - mae: 2.2190

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1537 - mae: 2.2196

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1047 - mae: 2.2147

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1572 - mae: 2.2208

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1201 - mae: 2.2178

411/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0591 - mae: 2.2095

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0555 - mae: 2.2109

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0315 - mae: 2.2080

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0803 - mae: 2.2160

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0668 - mae: 2.2128

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0336 - mae: 2.2101

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0522 - mae: 2.2127

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0440 - mae: 2.2116

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0343 - mae: 2.2106

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0809 - mae: 2.2177

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0649 - mae: 2.2149

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0615 - mae: 2.2178

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0624 - mae: 2.2215

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.0606 - mae: 2.2213 - val_loss: 10.3302 - val_mae: 2.5100

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 41s 79ms/step - loss: 10.3114 - mae: 2.6527

  8/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 9.6546 - mae: 2.6231

 14/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 9.5936 - mae: 2.4838

 18/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.7355 - mae: 2.3478

 21/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 8.4046 - mae: 2.2982

 26/522 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 9.2228 - mae: 2.3827

 33/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 8.3349 - mae: 2.2375

 40/522 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 7.9484 - mae: 2.1680

 47/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.0287 - mae: 2.1794

 54/522 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 8.1445 - mae: 2.2077

 62/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.2594 - mae: 2.2134

 70/522 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 8.1600 - mae: 2.2137

 78/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.6446 - mae: 2.2543

 87/522 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 8.8340 - mae: 2.2818

 96/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.4915 - mae: 2.2369

104/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3025 - mae: 2.2079

112/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1962 - mae: 2.2081

120/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.3619 - mae: 2.2186

129/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 8.1846 - mae: 2.1897

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.1993 - mae: 2.1939

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8.1898 - mae: 2.1942

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2070 - mae: 2.2030

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.2016 - mae: 2.2117

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.1198 - mae: 2.2015

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4365 - mae: 2.2406

190/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3783 - mae: 2.2331

199/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4543 - mae: 2.2458

208/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4735 - mae: 2.2534

218/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.4199 - mae: 2.2515

228/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8.3825 - mae: 2.2420

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3971 - mae: 2.2380

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.3490 - mae: 2.2409

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2659 - mae: 2.2297

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2047 - mae: 2.2194

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2803 - mae: 2.2349

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.2240 - mae: 2.2302

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8.1945 - mae: 2.2265

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1783 - mae: 2.2248

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0638 - mae: 2.2089

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0713 - mae: 2.2099

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0850 - mae: 2.2112

349/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0983 - mae: 2.2092

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0798 - mae: 2.2057

370/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0890 - mae: 2.2068

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0372 - mae: 2.2016

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0484 - mae: 2.2011

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0296 - mae: 2.2016

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9755 - mae: 2.1938

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9791 - mae: 2.1966

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0091 - mae: 2.2010

439/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0086 - mae: 2.2039

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9906 - mae: 2.2008

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9680 - mae: 2.1987

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9946 - mae: 2.2033

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9499 - mae: 2.1967

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0180 - mae: 2.2048

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0128 - mae: 2.2054

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0216 - mae: 2.2102

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0064 - mae: 2.2086

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.0078 - mae: 2.2090 - val_loss: 7.6230 - val_mae: 2.1552

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 7.8242 - mae: 2.3551

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.6701 - mae: 2.5275

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6655 - mae: 2.2611

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9089 - mae: 2.1865

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4930 - mae: 2.1258

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9149 - mae: 2.1910

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8108 - mae: 2.1647

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0707 - mae: 2.2034

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5954 - mae: 2.2604

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3654 - mae: 2.2312

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1029 - mae: 2.1817

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0328 - mae: 2.1880

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1829 - mae: 2.2019

133/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0679 - mae: 2.1848

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0245 - mae: 2.1834

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0731 - mae: 2.2034

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0981 - mae: 2.2077

173/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1532 - mae: 2.2124

183/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3073 - mae: 2.2299

193/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3625 - mae: 2.2374

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3571 - mae: 2.2376

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2780 - mae: 2.2314

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2337 - mae: 2.2264

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2520 - mae: 2.2191

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1755 - mae: 2.2143

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1344 - mae: 2.2126

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0832 - mae: 2.2042

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1174 - mae: 2.2112

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1209 - mae: 2.2147

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0708 - mae: 2.2079

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0288 - mae: 2.2049

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9848 - mae: 2.1976

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9268 - mae: 2.1872

334/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9611 - mae: 2.1932

344/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9173 - mae: 2.1888

353/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9365 - mae: 2.1847

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8982 - mae: 2.1792

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9244 - mae: 2.1799

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8645 - mae: 2.1731

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8994 - mae: 2.1786

402/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8614 - mae: 2.1758

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8115 - mae: 2.1715

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8191 - mae: 2.1746

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8262 - mae: 2.1762

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8270 - mae: 2.1756

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8044 - mae: 2.1741

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8201 - mae: 2.1759

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7974 - mae: 2.1735

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7931 - mae: 2.1724

492/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8633 - mae: 2.1838

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8500 - mae: 2.1805

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8557 - mae: 2.1848

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8542 - mae: 2.1863

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.8542 - mae: 2.1863 - val_loss: 7.9007 - val_mae: 2.1813

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 6.8546 - mae: 2.1334

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3427 - mae: 2.4638

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6494 - mae: 2.2435

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8101 - mae: 2.1672

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4186 - mae: 2.1087

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8839 - mae: 2.1899

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8416 - mae: 2.1673

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1718 - mae: 2.2215

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5852 - mae: 2.2614

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.7433 - mae: 2.2708

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4852 - mae: 2.2232

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2493 - mae: 2.2046

119/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5004 - mae: 2.2296

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4127 - mae: 2.2185

139/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.5220 - mae: 2.2377

149/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4956 - mae: 2.2410

159/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5903 - mae: 2.2581

169/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5737 - mae: 2.2689

179/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7707 - mae: 2.2879

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7461 - mae: 2.2862

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7830 - mae: 2.2876

210/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7821 - mae: 2.2935

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6553 - mae: 2.2785

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.7120 - mae: 2.2782

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.6162 - mae: 2.2668

251/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5554 - mae: 2.2669

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5096 - mae: 2.2593

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5081 - mae: 2.2597

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.5453 - mae: 2.2726

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.4175 - mae: 2.2551

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3879 - mae: 2.2531

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3441 - mae: 2.2461

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2811 - mae: 2.2344

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2729 - mae: 2.2348

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2313 - mae: 2.2296

350/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.2366 - mae: 2.2241

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1985 - mae: 2.2195

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1831 - mae: 2.2160

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1014 - mae: 2.2056

394/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.1424 - mae: 2.2129

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0865 - mae: 2.2059

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0691 - mae: 2.2058

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0119 - mae: 2.1992

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0558 - mae: 2.2068

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0427 - mae: 2.2029

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9957 - mae: 2.1965

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0187 - mae: 2.2019

474/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9905 - mae: 2.1978

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9742 - mae: 2.1956

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0177 - mae: 2.2037

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0095 - mae: 2.2027

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9887 - mae: 2.2029

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.9806 - mae: 2.2030 - val_loss: 7.9969 - val_mae: 2.2082

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 7.3339 - mae: 2.1197

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 9.3435 - mae: 2.4357

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7587 - mae: 2.2551

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0832 - mae: 2.2011

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4970 - mae: 2.1101

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0021 - mae: 2.2002

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8549 - mae: 2.1672

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2064 - mae: 2.2202

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6461 - mae: 2.2659

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.4350 - mae: 2.2414

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1565 - mae: 2.1925

113/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0433 - mae: 2.1892

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.0947 - mae: 2.1884

133/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1055 - mae: 2.1830

143/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0770 - mae: 2.1809

153/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1227 - mae: 2.1910

163/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1127 - mae: 2.1975

173/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1386 - mae: 2.1961

184/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2635 - mae: 2.2086

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3284 - mae: 2.2171

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.3414 - mae: 2.2215

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2802 - mae: 2.2195

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2554 - mae: 2.2192

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2577 - mae: 2.2106

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2054 - mae: 2.2065

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1981 - mae: 2.2111

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1502 - mae: 2.2039

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.1606 - mae: 2.2063

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.2072 - mae: 2.2190

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0862 - mae: 2.2023

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0713 - mae: 2.2020

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0336 - mae: 2.1970

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9776 - mae: 2.1863

331/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9720 - mae: 2.1867

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9315 - mae: 2.1817

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9289 - mae: 2.1749

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9113 - mae: 2.1744

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8827 - mae: 2.1697

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8366 - mae: 2.1653

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8799 - mae: 2.1719

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8509 - mae: 2.1713

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7871 - mae: 2.1635

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7708 - mae: 2.1622

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7997 - mae: 2.1651

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7670 - mae: 2.1602

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7686 - mae: 2.1600

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7459 - mae: 2.1565

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7632 - mae: 2.1599

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7325 - mae: 2.1575

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7689 - mae: 2.1623

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7384 - mae: 2.1587

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7874 - mae: 2.1695

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7650 - mae: 2.1675

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.7639 - mae: 2.1676 - val_loss: 7.8525 - val_mae: 2.1947

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 7.5672 - mae: 2.3376

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3807 - mae: 2.3553

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.6222 - mae: 2.3385

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8986 - mae: 2.2086

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3072 - mae: 2.1226

 52/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8166 - mae: 2.1899

 62/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7814 - mae: 2.1658

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9253 - mae: 2.1808

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.3795 - mae: 2.2343

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1514 - mae: 2.1990

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8720 - mae: 2.1491

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7306 - mae: 2.1355

122/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8064 - mae: 2.1343

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7430 - mae: 2.1257

142/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7288 - mae: 2.1282

152/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7223 - mae: 2.1328

162/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7592 - mae: 2.1429

172/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6279 - mae: 2.1265

182/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9515 - mae: 2.1689

192/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0132 - mae: 2.1706

202/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9867 - mae: 2.1738

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0221 - mae: 2.1796

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0111 - mae: 2.1833

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8.0709 - mae: 2.1823

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9999 - mae: 2.1768

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9450 - mae: 2.1763

262/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8889 - mae: 2.1688

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9462 - mae: 2.1751

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9744 - mae: 2.1862

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9432 - mae: 2.1857

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9100 - mae: 2.1834

314/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8538 - mae: 2.1727

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7928 - mae: 2.1607

332/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8160 - mae: 2.1668

341/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7947 - mae: 2.1654

351/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7961 - mae: 2.1596

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7943 - mae: 2.1615

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7975 - mae: 2.1618

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7493 - mae: 2.1581

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7657 - mae: 2.1607

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7281 - mae: 2.1602

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6795 - mae: 2.1557

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6756 - mae: 2.1568

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6873 - mae: 2.1580

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6864 - mae: 2.1594

448/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6660 - mae: 2.1548

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6410 - mae: 2.1530

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6540 - mae: 2.1550

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6069 - mae: 2.1493

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6506 - mae: 2.1556

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6336 - mae: 2.1526

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6861 - mae: 2.1634

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6462 - mae: 2.1583

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.6480 - mae: 2.1593 - val_loss: 8.0231 - val_mae: 2.2195

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 6.3136 - mae: 2.0792

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.1777 - mae: 2.2953

 23/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 8.2177 - mae: 2.2619

 33/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2542 - mae: 2.0908

 43/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9620 - mae: 2.0435

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3231 - mae: 2.1055

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3175 - mae: 2.0791

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.8288 - mae: 2.1368

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.9594 - mae: 2.1567

 95/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.7556 - mae: 2.1353

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6368 - mae: 2.1055

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4938 - mae: 2.0961

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.6166 - mae: 2.1009

135/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6702 - mae: 2.1051

145/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7052 - mae: 2.1195

155/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6677 - mae: 2.1203

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6271 - mae: 2.1259

175/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7639 - mae: 2.1365

185/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8117 - mae: 2.1383

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8768 - mae: 2.1510

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9370 - mae: 2.1610

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8548 - mae: 2.1510

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8543 - mae: 2.1565

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.9112 - mae: 2.1590

246/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8591 - mae: 2.1568

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8282 - mae: 2.1546

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7823 - mae: 2.1480

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8389 - mae: 2.1606

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.8121 - mae: 2.1563

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7688 - mae: 2.1540

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7387 - mae: 2.1490

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6705 - mae: 2.1415

327/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6186 - mae: 2.1303

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6192 - mae: 2.1331

346/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6635 - mae: 2.1357

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6368 - mae: 2.1305

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6132 - mae: 2.1268

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5768 - mae: 2.1250

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5424 - mae: 2.1232

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5663 - mae: 2.1280

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5306 - mae: 2.1240

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5391 - mae: 2.1270

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5312 - mae: 2.1227

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5203 - mae: 2.1230

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4929 - mae: 2.1180

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4645 - mae: 2.1152

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4823 - mae: 2.1193

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4605 - mae: 2.1168

486/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4681 - mae: 2.1176

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4922 - mae: 2.1218

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5264 - mae: 2.1283

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5106 - mae: 2.1270

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.5110 - mae: 2.1280 - val_loss: 8.0126 - val_mae: 2.2201

Epoch 21/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 6.4054 - mae: 2.0500

 12/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.4326 - mae: 2.1357

 22/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5924 - mae: 2.0417

 32/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.8344 - mae: 2.0152

 42/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4160 - mae: 1.9434

 52/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9966 - mae: 2.0250

 62/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9465 - mae: 2.0118

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1168 - mae: 2.0436

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5985 - mae: 2.1019

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3243 - mae: 2.0752

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2475 - mae: 2.0624

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2100 - mae: 2.0630

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3410 - mae: 2.0690

134/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3422 - mae: 2.0711

144/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4307 - mae: 2.0849

154/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4257 - mae: 2.0947

165/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4196 - mae: 2.1056

175/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5597 - mae: 2.1175

185/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6164 - mae: 2.1182

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6934 - mae: 2.1317

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7397 - mae: 2.1430

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7010 - mae: 2.1407

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7036 - mae: 2.1392

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.7195 - mae: 2.1374

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6901 - mae: 2.1343

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6459 - mae: 2.1339

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.6158 - mae: 2.1295

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5828 - mae: 2.1242

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5555 - mae: 2.1210

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5974 - mae: 2.1307

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6367 - mae: 2.1396

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5830 - mae: 2.1305

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5622 - mae: 2.1290

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5594 - mae: 2.1300

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5133 - mae: 2.1228

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4987 - mae: 2.1226

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4123 - mae: 2.1078

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4099 - mae: 2.1055

331/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4578 - mae: 2.1144

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4197 - mae: 2.1092

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4196 - mae: 2.1105

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4470 - mae: 2.1092

357/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4543 - mae: 2.1096

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4137 - mae: 2.1021

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4311 - mae: 2.1065

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4037 - mae: 2.1049

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3642 - mae: 2.1001

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3448 - mae: 2.0962

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3976 - mae: 2.1052

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3774 - mae: 2.1042

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3397 - mae: 2.0966

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3239 - mae: 2.0954

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3503 - mae: 2.0993

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3203 - mae: 2.0955

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3525 - mae: 2.0981

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3617 - mae: 2.1004

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3436 - mae: 2.0971

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3345 - mae: 2.0971

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3138 - mae: 2.0941

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3392 - mae: 2.0968

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3247 - mae: 2.0934

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3053 - mae: 2.0912

483/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3059 - mae: 2.0925

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3663 - mae: 2.1015

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3494 - mae: 2.0996

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3908 - mae: 2.1066

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3883 - mae: 2.1076

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3753 - mae: 2.1080

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 7.3769 - mae: 2.1088 - val_loss: 8.6598 - val_mae: 2.2996

Epoch 22/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 22s 43ms/step - loss: 6.2947 - mae: 2.1145

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.3517 - mae: 2.1492

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.5768 - mae: 2.0410

 31/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9411 - mae: 2.0457

 41/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.4943 - mae: 1.9515

 51/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.9527 - mae: 2.0116

 61/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.8819 - mae: 1.9975

 71/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0748 - mae: 2.0377

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.5115 - mae: 2.0925

 91/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.2240 - mae: 2.0550

101/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0220 - mae: 2.0178

110/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 6.8825 - mae: 2.0083

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.0968 - mae: 2.0354

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1580 - mae: 2.0449

140/522 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 7.1923 - mae: 2.0565

150/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.2147 - mae: 2.0653

160/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3014 - mae: 2.0859

170/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.2749 - mae: 2.0909

180/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4398 - mae: 2.1049

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4419 - mae: 2.1046

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5232 - mae: 2.1136

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5900 - mae: 2.1257

219/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5513 - mae: 2.1244

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5286 - mae: 2.1181

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5358 - mae: 2.1136

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.5275 - mae: 2.1210

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4528 - mae: 2.1051

269/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4751 - mae: 2.1130

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4941 - mae: 2.1189

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4395 - mae: 2.1139

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4405 - mae: 2.1136

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.4218 - mae: 2.1122

317/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3411 - mae: 2.1015

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7.3019 - mae: 2.0932

337/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3223 - mae: 2.0969

347/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3447 - mae: 2.0956

358/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3536 - mae: 2.0957

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3225 - mae: 2.0915

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2679 - mae: 2.0855

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2892 - mae: 2.0878

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2725 - mae: 2.0885

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2132 - mae: 2.0791

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2191 - mae: 2.0820

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2433 - mae: 2.0845

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2451 - mae: 2.0863

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2179 - mae: 2.0820

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1890 - mae: 2.0784

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1981 - mae: 2.0780

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.1748 - mae: 2.0759

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2152 - mae: 2.0825

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2059 - mae: 2.0824

509/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2591 - mae: 2.0947

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2504 - mae: 2.0936

522/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.2576 - mae: 2.0953 - val_loss: 8.2296 - val_mae: 2.2410

Epoch 22: early stopping

Restoring model weights from the end of the best epoch: 12.

In [18]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 3s 335ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step

MAE:  2.0859979574192953

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# LSTM two layer model

In [19]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = 1

# define model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, input_shape=(n_steps,n_features))) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(Conv1D(filters=32, kernel_size=3)) # notice how input shape goes in first layer
model.add(MaxPooling1D())
model.add(LSTM(30,
               return_sequences=True, # remember, if stacking layers, you need to return sequences!
               input_shape=(n_steps,n_features),
               activation='relu'))
model.add(Dropout(0.1))
model.add(LSTM(20, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)
# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

Epoch 1/500

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

  1/522 ━━━━━━━━━━━━━━━━━━━━ 32:17 4s/step - loss: 132.0573 - mae: 11.0949

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 63.8135 - mae: 6.8632

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 42.7958 - mae: 5.2864

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 40.3911 - mae: 5.0635

 38/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 33.8955 - mae: 4.5822

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 30.7484 - mae: 4.3462

 56/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 28.4100 - mae: 4.1560

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 27.8263 - mae: 4.1190

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 26.5503 - mae: 3.9924

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 25.5377 - mae: 3.9231

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 24.1943 - mae: 3.8068

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 23.2993 - mae: 3.7219

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 22.2919 - mae: 3.6168

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 21.8163 - mae: 3.5863

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 21.1353 - mae: 3.5142

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 20.7598 - mae: 3.4862

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 20.4123 - mae: 3.4646

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 20.0455 - mae: 3.4279

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 19.6160 - mae: 3.3990

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 19.4729 - mae: 3.3924

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 19.3211 - mae: 3.3888

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 18.9354 - mae: 3.3444

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 18.5865 - mae: 3.3072

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 18.5480 - mae: 3.3099

212/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 18.2781 - mae: 3.2851

221/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 18.3498 - mae: 3.2776

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 18.2206 - mae: 3.2703

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.9413 - mae: 3.2495

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.6906 - mae: 3.2332

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.5211 - mae: 3.2096

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.2920 - mae: 3.1915

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.3053 - mae: 3.2011

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.1680 - mae: 3.1876

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.0638 - mae: 3.1783

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 17.0117 - mae: 3.1727

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 16.8596 - mae: 3.1576

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 16.5509 - mae: 3.1239

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 16.4753 - mae: 3.1139

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 16.6012 - mae: 3.1212

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 16.5783 - mae: 3.1166

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.3961 - mae: 3.1014

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.2674 - mae: 3.0882

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.3608 - mae: 3.0977

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.2392 - mae: 3.0863

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.2586 - mae: 3.0878

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.1709 - mae: 3.0804

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.0101 - mae: 3.0647

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.1337 - mae: 3.0751

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.0619 - mae: 3.0710

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.9744 - mae: 3.0658

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.9239 - mae: 3.0624

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.7667 - mae: 3.0457

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.7998 - mae: 3.0506

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.7071 - mae: 3.0439

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.5859 - mae: 3.0320

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.5362 - mae: 3.0265

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.4559 - mae: 3.0211

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.5066 - mae: 3.0319

515/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 15.3917 - mae: 3.0201

522/522 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - loss: 15.3816 - mae: 3.0217 - val_loss: 7.7755 - val_mae: 2.1802

Epoch 2/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 6.7153 - mae: 2.1111

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.4175 - mae: 3.0425

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.7243 - mae: 3.0092

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.8020 - mae: 2.9343

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.6277 - mae: 2.9043

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.3772 - mae: 2.9095

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.1194 - mae: 2.9221

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.8223 - mae: 2.8963

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.8446 - mae: 2.8993

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.3089 - mae: 2.9552

 91/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.0713 - mae: 2.9376

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.5544 - mae: 2.8826

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.0088 - mae: 2.8211

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.3393 - mae: 2.8562

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.2023 - mae: 2.8489

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.1889 - mae: 2.8519

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.1232 - mae: 2.8549

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.1201 - mae: 2.8520

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.3123 - mae: 2.8574

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.4069 - mae: 2.8789

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 13.4345 - mae: 2.8762

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.3389 - mae: 2.8677

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.2202 - mae: 2.8530

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.2761 - mae: 2.8629

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.1746 - mae: 2.8600

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.2234 - mae: 2.8620

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.1888 - mae: 2.8439

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.1314 - mae: 2.8404

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 13.0481 - mae: 2.8350

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.8824 - mae: 2.8061

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.8530 - mae: 2.7997

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.9324 - mae: 2.8103

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.8724 - mae: 2.8041

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.8605 - mae: 2.8038

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.7311 - mae: 2.7913

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.6243 - mae: 2.7775

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.6258 - mae: 2.7746

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.6055 - mae: 2.7779

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.5872 - mae: 2.7779

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.5774 - mae: 2.7724

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5840 - mae: 2.7751

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5699 - mae: 2.7731

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5857 - mae: 2.7772

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5586 - mae: 2.7783

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6383 - mae: 2.7882

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5535 - mae: 2.7784

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4850 - mae: 2.7707

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5391 - mae: 2.7788

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4719 - mae: 2.7705

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5448 - mae: 2.7760

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6801 - mae: 2.7901

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.6145 - mae: 2.7827

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5721 - mae: 2.7785

468/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5429 - mae: 2.7753

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4860 - mae: 2.7690

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4573 - mae: 2.7644

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.5011 - mae: 2.7704

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4620 - mae: 2.7665

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4739 - mae: 2.7674

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4847 - mae: 2.7694

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 12.4807 - mae: 2.7689 - val_loss: 7.2781 - val_mae: 2.1037

Epoch 3/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 8.5753 - mae: 2.5999

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 14.8678 - mae: 3.0551

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.5328 - mae: 2.8437

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.8517 - mae: 2.8793

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0156 - mae: 2.7199

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0833 - mae: 2.7282

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0095 - mae: 2.7437

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.8049 - mae: 2.7246

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.8047 - mae: 2.7033

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.4396 - mae: 2.7735

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.2768 - mae: 2.7434

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.2824 - mae: 2.7166

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0552 - mae: 2.7011

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.3646 - mae: 2.7126

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.2718 - mae: 2.7005

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.2152 - mae: 2.6886

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0709 - mae: 2.6851

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1702 - mae: 2.7124

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0742 - mae: 2.7018

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1296 - mae: 2.7143

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1875 - mae: 2.7145

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.9963 - mae: 2.6975

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.0326 - mae: 2.7058

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8951 - mae: 2.6865

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8725 - mae: 2.6887

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8104 - mae: 2.6857

230/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.9747 - mae: 2.6951

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8751 - mae: 2.6838

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.7370 - mae: 2.6717

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.7587 - mae: 2.6697

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.6225 - mae: 2.6504

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.6731 - mae: 2.6519

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.6549 - mae: 2.6515

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.5885 - mae: 2.6464

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.5157 - mae: 2.6393

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4590 - mae: 2.6327

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3476 - mae: 2.6210

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2823 - mae: 2.6162

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3985 - mae: 2.6287

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4659 - mae: 2.6366

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4466 - mae: 2.6305

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4626 - mae: 2.6362

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4921 - mae: 2.6383

381/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4472 - mae: 2.6316

390/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4952 - mae: 2.6374

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4299 - mae: 2.6313

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3254 - mae: 2.6216

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3431 - mae: 2.6245

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2924 - mae: 2.6170

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3028 - mae: 2.6192

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2800 - mae: 2.6200

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2432 - mae: 2.6143

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2198 - mae: 2.6131

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2189 - mae: 2.6134

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1683 - mae: 2.6071

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1248 - mae: 2.6033

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1678 - mae: 2.6098

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1185 - mae: 2.6044

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.1051 - mae: 2.6045

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.0760 - mae: 2.6004

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 11.0787 - mae: 2.6018 - val_loss: 8.0566 - val_mae: 2.2006

Epoch 4/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 12.8675 - mae: 2.8066

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 14.8459 - mae: 3.0731

 19/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 13.2066 - mae: 2.9214

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.8034 - mae: 2.8118

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.2001 - mae: 2.6297

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.5966 - mae: 2.6675

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7030 - mae: 2.6945

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.4142 - mae: 2.6532

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.4539 - mae: 2.6653

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.9736 - mae: 2.7091

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.8119 - mae: 2.6949

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7225 - mae: 2.6629

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.6446 - mae: 2.6565

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7957 - mae: 2.6626

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7299 - mae: 2.6577

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7692 - mae: 2.6750

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.7224 - mae: 2.6698

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.8843 - mae: 2.6910

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.8319 - mae: 2.6883

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0376 - mae: 2.7275

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1823 - mae: 2.7460

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1387 - mae: 2.7376

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.1295 - mae: 2.7278

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.0461 - mae: 2.7218

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.9437 - mae: 2.7199

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.9157 - mae: 2.7171

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 12.0194 - mae: 2.7151

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8586 - mae: 2.6977

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8453 - mae: 2.7053

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.8628 - mae: 2.7006

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.7401 - mae: 2.6842

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.6221 - mae: 2.6755

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.5890 - mae: 2.6742

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4479 - mae: 2.6593

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.4332 - mae: 2.6567

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3722 - mae: 2.6527

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2449 - mae: 2.6351

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1568 - mae: 2.6267

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2276 - mae: 2.6325

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2894 - mae: 2.6351

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3442 - mae: 2.6355

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3924 - mae: 2.6387

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4960 - mae: 2.6510

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3752 - mae: 2.6367

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3372 - mae: 2.6296

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3444 - mae: 2.6294

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3052 - mae: 2.6204

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3827 - mae: 2.6315

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4144 - mae: 2.6321

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.5050 - mae: 2.6412

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.5387 - mae: 2.6445

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.5051 - mae: 2.6374

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4266 - mae: 2.6293

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3920 - mae: 2.6264

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3113 - mae: 2.6162

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3336 - mae: 2.6206

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2598 - mae: 2.6098

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2803 - mae: 2.6141

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.2359 - mae: 2.6100

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 11.2227 - mae: 2.6111 - val_loss: 6.4478 - val_mae: 1.9591

Epoch 5/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 7.6691 - mae: 1.7322

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 13.9426 - mae: 2.9334

 18/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 11.6331 - mae: 2.6631

 27/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 11.3716 - mae: 2.5440

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.5247 - mae: 2.4678

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.0446 - mae: 2.4281

 52/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.2011 - mae: 2.4565

 61/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.9379 - mae: 2.4411

 70/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.9292 - mae: 2.4584

 79/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.3411 - mae: 2.5695

 87/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.3862 - mae: 2.5803

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.1809 - mae: 2.5673

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9594 - mae: 2.5465

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8490 - mae: 2.5473

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.1346 - mae: 2.5607

132/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.0509 - mae: 2.5544

141/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9692 - mae: 2.5572

150/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9356 - mae: 2.5616

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.1943 - mae: 2.5814

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.2426 - mae: 2.5862

176/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.3211 - mae: 2.5835

185/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.2727 - mae: 2.5815

194/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3814 - mae: 2.6033

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2846 - mae: 2.5893

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2064 - mae: 2.5879

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1432 - mae: 2.5891

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1242 - mae: 2.5903

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.3195 - mae: 2.5955

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2285 - mae: 2.5922

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.2241 - mae: 2.5920

265/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1476 - mae: 2.5833

274/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1627 - mae: 2.5849

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.1164 - mae: 2.5836

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 11.0517 - mae: 2.5749

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.9811 - mae: 2.5714

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.9429 - mae: 2.5671

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.7925 - mae: 2.5453

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.7396 - mae: 2.5382

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.8149 - mae: 2.5447

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.7628 - mae: 2.5397

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.6919 - mae: 2.5322

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.6874 - mae: 2.5298

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.7106 - mae: 2.5291

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5898 - mae: 2.5120

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5191 - mae: 2.5060

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5013 - mae: 2.5049

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.3947 - mae: 2.4871

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4417 - mae: 2.4934

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.3662 - mae: 2.4836

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4202 - mae: 2.4919

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4936 - mae: 2.4933

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4566 - mae: 2.4901

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4327 - mae: 2.4877

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4452 - mae: 2.4900

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4695 - mae: 2.4962

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5056 - mae: 2.5027

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.5040 - mae: 2.5046

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4759 - mae: 2.5032

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4535 - mae: 2.5017

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4216 - mae: 2.4960

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 10.4254 - mae: 2.4972 - val_loss: 6.4514 - val_mae: 1.9634

Epoch 6/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 9.2262 - mae: 2.6852

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.0998 - mae: 2.8782

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.1543 - mae: 2.7002

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.7151 - mae: 2.7436

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9699 - mae: 2.5390

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.5397 - mae: 2.5114

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8385 - mae: 2.5444

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8187 - mae: 2.5330

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9513 - mae: 2.5757

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.4462 - mae: 2.6213

 91/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.2475 - mae: 2.6066

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.0290 - mae: 2.5785

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8744 - mae: 2.5658

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.0764 - mae: 2.5761

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.8450 - mae: 2.5504

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.9518 - mae: 2.5750

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.7914 - mae: 2.5623

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.7669 - mae: 2.5653

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.7709 - mae: 2.5712

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.5527 - mae: 2.5421

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.8723 - mae: 2.5732

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.8432 - mae: 2.5784

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.8993 - mae: 2.5849

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.8001 - mae: 2.5785

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.7449 - mae: 2.5703

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.6567 - mae: 2.5599

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.7079 - mae: 2.5667

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.6107 - mae: 2.5550

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.5416 - mae: 2.5483

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.5391 - mae: 2.5473

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.5370 - mae: 2.5462

278/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.4927 - mae: 2.5369

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.3855 - mae: 2.5258

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.3891 - mae: 2.5224

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.3437 - mae: 2.5164

313/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.3197 - mae: 2.5149

322/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.2757 - mae: 2.5022

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.2419 - mae: 2.5004

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.1774 - mae: 2.4933

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.1916 - mae: 2.4927

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2137 - mae: 2.4986

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1259 - mae: 2.4899

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1826 - mae: 2.4963

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0914 - mae: 2.4828

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2019 - mae: 2.4978

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1829 - mae: 2.4937

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1660 - mae: 2.4905

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1820 - mae: 2.4917

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1995 - mae: 2.4917

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1536 - mae: 2.4879

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.1094 - mae: 2.4822

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0795 - mae: 2.4779

461/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0776 - mae: 2.4749

470/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0682 - mae: 2.4754

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0567 - mae: 2.4734

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0620 - mae: 2.4758

495/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0097 - mae: 2.4700

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.0394 - mae: 2.4724

513/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.9723 - mae: 2.4639

522/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.9908 - mae: 2.4648

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 9.9908 - mae: 2.4648 - val_loss: 6.2120 - val_mae: 1.9334

Epoch 7/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 10.0162 - mae: 2.2519

  8/522 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 10.7223 - mae: 2.7700

 16/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 11.1047 - mae: 2.7791

 23/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.8906 - mae: 2.5727

 30/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0586 - mae: 2.4468

 37/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.0297 - mae: 2.3877

 45/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3367 - mae: 2.3927

 54/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3807 - mae: 2.4000

 62/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.2977 - mae: 2.3804

 71/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5274 - mae: 2.4176

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.8233 - mae: 2.4480

 89/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1927 - mae: 2.4949

 97/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.8869 - mae: 2.4514

105/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.8702 - mae: 2.4453

114/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.7294 - mae: 2.4288

123/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.9880 - mae: 2.4464

131/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0674 - mae: 2.4612

140/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.9715 - mae: 2.4541

148/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.9837 - mae: 2.4683

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0424 - mae: 2.4686

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.0117 - mae: 2.4716

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.8557 - mae: 2.4502

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1490 - mae: 2.4842

188/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.1249 - mae: 2.4926

197/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10.2084 - mae: 2.4992

206/522 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9.9634 - mae: 2.4643

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9303 - mae: 2.4625

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.8564 - mae: 2.4551

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9835 - mae: 2.4606

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 10.0055 - mae: 2.4619

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9630 - mae: 2.4615

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9043 - mae: 2.4535

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.8490 - mae: 2.4473

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9115 - mae: 2.4576

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.8580 - mae: 2.4516

295/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.8092 - mae: 2.4482

304/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.7750 - mae: 2.4477

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.7217 - mae: 2.4414

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6631 - mae: 2.4366

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6557 - mae: 2.4349

338/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6628 - mae: 2.4342

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6752 - mae: 2.4296

354/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6428 - mae: 2.4250

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6217 - mae: 2.4206

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6229 - mae: 2.4220

376/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5795 - mae: 2.4179

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5188 - mae: 2.4114

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6391 - mae: 2.4252

399/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6558 - mae: 2.4290

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5849 - mae: 2.4176

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6207 - mae: 2.4255

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6263 - mae: 2.4283

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.6407 - mae: 2.4308

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5815 - mae: 2.4227

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5499 - mae: 2.4196

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5846 - mae: 2.4260

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5900 - mae: 2.4292

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5524 - mae: 2.4248

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5327 - mae: 2.4211

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5817 - mae: 2.4269

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5377 - mae: 2.4215

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5698 - mae: 2.4292

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.4859 - mae: 2.4138

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 9.5097 - mae: 2.4176 - val_loss: 6.0823 - val_mae: 1.8991

Epoch 8/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - loss: 8.2466 - mae: 2.1018

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 11.8008 - mae: 2.7628

 19/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.6168 - mae: 2.4849

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.7039 - mae: 2.4800

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6963 - mae: 2.3436

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8938 - mae: 2.3412

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4779 - mae: 2.4052

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3582 - mae: 2.3969

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.2764 - mae: 2.3997

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.8455 - mae: 2.4769

 89/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.8714 - mae: 2.4952

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.5904 - mae: 2.4470

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.6181 - mae: 2.4718

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4329 - mae: 2.4457

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4059 - mae: 2.4245

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.3987 - mae: 2.4292

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4649 - mae: 2.4365

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.7375 - mae: 2.4698

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.8664 - mae: 2.4914

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.8816 - mae: 2.4931

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.9369 - mae: 2.4877

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.0064 - mae: 2.5008

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9009 - mae: 2.4792

203/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.9230 - mae: 2.4798

211/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.8215 - mae: 2.4687

220/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.7711 - mae: 2.4675

229/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.7203 - mae: 2.4675

238/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.7267 - mae: 2.4622

247/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.6367 - mae: 2.4551

255/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.5499 - mae: 2.4402

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.5716 - mae: 2.4446

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.5903 - mae: 2.4467

280/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.5092 - mae: 2.4370

289/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.4151 - mae: 2.4259

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.3667 - mae: 2.4189

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2361 - mae: 2.3989

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1490 - mae: 2.3925

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1136 - mae: 2.3802

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1669 - mae: 2.3865

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1362 - mae: 2.3831

345/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.0857 - mae: 2.3758

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1655 - mae: 2.3826

360/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1324 - mae: 2.3746

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.1415 - mae: 2.3741

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0434 - mae: 2.3592

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0265 - mae: 2.3571

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0764 - mae: 2.3635

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0377 - mae: 2.3593

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0543 - mae: 2.3640

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0063 - mae: 2.3576

430/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0399 - mae: 2.3590

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0630 - mae: 2.3627

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0527 - mae: 2.3603

452/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.0400 - mae: 2.3597

459/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9814 - mae: 2.3501

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9872 - mae: 2.3507

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9807 - mae: 2.3544

479/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9703 - mae: 2.3540

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9521 - mae: 2.3515

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9340 - mae: 2.3511

497/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9148 - mae: 2.3500

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9335 - mae: 2.3530

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9475 - mae: 2.3563

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9145 - mae: 2.3516

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.8851 - mae: 2.3476

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 8.9180 - mae: 2.3530 - val_loss: 6.1693 - val_mae: 1.9162

Epoch 9/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 21s 40ms/step - loss: 9.4579 - mae: 2.4856

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.7147 - mae: 2.6665

 17/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.5942 - mae: 2.6345

 25/522 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 9.3501 - mae: 2.5699

 34/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.4035 - mae: 2.4224

 43/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.7766 - mae: 2.4371

 51/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9441 - mae: 2.4455

 59/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7529 - mae: 2.4097

 67/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5978 - mae: 2.3739

 76/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0188 - mae: 2.4155

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1832 - mae: 2.4312

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1946 - mae: 2.4374

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9908 - mae: 2.4003

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9288 - mae: 2.3936

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1557 - mae: 2.4132

130/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1514 - mae: 2.4114

139/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0047 - mae: 2.3838

148/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9922 - mae: 2.3919

157/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9358 - mae: 2.3916

166/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0528 - mae: 2.3991

175/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9767 - mae: 2.3859

184/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9799 - mae: 2.3816

192/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.1082 - mae: 2.4007

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.0299 - mae: 2.3845

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1860 - mae: 2.4023

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.2308 - mae: 2.4101

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1170 - mae: 2.3947

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1287 - mae: 2.3948

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.0107 - mae: 2.3811

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9684 - mae: 2.3827

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9531 - mae: 2.3826

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9640 - mae: 2.3760

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8812 - mae: 2.3616

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7833 - mae: 2.3449

299/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8135 - mae: 2.3491

308/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7966 - mae: 2.3485

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7459 - mae: 2.3402

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6460 - mae: 2.3220

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7093 - mae: 2.3321

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7010 - mae: 2.3301

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7167 - mae: 2.3255

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6884 - mae: 2.3223

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6710 - mae: 2.3167

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6005 - mae: 2.3075

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6058 - mae: 2.3065

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6470 - mae: 2.3069

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6772 - mae: 2.3127

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7408 - mae: 2.3214

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7222 - mae: 2.3163

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.8034 - mae: 2.3265

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.8218 - mae: 2.3289

450/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.8164 - mae: 2.3284

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7757 - mae: 2.3224

467/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7381 - mae: 2.3193

476/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7390 - mae: 2.3200

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7726 - mae: 2.3257

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7614 - mae: 2.3236

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7439 - mae: 2.3240

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.7155 - mae: 2.3214

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6857 - mae: 2.3176

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.7035 - mae: 2.3193 - val_loss: 6.3159 - val_mae: 1.9618

Epoch 10/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 12.3498 - mae: 2.9098

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 12.1390 - mae: 2.7746

 20/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6961 - mae: 2.2863

 30/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3951 - mae: 2.2923

 38/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6450 - mae: 2.3127

 47/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6648 - mae: 2.3155

 56/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7203 - mae: 2.3066

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4888 - mae: 2.2756

 74/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7816 - mae: 2.3246

 83/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0429 - mae: 2.3457

 92/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9527 - mae: 2.3440

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6420 - mae: 2.2898

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3487 - mae: 2.2445

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6336 - mae: 2.2706

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6486 - mae: 2.2752

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7543 - mae: 2.2933

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7950 - mae: 2.3113

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.8703 - mae: 2.3403

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.9484 - mae: 2.3593

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7932 - mae: 2.3349

181/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0630 - mae: 2.3721

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9728 - mae: 2.3587

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1381 - mae: 2.3734

208/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.1099 - mae: 2.3701

217/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 9.0730 - mae: 2.3692

226/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9619 - mae: 2.3537

235/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9872 - mae: 2.3518

244/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8957 - mae: 2.3413

253/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8692 - mae: 2.3359

261/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8877 - mae: 2.3344

270/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8198 - mae: 2.3250

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8021 - mae: 2.3240

287/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7196 - mae: 2.3106

296/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6022 - mae: 2.2954

305/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5773 - mae: 2.2968

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5437 - mae: 2.2945

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4283 - mae: 2.2748

333/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4173 - mae: 2.2766

342/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4495 - mae: 2.2821

351/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4457 - mae: 2.2773

360/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4218 - mae: 2.2742

369/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4131 - mae: 2.2714

378/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3789 - mae: 2.2630

387/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3495 - mae: 2.2592

396/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3967 - mae: 2.2624

405/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3497 - mae: 2.2567

414/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4284 - mae: 2.2712

423/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4152 - mae: 2.2692

432/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4483 - mae: 2.2701

441/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4605 - mae: 2.2748

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4457 - mae: 2.2714

458/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4499 - mae: 2.2729

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4303 - mae: 2.2704

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4652 - mae: 2.2763

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4873 - mae: 2.2777

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5061 - mae: 2.2820

502/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5087 - mae: 2.2818

511/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4930 - mae: 2.2832

520/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4945 - mae: 2.2840

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.4977 - mae: 2.2838 - val_loss: 5.8472 - val_mae: 1.8650

Epoch 11/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 38ms/step - loss: 6.4633 - mae: 2.1815

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.8739 - mae: 2.6305

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6482 - mae: 2.2539

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7201 - mae: 2.2380

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1436 - mae: 2.1546

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4843 - mae: 2.1859

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8978 - mae: 2.2209

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0783 - mae: 2.2368

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8955 - mae: 2.2208

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3687 - mae: 2.2833

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4817 - mae: 2.3101

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2456 - mae: 2.2688

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1666 - mae: 2.2568

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3508 - mae: 2.2599

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2172 - mae: 2.2504

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2071 - mae: 2.2543

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2062 - mae: 2.2553

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3211 - mae: 2.2687

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3536 - mae: 2.2839

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2680 - mae: 2.2710

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4041 - mae: 2.2848

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5290 - mae: 2.3072

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5655 - mae: 2.3090

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4792 - mae: 2.2948

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3956 - mae: 2.2840

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3198 - mae: 2.2718

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5098 - mae: 2.2849

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4891 - mae: 2.2833

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4924 - mae: 2.2895

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4607 - mae: 2.2833

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4114 - mae: 2.2768

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4552 - mae: 2.2860

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3950 - mae: 2.2788

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4533 - mae: 2.2869

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4232 - mae: 2.2852

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3312 - mae: 2.2727

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3544 - mae: 2.2715

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2975 - mae: 2.2645

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2398 - mae: 2.2545

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2776 - mae: 2.2555

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2494 - mae: 2.2504

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2718 - mae: 2.2530

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2851 - mae: 2.2534

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2152 - mae: 2.2388

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2466 - mae: 2.2438

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2484 - mae: 2.2429

408/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1826 - mae: 2.2320

417/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2357 - mae: 2.2402

426/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2881 - mae: 2.2457

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3425 - mae: 2.2525

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3401 - mae: 2.2515

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3313 - mae: 2.2524

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3078 - mae: 2.2508

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3001 - mae: 2.2533

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2782 - mae: 2.2507

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3148 - mae: 2.2554

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2617 - mae: 2.2486

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2737 - mae: 2.2519

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2397 - mae: 2.2460

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.2345 - mae: 2.2465 - val_loss: 6.0105 - val_mae: 1.8951

Epoch 12/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - loss: 4.2431 - mae: 1.8605

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 10.2405 - mae: 2.5449

 18/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.4381 - mae: 2.2914

 27/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3064 - mae: 2.3312

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8395 - mae: 2.2692

 45/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7278 - mae: 2.2211

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8271 - mae: 2.2251

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5772 - mae: 2.1679

 72/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5984 - mae: 2.1722

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3327 - mae: 2.2374

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4198 - mae: 2.2684

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3832 - mae: 2.2472

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4384 - mae: 2.2690

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3590 - mae: 2.2660

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6005 - mae: 2.2846

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5305 - mae: 2.2715

143/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4418 - mae: 2.2666

152/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5796 - mae: 2.2857

161/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5787 - mae: 2.2923

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6303 - mae: 2.2985

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7267 - mae: 2.3087

187/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.7353 - mae: 2.3147

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8866 - mae: 2.3269

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9363 - mae: 2.3323

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9029 - mae: 2.3286

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8993 - mae: 2.3232

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9971 - mae: 2.3212

241/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.9240 - mae: 2.3171

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.8032 - mae: 2.3050

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7384 - mae: 2.2958

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.7038 - mae: 2.2954

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6800 - mae: 2.2937

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6393 - mae: 2.2896

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6050 - mae: 2.2847

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5639 - mae: 2.2801

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5122 - mae: 2.2726

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4398 - mae: 2.2596

329/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3604 - mae: 2.2520

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3467 - mae: 2.2506

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3287 - mae: 2.2493

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2872 - mae: 2.2364

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2637 - mae: 2.2349

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2913 - mae: 2.2378

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2741 - mae: 2.2338

391/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3546 - mae: 2.2518

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3429 - mae: 2.2511

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3112 - mae: 2.2493

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3537 - mae: 2.2591

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3523 - mae: 2.2554

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3604 - mae: 2.2558

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3928 - mae: 2.2587

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4107 - mae: 2.2613

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3805 - mae: 2.2610

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3549 - mae: 2.2589

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3635 - mae: 2.2622

489/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4119 - mae: 2.2673

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4047 - mae: 2.2675

507/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4265 - mae: 2.2720

516/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3642 - mae: 2.2608

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.3683 - mae: 2.2630 - val_loss: 6.0407 - val_mae: 1.9034

Epoch 13/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - loss: 7.1326 - mae: 2.1877

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 9.4877 - mae: 2.3835

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.0311 - mae: 2.0463

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3483 - mae: 2.1882

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7591 - mae: 2.1152

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9112 - mae: 2.1389

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7450 - mae: 2.0990

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7670 - mae: 2.1156

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9721 - mae: 2.1519

 81/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5449 - mae: 2.2199

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5941 - mae: 2.2471

 99/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3270 - mae: 2.2165

108/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3775 - mae: 2.2338

117/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6026 - mae: 2.2564

126/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4400 - mae: 2.2390

135/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4014 - mae: 2.2322

144/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3007 - mae: 2.2304

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3158 - mae: 2.2306

162/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3944 - mae: 2.2450

170/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3712 - mae: 2.2452

179/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4090 - mae: 2.2481

188/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4427 - mae: 2.2575

197/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6149 - mae: 2.2809

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5386 - mae: 2.2702

215/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5725 - mae: 2.2719

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5598 - mae: 2.2728

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5843 - mae: 2.2749

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4789 - mae: 2.2651

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4090 - mae: 2.2586

259/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3024 - mae: 2.2495

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3314 - mae: 2.2529

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3361 - mae: 2.2517

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2633 - mae: 2.2432

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3486 - mae: 2.2496

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2916 - mae: 2.2439

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2162 - mae: 2.2333

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2583 - mae: 2.2322

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2468 - mae: 2.2309

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2106 - mae: 2.2317

347/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2485 - mae: 2.2344

356/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2065 - mae: 2.2288

363/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1603 - mae: 2.2224

367/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1705 - mae: 2.2220

375/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1829 - mae: 2.2262

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2107 - mae: 2.2299

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2618 - mae: 2.2377

400/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2646 - mae: 2.2392

409/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2574 - mae: 2.2347

418/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2922 - mae: 2.2428

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3268 - mae: 2.2480

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3387 - mae: 2.2502

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3236 - mae: 2.2470

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2955 - mae: 2.2447

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2790 - mae: 2.2455

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2710 - mae: 2.2476

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2681 - mae: 2.2471

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2714 - mae: 2.2485

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2267 - mae: 2.2420

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1960 - mae: 2.2388

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1114 - mae: 2.2248

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.1282 - mae: 2.2289 - val_loss: 6.4332 - val_mae: 1.9888

Epoch 14/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - loss: 8.4820 - mae: 1.9606

  9/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.8120 - mae: 2.3588

 18/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.9528 - mae: 2.2800

 27/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5006 - mae: 2.3014

 36/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7916 - mae: 2.1880

 45/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5696 - mae: 2.0983

 54/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5383 - mae: 2.1027

 63/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6892 - mae: 2.1195

 71/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8949 - mae: 2.1352

 80/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5207 - mae: 2.2047

 89/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6337 - mae: 2.2391

 98/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5276 - mae: 2.2367

107/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2230 - mae: 2.2002

116/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0559 - mae: 2.1905

125/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2876 - mae: 2.2065

134/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2166 - mae: 2.2029

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1913 - mae: 2.2056

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2884 - mae: 2.2275

159/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3999 - mae: 2.2405

168/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4687 - mae: 2.2510

177/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4780 - mae: 2.2495

186/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5222 - mae: 2.2702

195/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6765 - mae: 2.2862

204/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6976 - mae: 2.2888

213/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6168 - mae: 2.2759

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6369 - mae: 2.2778

228/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6137 - mae: 2.2768

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6678 - mae: 2.2861

239/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.6611 - mae: 2.2866

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5903 - mae: 2.2850

256/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5642 - mae: 2.2806

264/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4731 - mae: 2.2688

273/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4522 - mae: 2.2662

282/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3964 - mae: 2.2628

291/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3500 - mae: 2.2560

300/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2966 - mae: 2.2535

309/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3236 - mae: 2.2556

318/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2348 - mae: 2.2415

327/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2065 - mae: 2.2360

336/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2276 - mae: 2.2412

344/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2586 - mae: 2.2491

353/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3127 - mae: 2.2513

362/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2929 - mae: 2.2493

371/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3055 - mae: 2.2498

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2705 - mae: 2.2413

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2950 - mae: 2.2431

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2819 - mae: 2.2409

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2668 - mae: 2.2391

412/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3344 - mae: 2.2488

420/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3225 - mae: 2.2458

429/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3852 - mae: 2.2556

438/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3932 - mae: 2.2577

447/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3995 - mae: 2.2571

456/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3552 - mae: 2.2531

464/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3505 - mae: 2.2551

473/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3506 - mae: 2.2567

482/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3961 - mae: 2.2618

491/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4083 - mae: 2.2658

498/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3686 - mae: 2.2621

506/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4508 - mae: 2.2704

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.4212 - mae: 2.2655

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.4612 - mae: 2.2702 - val_loss: 6.0914 - val_mae: 1.9222

Epoch 15/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 4.9844 - mae: 1.8057

 11/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 11.0261 - mae: 2.7564

 21/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3888 - mae: 2.3292

 30/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4863 - mae: 2.3478

 39/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8748 - mae: 2.2546

 48/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0688 - mae: 2.2496

 57/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0839 - mae: 2.2423

 66/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9811 - mae: 2.2201

 76/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4726 - mae: 2.2954

 85/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6538 - mae: 2.3180

 94/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3343 - mae: 2.2723

103/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1671 - mae: 2.2466

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9586 - mae: 2.2183

121/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1810 - mae: 2.2362

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1542 - mae: 2.2403

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1100 - mae: 2.2279

147/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0933 - mae: 2.2297

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1714 - mae: 2.2563

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3024 - mae: 2.2764

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2327 - mae: 2.2620

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2818 - mae: 2.2703

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2453 - mae: 2.2691

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4535 - mae: 2.2912

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4892 - mae: 2.2948

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4778 - mae: 2.2943

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4437 - mae: 2.2939

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5104 - mae: 2.3009

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4555 - mae: 2.2943

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4547 - mae: 2.2921

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3678 - mae: 2.2807

272/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3250 - mae: 2.2721

281/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2825 - mae: 2.2699

290/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1935 - mae: 2.2579

298/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1800 - mae: 2.2550

307/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1726 - mae: 2.2528

316/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1270 - mae: 2.2461

325/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0823 - mae: 2.2385

334/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1168 - mae: 2.2450

343/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1003 - mae: 2.2484

352/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0588 - mae: 2.2376

361/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0525 - mae: 2.2367

370/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0457 - mae: 2.2361

379/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0279 - mae: 2.2319

388/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0563 - mae: 2.2358

397/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0350 - mae: 2.2340

406/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9854 - mae: 2.2276

415/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0238 - mae: 2.2329

424/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9764 - mae: 2.2250

433/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9942 - mae: 2.2273

442/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9945 - mae: 2.2279

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9710 - mae: 2.2249

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9562 - mae: 2.2243

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9803 - mae: 2.2295

477/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9657 - mae: 2.2271

485/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9870 - mae: 2.2289

494/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0112 - mae: 2.2289

503/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9927 - mae: 2.2260

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9529 - mae: 2.2222

521/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9753 - mae: 2.2271

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.9766 - mae: 2.2275 - val_loss: 6.0047 - val_mae: 1.8961

Epoch 16/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 20s 39ms/step - loss: 14.8413 - mae: 2.4050

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 10.1330 - mae: 2.5117

 18/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5626 - mae: 2.2264

 27/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8096 - mae: 2.1561

 35/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2947 - mae: 2.1064

 44/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9826 - mae: 2.1679

 53/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1770 - mae: 2.1892

 61/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2065 - mae: 2.2005

 70/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8190 - mae: 2.1589

 79/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2463 - mae: 2.2017

 88/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4626 - mae: 2.2334

 97/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2295 - mae: 2.2015

106/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0801 - mae: 2.1809

115/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9041 - mae: 2.1635

124/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1304 - mae: 2.1774

133/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0109 - mae: 2.1704

142/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9130 - mae: 2.1638

151/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0367 - mae: 2.1815

160/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0820 - mae: 2.1936

169/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1018 - mae: 2.1992

178/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1997 - mae: 2.2033

187/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3187 - mae: 2.2241

196/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3802 - mae: 2.2336

205/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3317 - mae: 2.2284

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2800 - mae: 2.2236

223/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2864 - mae: 2.2252

232/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3608 - mae: 2.2323

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3449 - mae: 2.2337

248/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2874 - mae: 2.2297

257/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2294 - mae: 2.2186

266/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2550 - mae: 2.2251

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2121 - mae: 2.2216

283/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1646 - mae: 2.2171

292/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1652 - mae: 2.2211

301/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1578 - mae: 2.2249

310/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0873 - mae: 2.2183

319/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9405 - mae: 2.1908

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8971 - mae: 2.1860

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8969 - mae: 2.1914

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9585 - mae: 2.2022

355/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9192 - mae: 2.1955

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8800 - mae: 2.1903

372/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9113 - mae: 2.1993

380/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8745 - mae: 2.1950

389/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8849 - mae: 2.1942

398/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8803 - mae: 2.1936

407/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8305 - mae: 2.1846

416/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9432 - mae: 2.1992

425/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9682 - mae: 2.2008

434/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9983 - mae: 2.2039

443/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0148 - mae: 2.2032

451/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9976 - mae: 2.2037

460/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9935 - mae: 2.2064

469/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0024 - mae: 2.2106

478/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0053 - mae: 2.2107

487/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0265 - mae: 2.2129

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0094 - mae: 2.2098

505/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.0340 - mae: 2.2133

514/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9886 - mae: 2.2078

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.9794 - mae: 2.2073 - val_loss: 6.0656 - val_mae: 1.9186

Epoch 17/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 5.2175 - mae: 1.8578

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 11.5492 - mae: 2.7525

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.4238 - mae: 2.4080

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 9.0161 - mae: 2.3178

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3761 - mae: 2.2636

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.5056 - mae: 2.2899

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4958 - mae: 2.2693

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0818 - mae: 2.1977

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.0496 - mae: 2.2073

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6479 - mae: 2.2823

 91/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.6973 - mae: 2.2971

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4529 - mae: 2.2602

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3309 - mae: 2.2403

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.4259 - mae: 2.2457

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2534 - mae: 2.2183

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1816 - mae: 2.2135

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1158 - mae: 2.2087

153/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2433 - mae: 2.2249

162/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3704 - mae: 2.2570

171/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.2423 - mae: 2.2387

180/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.3089 - mae: 2.2461

189/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3896 - mae: 2.2585

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4139 - mae: 2.2569

206/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3151 - mae: 2.2419

214/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3716 - mae: 2.2533

222/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3718 - mae: 2.2504

231/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.5021 - mae: 2.2655

240/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.4461 - mae: 2.2591

249/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.3629 - mae: 2.2496

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2563 - mae: 2.2370

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.2274 - mae: 2.2325

275/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1681 - mae: 2.2253

284/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1205 - mae: 2.2192

293/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.1223 - mae: 2.2203

302/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0963 - mae: 2.2213

311/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0711 - mae: 2.2208

320/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0001 - mae: 2.2080

328/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9237 - mae: 2.1992

337/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8674 - mae: 2.1944

346/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9093 - mae: 2.2003

355/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8905 - mae: 2.1942

364/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8474 - mae: 2.1886

373/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8508 - mae: 2.1871

382/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7921 - mae: 2.1803

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9011 - mae: 2.1947

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9134 - mae: 2.1978

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8738 - mae: 2.1914

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9069 - mae: 2.1971

428/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9407 - mae: 2.1987

437/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9341 - mae: 2.1993

446/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8768 - mae: 2.1906

455/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8651 - mae: 2.1914

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8471 - mae: 2.1893

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8316 - mae: 2.1909

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8204 - mae: 2.1881

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9045 - mae: 2.1998

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8887 - mae: 2.1970

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8837 - mae: 2.1941

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8126 - mae: 2.1824

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.8217 - mae: 2.1842 - val_loss: 6.0610 - val_mae: 1.9191

Epoch 18/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 23s 44ms/step - loss: 3.2769 - mae: 1.5283

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.2074 - mae: 2.2620

 19/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 7.4685 - mae: 2.1670

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.7888 - mae: 2.0659

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.4075 - mae: 2.0004

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.8804 - mae: 2.0628

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2712 - mae: 2.1240

 65/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.9989 - mae: 2.0806

 75/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4349 - mae: 2.1568

 84/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8856 - mae: 2.2257

 93/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8432 - mae: 2.2272

102/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6593 - mae: 2.1934

111/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5184 - mae: 2.1703

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7359 - mae: 2.1854

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6792 - mae: 2.1794

138/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7006 - mae: 2.1761

147/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6615 - mae: 2.1753

156/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6681 - mae: 2.1791

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8730 - mae: 2.2145

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8793 - mae: 2.2078

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9607 - mae: 2.2210

191/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9551 - mae: 2.2267

199/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0521 - mae: 2.2393

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0554 - mae: 2.2422

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0693 - mae: 2.2385

224/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9921 - mae: 2.2268

233/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0648 - mae: 2.2320

242/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0327 - mae: 2.2288

250/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 8.0502 - mae: 2.2331

258/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9952 - mae: 2.2253

267/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.9626 - mae: 2.2200

276/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8993 - mae: 2.2097

285/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8112 - mae: 2.1962

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7743 - mae: 2.1934

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7143 - mae: 2.1841

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6634 - mae: 2.1791

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6021 - mae: 2.1688

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5874 - mae: 2.1671

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5895 - mae: 2.1679

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6855 - mae: 2.1806

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6593 - mae: 2.1744

366/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6598 - mae: 2.1733

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6813 - mae: 2.1761

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6258 - mae: 2.1672

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6678 - mae: 2.1731

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6970 - mae: 2.1785

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6859 - mae: 2.1757

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6573 - mae: 2.1709

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7201 - mae: 2.1752

436/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7339 - mae: 2.1757

445/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7565 - mae: 2.1767

454/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7699 - mae: 2.1811

463/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7793 - mae: 2.1866

472/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7426 - mae: 2.1812

481/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7413 - mae: 2.1802

490/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7618 - mae: 2.1846

499/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7436 - mae: 2.1832

508/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.7244 - mae: 2.1820

517/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6587 - mae: 2.1722

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.6832 - mae: 2.1761 - val_loss: 6.5540 - val_mae: 1.9944

Epoch 19/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 5.1528 - mae: 1.7461

 10/522 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 8.3935 - mae: 2.3056

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.9244 - mae: 2.1090

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1721 - mae: 2.1520

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.5639 - mae: 2.0589

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.9412 - mae: 2.0804

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.8564 - mae: 2.0571

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.7876 - mae: 2.0506

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.8393 - mae: 2.0667

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2570 - mae: 2.1347

 90/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2277 - mae: 2.1373

 96/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.0746 - mae: 2.1091

104/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1941 - mae: 2.1192

112/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1295 - mae: 2.0990

120/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2549 - mae: 2.0866

129/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2072 - mae: 2.0761

137/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2439 - mae: 2.0763

146/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.3095 - mae: 2.0884

155/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.3253 - mae: 2.0939

164/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5582 - mae: 2.1389

173/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6260 - mae: 2.1328

182/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7349 - mae: 2.1471

191/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6943 - mae: 2.1449

200/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7671 - mae: 2.1523

209/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7666 - mae: 2.1564

218/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7410 - mae: 2.1497

227/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6829 - mae: 2.1412

236/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7031 - mae: 2.1462

245/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6475 - mae: 2.1416

254/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6450 - mae: 2.1477

263/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6466 - mae: 2.1475

271/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6338 - mae: 2.1423

279/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5970 - mae: 2.1379

288/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4888 - mae: 2.1209

297/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4521 - mae: 2.1148

306/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.3991 - mae: 2.1113

315/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.3824 - mae: 2.1085

324/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.3093 - mae: 2.0975

332/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.2986 - mae: 2.0984

341/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.2556 - mae: 2.0964

350/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.3067 - mae: 2.1049

359/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2798 - mae: 2.1017

368/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2927 - mae: 2.1038

377/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2994 - mae: 2.1062

386/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2790 - mae: 2.1047

395/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3668 - mae: 2.1130

404/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3602 - mae: 2.1165

413/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3778 - mae: 2.1214

422/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3903 - mae: 2.1208

431/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4244 - mae: 2.1255

440/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4185 - mae: 2.1239

449/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4302 - mae: 2.1268

457/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4003 - mae: 2.1233

466/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3679 - mae: 2.1206

475/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3900 - mae: 2.1235

484/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3801 - mae: 2.1214

493/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3961 - mae: 2.1254

501/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3524 - mae: 2.1208

510/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3034 - mae: 2.1162

518/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2752 - mae: 2.1111

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.2783 - mae: 2.1127 - val_loss: 6.1073 - val_mae: 1.9348

Epoch 20/500

  1/522 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 1.0377 - mae: 0.7752

 10/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.3170 - mae: 2.0193

 19/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 6.1753 - mae: 1.9838

 28/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7976 - mae: 2.1277

 37/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.2625 - mae: 2.0795

 46/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.3638 - mae: 2.0863

 55/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4752 - mae: 2.0856

 64/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.1737 - mae: 2.0351

 73/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.4090 - mae: 2.0997

 82/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8293 - mae: 2.1729

 91/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 8.1232 - mae: 2.2301

100/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.8417 - mae: 2.1752

109/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7381 - mae: 2.1763

118/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.9446 - mae: 2.1851

127/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7672 - mae: 2.1495

136/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6759 - mae: 2.1391

145/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6477 - mae: 2.1378

154/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.6146 - mae: 2.1338

163/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.7221 - mae: 2.1526

172/522 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 7.5336 - mae: 2.1155

181/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6650 - mae: 2.1415

190/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7220 - mae: 2.1576

198/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.8152 - mae: 2.1649

207/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7172 - mae: 2.1538

216/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7428 - mae: 2.1641

225/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6588 - mae: 2.1489

234/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7019 - mae: 2.1466

243/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.7008 - mae: 2.1527

252/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6222 - mae: 2.1402

260/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6069 - mae: 2.1368

268/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6251 - mae: 2.1405

277/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6074 - mae: 2.1399

286/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5940 - mae: 2.1364

294/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6199 - mae: 2.1411

303/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.6120 - mae: 2.1451

312/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5565 - mae: 2.1402

321/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5187 - mae: 2.1313

330/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4625 - mae: 2.1221

339/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.4926 - mae: 2.1300

348/522 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.5275 - mae: 2.1335

357/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5426 - mae: 2.1341

365/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5125 - mae: 2.1303

374/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5342 - mae: 2.1322

383/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4989 - mae: 2.1265

392/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5961 - mae: 2.1363

401/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6187 - mae: 2.1409

410/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5981 - mae: 2.1399

419/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5967 - mae: 2.1408

427/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6643 - mae: 2.1475

435/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6505 - mae: 2.1476

444/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6649 - mae: 2.1479

453/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6792 - mae: 2.1511

462/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6583 - mae: 2.1504

471/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6508 - mae: 2.1483

480/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6572 - mae: 2.1493

488/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6727 - mae: 2.1539

496/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6304 - mae: 2.1482

504/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6067 - mae: 2.1463

512/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5676 - mae: 2.1410

519/522 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5854 - mae: 2.1437

522/522 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 7.5824 - mae: 2.1441 - val_loss: 5.8584 - val_mae: 1.8746

Epoch 20: early stopping

Restoring model weights from the end of the best epoch: 10.

In [20]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 3s 314ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step

MAE:  1.81413673458837

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [21]:
from keras.models import load_model

model.save('Univariate_Temperature_RNN_Advanced.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Univariate_Temperature_RNN_Advanced.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)               │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 12, 32)         │         3,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 6, 32)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 6, 30)          │         7,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 6, 30)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 20)             │         4,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44,681 (174.54 KB)

 Trainable params: 14,893 (58.18 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 29,788 (116.36 KB)

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [22]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Temp'].shift(1)
df.head()

         Date  Temp  Baseline
0  1981-01-01  20.7       NaN
1  1981-01-02  17.9      20.7
2  1981-01-03  18.8      17.9
3  1981-01-04  14.6      18.8
4  1981-01-05  15.8      14.6

In [23]:
# if you wanted to see how this model does, use df['Baseline'] for the pred
# here's how I'd do it
y_test_baseline = df['Baseline'].tail(y_test.shape[0])
# check your work
y_test_baseline.shape

(362,)

In [24]:
# check shapes, looks good!
y_test.shape

(362,)

In [25]:
# now set this equal to pred and repeat code!

# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = y_test_baseline # the pred
actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\583441606.py:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_34552\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

2.025414364640884

In [28]:
# our RNN models beats the baseline model!
# don't be FOOLED by the line plot... or model is 20% better than a dumb model!

# On Your Own
* Update the script to make some interesting comparisons of models - which one would you recommend to your boss?
* Can you analyze the distribution of errors instead of just MAE?
* Try even more architectures - play with number of filters, kernel size, number of layers, and see if you can beat 1.8 MAE.
* See if scalaing can help.