<img src="" width="100%" alt="OPIM 5509 banner"/>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/drdave-teaching/OPIM5509-notebooks/blob/main/Module4/Univariate_Temperature_RNN.ipynb)

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 6 — Univariate RNN Pt 1: the 3-D tensor and split_sequence
- Drop the window feature engineering - hand the RNN the raw sequence as a 3-D tensor and let it learn the temporal features (like the ConvNet learned image features).
- 3,650 daily temperatures, look-back 10 -> 3,640 samples of 10 x 1. split_sequence: [1,2,3] -> 4, [2,3,4] -> 5, oldest to newest.
- The reshape to add the trailing 1 is where 90% of RNN errors live - do it slowly on camera.
- Chronological 90/10: 3,276 train / 364 test.
-->

# Univariate Temperature Example (RNN)
-------------------------

**Dr. Dave Wanik - University of Connecticut**

Let's see if we can predict the next day's temperature as a function of N previous days.

Each of these is an example of a many-to-one classification (using a single feature with a lookback of N). This is the among the most tasks that need to be done with time series problems.

You could also try to implement a one-to-one by simply shifting the column by -1 then re-running (this is different than the baseline model we show at the end).

In [1]:
# standard modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# RNN-specific modules
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report,accuracy_score
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D
from tensorflow.keras.layers import Dense, Dropout, SimpleRNN, GRU, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# reproducibility: same seed every run (numbers on CPU match exactly; a GPU may drift a little)
import keras
keras.utils.set_random_seed(5509)

## Read in data
Check for missing values, make some plots.

In [2]:
# Dataset initially sourced from jbrownlee’s GitHub repository:
# url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv'
# Link to the data file on Github
url = "https://raw.githubusercontent.com/drdave-teaching/OPIM5509Files/refs/heads/main/OPIM5509_Module4_Files/data/daily-min-temperatures.csv"

# read the data
df = pd.read_csv(url)
print(df.info())
df.head(n=15) # nice complete data! this will allow us to check our work later

<class 'pandas.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   str
 1   Temp    3650 non-null   float64
dtypes: float64(1), str(1)
memory usage: 92.8 KB
None

          Date  Temp
0   1981-01-01  20.7
1   1981-01-02  17.9
2   1981-01-03  18.8
3   1981-01-04  14.6
4   1981-01-05  15.8
5   1981-01-06  15.8
6   1981-01-07  15.8
7   1981-01-08  17.4
8   1981-01-09  21.8
9   1981-01-10  20.0
10  1981-01-11  16.2
11  1981-01-12  13.3
12  1981-01-13  16.7
13  1981-01-14  21.5
14  1981-01-15  25.0

In [3]:
# visualize the data
df['Temp'].plot()
plt.show()

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\2877027861.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [4]:
# prep data for modeling (univariate)
# link: https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/

# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [5]:
# here's an example of how this script works
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90

In [6]:
# all we need to do is decide on is n_steps (what our lookback period is)
# since we have a bunch of data, why not n_steps=10? then try 30 later on.
n_steps = 10
raw_seq = df['Temp'] # the second column, where the data is. UPDATE THIS ON YOUR DATA!
# let's ignore the date column and just use the temperature data
X, y = split_sequence(raw_seq, n_steps)

In [7]:
# check out X and y shape
print(df.shape)
print(X.shape)

(3650, 2)
(3640, 10)

In [8]:
# take a peak at what it did
print(X[0])
print(y[0])

# scroll up and make sure you understand this!
# y is a function of X (the previous n_steps observations!)

[20.7 17.9 18.8 14.6 15.8 15.8 15.8 17.4 21.8 20. ]
16.2

In [9]:
# now we reshape the data into a 3D array
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1 # this is 1 because it is univariate data
X = X.reshape((X.shape[0], X.shape[1], n_features))
X.shape

(3640, 10, 1)

In [10]:
# split the data into train and test partitions
# we will use 90% of the data for train, and 10% for validation
train_pct_index = int(0.9 * len(X))
X_train, X_test = X[:train_pct_index], X[train_pct_index:]
y_train, y_test = y[:train_pct_index], y[train_pct_index:]

# pretty slick way of splitting your data using slicing!
# notice how we didn't do any shuffling (we don't want temporal leakage! keeps time series intact)

In [11]:
# check the shape to be sure
print(X.shape, X_train.shape, X_test.shape)

# verify that this all adds up!

(3640, 10, 1) (3276, 10, 1) (364, 10, 1)

In [12]:
# peak at it!
X_train[0]

array([[20.7],
       [17.9],
       [18.8],
       [14.6],
       [15.8],
       [15.8],
       [15.8],
       [17.4],
       [21.8],
       [20. ]])

In [13]:
y[0]

np.float64(16.2)

In [14]:
# if we wanted to, we could do some scaling/normalization here, would not hurt!

🔴
<!-- 🎙 DAVE TALKING POINTS — M4 · 7 — Univariate RNN Pt 2: fit SimpleRNN, then LSTM, then beat the baselines
- Confirm the tensor (3640, 10, 1); inherit n_steps and n_features FROM THE SHAPE; 30 red dots -> 31x30+30 params, spinning 10 times.
- Linear output, MSE loss, MAE tracked, early stopping on val_loss (20% of train as validation).
- SimpleRNN MAE ~1.77 vs the window method's ~1.76 - the same. One-word swap to LSTM -> ~1.74.
- The sermon: beat MEAN-ONLY and PERSISTENCE (shift-1, ~2.02) or you've learned nothing. A shifted copy looks great on a plot - always pair metric + scatter + time-series.
-->

# RNN one layer model

In [15]:
# samples, lookback, features
# samples = original rows in df - lookback period
# 3640 = 3650 - 10
X.shape

(3640, 10, 1)

In [16]:
# store these features for modeling
n_features = X.shape[2]
n_steps = X.shape[1]

print(n_steps, n_features)

10 1

In [17]:

# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before, but this is a better way)
n_features = X.shape[2] # 1 green dot
n_steps = X.shape[1] # 10 steps (not shown in the animation - this is how many times it loops)

# define model
model = Sequential()
model.add(SimpleRNN(30, input_shape=(n_steps,n_features), activation='relu')) # 30 red dots
model.add(Dense(1, activation='linear'))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the train data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 30)             │           960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 991 (3.87 KB)

 Trainable params: 991 (3.87 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 11:36 1s/step - loss: 92.7630 - mae: 9.0670

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21.8312 - mae: 3.5796

 43/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14.9030 - mae: 2.9138

 65/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.8282 - mae: 2.7438

 87/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.3956 - mae: 2.6158

108/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.5349 - mae: 2.5205

128/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.1524 - mae: 2.4800

148/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.6253 - mae: 2.4155

168/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.2511 - mae: 2.3681

188/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9809 - mae: 2.3279

209/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9092 - mae: 2.3218

229/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5550 - mae: 2.2712

249/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5076 - mae: 2.2664

269/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2601 - mae: 2.2262

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1061 - mae: 2.2037

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0601 - mae: 2.2022

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9859 - mae: 2.1933

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9146 - mae: 2.1917

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8527 - mae: 2.1844

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.7340 - mae: 2.1681

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6248 - mae: 2.1559

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5769 - mae: 2.1485

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6228 - mae: 2.1527

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4971 - mae: 2.1338

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4089 - mae: 2.1220

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3408 - mae: 2.1142

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 7.3304 - mae: 2.1151 - val_loss: 5.6334 - val_mae: 1.8702

Epoch 2/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 13.2829 - mae: 3.3985

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4824 - mae: 2.2121

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.5143 - mae: 2.2184

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.6021 - mae: 2.2181

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.5963 - mae: 2.2418

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3773 - mae: 2.2142

120/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3907 - mae: 2.1973

140/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.3320 - mae: 2.1862

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.1427 - mae: 2.1627

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0523 - mae: 2.1377

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0718 - mae: 2.1346

220/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0709 - mae: 2.1299

240/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9684 - mae: 2.1064

260/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8678 - mae: 2.0885

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8295 - mae: 2.0799

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7270 - mae: 2.0585

319/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8224 - mae: 2.0730

339/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7755 - mae: 2.0687

361/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7374 - mae: 2.0659

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7000 - mae: 2.0608

403/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6863 - mae: 2.0577

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6534 - mae: 2.0511

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7108 - mae: 2.0527

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6503 - mae: 2.0429

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5901 - mae: 2.0342

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5534 - mae: 2.0289

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.5357 - mae: 2.0275 - val_loss: 5.5176 - val_mae: 1.8575

Epoch 3/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 13.9532 - mae: 3.4841

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9582 - mae: 2.1219

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1532 - mae: 2.1663

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4220 - mae: 2.1868

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4349 - mae: 2.2156

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3295 - mae: 2.2043

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2834 - mae: 2.1762

139/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2074 - mae: 2.1641

159/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9996 - mae: 2.1370

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9147 - mae: 2.1124

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9259 - mae: 2.1062

219/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8808 - mae: 2.0976

239/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8142 - mae: 2.0785

259/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7244 - mae: 2.0616

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6621 - mae: 2.0502

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5662 - mae: 2.0292

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6776 - mae: 2.0464

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6275 - mae: 2.0437

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6235 - mae: 2.0443

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5459 - mae: 2.0325

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5605 - mae: 2.0341

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5304 - mae: 2.0279

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5930 - mae: 2.0300

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5428 - mae: 2.0225

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4538 - mae: 2.0090

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4313 - mae: 2.0054

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.4194 - mae: 2.0048 - val_loss: 5.4650 - val_mae: 1.8500

Epoch 4/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 14.2693 - mae: 3.5364

 18/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7747 - mae: 2.0865

 36/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1517 - mae: 2.1727

 54/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4154 - mae: 2.1844

 75/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4241 - mae: 2.1980

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3679 - mae: 2.2108

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2640 - mae: 2.1729

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2782 - mae: 2.1804

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0220 - mae: 2.1401

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8827 - mae: 2.1065

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8456 - mae: 2.0921

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8742 - mae: 2.0948

232/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6718 - mae: 2.0588

251/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7272 - mae: 2.0643

270/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5901 - mae: 2.0353

290/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5313 - mae: 2.0240

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5541 - mae: 2.0268

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5652 - mae: 2.0285

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5634 - mae: 2.0345

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5720 - mae: 2.0353

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5187 - mae: 2.0270

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4841 - mae: 2.0229

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4555 - mae: 2.0140

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5478 - mae: 2.0232

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4529 - mae: 2.0061

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4174 - mae: 2.0007

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3702 - mae: 1.9936

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3730 - mae: 1.9951 - val_loss: 5.4500 - val_mae: 1.8477

Epoch 5/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 14.3831 - mae: 3.5537

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0928 - mae: 2.1436

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1381 - mae: 2.1604

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3714 - mae: 2.1882

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3541 - mae: 2.1988

104/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1603 - mae: 2.1658

125/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1805 - mae: 2.1549

145/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0184 - mae: 2.1321

165/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8866 - mae: 2.1122

185/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8643 - mae: 2.0936

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7768 - mae: 2.0761

224/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7315 - mae: 2.0641

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7126 - mae: 2.0566

266/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5745 - mae: 2.0314

287/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5169 - mae: 2.0184

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5186 - mae: 2.0177

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5686 - mae: 2.0251

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5495 - mae: 2.0277

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5257 - mae: 2.0239

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4905 - mae: 2.0181

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4653 - mae: 2.0154

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4408 - mae: 2.0082

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5109 - mae: 2.0125

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4329 - mae: 1.9984

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4060 - mae: 1.9953

510/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3437 - mae: 1.9857

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3511 - mae: 1.9876 - val_loss: 5.4250 - val_mae: 1.8452

Epoch 6/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 13.9898 - mae: 3.5234

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6201 - mae: 2.0677

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8750 - mae: 2.1292

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2437 - mae: 2.1683

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3080 - mae: 2.1905

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2057 - mae: 2.1846

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1437 - mae: 2.1534

139/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0605 - mae: 2.1396

159/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8817 - mae: 2.1165

179/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7674 - mae: 2.0836

200/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7854 - mae: 2.0761

221/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7586 - mae: 2.0714

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6567 - mae: 2.0458

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5634 - mae: 2.0300

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5142 - mae: 2.0202

298/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4375 - mae: 2.0045

318/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5368 - mae: 2.0206

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5138 - mae: 2.0182

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4520 - mae: 2.0119

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4743 - mae: 2.0163

398/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4516 - mae: 2.0110

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4520 - mae: 2.0105

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4439 - mae: 2.0053

462/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4242 - mae: 1.9966

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3568 - mae: 1.9868

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3310 - mae: 1.9824

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3203 - mae: 1.9813

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3232 - mae: 1.9823 - val_loss: 5.4108 - val_mae: 1.8434

Epoch 7/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 13.9277 - mae: 3.5068

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5209 - mae: 2.0398

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8218 - mae: 2.1198

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3227 - mae: 2.1831

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3475 - mae: 2.1933

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2108 - mae: 2.1859

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1487 - mae: 2.1549

139/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0638 - mae: 2.1405

159/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8804 - mae: 2.1161

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7891 - mae: 2.0867

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7787 - mae: 2.0767

220/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7688 - mae: 2.0731

240/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6742 - mae: 2.0491

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5529 - mae: 2.0285

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5010 - mae: 2.0183

302/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4417 - mae: 2.0073

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5438 - mae: 2.0200

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4763 - mae: 2.0139

363/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4813 - mae: 2.0157

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4144 - mae: 2.0046

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4343 - mae: 2.0070

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4195 - mae: 2.0036

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4169 - mae: 1.9993

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4181 - mae: 1.9951

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3465 - mae: 1.9841

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3129 - mae: 1.9786

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3019 - mae: 1.9772

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3054 - mae: 1.9784 - val_loss: 5.4010 - val_mae: 1.8418

Epoch 8/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 13.5658 - mae: 3.4487

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8895 - mae: 2.1114

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9321 - mae: 2.1376

 63/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2575 - mae: 2.1657

 84/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2015 - mae: 2.1779

104/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0763 - mae: 2.1544

124/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1174 - mae: 2.1450

143/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9826 - mae: 2.1235

163/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8759 - mae: 2.1085

184/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7425 - mae: 2.0753

205/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7916 - mae: 2.0718

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6395 - mae: 2.0461

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6284 - mae: 2.0403

266/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4937 - mae: 2.0161

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4571 - mae: 2.0070

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4393 - mae: 2.0029

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4792 - mae: 2.0073

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4485 - mae: 2.0081

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4538 - mae: 2.0098

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3883 - mae: 1.9988

409/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3934 - mae: 2.0015

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3525 - mae: 1.9902

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4327 - mae: 1.9960

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3487 - mae: 1.9814

490/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3268 - mae: 1.9788

511/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2809 - mae: 1.9715

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2772 - mae: 1.9721 - val_loss: 5.3907 - val_mae: 1.8398

Epoch 9/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 13.4774 - mae: 3.4210

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8448 - mae: 2.1023

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8852 - mae: 2.1248

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1313 - mae: 2.1465

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1805 - mae: 2.1689

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9825 - mae: 2.1417

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0340 - mae: 2.1370

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9601 - mae: 2.1211

161/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8025 - mae: 2.1008

182/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7236 - mae: 2.0728

202/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7036 - mae: 2.0603

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6570 - mae: 2.0506

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6048 - mae: 2.0373

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4775 - mae: 2.0138

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4343 - mae: 2.0039

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4002 - mae: 1.9999

323/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4921 - mae: 2.0103

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4284 - mae: 2.0040

364/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4219 - mae: 2.0044

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3586 - mae: 1.9939

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3825 - mae: 1.9967

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3592 - mae: 1.9913

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4086 - mae: 1.9912

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3610 - mae: 1.9834

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2872 - mae: 1.9725

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2456 - mae: 1.9657

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2561 - mae: 1.9682 - val_loss: 5.3837 - val_mae: 1.8395

Epoch 10/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 13.1123 - mae: 3.3664

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7588 - mae: 2.0879

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8100 - mae: 2.1136

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0698 - mae: 2.1372

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1005 - mae: 2.1599

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9866 - mae: 2.1458

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0082 - mae: 2.1317

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0061 - mae: 2.1320

157/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8184 - mae: 2.1029

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7060 - mae: 2.0703

198/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7105 - mae: 2.0628

218/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6839 - mae: 2.0594

236/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5460 - mae: 2.0312

256/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5428 - mae: 2.0250

275/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4569 - mae: 2.0097

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3779 - mae: 1.9938

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4314 - mae: 2.0033

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4293 - mae: 2.0013

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3937 - mae: 1.9994

376/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4082 - mae: 2.0017

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3981 - mae: 2.0000

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3725 - mae: 1.9951

438/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3871 - mae: 1.9940

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3743 - mae: 1.9858

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2901 - mae: 1.9725

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2667 - mae: 1.9684

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2437 - mae: 1.9651

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2495 - mae: 1.9668 - val_loss: 5.3589 - val_mae: 1.8348

Epoch 11/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 12.5174 - mae: 3.2527

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7703 - mae: 2.0845

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7997 - mae: 2.1066

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1048 - mae: 2.1425

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0934 - mae: 2.1518

103/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9215 - mae: 2.1324

125/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0208 - mae: 2.1254

145/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8624 - mae: 2.1007

166/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7818 - mae: 2.0872

183/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6804 - mae: 2.0617

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6352 - mae: 2.0463

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5755 - mae: 2.0332

246/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5530 - mae: 2.0269

266/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4274 - mae: 2.0040

287/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3768 - mae: 1.9927

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3476 - mae: 1.9887

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4394 - mae: 1.9991

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3968 - mae: 1.9975

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4009 - mae: 1.9996

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3349 - mae: 1.9888

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3371 - mae: 1.9889

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2997 - mae: 1.9797

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3834 - mae: 1.9868

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2974 - mae: 1.9718

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2586 - mae: 1.9654

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2224 - mae: 1.9602

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2242 - mae: 1.9613 - val_loss: 5.3671 - val_mae: 1.8379

Epoch 12/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 12.8982 - mae: 3.3232

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8106 - mae: 2.0958

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8083 - mae: 2.1129

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0822 - mae: 2.1407

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0358 - mae: 2.1441

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8624 - mae: 2.1184

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9395 - mae: 2.1152

140/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8539 - mae: 2.0994

162/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7646 - mae: 2.0851

183/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6386 - mae: 2.0554

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5997 - mae: 2.0408

224/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5556 - mae: 2.0300

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5120 - mae: 2.0174

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4351 - mae: 2.0047

281/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3920 - mae: 1.9977

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3044 - mae: 1.9823

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4266 - mae: 1.9996

342/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3783 - mae: 1.9942

361/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3581 - mae: 1.9928

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3266 - mae: 1.9876

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3304 - mae: 1.9878

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3284 - mae: 1.9863

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2851 - mae: 1.9775

448/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3584 - mae: 1.9814

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3145 - mae: 1.9743

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2409 - mae: 1.9638

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2119 - mae: 1.9590

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2015 - mae: 1.9572

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2076 - mae: 1.9590 - val_loss: 5.3506 - val_mae: 1.8359

Epoch 13/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 12.9318 - mae: 3.3099

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4756 - mae: 2.0221

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7852 - mae: 2.1037

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0646 - mae: 2.1302

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1023 - mae: 2.1427

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9421 - mae: 2.1300

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9223 - mae: 2.1088

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8569 - mae: 2.0954

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7070 - mae: 2.0782

177/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6071 - mae: 2.0479

197/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6085 - mae: 2.0406

218/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5986 - mae: 2.0404

238/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5288 - mae: 2.0208

258/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4474 - mae: 2.0051

278/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3882 - mae: 1.9976

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2900 - mae: 1.9768

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4275 - mae: 1.9971

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3809 - mae: 1.9924

361/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3605 - mae: 1.9918

380/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3444 - mae: 1.9900

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3299 - mae: 1.9850

421/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3252 - mae: 1.9820

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3161 - mae: 1.9765

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3063 - mae: 1.9699

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2411 - mae: 1.9609

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2118 - mae: 1.9562

522/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2185 - mae: 1.9584

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2129 - mae: 1.9569 - val_loss: 5.3717 - val_mae: 1.8416

Epoch 14/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 12.9395 - mae: 3.3255

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6993 - mae: 2.0734

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7483 - mae: 2.0921

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0655 - mae: 2.1363

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0430 - mae: 2.1413

103/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8568 - mae: 2.1155

123/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9190 - mae: 2.1028

144/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8117 - mae: 2.0872

164/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6996 - mae: 2.0695

186/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6340 - mae: 2.0441

206/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6339 - mae: 2.0391

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5059 - mae: 2.0189

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4864 - mae: 2.0127

266/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3645 - mae: 1.9914

287/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3132 - mae: 1.9795

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3209 - mae: 1.9795

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3744 - mae: 1.9852

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3454 - mae: 1.9851

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3452 - mae: 1.9862

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3077 - mae: 1.9797

409/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3011 - mae: 1.9803

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2561 - mae: 1.9679

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3344 - mae: 1.9735

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2575 - mae: 1.9606

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2184 - mae: 1.9545

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1761 - mae: 1.9489

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1860 - mae: 1.9509 - val_loss: 5.3675 - val_mae: 1.8364

Epoch 15/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 12.6122 - mae: 3.2656

 22/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.6598 - mae: 2.0685

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7598 - mae: 2.0992

 64/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0435 - mae: 2.1248

 85/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9453 - mae: 2.1198

106/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9022 - mae: 2.1093

126/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8987 - mae: 2.0985

146/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7701 - mae: 2.0771

166/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6928 - mae: 2.0655

186/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6142 - mae: 2.0382

207/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6309 - mae: 2.0373

227/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4557 - mae: 2.0074

247/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5053 - mae: 2.0137

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3593 - mae: 1.9874

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2827 - mae: 1.9731

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3287 - mae: 1.9767

331/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3478 - mae: 1.9801

351/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3440 - mae: 1.9854

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3570 - mae: 1.9872

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3131 - mae: 1.9796

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2743 - mae: 1.9758

432/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2519 - mae: 1.9668

453/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3220 - mae: 1.9723

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2475 - mae: 1.9586

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2079 - mae: 1.9519

511/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1776 - mae: 1.9477

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1768 - mae: 1.9481 - val_loss: 5.3802 - val_mae: 1.8401

Epoch 16/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 13s 27ms/step - loss: 12.5230 - mae: 3.2460

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4226 - mae: 2.0096

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6775 - mae: 2.0839

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9794 - mae: 2.1138

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9687 - mae: 2.1251

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8641 - mae: 2.1127

120/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8577 - mae: 2.0944

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7624 - mae: 2.0738

161/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6310 - mae: 2.0600

182/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5488 - mae: 2.0330

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5221 - mae: 2.0214

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4559 - mae: 2.0082

246/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4373 - mae: 2.0036

266/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3209 - mae: 1.9831

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2859 - mae: 1.9749

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2455 - mae: 1.9684

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3453 - mae: 1.9806

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3045 - mae: 1.9784

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3001 - mae: 1.9788

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2754 - mae: 1.9747

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2560 - mae: 1.9728

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2361 - mae: 1.9653

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2772 - mae: 1.9637

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2281 - mae: 1.9555

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1799 - mae: 1.9488

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1371 - mae: 1.9426

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1436 - mae: 1.9439 - val_loss: 5.3483 - val_mae: 1.8367

Epoch 17/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 12.4325 - mae: 3.2452

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8570 - mae: 2.0967

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6929 - mae: 2.0901

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9996 - mae: 2.1157

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0081 - mae: 2.1270

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8543 - mae: 2.1067

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8563 - mae: 2.0904

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7753 - mae: 2.0720

163/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7013 - mae: 2.0640

184/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5608 - mae: 2.0319

205/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6146 - mae: 2.0309

226/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4602 - mae: 2.0062

247/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4815 - mae: 2.0080

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3314 - mae: 1.9816

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2721 - mae: 1.9695

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2800 - mae: 1.9698

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3316 - mae: 1.9756

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3085 - mae: 1.9757

361/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2973 - mae: 1.9761

376/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2956 - mae: 1.9759

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2928 - mae: 1.9749

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2322 - mae: 1.9676

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2219 - mae: 1.9609

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2916 - mae: 1.9644

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2166 - mae: 1.9519

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1812 - mae: 1.9472

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1369 - mae: 1.9410

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1465 - mae: 1.9425 - val_loss: 5.3360 - val_mae: 1.8314

Epoch 18/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 12.5951 - mae: 3.2902

 22/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7745 - mae: 2.0820

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7366 - mae: 2.0908

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0183 - mae: 2.1158

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9586 - mae: 2.1204

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8846 - mae: 2.1104

123/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8882 - mae: 2.0861

143/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7602 - mae: 2.0658

164/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6612 - mae: 2.0540

184/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5497 - mae: 2.0275

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5253 - mae: 2.0170

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4555 - mae: 2.0034

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4283 - mae: 1.9983

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3186 - mae: 1.9798

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2708 - mae: 1.9703

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2390 - mae: 1.9659

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3435 - mae: 1.9781

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2821 - mae: 1.9715

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2928 - mae: 1.9760

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2270 - mae: 1.9647

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2364 - mae: 1.9659

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2080 - mae: 1.9588

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2606 - mae: 1.9591

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2083 - mae: 1.9509

487/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1594 - mae: 1.9444

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1225 - mae: 1.9383

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1263 - mae: 1.9393 - val_loss: 5.3230 - val_mae: 1.8311

Epoch 19/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 11.8686 - mae: 3.1846

 22/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8774 - mae: 2.1084

 43/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8524 - mae: 2.1227

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0721 - mae: 2.1349

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9898 - mae: 2.1285

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9062 - mae: 2.1164

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9396 - mae: 2.0971

143/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7773 - mae: 2.0709

164/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6764 - mae: 2.0590

184/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5622 - mae: 2.0320

205/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6057 - mae: 2.0297

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4937 - mae: 2.0121

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4238 - mae: 1.9979

264/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3355 - mae: 1.9834

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2725 - mae: 1.9715

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2429 - mae: 1.9673

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3472 - mae: 1.9789

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2959 - mae: 1.9739

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2874 - mae: 1.9749

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2241 - mae: 1.9643

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2365 - mae: 1.9658

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2208 - mae: 1.9609

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2648 - mae: 1.9598

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2030 - mae: 1.9491

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1532 - mae: 1.9424

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1023 - mae: 1.9351

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1186 - mae: 1.9374 - val_loss: 5.3019 - val_mae: 1.8290

Epoch 20/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 12.4380 - mae: 3.3034

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9987 - mae: 2.1122

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8581 - mae: 2.1113

 63/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0972 - mae: 2.1283

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0171 - mae: 2.1304

103/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8683 - mae: 2.1081

123/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8995 - mae: 2.0887

144/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7813 - mae: 2.0704

162/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6991 - mae: 2.0607

183/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5755 - mae: 2.0325

202/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5521 - mae: 2.0220

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4932 - mae: 2.0113

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4207 - mae: 1.9968

264/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3318 - mae: 1.9823

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2723 - mae: 1.9709

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2412 - mae: 1.9668

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3568 - mae: 1.9803

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2933 - mae: 1.9732

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2840 - mae: 1.9743

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2226 - mae: 1.9633

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2318 - mae: 1.9646

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2100 - mae: 1.9593

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2578 - mae: 1.9581

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1945 - mae: 1.9476

490/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1589 - mae: 1.9434

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0974 - mae: 1.9343

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1112 - mae: 1.9360 - val_loss: 5.2982 - val_mae: 1.8285

Epoch 21/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 12.0539 - mae: 3.2478

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9918 - mae: 2.1171

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8389 - mae: 2.1147

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0453 - mae: 2.1312

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9807 - mae: 2.1232

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8307 - mae: 2.0996

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9155 - mae: 2.0931

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7525 - mae: 2.0679

160/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6397 - mae: 2.0590

180/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5227 - mae: 2.0260

201/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5244 - mae: 2.0169

222/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4959 - mae: 2.0151

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4002 - mae: 1.9942

264/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3139 - mae: 1.9798

283/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2517 - mae: 1.9681

303/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2231 - mae: 1.9642

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3379 - mae: 1.9779

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2698 - mae: 1.9698

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2718 - mae: 1.9723

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2054 - mae: 1.9606

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2122 - mae: 1.9620

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1718 - mae: 1.9525

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2504 - mae: 1.9579

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1702 - mae: 1.9442

493/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1278 - mae: 1.9376

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0869 - mae: 1.9320

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0970 - mae: 1.9335 - val_loss: 5.3160 - val_mae: 1.8277

Epoch 22/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 12.8484 - mae: 3.3783

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9140 - mae: 2.0921

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7872 - mae: 2.0942

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0133 - mae: 2.1191

 84/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9082 - mae: 2.1113

106/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8577 - mae: 2.0917

127/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7677 - mae: 2.0658

148/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6881 - mae: 2.0550

169/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5941 - mae: 2.0397

191/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5843 - mae: 2.0282

212/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5376 - mae: 2.0198

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3768 - mae: 1.9892

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3824 - mae: 1.9902

276/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2862 - mae: 1.9726

295/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1928 - mae: 1.9545

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2575 - mae: 1.9637

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2469 - mae: 1.9602

354/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2424 - mae: 1.9640

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2508 - mae: 1.9657

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2197 - mae: 1.9590

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1892 - mae: 1.9565

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1752 - mae: 1.9509

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2412 - mae: 1.9534

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1783 - mae: 1.9424

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1201 - mae: 1.9344

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0984 - mae: 1.9300

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0562 - mae: 1.9237

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0812 - mae: 1.9286 - val_loss: 5.3252 - val_mae: 1.8319

Epoch 23/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 12.4122 - mae: 3.3024

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7219 - mae: 2.0577

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8481 - mae: 2.1158

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1649 - mae: 2.1430

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9472 - mae: 2.1089

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9765 - mae: 2.1243

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9278 - mae: 2.0945

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8661 - mae: 2.0855

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7038 - mae: 2.0636

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5749 - mae: 2.0335

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5199 - mae: 2.0175

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5463 - mae: 2.0222

234/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3475 - mae: 1.9843

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3695 - mae: 1.9888

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2696 - mae: 1.9701

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1825 - mae: 1.9542

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2511 - mae: 1.9637

334/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2367 - mae: 1.9597

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2142 - mae: 1.9602

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2389 - mae: 1.9651

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2124 - mae: 1.9588

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2004 - mae: 1.9570

437/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1813 - mae: 1.9514

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1949 - mae: 1.9462

478/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1213 - mae: 1.9351

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0878 - mae: 1.9290

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0479 - mae: 1.9235

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0659 - mae: 1.9269 - val_loss: 5.3092 - val_mae: 1.8294

Epoch 24/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 13.0335 - mae: 3.4167

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6705 - mae: 2.0486

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7984 - mae: 2.1079

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0809 - mae: 2.1307

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9838 - mae: 2.1256

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8786 - mae: 2.1065

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8356 - mae: 2.0828

139/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7727 - mae: 2.0700

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6362 - mae: 2.0570

179/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5130 - mae: 2.0247

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5321 - mae: 2.0219

221/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4953 - mae: 2.0152

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3798 - mae: 1.9898

263/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2970 - mae: 1.9756

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2298 - mae: 1.9643

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2004 - mae: 1.9602

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3084 - mae: 1.9723

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2489 - mae: 1.9662

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2455 - mae: 1.9677

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1745 - mae: 1.9544

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1828 - mae: 1.9562

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1403 - mae: 1.9462

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2074 - mae: 1.9484

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1340 - mae: 1.9371

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1013 - mae: 1.9326

511/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0702 - mae: 1.9282

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0597 - mae: 1.9265 - val_loss: 5.2865 - val_mae: 1.8230

Epoch 25/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 12.5388 - mae: 3.3459

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0221 - mae: 2.1243

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8082 - mae: 2.1166

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0729 - mae: 2.1386

 80/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0132 - mae: 2.1435

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8701 - mae: 2.1182

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8496 - mae: 2.0937

142/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7752 - mae: 2.0748

161/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6285 - mae: 2.0597

182/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5440 - mae: 2.0322

202/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5347 - mae: 2.0237

222/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4957 - mae: 2.0177

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3929 - mae: 1.9947

262/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3159 - mae: 1.9807

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2529 - mae: 1.9709

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1851 - mae: 1.9572

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2023 - mae: 1.9604

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3132 - mae: 1.9739

342/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2322 - mae: 1.9625

360/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1988 - mae: 1.9601

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2225 - mae: 1.9640

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1885 - mae: 1.9561

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1720 - mae: 1.9557

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1328 - mae: 1.9453

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1955 - mae: 1.9470

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1279 - mae: 1.9359

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0720 - mae: 1.9290

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0523 - mae: 1.9258

517/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0205 - mae: 1.9194

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0466 - mae: 1.9252 - val_loss: 5.3188 - val_mae: 1.8305

Epoch 26/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - loss: 13.2519 - mae: 3.4381

 14/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9159 - mae: 2.1044

 27/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8994 - mae: 2.0952

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8722 - mae: 2.1206

 56/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.2191 - mae: 2.1521

 70/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9234 - mae: 2.1069

 85/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9004 - mae: 2.1167

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8459 - mae: 2.1081

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9155 - mae: 2.0961

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7914 - mae: 2.0758

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7406 - mae: 2.0647

159/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5998 - mae: 2.0501

173/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5732 - mae: 2.0343

187/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5561 - mae: 2.0226

202/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5102 - mae: 2.0136

218/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4892 - mae: 2.0146

234/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.3359 - mae: 1.9828

251/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3891 - mae: 1.9929

269/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2537 - mae: 1.9665

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2082 - mae: 1.9567

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2154 - mae: 1.9573

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2661 - mae: 1.9625

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2115 - mae: 1.9569

363/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2031 - mae: 1.9577

382/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1489 - mae: 1.9477

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1591 - mae: 1.9490

421/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1599 - mae: 1.9477

441/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1491 - mae: 1.9417

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1430 - mae: 1.9361

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0763 - mae: 1.9268

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0398 - mae: 1.9205

522/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0369 - mae: 1.9210

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.0324 - mae: 1.9200 - val_loss: 5.3086 - val_mae: 1.8285

Epoch 27/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - loss: 12.9617 - mae: 3.3903

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5201 - mae: 2.0185

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8613 - mae: 2.1202

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0200 - mae: 2.1235

 80/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9507 - mae: 2.1282

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8114 - mae: 2.0991

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7832 - mae: 2.0771

139/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7145 - mae: 2.0602

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5721 - mae: 2.0440

179/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4569 - mae: 2.0127

200/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4893 - mae: 2.0131

221/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4512 - mae: 2.0077

241/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3397 - mae: 1.9813

262/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2636 - mae: 1.9690

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1941 - mae: 1.9574

302/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1418 - mae: 1.9486

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2558 - mae: 1.9622

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1663 - mae: 1.9496

360/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1490 - mae: 1.9502

376/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1506 - mae: 1.9489

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1349 - mae: 1.9452

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1137 - mae: 1.9434

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0864 - mae: 1.9350

448/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1527 - mae: 1.9368

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0905 - mae: 1.9269

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0366 - mae: 1.9205

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0105 - mae: 1.9162

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0073 - mae: 1.9160 - val_loss: 5.3074 - val_mae: 1.8286

Epoch 28/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 13.1542 - mae: 3.4310

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8991 - mae: 2.0995

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8484 - mae: 2.1094

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1391 - mae: 2.1433

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8802 - mae: 2.1052

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9577 - mae: 2.1250

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8405 - mae: 2.0836

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7905 - mae: 2.0742

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6274 - mae: 2.0517

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5058 - mae: 2.0229

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4586 - mae: 2.0058

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4727 - mae: 2.0096

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2860 - mae: 1.9744

253/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2940 - mae: 1.9766

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1765 - mae: 1.9545

295/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0850 - mae: 1.9368

315/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1523 - mae: 1.9462

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1466 - mae: 1.9424

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1083 - mae: 1.9427

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1108 - mae: 1.9413

398/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0907 - mae: 1.9369

418/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1161 - mae: 1.9400

439/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0991 - mae: 1.9343

457/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1108 - mae: 1.9309

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0366 - mae: 1.9196

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9956 - mae: 1.9126

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9547 - mae: 1.9060

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9836 - mae: 1.9120 - val_loss: 5.3080 - val_mae: 1.8280

Epoch 29/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 13.1148 - mae: 3.4193

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5849 - mae: 2.0316

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7661 - mae: 2.1062

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0021 - mae: 2.1209

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9444 - mae: 2.1245

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8021 - mae: 2.0993

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8557 - mae: 2.0838

143/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6989 - mae: 2.0566

163/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6173 - mae: 2.0482

184/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4876 - mae: 2.0175

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4592 - mae: 2.0072

224/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3896 - mae: 1.9935

244/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3297 - mae: 1.9827

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2165 - mae: 1.9628

285/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1547 - mae: 1.9499

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1409 - mae: 1.9487

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2183 - mae: 1.9556

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1734 - mae: 1.9522

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1726 - mae: 1.9525

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1197 - mae: 1.9414

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1080 - mae: 1.9416

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0658 - mae: 1.9311

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1338 - mae: 1.9331

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0650 - mae: 1.9220

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0269 - mae: 1.9180

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9872 - mae: 1.9126

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9942 - mae: 1.9135 - val_loss: 5.3143 - val_mae: 1.8300

Epoch 30/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 13.3528 - mae: 3.4636

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5714 - mae: 2.0310

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7635 - mae: 2.1031

 61/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9943 - mae: 2.1180

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9052 - mae: 2.1195

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8380 - mae: 2.1045

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8041 - mae: 2.0771

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6679 - mae: 2.0474

157/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5599 - mae: 2.0380

177/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4300 - mae: 2.0077

197/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4324 - mae: 2.0006

217/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4230 - mae: 2.0011

238/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3147 - mae: 1.9775

258/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2263 - mae: 1.9604

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1425 - mae: 1.9486

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0474 - mae: 1.9281

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1977 - mae: 1.9505

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1321 - mae: 1.9405

357/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0993 - mae: 1.9395

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1133 - mae: 1.9406

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0909 - mae: 1.9347

415/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0419 - mae: 1.9287

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0581 - mae: 1.9291

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1012 - mae: 1.9279

476/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0247 - mae: 1.9155

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9882 - mae: 1.9095

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9424 - mae: 1.9018

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9747 - mae: 1.9085 - val_loss: 5.3034 - val_mae: 1.8269

Epoch 31/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 13.1136 - mae: 3.4114

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5446 - mae: 2.0246

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7442 - mae: 2.1023

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0194 - mae: 2.1226

 81/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8742 - mae: 2.1145

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7616 - mae: 2.0909

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8161 - mae: 2.0750

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6541 - mae: 2.0488

160/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5432 - mae: 2.0404

180/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4315 - mae: 2.0079

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4608 - mae: 2.0074

220/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4416 - mae: 2.0039

240/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3237 - mae: 1.9788

260/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2265 - mae: 1.9634

280/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1411 - mae: 1.9497

298/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0613 - mae: 1.9326

316/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1557 - mae: 1.9467

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1506 - mae: 1.9417

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0834 - mae: 1.9370

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1042 - mae: 1.9398

395/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0802 - mae: 1.9330

415/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0298 - mae: 1.9267

434/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0406 - mae: 1.9260

456/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0919 - mae: 1.9256

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0344 - mae: 1.9167

493/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9896 - mae: 1.9104

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9577 - mae: 1.9057

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9684 - mae: 1.9076 - val_loss: 5.3257 - val_mae: 1.8309

Epoch 32/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 13.7997 - mae: 3.5180

 22/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8100 - mae: 2.1015

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9099 - mae: 2.1335

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1504 - mae: 2.1590

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0312 - mae: 2.1449

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8706 - mae: 2.1161

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9152 - mae: 2.0978

142/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7615 - mae: 2.0719

163/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6680 - mae: 2.0622

183/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5257 - mae: 2.0290

203/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5001 - mae: 2.0181

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4306 - mae: 2.0037

245/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3522 - mae: 1.9897

264/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2440 - mae: 1.9697

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1802 - mae: 1.9567

304/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1347 - mae: 1.9489

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2352 - mae: 1.9605

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1457 - mae: 1.9463

364/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1252 - mae: 1.9446

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0597 - mae: 1.9317

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0852 - mae: 1.9357

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0685 - mae: 1.9312

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1061 - mae: 1.9284

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0537 - mae: 1.9202

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0052 - mae: 1.9139

509/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9597 - mae: 1.9078

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9742 - mae: 1.9094 - val_loss: 5.2917 - val_mae: 1.8260

Epoch 33/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 12.9815 - mae: 3.3969

 24/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8931 - mae: 2.1172

 44/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9551 - mae: 2.1386

 65/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9871 - mae: 2.1232

 88/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8639 - mae: 2.1146

109/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7783 - mae: 2.0883

128/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7586 - mae: 2.0717

148/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6455 - mae: 2.0551

168/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5486 - mae: 2.0386

188/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4853 - mae: 2.0133

209/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4845 - mae: 2.0132

229/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3041 - mae: 1.9802

248/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3449 - mae: 1.9872

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1741 - mae: 1.9567

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1051 - mae: 1.9398

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1283 - mae: 1.9421

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1407 - mae: 1.9426

351/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1109 - mae: 1.9422

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1062 - mae: 1.9403

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0590 - mae: 1.9306

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0407 - mae: 1.9288

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0147 - mae: 1.9213

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0921 - mae: 1.9259

472/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0207 - mae: 1.9135

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9769 - mae: 1.9075

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9417 - mae: 1.9028

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9528 - mae: 1.9048 - val_loss: 5.3196 - val_mae: 1.8283

Epoch 34/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 13.1727 - mae: 3.4239

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8736 - mae: 2.1001

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8678 - mae: 2.1218

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0867 - mae: 2.1447

 83/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9637 - mae: 2.1344

102/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8071 - mae: 2.1037

122/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8574 - mae: 2.0873

142/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7022 - mae: 2.0610

162/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6264 - mae: 2.0512

183/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4912 - mae: 2.0215

203/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4582 - mae: 2.0084

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3855 - mae: 1.9931

244/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2974 - mae: 1.9769

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1870 - mae: 1.9572

285/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1221 - mae: 1.9417

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0934 - mae: 1.9364

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1758 - mae: 1.9451

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1106 - mae: 1.9375

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1038 - mae: 1.9387

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0421 - mae: 1.9265

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0586 - mae: 1.9286

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0305 - mae: 1.9225

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0811 - mae: 1.9212

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0264 - mae: 1.9131

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9735 - mae: 1.9059

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9411 - mae: 1.9014

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9422 - mae: 1.9020 - val_loss: 5.3273 - val_mae: 1.8307

Epoch 34: early stopping

Restoring model weights from the end of the best epoch: 24.

In [18]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 1s 145ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

MAE:  1.7847634105891972

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## On your own: add the learning curve and the train results!

# LSTM one layer model
Literally, just grab the code above and change SimpleRNN to LSTM and boom! you have a more sophisticated model.

In [19]:
# now let's build a model

# since this is a univariate problem, n_features will be 1 (we also defined this before)
n_features = X.shape[2] # 1 green dot = 1 feature
n_steps = X.shape[1] # these are time steps = there are 10!

# define model
model = Sequential()
model.add(LSTM(30, input_shape=(n_steps,n_features), activation='relu')) # 30 red dots = hidden size of 30
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse',metrics=['mae'])
model.summary()

es = EarlyStopping(monitor='val_loss', mode='min',
                   patience=10,
                   verbose=1,
                   restore_best_weights=True)

# fit model (uses early stopping)
model.fit(X_train, y_train,
          epochs=500,
          batch_size=5,
          validation_split=0.2, # val is a random 20% of the data since we set shuffle = True
          verbose=1,
          callbacks=[es],
          shuffle=True)

C:\Users\dww05002\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         3,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,871 (15.12 KB)

 Trainable params: 3,871 (15.12 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 12:02 1s/step - loss: 196.6994 - mae: 13.5530

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91.0287 - mae: 8.8654

 42/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53.3199 - mae: 6.0182

 62/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39.0948 - mae: 4.8654

 82/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31.5289 - mae: 4.2542

101/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26.8451 - mae: 3.8481

121/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.6319 - mae: 3.5596

141/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3072 - mae: 3.3595

160/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.4794 - mae: 3.1975

179/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.1317 - mae: 3.0677

199/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.0806 - mae: 2.9768

217/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.2910 - mae: 2.9135

237/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.3938 - mae: 2.8254

256/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.7530 - mae: 2.7641

276/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.0950 - mae: 2.7000

295/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5228 - mae: 2.6412

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.1843 - mae: 2.6182

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.7459 - mae: 2.5776

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.3598 - mae: 2.5439

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1072 - mae: 2.5265

393/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.8135 - mae: 2.4990

413/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.4862 - mae: 2.4668

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2545 - mae: 2.4434

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.1426 - mae: 2.4322

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.8880 - mae: 2.4030

490/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6780 - mae: 2.3838

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.4711 - mae: 2.3609

524/524 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 10.3507 - mae: 2.3518 - val_loss: 5.4463 - val_mae: 1.8400

Epoch 2/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 16.1431 - mae: 3.7573

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6957 - mae: 2.0689

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2081 - mae: 2.1647

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.6511 - mae: 2.2217

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.5340 - mae: 2.2217

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3410 - mae: 2.2039

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2684 - mae: 2.1720

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1888 - mae: 2.1586

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.0008 - mae: 2.1301

175/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9168 - mae: 2.1024

194/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9655 - mae: 2.1024

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9524 - mae: 2.0993

232/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7791 - mae: 2.0719

251/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8180 - mae: 2.0753

269/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6756 - mae: 2.0466

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6224 - mae: 2.0373

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6201 - mae: 2.0389

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6661 - mae: 2.0436

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6011 - mae: 2.0365

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5846 - mae: 2.0352

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5081 - mae: 2.0214

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5244 - mae: 2.0232

420/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5214 - mae: 2.0218

440/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5157 - mae: 2.0173

460/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5116 - mae: 2.0119

480/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4283 - mae: 1.9978

499/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4078 - mae: 1.9943

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3673 - mae: 1.9889

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3839 - mae: 1.9923 - val_loss: 5.3895 - val_mae: 1.8313

Epoch 3/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 16.3258 - mae: 3.7899

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8932 - mae: 2.1034

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1511 - mae: 2.1448

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4848 - mae: 2.1823

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4185 - mae: 2.1929

 97/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2864 - mae: 2.1884

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1998 - mae: 2.1527

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1677 - mae: 2.1501

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9985 - mae: 2.1238

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8492 - mae: 2.0847

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8404 - mae: 2.0732

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8449 - mae: 2.0761

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6912 - mae: 2.0482

253/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7030 - mae: 2.0489

272/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5380 - mae: 2.0170

292/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5045 - mae: 2.0117

311/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5373 - mae: 2.0167

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5399 - mae: 2.0152

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4949 - mae: 2.0130

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5184 - mae: 2.0164

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4436 - mae: 2.0042

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4210 - mae: 2.0011

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4041 - mae: 1.9953

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4737 - mae: 1.9994

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4077 - mae: 1.9875

482/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3424 - mae: 1.9777

500/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3239 - mae: 1.9748

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2857 - mae: 1.9691

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.3090 - mae: 1.9739 - val_loss: 5.3739 - val_mae: 1.8321

Epoch 4/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 16.4130 - mae: 3.8070

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4722 - mae: 2.0205

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9257 - mae: 2.1173

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4792 - mae: 2.1826

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3717 - mae: 2.1801

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1949 - mae: 2.1670

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1176 - mae: 2.1335

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1206 - mae: 2.1378

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9589 - mae: 2.1134

175/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7856 - mae: 2.0701

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7972 - mae: 2.0626

215/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7808 - mae: 2.0611

234/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6236 - mae: 2.0327

253/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6574 - mae: 2.0374

271/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4838 - mae: 2.0035

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4533 - mae: 1.9999

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4879 - mae: 2.0062

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4908 - mae: 2.0050

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4577 - mae: 2.0043

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4744 - mae: 2.0071

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4216 - mae: 1.9973

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3910 - mae: 1.9940

429/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3558 - mae: 1.9841

448/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4317 - mae: 1.9881

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3617 - mae: 1.9765

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3242 - mae: 1.9720

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2749 - mae: 1.9639

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2801 - mae: 1.9662 - val_loss: 5.3631 - val_mae: 1.8321

Epoch 5/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 16.3097 - mae: 3.7978

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4394 - mae: 2.0154

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8954 - mae: 2.1139

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.4368 - mae: 2.1780

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3512 - mae: 2.1762

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1716 - mae: 2.1631

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0958 - mae: 2.1294

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0625 - mae: 2.1273

156/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9194 - mae: 2.1057

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7853 - mae: 2.0709

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7598 - mae: 2.0565

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7817 - mae: 2.0591

232/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5949 - mae: 2.0279

252/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6458 - mae: 2.0347

271/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4543 - mae: 1.9977

290/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4285 - mae: 1.9946

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4533 - mae: 1.9983

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4767 - mae: 1.9995

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4319 - mae: 1.9975

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4561 - mae: 2.0011

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3832 - mae: 1.9890

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3595 - mae: 1.9856

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3441 - mae: 1.9803

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3940 - mae: 1.9805

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3581 - mae: 1.9745

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2764 - mae: 1.9624

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2472 - mae: 1.9583

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2638 - mae: 1.9622

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2539 - mae: 1.9600 - val_loss: 5.3553 - val_mae: 1.8319

Epoch 6/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 16.3386 - mae: 3.8035

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4530 - mae: 2.0035

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8013 - mae: 2.0948

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3884 - mae: 2.1678

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2887 - mae: 2.1583

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2295 - mae: 2.1679

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0918 - mae: 2.1265

134/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1418 - mae: 2.1362

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9379 - mae: 2.1048

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7927 - mae: 2.0699

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7417 - mae: 2.0505

213/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7615 - mae: 2.0526

234/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5724 - mae: 2.0200

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5893 - mae: 2.0227

273/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4606 - mae: 1.9957

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4052 - mae: 1.9890

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4337 - mae: 1.9928

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4593 - mae: 1.9934

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4231 - mae: 1.9939

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4104 - mae: 1.9927

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3677 - mae: 1.9842

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3449 - mae: 1.9817

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3201 - mae: 1.9744

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3760 - mae: 1.9755

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3303 - mae: 1.9677

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2585 - mae: 1.9579

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2296 - mae: 1.9537

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2472 - mae: 1.9577

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2374 - mae: 1.9556 - val_loss: 5.3535 - val_mae: 1.8320

Epoch 7/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 16.2446 - mae: 3.7974

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3594 - mae: 1.9940

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7889 - mae: 2.0903

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3933 - mae: 2.1634

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2605 - mae: 2.1491

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2403 - mae: 2.1650

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1246 - mae: 2.1261

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0070 - mae: 2.1080

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9005 - mae: 2.0916

165/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7996 - mae: 2.0748

185/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7791 - mae: 2.0570

203/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7030 - mae: 2.0409

221/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7055 - mae: 2.0416

239/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6159 - mae: 2.0231

259/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5240 - mae: 2.0077

278/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4519 - mae: 1.9971

297/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3595 - mae: 1.9811

316/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4517 - mae: 1.9952

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4243 - mae: 1.9887

354/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3789 - mae: 1.9860

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3996 - mae: 1.9898

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3578 - mae: 1.9818

411/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3190 - mae: 1.9767

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2963 - mae: 1.9689

449/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3702 - mae: 1.9731

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2973 - mae: 1.9606

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2655 - mae: 1.9568

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2264 - mae: 1.9511

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2246 - mae: 1.9520 - val_loss: 5.3451 - val_mae: 1.8311

Epoch 8/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 16.1770 - mae: 3.7905

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7060 - mae: 2.0624

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7888 - mae: 2.0878

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2538 - mae: 2.1434

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2564 - mae: 2.1540

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0877 - mae: 2.1416

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9976 - mae: 2.1082

139/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9578 - mae: 2.1005

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8019 - mae: 2.0791

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7314 - mae: 2.0547

198/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7230 - mae: 2.0447

217/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6995 - mae: 2.0430

236/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5504 - mae: 2.0159

255/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5412 - mae: 2.0120

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4513 - mae: 1.9950

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3640 - mae: 1.9805

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4290 - mae: 1.9912

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4246 - mae: 1.9888

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3984 - mae: 1.9893

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3848 - mae: 1.9873

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3437 - mae: 1.9788

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3190 - mae: 1.9759

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3004 - mae: 1.9693

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3570 - mae: 1.9709

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3047 - mae: 1.9617

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2364 - mae: 1.9523

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2153 - mae: 1.9500

522/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2219 - mae: 1.9518

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2150 - mae: 1.9504 - val_loss: 5.3441 - val_mae: 1.8308

Epoch 9/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 16.2196 - mae: 3.7966

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6940 - mae: 2.0580

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7761 - mae: 2.0846

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2499 - mae: 2.1377

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2405 - mae: 2.1500

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1079 - mae: 2.1429

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0222 - mae: 2.1083

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0107 - mae: 2.1091

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8638 - mae: 2.0872

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7201 - mae: 2.0538

193/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7018 - mae: 2.0411

212/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7019 - mae: 2.0388

231/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5489 - mae: 2.0151

249/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6108 - mae: 2.0239

269/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4287 - mae: 1.9901

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3736 - mae: 1.9807

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3839 - mae: 1.9847

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4541 - mae: 1.9925

346/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3864 - mae: 1.9855

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3834 - mae: 1.9869

385/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3101 - mae: 1.9729

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3132 - mae: 1.9729

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2957 - mae: 1.9677

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3446 - mae: 1.9681

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2997 - mae: 1.9605

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2235 - mae: 1.9496

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1947 - mae: 1.9460

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2028 - mae: 1.9479

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.2028 - mae: 1.9479 - val_loss: 5.3416 - val_mae: 1.8304

Epoch 10/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 16.2091 - mae: 3.7960

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3775 - mae: 1.9796

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7993 - mae: 2.0929

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2226 - mae: 2.1377

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2299 - mae: 2.1466

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0705 - mae: 2.1357

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0088 - mae: 2.1061

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9663 - mae: 2.0998

157/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8001 - mae: 2.0747

178/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7064 - mae: 2.0485

197/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6946 - mae: 2.0381

217/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6741 - mae: 2.0369

236/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5255 - mae: 2.0100

255/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5182 - mae: 2.0070

275/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4180 - mae: 1.9895

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3414 - mae: 1.9759

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4052 - mae: 1.9867

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3998 - mae: 1.9843

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3648 - mae: 1.9839

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3759 - mae: 1.9844

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3249 - mae: 1.9743

409/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2999 - mae: 1.9728

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2688 - mae: 1.9631

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3456 - mae: 1.9685

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2816 - mae: 1.9564

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2258 - mae: 1.9492

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1981 - mae: 1.9458

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1937 - mae: 1.9452

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1934 - mae: 1.9460 - val_loss: 5.3368 - val_mae: 1.8314

Epoch 11/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 16.4485 - mae: 3.8270

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3289 - mae: 1.9869

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7819 - mae: 2.0848

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2372 - mae: 2.1370

 80/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2039 - mae: 2.1468

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0620 - mae: 2.1348

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9872 - mae: 2.1018

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9419 - mae: 2.0935

157/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7779 - mae: 2.0691

176/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6703 - mae: 2.0424

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6846 - mae: 2.0357

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6814 - mae: 2.0363

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5217 - mae: 2.0076

252/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5581 - mae: 2.0144

270/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3831 - mae: 1.9818

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3463 - mae: 1.9755

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3550 - mae: 1.9795

327/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4270 - mae: 1.9873

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3695 - mae: 1.9828

367/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3580 - mae: 1.9817

386/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2772 - mae: 1.9661

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2803 - mae: 1.9669

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2644 - mae: 1.9611

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3172 - mae: 1.9624

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2654 - mae: 1.9531

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1995 - mae: 1.9439

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1724 - mae: 1.9408

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1886 - mae: 1.9446

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1789 - mae: 1.9425 - val_loss: 5.3314 - val_mae: 1.8318

Epoch 12/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - loss: 16.3426 - mae: 3.8159

 13/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.5754 - mae: 2.0471

 25/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.9041 - mae: 2.0947

 37/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.8196 - mae: 2.0918

 49/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1227 - mae: 2.1252

 61/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 7.1766 - mae: 2.1270

 74/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.1751 - mae: 2.1244

 87/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0194 - mae: 2.1183

100/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0037 - mae: 2.1254

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 7.0508 - mae: 2.1100

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.9364 - mae: 2.0930

141/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8787 - mae: 2.0812

156/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8069 - mae: 2.0760

172/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7041 - mae: 2.0494

186/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.7011 - mae: 2.0426

201/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6431 - mae: 2.0269

217/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.6451 - mae: 2.0332

232/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.4965 - mae: 2.0057

248/524 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.5768 - mae: 2.0178

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4108 - mae: 1.9893

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3855 - mae: 1.9857

300/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.2990 - mae: 1.9724

318/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.4189 - mae: 1.9898

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3666 - mae: 1.9789

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3384 - mae: 1.9798

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.3599 - mae: 1.9814

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2849 - mae: 1.9672

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2702 - mae: 1.9657

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2616 - mae: 1.9618

443/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3219 - mae: 1.9639

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2683 - mae: 1.9542

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2152 - mae: 1.9462

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1902 - mae: 1.9425

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1609 - mae: 1.9396

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 6.1699 - mae: 1.9413 - val_loss: 5.3268 - val_mae: 1.8316

Epoch 13/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 16.3611 - mae: 3.8194

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3037 - mae: 1.9771

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7856 - mae: 2.0892

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2494 - mae: 2.1423

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1489 - mae: 2.1280

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0540 - mae: 2.1334

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9624 - mae: 2.0965

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9867 - mae: 2.1031

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8316 - mae: 2.0797

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6916 - mae: 2.0493

192/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6755 - mae: 2.0381

210/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6669 - mae: 2.0321

228/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5158 - mae: 2.0077

247/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5677 - mae: 2.0159

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4030 - mae: 1.9883

284/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3653 - mae: 1.9819

303/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3240 - mae: 1.9779

322/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4323 - mae: 1.9899

341/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3492 - mae: 1.9783

360/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3018 - mae: 1.9737

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3009 - mae: 1.9711

397/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2884 - mae: 1.9680

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2737 - mae: 1.9642

436/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2429 - mae: 1.9591

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2939 - mae: 1.9600

474/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2304 - mae: 1.9496

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1953 - mae: 1.9443

510/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1546 - mae: 1.9393

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1608 - mae: 1.9404 - val_loss: 5.3197 - val_mae: 1.8316

Epoch 14/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 16.2150 - mae: 3.8024

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3408 - mae: 1.9672

 37/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7877 - mae: 2.0845

 56/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.3083 - mae: 2.1461

 75/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1565 - mae: 2.1255

 94/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1479 - mae: 2.1418

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0279 - mae: 2.1053

132/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9448 - mae: 2.0906

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8140 - mae: 2.0706

168/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7109 - mae: 2.0551

187/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6654 - mae: 2.0359

206/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6832 - mae: 2.0325

224/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5570 - mae: 2.0122

242/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5071 - mae: 2.0018

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4196 - mae: 1.9887

280/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3576 - mae: 1.9812

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2750 - mae: 1.9664

319/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3896 - mae: 1.9837

339/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3499 - mae: 1.9772

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2761 - mae: 1.9687

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2941 - mae: 1.9692

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2871 - mae: 1.9666

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2612 - mae: 1.9606

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2374 - mae: 1.9565

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2825 - mae: 1.9563

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2166 - mae: 1.9450

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1758 - mae: 1.9391

513/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1515 - mae: 1.9366

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1533 - mae: 1.9371 - val_loss: 5.3147 - val_mae: 1.8301

Epoch 15/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - loss: 16.3562 - mae: 3.8189

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2805 - mae: 1.9714

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7571 - mae: 2.0837

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2263 - mae: 2.1405

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1167 - mae: 2.1247

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1083 - mae: 2.1427

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9531 - mae: 2.0965

134/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9951 - mae: 2.1030

153/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8175 - mae: 2.0759

172/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6630 - mae: 2.0419

191/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6738 - mae: 2.0381

211/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6316 - mae: 2.0246

230/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4761 - mae: 2.0010

250/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5335 - mae: 2.0112

270/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3472 - mae: 1.9774

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3005 - mae: 1.9710

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3292 - mae: 1.9747

331/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3556 - mae: 1.9759

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3123 - mae: 1.9740

368/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3103 - mae: 1.9730

387/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2487 - mae: 1.9613

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2460 - mae: 1.9608

426/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2293 - mae: 1.9550

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2970 - mae: 1.9592

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2331 - mae: 1.9472

483/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1771 - mae: 1.9396

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1540 - mae: 1.9365

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1461 - mae: 1.9355

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1462 - mae: 1.9362 - val_loss: 5.2956 - val_mae: 1.8281

Epoch 16/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 15.9669 - mae: 3.7674

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2781 - mae: 1.9533

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6709 - mae: 2.0645

 56/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2503 - mae: 2.1367

 73/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0844 - mae: 2.1081

 92/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0149 - mae: 2.1180

111/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0589 - mae: 2.1082

131/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8935 - mae: 2.0831

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7881 - mae: 2.0662

169/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6641 - mae: 2.0464

187/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6437 - mae: 2.0324

206/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6625 - mae: 2.0293

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5241 - mae: 2.0068

244/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4979 - mae: 2.0024

263/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3926 - mae: 1.9843

283/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3311 - mae: 1.9752

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2661 - mae: 1.9661

321/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3857 - mae: 1.9823

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3298 - mae: 1.9743

359/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2783 - mae: 1.9684

378/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2870 - mae: 1.9679

397/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2615 - mae: 1.9615

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2473 - mae: 1.9576

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2241 - mae: 1.9537

454/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2635 - mae: 1.9529

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1986 - mae: 1.9407

493/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1706 - mae: 1.9377

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1432 - mae: 1.9341

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1421 - mae: 1.9346 - val_loss: 5.3082 - val_mae: 1.8295

Epoch 17/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 16.2205 - mae: 3.8070

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2524 - mae: 1.9599

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7584 - mae: 2.0796

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1339 - mae: 2.1240

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1096 - mae: 2.1315

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9725 - mae: 2.1223

120/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8729 - mae: 2.0854

140/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.8040 - mae: 2.0677

159/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6782 - mae: 2.0545

179/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5959 - mae: 2.0315

198/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6149 - mae: 2.0246

218/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5826 - mae: 2.0226

235/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4254 - mae: 1.9924

250/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5169 - mae: 2.0083

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3674 - mae: 1.9821

281/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3497 - mae: 1.9796

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2515 - mae: 1.9625

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3501 - mae: 1.9788

335/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3205 - mae: 1.9703

353/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2785 - mae: 1.9683

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3021 - mae: 1.9705

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2429 - mae: 1.9582

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2248 - mae: 1.9570

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1974 - mae: 1.9492

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2588 - mae: 1.9513

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2141 - mae: 1.9435

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1508 - mae: 1.9342

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1245 - mae: 1.9313

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1325 - mae: 1.9330

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1325 - mae: 1.9330 - val_loss: 5.2949 - val_mae: 1.8274

Epoch 18/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 15.8744 - mae: 3.7603

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2037 - mae: 1.9500

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7326 - mae: 2.0744

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1048 - mae: 2.1194

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0934 - mae: 2.1277

 99/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9572 - mae: 2.1192

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8969 - mae: 2.0854

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9267 - mae: 2.0917

153/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7840 - mae: 2.0705

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6348 - mae: 2.0392

194/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6257 - mae: 2.0278

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6113 - mae: 2.0250

234/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4328 - mae: 1.9932

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4566 - mae: 1.9982

272/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3218 - mae: 1.9741

292/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2820 - mae: 1.9667

312/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3090 - mae: 1.9713

331/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3256 - mae: 1.9700

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2775 - mae: 1.9679

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2877 - mae: 1.9672

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2463 - mae: 1.9591

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2124 - mae: 1.9559

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1772 - mae: 1.9460

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2600 - mae: 1.9512

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1944 - mae: 1.9400

487/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1620 - mae: 1.9361

506/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1278 - mae: 1.9316

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1232 - mae: 1.9316 - val_loss: 5.2845 - val_mae: 1.8266

Epoch 19/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 15.5807 - mae: 3.7213

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2144 - mae: 1.9374

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6322 - mae: 2.0544

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1753 - mae: 2.1327

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0327 - mae: 2.1105

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0400 - mae: 2.1314

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9009 - mae: 2.0863

134/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9542 - mae: 2.0950

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7578 - mae: 2.0650

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6004 - mae: 2.0322

194/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6160 - mae: 2.0252

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6025 - mae: 2.0229

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4448 - mae: 1.9949

251/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4790 - mae: 2.0017

270/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3131 - mae: 1.9717

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2752 - mae: 1.9646

309/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2844 - mae: 1.9672

330/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3217 - mae: 1.9689

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2790 - mae: 1.9675

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2880 - mae: 1.9672

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2225 - mae: 1.9544

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2057 - mae: 1.9537

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1834 - mae: 1.9466

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2476 - mae: 1.9496

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1964 - mae: 1.9404

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1325 - mae: 1.9310

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1076 - mae: 1.9283

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1163 - mae: 1.9299

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1163 - mae: 1.9299 - val_loss: 5.2860 - val_mae: 1.8258

Epoch 20/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 15.4765 - mae: 3.7073

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1596 - mae: 1.9409

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7026 - mae: 2.0671

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1412 - mae: 2.1252

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0254 - mae: 2.1094

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0311 - mae: 2.1303

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9042 - mae: 2.0877

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9048 - mae: 2.0880

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7459 - mae: 2.0643

172/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6122 - mae: 2.0340

185/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6334 - mae: 2.0313

201/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5645 - mae: 2.0135

217/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5627 - mae: 2.0181

235/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3984 - mae: 1.9879

251/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4695 - mae: 2.0008

270/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3041 - mae: 1.9709

289/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2657 - mae: 1.9637

308/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2731 - mae: 1.9673

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3259 - mae: 1.9699

347/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2822 - mae: 1.9677

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2678 - mae: 1.9647

385/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2072 - mae: 1.9526

405/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2064 - mae: 1.9521

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1878 - mae: 1.9469

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2425 - mae: 1.9483

465/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1982 - mae: 1.9407

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1276 - mae: 1.9304

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1008 - mae: 1.9273

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1082 - mae: 1.9280

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.1091 - mae: 1.9289 - val_loss: 5.2840 - val_mae: 1.8257

Epoch 21/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 7:21 845ms/step - loss: 15.3285 - mae: 3.6852

 23/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.4662 - mae: 2.0239

 46/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8384 - mae: 2.0817

 69/524 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9761 - mae: 2.0943

 92/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9578 - mae: 2.1096

114/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9110 - mae: 2.0863

134/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9305 - mae: 2.0914

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7143 - mae: 2.0581

175/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5578 - mae: 2.0254

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5818 - mae: 2.0186

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5820 - mae: 2.0200

234/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4055 - mae: 1.9883

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4248 - mae: 1.9923

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3205 - mae: 1.9738

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2421 - mae: 1.9594

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2861 - mae: 1.9666

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2795 - mae: 1.9623

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2417 - mae: 1.9606

373/524 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2519 - mae: 1.9600

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2062 - mae: 1.9520

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1782 - mae: 1.9494

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1439 - mae: 1.9398

451/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2316 - mae: 1.9464

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1639 - mae: 1.9340

491/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1330 - mae: 1.9304

510/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0888 - mae: 1.9250

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0987 - mae: 1.9265 - val_loss: 5.2942 - val_mae: 1.8259

Epoch 22/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 15.2568 - mae: 3.6695

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1321 - mae: 1.9376

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6951 - mae: 2.0658

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.1409 - mae: 2.1252

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0588 - mae: 2.1199

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9344 - mae: 2.1176

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8413 - mae: 2.0800

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7649 - mae: 2.0619

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.7046 - mae: 2.0588

175/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5476 - mae: 2.0265

196/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5832 - mae: 2.0214

216/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5317 - mae: 2.0138

235/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3757 - mae: 1.9860

255/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3908 - mae: 1.9875

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3072 - mae: 1.9737

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2284 - mae: 1.9592

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2717 - mae: 1.9662

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2736 - mae: 1.9630

350/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2419 - mae: 1.9621

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2554 - mae: 1.9617

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1988 - mae: 1.9506

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1733 - mae: 1.9482

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1508 - mae: 1.9414

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2074 - mae: 1.9426

466/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1665 - mae: 1.9351

485/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1037 - mae: 1.9261

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0796 - mae: 1.9239

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0906 - mae: 1.9259 - val_loss: 5.2947 - val_mae: 1.8253

Epoch 23/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 15.2612 - mae: 3.6706

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5298 - mae: 2.0176

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6660 - mae: 2.0545

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0796 - mae: 2.1161

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0625 - mae: 2.1209

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9386 - mae: 2.1182

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8489 - mae: 2.0796

137/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8147 - mae: 2.0735

157/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6619 - mae: 2.0517

177/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5431 - mae: 2.0269

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5698 - mae: 2.0185

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5651 - mae: 2.0192

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4086 - mae: 1.9916

252/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4417 - mae: 1.9974

272/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2680 - mae: 1.9671

291/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2207 - mae: 1.9590

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2436 - mae: 1.9617

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2774 - mae: 1.9616

349/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2269 - mae: 1.9584

369/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2472 - mae: 1.9604

388/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1912 - mae: 1.9494

407/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1655 - mae: 1.9465

425/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1542 - mae: 1.9420

445/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2087 - mae: 1.9430

464/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1677 - mae: 1.9358

484/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0967 - mae: 1.9253

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0721 - mae: 1.9228

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0821 - mae: 1.9248 - val_loss: 5.2795 - val_mae: 1.8231

Epoch 24/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 14.7956 - mae: 3.5904

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1639 - mae: 1.9285

 37/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6773 - mae: 2.0591

 55/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9783 - mae: 2.0947

 74/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9626 - mae: 2.0927

 92/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9187 - mae: 2.1061

111/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9595 - mae: 2.0946

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7813 - mae: 2.0667

148/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6911 - mae: 2.0527

167/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6045 - mae: 2.0386

186/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5776 - mae: 2.0227

204/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5125 - mae: 2.0095

224/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4567 - mae: 1.9983

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4158 - mae: 1.9906

262/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3318 - mae: 1.9767

281/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2758 - mae: 1.9693

299/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1758 - mae: 1.9511

317/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2722 - mae: 1.9670

336/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2706 - mae: 1.9626

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1762 - mae: 1.9491

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2173 - mae: 1.9564

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1885 - mae: 1.9497

414/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1274 - mae: 1.9411

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1294 - mae: 1.9388

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2009 - mae: 1.9427

471/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1387 - mae: 1.9301

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1079 - mae: 1.9264

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0639 - mae: 1.9214

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0745 - mae: 1.9234

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0745 - mae: 1.9234 - val_loss: 5.2872 - val_mae: 1.8249

Epoch 25/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 14.9091 - mae: 3.6096

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2080 - mae: 1.9375

 37/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7097 - mae: 2.0676

 56/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.2187 - mae: 2.1320

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9685 - mae: 2.1023

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9908 - mae: 2.1241

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8916 - mae: 2.0849

132/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8420 - mae: 2.0789

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7283 - mae: 2.0600

167/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6155 - mae: 2.0418

186/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5737 - mae: 2.0229

206/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5712 - mae: 2.0180

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4377 - mae: 1.9974

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4117 - mae: 1.9920

262/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3244 - mae: 1.9770

282/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2640 - mae: 1.9689

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1790 - mae: 1.9545

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2990 - mae: 1.9703

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2312 - mae: 1.9598

358/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1631 - mae: 1.9490

377/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1863 - mae: 1.9514

396/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1777 - mae: 1.9493

416/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1562 - mae: 1.9443

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1324 - mae: 1.9402

455/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1794 - mae: 1.9401

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1178 - mae: 1.9295

494/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0785 - mae: 1.9234

514/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0506 - mae: 1.9208

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0632 - mae: 1.9228 - val_loss: 5.2684 - val_mae: 1.8228

Epoch 26/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - loss: 14.5743 - mae: 3.5484

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0899 - mae: 1.9290

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5757 - mae: 2.0435

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0723 - mae: 2.1107

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9461 - mae: 2.0963

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9394 - mae: 2.1159

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8026 - mae: 2.0698

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8124 - mae: 2.0730

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6948 - mae: 2.0565

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5356 - mae: 2.0238

194/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5415 - mae: 2.0147

214/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5295 - mae: 2.0139

233/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3761 - mae: 1.9867

253/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3926 - mae: 1.9892

273/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2602 - mae: 1.9655

294/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1797 - mae: 1.9518

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2374 - mae: 1.9616

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2333 - mae: 1.9575

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1905 - mae: 1.9530

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2069 - mae: 1.9552

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1664 - mae: 1.9472

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1118 - mae: 1.9405

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1021 - mae: 1.9350

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1792 - mae: 1.9387

470/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1260 - mae: 1.9296

490/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0967 - mae: 1.9268

507/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0477 - mae: 1.9199

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0539 - mae: 1.9215 - val_loss: 5.2746 - val_mae: 1.8229

Epoch 27/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - loss: 14.1277 - mae: 3.4471

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.1398 - mae: 1.9232

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5614 - mae: 2.0413

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0956 - mae: 2.1170

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9231 - mae: 2.0950

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9164 - mae: 2.1137

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8446 - mae: 2.0759

132/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7879 - mae: 2.0668

151/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6877 - mae: 2.0522

171/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5542 - mae: 2.0258

190/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5565 - mae: 2.0191

209/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5352 - mae: 2.0120

226/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4004 - mae: 1.9904

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3785 - mae: 1.9858

261/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2881 - mae: 1.9706

280/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2271 - mae: 1.9631

300/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1474 - mae: 1.9484

318/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2563 - mae: 1.9648

337/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2211 - mae: 1.9557

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1334 - mae: 1.9433

375/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1801 - mae: 1.9514

394/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1487 - mae: 1.9450

415/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0756 - mae: 1.9336

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1041 - mae: 1.9354

454/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1468 - mae: 1.9347

473/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0882 - mae: 1.9234

492/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0677 - mae: 1.9211

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0355 - mae: 1.9176

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0391 - mae: 1.9187 - val_loss: 5.2765 - val_mae: 1.8232

Epoch 28/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - loss: 14.3244 - mae: 3.4947

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0754 - mae: 1.9268

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6224 - mae: 2.0530

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9967 - mae: 2.1001

 78/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9849 - mae: 2.1065

 97/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9008 - mae: 2.1115

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8237 - mae: 2.0743

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8406 - mae: 2.0777

156/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6533 - mae: 2.0493

175/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5053 - mae: 2.0182

195/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5194 - mae: 2.0096

215/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4985 - mae: 2.0077

235/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3294 - mae: 1.9785

255/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3461 - mae: 1.9807

274/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2671 - mae: 1.9680

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1820 - mae: 1.9523

313/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2256 - mae: 1.9591

333/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2186 - mae: 1.9541

352/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1757 - mae: 1.9493

371/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1911 - mae: 1.9517

390/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1461 - mae: 1.9429

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1129 - mae: 1.9401

430/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0776 - mae: 1.9305

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1602 - mae: 1.9349

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1009 - mae: 1.9243

488/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0692 - mae: 1.9207

508/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0287 - mae: 1.9161

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0378 - mae: 1.9180 - val_loss: 5.2694 - val_mae: 1.8216

Epoch 29/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 13.7548 - mae: 3.3440

 16/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3119 - mae: 1.9466

 34/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6135 - mae: 2.0570

 53/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9079 - mae: 2.0779

 71/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8675 - mae: 2.0798

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8033 - mae: 2.0888

108/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7588 - mae: 2.0765

127/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7095 - mae: 2.0526

146/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6574 - mae: 2.0443

163/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6086 - mae: 2.0366

182/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4680 - mae: 2.0094

201/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4603 - mae: 1.9957

220/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4727 - mae: 2.0026

238/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3799 - mae: 1.9853

256/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3162 - mae: 1.9737

275/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2292 - mae: 1.9615

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1553 - mae: 1.9471

310/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1820 - mae: 1.9511

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2151 - mae: 1.9509

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1725 - mae: 1.9473

366/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1728 - mae: 1.9484

383/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1014 - mae: 1.9346

401/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1094 - mae: 1.9360

417/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1086 - mae: 1.9349

435/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0844 - mae: 1.9307

452/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1431 - mae: 1.9328

469/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0829 - mae: 1.9205

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0428 - mae: 1.9155

504/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0092 - mae: 1.9118

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0320 - mae: 1.9168

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0218 - mae: 1.9145 - val_loss: 5.2657 - val_mae: 1.8197

Epoch 30/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 18s 36ms/step - loss: 13.7137 - mae: 3.3334

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0947 - mae: 1.9083

 38/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5475 - mae: 2.0384

 57/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7.0694 - mae: 2.1136

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8751 - mae: 2.0881

 93/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9276 - mae: 2.1083

111/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8770 - mae: 2.0779

129/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7070 - mae: 2.0509

147/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6521 - mae: 2.0432

166/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5706 - mae: 2.0306

185/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5194 - mae: 2.0106

203/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4496 - mae: 1.9957

221/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4487 - mae: 1.9980

240/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3758 - mae: 1.9826

259/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2876 - mae: 1.9688

278/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2240 - mae: 1.9618

296/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1302 - mae: 1.9420

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1878 - mae: 1.9517

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2084 - mae: 1.9497

348/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1640 - mae: 1.9453

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1707 - mae: 1.9480

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0874 - mae: 1.9311

403/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0999 - mae: 1.9333

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0964 - mae: 1.9316

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0896 - mae: 1.9264

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0980 - mae: 1.9229

479/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0513 - mae: 1.9155

495/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0361 - mae: 1.9132

512/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0097 - mae: 1.9110

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0136 - mae: 1.9122 - val_loss: 5.2714 - val_mae: 1.8224

Epoch 31/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 13.7324 - mae: 3.3523

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4016 - mae: 1.9833

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6294 - mae: 2.0430

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9247 - mae: 2.0854

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8677 - mae: 2.0827

 95/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8965 - mae: 2.1023

113/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8035 - mae: 2.0633

131/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7309 - mae: 2.0539

150/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6454 - mae: 2.0401

169/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5195 - mae: 2.0196

188/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4719 - mae: 2.0018

208/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5352 - mae: 2.0089

227/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3603 - mae: 1.9802

247/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3995 - mae: 1.9877

267/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2327 - mae: 1.9593

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1918 - mae: 1.9527

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1470 - mae: 1.9465

325/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2561 - mae: 1.9586

344/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1633 - mae: 1.9441

363/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1556 - mae: 1.9446

382/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1054 - mae: 1.9337

402/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0969 - mae: 1.9319

421/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0929 - mae: 1.9297

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0852 - mae: 1.9251

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0933 - mae: 1.9218

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0409 - mae: 1.9142

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0092 - mae: 1.9099

521/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0036 - mae: 1.9098

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0066 - mae: 1.9110 - val_loss: 5.2713 - val_mae: 1.8240

Epoch 32/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 13.5802 - mae: 3.2855

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9933 - mae: 1.9030

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5510 - mae: 2.0382

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.9730 - mae: 2.0935

 77/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8618 - mae: 2.0821

 96/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8552 - mae: 2.0992

116/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7681 - mae: 2.0625

135/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7939 - mae: 2.0666

155/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.6217 - mae: 2.0407

173/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5013 - mae: 2.0149

192/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4843 - mae: 2.0030

211/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4705 - mae: 1.9974

230/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3275 - mae: 1.9764

249/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3995 - mae: 1.9888

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2225 - mae: 1.9574

287/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1729 - mae: 1.9489

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1420 - mae: 1.9456

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2620 - mae: 1.9596

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1501 - mae: 1.9413

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1506 - mae: 1.9429

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1004 - mae: 1.9327

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0832 - mae: 1.9298

420/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1003 - mae: 1.9313

439/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0994 - mae: 1.9278

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1055 - mae: 1.9237

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0506 - mae: 1.9145

496/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0226 - mae: 1.9102

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9717 - mae: 1.9035

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 6.0018 - mae: 1.9096 - val_loss: 5.2733 - val_mae: 1.8243

Epoch 33/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - loss: 13.6322 - mae: 3.3246

 17/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.9875 - mae: 1.8813

 34/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4942 - mae: 2.0291

 52/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7761 - mae: 2.0481

 71/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7898 - mae: 2.0619

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7328 - mae: 2.0706

107/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7338 - mae: 2.0682

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7424 - mae: 2.0535

144/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6437 - mae: 2.0367

162/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5796 - mae: 2.0272

178/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4400 - mae: 2.0028

194/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4654 - mae: 1.9977

209/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4881 - mae: 2.0001

223/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3973 - mae: 1.9856

239/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3583 - mae: 1.9790

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3233 - mae: 1.9755

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2172 - mae: 1.9560

279/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2051 - mae: 1.9570

285/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1784 - mae: 1.9497

293/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1467 - mae: 1.9437

298/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1207 - mae: 1.9402

306/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1382 - mae: 1.9452

316/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1976 - mae: 1.9522

329/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1970 - mae: 1.9467

340/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1668 - mae: 1.9455

351/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1487 - mae: 1.9429

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1597 - mae: 1.9454

379/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1171 - mae: 1.9368

393/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1110 - mae: 1.9349

406/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0753 - mae: 1.9301

420/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0954 - mae: 1.9313

433/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0514 - mae: 1.9246

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.1120 - mae: 1.9255

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0831 - mae: 1.9207

475/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0540 - mae: 1.9169

489/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0394 - mae: 1.9148

503/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9909 - mae: 1.9081

518/524 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9731 - mae: 1.9054

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 5.9969 - mae: 1.9101 - val_loss: 5.2750 - val_mae: 1.8250

Epoch 34/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - loss: 13.2574 - mae: 3.1522

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0206 - mae: 1.8837

 36/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6448 - mae: 2.0457

 54/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8074 - mae: 2.0577

 71/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7263 - mae: 2.0539

 89/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6884 - mae: 2.0661

108/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6695 - mae: 2.0607

125/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7009 - mae: 2.0470

142/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6310 - mae: 2.0341

157/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5214 - mae: 2.0217

173/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4513 - mae: 2.0052

189/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4659 - mae: 1.9987

207/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4755 - mae: 1.9965

225/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3467 - mae: 1.9770

243/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3177 - mae: 1.9726

260/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2455 - mae: 1.9610

277/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1983 - mae: 1.9553

296/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0955 - mae: 1.9351

314/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1507 - mae: 1.9436

332/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1574 - mae: 1.9402

351/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1252 - mae: 1.9375

370/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1389 - mae: 1.9392

389/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0681 - mae: 1.9261

408/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0505 - mae: 1.9254

427/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0354 - mae: 1.9197

447/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0941 - mae: 1.9210

467/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0551 - mae: 1.9139

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0058 - mae: 1.9074

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9677 - mae: 1.9030

523/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9877 - mae: 1.9076

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9776 - mae: 1.9054 - val_loss: 5.2798 - val_mae: 1.8291

Epoch 35/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - loss: 13.2998 - mae: 3.1139

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.3083 - mae: 1.9562

 40/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4191 - mae: 2.0113

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8099 - mae: 2.0637

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7812 - mae: 2.0754

 97/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7309 - mae: 2.0805

115/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6655 - mae: 2.0464

134/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7559 - mae: 2.0586

153/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5947 - mae: 2.0348

172/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4414 - mae: 2.0010

191/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4473 - mae: 1.9960

210/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4358 - mae: 1.9907

229/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2799 - mae: 1.9669

247/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3491 - mae: 1.9788

265/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1841 - mae: 1.9503

285/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1395 - mae: 1.9423

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1002 - mae: 1.9377

324/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2201 - mae: 1.9517

343/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1082 - mae: 1.9331

362/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1100 - mae: 1.9347

381/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0588 - mae: 1.9251

400/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0435 - mae: 1.9225

419/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0726 - mae: 1.9258

438/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0776 - mae: 1.9244

458/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0751 - mae: 1.9183

477/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0212 - mae: 1.9100

497/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9892 - mae: 1.9049

516/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9421 - mae: 1.8983

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9733 - mae: 1.9046 - val_loss: 5.2708 - val_mae: 1.8239

Epoch 36/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 13.4272 - mae: 3.2095

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2944 - mae: 1.9485

 41/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5292 - mae: 2.0212

 60/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8121 - mae: 2.0602

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7783 - mae: 2.0735

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6828 - mae: 2.0702

117/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6384 - mae: 2.0392

136/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6774 - mae: 2.0440

154/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5705 - mae: 2.0296

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4185 - mae: 1.9987

192/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4309 - mae: 1.9915

210/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4296 - mae: 1.9886

229/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2740 - mae: 1.9647

249/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3460 - mae: 1.9782

269/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1615 - mae: 1.9453

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1256 - mae: 1.9387

309/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1207 - mae: 1.9373

328/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1698 - mae: 1.9408

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1152 - mae: 1.9343

365/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1188 - mae: 1.9363

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0320 - mae: 1.9190

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0474 - mae: 1.9219

424/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0367 - mae: 1.9194

444/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1001 - mae: 1.9220

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0413 - mae: 1.9114

482/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9939 - mae: 1.9050

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9656 - mae: 1.9005

519/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9438 - mae: 1.8984

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9632 - mae: 1.9022 - val_loss: 5.2920 - val_mae: 1.8302

Epoch 37/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - loss: 13.2536 - mae: 3.1039

 21/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.2474 - mae: 1.9420

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4112 - mae: 2.0078

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7549 - mae: 2.0536

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7378 - mae: 2.0672

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6394 - mae: 2.0625

119/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5773 - mae: 2.0321

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5629 - mae: 2.0199

156/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.5035 - mae: 2.0174

174/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3902 - mae: 1.9933

192/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4045 - mae: 1.9870

212/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3897 - mae: 1.9826

231/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2597 - mae: 1.9633

249/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3207 - mae: 1.9733

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1475 - mae: 1.9416

288/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1032 - mae: 1.9342

307/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1020 - mae: 1.9347

326/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1624 - mae: 1.9389

345/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0942 - mae: 1.9303

364/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0760 - mae: 1.9290

384/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0110 - mae: 1.9153

404/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0267 - mae: 1.9184

423/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0277 - mae: 1.9177

442/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0266 - mae: 1.9135

461/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0357 - mae: 1.9109

481/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9848 - mae: 1.9038

502/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9462 - mae: 1.8978

522/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9548 - mae: 1.9011

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9486 - mae: 1.8998 - val_loss: 5.3306 - val_mae: 1.8391

Epoch 38/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - loss: 13.2458 - mae: 3.0424

 20/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5.8390 - mae: 1.8573

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4149 - mae: 2.0098

 59/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7637 - mae: 2.0555

 79/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7309 - mae: 2.0669

 98/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6372 - mae: 2.0644

118/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6126 - mae: 2.0384

138/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5681 - mae: 2.0232

158/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4511 - mae: 2.0113

177/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3547 - mae: 1.9908

196/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4032 - mae: 1.9859

216/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3679 - mae: 1.9827

235/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2266 - mae: 1.9585

254/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2666 - mae: 1.9663

268/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1594 - mae: 1.9459

283/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1318 - mae: 1.9427

301/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0604 - mae: 1.9318

320/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1747 - mae: 1.9462

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1222 - mae: 1.9369

356/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0449 - mae: 1.9255

374/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0933 - mae: 1.9336

392/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0455 - mae: 1.9242

412/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9995 - mae: 1.9191

431/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9961 - mae: 1.9148

450/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0777 - mae: 1.9197

468/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0229 - mae: 1.9109

486/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9819 - mae: 1.9056

505/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9441 - mae: 1.9007

524/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9548 - mae: 1.9032

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9548 - mae: 1.9032 - val_loss: 5.3844 - val_mae: 1.8456

Epoch 39/500

  1/524 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - loss: 13.5391 - mae: 3.0841

 19/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.0223 - mae: 1.8768

 39/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.4553 - mae: 2.0178

 58/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.8634 - mae: 2.0687

 76/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6751 - mae: 2.0482

 94/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.7174 - mae: 2.0695

114/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6384 - mae: 2.0387

133/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.6364 - mae: 2.0368

152/524 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6.5372 - mae: 2.0204

171/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4269 - mae: 1.9984

191/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4210 - mae: 1.9906

210/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4029 - mae: 1.9842

229/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.2509 - mae: 1.9608

248/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.3224 - mae: 1.9741

267/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1570 - mae: 1.9441

286/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1223 - mae: 1.9391

305/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0757 - mae: 1.9320

323/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1728 - mae: 1.9438

338/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1115 - mae: 1.9330

355/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0390 - mae: 1.9209

372/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0887 - mae: 1.9308

391/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0433 - mae: 1.9220

410/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0093 - mae: 1.9191

428/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9904 - mae: 1.9121

446/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0661 - mae: 1.9164

463/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0220 - mae: 1.9089

482/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9724 - mae: 1.9025

501/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9474 - mae: 1.8988

520/524 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9436 - mae: 1.8987

524/524 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 5.9483 - mae: 1.9007 - val_loss: 5.2809 - val_mae: 1.8289

Epoch 39: early stopping

Restoring model weights from the end of the best epoch: 29.

In [20]:
# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = model.predict(X_test)# the pred

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))

actual = y_test # the actual
plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.suptitle('Test Results')
plt.xlabel('Time')
plt.ylabel('Temperature')
plt.show()

 1/12 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

MAE:  1.760439450662215

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\3666477720.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\3666477720.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Save the model and use it again

Reproducibility means more than a seed: **save the fitted model** so you (or a teammate, or your future self) can reload it and predict without retraining. Keras 3 saves to a single `.keras` file. The reloaded model must give *identical* predictions - we check.

In [21]:
from keras.models import load_model

model.save('Univariate_Temperature_RNN.keras')                 # one file: architecture + weights + optimizer state
reloaded = load_model('Univariate_Temperature_RNN.keras')

# same inputs, same answers?
import numpy as np
same = np.allclose(model.predict(X_test[:5], verbose=0), reloaded.predict(X_test[:5], verbose=0))
print('reloaded model reproduces the predictions:', same)
reloaded.summary()

reloaded model reproduces the predictions: True

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         3,840 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,615 (45.38 KB)

 Trainable params: 3,871 (15.12 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 7,744 (30.25 KB)

# Baseline Model
What if you just use yesterday's value as the prediction?!

In [22]:
# baseline model - prediction is just the previous time step (a tough one to beat!)
df['Baseline'] = df['Temp'].shift(1)
df.head()

         Date  Temp  Baseline
0  1981-01-01  20.7       NaN
1  1981-01-02  17.9      20.7
2  1981-01-03  18.8      17.9
3  1981-01-04  14.6      18.8
4  1981-01-05  15.8      14.6

In [23]:
# if you wanted to see how this model does, use df['Baseline'] for the pred
# here's how I'd do it
y_test_baseline = df['Baseline'].tail(y_test.shape[0])
# check your work
y_test_baseline.shape

(364,)

In [24]:
# check shapes, looks good!
y_test.shape

(364,)

In [25]:
# now set this equal to pred and repeat code!



# show scatterplots of actual vs. predicted for train and test
# make a prediction
pred = y_test_baseline # the pred
actual = y_test # the actual

# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
print('MAE: ', mean_absolute_error(y_test, pred))


plt.scatter(x=actual, y=pred)
x = np.linspace(0,25) # 45 degree line from 0 to 25 (axes are the same)
plt.plot(x, x, color='red')
plt.suptitle('Test Results')
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.show()
# looks pretty good!

MAE:  2.0247252747252746

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\2020546298.py:21: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [26]:
# show timeseries plot on the train and validation data
plt.plot(np.arange(X_test.shape[0]), y_test, color='blue') # actual data
plt.plot(np.arange(X_test.shape[0]), pred, color='red') # predicted data
plt.show()
# looks good, BUT it's not a smart model! all the data is just shifted.

C:\Users\dww05002\AppData\Local\Temp\ipykernel_21888\3144420803.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [27]:
# calculate MSE for the baseline model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

2.0247252747252746

In [28]:
# our RNN models beats the baseline model!
# don't be FOOLED by the line plot... or model is 20% better than a dumb model!